### PR TITLE
stm32/rtc: Allow overriding startup timeouts from mpconfigboard.

### PR DESCRIPTION
**Pull request by andrewleech**
This PR Simply exposes the startup timeouts via `#ifdef` to allow overriding for particular boards.

On our custom stm32f765 based board, the external crystal for RTC was not being used with the default 1000ms timeout (unit was falling back to LSI, took a while to figure out why our clock was drifting).

After increasing the timeout to 2000 the crystal works, with a reported startup time between 1200 and 1600ms over a few hard cold boots (RTC backup battery off/on).

### CODE REVIEW

**Comment by dpgeorge** [comment]
I think the names should be `MICROPY_HW_RTC_LSE_TIMEOUT` etc (note addition of RTC), to match existing RTC config values, and make it explicit these timeouts relate to the RTC module.

**Comment by andrewleech** [comment]
Ah yes, good call.

**Comment by dpgeorge** [comment]
And maybe it's even better to add an `_MS` suffix to make it explicit the units of the timeout.  Then no need for `_VALUE`, ie `MICROPY_HW_RTC_LSE_TIMEOUT_MS`.

What do you think?  (I can make the change during merge if you like.)

**Comment by andrewleech** [comment]
Thanks for the suggestion, I've just made the `_MS` change myself, makes it easier to keep my board config that uses it in sync!

**Comment by dpgeorge** [comment]
Thanks, merged in 29865e3e58a89eace83fc1910221724363f55d64

**Pull request closed without merging**
