### PR TITLE
stmhal DAC deinit() method added

### PR DESCRIPTION
**Pull request by peterhinch**
Once a DAC is initialised its pin remains bound to the DAC and can't be reconfigured for other uses. This method enables its re-use.

### CODE REVIEW

**Comment by robert-hh** [comment]
Looks like the travis-ci check fails for the same reason like mine: a failure in the test system.

**Comment by pfalcon** [comment]
@peterhinch : Please rebase to get past travis error.

**Comment by pfalcon** [comment]
@peterhinch: Thanks. FYI, rebase is "git pull --rebase" (in case of master branch). Using merges complicates integrating patches. Also, please follow commit messages conventions: https://github.com/micropython/micropython/blob/master/CODECONVENTIONS.md . With commit message fix, committed as 641300dccb0a68e4ede07323aabeed564a892a8f.

**Comment by peterhinch** [comment]
Thanks for the pointers, duly noted. Git still confuses the hell out of me.

**Pull request closed without merging**
