### PR TITLE
py/objarray: memoryview requires MP_TYPE_FLAG_EQ_CHECKS_OTHER_TYPE.

### LINKED ISSUE #5674: Memoryview comparison not working correctly anymore
In an older release this worked:

```
>>> memoryview(b"hi")==b"hi"
True
```

Now it doesn't:

```
>>> memoryview(b"hi")==b"hi"
False
```

This causes all kinds of problems in my code, obviously.
My guess is that this is caused by the commit about equality comparison (can't find it right now but read it today before pulling the latest changes)

### PR DESCRIPTION
**Pull request by jimmo**
Fixes #5674 (comparison of memoryview against bytes).

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks, looks good to me!  I wonder if `array.array` also needs this flag set?

**Comment by jimmo** [comment]
Yes, it seems so, but actually needs different behavior.

MicroPython v1.12:
```
>>> array.array('b', [0x61,0x62,0x63]) == b'abc'
True
```

MicroPython master:
```
>>> array.array('b', [0x61,0x62,0x63]) == b'abc'
False
```

CPython (3.8.1)
```
>>> array.array('b', [0x61,0x62,0x63]) == b'abc'
False
```

I'll need to look up what CPython thinks the rules are.

**Comment by jimmo** [comment]
CPython checks that both sides are `array` (which means that `rich_compare` falls back to reference equality). So actually not setting the flag is the correct thing to do, and the recent equality stuff fixed a latent bug here!

I will add some similar tests to `tests/basics/array1.py`.

**Comment by jimmo** [comment]
> I will add some similar tests to `tests/basics/array1.py`.

Done

**Comment by dpgeorge** [comment]
Rebased and merged in 3ccce89b831bdccd1feaa41ea23bc5d3ea963b32 and 54db464a1bde6b09d17b95a283a2230689763720

**Pull request closed without merging**
