### PR TITLE
[STM32L475/B-L475E-IOT01A] Introduce new processor and boards support.

### PR DESCRIPTION
**Pull request by tobbad**
There is a cool IoT board by STM with a bunch of sensors and connectivity in Bluetooth, WiFi and SubGHz (http://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-eval-tools/stm32-mcu-eval-tools/stm32-mcu-discovery-kits/b-l475e-iot01a.html).
With this PR I introduce the basic support for this board and the STM32L475. 

"Basic" means that the used SPI/UART/I2C busses are declared but the other features of the BOARD (QUAD-SPI-Flash, BT, WiFi SubGHz) is later supported when the Wireless branch is merged into mp or related modules are pushed to the repo (Does a quadspi module already exist for STM32?). I will continue to write the MP drivers for the sensors on this board.

To run this repo on your IoT board be sure to merge as well PR #3295 into your local Repo copy.

### CODE REVIEW

**Comment by dpgeorge** [comment]
What is the difference between the L476 and L475?  It looks like they are similar enough that they can use the same stm32l47x_af.csv file, as well the same stm32l47xxg.ld linker script.

> Does a quadspi module already exist for STM32?

I am working on this, it might be available in a few weeks.

**Comment by dhylands** [comment]
It looks like the primary difference is that the STM32L4x6 has an LCD peripheral, where the STM32L4x5 doesn't.

**Comment by tobbad** [comment]
As dhylands mentioned 4x5 seems to be a cost optimized version of 476:
475 has:
    1. No LCD controller 
    2. No GPIO Port F and G
    3. Less ADC channels @ same count of ADC.
    4. Reduced count of touch sensing IO 
The drawing in the product specification of the 475 is not quite accurate - as it shows no USB OTG and no 3rd ADC.

**Comment by tobbad** [comment]
... thanks for the hint - I removed Port F and G from pins.csv.

**Comment by dpgeorge** [comment]
I'd prefer not to add a new xxx_af.csv file if possible.  The cost-reduced MCU should be able to use the same csv file as the high-end MCU.  If pins are never specified in pins.csv then their data won't be included from the af.csv file.

In summary: please remove the .csv and .ld files.

**Comment by tobbad** [comment]
Rechecked the difference between the alternate pins csv (475/476) resulted that the AF11 column in 475 is empty (no support for LCD). So I removed the 475 specific linker script and alternate Pins.

**Comment by dpgeorge** [comment]
Thanks @tobbad for checking the difference with the L475 vs L476.  I merged this PR with the change that the board directory uses underscores, ie `B_L475E_IOT01A`, to follow the existing names there.

**Comment by tobbad** [comment]
Thank you.

**Pull request closed without merging**
