### PR TITLE
extmod/modframebuf: rename all three kinds of color variable names

### PR DESCRIPTION
**Pull request by kamikaze**
Let's make variable naming more consistent. I've started with "col", "color" and "colour".

P.S. I've heard rumours about "colour" to be a decided choice. Isn't it a more common language in programming (an IT itself) an en-US instead of en-GB? I've seen en-US "color" almost everywhere.

### CODE REVIEW

**Comment by mcauser** [comment]
+1 for en-US "color"

I'm fine with a little US spelling as long as Fahrenheit doesn't become standard over Celsius :)

**Comment by dpgeorge** [comment]
Thanks, but such changes are not needed.  These are all internal identifiers, none of them are part of the Python API, so they don't need to be made consistent.

If you want to change the single occurrence of "colour" to "col" then I'd be ok with that.  At least then there is either "color" or "col" which are consistent (the latter being an abbreviation of the former).

Moving forward, new code should use "col" or even just "c" so as to be short and not bias US or GB spelling.

**Comment by kamikaze** [comment]
so does it mean that if it is not a part of a Python API there should be a mess and chaos in other places? Is this repo/project about Python API only?

Also what about readability? When you see "col" - does it mean "color" or "column"? Not even saying about "c" that could mean everything. What for C code should be so much cryptic?

This change is just a first PR before my next PR in modframebuf that adds GRAY4 mode. Just wanted to have some consistency and readability first.

**Comment by dpgeorge** [comment]
> so does it mean that if it is not a part of a Python API there should be a mess and chaos in other places?

IMO this is a very small inconsistency and not worth worrying about.  I'd rather keep the git history about who wrote the code intact, than make these changes.

> Is this repo/project about Python API only?

Mostly yes!  Lots of effort is made so the user has a "proper Python" experience, and so the code runs with little resources, and this is at the expense of code clarity in many places.

> Not even saying about "c" that could mean everything.

In a module that's about drawing graphics, variables "x", "y", "w", "h" and "c" should be self explanatory.

**Comment by kamikaze** [comment]
OK, if you think that "c" is a better choice also for refactoring actions (try to find all "c" that are color and not something else even in this single file, aha). So I've made it to be "c".

**Comment by dpgeorge** [comment]
> So I've made it to be "c".

No, please, there's no need make it all consistent like this (as I said above, git history is more important).  If you want to do something useful then just change the single occurrence of "colour" to "col", that would be consistent enough.

Then moving forward with your own additions, use "col" consistently.

**Comment by pfalcon** [comment]
This now conflicts with the latest tree. Should this be closed?

**Comment by dpgeorge** [comment]
In f3687109d56793b73288e081a5f4ad6884ded28d I made the framebuf module consistently use "col".  Thanks @kamikaze for the idea and initial patch.

**Pull request closed without merging**
