### PR TITLE
esp32: Add support for named pins.

### PR DESCRIPTION
**Pull request by dpgeorge**
This adds named-pins support to the esp32 port, following other ports.

It adds:
- ~~`machine.Pin.cpu.GPIOn` for all available CPU pins~~ Edit: this is now removed
- `machine.Pin.board.xxx` for any board-specific named pins, specified by a board's `pins.csv`
- ability to construct a pin by name, `machine.Pin("<name>")`, ~~eg the name can be `"GPIO1"` for a cpu pin~~

TODO:
- [x] reduce firmware size by combining pin and pin_irq objects

### CODE REVIEW

**Comment by robert-hh** [comment]
Thank you. Two questions:
- is a pins.csv file required for a board?
- does Pin.board exist if there is no pins.csv for a board? It could be the same as Pin.cpu.

**Comment by dpgeorge** [comment]
> * is a pins.csv file required for a board?

No.  If the board doesn't have one then nothing is populated in `machine.Pin.board`.  But `machine.Pin.cpu` will always contain all available CPU pins.



> * does Pin.board exist if there is no pins.csv for a board?

Yes but it's empty.

**Comment by iabdalkader** [comment]
btw, unrelated, but the workflows can run much faster if you cache arm gcc toolchain and enable pip cache.

**Comment by iabdalkader** [comment]
machine_pin.h seems to be missing this include ?
```diff
diff --git a/ports/esp32/machine_pin.h b/ports/esp32/machine_pin.h
index 1c6716571..4314bc0b3 100644
--- a/ports/esp32/machine_pin.h
+++ b/ports/esp32/machine_pin.h
@@ -27,6 +27,7 @@
 #define MICROPY_INCLUDED_ESP32_MACHINE_PIN_H
 
 #include "py/obj.h"
+#include "driver/gpio.h"
 
 #if CONFIG_IDF_TARGET_ESP32
```

**Comment by dpgeorge** [comment]
> the workflows can run much faster if you cache arm gcc toolchain and enable pip cache.

How do you do this?  And would it work for the esp32 CI, which doesn't use this toolchain?

> machine_pin.h seems to be missing this include

Thanks, that's now fixed.

**Comment by dpgeorge** [comment]
The code size increase for this PR is pretty large, it's +1031 bytes, and that's without any board-named pins (only `Pin.cpu` names).  Most of that code size increase is due to the additional qstrs for the GPIOx names.

IMO that's too much for an increase for a feature that no one really asked for (named CPU pins) and that probably no one will use.

The main reason for this PR is to add board-named pins, like `Pin.board.LED`.  So I've updated the code here to only provide `Pin.board` and not provide `Pin.cpu`.  The code size increase now is just +140 bytes.  (And adding two named board pins brings that up by +48 bytes, to give an idea of how much it costs to add a named pin.)

**Comment by iabdalkader** [comment]
> The code size increase for this PR is pretty large, it's +1031 

Don't all ESPs use external flashes ? There's usually a large amount of flash that's unused anyway. That said, for our purposes we're only interested in `Pin("pin name")`, does that still work ?

**Comment by robert-hh** [comment]
> That said, for our purposes we're only interested in Pin("pin name"), does that still work ?

That comes with the Pin.board dictionary.

**Comment by robert-hh** [comment]
> The code size increase for this PR is pretty large, it's +1031 bytes

I had the same experience with the SAMD port. So I made it configurable, but only for both dictionaries. I could split that to enable either one. The CPU names seem less often needed, and for the SAMD port they still can be addressed by a number.

**Comment by dpgeorge** [comment]
> Don't all ESPs use external flashes ? There's usually a large amount of flash that's unused anyway.

Some have internal flash.  The IDF takes up a lot of space and some of the esp32 board definitions in this repo are already at their limit.  See eg 2c67671651651363fc6f89a334508d0029758eef and the `GENERIC_D2WD` board.

I think it's important to try and keep size down even for "large" ports like esp32.

> The CPU names seem less often needed, and for the SAMD port they still can be addressed by a number.

Ports like stm32 need named CPU pins.  But other ports like esp8266, esp32, rp2, the pins can be just an integer.  In those cases `Pin.cpu` is not necessary (but may be useful for consistency with other ports, and also discoverability of available pins).

**Comment by dpgeorge** [comment]
I have now reduced the size of pin and pin-irq objects by removing the unnecessary `gpio_num_t` member from the structs.  The net change in firmware size for the GENERIC build is now -132 bytes for this PR.

**Comment by dpgeorge** [comment]
Rebase on top of merged #11731.

**Pull request merged**
