### PR TITLE
ports/stm32 Add support for STM32F413 and NUCLEO_F413ZH board

### PR DESCRIPTION
**Pull request by chrismas9**
Support STM32F413. It has 10 UARTs, 3 CAN ports and a different interrupt vector table.
Support NUCLEO_F413ZH board with all peripheral ports pinned out.
Add test scripts for hardware testing the peripheral ports using loop-back or external devices.

### CODE REVIEW

**Comment by dpgeorge** [comment]
It looks good, just a couple of points:
- in `stm32f413*.ld` the `_heap_end` is defined for 128k RAM device so can be increased a lot.  I'd suggest using `_heap_end = _ram_end - 16K;`, which leaves room for a 16k stack.
- I don't think it's necessary to use 2 regions to define the flashbdev, because the regions are contiguous.  So the configuration could be something like this:
```
in stm32f413*.ld:
FLASH_FS (rx)   : ORIGIN = 0x08004000, LENGTH = 176K /* sectors 1,2,3 are 16K, 4 is 64K, 5 is 128K (64K used) for filesystem

in flashbdev.c:
#define FLASH_MEM_SEG1_START_ADDR (0x08004000) // sector 1
#define FLASH_MEM_SEG1_NUM_BLOCKS (352) // sectors 1,2,3,4,5: 16k+16k+16k+64k+64K(of 128K)=176k
```

(If they make sense, you can make these changes as a separate commit and I'll squash when merging.)

**Comment by chrismas9** [comment]
What I had intended to do, but obviously didn't, was to include sector 5 (128k, 64k used) in FLASH_FS and sector 6 in FLASH_FS2. That would give a 240k file system and 640k or 1152k FLASH_TEXT. 

If you are happy with that proposal I will test it and submit an update, along with the increased heap.

**Comment by dpgeorge** [comment]
Yes that sounds good.

**Comment by dpgeorge** [comment]
Ok, I've merged the generic F413 support in 1b956ec81701ad9ae36e8e0fd625eff32e3e2a3d, and the new NUCLEO F413 board in 2a791170cea7841b9a7600d371b8c0355a3cc20a

I held off on updating the stm32lib submodule because it looks like it'll need further updates very soon (#4741).  If not, this submodule will be updated before the next release.

I also didn't merge the hardware test scripts.  They are definitely valuable but too specific to the F413 and would get lost sitting in a subdir of this Nucleo board (I see they each have a config section but it still needs changing by hand).  Ultimately they'd be made more generic (to other stm32 boards, and even other ports via the machine module) and also more automated, and then included alongside the other tests in the main test directory.  But thanks for submitting them anyway.

**Comment by dpgeorge** [comment]
The stm32lib submodule was updated in 1b3c1f9e6bf4669d2eb9c85c07bc83105aa97556 with the fixes for UART9/10.

**Pull request closed without merging**
