### PR TITLE
shared/runtime/softtimer.c: Use consistently the same clock source.

### PR DESCRIPTION
**Pull request by robert-hh**
Before, both uwTick and mp_hal_ticks_ms() were used as clock source. That assumes, that these two are synchronous and start with the same value, which may be not the case for all ports. If the lag between uwTick and mp_hal_ticks_ms() is larger than the timer interval, the timer would either rush up until the times as synchronous, or not start until uwTick wraps over.

Using consistently uwTick removes the potential discrepancy.

### CODE REVIEW

**Comment by dpgeorge** [comment]
I think it would be cleaner to use `mp_hal_ticks_ms()` here, instead of `uwTick`.

Then if a port wants efficiency, it could define an inline version of `mp_hal_ticks_ms()` which just returns `uwTick` (or whatever it calls the variable).

**Comment by robert-hh** [comment]
While it seems important that the same time source is used at all places, using mp_hal_ticks_ms() fails.  As I test, I forced uwTicks and mp_hal_ticks_ms() to be different by setting uwTick to a different start value than 0. When I use the proposed change, the timer works with different start values of uwTick (tested: 60000, 0x7fff15a0, 0xffff15a0). When I change all occurrences of uwTick to mp_hal_ticks_ms(), the timed tasks do not start.

**Comment by robert-hh** [comment]
One reason could be, that I tested that failing state with the SAMD port, where mp_hal_ticks_ms() is not affected by disable_irq(). It is based on a counter, which keeps running as long as the clock is present. That may be the same for other ports.

**Comment by robert-hh** [comment]
The reason is in `SysTick_Handler()` of various ports, where soft_timer_next is compared to `uwTick`. Changing `uwTick` in softtimer.c to `mp_mal_ticks_ms()` would make `soft_timer_next` be based on the `mp_hal_ticks_ms()` timer, and then the comparison fails. And calling `mp_hal_ticks_ms()` in  `SysTick_Handler()` seems to **heavy** and maybe unsafe.

**Comment by dpgeorge** [comment]
> The reason is in `SysTick_Handler()` of various ports, where soft_timer_next is compared to `uwTick`.

Yes I see now.  You are right.

I still think it's bad to have to access `uwTick` directly in the `softtimer.c` code.  Instead I would propose to create a new config macro that accesses the ticks value.  Eg in `mpconfigport.h`:
```c
#define MICROPY_SOFT_TIMER_TICKS_MS uwTick
```
or in `mphalport.h`:
```c
static inline uint32_t mp_hal_soft_timer_ticks_ms(void) {
    return uwTick;
}
```

**Comment by robert-hh** [comment]
> Instead I would propose to create a new config macro that accesses the ticks value. 

I agree that this makes the code better readable and shows the intention of that variable. The only drawback is, that it requires changing all ports, unless it is defined in mphal.h or mpconfig.h. uwTick is at the moment only used by the stm32 and renesas-ra port. The mimxrt and samd port just define uwTick as systick_ms. I could change that in using the name uwTick for the SysTick counter as well.

**Comment by dpgeorge** [comment]
Thanks for updating, looks good.

**Comment by robert-hh** [comment]
Thank you.

**Pull request merged**
