### PR TITLE
esp8266/esp8266.ld, esp8266_ota.ld: Grow main firmware size by 32KB.

### PR DESCRIPTION
**Pull request by pfalcon**
To accommodate both system and user frozen modules.

### CODE REVIEW

**Comment by dpgeorge** [comment]
What about esp.flash_user_start()?  And maybe we can take this change to reserver 1 sector (4096 bytes) for native code, like we wanted to do before?  Ie set RESERVED_SECS=1 in flashbdev.py

**Comment by pfalcon** [comment]
> What about esp.flash_user_start()? 

What, it doesn't follow .ld automatically? Awful!

> Ie set RESERVED_SECS=1 in flashbdev.py

Sure. Then scale back firmware increase to 28K or leave at 32K?


Will make these updates and push. What about scripts/ vs modules/ cleanup in esp-extra-scripts - do you wane me to do it, or you have it done and just need to push?

**Comment by pfalcon** [comment]
> What, it doesn't follow .ld automatically? Awful!

This is now fixed, see new commit in this PR.

**Comment by pfalcon** [comment]
Ok, all features discussed implemented, ready to merge.

**Comment by dpgeorge** [comment]
Ok this looks good.

> What about scripts/ vs modules/ cleanup in esp-extra-scripts - do you wane me to do it, or you have it done and just need to push?

I didn't touch it so feel free to do it.

**Comment by pfalcon** [comment]
Merged.

> I didn't touch it so feel free to do it.

Will do.

**Comment by pfalcon** [comment]
> Will do.

Done. Everything was moved from esp8266/scripts/ to modules/ , both in master and in esp-extra-scripts (don't forget to `git pull --rebase upstream esp-extra-scripts`). Now let's test if all that works ;-).

**Comment by pfalcon** [comment]
With current setup, it leaves ~21K for user bytecode.

**Pull request merged**
