### PR TITLE
samd: Extend the SAMD port.

### PR DESCRIPTION
**Pull request by robert-hh**
There was a configuration error, selecting the wrong port group, which was fixed in the first commit.
The fix applies to ADAFRUIT_ITSYBITSY_M4_EXPRESS, SAMD21_XPLAINED_PRO
and ADAFRUIT_TRINKET_M0. The wrong port group was set in mpconfigboard.h.
Compiled & built, tested with ADAFRUIT_ITSYBITSY_M4_EXPRESS only.

Since later in these commits machine.UART is introduced with a more general approach, these first fixes
get obsolete down the line. Therefore I hid them and removed that code later down the commit series.

Extensions:
- Add OPEN_DRAIN mode to the Pin class.
- for SAMD51: Set the default clock to 120Mhz and allow changing of the clock in the range 48 - 200 MHz.
- Extend mphalport.[ch] with common functions.
- Enable SoftI2C and SoftSPI. Using SoftSPI, the RGB led can be controlled and the external
  flash chip on some boards can be used e.g. for a file system, using the driver of @peterhinch.
- Enable machine.disable_irq(), .enable_irq(), .idle()
- Implement ticks_us() and sleep_us() properly, and ticks_cpu() with limited range.
- Implement a provisional time.time() using the systick time extended to 64 bit.
- Implement mp_hal_time_ns(). 
- Allow for a board-specific manifest.py.
- Add board files for ADAFRUIT_ITSYBITSY_M0_EXPRESS.
- Add examples of board.py files defining symbolic names for pins.
- Implement machine.UART. This covers the usual functions and methods, with a few exceptions:
  + Invert mode was enabled and then disabled again, since it is a data invert ans not a line invert.
  + According to the data sheet, sendbreak works only in fractional mode with external clock. A break
     state can as well be created by sending 0x00 at a lower baudrate.
  + Buffered transfer is used only for receive. That saves flash and RAM space. It could be added for
     SAMD51 boards, since these have larger RAM.
- Implement machine.ADC
- implement uos.urandom for SAMD51. SAMD21 chips do not have a TRNG.
- Add a few more MicroPython features. The actual approach, adding SAMD51 only features into the mpconfigboard.h files may have to be re-considered. Better use #ifdef sections in the mpconfigport.h file, or MCU-Specific include files.
- Enable uos.dupterm()
- Add the machine.Timer class
- Add pin.irq() to the machine.Pin class.
- Implement machine.PWM
- implement machine.WDT
- Add machine.SPI and machine.I2C

### CODE REVIEW

**Comment by robert-hh** [comment]
@dpgeorge. The PR is rebased, and since it was dangling around, I enabled the Pin.OPEN_DRAIN mode. The brought me to an issues about pin names. At the moment, it's simply an integer, which is fine for pins labeled with numbers on the board. But some boards have labels like Ax, or SDL, SDA, MISO, ... These are not intuitively matched to Pin numbers, if at all. So I see three options:
- just use pin numbers and documents, which signal is which pin.
- Allow to use a string as specifier, like "A0", "SDA", "D9". That would use some FLASH space for the names.
- use a Python script like board.py, which assigns the proper number to symbols, like board.SDA. This python script would live in the respective boards directory and be included by _boot.py. That would use RAM and some flash.

Do you have any preference?

P.S.: With OPEN_DRAIN and a changed sleep_us() implementation I could get SoftI2C working, at a speed of 60kHz. The clock and timing sections needs some rework.

**Comment by robert-hh** [comment]
Note: The force pushes are usually done for pleasing uncrustify. Most of the time is complains about whitespace at the end of a line or missing newlines at EOF. There seems to be a difference between the uncrustify.cfg file in tools and the one used at the web site, because even if I run uncrustify locally, there happen to be "Failes" when uploading.

**Comment by dpgeorge** [comment]
Thanks for the work on this, there are a lot of good additions and improvements which are very welcome.

Unfortunately it's a very big PR with lots of interconnected changes, and some later commits fixing earlier ones.  That makes it hard to review.

In general it's much easier to review and merge if a PR contains only one of:
- bug fixes
- adding features that already exist on other ports and whose API matches the docs and/or other ports
- adding new things that require discussion

Some example issues with this PR:
- the first commit changes stm32lib and the second commit changes it back
- the first commit intends to add OPEN_DRAIN support, but also makes UART changes and adds mp_hal_time_ns
- the commit that enables soft I2C/SPI also adds pins to a board and enables MICROPY_COMP_CONST
- the commit that adds machine.ADC also adds unrelated commented-out code to a board file
- the commit that adds uos.urandom also adds dupterm functions

There are some really good improvements and enhancements here, but at the moment it's too difficult to review this PR.

I would suggest to break this PR up into manageable chunks.  Starting with one to add OPEN_DRAIN support and enabling soft I2C/SPI would be a great start.  Then adding PWM support, then ADC support, etc.

Regarding `board.py` and pin names: this requires a separate discussion, but my feeling is that we should first remove the duplicate `pins.h` files (they are the same for every board, except the number of pins configured).  And then auto-generate the `pins.c` files based on a `pins.csv`, like how other ports do it.  Then it would be easy to extend that to have an optional pin name in the `pins.csv` file.

**Comment by robert-hh** [comment]
Thank you for your comments. I'll see what I can do to break things in pieces again. I started that work as a simple bug fix, and then one thing came to the other.

About pins.c and pins.h. That was something that existed before. I do not see a benefit in using a pins.csv file. pins.c and pins.csv would contain the same information, just in a different style. A pin name could be added as well to pins.c.

**Comment by dpgeorge** [comment]
> I do not see a benefit in using a pins.csv file. pins.c and pins.csv would contain the same information, just in a different style. A pin name could be added as well to pins.c.

Yes they would contain the same info.  But pins.c contains a lot of boiler plate code.  pins.csv would be much simpler and align with other ports.

**Comment by robert-hh** [comment]
So I'll leave this PR as it is will wil start a new PR for the changed approach. Looking through the series of additions and changes, there are a few topics which have been changes several times. These are the clock configuration, mphalport.* and the Python features in mpconfigport.h. I suggest to use actual state of these files from the beginning. So my work would start creating a new baseline, starting from the current Master branch:

- remove the nonfunctional code for REPL on UART.
- Introduce pins.csv instead of pins.c/-.h. There is also led.c and machine.LED. I would like to remove these, because the functionality if fully covered by machine.PIN. In a later commit, I have reduced the size of machine.LED already, saving code space.
- Change the clock set-up in samd_soc.c/-.h
- Change mpconfigport.c/-.h

And then go on with open_drain, SoftSPI, SoftI2C, ..... At the time of introducing machine.UART, samd_isr has to be updated and the pin_cap module has to be added.

**Comment by robert-hh** [comment]
I added one more module and some fixes and changes. That just shows the state of the package. The new build-up should happen in #8704.

**Comment by robert-hh** [comment]
@dpgeorge Hello Damien. I'm closing this PR in favor of PR #8704, which has the same functionality, but is ~2 kByte smaller and lost a few bugs.

**Pull request closed without merging**
