### PR TITLE
esp32/partition improve OTA functionality

### PR DESCRIPTION
**Pull request by ekondayan**
* add class method  mark_app_invalid_rollback_and_reboot() in Partition class

The reciprocal method "mark_app_valid_cancel_rollback()" is already implemented.

### CODE REVIEW

**Comment by tve** [comment]
Is there a use-case for this? I left it out of the original PR 'cause it just seems like a waste. You can just reboot and that has the same effect as far as I know.

**Comment by ekondayan** [comment]
If you flash the new firmware successfully, all the self tests pass successfully and you mark the new application valid with esp_ota_mark_app_valid_cancel_rollback().
Later on you find a severe regression bug that prevents you from further updating the app over the air. Your devices will be stuck with the buggy version forever, unless you have an option to rollback to the previous working version.
You can ask your customers to restore the previous version and then to proceed to the upgrade procedure again. Adding esp_ota_mark_app_invalid_rollback_and_reboot() gives you a quick and easy way of doing this.

**Comment by tve** [comment]
Hmm, interesting, sounds a bit far-fetched to me...
So mark_app_valid_cancel_rollback has documentation and a test, mark_app_invalid_rollback_and_reboot doesn't.

**Comment by ekondayan** [comment]
I wanted to make sure that this PR is going mainstream before I put more effort into it. Give me a green light and I will update the docs and create a test.

**Comment by ekondayan** [comment]
I forgot to mention that the test passes with success on my nodemcu(ESP-32S v1.1 from ai thinker)

`>>> import partition_ota
Copying current to next partition
Partition copy: (0, 16, 65536, 1572864, 'ota_0', False) --> (0, 17, 1638400, 1572864, 'ota_1', False)
   ... 0x000000
   ... 0x010000
   ... 0x020000
   ... 0x030000
   ... 0x040000
   ... 0x050000
   ... 0x060000
   ... 0x070000
   ... 0x080000
   ... 0x090000
   ... 0x0a0000
   ... 0x0b0000
   ... 0x0c0000
   ... 0x0d0000
   ... 0x0e0000
   ... 0x0f0000
   ... 0x100000
   ... 0x110000
   ... 0x120000
   ... 0x130000
   ... 0x140000
   ... 0x150000
   ... 0x160000
   ... 0x170000
Partition copied, booting into it
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:5768
load:0x40078000,len:12800
ho 0 tail 12 room 4
load:0x40080400,len:4292
entry 0x400806b0
Running partition: ota_1 STEP=0 EXPECT=ota_1
Not confirming boot ok and resetting back into first
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:5768
load:0x40078000,len:12800
ho 0 tail 12 room 4
load:0x40080400,len:4292
entry 0x400806b0
Running partition: ota_0 STEP=1 EXPECT=ota_0
Booting into second partition again
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:5768
load:0x40078000,len:12800
ho 0 tail 12 room 4
load:0x40080400,len:4292
entry 0x400806b0
Running partition: ota_1 STEP=2 EXPECT=ota_1
Confirming boot ok and rebooting into same partition
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:5768
load:0x40078000,len:12800
ho 0 tail 12 room 4
load:0x40080400,len:4292
entry 0x400806b0
Running partition: ota_1 STEP=3 EXPECT=ota_1
Booting into original partition
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:5768
load:0x40078000,len:12800
ho 0 tail 12 room 4
load:0x40080400,len:4292
entry 0x400806b0
Running partition: ota_0 STEP=4 EXPECT=ota_0
Mark app invalid and revert to the previous valid app!
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:5768
load:0x40078000,len:12800
ho 0 tail 12 room 4
load:0x40080400,len:4292
entry 0x400806b0
Running partition: ota_1 STEP=5 EXPECT=ota_1
Confirming boot ok and DONE!

SUCCESS!`

**Comment by ekondayan** [comment]
I am closing this PR in favor of a new one

**Pull request closed without merging**
