### PR TITLE
py/persistentcode: Only store a single instance of source_file in mpy.

### PR DESCRIPTION
**Pull request by dpgeorge**
This is a relatively simple change to only store a single instance of the source file name in a .mpy file.  It assumes that all code blocks (classes, functions, lambdas, etc) in a single .mpy file come from the same .py source file, which I think is a fair assumption (and is the case for the output of mpy-cross).

No extra RAM is needed to save or load the new .mpy files.  It should be faster loading because the source file is only loaded at the start of loading the .mpy.

On average it reduces .mpy file size by about 5%.

### CODE REVIEW

**Comment by dpgeorge** [comment]
For background see #3054

**Comment by pfalcon** [comment]
> It assumes that all code blocks (classes, functions, lambdas, etc) in a single .mpy file come from the same .py source file, which I think is a fair assumption (and is the case for the output of mpy-cross).

Well, one obvious optimization to would be to allow to merge several .mpy's into one. But to get real benefits from that, it would take to allow to share e.g. the same constant table among the different functions, i.e. change serialization format anyway.

But if planning to do that, how it should be done is apparently introducing a bitflag field before each code object with bits of "read new/use the same as previous" for filename/const table/etc.

**Comment by dpgeorge** [comment]
> one obvious optimization to would be to allow to merge several .mpy's into one

I'm not sure how that would work: a file has meaning to Python import (`import x` corresponds to `x.py`) so if multiple files are in one .mpy then it must all be imported as one unit, corresponding to a single filename.

**Comment by pfalcon** [comment]
> I'm not sure how that would work: a file has meaning to Python import (`import x` corresponds to `x.py`) so if multiple files are in one .mpy then it must all be imported as one unit, corresponding to a single filename.

Apparently, that would need to be addressed somehow by someone doing that optimization, e.g. init code added which creates entries in sys.modules manually, etc. Conceptually, it's the same thing which Android's .dex did to individual Java .class'es.

**Comment by dpgeorge** [comment]
Superseded by #4549

**Pull request closed without merging**
