### PR TITLE
py/compile: Disallow 'import *' outside module level

### LINKED ISSUE #5121: import * allowed at function level
Hello,
micropython allows import * in functions. Is this desired behavior?

micropython behavior: 

```pycon
>>> def test():
...   from os import *
... 
>>> 
>>> 
__class__       __name__        gc              uos
bdev            test
>>> 
>>> 
>>> test()
>>> 
>>> 
__class__       __name__        remove          VfsFat
chdir           dupterm         dupterm_notify  gc
getcwd          ilistdir        listdir         mkdir
mount           rename          rmdir           stat
statvfs         umount          uname           uos
urandom         bdev            test
>>> 
```

expected behavior (CPython):

```pycon
$ python3.4
Python 3.4.6 (default, Mar 26 2017, 13:41:08) 
[GCC 4.9.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> def test():
...   from os import *
... 
  File "<stdin>", line 1
SyntaxError: import * only allowed at module level
```

### PR DESCRIPTION
**Pull request by encukou**
Fixes: https://github.com/micropython/micropython/issues/5121

I haven't found a good place in the codebase for a test. I'd appreciate a hint.

### CODE REVIEW

**Comment by dpgeorge** [comment]
> I haven't found a good place in the codebase for a test.

Probably in a new file `tests/import/import_star.py`, tested via an exec like `exec('def foo(): from x import *')`

**Comment by dpgeorge** [comment]
> but CI complains of a [core code size increase](https://travis-ci.org/micropython/micropython/jobs/588910365#L550) by 64b. (The error message is 40b.)

Yes, and that's quite unavoidable in this situation.  It would be good though to shorten the error message to make the increase as small as possible.

Anyway, I'm still not sure this is a good/necessary change (as I mentioned it's not a pattern that should ever be used).

Perhaps a compromise is to wrap this code in a `#if MICROPY_CPYTHON_COMPAT`

**Comment by stinos** [comment]
> Perhaps a compromise is to wrap this code in a #if MICROPY_CPYTHON_COMPAT

Something like that, yes, this just doesn't seem important enough to waste bytes on.

**Comment by encukou** [comment]
Thanks for your patience! As you can probably tell, I'm new to MicroPython's design philosophy.

Does this apply just to new code, or should I minimize the existing code as well? Should I also:
* Wrap the check for `"'return' outside function"` in `#if MICROPY_CPYTHON_COMPAT`? (I believe returning from a module/class is less harmful/surprising than `import *` in a function.)
* Instead of `"'continue' outside loop"` and `"'break' outside loop"`, use a common message: `"break/continue outside loop"` or `"loop control outside loop"`?
* Coalesce the `return/yield/await` messages to `"return/yield/await outside function"`?
* Try to shorten all the messages above?
* Just replace all these messages with `"invalid statement in this context"`? Perhaps with the original in `MICROPY_CPYTHON_COMPAT` mode?

**Comment by dpgeorge** [comment]
> Does this apply just to new code, or should I minimize the existing code as well?

Please just concentrate on the new code for now, to make this commit/PR self contained.

> minimize the existing code

 You have some good ideas here to shorten the error messages.  In particular "break/continue outside loop" makes sense rather than having separate messages.  Feel free to open a issue/PR to discuss these things separately.

**Comment by dpgeorge** [comment]
Squashed and merged in 25a9bccdee2fe830046c1c1a0220ca7706597202

**Comment by dpgeorge** [comment]
> * Wrap the check for `"'return' outside function"` in `#if MICROPY_CPYTHON_COMPAT`? (I believe returning from a module/class is less harmful/surprising than `import *` in a function.)



> * Instead of `"'continue' outside loop"` and `"'break' outside loop"`, use a common message: `"break/continue outside loop"` or `"loop control outside loop"`?

@encukou feel free to follow up with PRs for these.

**Pull request closed without merging**
