### PR TITLE
esp8266: put pin interrupt handler in iRAM

### LINKED ISSUE #5714: ESP8266 Pin IRQ regression
This [device driver for IR remotes](https://github.com/peterhinch/micropython-async/blob/master/nec_ir/aremote.py) formerly worked on ESP8266. It now crashes with no changes to code. The problem is related to hard Pin IRQ's and the following code sample demonstrates it.
```python
from machine import Pin
from time import sleep
import gc

pin = Pin(13, Pin.IN)
count = 0
def cb_pin(_):
    global count
    count += 1

ei = pin.irq(handler = cb_pin, trigger = (Pin.IRQ_FALLING | Pin.IRQ_RISING), hard = True)
# ei = pin.irq(handler = cb_pin, trigger = Pin.IRQ_FALLING, hard = True)

while True:
    sleep(1)
    print(count)
    gc.collect()
```
To test the pin is fed with a burst of 14 pulses of Manchester encoded data repeating every 104ms. Pulses are 889μs or 1778μs wide, the burst lasting 24.9ms. A crash with reboot occurs usually within a few seconds.

A crash also occurs if the commented-out code is used, ensuring that the minimum time between triggers is a leisurely 1.8ms. The crash takes longer to trigger.

Testing was with firmware built from source acquired today.
[EDIT]
I simplified the test by feeding the pin with a 20Hz square wave. The crash occurs after counting about 200 edges.

### PR DESCRIPTION
**Pull request by dpgeorge**
Attempt to fix #5714

### CODE REVIEW

**Comment by dpgeorge** [comment]
@peterhinch if you could test this, that would be great.

**Comment by peterhinch** [comment]
OK, I now have a test running but it needs to run for a while as the fault was infrequent.

You managed to replicate my original report [here](https://github.com/micropython/micropython/issues/5714#issuecomment-593943915) so maybe that would be worth repeating?

**Comment by peterhinch** [comment]
This has now run for over two hours - I'm confident this has fixed it. Previously I doubt it ever ran for more than 15 minutes (without pinging).

This also confirms my belief that the I2C issues were a consequence of the ISR not running - this was breaking the protocol causing the Pyboard I2C slave to fail.

**Comment by peterhinch** [comment]
I have also run your test. I reduced the PWM frequency to 50Hz (10ms interrupt interval) as I thought 1ms rather ambitious for soft IRQ's. This has run for 30 minutes without error.

On occasion it reconnected to the LAN but the code continued to run:
```
165577
165677
state: 5 -> 2 (6c0)
rm 0
pm close 7
165777
reconnect
state: 2 -> 0 (0)
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 4
cnt 
165877

connected with misspiggy, channel 3
dhcp client start...
165979
ip:192.168.0.18,mask:255.255.255.0,gw:192.168.0.1
166079
166179
```
Code:
```python
from machine import Pin, PWM
from time import sleep
import gc

pin = Pin(13, Pin.IN)
count = 0
def cb_pin(_):
    global count
    count += 1

ei = pin.irq(handler = cb_pin, trigger = (Pin.IRQ_FALLING | Pin.IRQ_RISING))
PWM(machine.Pin(2), freq=50, duty=50)
while True:
    sleep(1)
    print(count)
    gc.collect()
```

**Comment by dpgeorge** [comment]
> You managed to replicate my original report [here](https://github.com/micropython/micropython/issues/5714#issuecomment-593943915) so maybe that would be worth repeating?

That was actually something subtly different: it didn't lead to a crash, rather it hung the Python code but the "OS" was still running.

> This has now run for over two hours - I'm confident this has fixed it.

Ok, that's really great news!  But let's wait a bit to merge this in case something else comes up.

**Comment by dpgeorge** [comment]
I cleaned this up a bit and removed support for `hard=True` in the `Pin.irq()` method (because it's no longer possible for this to work).  Setting that option will now raise a `ValueError`.

**Comment by dpgeorge** [comment]
Added a small note to the docs that the `hard` argument may not be supported on certain ports.

**Pull request merged**
