### PR TITLE
stm32: add support for F3 series.

### PR DESCRIPTION
**Pull request by Zaryob**
Signed-off-by: Suleyman Poyraz <zaryob.dev@gmail.com>

### CODE REVIEW

**Comment by Zaryob** [comment]
I'm going to check coding with my nucleo f303k8tx card today. probably it will work.

**Comment by Zaryob** [comment]
code cleaned. and previous problemmatic commit messages fixed for ci.

**Comment by Zaryob** [comment]
I have tested with changing gitmpdules file with my branch in https://github.com/micropython/stm32lib/pull/14 it works with f303k8 well

**Comment by dpgeorge** [comment]
Thanks for the contribution and the effort to get this working.

The STM32F3 series of MCUs is rather old (launched in 2012) and I don't think it's worth the effort to maintain support for it in MicroPython (same thing for F1 and F2).  ST have a lot of newer MCUs (eg G and H series), and I think it would be better to spend time supporting and maintaining those instead.

Also, it's uncertain as to what MCUs will even be available to purchase in the near future, due to the chip shortage.

So, I'll close this PR as "will not support".  Feel free to maintain this code yourself in your fork, and maybe if there's enough interest in adding we can add it here.

**Pull request closed without merging**
