### PR TITLE
Resolve symbols used by MICROPY_PY_TIME_TICKS for nrf9160 targets

### PR DESCRIPTION
**Pull request by glennrub**
Current master does not build due to lacking functions from nrfx_rtc.c. These two patches enables compilation of nrfx_rtc.c and fixes a bug in nrfx_config.h.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Looks good.  Should we also add pca10090 to the CI build?

**Comment by glennrub** [comment]
>Should we also add pca10090 to the CI build?

Great idea! Updated.

**Comment by dpgeorge** [comment]
Uh oh, looks like we need a more recent toolchain in CI to support Cortex-M33... see how the stm32 job does it, probably using it's settings for CI will work here.

**Comment by glennrub** [comment]
@dpgeorge , looks like it worked very well :) Ok to merge this?

**Comment by dpgeorge** [comment]
> Ok to merge this?

Yes ok to merge.

**Comment by glennrub** [comment]
Rebased and included `actinius_icarus` target board to also enable MICROPY_PY_MACHINE_RTCOUNTER.

**Comment by glennrub** [comment]
Merged in b776fe69692e92497c7aae0f38dfcbe14b2ca024 through d9e8edc8bcff7102d655b63c672ccb44adeca688.

**Pull request merged**
