### PR TITLE
RFC/WIP py/objtype: user classes: Allow to lookup __new__() method.

### PR DESCRIPTION
**Pull request by pfalcon**
__new__() method is present by definition in each class, because each class
inherits from "object". But due to effects of multiple inheritance and
subclassing native types, looking it up is tricky: object.__new__ should
be the last choice, if a more specific version is found (in one of multiple
bases, or in native type), that should be used.

This patch implements this behavior by wrapping existing attribute lookup
function, and looking inside "object" only if the otiginal function doesn't
find anything. This relies on "object" not being present explicitly in the
base class chain (otherwise multiple inheritance case will be broken -
object.__new__ will be found while following the very first inheritance
branch, while other branches may have more specific __new__).

This also leads to additional stack usage on each lookup due to extra
function call.

### CODE REVIEW

**Comment by pfalcon** [comment]
This is a patch which was required to make following code from CPython's datetime module work:

~~~
    @classmethod
    def _create(cls, offset, name=None):
        self = tzinfo.__new__(cls)
        self._offset = offset
        self._name = name
        return self
~~~

Without it, `tzinfo.__new__` can't be looked up.

**Comment by pfalcon** [comment]
I'm obviously not happy with this patch, and yet it's required for the upstream code to run (and arguably, kinda serves more or less obscure, but a valid usercase in Python advance OO programming (maybe not)). It also reminds of https://github.com/micropython/micropython/issues/606

**Comment by pfalcon** [comment]
So, fixing that in a patching way is simple:

~~~
-        self = tzinfo.__new__(cls)
+        self = object.__new__(cls)
~~~

The point, such patching needs to be done...

**Comment by pfalcon** [comment]
One way to deal with it might be to pass an extra arg to (the original) mp_obj_class_lookup(), a recursion depth, then we can do extra iteration to lookup in "object" "at the very end" (by knowing when there will be very end). Adding such an arg won't lead to extra stack usage for register-passing ABIs (and will, for stack-passing).

**Comment by dpgeorge** [comment]
It would be nice to improve MicroPython's handling and support of `__new__`, but IMO this is not the right approach.  It uses more stack, and an extra call, in a pretty critical lookup function.

**Pull request closed without merging**
