### PR TITLE
extmod/machine_timer: Consolidate soft-timer implementation to extmod

### PR DESCRIPTION
**Pull request by dpgeorge**
This moves stm32's `machine_timer.c` code to `extmod/machine_timer.c`, and then updates mimxrt, samd and renesas-ra to use it.  Because all 4 of those ports had duplicated code for this soft-timer `machine.Timer` class.

The nrf port needed some updating so that it didn't pick up this common version (it has its own custom version).

Eventually we want to consolidate all ports to use this code, but for now this is a straightforward refactoring that has no change to functionality.

### CODE REVIEW

**Comment by dpgeorge** [comment]
@robert-hh this removes your copyright line from the mimxrt version (because that file is removed completely).  But I think that's fair enough because it's the stm32 version of the file that is moved to extmod, and then your mimxrt version is no longer needed (which is anyway equivalent to the stm32 version).

**Comment by robert-hh** [comment]
No problem.

**Comment by robert-hh** [comment]
Looks fine. tested with stm32, rp2, samd, and mimxrt. Compiles with nrf. The nrf port is confusing, since the API for machine.Timer is different. For starting, it requires a call to timer.start(), instead of starting with the instantiation. And the period quantity is µs instead of ms.

**Comment by dpgeorge** [comment]
> The nrf port is confusing, since the API for machine.Timer is different

Yes, it's different/confusing.  But let's not tackle that issue here.

**Comment by jimmo** [comment]
Excellent!

**Pull request merged**
