### PR TITLE
ESP32:  add flush method to machine UART class

### PR DESCRIPTION
**Pull request by miketeachman**
Discard all data in the UART RX buffer.  Implemented with UART driver API call in ESP-IDF

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks.  Such a feature is useful but I think it should be named differently.  In CPython `file.flush()` is used to flush output buffers, and MicroPython already uses that for general streams, see `mp_stream_flush_obj`.

In pyserial there is `flush()` for output and `reset_input_buffer()` for input, but the latter is quite a long name.

**Comment by miketeachman** [comment]
how about `uart_rx?`

**Comment by nevercast** [comment]
Its not really flushing since the data isn't moving to somewhere else, flushing is usually an output only operation. I'd be happy with just `.reset()` or `.clear()` as a short name.

**Comment by miketeachman** [comment]
> `.clear()`

`clear` seems quite appropriate  e.g.  clearing data from the rx buffer/FIFO.

so how about, either:

machine.UART.clear()
or
machine.UART.clear_rx()   added '_rx' as the method only operates on the receive FIFO.

**Comment by dpgeorge** [comment]
I'd be happy with `uart.clear_rx()`, since "reset" might be used to reset all parameters/config of the device, and "clear" (with rx) is a bit ambiguous.

**Comment by dpgeorge** [comment]
It's worth thinking exactly what the semantics of this function would be, because it may be that new chars come in on the UART RX during the clear operation.

Maybe it should be called `uart.clear_rxbuf()` and be defined to clear the input buffer at the time of the call.  The buffer may fill up again while the call is returning / after the call.  (Also note that rxbuf matches the constructor keyword to set the rxbuf size.)

@miketeachman what use case needs this functionality?

**Comment by peterhinch** [comment]
I'd offer synchronising to a device which sends periodic asynchronous data packets (e.g. a GPS). On application start you may receive a partial packet. If invalid data is detected you flush the buffer and set up to receive the next packet.

**Comment by miketeachman** [comment]
@dpgeorge The use case is well-described by @peterhinch - syncing to a device that transmits data asynchronously.  For my immediate need, the device is a serial particulate sensor for air quality applications which has a 2-line UART interface.  I had been using the Loboris ESP32 port (which offers a uart flush method).  I've moved back the mainline of uPy and am looking to have this same functionality for the driver.

The name `uart.clear_rxbuf()` sounds good to me.

About semantics:   How exact do you think we need to specify the semantics?   I'm assuming we want the method to work across all ports.   Every port is likely to have subtle port-specific behaviour (dictated by the API, like ESP-IDF) so I imagine we want to have a broad-brush definition that can reasonably cover multiple ports.  And then, specify port-specific differences on an as-needed basis in the docs.

**Comment by dpgeorge** [comment]
> syncing to a device that transmits data asynchronously

But for this case `uart.clear_rxbuf()` won't be a cure 100% of the time, there could be some cases where more data comes in during the clearing of the buffer.  This means there will anyway need to be a synchronisation loop which retries if the incoming packet was malformed/corrupt/partial.

> How exact do you think we need to specify the semantics?

It could be something like: if no new chars are arriving then, after calling `clear_rxbuf()`, the uart will have no chars available to read.  But if new chars are arriving then the behaviour is undefined.  Undefined behaviour is not particularly useful though...

In fact, you can already get this behaviour using the current firmware (on esp32 and stm32 at least):
```python
uart.read(uart.any()) # read as many chars as available in the rx buffer
```
This small snippet should be equivalent to `clear_rxbuf()` (for the case of no new arriving chars) and I'd lean towards using that rather than adding a new method.

**Comment by peterhinch** [comment]
> there will anyway need to be a synchronisation loop which retries if the incoming packet was malformed/corrupt/partial.

Yes.

> This small snippet should be equivalent to clear_rxbuf() (for the case of no new arriving chars) and I'd lean towards using that rather than adding a new method.

Might there be a performance issue if the buffer holds a lot of data?

In the general case we need to consider the effect of hardware flow control. If the rxbuffer fills, and flow control holds off the TX, then clearing the buffer will cause the TX to send pending characters. In this case using
```python
uart.read(uart.any()) # read as many chars as available in the rx buffer
```
will ensure that all pending characters are discarded.

**Comment by miketeachman** [comment]
@dpgeorge 
> This small snippet should be equivalent to `clear_rxbuf()` (for the case of no new arriving chars) and I'd lean towards using that rather than adding a new method.

I tried a test on the ESP32 using this snippet as a means to clear the rx fifo.  A pms5003 particulate sensor sends 32 bytes of data to the uart every second.

**Results**:  using `uart.read(uart.any())` takes 2 to 3 calls to clear out the rx fifo.  I don't have a good understanding of the ESP32 uart so I can't explain this.  I expected one call would clear the rx buffer.

test results below. You'll see that two reads, one of 256 bytes, and a 2nd of 52 bytes are needed to clear the fifo.  It's not consistent.  It might be 256/32/64 (3 reads) or 256/90 (2 reads)...
```
>>>
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
256
b'BM\x00\x1c\x00\x04\x00\x07\x00\x07\x00\x04\x00\x07\x00\x07\x02\xca\x00\xe6\x00(\x00\x08\x00\x00\x00\x00\x97\x00\x03HBM\x00\x1c\x00\x04\x00\x07\x00\x07\x00\x04\x00\x07\x00\x07\x02\xca\x00\xe6\x00(\x00\x08\x00\x00\x00\x00\x97\x00\x03HBM\x00\x1c\x00\x04\x00\x07\x00\x07\x00\x04\x00\x07\x00\x07\x02\xca\x00\xe6\x00(\x00\x08\x00\x00\x00\x00\x97\x00\x03HBM\x00\x1c\x00\x04\x00\x07\x00\x07\x00\x04\x00\x07\x00\x07\x02\xdc\x00\xea\x00(\x00\x08\x00\x00\x00\x00\x97\x00\x03^BM\x00\x1c\x00\x04\x00\x07\x00\x07\x00\x04\x00\x07\x00\x07\x02\xdc\x00\xea\x00(\x00\x08\x00\x00\x00\x00\x97\x00\x03^BM\x00\x1c\x00\x04\x00\x07\x00\x07\x00\x04\x00\x07\x00\x07\x02\xdc\x00\xea\x00(\x00\x08\x00\x00\x00\x00\x97\x00\x03^BM\x00\x1c\x00\x03\x00\x06\x00\x06\x00\x03\x00\x06\x00\x06\x02\xd6\x00\xe8\x00"\x00\x08\x00\x00\x00\x00\x97\x00\x03JBM\x00\x1c\x00\x03\x00\x06\x00\x06\x00\x03\x00\x06\x00\x06\x02\xd6\x00\xe8\x00"\x00\x08\x00\x00\x00\x00\x97\x00\x03J'
52
b'BM\x00\x1c\x00\x03\x00\x06\x00\x06\x00\x03\x00\x06\x00\x06\x02\xd6\x00\xe8\x00"\x00\x08\x00\x00\x00\x00\x97\x00\x03J\x00\x05\x00\x05\x02|\x00\xce\x00\x14\x00\x00\x00\x00\x00\x00\x97\x00\x02\xbe'
0
b''
0
b''
0
b''
0
b''
0
b''
0
b''
>>>
```

using `uart.clear_rxbuf()` it's consistent.  I tried 20 or so runs and get the same results.
```
>>>
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== uart.clear_rxbuf()
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
=== uart.any()
=== uart.read(uart.any())
0
b''
0
b''
0
b''
0
b''
0
b''
0
b''
0
b''
0
b''
>>>
```

Perhaps this behaviour is part of the reason that Espressif recommends using the ESP-IDF API call `uart_flush()` to clear the fifo?

from the [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/uart.html#_CPPv410uart_flush11uart_port_t) it says:

> If the data in Rx FIFO is not required and should be discarded, call uart_flush()

I updated the commit in case you would still consider this PR, method name is now `uart.clear_rxbuf()`.  

Otherwise, likely best to close it to reduce the PR cruft on the mainline. I'm fine with implementing the PR on a fork.

**Comment by robert-hh** [comment]
Reading the reference manual I see that the FiFo is 128 byte by default. That's quite a number. If the firmware rx buffer size  was 256 in your test, that could explain it. The rx-buffer would have been filled between calls from the FiFo. In that situation, you flush call seems to be better. Otherwise, to calls of uart.read(uart.any()) would be required to be safe.

**Comment by kevinkk525** [comment]
I would also like to have the feature uart.flush_rx() for the same reasons as Mike.
A workaround seems like a bad option.

**Comment by tve** [comment]
I just implemented a driver for a particulate sensor with asyncio and have to admit that by the time I implemented the state machine and code to sync up I didn't miss any RX buffer flushing...
I think a plus for this PR is that it's actually small.
The minuses are that it lacks a docs update and adds yet another incompatibility (across ports).

And yes, reading the ESP-IDF uart driver gives me headaches! I can't help but wonder how many bugs are left in there....

**Comment by kevinkk525** [comment]
I hope this will get merged soon.

**Comment by kevinkk525** [comment]
Sorry for pinging this again after another month. Soon this pr will be open 6 month..

**Comment by jimmo** [comment]
> I just implemented a driver for a particulate sensor with asyncio and have to admit that by the time I implemented the state machine and code to sync up I didn't miss any RX buffer flushing...

I keep wondering about this point. The times where I've wanted a RX flush, I've always actually needed something more sophisticated at a higher level.

@kevinkk525 or @miketeachman can you explain a scenario where a flush actually puts the uart into a defined state? i.e. why is clear_rxbuf not an antipattern?

I can kind of see that if you had manual control over the flow control, you could disable the sender, flush the RX, then re-enable the sender in a known good state. Is that a realistic scenario? Perhaps an answer is that if you know the sender is periodic at a slow interval O(seconds), you can virtually guarantee that you can flush during a "quiet" period.

To ask another way based on @dpgeorge 's suggestion. This code:

```
# Flush the UART RX.
while uart.any(): uart.read(uart.any())
```

is clearly bad (infinite loop if the sender is continuously busy). But in that scenario, is clear_rxbuf() better? (From the perspective of putting you in a known good state).

> And yes, reading the ESP-IDF uart driver gives me headaches! I can't help but wonder how many bugs are left in there....

Yeah I had a quick look at trying to explain @miketeachman 's output above, but yeah it's...really complicated.

**Comment by peterhinch** [comment]
I assume the use case for this involves synchronising a receiving task to a transmitter, where the transmitter sends unsolicited messages.

If so, whatever means are employed to clear buffers and FIFO's there is a risk that a character arrives just after that process has completed successfully. This character may not be the first character of a new message: it could be the first of N trailing characters from the current message. At this moment in time, message level synchronisation has not been achieved.

To achieve message-level synchronisation one option is to read character by character, discarding until a delimiter is reached. Another is to parse whatever data has been received and discard any invalid message. In either case flushing has no obvious purpose other than a time saving at the start.

**Comment by kevinkk525** [comment]
Yes, in case of an active pms5003 unit there is a lot of data being transmitted all the time. So uart.flush() helps to quickly get a clean start. Of course it could happen within a data packet but that is ok. The only goal is to flush earlier data packets.
This use-case actually has been described already by Mike: https://github.com/micropython/micropython/pull/5156#issuecomment-536587368

The workaround of uart.read(uart.any()) is very unreliable and would require changes in code, which I would like to avoid. The code has been extensively tested with the functionality of uart.flush(), so if I need to use a workaround, I will need to re-test the new behaviour. 
However, once the new uasyncio gets merged, I will probably have to re-test and maybe even partly redesign the driver anyway, so I will see how I can use a workaround, given that this PR doesn't seem to get merged anytime soon.

**Comment by tve** [comment]
Food for thought: if you stop thinking about pms5003.init() vs pms5003.read() and instead focus on writing a pms5003.read() method that can handle any pre-existing situation, then is flush at all useful? I found it not to be. My read() method starts as follows (my init() doesn't touch the uart, and the constants I use could be tuned a bit):
```
    def read(self):
        cnt = self._uart.any()
        if (cnt > 250):
            print("PMSx003: uart overrun")
            self._uart.read(300)
            return None
        if cnt == 0: return None
        # read first header char
        ...
```
The point here is that (a) my app may get blocked unexpectedly and the uart buffer may get filled during that time (think of mqtt publish blocking for a bit waiting for an ack), and (b) the pms sensor may start to send data at a more rapid pace (check the "datasheet"!) and cause the buffer to build up.
When you write `the workaround of uart.read(uart.any()) is very unreliable` it sounds very alarmist. You need a loop for it to work (`while any() > 0`) or build a robust parser to begin with...
IMHO, the pros of this PR are that it's very little code and would stop this discussion, the cons are that it's another incompatibility across ports. That it leads to poor code, oh well...

**Comment by kevinkk525** [comment]
My read function itself can handle any situation.
However the problem is a bit more complex imho. In my code I used uart.flush() not only in the read method in case any() returned a too big number but also after issuing commands to the sensor so any old packages won't be processed.
I could use (while any() > 0): uart.read(uart.any()) but tbh that looks more like a bad workaround than "good code". (This will actually be what I'm going to use if this PR doesn't get merged)
I would prefer that every port has a uart.flush_rx() method as that leads to better code and more reliable behaviour across all ports.

**Comment by miketeachman** [comment]
what if, the PR was updated such that:
- uart.clear_rx() was implemented on the Pyboards, ESP8266
- docs were written

Would that clear the way to getting this PR accepted?

**Comment by mertozal** [comment]
Sorry for another pinging but this pr open for a 1.5 years. Is there any plan to merge or any walkaround for flush rx FIFO?

**Comment by miketeachman** [comment]
This PR has been open for more than one year - it is time to close it.  A workaround is to clear the read buffer by making this call:
`uart.read(uart.any())`.  As described in an earlier post, it may require multiple calls to `uart.read(uart.any())` to clear the UART read buffer.

**Pull request closed without merging**
