### PR TITLE
docs/reference/constrained.rst: Add missing symbols to mem_info().

### PR DESCRIPTION
**Pull request by chrisovergaauw**
…escription.

### CODE REVIEW

**Comment by chrisovergaauw** [comment]
first PR, some questions related to this process:

What's wrong with using my github email?
The convention demands the path to the file be present in the commit line, but that eats up a lot of the allowed 73 characters.
This commit message is exactly 73 characters and it still fails. what gives?

```
error: commit 5717811: Unwanted email address: 14801878+chrisovergaauw@users.noreply.github.com
error: commit 57178[11](https://github.com/micropython/micropython/actions/runs/3731424317/jobs/6329639342#step:4:12): Subject line should be 72 or fewer characters: docs/reference/constrained.rst: Add missing symbols to mem_info() in rst.
warning: commit 5717811: Message should be signed-off. Use "git commit -s".
```

**Comment by robert-hh** [comment]
> This commit message is exactly 73 characters and it still fails. what gives?

The limit is 72, as told by the error message.

**Comment by chrisovergaauw** [comment]
apologies, I can't read :)

**Comment by chrisovergaauw** [comment]
Can I split up the title and description in such a way that the parser accepts it?
I feel like the path to the filename eats up most of the 72 characters and the description is already pretty minimal

**Comment by robert-hh** [comment]
You can add any text to the body of the commit message. The trailing ' in rst' may be obsolete, since the file name is a .rst file. And you can further explain it in the body of the commit message, Or you write even shorter:
`docs/reference/constrained.rst: Add missing mem_info() symbols.`

**Comment by mattytrentini** [comment]
A nice little addition!

**Comment by dpgeorge** [comment]
Thanks, merged in 23ef29706e3be7515d07161234208b889cebae15

**Pull request closed without merging**
