### PR TITLE
Pyb dac write() and write_timed() add optional buffered arg.

### PR DESCRIPTION
**Pull request by peterhinch**
The behaviour of these methods is confusing because `write()` uses the analog buffer while `write_timed()` does not. Whatever the loading on the pin their behaviour will differ in respect of accuracy.

If the external hardware is designed with high-Z in the expectation of unbuffered output, the loss of accuracy incurred by `write()` is needless. Likewise if the hardware expects buffered output, `write_timed()` will produce poor accuracy. So any application wishing to use both methods will hit a problem with accuracy.

So it is useful to be able to determine in code whether the buffer is used. 

This PR adds an optional `buffered` boolean arg, defaulting to the current behaviour for each method so that existing applications are unaffected. The docs are amended to reflect this.

### CODE REVIEW

**Comment by dpgeorge** [comment]
> Whatever the loading on the pin their behaviour will differ in respect of accuracy.

Yes that's a good point.

This PR looks good.  The only thing I would change is rename the "buffered" keyword arg to "buffering" because buffering is an id that is already used (in the built-in open() function) and this would reduce code size.  Shortening it to simply "buffer" wouldn't be a good idea because that could be confused with a buffer of values to write to the DAC.

**Comment by peterhinch** [comment]
@dpgeorge I've done this but I think git has made a monkey out of me again - a spurious change to lib/stm32lib seems to have crept in. Perhaps you could advise?

**Comment by dpgeorge** [comment]
The PR looks fin to me, it's clean.

**Comment by dpgeorge** [comment]
Looking over this again I think there's a simpler/better way to do it: provide a setting in the constructor and init() method to configure the buffering behaviour.  See #3708

**Pull request closed without merging**
