### PR TITLE
extmod/mod: Added Python linkage for SO_BROADCAST for UDP broadcast.

### PR DESCRIPTION
**Pull request by xuancong84**
This PR solves the issue (https://github.com/micropython/micropython/issues/8729 ).
This PR makes `SO_BROADCAST` option available under socket library and allows for UDP broadcast.
In general, UDP broadcast is a very useful feature for devices belonging to the same group to discover each other on a local area network environment like home WiFi, so that they can communicate with each other even without Internet.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.  I have simplified the code and added support for SO_BROADCAST on esp32 as well.

**Comment by xuancong84** [comment]
Thanks @dpgeorge !
But did you simplify the code correctly?
I am not sure whether you overlooked, but the case for SOF_BROADCAST and SOF_REUSEADDR are similar but different as shown below:
```
case SOF_BROADCAST: {
            mp_int_t val = mp_obj_get_int(args[3]);
            // Options are common for UDP and TCP pcb's.
            if (val) {
                ip_set_option(socket->pcb.udp, SOF_BROADCAST);
            } else {
                ip_reset_option(socket->pcb.udp, SOF_BROADCAST);
            }
            break;
        }
```  
```
case SOF_REUSEADDR: {
            mp_int_t val = mp_obj_get_int(args[3]);
            // Options are common for UDP and TCP pcb's.
            if (val) {
                ip_set_option(socket->pcb.tcp, SOF_REUSEADDR);
            } else {
                ip_reset_option(socket->pcb.tcp, SOF_REUSEADDR);
            }
            break;
        }
```
Then the other thing I found is that in the original-version code, even if you do not set `SO_BROADCAST` for a UDP socket, UDP broadcast is working already.

**Comment by jimmo** [comment]
> I am not sure whether you overlooked, but the case for SOF_BROADCAST and SOF_REUSEADDR are similar but different as shown below:

@xuancong84 This is what the comment above is referring to: "Options are common for UDP and TCP pcb's." It should probably be explained better but what's going on here is that the `udp` and `tcp` members of the `pcb` are part of a union. Their IP options are in the same location (see the `IP_PCB` macro used at the start of both `struct tcp_pcb` and `struct udp_pcb`. So it actually doesn't matter whether you use `socket->pcb.udp` or `socket->pcb.tcp` here.

**Comment by xuancong84** [comment]
Thanks @jimmo !

But `SOF_REUSEADDR` and `SOF_BROADCAST` are different.
```
#define SOF_REUSEADDR     0x04U
#define SOF_KEEPALIVE     0x08U
#define SOF_BROADCAST     0x20U
```

Or maybe you want to mean the following:
```
    switch (opt) {
        // level: SOL_SOCKET
        case SOF_REUSEADDR:
        case SOF_BROADCAST: {
            mp_int_t val = mp_obj_get_int(args[3]);
            // Options are common for UDP and TCP pcb's.
            if (val) {
                ip_set_option(socket->pcb.tcp, opt);
            } else {
                ip_reset_option(socket->pcb.tcp, opt);
            }
            break;
        }
```
instead of 
```
    switch (opt) {
        // level: SOL_SOCKET
        case SOF_REUSEADDR:
        case SOF_BROADCAST: {
            mp_int_t val = mp_obj_get_int(args[3]);
            // Options are common for UDP and TCP pcb's.
            if (val) {
                ip_set_option(socket->pcb.tcp, SOF_REUSEADDR);
            } else {
                ip_reset_option(socket->pcb.tcp, SOF_REUSEADDR);
            }
            break;
        }
```

**Comment by dpgeorge** [comment]
@xuancong84 you are correct, I made a mistake and it should use `opt` instead of `SOF_REUSEADDR`.

I did test this patch and it worked on the stm32 port using lwip.  But now I see that broadcast is not actually enabled within lwip, neither `IP_SOF_BROADCAST` nor `IP_SOF_BROADCAST_RECV` are enabled.  I didn't follow through the lwip code exactly, but it seems that if these options are not enabled then broadcast packets are accepted unconditionally.  So that's why my tests still worked.

So, we need to investigate further how broadcast actually works with lwip.

**Comment by dpgeorge** [comment]
I fixed the mistake in 8dbdac8c8202be5ca90ac9291574057330095bae

**Pull request merged**
