### PR TITLE
py/objarray: Allow to create memoryview with offset/length.

### PR DESCRIPTION
**Pull request by pfalcon**
Constructor signature is extended to:

    memoryview(buf, offset, size)

This is equivalent to:

    m = memoryview(buf)
    m[offset:offset + size]

But allocates just 1 memoryview object instea of 2.

Also, .init(buf, offset, size) method added, which allows to reuse
(without allocation) existing memoryview object for new buffer object
(or to update "window" of memoryview into the buffer).

Change-Id: I1f864b908642b256305dc5caebf30662c306b1e0

### CODE REVIEW

**Comment by pfalcon** [comment]
This finally tackles matters discussed in https://github.com/micropython/micropython/issues/2552 . Of things discussed there it provides:

1. Additional offset/length arguments for memoryview constructor: `memoryview(buf, offset, size)`
2. Way to completely reinitialize a memoryview inplace, following RFC https://github.com/micropython/micropython/issues/4331 .
3. Doesn't implement way to change offset and/or change length of memoryview. This is deemed too much to do at once. p.2 allows to do that as a more general solution, even if in somewhat cumbersome way.


The main controversial issue, and something I'm anxious to get right is the matter of using `(start_offset, stop_offset)` vs `(offset, len)` parameters. The discussion is going to be long, so let me add a new comment on that.

**Comment by pfalcon** [comment]
So, as this PR adds `memoryview(buf, offset, size)` params, whereas, as we know, memoryview supports slicing syntax of `memview[start:stop]`. As a quick response, I think this is fine. Those are rather different syntaxes, and fairly different usecases, so they each stand out differently and no confusion.

However, would that sustain extended, critical consideration?

Let's first start with carefully reading https://github.com/micropython/micropython/issues/2552 to see what our own out-of-top-of-mind expectations were.

So, in https://github.com/micropython/micropython/issues/2552#issuecomment-255640617 , @dpgeorge first in that ticket himself wrote `inpl_memoryview(buf, offset, len)`. However, before writing that, he linked to https://github.com/micropython/micropython/blob/master/py/objarray.c#L215-L216 which talks about using slice start/stop.

(to be continued)

**Comment by pfalcon** [comment]
Well, how pervasive is slice (i.e. start, stop) syntax (on global scale)? Maybe everything should be expressed using it?

Some anthropology shows that slice syntax comes from Algol68. Wikipedia has a good article: https://en.wikipedia.org/wiki/Array_slicing . And Algol68's syntax quite directly taken to modern languages, like Python. For example, it allowed to omit start/stop to mean "from beginning"/"to end". The main difference to Python is that stop was inclusive, and there (apparently) was no special treatment for negative index to count from end. Oh, and of course Algol had 1-based array indexes ;-).

Python isn't the only popular language which adopted Algol68 slicing. Go and Rust are other examples. Just like Python the use mathematical (not 3rd-grade ;-) ) notation with 0-based indexing and exclusive "stop" bound.

So, it's fair to say that slicing (with start/stop indexes) is quite pervasive concept in the modern languages. Actually, it would be interesting to ask Go/Rust folks how unnatural it would be for a function working with slices, to take offset/size arguments. (Why not ask Python folks? Well, because we ourselves such, and supposed to know the answer? ;-) Except here we conjecture we don't. Why not ask wider Python audience? Well, the concern is that Python is so friendly language, that its user base is rather skewed, and a lot of people express rather random opinions, far from being rooted in language design considerations/expertise).

Also interesting question is whether there was a language with [start:len]-like slice syntax. The above Wikipedia article gives an example: Cilk Plus, the lingo now shelved by Intel.

**Comment by dpgeorge** [comment]
I think we need to find a solution that will be compatible with CPython, eg something like `micropython.update_memoryview(mv, buf, offset, size)`

**Pull request closed without merging**
