### PR TITLE
Convert all nlr .S files to .c with inline asm

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR converts all the py/nlrXXX.S assembler files to py/nlrXXX.c C files with inline assembler.  The benefits of this are:
- the core now only has .c files
- you can #include headers in .c files to get access to config variables (before, with .S files, this was a bit of a hack)
- no need for special treatment for linux vs mac vs windows (well, not as much as with .S files)
- much cleaner code because now half of it is written in C
- easily supports both threading and non-threading builds without magic numbers and difficult assembly

Drawbacks:
- slightly less efficient due to some C overhead (a few extra instructions here and there but nothing major)

@stinos I have a feeling that this won't work properly on all windows machines / with all supported windows compilers.  Can you please check and advise?  Thanks.

### CODE REVIEW

**Comment by stinos** [comment]
The msvc implementation uses setjmp so that is ok. With mingw the ode doesn't build currently due to an undefined reference to nlr_push_tail Reason for that, as well as the solution: http://stackoverflow.com/questions/1034852/adding-leading-underscores-to-assembly-symbols-with-gcc-on-win32.
Indeed after adding this this to nlrx86.c before the definition of nlr_push
```
#if NLR_OS_WINDOWS
unsigned int nlr_push_tail(nlr_buf_t *nlr) asm("nlr_push_tail");
#endif
```
everything builds and runs. No idea why nlrx64.c doesn't seem to need this modification though.

**Comment by dpgeorge** [comment]
@stinos thanks for testing.  I've now updated this PR to add that line in nlrx86.c and it seems that all tests are now passing.

**Comment by pfalcon** [comment]
ack

**Comment by dpgeorge** [comment]
Ok, this is now merged.

**Comment by pfalcon** [comment]
So, workaround for workaround for this is pushed as fd49ff991769a29b2dcc0f8ed88143487f2bd131.

**Comment by dpgeorge** [comment]
> So, this refactor, and this particular change broke Zephyr/x86

Sorry about that!  I didn't expect going from .S to .c with inline asm to be a simple change, but I still think it's worth it.

**Pull request merged**
