### PR TITLE
rp2/mpthreadport: Enable Systick for core1.

### PR DESCRIPTION
**Pull request by iabdalkader**
If core1 executes a `__WFI()` (for example when calling `cyw43_do_ioctl` as reported in issue #9597), it will never wake up, since it doesn't have any interrupts enabled by default (other than `SIO_IRQ_PROC1`). This patch enables `SysTick` for core1 to periodically interrupt it, to ensure that it wakes up from `__WFI()` if no other interrupt is enabled. Note each core has its own SysTick register, and SysTick IRQ is not enabled for core0, so this patch should Not affect core0 in any way.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks, I can see the need for this.

But I would actually rather go the other way and make sure core1 does not execute `__WFI()`.  We should be able to make it so core1 is tickless, that will be the most efficient thing to do.

If we add SysTick to core1 now it will be difficult to revert that and make it tickless in the future.  Better to keep it tickless from the beginning.

Is this PR only needed to fix #9597?  If so we should find a different way to fix that.  Eg not calling `cyw43_do_ioctl` from core1.

**Comment by iabdalkader** [comment]
> Is this PR only needed to fix https://github.com/micropython/micropython/issues/9597? If so we should find a different way to fix that. Eg not calling cyw43_do_ioctl from core1.

Yes sent it to fix that issue specifically, but if there's a WFI here or there in a sleep maybe, it will get stuck. I don't think the driver library should be aware of the port/core or this issue, so the fix should be in `cyw43_configport.h`

**Comment by iabdalkader** [comment]
Alternatively you can cherry-pick the second commit, which just ensures that core0 is the one calling __WFI().

**Comment by dpgeorge** [comment]
Thanks, that second commit looks good.  I merged it in 345f1d23957be43e1157463a6405ba9cb04bd43d

**Comment by iabdalkader** [comment]
@dpgeorge I may have found a better fix for this issue, see `SEVONPEND` bit in  https://developer.arm.com/documentation/dui0497/a/cortex-m0-peripherals/system-control-block/system-control-register?lang=en not tested yet though.

**Comment by iabdalkader** [comment]
It seems so, even though the documentation says enabled events and all interrupts including disabled ones.

**Pull request closed without merging**
