### PR TITLE
py/objcomplex: Allow strings of the form -A+Bj.

### PR DESCRIPTION
**Pull request by laurensvalk**
Allows parsing of a complex string with a similar result as CPython.

Until now, only strings like `3j` were supported, with strings like `1+2j` giving a syntax error.

The following strings will now also work.

```python
print(complex("1+2j"))
print(complex("+1+2j"))
print(complex("-1+2j"))
```

Cases with only a sign at [0] or no sign at all are treated as they already were.

Checks are added to force A to be real and B to be imaginary. This raises exceptions for the same cases as CPython, like Aj+B, even though MicroPython would otherwise return the correct result.

Fixes this [MicroPython forum post](https://forum.micropython.org/viewtopic.php?t=9216&p=51863).

Edit: Fix commit message < 75 characters per line.

Signed-off-by: Laurens Valk <laurens@pybricks.com>

### CODE REVIEW

**Comment by jimmo** [comment]
Thanks!

This is +96 bytes on PYBV11. I notice that objcomplex.c is the only place that sets the `force_complex=True` when calling `mp_parse_num_decimal` so I wondered whether this could be implemented more efficiently in `mp_parse_num_decimal` instead (when `force_complex=True` is set).

Here's an attempt at doing this: https://github.com/micropython/micropython/commit/ae8a38e3ac414b6703f12ec1db2ef80cbba8ffeb  Comes in at +64 bytes.

This also deals with an extra case where there's leading spaces (i.e. the +/- for the real component may not be the first character, e.g. `complex("  -1-2j")`). Although it does mean we now accept `complex("1 +2j")` which CPython doesn't.

**Comment by dpgeorge** [comment]
@jimmo 's version does look slightly more efficient, and it only creates one complex object whereas the version here creates 2 and then adds them (creating a third on the heap).

What do you think @laurensvalk ?

**Comment by laurensvalk** [comment]
Thanks for your quick responses. I'm all for @jimmo's more efficient implementation, so feel free to close this one.

For context, I came across this while documenting the MicroPython modules in more detail (still a work in progress) for use with Pybricks. Our plan is to provide typing and autocomplete in our [online editor](https://beta.pybricks.com/).

[image](https://docs.pybricks.com/en/latest/micropython/builtins.html#ubuiltins.complex)

**Comment by dpgeorge** [comment]
I took @jimmo 's attempt above and extended it, and made it #8799.  I'll close this PR in favour of that one (although it's still uncertain if it'll be merged or not).

**Pull request closed without merging**
