### PR TITLE
esp32: Add bootloader rollback support for all boards.

### PR DESCRIPTION
**Pull request by glenn20**
This PR adds support for OTA rollback to the bootloader for all ESP32 builds:

- Add `CONFIG_BOOTLOADER_ROLLBACK_ENABLE=y` to `ports/esp32/boards/sdkconfig.base` so that all micropython esp32 images support OTA rollback in the bootloader. 

With this change:

- Base micropython images for boards can be converted to OTA-capable images with app rollback support by user tools (eg. <https://github.com/glenn20/mp-image-tool-esp32>).
- Deployed devices can be hot-converted to OTA-enabled devices (with rollback support) be re-writing the partition table using tools, such as <https://github.com/glenn20/micropython-esp32-ota>.

There appears to be no detrimental impact arising rom enabling this feature in all ESP32 builds (see Espressif's [App Rollback documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/ota.html#app-rollback)).

This can also eliminate the need to build OTA variants of all esp32 boards for distribution if desired.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Shouldn't this be `CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=y`?  (note the "APP" bit in the config name).  How did you test this change?

If so, then would be good to remove this same config option from the three existing locations in board config files.

**Comment by glenn20** [comment]
Thanks for picking that up Damien. I must have merged the wrong commit from my dev branch. I'll fix, remove from the other OTA sdkconfig files, re-test with the right commits this time and push.

**Comment by glenn20** [comment]
Done. Let me know if there are any other issues. It's working for my tests....

**Comment by dpgeorge** [comment]
Thanks for updating.  Now merged.

**Pull request merged**
