### PR TITLE
lib/mp-readline: Make line wrapping work by not using VT100 commands.

### PR DESCRIPTION
**Pull request by dpgeorge**
The VT100 commands ESC[nD and ESC[K operate on a column basis and not a line basis, so do not work as intended when the line that is being entered is wrapped over more than one row on the terminal.

The simplest fix that should work everywhere is to just use space to erase and backspace to move back.

It might be possible to use fancy VT100 commands to do it more efficiently, but that costs code space and more importantly means that the readline might not work in situations where a full VT100 terminal is not available.  With this patch all that is required is that backspace works.

The terminal updating might be a little less efficient with this patch, but in my tests it wasn't noticeable when the line fit on one row.  With a wrapped line the line update does now become noticable, but this case didn't even work in the past.

Code size change for this patch is:
```
   bare-arm:    +0 
minimal x86:    +4 
   unix x64:    -8 
unix nanbox:   -14 
      stm32:    +0 
     cc3200:    -8 
    esp8266:    +4 
      esp32:    +4 
```

### CODE REVIEW

**Comment by dpgeorge** [comment]
@stinos if this goes through, maybe windows no longer needs to provide a custom version of these functions?

**Comment by dpgeorge** [comment]
For the record, the micro:bit port uses a similar algo to the one in the patch here, and that was done to improve compatibility with simple terminals.

**Comment by stinos** [comment]
Quickly tried it without the windows functions and it does seem to work at first sight. Which means we can also get rid of the `#if MICROPY_HAL_HAS_VT100`. Backspace works, cycling through history works, paste mode works. Anything else I should check for explicitly?

**Comment by dpgeorge** [comment]
> Quickly tried it without the windows functions

Thanks!

> Anything else I should check for explicitly?

Did/can you please check wrapping of the line?  Eg make a very long integer that wraps, then use left cursor to go back to the first line, then backspace and insert chars.

**Comment by stinos** [comment]
Wrapping doesn't work, cursor stays at same line. Might have something to do with the terminal being put in raw mode where it assumes the application handles everything including moving a line up. But it does do backspace so I'm not sure what exactly the problem is, would have to check the docs/code again for that.
Im going to look into that a bit tomorrow but if nothing comes out you can just commit this and I'll add a PR for wrapping on windows (which I never noticed but also doesn't work with the current windows_mphal code, but can be fixed easily)

**Comment by stinos** [comment]
Maybe I'm misunderstanding what this patch is supposed to do but line wrapping behaviour doesn't work correctly for me. I searched around a bit and I'm starting to think that if backspace works for you for going a line up it might actually be a side effect of the terminal being used: it doesn't work on windows so I also tried on 2 different ubuntu boxes and there it also doesn't work for me. I can't get back to the previous line with backspace, nor with the left arrow, cursor just sticks to the beginning of the second line?

**Comment by stinos** [comment]
#3887 is a fix for the windows port

Just now I also found out it should be possible to make windows consoles support VT100 and/or ANSI sequences so if we stick to those after all maybe I can still get rid of the windows-specific functions.

**Comment by dpgeorge** [comment]
> I searched around a bit and I'm starting to think that if backspace works for you for going a line up it might actually be a side effect of the terminal being used:

Hmm, ok, I'll need to do more testing then.  Maybe it's not actually possible to handle line wrapping in a simple way.

> I can't get back to the previous line with backspace, nor with the left arrow, cursor just sticks to the beginning of the second line?

That's not the behaviour I see, backspace (which also makes the cursor go back) does on my system go back to the previous line.

> Just now I also found out it should be possible to make windows consoles support VT100 and/or ANSI sequences so if we stick to those after all maybe I can still get rid of the windows-specific functions.

Well, it's not such an issue that windows has specific functions.  It's more important that things actually work!

**Comment by dpgeorge** [comment]
> Hmm, ok, I'll need to do more testing then. Maybe it's not actually possible to handle line wrapping in a simple way.

Testing using different terminal this patch doesn't work consistently.  On urxvt it works but on xterm it doesn't.  I guess it requires using a lot of "advanced" VT100 commands to properly support multiple lines (eg you need to know the current width of the terminal to know when the line wraps).

**Pull request closed without merging**
