### PR TITLE
Added txpower to WLAN config

### PR DESCRIPTION
**Pull request by ElHyperion**
I needed to configure tx power so I added a 'txpower' parameter to WLAN.config method for setting and getting max access point transmitter power. I tested it and the changes are effective immediately after entering the command. The WiFi signal strength on my phone dropped from excellent to poor after setting it from maximum to minimum. Minimum is -19 for -10.5 dBm and maximum is 76 for 19 dBm.

Minimal working example:
```
import network as net
ap = net.WLAN(net.AP_IF)
ap.active(True)
ap.config(txpower=76)
print(ap.config('txpower') * 0.25, 'dBm')  # 19.0 dBm
```

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.

I think it would make sense for the units of `txpower` to be dBm, so it's easier to understand and can be made compatible across different wireless devices.  Eg the CYW43 driver uses dBm units for `txpower`.

**Comment by tve** [comment]
Please add a docs update ;-)

**Comment by ElHyperion** [comment]
I tested the default levels and without any conversion it goes as follows, at least for the ESP32:

[-127, -20] -43
[-19, -8]   -19
[-7, 4]     -7
[5, 16]      5
[17, 24]     17
[25, 30]     25
[31, 40]     31
[41, 48]     41
[49, 52]     49
[53, 56]     53
[57, 63]     57
[63, 68]     63
[69, 74]     69
[75, 127]    75

I can set the output to be in dBm by multiplying it with 0.25 but the setter would have to be in this interval. I suggest keeping the setter as it is and just mentioning this list of intervals (converted to dBm) in the documentation, to reflect how it's defined for ESP-IDF, is that okay?

As for documentation, network.config seems to be mentioned only across all modules and the file I edited is only for ESP32. Do you want me to edit **library/network.rst** and/or **library/network.WLAN.rst** and perhaps mention under the param table that "config" is available only for the ESP32 ATM?

**Comment by tve** [comment]
This PR calls `esp_wifi_set_max_tx_power`, which is not AP-specific (unless I'm missing something). So putting it into the AP config is confusing at best (and annoying if someone needs to lower TX power in STA mode).

The power parameter of `esp_wifi_set_max_tx_power` is described in the ESP-IDF docs as "Maximum WiFi transmitting power, unit is 0.25dBm, range is [40, 82] corresponding to 10dBm - 20.5dBm here." So I want to second DG's request to use dBm as unit for portability reasons.

WRT docs, my recommendation is to add a paragraph that starts with "ESP32-only:" or something like that. @jimmo promised to tweak the style sheet so we can make these roll-up/roll-down...

**Comment by ElHyperion** [comment]
It is AP-specific, as I said the results are immediately visible when hosting an access point and scanning the network from another device. The setting sets the max tx power of an access point.

I'll update the getter only then, the range is different as you can see in my previous comment but I'll note it in the docs.

**Comment by tve** [comment]
> It is AP-specific

Can you elaborate what you base this statement on? I'm looking at https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/network/esp_wifi.html and I don't see a mention of AP in the description of that function. Unlike other functions that apply to the AP only, it doesn't have any `_ap_` in its name either.

**Comment by ElHyperion** [comment]
Misunderstood it, thought you meant it's not for access points, not that it's not only for access points.

It seems to be accepted by station interface but I'm not sure if it has any effect. I'll give it a few tests tomorrow and measure if it has any effect.

**Comment by ElHyperion** [comment]
I submitted my documentation edits, as requested. You can merge it now if no further edits are required.

**Comment by dpgeorge** [comment]
It looks like the code now returns dBm but still sets the power in non-dBm units.  It would be much more consistent if the units were the same, namely dBm for both setting and getting.

**Comment by tve** [comment]
This PR now has stray commits (e.g. adding MicroWebSrv2 as a submodule).
Also, I still have an issue with the fact that the txpower affects ap and sta communication, yet is placed into the AP API.

**Comment by dpgeorge** [comment]
This addition was made in ff28d2e3b349b10c10e57d9493f7f9d3869af8eb via #8518.  It should work on both AP and STA interfaces.

**Pull request closed without merging**
