### PR TITLE
extmod/ure: Fix warnings resulting from memset on const pointers

### PR DESCRIPTION
**Pull request by stinos**

### CODE REVIEW

**Comment by dpgeorge** [comment]
I don't think this is correct.  caps is an array of const pointers, not const itself, so you are allowed to write to caps (but not *caps).  There is no error with gcc 4.9.2 with -Wpedantic.

**Comment by stinos** [comment]
Pretty sure you are right, but msvc isn't happy with it. I'll do some digging first.

**Comment by stinos** [comment]
SO to the rescue as usual, which confirms this as a bug in msvc: http://stackoverflow.com/questions/29075288/convert-const-char-to-void and earlier http://stackoverflow.com/questions/10403713/why-does-visual-c-warn-on-implicit-cast-from-const-void-to-void-in-c-but.

Unfortunate, but I'd rather not see the warnings everytime. If you want I can add a comment of why the cast is there? Or locally suppress the warning with a pragma?

**Comment by dpgeorge** [comment]
I'd rather have the cast and a short comment than a pragma (since the latter would apply to the whole file and could mask other true bugs).

Strange that there are no other cases of this in the uPy source...

**Comment by stinos** [comment]
I agree on the comment, see commit. I looked around in the source and found no other occurences where such casts were done.

Filed a bug report, the sole comment from a member of the compiler team is

> Hi: this is a warning (that you can disable) and as far as I can tell it has been this way forever (I tried the code with the Visual C++ 6.0 compiler) so we currently do not have any plans to change this.

so unfortunately it looks like there aren't much plans to fix this.

**Pull request merged**
