### PR TITLE
RP2: Add wiznet5K support Raspberry pi pico.

### PR DESCRIPTION
**Pull request by irinakim12**
Changed to allow wiznet5k to be used in the ports/rp2 folder.

### CODE REVIEW

**Comment by irinakim12** [comment]
I want to add wiznet5K driver to be usable in the ports/rp2 folder.

**Comment by irinakim12** [comment]
The cause of the crash is that I modified ports/rp2/mpconfigport.h .
As far as I know, to use Wiznet5K's library under Network, I need to edit the file. 
This error occurs because I do not have permission to edit the file.

**Comment by robert-hh** [comment]
If you cloned the repository, you have full accesd rights and can do any change you like. Only the master repository is protected against changes by anyone. And that is good.

**Comment by dpgeorge** [comment]
This was implemented differently in bca816f5ac36609212ab087789ee028d1d5d534d

**Pull request closed without merging**
