### PR TITLE
esp32/boards: Adding ADAFTR_4M_2M_SPIRAM.

### PR DESCRIPTION
**Pull request by lukasz-lobocki**
Adding Adafruit ESP32-S3 Feather with 4MB Flash 2MB PSRAM.

### CODE REVIEW

**Comment by robert-hh** [comment]
You do not have to close a PR and open a new one, if you want to change something. You can do just a force-push to your repository on github after youi made the changes, which will update the open PR.

The problem, with the commit message format:
```
Message must be signed-off. Use "git commit -s".
See [https://github.com/micropython/micropython/blob/master/CODECONVENTIONS](https://github.com/micropython/micropython/blob/master/CODECONVENTIONS.md)
```
git commit -s creates a line like `Signed-off-by: robert-hh <robert@hammelrath.com>` with your name and e-mail in the commit message. You can modify an existing commit on your PC with `git commit -s -a --amend` and then force push it to github.

About the adaftr_4m_2m_spiram.py file: this is file is not needed and can go. Since recently the ESP32 port supports named pins, which are specifed in a pins.csv file of the board directory. See an example in PR #11405. 

And please write ADAFRUIT instead of ADAFTR, adafruit instead of adaftr (b.t.w.: why not adafrt?). You can change the title of a PR at github.

**Comment by lukasz-lobocki** [comment]
Thank you,

:) ADAFTR was ADAFRUIT + FEATHER.

I will create a new PR. I messed some other things beyond fixing.

**Comment by robert-hh** [comment]
What is the difference to the UM_FEATHER boards that already exist?

**Comment by lukasz-lobocki** [comment]
Replied in (https://github.com/micropython/micropython/pull/12072), which substitutes this PR.

**Pull request closed without merging**
