### PR TITLE
small unix and windows cleanups

### PR DESCRIPTION
**Pull request by dlech**
The first commit was suggested to be separated from #5723 in https://github.com/micropython/micropython/pull/5723#discussion_r395452395

The second commit is the same thing for windows.

The third commit was something I noticed while looking at the other two.

### CODE REVIEW

**Comment by dlech** [comment]
The 4th commit, I caught out of the corner of my eye as I was closing a window. 😃

**Comment by dlech** [comment]
The 5th commit fixes a windows build error that has probably been around for at least 2 years but wasn't noticed on CI until the other changes here.

**Comment by dlech** [comment]
The 6th commit fixes another windows CI build error that seems unrelated to the other changes here.

**Comment by stinos** [comment]
First commit mentions an SHA for `https://github.com/micropython/micropython/commit/354d17523f599746a84e5b22fa670c9910137947` which seems completely unrelated to what gets done there? Or if it isn't, can you explain exactly why? Minor: commit message should be 'removes' instead of 'removed'. And start with a capital after the colon.

Second commit seems to have the squashed message of other commits, but the commits themselves are still separate.

Anyway maybe merge the first 2 commits since they do the same and require the same explanation, then squash introduction of STDIN_FILENO and the needed includes.

**Comment by dlech** [comment]
Thanks for the review. Having the second commit separate is intentional since the first is just a clean up and the second is fixing a mistake. And as far as I can tell, the last two commits are not directly related to the other changes but are fixing existing independent problems that were exposed as a side effect.

**Comment by stinos** [comment]
> Having the second commit separate is intentional

Both are removing custom MP_PLAT_PRINT_STRN for essentially the same reasons I think (cleanup, not needed to have a separate definition since the mp_hal_xxx function does the same thing already)? And the windows one additionally was also wrong in the first place? I guess that could stay separate, but it's a bit confusing that the common reason isn't mentioned in both then.

> the last two commits are not directly related to the other changes

Yes you're right, I missed that it was adding unistd.h for extmod, not for the ports.

**Comment by dpgeorge** [comment]
Thanks for this.  Even though the first two commits are related I think it makes sense to have them separated as done here, eg in case they introduce regressions they are easier to track down (but I would have also been happy to merge had they been combined).

Merged in b1066a9f967ba4e12e9ca87820eab494177d8467 through 2f7d2bb3e20cb1a9034c1eabeff1e7fd6caaed78 with some minor edits to the commit messages.

**Pull request closed without merging**
