### PR TITLE
rp2/boards: Add Adafruit ItsyBitsy RP2040.

### PR DESCRIPTION
**Pull request by mcauser**

### CODE REVIEW

**Review by dpgeorge — APPROVED** [review]

**Comment by mattytrentini** [comment]
Also keen to get a Neopixel driver - implemented with PIO - bundled in for this board...

**Comment by dpgeorge** [comment]
> Also keen to get a Neopixel driver - implemented with PIO - bundled in for this board...

Yes it would be great to have the Neopixels on these boards work out-of-the-box (something for a separate PR).

**Comment by mcauser** [comment]
> Also keen to get a Neopixel driver - implemented with PIO - bundled in for this board...

Great idea! Where would that go? /drivers and /extmod are generic.
Should we have port specific drivers for PIO implementations?
`/ports/rp2/drivers` or `/ports/rp2/modules` or ... ?

**Comment by dpgeorge** [comment]
The `ports/esp8266/modules/neopixel.py` and `ports/esp32/modules/neopixel.py` are almost identical, so could be put somewhere else.  And maybe even reused for rp2 if rp2 provided the underlying write function.

**Comment by mcauser** [comment]
TinyPICO's dotstar.py could also be moved higher up: `/ports/esp32/boards/UM_TINYPICO/modules/dotstar.py`

**Comment by dpgeorge** [comment]
@mcauser does this need VID/PID configuration added now that #7594 is merged?

**Comment by mcauser** [comment]
Added VID/PID as per [CircuitPython board def](https://github.com/adafruit/circuitpython/blob/main/ports/raspberrypi/boards/adafruit_itsybitsy_rp2040/mpconfigboard.mk)

**Comment by dpgeorge** [comment]
Rebased and merged in 043848158df7d211f30d83b2565a7d3039b0592e

**Pull request closed without merging**
