### PR TITLE
esp32/boards: Adding ADAFRUIT_4M_2M_SPIRAM.

### PR DESCRIPTION
**Pull request by lukasz-lobocki**
Adafruit ESP32-S3 Feather with 4MB Flash 2MB PSRAM

https://www.adafruit.com/product/5477

### CODE REVIEW

**Comment by lukasz-lobocki** [comment]
[Original question](https://github.com/micropython/micropython/pull/12071#issuecomment-1646768529) from @robert-hh

Difference is in CONFIG_PARTITION_TABLE. For UM_FEATHERS3 it is "partitions-16MiB.csv". Here it is ""partitions.csv".

I used [this](https://github.com/orgs/micropython/discussions/10156) as a reference. And the board itself look like [this](https://gist.githubusercontent.com/lukasz-lobocki/706e2d53d86a0ba8085aed76dc07049b/raw/6f6bf3bcffee4b62b99c8ea6c9332b2f92a45f71/Feather%2520ESP32-S3%2520SPIRAM.png).

**Comment by robert-hh** [comment]
I've seen that. Even on closed PR's the conversation is e-mailed. But again: You do not have to close a PR and open a new one if you want to change a PR. You can always modify or extend an existing PR. Make yourself comfortable with the --force option of push, which allows to overwrite an existing PR, and the --amend option of commit, which allows to modify a commit.

Your deploy.ms file is pretty extensive. So you felt the need to write more than the existing ones in the boards directory. Please note, that on Linux it's not always `/dev/ttyACM0`, and similar on MAC. /dev/ttyACM0 is assigned to the first board plugged into the PC at a given time. If other CDC type device(s) were plugged in before the ESP32 board, then the ESP32 board will get a different device name.

**Comment by lukasz-lobocki** [comment]
Thank you, yes I will learn how to amend PR. Your hints are very helpful.

As of deploy.md; I assumed that this is what shows on https://micropython.org/download page. So chosen a longer description as newbies rarely feel comfortable with using instructions for other boards. Shall I amend deploy.md anyway?

**Comment by mattytrentini** [comment]
I have created a _very_ similar PR #10874 for the Adafruit ESP32-S3 _TFT_ Feather. Those boards share everything except the display, I believe. We should probably consolidate our efforts!

I believe the `deploy.md` you've used is from the Unexpected Maker S3 boards. Instead of duplicating that file, we should use one copy and link to it - and update the UM_xS3 boards to also use it. However, as @robert-hh mentioned, the current `UM/deploy.md` could be improved. So, for now, I think it's best to just link to the default `esp32/boards/deploy_s3.md`.

We can improve the deploy instructions in a separate PR - and update any S3 board (that has a Boot & Reset button) to use it.

**Comment by lukasz-lobocki** [comment]
Thank you, seems the display is the only difference.

Interesting idea of combining efforts. I am new to this, so I would appreciate someone with more experience.  How can we do it?

**Pull request closed without merging**
