### PR TITLE
sthmal/rtc.c: Add setcal() method to adjust RTC clock speed

### PR DESCRIPTION
**Pull request by blmorris**
This is a quick test of concept for using the RTC crystal calibration facilities on the STM32F4xx processors. It is extremely minimal and not intended to be pull-ready just yet, but I wanted to post it in case I get called to do other work for a while… feel free to close or set aside if it isn't a priority right now, but I will gladly implement any suggestions to get it able to be merged.

Motivation: see discussion at http://forum.micropython.org/viewtopic.php?f=2&t=326&start=20

Reference - section 26.3.11 of the programmers reference manual RM0090 
The RTC smooth digital calibration mechanism allows the clock to be sped up by up to 512 steps and slowed down by up to 511 steps, with each step corresponding to a change in speed of 0.954 ppm, for a total range of -487.1 to +488.5 ppm
I haven't yet set up my GPS timebase to attempt a proper calibration, but the following code compares the RTC subseconds value to the milliseconds timer (running on the main 8MHz system crystal) at different calibration values to demonstrate that the calibration is taking effect.

```
>>> rtc = pyb.RTC()
>>> rtc.setcal(-511)
>>> x = rtc.datetime()[7]; pyb.delay(30000); x - rtc.datetime()[7]
-3
>>> x = rtc.datetime()[7]; pyb.delay(30000); x - rtc.datetime()[7]
-3
>>> rtc.setcal(512)
>>> x = rtc.datetime()[7]; pyb.delay(30000); x - rtc.datetime()[7]
4
>>> x = rtc.datetime()[7]; pyb.delay(30000); x - rtc.datetime()[7]
5
>>> x = rtc.datetime()[7]; pyb.delay(30000); x - rtc.datetime()[7]
4
>>> rtc.setcal(0)
>>> x = rtc.datetime()[7]; pyb.delay(30000); x - rtc.datetime()[7]
1
>>> x = rtc.datetime()[7]; pyb.delay(30000); x - rtc.datetime()[7]
1
```

### CODE REVIEW

**Comment by blmorris** [comment]
@dhylands - Thanks, you are right of course. The `printf` was there for testing; I used hex format because I wanted to see that all the bits were actually being set, but didn't bother to mark it as a debug statement.
I will change the read-back code to return the calibration value in the same -511 to +512 range that gets passed to setcal(). It will read the CALR register and reserve the logic used to set it. This way any actual calibration values can be stored in a temporary variable while a test routine exercises the calibration setting code.

**Comment by blmorris** [comment]
Updated so that `rtc.setcal()` returns current calibration value when called with no argument.
Also added test cases and documentation.
I think this could be workable as-is; there are more mechanisms available in the hardware to do automatic RTC calibration by applying a reference clock signal to a designated input pin, but implementing all of those options adds bloat for functions that will likely see little use. This method allows for manual calibration, which is what I think most pyboard RTC users will want anyway.
One possible addition that I considered would be to check the return status of the call to `HAL_RTCEx_SetSmoothCalib()`, but I was't sure if it was necessary.
As always, any suggestions or recommendations on my amateur coding are appreciated.

**Comment by dpgeorge** [comment]
Looks good.  I would rename the function to `calibration` since then it makes sense that it can return or take parameters (and we already have Servo.calibration).

The usual discussion now arises: how does this generalise to other MCUs?  Answer: having a calibration method seems sensible and would be used by a generic RTC, but the arguments to it would differ.  I think anyway if you're calibrating the RTC you need to really know the hardware you're running on so couldn't expect rtc.calibration(10) on one board to mean the same thing on another.

@danicampora Does the CC3200 have an RTC calibration capability?

**Comment by blmorris** [comment]
Great, it will be `calibration` then.

>The usual discussion now arises: how does this generalise to other MCUs? Answer: having a calibration method seems sensible and would be used by a generic RTC, but the arguments to it would differ. I think anyway if you're calibrating the RTC you need to really know the hardware you're running on so couldn't expect rtc.calibration(10) on one board to mean the same thing on another.

It is hard for me to imagine an RTC with a reasonably sane calibration method that wouldn't map onto a signed integer within a specified range, like I have done here. Of course the actual range and scaling could differ; one way to address the scaling would be to pass a floating point argument indicating the adjustment in terms of parts-per-million, but then we cant assume that floats are available on all ports. I hope that a single signed integer calibration value strikes a reasonable balance between simplicity and a generic API.
That said, I don't have any experience using RTC's on other processors, but I think that @manitou48 does.

**Comment by dpgeorge** [comment]
> one way to address the scaling would be to pass a floating point argument indicating the adjustment in terms of parts-per-million

We could define it to take an integer which specifies a PPM adjustment... but then that is already too coarse (just) for the case at hand, which has a resolution of 0.954 PPM.  Instead it could be PPB, but then you'd need some awkward maths to convert the input value to the value for the RTC calibration register, and you'd lose some accuracy in this conversion.

If it was PPB the formula would be: rtc_cal_value = ppb_input_value / 954.

If it was PPB then you could perhaps use the RTC_SMOOTHCALIB_PERIOD_8SEC to get finer resolution if the input number was within range.

**Comment by blmorris** [comment]
We could use PPB, but I don't really like it, and my reasons for not liking it would also apply to using a floating point calibration (if it were available.)
* It gives the illusion of precision which isn't actually there.
* In spite of seeming to be precise, it isn't exact - the actual resolution isn't 0.954 PPM, but `pow(2,-20)` or `9.5367431640625e-07`
* It introduces an additional layer of complexity unnecessarily masking the operation of the actual hardware.

Instead I would suggest the following: keep the argument to the `calibration` method as a simple integer representing the number of native resolution steps, and introduce an additional attribute to the RTC class which describes the calibration resolution and range for a given port. For example, for the stmhal port this could be the following tuple: `(resolution, min_cal_value, max_cal_value) = (2**20, -511, 512)`. The actual calibration resolution would be `1/resolution`; in this way the exact resolution would be captured by a simple unsigned integer.
This proposal would keep the code written in C for RTC calibration on each port as simple as possible, and keep the interface transparent to users who understand the hardware and want to calibrate manually. For others, a generic RTC calibration routine could be written in Python which could apply to all ports were RTC calibration is implemented, and the Python routine would determine the exact calibration parameter based on the resolution and range attribute.
This calibration attribute tuple could aways be added at a later time once we decide exactly what it should look like.

> If it was PPB then you could perhaps use the RTC_SMOOTHCALIB_PERIOD_8SEC to get finer resolution if the input number was within range.

If I understand correctly, the shorter calibration periods actually reduce the achievable resolution - that is why I fixed it at 32 seconds.

**Comment by blmorris** [comment]
I pulled together a short summary of RTC calibration features in the existing RTC hardware ports (besides stmhal, which is discussed above):

* cc3200 - no RTC calibration features are described in CC3200 data sheet or programmer's reference manual. Given that this processor is designed to connect to a network, it might have been assumed that accurate time is available from outside so that long-term internal precision is not as critical.

* teensy (Freescale MK20DX256) - The teensy board provides a footprint for an RTC crystal, but it is not installed by default. The processor hardware has an RTC Time Compensation Register (RTC_TCR), described in section 40.2.4 of the K20 Sub-Family reference manual.
This function appears to take two parameters:
1- an update interval between 1 and 256 seconds
2- the number of 32768 Hz ticks (range -127 to 128) that get added to the current second counter at each update interval

According to the documentation this system can correct errors between 0.12 ppm and 3906 ppm (adding or subtracting a single 32768 Hz tick every 256 seconds is an adjustment of 0.1192 ppm).

This is the oddball; it requires two integers to describe the calibration value. Also, with this method the apparently high precision is only available when the required correction is small; it also produces discontinuities not present in the stmhal method.

* eps8266 - I haven't dug into the documentation here.

* dspic16 - quote from section `37.5 - RTCC CALIBRATION` of http://ww1.microchip.com/downloads/en/DeviceDoc/70301C.pdf

 > Each calibration step either adds four or subtracts four oscillator cycles for every one minute (60 x 32.768 kHz = 1,966,080 oscillator cycles). This equates to ±2.034 parts per million (ppm) of adjustment per calibration step or ±5.35 seconds per month. It allows calibrating the timekeeping accuracy to within three seconds per month. Table 37-3 details the amount of adjustment for each value in the calibration register.

Say what you will about the PIC architecture(s), but I have always
appreciated the clarity of the documentation produced by Microchip.

**Comment by dpgeorge** [comment]
@blmorris thanks for the comprehensive survey.

It's probably general enough then to say that rt.calibration takes 1 integer argument and adjusts the RTC by that integer, approx 1ppm, but the exact details are machine specific.  Extra keyword args can be used to control other params; eg for teensy the update interval could be a sensible default, and can be overridden by a keyword arg.

**Comment by dpgeorge** [comment]
Rebased, squashed and merged in 5df81de7afbf4e9f24413ba957f4a7cce89fa1e0.

**Comment by blmorris** [comment]
@dpgeorge - Thanks for pulling this in.
I just had a few more thoughts to add to this thread before moving on.
Given that stmhal is the only hardware port that currently implements RTC and has calibration capability, having a consistent calibration API across multiple ports is not yet an urgent priority.
However, I want to suggest here that the three hardware ports that support calibration (stmhal, teensy, and pic16bit) _could_ be unified by including a 3-tuple of calibration attributes.
The fields would be (cycle time in seconds, min calibration value, max calibration value)
The cycle time is the period in which a single calibration step can be added or subtracted, and it entirely determines the calibration resolution. 
* For stmhal, the cycle time could be 8 sec, 16 sec or 32 sec (I have fixed it to 32 in this implementation); min_cal = -511, max_cal = 512
* For teensy, the cycle time could be any integer from 1 to 256 seconds; min_cal = -127, max_cal = 128
* For pic16bit, cycle time is fixed at 15 seconds (four cycles added or subtracted each minute); min_cal = -128, max_cal = 127

If the cycle time is a settable value, and a Python script could determine whether it is settable, then a library function could be written in pure Python to compute the optimal calibration settings required for any processor, given a target adjustment in PPM (and in this way the goal of a completely generic API can be achieved.)
But that is a project for another day :)

**Comment by dpgeorge** [comment]
@blmorris that does sound quite generic, the concept is like leap years: add 1 day ever 4 years.

So for the calibration() method it could take 2 parameters: rtc.calibration(cycle, leap); ie every cycle seconds it adds leap to the counter (which could be positive or negative).  Do you think it's worth changing the API to this?

**Comment by blmorris** [comment]
@dpgeorge - I like it, and the leap-year metaphor sounds exactly right to me.
I'll suggest the following API:
* With no arguments, `calibration()` returns a tuple of (leap, cycle) - and I deliberately place 'leap' first, because:
* With one argument, `calibration(leap)` works exactly as we have it now.
* Finally, with two arguments, `calibration(leap,cycle)` sets both parameters; however, it will test whether 'cycle' is a valid value and throw an exception if it isn't.

For stmhal and pic16bit, 'cycle' will always be 32s and 15s, respectively; for teensy it can be any value in `range(256)`; a python driver can test whether the cycle is configurable simply by trying to configure it. (It's the Python way!) Likewise, I think that the specific calibration range for a given implementation can be left for the external documentation - an out-of-range value just throws an exception.
I realized that I misinterpreted the documentation for stmhal when I suggested that 8 and 16 seconds were available cycle times - in fact it always applies a 32 second calibration cycle. The stmhal RTC peripheral provides a hardware mechanism for automatically calibrating the RTC from a reference signal applied to one of the pins. The options for 8 and 16 second cycles are specifically to allow this mechanism to calibrate in a shorter time at the expense of coarser calibration resolution; the ultimate range of ~+/-488 ppm still applies.
I am not going to suggest providing python bindings for this automatic calibration mechanism. It will be too implementation-specific, I don't see providing an API that could be generic across ports.

**Pull request closed without merging**
