### PR TITLE
stm32: boards/NUCLEO_L476RG mpconfigboard.h update

### PR DESCRIPTION
**Pull request by Jolatomme**
Dear micropython community,
This is my first pull request. I am discovering github and I am not a software engineer.
I do apologize in advance  if I am not doing things right.
By default RNG and DAC support were not enabled on NUCLEO L476RG.
CAN bus was also not mapped. I needed this stuff for my project and thought it could useful to have
it by default.
Regards,
  Jo.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution!  I see that there's more than just the NUCLEO-L476RG change here, and so I'll ignore the commits related to L1 support.

Did you test RNG and DAC on this board?  And why is the PLLQ value changed from 4 to 2?

Did you intend for the pin changes for I2C and SPI buses to be included here?

**Comment by Jolatomme** [comment]
Hello Damien,
Thank you for the reply. I just wanted to make the request for this file :
/boards/NUCLEO_L476RG mpconfigboard.h
But since I am trying to port micropython on STM32L152 architecture, all the modifications I did were included in the request. I do apologize, I am new to github and did not figure out yet how to do a pull request for a single file.
Yes I tested RNG, DAC on this board. RNG returns a random number. I tested the DAC in closed loop with the ADC. ADC is nice on L4, it is fully differential. And yes, DAC is working fine.
PLLQ  is set to 2 for CAN bus. I could not manage to compile micropython with PLLQ=4.
On discovery board setup : CAN is enabled and PLLQ is set to 2.
Yes I intended a PIN change to free space (pin mapping) for the CAN bus.  CAN bus is not enabled by default, but according to me, CAN bus is a nice interface on L4.
I already replied by mail but I realized for documentation purpose, it could be nice to have a trace in github. So I do apologize for answering twice.
Regards,
  Jo.

**Comment by dpgeorge** [comment]
Thanks @Jolatomme for the info.

Regarding the changes here:
1. enabling RNG and DAC is good
2. changing PLL values is ok
3. changing I2C1 default pins is ok, they match the SCL/SDA labels on the nucleo board
4. adding CAN1 pins is good
5. commenting out I2C3 and SPI2 pins: I don't think this is a good change, CAN should be able to work with these still here, right?

Also, this project requires that any commits from contributors include a real email address (for traceability of code), but your commit uses the github no-reply address.  Are you able and willing to supply an email address that will be written into the commit against your name?

**Comment by Jolatomme** [comment]
Hello Damien,
Thank you for your reply.
Regarding point 5, I totally agree with you. It should work.
I will check and get back to you. I will run two sets of compilation on 2 different operating systems (W7 & Freebsd). And Then I will test the two builts on my nucleo board. This way I will have and extensive coverage.
Regarding the email address I have absolutely no problem with that. It is just that I am new to github and software development. I have to figure out how to do that.

**Comment by Jolatomme** [comment]
Hello Damien,
As promised I tested your point 5. You are right, it is working without commenting I2C and SPI.
I have no idea on how to proceed now. Shall I cancel or close my pull request and submit a new one, or may we go ahead with this one just removing the comment on I2C and SPI ?

**Comment by dpgeorge** [comment]
> Shall I cancel or close my pull request and submit a new one, or may we go ahead with this one just removing the comment on I2C and SPI ?

Unless you want to have another go at it (for learning purposes), I can fix it up when I merge it.  The main thing is to add a contact email for yourself.... which you can send me, or, again, try to open a new PR with your address in it.

**Comment by Jolatomme** [comment]
OK, let's close this PR and I will make a new one. Sorry for inconvenience. I also figure out (I believe so) how to change the settings for the mail contact.

**Pull request closed without merging**
