### PR TITLE
port-javascript: can't push twice

### PR DESCRIPTION
**Pull request by pmp-p**
would raise syntax error when importing externals.

### CODE REVIEW

**Comment by pmp-p** [comment]
patch is invalid it's just to show what will fail when going from do_load_from_lexer() there 
https://github.com/micropython/micropython/blob/34c04d2319cdfae01ed7bf7f9e341d69b86d751a/py/builtinimport.c#L143

**Comment by pmp-p** [comment]
that seems to work https://gist.github.com/pmp-p/d72c8dddc8c3e28072b64176fa6a2492 but could be only for one code path in a test case. I leave that to any emscripten expert around.

**Comment by pmp-p** [comment]
no idea if there's a connexion to the nlr_push(&nlr) return value,  but since recent emsdk update i get (on WASM builds not WASM=0 like javascript port) ```Linking globals named 'nlr_push_tail': symbol multiply defined!```

**Comment by dpgeorge** [comment]
> would raise syntax error when importing externals.

Can you please expand on this, and also provide a way to reproduce the error that you see?

**Comment by pmp-p** [comment]
@dpgeorge just drop and compile https://github.com/pmp-p/micropython-ports-wasm into ports folder and launch the python mini server provided with and goto to http://127.0.0.1:8000/next.html 
then type "import assets", a one line module that contains ```print("*assets.py*")``` that got built in emscripten FS.


depending on emsdk used you may have some "syntax error" or just nothing instead of the printed ouput and a module half loaded in sys.modules.

 I can't explain to myself why at all apart from emsdk problem since the imp workaround here https://github.com/pmp-p/micropython-ports-wasm/blob/master/assets/imp.py can build a good module via its source even with untouched micropython git source.

**Comment by pmp-p** [comment]
i added empty.py and asset.py into assets folder,

namespace packages and empty modules or containing '#' are fine ( and still import assets.assets raise the syntax too error i checked )
so it's the parser, module object creation is ok.

```
MicroPython 4913cdb-dirty on 2019-06-24; emscripten with wasm
>>> import empty
>>> import assets
>>> import asset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "assets/asset.py", line 2
SyntaxError: invalid syntax
>>> dir(empty)
['__class__', '__name__', '__file__']
>>> dir(assets)
['__class__', '__name__', '__path__']
>>> dir(asset)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name not defined
>>> 
```

**Comment by pmp-p** [comment]
i think it has to do with memory allocation in parser.

https://github.com/micropython/micropython/pull/4723 is failing too but in a different way.

**Comment by pmp-p** [comment]
@dpgeorge  i found something weird by changing a mp_lexer_show_token to
```
printf("(" UINT_FMT ":" UINT_FMT ") kind:%u str:%s len:%lu vstr.len:%zu", (uint)lex->tok_line, (uint)lex->tok_column, (uint)lex->tok_kind, lex->vstr.buf,strlen(lex->vstr.buf), lex->vstr.len);
```
i get a 0 sized vstr len though it points to a correct c string
```
MicroPython 6f611c2-dirty on 2019-07-05; emscripten with wasm
>>> import xpy
(2:4) kind:1 str:try len:3 vstr.len:0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xpy/__init__.py", line 2
SyntaxError: invalid syntax
>>> 
```

**Comment by dpgeorge** [comment]
> i get a 0 sized vstr len though it points to a correct c string

That's allowed.  If the kind is MP_TOKEN_INVALID (=1) then vstr is not necessarily valid.  Only certain tokens are associated with a valid vstr.  The "try" value you see in the vstr is from the previous valid token.

**Comment by dpgeorge** [comment]
> #4723 is failing too but in a different way.

You might need to combine both that patch (explicit root stack) and NLR removal #4131

**Comment by pmp-p** [comment]
>  The "try" value you see in the vstr is from the previous valid token
@dpgeorge thx now i know what to search for, i guess lexer buffer got corrupted while parsing.
i hope it's somewhere in my file handling code.

**Comment by pmp-p** [comment]
pfffff i used fread instead of fgets lexer was running after source code len

well at least i'll keep that https://github.com/micropython/micropython/pull/4860/commits/e615932b8a013601db32d55d2302cbdb25daf92f

**Pull request closed without merging**
