### PR TITLE
adding MICROPY_HW_FLASH_DQS flag

### PR DESCRIPTION
**Pull request by d3v1c3nv11**

### CODE REVIEW

**Comment by robert-hh** [comment]
> but have problem with second REPL

What was the problem with a second REPL, you mentioned in the conversation of PR #8092? Is it about using dupterm()?

**Comment by d3v1c3nv11** [comment]
> > but have problem with second REPL
> 
> What was the problem with a second REPL, you mentioned in the conversation of PR #8092? Is it about using dupterm()?

UART don't receive, output to terminal is ok but no input to REPL

boot.py
`import uos, machine` 
`uos.dupterm(machine.UART(1, 57600), 1)`

REPL:
`MicroPython v1.17-257-gd6dc4cb65-dirty on 2021-12-17; RT1010-Py-DevKIT with MIMXRT1011DAE5A
Type "help()" for more information.....`

**Comment by robert-hh** [comment]
Dupterm support may be incomplete. It works if you tell duperm that there is something present in the input queue:
```
import uos, machine
uos.dupterm(machine.UART(1, 57600), 1)
tim=machine.Timer(mode=machine.Timer.PERIODIC, period=30, callback=lambda x:uos.dupterm_notify(x))
```

**Comment by d3v1c3nv11** [comment]
> Dupterm support may be incomplete. It works if you tell duperm that there is something present in the input queue:
> 
> ```
> import uos, machine
> uos.dupterm(machine.UART(1, 57600), 1)
> tim=machine.Timer(mode=machine.Timer.PERIODIC, period=30, callback=lambda x:uos.dupterm_notify(x))
> ```
> 
> The time callback tells dupterm every 30ms to look for data. The time is not critical. Could be 50ms as well.

this works. Now i'm sure all the hardware is ok. Sorry but we shipped yours board with cdc hard setted to 57600. Will be corrected next week on cmsis-dap firmware.

**Comment by dpgeorge** [comment]
Merged in 802ef271b8a90acf504b9750b0b4494146b7fb22

**Pull request closed without merging**
