### PR TITLE
ports/mimxrt: Flash configuration updates and fix IMXRT1064 board config.

### PR DESCRIPTION
**Pull request by iabdalkader**
* This patch is necessary to make MicroPython work on this eval kit out of the box, as the eval kit ships with the HyperFlash physically disconnected from the bus (refer to the schematics or the user guide) and the QSPI connected instead, but the fuses/board/pins are configured to boot from internal flash (on FlexSPI2). Note enabling the HyperFlash is not trivial, as it requires soldering and desoldering of many small footprint resistors and changing fuses.

Tested 1170_EVK (still builds) and 1064_EVK:

```bash
>>> 
MPY: soft reboot
MicroPython v1.19.1-911-g75cdecca3-dirty on 2023-02-28; i.MX RT1064 EVK with MIMXRT1064DVL6A
Type "help()" for more information.
>>> 
```

robert-hh tested the following:

Olimex rt1010 (i.mx rt 1010)
MIMXRT1050_evkb (Hyperflash)
Teensy 4.1 (i.mx RT 1062)
MIMXRT1170_EVK

### CODE REVIEW

**Comment by robert-hh** [comment]
Thanks. We always had the 1ß60_EVK and 1064_EBK  boards in the list, but lacking a board we could not test it. And since the initial commit, the board has changed in supporting Hyperflash instead of SPI flash. I'm wondering about your flash type comment. The i.MX RT1064 has 4 MB built-in flash. Does the board really have an external SPI flash chip?
And yes, i was concerned when seeing the list of files being changed. But before reading your explanaition (on my mobile I did not see it immediately) I noticed the kind of change.
I will test your PR with the other MIMXRT board I have here. I assume you had tested it with a Teensy 4.x already.

**Comment by iabdalkader** [comment]
> The i.MX RT1064 has 4 MB built-in flash. Does the board really have an external SPI flash chip?

Yes, this board/chip combined have the following:

4 Mbit (internal) QSPI Flash
64 Mbit (external) QSPI Flash
512 Mbit Hyper Flash

The HypeFlash is disconnected by default, only the external QSPI is connected to the chip, but the board/fuses/GPIOs seem to be configured for internal boot (from the internal 4 MBs QSPI) so we can't use either of them out of the box. Note when you set the flash type to internal the build breaks (the Makefile/LD just doesn't handle "internal" type) instead of trying to fix that I just made the base address/FlexSPI configurable since they use the same drivers anyway.

> I will test your PR with the other MIMXRT board I have here. I assume you had tested it with a Teensy 4.x already.

No I don't have any other iMX boards/chips to test with (but I may get an 1170 kit soon), however this change shouldn't break anything else.

**Comment by robert-hh** [comment]
I tried a few builds. The one for MIMXRT1170 does not build. You could try yourself.

**Comment by iabdalkader** [comment]
@robert-hh I realized it may be easier to fix the internal flash type, working on it and will retest, I noticed this was part of the problem:
```c
#if MICROPY_HW_FLASH_TYPE == qspi_nor_flash
```
I don't think this is valid cpp macro check (both macros here will just equal 0, so 0 == 0)

**Comment by robert-hh** [comment]
This type of check worked for the two flash types. One of the boards I have uses hyperflash.

**Comment by iabdalkader** [comment]
> This type of check worked for the two flash types. One of the boards I have uses hyperflash.

It's invalid, it just always evaluates to true, it worked before because both external QSPI and HyperFlash use 0x60000000 base, just lucky, not for internal which uses a different base.

**Comment by robert-hh** [comment]
b.t.w. I found the reason why the 1170 did not build. Now it does. Built and started MP with:
i.mx rt1010 (Olimex board)
mimxrt1015_EVK
MIMXRT1020_EVK
MIMXRT1050_EVKB (Hyperflash)
Seeed Arch Mix (i.mx rt1052 with QSPI flash)
Teensy 4.0 and 4.1 (i.mx rt 1062)
MIMXRT1170_EVK

**Comment by iabdalkader** [comment]
@robert-hh I fixed the internal flash build instead, and updated, tested 1170 (builds) and 1064 builds and works, the changes should be much simpler now. Assuming all the boards with internal flashes have it on FlexSPI2, it should be good for now we don't need to make the bus configurable (for now).

**Comment by robert-hh** [comment]
OK. I'll do the re.test, but not today anymore.

**Comment by iabdalkader** [comment]
> OK. I'll do the re.test, but not today anymore.

Thank you! Please take your time.

**Comment by robert-hh** [comment]
I tested a few edge case boards, and all build fine and run:
Olimex rt1010 (i.mx rt 1010)
MIMXRT1050_evkb (Hyperflash)
Teensy 4.1 (i.mx RT 1062)
MIMXRT1170_EVK

What brought you to look into the MIMXRT series? And which 1170 board did you order? If it is the NXP MIMXRT1170_EVK, it would be interesting if the WiFi module is assembled. The one I have here has no WiFi, diffferen to what was announced.

**Comment by iabdalkader** [comment]
That's great, thanks for testing @robert-hh 

> What brought you to look into the MIMXRT series? And which 1170 board did you order? If it is the NXP MIMXRT1170_EVK,

Just trying alternative chips, the out of the box experience is very bad (unless you use their tools maybe mcuxpresso) but they still need to provide better documentation, user guides etc.. but I thought at least MicroPython should work out of the box. I actually didn't order the 1170_EVK I ordered the SLN-TLHMI-IOT and it has WiFi/BT so may add a new board for it.

**Comment by robert-hh** [comment]
> Just trying alternative chips, the out of the box experience is very bad (unless you use their tools maybe mcuxpresso) but they still need to provide better documentation, user guides etc

I did not like the mcuxespresso, like I do not like the dev environment for SAMD chips. Too much overhead and implicit restrictions. The NXP API documentation is sparse, mostly that what is written in the comments of the library code. So I hardly ever looked into that and instead into the code, which is better readable than their documentation. The same for SAMD. The dev system's documentation is lousy. But the data sheet is excellent, making it easier to code along the data sheet than using their ASF library.

> I ordered the SLN-TLHMI-IOT

Wow. That's an expensive piece of electronics.

**Comment by iabdalkader** [comment]
> Wow. That's an expensive piece of electronics.

Yes it's a bit on the high side, but it comes with a lot attachments, display and WiFi/BT, so it could be a useful for improving the mimxrt port, may also get the EVK if I do will give the 1170 a test.

**Review by robert-hh — APPROVED** [review]

**Comment by iabdalkader** [comment]
Hi @dpgeorge Can you please take a look at this as the EVK doesn't work at all without it 🙏🏼

**Comment by dpgeorge** [comment]
This looks OK, and thanks both of you for extensive testing.

**Pull request merged**
