### PR TITLE
[WIP] nrf: Change Xenon board to use built-in bootloader.

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR is a WIP to support the built-in bootloader on the nrf Xenon board (currently the entire flash is overwritten with MicroPython firmware using an external programmer; using this PR allows to use the built-in USB DFU to download firmware).

### CODE REVIEW

**Comment by glennrub** [comment]
@dpgeorge , we used to have something similar for Feather52, but removed it before we merged with mainline ([Link](https://github.com/tralamazza/micropython/pull/204)) as i wanted all targets to be aligned with S132v6 and it was a bit hard to get in a new SoftDevice with larger size using the onboard bootloader and available tools at that time.

Do you know the location of the bootloader? Is this the reason why `_app_start` is a bit unfamiliar? or would it be at the end of flash?

**Comment by dpgeorge** [comment]
@glennrub from my (limited) understanding the SoftDevice from Nordic actually includes a small bootloader in the first 4k (8k?).  And it looks like Particle just replaces this with their own USB-DFU-based bootloader.  So the flash memory footprint is the same using their bootloader with SD, or just using the standard SD.

> Do you know the location of the bootloader?

It's at 0x00000000.

> Is this the reason why `_app_start` is a bit unfamiliar?

The start of the app is at 192k = 0x30000.

**Comment by mzdaniel** [comment]
Thank you glennrub and dpgeorge for working on this. 

As https://github.com/micropython/micropython/pull/5041 was merged and Micropython can be compiled, flashed (in my case with Particle's debugger and OpenOCD) and run in a pca10059, I assumed the xenon board would work. It is not clear what else is missing...

I tried compiling with "make BOARD=particle_xenon" (generating a firmware.hex of 467176 bytes) and "make BOARD=particle_xenon SD=s140" (generating a firmware.hex of 499917) and after flashing none of these firmwares made the xenon show as /dev/ttyACMx (no even messages on dmesg)

Will be great to run micropython in Xenons even with no bluetooth, SD or Particle's built-in bootloader, at least to start experimenting with them. I can help with testing.

**Comment by mzdaniel** [comment]
Made an interesting and validating discovery. After successfully flashing a pca10059 with pyocd, I tried to flash the xenon with "pyocd flash -e chip -t nrf52840 pca10059.hex". For the first time, I am able to run micropython on the Xenon, which makes sense as both boards are based on underlying nrf52840

**Comment by dpgeorge** [comment]
>  I assumed the xenon board would work. It is not clear what else is missing...

@mzdaniel the Xenon board does currently work.  The point is that the MicroPython firmware will overwrite everything on the Xenon, starting at offset 0x00000000.  This means you must use an external debugging device to load the firmware.  Also the REPL is available only on a UART, not on the native USB of the Xenon.

This PR here aims to get the Xenon board working using its own bootloader, the one it ships with from Particle, so that it doesn't need an external debugging device.

**Comment by mzdaniel** [comment]
Ah, it completely escaped me to test if UART was live on the boards. 

And thank you again for the outstanding Micropython.

**Comment by dpgeorge** [comment]
Closing.  The Xenon board is deprecated https://blog.particle.io/mesh-deprecation/. Particle recommend using CircuitPython's bootloader https://docs.particle.io/tutorials/learn-more/xenon-circuit-python/.  In the future we can support that bootloader instead (but the Xenon does still work with MicroPython, you just need to use an external debugger to flash it).

**Comment by mzdaniel** [comment]
That's a great idea to support CircuitPython bootloader and as a big plus run micropython in their boards!  I attempted it before with mixed results, being able to boot micropython, but crashing the second I attempted to use the filesystem. That was before the merging of #7619 so things might be already better

**Pull request closed without merging**
