### PR TITLE
mimxrt: Align the FROZEN_MANIFEST statement.

### PR DESCRIPTION
**Pull request by robert-hh**
Change them in the mpconfigboard.mk files from

FROZEN_MANIFEST ?= $(BOARD_DIR)/manifest.py
to
FROZEN_MANIFEST = $(BOARD_DIR)/manifest.py

Similar to the stm32 port. Alternative, Makefile could be changed.

### CODE REVIEW

**Comment by robert-hh** [comment]
@dpgeorge Quite a few formatting error messages in Python code that was NOT changed. So it seems that the black profile or version has changed.

**Comment by jimmo** [comment]
Thanks @robert-hh but I think this is correct as-is. For consistency, we should use `?=` by default for all assignments to avoid surprises where later assignments replace earlier ones.

The bug here is as you suggested in the comment on the micropython-lib PR: https://github.com/micropython/micropython-lib/commit/c1f553eab9fd740dcea4adfe404dc24584ef2ab0#commitcomment-98855835 the top-level Makefile shouldn't default the manifest until after including mpconfigboard.mk. That's how it works on other ports.

**Comment by jimmo** [comment]
> @dpgeorge Quite a few formatting error messages in Python code that was NOT changed. So it seems that the black profile or version has changed.

Yep. See https://github.com/micropython/micropython/pull/10639

**Comment by dpgeorge** [comment]
I actually just went the other way in fe2a8332ff9c7cc7b66ed6da04f5a4a825309818 to fix a build error on stm32.  So IMO keeping it as `?=` is the right thing.

**Comment by robert-hh** [comment]
When changing, I looked how it was done at the STM32, before you changed it again.

**Comment by robert-hh** [comment]
So instead, I moved a line in Makefile.

**Comment by robert-hh** [comment]
Fixed the build errors. Code formatting is fine now again with the change to black v23.x.

**Comment by dpgeorge** [comment]
Thanks!

**Pull request merged**
