### PR TITLE
extmod/mbedtls: Enable modern cipher suites

### PR DESCRIPTION
**Pull request by sylvinus**
Following the comments in https://github.com/micropython/micropython/issues/14204#issuecomment-2024366349 and https://github.com/micropython/micropython/issues/10485#issuecomment-1396426824 , I've run some tests on the [top 500 domains from moz.com](https://moz.com/top500).

Without this patch, 155 out of 500 fail to connect because of TLS issues. This patch fixes them all!

One of the suites it enables is TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, which is actually required by hosts like bloomberg.com for TLS1.2:
https://www.ssllabs.com/ssltest/analyze.html?d=bloomberg.com&s=15.197.146.156&hideResults=on&ignoreMismatch=on

I tried disabling some other flags but it seems all of them are needed to get good coverage of those top 500 domains.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution!  Very nice to see your approach of testing the top 500 domains.

Although code size will increase quite a lot with these additional ciphers, I think it's unavoidable.  MicroPython needs to be able to talk to sites on the internet.

Also, the rp2 port already enables both of these options, so this PR brings all ports together to have the same mbedtls options enabled.

Can you please then remove the two now-redundant `#define` lines from `ports/rp2/mbedtls/mbedtls_config_port.h`?

**Comment by dpgeorge** [comment]
> Can you please then remove the two now-redundant `#define` lines from `ports/rp2/mbedtls/mbedtls_config_port.h`?

I have now done this.

I also updated the `ssl_poll.py` test so it works again, by regenerating the key/cert with a higher number of bits.

**Comment by dave4jr** [comment]
@dpgeorge Hi Damien, sorry to ask here but can't find it elsewhere. I need this update on the ESP32 so I can send using HTTPS to our external API. How can I load the nightly or this master branch onto the ESP32? I downloaded it but it's 10mb whereas the 1.23 release is much larger (I believe without submodules). Will that mean I will be losing out on having key functionality / other modules if i load up from master directly? Any help would be super appreciated! Thank you!

**Comment by dpgeorge** [comment]
> I need this update on the ESP32 so I can send using HTTPS to our external API.

@dave4jr The ESP32 port uses a different configuration to this PR.  The ESP32 already had these mbedTLS options enabled for some time, so release v1.23.0 should already be able to access HTTPS sites using these ciphers.

**Comment by dave4jr** [comment]
Ahhh okay cool.. Thank you very much for the quick response @dpgeorge !

**Pull request merged**
