### PR TITLE
stm32/af_pin_speed: Increase pin speed setting on sdcard and sdram

### PR DESCRIPTION
**Pull request by andrewleech**
Currently all usages `mp_hal_pin_config_alt_static()` set the pin speed to "high" (50Mhz)
This commit adds `mp_hal_pin_config_alt_static_speed()` which also allows setting the pin speed.

On stm32f series chip the sdcard can run up to 50Mhz and has shown instability for us on some boards with certain sd cards without the pin speed being increased to "very high".
The SDRAM also runs much faster than this so should also be set to the maximum pin speed.

Turns out I independently ran into the issue dealt with in https://github.com/micropython/micropython/commit/86f06d6a874d4eb3d6c50deec0240942344c01ea with serious corruption and transfer errors to some sd cards. 
I missed that commit (we're pinned a few weeks behind master currently) and I seem to have resolved the errors for us by adjusting the pin speed setting rather than reducing the overall peripheral speed.
As such this PR reverts 86f06d6a874d4eb3d6c50deec0240942344c01ea in favor of the pin speed change, which is also applied to the sdram interface

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for this.  I agree it makes sense to increase the GPIO speed to very-high.  But I'm not sure about making the SD card clock run at maximum speed (48MHz).  I just quickly tried this GPIO speed fix with an SD card that I have that was giving issues at 48MHz, and it still has issues.  It's a little better now, sometimes it can be mounted, but the directory listing is corrupt, and doing a more sophisticated read-block test (using SHA256 to hash blocks and then check them on subsequent reads) fails consistently.  I think this SD card I have simply cannot do above the "standard" 25MHz.

Perhaps there should be an option (compile time?) to enable maximum speed if the user knows they have good SD cards?

**Comment by andrewleech** [comment]
yep directory listing corruption was a big thing I was seeing too. This change fixed it for me on cards that would reliably fail when copying a large file dir (with mprepl).

Shame but good to hear the same fix doesn't work for you, I'll replace my change with yours (aka move my micropython pin up) if it's showing to be more reliable.

I doubt it's a case of your card being bad, as the ones initially giving me trouble were brand new sandisk ultra 16gb class 10 cards. We got a few and they all behave the same, while some other samsung ones I've got are fine. 
This is a UHS-I card which is rated for 100 Mhz with 10MB/s write speed.
https://en.wikipedia.org/wiki/SD_card#Bus

This means either the pc board layout or the chips peripheral is somewhat out of spec. 

Do you have external pull-up resistors on the lines (we don't). I've read recommendations to fit them and not rely on internal pull-ups, but oh well, too late now for this board.

**Comment by dpgeorge** [comment]
> Do you have external pull-up resistors on the lines (we don't)

No, not on any of the boards I tested.

For this PR I suggest to keep the new alt-static-speed helper function, and also the changes to sdram.c, but none of the other changes.

**Comment by andrewleech** [comment]
I'd be interested in testing with external pull-ups to see if that also fixes the issue, but it's just as likely to be a electrical layout issue. 

I didn't see this issue until our second board design which does have longer traces to the sd card, so it's quite likely that's involved. The traces aren't as perfectly matched in length too, which will impact a high speed interface. Keeping the speed lower is a safer option.

Either way, I've reworked this commit to only touch the sdram as suggested, that should be a safe and sensible change!

**Comment by dpgeorge** [comment]
Thanks for updating, merged in 8ed4a28dae80fb369ceee5ab81fb5302a8a09050

**Pull request closed without merging**
