### PR TITLE
unix/unix_mphal: Raise KeyboardInterrupt straight from signal handler.

### PR DESCRIPTION
**Pull request by pfalcon**
POSIX doesn't guarantee something like that to work, but it works on any
system with careful signal implementation. Roughly, the requirement is
that signal handler is executed in the context of the process, its main
thread, etc. This is true for Linux.

### CODE REVIEW

**Comment by pfalcon** [comment]
So, this is the most efficient solution for #1722, which is however not guaranteed to work on any OS. This needs to be tested on MacOSX and FreeDOS. As patch, there's going to be provision for old behavior anyway, suggestion for config var name are welcome. (Note that it will select either efficient async raising of KeyboardInterrupt, or caching it like before and them polling at various points of code, which is yet to be implemented).

**Comment by pfalcon** [comment]
@blmorris , @Anton-2, @pohmelie : Please help test this patch on your OSes.

**Comment by pohmelie** [comment]
@pfalcon, what test should we do? Ctrl-c on repl? Or sys.stdin… from linked issue?

**Comment by pfalcon** [comment]
@pohmelie : Yes, cases quickly described in https://github.com/micropython/micropython/commit/2195046365c661551c30d4156cecafa603214375#commitcomment-15080573 . Let me know if something is unclear there, I'll write up detailed test script.

**Comment by Anton-2** [comment]
Rock solid on OS X (10.11.3 beta, clang-700.1.81). Tried 64 an 32 bit build, on repl and executing scripts, during syscall and busy loops.
Got a  KeyboardInterrupt each time, even on repeated Ctrl-C.

**Comment by pfalcon** [comment]
@Anton-2 : Great, thanks!

**Comment by pohmelie** [comment]
@pfalcon 
Almost all cases are ok. Except executing script with sys.stdin.read(1). There is no KeyboardInterrupt until I press *enter*. Also, if I try ctrl-c in repl it looks like it actually do *enter*, even on unix build.
``` python
$ ./micropython
MicroPython v1.4.5-654-g37f414f on 2015-12-21; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> 
>>> 
>>> fooTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'foo' is not defined
>>> 
```

**Comment by pfalcon** [comment]
> Also, 

Worth a separate bugreport: https://github.com/micropython/micropython/issues/1742

**Comment by pfalcon** [comment]
> Except executing script with sys.stdin.read(1). There is no KeyboardInterrupt until I press enter. 

Let's go step by step:

~~~
$ cat kbdintr1.py 
import sys
sys.stdin.read(1)
$ micropython kbdintr1.py 
^CTraceback (most recent call last):
  File "kbdintr1.py", line 2, in <module>
KeyboardInterrupt: 
~~~

I pressed just Ctrl+C above. Do you say that with djgpp build, pressing Ctrl+C doesn't have any effect, only when you make .read() to return (by finishing line input by pressing Enter), only then traceback with KeyboardInterrupt is printed? It's hard to explain such behavior, especially if it works as expected in REPL.

**Comment by dpgeorge** [comment]
If this patch does actually work then I'd say go for it!  It's nice and efficient.

**Comment by pfalcon** [comment]
Anyway, I'm merging this, as it's proven to work on MacOSX. I added config setting to enable this feature, it's off by default, by on for unix port. @pohmelie , if you think that freedos is better of without, please submit a patch to override it in mpconfigport_freedos.h

**Comment by pohmelie** [comment]
@pfalcon 
Yes, your "step by step" and result is right. I'm also don't know why this is possible. And I think it's ok to leave this as is right now.

**Pull request closed without merging**
