### PR TITLE
stm32: add NadHAT PYBF405 board support (v2)

### PR DESCRIPTION
**Pull request by dpgeorge**
Cleaned up version of #5124 to make `ports/stm32/accel.c` more generic.

### CODE REVIEW

**Comment by dpgeorge** [comment]
@garatronic can you please test this on your board to see that it still works correctly?

Also, what is the name of the board?  The directory you added is `NADHAT_PYBF405`, but `MICROPY_HW_BOARD_NAME` is just `PYBF405`.  It would be good to make them match, and also not cause confusing with the actual PYBv1.x boards.

**Comment by garatronic** [comment]
I'll do the tests and changes. Thanks.
I deleted my last commit (i wanted to remove the useless conditional index, zero can be divided by everything.. but zero Hope this will not affect this git.

**Comment by garatronic** [comment]
The code work fine. I don't understand why, but my compiler do not like line 237
`CC accel.c
accel.c: In function 'pyb_accel_filtered_xyz':
accel.c:237:5: error: variable-sized object may not be initialized
     uint8_t data[DATA_SIZE] = { ACCEL_REG_X };
     ^~~~~~~
accel.c:73:37: error: excess elements in array initializer [-Werror]
 #define ACCEL_REG_X                 0x07 // XOUT_H
                                     ^
accel.c:237:33: note: in expansion of macro 'ACCEL_REG_X'
     uint8_t data[DATA_SIZE] = { ACCEL_REG_X };
                                 ^~~~~~~~~~~
accel.c:73:37: note: (near initialization for 'data')
 #define ACCEL_REG_X                 0x07 // XOUT_H
                                     ^
accel.c:237:33: note: in expansion of macro 'ACCEL_REG_X'
     uint8_t data[DATA_SIZE] = { ACCEL_REG_X };
                                 ^~~~~~~~~~~
cc1: all warnings being treated as errors`
I update my compiler to the lastest version : from 7.2_2017q4 to 8-2019-q3. Same error.
So i split the declaration and initialization of the array.
I change the range of KXT accelerometer to +/- 8G to have something working with xyz_filtering method. All work in that case. Also changed board name. Pull all in one commit on my deposit. 
Hope it will be the good one.

**Comment by dpgeorge** [comment]
> So i split the declaration and initialization of the array.

Ok, thanks, that change has been incorporated.

> I change the range of KXT accelerometer to +/- 8G to have something working with xyz_filtering method. All work in that case. Also changed board name.

I also incorporated these changes.  Thanks for testing!

**Comment by garatronic** [comment]
I tested from scratch and it work ... perfectly. 
Many thanks. 


De: "Damien George" <notifications@github.com> 
À: "micropython/micropython" <micropython@noreply.github.com> 
Cc: "Garatronic" <github@garatronic.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Vendredi 18 Octobre 2019 03:00:51 
Objet: Re: [micropython/micropython] stm32: add NadHAT PYBF405 board support (v2) (#5217) 





So i split the declaration and initialization of the array. 



Ok, thanks, that change has been incorporated. 
BQ_BEGIN


I change the range of KXT accelerometer to +/- 8G to have something working with xyz_filtering method. All work in that case. Also changed board name. 
BQ_END


I also incorporated these changes. Thanks for testing!

**Pull request merged**
