### PR TITLE
cc3200: Bindings for FreeRTOS task list and heap

### PR DESCRIPTION
**Pull request by mattande**
I'd like to suggest that any port with FreeRTOS should have a method for displaying the task list and heap information for debugging. While this is sort of available currently using `pyb.info()`, this function is specific to the cc3200 port and data is printed to stdout using `printf()` instead of returned to the python environment. Since the cc3200 is the only port with FreeRTOS currently in the repository, I suggest these changes here. Note that I don't have this hardware so I am unable to test this patch exactly, but it has been checked on my hardware.

This change adds two methods: `pyb.tasks()` and `pyb.heap()`. `pyb.tasks()` is available only when compiled with `DEBUG` to be consistent with the current implementation of `pyb.info()` - but I would suggest that it can be made available in a release build as well.

`pyb.tasks()` returns a list of 7-tuple containing the task name, TCB address (Task handle), current state, base priority, current priority, run time count and free stack low water mark for each task.

Using a python function similar to below, a developer can get a friendly task list:

```
def i():
  print("    Name       TCB    St Prio     Time   Stack")
  print("----------------------------------------------")
  for t in pyb.tasks():
     print("%9s  0x%08x  %c  %u %u  %8u   %u" % t)
```

Output:

```
>>> def i():
...   print("    Name       TCB    St Prio     Time   Stack")
...   print("----------------------------------------------")
...   for t in pyb.tasks():
...      print("%9s  0x%08x  %c  %u %u  %8u   %u" % t)
...
>>> i
<function i at 0x10001060>
>>> i()
    Name       TCB    St Prio     Time   Stack
----------------------------------------------
       MP  0x20006820  R  1 1    375197   2692
     IDLE  0x20005f28  R  0 0    774177   109
backgroun  0x200056a8  B  1 1    364663   179
    tcpip  0x20003c58  B  5 5     51238   110
 MPTelnet  0x20009ca0  B  2 2    691852   149
     http  0x200044d8  B  4 4     12513   31
   eth_rx  0x2000a830  B  5 5      7318   45
      i2c  0x200035a8  B  7 7    300996   29
  control  0x20004e28  B  6 6        61   92
      log  0x20001bf8  B  1 1        49   217
      nvm  0x20002a60  B  3 3      8704   157
>>>
```

`pyb.heap()` returns a 3-tuple, with the configured heap size, currently free heap size, and min ever encountered heap free size:

```
>>> pyb.heap()
(71680, 29896, 29648)
```

### CODE REVIEW

**Comment by danicampora** [comment]
I like it! :-)

Just a couple of remarks:

1. Why the modifications to the FreeRTOS source? Is that something that is part of the newer releases of FreeRTOS or is it a hack?
2. I want to keep all this extra "C developer only" features only in debug mode, at least for the CC3200. This chip executes everything from RAM, so in release mode we want to have only what is absolutely needed. This information is not useful for the Python developer, they don't need to know about FreeRTOS or other things under the hood.

**Comment by ARMWorks** [comment]
This is the first I heard of using FreeRTOS and MicroPython. Where is the
most info on this? It interests me strangely!

**Comment by pfalcon** [comment]
> I'd like to suggest that any port with FreeRTOS should have

If you suggest that, then "pyb" is bad place for that information.

> pyb.heap() returns a 3-tuple, with the configured heap size, currently free heap size, and min ever

heap == "micropython heap". if that returns freertos heap info, it should not be called just "heap". And micropython has functions in "micropython" module (if enabled in build params) to return various heap info (that's beyond what's offered by standard "gc" module).

**Comment by mattande** [comment]
> Why the modifications to the FreeRTOS source?

The modification to FreeRTOS source is to enable building `uxTaskGetSystemState()` without having to fully enable `configUSE_TRACE_FACILITY`. We don't want to enable all of trace, since it is generally used with 3rd party tools, and requires you to define a bunch of other macro's specific to the trace function. Really all we want is the ability to read the system task state, which can function fully without   `configUSE_TRACE_FACILITY`. Yes its a modification to the FreeRTOS source. This change is not upstream.

> extra "C developer only" features only in debug mode

On the CC3200/WiPy port I agree. For others who will likely base their own FreeRTOS port on your CC3200 work, its handy to have easy access to task list and stack use. My statement about including it in non-debug was meant as, `pyb.tasks()` could be included in a release build, not that it should be for this port.

**Comment by mattande** [comment]
@pfalcon I've noticed that ports tend to add functions specific to their port to `pyb`. Adding this to `pyb` was not the best place if its meant to refer specifically to the PyBoard.

What about creating a `freertos` module, which could be built for any port that uses FreeRTOS? There may be other bindings which are useful on the console as well from a developer point of view.

**Comment by danicampora** [comment]
If you want to make this re-usable, then, like @pfalcon said, should be in a different place. I'll give it a thought.

**Comment by danicampora** [comment]
> What about creating a freertos module, which could be built for any port that uses FreeRTOS? There may be other bindings which are useful on the console as well from a developer point of view.

That sounds good to me.

**Comment by pfalcon** [comment]
> I've noticed that ports tend to add functions specific to their port to pyb

Yes, and we (maintainers of uPy) need to fight such practice, otherwise it all will be a mess to maintain, and we lose one of the biggest Python's pro's - portability.

> What about creating a freertos module, which could be built for any port that uses FreeRTOS?

If you don't want to try to fit that functionality into one of standard Python modules (your probably don't, because you may lose useful details), having "freertos" module would be right approach. But you should at least well understand who would be target audience of that module. For example, I know @danicampora does a lot of work to save as much flash as possible - to use for application-level stuff. I may imagine he won't be interested to enable it by default for WiPy. So, it will be a tool for advanced users (who will build it themselves). If that sounds good, then well, it's indeed a clean and productive approach.

**Comment by danicampora** [comment]
If you make it a freertos module then it's easy to choose where and when to use it. I'd go for that approach.

**Comment by mattande** [comment]
Thanks, I will withdraw this for the time being.

**Comment by dpgeorge** [comment]
A more general place would be the os module.  How would one find out the running processes on unix/windows with Python?

**Comment by dhylands** [comment]
Under linux, you would either open /proc and enumerate the files, or you would call out (using subprocess.Popen) to the ps command (and ps will open /proc and enumerate the files). From the google searching I've done, under windows, they seem to call out to a program called "tasklist".

ps also seems to be the osx way.

After discovering the above, I also stumbled on a module called psutil which has a bunch of very useful system related functions (psutil.pids(), psutils.process_iter(), etc).
https://pythonhosted.org/psutil/ and that supports a wide variety of OSes.

**Comment by dpgeorge** [comment]
Most of psutil is overkill for us, but it does have some nice functions that we are lacking: disk_usage (there's currently no (programatic) way to tell how much free space is on the flash or SD) and net_io_counters (I assume this will be useful for WiPy).

**Comment by chrismas9** [comment]
What about creating a  freertos  module, which could be built for any port that uses FreeRTOS? There may be other bindings which are useful on the console as well from a developer point of view.
    That sounds good to me.

It sounds as if this would be relevant to any RTOS, eg Chibios, If you chose a new module could I suggest a more generic name such as rtos?

**Comment by danicampora** [comment]
I agree that `psutil.disk_usage` and `psutil.net_io_counters` would be nice to have. We could also use something line `psutil.memory_info_ex` or `memory_maps` to display the information that  @mattande wants to make available with this PR. On the other hand, since there's no standard way of querying this information in Python, we might just choose and API that makes a better fit for a RTOS.

> It sounds as if this would be relevant to any RTOS, eg Chibios, If you chose a new module could I suggest a more generic name such as rtos?
Yes, a more generic name will be better.

**Pull request closed without merging**
