### PR TITLE
py/compile: De-duplicate constants in the compiler.

### PR DESCRIPTION
**Pull request by dpgeorge**
The recent rework of bytecode (to v6 of .mpy files) made constants global to a module (prior, each function had its own constant table).  That means the constant table for a module is shared among all functions/methods/etc within the module.

This PR add support to the compiler to de-duplicate constants in this module constant table.  That means if a constant is used more than once (eg `1.0` or `(None, None)`) then the same object is reused for all instances.

IMO this is a worthy change, but the code size increase can be rather big on certain ports:
```
   bare-arm:  +104 +0.181% 
minimal x86:  +679 +0.412% 
   unix x64:  +880 +0.168% [incl -32(data)]
unix nanbox:  +156 +0.034% 
      stm32:  -120 -0.030% PYBV10
     cc3200:   +64 +0.035% 
    esp8266:  -368 -0.053% GENERIC
      esp32:  -112 -0.007% GENERIC[incl -152(data)]
        nrf:   +76 +0.041% pca10040
        rp2:   -48 -0.009% PICO
       samd:   +60 +0.043% ADAFRUIT_ITSYBITSY_M4_EXPRESS
```
Ports that decrease size are benefiting from frozen code which now has de-duplicated constants.  Ports that increase size don't have (much/any) frozen code.

It might make sense to make this feature optional (after all it is just an optimisation), then code size can be kept under control for ports that don't need this feature.

### CODE REVIEW

**Comment by dpgeorge** [comment]
This is needed for #8548 to work properly.

**Comment by jimmo** [comment]
> Ports that decrease size are benefiting from frozen code which now has de-duplicated constants. Ports that increase size don't have (much/any) frozen code.

But just to clarify, this is a RAM saving for non-frozen code? (If so, it's definitely worth paying some amount of code size for that!)

**Comment by dpgeorge** [comment]
> But just to clarify, this is a RAM saving for non-frozen code?

Kind of... if you have some code like `print(1.0, 1.0)` then the parser will create two independent constants `1.0` and `1.0`.  The compiler will then (with this PR) notice they are the same and only put one of them in the constant table.  The bytecode will be `LOAD_GLOBAL print`, `LOAD_CONST 0`, `LOAD_CONST 0`, `CALL_FUNCTION`, ie the single constant is reused.  That does allow the second `1.0` to be reclaimed by the GC.  So in the end, yes, it saves RAM because only one of the `1.0`'s needs to stick around.  Also the constant table only has one entry instead of two, so saves a word.

**Comment by dpgeorge** [comment]
I updated this PR to slightly optimise for code size, by reordering elements in the compiler's struct, which helps on some archs like x86 (the compiler's struct is rather large and accessing elements towards the end is expensive in terms of generated machine code).

Code size diff is now (this PR relative to master):
```
   bare-arm:  +120 +0.209% 
minimal x86:  +293 +0.178% 
   unix x64:  +256 +0.049% [incl -32(data)]
unix nanbox:  +412 +0.089% 
      stm32:   -44 -0.011% PYBV10
     cc3200:  +112 +0.061% 
    esp8266:  -772 -0.111% GENERIC
      esp32:  -636 -0.042% GENERIC[incl -96(data)]
        nrf:   +92 +0.050% pca10040
        rp2:   +32 +0.006% PICO
       samd:  +112 +0.080% ADAFRUIT_ITSYBITSY_M4_EXPRESS
```
I think that's much more acceptable.  It's a good feature and not easy to make it configurable/optional.

**Pull request merged**
