### PR TITLE
Add objfloaf.h

### PR DESCRIPTION
**Pull request by IhorNehrutsa**
I need objfloat.h in the future

### CODE REVIEW

**Comment by dpgeorge** [comment]
This is intentionally not exposed, because float objects can have different representations and the struct is not always the right way to make a float.

**Comment by dpgeorge** [comment]
> I need objfloat.h in the future

Can you describe how you would use this?

**Comment by IhorNehrutsa** [comment]
Thanks, Damien.
I am developing https://github.com/IhorNehrutsa/micropython-extmod-generator
I want to have module constants.

This Python code should produce
```
...
# These UPPERCASE Python variables are treated as constants in C code
CONST_NONE = None
CONST_INT = 1 + 1
ONE_BOOL = True
CONST_STR = "333" + '444'
CONST_FLOAT = 2.2 * 2.2
...
```
C code for external C module for MicroPython
```
...
STATIC const MP_DEFINE_FLOAT_OBJ(CONST_FLOAT_float_obj, 4.840000000000001);
...
// Set up the module properties
STATIC const mp_rom_map_elem_t example_globals_table[] = {
...
    { MP_ROM_QSTR(MP_QSTR_CONST_NONE), MP_ROM_NONE },
    { MP_ROM_QSTR(MP_QSTR_CONST_INT), MP_ROM_INT(2) },
    { MP_ROM_QSTR(MP_QSTR_ONE_BOOL), MP_ROM_TRUE },
    { MP_ROM_QSTR(MP_QSTR_CONST_STR), MP_ROM_PTR(&CONST_STR_str_obj) },

I am not sure here
    { MP_ROM_QSTR(MP_QSTR_CONST_FLOAT), MP_ROM_PTR(&CONST_FLOAT_float_obj) },
or
    { MP_ROM_QSTR(MP_QSTR_CONST_FLOAT), MP_ROM_FLOAT(4.84) },
or
    { MP_ROM_QSTR(MP_QSTR_CONST_FLOAT), something else},
...
```
Could you give the cue about the MP_ROM_FLOAT?

**Comment by dpgeorge** [comment]
Ok, I understand the use case.

Constant float objects are rarely used, but there are 2 examples: `math.pi` and `math.e`.  There are 3 different ways to define them depending on the object representation:
```
// repr A, B
#define mp_const_float_e MP_ROM_PTR(&mp_const_float_e_obj)
const mp_obj_float_t mp_const_float_e_obj = {{&mp_type_float}, (mp_float_t)M_E};

// repr C
#define mp_const_float_e MP_ROM_PTR((mp_obj_t)(((0x402df854 & ~3) | 2) + 0x80800000))

// repr D
#define mp_const_float_e {((mp_obj_t)((uint64_t)0x4005bf0a8b145769 + 0x8004000000000000))}
```
It's not really easy to do it for all cases.  Best way would be to just copy the code it `tools/mpy-tool.py` lines 361-373.

**Comment by jimmo** [comment]
As per @dpgeorge 's comment above, this needs to work for all representations.

**Pull request closed without merging**
