### PR TITLE
drivers/nRF24L01: Updated for ESP8266 with machine/SPI syntax

### PR DESCRIPTION
**Pull request by mcauser**
Works between two of my WeMos D1 Minis, each running MicroPython v1.8.6-204-gde9cd00

img_8333

nrftop

WeMos D1 Mini | nRF24L01+
------------- | -----------
D4 GPIO2      | CE
D5 GPIO14     | SCK
D6 GPIO12     | MISO
D7 GPIO13     | MOSI
D8 GPIO15     | CSN
GND           | GND
3V3           | VCC
N/C           | IRQ

Copy `/drivers/nrf24l01/esp8266/*.py` into `/esp8266/modules/`
`cd esp8266`
`make clean && make axtls && make deploy`

On slave device:
```
>>> import nrf24l01test
>>> nrf24l01test.slave()
```

On master device:
```
>>> import nrf24l01test
>>> nrf24l01test.master()
```

### CODE REVIEW

**Comment by deshipu** [comment]
See #2285 too.

**Comment by mcauser** [comment]
Closed in favour of almost identical changes #2285

**Comment by peterhinch** [comment]
The current test/example program nrf24l01test.py uses the pyb module and hence is not portable. Would it not be worthwhile to replace it with this portable one?

**Comment by dpgeorge** [comment]
> Would it not be worthwhile to replace it with this portable one?

Yes that's a good idea, but the one here is not 100% portable because it relies on specific pins of the ESP8266.

In 54acd0b0f050a99e9a5472b8d54cc729a60c3bc8 I made the test script use utime and machine modules to make it more portable.  Feel free to submit a PR to make it run on both pyboard and esp8266.

**Comment by peterhinch** [comment]
Please see #3366 for discussion of a portable solution.

**Pull request closed without merging**
