### PR TITLE
Fixes for makeqstrdefs.py getting broken by "clean" on cmake

### PR DESCRIPTION
**Pull request by xyzzy42**
Using "clean" with the cmake build leaves the build directory in a broken state, due to stale makeqstrdefs.py hash files.

This fixes the cmake issue that the hash files are not deleted on a clean when they should be.

makeqstrdefs.py is also updated so that stale hash files left behind with the output is deleted will not prevent generation of the output.  While cmake + clean will not do this anymore, it could still happen for other reasons.  I've found a good goal for a robust build system is that any generated file can be deleted and it will correctly cope with this.

### CODE REVIEW

**Comment by xyzzy42** [comment]
I noticed that makeqstrdefs is writing the output to a file named always `out`, then renames this to the real output file.  But only when it's changed, otherwise the `out` file is just left there.  Any reason for this?

I know that file rename is the standard way to atomically update a file on POSIX systems.  But what reason does this update have to be atomic?  Any parallel build operation that tried to depend on that to fix a race would still be broken as it could get the old output file before the atomic update.

Also using intermediate files with fixed names is problematic as parallel builds of different outputs might still use the same intermediate file and clobber each other.

**Comment by dpgeorge** [comment]
> I noticed that makeqstrdefs is writing the output to a file named always `out`, then renames this to the real output file. But only when it's changed, otherwise the `out` file is just left there. Any reason for this?

I think it's so that make only sees a changed file (date/time stamp changed) if there were any change to the contents.  Otherwise, if it were always renamed, all files would be recompiled if any other file changed (everything would depend on everything else).

But it would probably be a good idea to remove the `out` file if it weren't renamed.  That bit can be fixed.

> Any parallel build operation that tried to depend on that to fix a race would still be broken as it could get the old output file before the atomic update.

This preprocessing stage does not run in parallel, so it should be OK as-is.

> Also using intermediate files with fixed names is problematic as parallel builds of different outputs might still use the same intermediate file and clobber each other.

Yes, I agree there.  Could change that `out` name to be something more unique and related to the input file names used to create it.

**Comment by dpgeorge** [comment]
As for this PR itself, it looks good, thanks!  Rebased and merged.

**Comment by xyzzy42** [comment]
> I think it's so that make only sees a changed file (date/time stamp changed) if there were any change to the contents. Otherwise, if it were always renamed, all files would be recompiled if any other file changed (everything would depend on everything else).

What that's true about not changing the file's date if the contents don't change, the way the script works is to generate the new contents in memory and check a hash to see if it's changed from the existing file.  If they are the same, there was no need to write the `out` file in the first place.  And of course the need to name it goes it away if it's never made.

**Comment by dpgeorge** [comment]
Aah, I see what you're saying.  You are right that the `out` file never needs to exist.  The hashing is done on the in-memory copy of the contents, and only if that hash is different (or the output file not exist) does anything need to be written to disk.

There doesn't need to be any atomicity with this file when it's being created.

Would you like to make a PR to clean that up?

**Comment by dpgeorge** [comment]
For reference, see c618f91e22613b2e530f7c21be0be789a7e8eed5 where this `out` code was added.

**Pull request merged**
