### PR TITLE
stm32/rfcore: Intercept addr-resolution HCI cmd to work around BLE bug.

### PR DESCRIPTION
**Pull request by dpgeorge**
The STM32WB has a problem when address resolution is enabled: under certain
conditions the MCU can get into a state where it draws an additional 10mA
or so and eventually ends up with a broken BLE RX path in the silicon.  A
simple way to reproduce this is to enable address resolution (which is the
default for NimBLE) and start the device advertising.  If there is enough
BLE activity in the vicinity then the device will at some point enter the
bad state and, if left long enough, will have permanent BLE RX damage.

The only known workaround at this stage is to not enable address
resolution.  That is done here by intercepting any command that enables
address resolution and convert it into a command that disables address
resolution.

Work done in collaboration with @jimmo.

### CODE REVIEW

**Comment by andrewleech** [comment]
What's the end user impact of not having address resolution enabled?

**Comment by dpgeorge** [comment]
> What's the end user impact of not having address resolution enabled?

AFAIK, bonding will not work with devices that have an RPA (resolvable private address).

**Comment by andrewleech** [comment]
Ah right, I was wondering if that was the kind address resolution in question. So, this would basically make the WB55 the same as the pybd in this regard.

**Comment by dpgeorge** [comment]
> So, this would basically make the WB55 the same as the pybd in this regard.

Exactly.

**Comment by dpgeorge** [comment]
Note that this bug took about 7 weeks to track down.  ST are aware of the issue.

**Pull request merged**
