### PR TITLE
Struct doc fix

### PR DESCRIPTION
**Pull request by sponster-au**
Update struct docs, fix environment variable handling in doc Makefile.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Note that there is already a good place to put "differences to CPython", but it's not in docs, rather in tests: `tests/cpydiff/module_struct_*.py`.  So I think for the case here it'd be good to create another file in `tests/cpydiff` describing this difference with whitespace not accepted by MicroPython.

**Comment by sponster-au** [comment]
I'm not sure why you say the docs aren't a good place to put "differences to CPython" - there are 18 other library sub-sections that include CPython differences in the docs.

As a user, if I was investigating why a format string that worked in CPython threw an exception in micropython, I'd look in the online docs, not the source.

I'll add a test to `tests/cpydiff/module_struct_whitespace_in_format.py` to be consistent.

**Comment by sponster-au** [comment]
I notice that the tests in `tests/cpydiff` often won't pass, even if the feature was added, because the relevant module has a different name under micropython.

For example, if `ustruct.pack()` was updated to throw an exception if too many arguments are provided, the test would still fail because `import struct` fails in micropython.

Would it be useful to update the tests to have the dual `struct/ustruct as struct` import?

**Comment by dpgeorge** [comment]
> I'm not sure why you say the docs aren't a good place to put "differences to CPython" - there are 18 other library sub-sections that include CPython differences in the docs.
> 
> As a user, if I was investigating why a format string that worked in CPython threw an exception in micropython, I'd look in the online docs, not the source.

Sorry I didn't make it clear that these cpydiff tests actually auto-generate associated docs that appear here: http://docs.micropython.org/en/latest/genrst/index.html

The other admonitions in the docs describe subtle (or not so subtle) behavioural differences between uPy and CPy.  I agree it's not 100% black and white where such differences should be documented (in the special cpydiff section, or inline in the module), but at least the case here really does match what's already documented as differences in cpydiff.

**Comment by dpgeorge** [comment]
The struct alignment issue was fixed in 1022f9cc35564b216a4bcd7c65e8243c810a0ca9

**Comment by dpgeorge** [comment]
Docs changes are squashed and merged in c1f74b300548912f92edb4ae004dc486e0b7c8bf (with spelling fixes).

**Pull request closed without merging**
