### PR TITLE
docs: Explicitly specify behavior of UART stream protocol methods on timeout.

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by pfalcon** [comment]
This document changes recently made to stmhal and otherwise follow Python stream protocol.

**Comment by danicampora** [comment]
Thanks!

**Comment by pfalcon** [comment]
@danicampora : I hope you'll check that wipy conforms to this behavior!

**Comment by danicampora** [comment]
@pfalcon It does, check test/wipy/uart.py ;-)

**Comment by pfalcon** [comment]
Cool, thanks!

**Comment by pfalcon** [comment]
Ok, as both pyboard and wipy work like that, merging this.

**Pull request closed without merging**
