### PR TITLE
modmachine: Implement physical memory access using /dev/mem (Linux, etc.)

### PR DESCRIPTION
**Pull request by pfalcon**
This requires root access. And on recent Linux kernels, with
CONFIG_STRICT_DEVMEM option enabled, only address ranges listed in
/proc/iomem can be accessed. The above compiled-time option can be
however overriden with boot-time option "iomem=relaxed".

This also removed separate read/write paths - there unlikely would
be a case when they're different.

### CODE REVIEW

**Comment by pfalcon** [comment]
This finally implements intended semantics of machine.mem* to access *physical* memory on linux.

**Comment by dpgeorge** [comment]
This seems very ad-hoc to provide a feature that likely no-one will use.  Do you have a use case?

**Comment by pfalcon** [comment]
> This seems very ad-hoc to provide a feature that likely no-one will use. Do you have a use case?

"This" - what? This has the same usecase is mem* in stmhal. E.g. accessing hardware registers.

**Comment by dpgeorge** [comment]
That something very generic (read/write mem using pointers) must instead have a very specific implementation that'll only work on *nix.  And now MICROPY_PLAT_DEV_MEM must be defined to 0 for all other ports.

Will anyone write an, eg, VGA driver in uPy?  And how will it not clash with the OS's driver?  If you want to write an OS with uPy then you'd anyway have access to the physical memory through the page table using normal pointers.

**Comment by dhylands** [comment]
This method does clash with the OS's drivers (when such drives exist), but it is popular nonetheless.

Like anything, this is a footgun that if used properly allows things to be done which would otherwise require writing a kernel driver (which even C programmers are often reluctant to do). Used improperly, you can crash your machine (just like with stm.memXx).

This is really just semantic sugar hiding file I/O

**Comment by pfalcon** [comment]
> That something very generic (read/write mem using pointers) must instead have a very specific implementation that'll only work on *nix.

Why suddenly, if we have generic interface for that stuff?

> And now MICROPY_PLAT_DEV_MEM must be defined to 0 for all other ports.

Same concern can be applied to other settings. Well, we can switch to #ifdef here.

> Will anyone write an, eg, VGA driver in uPy?

Yes, for VGA, and for bunch of other stuff. Moreover, if someone already wrote a driver using machine.mem*, it will just work.

> And how will it not clash with the OS's driver?

So, it's "OS" which makes you have all those concerns? But who cares about OS? There's no big difference between embedded hardware whether it runs "bare metal" or "under OS". Treat OS as a bootloader for micropython, possibly with some added features like file system (strictly optional). Regarding "OS driver", there can be anything about it, and most likely case is that it doesn't exist, and that's the reason why somebody wants to play with hardware in uPy.

>  If you want to write an OS with uPy then you'd anyway have access to the physical memory through the page table using normal pointers.

Few people want to write a complete OS in Python - would be nice, but too much effort. But many enough people want to: 1) learn embedded programming whether their board run Linux or not; 2) do an exploration/investigation into (unknown/unsupported) hardware; 3) write a driver just for hardware piece they care, leave the rest to "OS".


I particularly pay attention to 2) usecase. That's essentially why I put up with mem*[addr] interface which I didn't like initially - it's not exactly formal, but very pragmatic, especially to use interactively. I want uPy to be good tool for system bring up/exploration, and this is just small piece of the puzzle. Another piece is being discussed in #1368 - even without any FS and connectivity, people should be able to just paste in i2c/spi/pcix/whatever scanner or dumper and run it (complete, not "function by function").

**Comment by dpgeorge** [comment]
> That something very generic (read/write mem using pointers) must instead have a very specific implementation that'll only work on *nix.
> 
> Why suddenly, if we have generic interface for that stuff?

Well, ok.  But usually for platform specific things we leave that to the platform to define (eg file builtin).  For example we could require a given port to provide a mod_machine_get_addr() function if it wants to implement the machine module, and then extmod/modmachine.c contains only generic stuff.  I would say this is preferred to the way done in this PR.  For example it allows anyone else with their own port to easily add machine mem access without changing a file in the core repo.  [In fact this way stmhal could even use modmachine.]

> Well, we can switch to #ifdef here.

Or `#if defined(X) && X`.  But if we go with proposal above to make get_addr() provided by a port then it's not needed.

> Treat OS as a bootloader for micropython, possibly with some added features like file system (strictly optional).

But this patch requires a filesystem to work!  Well, anyway, I understand your point.

> I want uPy to be good tool for system bring up/exploration

Ok, I see the point.

**Comment by pfalcon** [comment]
> Well, ok. But usually for platform specific things we leave that to the platform to define (eg file builtin).

Yes, but unfortunately that doesn't scale to all usages.

> For example we could require a given port to provide a mod_machine_get_addr()

And where would it belong? To "HAL"? But then common case is identity mapping, which calls to have a define, then apparently in mpconfigport.h. That's already half-step to MICROPY_PLAT_DEV_MEM. Another half-step is that I initially wrote Linux mapping code as a separate code and with globals, bit then I just saw that it can use static vars and be inlined right away. Saves some bytes and cycles.

Overall, I proposed to have extmod/ exactly to have alternative/more relaxed integration rules and don't feel bad about it. And MICROPY_PLAT_DEV_MEM is there exactly to let people patch port's mpconfigport.h instead of modmachine.c, I could have added `#ifdef __linux__` to the latter instead.

> For example it allows anyone else with their own port to easily add machine mem access without changing a file in the core repo. [In fact this way stmhal could even use modmachine.]

It could stop being over-protective and use it right away, or it can be handled as separate patch later.

**Comment by dpgeorge** [comment]
> And where would it belong? To "HAL"?

Just like file, stdin, stdout, stderr work, you define them and they link in correctly.

> But then common case is identity mapping, which calls to have a define, then apparently in mpconfigport.h

In mp-readline/readline.c we have a case of default VT100 commands, being overridden if you define the relevant macro.

So there are ways to do it.

> Overall, I proposed to have extmod/ exactly to have alternative/more relaxed integration rules

Right.  Well, how will it go when/if we start adding things like UART to mod machine?  How will each specific port implement its behaviour?

**Comment by dpgeorge** [comment]
Anyway, I'm probably being unduly contrary at this point :)

Still, we will need to decide how it will work when we want to implement machine.sleep/deepsleep/etc.  I'd rather not put all the implementations for different boards/ports/machines in one big file, or even in extmod/ at all.  Since implementations of, eg, deepsleep need intimate knowledge of the HAL for a given board it's best that such functionality goes in each port.

**Comment by pfalcon** [comment]
> Still, we will need to decide how it will work when we want to implement machine.sleep/deepsleep/etc.

I don't have immediate answer for this question. Previously, we mostly had a port implement something down from Python function/object, this is an attempt to not involve ports. In selected cases, we have "middleware API", like socket/network handlers. Apparently, we'll need to use this pattern more and design reusable HAL APIs, etc. But doing that requires actually implementing them, which comes at due time.

**Comment by pfalcon** [comment]
So, merging this.

**Pull request closed without merging**
