### PR TITLE
ESP8266: Fixed scan unable to discover hidden SSID problem

### PR DESCRIPTION
**Pull request by Adam5Wu**
Provide scan_config structure to enable discovery of hidden SSID.

### CODE REVIEW

**Comment by pfalcon** [comment]
Perhaps this should be an optional parameter to .scan().

**Comment by dpgeorge** [comment]
> Perhaps this should be an optional parameter to .scan().

Yes.  "Hidden" means they shouldn't be part of a scan, yet it would be a good feature to have, so a boolean argument to scan() to get hidden SSIDs would be good.

**Comment by Adam5Wu** [comment]
I am a bit concerned that adding an optional parameter will destroy network module API compatibility wrt. other MP ports. Posted a question in the forum but so far nobody replied.

Meanwhile, I went ahead and implemented it anyway. And while I update the documentation, I noticed that the networking API already wasn't quite uniform across ports, so I guess my concern is probably not much of an issue right now. :D

Improved code and commit message now in PR #2737.
Please have a look, and happy holidays~

**Comment by PsuFan** [comment]
Whats the status of this in v1.11? My ESP8266 lists no hidden WiFi networks. I don't see the hidden config code in latest code, and I don't see micropython documentation for optional parameter.

**Comment by dpgeorge** [comment]
> Whats the status of this in v1.11?

It was never merged.  This PR was superseded by #2737.

**Pull request closed without merging**
