### PR TITLE
travis: Switch unix stackless build to use clang.

### PR DESCRIPTION
**Pull request by dpgeorge**
To test a different compiler, other than gcc.

Also might be worth adding circleci as an additional CI to test Mac explicitly.

### CODE REVIEW

**Comment by pfalcon** [comment]
That doesn't look good. Stackless is quite a configuration on its own, and should be built with "standard" compiler. Clang should be a separate build target.

**Comment by dpgeorge** [comment]
> Stackless is quite a configuration on its own, and should be built with "standard" compiler.

The aim here is to keep the build time down.  We can't check all compilers with all configs.

**Comment by pfalcon** [comment]
Builds happen in parallel. Stackless is not the best feature to correlate with another one. Try nanbox or something.

**Comment by dpgeorge** [comment]
> Builds happen in parallel.

Only up to a limit, beyond that they are sequential.

> Stackless is not the best feature to correlate with another one. Try nanbox or something.

Stackless is pretty similar to non-stackless.  nanbox is a lot different.

**Comment by dlech** [comment]
> Also might be worth adding circleci as an additional CI to test Mac explicitly.

Why not use Travis for macOS? We should be able to add

```yml
os:
  - linux
  - osx
```

Then add `if: os = linux` to all of the jobs except the ones to build on Mac.

**Comment by dpgeorge** [comment]
> Why not use Travis for macOS?

Thanks for the hint, I just pushed a change with this to test it.  Still, I would like to also try CircleCI, maybe it will be faster and can run in parallel with Travis CI.

**Comment by dpgeorge** [comment]
I'm unable to get OSX working under Travis using the stages/jobs that are configured for this repo.  I guess it's possible, I just don't know how to do it.

So at this stage I propose to just switch unix stackless build to clang, and investigate OSX CI later on (CircleCI does offer free OSX builds for open source projects).

**Comment by hroncok** [comment]
JFYI `tests/stress/recursive_iternext.py: Increase large depth to 5000` also appears to fix a test failure with gcc 10.

**Comment by dpgeorge** [comment]
> JFYI `tests/stress/recursive_iternext.py: Increase large depth to 5000` also appears to fix a test failure with gcc 10.

Thanks, good to know.

**Pull request merged**
