### PR TITLE
WIP: tests/extmod/websocket: modwebsocket test coverage.

### PR DESCRIPTION
**Pull request by hosaka**
Starting draft for websocket tests.

### CODE REVIEW

**Comment by pfalcon** [comment]
Looks good for starters, but do you have an idea of any further steps?

**Comment by hosaka** [comment]
Hi Paul,

I actually don't, I wanted to open the PR, look at the affected coverage
and perhaps get some opinions on how this can be done. Of course the Unix
port being the main target for now.

I have experienced some problems with being dropped out of REPL, with
websocket and ussl.wrap_socket() as I described. So I guess I'll just poke
around and see what can be done.

In the meantime, please let me know any suggestions that you might have!

**Comment by dpgeorge** [comment]
The websocket code is hurting coverage so would be good to test it.  One idea to test it is to make a dummy socket to initialise it with, and the dummy socket just prints out the data it gets sent.  Then feed into the websocket some known bytes and make sure it produces the right output.

**Comment by hosaka** [comment]
I am getting a bit puzzled with testing the mask. If Damien or Paul can have a quick look and perhaps let me know if I'm doing things right. Apart from that, and a couple of stream errors, this should be good to go.

**Comment by pfalcon** [comment]
@hosaka : Backlogged as usual. It's great that you found way to test it. But what you did is integration test, not unit test. It requires external resource, network socket, and tests how websocket module works in integration with this external resource. Unit tests don't work like that, they test each unit of functionality in isolation, replacing any dependencies, and especially external resources, with mock objects.

Here's an example: https://github.com/micropython/micropython/blob/master/tests/extmod/btree1.py#L10 . As you can see, instead of using a real file in filesystem, and thus testing integration of DB and filesystem functionality, it tests solely DB, using mock object - in-memory file.

Test that you wrote is definitely a good start, but it's new kind of test. We either need to make them unit tests (apaprently, not possible right away), or setup separate structure for integration tests.

Sorry for (late) bad news. Well, I tried to drive discussion of *how* to do this testing, before doing it ;-).

**Comment by pfalcon** [comment]
> I am getting a bit puzzled with testing the mask. If Damien or Paul can have a quick look and perhaps let me know if I'm doing things right. Apart from that, and a couple of stream errors, this should be good to go.

I hope you're aware of https://github.com/micropython/micropython/issues/2410 . That ticket claims, without any specifics, that "websocket ... doesn't work as a client with most servers it seems." It's very easy to believe in, because websocket module was written to implement the needed subset of websocket functionality, not spend extra time on what's not needed with a queueful of what's-needed's.

So, you should first say what you're testing - the websocket module as it is, or websocket protocol as it should be. All those binary strings in your tests - where they come from?

**Comment by hosaka** [comment]
Hi Paul, thanks for your reply. I fully agree with you on current patch not
being a unit test, and going beyond minimal, while it could be viewed as a
waste of time, I didn't spend too much time on it and it gave me some
understanding of the protocol, so I'd be happy to work on top what I
learned.

I see your points on this having external dependency. As Damien mentioned,
having a dummy socket, rather than importing usocket, should be a better
solution, and I will try to add that in the next commits. Could that be a
class that implements stream read/write functions?

The binary strings I am using came from reading the websocket spec and
looking at the code itself, I think the states that I covered send small,
one case at a time, frames. Which is what i though would be desired, rather
than constructing longer messages.

I will pick this up again next week, make some small changes and will come
back to you.

Thanks for finding the time to answer, I appreciate your advice!

**Comment by pfalcon** [comment]
> while it could be viewed as a waste of time, I didn't spend too much time on it and it gave me some understanding of the protocol, so I'd be happy to work on top what I learned.

It's not a waste of time, it's very important and useful work, and I appreciate it very much by 2 reasons: a) because it's just important; b) because it's what suggested to contributors https://github.com/micropython/micropython/issues/1331, and I very much appreciate listening and actually picking up a task from there. Over all this time, only few (3 exactly) persons followed an advice of taking a task form there, and MicroPython would be much ahead if more people participated in coordinated (rather than multidirectional) effort. So again, thanks.

The point is - you've reached beyond the low-hanging fruit. You reached the point where to test more, one would need to develop more. And then first typical outcome - patches don't replace developer communication. With more complex tasks, discussions of what's and how's are required. So, you'd need to that now (after first patch), if you'd like to proceed (vs for example to let this specific testcase wait for some time).

> Could that be a class that implements stream read/write functions?

Nope, we don't have stream support up to such level. So, to implement *unit* test that's what you'd need to implement (among other possible choices). I'm not sure if you're interested in that. And the obvious drawback is that we'll likely have that feature enabled only for the coverage build (in other words, if you implement that, that will benefit MicroPython testing coverage, but not MicroPython in general). Let us know if you're interested.

> The binary strings I am using came from reading the websocket spec and looking at the code itself

Let me say that this is very laborious process. Well, websocket is a simple protocol, and following thru spec hopefully was (or will be) useful to you beyond just writing this test, but you don't want to repeat the same with SSL. I'd do as Damien suggested (and I interpret his words only in such way) - try to capture an actual protocol exchange, and feed it into a unit (using mock objects) and capture response (using mock objects). This is more black-box approach, the caveat is that it never works as easy as that - there's always some internal state (random, literally, in case of SSL and even websocket partially (that mask thing)). At least it's top-down approach, where you look into internal stuff only when needed, not start with that ;-).

> Thanks for finding the time to answer, I appreciate your advice!

Thanks for your systematic effort on this. Please keep in mind there're different choices and approaches, e.g. if you hit a hard thing, you can pause and look for some other more low-hanging fruit, and in general, having *some* coverage where there was *none* is already big progress, there's no need to have as much as possible coverage all at once.

**Comment by hosaka** [comment]
Apologies for not having enough time to proceed with this, but I will pick this up again some time after the new year, I have read all your comments Paul and taken it all in, thank you. I have started another draft using BytesIO and will push this next.

**Comment by dpgeorge** [comment]
@hosaka just wondering if you're planning on continuing with this?  If not I'll pick it up myself.

**Comment by hosaka** [comment]
@dpgeorge hey, sorry my fulltime job has been pretty busy lately, please feel free to do as you please!

**Comment by dpgeorge** [comment]
This was reworked to use only io.BytesIO() and merged in ce0b5e078b376dadcc33226647c91c73d6c73600.  Thanks @hosaka for the initial tests!

**Pull request closed without merging**
