### PR TITLE
Non-blocking implementation of WebREPL "GET_FILE" operation

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by pfalcon** [comment]
This PR is posted as a notice of upcoming non-compatible change. Once this is merged, webrepl_cli.py client from master won't work with MicroPython master. Working version is in "wip" branch: https://github.com/micropython/webrepl/tree/wip

**Comment by pfalcon** [comment]
webrepl.html side for updated and tested too, so I'm going to merge this shortly.

**Comment by dpgeorge** [comment]
It looks good, but I did not test it.  After you merge I can update micropython.org/webrepl webpage.

**Comment by pfalcon** [comment]
> After you merge I can update micropython.org/webrepl webpage.

I thought it's done automatically from master branch. Anyway, I guess we shouldn't do this until 1.8.3 release. So, micropython.org/webrepl and webrepl.git master are for the latest release, webrepl.git wip branch is for micropython master. It's not yet complicated, because micropython-lib master is for micropython master (while packages on PyPI is for the latest release). What's common for them all is that both webrepl.git and micropython-lib.git are tagged with the same version as the release of micropython they intended to work with (well, I've made first round of such tagging, and we should do it at the time of release).

**Comment by pfalcon** [comment]
Merged.

**Pull request closed without merging**
