### PR TITLE
logo/1bit-logo A black & white version of the logo

### PR DESCRIPTION
**Pull request by deshipu**
This version of the logo may be useful for displaying on small
devices to show that they use MicroPython.

### CODE REVIEW

**Comment by mcauser** [comment]
Spotted: http://hackaday.com/2016/07/29/esp8266-micropython-contest-gives-you-the-excuse-you-need/

**Comment by deshipu** [comment]
Right, I figured out I'd make it generally available.

**Comment by pfalcon** [comment]
To sort better and avoiding to be missed, I'd suggest to call this logo-bw.png or logo-1bit.png (I'm not sure if it's correct call a PNG image 1-bit).

**Comment by deshipu** [comment]
I tried to follow the existing naming convention -- most of the files here seem to be named according to a "format-logo" scheme (vector-logo, trans-logo, etc.).

As for calling a PNG image 1-bit, I can assure you that PNG supports a wide variety of image formats, including indexed and 1-bit images, and if you take a moment to examine this file, you will see that it is indeed a 1-bit image.

**Comment by pfalcon** [comment]
Sounds good. Merged, thanks.

**Pull request closed without merging**
