### PR TITLE
py/obj: Verify floating point type is correct for OBJ_REPR_C.

### PR DESCRIPTION
**Pull request by jimmo**
Prevents double-precision floats being enabled on 32-bit architectures where they will not fit into the mp_obj_t encoding.

Also reverts the Portenta board to the default representation as it uses double-precision floats.
@iabdalkader -- I'm not sure why the Portenta was set to OBJ_REPR_C, assuming to avoid heap-allocation of floats. If you want to keep that I guess we could switch the Portenta to use single-precision float instead?

### CODE REVIEW

**Comment by iabdalkader** [comment]
> I'm not sure why the Portenta was set to OBJ_REPR_C, assuming to avoid heap-allocation of floats

Yes, there's a longer discussion here: https://github.com/micropython/micropython/pull/8547#discussion_r853143893

We don't need double precision, but we do need `REPR_C`. Can you please instead set it to single precision ?

**Comment by iabdalkader** [comment]
@jimmo 

> Can you please instead set it to single precision ?

Actually I'm sending a PR to update the board config, will set it to single.

**Comment by jimmo** [comment]
OK sure thing. I've updated the branch, but can drop the commit later in the rebase if necessary.

**Comment by iabdalkader** [comment]
It's fixed here too along with misc small fixes https://github.com/micropython/micropython/pull/9657

**Comment by iabdalkader** [comment]
@dpgeorge Could you please merge this, because it includes a critical fix for Portenta board.

**Comment by dpgeorge** [comment]
Thanks, these patches look good.  Merged in b161abc574b8e4fb2b00ef76be2b9c8967e18584 and 5ee1cb27711d3747747db3ecd7b761c2a064addf

**Pull request closed without merging**
