### PR TITLE
Generalize binary operators parsing.

### PR DESCRIPTION
**Pull request by blazewicz**
This patch modifies parser and compiler so that all arithmetic and bitwise operators are processed through the same set of functions, therefore minimizing complexity and reducing code size.

Due to modification to grammar rules parsing of expressions with bitwise operator may use little bit more RAM because parser must generate additional parse nodes.

This patch brings some significant changes in code size:
bare arm: -180 B
minimal: -584 B
unix x64: -1080 B
stmhal: -196 B
esp8266: -348 B

I'm open to suggestions on how to squash/split/reword commits in this PR.

### CODE REVIEW

**Comment by pfalcon** [comment]
That's definitely cool, but we face the opposite problem - how to modify parser/compiler so they used *less* memory, because memory requirements by large subset of scripts already governed by parser/compiler requirements.

**Comment by blazewicz** [comment]
Just to clarify things, here is a little explanation of changes to the parser:

Because of the operator precedence, bitwise ops '|', '^' and '&' must have separate parse rules and therefore can be easily distinguished with its parse node types. Because of this, they were parsed and compiled differently than all other binary operations that must carry information about actual token used (for example `arith_expr` can be '+' or '-').

After this patch, bitwise ops are processed through the same functions as other arithmetic ops and therefore they require information about used token, this information is redundant and hence increase in RAM usage.

Cost of this change is additional word in parse tree for each bitwise operator.

before:
```
>>> x | y | z
result stack, most recent first
[   1] expr_stmt(5) (n=2)
[   1]   expr(34) (n=3)
           id(x)
           id(y)
           id(z)
         NULL
7
>>> x | y & z
result stack, most recent first
[   1] expr_stmt(5) (n=2)
[   1]   expr(34) (n=2)
           id(x)
[   1]     and_expr(36) (n=2)
             id(y)
             id(z)
         NULL
1
```

after:
```
>>> x | y | z
result stack, most recent first
[   1] expr_stmt(5) (n=2)
[   1]   expr(34) (n=5)
           id(x)
           tok(61)
           id(y)
           tok(61)
           id(z)
         NULL
7
>>> x | y & z
result stack, most recent first
[   1] expr_stmt(5) (n=2)
[   1]   expr(34) (n=3)
           id(x)
           tok(61)
[   1]     and_expr(36) (n=3)
             id(y)
             tok(60)
             id(z)
         NULL
1
```

> That's definitely cool, but we face the opposite problem - how to modify parser/compiler so they used less memory, because memory requirements by large subset of scripts already governed by parser/compiler requirements.

If RAM usage is more valued in this tradeoff I can drop the commit changing grammar rules, then bitwise ops will stay as they were and we'll still have optimization generalizing all arithmetic operators and bit shifts. Since `shift_expr`, `arith_expr` and `term` carry token type anyway we don't need to differentiate between them other way than the token type ad we can use single compile function for them (see first commit of this PR).

**Comment by dpgeorge** [comment]
> Since shift_expr, arith_expr and term carry token type anyway we don't need to differentiate between them other way than the token type ad we can use single compile function for them (see first commit of this PR).

Yes, that commit looks good.  The compilation will be a tiny bit slower (maybe) because now compile_term must search through more operator types, but it definitely saves some code space, which is more important (compilation is only done once per script so doesn't need to be highly optimised for speed).

Otherwise, we really can't increase RAM usage by the parser.  Lots of work already went into making it use less RAM by optimising the layout of the parse tree.

So, please just make a PR with the single commit and well see how much it decreases the code by.  Also, maybe it can benefit from a simple lookup table to translate token to operator.

**Comment by blazewicz** [comment]
> The compilation will be a tiny bit slower (maybe) because now compile_term must search through more operator types

> maybe it can benefit from a simple lookup table to translate token to operator

I don't think so George, modern C compilers are pretty good at optimizing switch-case statements. If possible options are close together (they are in this case) it will end up either as lookup table or jump table, constant time anyway. In this situation there is no point trying to outsmart the compiler and the switch case is very readable and easily debuggable.

Here's what GCC 6.3.1 generates for x64:
```
  Disassembly of section .text.compile_expr:

0000000000000000 <compile_expr>:
   0:   41 55                   push   %r13
   2:   41 54                   push   %r12
   4:   41 bc 02 00 00 00       mov    $0x2,%r12d
   a:   55                      push   %rbp
   b:   53                      push   %rbx
   c:   48 89 f3                mov    %rsi,%rbx
   f:   48 83 c3 10             add    $0x10,%rbx
  13:   49 89 fd                mov    %rdi,%r13
  16:   48 83 ec 08             sub    $0x8,%rsp
  1a:   8b 6e 04                mov    0x4(%rsi),%ebp
  1d:   48 8b 76 08             mov    0x8(%rsi),%rsi
  21:   c1 ed 08                shr    $0x8,%ebp
  24:   e8 00 00 00 00          callq  29 <compile_expr+0x29>
  29:   44 39 e5                cmp    %r12d,%ebp
  2c:   0f 8e a0 00 00 00       jle    d2 <compile_expr+0xd2>
  32:   48 8b 73 08             mov    0x8(%rbx),%rsi
  36:   4c 89 ef                mov    %r13,%rdi
  39:   e8 00 00 00 00          callq  3e <compile_expr+0x3e>
  3e:   48 8b 03                mov    (%rbx),%rax
  41:   48 c1 e8 04             shr    $0x4,%rax
  45:   48 83 e8 31             sub    $0x31,%rax
  49:   48 83 f8 0a             cmp    $0xa,%rax
  4d:   77 43                   ja     92 <compile_expr+0x92>
  4f:   ff 24 c5 00 00 00 00    jmpq   *0x0(,%rax,8)
  56:   be 06 00 00 00          mov    $0x6,%esi
  5b:   eb 5a                   jmp    b7 <compile_expr+0xb7>
  5d:   be 08 00 00 00          mov    $0x8,%esi
  62:   eb 53                   jmp    b7 <compile_expr+0xb7>
  64:   be 09 00 00 00          mov    $0x9,%esi
  69:   eb 4c                   jmp    b7 <compile_expr+0xb7>
  6b:   be 0a 00 00 00          mov    $0xa,%esi
  70:   eb 45                   jmp    b7 <compile_expr+0xb7>
  72:   be 03 00 00 00          mov    $0x3,%esi
  77:   eb 3e                   jmp    b7 <compile_expr+0xb7>
  79:   be 04 00 00 00          mov    $0x4,%esi
  7e:   eb 37                   jmp    b7 <compile_expr+0xb7>
  80:   31 f6                   xor    %esi,%esi
  82:   eb 33                   jmp    b7 <compile_expr+0xb7>
  84:   be 01 00 00 00          mov    $0x1,%esi
  89:   eb 2c                   jmp    b7 <compile_expr+0xb7>
  8b:   be 02 00 00 00          mov    $0x2,%esi
  90:   eb 25                   jmp    b7 <compile_expr+0xb7>
  92:   b9 00 00 00 00          mov    $0x0,%ecx
  97:   ba 41 08 00 00          mov    $0x841,%edx
  9c:   be 00 00 00 00          mov    $0x0,%esi
  a1:   bf 00 00 00 00          mov    $0x0,%edi
  a6:   e8 00 00 00 00          callq  ab <compile_expr+0xab>
  ab:   be 05 00 00 00          mov    $0x5,%esi
  b0:   eb 05                   jmp    b7 <compile_expr+0xb7>
  b2:   be 07 00 00 00          mov    $0x7,%esi
  b7:   49 8b 45 48             mov    0x48(%r13),%rax
  bb:   49 8b 7d 40             mov    0x40(%r13),%rdi
  bf:   41 83 c4 02             add    $0x2,%r12d
  c3:   48 83 c3 10             add    $0x10,%rbx
  c7:   ff 90 c0 01 00 00       callq  *0x1c0(%rax)
  cd:   e9 57 ff ff ff          jmpq   29 <compile_expr+0x29>
  d2:   58                      pop    %rax
  d3:   5b                      pop    %rbx
  d4:   5d                      pop    %rbp
  d5:   41 5c                   pop    %r12
  d7:   41 5d                   pop    %r13
  d9:   c3                      retq   

Disassembly of section .rodata.compile_expr:

0000000000000000 <.rodata.compile_expr>:
        ...
```

And arm-none-eabi-gcc 6.2.0 for pyboard:
```
Disassembly of section .text.compile_expr:

00000000 <compile_expr>:
   0:   b5f8            push    {r3, r4, r5, r6, r7, lr}
   2:   684d            ldr     r5, [r1, #4]
   4:   460c            mov     r4, r1
   6:   6889            ldr     r1, [r1, #8]
   8:   4606            mov     r6, r0
   a:   f7ff fffe       bl      0 <compile_expr>
   e:   0a2d            lsrs    r5, r5, #8
  10:   2702            movs    r7, #2
  12:   42bd            cmp     r5, r7
  14:   dc00            bgt.n   18 <compile_expr+0x18>
  16:   bdf8            pop     {r3, r4, r5, r6, r7, pc}
  18:   6921            ldr     r1, [r4, #16]
  1a:   4630            mov     r0, r6
  1c:   f7ff fffe       bl      0 <compile_expr>
  20:   68e3            ldr     r3, [r4, #12]
  22:   091b            lsrs    r3, r3, #4
  24:   3b31            subs    r3, #49 ; 0x31
  26:   2b0a            cmp     r3, #10
  28:   d8f5            bhi.n   16 <compile_expr+0x16>
  2a:   e8df f003       tbb     [pc, r3]
  2e:   171f1d1b                        ; <UNDEFINED> instruction: 0x171f1d1b
  32:   0f062119        svceq   0x00062119
  36:   00151113        andseq  r1, r5, r3, lsl r1
  3a:   2106            movs    r1, #6
  3c:   6af3            ldr     r3, [r6, #44]   ; 0x2c
  3e:   6ab0            ldr     r0, [r6, #40]   ; 0x28
  40:   f8d3 30e0       ldr.w   r3, [r3, #224]  ; 0xe0
  44:   4798            blx     r3
  46:   3702            adds    r7, #2
  48:   3408            adds    r4, #8
  4a:   e7e2            b.n     12 <compile_expr+0x12>
  4c:   2107            movs    r1, #7
  4e:   e7f5            b.n     3c <compile_expr+0x3c>
  50:   2108            movs    r1, #8
  52:   e7f3            b.n     3c <compile_expr+0x3c>
  54:   2109            movs    r1, #9
  56:   e7f1            b.n     3c <compile_expr+0x3c>
  58:   210a            movs    r1, #10
  5a:   e7ef            b.n     3c <compile_expr+0x3c>
  5c:   2103            movs    r1, #3
  5e:   e7ed            b.n     3c <compile_expr+0x3c>
  60:   2104            movs    r1, #4
  62:   e7eb            b.n     3c <compile_expr+0x3c>
  64:   2100            movs    r1, #0
  66:   e7e9            b.n     3c <compile_expr+0x3c>
  68:   2101            movs    r1, #1
  6a:   e7e7            b.n     3c <compile_expr+0x3c>
  6c:   2102            movs    r1, #2
  6e:   e7e5            b.n     3c <compile_expr+0x3c>
  70:   2105            movs    r1, #5
  72:   e7e3            b.n     3c <compile_expr+0x3c>
```

I'll look into further optimizing this patch and I'll return with results.

**Comment by blazewicz** [comment]
Changes in ROM sizes in reference to master after dropping changes to bitwise ops:

unix x64: -704 B
minimal: -204 B
stmhal: -88 B
esp8266: -160 B

**Comment by pfalcon** [comment]
@blazewicz : Thanks. Please try to provide some RAM figures. I.e. choose more or less big source, and show how much RAM is used by just importing it - with and without your patch.

**Comment by blazewicz** [comment]
@pfalcon why would you expect any change in RAM usage?

My patch doesn't change anything in the parser (I've edited the commit message, it was wrong), two changes to the compiler are:
* merging `compile_shift_expr` and `compile_arith_expr` into `compile_term`,
* replaces pointers in `compile_function` lookup table from `compile_{shift_expr,arith_expr}` to `compile_term` (through `c(term)` in grammar.h).

All base functions used same amount of stack as the result of the merging (I've checked with `-fstack-usage` GCC option).

Concluding, this patch should not affect nor compilation speed nor RAM usage, all it does is code size reduction.

Also, I've added tests for operator precedence because I was playing with grammar rules, should I leave it?

**Comment by pfalcon** [comment]
> why would you expect any change in RAM usage?

Solely based on your initial comment where you speculated about RAM usage being affected. If the commit you mention for sure doesn't touch anything related, sounds good.

> Also, I've added tests for operator precedence

From my side, I'd say yes (especially that I never patched parser, and if I would, I'll certainly appreciate such tests), but @dpgeorge can say for sure.

**Comment by dpgeorge** [comment]
Ok, it looks good now except for one thing: please don't add any unreachable code (like assert(false)), instead make the default switch statement actually do one of the cases and assert the switch expression in the default statement (this pattern is used elsewhere).

**Comment by dpgeorge** [comment]
@blazewicz do you have time to address the above comments?  If not that's fine, just let me know and I'll incorporate your changes.

**Comment by blazewicz** [comment]
@dpgeorge I didn't have much time lately, but I'll try to find some today or tomorrow evening

**Comment by dpgeorge** [comment]
Thanks for this patch, it has now been merged; see 7feb7301b2cefd568fa65ee9907a1a179ea41f1c

Total change in code size for this PR is:
```
   bare-arm:  -136
minimal x86:  -296
   unix x64:  -368
unix nanbox:  -600
     stmhal:  -144
    esp8266:  -208
     cc3200:  -136
```
RAM usage is unaffected.

**Pull request closed without merging**
