### PR TITLE
tools: Add telnet support to pyboard.py

### PR DESCRIPTION
**Pull request by danicampora**
The file wipy.py contains two classes "WiPy" which inherits from
"Pyboard" reusing all it's functionality and adding  the option to
connect to the WiPy via Telnet. The second one is the adapter class
"TelnetToSerial" which is used to access the Telnet connection using
the same API as with the serial connection.

### CODE REVIEW

**Comment by danicampora** [comment]
@dpgeorge has two ideas about this PR:

1. Use the `telnet program` or `netcat` instead of `telnetlib` to do the tunneling between the telnet connection and the pyboard "serial" API. I can argue against this that I don't see any advantage, and telnetlib is part of the Python standard library so it's not adding any external dependencies. It can also be argued that if we are taking this route, then why use *PySerial* at all (which is not part of the standard library) and use `screen` instead.

2. Merge wipy.py into pyboard.py and then have a single file to handle communications with the target boards. I like this one. There's one function used to run a small tests suite on the pyboard (it mainly checks the accelerometer) that wouldn't belong there but @dpgeorge already agrees that is not needed anymore and it could be removed.

**Comment by dpgeorge** [comment]
I think we should go for option 2, where we merge TelnetToSerial into pyboard.py.  Of course, it would only import the telnetlib and other libraries if it was actually used.

By having one script able to talk to pyboard and wipy, users only need one script installed.  And it can then likely be used to talk to esp8266 over the air (as well as pyboard with a wifi adaptor, or wired, etc).

**Comment by danicampora** [comment]
@dpgeorge should I merge TelnetToSerial into pyboard.py within this same PR (and update the title accordingly)?

**Comment by dpgeorge** [comment]
Yes, that seems sensible.

**Comment by danicampora** [comment]
@dpgeorge merged `TelnetToSerial` into `pyboard.py` and updated the PR title.
I've tested this many times on both serial and telnet modes and so far is working like a charm :-).

**Comment by dpgeorge** [comment]
Ok, merged in cd14188bc8b4cd942ea7ea5cf5eb27955d8695ae with some minor changes: removed "SKIP" fix since it should be fixed already; kept name of device as "serial" not "conn"; detect IP address using string logic rather than socket.inet_aton.

**Pull request closed without merging**
