### PR TITLE
*: Spelling fixes

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by stinos** [comment]
Out of curiosity: did you run a spell checker ober all comments or was this manual work?

**Comment by scop** [comment]
I used https://github.com/client9/misspell, and selectively fixed flagged issues in seemingly non-3rdparty files.

**Comment by pfalcon** [comment]
> https://github.com/client9/misspell

Thanks for the link.


The common suggestion for patches like this is that they should be split into few smaller, logically structure patches. However, time immediately after a release is good for en masse changes, so for this time, it should be ok. The commit messages however would rather be "various: Spelling fixes."

**Comment by scop** [comment]
Commit message changed as suggested.

**Comment by pfalcon** [comment]
+1

**Comment by dpgeorge** [comment]
Thank you!  Merged.

**Pull request merged**
