### PR TITLE
modsys: Add basic sys.exc_info() implementation.

### PR DESCRIPTION
**Pull request by pfalcon**
The implementation is very basic and non-compliant and provided solely for
CPython compatibility. The function itself is bad Python2 heritage, its
usage is discouraged.

### CODE REVIEW

**Comment by pfalcon** [comment]
So, I gave up patching sys.exc_info() away from CPython stdlib. And this patch actually sat in my stash for couple of fix in case it could get any better, but nope, doesn't seem so ;-).

**Comment by dpgeorge** [comment]
Did you consider somehow using `code_state->exc_sp`?  This holds exactly the info you need, since it's needed anyway for a `raise` without args.  Eg, you could expose the currently executing `code_state` for sys.exc_info to access.  This could be done by copying `code_state` to a global variable on entry to the VM, or just when an exception occurs in the VM.

**Comment by pfalcon** [comment]
> Did you consider somehow using code_state->exc_sp?

Yes, that's why it spent enough time in queue. But as can be seen in testcase, exc_info() should work across function calls. So,

> expose the currently executing code_state

wouldn't help, you need to walk the stack (that's how CPython defines exc_info() btw).

Even if it did, it would be adding one global var instead of another. But ironically, I have another patch in stash which exactly exposes current code_state to achieve introspection of value stack. That's so far just local non-upstreamable experiments.

**Comment by dpgeorge** [comment]
> But as can be seen in testcase, exc_info() should work across function calls.

Damn crazy Python specs that are tied too tightly to the CPython implementation.

Well, I guess more can be done to improve the impl of sys.exc_info: eg in POP_EXCEPT bytecode you could set cur_exception to NULL (or better still, to the previous exception on the stack if it exists).  But since this feature (sys.exc_info) should not be used we can defer such work until needed (maybe never).

**Comment by pfalcon** [comment]
> Well, I guess more can be done to improve the impl of sys.exc_info: eg in POP_EXCEPT bytecode you could set cur_exception to NULL 

Ok, done in ae2c81ff388d9b06bc11ac1e14bd5d71b4f4637c. That's unlikely to hit, but if does, very weird debugging session is guaranteed, so makes sense to fix.

**Pull request merged**
