### PR TITLE
docs: Fix minor grammer error in docs/reference/glossary.rst.

### PR DESCRIPTION
**Pull request by mytechnotalent**
This is a minor fix to the docs/reference/glossary.rst file.

### CODE REVIEW

**Comment by mytechnotalent** [comment]
@jimmo is this going to be merged?

**Comment by dpgeorge** [comment]
Thanks for the patch!  And sorry for the slow response.  Merged in 6eebdbc495a52d1965d7e9255816db310041f96a

**Comment by mytechnotalent** [comment]
No worries at all @dpgeorge thank you!

**Comment by mytechnotalent** [comment]
Since it is merged in `6eebdbc` I will close this PR out thanks again!

**Comment by dpgeorge** [comment]
Ah, usually I close the PR once it's merged... I missed doing that here.

**Comment by mytechnotalent** [comment]
Apologies it is reopen for you to close once it is merged.

**Comment by dpgeorge** [comment]
You were correct to close it.  It was merged and I just forgot to close it when I did the merge!

So let's close it again.

**Pull request closed without merging**
