### PR TITLE
machine I2C/SPI: add explicit SoftI2C and SoftSPI classes, and remove ability to use -1 to specify software implementation

### LINKED ISSUE #4262: HW SPI type does not match machine.SPI
```python
import machine
s = machine.SPI(1, 10000000, sck=machine.Pin(18), mosi=machine.Pin(19))
type(s) = machine.SPI
False

## Huh?

type(s)
<class 'SPI'>
type(machine.SPI)
<class 'type'>
machine.SPI
<class 'SoftSPI'>
```

Not sure how to resolve this in C code ...

Present workaround is 
```python
isSpi = 'SPI' in repr(type(s))
```

### PR DESCRIPTION
**Pull request by dpgeorge**
The motivation for this PR is that the existing way of specifying software based I2C/SPI implementations is confusing:
- a single constructor can create different instance objects; it can be confusing to create a `machine.SPI` instance yet get a `machine.SoftSPI` instance back (see #4262 ) 
- the constructor is heavily overloaded, making it hard to document and understand (also complicates the implementation)
- there are subtle differences in the way to construct a soft vs hard I2C/SPI peripheral, and this makes it confusing for users
- soft I2C has additional methods that hard I2C does not (start, stop, read, write), and that's been a source of confusion

The original reason to merge soft and hard into the same constructor was to make it easier for the user, and essentially hide the difference between soft and hard implementations.  But in practice having a combined constructor makes it harder to use/understand.

For example, currently it works like this:
```python
machine.I2C(-1, scl=Pin(1), sda=Pin(2))  # software based
machine.I2C(scl=Pin(1), sda=Pin(2))  # software based
machine.I2C(1)  # hardware based (default pins used)
machine.I2C(1, scl=Pin(1), sda=Pin(2))  # hardware based
```

And with this PR the above lines change to:
```python
machine.SoftI2C(scl=Pin(1), sda=Pin(2))  # software based
machine.SoftI2C(scl=Pin(1), sda=Pin(2))  # software based
machine.I2C(1)  # hardware based (default pins used)
machine.I2C(1, scl=Pin(1), sda=Pin(2))  # hardware based
```

Benefits of this new approach:
- there's a clear separation between soft and hard peripherals
- it's obvious if you are constructing a soft or hard instance
- the type of the returned object is the same as the constructor type (fixes #4262 )
- the constructors are simplified
 
This is a breaking change for use of software-based I2C and SPI.  Code that constructed I2C/SPI peripherals in the following way will need to be changed:

        machine.I2C(-1, ...)            ->  machine.SoftI2C(...)
        machine.I2C(scl=scl, sda=sda)   ->  machine.SoftI2C(scl=scl, sda=sda)

        machine.SPI(-1, ...)            ->  machine.SoftSPI(...)
        machine.SPI(sck=sck, mosi=mosi, miso=miso)  ->  machine.SoftSPI(sck=sck, mosi=mosi, miso=miso)

In all cases which have changed, existing code will now raise an exception in the constructor (because the id arg is negative and invalid, or because the id arg is missing).

Code which uses machine.I2C and machine.SPI classes to access hardware peripherals does not need to change.

### CODE REVIEW

**Comment by tve** [comment]
For v1.14 what do you think of adding a conditional in the hardware constructor that prints a warning and calls the SoftXXX constructor with the remaining arguments if the ID==-1? Then remove that in v1.15. That would provide a transition period with a warning if I understand correctly?

**Comment by dpgeorge** [comment]
> For v1.14 what do you think of adding a conditional in the hardware constructor that prints a warning and calls the SoftXXX constructor with the remaining arguments if the ID==-1? Then remove that in v1.15. That would provide a transition period with a warning if I understand correctly?

Yes that would provide a transition.  Might also need to cover the case of no ID given, which would also divert to SoftXXX.

There have never been any deprecation warnings in MicroPython... I don't have any strong feelings either way to add them, but IMO raising an exception is a decent enough way to make sure that code doesn't silently do the wrong thing after an update.

An alternative would be to wait for MicroPython 2.0 to put this change in, but I'd rather do it sooner than later.

**Comment by UnexpectedMaker** [comment]
This looks good and I agree, it's a lot less confusing.

**Comment by peterhinch** [comment]
> There have never been any deprecation warnings in MicroPython

Changes that break code have been mercifully very rare. I'm +1 for the change, but also +1 for the suggestion of @tve.

**Comment by dpgeorge** [comment]
> For v1.14 what do you think of adding a conditional in the hardware constructor that prints a warning and calls the SoftXXX constructor with the remaining arguments if the ID==-1?

Now done.  It also supports the existing pattern of no ID specified.

**Comment by dpgeorge** [comment]
Docs updated.

**Pull request merged**
