### PR TITLE
make it possible to configure the USART pins completely via mpconfigboard.h

### PR DESCRIPTION
**Pull request by rambo**
Instead of adding yet another `if defined(BOARDNAME)` define the port and pins.

[Example configuration](https://github.com/rambo/ruuvitracker_fw/blob/MicroPython_rambo/stmhal/boards/RUUVITRACKER_C3/mpconfigboard.h#L67) (tested to work).

### CODE REVIEW

**Comment by pfalcon** [comment]
+1 for this change. And I know such kind of change is usually hard on contributors, waiting for maintainers, which never get to it because working on other things, so extra +1 for that.

@rambo: To help with further progress of this patch, please elaborate how you tested it.

**Comment by dpgeorge** [comment]
Thanks @rambo! This was something I wanted to do (following similar changes I made to I2C config) but didn't get around to it yet.  I'll check it all works and rename the macros to begin with MICROPY_HW_ for consistency.

**Comment by rambo** [comment]
@pfalcon  On `RUUVITRACKER_C3` I verified that the 3 UARTs (1,2,3) wired to SIM968 can be used to talk with the module. on `PYBV10` I tested the all the UARTs with bus-pirate

Flow-control has not been tested but I see no reason why it would not work.

@dpgeorge I can rename those macros ( would have to edit my own board file for that rename anyway), just `s/PYB_USART_/MICROPY_HW_USART_/g` ?

**Comment by dpgeorge** [comment]
@rambo I'm in the middle of it now, and also some other changes.

**Comment by dpgeorge** [comment]
Merged in 2378be4e933dda0f7e7adb2f227530d3fcc3a6aa.

@rambo You'll have to update your own board config file, but it should be easy :)

**Comment by rambo** [comment]
Compiled my firmware against this new upstream after renaming the macros, works fine. Thanks.

**Pull request closed without merging**
