### PR TITLE
ports: Rename USBD_VID/PID config macros to MICROPY_HW_USB_VID/PID.

### PR DESCRIPTION
**Pull request by dpgeorge**
For consistency with other board-level config macros that begin with MICROPY_HW_USB.

See discussion in #7594.

### CODE REVIEW

**Comment by iabdalkader** [comment]
Should the macros in stm32/usbd_desc.c be renamed too ? here: https://github.com/micropython/micropython/blob/master/ports/stm32/usbd_desc.c#L42

And the CDC buffer config `USBD_CDC_TX/RX_DATA_SIZE` ?

**Comment by dpgeorge** [comment]
> Should the macros in stm32/usbd_desc.c be renamed too ?

Yes I'd say they should be as well, for consistency.

I think then we need a deprecation period, and provide backwards compatibility macros for some time.

**Comment by iabdalkader** [comment]
> I think then we need a deprecation period, and provide backwards compatibility macros for some time.

Yes something like ?
```C
#if defined(USBD_LANGID_STRING)
#warn "Warning, deprecated configuration option used."
#define MICROPY_HW_USB_LANGID_STRING  USBD_LANGID_STRING
```

**Comment by dpgeorge** [comment]
I've now renamed all USBD config options to MICROPY_HW_USB.  And moved them to `mpconfigboard_common.h` so they are in one place and it's easy to see what is configurable.

**Comment by iabdalkader** [comment]
>  And moved them to `mpconfigboard_common.h`

Just to be sure, we can still override VID/PID per board right ?

**Comment by dpgeorge** [comment]
> Just to be sure, we can still override VID/PID per board right ?

Yes for sure.  `mpconfigboard_common.h` is where all the board-level config options are, with their defaults.

**Comment by iabdalkader** [comment]
Looks good, but just a suggestion it might be a good idea while we're at it, to make VID/PID configurable in all other ports (nrf, samd, mimrxt).
```
#ifndef MICROPY_HW_USB_VID
#define MICROPY_HW_USB_VID (0xxxx)
#endif
etc...
```

**Comment by dpgeorge** [comment]
> it might be a good idea while we're at it, to make VID/PID configurable in all other ports

Done!

**Pull request merged**
