### PR TITLE
ntptime: support different ntp hosts

### PR DESCRIPTION
**Pull request by puuu**
This is useful to choose other area specific ntp pools or a local ntp server (e.g., a router).

### CODE REVIEW

**Comment by pfalcon** [comment]
It's clear that it's useful, but ntptime.time() was intended to be drop-in replacement for time.time() (and vice-versa). So, I'm not sure that interface is good here.

**Comment by puuu** [comment]
Ahh, I see, I broke the api compatibility. I have not noticed the api compatibility to `time.time()`.

But making it that easy, creates side effects the user may not be aware of:
- high traffic on the ntp pool. Especially if many IoT devices frequently use the server. See also https://en.wikipedia.org/wiki/NTP_server_misuse_and_abuse.
- It will not work and may break your program, if the internet connection is lost.
- `ntptime.time()` can raise exceptions (host not found, timeout), whereas `time.time()` not.

**Comment by puuu** [comment]
With the new commit, you can use `ntptime.time()` again as replacement for `time.time()`. The ntp server can be choosen as argument or by changing `ntptime.host`.

**Comment by pfalcon** [comment]
Done differently (simpler!) in 225562d915a9563f25225f9c8ec1764b2fbb3613. Please mind what's written in the commit message (way to override NTP server may change at any time). Thanks for driving this.

**Comment by one-quaker** [comment]
Guys, how can I change host? Mayb we can add argument to settime(host=)?

**Comment by robert-hh** [comment]
It's a python script in frozen bytecode. Source here: https://github.com/micropython/micropython/blob/master/ports/esp8266/modules/ntptime.py
As shrot fix, you can take thatm change the name & host, and run it from the file system.

**Comment by one-quaker** [comment]
Yes, I can copy full module to local fs and edit it. But "change host" feature is obvious, don't you? Few extra lines can't broke small ntptime module

**Comment by robert-hh** [comment]
Actually it's one line less, as far as I see. Something like: 
```
try:
    import usocket as socket
except:
    import socket
try:
    import ustruct as struct
except:
    import struct

# (date(2000, 1, 1) - date(1900, 1, 1)).days * 24*60*60
NTP_DELTA = 3155673600

def time(host):
    NTP_QUERY = bytearray(48)
    NTP_QUERY[0] = 0x1b
    addr = socket.getaddrinfo(host, 123)[0][-1]
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.settimeout(1)
    res = s.sendto(NTP_QUERY, addr)
    msg = s.recv(48)
    s.close()
    val = struct.unpack("!I", msg[40:44])[0]
    return val - NTP_DELTA

# There's currently no timezone support in MicroPython, so
# utime.localtime() will return UTC time (as if it was .gmtime())
def settime(host="pool.ntp.org"):
    t = time(host)
    import machine
    import utime
    tm = utime.localtime(t)
    tm = tm[0:3] + (0,) + tm[3:6] + (0,)
    machine.RTC().datetime(tm)
    print(utime.localtime())
```

**Comment by one-quaker** [comment]
Yes, you are right. This code is ready for master branch? :)

**Comment by puuu** [comment]
Please have a look to the commit 225562d915a9563f25225f9c8ec1764b2fbb3613 of @pfalcon. 

You simply can change the host variable, e.g.:
```python
import ntptime
ntptime.host = 'myntpserver.example.com'
print(ntptime.time())
```

**Pull request closed without merging**
