### PR TITLE
bluetooth: remove hardcoded generic attribute service.

### PR DESCRIPTION
**Pull request by andrewleech**
Allows it be be defined & managed in python code if needed, eg with https://github.com/micropython/micropython-lib/pull/439

### CODE REVIEW

**Comment by dpgeorge** [comment]
I'm all in favour of removing and simplifying code.  But what kind of impact does this have on existing code?

**Comment by jimmo** [comment]
It seems like micropython/micropython-lib#439 is trying to work around the fact that NimBLE's built-in implementation of the default GATT service is missing this (seemingly very important) feature. I don't really understand why a phone would cache the services for a server that doesn't support this characteristic, but can't do anything about that as far as I can tell.

I'd much prefer to fix this in NimBLE and make the default thing "just work" -- i.e. add the database hash attribute to https://github.com/apache/mynewt-nimble/blob/master/nimble/host/services/gatt/src/ble_svc_gatt.c

I notice that btstack already has database hash calculation functions, so at least btstack won't be too tricky. https://github.com/bluekitchen/btstack/blob/master/src/ble/att_db_util.c#L363

**Comment by andrewleech** [comment]
Yeah we really could add the hash support to nimble itself, that's going to be cleaner of the hash works in C, we can still query that from micropython to compare to a stored hash in pairing db to use as trigger to indicate on service changed (that's still going to need to be managed by application at pairing layer)

Marceau has got a pure Python AES CMAC hash working, but we'll need to switch to a suitable C implementation if we want to add it to nimble properly.

**Comment by jimmo** [comment]
NimBLE already has AES-128 CMAC.

**Comment by andrewleech** [comment]
Sounds like I really overcomplicated things by trying to avoid editing nimble by doing this all in python...

**Comment by andrewleech** [comment]
Deprecated in favour of https://github.com/micropython/micropython/pull/7877

**Pull request closed without merging**
