### PR TITLE
docs/conf.py: Add myself as a copyright holder on the docs.

### PR DESCRIPTION
**Pull request by pfalcon**
Based on the following statistics:

$ git log docs |grep Author | sort | uniq -c | sort -n -r
    175 Author: Paul Sokolovsky
    135 Author: Damien George
     31 Author: Daniel Campora
     26 Author: danicampora
     14 Author: Peter Hinch

git blame stats script from http://stackoverflow.com/a/13687302/496009:

$ sh git-authors docs
   9977 author Damien George
   2679 author Paul Sokolovsky
   1699 author Daniel Campora
   1580 author danicampora
   1286 author Peter Hinch
    282 author Shuning Bian
    249 author Dave Hylands

Total lines per this script: 18417, my contribution is 14.5%.

### CODE REVIEW

**Comment by pfalcon** [comment]
With this I'd also like to propose a formal criteria that a contributor can request an explicit inclusion in the docs copyright notice if they contributed at least 15% of the content. This would limit number of people in the copyright notice to 6. I myself slightly below this threshold, by hope the commit count shows my commitment to maintenance of the docs, which is not less important than writing content.

**Comment by peterhinch** [comment]
I have GitHub set to hide my email address. This post makes it public.

**Comment by pfalcon** [comment]
I removed it, but generally, by submitting your work to a public project you agree that your name and email will be public. Well, some project smartly require explicit sign-off on basic facts (authorship, licensing, publicity), but we keep it easy by treating the fact of submitting a contribution as such sign-off.

**Comment by dpgeorge** [comment]
Looks good to me.

**Comment by pfalcon** [comment]
Merged.

**Pull request closed without merging**
