### PR TITLE
py/runtime: Add mp_raise_RuntimeError function.

### PR DESCRIPTION
**Pull request by Li-Weiwei**
Add a new mp_raise_RuntimeError function to the runtime.

### CODE REVIEW

**Comment by Li-Weiwei** [comment]
This patch increases the code size.

**Comment by dpgeorge** [comment]
> This patch increases the code size.

Did you try to convert existing uses of mp_type_RuntimeError to use this new helper function?  That may reduce code size.

Note that the only reason the other helpers are there (for the other exception types) is because they reduce code size.  So this one here that you add will only be added if it too reduces code size.

**Comment by Li-Weiwei** [comment]
I see runtime.c with functions like mp_raise_ValueError and mp_raise_TypeError.  
I thought adding a separate mp_raise_RuntimeError would make the code look consistent, but it looks like I`m missing the code size issue. 
I wonder if a function like mp_raise_ValueError will be replaced by mp_raise_msg in the future?

**Comment by dpgeorge** [comment]
Converting all uses of RuntimeError to use this helper has a code-size change of:
```
   bare-arm:   -12
minimal x86:   +52
   unix x64:   +16
unix nanbox:   +52
      stm32:   -16
    esp8266:    +0
     cc3200:   -16
```
So at this stage it's not a good change to do.

> I wonder if a function like mp_raise_ValueError will be replaced by mp_raise_msg in the future?

No, the ones that already exist are there because there are enough uses of them that they decrease code size.  So they will stay.

**Pull request closed without merging**
