### PR TITLE
rp2/boards/ARDUINO_NANO_RP2040_CONNECT: Add urequests module.

### PR DESCRIPTION
**Pull request by jimmo**
Seeing as the PICO_W has it, should probably be consistent?

FYI @iabdalkader

### CODE REVIEW

**Comment by iabdalkader** [comment]
Yes why not btw I have an improved version here that supports posting files and authentication:
module: https://github.com/openmv/openmv/blob/master/scripts/libraries/urequests.py
example: https://github.com/openmv/openmv/blob/master/scripts/examples/00-OpenMV-Boards/01-WiFi-Shield/http_post.py
There's docker stuff here for testing too: https://github.com/openmv/openmv/tree/master/docker#testing-http-postget

That said, I have a concern with adding modules from `micropython-lib` to manifests, because that adds a dependency on cloning that repo first. Maybe `micropython-lib` should be a submodule.

**Comment by jimmo** [comment]
> Yes why not btw I have an improved version here that supports posting files and authentication:

@iabdalkader There was a recent PR (thanks @andrewleech @mattytrentini ) that added basic auth to the micropython-lib version but file upload is something that comes up in the forum pretty often so this would definitely be worth considering upstreaming (although I am worried about the increasing size of this module!)

> That said, I have a concern with adding modules from micropython-lib to manifests, because that adds a dependency on cloning that repo first. Maybe micropython-lib should be a submodule.

Yeah there have been a few reports of people being surprised by this recently. Not sure tbh.

**Comment by mattytrentini** [comment]
> Maybe micropython-lib should be a submodule.

+1

I was recently going to try and explain how `urequests` is included to respond to #8852. I knew it was included for ESP32 and have a solid idea how the manifest system works - but then I took a look...and it's quite opaque. Having micropython-lib as a submodule (and tidying up the build system so it's clear which manifest file is called!) would have helped.

**Comment by jimmo** [comment]
I'm inclined to agree.

So if micropython-lib was a submodule, would we remove the if statements in the manifest scripts to see if the path exists? In other words, if the submodule wasn't initialised, then the build would fail? Should micropython-lib be included in `make submodules` ?

Also, I sort of like the idea of being able to pin the micropython-lib version, and explicitly moving it forward (i.e. with a release).

> and tidying up the build system so it's clear which manifest file is called!

@mattytrentini  Is this referring to manifest.py vs manifest_release.py ?

FWIW, longer term what I'd love to do is the equivalent of feature levels for micropython-lib. i.e. a board (or port's default) manifest would include the top-level micropython-lib manifest with a bunch of arguments that include a feature level and supported features (e.g. networking), and that top-level manifest figures out what to include from micropython-lib. That would avoid situations like this where not all boards with wifi automatically get urequests.

Similarly, when we have a good asyncio alternative for urequests, then if you have asyncio you get the async http library instead.

**Comment by mattytrentini** [comment]
> In other words, if the submodule wasn't initialised, then the build would fail?

Yes.

> Should micropython-lib be included in make submodules?

Yes.

>  Is this referring to manifest.py vs manifest_release.py?

Yes, it's not clear why there's a need for both - or why there's also `manifest_test.py`. Tracing the use of `manifest_release.py` through from `build-boards.sh` is not at all obvious either - you need to know that there's a whole separate build system (`tools/autobuild`). Further, my opinion is that we ought to be building using Github Actions so the build process is clear.

> longer term what I'd love to do is the equivalent of feature levels for micropython-lib...

Was just discussing something similar today. 😄

**Comment by dpgeorge** [comment]
I'm happy with this PR, it looks fine.

Regarding making `micropython-lib` a submodule: would be good to discuss this in a separate issue.

**Comment by iabdalkader** [comment]
I agree with all of the above, also please mention me in the new discussion.

**Pull request closed without merging**
