### PR TITLE
unix/modtime: Add mktime function (v2)

### PR DESCRIPTION
**Pull request by dpgeorge**
This is just #5333 with some minor clean ups, made a PR to test AppVeyor.

### CODE REVIEW

**Comment by dpgeorge** [comment]
It looks like AppVeyor is hanging forever when running the test suite.

**Comment by andrewleech** [comment]
Oh geez, that's unexpected!

**Comment by dpgeorge** [comment]
Ok, this passes all tests now.  I used the simple expression `-time.mktime((1970, 1, 1, 0, 0, 0, 0, 0, 0))` to compute the local timezone offset, instead of doing `os.system('date ...')`, the latter which looks like it was stalling AppVeyor (and creating a temporary file...).  Although using mktime itself to compute the offset isn't fully testing mktime behaviour I think it's an ok compromise to get it working.

**Comment by stinos** [comment]
The `date` command on windows isn't the same as the one on unix:
```
date /?
Displays or sets the date.

DATE [/T | date]

Type DATE without parameters to display the current date setting and
a prompt for a new one.  Press ENTER to keep the same date.

If Command Extensions are enabled the DATE command supports
the /T switch which tells the command to just output the
current date, without prompting for a new date.
```

**Comment by andrewleech** [comment]
Ah, yes that makes sense. Thanks for the fix! We shouldn't really have to test C mktime impl ourselves, just the usage. Using the known date to get timezone offset is cleaner and more efficient to my date parsing, I like it.

**Pull request merged**
