### PR TITLE
asyncio: fix import

### LINKED ISSUE #7266: Import / AttributeError error in new asyncio
If some module imports with `from uasyncio import *` and then the this module
is imported  somewhere else there will occur an AttributeError if e.g. `start_server` is invoked: 
```
AttributeError: 'module' object has no attribute 'start_server'
```
The culprit is the "lazy loading" in: https://github.com/micropython/micropython/blob/master/extmod/uasyncio/__init__.py#L8-L30 
Replacing the lazy loading with regular `import` solves the problem.

### PR DESCRIPTION
**Pull request by DrTom**
fixes https://github.com/micropython/micropython/issues/7266

### CODE REVIEW

**Comment by dlech** [comment]
FYI, the reasoning behind the current imlementation was discussed at https://github.com/micropython/micropython/pull/5332#pullrequestreview-347083035

**Comment by DrTom** [comment]
@dlech: as far as I understand the discussion is around problems for IDE tooling etc. But what I ran into is a real bug. As far as I understand the lazy import was predominantly done to save memory. But I have not seen any evidence/numbers how much good that does in reality. In my personal experience I have not seen problems from overhead of imports in frozen code. There are other "things" which are much more likely to result in memory problems. 

So where does that leave us with this bug? I can see two options: apply the fix or write up some documentation how to work around the issues.

**Comment by kevinkk525** [comment]
Yes the main goal was memory saving (afaik). There is no need for absolute numbers in my opinion but you can easily check. It saves some bytes for every module you don't use. On most platforms this might be irrelevant and even on an esp8266 I would be able to live with 500Bytes less but why waste RAM?

I can see that the lazy import doesn't work in your use-case but in my opinion that's an acceptable problem because your use-case isn't a recommended way of programming either:

See [pep8](https://www.python.org/dev/peps/pep-0008/#imports):
```
Wildcard imports (from <module> import *) should be avoided, as they make it unclear which names are present in the namespace, confusing both readers and many automated tools. There is one defensible use case for a wildcard import, which is to republish an internal interface as part of a public API (for example, overwriting a pure Python implementation of an interface with the definitions from an optional accelerator module and exactly which definitions will be overwritten isn't known in advance).
```

**Comment by DrTom** [comment]
@kevinkk525 There is a good reason why I need the `*` import in my case. 

When it comes to premature optimization I am all for numbers to do informed decisions. Here are some for the ESP32 Wroom: 
``` 
>>> import uasyncio
>>> gc.collect(); gc.mem_free()
107776
>>> import uasyncio.stream
>>> gc.collect(); gc.mem_free()
106848
>>> import uasyncio.funcs
>>> gc.collect(); gc.mem_free()
106672
>>> import uasyncio.event
>>> gc.collect(); gc.mem_free()
106080
>>> import uasyncio.lock
>>> gc.collect(); gc.mem_free()
105744
```

A typical use case is to pull in `stream` and `funcs` which leaves us at a saving of less than 1k or about 0.8%.  So we have to weight this against unnecessary incompatibilities vs CPython.

**Comment by kevinkk525** [comment]
Well if you have a good reason (please tell us), then you could simply do the exports differently because you'll likely be the only one to use a wildcard import on uasyncio.
So you could just as well do something like
```
from uasyncio import *
from uasyncio.stream import *
from uasyncio.funcs import *
```
Or is there a reason not to do that?

I see a savings of almost 2k if no stream,funcs,event or lock is being used. That is a significant amount. Maybe not on your esp32 wroom and in your project but overall, 2k is quite something.


Of course I'm just another developer. Personally I just don't see a need here to fix a problem, that maybe 0.8% of all users might encounter and can easily work around, while giving everyone else a disadvantage of up to 2k more RAM usage.

**Comment by DrTom** [comment]
@kevinkk525 

> while giving everyone else 

False! Correct: those importing `asyncio` but not the `asyncio.stream`.

**Comment by DrTom** [comment]
@kevinkk525 I believe discussions about workarounds should be made in the corresponding issue. But it is anyways trivial and really no need for that. 

Costly it is for others to run into a bug and find the reason. This PR is about that. No more no less. The disadvantages in numbers are listed above. The maintainers should be able to decide whether to include the PR or reject it.

**Comment by peterhinch** [comment]
Bear in mind that `uasyncio` is used on ESP8266 where every byte of RAM counts.

**Review by w0ssh — COMMENTED** [review]
salam_.84

**Comment by w0ssh** [comment]
احتراق

**Comment by w0ssh** [comment]
ولت

**Comment by w0ssh** [comment]
1. ### **hg__**

[ ] ### **__**

**Pull request closed without merging**
