### PR TITLE
py/vm.c: Optimise bytecode dispatch (non computed-goto mode).

### PR DESCRIPTION
**Pull request by jimmo**
Random thought from over the weekend, thought I'd test it out. I think this is a worthwhile improvement for constrained boards that disable computed goto, and possibly makes a case for removing computed goto altogether.

Background: From discussion in https://github.com/micropython/micropython/pull/7680#issuecomment-901170391 I found that disabling computed goto has a moderate code size benefit (-1260 bytes on PYBV11), but it appears that there is a small perf benefit from computed goto (numbers are different to linked comment now that #7680 is merged).

```
$ ./run-perfbench.py -s ~/compgoto-baseline ~/compgoto-off
diff of scores (higher is better)
N=100 M=100              /home/jimmo/compgoto-baseline -> /home/jimmo/compgoto-off         diff      diff% (error%)
bm_chaos.py                  375.93 ->     372.37 :      -3.56 =  -0.947% (+/-0.01%)
bm_fannkuch.py                78.36 ->      78.64 :      +0.28 =  +0.357% (+/-0.00%)
bm_fft.py                   2573.16 ->    2523.97 :     -49.19 =  -1.912% (+/-0.00%)
bm_float.py                 6178.73 ->    6075.02 :    -103.71 =  -1.679% (+/-0.01%)
bm_hexiom.py                  44.35 ->      44.48 :      +0.13 =  +0.293% (+/-0.00%)
bm_nqueens.py               4432.25 ->    4472.80 :     +40.55 =  +0.915% (+/-0.00%)
bm_pidigits.py               648.77 ->     648.44 :      -0.33 =  -0.051% (+/-0.39%)
misc_aes.py                  427.67 ->     426.77 :      -0.90 =  -0.210% (+/-0.01%)
misc_mandel.py              3600.02 ->    3491.72 :    -108.30 =  -3.008% (+/-0.00%)
misc_pystone.py             2470.25 ->    2453.13 :     -17.12 =  -0.693% (+/-0.01%)
misc_raytrace.py             384.17 ->     382.95 :      -1.22 =  -0.318% (+/-0.02%)
```

I'm a little bit surprised that computed goto is necessary given that the compiler should be able to do the same jump table optimisaton -- disassembly shows that it does actually do this, but not in the most efficient way. This change gives the compiler a little bit of help and has the effect of reducing the size of the jump table and slightly improving performance.

This change (relative to the existing switch/case implementation) is -208 bytes:

```
$ ./run-perfbench.py -s ~/compgoto-off ~/compgoto-off-case-fix3
diff of scores (higher is better)
N=100 M=100              /home/jimmo/compgoto-off -> /home/jimmo/compgoto-off-case-fix3         diff      diff% (error%)
bm_chaos.py                  372.37 ->     375.22 :      +2.85 =  +0.765% (+/-0.01%)
bm_fannkuch.py                78.64 ->      77.53 :      -1.11 =  -1.411% (+/-0.00%)
bm_fft.py                   2523.97 ->    2570.41 :     +46.44 =  +1.840% (+/-0.00%)
bm_float.py                 6075.02 ->    6099.42 :     +24.40 =  +0.402% (+/-0.01%)
bm_hexiom.py                  44.48 ->      44.02 :      -0.46 =  -1.034% (+/-0.00%)
bm_nqueens.py               4472.80 ->    4343.48 :    -129.32 =  -2.891% (+/-0.00%)
bm_pidigits.py               648.44 ->     653.70 :      +5.26 =  +0.811% (+/-0.41%)
misc_aes.py                  426.77 ->     433.21 :      +6.44 =  +1.509% (+/-0.01%)
misc_mandel.py              3491.72 ->    3569.65 :     +77.93 =  +2.232% (+/-0.01%)
misc_pystone.py             2453.13 ->    2446.61 :      -6.52 =  -0.266% (+/-0.01%)
misc_raytrace.py             382.95 ->     381.53 :      -1.42 =  -0.371% (+/-0.02%)
```

And relative to computed goto (code size: -1476 bytes)

```
$ ./run-perfbench.py -s ~/compgoto-baseline ~/compgoto-off-case-fix3
diff of scores (higher is better)
N=100 M=100              /home/jimmo/compgoto-baseline -> /home/jimmo/compgoto-off-case-fix3         diff      diff% (error%)
bm_chaos.py                  375.93 ->     375.22 :      -0.71 =  -0.189% (+/-0.01%)
bm_fannkuch.py                78.36 ->      77.53 :      -0.83 =  -1.059% (+/-0.00%)
bm_fft.py                   2573.16 ->    2570.41 :      -2.75 =  -0.107% (+/-0.00%)
bm_float.py                 6178.73 ->    6099.42 :     -79.31 =  -1.284% (+/-0.01%)
bm_hexiom.py                  44.35 ->      44.02 :      -0.33 =  -0.744% (+/-0.00%)
bm_nqueens.py               4432.25 ->    4343.48 :     -88.77 =  -2.003% (+/-0.01%)
bm_pidigits.py               648.77 ->     653.70 :      +4.93 =  +0.760% (+/-0.29%)
misc_aes.py                  427.67 ->     433.21 :      +5.54 =  +1.295% (+/-0.01%)
misc_mandel.py              3600.02 ->    3569.65 :     -30.37 =  -0.844% (+/-0.01%)
misc_pystone.py             2470.25 ->    2446.61 :     -23.64 =  -0.957% (+/-0.02%)
misc_raytrace.py             384.17 ->     381.53 :      -2.64 =  -0.687% (+/-0.02%)
```

What the compiler is doing here is hoisting the multi ops out of the switch, and then making a much more efficient jump table. I tried a couple of other things (including manually including all the 64+16+16+8 labels for all possible multi ops, but this was the best outcome in both code size and performance). If you do the hoisting explicitly (which I don't want to do if we keep computed goto) then it generates the same code.

### CODE REVIEW

**Comment by jimmo** [comment]
Added an extra `else` around the switch to ensure that the optimisation happens in `-Os` as well (bare-arm/minimal get -100 bytes).

**Comment by jimmo** [comment]
This is a clearer performance boost on CM0 (e.g. STM32F091), although here it seems to increase code size (+100 bytes).

```
$ ./run-perfbench.py -s ~/compgoto-off-f091 ~/compgoto-off-case-fix3-f091
diff of scores (higher is better)
N=50 M=50                /home/jimmo/compgoto-off-f091 -> /home/jimmo/compgoto-off-case-fix3-f091         diff      diff% (error%)
bm_fannkuch.py                87.03 ->      91.10 :      +4.07 =  +4.677% (+/-0.00%)
bm_nqueens.py                476.80 ->     478.86 :      +2.06 =  +0.432% (+/-0.00%)
bm_pidigits.py               153.10 ->     157.33 :      +4.23 =  +2.763% (+/-0.08%)
misc_aes.py                   72.71 ->      77.88 :      +5.17 =  +7.110% (+/-0.00%)
misc_pystone.py              292.61 ->     298.99 :      +6.38 =  +2.180% (+/-0.01%)
```

Note that we have computed goto disabled on the CM0 STM32 boards (for the size benefit). Just for reference, this comes at a moderate performance cost. (Note: we should replicate this on RP2040).

```
$ ./run-perfbench.py -s ~/compgoto-off-f091 ~/compgoto-baseline-f091 
diff of scores (higher is better)
N=50 M=50                /home/jimmo/compgoto-off-f091 -> /home/jimmo/compgoto-baseline-f091         diff      diff% (error%)
bm_fannkuch.py                87.03 ->      97.48 :     +10.45 = +12.007% (+/-0.00%)
bm_nqueens.py                476.80 ->     506.38 :     +29.58 =  +6.204% (+/-0.00%)
bm_pidigits.py               153.10 ->     158.30 :      +5.20 =  +3.396% (+/-0.11%)
misc_aes.py                   72.71 ->      82.02 :      +9.31 = +12.804% (+/-0.00%)
misc_pystone.py              292.61 ->     310.09 :     +17.48 =  +5.974% (+/-0.01%)
```

**Comment by dpgeorge** [comment]
@jimmo is this still worth considering and possibly merging?

**Comment by dpgeorge** [comment]
I tested this PR with the latest master (at d6bc34a13aa734d8b32e5768c021377ac4815029) and with arm-none-eabi-gcc v12.2.0, on a NUCLEO_F091RC (which has computed goto disabled, and -Os for compiling vm.c).

The results are different to above: it's now only a +16 code size diff, and the performance is worse:
```
diff of scores (higher is better)
N=100 M=100                    master ->         PR         diff      diff% (error%)
bm_fannkuch.py                  13.54 ->      13.09 :      -0.45 =  -3.323% (+/-0.00%)
bm_nqueens.py                  717.37 ->     686.31 :     -31.06 =  -4.330% (+/-0.01%)
core_import_mpy_multi.py        72.90 ->      71.76 :      -1.14 =  -1.564% (+/-0.00%)
core_import_mpy_single.py        9.26 ->       9.14 :      -0.12 =  -1.296% (+/-0.00%)
core_qstr.py                    12.03 ->      11.97 :      -0.06 =  -0.499% (+/-0.00%)
core_yield_from.py              52.63 ->      49.86 :      -2.77 =  -5.263% (+/-0.00%)
misc_aes.py                     58.46 ->      58.23 :      -0.23 =  -0.393% (+/-0.00%)
misc_pystone.py                248.13 ->     243.71 :      -4.42 =  -1.781% (+/-0.15%)
```

Since the code size diff is small, I suspect the compiler is now doing the bulk of the changes in this PR itself (ie pulling the multi opcodes out of the switch).

Since there doesn't seem to be much benefit for this now, I'll close it.

**Pull request closed without merging**
