### PR TITLE
extmod/framebuf: Add "remap" option to blit

### PR DESCRIPTION
**Pull request by deshipu**
Add an optional keyword argument "remap" to the framebuf.blit method,
which allows to pass an array specifying the color palette to be used
for mapping the colors while blitting. This makes it possible to blit
between framebufs with different color depths, and also to do palette
effects.

### CODE REVIEW

**Comment by deshipu** [comment]
I added the docs and a simple test.

**Comment by deshipu** [comment]
Is there anything else that needs to be done here?

**Comment by dpgeorge** [comment]
Overall the idea is good, thanks.

Considering code size: it might be more compact to use positional args rather than have a full array of allowed args.  If it's positional then you need to specify "key" if you want to specify "remap", but you can just pass -1 for key if you don't want to use that feature.

How about making the remap argument something with the buffer protocol (eg bytes, bytearray), rather than a list/tuple?  Using a buffer object would allow much more compact mappings and allow them to be stored in ROM.

**Comment by deshipu** [comment]
Not sure what you mean with list/tuple. I used array of ints, because that seems to fit the color data type best. How would bytes/bytearray work? Take two bytes for every color?

**Comment by deshipu** [comment]
Oh, I see I have a list in the test, not an array — I guess it's getting converted? I'm not sure how this all works internally in MicroPython, to be honest.

**Comment by dpgeorge** [comment]
> Not sure what you mean with list/tuple. I used array of ints, because that seems to fit the color data type best. How would bytes/bytearray work? Take two bytes for every color?

The `mp_obj_get_array` helper function gets the items in either a tuple or a list.  It doesn't work for bytes, bytearray or array.array objects.

I'd suggest converting this to `mp_get_buffer_raise` to support bytes, bytearray and array.array objects.  You can use `mp_binary_get_val_array` to help extract the value from the array, and that will automatically type it to the correct byte-width.  Eg `array.array('B', [1, 2, 3])` will use bytes and `array.array('H', [1, 2, 3])` will use 16-bits.  And not to forget that in the future the module may support 32-bit colour width, so makes sense to try and support that as well (which array.array can).

**Pull request closed without merging**
