### PR TITLE
Apply astyle to format all code (v2)

### PR DESCRIPTION
**Pull request by dpgeorge**
Per discussion in #4223, here is another attempt at formatting the code.  Compared to #5631 there are less changes, but could be mainly due to longer line length (200 chars).

### CODE REVIEW

**Comment by stinos** [comment]
A .py file instead of a .sh would allow running this on windows as well, but on the other I imagine project-wide formatting isn't going to be used all that much, if ever (except for this commit), so probably doesn't matter.

**Comment by stinos** [comment]
Not sure which to pick between this and the other version, but I'm +1 on *not* using `--keep-one-line-statements` and `--keep-one-line-blocks`.

**Comment by dpgeorge** [comment]
Rebased on latest master to pull in changes to mp_raise functions.

**Comment by dpgeorge** [comment]
> A .py file instead of a .sh would allow running this on windows as well, but on the other I imagine project-wide formatting isn't going to be used all that much, if ever (except for this commit), so probably doesn't matter.

I guess it makes sense to make it a .py file, in order to help Windows.  This repo already has a large number of .py helper scripts, and Python is pretty much a prerequisite to build, so doesn't add a dependency in this respect.  This script could also in the future be enhanced to format individual files, and do automatic formatting as part of commits/CI.

**Comment by dpgeorge** [comment]
> Not sure which to pick between this and the other version, but I'm +1 on _not_ using `--keep-one-line-statements` and `--keep-one-line-blocks`.

I would agree to not use these, ie to always put blocks and separate statements on their own line.

**Comment by tve** [comment]
Do I assume correctly that committing this PR will break a large number of the pending PRs? Do you plan to make an effort to merge pending PRs first? Or use this as a way to see which PRs are still "live", i.e. where there is an author that cares enough to update their PR?

**Comment by dpgeorge** [comment]
> Do I assume correctly that committing this PR will break a large number of the pending PRs?

Hopefully not that many, because the changes here are actually relatively sparse.  But I'm happy to fix/reformat pending PRs during merge if they get broken by this change.

> Do you plan to make an effort to merge pending PRs first?

IMO it would make sense to merge this PR first, so that subsequent code changes (including older PRs) don't need to be fixed: they will be merged with proper formatting and the git history will be easier to trace for them.

**Comment by dpgeorge** [comment]
Closed in favour of #5700.

**Pull request closed without merging**
