### PR TITLE
Prevent email harvesting from acknowledgements file

### PR DESCRIPTION
**Pull request by arikb**
The ACKNOWLEDGMENTS file, well intended as it is, contains some email addresses (including mine!). Being the non-spam-lover that I am, I rather my email address would not appear in a world-readable file on the internet to be harvested by spammers.

This pull request converts all email addresses to a non-harvestable format using a very simple "@" --> " at ", "." --> " dot " algorithm.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Good idea, thanks!

Just for the record, all the names/personal data that appear here were explicitly asked to be included.

**Comment by arikb** [comment]
I don't remember asking or being asked, but I don't mind being included at all!

The spam, however, is not that tasty. Had a fair few cases where someone decided to dump my email address (and some where they were part of a data dump stolen from companies) - so many in fact that I have rules excluding specific email addresses from my inbox (and also why I give unique addresses in my domain for everything).

**Comment by dpgeorge** [comment]
In the Kickstarter survey there was a question along the lines of "acknowledgement in the source code, put N/A if you don't want to be acknowledged".

**Comment by arikb** [comment]
Fair enough.

**Pull request merged**
