### PR TITLE
modmachine: Add new module to access hardware, starting with physical memory.

### PR DESCRIPTION
**Pull request by pfalcon**
Refactored from "stm" module, provides mem8, mem16, mem32 objects with
array subscript syntax.

### CODE REVIEW

**Comment by pfalcon** [comment]
Time to have some progress on #1085. This definitely will need further elaboration, but should be good start and already works.

**Comment by dpgeorge** [comment]
Main problem is that this version is unusable with stmhal port due to the need to "and" the address argument with 0x7fffffff.  The anding is needed because the stm constants use 31-bits (they look like 0x400xxxxx) and so come out negative if you simply use them as-is.  I know it's a hack with the anding, but I don't see any other way to do it.  Note that if these constants are bignum's then the constant folding in the compiler doesn't work anymore.

**Comment by pfalcon** [comment]
Well, I don't see any immediate way to do it either. 31 bit means 31 bit. But and'ing means that system ARM stuff, which is usually on private bus at the last quarter of memory space can't be accessed, right?

So, that only means we won't be discussing deprecation plan for stm.mem* any time soon ;-).

**Comment by dpgeorge** [comment]
> But and'ing means that system ARM stuff, which is usually on private bus at the last quarter of memory space can't be accessed, right?

Right.  We're super lucky that (almost) all stm peripheral addr's fit in 31 bits.  There are fixes but all I can think of require lots of new code and are not efficient (eg could define an additional int implementation which is exactly 32 bits...).

> So, that only means we won't be discussing deprecation plan for stm.mem* any time soon ;-).

Sadly we won't.  It might need to stay for a long time.

**Comment by dpgeorge** [comment]
> Time to have some progress on #1085.

Big discussion from there is about what else to put in machine module.  I'm not sure anymore that low-power control (idle, sleep, deepsleep) fits in this module.  But, that aside, surely there are other machine-generic functions that do fit (eg reset), and so it is worth making a machine module rather than a physmem module for the mem* functions.

I would consider the machine module to be a low-level cousin to the sys module.

**Comment by dhylands** [comment]
What about having some type of "peripheral" pointer which can be initialized using an mpz but which is stored using an internal pointer object? Then allow array like accesses using that object as a base and having the array offsets be added to that. As long as the base object were allocated from the main thread, it would still allow use from IRQ level.

**Comment by dpgeorge** [comment]
> What about having some type of "peripheral" pointer which can be initialized using an mpz but which is stored using an internal pointer object?

This smells very much like ustruct's job.  People can indeed make such objects themselves, but it won't solve all our problems here: remember that there's also the inline assembler which uses the stm constants and that really does need them to be constants.

**Comment by pfalcon** [comment]
Yes, we already resolved "how to do it right way" problem with ustruct. machine.mem* is a nothing but a practical hack (so we can argue that someone who want to poke at hardware would rather user uPy than devmem2). It doesn't have to super-efficient. It just needs to be.

**Comment by pfalcon** [comment]
> Big discussion from there is about what else to put in machine module.

Well, we agreed there that we want "all stuff low-level" module rather that just physical memory, and I follow that decision. But each new piece to fir there is worth separate discussion of course.

> I would consider the machine module to be a low-level cousin to the sys module.

In my look, "machine" would be "hardware interfaces v2", reworked stuff from "pyb". But we'll see what it will be actually ;-).

**Comment by pfalcon** [comment]
> ustruct

Of course, it's uctypes ;-).

**Comment by dpgeorge** [comment]
> In my look, "machine" would be "hardware interfaces v2", reworked stuff from "pyb".

I have second thoughts about this way of doing it, but we will see :)

> Of course, it's uctypes ;-).

Yes!

**Comment by pfalcon** [comment]
Ok, merging this in the meantime.

**Comment by pfalcon** [comment]
>>    Of course, it's uctypes ;-).
> Yes!

But you foresaw it well: #1220 ;-).

**Pull request closed without merging**
