### PR TITLE
py: Add support for floats in mp_binary_{get,set}_val()

### PR DESCRIPTION
**Pull request by doogle**
To fix issue #1086.

### CODE REVIEW

**Comment by pfalcon** [comment]
And looking at the patch, I remembered why I didn't implement float support for struct - because it's a bit boring to handle byte order stuff. You see to care about that for set case (will it work for all host vs target endianness combinations? ;-) ), but not for get. Care to at least add asserts?

**Comment by pfalcon** [comment]
Ok-ok, I got rusty on that code, I see that get case is handled of automagically. So, please just confirm that you thought about different combinations and think it should work.

**Comment by doogle** [comment]
Yeah I figured it made sense to make use of `mp_binary_{get,set}_int()` to handle the endianness stuff.

The only special case is due to `mp_binary_set_int()` taking a mp_uint_t value (as opposed to `mp_binary_get_int()`, which returns a long long): when `sizeof(mp_uint_t) != 8`, I have to add another call to `mp_binary_set_int()` in order to set all 8 bytes.
By using the compile-time endian configuration along with the value of `struct_type` to decide the order of these two 32-bit values, all required combinations should be handled.

The only combination that wouldn't be handled here are mixed-endian doubles.

**Comment by pfalcon** [comment]
Thanks, merged!

**Pull request closed without merging**
