### PR TITLE
extmod/modmachine: Factor ports' machine module dict to common code.

### PR DESCRIPTION
**Pull request by dpgeorge**
This is a code factoring to have the dict for the machine module in one location, and all the ports use that same dict.  The machine.soft_reset() function implementation is also factored because it's the same for all ports that did already implement it.  Eventually more functions/bindings can be factored.

All ports remain functionally the same, except:
- cc3200 port: gains soft_reset, mem8, mem16, mem32, Signal; loses POWER_ON (which was a legacy constant, replaced long ago by PWRON_RESET)
- nrf port: gains Signal
- qemu-arm port: gains soft_reset()
- unix port: gains soft_reset()
- zephyr port: gains soft_reset(), mem8, mem16, mem32

### CODE REVIEW

**Comment by jimmo** [comment]
This looks good!

Out of curiosity, does this need the "include file" treatment, what actual inlining benefit do we gain here? (Unlike say an implementation of PWM where the port is providing inlinable implementation functions, for the machine module ports are providing top-level functions that go straight into the globals dict).

**Comment by dpgeorge** [comment]
> Out of curiosity, does this need the "include file" treatment, what actual inlining benefit do we gain here?

It's not really needed yet, but:
1. I wanted to be consistent with how the other machine classes are implemented.
2. Eventually the ports' `modmachine.c` will implement functions to be inlined, eg for `machine.bootloader()`, `machine.unique_id()` etc.

**Comment by dpgeorge** [comment]
I should say there's still more factoring to be done later on, but for now this is a decent start that sets up the framework.

**Comment by jimmo** [comment]
Cool, sounds good to me!

**Comment by robert-hh** [comment]
This is again a lot of rework to the ports. I have a question about style of defining the machine_module_globals. In extmod, you use sequences like:
```
    #if MICROPY_PY_MACHINE_WDT
    { MP_ROM_QSTR(MP_QSTR_WDT), MP_ROM_PTR(&machine_wdt_type) },
    #endif
```
while in the port specific modmachine.c files you define symbols like `MICROPY_PY_MACHINE_I2C_ENTRY` and then include these into the table. What is the reason for the different style?  The latter makes indeed  the table look more clean, at the cost of splitting a definition in two parts. It's also not clear, why the definition for I2C, SPI and RTC are in the port specific sections, if they are enabled by mpconfigport.h.

**Comment by dpgeorge** [comment]
> while in the port specific modmachine.c files you define symbols like `MICROPY_PY_MACHINE_I2C_ENTRY` and then include these into the table. What is the reason for the different style?

Ideally it would all be the former and everything would be in `extmod/modmachine.c`, with very few additional entries added by the ports.  But for this initial factoring of code, it wasn't easy to factor all the classes due to the way that the ports enable them.  So it had to be done this way as an intermediate step.

> It's also not clear, why the definition for I2C, SPI and RTC are in the port specific sections, if they are enabled by mpconfigport.h.

It's because some ports use non-standard config options to enable these particular classes, and it wasn't clear how to factor that to make all ports use the same config options.  Cleaning this up will be the next step in a follow-up PR.

**Comment by dpgeorge** [comment]
I updated SPI so that the entry in the machine globals dict is now shared among all ports.

I also made machine.idle() bindings common among ports, as a start on factoring all the functions.

**Comment by dpgeorge** [comment]
Updated I2C to use a shared entry in the machine globals dict.

Made common bindings for:
- bootloader
- freq, reset, reset_cause, unique_id, lightsleep, deepsleep
- enable_irq/disable_irq

**Comment by robert-hh** [comment]
About RTC: at the SAMD port, MICROPY_PY_MACHINE_RTC is always set. That changed a while ago, accepting that at boards w/o RTC the time precision would be poor. So the conditionals around RTC could be dropped, and it can simply be included into the modmachine locals table, like it is done in most other ports.

**Pull request merged**
