### PR TITLE
py/persistentcode: Full set of optimisations to reduce mpy file size

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR combines and improves upon previous PRs to reduce size of mpy files: #4473 (static qstrs), #4549 (qstr window).

It also adds a further optimisation (second commit) to pack the qstr data directly into the bytecode instead of writing it at the end of the bytecode.  This allows to shrink the mpy file by about 2 bytes for every opcode that has a qstr argument.

Eg, for the sequence (LOAD_GLOBAL 'print', CALL_FUNCTION 0), instead of encoding it as `0x1c 0x00 0x00 0x64 0x00 0x05 p r i n t` it's now encoded as `0x1c 0x05 p r i n t 0x64 0x00` (the 0x05 is the length of the string "print").

The mpy saver can write such a stream in one pass without needing any additional temporary memory, and same goes for the mpy loader.

Size reduction is about 25% for the qstr window, then a further 10% for packed qstrs in bytecode, then a further 5% with the addition of a static qstr set.

On a bunch of 19 test py scripts (including uasyncio, upip, lcd160cr), the sum of all 19 mpy file sizes went from 60064 bytes before the patches here down to 39185 bytes.

### CODE REVIEW

**Comment by pfalcon** [comment]
Unexpected twist. One may only wonder why it wasn't done like that from the beginning, and look for premonitions like "but before we could read the whole bytecode efficiently with one read() call", or "but before we could mmap() bytecode".

Skipping that, one can point that there's still no support for specifying the exact window size (in ones, not in powers of two).

**Comment by dpgeorge** [comment]
>  "but before we could read the whole bytecode efficiently with one read() call", or "but before we could mmap() bytecode".

Well, everything is a compromise / trade off.  Efficiency concerns with multiple read() calls can be mitigated with a buffer (and vfs_reader already has one).  Not being able to mmap a .mpy file is a valid concern, but I don't think it's an important one: since the data has to anyway be modified the mmap needs to be MAP_PRIVATE and it's really just a potential speed optimisation to load it, not one to reduce memory usage (and on bare-metal mmap doesn't really exist, and if it does then it must anyway allocate RAM, it can't map ROM).

I tested the speed of importing lcd160cr.mpy (a large file) before and after the set of patches here, and got:
```
        before  after
PYBv1.0  40 ms   20 ms
esp8266 226 ms  161 ms
```
So the import speed is reduced by a lot, most likely due to less handling of qstrs.

> Skipping that, one can point that there's still no support for specifying the exact window size (in ones, not in powers of two).

The reason for a power-of-two is to be able to use `&` instead of `%` in the window computation.  But if you really think it's an important option to have...

**Comment by pfalcon** [comment]
> But if you really think it's an important option to have...

Well, that was a "feature request" from me from the start, and given all the other refactors made, hopefully this one can fit in too.

> The reason for a power-of-two is to be able to use & instead of % in the window computation. 

Otherwise it's just an `if` to wrap the index.


Thanks for other repsonses and figures - I agree with all of them.

**Comment by dpgeorge** [comment]
> Well, that was a "feature request" from me from the start, and given all the other refactors made, hopefully this one can fit in too.

Ok, I pushed a commit implementing this.  It needs further testing though (and squashing).

**Comment by dpgeorge** [comment]
Merged in 5996eeb48fa6ce773003eacbc7e0b52ad5cc4d31 through 62483bb957f5882e550e059d577718f347f0cba4

**Comment by pfalcon** [comment]
Thanks!

**Pull request merged**
