### PR TITLE
esp32/machine_hw_spi: Use default pins when making SPI if none given.

### PR DESCRIPTION
**Pull request by dpgeorge**
Fixes issue #6974.

Also updated the quickref to show this is possible.

### CODE REVIEW

**Comment by tve** [comment]
Did you consider that the defaulkt pin numbers for esp32-s2 and -c3 are going to be different? Do you plan on using ifdefs for these? I don't know how this is handled in other ports.

**Comment by dpgeorge** [comment]
> Did you consider that the defaulkt pin numbers for esp32-s2 and -c3 are going to be different? Do you plan on using ifdefs for these?

No I didn't consider this.  Would be good to retain the same defaults if that's possible.  Otherwise using ifdefs would be OK.

> I don't know how this is handled in other ports.

In stm32 it's up to a board to configure its default pins for UART, SPI, I2C, CAN (and others).  Would probably make good sense to do a similar thing for esp32, so that boards that have labelled buses (eg Feather layout) have the default pins in the labelled locations.  That would just be a matter of making the default pins configurable names like `MICROPY_HW_SPI1_SCK` etc.

**Comment by kevinkk525** [comment]
I'd also like to add the issue mentioned in #6859. If the ESP32 can't do Hardware SPI on non-standard pins, then it should not accept other pins, which then silently doesn't work.

**Comment by dpgeorge** [comment]
> If the ESP32 can't do Hardware SPI on non-standard pins, then it should not accept other pins, which then silently doesn't work.

Yes, agree.  Let's tackle that as part of #6859.

**Comment by iot49** [comment]
Would be great if PR #7009 could be merged also. 
The ESP32/UART driver presently ignores RTS/CTS as can be verified with an Oscilloscope. The fix is just a couple of lines.

**Comment by kevinkk525** [comment]
Sorry but I don't see what that PR has to do with the hardware SPI in this PR? I just don't see the relevance of your answer in this PR.

**Comment by dpgeorge** [comment]
I updated this PR so that the default pins are macro constants that can be optionally overridden by a board.

**Pull request merged**
