### PR TITLE
Data seg

### PR DESCRIPTION
**Pull request by odewdney**
The minimal build has 4 bytes in the data segment, because the pyexec_mode_kind is initialised to enum value 1, changing the order of the enum changes the default to 0, so it can be in the bss segment

### CODE REVIEW

**Comment by mikewadsten** [comment]
See also #5321.

**Comment by odewdney** [comment]
It seems that most code has a test for both values or the optimiser does its magic, so the net change seems to be about 0

**Comment by dpgeorge** [comment]
Thanks for the patch!  Testing code size difference for the first commit (just reordering the enums) gives (using `tools/metrics.py`):
```
   bare-arm:    +0 +0.000% 
minimal x86:    -4 -0.003% [incl -4(data)]
   unix x64:    +0 +0.000% 
unix nanbox:    +0 +0.000% 
      stm32:    +0 +0.000% PYBV10[incl -4(data) +4(bss)]
     cc3200:    +0 +0.000% [incl -8(data)]
    esp8266:    +4 +0.001% GENERIC[incl -4(data) +8(bss)]
      esp32:    +4 +0.000% GENERIC
        nrf:   +28 +0.019% pca10040[incl -4(data) +8(bss)]
       samd:    +0 +0.000% ADAFRUIT_ITSYBITSY_M4_EXPRESS[incl -4(data)]
```
I guess the +8 bss on esp8266/esp32 is due to alignment.  And similarly -8 data on cc3200 but no additional bss is (I guess) due to alignment.  So that's nothing to worry about.

The only real change in text size is nrf, because (I guess again) it's using LTO.

Well, I'd be happy to merge this change (probably just the first commit because the second one doesn't do anything really) because reducing the size of the data segment helps improve start up time (less data to copy).

**Comment by dpgeorge** [comment]
Merged first commit in b51a2c266a50163f41cb4320f9b9f68a91132403.  Thank you!

**Pull request closed without merging**
