### PR TITLE
RTC mod from @chuckbook: check for LTE ready in rtc_init()

### PR DESCRIPTION
**Pull request by peterhinch**
This mod fixes the loss of RTC clock cycles on re-initialisation but does not address the LSE/LSI detection.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks @peterhinch and @chuckbook!

It would be great to be able to detect LSE/LSI.  Maybe that can go in the next PR? :)

**Comment by chuckbook** [comment]
@dpgeorge 
I'm glad I could help!
As mentioned before, this little patch is only a small part of the full RTC handling. Before I start to throw in some more functions, we should discuss this. Would this be the right place?
Anyhow, here is a raw list of features we have:
- LSE/LSI fallback
- LSx to HSE handover during runtime (even on the pyboard, the HSE is sometimes more precise than LSE)
- LSx calibration (enable/disable LSx 512Hz output)
- LSE temp. compensation (parabolic match)
- replace the sub-second value by a more convenient ms or µs value
It is obvious that each of these modifications has implications to other parts of the system.
BTW. I forced one of the younger guys into service to educate me about all this git voodoo. He is not very happy, but I'm stronger -:)

**Comment by blmorris** [comment]
@chuckbook - Thanks for this, it would be good to fill out MIcroPython's RTC support, and it looks like you already have quite a lot of it worked out.
> Before I start to throw in some more functions, we should discuss this. Would this be the right place?

Could start here, but probably better to open a new issue to discuss RTC features, and then open separate PR's to prepare each feature for merging; that is the usual process.
Most of the features you mention will be new for MicroPython. We do have the beginning of LSE calibration, but it is just a function to manually set the smooth calibration register after the calibration offset has been measured and computed off-line. As you know, the hardware provides features to help automate LSx calibration (LSx 512Hz output being one of those features; there is also a mechanism to automatically determine a calibration offset from a 50/60Hz reference input), IMO it would be helpful to have those supported as well.

**Comment by dpgeorge** [comment]
Merged in 38196344691ad32b7f80bb44489c069ceaecb1ec.

I think with this patch we no longer need to check if YMD is 0.  I think now we only init the RTC on power up (not reset or exiting standby).  And so after the power-up init we will always need to configure the calendar (YMD will always be 0 if we get to that check).

Anyway, there's a lot that can be improved with the RTC and we should work towards that using the new machine API.  I'll open a new PR.

**Comment by dpgeorge** [comment]
See #1546 and #1559 for further discussion.

**Pull request closed without merging**
