### PR TITLE
powerpc: UART fixes

### PR DESCRIPTION
**Pull request by shenki**
Some changes to the way UARTs are probed in the powerpc port. Previously they were selected based on some machine state, but this changes them to be selected at compile time.

In the future microwatt will gain a 16650 style UART (the register layout used by uart_lpc_serial.c) so the one driver can be used. For now we need both potato and the lpc driver.

### CODE REVIEW

**Comment by mikey** [comment]
Thanks @shenki. The build stuff looks fine in the first 2 patches.

The generic travis changes should either be in a separate PR or at least called out as being changed here.

I'm not a big fan of losing the runtime detection of the UART type.
> This breaks probing of the uart type.
How does it break this?

**Comment by shenki** [comment]
> Thanks @shenki. The build stuff looks fine in the first 2 patches.
> 
> The generic travis changes should either be in a separate PR or at least called out as being changed here.

They change the build to test the changes that are in this PR.

> I'm not a big fan of losing the runtime detection of the UART type.
> 
> > This breaks probing of the uart type.
> 
> How does it break this?

If the system has something else in r3, then the code assumes you want the LPC UART. 

I use the same bootloader for Linux and Micropython, and the Linux bootloader puts the device tree address in r3.

In addition we're broken because you hardcoded the system frequency to 50MHz, which is now commonly 100MHz. This PR also fixes that.

To do proper runtime detection you would need to add device tree support to microwatt. This would would allow to to determine the driver to use, the addresses, and the system frequency. I wanted to get the build working for microwatt again and look at more invasive changes like that in a future change.

**Comment by mikey** [comment]
> > Thanks @shenki. The build stuff looks fine in the first 2 patches.
> > The generic travis changes should either be in a separate PR or at least called out as being changed here.
> 
> They change the build to test the changes that are in this PR.

Sorry I was confusing the changes with something that's upstream already.  Ignore that

> > I'm not a big fan of losing the runtime detection of the UART type.
> > > This breaks probing of the uart type.
> > 
> > 
> > How does it break this?
> 
> If the system has something else in r3, then the code assumes you want the LPC UART.
> 
> I use the same bootloader for Linux and Micropython, and the Linux bootloader puts the device tree address in r3.

OK. Makes sence. If we can get micropython to support reading the device tree I guess we can get the single binary back.

> In addition we're broken because you hardcoded the system frequency to 50MHz, which is now commonly 100MHz. This PR also fixes that.

ACK.

> To do proper runtime detection you would need to add device tree support to micropython. This would would allow to to determine the driver to use, the addresses, and the system frequency. I wanted to get the build working for microwatt again and look at more invasive changes like that in a future change.

OK. Please add that info to the commit.

**Comment by dpgeorge** [comment]
This looks OK to me.  Is it ready to merge?

**Comment by shenki** [comment]
I spoke with Mikey and I think he was okay with the changes. He also tested on hardware and said it looked good.

**Comment by mikey** [comment]
Yeah good with me

**Comment by dpgeorge** [comment]
Rebased and merged in f03d030080ccf89c6ad677c818c949c3bd71ec37 and 5cfc09ffca3203eb474aec478b8baf1f35fd2a0b

**Pull request closed without merging**
