### PR TITLE
Nordic port for nRF5x (with commits cleaned up)

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR takes PR #3137 and rebases it, squashes the first 800 or-so commits into a single one (up to and included the move to the ports/nrf/ subdir), and changes some commit messages to fit the style of this repo.

I checked copyright and licensing of all files and they fall under one of the following categories:
- fresh code written specifically for this Nordic port of MicroPython with MIT license
- based on existing MIT code from this MicroPython repo (copyright header was retained and in some cases updated to include new authors)
- code copied from the micro:bit repo which has an MIT license and which was originally written specifically for MicroPython on the micro:bit

There is also some HAL code committed in the first commit here that is copyright by Nordic and ARM with a BSD 3-clause license (which is compatible with the MIT license used here).  But this was subsequently removed and replaced by a git submodule with that content.  This history of removal/replacement will remain in the commits that are part of this PR.

I'm happy to merge this PR as-is (well, at least rebase one final time upon master).

### CODE REVIEW

**Comment by aykevl** [comment]
> There is also some HAL code committed in the first commit here that is copyright by Nordic and ARM with a BSD 3-clause license (which is compatible with the MIT license used here).

Which code do you mean? The code in `ports/nrf/hal`? AFAIK that's all freshly written and MIT-licensed, specifically to avoid SDK code which [back then](https://devzone.nordicsemi.com/b/blog/posts/introducing-nordics-new-software-licensing-schemes) wasn't yet published under a BSD license (@glennrub probably knows more about this). I can only see references to the SDK in the one squashed commit, but as far as I can see, they're all gone in the first commit.

But aside from that comment, I'm fine with this PR as-is (and can't wait to see it merged :grinning:).

**Comment by dpgeorge** [comment]
> Which code do you mean? The code in ports/nrf/hal?

No, I mean the code that was in `ports/nrf/device/` and appears in this initial commit: https://github.com/dpgeorge/micropython/commit/e0ea077da523c3d67baac46576d66ded04b89945, and it was then replaced with the nrfx git submodule in https://github.com/dpgeorge/micropython/commit/d3f5e54f6070deecb535f682f49270839a2668ee

**Comment by aykevl** [comment]
Ah, you're right. I missed those register header files and startup code.

**Comment by dpgeorge** [comment]
I cherry picked @glennrub 's latest commit to add license and copyright info to the two remaining micro:bit files.

**Comment by glennrub** [comment]
With this last commit in, it looks good to me to merge.

**Comment by dpgeorge** [comment]
Now merged.  See e22b94350889af32527e4ebf3a8323e4eba9280e through 264d80c84e034541bd6e4b461bfece4443ffd0ac

**Pull request closed without merging**
