### PR TITLE
esp8266: Move status() from esp module to network

### PR DESCRIPTION
**Pull request by owens-bill**
Moving status to the network module. This may be the last small method to move before the big pull of socket and all its methods along with getaddrinfo; the other small ones look like they'll either stay in esp (flash_id, deepsleep) or be subsumed by WLAN.iwconfig (phy_mode, sleep_type, mac).

### CODE REVIEW

**Comment by pfalcon** [comment]
> before the big pull of socket and all its methods along with getaddrinfo;

socket and friends won't go to "network", they don't belong there, so they stay in "esp" (they can't be moved to "socket" because their interface is not compliant with normal python "socket").

**Comment by roger-** [comment]
> they stay in "esp" 

How about `esp.socket` so that `esp`  doesn't just become a collection of unsorted stuff?

**Comment by pfalcon** [comment]
It exactly destined to be collection of stuff which can't be put anywhere else. When (if) there will be normal execution model for esp8266, not limited toy-like model as implemented by its vendor, there will be just normal "socket" module which will just work. When stuff doesn't work, no matter how you call it, it will be just same non-usable stuff.

**Comment by roger-** [comment]
I guess for now it's not too bad, but it makes the REPL slightly easier to use when functions are neatly sorted into modules.

**Comment by pfalcon** [comment]
Merged, thanks!

**Pull request closed without merging**
