### PR TITLE
renesas-ra/machine-pin: Remove unsupported feature code and test

### PR DESCRIPTION
**Pull request by TakeoTakahashi2020**
* Remove legacy feature code and unsupported feature code to reduce code size.

### CODE REVIEW

**Comment by dpgeorge** [comment]
If you want to remove these that is good, but there is other code that should probably also be removed at the same time:
- `#define AF(af_idx, af_fn, af_unit, af_type, af_ptr)` in boards/ra_pin_prefix.c
- contents of `machine_pin_init()`
- the code in `machine_pin_find()` that accesses `pin_class_mapper` and `pin_class_map_dict` (because these objects are now always None)
- the unused variables in mpconfigport.h `MICROPY_PORT_ROOT_POINTERS`

**Comment by TakeoTakahashi2020** [comment]
Thank you for your review.  I will check them.

**Comment by TakeoTakahashi2020** [comment]
I could remove the other code and reduced the rom size more.  Thanks.

**Comment by dpgeorge** [comment]
Thanks for updating.  Rebased and merged in dd83f48fb28b925cfc2c5e5722f129378d30aed9 and 19c680ff579c5d250d8929959b392f236286bb66

**Comment by TakeoTakahashi2020** [comment]
Thank you for the merge.

**Pull request closed without merging**
