### PR TITLE
tests/extmod/uhashlib: Coverage for SHA1.

### PR DESCRIPTION
**Pull request by hosaka**
Although SHA256 is tested as a part of builtin_hash test, there was no separate moduhashlib test. This also tests SHA1 algo for supported ports.

### CODE REVIEW

**Comment by hosaka** [comment]
There is a separate 256sha.py that I just didn't notice. Can we rename it to uhashlib and add SHA1 tests?

**Comment by dpgeorge** [comment]
You don't need .exp files because these tests also run under CPython.

**Comment by hosaka** [comment]
My oversight, removed .exp!

**Comment by dpgeorge** [comment]
> Although SHA256 is tested as a part of builtin_hash test

Can you please expand on this... how is SHA256 tested by tests/basics/builtin_hash.py?

**Comment by hosaka** [comment]
> Can you please expand on this

This is incorrect, I have mistakenly though that builtin_hash.py calls functions from moduhashlib. I didn't notice extmod/sha256.py and made an assumption that builtin_hash uses uhashlib, which is obviously incorrect and comes down to my lack of knowledge of how python works internally :)

**Comment by dpgeorge** [comment]
> This is incorrect, I have mistakenly though that builtin_hash.py calls functions from moduhashlib

Ok, no problem.  Then please edit the commit message to reflect this.  Also, please make the rename of sha256.py a separate commit.  Thanks!

**Comment by hosaka** [comment]
All done, thanks Damien!

**Comment by pfalcon** [comment]
Merged, thanks!

**Pull request closed without merging**
