### PR TITLE
travis: use ppa for uncrustify

### PR DESCRIPTION
**Pull request by dlech**
Use PPA so that we don't have to rebuild uncrustify from source.

### CODE REVIEW

**Comment by dlech** [comment]
We packaged uncrustify 0.70.1 in a PPA so that it doesn't have to be built from source.

**Comment by stinos** [comment]
It's not 0.70.1 being used there but 0.66.1, maybe your package didn't get installed or you built the wrong version?

**Comment by dpgeorge** [comment]
Travis can be hard to get working sometimes....

**Comment by dlech** [comment]
I figured out the problem. The code format build was running on arm64 and the PPA doesn't have a build for that architecture, so I removed the arm64 setting.

**Comment by dlech** [comment]
It looks like this PR reduces the test from 5 minutes to 1 minute.

**Comment by dpgeorge** [comment]
Thanks, merged in 0608fbff29fab758fa9cee67e9a485e695e5d1f7

**Pull request closed without merging**
