### PR TITLE
ESP8266 made compatible with ulab module

### PR DESCRIPTION
**Pull request by rcolistete**
MicroPython for ESP8266 made compatible with [ulab user C module](https://github.com/v923z/micropython-ulab), by changing files :
-  "../ports/esp8266/boards/esp8266_common.ld" so ulab is moved from IRAM1 to IROM0, fixing the "`iram1_0_seg' overflowed" error;
-  '.../esp8266/Makefile' and '.../esp8266/mpconfigport.h' to define some math functions used by ulab, fixing the building/linking errors  "undefined reference to acoshf, asinhf, atanhf, erff, erfcf, tgammaf, lgammaf, log2f."

These file changes don't increase the firmware size when not including ulab module.

ulab compiles for MicroPython ESP8266 GENERIC (flash >= 2 MB) board, but overflow the IROM0 for GENERIC_1M and GENERIC_512k configurations.

See this [MicroPython Forum topic, "ulab for ESP8266"](https://forum.micropython.org/viewtopic.php?f=16&t=8767) for some discussions about ulab on ESP8266.

### CODE REVIEW

**Comment by stinos** [comment]
Seems a bit tricky to start modifying MicroPython to make it accomodate a library instead of the other way around; which in this case would mean a generic  solution for adding things to the linker section (the other 2 changes, i.e. adding code files and a define can already be done without having to modify core files I think?)

**Comment by rcolistete** [comment]
> Seems a bit tricky to start modifying MicroPython to make it accomodate a library instead of the other way around; which in this case would mean a generic solution for adding things to the linker section (the other 2 changes, i.e. adding code files and a define can already be done without having to modify core files I think?)

[ulab module](https://github.com/rcolistete/micropython-ulab) is included in the :
* [CircuitPython firmware >= v5.1.0 (2020-04-02)](https://blog.adafruit.com/2020/04/02/circuitpython-5-1-0-released-circuitpython-python-ulab-adafruit-circuitpython/);
* [OpenMV Cam firmware >= v3.5.0 (2019-11-04)](https://docs.openmv.io/library/index.html?highlight=ulab#third-party-libraries-on-the-openmv-cam) :
* [MicroPython for K210 Lobo firmare >= v202002](https://loboris.eu/forum/showthread.php?tid=1004).

The one line added to "../ports/esp8266/boards/esp8266_common.ld" is specific to allow building MicroPython for ESP8266 + ulab module, but **it doesn't make any problem (neither 1 byte more in the firmware) when building without ulab, just take space (1 line) from the source code**.

The changes '.../esp8266/Makefile' and '.../esp8266/mpconfigport.h' to make some math functions (acoshf, asinhf, atanhf, erff, erfcf, tgammaf, lgammaf and log2) available :
- are useful for ulab and any other C module using some of these math functions;
- make MicroPython for ESP8266 more compatible with MicroPython for STM32 (Pyboard, etc) with respect SP (single precision in float point numbers).

**Comment by stinos** [comment]
Yes I'm well aware, but still I think a better solution would be a generic one - if possible. Especially for the linker script. If only to avoid all module makers start requesting 1-line changes :)

**Comment by v923z** [comment]
> Yes I'm well aware, but still I think a better solution would be a generic one - if possible. Especially for the linker script. If only to avoid all module makers start requesting 1-line changes :)

I think this is a very fair point. But then there must be some sort of infrastructure on `micropython`'s side. I would be more than happy to handle this in `ulab` itself, if necessary, but there must be a clean way of adding to/overriding `micropython` defaults, when compiling a user library. 

So, perhaps, this PR should have a much broader scope, and should aim at implementing the required tools for third-party components.

**Comment by rcolistete** [comment]
> Yes I'm well aware, but still I think a better solution would be a generic one - if possible. Especially for the linker script. If only to avoid all module makers start requesting 1-line changes :)

@stinos
I've made a new commit removing the linker script modification.

So now there are only the changes in '.../esp8266/Makefile' and '.../esp8266/mpconfigport.h' to make more math functions (acoshf, asinhf, atanhf, erff, erfcf, tgammaf, lgammaf and log2) available, so that it :
- is useful for some C modules;
- makes MicroPython for ESP8266 more compatible with MicroPython for STM32 (Pyboard, etc) with respect SP/FP32.

**Comment by dpgeorge** [comment]
Merged in b099db4426c3a47e842c3e8afd5b5bb05cbcdd72

One good argument for merging this (with just the additional libm files added to the build) is that it now allows `MICROPY_PY_MATH_SPECIAL_FUNCTIONS` to be enabled on esp8266 (if someone needs that in a custom build).

**Pull request closed without merging**
