### PR TITLE
nrf: minor fixes, and add to Travis build

### PR DESCRIPTION
**Pull request by dpgeorge**
With the fix to the Makefile, `make -j4` now works without complaining about bad dependencies.

### CODE REVIEW

**Comment by glennrub** [comment]
@dpgeorge , i believe you are right. I can provoke the same error on an old computer running arm-none-eabi 4.9.3. I have not seen this issue with 6.3.1 and 7.2.1. Would it be a big hassle to upgrade it, or would it be better to get the linker scripts work with the old linkers?

**Comment by glennrub** [comment]
The distribution of _arm-none-eabi_ has moved from Launcpad to ARM recently. I have not yet been able to track down a PPA which contains the latest releases after ARM took over the distribution ([Launchpad](https://launchpad.net/gcc-arm-embedded), [ARM](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads)). I'm not too familar with Travis, but could Travis somehow use wget to retrieve the zip from ARM directly and add it to PATH?

**Comment by dpgeorge** [comment]
> could Travis somehow use wget to retrieve the zip from ARM directly and add it to PATH?

Yes.

**Comment by aykevl** [comment]
I added these variables to the linker script in commit https://github.com/micropython/micropython/commit/2de65dda2226b6ac08e978a93365b886424838f1, not aware that it is a relatively recent addition to binutils. It removes a lot of redundancy so I am hesitant in reverting that commit (and I don't think there is a good workaround). So if a newer binutils version can be installed that would be great.

Support for these variables was added in 2015: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=cc9ad334a71b0c032f711e86885fb73821f3be16

The changes themselves look good to me.

**Comment by dpgeorge** [comment]
Ok, I updated the old arm-none-eabi-gcc PPA to the new one described here: https://launchpad.net/gcc-arm-embedded/+announcement/13824 .  That installs arm-none-eabi-gcc 7.3.1 built on 20180622 which is very recent.  Now the nrf build works.

**Comment by dpgeorge** [comment]
Merged, see 55632af70a66f93b568935dfda09e90de9dcc2c3 through b7004efe369f3aa005b019d6a8afcbfb399607d6

**Pull request closed without merging**
