### PR TITLE
travis: Build "deplibs" in unix port.

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by dpgeorge** [comment]
Yes, this is ok.

**Comment by pfalcon** [comment]
Merged. Adds about 2 mins to build time.

**Comment by dpgeorge** [comment]
> Adds about 2 mins to build time.

Apparently we can make Travis faster by using their new architecture, but I don't have the time to work that out.

**Comment by pfalcon** [comment]
It doesn't allow sudo, and thus have restrictions regarding installing stuff from PPAs, using pip, etc. So, until they kick everyone from the old one, I'd say isn't worth to bother.

And I don't think currently our Travis is slow, I just care for it not to become slow ;-)

**Pull request closed without merging**
