### PR TITLE
RFC: emscripten: Got something to compile and link.

### PR DESCRIPTION
**Pull request by dhylands**
I used the following command line from within the unix tree:
make CC=emcc CPP='gcc -E' CFLAGS_EXTRA=-DMICROPY_NLR_SETJMP MICROPY_PY_FFI=0 STRIP=echo SIZE=echo V=1

I was building under Ubuntu 14.04 using emscripten 1.35.4

emcc doesn't recignize .S files at all, so my commit needs work (I just removed all of the nlrXXX.o files which originate from source).

In obj.h, I changed some mp_int_t to mp_uint_t because left shifting an int is apparently undefined. I tested a bunch of different values using the modified macro and it seems to produce the same results.

The resulting micropython file doesn't run under node, so I still need to figure out why not. But I figured I'd post what I've done up until now as a PR as a form of documentation.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Wow, cool!  Please keep us posted as to progress.  You may want to use minimal/ instead of unix/ since it has less to go wrong.

**Comment by dhylands** [comment]
I updated my branch to create an emscripten port, based off a copy of the minimal port.

At least now, it can build by just typing make.

It's still not running for me, so will need further

**Comment by pfalcon** [comment]
py/obj.h changes were finally applied in https://github.com/micropython/micropython/commit/2bddfd492255d03a695a1e7488de3fba80b8e5ab . The rest is indeed better to maintain in a branch.

**Comment by piranna** [comment]
Why didn't work? Did it gave an error or something?

**Comment by alanjds** [comment]
Heh... I have no clue. Better to ask on that ticket ;)

**Comment by dhylands** [comment]
I didn't get a REPL and didn't have time to investigate.

If I were going to approach this again, I would probably start with something other than MicroPython and just try to get basic input and output working (i.e. basic needs of the REPL). I'd then figure out how to create the heap, and then how to get setjmp/longjmp working. Those 3 things are the fundamental things that MicroPython needs to function.

Once you've got those things working, I suspect it's not much more difficult to bring up minimal MicroPython to a REPL.

**Comment by piranna** [comment]
I would try to exec a simple script that prints to the console, and later
go into details why the REPL doesn't work.

**Comment by dpgeorge** [comment]
On approach to the GC would be to disable it altogether and rely on the underlying JavaScript memory manager.

**Comment by alanjds** [comment]
[Here](https://github.com/pypyjs/pypyjs/blob/e804ada21fb727bc1bd93df923537e94213dc28b/src/pypyjs.js#L664) is how PyPy.js handled the REPL thing, via ``jq-console``.

A simpler version can be found here: https://github.com/pypyjs/pypyjs-examples/blob/gh-pages/minimal_console.html

**Comment by alanjds** [comment]
Ideas about overcoming the setjmp/longjmp issue on Javascript: The ["suspensions" pull request](https://github.com/skulpt/skulpt/pull/286) of Skulpt

**Comment by dpgeorge** [comment]
It would be nice to further abstract the nlr behaviour (push/pop/raise) so it can be optionally replaced (at compile time) with samething like try/throw (eg to compile and work with native C++ exceptions).  Maybe this could also be used when converting to JS, to use JS exceptions.

**Comment by matthewelse** [comment]
I've been playing around with micropython on emscripten this evening (spoke to @jaustin about it). I'll put something working up on GitHub soon, but it's successfully printing 'hello world' to the screen 😄

**Comment by matthewelse** [comment]
I've managed to get a small example running on micropython on top of emscripten this evening (only prints 'hello, world').

I tried running the minimal example on OS X before I got it running with emscripten, which may explain the issue @dhylands was having before. I'll put some code up on GitHub this evening to show it working.

cc: @jaustin

**Comment by matthewelse** [comment]
I've put the code up here: matthewelse/micropython - you should be able to run it by following the instructions in the README, though there may be additional dependencies I've forgotten.

**Comment by piranna** [comment]
Wiii!!! ^^ When we get this working publish it to npm too!!! :-D

**Comment by matthewelse** [comment]
@piranna - the REPL is _almost_ working ;) - we're getting there

**Comment by piranna** [comment]
What problems has the REPL?

**Comment by matthewelse** [comment]
The problem I've had at the moment is an issue with the way that Emscripten deals with STDIN, though it's straight forward enough to use the REPL package in node to produce a REPL.

**Comment by piranna** [comment]
Then the output of emscripten could be used as a library and just add a Javascript cli using that library for the REPL :-)

**Comment by matthewelse** [comment]
@piranna that's what I've done here :) https://github.com/matthewelse/micropython/blob/emscripten/emscripten/main.js

**Comment by matthewelse** [comment]
screen shot 2016-11-10 at 22 20 45

**Comment by piranna** [comment]
Then expand it a bit, add a `package.json` file and you are go :-)

**Comment by jaustin** [comment]
Matt this is amazing! 

--
Please excuse brevity and typos, this was sent from a phone

**Pull request closed without merging**
