### PR TITLE
extmod/network_ninaw10.c: Fix config ap mode.

### PR DESCRIPTION
**Pull request by iabdalkader**
* Fix missing call to connect() to configure module in AP mode.
* Use enums for keyword args indices.
* Rename keyword args for consistency with other network drivers.

### CODE REVIEW

**Comment by iabdalkader** [comment]
Working example:
```Python
import network, socket, sys, time, gc

SSID ='NANO-RP2040'   # Network SSID
KEY  ='1234567890'  # Network key (must be 10 chars)
HOST = ''           # Use first available interface
PORT = 8080         # Arbitrary non-privileged port

# Init wlan module and connect to network
wlan = network.WLAN(network.AP_IF)
wlan.active(True)
wlan.config(essid=SSID, key=KEY, security=wlan.WEP, channel=2)
print("AP mode started. SSID: {} IP: {}".format(SSID, wlan.ifconfig()[0]))
```

**Comment by dpgeorge** [comment]
The esp32 port uses the kw-arg `password` for the key, and kw-arg `authmod` for the security type.  As with other things, best to keep these consistent across WLAN drivers (and cyw43 also uses `password`).

**Comment by iabdalkader** [comment]
> The esp32 port uses the kw-arg `password` for the key, and kw-arg `authmod`

I can't find `authmod` used anywhere, there's `auth` in cyw43 and `authmode` in esp32, can you confirm that ? would prefer to follow cyw43, been using it as a reference, so `auth` is fine, but `security` is also very common in WiFi terminology. Can we support alias keywords ?

Example:
```
            case MP_QSTR_auth:
            case MP_QSTR_security: {
           ....
```

**Comment by dpgeorge** [comment]
> I can't find `authmod` used anywhere

Sorry, that's a typo, I meant `authmode` to follow esp32 and esp8266.  It's also in the docs: http://docs.micropython.org/en/latest/library/network.WLAN.html?highlight=authmode#network.WLAN.config

When cyw43 supports this functionality it would use `authmode` as well in the `.config()` method.

> there's `auth` in cyw43

Ah, you're right, but that's actually for the `.connect()` method.  That should really be changed to `authmode` for consistency (and also `key` changed to `password`, and that one is more of a positional parameter).

Please use `authmode` in `.config()`.

> Can we support alias keywords ?

We could... but that would only be to transition from one keyword to another, eg if it was deemed that `security` was better than `authmode`.  Again, the main thing to consider is how to write portable code that works on all ports (and using `security` only on nina-based boards isn't very portable).

**Comment by iabdalkader** [comment]
> Ah, you're right, but that's actually for the `.connect()` method. That should really be changed to `authmode` for consistency (and also `key` changed to `password`,

I think `auth`, `authmode` and `password` should all be deprecated in favor of `security` and `key`, as referred to in the 802.11 IEEE standards, but also logically authentication is only a part of the security protocol.

If I switch to `authmode` and `password` now, they will have to be deprecated later, so why not fix it now and start deprecating the others ? That is if you agree on the naming.

**Comment by iabdalkader** [comment]
I pushed this 75f4c21d2f370d2e50f0bb7b830f92650be4f55b which renames the args to `authmode` and `password`, so if you decided to use them you can merge the 2 commits in this PR.

**Comment by dpgeorge** [comment]
I've merged the first commit (that fixes AP config) in 1b7eee24eb024ee3822db341c3447423a684b84f

**Comment by dpgeorge** [comment]
For the rename of keywords I've opened #8083 to discuss it.  So I'll close this PR for now.

**Pull request closed without merging**
