### PR TITLE
LICENSE: Add my copyright, as the author of ~30% of commits to the project.

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by pfalcon** [comment]
So, number of commits alone can't be fully adequate measure of "substantial contribution". Actually, no single metric could be. Of all single metrics, number of commits is probably giving the most insight.

I actually was keen to make other measurements, e.g. percentage of active lines authored by me, and number of changes lines (then apparently to py/ and extmod/, because number of changed lines in various HALs and BSPs can easily overshadow anything), but I don't see a tool which readily does that. As usual, there's a gazillion of tools which do "something", and it's not exactly clear what that something is. All in all, looking that, I figure I spend time which could better be spent on something else, and just submit this patch for starters.

**Comment by pfalcon** [comment]
Also, actually adjusting the figure from 40% to 30%. The 40% was based on one-year ago stats, plus also was based not on total no. of commits, but on the number of commits from 2 largest contributors.

My current stats show:

~~~
$ git log | grep "Author:" | grep "Sokolovsky" | wc
   2876   11504  161016
$ git log --oneline | wc
   9823   85499  663136
~~~

**Comment by pfalcon** [comment]
Well, I can reasonably care about just my stuff, that's why there's just one line change. There's a maintainer to care about all the other lines.

Otherwise, it's established practice to credit significant contributors explicitly. The exact contribution list and credits can be indeed found in "git log".

**Comment by pfalcon** [comment]
> For the copyright in the LICENSE file pertaining to MicroPython itself, either 1) write "Copyright 2013-2018 The MicroPython Developers" and leave it at that (individual names can be found elsewhere)

I'd say this is OK, but then this single-line patch would indeed turn into pretty boring long patch to add/update my copyrights on many files that I missed (as I concentrated on other things when I had commit access). Actually, this PR was exactly an attempt to avoid preparing/maintaining such a boring patch.

**Comment by pfalcon** [comment]
> and the top-level LICENSE file be used to describe (and point to) all the kinds of licenses that appear in the whole project. The latter is definitely needed because at the moment it's hard to know exactly what licensing conditions there are when using a given port (eg if berkeley-db is used then UC Berkeley must be mentioned in advertising material).

Good catch on libs like berkeley-db. And the reason why I called to avoid license zoo (for content written purposedly for MicroPython, i.e. any tool written should be just MIT licensed), and 100% avoid adding any GPL content, even if it's just a tool. And consequently, I'd say that top-level LICENSE should indeed list licensing for any code which may go *inside* a MicroPython binary, but not list any possible different licenses for tools/ and similar dirs (e.g. licenses for similar support scripts in imported/submodule'd projects).

**Comment by dpgeorge** [comment]
> Which also makes me wonder how necessary it is to keep the date in there, is that something legally required?

Copyright expires after a certain number of years (eg 70, or 120) so it's important to list the year of creation of the works.

> but then this single-line patch would indeed turn into pretty boring long patch to add/update my copyrights on many files that I missed

In such a case there would need to be a rule as to when it's fair to add a copyright line at the top of the file, eg when there are more than 25% of the lines authored by one individual.

> And consequently, I'd say that top-level LICENSE should indeed list licensing for any code which may go _inside_ a MicroPython binary, but not list any possible different licenses for tools/ and similar dirs (e.g. licenses for similar support scripts in imported/submodule'd projects).

Yes that makes sense.  But then it would be good to add a one-liner to the LICENSE (at the end) along the lines of "Additional licenses may apply to support tools and scripts."

**Comment by pfalcon** [comment]
> In such a case there would need to be a rule as to when it's fair to add a copyright line at the top of the file, eg when there are more than 25% of the lines authored by one individual.

Well, to remind, lack of formal rules (your no-desire to set them up) was the reason of the current project org situation. So yep, it's a bit strange to hear about formal rules now. I don't think "25% of the lines authored" would cut, the usual rule is "substantial contribution", which is either effectively writing it initially (also includes turning a many-lines placeholder into something really working), or adding something which takes a noticeable (also to others) algorithmic and/or debugging work - all surveyed and acked (or not acked) by project maintainer(s).

**Comment by nickovs** [comment]
I'm +1 on separating the license, copyright notice and authors at the top level and then including authors at a per-file level. I would caution against having a firm, written rule for what constitutes a substantial contribution for many of the reasons that @pfalcon just gave.

Regarding specifying licenses, it would make sense to at least mention the licenses for included components in the top level license file, as well as including the full license for the MicroPython code itself. Making mention of these at the top level makes it easier for users to find them and having the policy that you will do so helps ensure that people are aware when additional license requirements might creep in (which provides a little back-pressure against "license zoo"). I would also love to see [SPDX](https://spdx.org) license specifier tags in such files to make it easier for users to use tools to examine licenses in projects they use. Once this discussion is settled I am happy to submit a PR to add SPDX tags in the appropriate places.

**Comment by dlech** [comment]
> My proposal would be:
> 
>     1. Update the top-level LICENSE file to mention all licenses used in the repository (with MicroPython's MIT first).

I would like to suggest the [debian/copyright](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/) file format for this (saves time vs. coming up with our own policy/specification and makes life easier for ~me~ debian package maintainers).


> I am happy to submit a PR to add SPDX tags in the appropriate places.

👍 for SPDX, but I do know that in the Linux kernel, only the original author is allowed to make the patch that changes the license header (for legal reasons).

**Comment by pfalcon** [comment]
> For the copyright in the LICENSE file pertaining to MicroPython itself, either 1) write "Copyright 2013-2018 The MicroPython Developers" and leave it at that (individual names can be found elsewhere)

@dpgeorge, So, do you intend to make this change?

**Comment by pfalcon** [comment]
Ok, so this PR is 3 months old by now. Nothing in the discussion was done soon after discussion, or before the 1.10 release, or at all so far. @dpgeorge, please merge this PR, then feel free to make rest of changes, if any, at your convenience. Thanks.

**Comment by dpgeorge** [comment]
Ok, since I didn't find time to make comprehensive changes to the LICENSE file (even though there were excellent efforts by @dlech in #4432), I'm happy to just merge the change here as a "temporary" solution **as long as @pfalcon agrees that these copyright lines can be eventually removed and replaced with something like "Copyright 2013-2019 The MicroPython developers"**.  Is that acceptable?

**Comment by pfalcon** [comment]
> I'm happy to just merge the change here as a "temporary" solution as long as @pfalcon agrees that these copyright lines can be eventually removed and replaced with something like "Copyright 2013-2019 The MicroPython developers". Is that acceptable?

I'd appreciate merging this, yeah. Regarding 2nd part, I have to admit that I've come to a feeling, that no, I don't like and don't agree to that. The reason is that, using the rhetoric of author of some texts which got popular at recent times, it would be an act of dehumanizing the Open Source software development.

That said, I'd suggest to treat those as separate issues with separate reasoning (and discussion). The reasoning behind the change here was presented above - I'm the author of ~30% commits to the project, and designer of some subsystems and facilities in MicroPython which are now taken for granted as natural and integral parts of it, so I'd like to be clearly presented as such.

**Comment by dpgeorge** [comment]
> I have to admit that I've come to a feeling, that no, I don't like and don't agree to that.

In that case we need to have a longer discussion about this.  I don't want merging this PR to be a complete blocker to actions that might be taken later on (like I discuss above).

> so I'd like to be clearly presented as such.

I was under the impression that #4787 was intended to take care of this, as you stated in https://github.com/micropython/micropython/pull/4363#issuecomment-457112210

**Comment by pfalcon** [comment]
@dpgeorge 

> In that case we need to have a longer discussion about this. I don't want merging this PR to be a complete blocker to actions that might be taken later on (like I discuss above).

But what seems to be blocker is the lack of response and activity on this pretty important and yet simple matter. I said it's ok from my side on Jan 24, I pinged you on Jan 31, but there were no actions or even responses, which raises questions if there're reservations and double-think on your side.

>>     so I'd like to be clearly presented as such.

> I was under the impression that #4787 was intended to take care of this, as you stated in #4363 (comment)

Well, those patches were just routine updates of per-file copyrights which I didn't do when I had commit access because I concentrated on more technical things and kept book-keeping things like that in backlog.

Anyway, don't let me be the weakest link here.

> Ok, since I didn't find time to make comprehensive changes to the LICENSE file (even though there were excellent efforts by dlech in #4432), I'm happy to just merge the change here as a "temporary" solution as long as @pfalcon agrees that these copyright lines can be eventually removed and replaced with something like "Copyright 2013-2019 The MicroPython developers". Is that acceptable?

Yes, please merge this patch, and I assume the reason for not having made the change of "Copyright 2013-2019 The MicroPython developers" in the LICENSE file since January is the desire to prepare it somehow "better" than just to make that change (e.g. to accompany it with additional stats). So, I assume such a future change will be for better, and agree to it. Thanks.

**Comment by dpgeorge** [comment]
>  So, I assume such a future change will be for better, and agree to it.

It's a bit hard to agree to "any future change for the better", since "better" is subjective.  So probably the future direction should be spelled out now and agreed to now.

But apart from that, one issue with adding your copyright to the top-level LICENSE file is that it would (I assume) then apply to all files in the repo that don't have an explicit license.  Eg ports/stm32/boards/pllvalues.py.  That's obviously not a true reflection of the copyright of such files.

**Comment by pfalcon** [comment]
> But apart from that, one issue with adding your copyright to the top-level LICENSE file is that it would (I assume) then apply to all files in the repo that don't have an explicit license.

Well, it's probably possible to find a file in the repo without copyright which wasn't created, and not/barely touched by you. So, it's a bit looking for breadcrumb issue. I look at the top-level LICENSE as a license/copyright overview file, listing major contributors (as copyright holders).

**Comment by jimmo** [comment]
Please see #4800 for a simple and concrete suggestion for the LICENSE file. The intent here is to clarify the overall project copyright and licensing, and making it clear that any author can claim copyright over their own individual work at a per-file level.

**Comment by pfalcon** [comment]
@dpgeorge: Ping.

**Comment by dpgeorge** [comment]
> Well, it's probably possible to find a file in the repo without copyright which wasn't created, and not/barely touched by you.

But if it was added without a copyright/license then the top-level LICENSE file should implicitly apply to it (if said file was added after the top-level LICENSE was added).  And changing LICENSE now is kind of like rewriting the copyright history of all those files.

> I look at the top-level LICENSE as a license/copyright overview file, listing major contributors (as copyright holders).

There's a difference between an overview/summary of all the licenses/copyright holders in the repo (see eg #4800), and having a license that is generally applicable to the code in the repository.  The latter is currently what LICENSE is.

All in all this is a pretty complex issue, and since is it's hard to undo some of these decisions once taken they should be well considered.

In the end there needs to be a way to fairly attribute contributions (eg done by #4787), make sure that everything in the repo has a well defined license/copyright (currently done by the LICENSE file as a default), and provide a way for users to understand and comply with the various licensing (eg #4432, #4800).

**Comment by pfalcon** [comment]
> But if it was added without a copyright/license then the top-level LICENSE file should implicitly apply to it (if said file was added after the top-level LICENSE was added). And changing LICENSE now is kind of like rewriting the copyright history of all those files.

But it wasn't "good" in the first place. And that's the reason why "enterprisey" project are paramount about each and every file to have a copyright and licensing blurb. And it seems that at certain popularity (== accumulated controversy), any project needs to pay attention to that. So, the right way to resolve that appears to be: 1) be absolutely strict about licensing/copyright; 2) to track down any unlicensed/uncopyrighted files and add relevant copyrights (with proper communication to assumed copyright holders.

All that's still orthogonal to the issue of this patch, and shouldn't influence/block it too much.

>  and having a license that is generally applicable to the code in the repository. The latter is currently what LICENSE is.

Again, my pragmatic treatment is that top-level LICENSE applies to the whole *project*. And I seek proper recognition of my efforts on the whole-project level, as unalienable part of the license. The fact that formally top-level LICENSE applies to each file not explicitly stated otherwise, is a low-level, formal, procedural issue, which of course should be resolved too, and proposal for that is outlined above.

> In the end there needs to be a way to fairly attribute contributions (eg done by #4787), make sure that everything in the repo has a well defined license/copyright (currently done by the LICENSE file as a default), and provide a way for users to understand and comply with the various licensing (eg #4432, #4800).

Right. This patch is however orthogonal to those issues, and as I stated, it's not my intention to interfere with resolving or evolving these matters further, only to capture the status quo.

**Comment by pfalcon** [comment]
> make sure that everything in the repo has a well defined license/copyright (currently done by the LICENSE file as a default), and provide a way for users to understand and comply with the various licensing

It's hard to refrain from a comment that one of the source of disagreement was exactly my efforts to "raise the bar" of contributions to the codebase, in particular, define principles and rules, and efforts to apply them more thoroughly (instead of "anything will do, we'll clean up after users" approach exercised during a few initial years of the project). There was ~ zero response and support of those efforts, leaving me one on one against the tide, with predictable consequences. In the end, turns out those issues are still ("now"?) relevant and need to be resolved. D'oh.

**Comment by dpgeorge** [comment]
> the right way to resolve that appears to be: 1) be absolutely strict about licensing/copyright;

As part of that the purpose of the LICENSE file should be clarified, which is what I attempt in #4812

**Comment by dpgeorge** [comment]
> Yes, please merge this patch, and I assume the reason for not having made the change of "Copyright 2013-2019 The MicroPython developers" in the LICENSE file since January is the desire to prepare it somehow "better" than just to make that change (e.g. to accompany it with additional stats). So, I assume such a future change will be for better, and agree to it. Thanks.

This is what I have tried to do in #4812, to "prepare it somehow better" and "accompany it with additional stats".  IMO such a change is for the better, and so according to what you say here you would agree to it.  But from your comments on #4812 it seems you do not agree to it.

> to track down any unlicensed/uncopyrighted files and add relevant copyrights (with proper communication to assumed copyright holders.

So my next proposal would be along these lines.  To go through the repository and make sure all files are licensed properly, remove/replace things that have no or unfavourable licenses, and clean it up.  Then revisit this question of top-level licensing/copyright.

**Comment by pfalcon** [comment]
> IMO such a change is for the better, and so according to what you say here you would agree to it. But from your comments on #4812 it seems you do not agree to it.

Nope, I just personally feel:

1. That #4812 is being done as a *replacement* of doing specific steps about this patch.
2. Now that I'm pulled into discussion of #4800/#4812, I had to say that I indeed don't see it as improvement. Improvement attempt - perhaps, but IMHO, it confuses things more than improves them.

Both are rather subjective of course. And, I'm not "against it", just express my reservations.

 > So my next proposal would be along these lines. To go through the repository and make sure all files are licensed properly, remove/replace things that have no or unfavourable licenses, and clean it up. Then revisit this question of top-level licensing/copyright.

Sounds good.

**Comment by pfalcon** [comment]
> Ok, since I didn't find time to make comprehensive changes to the LICENSE file (even though there were excellent efforts by @dlech in #4432), I'm happy to just merge the change here as a "temporary" solution as long as @pfalcon agrees that these copyright lines can be eventually removed and replaced with something like "Copyright 2013-2019 The MicroPython developers". Is that acceptable?

Ok, besides me agreeing to this, this still wasn't done in time for the 1.11, even though it was requested in its planning ticket, https://github.com/micropython/micropython/issues/4784#issuecomment-492228213 .

@dpgeorge, all your behavior here looks like ignoring the issue, then finding excuses for not making the requested change, to which even you yourself agreed.

**Comment by dpgeorge** [comment]
Closed in favour of commit 2fa975c26465a1afed93b5723435e7cfe96e129f

**Pull request closed without merging**
