### PR TITLE
H7 Series support.

### PR DESCRIPTION
**Pull request by iabdalkader**
Not sure why it was removed.

### CODE REVIEW

**Comment by dpgeorge** [comment]
> Not sure why it was removed.

I recently found out that the CMSIS library already defines an equivalent macro to `MCU_SERIES_H7`: `STM32H7` (and similar for the other MCU series).  So I'd prefer to use this standard name rather than invent our own.  You'll see that I did change to use this new macro for the H7.

**Comment by iabdalkader** [comment]
@dpgeorge I fixed it, although it's not consistent as the other HALs don't define the same macro (yet).

**Comment by iabdalkader** [comment]
@dpgeorge re the SD card. I'm fixing the driver locally, but there's a lot of changes between HALs. For starters, the SD doesn't need a DMA to be configured or used anymore, also some typdef's and status/error codes have changed. Would you rather use a separate H7 driver instead of all the #ifdefs ? Or try to keep it all in sdcard.c ? I can send something later for review.

**Comment by dpgeorge** [comment]
> Would you rather use a separate H7 driver instead of all the #ifdefs ? Or try to keep it all in sdcard.c ?

The majority of sdcard.c is generic code (eg the last 25% is just Python bindings) so maybe the best thing to do is split this file up into generic code, and MCU-specific code with a separate file for F4/F7 vs H7.  But before we go down that path it would be good to review the changes needed (just however you have it).

**Comment by iabdalkader** [comment]
@dpgeorge Will do.. Should I fix those conflicts first ?

**Comment by dpgeorge** [comment]
> Should I fix those conflicts first ?

Yes please, it should be easy, I think it's just that I changed the MCU_SERIES macros to STM32.

**Comment by iabdalkader** [comment]
Fixed.

**Comment by iabdalkader** [comment]
@dpgeorge Going to send the SDMMC PR later for review, but I need this PR merged first.

**Comment by dpgeorge** [comment]
Please can you separate the 2nd commit into two: one for the changes to ports/stm32/i2c.c, and one for the changes to files in ports/stm32/boards/NUCLEO_H743ZI.

**Comment by iabdalkader** [comment]
@dpgeorge done.

**Comment by dpgeorge** [comment]
Thanks for updating.  Merged in 2ebc538d63fedcddf89d8c9f0e86b2bb00ff164d through 7b0a020a02595d4ca1e782c8282d01bc220c84c7.

**Comment by chuckbook** [comment]
We successfully tested H7 HW I2C clocked from HSI (64MHz) with the following parameters:
```
// from datasheet (HSI = 64 MHz)
#define MICROPY_HW_I2C_BAUDRATE_TIMING { \
                                        {PYB_I2C_SPEED_SLOW,        0xf042c3c7}, \
                                        {PYB_I2C_SPEED_STANDARD,    0xb0421619}, \
                                        {PYB_I2C_SPEED_FULL,        0x5033070b}, \
                                        {PYB_I2C_SPEED_FAST,        0x50100003}, \
                                        }
```
Slave device: LCD160CR
Measured throughput: 10k, 100k, 400k and 1000k bits/s
ST tool wasn't very useful indeed.

**Pull request closed without merging**
