### PR TITLE
all: Use the name MicroPython consistently

### PR DESCRIPTION
**Pull request by webmeister**
There were several different spellings of MicroPython present in the code,
when there should be only one.

### CODE REVIEW

**Comment by pfalcon** [comment]
The reason why this patch wasn't applied before is exactly because it's a sweeping change adding a lot git log -p/git blame noise. It definitely needs to be done for 2.0 with other sweeping changes, I'm not sure that time is now. But if it's done, this change should be combined with copyright year updates (and in that sense might be better done by a maintainer).

**Comment by webmeister** [comment]
> adding a lot git log -p/git blame noise

How does this negatively affect git blame? It mostly touches lines in the copyright comment block, that probably nobody will look at anyway. (But it would have helped me in #3180, to have an easy way to identify files belonging to MicroPython by searching for the string "MicroPython" in the first comment block.)

> But if it's done, this change should be combined with copyright year updates

Is that really necessary, from a legal point of view, especially if the file has not been touched in recent years? If it is, then please do not delay applying this patch until the other changes are ready. Copyright years are in different lines than the MicroPython string, so the diff won't get any smaller.

At the moment, you have things like c408ed9 from just a few days ago, that fix this issue for maybe a single file. To me, that does not look like a better approach than fixing it once everywhere and be done with it.

**Comment by pfalcon** [comment]
> Is that really necessary, from a legal point of view, especially if the file has not been touched in recent years?

So, all files which were updated, need copyright year updated.

**Comment by webmeister** [comment]
Do you mean I should update the copyright year to include 2017 for all files that this commit touches? Or that there needs to be a commit that updates the copyright year for all files in the repository that have been touched after their specified copyright year, even if those files were not originally touched by this commit?

**Comment by pfalcon** [comment]
I, as "IMHO", would suggest that patch like this also included copyright year updates. The best next step is to wait for @dpgeorge's comments, specific details can be discussed later.

**Comment by tomlogic** [comment]
Should there be a post-commit hook to notify when files were modified but the copyright wasn't updated?

**Comment by mcauser** [comment]
According to US copyright law, you do not need to update the copyright each year on all the files.
The year is the year of first publication, not the current year.
http://www.contentious.com/2007/01/07/copyright-notice-is-the-year-really-necessary/
> If the work is a derivative work or a compilation incorporating previously published material, the year date of first publication of the derivative work or compilation is sufficient.

**Comment by dpgeorge** [comment]
Let's just do this and get it out of the way.

@webmeister please can you change only those instances of "Micro Python" that appear in comments (which I think is all instances of "Micro Python").  Anything in the docs should be a separate PR, and changes to the code should be separate (eg the change to cc3200 ftp server would be a breaking change from a users' point of view).

IMO copyright year should be changed by the author who's name appears in the copyright line, and only if/when they make non-trivial changes to the respective file.  (Eg there are some files with multiple copyright lines, and it doesn't make sense to change them all to include the year 2017 because in a lot of those cases there is nothing new by that person to copyright.)

**Comment by pfalcon** [comment]
@webmeister : Are you going to proceed with this as recommended with @dpgeorge ? Otherwise, conflicts start to accumulate, etc.

**Comment by webmeister** [comment]
Oh, sorry, I didn't notice that this was still open. Together with #3211 and #3212 I had uploaded a new version of this PR (e0415da), but I did not add another comment here, so it probably slipped through?

I can rebase the commit and check for new misspellings later.

**Comment by dpgeorge** [comment]
Thanks @webmeister for updating.  This was merged in 55f33240f3d7051d4213629e92437a36f1fac50e

**Pull request closed without merging**
