### PR TITLE
extmod: Modify cyw43_connect function to prevent crash when not specifying security parameters for open networks

### PR DESCRIPTION
**Pull request by LukeBriggsDev**
Allows user to connect to an open network without the need to provide a security parameter.

Related to #9016 and [cyw43 driver fix](https://github.com/georgerobotics/cyw43-driver/pull/45). This fix is redundant until the merge of the cyw43 driver fix.

This change sets the default `security` parameter of `network_cyw43_connect` to `0`. Without this change, fixes to the cyw43 driver will lead to a failure unless `security=0` is specified when connecting to open networks.

### CODE REVIEW

**Review by gwo0d — APPROVED** [review]
Nice change! Great improvement to functionality - very Pythonic.

**Comment by dpgeorge** [comment]
I don't understand this patch... passing -1 (the current default) indicates "auto security", and if you don't pass in a key that means it will use no security / open network.  If you do pass a key it will use `CYW43_AUTH_WPA2_MIXED_PSK`.

Making this 0 by default would mean that you must always pass in a value for the `security` keyword argument if the network is not open.

**Comment by gwo0d** [comment]
@dpgeorge if this is the intended behaviour, it is not observed in practice. After testing this, if a key is not provided, a RPI Pico W will currently throw an OS error. Having this value at 0 prevents that, and the module works as intended.

@LukeBriggsDev I'm not sure if you have anything to add here?

**Comment by LukeBriggsDev** [comment]
> @dpgeorge if this is the intended behaviour, it is not observed in practice. After testing this, if a key is not provided, a RPI Pico W will currently throw an OS error. Having this value at 0 prevents that, and the module works as intended.
> 
> @LukeBriggsDev I'm not sure if you have anything to add here?

This is correct. Currently the auto setting of security does not work as intended for open networks. I believe the trouble lies in a mismatch between the [default values](https://github.com/micropython/micropython/blob/ca346ee5bea4bf74e8f811c2ef8d571165c6d235/extmod/network_cyw43.c#L229) and the [expected values](https://github.com/georgerobotics/cyw43-driver/blob/61432f360748949ad06564193a93d9fdb5afe9dd/src/cyw43_ll.c#L2048) ,

**Comment by dpgeorge** [comment]
> if this is the intended behaviour, it is not observed in practice.

It is the intended behaviour, and indeed it is buggy!  That is, it doesn't work as it should.

> After testing this, if a key is not provided, a RPI Pico W will currently throw an OS error. Having this value at 0 prevents that, and the module works as intended.

You are right, if a key is not provided then the underlying cyw43 driver doesn't handle the -1 value correctly.  That is now fixed in the cyw43 driver (thanks to yourself!).

I also applied another fix to the cyw43 driver so that it no longer does any auto setting of security.  That auto setting is moved up into the Python bindings.  See #10273, which should fix the case of open security, and also retain the existing behaviour (that you don't need to pass in a value for `security`, it should just work).

**Comment by LukeBriggsDev** [comment]
> > if this is the intended behaviour, it is not observed in practice.
> 
> It is the intended behaviour, and indeed it is buggy! That is, it doesn't work as it should.
> 
> > After testing this, if a key is not provided, a RPI Pico W will currently throw an OS error. Having this value at 0 prevents that, and the module works as intended.
> 
> You are right, if a key is not provided then the underlying cyw43 driver doesn't handle the -1 value correctly. That is now fixed in the cyw43 driver (thanks to yourself!).
> 
> I also applied another fix to the cyw43 driver so that it no longer does any auto setting of security. That auto setting is moved up into the Python bindings. See #10273, which should fix the case of open security, and also retain the existing behaviour (that you don't need to pass in a value for `security`, it should just work).

Excellent! Much nicer. Thanks for finding a way to maintain intended behaviour and making it work.

**Pull request closed without merging**
