### PR TITLE
Fixed WizNet Wiz5500 support.

### PR DESCRIPTION
**Pull request by hjf**
Now it compiles and ifconfig() works. The chip seems to respond to PING after ifconfig.
There may be some performance optimizations that could be added too.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Is the W5500 driver backwards compatible with W5200? Does the Wiz820IO module work with the W5500 driver?  What hardware did you use to test your changes?

**Comment by hjf** [comment]
No, it's not. They are provided as different .c files, one for each chip. They should be set with the appropriate #define. I tested this with a STM32F4 Discovery and a $3 ebay W5500 module. TCP sockets seem to work (I can get an HTTP response from a remote server).

**Comment by dpgeorge** [comment]
Ok, the changes to w5500.[ch] are good, thanks!, but I can't merge the other changes because they mean that the W5200 no longer works.

A good solution would be to be able to select between W5200 and W5500 at compile time.  A better solution would be able to do it at runtime, but that's really hard (too many names/symbols clash if you compile in both drivers at once).

@hjf: Are you able to make W5200/W5500 selectable at compile time?

**Comment by hjf** [comment]
The driver already supports this, you just have to #define _WIZCHIP_=5500 or 5200, but the Makefile needs to be patched to select w5200.c or w5500.c 
MICROPY_PY_WIZNET5K is currently used to enable ethernet. But I think we'll also need to require the chip type, as in MICROPY_PY_WIZNET5K_CHIP=5200 (fail make if MICROPY_PY_WIZNET5K is defined but MICROPY_PY_WIZNET5K_CHIP is not), or define MICROPY_PY_WIZNET5K_CHIP ?= 5200, to default to 5200.
I will add the #defines for the rest of the files. Should I commit and make a new pull request?

**Comment by dpgeorge** [comment]
Yes, good idea to add `MICROPY_PY_WIZNET5K_CHIP ?= 5200` to the Makefile.

> Should I commit and make a new pull request?

Yes, please!  But just push to the branch of this PR so that it's included in this PR.

**Comment by mhanuel26** [comment]
Hi,
Are the W5500 changes going to be included in the master branch? 
I would like to use the latest version of micropython with a working w5500 driver, how should I proceed?

Please let me know,

**Comment by dpgeorge** [comment]
> Are the W5500 changes going to be included in the master branch?

I was waiting for @hjf to make the above-requested changes, then it can be merged.  @mhanuel26 you may want to pick up where @hjf left off...

**Comment by Lisa999** [comment]
Can you **PLEASE** fix the branch conflict so that it get's merged into the master branch??? I have an W5500 and it ain't working with the W5200 software. It only works on the hjf W5500 branch, which i can compile, run and use.

**Comment by hjf** [comment]
I'm sorry guys, I no longer work for the company where I used this. I don't even have the toolchain installed in my home computer. I am a now a .NET Windows Forms developer :( Sigh.

**Comment by Lisa999** [comment]
Not happy now, copied all files over to the latest master. Change 5200 to 5500 in the makefile.
Changed netutils.h to lib/netutils/ in the hjf branch file modnwwiznet5k.c
Other error appears:
`modnwwiznet5k.c:68:5: error: implicit declaration of function 'GPIO_clear_pin' [-Werror=implicit-function-declaration]
     GPIO_clear_pin(wiznet5k_obj.cs->gpio, wiznet5k_obj.cs->pin_mask);
`
W5500 IS NOT WORKING WITH A PYBOARD!!!

**Comment by dpgeorge** [comment]
Please see a simplified version of this PR at #3362, which merges cleanly with current master.

@Lisa999 are you able to test #3362?

**Comment by Lisa999** [comment]
@dpgeorge Sorry, i was busy the last few days with this: [https://www.letscontrolit.com/forum/viewtopic.php?f=14&t=3577](url)
I'm going to test today!

**Comment by dpgeorge** [comment]
Superseded by #3362.

**Pull request closed without merging**
