### PR TITLE
Super method call optimisation

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR adds the LOAD_SUPER_METHOD bytecode to allow heap-free super method calls.  See #2719 for background discussion.

This allows the following code to run without allocating on the heap:

        super().foo(...)

Before this patch such a call would allocate a super object on the heap and then load the foo method and call it right away.  The super object is only needed to perform the lookup of the method and not needed after that.  This patch makes an optimisation to allocate the super object on the C stack and
discard it right after use.

The first patch of this PR does a refactoring of the compiler's handling of super to facilitate the optimisation of super method calls.  The second patch adds the new bytecode and the third patch adds tests.  Total code size change for the PR is:

       bare-arm:  +140
        minimal:  +232
       unix x64:  +464
    unix nanbox:  +348
         stmhal:  +188
         cc3200:  +128
        esp8266:  +284

I spent a fair bit of effort to get the overall increase as low as possible.  With the first attempt it was around +300 bytes for bare-arm but I managed to get it down to half of that, which I'm quite happy with.  It's still a fair increase for all ports, and adds a new bytecode (so MPY version number needed to be increased) but probably it's worth it in the end.

### CODE REVIEW

**Comment by pfalcon** [comment]
Looks great, thanks! Yes, code size increase is noticeable, but I think it's worth it, because it's basic OO feature.

(Didn't look why travis failed.)

**Comment by dpgeorge** [comment]
> Didn't look why travis failed.

It's because the code size check for minimal failed, because the code size increased.

**Comment by dpgeorge** [comment]
@stinos any idea why the cmd_showbc.py test is failing on windows/appveyor?

**Comment by stinos** [comment]
There's a slight difference in the instruction addresses for the function with the super() call (at least I assume that is what the numbers are?):
```
--- cmd_showbc.py.exp
+++ cmd_showbc.py.out
@@ -441,12 +441,12 @@
   bc=0 line=156
 00 LOAD_GLOBAL super (cache=0)
 04 LOAD_GLOBAL __class__ (cache=0)
-08 LOAD_FAST 0
-09 LOAD_SUPER_METHOD f
-12 CALL_METHOD n=0 nkw=0
-14 POP_TOP
-15 LOAD_CONST_NONE
-16 RETURN_VALUE
+07 LOAD_FAST 0
+08 LOAD_SUPER_METHOD f
+11 CALL_METHOD n=0 nkw=0
+13 POP_TOP
+14 LOAD_CONST_NONE
+15 RETURN_VALUE
 File cmdline/cmd_showbc.py, code block '<genexpr>' (descriptor: \.\+, bytecode @\.\+ bytes)
 Raw bytecode (code_info_size=\\d\+, bytecode_size=\\d\+):
 ########
```

**Comment by dpgeorge** [comment]
> There's a slight difference in the instruction addresses for the function with the super() call

Ahh, I see, thanks for that.  The difference is that windows doesn't have persistent code enabled (ie it can't import .mpy files) so encoding of qstrs in the bytecode is variable, whereas in unix it's fixed to 2 bytes per qstr.

**Comment by stinos** [comment]
> it can't import .mpy files

Is that something which should be addressed, it's likely just a matter of enabling some definitions?

**Comment by dpgeorge** [comment]
> Is that something which should be addressed, it's likely just a matter of enabling some definitions?

I don't know if it should be... it depends what the windows port is used for.  But I guess it should mirror unix as much as possible.  It is simply a matter of enabling the MICROPY_PERSISTENT_CODE_LOAD definition.

**Comment by pfalcon** [comment]
> But I guess it should mirror unix as much as possible.

Yep, +1.

**Comment by stinos** [comment]
Indeed enabling MICROPY_PERSISTENT_CODE_LOAD makes the tests pass. It's been a while since I compared unix' mpconfigport.h vs the windows one anyway: I'll do that right now and then the last commit here isn't needed anymore.

**Comment by dpgeorge** [comment]
With some recent space-saving optimisations made to the core (mainly in the compiler, see eg ae54fbf1668959e50632034495631b0c5952ae9d) I've managed to offset a little the size increase that this patch brings.  These optimisations plus this PR have a combined change in code size of:

       bare-arm:   +32
        minimal:   +12
       unix x64:  +376
    unix nanbox:  +260
         stmhal:  +132
         cc3200:   +16
        esp8266:  +140

**Pull request merged**
