### PR TITLE
Move all ports to ports/ subdirectory, and rename "stmhal" to "stm32"

### PR DESCRIPTION
**Pull request by dpgeorge**
As discussed previously in a few places, eg #1907 and #2401, this PR creates a new sub-directory called "ports/" and moves all the MicroPython ports to that directory.

In the process, "stmhal" has been renamed "stm32" (thanks to @hoihu for suggesting this in https://github.com/micropython/micropython/issues/1907#issuecomment-322564946).  "stm32" better reflects the MCU name that it supports (so it's clearer to newcomers, among other things), and de-emphasises the role of the STM Cube HAL which ideally we'd move away from and access the peripherals directly using registers (this is already mostly done for simple things like GPIO).  It's also 1 character shorter and quite a bit easier to type :)

I'll leave this open for a bit to give everyone the chance to comment and raise any further issues.

@pfalcon can you please check that zephyr builds?

@stinos can you please check that the various version of windows build?

Thanks!

### CODE REVIEW

**Comment by stinos** [comment]
This should do it: https://github.com/stinos/micropython/commit/cbfb6225f83d0f21377f4710548037f59ca99620

Also changed the default path for the uPy binary on unix in run-tests.
You just have to login to Appveyor and point it to ports/windows/appveyor.yml in the settings.

**Comment by pfalcon** [comment]
What? Even unix port is moved??

**Comment by pfalcon** [comment]
> What? Even unix port is moved??

Nevermind of course, but it will take quite a bunch of time to get used to this new layout...

**Comment by pfalcon** [comment]
> @pfalcon can you please check that zephyr builds?

Yes, builds ok.

Given the nature of this patch (e.g., there're already conflicts, so needs to be redone from scratch), I guess this should be either merged ASAP, or vice-versa, a specific deadline is set.

**Comment by torwag** [comment]
Hi,
as there are controversial ideas about when a port should be added or dropped, would it make sense to introduce a official/maintained, staging/community , deprecated/drop soon  folder structure for the ports?
Thus, people can get pretty fast an idea what to expect.  That accompanied with a few easy rules how to move the ladder up and down would maybe help a lot.

1. official: Requires two main maintainers (lead and deputy) as well as an almost feature complete port e.g. tested by some unit test to be defined
2. staging: A port in progress with a maintainer, not yet feature completed, potentially instable and buggy  
3. deprecated: No maintainer, no backports, no longer supported, might drop out in the future.

**Comment by stinos** [comment]
That could be confusing and complicated. Also say you'd introduce a directory with a 'deprecated' port you still end up with 'live' code (as in: still in the last commit in master branch). Such code should pass all tests else it shouldn't be in master. Meaning it still should be maintained in some way, which is contradictory with 'no maintainer'. Also I'd say git branches/history got this covered already?

**Comment by pfalcon** [comment]
git forks got this covered. Everything in the mainline is maintained by definition, and unmaintainable stuff should not be let in.

**Comment by dpgeorge** [comment]
Thanks @stinos for the patches, and thanks @pfalcon for checking Zephyr.

> but it will take quite a bunch of time to get used to this new layout

Yes, a bit of time, but it will be worth it!  Also, take care that any files one has locally that are not tracked by git will need to be moved manually into the moved directories.

> would it make sense to introduce an official/maintained, staging/community , deprecated/drop soon folder structure for the ports?

@torwag I think that is unnecessarily complicated, and adds too many levels of nesting of directories.  The same thing could be achieved with a simple README file stating the state of each port, and other data like maintainer names/emails.  But that can be done at a later time, if it's at all needed.

> Given the nature of this patch (e.g., there're already conflicts, so needs to be redone from scratch), I guess this should be either merged ASAP,

I would prefere to do it ASAP, then get on with the rest of the things.

Note that the ports directory could be called "port" (no plural) and then "port/unix" would be read as "the port to unix".... But the plural version "ports" emphasises that there are many of them, and being plural follows a lot of the other top-level dirs, eg docs, tools, tests, examples, drivers.  So they are the arguments for it being "ports".

**Comment by tannewt** [comment]
Yes! Great work @dpgeorge!

**Comment by pfalcon** [comment]
> So they are the arguments for it being "ports".

Sure, "ports" is better.

> I would prefere to do it ASAP

Looking forward for this to land then.

**Comment by dpgeorge** [comment]
Right, this is done!  See 01dd7804b87d60b2deab16712eccb3b97351a9b7 and 4a93801c12898898744131f57d79cf216d0861b3

**Comment by dpgeorge** [comment]
> You just have to login to Appveyor and point it to ports/windows/appveyor.yml in the settings.

@stinos thanks for the pointer, now done.

**Pull request closed without merging**
