### PR TITLE
stmhal: fix uart buffer off by 1 bug

### PR DESCRIPTION
**Pull request by ryannathans**
patch for #1653

### CODE REVIEW

**Comment by pfalcon** [comment]
-1, see https://github.com/micropython/micropython/issues/1653#issuecomment-160270799

**Comment by ryannathans** [comment]
@pfalcon are you suggesting that we intentionally continue to provide the user with a buffer size other than what they asked for?

**Comment by pfalcon** [comment]
We provide user with the buffer size exactly of the requested figure.

Buffer is internal structure, user provides upper bound of its size and rejoices. One shouldn't have any expectations about exact details of buffer behavior, only generic ideas - that increasing buffer size improves performance, subject to law of diminishing returns - at some point, even large increase in buffer size will lead to minuscule or no increase in performance. That's all a user should know.

You're welcome to argue for useful, realistic usecase when user should have exact expectations of buffer size vs number of characters which need to fit there.

**Comment by ryannathans** [comment]
@pfalcon In my project received packets are of a fixed size, 256 bytes. The application is not bound by receiving data on the UART, there are many other tasks to perform in the background and such I'm not endlessly reading the UART byte by byte waiting for data. When allocating a buffer of 512 bytes, I expected to be able to hold two full packets - as confirmed by reading back the set buffer size. What I actually received was obviously not what I was expecting... It did not fit correctly.

It took much longer to debug this than I'm willing to admit, I assumed there was a problem with my code because reading buffer length confirmed that the buffer was, in fact 512 bytes long (when in fact it really wasn't...)

**Comment by pfalcon** [comment]
> In my project received packets are of a fixed size, 256 bytes.

So, set buffer size 5 or 10 times that and rejoice, that's how it's usually done.

Otherwise, we can't optimize micropython for your particular application - we can optimize it just generically, and you can enjoy it just the same, just making conservative assumptions (like that you need to have buffer space for several packets, not that 512 bytes buffer will fit exactly 2 packets).

Well, that's just my opinion, other folks may see it differently.

**Comment by peterhinch** [comment]
@pfalcon I entirely agree with your point about allocating a generous size. But not everyone will be aware of this practice and if the current implementation is going to confuse users why not implement @dhylands idea of allocating one byte more than the user requested? From the user point of view this is buffer size: the fact that one location is always empty is transparent to the user.

**Comment by ryannathans** [comment]
Can admin make a decision regarding the API so we can move on with life?

As far as I see it, the user should be able to know how big the buffer is. Either implement a function that can query the buffer size and document that setting the buffer to n bytes is actually n-1 or extend buffer by 1 byte so the requested size is the usable size.

**Comment by pfalcon** [comment]
@ryannathans : @dpgeorge is the admin and in his comment https://github.com/micropython/micropython/issues/1653#issuecomment-160765317 he agrees that this is an issue, and the patch like yours is the most obvious way to address it of course. It will be merged when will be formally tested. In the meantime, if you want to improve your patch, it would be better to avoid comments like "-1 part of #1653" - a random reader won't even know what #1653 is, and generally, comments should be as self-contained as possible. So, I'd suggest replacing that with something like "Payload size of ring buffer is one byte less than allocated size, so adjust for that".

**Comment by ryannathans** [comment]
@pfalcon good point about the comment. Will fix

**Comment by dpgeorge** [comment]
Once comment is fixed I will merge.

**Comment by dpgeorge** [comment]
Merged in c03dd3b2f94370b9126dfb1bcd5429beb4b6e76d.  Thanks @ryannathans!

**Pull request closed without merging**
