### PR TITLE
ports/esp32/machine_i2s.c: specify mck_io_num.

### PR DESCRIPTION
**Pull request by oclyke**
Solves #7853.

### CODE REVIEW

**Comment by miketeachman** [comment]
You will need to add some conditional compilation as this I2S parameter is not supported for ESP-IDF versions that are presentably used by MicroPython (v4.0.2, v4.1.1 and v4.2)

What ESP32 hardware variant are you using?
What version of ESP-IDF?

**Comment by oclyke** [comment]
I was using version ```v4.4-dev-3224-g23a03a3bdb```

I need to go back and reevaluate with one of the proper supported versions of the IDF - I thought there was a reason that I moved up to the latest...

I'll report back asap

**Comment by miketeachman** [comment]
@oclyke I made a separate PR to address this issue and other issues related to ESP-IDF v4.4. 
https://github.com/micropython/micropython/pull/8110
If you are happy with this new PR you might want to close this PR.  thanks.

**Comment by jd3096-mpy** [comment]
> @oclyke I made a separate PR to address this issue and other issues related to ESP-IDF v4.4. #8110 If you are happy with this new PR you might want to close this PR. thanks.

this error is still here ,for esp32s3?
my fireware is MicroPython v1.19.1-722-g1b774b373-dirty on 2022-11-29
here is my code:
audio_in = I2S(0,
               sck=bck_pin, ws=ws_pin, sd=sdin_pin,mck=mck_pin,
               mode=I2S.RX,
               bits=16,
               format=I2S.MONO,
               rate=8000,
               ibuf=64000)

TypeError: extra keyword arguments given

but if i del mck ,it works normally
like this:
audio_in = I2S(0,
               sck=bck_pin, ws=ws_pin, sd=sdin_pin,
               mode=I2S.RX,
               bits=16,
               format=I2S.MONO,
               rate=8000,
               ibuf=64000)

**Comment by RonTang** [comment]
> > @oclyke I made a separate PR to address this issue and other issues related to ESP-IDF v4.4. #8110 If you are happy with this new PR you might want to close this PR. thanks.
> 
> this error is still here ,for esp32s3? my fireware is MicroPython v1.19.1-722-g1b774b373-dirty on 2022-11-29 here is my code: audio_in = I2S(0, sck=bck_pin, ws=ws_pin, sd=sdin_pin,mck=mck_pin, mode=I2S.RX, bits=16, format=I2S.MONO, rate=8000, ibuf=64000)
> 
> TypeError: extra keyword arguments given
> 
> but if i del mck ,it works normally like this: audio_in = I2S(0, sck=bck_pin, ws=ws_pin, sd=sdin_pin, mode=I2S.RX, bits=16, format=I2S.MONO, rate=8000, ibuf=64000)

At current, I also have the same problem~ MicroPython (1.25.0)  ESP32-S3

**Pull request closed without merging**
