### PR TITLE
Raspberry Pi baremetal port

### PR DESCRIPTION
**Pull request by naums**
This is a (clean) Raspberry Pi-port. There is no REPL at the moment, just executed hardcoded strings using the `do_str`-routine. For testing purposes the code can also be built and ran on QEMU, set the `BOARD` variable in the Makefile to "qemu".

### CODE REVIEW

**Comment by Neon22** [comment]
How would you characterise the nature of the difference between this and the unix build ?

**Comment by stinos** [comment]
^ that's a good question indeed, last time I tested it (a while ago though) uPy built straight out of the box on a Raspberry Pi. Is this like unix port + (not yet implemented) support for uart/jtag? That could just be built as modules?

Btw you have some dead code in the files, that is one roadblock to getting it merged.

**Comment by WayneKeenan** [comment]
It's targeting his custom [bare-metal/embedded OS](https://github.com/naums/PiOS) not a unix/posix environment.

**Comment by naums** [comment]
This is a bare-metal port for the Raspberry Pi (and QEMU versatilepb for that matter). Run make, then you'll have a kernel.img you can copy over to a Raspberry Pi-SD-card and boot the Raspberry Pi from it. This has nothing to do with the Unix-port, and does not need any operating system running on the Raspberry Pi to run. 

The dead code @stinos is referring to is probably PiOS, right? This is another project of mine, @WayneKeenan already pointed out. I'm using this collection of "drivers" in the Micropython port for UART on both QEMU and Raspberry Pi and JTAG-support. If you don't like the dependency to the external project - I can copy the necessary files into the port itself. That includes gpio.c, both uart.c's, jtag.c + header-files, and everything from the boards-directory. 

PS: the word embedded OS for PiOS is a bit to much. It's rather a selection of drivers with bare-minimum boot-code (at the moment).

**Comment by stinos** [comment]
> This is a bare-metal port for the Raspberry Pi (and QEMU versatilepb for that matter). Run make, then you'll have a kernel.img you can copy over to a Raspberry Pi-SD-card and boot the Raspberry Pi from it.

Neat!

> The dead code @stinos is referring to is probably PiOS, right?

no, the commented out code lines in this commit which don't serve as documentation. Just to name one: main.c line 126 has `//blinkloop();` which is obvioulsy a leftover from playing around

**Review by pfalcon — CHANGES_REQUESTED** [review]
The blocking reason why this can't be merged is that this adds GPLed module to the MicroPython codebase. MicroPython goes under liberal MIT license.

Otherwise please be sure to follow https://github.com/micropython/micropython/blob/master/CODECONVENTIONS.md

**Comment by naums** [comment]
done.

**Pull request closed without merging**
