### PR TITLE
Add support for NUCLEO-H743ZI2 board

### PR DESCRIPTION
**Pull request by rolandvs**
Basic definitions for the newer H743 board.
Some GPIO is relocated compared to the old(er) H743ZI boards
Also features the STLINKv3.
Notes some peculiarities that are good to know
Tested REPL, USB, SDCARD, DFU

### CODE REVIEW

**Comment by ccccmagicboy** [comment]
Can the ethernet part work？

**Comment by rolandvs** [comment]
That needs work. There are differences in comparison with the NUCLEO_F767. Probably not to much work, but the next weeks I have no time to get into it.

**Comment by dpgeorge** [comment]
Sorry I didn't see this until now.  It would be good to support this board (and I still need to get one to test...).

**Comment by rolandvs** [comment]
I make some more changes and return...

**Comment by chhartmann** [comment]
Is it still planned to add support for NUCLEO-H743ZI2 board?

**Comment by rolandvs** [comment]
Yes it is, but at this moment and the next few weeks I do not have the time to update it further.

**Comment by chhartmann** [comment]
Thanks for the info - looking forward to it. I used your patch and build and flashed it and it seems to work - except for the ethernet part, which is disable in the config file. Could you give me a hint, why it is not working?

**Comment by rolandvs** [comment]
- Lots of definitions used in the HAL regarding the H743 are different from for instance the F767 and needs changes in the Ethernet driver.
- The STLINK3 is on board and is not supported yet (last time I checked). However USB-DFU works fine.

**Pull request closed without merging**
