### PR TITLE
esp8266: Remove unused MODE constanst from modesp

### PR DESCRIPTION
**Pull request by deshipu**
Since all the connection functions were moved to modnetwork, which
has its own constants, with different values, those are not needed
anymore.

### CODE REVIEW

**Comment by pfalcon** [comment]
This patch isn't exactly correct. MODE_11* shouldn't be removed, but rather moved to modnetwork (now done). But general approach to clean up is "A lot of code will need to be removed. Later, when new code will be well proven." So, cleanups will have to wait till we master cases like #1946 and similar.

**Comment by deshipu** [comment]
I see, sorry, I just saw something I though I knew how to do, so I wanted to help. I guess reviewing trivial patches is as much work as writing them, so that doesn't really help. I didn't thought this trough.

**Comment by pfalcon** [comment]
@deshipu : I'd really appreciate if you didn't lead the interaction in directions it was to previously. The help is always appreciated. At the same time, we have a lot of work to do ourselves, so any work crossing our development line will only require extra time to deal with, and if exercised regularly, may lead to risk of breaking the development schedule. So we have little choice what to do: either ignore sideways patches until release, or still process some of them. As you're a regular contributor, I do pay attention to your patches, but if one isn't correct, that's the response you get, as well as I share development insights to avoid further "mis-scheduled" effort. Thanks for understanding.

**Comment by deshipu** [comment]
Yes, I understand that, and I'm really sorry -- I didn't think about this, and I absolutely agree that it was stupid of me to waste your time with this. I'm being honest here and I not cynical or anything. Really. I'm not complaining, and I'm happy you are working on this, and I will try to focus on testing, which seems to be genuinely helpful here.

**Comment by pfalcon** [comment]
Thanks: http://forum.micropython.org/viewtopic.php?f=16&t=1731

**Pull request closed without merging**
