### PR TITLE
Add new make target "submodules" which inits required modules.

### PR DESCRIPTION
**Pull request by dpgeorge**
Because there are now a lot of submodules in this project, and only a subset are needed for any given port, introduce a new make target called `submodules` which initialises only the required modules.

### CODE REVIEW

**Comment by andrewleech** [comment]
Looks like a clean change to me. Doesn't nrf target want tinyusb now as well?

**Comment by dpgeorge** [comment]
> Doesn't nrf target want tinyusb now as well?

Yes indeed, for the nRF52840 MCUs.

**Comment by stinos** [comment]
Good idea, also makes build more self-contained. There are still README files containing information about submodules, mainly in the build instructions. Technically the information is still correct, but I think it would be better to update it.

**Comment by dpgeorge** [comment]
> There are still README files containing information about submodules, mainly in the build instructions.

Ok, I updated these (and README's in general need an overhaul).

**Pull request merged**
