### PR TITLE
extmod/machine_mem: Add slice support to memory object.

### PR DESCRIPTION
**Pull request by p3we**
Use slice to create a new mem object bound to a fragment of memory address space. It is useful for passing around registers that are relevant to a given peripheral. For example one can create a function that may work on any of STM32 timers by taking as an parameter a memory slice that start at the address of the first timer register.

### CODE REVIEW

**Comment by jimmo** [comment]
@p3we Thanks, I can see why this is a useful feature.

FWIW, we do kind of support a byte-addressable version of this with https://docs.micropython.org/en/latest/library/uctypes.html#uctypes.bytearray_at

The modification in this PR to `machine_mem_obj_t` is essentially making it identical to a memoryview. I wonder if we could just use `memoryview` directly -- i.e. have the subscr operator return a memoryview instance (with type code B, H, I for mem8, mem16, mem32 respectively).

memoryviews already know about object sizes -- you can construct a memoryview from array.array for example.

**Comment by jimmo** [comment]
That idea to use memoryview might need some thought around `MICROPY_MACHINE_MEM_GET_READ_ADDR` / `MICROPY_MACHINE_MEM_GET_WRITE_ADDR`...

**Comment by p3we** [comment]
Hi @jimmo Yes, I see how this feature is quite similar to memoryview, I even thought about implementing buffer protocol for mechine_mem object. However I think there is a slight but important difference between those two objects in the way how they are indexed. Generally memoryview is indexed by the position of the element in the array, where machine_mem object is always addressed by the memory address. For example I would like to be able to write a following code:
```
import stm
tim3 = stm.mem16[stm.TIM3]
tim3[stm.TIM_CCMR1] = (0xC << 12) | (0xC << 4)
```
So the size of the element is 2 bytes in that case and stm.TIM_CCMR1 value is a byte offset from the base timer address. A memoryview object would not expect an offset in bytes, but the index of the element that would be multiplied by element size internally to get an actual memory address. In this context using memory view as a return value of subscr operator would require to divide stm.TIM_CCMR1 by the size of element, what I wanted to avoid.

**Comment by dlech** [comment]
uctypes seems like a better fit for this use case. It even allows for bitfields.

**Comment by p3we** [comment]
@dlech Thanks, indeed uctypes is perfect for my use case. 
```python
import stm, uctypes
tim3 = uctypes.struct(stm.TIM3, {"CCMR1": stm.TIM_CCMR1 | uctypes.UINT16})
tim3.CCMR1 = (0xC << 12) | (0xC << 4)
```
I guess this PR may be dismissed. Moreover it looks like machine_mem should be deprecated.

**Pull request closed without merging**
