### PR TITLE
mpy-cross: Respect existing CFLAGS and LDFLAGS

### PR DESCRIPTION
**Pull request by yangfl**

### CODE REVIEW

**Comment by dlech** [comment]
What problem are you trying to solve? ` CFLAGS_EXTRA` and `LDFLAGS_EXTRA` are already provided for passing additional flags as arguments to `make`.

**Comment by yangfl** [comment]
Oops, I didn't notice this. But what I want to do is to keep pace with https://github.com/micropython/micropython/blob/master/ports/unix/Makefile#L42

**Comment by dpgeorge** [comment]
I think this change is OK, many other Makefile variables use `+=` at their first use in the Makefile.

**Comment by dpgeorge** [comment]
I know this PR is a minor change, but we do require a proper email address for contributes to core code components.  So please can you update your email address.

**Comment by yangfl** [comment]
email changed

**Comment by dpgeorge** [comment]
Thanks for updating.  Rebased and merged in d7ef90122e9215b5a5f47b5a340b29e2666fa164

**Pull request closed without merging**
