### PR TITLE
unix/modtime: Implement sleep_ms(), sleep_us(), ticks_ms/us/diff()

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by pfalcon** [comment]
So, this patch is pretty straightforward and mostly a FYI that ideas in https://github.com/micropython/micropython/issues/1225#issuecomment-114465157 are finally being implemented.

**Comment by dpgeorge** [comment]
Looks good to me.

BTW, @danicampora has implemented the full set (sleep_xx and ticks_xx) in the cc3200 port.

Also, it's a bit unfortunate that time.sleep is completely different in semantics to machine.sleep... :(

**Comment by dpgeorge** [comment]
@pfalcon is this ok to merge?

**Comment by pfalcon** [comment]
> is this ok to merge?

Well, I kinda wanted to review cc3200, post ticks_* my implementation, and discuss it all a bit... So, will post draft comments I had in my mind.

**Comment by pfalcon** [comment]
> BTW, @danicampora has implemented the full set (sleep_xx and ticks_xx) in the cc3200 port.

I missed this, hoped that a comment would be posted to #1225 when somebody starts to implement it.

Ok, I looked at cc3200 implementation, and even with simple sleep_*(), there's a difference. @danicampora treats negative delays as 0, and I'm happy to leave behavior undefined in this case.

With ticks_*(), there're even more things to ponder about. It's fair to expect that ticks_diff() should return positive number (if arguments are ticks_diff(old, new) and are always given in that order (result with opposite order is undefined) - that's not even documented in #1225 or new hw api wiki). Then it should be 30 bit. And then ticks_ms/us/cpu also should provide positive 30 bit number, or otherwise ticks_diff() won't be able to provide expected result. I don't see such handling in cc3200 implementation. Instead, implementation there talks in comments about relying on internal implementation details of MP_OBJ_NEW_SMALL_INT(), which makes me think it doesn't do correct thing. I wanted to check that closer though, hence the delay, but now I just post draft thoughts on that.

**Comment by danicampora** [comment]
@pfalcon, ok I'll check your comments.

**Comment by pfalcon** [comment]
> ok I'll check your comments.

Thanks. It probably would be nice if told (in words) how you wanted ticks_* to work, and then we can check with my description above.

**Comment by danicampora** [comment]
@pfalcon, CC3200's implementation is just a copy and paste from the original time functions in the pyb module. I didn't have time to analyse everything in depth, but I agree that we should do that now and fine tune the behaviour.

**Comment by danicampora** [comment]
I understood that ticks_* would be simply a number showing the numbers of ms/us since the MCU was powered. I really didn't think about wrapping behaviour or number of bits. I am happy to change the implementation to fit what you have in mind since you were the one to that defined those methods.

**Comment by pfalcon** [comment]
Ok, so I updated this PR to also include my ticks_*() implementation, please see if it makes sense, and if it does, I'll update Hew HW API wiki with more details for these functions, as describe above.

**Comment by danicampora** [comment]
@pfalcon your implementation makes sense. I'll change CC3200's implementation to make the values 30-bit. What about `ticks_cpu`?

**Comment by pfalcon** [comment]
> What about ticks_cpu?

Its result also run thru to ticks_diff(), so it should have same constraint on representation, i.e. be 30-bit.

**Comment by pfalcon** [comment]
I've updated NewHWAPI, please see if it makes sense: https://github.com/micropython/micropython/wiki/Hardware-API/_compare/afc160fea3b2d4df15296a101960fb468c6cb340...74e4267118eb4494bc2474eae447068bd7dc445f

**Comment by danicampora** [comment]
Looks good. Thanks.

**Comment by dpgeorge** [comment]
I agree with everything, except that I think we should handle the case of negative arguments to sleep.  Well, at the moment it's unspecified behaviour, so a given port is free to actually check for negative numbers and raise an exception or clamp them.  So I'd be happy to leave it if you think that it's fair for an implementation to provide such a "safety net".

**Comment by pfalcon** [comment]
>  Well, at the moment it's unspecified behaviour, so a given port is free to actually check for negative numbers and raise an exception or clamp them. So I'd be happy to leave it if you think that it's fair for an implementation to provide such a "safety net".

I'm thinking just that - a particular implementation can do anything of that, or nothing at all. And I'd actually suggest for WiPy/PyBoard to clamp values like @danicampora does (and for unix, I'd like to keep dreaming that @viper can recognize those functions and optimize them to super-efficient code, where each instruction is counted ;-) ).

**Comment by pfalcon** [comment]
> Also, it's a bit unfortunate that time.sleep is completely different in semantics to machine.sleep... :(

Ah I missed to add I-told-you-so style comment to this one. You remember guys when I expressed concern that "sleep" may be not the best terminology from the Python point of view for this. And you with @danicampora both told it's generally accepted industry terminology, ARM uses it, etc. (Indeed it is, but as pointed out, there's other terminology which avoids using "sleep" term, as used by Linux, ACPI, etc.)

**Comment by dpgeorge** [comment]
> And I'd actually suggest for WiPy/PyBoard to clamp values like @danicampora does

That's how it's been done since a while now (see bff1ff28eec5611a2e963601b98044135694df57); cc3200 implementation was copied from stmhal's.

> I'd like to keep dreaming that @viper can recognize those functions and optimize them to super-efficient code

Yes, it sure could recognise `time.sleep_us`, with integer argument, and call the underlying HAL directly (or do anything).  Of course that will lead to a lot of extra code in the native emitter, but there is a clear path for such additions.

**Comment by dpgeorge** [comment]
> You remember guys when I expressed concern that "sleep" may be not the best terminology from the Python point of view for this.

Sorry, but you did suggest "deepsleep" for lowest power-saving mode.  And it seems you didn't like "sleep" for the name of "wfi".

> there's other terminology which avoids using "sleep" term

You mean "suspend" and "hibernate"?  But IIRC you were against those because they were for "big machines".  Were there other concrete suggestions for what is now called idle/sleep/deepsleep?

**Comment by pfalcon** [comment]
Well, I don't remember all the details now (and don't want to dig them out now), but I definitely felt intuitive discomfort with "sleep" because it's pretty overloaded term, and "suspend" and "standby" were offered as alternatives, even if lowest mode was still called "deepsleep".

**Comment by dpgeorge** [comment]
The main reason for using sleep/deepsleep is that it's completely obvious which is the lower power saving mode of the 2.  With any other pair of words you need to think twice.

**Comment by danicampora** [comment]
@pfalcon I'll fix the cc3200 implementation once you merge this PR (in order to use `MP_SMALL_INT_POSITIVE_MASK`)

**Comment by pfalcon** [comment]
Ok, merged.

**Pull request closed without merging**
