### PR TITLE
stm32: Use lib/wiznet5k instead of drivers/wiznet5k.

### PR DESCRIPTION
**Pull request by robert-hh**
This PR uses lib/wiznet5k instead of drivers/wiznet5k, like the rp2040 port already does. The change was initiated by @omogenot, and I picked up the baton for test, bug fixing and completion. See the thread at issue #9013. I tested the code change with a Wiznet W5500 breakout, with and without LWIP support. The performance is equivalent to the W5500 support for RP2040.
Two notes:
- The last commit in this PR consists of the combined changes of PR #8974, so testing runs well. This last commit can either be removed, or the other PR gets obsolete.
- There is a hiccup in the CI of this PR. If I include lib/wiznet5k as a submodule only in builds for W5x00 devices, then it is not pulled in the CI build and it fails because of the missing files. If I included lib/wiznet5k unconditionally, the build with cc3k support fails. What could be done?

### CODE REVIEW

**Comment by omogenot** [comment]
@robert-hh 
In the rp2 port, there is a CMakeList.txt file, which does not exist for the stm32, that contains a definition for an extra git submodule under the condition `if (MICROPY_PY_NETWORK_WIZNET5K)`:
`string(CONCAT GIT_SUBMODULES "${GIT_SUBMODULES} " lib/wiznet5k)`.
This is probably missing in the Makefile of the stm32 port. There is at line 38 in the file the following statement:
`GIT_SUBMODULES += lib/libhydrogen lib/lwip lib/mbedtls lib/stm32lib`
And we should probably add in the `ifneq ($(MICROPY_PY_NETWORK_WIZNET5K),0)` block a line like:
`GIT_SUBMODULES += lib/wiznet5k` to make sure that this git submodule is added. What do you think?

**Comment by omogenot** [comment]
@robert-hh 
What about:
```
ifneq ($(MICROPY_PY_CC3K),1)
GIT_SUBMODULES += lib/wiznet5k
endif
```
in `Makefile` after line 38:
`GIT_SUBMODULES += lib/libhydrogen lib/lwip lib/mbedtls lib/stm32lib`

**Comment by robert-hh** [comment]
There's already a conditional `GIT_SUBMODULES += lib/wiznet5k` in the block of `ifneq ($(MICROPY_PY_NETWORK_WIZNET5K),0)`. And I placed that for tests already after the other GIT_SUBMODULES statement. at line 38. No change.

**Comment by omogenot** [comment]
> There's already a conditional `GIT_SUBMODULES += lib/wiznet5k` in the block of `ifneq ($(MICROPY_PY_NETWORK_WIZNET5K),0)`. And I placed that for tests already after the other GIT_SUBMODULES statement. at line 38. No change.

I propose to do a conditional `GIT_SUBMODULES += lib/wiznet5k` with a **CC3K** condition instead:
```
# CC3K vs WIZNET driver incompatibility workaround
ifneq ($(MICROPY_PY_CC3K),1)
GIT_SUBMODULES += lib/wiznet5k
endif
```
It might not be an obvious workaround if someone reads the makefile in the future, but I kind of remember that you told me that this CC3K was obsolete, no?

**Comment by robert-hh** [comment]
No. That does not help. It looks like the problem is in ci.sh. The respective section is below:
```
function ci_stm32_pyb_build {
    make ${MAKEOPTS} -C mpy-cross
    make ${MAKEOPTS} -C ports/stm32 submodules
    git submodule update --init lib/btstack
    git submodule update --init lib/mynewt-nimble
    make ${MAKEOPTS} -C ports/stm32 BOARD=PYBV11 MICROPY_PY_NETWORK_WIZNET5K=5200 MICROPY_PY_CC3K=1 USER_C_MODULES=../../examples/usercmodule
    make ${MAKEOPTS} -C ports/stm32 BOARD=PYBD_SF2
    make ${MAKEOPTS} -C ports/stm32 BOARD=PYBD_SF6 NANBOX=1 MICROPY_BLUETOOTH_NIMBLE=0 MICROPY_BLUETOOTH_BTSTACK=1
    make ${MAKEOPTS} -C ports/stm32/mboot BOARD=PYBV10 CFLAGS_EXTRA='-DMBOOT_FSLOAD=1 -DMBOOT_VFS_LFS2=1'
    make ${MAKEOPTS} -C ports/stm32/mboot BOARD=PYBD_SF6
    make ${MAKEOPTS} -C ports/stm32/mboot BOARD=STM32F769DISC CFLAGS_EXTRA='-DMBOOT_ADDRESS_SPACE_64BIT=1 -DMBOOT_SDCARD_ADDR=0x100000000ULL -DMBOOT_SDCARD_BYTE_SIZE=0x400000000ULL -DMBOOT_FSLOAD=1 -DMBOOT_VFS_FAT=1'
```

**Comment by robert-hh** [comment]
I'll close that for now to do a silent test for ci.sh changes.

**Comment by omogenot** [comment]
Apparently the main issues are:
```
drivers/cc3000/inc/socket.h:67: error: "SOCK_STREAM" redefined
drivers/cc3000/inc/socket.h:67: error: "SOCK_DGRAM" redefined
```
I will try to do a `#ifdef` `#undef` to see if it goes further

**Comment by robert-hh** [comment]
`MICROPY_PY_NETWORK_CYW43=1` is for PYBD_SFxx.

**Comment by robert-hh** [comment]
I have a proper set-up, ci passes. I'm just cleaning it now and run a further test.

**Comment by robert-hh** [comment]
I changed ci.sh in splitting the builds for wiznet5k and cc3k.

**Pull request closed without merging**
