### PR TITLE
create nios2 port

### PR DESCRIPTION
**Pull request by bitmachinejc**
Hello. The purpose of this commit is to create the Altera nios2 processor port.
This family of processors use a soft-core architecture (FPGA based).

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution!

But, there doesn't look to be that much port-specific code here, mostly it is based on unix/minimal, correct?  You are using stdio read/write for IO.  So I don't think that justifies it having a top-level directory.

Perhaps we need a new repository for ports like this which can serve as examples and working code, so that we don't burden the main repo.

**Comment by pfalcon** [comment]
As far as I can tell, this is based on minimal port, not unix/minimal. And indeed, there doesn't seem to be anything to call "port" - it's just standard micropython POSIX port cross-compiled for particular architecture.

What we need is repository to host (known working/maintained) crosscompiling scripts. I've been hosting such for a while in my fork repo: https://github.com/pfalcon/micropython/tree/cross . Sooner or later, I'd like that to be moved to main repo (but still to a branch, to rebase it), and serve a basis for https://github.com/micropython/micropython/issues/1295

**Comment by dpgeorge** [comment]
> As far as I can tell, this is based on minimal port, not unix/minimal.

It has unix signal handler code as well as termios stuff from unix.

**Comment by bitmachinejc** [comment]
The port so far is bare bones, in that you can run a script from memory. The nios2 API and compiler set is similar to Linux. There are some differences here and there. The tree is here for further development:
https://github.com/bitmachinejc/micropython-nios2/tree/nios2
I'll also look at https://github.com/pfalcon/micropython/tree/cross

**Comment by dpgeorge** [comment]
This issue is pretty old now, so I'll close it with the following points:

**Comment by dpgeorge** [comment]
Points:
- zephyr supports Nios-II on the Altera MAX10, so MicroPython can be run on Nios-II via the zephyr port.
- eventually we'd like a common mechanism to support cross-compiling a generic port of MicroPython to various architectures, and this would be through libmicropython.a (see #5964)

**Pull request closed without merging**
