### PR TITLE
unix: Add support for executing directories (by searching for the __main__.py module).

### PR DESCRIPTION
**Pull request by Jongy**
Follows CPython's handling regarding error codes and prints.

#3975

### CODE REVIEW

**Comment by pfalcon** [comment]
That's a pretty weird feature. Instead of it, I'd suggest to implement CPython-compatible `-m` option handling for packages (where if package is an argument for `-m`, then `__main__` module is that package is what actually gets imported). That's much more useful than "executing directories".

**Comment by Jongy** [comment]
> That's a pretty weird feature

I agree, but I also think `-m` is weird. I've implemented this feature it for compatibility with CPython, just like `-m` is another compatibility feature which can be implemented separately.

The only reason I see for not inserting this is if we care too much about the little increase in code size.

**Comment by pfalcon** [comment]
> The only reason I see for not inserting this is if we care too much about the little increase in code size.

We always do.

And actually, heh, `__main__.py` handling for packages is actually implemented. Then why I still do `-m foo.__main__` ?

**Comment by Jongy** [comment]
Size increase is about 300 bytes for an `x86` compilation.

> And actually, heh, `__main__.py` handling for packages is actually implemented. Then why I still do `-m foo.__main__` ?

Yeah it's indeed somewhat broken.

```
$ pwd
/path/to/micropython
$ cat __main__.py
print(1)
$ micropython -m .
1
$ micropython -m ../micropython
ImportError
$ python -m ../micropython
/usr/bin/python: Relative module names not supported
$ python -m .
/usr/bin/python: Relative module names not supported
```
So I'm not sure, after all...

**Comment by pfalcon** [comment]
-m argument is a package name, and it works ok:

~~~
$ find .
.
./foo
./foo/bar
./foo/bar/__main__.py

$ micropython -m foo.bar
hello, __main__.py
~~~

**Comment by dpgeorge** [comment]
I'll close this because it's not an often-requested feature.  And the alternative of using `-m` already works.

**Pull request closed without merging**
