### PR TITLE
ports/nxp: Add nxp mcu port

### PR DESCRIPTION
**Pull request by Albort12138**
Enable NXP evkmimxrt1064 board

Signed-off-by: Albort Xue <yao.xue@nxp.com>

### CODE REVIEW

**Comment by yanyao12138** [comment]
This pull request is to Enable NXP's MIMXRT1064-EVK board. Currently, this patch only enables a few modules of the MCU. I newed the folder under 'lib/' and named it as "nxplib" to store NXP's device drivers. Under 'port/', I newed 'nxp' folder to contain the port of MicroPython to  NXP's MIMXRT1064 MCU.  I don't change the language core code except add the new submodule(lvgl), however, the code size check is failed. I will be grateful if someone can give me some advice.

**Comment by yanyao12138** [comment]
This is not related to the Micropython and OpenMV port. We have the plan to Integrate Micropython and NXP MIMXRT series MCU. So take MIMXRT1064 EVK board as the try.

**Comment by dpgeorge** [comment]
Thanks for the PR.

As it stands it's not possible to review this because there is too much new code, over 1600 new files and 800k+ lines.

To improve the situation the first thing to do would be make all the support libraries (eg nxplib, freertos) git submodules and split the PR into multiple, logically separate commits.

**Comment by yanyao12138** [comment]
> Thanks for the PR.
> 
> As it stands it's not possible to review this because there is too much new code, over 1600 new files and 800k+ lines.
> 
> To improve the situation the first thing to do would be make all the support libraries (eg nxplib, freertos) git submodules and split the PR into multiple, logically separate commits.

Thanks for your comments, It is very useful to me. I will split the PR

**Comment by yanyao12138** [comment]
> Thanks for the PR.
> 
> As it stands it's not possible to review this because there is too much new code, over 1600 new files and 800k+ lines.
> 
> To improve the situation the first thing to do would be make all the support libraries (eg nxplib, freertos) git submodules and split the PR into multiple, logically separate commits

**Pull request closed without merging**
