### PR TITLE
esp8266/modmachine: idle(): Return number of CPU cycles spent idling.

### PR DESCRIPTION
**Pull request by pfalcon**
Useful to better understand esp8266 inner workings and compare behavior
in different cases.

### CODE REVIEW

**Comment by pfalcon** [comment]
I propose to apply following patch. There's a lot to research and investigate in esp8266, and introspection guides like this are useful.

**Comment by dpgeorge** [comment]
Probably you need to use ticks_diff to handle overflow of the counter.

I'd be ok adding this to just esp8266 port since it's backwards compatible with the API.  Would you propose that all other ports follow suit?  Well, I guess first step is to see how useful this is on esp, then promote it to a change to the machine docs (and hence other ports) if wanted.

**Comment by pfalcon** [comment]
> Would you propose that all other ports follow suit?

Of course no. That's internal, undocumented (in the official docs), "reverse engineering" helper just for esp8266.

Overflow doesn't happen, and even if it does (CPU idles for 10+s), nevermind.

**Comment by dpgeorge** [comment]
> Overflow doesn't happen

True.  Since you use full 32-bit arithmetic for the difference it will handle overflow automatically.

**Comment by pfalcon** [comment]
I mean, from testing, return values are usually under 1M, so uPy small int overflow isn't expected to happen in realistic scenarios.

**Comment by pfalcon** [comment]
And unrelated question - we almost 100% lately have CI failures for changes, in coveralls. He it shows "Coverage increased (+0.002%) to 89.511%", and yet it's "failed". Does anybody know what happens?

**Comment by dpgeorge** [comment]
> And unrelated question - we almost 100% lately have CI failures for changes, in coveralls.

If it's below 90% coverage then it's by default a failure.  That threshold can be changed, but would be nicer to actually get above 90% :)

**Comment by pfalcon** [comment]
I see, makes sense ;-).

**Comment by pfalcon** [comment]
(Though for pull requests, it would make sense to "pass" in coverage increases or stays the same, and "fail" otehrwise.)

**Comment by pfalcon** [comment]
Ok, merged.

**Pull request closed without merging**
