### PR TITLE
NUCLEO_F091RC fixing pin definitions

### PR DESCRIPTION
**Pull request by rolandvs**
Added some more pins that were missing, added Arduino labels for connector.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks, but please try to remove the unrelated F767 stuff and the DS store's.

**Comment by rolandvs** [comment]
I have some problems with git. :-( I try to do better :-)

**Comment by dpgeorge** [comment]
Ok, I took 2 commits from here and cleaned them up and merged them: 0d3de686692e25c85d322c626921bc982a79581d has fixes to the F091 af.csv, and ca2b1d6b36b11706b537eba90144469ba28561d2 has additions to the NUCLEO_F091RC pins.csv file.

**Comment by dpgeorge** [comment]
> Could you update .gitignore with the .DS_Store file from Mac OSX anyway?

You can make a global gitignore setting so that the file is ignored for all your repos, eg see the 3rd answer here: https://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository

**Pull request closed without merging**
