### PR TITLE
Fix memory leaks on soft reboot

### PR DESCRIPTION
**Pull request by iSevenDays**

### CODE REVIEW

**Comment by dpgeorge** [comment]
This won't fix any problems.  The call to mp_reset() after your added code will completely reset the uPy heap, so there's no need to explicitly call gc_collect().  The only thing gc_collect() might do is call some finalisers, but finalisation's not enabled on this port.

The ENOMEM is out of memory from the underlying O/S, not from MicroPython itself.

**Comment by iSevenDays** [comment]
@dpgeorge thanks, so it seems that ESP8266 can not handle websockets for programming like FTP for WiPy?

https://github.com/micropython/micropython/issues/2303

**Comment by dpgeorge** [comment]
> so it seems that ESP8266 can not handle websockets for programming like FTP for WiPy?

No, webrepl does not support soft reset.  A way to make Pymakr work would be to not do a soft reset after uploading a file, or to do a hard-reset and then reconnect.

**Comment by pfalcon** [comment]
As explained, this doesn't fixes the problem. See https://github.com/micropython/micropython/issues/1896 for the underlying problem. Research in that direction is welcome.

**Pull request closed without merging**
