### PR TITLE
mpprint: assertion no longer holds

### PR DESCRIPTION
**Pull request by texane**
see https://github.com/micropython/micropython/issues/1661

### CODE REVIEW

**Comment by dpgeorge** [comment]
Since the assert(0) was never hit by our tests we will now need some way to test this.

**Comment by texane** [comment]
I used the following code in unix/main.c:

```
            ...
            mp_obj_t in1;
            mp_obj_t in2;

            in1 = mp_obj_new_int(42);
            in2 = mp_obj_new_float(-42.43);
            mp_store_name(QSTR_FROM_STR_STATIC("in1"), in1);
            mp_store_name(QSTR_FROM_STR_STATIC("in2"), in2);

            ret = do_file(argv[a]);

            in1 = mp_load_name(QSTR_FROM_STR_STATIC("in1"));
            in2 = mp_load_name(QSTR_FROM_STR_STATIC("in2"));
            printf("%d %lf\n", mp_obj_int_get_checked(in1), mp_obj_float_get(in2));

            ...
```

**Comment by pfalcon** [comment]
I can tell why I didn't make change like this - because I still don't feel comfortable with cutting libc support for printing floats. That may bite. So, I kind left some time to let there be more testing, while leaving hint which that comment gives.

Well, ok, let's have this merged.

**Comment by pfalcon** [comment]
@texane : Merged, thanks. We'd like to have more detailed commit messages, cf. how I changes yours: e042f485ed9fc71b0a8ceca1dca89fe29d2179df

**Comment by texane** [comment]
Thanks. I will be careful with the message in future requests.

**Pull request closed without merging**
