### PR TITLE
unix/mphalport: add mp_hal_delay_us_fast

### PR DESCRIPTION
**Pull request by prusnak**
hw ports have this function, let's add it to unix port as well

### CODE REVIEW

**Comment by pfalcon** [comment]
What do you mean "let's"? Unix port doesn't even have standard mp_hal_delay_us(), because it didn't need it, and suddenly it gets all too new mp_hal_delay_us_delay(). Not saying it shouldn't be added, but please mind what's written in https://github.com/micropython/micropython/wiki/ContributorGuidelines - there's should be clear[ly described] reason for any change.

**Comment by dpgeorge** [comment]
The mp_hal_delay_us_fast function was added as a (small) hack to get the bit-banged I2C driver working at acceptable speeds on the esp8266.

**Comment by prusnak** [comment]
Reason: I am writing a set of cross-port modules that would benefit from having this in mphal.

**Comment by dpgeorge** [comment]
Then maybe just mp_hal_delay_us?

**Comment by pfalcon** [comment]
> Then maybe just mp_hal_delay_us?

+1

> The mp_hal_delay_us_fast function was added as a (small) hack to get the bit-banged I2C driver working at acceptable speeds on the esp8266.

So, the other way to deal with this is to make mp_hal_delay_us() "fast" by default, and do any event polling, etc. only in mp_hal_delay_ms() (that's why we have 2 functions after all - there's not just quantitative differences behind them, but qualitative too). Let's think about it (not changing it before esp8266 release).

**Comment by pfalcon** [comment]
> to make mp_hal_delay_us() "fast" by default, and do any event polling, etc. only in mp_hal_delay_ms()

Forgot to add that it's how it was in my original esp8266 event polling prototype.

**Comment by dpgeorge** [comment]
> So, the other way to deal with this is to make mp_hal_delay_us() "fast" by default, and do any event polling, etc. only in mp_hal_delay_ms()

Sounds good!  I didn't want to make such a drastic change at the time, so added the fast version.

Another option is to make the us delay function only call the poll periodically, and only if the delay is larger than some threshold.  Otherwise time.sleep_us(1000000) will crash the system.

**Comment by prusnak** [comment]
> Then maybe just mp_hal_delay_us?

+1

**Comment by pfalcon** [comment]
>  Otherwise time.sleep_us(1000000) will crash the system.

As expected, I'd say, now it's become almost impossible to trigger WDT ;-).

**Comment by pfalcon** [comment]
Any updates?

**Comment by pfalcon** [comment]
Changed as discussed and merged.

**Comment by prusnak** [comment]
Adding commit for reference: https://github.com/micropython/micropython/commit/bc7ca7ca01fc0e8b430e9094d846406f375b2a91

**Comment by prusnak** [comment]
Does it make sense to rename mp_hal_delay_us_fast(us) in stmhal and other ports to mp_hal_delay_us(us) so it is consistent across ports? That was my main goal actually. (So I don't have to #ifdef in generic cross-port code).

**Pull request closed without merging**
