### PR TITLE
tests: Add new test running to run multiple Py instances in parallel

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR adds a test runner and initial test scripts which run multiple Python/MicroPython instances (eg executables, target boards) in parallel.  This is useful for testing, eg, network and bluetooth functionality.

Each test file has a set of functions called `instanceX()`, where X ranges from 0 up to the maximum number of instances that are needed, N-1.  Then `run-multitests.py` will execute this script on N separate instances (eg micropython executables, or attached boards via `pyboard.py`) at the same time, synchronising their start in the right order, possibly passing IP address (or other address like bluetooth MAC) from the "server" instance to the "client" instances so they can connect to each other.  It then runs them to completion, collects the output, and then tests against what CPython gives (or what's in a provided `.py.exp` file).

A simple TCP data transfer test is:
```python
import socket

PORT = 8000

# Server
def instance0():
    multitest.write_network_ip()
    s = socket.socket()
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(socket.getaddrinfo("0.0.0.0", PORT)[0][-1])
    s.listen(1)
    multitest.next()
    s2, _ = s.accept()
    print(s2.recv(16))
    s2.send(b"server to client")
    s.close()


# Client
def instance1():
    multitest.next()
    s = socket.socket()
    ai = socket.getaddrinfo(IP, PORT)[0][-1]
    s.connect(ai)
    s.send(b"client to server")
    print(s.recv(16))
    s.close()
```
Note that the `IP` variable will be injected into the script when it is run.

The tests will be run using the standard unix executable for all instances by default:
```
$ ./run-multitests.py multi_net/*.py
```
Or can be run with a board and unix executable via:
```
$ ./run-multitests.py --instance pyb:/dev/ttyACM0 --instance exec:micropython multi_net/*.py
```

The test runner currently works as described above, but there are still a lot of "rough edges" and things to improve, but IMO it's a good start to begin writing device-to-device bluetooth tests (eg should be able to test having a central and multiple connected peripherals).

### CODE REVIEW

**Comment by dpgeorge** [comment]
I added a bluetooth test for advertising and scanning, that requires running on 2x boards, eg:
```
$ ./run-multitests.py -i pyb:/dev/ttyACM0 -i pyb:/dev/ttyACM1 multi_bluetooth/*.py
```

**Comment by stinos** [comment]
> Note that the IP variable will be injected into the script when it is run

That's kinda hard to discover, is that one of the rough edges which needs cleaning up?

For the rest: good idea.

**Comment by dpgeorge** [comment]
> That's kinda hard to discover, is that one of the rough edges which needs cleaning up?

Yes it's hard, mainly because a device may have more than one network interface.  When all instances are unix/windows/mac executables running on a local PC then it works using IP=127.0.0.1.  When a board (eg stm32, esp8266, esp32) is involved and is the server then it can usually get its IP via `network.WLAN().ifconfig()[0]` and tell that IP to all the clients (including a PC executable instance).  The only case it doesn't work is when the server is on the PC and the client(s) are boards.  In that case the boards must know the PC's IP address and this would need to be passed manually, eg something like:
```
$ ./run-multitests.py --instance exec:micropython@192.168.0.10 --instance pyb:/dev/ttyACM0
```

**Comment by tve** [comment]
Was any documentation committed with this PR? I'm not seeing it, but perhaps I didn't look in the right place.

**Comment by dpgeorge** [comment]
> Was any documentation committed with this PR?

No there was not.  Just something in the commit message, which could be used as a starting point for docs.

**Comment by tve** [comment]
> > Was any documentation committed with this PR?
> 
> No there was not. Just something in the commit message, which could be used as a starting point for docs.

:-( If you commit your stuff without docs how can you hold anyone else to providing docs? ;-)

**Comment by dpgeorge** [comment]
> If you commit your stuff without docs how can you hold anyone else to providing docs?

Well, this is an internal test framework, not really for general purpose use (at least not yet).

**Comment by tve** [comment]
> > If you commit your stuff without docs how can you hold anyone else to providing docs?
> 
> Well, this is an internal test framework, not really for general purpose use (at least not yet).

Well, this is your project and you get to decide. IMHO "internal" is a facetious term in this context when you want others to contribute to the project. My motivation to respond to PRs and nudge people to provide docs certainly isn't increased by this. But I'm new here...

**Comment by stinos** [comment]
For cases like this I honestly think the code and examples are clear enough documentation by themselves.

**Pull request merged**
