### PR TITLE
top: Add CODEOFCONDUCT.md document based on the PSF code of conduct.

### PR DESCRIPTION
**Pull request by dpgeorge**
This is attempt number two adding a Code of Conduct document to the project.  See previous attempt at #4358 

The document here is based on the (new) PSF code of conduct, with significant simplifications to make it short and to the point.

### CODE REVIEW

**Comment by stinos** [comment]
Should be good, no? In the end I don't think it matters too much what exact words are used and what is in there as long as it's clear, which it seems to be, and can be used to point to in case of discussions.

**Comment by klardotsh** [comment]
Generally I'm a fan here. The only potential addition I'd throw in would be classified as a revert of things removed: `Examples of unacceptable behavior`. Contributor Covenant has these, Adafruit's Code of Conduct used in CircuitPython has these, PSF's Code of Conduct has these (expanded upon many, many lines beyond the former two example), etc.

From Contributor Covenant 1.4:

```
Examples of unacceptable behavior by participants include:

    The use of sexualized language or imagery and unwelcome sexual attention or advances
    Trolling, insulting/derogatory comments, and personal or political attacks
    Public or private harassment
    Publishing others’ private information, such as a physical or electronic address, without explicit permission
    Other conduct which could reasonably be considered inappropriate in a professional setting
```

(The last one is, of course, the most vague of the set, as what I consider "professional" is going to vastly differ from some other folks, and likewise for almost every permutation of people on the planet)

**Comment by nevercast** [comment]
The private harassment one is an interesting case too, if someone is an ass on Twitter are they to be banned from the forum? 

Maybe the answer is "Yes, absolutely, they are a bad seed". But I felt it important to be a devil's advocate and at least ask.

Also, in agreement with @klardotsh I'd say that the professional development around the globe probably differs a lot and is difficult to quantify. 

As it stands, I think I would be happy with the code of conduct as it is now, if it was merged. But I usually glaze over the finer points of a CoC and just assume it says "Be Nice". Glad we can have this discussion about the details.

**Comment by tuupola** [comment]
`This code of conduct covers all offline and online presence`

Quite far reaching, eh? Shouldn't it cover only MicroPython related offline and online presence? 
 Check also Ruby which has short and no-nonsense one: https://www.ruby-lang.org/en/conduct/

**Comment by nevercast** [comment]
I gotta say, I really like the Ruby CoC, it was pleasing to read.

**Comment by dpgeorge** [comment]
Thanks all for the feedback and majority thumbs up.

> The only potential addition I'd throw in would be classified as a revert of things removed: `Examples of unacceptable behavior`

Agreed, it doesn't read well without there being a list of things that are actually frowned upon.  So I've now added these back in condensed form from the PSF's CoC.

> Quite far reaching, eh? Shouldn't it cover only MicroPython related offline and online presence?

Good point, text has been amended for this.

**Pull request merged**
