### PR TITLE
stm32: get small filesystem working on NUCLEO_L432KC

### PR DESCRIPTION
**Pull request by dpgeorge**
The filesystem is 26k in size.

### CODE REVIEW

**Comment by mindforger** [comment]
tested and working

made one addition on my own
froze the sdcard.py
resized the FS to 25k as i was overlapping by 800ish bytes with the frozen sdcard.py
tested on SPI 1 and 3, works flawless, Board Pin A7 is not working as chip select, the whole board freezes then

great job

**Comment by dpgeorge** [comment]
> resized the FS to 25k

That probably won't work because the page erase size is 2k, so the filesystem must be a multiple of 2k.

> Board Pin A7 is not working as chip select

PA7 should be a MOSI pin.

**Comment by dpgeorge** [comment]
I merged one of the commits here in a974f2dc6e45dc1fde88863df6b90dcaebf5bfe8 and rebased and force pushed the remaining one.

**Comment by mindforger** [comment]
hm ... now something is broken again, just did a hard reset origin/master and now i won't get a FS anymore

**Comment by dpgeorge** [comment]
There is still one commit on this branch which is not yet in master.  The reason I don't want to merge this (yet) is because this board is a good candidate for using littlefs by default (since it doesn't have USB, doesn't need to use FAT).  Soon littlefs v2 will be integrated and this board will use it, and likely have more free space on its filesystem.

**Comment by mindforger** [comment]
Ah, okay. Will stay on my modified branch then. But will i be able to read a sdcard when i freeze in the sdcard.py? I still did something to my local code but i dont know how to diff in console XD
If you have an advice on how i can push my local version to github i could diff it online

**Comment by cdwilson** [comment]
> Soon littlefs v2 will be integrated and this board will use it

@dpgeorge is there any activity on this now that littlefs V2 is released?

**Comment by dpgeorge** [comment]
Commit 378659209778a1bde24e9b15793087023b02bbd9 made progress on this, and now this PR (which has been updated) is very minimal.

See also #7123 which does what's done here in a different way.

**Comment by dpgeorge** [comment]
Fixed filesystem partition offset, and tested on a board.

**Pull request merged**
