### PR TITLE
nrf: Update to nrfx 2.0.0 to match TinyUSB. 

### PR DESCRIPTION
**Pull request by jimmo**
PR #5558, and specifically commit 6cea369 updated the TinyUSB submodule to a version based on nrfx 2.0.0, which broke the NRF build for USB-enabled boards.

It's not really feasible to be using a different nrfx to TinyUSB, so this PR both fixes the (minor) TinyUSB changes and updates to nrfx 2.0.0.

I only have a limited amount of NRF dev boards (a 52840 (Xenon) and a 51822 (micro:bit)) so will do some testing when I get a chance.

Also added more boards to the Travis build to avoid breaks like this in the future.

@glennrub

### CODE REVIEW

**Comment by jimmo** [comment]
Edit: fixed PR title.

**Comment by dhalbert** [comment]
TinyUsb just recently upgraded to nrfx 2.1.0: https://github.com/hathach/tinyusb/commit/c47d9c3c683c2be632b0d9e99eb0698973fe1795

Changes in 2.1.0 are here: (https://github.com/NordicSemiconductor/nrfx/blob/master/CHANGELOG.md).

There is a bug introduced in nrfx 2.0.0 that hasn't been fixed yet, but is on their list that bit me: the internal flash writing routines mistakenly forbid writing into the UICR region, so you have to use low-level writes if you want to do that. We only do that to fix some fuse settings if they are wrong.

**Comment by dpgeorge** [comment]
Thanks for this, I'll also do some testing on hardware.

I'm not sure why Travis fails building microbit, I can build it OK locally.

**Comment by jimmo** [comment]
> I'm not sure why Travis fails building microbit, I can build it OK locally.

From the travis log:

```
$ arm-none-eabi-gcc --version

arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)
```

**Comment by dpgeorge** [comment]
I'm testing this on a PCA10040 (nRF52832) and the ADC does not work, it returns 0 and then hangs.  Same code running before this PR worked ok.

**Comment by dpgeorge** [comment]
Adding a small delay after `nrfx_saadc_mode_trigger()` makes the ADC work.

**Comment by jimmo** [comment]
I looked at how this works in nrfx 1.8.1 and realised that it supports a blocking mode (by not passing a callback). Updated and tested ADC.read_u16 and ADC.read_battery.

I've also tested I2C and RNG which are fine. Cannot get machine.Temp() to work though -- `nrfx_temp_measure()` always fails.

@glennrub is building a more permanant test shield (and has already confirmed SPI and I2C working), so probably best to wait for results from that before merging.

I've also added a openocd flasher to the Makefile, as I'm testing this on a Particle Xenon with attached Particle Debugger.

> TinyUsb just recently upgraded to nrfx 2.1.0:

OK thanks @dhalbert , I'll update in a follow-up PR.

**Comment by dpgeorge** [comment]
> I looked at how this works in nrfx 1.8.1 and realised that it supports a blocking mode (by not passing a callback). Updated and tested ADC.read_u16 and ADC.read_battery.

Great, can confirm it now works on a pca10040.



> Cannot get machine.Temp() to work though

It works on this board, doing `machine.Temp().read()` returns a value of around 2200 and it looks like it changes based on temperature.

**Comment by glennrub** [comment]
> @glennrub is building a more permanant test shield (and has already confirmed SPI and I2C working), so probably best to wait for results from that before merging.

My test shield is complete.

I'm seeing the same issues as described earlier on the SAADC. Also, SPI seems to have an issue as well. SD cards does not mount anymore. I'm gussing it could either be the frozen `sdcard.py` or nrfx has an issue with incoming data / speed setting, as ssd1306 SPI displays still work fine. I'm aware of a few other bugs/issues, but they are not introduced by the nrfx upgrade.

I'll take a closer look at the SPI issue i'm having and report back / make a patch to @jimmo.

**Comment by dpgeorge** [comment]
Thanks @glennrub for the update.  I guess we hold off on merging this for now.

> I'm seeing the same issues as described earlier on the SAADC

Did you use a pca10040 or some other board?  As I mentioned above, the ADC works ok for me on a pca10040.

**Comment by andrewleech** [comment]
Without this change however all nrf52840 builds are competent broken, they won't even compile. I'd suggest merging this to get more information about the little things broken or otherwise unreliable.

**Comment by dpgeorge** [comment]
> Without this change however all nrf52840 builds are competent broken, they won't even compile. I'd suggest merging this to get more information about the little things broken or otherwise unreliable.

Yes I tend to agree with that... but it breaks other things that previously worked on non-nrf52840 boards...

TinyUSB was updated for i.MX support, so reverting it would break the mimxrt port.

@glennrub can we get a list of all regressions with this PR?  It looks like ADC, SPI and SD card.  Are you able to provide simple Python code which shows the problems for each of these, and which board(s) the problem appears on (doesn't need to be an exhaustive list of boards, just one for each of ADC/SPI/SD card would do).  Then others could help fix the issues and get this merged sooner.

**Comment by glennrub** [comment]
> Did you use a pca10040 or some other board?

I'm running the tests on pca10028 (nrf51), pca10040 (nrf52832), pca10056 and pca10090 (only partly as ADC/SPI/I2C-scan is not 100% supported on nrf91 yet).
Scripts have been uploaded here: [nrf_tests](https://github.com/glennrub/micropython_nrf_tests/tree/master/testshield)

> As I mentioned above, the ADC works ok for me on a pca10040.

Stupid mistake by me. I forgot to fetch the remote to get the latest force-push before i started the testing. ADC is working very well! :) Except an unrelated issue on nrf51 where scaling/gain is wrong, reporting 255 of 255 when voltage is cut from 2.8 to 1.4 (this is not an issue introduced by this PR).

>>   Without this change however all nrf52840 builds are competent broken, they won't even compile. I'd suggest merging this to get more information about the little things broken or otherwise unreliable.

> Yes I tend to agree with that... but it breaks other things that previously worked on non-nrf52840 boards...

No specific details on the SPI/SDCard issue other than SDCard() constructor hangs forever. No timeout, nothing. This works fine on master. 
Test: [sdcard_spi.py](https://github.com/glennrub/micropython_nrf_tests/blob/master/testshield/sdcard_spi.py) - Running it on pca10040 or pca10056 should provoke it.

A side note is that the `.travis.yml` change, adding `microbit`as target will most probably fail building. For me nrf51 targets (microbit/pca10028) overflow .TEXT region with > 600Kb making the build fail (GCC 8.2.1). The closest i have manged to locate any change is 073b9a5eb888b26be7ce4c65e9649b6c3857ba39. 
Reverting this commit makes the build succeed. I'm not sure if this is the exact commit yet. However, it would be good to get a nrf51 target on travis, so i'm definitely in favor of keeping it.

I'm also ok merging this and fix the SPI stuff afterwards.

**Comment by dpgeorge** [comment]
@glennrub I tested an SD card with a pca10040 with this PR, and it works for me, using your sdcard_spi.py test combined with the latest `drivers/sdcard/sdcard.py` driver.  Note that I didn't use any frozen code for this.  I used an external SD card adaptor connected to pins 15/23/24/25 as per the test.

**Comment by glennrub** [comment]
> I tested an SD card with a pca10040 with this PR, and it works for me

@dpgeorge thanks a lot for verifying my results. I finally made a successful run as well. Now, I move the suspicion over to my test shield :) As I have a ssd1306 OLED screen multiplexed with the SDcard on the same SPI pins, it all worked out great if I ran the script for ssd1306 before the SDcard. Most likely an issue on my side. I'll continue to fine-tune the test shield and tests so that next upgrade of nrfx will go a bit faster.

So, wrapping my testing up a bit. I have not found any new issues introduced by this PR. However, I learned about a few more issues when writing my tests and will address these separately.

**Comment by dpgeorge** [comment]
> So, wrapping my testing up a bit. I have not found any new issues with nrfx integration introduced by this PR.

Ok, really good!  So I suggest we move forward with merging this PR as-is.

**Comment by dpgeorge** [comment]
The microbit build was fixed by eb5e9c00f8119e8a69dea7590dbbe25a67a38e38 and 8f348778e12d3c8a55c6fe4c4475bb9ab07aa978, and this PR was rebased and merged in 9ee5aff33444ef37c928c9dbd0580ccd5904a4b7 through cd9a8c174209c869bd590e8408503dc20863c291

**Pull request closed without merging**
