### PR TITLE
mimxrt: Add MSC support for the mimxrt port.

### PR DESCRIPTION
**Pull request by robert-hh**
Using the good implementation by @iabdalkader for RP2 and some of  @alphafred's work for the bootloader.
This is a build option. The PR consists of two major parts:

- Adding basic MSC support in the commits up to the commit `mimxrt: Change the MSC enable/disable setting`
- Adding the work of PR #8814 for mimxrt in the following commits.

MSC support is not possible for device with hyperflash memory. FAT does not match with the 256k sector size of these devices. For all other devices, MSC is enabled by default.

### CODE REVIEW

**Comment by robert-hh** [comment]
Assuming that with PR #9497 it will be possible to have MSC support using a Python coded driver, which can be the same for all ports using TinyUSB, I close this PR. I will keep the branch in my repository and maintain it.

**Comment by iabdalkader** [comment]
Thank you for this, I will cherry-pick it in my fork too until we see if the other PR is merged. @robert-hh  I wanted to mention a storage related issue, with the port in general, so the VFS offset is fixed without checking if firmware overflows, if the firmware grows more than `0x100000`, it gets overwritten and weird bugs happen, at least for the `1062`... I've been debugging this issue for few days, the VFS should be in its own section.
```
vfs_start           = flash_start + 0x00100000;
```

**Comment by robert-hh** [comment]
Yes I know hat there is no automatic check. When starting 1Mbyte for code seemed huge. And the actual Teensy 4.1 build is as 580k. So you must have added a lot.

**Comment by iabdalkader** [comment]
> When starting 1Mbyte for code seemed huge

Not really if you add WiFi driver and firmware (which is ~400K alone) LWIP, nimble etc

**Pull request closed without merging**
