### PR TITLE
Nucleo f767 zi

### PR DESCRIPTION
**Pull request by flowergrass**

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thank you.  Merged with minor changes to .ld files to reflect actual RAM layout of the MCUs.  See 8001918a896586438ed5e82a9d0a200bb61027ee.

**Comment by sergiuszm** [comment]
Hello @flowergrass, @dpgeorge  I'm trying to create support for another STM32 board: L476RG. @flowergrass  PR is really useful for me as a guide how to do it correctly. 

However, I am missing one point in it. I'm trying to use STM32CubeMX to generate AF pins layout but I am unable to get the same result as yours (for the same board as yours: F767ZI). Could you help me a little bit and tell how I should do that? Default pins' configuration is different.

Thanks a lot!

**Comment by dpgeorge** [comment]
@sergiuszm it may be that the AF pins layout for the F767 is not 100% correct.  If it's not correct then it's not such a problem, you may just miss a few alternate functions.  But since you are working on an L476 board you can just use the existing stmhal/boards/stm32l476_af.csv file.  Look at the stmhal/boards/STM32L476DISC directory for hints.

**Comment by sergiuszm** [comment]
Thanks @dpgeorge. I looked at it before I have decided to ask for help. The problem with L476DISC is that it has more than 100 pins [link](http://prntscr.com/dlq4tf) Nucleo L476RG has 51 pins [link](http://prntscr.com/dlq5bp) That's why I am looking for any hints how it should be done correctly.

**Comment by dhylands** [comment]
Normally, the xxx_af.csv file contains all of the pin alternate functions for the largest pin count. The way the chips are designed, the reduced pin count parts just have fewer pins - they don't change pin functionality (they typically have the same chip inside and just bond out fewer pads).

I would expect that the 746 and 476 to have different xxx_af.csv files. I normally copy/paste the tables from the actual datasheets and then do some search/replace massaging to clean them up.

The pins.csv file then determines which pins from the xxx_af.csv file are actually used on a given board and what the board names for those pins are.

**Pull request closed without merging**
