### PR TITLE
fixed badges

### PR DESCRIPTION
**Pull request by ioncodes**
fixed the badges, they look better now since they load a svg now instead of a png

### CODE REVIEW

**Comment by dpgeorge** [comment]
> they look better now since they load a svg now instead of a png

That may be true, but isn't png much more widely supported in (older) browsers than svg?

**Comment by pfalcon** [comment]
Likewise, -1. First, it tells "fixed", but it doesn't fixes anything, maybe attempts at improvement. But as mentioned, switching to SVG will cause problems in many environments (think mobile browsers, etc.)

**Comment by ioncodes** [comment]
I can't agree with you: http://caniuse.com/#feat=svg
Also, if I open the page, I can't read what the badges say...

**Comment by mcauser** [comment]
https://blog.travis-ci.com/2014-03-20-build-status-badges-support-svg/

**Comment by ioncodes** [comment]
@mcauser Yeah, however, I don't that anyone will visit this page with an very old webbrowser. If he would, GitHub wouldn't work correctly, since it supports only newer browsers.

**Comment by pfalcon** [comment]
> I can't agree with you:

It's human to disagree.

> Also, if I open the page, I can't read what the badges say...

Perhaps, you should report a bug (maybe even submit a patch?) to the browser you use.

Thanks for your report, but let me close it for now. It can be reopened if sufficiently large number of users will report similar issues.

**Pull request closed without merging**
