### PR TITLE
stmhal/modmachine.c reset_cause() supports additional causes

### PR DESCRIPTION
**Pull request by peterhinch**
Supports detection of wakeup event, tamper, pin X1 wakeup plus the two RTC alarms.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks, but this is not compatible with the machine API, which only defines a certain set of reset-cause constants (the ones already implemented).  All these extra causes that are added in this PR are a subset of DEEPSLEEP_RESET.

It would be nice to support more fine-grained reset causes but we need to think how to do it in a way that works for other ports.

**Comment by peterhinch** [comment]
More fine-grained causes are essential to applications using the Pyboard's deep sleep mode. I had a solution in Python using the STM module which was broken by a recent firmware change, an obvious hazard with such hacks. Hence my suggestion of an official solution.

**Comment by pfalcon** [comment]
There was a similar PR for esp8266: https://github.com/micropython/micropython/pull/2452 (and #2453), which was "talked down" into non-merge. If this PR is merged, that one should be reopened and merged too.

**Comment by deshipu** [comment]
I wonder if it could be done in a more backwards-compatible way. For instance `reset_cause()` could behave as it does right now by default, but `reset_cause(True)` would return additional, board-specific information?

**Pull request closed without merging**
