### PR TITLE
stm32/littlefs: enable littlefs2 for wb series

### PR DESCRIPTION
**Pull request by dmazzella**

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for this.  Did you test it?  I think it's still going to be using 512 byte block size for littlefs with a cache, even though the internal flash has a 4k erase size.  So it won't be as efficient as it could be.  This can be fixed/improved later, but it would mean a breaking change at the time it's fixed, in the sense that users would need to reformat their littlefs partitions.

**Comment by dmazzella** [comment]
Yes i have tested it and it work fine.
if you prefer i close this PR for now and wait for the future fix/improvments.

**Comment by dpgeorge** [comment]
I think this is a good improvement for the time being, I'm happy to merge it.

**Comment by dpgeorge** [comment]
Merged in cc634b9e92cffa4ddbc6ccf60e346f550e7b0364

**Pull request closed without merging**
