### PR TITLE
Minimal integration of STM32F429I-disco kit

### PR DESCRIPTION
**Pull request by tobbad**
# Intent

With this pull request I would like to add minimal support for the STM32F429I-Discovery kit of STM. USB-CDC and USB-MSC interface works but there is no support for the on board sensors and the LCD. 
# Changes in stmhal subfolder
- **flash.c**: Added definitions for stm32f429 which has slightly more flash. Added calculation of flash table directly from table instead using a hard coded value and therby remove a magic constant.
- **storage.c**: Added defintition for stm32f429 as copy of STM32F405xx configuration.
- **usbd_conf.c**: Added USB setup for stm32f429 as copy of stm32f405/7 but on the USB_OTG_HS instance. The formatting of the code does not follow micropythons C Code conventions with respect to braces. I just did the minimal changes. Further the line endings are changed to unix style.
- **boards/stm32f429_af.csv**: Alternate pin function defines for stm32f429.
- **boards/stm32f429.ld**: Linkerscript for stm32f429.
- **boards/STM32F429DISC/**: Board defintions files for STM32F429i-Disco kit.
# Changes in tools subfolder
- **build-stm-latest.sh**: Added build of new platform.

### CODE REVIEW

**Comment by tobbad** [comment]
How is it possible to reduce my 215 commit into one single commit?

**Comment by pfalcon** [comment]
@tobbad : Start here: https://github.com/micropython/micropython/wiki/DevelWorkflow and remember the rule of thumb: never-ever use "git pull" without "--rebase" flag (well, unless you know what you do).

**Comment by dhylands** [comment]
@tobbad What I did was to take the half dozen files that you modified, and save them away.

Then checkout master, and pull down the latest.

Start a new branch, and then using a diffmerge tool (I personally use meld) merge your changes from your saved directory into the new branch.

Commit and you're done.

That's probably the easiest way.

**Comment by tobbad** [comment]
@dhylands 
Thanks for the hint. If I understand I do the following:
git clone https://github.com/micropython/micropython.git
cd micropython
git branch stm32f429_integration
git checkout stm32f429_integration
... merge changes
git add modified_files
git commit -m "Add support for STM32F429i-DISCOVERY kit by STMicro."
but now I have to push it back to https://github.com/micropython/micropython
but I do - of course - not have write access to the repo. How do I do that?

**Comment by dhylands** [comment]
You need to push to your forked repository. So you can either clone your repository or add a remote (I tend to clone the main micropython repo and add a remote for my fork).
```
git remote add tobbad git@github.com:tobbad/micropython.git
```
Now since your remote already has a branch named stm32f429_integration you'll need to do:
```
git push -f tobbad stm32f429_integration
```
The -f says you want to forcibly ovwerwrite.

**Comment by tobbad** [comment]
@dhylands: Thanks seems to work now!!

**Pull request closed without merging**
