### PR TITLE
stm32: add support for STM32H723 MCUs and NUCLEO_H723ZG board

### PR DESCRIPTION
**Pull request by dpgeorge**
Support for STM32H723, as requested in #10262.

Note: this has not been tested on hardware because I do not yet have a NUCLEO_H723ZG (and won't until next year).  The firmware builds but that is all.

If the NUCLEO_H723ZG board works then it'll have a REPL on the UART, accessible via the ST-LINK USB-UART port.  There is currently no support for native USB on the H723.

### CODE REVIEW

**Comment by dpgeorge** [comment]
@PYTRONIX-INC @softcity003 FYI

**Comment by PYTRONIX-INC** [comment]
Thanks Damien, we will test on our custom board. with regards to the native USB support can you please provide some more details

**Comment by dpgeorge** [comment]
> with regards to the native USB support can you please provide some more details

The H723 only has one USB peripheral and it's HS and usually would be on PB14/PB15, but on the Nucleo board it's on PA11/PA12 and I don't know how to switch it to these pins (it doesn't use the standard GPIO alternate function mapping).  But otherwise the USB should work.

How is the USB wired up on your custom board?

**Comment by PYTRONIX-INC** [comment]
our custom board does also use PA11/PA12. We have tried to map the REPL to UART2, UART3 but we were not able to get the micropython prompt.

I have attached the schematics to our custom board. 
[PY_Core.pdf](https://github.com/micropython/micropython/files/10279472/PY_Core.pdf)

can you please advise on which UART to use??

**Comment by dpgeorge** [comment]
For the NUCLEO_H723ZG, the REPL is configured on UART3, PD8/PD9 pins.  Also note that the MCU is clocked from an external HSE at 8MHz.  You'll need to change that for your board.  Eg remove this line:
```
#define MICROPY_HW_CLK_USE_BYPASS   (1)
```
and change PLLM to 6:
```
#define MICROPY_HW_CLK_PLLM         (6)
```

**Comment by softcity003** [comment]
hello damien ,
I made the changes you recommended but when I try to get micropython REPL with putty i get this 
image
in our custom board uart3 is on B10/D9 pins and the baud rate is correct , this is our configuration 
`#define MICROPY_HW_BOARD_NAME       "NUCLEO_H723ZG"
#define MICROPY_HW_MCU_NAME         "STM32H723ZGT6"

#define MICROPY_HW_ENABLE_RTC       (1)
#define MICROPY_HW_ENABLE_RNG       (1)
#define MICROPY_HW_ENABLE_ADC       (1)
#define MICROPY_HW_ENABLE_DAC       (1)
#define MICROPY_HW_ENABLE_USB       (0)
#define MICROPY_HW_ENABLE_SDCARD    (1)
#define MICROPY_HW_HAS_SWITCH       (1)
#define MICROPY_HW_HAS_FLASH        (1)

#define MICROPY_BOARD_EARLY_INIT    NUCLEO_H723ZG_board_early_init

// There is no external HS crystal, instead it comes from ST-LINK MCO output.
// The following gives 400MHz CPU speed.
#define MICROPY_HW_CLK_PLLM         (6)
#define MICROPY_HW_CLK_PLLN         (400)
#define MICROPY_HW_CLK_PLLP         (2)
#define MICROPY_HW_CLK_PLLQ         (4)
#define MICROPY_HW_CLK_PLLR         (2)
#define MICROPY_HW_CLK_PLLVCI       (RCC_PLL1VCIRANGE_1)
#define MICROPY_HW_CLK_PLLVCO       (RCC_PLL1VCOWIDE)
#define MICROPY_HW_CLK_PLLFRAC      (0)

// The USB clock is set using PLL3
#define MICROPY_HW_CLK_PLL3M        (4)
#define MICROPY_HW_CLK_PLL3N        (120)
#define MICROPY_HW_CLK_PLL3P        (2)
#define MICROPY_HW_CLK_PLL3Q        (5)
#define MICROPY_HW_CLK_PLL3R        (2)
#define MICROPY_HW_CLK_PLL3VCI      (RCC_PLL3VCIRANGE_1)
#define MICROPY_HW_CLK_PLL3VCO      (RCC_PLL3VCOWIDE)
#define MICROPY_HW_CLK_PLL3FRAC     (0)

// 4 wait states
#define MICROPY_HW_FLASH_LATENCY    FLASH_LATENCY_4

// The board has an external 32kHz crystal attached
#define MICROPY_HW_RTC_USE_LSE      (1)

// UART config
#define MICROPY_HW_UART2_TX         (pin_D5)
#define MICROPY_HW_UART2_RX         (pin_D6)
#define MICROPY_HW_UART2_RTS        (pin_D4)
#define MICROPY_HW_UART2_CTS        (pin_D3)
#define MICROPY_HW_UART3_TX         (pin_B10)
#define MICROPY_HW_UART3_RX         (pin_D9)
#define MICROPY_HW_UART4_TX         (pin_A0)
#define MICROPY_HW_UART4_RX         (pin_D0)
//#define MICROPY_HW_UART4_RTS        (pin_B14)
//#define MICROPY_HW_UART4_CTS        (pin_B0)
#define MICROPY_HW_UART5_TX         (pin_B6)
#define MICROPY_HW_UART5_RX         (pin_B5)
#define MICROPY_HW_UART6_TX         (pin_C6)
#define MICROPY_HW_UART6_RX         (pin_C7)
#define MICROPY_HW_UART7_TX         (pin_E8)
#define MICROPY_HW_UART7_RX         (pin_E7)
#define MICROPY_HW_UART8_TX         (pin_E1)
#define MICROPY_HW_UART8_RX         (pin_E0)
#define MICROPY_HW_UART8_RTS        (pin_D15)
#define MICROPY_HW_UART8_CTS        (pin_D14)
#define MICROPY_HW_USART10_TX         (pin_E3)
#define MICROPY_HW_USART10_RX         (pin_E2)

#define MICROPY_HW_UART_REPL        PYB_UART_3
#define MICROPY_HW_UART_REPL_BAUD   115200

// I2C buses
#define MICROPY_HW_I2C1_SCL         (pin_B8)
#define MICROPY_HW_I2C1_SDA         (pin_B9)
#define MICROPY_HW_I2C2_SCL         (pin_F1)
#define MICROPY_HW_I2C2_SDA         (pin_F0)
#define MICROPY_HW_I2C4_SCL         (pin_F14)
#define MICROPY_HW_I2C4_SDA         (pin_F15)

// SPI buses
#define MICROPY_HW_SPI3_NSS         (pin_A4)
#define MICROPY_HW_SPI3_SCK         (pin_B3)
#define MICROPY_HW_SPI3_MISO        (pin_B4)
#define MICROPY_HW_SPI3_MOSI        (pin_B5)

// USRSW is pulled low. Pressing the button makes the input go high.
#define MICROPY_HW_USRSW_PIN        (pin_C13)
#define MICROPY_HW_USRSW_PULL       (GPIO_NOPULL)
#define MICROPY_HW_USRSW_EXTI_MODE  (GPIO_MODE_IT_RISING)
#define MICROPY_HW_USRSW_PRESSED    (1)

// LEDs
#define MICROPY_HW_LED1             (pin_B0)    // green
#define MICROPY_HW_LED2             (pin_E1)    // yellow
#define MICROPY_HW_LED3             (pin_B14)   // red
#define MICROPY_HW_LED_ON(pin)      (mp_hal_pin_high(pin))
#define MICROPY_HW_LED_OFF(pin)     (mp_hal_pin_low(pin))

// USB config
// TODO: work out how to configure PA11/12 for USB_OTG_HS
//#define MICROPY_HW_USB_HS               (1)
//#define MICROPY_HW_USB_HS_IN_FS         (1)
//#define MICROPY_HW_USB_VBUS_DETECT_PIN (pin_A9)
//#define MICROPY_HW_USB_OTG_ID_PIN      (pin_A10)
//#define MICROPY_HW_USB_OTG_DP_PIN      (pin_A12)
//#define MICROPY_HW_USB_OTG_DM_PIN      (pin_A11)
// FDCAN bus
#define MICROPY_HW_CAN1_NAME  "FDCAN1"
#define MICROPY_HW_CAN1_TX    (pin_D1)
#define MICROPY_HW_CAN1_RX    (pin_D0)

// SD card detect switch
#define MICROPY_HW_SDCARD_DETECT_PIN        (pin_G2)
#define MICROPY_HW_SDCARD_DETECT_PULL       (GPIO_PULLUP)
#define MICROPY_HW_SDCARD_DETECT_PRESENT    (GPIO_PIN_RESET)

// Ethernet via RMII
#define MICROPY_HW_ETH_MDC          (pin_C1)
#define MICROPY_HW_ETH_MDIO         (pin_A2)
#define MICROPY_HW_ETH_RMII_REF_CLK (pin_A1)
#define MICROPY_HW_ETH_RMII_CRS_DV  (pin_A7)
#define MICROPY_HW_ETH_RMII_RXD0    (pin_C4)
#define MICROPY_HW_ETH_RMII_RXD1    (pin_C5)
#define MICROPY_HW_ETH_RMII_TX_EN   (pin_G11)
#define MICROPY_HW_ETH_RMII_TXD0    (pin_G13)
#define MICROPY_HW_ETH_RMII_TXD1    (pin_B13)

void NUCLEO_H723ZG_board_early_init(void);`

**Comment by dpgeorge** [comment]
@softcity003 the fact you get some garbage output on the serial is a very good sign!  Most likely everything is working, except that the CPU is running at a different speed to what's expected, and so the UART baudrate is wrong.

I suggest to just keep changing the UART baudrate until it works.  Then from that determine the actual CPU frequency and adjust accordingly the PLLx constants.

**Comment by pschindler** [comment]
I tried it on a  Nucleo-H7232ZG and it worked immediately after compilation! It seems that the ADC also works. Thanks @dpgeorge 
Let me know if there is anything I should test.

**Comment by dpgeorge** [comment]
I now have a NUCLEO-H723ZG and have tested and updated this PR.  USB is now enabled and working.  I also tested Ethernet and it works (can get up to 90MBit/sec using `iperf3`).

I had to disable the RNG because it was not working correctly.  I'm not sure why.

**Pull request merged**
