### PR TITLE
stmhal: DMA support for sdcard

### PR DESCRIPTION
**Pull request by dhylands**
This takes the work done by IgorLektorovEpam in PR #1389
and fixes up a few small mistakes and does some cleanup
based on the comments.

I tested with rshell over serial and I can now copy files to the sdcard (previously serial characters were being dropped due to interrupts being disabled while doing sdcard transfers).

### CODE REVIEW

**Comment by chuckbook** [comment]
@dhylands I just tried your DMA-SD driver and it looks pretty good. I realized an increase in power consumption of up to 10mA (pyboard) during idle REPL. (with the polling driver it was ~3mA)
Before I dive into this, do you have any idea what could be the reason?

**Comment by dhylands** [comment]
Hmm. The only thing I can think of is that interrupts are firing. Let me add some instrumentation to all of the IRQ handlers that were added and see if they're firing while we're not doing anything at the REPL.

**Comment by chuckbook** [comment]
@dhylands Let me know if I can help.

**Comment by chuckbook** [comment]
It looks like the extra ~10mA is the price we have to pay for having DMA.....

**Comment by dhylands** [comment]
Yeah - if you execute this at the REPL:
```
>>> import stm
>>> >>> hex(stm.mem32[stm.RCC + stm.RCC_AHB1ENR])
'0x50000f'
```
that shows that DMA2 clock is enabled (0x400000). If we set that to zero:
```
>>> stm.mem32[stm.RCC + stm.RCC_AHB1ENR] = 0x10000f
```
then I see an immediate drop in current.

I think that to manage this properly we'd need to keep a reference count on active streams, and turn the clock off when there are no active streams. For some things (like DAC) the DMA is probably on all of the time.

But we could certainly improve this. I'll open a new issue.

**Comment by dhylands** [comment]
I filed issue #1618 to have the DMA clocks shutdown when no streams are being used.

**Comment by dpgeorge** [comment]
Thanks @dhylands, it looks good... except that ~10mA increase in idle current is really not acceptable, especially if no SD card is inserted.

The simplest thing to do is to set up the DMA only when needed.  The DMA set up could go in sdcard_power_on.  Or, at the start of sdcard_read_blocks/write_blocks it could check if the DMA is configured, and if not then configure it.  But I think in sdcard_power_on is enough for the moment, because if the SD card is present then it'll be mounted straight away (by fatfs driver) and will start reading blocks straight away.

**Comment by chuckbook** [comment]
What about tracing DMA usage in dma_init() and dma_deinit() in dma.c? The last one shut down the light.

**Comment by dhylands** [comment]
The problem is much bigger than just the sdcard. If affects all users of DMA.

I was going to add a dma_enable_clk and dma_disable_clk functions. They would have a bitmask per stream, and when the bitmask for a particular dma block transitioned from 0 to non-zero it turn the clock on, and then it transitioned from non-zero to zero it would disable the clock.

For backwards compatability, I was going to propose putting a call to dma_enable_clk at the end of dma_init (so that any existing code would continue to work.

Users of dma_xxx that wanted to get the power saving (which would eventually be all of them) would then call dma_disable_clk after calling dma_init, and call dma_enable_clk before performing a dma operation and dma_disable_clk when done. For the sdcard, this would mean that the power would only be increased when actually using the DMA blocks.

I was going to do that work as part of #1618 since I thought it was more than just an sdcard problem.

**Comment by dhylands** [comment]
> Thanks @dhylands, it looks good... except that ~10mA increase in idle current is really not acceptable, especially if no SD card is inserted.
> 
> The simplest thing to do is to set up the DMA only when needed. The DMA set up could go in sdcard_power_on. Or, at the start of sdcard_read_blocks/write_blocks it could check if the DMA is configured, and if not then configure it. But I think in sdcard_power_on is enough for the moment, because if the SD card is present then it'll be mounted straight away (by fatfs driver) and will start reading blocks straight away.

The current code to initialize the DMA is already only called when the sdcard is powered on. The DMA initialization is in the function HAL_SD_MspInit which is called by HAL_SD_Init which is only called fom inside sdcard_power_on if a card is present.

I've been playing around with the code a bit, and made the following discoveries:
1 - If you turn off the DMA clock, then you need to reinitialize everything.
2 - I tried adding a disable of the clock when nobody was using it into dma_deinit, but this meant that I had to disable the "last channel" optimization: https://github.com/micropython/micropython/blob/master/stmhal/dma.c#L122-L127

The I2C and SPI drivers call dma_init/dma_deinit around each transfer.

I can get the exact same increase in power consumption by doing this sequence:
```
>>> a = pyb.Accel()
>>> i2c = pyb.I2C(1, pyb.I2C.MASTER)
>>> i2c.mem_read(1,76,0)
b'?'
```
As soon as I call i2c.mem_read, the current goes up by 8mA and stays up. Not only that, but each DMA block adds an additional 8mA. So:
```
>>> hex(stm.mem32[stm.RCC + stm.RCC_AHB1ENR])
'0x10000f'
>>> stm.mem32[stm.RCC + stm.RCC_AHB1ENR] = 0x30000f
>>> stm.mem32[stm.RCC + stm.RCC_AHB1ENR] = 0x70000f
>>> stm.mem32[stm.RCC + stm.RCC_AHB1ENR] = 0x10000f
```
When I turn on DMA1 (value 0x30000f) then I see a current jump. When I turn on both DMA blocks (the  0x70000f value) then I see an additional current jump (about 8mA each time). Turning off both DMA blocks (the 0x10000f value) then the current goes back to where it was before turning either DMA block on.

Having the last channel optimization seems like a good thing, especially if we're going to be doing back-to-back DMA transfers.

Perhaps one approach might be to use a timeout. After some period of time with no DMA activity, we turn off the DMA clock and invalidate the last-channel cache. We could use the existing millisecond timer tick interrupt to do this housekeeping. Then if we're doing lots of I/O, the DMA block stays on, and we don't need to reinitialize the channels on every call. Once the I/O dies down, the DMA blocks get shut off and power consumption drops.

I think that would be a reasonable tradeoff. Perhaps we should introduce a DMA module? Then we could have some status functions to see the internals of the DMA block, and add a configurable timeout. Or we could just add a bare function to set the timeout, or we could use some hardcoded values (like 100 milliseconds).

**Comment by dhylands** [comment]
And perhaps we should consider adding a 'use_dma' option to the peripherals (i.e. SPI/I2C/SD). For low-power setups it may make more sense to just not use DMA at all.

**Comment by dhylands** [comment]
Closing in favor of PR #1625

**Pull request closed without merging**
