### PR TITLE
modframebuf.c Supports the RFC #1817 1-bit mappings.

### PR DESCRIPTION
**Pull request by peterhinch**
This serves a purpose beyond supporting hardware which uses these mappings.

It facilitates the blitting of arbitrary one bit per pixel graphics (such as font glyphs) to other framebufs. The existing blit method is mapping-agnostic; it allows the graphics to be in any of these agreed mappings regardless of the mapping used by the display device (e.g. SSD1306).
```python
buf = bytearray(glyph)
# In this instance the glyph is mapped with HMAP
# and the device (SSD1306) uses MVLSB
fbc = framebuf.FrameBuffer(buf, char_width, char_height, framebuf.HMAP)
self.device.framebuf.blit(fbc, Writer.text_col, Writer.text_row)
```
```

### CODE REVIEW

**Comment by kamikaze** [comment]
isn't there a time to make different formats optionally available? or at least option to disable?

**Comment by dpgeorge** [comment]
It looks like HMAP and VMAP are just x<->y transpositions of each other, right?  Is it really necessary/useful to have both of them?  I'd say that HMAP is the one that's most common.

**Comment by peterhinch** [comment]
They are x-y transpositions. In the original discussion I referenced (#1817) I thought we agreed to support both. I identified hardware using hmap (e-paper) and you identified some using vmap (the Pyboard LCD skin). For the minimal amount of code involved, I'd argue for supporting both.

**Comment by peterhinch** [comment]
I'm puzzled why travis is failing. The log shows:
```
FAIL  extmod/framebuf1.py
```
 yet if I do:
```
./run-tests --target=pyboard
```
it passes:
```
pass  extmod/framebuf1.py
pass  extmod/framebuf16.py
pass  extmod/framebuf4.py
```

**Comment by dpgeorge** [comment]
> I'm puzzled why travis is failing.

If you look at the output of Travic CI, right at the bottom of the page, and click on the right-arrow to open the output of the tests, you'll see that the issue is that your tests/extmod/framebuf1.py.exp needs a newline at the end of the file.

You can run the coverage tests locally via "make coverage_test" in the unix/ dir.

**Comment by dpgeorge** [comment]
@peterhinch sorry for the delay, just coming back to this now.

I don't think we need the VMAP.  The SSD1306 and pyboard LCD32 screen use vertical mapping, but not the one you implemented with VMAP.  Those screens both use the existing MVLSB format.  This format is not a x-y transpose of a horizontal mapping, but rather the first byte is draw vertically at (0,0) and the second byte is drawn vertically at (1,0), to the right of the first one.  In your VMAP the second byte would be drawn vertically at (0, 8), below the first one.

Keeping with the existing naming of MVLSB, Your HMAP would be better named MHLSB (the LSB of the byte is drawn first), and HMAP_REV would be MHMSB (the MSB of the byte is drawn first).  And then we can add MVMSB by generalising the existing MVLSB code, the same way you put HMAP and HMAP_REV in the same functions.

> Users may find it easier to generate these in horizontal or vertical forms depending on their tools/skills.

I think horizontal is the most natural format and we should encourage users to generate them that way.  After all, VMAP is just a simple transpose of HMAP, whereas MVLSB is a more complex transformation.

**Comment by peterhinch** [comment]
The SSD1306 can be configured for VMAP (true vertical mapping) as an alternative to MVLSB. I have tested it in this mode, but I don't know if VMAP is widely used by graphics hardware. In any event I'll remove it and rename as requested.

**Comment by dpgeorge** [comment]
> The SSD1306 can be configured for VMAP (true vertical mapping) as an alternative to MVLSB.

That option could be used to make the display go into portrait mode, by then using the MHLSB format, no?

**Comment by peterhinch** [comment]
I think so. I could test this.

**Comment by dpgeorge** [comment]
Ok, this was squashed and merged in 231cfc84a7cae31f93208c334fc33b08278040eb, with very minor changes (in particular I simplified the alignment of the stride variable).

Looking at the format names again, I think some are a bit difficult to read, eg: MHMSB.  It might be a good idea to add underscores, eg M_HMSB, M_HLSB, and then MVLSB becomes M_VLSB.  This matches GS4_HMSB.

**Comment by peterhinch** [comment]
I've submitted PR #2967 which implements these name changes and amends the doc.

**Pull request closed without merging**
