### PR TITLE
Adds a setmode method for setting the WiFi mode.

### PR DESCRIPTION
**Pull request by Sweet-Peas**
This patch adds a new setmode command so that the WiFi mode can be selected. Absolutely necessary of you want to do a scan for instance. Sorry for the mess in commits, I think my brain had a git meltdown just now.

/Pontus

### CODE REVIEW

**Comment by dpgeorge** [comment]
This is already propossed in #1318.  It's pending a (long standing) decision on the network API.

**Comment by danicampora** [comment]
> This is already propossed in #1318. It's pending a (long standing) decision on the network API.

@Sweet-Peas we are working on a new hardware API, and soon we will get to the network drivers. Check out what we have so far here: https://github.com/micropython/micropython/wiki/Hardware-API

And feel free to share your thoughts in #1430

**Comment by Sweet-Peas** [comment]
Okay, I get it. I'll hold on and see what happens. This will live in our fork for now so people can use our module with mp. I'll chime on on the Hardware-API discussions as we are already working on I2C and SPI stuff for the ESP8266.

**Comment by dpgeorge** [comment]
@Sweet-Peas I guess you don't have to ship hardware for a few months, and by then the API should be worked out.

> I'll chime on on the Hardware-API discussions as we are already working on I2C and SPI stuff for the ESP8266.

Please do!  It's important, because having a consistent API across different boards will help the MicroPython ecosystem and all the users.  Concrete thing for you to do is check that the proposed API maps cleanly to the ESP8266 and tell us when/where it doesn't.  Thanks!

**Comment by pfalcon** [comment]
#1318 was merged as being first in row, offering more functionality (get current mode), and being clean, single-commit patch. @Sweet-Peas : Please consider squashing individual commits for future changes. Another issue is that you submitted pull request against your master branch, which means any new commits you push there end up in PR, unrelated to original topic. There're few hinst how to best contribute patches at https://github.com/micropython/micropython/blob/master/CONTRIBUTING.md .

In the meantime, one thing your patch had and #1318 missed is error handling. It's nice low-hanging fruit to re-add (and easy way to practice PR submission), hope you can rebase and re-submit that part. Thanks!

**Comment by dpgeorge** [comment]
This has been superseded by the functionality in 9e8396accbcb695e2fe9def666bfb31b26efde06 and 1c43a0fbf872ab44e3fc8c427f6ce180b7d6cb8c.

**Pull request closed without merging**
