### PR TITLE
Update ESP-IDF. Also, add RS485 support to esp32 serial.

### PR DESCRIPTION
**Pull request by fake-name**
I have some RS-485 devices I want to talk to. This should compromise the micropython changes needed to expose the ability to specify the value passed to `uart_set_mode()`, which controls the operating mode of the UART in the esp.

Currently, this is broken, because the linked version of the ESP-IDF is not recent enough. https://github.com/espressif/esp-idf/pull/667 was for the the `uart_set_mode()` call, which was implemented in https://github.com/espressif/esp-idf/commit/51e9cf6848642460444627a1e933d11f476a53f2, this July, about 3 weeks after 9a55b42f0841b3d38a61089b1dda4bf28135decd. 

Currently, I'm poking around trying to figure out how to update the linked version of the idf. Just updating it causes compilation failures, because apparently expressif have been rearranging files in the bootloader sources for \~\~reasons\~\~.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.  I see it's compiling, but is it running on an ESP32 board?

**Comment by fake-name** [comment]
I'm currently having issues, but I'm not sure the specific cause of the issue so far.

**Comment by fake-name** [comment]
(Writing this out here so I can remember what I'm doing)

I've bisected the issue down to https://github.com/espressif/esp-idf/commit/43b6c76bba31450dfa1e962772dc7195852c6084. Right now, I get a abort on startup:

```
    Fatal exception (28): LoadProhibited

epc1=0x4008070e, epc2=0x00000000, epc3=0x00000000, excvaddr=0x8fbe8057, depc=0x00000000
```

`0x4008070e` is 

```

 .iram1.literal
                0x00000000400806f4       0x1c build//home/durr/esp/esp-idf/components/esp32/crosscore_int.o
                                         0x40 (size before relaxing)
 .iram1.literal
                0x0000000040080710       0x20 build//home/durr/esp/esp-idf/components/esp32/ipc.o
                                         0x34 (size before relaxing)
```

So my assumption right now is the reworking of the partition layout that occurred in https://github.com/espressif/esp-idf/commit/43b6c76bba31450dfa1e962772dc7195852c6084 is causing the current `sdkconfig.h` to no longer be valid.

 The ESP port seems to not be using the normal ESP-IDF `kconfig` setup process, so I'm not sure exactly how the current `sdkconfig.h` was generated/written.

**Comment by dpgeorge** [comment]
> The ESP port seems to not be using the normal ESP-IDF kconfig setup process, so I'm not sure exactly how the current sdkconfig.h was generated/written.

It was written by hand, but you can get hints about what to add/change by building an example app from the ESP IDF (eg protocols/http_request).

> I've bisected the issue down to espressif/esp-idf@43b6c76. Right now, I get a abort on startup:

The issue could be to do with esp32.bootloader.ld: that expects compiled files to be in .a archives so it can place text in iRAM, etc.  Eg this line from that file:
```
*libbootloader_support.a:bootloader_utility.o(.literal .text .literal.* .text.*)
```
expects bootloader_utility.o to be in libbootloader_support.a.  But we don't do that, so the text from this source file won't be going in iRAM as it should be.  One way to fix this is to provide a custom version of this file that doesn't require objects to be in a .a archive (that's why esp32.custom_common.ld exists in this repo).  Another way to fix it would be to actually package these files into a .a in the Makefile here to make it closer to what the ESP IDF does.  Probably that's a better solution than having a custom .ld file.

Ultimately, because these problems keep popping up, it might be a good idea to switch to using the ESP IDF's build system....

**Comment by fake-name** [comment]
> Ultimately, because these problems keep popping up, it might be a good idea to switch to using the ESP IDF's build system....

If that's something you'd consider, I can see about doing that?

There may be some wailing and gnashing of teeth, though.

**Comment by fake-name** [comment]
Ok, at this point I've bodged the two build-systems together. It seems to build both the esp-idf components, and the various micropython sources.

However, the string extraction/qstr header is not being properly generated, and I can't figure out why. 

```
In file included from /home/durr/micropython-mine/ports/esp32/../../py/obj.h:31:0,
                 from /home/durr/micropython-mine/ports/esp32/main/modmachine.c:40:
/home/durr/micropython-mine/ports/esp32/../../py/qstr.h:42:39: fatal error: genhdr/qstrdefs.generated.h: No such file or directory
compilation terminated.
In file included from /home/durr/micropython-mine/ports/esp32/../../py/obj.h:31:0,
                 from /home/durr/micropython-mine/ports/esp32/../../py/mpstate.h:35,
                 from /home/durr/micropython-mine/ports/esp32/main/gccollect.c:33:
/home/durr/micropython-mine/ports/esp32/../../py/qstr.h:42:39: fatal error: genhdr/qstrdefs.generated.h: No such file or directory
compilation terminated.
/home/durr/esp/esp-idf/make/component_wrapper.mk:285: recipe for target 'modmachine.o' failed
make[1]: *** [modmachine.o] Error 1
make[1]: *** Waiting for unfinished jobs....
CC build/nghttp/nghttp2/lib/nghttp2_rcbuf.o
In file included from /home/durr/micropython-mine/ports/esp32/../../py/obj.h:31:0,
                 from /home/durr/micropython-mine/ports/esp32/../../py/mpstate.h:35,
                 from /home/durr/micropython-mine/ports/esp32/../../py/runtime.h:29,
                 from /home/durr/micropython-mine/ports/esp32/main/network_lan.c:29:
/home/durr/micropython-mine/ports/esp32/../../py/qstr.h:42:39: fatal error: genhdr/qstrdefs.generated.h: No such file or directory
compilation terminated.
```

As far as I understand, adding a dependency on `$(HEADER_BUILD)/qstrdefs.generated.h` should result in the qstr target from `py.mk` being required as a dependency, but after trying to add it as a dependency to basically every intermediate target I could think of, it's still not doing anything. 

At this point, I really am not familiar enough with makefiles to have any idea what's going on. 

Anyone have suggestions?

**Comment by dpgeorge** [comment]
Is it really necessary to move all the source files to a "main" subdirectory?  It might be possible instead to override the `COMPONENTS` variable to keep the source files where they are.

But, to move forward, it's probably easier right now to just update the existing Makefile to archive all the .o files for the `bootloader_support` component into a .a file and link that in, which should solve the problem with it crashing.

**Comment by fake-name** [comment]
@dpgeorge - There's no reason it's necessary, but I find it much easier to use, and it separates your source files from your build system files.

At the moment, I wound up having serial issues that I couldn't fix and gave up, and just wrote the project in C++. I was having some issues I couldn't understand related to the serial interfaces apparently not acting like it was configured too. At this point, I suspect that the stop-bits settings are ignored, but I just wanted to get the project I was working on deployed, so it's not in a state where I can tinker with it any more.


I think pursuing https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo might be a more productive option in the future.

**Comment by fake-name** [comment]
This PR should probably be closed in lieu of https://github.com/micropython/micropython/pull/4018.

**Comment by dpgeorge** [comment]
Ok, thanks for the attempt to update the IDF.

**Comment by fake-name** [comment]
I've subsequently bought another esp32 module, so I may spend more time on this in the future (or at least try to resolve the weird stop-bits thing).

**Comment by dpgeorge** [comment]
The IDF was updated to the latest one in 48d736f491dbaf106b0b1a4f1cdc79bf67452b54

**Comment by fake-name** [comment]
It'd probably be worth rolling in https://github.com/micropython/micropython/pull/3995/commits/12613ee28228eb76e07d21b9ed0b439241d8b4f6, if nothing else.

**Comment by fake-name** [comment]
Ok, I rolled https://github.com/micropython/micropython/pull/3995/commits/12613ee28228eb76e07d21b9ed0b439241d8b4f6 / https://github.com/micropython/micropython/pull/3995/commits/39b6d9d5f6aeff68841e1838990ffa9aa9be5ec8 into https://github.com/micropython/micropython/pull/4018

**Pull request closed without merging**
