### PR TITLE
all: Compress error strings in ROM (v2)

### PR DESCRIPTION
**Pull request by dpgeorge**
This is #5168 rebased on latest master, with a minor addition to lazily compute the error string hash only if it's extracted (so raised errors that don't have their message extracted will never spend time unnecessarily computing the hash).

Code size change with this PR (0 for ports that don't enable the string compression):
```
   bare-arm:  -600 -0.906% 
minimal x86:  -308 -0.208% 
   unix x64:    +0 +0.000% 
unix nanbox:    +0 +0.000% 
      stm32: -3368 -0.869% PYBV10
     cc3200: -1024 -0.558% 
    esp8266: -2308 -0.338% GENERIC
      esp32: -2688 -0.199% GENERIC[incl -2976(data)]
        nrf: -1708 -1.175% pca10040
       samd:    +0 +0.000% ADAFRUIT_ITSYBITSY_M4_EXPRESS
```

### CODE REVIEW

**Comment by dpgeorge** [comment]
@jimmo I noticed the new str typedef you introduced is called `_mp_rom_error_text`.  I guess you made it have an underscore prefix because it's considered internal, but such identifiers are technically reserved for the compiler to use, and we avoid them.  And for consistency with other types I think it's good that it ends in `_t`.  So, what about changing it to `mp_rom_error_text_t`?  (I can do it in this PR.)

**Comment by Ozturk470** [comment]
Hata ayıklama kodlarımı oluyor

4 Nis 2020 Cmt, saat 16:18 tarihinde Damien George <notifications@github.com>
şunu yazdı:

**Comment by jimmo** [comment]
> So, what about changing it to `mp_rom_error_text_t`?  (I can do it in this PR.)

Yes, agreed. Originally my goal was to just find the places that my script had missed, and wasn't planning to keep it around, so hadn't given much thought to the name. But I think it's useful to keep and your suggested name makes much more sense.
Thanks!

**Comment by dpgeorge** [comment]
> But I think it's useful to keep and your suggested name makes much more sense.

Ok, now renamed (and force-pushed because I needed to rebase-edit to change the name across multiple commits).

**Comment by dpgeorge** [comment]
I squashed the commits that enabled it on ports into one commit, and update commit messages on most commits.

**Comment by dpgeorge** [comment]
Ok, I'm happy with this, it's ready to go in.

**Comment by dpgeorge** [comment]
Merged!

**Comment by tannewt** [comment]
Is it possible to use the compression for non-error strings? We compress the messages printed to the serial console as well (after we translate them.)

**Comment by jimmo** [comment]
hey @tannewt, yes for sure. The help text being an obvious candidate. I did some preliminary tests and there was definitely a benefit! (The help text on STM32 is over 2kiB).

I really wanted to avoid the need for any heap allocation, and minimise stack usage while decompressing, hence why the MP_MAX_UNCOMPRESSED_TEXT_LEN constant gets generated during the compression stage. But if we add longer text like the help text then that would skew that.

So the missing thing is a way to stream compressed data straight to a printer. There was also a TODO I added in this PR to make string formatting work with a compressed format string (without first decompressing in full) which would work in the same way.

**Pull request merged**
