### PR TITLE
esp8266: Move scan() from esp module to network

### PR DESCRIPTION
**Pull request by owens-bill**
Per the suggestion by @pfalcon on PR# 1325, moving the scan method from esp to network. This PR does not include any new code, nor the constants for the various authentication modes.

### CODE REVIEW

**Comment by pfalcon** [comment]
Looks good, will merge when when time permits. Doing it at this pace - one function at time, is just right, thanks @owens-bill !

**Comment by dpgeorge** [comment]
+1 from me.

[Note that the debug printf in the scan callback is removed, but I'm ok with that.]

**Comment by owens-bill** [comment]
> [Note that the debug printf in the scan callback is removed, but I'm ok with that.]

I figured that if I left that line in, there was at least a 50/50 chance that someone would say, "Why didn't you remove that old commented-out debug printf?" ;)

**Comment by dpgeorge** [comment]
> old commented-out debug printf

In some cases they are not "old" but are in fact used semi-regularly.  This case though is probably not needed anymore so good call removing it :)

**Comment by pfalcon** [comment]
Generally, it's better to avoid any other changes when performing a code move.

Merged, thanks.

**Pull request closed without merging**
