### PR TITLE
esp8266: Change UART(0) to attach to REPL via uos.dupterm interface.

### PR DESCRIPTION
**Pull request by dpgeorge**
This patch makes it so that UART(0) can by dynamically attached to and
detached from the REPL by using the uos.dupterm function.  Since WebREPL
uses dupterm slot 0 the UART uses dupterm slot 1 (a slot which is newly
introduced by this patch).  UART(0) must now be attached manually in
boot.py (or otherwise) and inisetup.py is changed to provide code to do
this.  For example, to attach use:

    import uos, machine
    uart = machine.UART(0, 115200)
    uos.dupterm(uart, 1)

and to detach use:

    uos.dupterm(None, 1)

When attached, all incoming chars on UART(0) go straight to stdin so
uart.read() will always return None.  Use sys.stdin.read() if it's needed
to read characters from the UART(0) while it's also used for the REPL (or
detach, read, then reattach).  When detached the UART(0) can be used for
other purposes.

If there are no objects in any of the dupterm slots when the REPL is
started (on hard or soft reset) then UART(0) is automatically attached.
Without this, the only way to recover a board without a REPL would be to
completely erase and reflash (which would install the default boot.py which
attaches the REPL).

See #2891 and #3277 for previous attempts at this.

### CODE REVIEW

**Comment by dreasGh** [comment]
Hi @dpgeorge,

i'm trying to do that with an esp32 (latest MP version) but without success, micropython throws the following error:
```
Traceback (most recent call last):
  File "boot.py", line 8, in <module>
ValueError: UART(0) is disabled (dedicated to REPL)
```
Is not it still possible to do it for now or am I doing something wrong?
Thanks in advance.

**Comment by robert-hh** [comment]
As the title tells, this change is dedicated to ESP8266. On an ESP32, you have more UART ports, so the need may not be that strong.

**Comment by dpgeorge** [comment]
> Is not it still possible to do it for now or am I doing something wrong?

As @robert-hh says, this PR here is for esp8266.  The ESP32 has 3 UARTs and 2 can be used for anything, while UART(0) is dedicated to the REPL.  @dreasGh are you really looking to use all 3 UARTS on the ESP32?

**Comment by dpgeorge** [comment]
This was merged in afd0701bf7a9dcb50c5ab46b0ae88b303fec6ed3

**Comment by hasenradball** [comment]
Hi guys,

one question about this Topic now it is possible to disable REPL but how can I disable the UART for example to use the UART Pins for one wire or else?

Frank

**Comment by dpgeorge** [comment]
> how can I disable the UART for example to use the UART Pins for one wire or else?

This is a good question for: https://forum.micropython.org .  A short answer: it's probably possible to just reconfigure them with `machine.Pin(1, machine.Pin.OUT)`.

**Pull request closed without merging**
