### PR TITLE
stmhal/can: Fix a bug in filterhandling

### PR DESCRIPTION
**Pull request by HenrikSolver**
reported here: http://forum.micropython.org/viewtopic.php?f=2&t=845

### CODE REVIEW

**Comment by dpgeorge** [comment]
I guess I'll trust you on this one!

Are there tests that can be written for this case?

**Comment by PappaPeppar** [comment]
Of course there shall be tests, I will add them. Sorry for my sloppiness :-)

**Comment by dpgeorge** [comment]
No problem.  It's just that if we are changing one seemingly random hex mask to another, then it would be nice to have a firm reason (ie test) that the change is correct :)

**Comment by PappaPeppar** [comment]
Now this PR also includes tests for the bug.

**Comment by dpgeorge** [comment]
Thanks @PappaPeppar!  Merged in 35e7d9c0f114ea078d0a19c7f9743fdc4c7e8a3b with some code-formatting edits to the test file (also, did you know in Python you can specify literal integers in base-2, eg `0b10110001`?).

**Pull request closed without merging**
