### PR TITLE
modmath: Add domain error checking to sqrt, log, log2, log10

### PR DESCRIPTION
**Pull request by mbuesch**
These functions will raise 'ValueError: math domain error' on invalid input.

My application catches this exception and does some required actions. See this for example: https://github.com/mbuesch/awlsim/blob/master/awlsim/core/instructions/insn_sqrt.py

### CODE REVIEW

**Comment by dpgeorge** [comment]
I think this would need to be configurable.  At the moment such functions return nan/inf, which is reasonable (?).  Note that there are a lot of other functions that need checking (eg atan2, acos, asin, atanh).

**Comment by mbuesch** [comment]
>At the moment such functions return nan/inf, which is reasonable (?).

I'm not sure. Is this really guaranteed by libc, or is it rather implementation defined or even undefined?

>I think this would need to be configurable.

The whole thing (math) already is configurable. Why bother adding another YES_I_REALLY_WANT_A_COMPLIANT_MATH config option?

**Comment by dpgeorge** [comment]
For the record, it adds 132 bytes to stmhal, 176 to unix (x86-64).

**Comment by dpgeorge** [comment]
Yes, ok, I accept that domain checking should be an integral part of the math module.

**Comment by pfalcon** [comment]
> Yes, ok, I accept that domain checking should be an integral part of the math module.

Good, because we don't have too much choice if CPython does that ;-)

**Comment by pfalcon** [comment]
> For the record, it adds 132 bytes to stmhal, 176 to unix (x86-64).

Obvious thing to try is to make

> nlr_raise(mp_obj_new_exception_msg_varg(&mp_type_ValueError, "math domain error"));

a standalone function.

**Comment by dpgeorge** [comment]
Modification made as per @pfalcon's suggestion and merged in 17298af61ededcfa4e96a6fdc6f484c79ffe220d.

Increase in code size is: 112 bytes for stmhal, 144 bytes for unix x86-64.

**Comment by mbuesch** [comment]
Nice, thanks.

**Pull request closed without merging**
