### PR TITLE
shared/runtime/softtimer: Generalise soft_timer to work with rp2

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR generalises the low-level soft timer driver so that it can be used on the rp2 port.  And then it integrates it into the rp2 port.

This allows the rp2 port to schedule C callbacks to run periodically/one-shot, preemptively and at PendSV interrupt level.

### CODE REVIEW

**Comment by dpgeorge** [comment]
@iabdalkader FYI.  You can pull this into #12858 and see if it works there.

**Comment by iabdalkader** [comment]
@dpgeorge I tested this and it seems to be working fine, meaning connection poll works as expected. I've also updated this PR: https://github.com/micropython/micropython/pull/12858

**Comment by robert-hh** [comment]
The SAMD build error can be silenced by adding these three lines to mpconfigport.h:
```
#define MICROPY_PY_PENDSV_ENTER   uint32_t atomic_state = raise_irq_pri(IRQ_PRI_PENDSV);
#define MICROPY_PY_PENDSV_REENTER atomic_state = raise_irq_pri(IRQ_PRI_PENDSV);
#define MICROPY_PY_PENDSV_EXIT    restore_irq_pri(atomic_state);
```

**Comment by dpgeorge** [comment]
Thanks for testing.  Good that it's working.

I've now updated samd and renesas-ra to build.

**Comment by dpgeorge** [comment]
This is blocked on #12873.

**Comment by dpgeorge** [comment]
We will probable need to work around the alarm-pool bug in pico-sdk, by using our soft-timer instead of alarm pool.  That means this PR needs to be merged now, then the bug can be fixed.

**Pull request merged**
