### PR TITLE
mpy-cross/main.c: Don't set a default native architecture.

### PR DESCRIPTION
**Pull request by jimmo**
If `-march` isn't set then it means the user hasn't thought about it, or in the case of freezing, MPY_CROSS_FLAGS isn't set. It's almost certainly going to lead to problems, as there's no reason why the host architecture is likely to be the right choice.

Compiling regular Python code is unaffected, but if `@native`/`@viper` is used, the compiler will raise `SyntaxError: invalid arch`.

_This work was funded through GitHub Sponsors._

### CODE REVIEW

**Comment by dpgeorge** [comment]
I agree with this change.  But I think it breaks some tests.  I added a commit to this branch to run unix CI to test things (apparently we don't run any builds or tests if only `mpy-cross` changes).

**Comment by dpgeorge** [comment]
When it runs the test suite with `--via-mpy` it gives:
```
 subprocess.CalledProcessError: Command '['/home/runner/work/micropython/micropython/mpy-cross/build/mpy-cross', '-o', 'tmp7axk_2ld.mpy', '-X', 'emit=bytecode', 'micropython/native_closure.py']' returned non-zero exit status 1.
```

Somehow we need to know the host machine's architecture and pass that through to mpy-cross during these tests... it might be easiest to do that via an option like:
```
$ mpy-cross -march=host
```

**Comment by jimmo** [comment]
> `$ mpy-cross -march=host`

Yes, that's a good idea. I will add that.

**Comment by jimmo** [comment]
Done.

**Comment by dpgeorge** [comment]
Very good, thank you!

**Pull request merged**
