### PR TITLE
extmod/mod_network: Define network hostname globally for all nic boards.

### PR DESCRIPTION
**Pull request by omogenot**
This PR proposes to globally move hostname definition to the `network` module, so that it will be defined for all nic boards by using the `network.hostname()` method. The default host name is set to` mp-host` and the hostname length is controlled by the `MICROPY_PY_HOSTNAME_LENGTH` constant which is defaulted to 32 if not defined.
```
>>> import network
>>> network.hostname("my-host")
>>> network.hostname()
'my-host'
>>>
```
_Note:_ This PR would replace some of the modifications done specifically for the cyw43 board only (PR #8918), but keeps the ioctl functions up and running using this global hostname definition.

If the nic board uses the LWIP library, we take advantage of the integrated `mDNS` server (if the `LWIP_MDNS_RESPONDER` constant is defined) to declare hostname for that nic board.
```
>>> import network
>>> network.hostname("my-host")
>>> nic = network.WIZNET5K()
>>> nic.active(True)
>>> nic.ifconfig("dhcp")  
>>> # nic.ifconfig(("192.168.1.100", "255.255.255.0", "0.0.0.0", "0.0.0.0"))  # for fixed IP
```
From now on, on the network, you can perform a ping `my-host.local` to get a response from your micropython board.
I could not test these modifications for all nic boards, I have only WIZNET5K boards available.

### CODE REVIEW

**Comment by robert-hh** [comment]
This PR looks like a git fault.

**Comment by omogenot** [comment]
@robert-hh 
> This PR looks like a git fault.

This git stuff is really a pain... All this to resolve the conflicts introduced by the new `MP_DEFINE_CONST_OBJ_FULL_TYPE` macro usage in master.

**Comment by omogenot** [comment]
Commit message formatting error is not mine (don't know what to do...):
```
error: commit fe55984: Unwanted email address: peterhinch@users.noreply.github.com
```

**Comment by robert-hh** [comment]
How did you attempt to update? With `git merge master` or with `git rebase master`. I usually use `git rebase` to keep my PRs up-to-date. And I do it frequently. There were quiet a few git bombs recently which required a major rework of the PRs.

**Comment by omogenot** [comment]
@robert-hh 
I did a `git rebase master`, after having re-synced my master via the GitHub web page `Sync fork` button. 
But since, there were modifications in the same files as the one I modified, I had to resolve conflicts. I solved them, etc.
Then I ran a multiple build bash command file to check that everything was OK, before pushing the branch. 
And for any strange reason, the >>> Git conflict sign was added in the mod network.h file afterwards (since the multiple build worked before). This git stuff is really driving me nuts.
The funny thing is that my master is in sync with the micropython:master: `This branch is up to date with micropython/micropython:master.`, but my global-hostname brach is still behind the master `This branch is [9 commits ahead], [14 commits behind] micropython:master.`.
That's totally illogical, but I don't care as long as my RP now includes the master modified files with my own mods.
But as you can see, it still states: `This branch cannot be rebased due to conflicts` without showing any file being in conflict.
This git does whatever it wants...

**Comment by robert-hh** [comment]
@omogenot You cannot do it like that. There are 137 commits and 520 changed files in this PR, which aims to change a single feature.  So something went fundamentally wrong, and you have to start over.

The structures I  use are:
I have called the repository at micropython.org the `upstream` repository, and my fork of it is the `origin` repository. You may name them different, it's just names.
When I want to sync to a changed master, I change locally in to the master branch and run `git pull upstream master --tags`.
When I want to resync a branch (let's call it `new_feature`), I checkout into that branch with `git checkout new_feature` and rebase it with `git rebase master`. The rebase might bring up conflicts or even worse silent merge errors, which have to be resolved. If finally you run e.f. `git log --online`, you should see the master branch and on top of that your commit. Example below.
Then I might push it to my fork with `git push origin my_feature -f`. The -f option is required after the rebase. 

Example of a rebased branch. Note the line with the `upstream/master` tag:
```
336696883 (mimxrt_qecnt) mimxrt: Adapt for PR8813 - Optimise mp_obj_type_t storage.
fea4ffb8f mimxrt: Fixes to the documentation of the Encoder/Counter class.
6f2d90414 mimxrt: Add the documentation for the Encoder/Counter class.
9fb21ebde mimxrt: Add settings for MIMXRT1015.
20fe65df7 mimxrt: Add missing definition for the OLIMEX_RT1010.
ee6ca5339 mimxrt: Implement a Quadrature Encoder and Counter class.
bdbc44474 (upstream/master, origin/master, origin/HEAD, master) rp2/boards/WEACTSTUDIO: Add WEACTSTUDIO with multiple variants.
0bc1d1055 rp2/Makefile: Add support for BOARD_VARIANTS.
9d6f474ea py/objstr: Don't treat bytes as unicode in str.count.
dd9dcb594 esp32/machine_pwm: Don't use LEDC_USE_REF_TICK on ESP32-C3 variants.
3abcfb9ae esp32/modsocket: Use mp_obj_is_integer to test port type.
e6d351318 stm32/boards/NUCLEO_L152RE: Add NUCLEO-L152RE board support.
427d72667 stm32: Add support for STM32L1 MCUs.
```

**Pull request closed without merging**
