### PR TITLE
docs/library/machine.Pin.rst: Make it clear which methods are not core.

### PR DESCRIPTION
**Pull request by dpgeorge**
- Moved the non-core Pin methods (pull, mode, drive) to a separate sub-section.
- Added high/low methods to this section.
- Added "availability" lines to each method.

### CODE REVIEW

**Comment by kadamski** [comment]
@dpgeorge So, in order to set some pin high we can do:
pin(1)
pin.value(1)
pin.on()

and that should work on **all** boards, right? But additionally on some boards we can also do:
pin.high()

Could you help me to understand the reasoning behind this? I mean, its not a legacy thing as it was added even for the latest rp2 port, yet it is not available on all boards, for some reason, even though it could as pin.high is an equivalent of pin.on which is a core API. So what is the rationale?

**Comment by dpgeorge** [comment]
> and that should work on **all** boards, right? But additionally on some boards we can also do: pin.high()

Yes.

> Could you help me to understand the reasoning behind this?

There's a long history with pins and setting/getting their value.  They originally had high/low methods to start with but that choice of method name was discussed and argued at length and the methods on/off eventually added so that one could write something like `led = Pin(3, Pin.OUT)` and then `led.on()`, instead of `led.high()`.  And then to simplify things the high/low names were removed (again after much discussion).  But in my opinion, and with hindsight, removal of high/low was not the right thing to do because the high/low names make a lot more logical sense in many applications of GPIO.  Eg an SPI chip-select line goes "low" to turn it "on", and using the words high/low is a lot of the time conceptually what you want.

So my aim is to reintroduce the high/low methods (and also keep on/off).  I wanted to discuss and do that before merging the rp2 port, but I didn't get to it in time.  Hence the docs look like this at the moment.

**Comment by peterhinch** [comment]
For my money `__call__` does it all. I never understood the need for the rather theological debate. The following strike me as clear, concise and unambiguous:

```python
red_led(1)
green_led(0)
left_motor(1)
display_power(1)
```
Surely we all understand binary? After all, even on/off switches are labelled 1/0.

**Comment by kadamski** [comment]
@dpgeorge thanks for the explaination. I guess it's ok to have aliases but the situation where the code cannot be easily ported from one board to the other even if it's using just the basic functionality (like a gpio toggling) is not perfect. If the plan is to fix this issue and  reintroduce the high low to all boards, then I wouldn't see any issue about that :)

**Comment by robert-hh** [comment]
0/1 is supported on all ports, anf that's what I use.

**Comment by peterhinch** [comment]
> ...the situation where the code cannot be easily ported from one board to the other even if it's using just the basic functionality (like a gpio toggling) is not perfect.

This is very true. Writing cross platform code is becoming progressively harder, not least because of https://github.com/micropython/micropython/issues/5564. From time to time get reports of my code failing from users of hardware I don't possess: it turns out that some language feature or some library is missing from that port.

Where aliases exist, the docs should clearly show which one is supported by all ports.

**Comment by dpgeorge** [comment]
Thanks for the discussion.  Hopefully this PR (now merged) makes the situation at least clearer.

**Pull request merged**
