### PR TITLE
ports/mimxrt: Enable ROM text compression.

### PR DESCRIPTION
**Pull request by iabdalkader**

### CODE REVIEW

**Comment by dpgeorge** [comment]
@robert-hh  any comments?  IMO it's a good change.

**Comment by iabdalkader** [comment]
>  IMO it's a good change.

I think it saves about 3KBs (if I saw the before/after text size correctly) when building the 64 EVK.

**Comment by robert-hh** [comment]
No. That's fine. Saving flash is always good, even if the mimxrt boards have plenty of it.

**Comment by iabdalkader** [comment]
If it's enabled by default that's fine by my, but  it should be controllable from the board `mk` files and command line etc... which also requires the `MP_ERROR_TEXT` fixes

**Pull request merged**
