### PR TITLE
github/workflows: Add spell checking via codespell.

### PR DESCRIPTION
**Pull request by dpgeorge**
Running `codespell` on this repo picks up quite a few spelling mistakes that would be good to fix.

It also has lots of false positives...

Is this worth including in the CI?

Does it belong in the `code_formatting.yml` workflow, or in its own workflow?

### CODE REVIEW

**Comment by stinos** [comment]
> It also has lots of false positives...

Unless there's an easy way to make it ignore those (something like a rule making it discard all uppercase things, plus lists of things to ignore like 'ure') it seems more like an annoyance.

**Comment by dpgeorge** [comment]
> Unless there's an easy way to make it ignore those

Yes there are lots of options.  Like `--ignore-regex` and the ability to skip files.

**Comment by dpgeorge** [comment]
OK, with some simple exclusions I've reduced the number of reported spelling mistakes down from 850 to 380.  And most of these are spelling mistakes that should be corrected.

**Comment by stinos** [comment]
Yeah that looks good. Well, apart from the spelling errors themselves :)

**Comment by Josverl** [comment]
I think it would help if contributors run a check with the same rules before committing.
therefore I would suggest using a config file, there are [a few different formats](https://github.com/codespell-project/codespell#using-a-config-file) supported.
That way it can be included in a pre-commit hook or into an IDE.
Also I think a few more folder exclusions make sense to make this more usable on a dev setup rather than only in CI ( `.git,.*_cache,**/build*` ) 
**.codespell.rc** 
```
[codespell]
skip = ./drivers/cc3100,./ports/cc3200/hal,./lib,.git,.*_cache,**/build*
count =
quiet-level = 3
ignore-words-list = iput,ans,ure,extint 
ignore-regex = '\b[A-Z]{3}\b'
```

**Comment by dpgeorge** [comment]
Thanks for the feedback.

I've now make a config file `tools/codespell.cfg` with the relevant configuration.  And the `ci_code_spell_run` function in `tools/ci.sh` can be used (eg at the CLI) to run `codespell`.

I've also only included certain directories at the moment in the spell check, to make it easier to pass CI.  I excluded the `ports/` directory.  We can add that later with spelling fixed (when someone has time to do it).

I also fixed about 64 spelling mistakes in those directories that are included in the code spell CI.



> As a last comment, as a non-native-speaker:
> Please make it explicit which flavor/flavour of English should be used for the documentation. Im OK with UK , and US , but now I'm wondering if I need to update my internal AU dictionaries as well kangaroo

In AU we usually use UK spelling :smile:  

I think `codespell` allows both US and UK spelling, and we can leave it at that (although I prefer UK).

**Comment by jimmo** [comment]
> I've now make a config file `tools/codespell.cfg` with the relevant configuration

This probably won't help IDE auto-detection of the config, which would expect to find .codespellrc (hopefully this would be configurable but it would be good to make it work out-of-the-box which is I think what @Josverl was suggesting).

**Comment by dpgeorge** [comment]
> This probably won't help IDE auto-detection of the config, which would expect to find .codespellrc

Maybe we will go with `pyproject.toml`, per #10977.

@Josverl does `pyproject.toml` work for you?

**Comment by Josverl** [comment]
That should work. I can test tomorrow. Need to find a decent adding wit proper support for the tool ide platform combo

**Comment by dpgeorge** [comment]
I've moved the config to `pyproject.toml` in the root directory of this repo.  It's now possible to simply run `codespell` in the root of the repo to check the spelling (ie no arguments needed).

**Comment by Josverl** [comment]
The config in `pyproject.toml` is picked up by all tools I have tried with IDE integration in VSCode and Pycharm.
In most cases there are options to provide overrides in IDE settings. 
tested:
- black 
- codespell - included in Trunk
- pylance/pyright
- ruff

**Comment by dpgeorge** [comment]
Great, thanks for confirming `pyproject.toml` works!

**Pull request merged**
