### PR TITLE
rp2/boards/WAVESHARE_RP2040_PLUS: Add Waveshare RP2040-Plus board.

### PR DESCRIPTION
**Pull request by serialuart**

### CODE REVIEW

**Comment by jimmo** [comment]
Thanks @knuxify 

Could you please rename to remove the `_4MB`. We're going to start merging the different flash sizes into single boards with multiple variants. See https://github.com/micropython/micropython/pull/8505 where @mattytrentini is adding support for board variants to the rp2 port.

In the meantime though, I don't think this board comes in other sizes, so just renaming it should be all you need to do for this PR. Please also send a corresponding PR to https://github.com/micropython/micropython-media for the board image.

**Comment by knuxify** [comment]
I added the `_4MB` suffix to match [the board file definition in the pico-sdk](https://github.com/raspberrypi/pico-sdk/blob/master/src/boards/include/boards/waveshare_rp2040_plus_4mb.h), there's also a 16MB variant in that repo but it indeed seems that it never reached the market.

Without that, I get this error:

```
PICO target board is waveshare_rp2040_plus.
CMake Error at /home/knuxify/projects/micropython/lib/pico-sdk/src/boards/generic_board.cmake:22 (message):
  Unable to find definition of board 'waveshare_rp2040_plus' (specified by
  PICO_BOARD):

     Looked for waveshare_rp2040_plus.h in /home/knuxify/projects/micropython/lib/pico-sdk/src/boards/include/boards (additional paths specified by PICO_BOARD_HEADER_DIRS)
     Looked for waveshare_rp2040_plus.cmake in /home/knuxify/projects/micropython/lib/pico-sdk/src/boards (additional paths specified by PICO_BOARD_CMAKE_DIRS)
Call Stack (most recent call first):
  /home/knuxify/projects/micropython/lib/pico-sdk/src/board_setup.cmake:28 (include)
  /home/knuxify/projects/micropython/lib/pico-sdk/src/CMakeLists.txt:15 (include)
```

Where should I define the `PICO_BOARD` override?

**Comment by jimmo** [comment]
> Where should I define the `PICO_BOARD` override?

At the start of mpconfigboard.cmake

See e.g. https://github.com/micropython/micropython/blob/master/ports/rp2/boards/W5100S_EVB_PICO/mpconfigboard.cmake

**Comment by knuxify** [comment]
I'll let #10314 supersede this one.

**Comment by RetiredWizard** [comment]
Sorry, I obviously didn't search open pull requests :/  I'll be sure for future PRs....

**Pull request closed without merging**
