### PR TITLE
extmod/moduhashlib: sha256 w/ mbedtls

### PR DESCRIPTION
**Pull request by Jongy**
Also, a bit of cleanup in `extmod/moduhashlib.c`.
It can now replace `ports/esp32/moduhashlib.c` so I might as well remove it and enable the common `uhashlib` module.

### CODE REVIEW

**Comment by Jongy** [comment]
Building with mbedtls reduces size by 2k~ on Linux 64-bit.

**Comment by dpgeorge** [comment]
Thanks for the contribution, it's a nice improvement!

Regarding the renaming of crypto-algorithms/ functions by prefixing `cryal_`: what exactly were they clashing with that prompted the change?  You'll notice that this change breaks the unix build, see lib/axtls/ssl/os_port_micropython.h for where these functions are referenced (but changing that requires changing the axtls submodule).

**Comment by Jongy** [comment]
I see. My bad, I'm more of an mbedtls guy, I didn't even attempt the axtls build.. :)

As I changed the sha256 object functions to match the names of the sha1 object methods (instead of being vaguely named `hash_update`, `hash_digest`...), we now had a `sha256_update` method and `sha256_update` which is the function from crypto-algorithms.

I can update the axtls `os_port_micropython.h` but I admit I don't like performing such changes in submodules (Such an header should probably reside in the MicroPython repository in the first place; How can we pull changes from axtls this way?).
Or, I can refactor the object methods in `moduhashlib.c` e.g to `sha1_obj_update`, `sha256_obj_digest` etc. Maybe prefix them all with `mp_` to give the notion these functions are exported to python? Anyway, the sha256 names should match the sha1 names.

**Comment by Jongy** [comment]
I'll continue with more work in other PRs (add optional md5 support, reuse extmod/moduhashlib in esp32)

**Comment by dpgeorge** [comment]
> Maybe prefix them all with mp_ to give the notion these functions are exported to python?

If you look at other modules in extmod/ you'll see that there's some consistency (but not 100% consistency) to prefix the internal function names with the name of the module.  In this case it would be something like `uhashlib_sha256_digest`.  That would be my preferred option.

**Comment by Jongy** [comment]
Prefixed everything with `uhashlib_`.

**Comment by dpgeorge** [comment]
Thanks for updating with the prefix.  I rebased this PR and did a bit of squashing to make the commits cleaner, in particular the prefixing with `uhashlib_` was done first.

See c2fb725e72f041a81b66e82ee4f7eebf55945061 for the last of the 5 commits.

And then in 0501427907283a29cf61bf5fba3ab17ac81b89df I removed the esp32 specific uhashlib implementation, to use the generic one instead.

**Pull request closed without merging**
