### PR TITLE
RP2 DMA Class

### PR DESCRIPTION
**Pull request by markb139**
Hi, Hope I haven't caused chaos trying to create this PR.
I've written a DMA class for the RP2040 microcontroller. 
The class handles 3 scenarios at present
1) write from a buffer to a peripheral
2)  read to a buffer from a peripheral
3)  copy one buffer to another

 Transfers can happen at full bus speed or be paced by a DREQ channel. 
This code includes a DMA timer class for pacing transfers at a fixed rate - see example code. 

The methods can be given an optional handler for callback when a transfer completes when an IRQ is raised. Which IRQ is raised defaults to IRQ0, but can be passed in with the irq parameter.

Regards 
Mark

### CODE REVIEW

**Comment by samskiter** [comment]
Would be amazing to see this merged!

**Comment by markb139** [comment]
Hi,
I've been away from the Micropython world and the RP2040 over the summer.
I plan to update my project that makes use of the DMA code. 

Looks like I have a couple of merge conflicts to fix

Regards

**Comment by samskiter** [comment]
I've 

> Hi, I've been away from the Micropython world and the RP2040 over the summer. I plan to update my project that makes use of the DMA code.
> 
> Looks like I have a couple of merge conflicts to fix
> 
> Regards

Might have you sorted there... https://github.com/markb139/micropython/pull/1

**Comment by samskiter** [comment]
Just to let you know there's issues with the documentation and the stubs

https://github.com/Josverl/micropython-stubs/issues/727

**Comment by samskiter** [comment]
@markb139 just FYI, there's a competing PR: https://github.com/micropython/micropython/pull/7641 can you evaluate and compare?

**Comment by markb139** [comment]
I'll take a look.
I'm currently Pi-less as my Pi's are doing other things and my Pi5 hasn't arrived :)

**Comment by dpgeorge** [comment]
Thanks for the contribution, but I'll close this in favour of the implementation made in #7641 (which is now merged).

**Comment by markb139** [comment]
No problem.

**Pull request closed without merging**
