### PR TITLE
esp32/modesp32: Add temperature method for S2,C3 chips.

### PR DESCRIPTION
**Pull request by ThinkTransit**
Provide access to temp_sensor_read_celsius() on S2/S3/C3 chips.

Signed-off-by: Patrick Joy <patrick@joytech.com.au>

### CODE REVIEW

**Comment by ThinkTransit** [comment]
Support for S3 removed as this requires idf v4.4.2 or greater.

**Comment by dpgeorge** [comment]
Now that the esp32 port uses IDF v5, it looks like this function has been deprecated.

Could you please update to use the new API `temperature_sensor_get_celsius`?

**Comment by ThinkTransit** [comment]
> Now that the esp32 port uses IDF v5, it looks like this function has been deprecated.
> 
> Could you please update to use the new API `temperature_sensor_get_celsius`?

Will do, I don't know why this PR decided to close itself so will need to reopen a new one.

**Comment by ThinkTransit** [comment]
Reopening

**Comment by ThinkTransit** [comment]
@dpgeorge This has now been updated to use the new API. Tested on S2 and S3 modules, C3 compiles ok.

**Comment by projectgus** [comment]
This is an automated heads-up that we've just merged a Pull Request
that removes the STATIC macro from MicroPython's C API.

See https://github.com/micropython/micropython/pull/13763

A search suggests this PR might apply the STATIC macro to some C code. If it
does, then next time you rebase the PR (or merge from master) then you should
please replace all the `STATIC` keywords with `static`.

Although this is an automated message, feel free to @-reply to me directly if
you have any questions about this.

**Comment by dpgeorge** [comment]
Sorry, this PR got lost, and it was superseded by the alternative implementation in 63c30a2dfc3118f2f82693dd96114b1efebf071c (which installs the temp sensor once).

**Pull request closed without merging**
