### PR TITLE
mimxrt: Some extensions and refactoring.

### PR DESCRIPTION
**Pull request by robert-hh**
- Refactor the reading of the machine id. The machine ID is provided by a single
  function, which can be used at different places.
- Add a driver for the DP83848 PHY device.
- Fix a tiny unnoticed bug in sdcard.c.
- Re-Enable ETH checksum creation by the Ethernet controller.
- Support selection of PHY type and address. Allowing to use various PHY adapters
  for boards without a PHY device.
- Define UART 0 on MIMXRT boards. At MIMXRT boards UART0 is then mapped
  onto the DEBUG USB port.

### CODE REVIEW

**Comment by robert-hh** [comment]
Hello @dpgeorge. May I kindly ask to to have a look at this PR. It is another 'service' type PR with a set of small improvements and fixes. The commits are:
- Define UART 0 on MIMXRT boards. At MIMXRT boards UART0 is then mapped onto the DEBUG USB port.
- Support selection of PHY type and address. Allowing to use various PHY adapters for boards without a PHY device.
- Fix a tiny unnoticed bug in sdcard.c.
- Add a driver for the DP83848 PHY device.
- Refactor the reading of the machine id. The machine ID is provided by a single function, which can be used at different places. That supports PR #8049 which then can use this function.
- Re-Enable ETH checksum creation by the Ethernet controller.
- Tidy up the board flash related files. Instead of 2 files per board, it's then 3 common files at the hal directory.

**Comment by dpgeorge** [comment]
Thank you, it looks really good, cleanly separated commits with good commit info.  Merged as-is.

**Comment by dpgeorge** [comment]
I see that you provided the same kw-args for the ETH constructor as esp32, `phy_addr` and `phy_type`.  Very good!

But one difference is that you put the `PHY_xxx` constants in the `network.LAN` class itself, whereas esp32 puts them in `network` directly.  IMO what you did here is better because the constants are only for `LAN` not any other network interface.  And it matches how `machine.Pin` works, its constants are like `Pin.IN` etc.

**Comment by robert-hh** [comment]
Thank you. You teached me well.

**Pull request merged**
