### PR TITLE
Preliminary but working implementation of 64-bit NaN boxing for 32-bit archs

### PR DESCRIPTION
**Pull request by dpgeorge**
I've been quiet the past few days because I wanted to get this finished off: a new object model that implements 64-bit NaN boxing for 32-bit architectures.

The PR is not for merging, and there's no real need to review it yet.  It's more that I wanted to publish what I had in case others find it interesting and/or useful.  It'll sit on the back burner until a lot of the other, more important stuff has been dealt with.

Tested with x86 unix version, passes all tests in basics/ directory and all but 2 in float/ directory.  Build the unix version on a 32-bit machine, or on a 64-bit machine with `make MICROPY_FORCE_32BIT=1`.  Then run the tests as usual (or just use it as usual!).

There are a lot of changes, but most are just wrapping object pack/unpack in `MP_OBJ_CAST` and `MP_OBJ_UNCAST`.  Interesting thing to note is the introduction of types more friendly for putting in ROM (eg `mp_rom_map_t` instead of `mp_map_t`).  To understand the object model, check out mpconfig.h and obj.h, the sections around `MICROPY_OBJ_REPR_D`.

### CODE REVIEW

**Comment by pfalcon** [comment]
I'm glad that MP_OBJ_CAST/MP_OBJ_UNCAST show their viability. And I guess, applying them can be a separate commit on its own (I at all did it on file by file basis). NaN boxing itself looks clean and easy. Didn't yet grok new ROM object stuff, guess that could use separate commit too.

**Comment by dpgeorge** [comment]
> I'm glad that MP_OBJ_CAST/MP_OBJ_UNCAST show their viability.

Yes they are necessary.  But, even after adding 100's of them I still can't remember intuitively which goes from obj->ptr and which ptr->obj...... Much easier to read/use would be MP_OBJ_TO_PTR and MP_OBJ_FROM_PTR (or even swap them, because I think MP_OBJ_CAST should create a uPy object).

> And I guess, applying them can be a separate commit on its own

It could.

> NaN boxing itself looks clean and easy

It is rather simple, once the CAST/UNCAST stuff is there, and also the MP_ROM_OBJ stuff.

Whilst this PR works, there are lots of things to tidy up (eg mp_uint_t should be size_t in many places).  But that can come another day.

**Comment by dpgeorge** [comment]
Closed in favour of #1655.

**Comment by pfalcon** [comment]
> But, even after adding 100's of them I still can't remember intuitively which goes from obj->ptr and which ptr->obj...... Much easier to read/use would be MP_OBJ_TO_PTR and MP_OBJ_FROM_PTR (or even swap them, because I think MP_OBJ_CAST should create a uPy object).

Sorry, I missed to respond to this, but I agree, after few months not looking into it, it takes some peering into code to grasp which does what.

> (or even swap them, because I think MP_OBJ_CAST should create a uPy object)

If it can be swapped and used both ways, that's usually a criterion for naming not being clean enough.

> MP_OBJ_TO_PTR and MP_OBJ_FROM_PTR 

I can only propose shorter alternative of MP_OBJ2PTR and MP_PTR2OBJ, but otherwise ok with change like that.

**Pull request closed without merging**
