### PR TITLE
tools/pyboard: Use platform-appropriate default serial device.

### PR DESCRIPTION
**Pull request by pramasoul**
Improve OSX compatability by glob-searching Linux and OSX ttys for the default device.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks, this looks good.

**Comment by pfalcon** [comment]
Is it? This adds a new dependency, but what value does it bring? Chooses "default" value randomly instead of it being static?

**Comment by dpgeorge** [comment]
> This adds a new dependency

Yes.  Alternative would be to check sys.platform (or os.uname()) and decide based on that.  But checking for the actual file is a more direct way.

Instead of glob could use os.stat and check known devices.

> what value does it bring?

Ease of use on more than 1 platform.

> Chooses "default" value randomly instead of it being static?

default value is currently rather arbitrary; it could have easily been tty.usbxx had I been developing on OSX.

**Comment by pfalcon** [comment]
> Ease of use on more than 1 platform.

It doesn't give any "ease of use", and value "calculated" is as arbitrary as a static. Real value on Linux can be /dev/ttyACM0, /dev/ttyACM1, ..., /dev/ttyUSB0, /dev/ttyUSB1, or any other /dev/tty*. That's especially true if "pyboard" tool is not seen as pyboard-specific, but as a generic tool to communicate with any MicroPython board.

Sure, if you see any value in adding extra dependencies for ~0 actual gain, well, ok.

**Comment by stinos** [comment]
Actual gain = on platforms which do have ttyUSB0 but not ttyACM0 - likely OSX - there's now a working default?

**Comment by dpgeorge** [comment]
There must be some gain if @pramasoul is submitting this PR.  And I guess it makes the script easier to use for a >90% of OSX users.

The code can also be extended to search for ttyUSB* if ttyACM* is not there.

> adding extra dependencies

We don't have to be so strict with dependencies here.  And a dependency on os.stat is pretty benign compared with a dependency on serial (which is most likely going to depend on os module anyway).

**Comment by pfalcon** [comment]
> Actual gain = on platforms which do have ttyUSB0 but not ttyACM0 - likely OSX - there's now a working default?

1) OSX doesn't have ttyUSBx; 2) this patch doesn't help anyhow with ttyUSBx.

The above proves the point - without user actually knowing where one's device is connected, doing any random guesses will likely only spur more layers of confusion. For example, I picture following "bug report": "My PyBoard works well with 'pyboard' tool on one Mac, but not on the other. My PyBoard must be broken, right?" Real cause: another Mac has Arduino attached, or 3G modem, or something you can't even predict and imagine.

**Comment by dpgeorge** [comment]
> 1) OSX doesn't have ttyUSBx ... The above proves the point

Not really, since @stinos is not an OSX user so he's not expected to know about tty.usb*.

> or something you can't even predict and imagine.

By this reasoning there should be no default.

**Comment by pfalcon** [comment]
> By this reasoning there should be no default.

Or maybe it can be left as is and no "solutions" applied which, while bringing supposed benefits, also bring more problems (I won't be saying they bring more problems than benefits, but for me "more problems" part is enough).

All in all, it's not *that* important, but I'm happy to be a conservative force to vote against vendor-specific bloat. (It may become a problem if past OSX users we get a line of BeOS, VAX, etc. users, Raspberry Pi users who want their HW UART device to be default, etc., etc.)

**Comment by stinos** [comment]
> Not really, since @stinos is not an OSX user so he's not expected to know about tty.usb*

Have been though :) I actually did mean tty.usb*, not ttyUSBx, that was a bad copy-paste from the above comment instead of from the source

Anyway: listing what is available and defaulting to the first one (either fully programatically like here, or through a UI where a list is presented and first one is selected) is pretty much the standard when it comes to selecting serial (or other) ports. So this change seems reasonable except maybe that it does not cover all possible platforms out there. Which is impossible anyway, but it doesn't really hurt to address the platforms which are used most in a sensible way

**Comment by dpgeorge** [comment]
> while bringing supposed benefits, also bring more problems ... for me "more problems" part is enough

And by *this* reasoning no one should ever write any code, ever :)

**Comment by pfalcon** [comment]
> through a UI

> So this change seems reasonable except maybe that it does not cover all possible platforms out there.

So that's why it's not reasonable. Command-line apps are usually written per Unix paradigm - doing one thing, and doing it well. Doing something and yet guessing where might have attached something is already too much for a good backend tool. Indeed that's quite different from how GUI apps are written. So perhaps users who care should write big fat GUI app with exciting new ribbon toolbars which does port auto-detection, and then maintain it ;-).

**Comment by pfalcon** [comment]
> And by this reasoning no one should ever write any code, ever :)

Good thing that you will decide how it should be ;-)

**Comment by dpgeorge** [comment]
> a good backend tool

Maybe this is where we differ in opinion: pyboard.py is both backend and frontend.

**Comment by dhylands** [comment]
I wrote a script for linux called find_port.py https://github.com/dhylands/usb-ser-mon/blob/master/find_port.py

I wrote this with the intention of calling it from within bash scripts. It What we really need is a cross platform version of that (and make find_port importable).

With find_port.py, I can do: [code]find_port.py -n Micro_Python[/code] and it will print /dev/ttyACM0 (or /dev/ttyACM1 etc). It can also search by VID or PID or list all of the available ports.

**Comment by dhylands** [comment]
I put my version of providing a default port in PR #1328

**Comment by pramasoul** [comment]
Unnecessary.

**Pull request closed without merging**
