### PR TITLE
py: Overhaul and simplify printf/pfenv mechanism.

### PR DESCRIPTION
**Pull request by dpgeorge**
Previous to this patch the printing mechanism was a bit of a tangled
mess.  This patch attempts to consolidate printing into one interface.

All (non-debug) printing now uses the mp_print\* family of functions,
mainly mp_printf.  All these functions take an mp_print_t structure as
their first argument, and this structure defines the printing backend
through the "print_strn" function of said structure.

Printing from the uPy core can reach the platform-defined print code via
two paths: either through mp_sys_stdout_obj (defined pert port) in
conjunction with mp_stream_write; or through the mp_plat_print structure
which uses the MP_PLAT_PRINT_STRN macro to define how string are printed
on the platform.  The former is only used when MICROPY_PY_IO is defined.

With this new scheme printing is generally more efficient (less layers
to go through, less arguments to pass), and, given an mp_print_t*
structure, one can call mp_print_str for efficiency instead of
mp_printf("%s", ...).  Code size is also reduced by around 200 bytes on
Thumb2 archs.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Update: converted remaining non-debug printfs to mp_printf, and added support for %q formatting.  The latter makes printing qstrs a bit simpler and decreases code size a bit.

**Comment by dpgeorge** [comment]
@pfalcon this PR was mainly for advertising, but if you have any comments let me know, otherwise I'll merge.

**Comment by danicampora** [comment]
Merge it ;-)

**Comment by pfalcon** [comment]
Yes, looks good, thanks!

**Comment by dpgeorge** [comment]
Merged, see a86d40ccd437fe0235c09426ef6d552b968d86e8 and previous 4 commits.

**Pull request closed without merging**
