### PR TITLE
unix/modffi: Use a union for passing/returning FFI values.

### PR DESCRIPTION
**Pull request by dpgeorge**
See issue #7064.

I'm not sure if this is 100% correct, will need more testing.

### CODE REVIEW

**Comment by dpgeorge** [comment]
@hroncok can you please test this PR out with GCC 11 on i686 and armv7hl, to see if it compiles without warnings/errors?  Also would be great if you can run the test suite:
```
$ cd ports/unix
$ make
$ make test
```

**Comment by hroncok** [comment]
Here is a 1.14 with this patch, we run tests during the build: https://koji.fedoraproject.org/koji/taskinfo?taskID=65904891

**Comment by hroncok** [comment]
All good.

**Comment by dpgeorge** [comment]
Great, thanks for testing.  Looks like `unix/ffi_float.py` tests are running and passing, so that is very good.

@hroncok is there a deadline for this patch to go in so it's usable by Fedora?  I still want to add some more tests to the test suite for this.

**Comment by hroncok** [comment]
No deadline really. This blocks us from upgrading to 1.14 but the final freeze for Fedora 34 is already over anyway. We'll update in Fedora 35 and that gives us plenty of time.

**Comment by dpgeorge** [comment]
Added a test which failed prior to this fix.

**Pull request merged**
