### PR TITLE
Make unix port use mp-readline library, take 2

### PR DESCRIPTION
**Pull request by dpgeorge**
An improved version of #1263, which adds mp-readline to unix port, but also keeps option to use GNU readline.  Default is mp-readline.

@blmorris could you please check this on OSX?

@stinos could you please check this on Windows?

### CODE REVIEW

**Comment by dpgeorge** [comment]
There are still some issues with this.  Eg, when executing a file it shouldn't set the terminal to raw mode.

**Comment by Anton-2** [comment]
Tested on OS X (v 10.10.3, command line tools v 6.3). Compiles cleanly,  works perfectly.

**Comment by blmorris** [comment]
@Anton-2 - Thanks, good to hear. I won't get a chance to try it until this evening - using 10.7.5, although it probably won't make a difference with compiling.

**Comment by blmorris** [comment]
Working for me, compiles, tests pass, looks good.

**Comment by stinos** [comment]
Seems ok for msvc after implementing it's own mp_hal due to lack of termios and VT100 commands. See https://github.com/stinos/micropython/commit/bca85b79b4b5a7ffa62d16c1b76505245e0f879a and https://github.com/stinos/micropython/commit/8dd0a3ec5114894284dbb9f29256a881f5385000.

**Comment by dpgeorge** [comment]
Simplified and improved the handling of ctrl-C and setting of raw terminal mode, and merged in 9ae3fc65235303322ef5282d3cdd4ca99a2c37cc.

Raw mode is now only active when doing the readline call (as per GNU readline).  This makes it more compatible with original behaviour (which is CPython behaviour) and decouples raw terminal mode from ctrl-C handling.

**Comment by dpgeorge** [comment]
@stinos would you be able to update your patches for msvc?

**Comment by stinos** [comment]
Yes no problem; also wanted to address to minor annoyances but need some info:
- the escape sequence for the delete key I see here when using the unix port is ```ESC[3~``` It is not handled by readline.c so I'm wondering what the reason is: do i have a different escape sequence than others, is it an oversight or is it something else?
- it seems feasible to print a newline after using Ctrl-D as most other programs do this as well and it leaves you with a proper prompt instead of ```>>> <prompt here>``` Ok?

**Comment by pfalcon** [comment]
>  the delete key I see here when using the unix port is ESC[3~

Ack, that's also what I have (xterm).

**Comment by dpgeorge** [comment]
> do i have a different escape sequence than others, is it an oversight or is it something else?

Reason: my keyboard doesn't have a "delete" key (only backspace) so I never use it, hence why I never implemented it :)

> it seems feasible to print a newline after using Ctrl-D

Agree.

**Pull request closed without merging**
