### PR TITLE
mp_vprintf: when an unsupported format specifier is encountered print it and exit

### PR DESCRIPTION
**Pull request by dxxb**
Arguments of an unknown type cannot be skipped and continuing to parse a format string after encountering an unknown format specifier leads to undefined behaviour.

### CODE REVIEW

**Comment by dpgeorge** [comment]
This will break the previous case (the 'l') which falls through to this default.  Also, if the conversion char is unknown then it's also not know what the size is of the argument (it could be an int or a double, for example).

**Comment by pfalcon** [comment]
@dxxb : You don't explain why all this is needed at all. Please see https://github.com/micropython/micropython/wiki/ContributorGuidelines - we don't need more bytes in uPy, we need less (and some people work on this, so please have good reasons to go in the opposite direction).

**Comment by dxxb** [comment]
@pfalcon, I was going to open a separate issue to talk about the way I found this issue. When I submitted this pull request I thought I was fixing a bug with next to no code size increase. I still think mp_vprintf() should print an error and exit rather than producing undefined results (i.e. segfault with utterly unhelpful backtrace like in my case).

As to how I found this problem: I am loading a shared library using FFI which uses vsnprintf(), micropython defines it's own vsnprintf() which ultimately calls mp_vprintf() and the dynamic linker decides to use micropython's vsnprintf() which has undefined behaviour for unsupported format specifiers.

So my options are:
- Make micropython use libc's *printf() functions. How do I do that? I tried removing lib/utils/printf.c from LIB_SRC_C and it seems to work on but it probably has side effects I am unaware of.
- Hide *printf() symbols using visibility options when linking micropython (I tried, no joy)
- Implement format specifiers in mp_vprintf() each time I stumble upon an unsupported one I need. This isn't going to to go down well with you guys... (but surely I don't want my program to segfault when this happens!)

I figured the best option is to make micropython use libc's implementation because it doesn't require changes to mp_vprintf() (except for adding a clear error when it misbehaves 😉). Any advice please? Thank you

**Comment by dxxb** [comment]
Updated commit, title and description. Some tests now fail. For instance 
```
>>> '%c' % 'aa'
unsupported fmt char '%'
micropython: ../py/mpprint.c:545: mp_vprintf: Assertion `0' failed.
```
instead of the the expected TypeError.

**Comment by dpgeorge** [comment]
> Some tests now fail.

That's because the "default" case is doing something important, in this case printing the "%" character when given "%%".

Note that the behaviour of printf from the C library is to just print the unknown format character and not consume any varargs, and then continue.

**Comment by dxxb** [comment]
> That's because the "default" case is doing something important, in this case printing the "%" character when given "%%".

Ack, updated pull request to handle quoting %. Only unix/extra_coverage.py fails for obvious reasons:
```
mp_printf(&mp_plat_print, "%t\n"); // non-format char
```

> Note that the behaviour of printf from the C library is to just print the unknown format character and not consume any varargs, and then continue.

There are many libc implementations and many versions of each; maybe they all do the same thing, maybe they do not but micropython does not have to reproduce implementation details of any. Also, a C compiler will emit a warning when it encounters an invalid conversion specifier which mitigates the issue in case of C.
> The results are undefined if there are insufficient arguments for the format. 
> [...]
> If a conversion specification does not match one of the above forms, the behavior is undefined. If any argument is not the correct type for the corresponding conversion specification, the behavior is undefined.
> [...]

(see http://pubs.opengroup.org/onlinepubs/9699919799/)
So according to the standard the behaviour is undefined i.e. we can do what we like including corrupting the stack and make the problem harder to trace when it happens, but why would we?
I think the two sane alternatives are displaying an error and abort the interpreter or emit a warning and immediately return from mp_vprintf(). Comments?

**Comment by pfalcon** [comment]
> Comments?

The best alternative is "don't do anything, unless there're compelling reasons". In this case, you're trying to fix problem with dynamic linker of your OS by patching a specific function of MicroPython. Likely wrong place to apply effort.

**Comment by dxxb** [comment]
> In this case, you're trying to fix problem with dynamic linker of your OS by patching a specific function of MicroPython. Likely wrong place to apply effort.

That's another issue and there a separate issue number for it. Here I am trying to improve micropython a bit by sparing someone else a lot of work tracing a segfault caused by an unsupported 
printf conversion specifier. It is potentially hard to trace because the undefined behaviour can (and did in my case) result in an empty call stack.

> The best alternative is "don't do anything, unless there're compelling reasons".

Right, and the reason seems very compelling to me. I am making this error unambiguous instead of having unpredictable (and possibly delayed) side effects.

**Comment by pfalcon** [comment]
Sounds good. I'm all for fixing real issues if they're discovered while working on something else. It's sometimes "fixing" "issues" in such "I passed by and decided to tweak something" manner lead to trail of regressions to be discovered later. One was discovered already (a luck). And note that there's no undefined behavior on MicroPython side - it's closed system, and only supported format specifiers are used. Bug in your dynamic loading opened it up, and now you try to fix "something".

**Comment by dxxb** [comment]
I can trigger undefined behavior in MicroPython calling  *printf() from an extension module written in C. C compiler will not emit a warning because it knows about the conversion specifiers supported by a standard compliant *printf() function not the limited set supported by the MicroPython one at any given time.

**Comment by dpgeorge** [comment]
I'm happy to change the code in the following way: add a case for "%%" (as it's done in the current version of the PR) and make the default case simply an unconditional assertion, eg `assert(!"unsupported format character")`.  That way the code stays the same size as before with debugging (assertions) disabled, but gives an error message when debugging is enabled.

**Comment by dxxb** [comment]
@dpgeorge, PR updated as per your suggestion. I have folded the "% at end of string" case into the default case and removed the two test cases which triggered assert()

**Comment by dpgeorge** [comment]
> I have folded the "% at end of string" case into the default case

That's a nice trick, but it's too tricky: when compiling without assertions there will be nothing that checks for % followed by null and the loop will continue reading past the end of the string.

**Comment by dxxb** [comment]
> when compiling without assertions there will be nothing that checks for % followed by null and the loop will continue reading past the end of the string.

Ouch, sorry about that! If you are OK with a _return_ after the _assert()_ I'll add it, otherwise I'll just restore the previous handling of the 'end of string' case.

**Comment by dxxb** [comment]
@dpgeorge, I have updated the PR reinstating previous handling of the 'end of string' case.

**Comment by dpgeorge** [comment]
I changed the way you implemented it so it's closer to the original behaviour, and still has full coverage testing.  See f98bb2ddcbfed7033ae93ae8fe98b0540a9fb42f

**Pull request closed without merging**
