### PR TITLE
tests/extmod/vfs_fat_ramdisk.py: Fix tests failing on appveyor due to missing uerrno

### PR DESCRIPTION
**Pull request by deshipu**

### CODE REVIEW

**Comment by deshipu** [comment]
Appveyor fixed, but Travis died (I think it's unrelated to this change, though).

**Comment by dpgeorge** [comment]
I would rather enable uerrno on windows build, that should be as simple as adding `#define MICROPY_PY_UERRNO (1)` to windows/mpconfig.h...

**Comment by deshipu** [comment]
That indeed seems like a much saner approach, thanks for pointing it out.

**Comment by deshipu** [comment]
Now this time Travis's failure seems legit https://travis-ci.org/micropython/micropython/builds/158131161#L3669-L3679

```
../py/moduerrno.c:63: error: ‘EOPNOTSUPP’ undeclared here (not in a function)
../py/moduerrno.c:63: error: ‘EADDRINUSE’ undeclared here (not in a function)
../py/moduerrno.c:63: error: ‘ECONNABORTED’ undeclared here (not in a function)
../py/moduerrno.c:63: error: ‘ECONNRESET’ undeclared here (not in a function)
../py/moduerrno.c:63: error: ‘ENOBUFS’ undeclared here (not in a function)
../py/moduerrno.c:63: error: ‘ENOTCONN’ undeclared here (not in a function)
../py/moduerrno.c:63: error: ‘ETIMEDOUT’ undeclared here (not in a function)
../py/moduerrno.c:63: error: ‘ECONNREFUSED’ undeclared here (not in a function)
../py/moduerrno.c:63: error: ‘EHOSTUNREACH’ undeclared here (not in a function)
../py/moduerrno.c:63: error: ‘EALREADY’ undeclared here (not in a function)
../py/moduerrno.c:63: error: ‘EINPROGRESS’ undeclared here (not in a function)
```
I guess we need some additional ``#include`` on Windows?

**Comment by deshipu** [comment]
Or we could move the `ERRNO_LIST` out of `moduerror.c` and into the individual `mpconfigport.h` files, and just skip those constants on Windows?

**Comment by deshipu** [comment]
So I removed the troublesome constants from the Windows build for now. Perhaps they can be found in one of the header files specific to Windows, but I have no way to test that. I guess they could be added when they become needed.

**Comment by dpgeorge** [comment]
Although there is a comment in moduerrno.c about putting ERROR_LIST in mpconfigport.h, I think it would be good to keep the centralised list in moduerrno.c to prevent too much difference across ports.

The windows port does build and pass all other tests so fixing this is not critical for release.  Let's wait for @stinos to comment and/or provide a neater solution.

**Comment by stinos** [comment]
Problem is for the mingw cross-compiler only: it builds fine with mingw here (which has EOPNOTSUPP and the others in errno.h, as it should be). looking into this I figured the real problem is travis uses mingw32 which is afaik abandoned and broken. See https://github.com/micropython/micropython/pull/2409 for a fix.

**Pull request closed without merging**
