### PR TITLE
extmod/modure: Make regex dump-code debugging feature optional.

### PR DESCRIPTION
**Pull request by dpgeorge**
Background: the `ure` module provides a debugging capability via `ure.compile(<regex>, ure.DEBUG)`, in which case it dumps out the compiled regular expression in human readable form.

This patch makes this debugging feature optional, enabled via MICROPY_PY_URE_DEBUG, and disabled by default.

This is a backwards incompatible change, but I doubt that it's used much, and debugging of regular expressions can be easily done offline with other tools.

Change in code size is significant:
```
   bare-arm:    +0 +0.000% 
minimal x86:    +0 +0.000% 
   unix x64:  -864 -0.173% [incl -32(data)]
unix nanbox:  -848 -0.190% [incl -32(data)]
      stm32:  -524 -0.142% 
     cc3200:  -560 -0.301% 
    esp8266:  -788 -0.120% 
      esp32:  -828 -0.075% [incl -144(data)]
        nrf:    +0 +0.000% 
       samd:    +0 +0.000% 
```

### CODE REVIEW

**Comment by stinos** [comment]
+1 seems worth it, I really wonder how many people are aware this even exists, let alone use it

**Comment by MrSurly** [comment]
Just by 2 cents -- I come from using Perl, which is pretty heavy on regex, so I often use regexes in Python.  I've never heard of this flag, and obviously have never used it, so I'd also vote +1.

**Comment by dpgeorge** [comment]
Thanks for the comments/feedback.

This feature is actually in CPython as well, but there it is almost undocumented (`re.compile` mentions the flags argument but not what flags are available, nor what they do, and the `re.DEBUG` constant is listed later on but not which function it applies to).

**Comment by dpgeorge** [comment]
Merged in 7d851a27f146188752e89bb026021fb8d3985395

**Pull request closed without merging**
