### PR TITLE
Add .__base__

### PR DESCRIPTION
**Pull request by nanfang2000**
Add CPython compatible attribute .__base__ for retrieving base Class

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.

Independent of whether or not this would be a good thing to add, I think the correct implementation would be to put it in `py/objtype.c:type_attr()`, similar to how `__name__` is handled.

Also, it seems that `__base__` (singular) is not documented in the Python docs, but `__bases__` (plural) is: https://docs.python.org/3/library/stdtypes.html#class.__bases__ .  Arguable the plural version is more useful to have because it will give all base classes in the case of multiple inheritance.

**Comment by nanfang2000** [comment]
That's OK. Hope you can implement it both __base__ and __bases__. I have no confidence to modify the py/objtype.c:type_attr()

**Comment by pmp-p** [comment]
about usefullness    `__base__` is a readonly attribute and its implementation has almost no cost.
meanwhile `__bases__ ` is for modifying mro of a class and i really doubt it's usefull for everyday micropython. I think if one wants mutabilty reassigning `.__class__` of instance would be more than enough which actually does not work. 
test code 
`

class null(object):
    pass

class A(null):
    a = 'a'
    b = '?'

class B(null):
    a = '?'
    b = 'b'


a = A()
b = B()

x = A()



print()
print('a', a )
print('a.a', a.a )
print('a.b', a.b )


print()
print('b', b )
print('b.a', b.a )
print('b.b', b.b )

print()
print('x',x)
print('x.a',x.a)
print('x.b',x.b)


print("="*60)
try:
    print( x.__class__.__base__ )
except : print('no.__base__')
try:
    print( x.__class__.__bases__ )
except : print('no.__bases__')

x.__class__ = B #.__class__


print()
print('a', a )
print('a.a', a.a )
print('a.b', a.b )


print()
print('b', b )
print('b.a', b.a )
print('b.b', b.b )

print()
print('x',x)
print('x.a',x.a)
print('x.b',x.b)
`



cpython

`
[...]

x <__main__.A object at 0x7fa7a4371c50>
x.a a
x.b ?
============================================================
<class '__main__.null'>
(<class '__main__.null'>,)

[...]
x <__main__.B object at 0x7fa7a4371c50>
x.a ?
x.b b

`


micropython
`
[...]
x <A object at 7f7aa1b0d5a0>
x.a a
x.b ?
============================================================
<class 'null'>
no.__bases__

[...]
x <A object at 7f7aa1b0d5a0>
x.a a
x.b ?
`

**Comment by pmp-p** [comment]
`__base__`  also allow a naive  read only `__bases__`  using 

```
class null(object):
    pass

    @classmethod
    def __bases__(cls):
        stack = [cls]
        while True:
            try:
                stack.append(stack[-1].__base__)
            except:
                break
            if stack[-1] is cls:
                break
        stack.pop(0)
        stack.pop()
        return tuple(stack)


class A(null):
    a = 'a'
    b = '?'

class B(null):
    a = '?'
    b = 'b'

x = A()


print("="*60)
try:
    print( x.__class__.__base__ )
except : print('no.__base__')
try:
    if not isinstance( x.__class__.__bases__ , tuple):
        raise Exception('no.__bases__')
    print( x.__class__.__bases__ )
except :
    print('no.__bases__','fixing')
    print( x.__class__.__bases__() )
```

result 
```
<class 'null'>
no.__bases__ fixing
(<class 'null'>,)
```

**Comment by nanfang2000** [comment]
agree with Paul, we can implement '__base__' first than '__bases__'since multi-inherit is not fully supported in MPY.
if really need '__bases__' then we can use a native version Paul shows above.

**Comment by dpgeorge** [comment]
Closing in favour of #5139 (adds `__bases__`).

**Comment by dpgeorge** [comment]
8f9e2e325ab0d0dfa9457779010a4cb2cfe60fef added `__bases__`

**Pull request closed without merging**
