### PR TITLE
mpy-cross: Remove unnecessary else

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by stinos** [comment]
It's called *mpy-cross* :]

**Comment by patrickelectric** [comment]
ooooops, ty @stinos

**Comment by dpgeorge** [comment]
Thanks for the contribution.  But the refactoring here is arguably just a code-style issue, rather than an optimisation or something with a real effect.  And in this particular case it really is an important coding style: the if/else block is implementing a C++-style try/catch statement.  You will see some other cases of the same pattern in the code base (grep for nlr_push) and so this pattern here should stay as it is to match those.

**Comment by adritium** [comment]
@patrickelectric so are you gonna close this?

**Pull request closed without merging**
