### PR TITLE
esp32: Support dynamic configuration of ETH ref-clk mode and pin.

### PR DESCRIPTION
**Pull request by robert-hh**
Consisting of three commits:

- Add the PHY_LAN8710 name. the LAN8710 shares the code with the LAN8720.
- Implement the keyword options ref_clk_mode and ref_clk_pin to set the mode and Pin.
- Add a few words of documentation, picking up #7356, which was never merged, albeit considered as appropriate.

If ref_clk_mode is not set, the default settings e.g. taken from the board's config file are used. Setting ref_clk_mode and ref_clk_pin requires at least esp-idf v4.4. It builds with 

Tested with the Olimex esp32_POE and Olimex ESP32 POE ISO boards.

### CODE REVIEW

**Comment by robert-hh** [comment]
It seems that i forgot about PR #9710, which adds the same feature in a slightly different way. So one of both is obsolete.

**Comment by dpgeorge** [comment]
> It seems that i forgot about PR #9710, which adds the same feature in a slightly different way. So one of both is obsolete.

Since the author of that one is not responding, I'm happy to take this PR instead.

But see from the conversion there that we decided on `ref_clk` for the name of the argument that takes the pin.  So please change that here (from `ref_clk_pin` to `ref_clk`).

Also, the constant for the mode on mimxrt are `LAN.IN` and `LAN.OUT`, right?  And it also supports `Pin.IN` and `Pin.OUT`?  Yet in this PR its `LAN.REF_CLK_IN` and `LAN.REF_CLK_OUT`.  We need to be consistent.  As per https://github.com/micropython/micropython/pull/9710#issuecomment-1316080957 please change this PR to use `Pin.IN` and `Pin.OUT` for the `ref_clk_mode` constants.

**Comment by robert-hh** [comment]
No problem with teh changes.
Actually the constants are `NETWORK.REF_CLK_IN` and `NETWORK.REF_CLK_IN`, because the ESP32 implementation uses it's own modnetwork.c and not the one from extmod. That could eventually be changed, but would be a breaking change, requiring to keep the old mapping for a while. I have mapped them now to `PIN.IN` and `PIN_OUT` as well.

**Comment by dpgeorge** [comment]
> I have mapped them now to `Pin.IN` and `Pin.OUT` as well as `network.IN` and `network.OUT`.

Since these are new constants, I don't see why we need to have `network.IN` and `network.OUT` at all...?  Can't we just support `Pin.IN` and `Pin.OUT`?

**Comment by robert-hh** [comment]
Sure. That's as easy as deleting two lines of the code.

**Comment by dpgeorge** [comment]
Thanks, this has now been rebased, last commit squashed, and merged.  I also made one minor change, `ARG_ref_clk_pin` -> `ARG_ref_clk`.

**Comment by robert-hh** [comment]
Thanks twice. PR #7356 could be closed now as well, since I integrated it.

**Comment by robert-hh** [comment]
Thanks.

**Pull request merged**
