### PR TITLE
esp32/machine_timer: Switch from legacy driver to timer HAL.

### PR DESCRIPTION
**Pull request by dpgeorge**
The legacy driver was deprecated in IDF v5, and crashes when the ISR handler is called.  Instead of fixing the legacy code, this commit reworks the machine.Timer class to use the low-level HAL driver.

Fixes issue #11970.

TODO:
- [x] check behaviour of `timer.value()` matches existing behaviour (pre IDF v5)
- [x] test on ESP32S2
- [x] test on ESP32S3
- [x] test on ESP32C3

### CODE REVIEW

**Comment by robert-hh** [comment]
Tested with an Generic ESP32, timer.value() reports the time in ms units since the recent callback event of the timer. In one-shot mode, it is not reset.

**Comment by dpgeorge** [comment]
Thanks for testing.  Did you test with v1.20.0 (IDF v4)?  I'm wondering if the `timer.value()` return value matches the old behaviour.  (The new behaviour is as you describe above.)

**Comment by robert-hh** [comment]
I tested that with IDF 5.0.2. I can test with IDF 4.0 as well. 
Tested with:
ESP32C3_USB using a XIAO ESP32C3
ESP32S2 Generic build with a LILYGO board
ESP32S3 Generic build with a LOLIN S3 board

**Comment by robert-hh** [comment]
Tested timer.value() using a GENERIC ESP32 and the v1.20.0 image from the download site:
The behavior is the same.

There is a difference in how the timer object properties are printed. But that's another story. In the new version, it irritates slightly that the period is shown as µs units, while it is specified as ms. But that allows a better resolution if the freq=xxx argument is used.

**Comment by dpgeorge** [comment]
> There is a difference in how the timer object properties are printed.

Yes I deliberately changed this.  The old printing was not very useful.

I can change the new one to print the period in ms.

**Comment by robert-hh** [comment]
> I can change the new one to print the period in ms.

I just noticed that the printed value even as µs units seems wrong by a factor of 10. For a period of 1000 is shows 10_000_000. For a freq=333 is shows 30030 instead of 3003.

**Comment by dpgeorge** [comment]
> Edit: it has to be corrected by TIMER_SCALE

Yes indeed.  I have now fixed this, so it prints `period` in ms units.

This should be good to merge now.

**Comment by robert-hh** [comment]
Looks good & works.

**Pull request merged**
