### PR TITLE
Atmel/Microchip XPLAIN BOARD

### PR DESCRIPTION
**Pull request by rolandvs**
First in a series of the standard Atmel XPLAIN boards featuring the SAMD21J18

### CODE REVIEW

**Comment by jimmo** [comment]
Thanks! Please see #4994 for some changes that were made to SAMD configs (sharing the linker files across boards, renaming board.mk).

**Comment by rolandvs** [comment]
@jimmo I changed the file accordingly and as a result updated the two other ports and the Makefile too.

**Comment by rolandvs** [comment]
Also I noticed that the .P files are not in .gitignore

**Comment by jimmo** [comment]
@rolandvs Can you rebase on master, that will fix the gitignore (this is because #4991 moved the rule to the root .gitignore). Might as well squash while you're rebasing.

**Comment by jimmo** [comment]
Also, can you move the linker script to the parent directory and rename to the MCU, so that boards with the same MCU can share it. (see the other boards for examples).

**Pull request closed without merging**
