### PR TITLE
Introduce new top-level "shared/" dir and move 1st party lib code there.

### PR DESCRIPTION
**Pull request by dpgeorge**
Following on from #5036, this PR moves all first-party code developed for this project from lib/ to shared/, so that lib/ now only contains third-party code.

The following directories are moved as-is from lib to shared:

        lib/libc            -> shared/libc
        lib/memzip          -> shared/memzip
        lib/netutils        -> shared/netutils
        lib/timeutils       -> shared/timeutils
        lib/upytesthelper   -> shared/upytesthelper

All files in `lib/embed/` have been moved to `shared/libc/`.

`lib/mp-readline` has been moved to `shared/readline`.

`lib/utils` has been moved to `shared/runtime`, with the exception of `lib/utils/printf.c` which has been moved to `shared/libc/printf.c`.

The directory tree looks like this:
```
shared
├── libc
│   ├── abort_.c
│   ├── __errno.c
│   ├── printf.c
│   └── string0.c
├── memzip
│   ├── import.c
│   ├── lexermemzip.c
│   ├── make-memzip.py
│   ├── memzip.c
│   ├── memzip.h
│   └── README.md
├── netutils
│   ├── dhcpserver.c
│   ├── dhcpserver.h
│   ├── netutils.c
│   ├── netutils.h
│   └── trace.c
├── readline
│   ├── readline.c
│   └── readline.h
├── runtime
│   ├── gchelper_generic.c
│   ├── gchelper.h
│   ├── gchelper_m0.s
│   ├── gchelper_m3.s
│   ├── gchelper_native.c
│   ├── interrupt_char.c
│   ├── interrupt_char.h
│   ├── mpirq.c
│   ├── mpirq.h
│   ├── pyexec.c
│   ├── pyexec.h
│   ├── semihosting.c
│   ├── semihosting.h
│   ├── stdout_helpers.c
│   └── sys_stdio_mphal.c
├── timeutils
│   ├── timeutils.c
│   └── timeutils.h
└── upytesthelper
    ├── upytesthelper.c
    └── upytesthelper.h
```

Remaining in lib is now:
```
lib
├── asf4
├── axtls
├── berkeley-db-1.xx
├── btstack
├── cmsis
├── libffi
├── libhydrogen
├── libm
├── libm_dbl
├── littlefs
├── lwip
├── mbedtls
├── mbedtls_errors
├── mynewt-nimble
├── nrfx
├── nxp_driver
├── oofatfs
├── pico-sdk
├── README.md
├── stm32lib
├── tinytest
└── tinyusb
```

### CODE REVIEW

**Comment by iabdalkader** [comment]
This looks like a good time/place to ask, would it make sense to move pendsv.c and systick.c to runtime ? These two files can be used by any CMSIS-compliant port, even the rp2/pico-sdk now has a CMSIS component/layer, and generic enough to move a few levels up. One minor detail the dispatch enums will have to cover all the possible calls, but maybe it can be defined in mpconfigport.h.

**Comment by dpgeorge** [comment]
> This looks like a good time/place to ask, would it make sense to move pendsv.c and systick.c to runtime ?

Yes it would make sense to move those.  And also softtimer.c (and probably some other things).  This can be done at a later stage (ie not part of this PR).

**Comment by iabdalkader** [comment]
> Yes it would make sense to move those. And also softtimer.c (and probably some other things).

If softtimer.c is moved then at least mpbthciport.c can be moved too, if it's switched to machine_uart. I have an mpbthciport.c implementation with machine_uart (not tested) but should work.

**Comment by robert-hh** [comment]
Looks reasonable. Seems like some work for me to rebase the open mimxrt PR and PR's under construction to it.

**Comment by tannewt** [comment]
Looks good! Thanks for the reorg.

**Comment by dpgeorge** [comment]
> If softtimer.c is moved then at least mpbthciport.c can be moved too, if it's switched to machine_uart. I have an mpbthciport.c implementation with machine_uart (not tested) but should work.

Ultimately, the less code in ports/ the better (ie the more shared code the better).

> Seems like some work for me to rebase the open mimxrt PR and PR's under construction

It hopefully shouldn't be.  At the most it's just a few paths to find headers...

**Comment by robert-hh** [comment]
> It hopefully shouldn't be. At the most it's just a few paths to find headers...

It was indeed not that much. Most of it was sorted out by git. Just a few path names in the #include statements.

**Pull request merged**
