### PR TITLE
esp8266: modnetwork: add optional save_to_flash parameter to connect

### PR DESCRIPTION
**Pull request by MarkR42**
If an esp8266 wants to connect to many, many different networks over its lifetime,
writing the config to the same location in the flash each time will wear it out and significantly
shorten the device life.

I have bricked only 1 esp-12 module so far doing this :)

This patch adds an extra parameter to the connect() function, save_to_flash, which defaults to true, so it's backwards compatible.

I don't know why there were previously up to 5 optional ignored parameters to connect(), they were never documented but are gone now.

### CODE REVIEW

**Comment by pfalcon** [comment]
Same comments as to https://github.com/micropython/micropython/pull/2506#issuecomment-253236339

**Comment by deshipu** [comment]
I think that if we want to keep `connect()` compatible across the ports, then it should not save the credentials in the flash at all. No other port does that, and it's a potentially dangerous function that can physically damage your hardware.

**Comment by MarkR42** [comment]
However, it's a very useful function which is consistent with what's implemented in other esp8266 environments e.g. nodemcu. And probably existing users are relying on it.

**Comment by deshipu** [comment]
Then perhaps it should be in the `esp` module?

**Comment by pfalcon** [comment]
> I think that if we want to keep connect() compatible across the ports, then it should not save the credentials in the flash at all.

Yes, that's the plan how to do it, eventually (think years, not months).

In the meantime, the behavior of connect() regarding that stuff is underspecified - it's guaranteed to (try to) connect with the given credentials, and may do something else as a particular port wants (or has to do). That underspecification is golden, and trying to break it leads to problems. For example, this patch makes documentation lie to WiPy users - there connect() doesn't have no save_to_flash param (and it doesn't have it, because it's not part of the spec of "network" module interface; it's also the reason why esp8266 doens't have it).

**Comment by deshipu** [comment]
I don't know, "It's guaranteed to connect with the given credentials, and may permanently damage your hardware on a particular port" doesn't sound reasonable to me. If there is now a function that does connecting without the saving, why not switch to it? It's safer and more compatible with other ports.

**Comment by MarkR42** [comment]
The damage to the hardware is only in an extreme case. Normal usage of connecting to an accesspoint occasionally, or doing it as a one-time setup activity, would be fine.

In fact you can call it lots of times without a problem.

Even calling it on every boot would be ok, if you don't constantly reboot the device.

The problem really appears if you've got a loop which effectively does little else except connect to lots of accesspoints (like a "stumbler" application), which will wear out the flash within a relatively short time.

**Comment by kfricke** [comment]
> Even calling it on every boot would be ok, if you don't constantly reboot the device.
I have distributed a few battery based sensor nodes across my house. They do reboot every 5 minutes. So this is a case of destructive behavior in my opinion!

**Comment by peterhinch** [comment]
@kfricke Rebooting every 5 minutes sounds extreme - I thought I had dodgy WiFi but I can run for many hours without a reboot. In any case, rebooting to the same network doesn't update the flash and so won't cause wear - see the initial message.

**Comment by kfricke** [comment]
The reboot every 5 minutes is intended and during startup i do disable the network immediately. The reason is that keeping it running does influence my temperature sensors significantly.

After taking the measurements i do actively connect to my network (using the connect method). So this does indeed rewrite the configuration to flash on every boot.

**Comment by puuu** [comment]
I have a similar use case. I run a kind of weather station with solar charged battery. To save energy, the ESP is most of the time in deep-sleep mode and wakes up every 5 or 10 minutes. On every boot I check the battery state before activation of WiFi. Unfortunately, this requires running `wlan.connect(ESSID, PASSWD)` (including rewriting of the flash) on every reboot/wakeup. Therefore, I asked for a kind of reconnect without WiFi credentials (#2493 and #2506).

**Comment by peterhinch** [comment]
Perhaps you guys can explain this to me. After a reboot or a power cycle I simply wait until it's connected automatically. Only if this times out (rarely) do I send the credentials and specific network details. This seems to work. Is there a reason not to do it this way?:
```python
    sta_if = WLAN(STA_IF)
    if use_default:  # if not, skip this to force connection to a specific network
        secs = _WIFI_DELAY
        while secs >= 0 and not sta_if.isconnected():
            yield 1
            secs -= 1
    if not sta_if.isconnected():
        # connect to specific network
```

**Comment by chrismas9** [comment]
I won't comment on the merits of changing the API, except to say that I think its preferable to have a common API across all ports. That seems to be the long term plan ( @pfalcon ).

However an immediate fix to flash wear without an API change could be for connect() to read the credentials in flash first and only write them again if they are different.

There are valid use cases for coming out of deep sleep every 5 minutes ( @kfricke  @puu ) and this will wear out the flash in 11 months (100,000 cycles). @peterhinch your solution will work but requires users to understand the need to not wear out the flash. There will be lot of people (eg most young micro:bit owners migrating to ESP8266) who won't know that repeated connect() is dangerous until they brick a few modules. Also since other ports don't store credentials in flash portable examples and tutorials will probably use connect() every time.

**Comment by MarkR42** [comment]
@chrismas9 It won't fix the wear issue for me to only write to flash if different.

My application is connecting to many different accesspoints, I don't want the flash written each time I try to connect to an AP.

**Comment by kfricke** [comment]
I just tried out the suggestion of @peterhinch and can not succeed with his example. My Huzzah Feather does not reconnect to the previous network within 10 seconds and waiting even longer is not an option, because I do still need to run some of my ESP8266s on battery.
Two of my sensor nodes are running on 3x AA cells for 37 days now. My capacity and power usage calculations will let them run on the batteries for around 60 days. They do wake up every 5 minutes for 3-4 seconds with my old behavior of actively connecting to the wireless network.

Keeping the standpoint to support bad design decisions of others is counter-productive.

@pfalcon has the choice to react on constructive feedback or @dpgeorge should add the following features to the next release notes for the ESP8266 port to not lie on users:

1. Usage in battery powered environments depends on huge battery capacities or is only feasible without wireless network connectivity.
2. Rewrites a file on your flash every time connecting to wireless networks and thereby supports flash destruction.

**Comment by MarkR42** [comment]
@kfricke it is not a lie or a bug really.

Writing the wifi config information is a function of the ESP firmware and nothing in Micropython's implementation makes it happen. The other environments for esp8266 use the same scheme (as far as I'm aware); NodeMCU does not have a way to call wifi_station_set_config_current (as far as I can see)

**Comment by pfalcon** [comment]
> @pfalcon has the choice to react on constructive feedback

I already provided constructive feedback - this patch attempts to modify the standard MicroPython API in a non-compatible way. So, the submitter of such patch should provide discussion of this problem in the pull request. And now it's actually your turn to provide constructive feedback on that matter. Note that I'm not against this patch (well, the feature), but it should be done in a such way as to not break API compatibility. And exactly *your* thoughts on how to achieve this I invite you to share.

**Comment by pfalcon** [comment]
>  My Huzzah Feather does not reconnect to the previous network within 10 seconds and waiting even longer is not an option, because I do still need to run some of my ESP8266s on battery.

All modules I have *start* to connect using the saved parameters immediately after boot (say, within 1st second). However, how much time it takes for them to actually connect depends on a module or MicroPython, but on your WiFi signal picture. If you're living in a typical WiFi hell, and on the fringe of your own WiFi range (in WiFi hell, that can be 5 meters from the access point), it may take longer. If you're living on your private island, with only your own WiFi around, it will be fast.

**Comment by kfricke** [comment]
Looking at the MicroPython code and reading the Espressif SDK API reference (v1.4.0_0) I did notice that even our method esp_active does write to flash (https://github.com/MarkR42/micropython/blob/ba8b2b239a19c835fff4857eb2394dd0de859b48/esp8266/modnetwork.c#L74).
The API reference in section 4.11.4.15 `bool wifi_set_opmode ( WIFI_MODE opmode )` does write the sation mode into flash. Why don't we sue the non-persisting variant `..._current(...)` as @MarkR42 already mentioned for the connnect method and the `wifi_station_set_config_current` method?

Consistently using methods which use only the things they document to do should be the way to go and the persisting-everything-o-mania of the Espressif API can and should be avoided.
This is of course my opinion as a pure MicroPython user. But the insight and behavior more experienced developers got used to should not stand in the way of a clean and working API, which does things the way they are needed.
As can be seen in the current forum discussions regarding the machine API one should not argue with a stable and well prooven API, which effectively does not yet exist.

I do use the active() method at least twice in my programs each time it does run. So my flash wearing is even worse than thought :-(

@pfalcon, i am aware enough of my wireless network to know this and as described earlier connecting does only take a between 3-5 seconds. The connection in station mode does not get re-established after a manual `active(False)` ...do something... `active(True)` on the station interface. This was my problem. This will be avoided as i it wears flash even more.
If i'd use static IP addresses (without the DHCP client) the time to connect will of course get shorter as well.

What makes my use-cases different from the ones mentioned by @peterhinch of @pfalcon is the fact that i do deactivate the WLAN interface right at startup after initializing the WLAN object, when no automatic re-connection has had a chance to have been happened.

**Comment by deshipu** [comment]
> I already provided constructive feedback - this patch attempts to modify the standard MicroPython API in a non-compatible way. So, the submitter of such patch should provide discussion of this problem in the pull request. And now it's actually your turn to provide constructive feedback on that matter.

I think you need to check the dictionary and see what the word "constructive" actually means. Your "feedback", would be constructive if it suggested a way to modify the pull request to avoid the problem it states. What you are saying now basically amounts to "keep trying". Moreover, you now have in this pull request an extensive discussion of why this is needed, together with at least three use cases from the real world. I think that if you want to achieve your stated goal of blocking this fix for at least a couple of years, then you need to find better way than just answering "no, it's not" to all arguments.

**Comment by dpgeorge** [comment]
How about this: 1) network API stays the same; 2) add a port-specific function `esp.persist_wlan(val)`, with val=True/False, which allows the user to turn on/off the feature of saving wifi settings to flash.  It can be enabled by default on boot-up.  Users who don't want the feature must call this new function ASAP to disable the persistence.  If disabled, wlan.connect() method will use the wifi_station_set_config_current() function.

**Comment by deshipu** [comment]
I think it's not that simple. When we disable that feature, we also don't want the board to read the saved configuration and bring up the configured interfaces. So putting it in your program is too late.

Perhaps we could write some special value to the flash when this is disabled (and the value is not in the flash yet, to avoid repeated writes), that would prevent both loading and saving?

**Comment by deshipu** [comment]
But the simplest possible solution that immediately fixes the problem is to just use the `_current` versions everywhere -- this way the functions are all compliant with the API spec and safe.

Then we can think about adding an additional function in the `esp` module for saving a particular set of configurations to the flash, as a completely separate thing, and for loading them from that flash. The users who want that feature can then add a call to loading from flash to their `boot.py`.

**Comment by kfricke** [comment]
Sounds like a really good solution to me. But regarding the details on the "C-side" of our code, I can not involve in any way.

Regarding the default settings... What API is the one we need to comply to, as demanded by @pfalcon? The MicroPython `network` module or the default ESP API/behavior?

In the case we only need to comply to "ours", I would like to ask for a by default not-persisting behavior. The real world scenarios i cam across (not only mine but all other setups seem to do the same) do always connect actively from the python code. So the persistence is unreasonable most of the time.

The WiPy does also not persist the WLAN credentials, or am I wrong?

**Comment by pfalcon** [comment]
> How about this: 1) network API stays the same; 2) add a port-specific function esp.persist_wlan(val), with val=True/False, which allows the user to turn on/off the feature of saving wifi settings to flash.

Well, there're multiple ways to achieve it, and the above is not the easiest or the most elegant (from interface/code side of things). The easiest would be: not change networking API by not changing the docs. Use generic name for optional (adhoc, undocumented) param, like "persistent=False".

That's all for code changes, but not all for API process. For example, if it's not in docs, how users will know about it? The author of the patch may say: "I'll post about it in my blog, and on the forum, and also watch the forum for related users questions and answer them. I'll also watch development, and if there will be support for another module which has such feature of either storing or not storing credentials persistently, I'll re-raise the question of adding it as an official API parameter".

Or it could be a different way - like "Let's update update network API's .connect() method to include support for arbitrary kwargs, just like .config() has." Then maybe list "persistent" as a possible kwarg, or maybe still not.


The point is - all this should come from a contributor who effectively tries to change Networking API, not maintainers should theorize what a contributor could say to back their proposal. 

How it's currently is "maintainers vs contributors". Maintainers get out of their way to try to stabilize platform and make it maintainable, well-documented, etc., and contributors get out of the way trying to snick in some inconsistency. There should be understanding that if your change may affect thousands of users, then this change should be well thought out and planned from various aspects.

**Comment by kfricke** [comment]
I am baffled if not sad... or hopefully confused by the painkiller i got prescribed today!

Do i understand this correctly? You do suggest the same as the original PR author did in his initial code, just with another argument name and refuse to add documentation for it. Why did you refuse it?

My concern is that we need a proper review of the code to avoid any operation which does wear flash. We do not need a half implemented, suspicious and undocumented feature. We need to safe modules from getting bricked!

**Comment by pfalcon** [comment]
> Do i understand this correctly?

No, you don't. Please re-read what I wrote again. Pay attention to the words "The point is - all this should come from a contributor who effectively tries to change Networking API, not maintainers should theorize what a contributor could say to back their proposal."

**Comment by kfricke** [comment]
Following the discussion on this pull request I have implemented a set of patches in another pull request #2564. Implementation is stable API-wise and does introduce a new method for the `esp` module to save the current configuration to flash.

**Comment by kfricke** [comment]
> Then we can think about adding an additional function in the esp module for saving a particular set of configurations to the flash, as a completely separate thing, and for loading them from that flash. The users who want that feature can then add a call to loading from flash to their boot.py.
This could be implemented but is useless, because the configuration is loaded from flash automatically on startup.

**Comment by dpgeorge** [comment]
Closing due to inactivity.  But would be good to investigate if this is useful for all ports and can be made to work generically, eg for esp32 and stm32 as well.

**Pull request closed without merging**
