### PR TITLE
py/vm.c: Add a fast path for LOAD_ATTR on instance types.

### PR DESCRIPTION
**Pull request by jimmo**
Suggested by @dpgeorge in #7680 but can be applied independently.

When the LOAD_ATTR opcode is executed, there are quite a few different cases that have to be handled, but the common case is accessing a member on an instance type. Typically, built-in types provide methods which is why this is common.

Fortunately, for this specific case, if the member is found in the member map, then there's no further processing.

This change does a relatively cheap check (type is instance) and then forwards directly to the member map lookup, falling back to the regular path if necessary.

It's +48 bytes on PYBV11 and gives an improvement on the tests that do lots of attribute access (e.g. `bm_float.py`).

PYBV11:

```
$ ./run-perfbench.py -s ~/cache-baseline ~/cache-attr-pybv11 
diff of scores (higher is better)
N=100 M=100              /home/jimmo/cache-baseline -> /home/jimmo/cache-attr-pybv11         diff      diff% (error%)
bm_chaos.py                  313.53 ->     333.64 :     +20.11 =  +6.414% (+/-0.01%)
bm_fannkuch.py                78.17 ->      78.17 :      +0.00 =  +0.000% (+/-0.01%)
bm_fft.py                   2551.16 ->    2548.07 :      -3.09 =  -0.121% (+/-0.00%)
bm_float.py                 4930.98 ->    5194.23 :    +263.25 =  +5.339% (+/-0.01%)
bm_hexiom.py                  35.62 ->      36.72 :      +1.10 =  +3.088% (+/-0.00%)
bm_nqueens.py               4219.69 ->    4219.20 :      -0.49 =  -0.012% (+/-0.00%)
bm_pidigits.py               647.28 ->     647.65 :      +0.37 =  +0.057% (+/-0.13%)
misc_aes.py                  384.48 ->     385.60 :      +1.12 =  +0.291% (+/-0.01%)
misc_mandel.py              3121.44 ->    3122.66 :      +1.22 =  +0.039% (+/-0.01%)
misc_pystone.py             1954.67 ->    1995.08 :     +40.41 =  +2.067% (+/-0.01%)
misc_raytrace.py             314.00 ->     335.36 :     +21.36 =  +6.803% (+/-0.01%)
```

PYBD_SF6:

```
$ ./run-perfbench.py -s ~/cache-baseline-sf6 ~/cache-attr-sf6 
diff of scores (higher is better)
N=100 M=100              /home/jimmo/cache-baseline-sf6 -> /home/jimmo/cache-attr-sf6         diff      diff% (error%)
bm_chaos.py                  382.55 ->     417.03 :     +34.48 =  +9.013% (+/-0.03%)
bm_fannkuch.py               101.40 ->     100.30 :      -1.10 =  -1.085% (+/-0.04%)
bm_fft.py                   1815.18 ->    1795.83 :     -19.35 =  -1.066% (+/-0.02%)
bm_float.py                 5939.99 ->    6550.83 :    +610.84 = +10.284% (+/-0.06%)
bm_hexiom.py                  49.78 ->      52.22 :      +2.44 =  +4.902% (+/-0.03%)
bm_nqueens.py               5706.74 ->    5653.05 :     -53.69 =  -0.941% (+/-0.02%)
bm_pidigits.py               959.77 ->     961.11 :      +1.34 =  +0.140% (+/-0.03%)
misc_aes.py                  530.32 ->     528.30 :      -2.02 =  -0.381% (+/-0.03%)
misc_mandel.py              4037.38 ->    4002.67 :     -34.71 =  -0.860% (+/-0.18%)
misc_pystone.py             2485.09 ->    2569.43 :     +84.34 =  +3.394% (+/-0.05%)
misc_raytrace.py             401.04 ->     456.52 :     +55.48 = +13.834% (+/-0.03%)
```

It's interesting that bm_fannkuch.py takes a hit because it doesn't use LOAD_ATTR anywhere in the main loop. bm_fft.py only uses `cmath.pi`. Perhaps increasing the code size of the VM has some effect and adding this to the top of mp_load_attr would be better (and would benefit native code too).

### CODE REVIEW

**Comment by jimmo** [comment]
> Perhaps increasing the code size of the VM has some effect and adding this to the top of mp_load_attr would be better (and would benefit native code too).

Nope, this seems to be consistently about 1% worse.

**Comment by dpgeorge** [comment]
Can you please rebase on latest master?  It may fix the stm32 build.

**Comment by jimmo** [comment]
> Can you please rebase on latest master? It may fix the stm32 build.

Done

**Comment by dpgeorge** [comment]
Merged in 7b89ad8dbf432ab51eea6d138e179bf51394c786

**Pull request closed without merging**
