### PR TITLE
tools: Add build_ports.sh and diff_sizes.py scripts.

### PR DESCRIPTION
**Pull request by dpgeorge**
These are the scripts I use to build all ports and compare sizes across different builds.

Eg:
```
$ ./tools/build_ports.sh all | tee size0
<wait>
$ git switch new-feature-branch
$ ./tools/build_ports.sh all | tee size1
<wait>
$ ./tools/diff_sizes.py size0 size1
```

TODO:
- add more comments / docs how to use the scripts
- maybe combine them into one script

### CODE REVIEW

**Comment by Jongy** [comment]
> maybe combine them into one script

I think it's okay to leave them independent. It's nice when you have multiple different unrelated changesets and you only need to run `build_ports.sh | tee sizes_before` once, then you can reuse the `sizes_before` file for all future diffs that are based on that single commit. If you'd combine them, it'll probably have to run the build twice each invocation of the combined.

**Comment by dpgeorge** [comment]
> I think it's okay to leave them independent.

Actually I meant to combine `build_ports.sh` and `diff_sizes.py` into one script where you select the mode that it runs in via a command line option, eg:
```bash
$ ./tools/build_ports.py all | tee size0
$ ./tools/build_ports.py all | tee size1
$ ./tools/build_ports.py --diff size0 size1
```

**Comment by Jongy** [comment]
A few proposals for enhancements (I don't mind to add them myself after you merge this):

1. The `tee` part should be done by the script automatically.
2. Git tag & working tree state (clean/dirty) should be included in the output.
3. If you `diff_sizes.py` between `build_ports.py` of different ports, you get funny `KeyError`, which should be made more clear IMO

**Review by Jongy — COMMENTED** [review]
A few proposals for enhancements (I don't mind to add them myself after you merge this):

1. The tee part should be done by the script automatically.
2. Git tag & working tree state (clean/dirty) should be included in the output.
3. If you diff_sizes.py between build_ports.py of different ports, you get funny KeyError, which should be made more clear IMO

**Comment by Jongy** [comment]
Time to merge this?

**Comment by dpgeorge** [comment]
I totally redid this, merging all functionality into one file, now called `tools/manage.py` (not sure about the name but couldn't think of anything better).

New usage:
```
$ ./tools/manage.py build | tee size0
<wait>
$ git switch new-feature-branch
$ ./tools/manage.py build | tee size1
<wait>
$ ./tools/manage.py diff size0 size1
```
Other commands:
```
$ ./tools/manage.py sizes # print all firmware sizes
$ ./tools/manage.py clean # clean all ports
```

**Pull request merged**
