### PR TITLE
Make unix port use mp-readline library

### PR DESCRIPTION
**Pull request by dpgeorge**
With this patch unix uses our own mp-readline library.  So now it has tab completion, yay!  Also has history read/write capabilities.

Hopefully addresses issue #1253.

### CODE REVIEW

**Comment by blmorris** [comment]
Nice! Compiles and runs on OSX (though I still need to manually comment out `#include <stdio.h>` from `unix/mpconfigport.h` because of #1252)
Tab autocomplete working as expected.

**Comment by stinos** [comment]
This breaks builds for both mingw/msvc windows ports so maybe needs some #ifdefs to unbreak those until they are fixed (by providing unix_mphal.c or making it build). I thought at least mingw would have termios.h but appears it doesn't. Maybe @msiemens has an idea about the best way to fix this? For msvc I can probably come up with a winapi based solution.

**Comment by pfalcon** [comment]
We certainly want any readline support to be configurable, as @stinos suggests.

**Comment by pfalcon** [comment]
Otherwise looks good for initial version, I won't even ask why there're fgetc instead of fgets ;-).

**Comment by dpgeorge** [comment]
Superseded by #1286.

**Pull request closed without merging**
