### PR TITLE
unix: enable `random` module seed initialisation on import

### PR DESCRIPTION
**Pull request by dpgeorge**
This enables random seed initialisation on import of the `random` module, on unix dev and coverage builds.

### CODE REVIEW

**Comment by dpgeorge** [comment]
@stinos I'm not sure how to get this working for windows (mingw and msvc).

Does `uos.urandom()` even work on windows in current master?  It uses either `getrandom()` or `/dev/urandom`, neither of which exist on windows AFAIK.

**Comment by stinos** [comment]
Currently it tries to open `/dev/urandom` resulting in `OSError: [Errno 2] ENOENT`. I'd implement `mp_hal_get_random` for the windows port using https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-rtlgenrandom. It's deprecated, alternative looks more complicated: https://docs.microsoft.com/en-us/windows/win32/api/bcrypt/nf-bcrypt-bcryptgenrandom and has no Windows XP support (although I'm not sure a) we have to care about that and b) whether that even works now). You gave a preference?

**Comment by dpgeorge** [comment]
This was rebased on master which includes #8734.

@stinos does it look OK to you, the refactoring to `mp_hal_get_random()`?

**Comment by dpgeorge** [comment]
I tested this with an msvc build, and it works.

**Comment by stinos** [comment]
Yes it's ok. Just one question: why is the seeding needed exactly here?

**Comment by dpgeorge** [comment]
The seeding is just something enabled on unix (there are 3 commits here, only one is related to windows, which is just a factoring of the code).

For the `random` module, its PRNG is supposed to be seeded by a true random number when it is imported, so that your program always starts with a new random seed.  That feature is optional in uPy, and enabled in one of the commits here mainly for coverage purposes.

**Pull request merged**
