### PR TITLE
esp8266: Export station status() constants

### PR DESCRIPTION
**Pull request by atx**

### CODE REVIEW

**Comment by dpgeorge** [comment]
I guess these are needed, but considering that esp has little code space, can we shorten them?  Eg no STATION_ prefix?  Since they are a status return value, maybe they should start with STATUS_?  Maybe shorten it to STAT_?

**Comment by pfalcon** [comment]
Well, @dpgeorge sounded concerns I had. IIRC, this stuff would go to IRAM due to Xtensa peculiar architecture, and (any) RAM is precious for other things.

I can propose 3 choices:

1. Have STATUS_ or STAT_ prefix (because STATION_ is just confusing; the fact that it's used in SDK is poor argument, they have typos in API names).
2. Drop prefix altogether.
3. Not include this in C code at all - quite not every app will use them, so it can go into an importable Python module at all.

If choice 3 is not selected, I suggest wrapping them in #ifdef, because easily imaginable step in esp8266 port is hunting for something which can be optimized away to get more RAM.

**Comment by atalax** [comment]
> If choice 3 is not selected, I suggest wrapping them in #ifdef, because easily imaginable step in esp8266 port is hunting for something which can be optimized away to get more RAM.

Added `MODESP_INCLUDE_CONSTANTS` to `mpconfigport.h`. The constants can be moved to a file later, after the flash file system is implemented.

**Comment by pfalcon** [comment]
Merged in 7e7039b53ccc3c02815823bd95fa50da2955b5c1 . Putting stuff in mpconfigport.h requires sticking to naming conventions, and in this case it's ok for that define to stay module-local define, so I just moved #define to module itself for now.

**Pull request closed without merging**
