### PR TITLE
move generic CMSIS files to lib/cmsis

### PR DESCRIPTION
**Pull request by blazewicz**
As per @dpgeorge's request from #2408.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Is this the latest version of CMSIS?  If we are going to upgrade, why not do it in one go: upgrade and move.

**Comment by dpgeorge** [comment]
> I thought you may want to separate those two changes too have cleaner git log.

Yes, thanks, having the change log is better than not having it.

One last minor point: is there a reason to put the common cmsis files in lib/cmsis/inc instead of lib/cmsis?

Also, I removed the stm32f2xx cmsis files in 53bfcc9e848c43e58694c7cb7a2356b31fc67445, so please rebase against that.

**Comment by blazewicz** [comment]
> One last minor point: is there a reason to put the common cmsis files in lib/cmsis/inc instead of lib/cmsis?

I thought about users that may want to use other parts of CMSIS - like the [CMSIS-DSP library](http://www.keil.com/pack/doc/CMSIS/DSP/html/index.html) or [CMSIS-RTX RTOS](http://www.keil.com/pack/doc/CMSIS/RTX/html/index.html), for them the best place to put its source code would be lib/cmis/{dsp|rtx}.

Especially DSP library is interesting with its target optimized math/control/statistics functions.

If you would ever consider adding another part of CMSIS I think its better to add those extra 4 characters to the path now than to move all files when there will be need to.

But its your call, I'll move them up if you wish.

I've rebase the changes and also added a commit removing CMSIS-DSP headers which are currently unused.

**Comment by dpgeorge** [comment]
That's great, thank you.  I left it as-is and merged, see b04d4a5b1360b73d905cd018ca0182b0d2ff4454 for the final commit.

**Pull request closed without merging**
