### PR TITLE
stmhal: whitespace adapt stm32f4xx_hal_conf.h accross all boards, so …

### PR DESCRIPTION
**Pull request by prusnak**
…it is easier to spot differences

Basically, it is minor change in EOL usage (dos vs unix), and fixing comment style.

### CODE REVIEW

**Comment by dpgeorge** [comment]
That's a lot of changes.  There's apparently a way to use diff so that it ignores whitespace differences.  Maybe that will help you?

**Comment by prusnak** [comment]
I tried to make the same line endings of the files, if you prefer I don't do this I will submit just a non-whitespace changes.

**Comment by prusnak** [comment]
Commit c1c787f contains just changes in comments, no whitespace change.

**Comment by prusnak** [comment]
Obsoleted by https://github.com/micropython/micropython/pull/1860

**Pull request closed without merging**
