### PR TITLE
mimxrt: Add support for the Seed ARCH MIX board.

### PR DESCRIPTION
**Pull request by robert-hh**
The ARCH MIX board is based on the i.MX RT1052 MCU. Beside the MCU has 8MByte of qspi flash and 32MByte SDRAM. 34 GPIO pins are available at edge connectors, as well as J-Tag pins.
There is also a 50 pin display connector. 
Since the Ethernet connections are accessible at the board, this PR includes  the driver for using a LAN8720 PHY device, which are commonly available.
The only drawback is, that firmware loading is a little bit tedious, requiring either a J-Link adapter or using the NXP serial download method.

### CODE REVIEW

**Comment by dpgeorge** [comment]
How about naming the board `SEEED_ARCH_MIX`?  We need to make sure all board names are unique across all ports (because on the downloads page they are all presented together) and so they should be reasonably full names.

**Comment by robert-hh** [comment]
No problem. I'll change it.

**Comment by robert-hh** [comment]
Changed and rebased. I did not squash the two commits yet. Can do that later.

**Comment by robert-hh** [comment]
The BOARD is renamed and the PR is rebased. I did not squash it yet. I can do that if you want,

**Review by dpgeorge — APPROVED** [review]

**Comment by robert-hh** [comment]
Rebased. But there might be a conflict with #7975 with respect to the file boards/deploy.md. So it's better to merge one of them first. Then I can solve a potential conflict.

**Comment by dpgeorge** [comment]
Squashed and merged in d72d699dad6c75966397873d108bcc2f36222144

**Comment by robert-hh** [comment]
There may be a problem with the automatic build for the Seeed Arch mix board. It does not show up, maybe cause by a wrong link to the picture. Can I test before uploading if a configuration works with the web page?
I noticed also that there is some confusion with the other mimxrt builds. For Teensy, there are no .hex files in the daily build, which are required. For the MIMXRT boards there are .hex files, which cannot be used.

**Comment by dpgeorge** [comment]
@robert-hh it looks like the Seeed Arch Mix page is working well, the firmware is there.  The only issue is that the image is missing.  Do you have a `main1.jpg` that can be submitted to https://github.com/micropython/micropython-media?

**Comment by robert-hh** [comment]
I noticed that the builds appear now well. It is just the link that's wrong. I can take the picture from the Seed web page, or I can make a picture myself, free of any license issues. Shall I make then a PR to that repository?

**Comment by dpgeorge** [comment]
> Shall I make then a PR to that repository?

Yes please.  A picture from the Seeed page would be OK.

**Pull request closed without merging**
