### PR TITLE
WIP: ESP32: Fix tcpip adapter in esp-idf v5.0.

### PR DESCRIPTION
**Pull request by IhorNehrutsa**
I try to build MicroPython with esp-idf v5.0
```
cd ~/esp-idf
git checkout release/v5.0
git submodule update --init --recursive
./install.sh
. ./export.sh
```
Error log:
```
-- Building ESP-IDF components for target esp32
CMake Error at /home/pc/esp-idf/tools/cmake/build.cmake:207 (message):
  Failed to resolve component 'esp32'.
Call Stack (most recent call first):
  /home/pc/esp-idf/tools/cmake/build.cmake:243 (__build_resolve_and_add_req)
  /home/pc/esp-idf/tools/cmake/build.cmake:538 (__build_expand_requirements)
  /home/pc/esp-idf/tools/cmake/project.cmake:434 (idf_build_process)
  CMakeLists.txt:58 (project)


-- Configuring incomplete, errors occurred!
See also "/home/pc/micropython/ports/esp32/build-GENERIC/CMakeFiles/CMakeOutput.log".
FAILED: build.ninja 
/usr/bin/cmake -S/home/pc/micropython/ports/esp32 -B/home/pc/micropython/ports/esp32/build-GENERIC
ninja: error: rebuilding 'build.ninja': subcommand failed
ninja failed with exit code 1
make: *** [Makefile:34: all] Error 2
```

Can anyone resolve cmake eroor,?

### CODE REVIEW

**Comment by dpgeorge** [comment]
> Can anyone resolve cmake eroor,?

Maybe remove this line in main/CMakeLists.txt: `list(APPEND IDF_COMPONENTS esp32)`

**Comment by IhorNehrutsa** [comment]
```
cd ~/esp-idf/examples/get-started/hello_world/
idf.py build
```
Output is ok:
```
...
Project build complete. To flash, run this command:
...
```

**Comment by IhorNehrutsa** [comment]
> Maybe remove this line in main/CMakeLists.txt: `list(APPEND IDF_COMPONENTS esp32)`
Yes.
Thanks @dpgeorge

**Comment by dpgeorge** [comment]
I'll close this in favour of #11528, which has WiFi working on IDF v5.0.1.

**Pull request closed without merging**
