### PR TITLE
gpio module drafted

### PR DESCRIPTION
**Pull request by dvv**
A first stab to TODO. Please, consider applying.

### CODE REVIEW

**Comment by pfalcon** [comment]
Thanks for the patch, but MicroPython API to work with GPIO is "pyb" module, which offers Pin class with well defined interface: http://docs.micropython.org/en/latest/library/pyb.Pin.html

**Comment by dvv** [comment]
I see. Let it then stay here for reference.
(There's so far imo little sense in obeying `pyb.Pin` while no networking for esp8266 (the killer feature) done)

**Comment by pfalcon** [comment]
But wouldn't you like to refactor your patch to follow pyb.Pin interface? Developing a complete port for esp8266 will require contribution from interested parties. I have initial function of networking implemented - AP scan, but it requires some discussion too before merging (e.g. https://github.com/micropython/micropython/issues/876#issuecomment-70385535)

**Comment by dvv** [comment]
Not ATM. Putting to TODO

**Pull request closed without merging**
