### PR TITLE
esp32/modnetwork: interface to the WIFI power save functions of ESP-IDF

### PR DESCRIPTION
**Pull request by karfas**
New function WLAN.wifi_ps() with zero or one parameter.
New constants in network:
  WIFI_PS_NONE
  WIFI_PS_MIN_MODEM
  WIFI_PS_MAX_MODEM

When called without parameter, the function returns the current WIFI power save mode.
When called with one parameter, the power save mode is set to the value of the parameter and the previous power save mode is returned.

### CODE REVIEW

**Comment by tve** [comment]
FYI: #5473

**Comment by karfas** [comment]
@tve: yes, I had seen #5473 before.
However, I think it's more flexible to have a dedicated function instead of a parameter to connect().
This allows  to switch the WIFI speed depending upon current requirements (e.g. switch to PS_NONE when I have a lot of data to transfer).

Regards,
Thomas

**Comment by EternityForest** [comment]
I'm using code adapted from here(In addition to some other stuff) and getting down to 7mA (With spikes when it wakes up) on a TTGo T-Display when using auto light sleep(Most of the current is probably from the USB chip).

It really is night and day.  Is this still on the roadmap?

Seems like a lot of stuff has changed, but it integrated with a fork of master here just fine:

https://github.com/EternityForest/micropython/tree/dev-branch

**Comment by karfas** [comment]
Closing this in favor of #8993, as the new PR 
- works for both ESP32 and ESP8266 ports 
- has a nicer interface (`wlan.config(pm=X)`)

**Pull request closed without merging**
