### PR TITLE
tools/manifestfile.py: Add support for external libraries.

### PR DESCRIPTION
**Pull request by jimmo**
This adds a `add_library(name, path)` method for use in manifest.py that allows registering an external path (e.g. to another repo) by name.

This name can then be passed to `require("package", library="name")` to reference packages in that repo/library rather than micropython-lib.

Within the external library, `require()` continues to work as normal (referencing micropython-lib) by default, but they can also specify the library name to require another package from that repo/library.

---

The idea here is that a board author can now do the following:
- Build their own libraries in a separate repo (using `manifest.py` with `metadata()`, just like micropython-lib)
- Add that repo as a submodule to `$(TOP)/lib`
- Add that repo to the board's `GIT_SUBMODULES`
- Add `MICROPY_MANIFEST_FOO_LIB_DIR = $(TOP)/lib/foo` to `mpconfigboard.mk`
- Add `add_library("foo", "$(FOO_LIB_DIR)")` to `manifest.py`
- Use `require("my-driver", library="foo")` to `manifest.py`

This does not provide a way to publish third-party packages to `mip`, but we're working on that separately.

Terminology note: a library (or repo) is a collection of packages (which may be either packages or modules). https://github.com/micropython/micropython-lib/#notes-on-terminology  (This PR fixes up some incorrect usage of these terms in manifestfile.py)

cc @iabdalkader

### CODE REVIEW

**Comment by iabdalkader** [comment]
@jimmo I tested this locally and it works exactly as expected! Thanks Jim for this excellent work.

**Comment by robert-hh** [comment]
@jimmo  b.t.w.: Did you implement access to user symbols defined with MICROPY_MANIFEST_MY_VARIABLE in manifest.py scripts?

**Comment by dpgeorge** [comment]
> Did you implement access to user symbols defined with MICROPY_MANIFEST_MY_VARIABLE in manifest.py scripts?

Yes that was done in 992cd6455522da04bd209e7f7b0915ba7bbfc2f0

**Comment by robert-hh** [comment]
@dpgeorge I know this PR. But Jimmo talked about general access to the variables in the manifest.py, not only in the built-in functions like include and require. That would allow a flow of control in the code depending on these variables. Could be done by e.g. having the VARS dictionary in scope as global symbol.

**Comment by dpgeorge** [comment]
I have reviewed this and it looks great, nice and simple but adds good functionality.

**Pull request merged**
