### PR TITLE
Add pyb.wfe() function. Execute wfe instead of wfi in machine.idle.

### PR DESCRIPTION
**Pull request by HenrikSolver**
The wfi instruction puts the CPU into sleep mode unconditionally which means that it will go to sleep even if there is a pending interrupt. the result is that in some cases, pending interrupts will not be seviced until some other event wakes the CPU. Wfe on the other hand, does not put the cpu to sleep if there is a pending interrupt. So in most cases it is safer to call wfe instead of wfi.

It can be verified with the following code. It is simply a loop that wait for a timer interrupt to happen. Timer 2 is only used to measure the number of 10s of us that elapses between the interrupt and the execution of the main contents of the loop. Running this will eventually result in a maximum delay of 1ms. I guess that the situation is saved by the systick. Replacing pyb.wfi() with pyb.wfe() results in a maximum delay of 40 us even after an longer period of execution.

```python
import pyb
import gc
from pyb import Pin

flag = False
t1 = 0
t2 = 0

pin = Pin('X1', Pin.OUT_PP)
#10us
tim2 = pyb.Timer(2, prescaler=840, period=0x3FFFFFFF)
tim4 = pyb.Timer(4, freq=12)

def cb(t):
    global flag
    global t1
    t1 = tim2.counter()
    flag = True    

tim4.callback(cb)
tmax = 0
print('start')
while True:
    if not flag:
        pin.low()
        pyb.wfi()
        #pass
        pin.high()
    else:    
        t2 = tim2.counter()
        flag = False
        #t2 = tim2.counter()
        diff = t2-t1
        if diff > tmax:
            tmax = diff
        print(diff, tmax)
        gc.collect()

```

### CODE REVIEW

**Comment by dhylands** [comment]
I know on the A9 series, the sequence used for WFI is to disable interrupts, execute WFI and then re-enable interrupts.

I haven't played with this on the M4, but its probably worth trying.

**Comment by HenrikSolver** [comment]
To me that seems to be a recipe for "sleep forever", but the cortex-A is pretty different from a M on this level due to pipelines and such things. I studied quite a bit in forums and documentation to find out the details on this but the information I found is a bit vague. The most concrete I found is in the book The definitive guide to ARM Cortex-M3 and Cortex-M4 processors by  Joseph Yiu, which has a section about WFI and WFE. It ends in "If we are not certainly about the timing, then we need to make the sleep operation conditional by using WFE."

**Comment by dhylands** [comment]
I initially thought the same, but the reason it works is that when you disable interrupts, you're really just applying a mask. The WFI works off the circuitry before the mask.

**Comment by dpgeorge** [comment]
Thanks for the PR.  But changing `machine.idle()` to use WFE is too disruptive to how the system works at a low level, in particular with power saving features.  Eventually I want to replace WFI with WFE everywhere in stm32 and use events rather than interrupts to do power saving (and maybe even make it tickless and put systick and lowest priority...).

So I'll close this PR.

**Pull request closed without merging**
