### PR TITLE
stm32/dma,spi: Fix invalid SPI reads due to D-Cache coherency.

### LINKED ISSUE #13471: STM32: SPI.read(n) fails if n > 1 (regression)
This arose driving an EEPROM using hard SPI on Pyboard D hardware (soft SPI works OK). Baudrate was 5MHz, other args default. Hardware is a Pyboard D on a DIP28 adaptor on a small PCB with a pair of EEPROM chips on the bus. Traces are very short. This setup has worked in the past when developing [this driver](https://github.com/peterhinch/micropython_eeprom/blob/master/eeprom/spi/SPI.md), and in fact still works with a Pyboard D SF2W running
```
MicroPython v1.18-355-g9ab66b50c-dirty on 2022-04-29; PYBD-SF2W with STM32F722IEK
```
With a Pyboard D SF6W running
```
MicroPython v1.22.1 on 2024-01-05; PYBD-SF6W with STM32F767IIK
```
it behaves as follows. A single byte read from an arbitrary address returns the correct contents, but a multi-byte read returns a bytes object of the correct length but containing zeros. To investigate the fault reading was done with a simple `spi.read(n)`. The hardware was examined with an LA: the single byte and multi-byte reads were identical aside from the extra byte and conformed with the device spec. The MISO result for a 2-byte read was as follows:
Image

The LA shows correct data being transmitted by the EEPROM but `spi.read(2)` returned `b'\x00\x00'`.

### PR DESCRIPTION
**Pull request by projectgus**
Adds a new DMA API to protect against cache coherency issues on chips with D-Cache, when working with arbitrary buffers (i.e. supplied by Python code).

The API is added to SPI, fixes #13471. Future work may be needed to call this API from other STM32 drivers that use DMA with arbitrary buffers.

Explanation:

1) It's necessary to invalidate D-Cache after a DMA RX operation completes, in case the CPU read (or speculatively accessed) memory in the DMA region during the operation. This seems to have been the root cause of #13471 (and only when src==dest, for that case.)

2) More generally, it is also necessary to temporarily mark the first and last cache lines of a DMA RX operation as "uncached", in case the DMA buffer shares this cache line with unrelated data. The CPU could otherwise write the other data at any time during the DMA operation (for example from an interrupt handler), creating a dirty cache line that's inconsistent with the DMA result.

## Test code

Regression test included in the PR, based on the work done by @peterhinch and @robert-hh in the linked issue.

### CODE REVIEW

**Comment by projectgus** [comment]
@dpgeorge @jimmo Is there any reasonable place to include those tests in the code base? I saw there is a `tests/ports/stm32/spi.py` but it doesn't rely on any hardware configuration. These tests require the MISO pin to be connected to GND.

**Comment by dpgeorge** [comment]
> Is there any reasonable place to include those tests in the code base? I saw there is a `tests/ports/stm32/spi.py` but it doesn't rely on any hardware configuration. These tests require the MISO pin to be connected to GND.

We should definitely include those tests in the repo, and `tests/ports/stm32/` is the best location for them.

I suggest making these tests separate file(s) to the existing tests, adding a comment at the top of the file of the require hardware connections, and then possibly trying to auto-detect those hardware connections (eg toggle IO and see if it changes) and SKIP'ing if they are not there.

Alternatives:
- don't do any auto-detection of the hardware connection and let the test fail if it's not set up properly, then the user is made aware that they must make hardware connections
- make a new `tests/ports/stm32_hardware` directory for these kinds of tests, so they can be easily included/excluded from a test run

Note there are already some tests in `stm32` that require specific hardware, like a PYBv1 with accelerometer.  Also the `tests/ports/cc3200` directory has similar hardware-dependent tests.

**Comment by projectgus** [comment]
Have added regression test in `ports/stm32_hardware`. Would have preferred auto-skip idea, but couldn't think of a good way to programmatically find the GPIO for SPI2 MOSI to toggle it for a given SoC.

**Comment by dpgeorge** [comment]
I tested a PYBD_SF2 with the test in this PR, both before and after the DMA/SPI fix in this PR.  The test fails without the fix and passes with the fix.  Very good!

**Pull request merged**
