### PR TITLE
docs/library/btree.rst: Add note about `btree` availability.

### PR DESCRIPTION
**Pull request by hlovatt**

### CODE REVIEW

**Comment by stinos** [comment]
Friendly reminder: first commit message line should be a sentence in the imperative mood. It is a description of what the commit will do when applied, i.e. read it like *"this commit, when applied, will"* .... *"Add a note about btree availability."* Makes a lot of sense if you think about it and how git works.

**Comment by hlovatt** [comment]
@stinos. Thanks, correct as suggested.

**Comment by dlech** [comment]
It would probably be worth noting that the advertising clause has since been retracted. https://www.freebsd.org/copyright/license.html

Also, as suggested in https://github.com/micropython/micropython/issues/6186#issuecomment-649546619, we could alternately update the license accordingly and include btree by default.

**Comment by hlovatt** [comment]
Suggest accept pull request as is. Then sort out if worth including btree in the longer term. It is easy enough to change the doc once long term decision made. 

Btree presumably isn’t heavily used since the forum isn’t full of where is btree questions. I could only find one such thread. 

-- Howard.

**Comment by stinos** [comment]
> @stinos. Thanks, correct as suggested.

@hlovatt I think you only changed the title of the PR, the commit message is still the same.

**Pull request closed without merging**
