### PR TITLE
py: rename array module to uarray

### PR DESCRIPTION
**Pull request by dpgeorge**
And provide backwards compatible weak link so that `import array` still works.

See #4370

### CODE REVIEW

**Comment by pfalcon** [comment]
Thanks. But I'm not sure if it's worth to enable weak links in unix port just for one module. How about just to re-add "array" alias name via MICROPY_PORT_BUILTIN_MODULES until the next release?

**Comment by dpgeorge** [comment]
> How about just to re-add "array" alias name via MICROPY_PORT_BUILTIN_MODULES until the next release?

I don't think that will work, in the sense that it will always be found first and so an `array.py` file could not override it.

> But I'm not sure if it's worth to enable weak links in unix port just for one module.

Well, I wanted to enable it anyway, and add many links there, so the unix binary can emulate CPython more closely without needing a set of libraries on the filesystem.

**Comment by pfalcon** [comment]
> Well, I wanted to enable it anyway, and add many links there, so the unix binary can emulate CPython more closely without needing a set of libraries on the filesystem.

How about all the concerns that it adds more confusion than benefits?

**Comment by dhylands** [comment]
I find the fact that it doesn't behave like the bare metal ports to be more confusing than the way it behaves now.

**Comment by pfalcon** [comment]
So, as usual, confusion comes in layers. Baremetal ports behaves confusing by offering fake "CPython compatibility". Then to some people the fact that unix port doesn't fake it is also confusing, and it goes in rounds and in circles.

The well-known solution is to cut solution where it begins. The worst solution is to make confusion all-encompassing and unescapable.

**Comment by dpgeorge** [comment]
> Baremetal ports behaves confusing by offering fake "CPython compatibility".

MicroPython is intended to provide a faithful as possible implementation of Python, with modules included where possible.

> The well-known solution is to cut solution where it begins.

So is the proposal to remove weak links altogether and make `import array` (and all the others like `import time`) stop working?

**Comment by pfalcon** [comment]
> MicroPython is intended to provide a faithful as possible implementation of Python, with modules included where possible.

As you understand, in this case, "as faithful as possible" would be "allowing to implement as complete as possible API of CPython in the obvious way, by clearly separating what's MicroPython API and not hogging namespaces which don't belong to it".

 > So is the proposal to remove weak links altogether and make import array (and all the others like import time) stop working?

As you very well understand either, I hardly could realistic propose *that*, even though I definitely try to maintain a view opposing weak links (so the truth was somewhere in the middle). My point would be to try to define well what weak links are. In my view, it is a product-specific feature, offered by vendors of specific products as a feature to their users to smooth the curve of learning "native MicroPython". On the level of the language itself, it's an ugly hack, which despite its good intentions, leads to the opposite effect - people don't learn how to use native MicroPython well, and instead remain in permanent confusion regarding what MicroPython vs CPython are.


Anyway, beyond paradigmatic aspect of it, I have a specific proposal: how about dropping all those growing data structures to maintain, and add following code (under the config option of course):

* If the import is absolute (should make sure to not  apply to package-local imports), if import of "foo" fails, then try to see if there's a builtin module "ufoo", and if there's, import it instead.

Done like that, it should be clear to anyone that it's nothing but a special-purpose hack. Should save some bytes, too.

**Comment by pfalcon** [comment]
Ok, so can we finish with this in obvious least effort/least scope creep way: a) proceed with the rename; b) for ports which already have weak links enabled, add a weak link; c) for ports which don't use weak links, just have 2 entries "array" and "uarray" pointing to the same module.

This will allow to normalize docs, and that's the main driver for the, change, and seeing how to allow to actually override "array" consistently can be dealt with as a next task.

**Comment by dpgeorge** [comment]
`array` was renamed to `uarray` in 21a60935a5d5885817881b4f690fdfd3ef009100, docs updated in a2eea57b1d5456696598703aa4ffdbc7e9fb52ea

A weak link is provided from `array` to `uarray` so that `import array` will still work.

**Pull request closed without merging**
