### PR TITLE
stmhal: Add pyb.irq_stats() to get statistics about IRQ calls.

### PR DESCRIPTION
**Pull request by dpgeorge**
Adds a lot of code, makes IRQs a bit less efficient, but is very useful for debugging.  Disabled by default, enable by setting IRQ_ENABLE_STATS in irq.h.  Usage: pyb.irq_stats() returns a memory view that can be read and written, eg:

```
list(pyb.irq_stats())
pyb.irq_stats()[0]
pyb.irq_stats()[0] = 0
```

### CODE REVIEW

**Comment by dpgeorge** [comment]
@dhylands I think I pointed you to an earlier branch of this.  I've found this to be really useful.

**Comment by dhylands** [comment]
@dpgeorge Looks pretty clean.

There's also https://github.com/micropython/micropython/blob/master/stmhal/sdcard.c#L198

If we're going to add some macros to every IRQ Handler, do you think it makes sense to add a ENTER/EXIT macro?

The counter stats could just modify the ENTER macro and the EXIT would do nothing. But having an EXIT macro would allow for things like measuring how long you were in an IRQ, and also allow for things like toggling GPIOs.

I haven't really seen memoryview before - will need to investigate further.

Totally off-topic: Something like a memoryview on the heap bitmaps would also be nice, so that python code could print the equivalent of the heap dump that you get with pyb.info(1).

**Comment by pfalcon** [comment]
+1

**Comment by dpgeorge** [comment]
@dhylands yes, IRQ_ENTER/IRQ_EXIT are much more general than IRQ_COUNT.  I'm happy to change this PR to use that scheme.

Thanks for the sd card link, I missed that one!

> Totally off-topic: Something like a memoryview on the heap bitmaps would also be nice, so that python code could print the equivalent of the heap dump that you get with pyb.info(1).

You can already do it (sort of): `ram = uctypes.bytearray_at(0x20000000, 0x20000)`, then you just need to find the address of the heap :)

**Comment by dpgeorge** [comment]
Ok, updated to use IRQ_ENTER/IRQ_EXIT.

**Comment by dhylands** [comment]
> You can already do it (sort of): ram = uctypes.bytearray_at(0x20000000, 0x20000), then you just need to find the address of the heap :)

So then maybe its as simple as exposing some constants.
address of ATB, address of FTB (if it exists), address of POOL, number of blocks, and block size.

I'm guessing that the gc module would be the place to put these?

**Comment by dpgeorge** [comment]
> So then maybe its as simple as exposing some constants.
> address of ATB, address of FTB (if it exists), address of POOL, number of blocks, and block size.
> 
> I'm guessing that the gc module would be the place to put these?

We should discuss this in a separate ticket.  It would be a low priority issue.

**Comment by dpgeorge** [comment]
Merged in 401af50dc081faa421e7caef18fde2beb15632e4.

**Pull request closed without merging**
