### PR TITLE
unix: Implement 'tell()' method for file class

### PR DESCRIPTION
**Pull request by blmorris**
'tell' returns the current position of the read/write pointer on an open file. Already implemented in stmhal.

While trying to use MicroPython to analyze .wav (audio) files using the [wave.py](http://micropython.org/resources/examples/wave.py) and [chunk.py](http://micropython.org/resources/examples/chunk.py) modules from the [AMP audio skin tutorial](http://docs.micropython.org/en/latest/pyboard/tutorial/amp_skin.html) I ran into a difference in behavior between stmhal and unix. On stmhal I could use `setpos()` to read data from anywhere in the file, but this wouldn't work on unix. It turned out that the chunk module uses the presence of the `tell` method to determine whether a file object is 'seekable'. I took the liberty to implement the tell method to fix the issue; please let me know if there is anything that needs to be fixed.

### CODE REVIEW

**Comment by pfalcon** [comment]
> It turned out that the chunk module uses the presence of the tell method to determine whether a file object is 'seekable'.

Well, then the focused solution is to change that module to to use "seek" for seekability check, especially that it doesn't use .tell() in any other way.

As for this patch, it apparently would need to be implemented in terms of underlying seek ioctl. This will also take care of 64-bit cleanness, once it's fixed for seek(). But I'd prefer it to be #ifdef'ed, and off by default then, until unavoidable need for it arises.

**Comment by blmorris** [comment]
> Well, then the focused solution is to change that module to to use "seek" for seekability check, especially that it doesn't use .tell() in any other way.

That is a reasonable suggestion; the reason I implemented "tell" instead is that wave and chunk are part of the standard python library, with a few changes to run on MicroPython - primarily using `struct.unpack` instead of `struct.unpack_from`, and I didn't want to add my own changes if it could be avoided.

> As for this patch, it apparently would need to be implemented in terms of underlying seek ioctl. 

That makes sense; I didn't immediately see how to make that work.
Is it possible that this patch actually caused the Travis failure in `qemu_arm`? I didn't imagine it could affect anything there.

**Comment by blmorris** [comment]
@pfalcon - As I understand it, in `unix/file.c` the functions `readall`, `readinto`, `readline`, `readlines`, and `seek` are implemented in terms of the ioctl function, but I don't see how it works; the functions are clearly present, but I don't see where or how they actually get implemented.
I imagine there is a basic programming idiom that is familiar to experienced C programmers here, but I'm not seeing it and would appreciate any hints… I'd like to understand it well enough to implement it correctly myself :)

**Comment by dhylands** [comment]
@blmorris In unix/file.c, seek is implemented as mp_stream_seek_obj: https://github.com/micropython/micropython/blob/master/unix/file.c#L213 which is implemented here: https://github.com/micropython/micropython/blob/master/py/stream.c#L377-L401

This calls through the stream's ioctl method (some streams are seekable, others aren't). For a straight forward file, that will wind up calling this ioctl method: https://github.com/micropython/micropython/blob/master/unix/file.c#L91-L106 which will in turn call lseek.

So I think what @pfalcon is getting at is that the tell method should probably be implemented the same way. So that tell would call an mp_stream_tell function, which would also do an ioctl call. Then the seek and tell for the file object both wind up being implemented in fdfile_ioctl.

**Comment by blmorris** [comment]
@dhylands - Thanks, I think that was the hint I needed; I hadn't traced the logic through `stream.c` 
Now to decide whether it's worth doing in terms of MicroPython development. As a learning exercise for me, it will be valuable either way.

**Comment by pfalcon** [comment]
> but I don't see where or how they actually get implemented.
> I imagine there is a basic programming idiom that is familiar to experienced C programmers here

As @dhylands covered concrete parts above, I'd like to answer this: it's indeed basic programming thing-to-know, so worth mastering: it tells that if you don't see how something gets implemented , you still should be able too! If you don't see it in current file, look into other files in the same dir. If can't find there, go level up and search all dirs from there. "grep -r" (recursive) is your friend. Or you favorite IDE/filemanager. Finally, searching using github isn't last choice at all! With big projects, it's actually harder than that, because they may depend on libraries which are external to project, but uPy is pretty self-contained, so you're unlikely hit a dead-end if you try.

**Comment by blmorris** [comment]
@pfalcon @dhylands - Thanks again for the advice. I know about 'grep -r', and I do my coding from emacs and the command line; my problem was in not knowing to look for the file methods as being special cases of the stream methods, and tracing the logic from file.c to stream.c and back again. The link that I missed was the `MP_DEFINE_CONST_FUN_OBJ_*` statements; so I learned another valuable trick here.
uPy development is an 'old dog, new tricks' situation for me, but it's my choice to work on it so I'm trying not to use my inexperience to make excuses for myself ;) 
I do appreciate the help and support!

**Comment by dhylands** [comment]
I actually like a tool called ack for recursive searching.
http://beyondgrep.com/

On Wed, Aug 5, 2015 at 12:58 PM, Bryan Morrissey <notifications@github.com>
wrote:

> @pfalcon <https://github.com/pfalcon> @dhylands
> <https://github.com/dhylands> - Thanks again for the advice. I know about
> 'grep -r', and I do my coding from emacs and the command line; my problem
> was in not knowing to look for the file methods as being special cases of
> the stream methods, and tracing the logic from file.c to stream.c and back
> again. The link that I missed was the MP_DEFINE_CONST_FUN_OBJ_*
> statements; so I learned another valuable trick here.
> uPy development is an 'old dog, new tricks' situation for me, but it's my
> choice to work on it so I'm trying not to use my inexperience to make
> excuses for myself ;)
> I do appreciate the help and support!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/micropython/micropython/pull/1411#issuecomment-128130776>
> .
>



-- 
Dave Hylands
Shuswap, BC, Canada
http://www.davehylands.com

**Comment by dpgeorge** [comment]
> "grep -r" (recursive) is your friend

I actually found out the other day that "git grep ..." does a slightly better job: it does a "grep -r" from the current directory but only searches files under revision control.  Also does highlighting and paging which is a nice touch.

> Is it possible that this patch actually caused the Travis failure in qemu_arm?

No, the Travis failure is totally (?) unrelated and strange and I don't know how to fix it (fails on dict_copy.py).  So don't worry about it.

> As for this patch, it apparently would need to be implemented in terms of underlying seek ioctl.

Yes that makes sense.  Since seek is implemented using ioctl, so should tell.

That means stmhal needs to be changed (because it currently uses a dedicated function for file.tell).

> But I'd prefer it to be #ifdef'ed, and off by default then, until unavoidable need for it arises.

I think tell is basic enough that it should be always-on (and have no config option).  But anyway the config option would be specific to a port because the stream implementation provides stream_tell and if a port doesn't use it then it costs nothing.

**Comment by pfalcon** [comment]
> I think tell is basic enough that it should be always-on (and have no config option). But anyway the config option would be specific to a port because the stream implementation provides stream_tell and if a port doesn't use it then it costs nothing.

So, with this latest reincarnation of implementation idea, stream_tell would be #if'ed, and then specific stream implementation would either not use it, of #if using the same config setting.

I don't know how much basic .tell() should be considered, so perhaps #if'ing can be left until later.

**Comment by dpgeorge** [comment]
> I don't know how much basic .tell() should be considered, so perhaps #if'ing can be left until later.

The ports that have file IO are stmhal, cc3200 and unix.  stmhal will enable stream_tell and I guess unix as well.  So it's up to @danicampora: if he wants stream_tell then we should just have it always enabled without a #if (at least for now), otherwise provide one and disable it for cc3200.

**Comment by danicampora** [comment]
@dpgeorge I want it enabled for the CC3200. I do think it is basic
functionality and doesn't sound like it will take a lot of ROM bytes.

**Comment by blmorris** [comment]
Since this discussion was launched from my PR, I would be happy to try to implement stream_tell, but I will be traveling for the next few days and probably won't get a chance to do it until I return. I won't be offended if anyone else gets it done before I get to it. ;)

**Comment by dpgeorge** [comment]
@blmorris: as a hint for the implementation, file.tell() is equivalent to file.seek(0, SEEK_CUR).

**Comment by blmorris** [comment]
@dpgeorge - Thanks for the tip and the vote of confidence.
PR is updated; file.tell() is now implemented in terms of stream_tell on both unix and stmhal.

**Comment by dpgeorge** [comment]
Thanks!  Merged in bdd78c31b68db5323796d93e0a17159806ce10fc.

**Pull request closed without merging**
