### PR TITLE
Added bounce option for Machine.Pin

### PR DESCRIPTION
**Pull request by BASM**
Contact bounce problem solved from Pin module. The problem is very popular, it makes no sense to solve it in python by user.

### CODE REVIEW

**Comment by pfalcon** [comment]
Of course it makes sense to solve it in Python by user. What doesn't make sense is to solve it again and again in thousands and millions of MicroPython ports to different boards.

**Comment by BASM** [comment]
I agree that this should be done through the use of standardized classes working with GPIO and Timer, but MicroPython does not have it. (yet?) 

Anyway, now user has to rewrite again and again in thousands and millions times for each ports, because MicroPython not have standard GPIO and Timer class, this is also abnormal...

I do not insist on adding this feature to all ports, but in esp8266 it would be very useful.

**Comment by pfalcon** [comment]
> I agree that this should be done through the use of standardized classes working with GPIO and Timer, but MicroPython does not have it. (yet?)

Of course it has, please read the docs: http://docs.micropython.org/

> Anyway, now user has to rewrite again and again in thousands and millions times for each ports, because MicroPython not have standard GPIO and Timer class, this is also abnormal...

Absolutely not, the whole idea of Python (and MicroPython) - to write portable software, and there's everything for that already available.

> I do not insist on adding this feature to all ports, but in esp8266 it would be very useful.

But that's the whole problem with this change - you break compatibility of esp8266 with any other MicroPython port. So, you either need to port your change to every other port (present and future), or find another way to do it, which is portable.

**Comment by BASM** [comment]
> > I agree that this should be done through the use of standardized classes working with GPIO and Timer, but MicroPython does not have it. (yet?)
> Of course it has, please read the docs: http://docs.micropython.org/
> to write portable software, and there's everything for that already available.

Ok, http://docs.micropython.org/en/latest/library/machine.Pin.html#machine.Pin.irq
Pin irq have argument "hard", but it work only for esp8266, stm32, not work for esp32
By default "soft mode" event send to "mp_sched_schedule" 

How many events will be pushed to the mp schedule in the "soft" mode, if bounce contact occured?
Maybe one... or six. This forces us to read pin value only via timers... Only by Timers for compatibility?
I think it is half measure, it beginning of the End...

I think add "bounce" argument is best solution. 

> But that's the whole problem with this change - you break compatibility of esp8266 with any other MicroPython port. So, you either need to port your change to every other port (present and future), or find another way to do it, which is portable.

I agree, to break compatibility is bad. But MicroPython must be simple and logical. Should not have artificial restrictions, because "is to solve it again and again in thousands and millions of MicroPython ports to different boards". I think for compatibility you, or I or we need think about "helper" functions beyond "ports"... Or else... I don't have good solution, maybe you give a hint? 

But if I could convince you, that the "bounce" argument is a best solution, I would like to include this commit to the project. As a first step.

**Comment by chrismas9** [comment]
Would it be worth considering putting debounce in extmod/machine_signal? This already provides a helper function in C for handling inverted signals like active low LEDs and is available across all ports. Signal was done in C, not Python for some reason (speed?), so doesn't this set a precedent for providing convenience functions without bloating pin?

**Comment by pfalcon** [comment]
> Would it be worth considering putting debounce in extmod/machine_signal?

I'm not sure. But it definitely worth considering to put it in https://github.com/somewhere/here and on https://pypi.org/somewhere .

> Signal was done in C, not Python for some reason (speed?), so doesn't this set a precedent for providing convenience functions without bloating pin?

Sure, Signal shows an example how to implement some additional pin-related functionality in a completely portable way, and in C. If debouncing can be implemented in such a completely portable way, then I guess it would make sense to consider it for inclusion in the mainline. Until that, and in all other cases, I guess it make more sense to treat it as a 3rd-party extension module: https://github.com/micropython/micropython/pull/4195

**Comment by andrewleech** [comment]
I agree with @pfalcon that adding this just for esp8266 is a shortsighted change. 
Don't get me wrong, I'd really like this feature to be provided by micropython (on the stm32 port personally), however it should be provided across the board to all ports.

A lot of work has been put in lately to try to bring all the ports to a common level of functionality behind the `machine` interface: https://docs.micropython.org/en/latest/library/machine.Pin.html
Sure there's more to go, with port specific features and args still widespread, but adding new port specific features to a common interface like Pin should be avoided.

Ideally a virtual timer (https://docs.micropython.org/en/latest/library/machine.Timer.html#machine.Timer) could be used rather than `os_timer_t` as that's an esp8266 construct. However virtual timers aren't available on all platforms either. For many people though a blocking wait loop for a few ms would be fine instead of using a timer anyway, even if it's far less efficient.

I like @chrismas9 suggestion of `machine.Signal` (https://docs.micropython.org/en/latest/library/machine.Signal.html), it definitely looks like the right place to put this kind of functionality considering it's already designed as a port agnostic abstraction over `Pin`, although it currently doesn't support interrupt callbacks either.

**Comment by peterhinch** [comment]
Anyone considering implementing this should read [this article](http://www.ganssle.com/debouncing.htm). Some contacts can bounce for a long time: perhaps the time interval should be configurable. A solution usable on any MicroPython platform needs to be able to handle an arbitrary number of switches.

**Comment by andrewleech** [comment]
@peterhinch I think this implementation does have a configurable delay already.

@pfalcon Thinking about it more, there is a strong argument for still allowing single-port-only features, even in common modules like this.
Besides the whole people only have so much time to put towards things, and are more likely to work on areas/ports they're familiar with, it's often a case people can only test with the board/port they have and some features (`machine.Pin`) don't exist on unix port to test there.

So then the question comes down to the acceptance level, do you want to encourage contribution from people who have useful, if somewhat limited, features to add? 

I'm all for trying to continually raise the bar on quality but it can go too far.... 
I've been seriously turned off contributing to the mbed project recently because some large, requested features I've worked on have problems under some of the myriad of commercial (expensive) compilers they insist on being compatible with and I don't have time or ability to test and fix against them, so the PR's end up getting closed and the features lost.

By contrast, I really want virtual timer's on stm32. I have a serious need for them, and will implement them in the coming months. 
However, I may not have realized I even had a need for such a feature if it didn't already exist for another port (esp?) and is mentioned there in the docs. Sure I was disappointed it wasn't already working for stm32, but because it's there and written about I now have a desire, and reference code to work from, when I get time to implement it myself (hopefully in a port-agnostic way).
So by allowing a port-specific machine feature (in the past) it has inspired me, someone other than the original author, to want to add matching features elsewhere. 
Isn't that a great way to share the load of adding new features?

**Comment by pfalcon** [comment]
@andrewleech 

> So then the question comes down to the acceptance level, do you want to encourage contribution from people who have useful, if somewhat limited, features to add?

I don't know, what do you think, CPython wants to "encourage contribution from people who have useful, if somewhat limited, features to add"?

> I've been seriously turned off contributing to the mbed project recently because some large, requested features I've worked on have problems under some of the myriad of commercial (expensive) compilers they insist on being compatible with and I don't have time or ability to test and fix against them, so the PR's end up getting closed and the features lost.

I'm glad to hear you decided to not waste your life on that stuff. Now put yourself in the shoes of the mbed maintainers. Suppose a good-intentioned  gentleman comes by and says that he wants you to support yet another proprietary compiler. It works with just one board, but it's very, very useful compiler to support.

> By contrast, I really want virtual timer's on stm32. I have a serious need for them, and will implement them in the coming months.

Sounds great! And sorry to break fun for you, but you'll be wasting your time. "Virtual timers" is a basic feature of any RTOS, and one RTOS usually support a bunch of subarchs, and even archs. Obviously, it's great fun to reinvent the wheel and do it again and again for each new MCU type, so surely, you won't let comments like that to spoil that fun.

> Isn't that a great way to share the load of adding new features?

Umm, no? However, https://github.com/micropython/micropython/pull/4195 is such a great way, which lets everyone to be as creative as they want, and not put maintenance and support burden on the main project (just imagine, that new Python module you wrote yesterday - you don't need to push it to CPython!). What should happen in the main project is the work on the core language and ecosystem features, not inconsistent hardware hacks.

**Comment by peterhinch** [comment]
Debouncing is straightforward in Python using **uasyncio**, with the advantage that the solution is portable and requires no hardware resources such as timers. See [these example classes](https://github.com/peterhinch/micropython-async/blob/master/DRIVERS.md).

**Comment by dpgeorge** [comment]
As mentioned above, this can be easily done using `uasyncio`.

**Pull request closed without merging**
