### PR TITLE
Add axTLS dependency library.

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by pfalcon** [comment]
After this, https://github.com/micropython/micropython/pull/1317 can be merged.

**Comment by dpgeorge** [comment]
Looks ok and works for me, so can be merged.

Do you think we need a (short) description somewhere of best practices and commands for using submodules?

**Comment by dhylands** [comment]
I think that would be a good idea. I know I've used submodules with git a few years ago, but I'd have to go and read up on them to refresh my memory.

For people who have just gotten started with git, they'll already be overwhelmed, so providing at least the basics like:

- how to get it checked out
- how to update it once the tree exists
- how to incorporate new changes that were made in the submodule

**Comment by pfalcon** [comment]
> Do you think we need a (short) description somewhere of best practices and commands for using submodules?

Definitely. Actually, the best thing I can suggest is #1475, to have enough time to stabilize and test such changes for after-the-next release.

**Comment by pfalcon** [comment]
So I didn't want to merge this while travelling and responding to comments. But basically I agree with what @dhylands said: README of course should be updated with info how to deal with submodule(s). But: a) this change is just another step in long way of having SSL integrated, and b) I'd like to keep submodules optional for as long as it is practical (i.e. until it becomes a burden to maintain).

So, for now I'm merging this change as is to have the usual gradual progress - it doesn't change the wat uPy is build by default in any way. I'll keep polishing it, ultimately adding docs (I'd of course appreciate help with testing it, I'll post interim instructions on forum).

**Comment by dpgeorge** [comment]
Sounds good!

**Comment by pfalcon** [comment]
Ok, I posted instruction on building axtls and modussl on the forum: http://forum.micropython.org/viewtopic.php?f=15&t=524&p=5769#p5769 . Once tested and confirmed by few people, they would be basis for instructions to add to README. So, I'd appreciate help with testing it.

**Pull request closed without merging**
