### PR TITLE
stm32: Confirmed working STM32F413xH integration

### PR DESCRIPTION
**Pull request by gtomassi**
Adds MP support for STM32F413xH series. AD pinout files missing but drop-in with F11 with minor differences. Tested stability on hardware using board config:
MCU_SERIES = f4
CMSIS_MCU = STM32F413xx
AF_FILE = boards/stm32f411_af.csv
LD_FILES = boards/stm32f413xh.ld boards/common_ifs.ld
TEXT0_ADDR = 0x08000000
TEXT1_ADDR = 0x08020000

If someone knows where to find AF pinout CSV file, please add.

### CODE REVIEW

**Comment by dmazzella** [comment]
AF pinout CSV file 
[stm32f413_af.csv.zip](https://github.com/micropython/micropython/files/2834000/stm32f413_af.csv.zip)

**Comment by gtomassi** [comment]
Thank you @dmazzella !

I've added the pinouts and performed a flash successfully.

**Comment by chrismas9** [comment]
I am working on a comprehensive F413 port with support for all peripherals including CAN3 and UARTs 9 and 10. There are several bugs and omissions in the STM cube libraries and more MicroPython changes needed to support them. I am currently doing driver tests with external peripherals on all ports (eg EEProms on I2C and SPI). I will be submitting. PR as soon as I finish hardware testing.

**Comment by dpgeorge** [comment]
Thanks @gtomassi for the contribution.  Let's wait for @chrismas9 to submit his version, then we can review them.

**Comment by TravisJoe** [comment]
This it nice to hear!
I was bugging Damien about this but got distracted with another project. Unfortunately I rarely have time to help, but I can send beer money if that is needed for extra incentives.

**Comment by dpgeorge** [comment]
F413 support was added in 1b956ec81701ad9ae36e8e0fd625eff32e3e2a3d

**Pull request closed without merging**
