### PR TITLE
ports/all: Rename machine types consistently across ports.

### PR DESCRIPTION
**Pull request by iabdalkader**

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thinking about this some more, all the core types like `mp_type_str` begin with `mp_type_`.  So maybe we should follow that naming scheme and use `mp_type_machine_spi` etc?

I think the original reasoning for naming it `(mp_)machine_spi_type` was that it's an extension to the core and so is prefixed with `mp_machine_` first of all.  And then the type went at the end for some reason.

**Comment by iabdalkader** [comment]
I think it should be `mp_machine_type_*` because it will match existing patterns in: protocols like `mp_machine_spi_p_t`, and in soft i2c/spi types: `mp_machine_soft_spi_p` and `mp_machine_soft_i2c_type`, and `mp_type_*` can be justified because it's for core/built-in types. That said, this will be a major change (will basically have to rename *all* types in *all* ports) including some modules outside of `ports` (at least 2 of them, wiznet and nina that make use of machine types), not just i2c/spi otherwise types in a `modmachine.h` will look like this:

```
extern const mp_obj_type_t machine_adc_type;
extern const mp_obj_type_t mp_machine_i2c_type;
extern const mp_obj_type_t mp_machine_spi_type;
extern const mp_obj_type_t machine_i2s_type;
extern const mp_obj_type_t machine_pin_type;
extern const mp_obj_type_t machine_rtc_type;
extern const mp_obj_type_t machine_timer_type;
```

**Comment by dpgeorge** [comment]
I think whatever it's changed to, a lot of things need to be renamed to match.

With modules, it's now mostly standardised to `mp_module_*`.  So IMO it makes sense to standardise types to `mp_type_*`.

**Comment by dpgeorge** [comment]
This is a good clean up to start with that has minimal changes, so let's go for it.  Later on things can be made further consistent (eg `mp_type_<module-name>_<class-name>`) if needed.

Rebased and merged in af4ba6d1b4558e0ce1c81b8acd975f0bcbe83072 through 93f3910fe7e43de5661ff0d6f961c6eccb8537e5

**Pull request closed without merging**
