### PR TITLE
stmhal: Fix broken USB REPL on STM32F429DISC board

### PR DESCRIPTION
**Pull request by mulleand**
USB REPL has been broken since commit d363133
This small patch is fixing issue #1944
Original patch by @hoihu

### CODE REVIEW

**Comment by pfalcon** [comment]
From the commit message, it's not clear what it does in the first place and why it's correct. Also, there's another place which still has "pcd_fs_handle.Init.Sof_enable = 0". @hoihu, please confirm that it should be set to 1 too.

**Comment by mulleand** [comment]
I apologize for the inadequate commit message. The reason for this change is, that the STM429DISC has the USB configured using HS mode ("USE_USB_HS"). The SOF irqs that were introduced in 1.6 are currently configured only in FS mode. Due to that the callback that inputs the REPL with the chars received from USB is not called.

**Comment by hoihu** [comment]
@pfalcon High Speed mode is only enabled on this specific board, for the reason given by @dhylands in #1944. 

The section further down would apply to a board that has pure  high speed mode configured - but such a board doesn't exist in the repo.

It makes sense to set both lines to 1. SOF irqs are the new way of periodically polling the USB rx/tx buffers, so any board that has not configured it would fail to activate the REPL or in fact would fail to send any data over USB.

@mulleand can you  do the additional commit? Sqash it  it with the previous commit and push it to your branch again. It will automatically be updated here (no need to make a new pull request). See also the micropython wiki for guideline on contributions. Thanks!

**Comment by pfalcon** [comment]
> SOF irqs are the new way of periodically polling the USB rx/tx buffers, so any board that has not configured it would fail to activate the REPL or in fact would fail to send any data over USB.

Exactly, that's what I figured after looking at it for a couple of minutes. So, it's not even about "boards", it's about CPU features which must be enabled now.

The commit message I may suggest is:

~~~
stmhal: Consistently enable USB SOF for all CPU modes.

Since d363133, SOF interrupt is required for USB REPL to function. This change
in particular fixes REPL on STM32F429DISC.
~~~

Thanks!

**Comment by mulleand** [comment]
@hoihu I'm sorry, I just don't know enough about git to follow your suggestion. It probably will be easier if we just close this pull request and you can make a new one.

**Comment by hoihu** [comment]
ok i have submitted #1970, please close this pull request

**Pull request closed without merging**
