### PR TITLE
esp32: Switch to IDF v5.0

### PR DESCRIPTION
**Pull request by dpgeorge**
For the esp32 port, MicroPython currently supports IDF v4.x (from 4.0.2 up to the latest 4.4.4).  There is now a new major version of IDF v5.x, with a release v5.0.1.

IDF 5 is needed for some of the newer esp32 SoCs to work.  It also cleans up a lot of the inconsistencies between existing SoCs (eg S2, S3, C3).

I propose to switch entirely to IDF v5, ie drop support for IDF v4.  Mainly because it's a lot of effort to maintain both at the same time, and that effort is better spent elsewhere.

This PR gets basic IDF v5. support working.  Current status:
| | ESP32 | ESP32-S2 | ESP32-S3 | ESP32-C3 |
|-|-|-|-|-|
| builds | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| SPIRAM | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | N/A |
| REPL (UART) | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| REPL (USB) | N/A | :heavy_check_mark: | :heavy_check_mark: | N/A |
| filesystem | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| GPIO | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| SPI | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| I2C | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| PWM | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| ADC | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| WiFi STA | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| WiFi AP | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| BLE | :heavy_check_mark: | N/A | :heavy_check_mark: | :heavy_check_mark:  |
| ETH | :heavy_check_mark: | | | |
| PPP | :heavy_check_mark: | | :heavy_check_mark:  | :heavy_check_mark:  |
| sockets | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| SSL | :heavy_check_mark: | ENOMEM | :heavy_check_mark: | :heavy_check_mark: |
| RMT | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| NeoPixel | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| I2S | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | N/A |
| ESPNow | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark: |
| ULP-FSM | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | N/A|
| SDCard | :heavy_check_mark: | N/A | N/A |  :heavy_check_mark: |
| WDT | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

### CODE REVIEW

**Comment by wnienhaus** [comment]
For the table above: I just tested this branch on both the ESP32-S2 and the ESP32-S3 and the ULP-FSM works correctly.

(To test, I used this sample code: https://github.com/micropython/micropython/pull/11761#issuecomment-1586565719).

I still want to test the same on the original ESP32 and will then let you know my result.

**Comment by wnienhaus** [comment]
Now I tested this branch on the original ESP32 too and the ULP-FSM works correctly.

**Comment by dpgeorge** [comment]
Thank you @wnienhaus !  I have updated the table.

**Comment by bwhitman** [comment]
I am using this on ESP32-S3 and can confirm SPIRAM works great there (gc.mem_free() shows me 4MB heap and it works), and UART REPL is fine. I have also tested WIFI STA and it works. It's a huge help for my project, so thank you!

**Comment by bwhitman** [comment]
I am having issues with this branch (and only this branch) flashing my custom LFS2 partition and it booting properly. [I run this script locally](https://github.com/bwhitman/tulipcc/blob/main/ports/esp32s3/tulip_fs_create.py) to generate a .bin from local files and use `parttool` to flash the `vfs` partition. But on boot `inisetup.py` runs and always falls back to `fs_corrupted()`, whereas on the main branch of Micropython, it will mount my partition just fine. I'm digging in but wanted to point it out just in case.

**Comment by bwhitman** [comment]
> @bwhitman did you delete a comment about LFS2 partitions not working? I just want to make sure everything is OK with that (it would be a show-stopper if it didn't work).

I did. I thought it was due to the new MP or IDF, but it was because the new IDF gave me a new env where I re-installed `littles-python`, which got me a brand new version that made a LFS partition version 2.1, which was too new for MP / IDF 5.0.2. (It will return `ENOENT` if it's over 2.0. I eventually found it by turning on LFS debugging.) [I've made an issue for that over there.](https://github.com/jrast/littlefs-python/issues/35). Apologies, I should have updated my comment instead of deleting it.

**Comment by dpgeorge** [comment]
> Apologies, I should have updated my comment instead of deleting it.

No worries.  But, yes, definitely best to update your comment instead of deleting :smile:

**Comment by jimmo** [comment]
Tested: GPIO, I2C, SPI, RMT, NeoPixel, ADC, PWM across OG,S2,S3,C3. Also added REPL UART+USB on S2,S3, and Ethernet (IP101) on OG.

**Comment by dpgeorge** [comment]
SD card code has been updated for IDF v5, and tested working on ESP32.

**Comment by jimmo** [comment]
Tested PPP on OG/S3/C3, SDCard on S3.

**Comment by dpgeorge** [comment]
The `esp32.hall_sensor()` function has been removed.  The Hall sensor is no longer supported by the IDF.

**Comment by dpgeorge** [comment]
All 26 existing esp32 boards build successfully with this PR.

**Comment by robert-hh** [comment]
That's indeed a massive test.

**Comment by AmirHmZz** [comment]
First of all, thanks to @jimmo @glenn20 @projectgus and specially @dpgeorge for their massive work done here.
It seems to be some warnings about compiling `modbtree.c` against `IDF v5.0.2` which I've uploaded as a gist [here](https://gist.github.com/AmirHmZz/c26dd51c6daea0166bb30bc82685bf4b#file-gistfile1-txt). What's that all about?

**Comment by dpgeorge** [comment]
> It seems to be some warnings about compiling `modbtree.c` against `IDF v5.0.2`

Thanks for reporting that.  Should now be fixed.

**Comment by ThinkTransit** [comment]
This is looking great!

I have tested on a UMFEATHERS2 board and the SPI flash doesn't seem to work, I'm not sure if it is something that I have done incorrectly but I get this error on boot. The board has a bootloader by default and is programmed by copying over a UF2, maybe this has something to do with it?

```
MPY: soft reboot
Performing initial setup
Traceback (most recent call last):
  File "_boot.py", line 11, in <module>
  File "inisetup.py", line 40, in setup
OSError: [Errno 22] EINVAL
MicroPython v1.20.0-239-g1cb22e7be on 2023-06-22; FeatherS2 with ESP32-S2
Type "help()" for more information.
>>> 
```


```
cp main.py :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 19] ENODEV
```

**Comment by dpgeorge** [comment]
@ThinkTransit if you programmed with a UF2 file then it's likely that the partition table is different to what's expected by the MicroPython firmware.

Can you run:
```
from esp32 import Partition
print(Partition.find(Partition.TYPE_DATA, label="vfs"))
print(Partition.find(Partition.TYPE_DATA, label="ffat", block_size=512))
```
?

If the first line prints `None` and the second line prints something else then you might be able to fix it by manually creating the filesystem:
```
os.VfsFat.mkfs(bdev)
```

**Comment by ThinkTransit** [comment]
> @ThinkTransit if you programmed with a UF2 file then it's likely that the partition table is different to what's expected by the MicroPython firmware.
> 
> Can you run:
> 
> ```
> from esp32 import Partition
> print(Partition.find(Partition.TYPE_DATA, label="vfs"))
> print(Partition.find(Partition.TYPE_DATA, label="ffat", block_size=512))
> ```
> 
> ?
> 
> If the first line prints `None` and the second line prints something else then you might be able to fix it by manually creating the filesystem:
> 
> ```
> os.VfsFat.mkfs(bdev)
> ```

Thanks @dpgeorge , creating the filesystem manually works.

```
>>> from esp32 import Partition
>>> print(Partition.find(Partition.TYPE_DATA, label="vfs"))
[]
>>> import os
>>> os.VfsFat.mkfs(bdev)
>>> 
MPY: soft reboot
MicroPython v1.20.0-239-g1cb22e7be on 2023-06-22; FeatherS2 with ESP32-S2
Type "help()" for more information.
>>> 

```

**Comment by dpgeorge** [comment]
> creating the filesystem manually works

In this case (programming with a UF2) it's assumed that the previous firmware has created the FAT filesystem.

To improve this situation we need to modify `inisetup.py` to detect if it should create a LFS or FAT filesystem, based on the Partition label.

**Comment by ThinkTransit** [comment]
> > creating the filesystem manually works
> 
> In this case (programming with a UF2) it's assumed that the previous firmware has created the FAT filesystem.
> 
> To improve this situation we need to modify `inisetup.py` to detect if it should create a LFS or FAT filesystem, based on the Partition label.

Ok makes sense thanks.

I just tested this board without the bootloader.
```
esptool.py --chip esp32s2 --port /dev/ttyACM0 erase_flash
esptool.py --chip esp32s2 --port /dev/ttyACM0 write_flash -z 0x1000 ports/esp32/build-UM_FEATHERS2/micropython.bin
```
again probably doing something wrong but the usb doesn't enumerate and a loadstore error is repeated on uart0. Could it be related?

```
ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3f000020,len:0x364a4
Panic at 4001126a
Fatal exception (3): LoadStoreError
epc1=0x4000ff4b, epc2=0x00000000, epc3=0x00000000, excvaddr=0x3f000020, depc=0x00000000
ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x4000f254
SPIWP:0xee
mode:DIO, clock div:1
load:0x3f000020,len:0x364a4
Panic at 4001126a
Fatal exception (3): LoadStoreError
epc1=0x4000ff4b, epc2=0x00000000, epc3=0x00000000, excvaddr=0x3f000020, depc=0x00000000

```

**Comment by wnienhaus** [comment]
I had this exact same error (LoadStoreError), when I used the wrong offset for the `micropython.bin`. I believe it should be 0x10000 (4 zeros) instead of 0x1000 (3 zeros). Now you would also have to write `bootloader.bin` to 0x1000 again, to restore a working bootloader.

**Comment by AmirHmZz** [comment]
I've run our main project on this PR built with `idf5.0.2` and everything worked correctly!
- Tested components : `GPIO` `SPI` `SD Card` `I2C` `PWM` `WIFI STA` `Socket` `ESPNow` `BTree`
- Tested on : ESP32

**Comment by dpgeorge** [comment]
> I've run our main project on this PR built with `idf5.0.2` and everything worked correctly!


Very good, thanks for the additional testing!

I have also tested `machine.I2S` on ESP32, ESP32S2 and ESP32S3.

**Comment by dpgeorge** [comment]
Merged!

**Comment by robert-hh** [comment]
Thanks. That was surely a lot of work. Time for a relaxed weekend.

**Comment by Carglglz** [comment]
@dpgeorge I've managed to rebase #8968 to include these changes and everything seems to be working but I've noticed that `mDNS` support and `esp32_mbedtls_errors.c` where left behind, is there any reason for this? So far I've managed to add `mDNS` support again and I will look into `mbedtls_errors.c` next, also now that the `esp32` port is at `mbedtls 3.3.0` maybe is time to revisit #8988 ? 👀

**Comment by Wind-stormger** [comment]
> To improve this situation we need to modify `inisetup.py` to detect if it should create a LFS or FAT filesystem, based on the Partition label.

https://github.com/orgs/micropython/discussions/9961#discussioncomment-6227871

I've put my code up for this.

 Would I submit a PR?

**Comment by dpgeorge** [comment]
> I've noticed that `mDNS` support and `esp32_mbedtls_errors.c` were left behind

I thought I left mDNS as is... but maybe I missed something there.

For the custom mbedtls errors, yes, I did not update that.  The only downside there is that the error messages will be longer/take up more flash (and be different to other mbedtls ports...).  For example what used to be:
```
OSError(-29184, 'MBEDTLS_ERR_SSL_INVALID_RECORD')
```
Is now (on esp32 with IDF 5):
```
OSError(-29184, 'SSL - An invalid SSL record was received')
```
I would like to eventually fix this (feel free to try!) but it's not a high priority at the moment.

> also now that the esp32 port is at mbedtls 3.3.0 maybe is time to revisit https://github.com/micropython/micropython/pull/8988

Maybe... you already did update to v2.28.3 in 61b8e1b2d89175d288239376762184c78fdd5c9d and it would be good to have that in the next release which is scheduled for the end of this month (!).  Then we can update to v3.3.0 after the release.

**Comment by Carglglz** [comment]
> I thought I left mDNS as is... but maybe I missed something there.

Yes, for some reason Espressif decided to move `mDNS` outside of the `esp-idf` repo, is now here [esp-protocols](https://github.com/espressif/esp-protocols), I had to clone it and copy the `mdns` component  to `esp-idf/components`, add it to 
`esp32_common.cmake` and include `mdns.h` in `network_wlan.c` and `modsocket.c`, after that it worked again as expected, I'll do a PR if necessary. 👍🏼  

> I would like to eventually fix this (feel free to try!) but it's not a high priority at the moment.

I agree 

> Then we can update to v3.3.0 after the release.

Yes, this is probably the best option 🤔

**Comment by dpgeorge** [comment]
> I'll do a PR if necessary

If you have time, that would be great.

**Pull request merged**
