### PR TITLE
ports/esp32: WLAN use esp_wifi_s/get_channel() to set and get wifi channel.

### PR DESCRIPTION
**Pull request by glenn20**
This PR updates `ports/esp32/network_wlan.c` to use the `esp_wifi_set_channel()` and `esp_wifi_get_channel()` to set and get the current wifi channel.

**Fixes:** WLAN.config('channel') returns incorrect channel for AP_IF if STA has connected to an external AP running on a different channel.

> Currently, WLAN.config('channel')  returns the configured channel for the AP_IF rather than the current channel. The current channel of the AP_IF will change if the STA_IF has connected to an Access Point on a different channel. eg:
> ```
> import network, time
> sta, ap = [network.WLAN(i) for i in (0, 1)]; sta.active(True); ap.active(True)
> ap.config(channel=6)
> sta.connect(ssid, password)    # Connect to AP running on channel 11
> while not sta.isconnected(): time.sleep(0.1)
> print("AP channel =", ap.config('channel'))
> ```
> will print "AP channel = 6" but the AP is actualy running on channel 11. With this PR, the correct "AP channel = 11" will be printed.
> 

**Extends**: Provides support for setting the secondary wifi channel as well as the primary channel.

> WLAN.config(channel=x) will also accept x as a tuple: (p, s) where p is the primary channel and s signifies the secondary channel by: 
> 
> - s < 0: WIFI_SECOND_CHAN_BELOW, s == 0: WIFI_SECOND_CHAN_NONE; s > 0: WIFI_SECOND_CHAN_ABOVE
> 
> Example:
> ```
> import network
> ap = network.WLAN(1); ap.active(True)
> ap.config(channel=6)
> ap.config(channel=(6,-1))
> ap.config(channel=(6,0))
> ap.config(channel=(6,+1))
> ```
> 

Also provides support for setting the channel of the STA_IF interface (supported in the IDF since IDFv4+).

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for this, it seems like a necessary fix.

But it would be better to split the fix and the extension into separate commits.  I'm not sure it's the right approach to allow passing in a tuple for the channel to select the secondary channel (what is the secondary channel used for?).  It might be better to use a new config option like `channel_secondary`, and that will also allow the user to query it rather than just set it.

> Also provides support for setting the channel of the STA_IF interface

What does it mean to set the channel of the STA interface?  Isn't that dictated by the AP it connects to?

**Comment by glenn20** [comment]
> Thanks for this, it seems like a necessary fix.
> 
> But it would be better to split the fix and the extension into separate commits. I'm not sure it's the right approach to allow passing in a tuple for the channel to select the secondary channel (what is the secondary channel used for?). It might be better to use a new config option like `channel_secondary`, and that will also allow the user to query it rather than just set it.

(Secondary channel is used in 40MHz bandwidth mode where the secondary channel must be one above or one below the primary channel. If it is not set, the radio operates in 20MHz bandwidth mode. An alternative would be to use some recipe to set the secondary channel - but it seemed better to give users control over this since the low-level API does).

A good point - I considered this approach too. I will move the secondary channel to a separate PR and change the approach as recommended. 

> 
> > Also provides support for setting the channel of the STA_IF interface
> 
> What does it mean to set the channel of the STA interface? Isn't that dictated by the AP it connects to?

Well, the esp_wifi_set_channel() call accepts the STA or AP interface (since IDF 4+), so it seems unnecessary to exclude the STA interface in micropython. Espressif probably added this to support configuring the channel for ESP-Now traffic on STA (and this will be needed if the espnow PR is merged).

**Comment by glenn20** [comment]
Updated to remove the secondary channel option for WLAN.config(channel=), as proposed.

**Comment by dpgeorge** [comment]
Thanks for updating, it looks good now, a good improvement.  Merged in 98d1c50159fe9427d72ec358ba0219eaebb1d991

**Comment by davefes** [comment]
`MicroPython v1.22.2 on 2024-02-22; Generic ESP32 module with SPIRAM with ESP32` can not set the channel and the bandwidth is 60MHz

**Pull request closed without merging**
