### PR TITLE
samd: Add the Pycubed-Mini V4 board.

### PR DESCRIPTION
**Pull request by thetazero**

### CODE REVIEW

**Comment by robert-hh** [comment]
That's an interesting board. The errors you got with the PR attempt are minor:
- at mpconfigboard.h the newline at the end is missing.
- The commit message has the wrong format. It could e.g. be:
`samd: Add the Pycubed-Mini V03 board.`

I'm a little bit confused. The web site you link does not mention the V03 board. It shows V2, V4 and V5. And sometimes you call it V03, sometimes V3. That should be consistent. 
The pins.csv file might need some rework as well. It should probably be:
```
PIN_PB13,SCL1
PIN_PA17,SDA2
```
And in line 19:
`PIN_PA05,RF_IO0`

**Comment by robert-hh** [comment]
Note: You do not have to close a PR for corrections. Just fix the things on your PC and make a force push to your repository. The PR will then be updated.

**Comment by thetazero** [comment]
Thanks @robert-hh, I've implemented your suggestions.  (I'll be better with commit messages going forward)

I'd really appreciate a suggestion for how to debug this firmware.  

The firmware doesn't seem to work, it doesn't even boot anymore.
If it helps we're trying to switch from Circuitpython to Micropython, here's a copy of our most recent working firmware: https://github.com/PyCubed-Mini/avionics-mainboard/tree/main/firmware/pycubedminiv03

**Comment by robert-hh** [comment]
Line 22 of pins.csv is still wrong. It starts with `in_PA05`. Should probably be `PIN_PA05`.

**Comment by thetazero** [comment]
Thanks fixed that

**Comment by robert-hh** [comment]
It is an interesting board. Until now I did not have one with a SAMD51J19 chip.
A few comments:
- There are a lot of commented lines in mpconfigboard.h, which also create code formatting error. If you do not need them, delete them.
- There are quite a few error messages about the commit message format. The expected format is:
`topic: Commit message starting with a capital end ending with full stop.` for instance:
samd: Add the Pycubed-Mini V3 board.
You used that message for the PR, but is must be used for every commit as well. That makes i easier for the maintainer to find commits about a specific file or topic. You can update the last commit in your repository with `git --amend` and then make a force push to your fork.

Sorry about this formal pedantry, but it helps.

**Comment by robert-hh** [comment]
Please check pins.csv. I tried to compare that with the schematics in the link, and for instance PA09 is most likely FLASH_MISO, and PB10 is missing, which is FLASH_SCK. The other pins seem ok.

**Comment by robert-hh** [comment]
It looks like CI is broken at the moment. It complains a lot about perfect commit messages like your‘s.

**Comment by thetazero** [comment]
@robert-hh any way to re-trigger the CI?

Would be nice to get this merged.

**Comment by robert-hh** [comment]
If you rebase your branch and do a force push the CI checks are run again.
It seems lately that PR for new boards are processed quite slowly. At the SAMD port, 3 new boards are in the queue. Not to mention the ESP32 and rp2040 ports. And there is #12211, which require for SAMD board PR to update the pins.csv file. No clue when 12211 will be merged.

**Comment by robert-hh** [comment]
This PR seems stuck in time, and I do not know If you still support it. But if yes, it has to be changed:
Since PR #12211, the pins.csv file has been changed.

- the columns of the file are swapped. It's board_name, pin_name now.
- the pin names have changed form PIN_Pxnn to Pxnn, e.g. PIN_PA00 to PA00.

**Comment by thetazero** [comment]
@robert-hh, I've moved on from the team working on this board, and I don't think anyone is planning on taking it on in the near future. 

I appreciate all your help though!

**Pull request closed without merging**
