### PR TITLE
Clarify ESP8266 build instructions

### PR DESCRIPTION
**Pull request by SpotlightKid**
- Add instructions to get external dependencies to `esp8266/README.md`.
- Add reference to ESP8266 README in main README.
- Make section on external deps in main README more generic.
- Move unix section behind it.

### CODE REVIEW

**Comment by SpotlightKid** [comment]
Any opinions on this? I'm asking because the missing instruction to init the git submodules in the esp8266 readme has already tripped up several people [on the forum](http://forum.micropython.org/viewtopic.php?f=16&t=1546).

**Comment by dpgeorge** [comment]
I'm happy to merge the change to esp8266/README.md; that should be enough (you anyway must read that file to know how to build it).

**Comment by pfalcon** [comment]
> I'm happy to merge the change to esp8266/README.md; that should be enough (you anyway must read that file to know how to build it).

That's exactly what I wanted to do (but didn't get to). The rest of changes as they are complicate unix build. They would be grounded if unix is switched to require external modules (axTLS), and it's a shame it wasn't still, but the reason for that is exactly not to complicate unix build for newcomers. And for now we have enough changes with esp8266 port to put other "breaking" changes on hold.

**Comment by SpotlightKid** [comment]
I'm not sure what you mean with your remark about the unix build. All I did was put the section "External dependencies" before the section "The Unix version" so that all sections on different ports follow each other, and changed the first and fourth paragraph of the "External dependencies" section to make it clear that the part about git submodules not only applies to the unix build but also to other ports, namely (atm) the esp8266 port.

**Comment by SpotlightKid** [comment]
Maybe the main README should just have a short reference to the README in the port's subdirectory for each port anyway.

**Comment by dpgeorge** [comment]
> Maybe the main README should just have a short reference to the README in the port's subdirectory for each port anyway.

No, that will be too many paragraphs just saying "see here".

**Comment by dpgeorge** [comment]
Changes to esp8266/README.md were merged in 3d0e3a3d3eb3079599de63f2a232b5cf4b26399f.

The main readme needs to stay lean and efficient, like uPy itself :)

**Comment by SpotlightKid** [comment]
Ok, thanks! I might do another PR to move that unix port specific stuff into its own README then ;)

**Comment by pfalcon** [comment]
@SpotlightKid : Alternatively, feel free to leave it to project maintainers ;). There're a lot of places where community can help, and few places which better be left as responsibility of the maintainers. You of course welcome to argue your cause (but then please start with arguments, not patches).

**Comment by SpotlightKid** [comment]
To me, a PR *is* an invitation for a discussion. :) I'm not bothered if a PR is rejected.

**Comment by pfalcon** [comment]
Sounds good!

**Pull request closed without merging**
