### PR TITLE
ESP32: add pin drive strength

### LINKED ISSUE #8315: ESP32: port missing support for pin drive strength
The ESP32 GPIO hardware can be configured between four different drive strengths, but the port doesn't support the `drive=` argument to `Pin()`.

### PR DESCRIPTION
**Pull request by jonathanhogg**
Add support for setting the ESP32 GPIO drive strength. There are four supported strengths:

 - 0 = `Pin.DRIVE_WEAK`: 5mA (max source/sink current) / 130 ohm (approx internal resistance)
 - 1 = `Pin.DRIVE_LOW`: 10mA / 60 ohm
 - 2 = `Pin.DRIVE_MED`: 20mA / 30 ohm
 - 3 = `Pin.DRIVE_HIGH`: 40mA / 15 ohm

I've used the standard 3 documented drive strength constant names from the `machine.Pin` module docs and added `DRIVE_WEAK` for the extra one that the ESP32 supports – decided to put it at the weaker end rather than having a `DRIVE_HIGHEST` constant as the ESP32 default is `2` and that seems to match most naturally to `DRIVE_MED`.

This was previously bundled up in PR #8284, but having used this functionality for a bit I've decided that it is sufficiently useful to be pulled out on its own and not tied to that (more controversial) PR.

Fixes #8315.

### CODE REVIEW

**Comment by jonathanhogg** [comment]
I have verified all four drive strengths on real ESP32 hardware. The IDF docs suggest that the same drive strength values apply to S2, S3 and C3 variants, but I have no real hardware to test this on.

The maximum source/sink currents come from note 8 in table 24 of the ESP32 Datasheet; the approximate internal resistances come from my own tests and [this useful forum post](https://www.esp32.com/viewtopic.php?t=5840#p25550).

The drivers are non-linear so pushing them to the limit results in much higher apparent resistance. I've gone with roughly where they stand when running at the maximum recommended current. I've included these rough internal resistances in the docs because they can make a big difference to circuit design – e.g., in terms of resistor choice when driving an LED.

**Comment by dpgeorge** [comment]
Thanks for this, the feature looks good.

The only problem is the name of the drive constants:
- in the docs it specifies `LOW_POWER`, `MED_POWER` and `HIGH_POWER`
- cc3200 and samd ports use the above constants
- mimxrt uses `DRIVER_OFF` and `POWER_0` - `POWER_6`

There was a discussion of the drive/power constants for mimxrt, but I'm not sure why it ended up being different to the docs.  Probably because there are many values and it's hard to name them with low/med/high etc and understand the ordering.

I do actually prefer the names `DRIVE_LOW`, `DRIVE_MED`, `DRIVE_HIGH`, because it's clear what argument they should be used for, namely `drive`.  This matches the `pull` constants like `PULL_UP`.

----------

It would be good to make all of this consistent.  Here is my suggestion: use constants `DRIVE_0`, `DRIVE_1`, `DRIVE_2` etc (without a limit on the number of them).  Then a port just uses 0 up to the maximum number of options that it has.  It's very clear what the ordering are.  And the word `DRIVE_` matches the argument name `drive`.

@robert-hh what do you think?

**Comment by robert-hh** [comment]
@dpgeorge It is always favorable to have a common API, and I can go with any name, shorter being better. I'll discuss it with @alphaFred, because that part was made by him.

**Comment by alphaFred** [comment]
Hi @dpgeorge   
@robert-hh relayed your message since that module was implemented by me. I would be fine with the name change. I totally agree - having a commons naming is much better.

**Comment by dpgeorge** [comment]
OK, so we go with `DRIVE_n` constants for all ports then.

**Comment by alphaFred** [comment]
Yes. I will provide a PR for mimxrt soon, too.

**Pull request closed without merging**
