### PR TITLE
extmod/uasyncio: Add readinto() method to Stream class.

### PR DESCRIPTION
**Pull request by miketeachman**
This new method is needed for the I2S PR  https://github.com/micropython/micropython/pull/7183

I wrote a test that runs on the ESP32 and Pyboard ports.  The test requires `io.IOBase` which unfortunately is not supported on the unix port.   Hence, it fails on the unix port, so I didn't commit the test.

The test is below.  Any ideas on how to get this running on the unix port are appreciated.

```
try:
    import uasyncio as asyncio
except ImportError:
    try:
        import asyncio
    except ImportError:
        print("SKIP")
        raise SystemExit

try:
    import uio as io
except ImportError:
    try:
        import io
    except ImportError:
        print("SKIP")
        raise SystemExit

MP_STREAM_POLL_RD = 1
MP_STREAM_POLL = 3
MP_STREAM_ERROR = -1


class MyDriver(io.IOBase):
    def __init__(self):
        pass

    def readinto(self, buf):
        buf[0] = 99
        return 1

    def ioctl(self, req, arg):
        ret = MP_STREAM_ERROR
        if req == MP_STREAM_POLL:
            ret = 0
            if arg & MP_STREAM_POLL_RD:
                ret |= MP_STREAM_POLL_RD
        return ret


async def main():
    print("start")

    driver = MyDriver()
    sreader = asyncio.StreamReader(driver)
    buf = bytearray(1)
    num_bytes_from_readinto = await sreader.readinto(buf)
    print(num_bytes_from_readinto)
    print(buf[0])

    print("finish")


asyncio.run(main())

```

### CODE REVIEW

**Comment by dlech** [comment]
Can you commit the test so we can see the failure in CI? The unix port has `MICROPY_PY_IO_IOBASE` enabled so I'm not sure what you mean when you say that it is not supported.

**Comment by miketeachman** [comment]
> Can you commit the test so we can see the failure in CI? The unix port has `MICROPY_PY_IO_IOBASE` enabled so I'm not sure what you mean when you say that it is not supported.

The test is committed.   I should of just said that the test failed rather saying it is not supported - poor choice of words.

I would be grateful for any insights.

**Comment by dlech** [comment]
> TypeError: can't convert MyDriver to int

I haven't gone digging to see why, but I'm guessing it is expecting a file descriptor (`int`) instead on the unix port.

**Comment by miketeachman** [comment]
Thanks for taking a look!    I do not have a running unix build to debug this further so I am hoping that someone has seen this problem before and can suggest a fix.   

Here is the full debug trace coming from the test run:

```
+Traceback (most recent call last):
+  File "extmod/uasyncio_readinto.py", line 54, in <module>
+  File "/home/runner/work/micropython/micropython/extmod/uasyncio/core.py", line 208, in run
+  File "/home/runner/work/micropython/micropython/extmod/uasyncio/core.py", line 187, in run_until_complete
+  File "/home/runner/work/micropython/micropython/extmod/uasyncio/core.py", line 176, in run_until_complete
+  File "extmod/uasyncio_readinto.py", line 47, in main
+  File "/home/runner/work/micropython/micropython/extmod/uasyncio/stream.py", line 34, in readinto
+  File "/home/runner/work/micropython/micropython/extmod/uasyncio/core.py", line 94, in queue_read
+  File "/home/runner/work/micropython/micropython/extmod/uasyncio/core.py", line 79, in _enqueue
+TypeError: can't convert MyDriver to int
+CRASH
```

**Comment by dpgeorge** [comment]
It's not possible to test using a custom stream.  Please see this commit which added `readexactly()`: 441460d81ff2b1faee7d044d859896f754361b93

**Comment by dpgeorge** [comment]
> It's not possible to test using a custom stream

I should clarify: it's not possible to test on the unix port because unix requires a true file to do IO, not a custom one.

**Comment by miketeachman** [comment]
Thanks.  I will rework the test using the `readexactly` test as a guide.

**Comment by miketeachman** [comment]
I'll be out of town for the next week.  I'll be able to finish and commit the test piece shortly after I get back.

**Comment by miketeachman** [comment]
The `readinto()` test has been updated

**Comment by dpgeorge** [comment]
Thank you!  Squashed and merged in b0b8ebc4f6e337e18c79367ccc5f379dfa8681d9, with a note added to the docs that this method is a MicroPython extension.

**Pull request closed without merging**
