### PR TITLE
ports/renesas-ra: Update linker script to detect code flash overflow.

### PR DESCRIPTION
**Pull request by TakeoTakahashi2020**
This PR solves code flash overflow issue.  
The latest code increases about 6KB on RA4M1 board and code image breaks the internal file system area.
So update followings:

* Update linker script to detect Code Flash overflow.
* Enable configurable ADC, SPI and I2c to reduce code.
* Update optional feature description for RA4M1 boards.
* Fix internal flash file system size for RA6M2 boards.

### CODE REVIEW

**Comment by TakeoTakahashi2020** [comment]
Thank you for your helpful comments.
I recognized code does not overflow if debugging option is disabled for RA4. So I just improved followings and rebased to the latest.

*  Improved linker script file so that it detects code overflow.
*  Defined flash file system size and start & end symbols in linker script, and improved flashbdev.c to just use the symbols.
* Fixed file system size of EK-RA6M2.

**Comment by TakeoTakahashi2020** [comment]
@dpgeorge Could you please review again?  If there are somethings to be more improved, please let me know.   Thanks.

**Comment by TakeoTakahashi2020** [comment]
Rebased to the recent code for review.

**Comment by dpgeorge** [comment]
Sorry for not getting to this earlier.

Everything here now looks good!

The only thing I'm wondering is, why do RA4W1 and RA6M1 have different size filesystems even though they have the same total flash (512k)?   Maybe now would be a good time to make those filesystems the same size if that makes sense to do?

**Comment by TakeoTakahashi2020** [comment]
@dpgeorge san,  Thank you for your review.  I agree with your comment and I changed the filesystem size for RA6M1 as same as RA4W1.  Please kindly review again.   Thanks.

**Comment by dpgeorge** [comment]
Thanks for updating.  It looks good.

Rebased and merged in 45a85f5a357f0064388a42627f3c39e811c78780 through 5228f4067da028f0663e1ec2ceda139e07865b9d

**Comment by TakeoTakahashi2020** [comment]
@dpgeorge san, thanks for merging.

**Pull request closed without merging**
