### PR TITLE
tests/multi_net/ssl_data.py: Skip test if SSL module is not available.

### PR DESCRIPTION
**Pull request by iabdalkader**

### CODE REVIEW

**Comment by iabdalkader** [comment]
I see this fix has been committed, closing PR.

**Comment by dpgeorge** [comment]
Yes, done slightly differently in acfc3bbdf804eac7b230e1bba1546c86aec4e201 (part of trying to get more tests running on the stackless/systrace builds).

**Comment by iabdalkader** [comment]
Some of the other tests fail too (some fail on PYBD_SF2) reported in my other PR. And there's another issue with `multi_net/tcp_accept_recv.py`, the linux/errno.h `ENOTCONN` is 107 (so in Python it is 107) but in baremetal/arm-gcc etc.. it's actually `128`. So if you use system errno this test fails, not sure how to fix it.

**Comment by iabdalkader** [comment]
Maybe ?
```python
    except OSError as er:
        print(107 if (er.errno == 128) else er.errno)
```

**Comment by dpgeorge** [comment]
How about: `print(er.errno in (107, 128))`?

**Comment by iabdalkader** [comment]
That will print `true`, I think the test expects `107`

**Comment by iabdalkader** [comment]
No actually you're right, the result is not fixed.

**Comment by iabdalkader** [comment]
Do you want me to send a PR for that ?

**Comment by iabdalkader** [comment]
> , I don't recall seeing any issues with the tcp_accept_recv test

You won't because `stm32` port is using internal error numbers.

https://github.com/micropython/micropython/pull/8678

**Pull request closed without merging**
