### PR TITLE
renesas-ra: Update FSP to the latest v4.4.0 and modify related files.

### PR DESCRIPTION
**Pull request by TakeoTakahashi2020**
FSP has been updated to the latest v4.4.0.
This PR is related with the PR #10943 conversation.
I really appreciate it if you could review it @dpgeorge , @iabdalkader, @mbedNoobNinja.

Changes are as follows:
* Update FSP for renesas-ra to the latest version v4.4.0.
* Update boards and ra directory files to support FSP v4.4.0.
* Add a macro definition file and modify Makefile to avoid compile error.
  FSP v4.4.0 refers to CMSIS V5.4.1, and `__COMPILER_BARRIER()` is used in bsp.
  On the other hand, lib/cmsis is V5.1.0 and the macro is not defined.
  Therefore, compile error happens.
  As the workaround, the macro definition is added.
  If lib/cmsis is updated in the future, this addition can be removed.
*  Add import line to avoid no attribute error on run-tests.py

I have updated as following steps:
* Used `e2 studio 2023-04` + `FSP v4.4.0` that was installed by setup_fsp_v4_4_0_e2s_v2023-04.exe on https://github.com/renesas/fsp/releases/tag/v4.4.0.
* Import previous projects for EK and CLICKER boards. 
* Open `configuration.xml` in the projct and press `Generate Project Content`.
* Replace `boards/EK & CLICKER/ra_cfg/*` and `boards/EK & CLICKER/ra_gen/*` with generated files.
* Update some renesas-ra/ra/*.[ch] to support FSP v4.4.0.
* Prepared boards/compiler_barrier.h and modify Makefile to avoid compile errors.
* Build & test. 
* I needed to modify tools/pyboard.py to avoid `AttributeError: module 'serial' has no attribute 'tools'` error.
* FInally executed tools/codeformat.py for modified files.

### CODE REVIEW

**Comment by iabdalkader** [comment]
Looks good, thanks! I also had to fix the missing compiler barrier when testing v4.0.0.

**Comment by dpgeorge** [comment]
Thanks for doing this @TakeoTakahashi2020 .  

Are all the generated files needed?  @iabdalkader mentioned before that he thinks only the ISR vector code is needed.

**Comment by TakeoTakahashi2020** [comment]
@dpgeorge san,  Thank you for pointing that out.  I will check some more details to see if there are any files that can be deleted.

**Comment by iabdalkader** [comment]
Hi, I tested all the changes (in this PR, on top of the other PR and my USB/board support in #11405) and things seem to work fine, well at least for RA6M5, I will do more testing once everything is merged. Thanks @TakeoTakahashi2020 .

**Comment by TakeoTakahashi2020** [comment]
@iabdalkader san, Thank you very much for the test and I am very happy to see your PR to support Portenta C33.  I am still checking and testing if there are any files that can be deleted.   I need a little more time.

**Comment by TakeoTakahashi2020** [comment]
> Are all the generated files needed? @iabdalkader mentioned before that he thinks only the ISR vector code is needed.

@dpgeorge san, I have finished checks and tests.
Many of the generated files were related to clocks and FSP instances, and it was not possible to remove them on a per-file basis without modifying the files. Replacing was the easiest way to update the FSP.

However, some header files could be removed by editing some c-source files to remove unreferenced instances. This reduces RAM usage to 360 bytes (for RA4M1_CLICKER), 312 bytes (for EK-RA4M1), 468 bytes (for EK-RA4W1), 648 bytes (for EK-RA6M1), 744 bytes (for EK-RA6M2 ) .

Also I have removed the unreferenced board_init.c and board_leds.c from the Makefile. This was already reported in #10943 by @iabdalkader .

**Comment by TakeoTakahashi2020** [comment]
@dpgeorge san, I have recognized that tools/pyboard.py serial import issue had been fixed on https://github.com/micropython/micropython/commit/0264465585ba10e80bb8ade5b3df2979363d53d0.
So I believe my change is not needed fot it.  Please let me know if I should rebase this PR to the latest without my change for pyboard.py.  I am happy to do it.

**Comment by dpgeorge** [comment]
@TakeoTakahashi2020 this PR looks quite good now.  Thanks for removing the unnecessary files.



> So I believe my change is not needed fot it. Please let me know if I should rebase this PR to the latest without my change for pyboard.py. I will be happy to do it.

Yes, if you rebase you can leave out that commit.

And, are you happy to squash the following two commits together:
- renesas-ra: Update boards and ra directory files to support FSP v4.4.0.
- renesas-ra: Remove unreferenced files and instances.
?

**Comment by TakeoTakahashi2020** [comment]
@dpgeorge san, OK, I will rebase this and squash the two.

**Comment by dpgeorge** [comment]
Thanks @TakeoTakahashi2020 !

**Comment by TakeoTakahashi2020** [comment]
Thank you @dpgeorge san.

**Pull request merged**
