### PR TITLE
Allocate iterators on the Python stack when possible

### PR DESCRIPTION
**Pull request by dpgeorge**
This patch was made some time ago as part of the ESA work, to make uPy more deterministic.  It allows to allocate iterators on the stack whenever possible (most of the usual cases).  I think it would be a good addition to the main repo becaues it eliminates (short term) heap allocation for very common operations of `for x in it: ...`

Allows to iterate over the following without allocating on the heap:
- tuple
- list
- string, bytes
- bytearray, array
- dict (not dict.keys, not dict.values, not dict.items)
- set, frozenset

Allows to call the following builtins without using heap memory: all, any, min, max, sum.

The downside is that it uses more stack (4 words temporary space for each iterator, instead of on the heap) and increases code size.  It would be difficult to make this feature a compile time option.

### CODE REVIEW

**Comment by dpgeorge** [comment]
This will require a bit of work to rebase it onto current master, but I wanted to get opinions/feedback before attempting that.

**Comment by stinos** [comment]
Have you perhaps compared execution speed between the two?

**Comment by dpgeorge** [comment]
> Have you perhaps compared execution speed between the two?

No I didn't do that.  Probably a good idea to do.  It could make a difference because allocating on the stack means less runs of the GC.

**Comment by dpgeorge** [comment]
Just to give some technical background, let's consider iterating over a list:
```
lst = [1, 2, 3]
for x in lst:
    print(x)
```
Currently, when this code is executed the for loop will set up the iterator object by asking the `lst` to create an iterator.  This allocates an object on the heap of 4 words size, which holds info about the current position in the list.  The for loop then uses this iterator object to get all the elements.  At the end of the loop the iterator object is garbage and should eventaully be collected.

With the patch the emitted bytecode will reserve 4 words on the Python value stack (which usually lives on the C stack, but can be on the heap if it's large) and passes a pointer to this reserved memory to the `lst` object when it's asked to create an iterator.  If the iterator fits in 4 words (which it does for a list) then those words are used, else it allocates the full iterator from the heap.  The memory for the iterator is reclaimed when the function exits (because then the stack pointer shifts).

**Comment by pfalcon** [comment]
Just reading title/description, it wasn't clear which stack is meant, probably worth spelling it explicitly, like "C stack".

**Comment by pfalcon** [comment]
And quick offtopic answer - while this is definitely cool and useful, I'd say that merging more efficient parser from microbit is more useful/would be higher priority. I wanted to open a ticket for that for a while actually, now I did: https://github.com/micropython/micropython/issues/2417

**Comment by pfalcon** [comment]
> will reserve 4 words on the Python value stack (which usually lives on the C stack, but can be on the heap if it's large)

It's not C stack after all, definitely should be mentioned in the commit message IMHO.

**Comment by pfalcon** [comment]
> If the iterator fits in 4 words (which it does for a list) then those words are used, else it allocates the full iterator from the heap.  The memory for the iterator is reclaimed when the function exits (because then the stack pointer shifts).

Any concerns about usage in generators? (There shouldn't be, but unittest definitely should inlcude cases for this.)

**Comment by blazewicz** [comment]
+1 for bare-metal ports with heap on external memories

Placing iterators on C stack (since such ports can have more internal memory available for C stack VM_MAX_STATE_ON_STACK may have greater value) will surely have substantial impact on performance.

I'm thinking about STM MCU + FSMC, using internal RAM is always much faster than external.

**Comment by dpgeorge** [comment]
> Any concerns about usage in generators?

As far as I can remember, if you use for loops in generators then it'll allocate a larger stack for that generator so the iterator can live there.  Since generator's stacks are always allocated on the heap it should be fine (and should also cut down on framentation in that case).

Since there is interest in this patch I will look at rebasing and providing proper metrics re size, speed and memory usage.

**Comment by VlastimilHovan** [comment]
Hi guys. 

I know this is bit of the topic but I am new to github and dont know how to contact anybody directly. Not sure if it is even possible here. 
Would you be able to help me. Do you know who is the brain behind MU complier for BBC microbit ? I would like to add few functions to the microbit library but dont know how to do it. Can I do it myself or is library integrated to MU complier. Please help if you can. 

Many thanks

**Comment by dpgeorge** [comment]
@VlastimilHovan the repository for the Mu editor is here: https://github.com/mu-editor/mu .  But if you want to add something to the microbit then go here: https://github.com/bbcmicrobit/micropython/

**Comment by VlastimilHovan** [comment]
Thank you very much.


________________________________

**Comment by dpgeorge** [comment]
I rebased this on to the current master.  Changes in code size are:
```
+148 bare-arm
+296 minimal
+232 unix x86-64
+220 stmhal
 +92 esp8266
+192 cc3200
```

Pystone performance is pretty much unchanged (but pystone has only 1 for loop and doesn't really stress this feature).

Timing a simple triple-nested for loop over the same iterator shows that this PR actually decreases performance about 5%, probably due to the 4 extra POP_TOP opcodes per loop (see below).

Things still to address:
 - Bytecode is increased by 4 bytes for every "for" loop that is used, to "pop" the iterator buffer (it's 4x POP_TOP).  Could improve this by adding another bytecode to pop 4 items at once, or adding a second FOR_ITER opcode, or an extra argument to the current FOR_ITER opcode.
 - Would want to increase the VM_MAX_STATE_ON_STACK macro so that more functions can use the C stack for their state, rather than the heap (stack is always a fallback if heap is locked).
 - Write some tests for this new feature.

**Comment by pfalcon** [comment]
With #2716 in mind, how far we're from merging this?

> Bytecode is increased by 4 bytes for every "for" loop that is used, to "pop" the iterator buffer (it's 4x POP_TOP). Could improve this by adding another bytecode to pop 4 items at once, or adding a second FOR_ITER opcode, or an extra argument to the current FOR_ITER opcode.

Doing something of that makes sense. Can't say which is better, would leave that to you.

> Would want to increase the VM_MAX_STATE_ON_STACK macro so that more functions can use the C stack for their state, rather than the heap (stack is always a fallback if heap is locked).

It's already 11 words, which isn't little. Probably makes sense to make it configurable per-port.

> Write some tests for this new feature.

Do you mean just Python unit tests, with various combinations of loops?

**Comment by dpgeorge** [comment]
> With #2716 in mind, how far we're from merging this?

There's still some testing and further profiling to do.  For example, I just found that it will always allocate memory unnecessarily when doing a `yield from`.

> It's already 11 words, which isn't little. Probably makes sense to make it configurable per-port.

Yes, makes sense.

> Do you mean just Python unit tests, with various combinations of loops?

Yes, unit tests for all the cases where one can do something without allocating on the heap.  But these can come later.

**Comment by dpgeorge** [comment]
I have done a lot of extra work on this, trying to optimise it further.  The main improvement has been that only 3 extra slots on the Python stack are needed to store the iterator, compared with 4 from the earlier implementation (basically it reuses the existing single slot that stored the pointer to the iterator, so instead of 1+4 slots in now uses just 4).

Also, list/set/dict comprehensions now benefit from having iterators on the Python stack.

I have added a test for iterating with the heap locked.

Impact of this entire PR:
- heap usage by bytecode: only in a very few cases will size of bytecode increase, notably when you break/continue within a for loop (and then only by 3 bytes).
- RAM usage by running functions: the Python stack of functions that have a for loop is increased by 3 words.  This is sometimes allocated on the stack, other times on the heap.
- stack usage by C functions: some C functions now use 4 extra words to store the temporary iterator.
- heap usage: many for loops no longer need to allocate the iterator on the heap (this is the big benefit of the patch)
- Performance: not yet measured
- Code size is increased:
```
bare-arm: +212
minimal:  +380
unix x64: +512
stmhal:   +312
esp8266:  +276
cc3200:   +256
```

**Comment by dpgeorge** [comment]
Further updates on this patch:
- I de-optimised some of the uses of iterators so they allocate on the heap instead of C stack, which reduces code size a little.  All the cases were those that anyway allocated on the heap for some other reason, for example constructors, dict.fromkeys().
- Added some tests for other things that can now be done without the heap: containment (eg `x in y`) and unpacking (eg `a, b, c = lst`).  IMO being able to do these things without the heap is a big win.
- Did some simple speed tests: pystone performance on pyboard is down by about 1.1% (don't know why) and the case of a simple triple-nested for loop is improved by about 3.3% on pyboard.

Increase in code size for the current set of patches in this PR is:
```
bare-arm: +200
minimal:  +364
unix x64: +464
stmhal:   +284
esp8266:  +254
cc3200:   +240
```
At this point I'm inclined to merge this PR.  The amount of performance lost is small, and the increase in code size is, I think, worth it for the things you can now do without the heap.

**Comment by stinos** [comment]
Can you explain what is the main incentive of not needing the heap here: being able to do things in interrupts or just avoid going via the heap as it (usually?) slower for small allocations? Or both or something else? Just trying to understand exactly who/what benefits from this. In any case I assume you have good reasons to spend considerable amount of time on this so +1

**Comment by dpgeorge** [comment]
> Can you explain what is the main incentive of not needing the heap here: being able to do things in interrupts or just avoid going via the heap as it (usually?) slower for small allocations? Or both or something else?

The original reason for implementing this was avoid using the heap so that execution is more deterministic.  If some operation uses the heap and is executed repeatedly, then even if it succeeds the first time there's no guarantee it'll succeed every time.  This is because the heap may have a different layout on subsequent iterations (eg due to fragmentation), and the allocation could fail on latter runs.

On the other hand, if an operation uses only the stack and it works once then (with some small caveats) it's guaranteed to work every time.

Using the stack instead of the heap also helps with determinism it *time*: allocations on the stack will happen the same way every time and so take (sometimes exactly) the same number of CPU cycles.

Aside from determinism the other general benefits of not using the heap are:
- faster execution at the point of allocation, since you don't need to touch the heap, search for free mem, do a GC if nothing found
- because you're not using the heap you have reduced fragmentation of the heap, less heap pressure, smaller number of garbage collections
- ability to use more of the language without needed the heap; eg you can turn the heap off entirely after you loaded your program; also can do more stuff in a hard interrupt

> Just trying to understand exactly who/what benefits from this.

It hopefully benefits everyone who tries to run uPy with a small heap and wants it to run reliably over a long period of time.

**Comment by stinos** [comment]
Thanks, that was an informative read.

**Comment by pfalcon** [comment]
+1, please merge. Thanks for measuring code size increase across ports - I always call to stay conservative in (mostly enabling) other things to give green way to such optimizations which are more important and can't be made conditional.

**Comment by dpgeorge** [comment]
Merged.  Awesome!

**Pull request merged**
