### PR TITLE
ESP32: new/reworked GPIO hold functionality

### LINKED ISSUE #8283: ESP32: `Pin.PULL_HOLD` does not do what the quickref says it does
The ESP32 quickref says this about `PULL_HOLD` in [Pins and GPIO](http://docs.micropython.org/en/latest/esp32/quickref.html#pins-and-gpio):

> - The pull value of some pins can be set to `Pin.PULL_HOLD` to reduce power consumption during deepsleep.

and this in [Deep-sleep Mode](http://docs.micropython.org/en/latest/esp32/quickref.html#deep-sleep-mode):

> - There may be some leakage current flowing through enabled internal pullups. To further reduce power consumption it is possible to disable the internal pullups:
> 
> ```
> p1 = Pin(4, Pin.IN, Pin.PULL_HOLD)
> ```

Looking at the code that implements this I see:

```C
        if (mode & GPIO_PULL_HOLD) {
            gpio_hold_en(self->id);
        } else if (GPIO_IS_VALID_OUTPUT_GPIO(self->id)) {
            gpio_hold_dis(self->id);
        }
```

but the [IDF documentation for `gpio_hold_en`](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/gpio.html#_CPPv412gpio_hold_en10gpio_num_t) says:

> Enable gpio pad hold function.
> 
> The gpio pad hold function works in both input and output modes, but must be output-capable gpios. If pad hold enabled: in output mode: the output level of the pad will be force locked and can not be changed. in input mode: the input value read will not change, regardless the changes of input signal.
> 
> The state of digital gpio cannot be held during Deep-sleep, and it will resume the hold function when the chip wakes up from Deep-sleep.

I've verified this locking behaviour in an actual device for outputs using `pull=Pin.PULL_HOLD`: subsequent calls to `.value(0|1)` do nothing. Curiously, I do **not** see this locking behaviour for input-configured pins: I can change the applied voltage and `.value()` will return either 0 or 1 – I need to do some more digging on this.

I've also confirmed that the output drivers and input pull-ups/-downs disconnect when going into deep-sleep, leaving the GPIO floating whether the pin is held or not. On wake, a held pin will still be locked but the drive and pull status is **not** restored so the pin remains floating. I don't really understand the purpose of this floating-but-held-on-wake behaviour.

However, the IDF docs go on to say:

>  If the digital gpio also needs to be held during Deep-sleep, `gpio_deep_sleep_hold_en` should also be called.

which is the behaviour that I'm *actually* interested in. So I added a new `gpio_deep_sleep_hold(True|False)` function to the `esp32` module that calls this, and then confirmed that:

```python
from machine import Pin, deepsleep
from esp32 import gpio_deep_sleep_hold

Pin(22, Pin.OUT, value=1, pull=Pin.PULL_HOLD)
gpio_deep_sleep_hold(True)
deepsleep(5000)
```

will maintain the drive value on the pin when the chip enters deep-sleep and on wake. This also works for pull-ups and -downs, a la:

```python
from machine import Pin, deepsleep
from esp32 import gpio_deep_sleep_hold

Pin(22, Pin.IN, pull=Pin.PULL_HOLD|Pin.PULL_UP)
gpio_deep_sleep_hold(True)
deepsleep(5000)
```

So, in short:

- `gpio_hold_en()` only works on output-capable pins so the test in the code seems to be in the wrong place;
- the `PULL_HOLD` behaviour documented with regard to pull-ups in deep-sleep seems to already be the default;
- `PULL_HOLD` actually results in output locking behaviour that is not documented;
- its only current connection to deep-sleep is that the GPIO will still be locked on wake;
- *actually* retaining drive/pull status during deep-sleep (/wake) requires use of a function that is not currently exposed;
- if one *does* enable hold-during-deep-sleep then the `PULL_HOLD` behaviour is actually the *reverse* of that documented in the quickref.

What would be the best changes here? Since `PULL_HOLD` doesn't currently do what it says it does, I'm curious as to whether anyone is actually using it.

I would have thought that this functionality is better moved to either some new `hold=True|False` keyword parameter or new `IN_HOLD`|`OUT_HOLD` pin modes?

Regardless, I'd definitely like to add a mechanism for calling `gpio_deep_sleep_hold_en()` to the ESP32 port. Honestly, the hold behaviour seems to be of such limited value without this that I wonder if it should just be enabled by default?

### PR DESCRIPTION
**Pull request by jonathanhogg**
The current `pull=Pin.PULL_HOLD` argument doesn't make a lot of sense in the context of what it actually does vs what the ESP32 quickref document says it does.

This patch proposes dumping this and adding a new `hold=True|False` keyword argument to `Pin()`/`Pin.init()`. Setting this to `True` will cause the ESP32 to lock the configuration of the pin – including direction, output value, drive strength, pull-up/-down – such that it can't be accidentally changed and will be retained through a watchdog or internal reset.

In addition, a new `gpio_deep_sleep_hold(True|False)` function in the `esp32` module allows this behaviour to be extended to entering and waking from deep-sleep.

~~Support for configuring output drive strength is also added through the standard `drive` keyword argument and constants:~~

- ~~`Pin.DRIVE_WEAK`~~
- ~~`Pin.DRIVE_LOW`~~
- ~~`Pin.DRIVE_MED` (default pin drive strength)~~
- ~~`Pin.DRIVE_HIGH`~~

**Edit: see comment below about moving of drive strength commits**

Will write documentation if this looks like being accepted.

I'm also happy to put back in some kind of legacy compatibility for `pull=Pin.PULL_HOLD` if there's concern that this is being used in the wild for what it actually does (rather than what it's documented as doing).

Fixes #8283

### CODE REVIEW

**Comment by jonathanhogg** [comment]
Note, that if the `hold` keyword argument is given *at all* then my implementation disables hold, makes any config changes and *then* applies the hold if `hold=True`. This allows you to do things like:

```python
pin = Pin(NUMBER, Pin.OUT, value=1, hold=True)
...
pin.init(value=0, hold=True)
```

and have these always work – including the original config working on a watchdog/internal reset. Without this, one would have to explicitly disable the hold before doing anything else, i.e.:

```python
pin = Pin(NUMBER, hold=False)
pin.init(Pin.OUT, value=1, hold=True)
...
pin.init(hold=False)
pin.init(value=0, hold=True)
```

which both looks clunky to me and feels like it'd be forgotten and result in subtle bugs creeping in.

I also fear crazy race conditions like a MicroPython task switch occurring between the line releasing the hold and the one changing the config and reapplying the hold, then that other task triggering a reset. This way isn't foolproof – it doesn't use a critical section – but it feels safer.

However, it still means that casual use of something like:

```python
Pin(NUMBER, Pin.IN)
```

or:

```python
pin.value(0)
```

on a held pin would be (silently) ignored.

I am basically saying that *if you use the `hold` keyword, I will assume that you really meant this config to apply*.

**Comment by jonathanhogg** [comment]
> I'm also happy to put back in some kind of legacy compatibility for pull=Pin.PULL_HOLD if there's concern that this is being used in the wild for what it actually does (rather than what it's documented as doing).

Actually, I thought a bit more about this but I can't see a clean way of adding this compatibility behaviour that doesn't defeat the new `hold` keyword.

Making `pull=Pin.PULL_HOLD` the same as `hold=True` is easy, but the only way to currently disable the hold is to set `pull` to some other value, and having that imply `hold=False` is a bit messier. It would mean that:

```python
Pin(NUMBER, Pin.IN, pull=Pin.PULL_UP)
```

would reconfigure a held pin, but:

```python
Pin(NUMBER, Pin.IN)
```

would be ignored.

**Comment by jonathanhogg** [comment]
> So there is no need to call `gpio_hold_dis()` in the init helper before configuring the pin; we can do so at the end just before (re-)enabling the hold.

Ah! Good spot. I hadn't realised that the docs were implying this behaviour, but have been able to confirm it in my hardware. So I've simplified my code to move the disable back to the end. I'm still doing it even if hold is then to be immediately re-enabled so that any config changes will be latched.

> It would probably also be very nice to add an extra method to allow setting the hold after the Pin is initialized, which would be more explicit than having to re-init the entire pin

The `Pin.init()` method doesn't reinitialise anything that you don't specify in the arguments so `pin.init(hold=True)` is equivalent to your `pin.hold(False); pin.hold(True)`.

I thought about adding a method, but felt that being able to do everything in one hit felt more useful. One could obviously add a method anyway the same as `pin.value(level)` is (almost) equivalent to `pin.init(value=level)`.

> As for `PULL_HOLD`, while I agree that removing the constant would be cleaner than just changing its behaviour, since at least we'll get a clear error message instead of silently changed behaviour, a quick search across all of GitHub shows `PULL_HOLD` being used, [even in this repository](https://github.com/micropython/micropython/blob/605b74f390e1ce9acdbca32d0b3215d37b96852e/ports/esp32/boards/UM_TINYPICO/modules/tinypico.py).

Yeah, looking at that code I can't see what purpose the use of `PULL_HOLD` is serving. Unless I'm missing something, it looks like it has been added based on the current documentation in the belief that it will affect deep-sleep current draw.

I'm gonna have a hunt around and see if I can find anyone using `PULL_HOLD` for its actual pad holding behaviour…

**Comment by DvdGiessen** [comment]
> The `Pin.init()` method doesn't reinitialise anything that you don't specify in the arguments so `pin.init(hold=True)` is equivalent to your `pin.hold(False); pin.hold(True)`.

My bad, I didn't read the read the code before commenting and blindly assumed there'd be a downside.

> I thought about adding a method, but felt that being able to do everything in one hit felt more useful. One could obviously add a method anyway the same as `pin.value(level)` is (almost) equivalent to `pin.init(value=level)`.

A better reason might be parity with the `.mode()` and `.pull()` methods. Which I just noticed are not implemented in the esp32 port either, currently, but they do exist [in other ports](https://docs.micropython.org/en/latest/library/machine.Pin.html). So perhaps that's something for a separate change.

**Comment by jonathanhogg** [comment]
I've pulled the drive strength commits out of here into #8313 in the hope that they can be accepted faster on their own.

**Comment by jonathanhogg** [comment]
I've put the `PULL_HOLD` constant back in so that existing code won't break. It will behave exactly the same as using `pull=None`, which is sufficient to disable RTC-pin pull resistors going into deep-sleep (see discussion in linked issue). I've also updated all of the associated documents.

I've tried to do all of this as separate commits that can be cherry-picked – e.g., the new power-saving documentation in 41c86f78b38839f2b24fe9cbf77ded19f500419b stands alone even if nothing else is accepted. However, my documentation of `gpio_deep_sleep_hold()` assumes that the pin `hold` keyword is there.

**Comment by jonathanhogg** [comment]
Rebased this on top of #8313 as the merge conflicts in my local repo were driving me crazy.

**Comment by jonathanhogg** [comment]
I'm now using this in the wild for a project that requires careful control over pins in deep-sleep to correctly disable external hardware and unnecessary avoid power drain.

**Comment by dpgeorge** [comment]
Please rebase on latest master, to pick up the merge of the pin drive strength commits.

**Comment by dpgeorge** [comment]
> I've put the `PULL_HOLD` constant back in so that existing code won't break. It will behave exactly the same as using `pull=None`, which is sufficient to disable RTC-pin pull resistors going into deep-sleep (see discussion in linked issue). I've also updated all of the associated documents.

If `PULL_HOLD` doesn't work as expected (as it was previously documented in the quickref before this PR) then IMO we should just remove it completely.  Then anyone using it will see their code break very visibly and they can investigate and fix it properly.  If we leave `PULL_HOLD` and subtly change its behaviour then that is worse.

**Comment by jonathanhogg** [comment]
Quick search for `PULL_HOLD` on the repo to check for other uses:

- `PULL_HOLD` is actually listed in the `machine.Pin` docs, though no behaviour is given for it.
- The `mimxrt` port uses the `PULL_HOLD` constant. On that port it is used to enable the pad "keeper". As far as I can make out this is a mechanism for disabling the output driver while keeping a weak pull up/down to hold the output level. It seems to be a power-reduction device allowing the pad to be connected to a capacitive load (including a long wire I guess) that requires a fair bit of current when transitioning level, but none after that to "keep" it. `PULL_HOLD` makes some degree of sense here as configuration of the pad keepers is bound up in the pull configuration.
- Also, obviously, my patch here will break the `tinypico.py` module. Should I add a fix for that?

**Comment by dpgeorge** [comment]
Thanks @jonathanhogg for all the effort on this, with nice clean commits and documentation.

I have re-read through this PR and issue #8283, and also looked again at the IDF, and I think your reasoning and implementation here are correct.  The API here exposes the IDF functionality in a clean and orthogonal manner, you can enable and disable hold on the GPIO, and enable and disable the hold-during-deep-sleep.

Merged in 5887dfeea6a4899e8f30ac1435159d760a985642 through 3b9de192be8177abd07c18cf58468939c4c5fd5d

**Pull request closed without merging**
