### PR TITLE
Remove unreachable code related to relative imports

### PR DESCRIPTION
**Pull request by dpgeorge**
Unreachable code is removed and a test is added for calling `__import__` directly.

@pfalcon FYI

### CODE REVIEW

**Comment by pfalcon** [comment]
As you saw, there's whole big comment describing the situation. It's easier to imagine that while loop misses a condition for this_name becoming empty as a result of chop than that the code is not needed.

**Comment by dpgeorge** [comment]
Going back to the commit that made this code unreachable 9e6c82960e38963e4392ad3180811d10657519b3, before said commit there were no tests for the now-unreachable code.

I can retroactively write tests that excercise both paths in the now-unreachable code.  They are the following:
```
$ cat pkg/__init__.py
from . import xx
$ cat pkg/xx.py
print('in xx')
```
That will test the true part of the if.  Then:
```
$ cat pkg/__init__.py
from .. import xx
```
That will test the else part of the if.

Both of these tests pass in the latest version of the code, ie they don't need the now-unreachable code.

The comment in the now-unreachable code says "This condition happens when package's __init__.py does something like "import .submod" ".  Well, you can't do "import .a", so I assume the comment means "from . import submod".  Then that's the case that is talked about above and which is correctly handled in latest master.

Digging deeper, the comment also says "If the module's name does not contain any package information (e.g. it is set to `__main__`)".  This case can be triggered by doing "from . import submod" from within a script that was *not* imported, ie it's not part of a package (or it's executed from the REPL).  This case is broken in uPy due to the trick to let modules be run by the -m command line switch on the unix port.

**Comment by pfalcon** [comment]
> Well, you can't do "import .a"

Perhaps. Did you try testcases from https://www.python.org/dev/peps/pep-0328/#guido-s-decision , some of which are no longer valid, and after that possibly more?

~~~
# from ...sys import path

>>> import package.subpackage1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "package/subpackage1/__init__.py", line 1, in <module>
ImportError: no module named '.sys'
~~~

**Comment by dpgeorge** [comment]
Ok, I tested all the relative import cases in PEP0328 referenced above and updated this PR so they all pass.  Imports beyond the top-level are no longer supported (give an error) in CPython, and uPy now follows CPython behaviour.  In particular `from ...sys import path` will now fail correctly in uPy with a ValueError.

So this PR should be good to merge.

**Comment by pfalcon** [comment]
> Imports beyond the top-level are no longer supported (give an error) in CPython

Any more specific details about "no longer"?

> So this PR should be good to merge.

Sounds good. Strangely, the minimal code size increased with this patch.

**Comment by dpgeorge** [comment]
> Any more specific details about "no longer"?

According to PEP328, when it was written and implemented the "...sys" thing would work.  But now, in v3.6.1 at least, it seems to raise a ValueError.  I couldn't find a PEP that discussed this change, so it remains a mystery.

> Strangely, the minimal code size increased with this patch.

I think the compiler was smart enough to eliminate the dead/unreachable code so removing it by hand in this patch didn't change anything.  But this patch also added another minor check and that would increase the code size in minimal.

**Pull request merged**
