### PR TITLE
esp32/machine_hw_spi: Release GIL during transfers. 

### LINKED ISSUE #7662: ESP32: long hardware SPI transfers unnecessarily holding up other threads
The ESP32 hardware SPI implementation spends most of its time just waiting for the hardware to indicate that a transfer is complete. When doing a lot of large transfers (as I do), this means the processor spends a lot of time idle.

I tried shoving the write loop onto a thread but discovered that it makes no difference. Digging into my code (since this bit is my fault now) I realised that I'm not releasing the GIL when waiting on transactions. Adding `MP_THREAD_GIL_EXIT`/`MP_THREAD_GIL_ENTER` calls around the waits improves my frame rate by an extraordinary 3x, since my code can now get on with other stuff while the SPI transfers are done.

### PR DESCRIPTION
**Pull request by jonathanhogg**
Release the GIL while waiting for SPI transfers to  complete to allow other threads to make progress. Fixes #7662.

### CODE REVIEW

**Comment by jonathanhogg** [comment]
I've somewhat arbitrarily chosen the 512 bits (64 bytes) threshold. At the default 500kbps that's about 1ms, which seemed like a long time to be doing nothing.

**Comment by jimmo** [comment]
Seems like a good change, thanks @jonathanhogg 

I wonder if the threshold is necessary at all? Just always unconditionally release the GIL during any transfer? I don't think it will make much difference but it will simplify the code.

**Comment by jonathanhogg** [comment]
Yeah, I did this first for testing, @jimmo, but then I worried that the regular use case for SPI is normally very short command transfers to peripherals and I was perturbing that case without obvious benefit to those users. It is much simpler without it though, so I'm happy to take out if that seems like the best idea.

**Comment by jimmo** [comment]
In https://github.com/micropython/micropython/issues/5344#issuecomment-558865337 I think I convinced myself that releasing a mutex on FreeRTOS doesn't actually cause an immediate context switch until the end of the time slice. (Although I haven't looked into this extensively).
So my guess is that releasing the GIL for short transactions will basically have no effect. Would be good to confirm this for sure.

**Comment by jonathanhogg** [comment]
OK, I've gone back to my original, simpler change.

**Comment by dpgeorge** [comment]
Thanks.  Merged in 5b655665ab068c4ee7de7891ae2d3cb7ed630512

**Pull request closed without merging**
