### PR TITLE
unix: Clean build directories and artifacts of all build variants.

### PR DESCRIPTION
**Pull request by Jongy**

### CODE REVIEW

**Comment by jimmo** [comment]
I don't think that `make VARIANT=x` should delete the build directory or output of other variants. It definitely doesn't do this on other ports.

But I agree the current behavior isn't quite right because of the way it puts the output in the current directory. Perhaps:

 `CLEAN_EXTRA = $(PROG) $(PROG).map`

would be sufficient?

**Comment by Jongy** [comment]
`VARIANT` and `PROG` come from invoking the Makefile with `minimal`/`nanbox` etc. So e.g `make -C ports/unix minimal clean` won't invoke `clean` with `minimal`'s setting, but invoke `minimal` and then `clean`.

`VARIANT` must be given manually for this to work - `make clean VARIANT=minimal` which is weird because you don't use `VARIANT` when you build. And that's why I preferred a simple `make clean` to work. The other ports specify variants with Make variables instead of targets, perhaps `unix` should, too?

Anyway I'm just annoyed there's no way to clean the build directory of variants, besides running `rm -r` manually... :(

**Comment by jimmo** [comment]
Thanks for the explanation.

The intent was for this to work exactly like the other ports where you pretty much always specify `BOARD=` on the make command line. Or, more conveniently, have a custom `makefile` (or `GNUmakefile`) that sets the `BOARD` variable to whichever board/variant you're currently working with.

I left the old targets (with some hesitation) in the `Makefile` for backwards compatibility (i.e. so `make minimal` would still work), although it is confusing that there's no good `clean` option, so I would be keen to remove them. (This was part of why I added variants for the Unix port, the way the non-default builds worked was confusing).

But I agree -- sometimes you just want to get rid of all build artifacts from all boards/variants. I need this so rarely that `rm -rf build-* micropython*` is fine, but perhaps a `clean_all` target would be useful (in `mkrules.mk` so it works on all ports).

**Comment by dlech** [comment]
Would it make sense to add `clean-nanobox` and `clean-minimal` targets to clean specific targets?

**Comment by Jongy** [comment]
I thought about it a bit more. I think it's better with `VARIANT=`, also when building. (So @jimmo your note about the old targets makes sense into it). `clean-minimal` etc doesn't follow the Make convention of "just take the command line you used to build and add `clean`". That's how I expect it to work, at least :)

About a `clean_all` target, then again since I think `clean` targets should be named a plain `clean`, perhaps a Makefile in the root directory would do (and that Makefile will define `clean` to `for p in ./ports/* ; do make -C $p clean; done`)

**Comment by Jongy** [comment]
Well, it appears that no extra work needs to be done. `make VARIANT=minimal clean` already does everything that's necessary :)

It's just confusing since the existing of extra targets imply you should be using them, but to clean you have to use `VARIANT`. So perhaps we should remove the old targets.

**Comment by dpgeorge** [comment]
> So perhaps we should remove the old targets.

The new unix build system/Makefile works pretty well so I'm happy to remove the old targets, to eliminate confusion (and force people to use the new system...).

**Comment by dpgeorge** [comment]
> So perhaps we should remove the old targets.

See #5635

**Pull request closed without merging**
