### PR TITLE
ports/esp32: Added new UM boards.

### PR DESCRIPTION
**Pull request by UnexpectedMaker**
- Added 2 new UM boards: OMGS3 and RGB Touch Mini
- Fixed NanoS3 deploy info.

### CODE REVIEW

**Comment by mattytrentini** [comment]
Ruff format is complaining about the use of tabs, which should be converted to spaces. But otherwise, it looks good to me. 😄

**Comment by UnexpectedMaker** [comment]
> Ruff format is complaining about the use of tabs, which should be converted to spaces. But otherwise, it looks good to me. 😄

Thanks - Ok, converted the script to spaces... let's see what it fails on now ;)

**Comment by Gadgetoid** [comment]
You should be able to `git rebase -i HEAD~4` and "squash" all of your linting fixes into the original commit. No need to add separate commits.

You can also `git commit --amend` to edit the last commit, and push with `--force` to rewrite your remote with basic fixes like this. Then you only need to format *one* commit message!

**Comment by UnexpectedMaker** [comment]
> You should be able to `git rebase -i HEAD~4` and "squash" all of your linting fixes into the original commit. No need to add separate commits.
> 
> You can also `git commit --amend` to edit the last commit, and push with `--force` to rewrite your remote with basic fixes like this. Then you only need to format _one_ commit message!
> 
> EDIT:
> 
> For example `git rebase -i HEAD~4` and:
> 
> ```
> pick c94eb7420 ports/esp32: Added new UM boards.                                 
> squash 062ec7258 Fixed some github check issues.                                 
> squash 728afea4c Convert some TABS to spaces                                     
> squash 909616271 Convert some single quotes to dbl quotes.  
> ```
> 
> Followed by cleaning up the commit message.
> 
> Results in one clean commit: [pimoroni@62f1503](https://github.com/pimoroni/micropython/commit/62f1503415c3412269b02641220e160f02e41984)
> 
> Commits for linting fixes are unnecessary noise that _someone_ will have to fix, better the PR-author than the stretched-thin maintainers.
> 
> Forgive the intrusion but I sensed some frustration in #15823!

Hey, thanks for your post - Interactive rebasing is a little beyond my git skills, but giving it a go, and hoping for the best :)

Yes, some ongoing frustration with the rules and previous vagueness of the cryptic fails in the CI tests. Some things have been improved over time, but some I just don't agree with, like the rules around commit message naming.

**Comment by Gadgetoid** [comment]
> but some I just don't agree with, like the rules around commit message naming.

You'll come 'round eventually! If you ever have to chase down a bug and bisect a repository this big and complex you'll be singing the praises of a little consistency 😆 

Do hit me up if you ever need a hand!

**Review by dpgeorge — APPROVED** [review]

**Comment by UnexpectedMaker** [comment]
Thank you!

**Comment by dpgeorge** [comment]
@UnexpectedMaker it looks like `UM_RGBTOUCH_MINI` doesn't compile.  Can you please investigate that?

**Comment by UnexpectedMaker** [comment]
> @UnexpectedMaker it looks like `UM_RGBTOUCH_MINI` doesn't compile. Can you please investigate that?

It definitely compiles, as I am currently hosting the firmware in my rgbtouch repo.

```
MPY: soft reboot
MicroPython v1.24.0-preview.309.gf1bdac375.dirty on 2024-09-12; RGB Touch Mini with ESP32-S3-PICO-1-N8R2
Type "help()" for more information.
>>> 
```

Built with:
```
idf.py --version
ESP-IDF v5.2.2-388-g021c03c9f2
```

What IDF version and what error are you getting?

**Comment by UnexpectedMaker** [comment]
I just built it again here and it compiled fine with no errors, so looks like it's IDF version specific?

**Comment by dpgeorge** [comment]
I'm building with IDF v5.2.2.  The error is:
```
freeze error executing "micropython/ports/esp32/boards/UM_RGBTOUCH_MINI/manifest.py": Error in manifest file: micropython/ports/esp32/boards/UM_RGBTOUCH_MINI/manifest.py: [Errno 2] No such file or directory: 'micropython/ports/esp32/boards/UM_RGBTOUCH_MINI/modules'

```

**Comment by UnexpectedMaker** [comment]
Hmm, so because the modules folder is empty, git doesn't send it. Nice.

It's in my local folder, so compiles fine here. The folder wont be empty in the future, so I didn't want to remove the framework using it.

I'll get this sorted right now, thanks.

**Comment by UnexpectedMaker** [comment]
Ok, I fixed it, but now the PR is merged, I can't add my fix to it?
I have to create a new PR?

**Comment by UnexpectedMaker** [comment]
Ok, sorted it out... this is fixed in https://github.com/micropython/micropython/pull/15880

Cheers :)

**Pull request merged**
