### PR TITLE
extend carrier frequency into RMT class

### PR DESCRIPTION
**Pull request by JonRob812**
The esp32 has hardware for the carrier freq. This allows micropython to use it! envoke with 
`r = esp32.RMT(0, pin=Pin(2), clock_div=80, carrier_en=True, carrier_duty_percent=50, carrier_freq_hz=38000)`

these three keyword args added `carrier_en=True, carrier_duty_percent=50, carrier_freq_hz=38000`

### CODE REVIEW

**Comment by tve** [comment]
docs?

**Comment by JonRob812** [comment]
I need to work on this more

**Comment by robert-hh** [comment]
Just a note: you may omit the carrier_en keyword, if you allow for carrier_freq=None for specifying, that no carrier is used.

**Comment by JonRob812** [comment]
https://github.com/micropython/micropython/pull/6127 is updated pull request

**Pull request closed without merging**
