### PR TITLE
stm32/usb: Restructured initialisation to support any mix of configurations

### PR DESCRIPTION
**Pull request by andrewleech**
This stm32 port change allows an arbitrary number of USB CDC ports at compile time with new optional 'mpconfigboard.h' entry: 
```
#define MICROPY_HW_USB_NUM_CDC         (2)
```
It also provides at-boot configuration of any combination of 0 to `MICROPY_HW_USB_NUM_CDC` com ports on their own or with a HID and / or MSC interface. 
HID has been tested in the default mouse mode simultaneously with mass storage and vcp port.

Repl access can be (simultaneously) enabled/disabled on any CDC, with it enabled on just the first one by default.

This changeset has been finished and tested on F429I-DISCO though it started on an OPENMV STM32F765 board.
It has been used on a Windows 10 PC with no driver issues present.

This is my first time working on the micropython codebase so I've probably missed some conventions or restrictions, please don't hold back with any issues in my changeset.

I realise this replaces a decent chunk of 47ecbbbecbad117820e1c37282e7e61528e5d969 and related commits. I initially developed this against the OpenMV fork thinking it was much closer to mainline than it was, so unfortunately I ended up duplicating effort. Hopefully this is seen as useful enough enhancements to take on.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution!  It's indeed a pretty nice feature to add, but...

> I realise this replaces a decent chunk of 47ecbbb and related commits.

Yes it does.  I added support for dual VCP very recently, and when I did it I didn't consider that more than 2 VCP's was worth supporting because 1) it added a lot of extra complexity to the code; 2) the MCUs don't have enough endpoints / TX fifo to support more than a few VCPs (depending on the particular MCU).  So I just left it as 1 or 2 VCPs max, selectable at compile time.

> HID has been tested in the default mouse mode simultaneously with mass storage and vcp port.

That's a cool new feature!

> Hopefully this is seen as useful enough enhancements to take on.

It would be good to have the features added in this PR.  But at the moment the main issues are:

1. Number of lines of code changed by this PR is large (+741 -908).  This in itself is not bad, the problem is that it's hard to review and track any bugs that might have crept in with a large change set.

2. Code size of the firmware is greatly increased even for boards that don't use multiple VCPs.  There's about an extra 800 bytes added to code of the PYBv1.0 board (and 8 bytes of data and 32 bytes of BSS, not such an issue).  Would be nice to reduce this down, might be possible by using `memcpy` in 
`cdc_descriptor()` to copy in the default values to the descriptor, then just update the dynamic entries using explicit C statements.

3. I'm not sure that USB HS mode still works after this PR because it changes how the max packet and polling interval are configured for CDC.  AFAIK, these values must be configured during enumeration, after the speed of the device is selected, because different speeds (FS vs HS) require different values, and you don't know the speed in the `USBD_SelectMode()` function (where this PR sets these values).

It's probably a fair amount of effort to address these points (especially the first 2) and I can understand @andrewleech if you don't have the time/inclination to do it.  I myself wouldn't be able to work on this in the near future.

**Comment by andrewleech** [comment]
Thanks for the detailed feedback!

I had worried about compile size bloat a few times but must confess I didn't do a before and after build to check.

I do have a bad habit of doing more and more in the one commit, with it ending up getting quite large, sorry. There are a few things in here that probably should have been separate features, it's hard when they depend on other things though.

I was not aware of the HS / enumeration timing issue either, thanks for the heads up.

I will do more work on this, possibly through splitting it up. However I've been derailed onto a related project for the next week or two, so it might be a little while.
At the very least I'll ensure the code bloat issue is addressed before re-raising this.

Cheers,
Andrew

**Comment by dpgeorge** [comment]
Most of the changes here are superseded by 0c29502ad995cfacc3b11f26a135707a06b8c27d

@andrewleech shall we close this PR?  It'd be pretty difficult to rebase it now on top of master.

**Comment by andrewleech** [comment]
Ah yes, absolutely. 

If/when we move towards an even more dynamic method of configuring USB descriptors it certainly won't look much this anymore!

**Pull request closed without merging**
