### PR TITLE
Add ESP32 port

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR merges the development of the ESP32 port of MicroPython into this main repository.  The ESP32 port has been, for its initial stages, separately developed over the past year in the repository found at https://github.com/micropython/micropython-esp32 .  In that time the port has matured enough and gained enough interest that I consider it ready to be pulled into this repository and for work on the port to continue here.

The plan is for the original repository to remain for historical purposes, and the only activity there will be to discuss and close existing issues.

Not all of the git history of the initial development of the ESP32 port has been kept in the PR here.  There were roughly 250 commits and many of the early ones were back-and-forth commits to get things working.  The first commit in this PR contains the first 216 original commits squashed together, with a large comment detailing who commited what.  The main reason to squash at that point was because it was just after the code was moved from the directory esp32/ to the directory ports/esp32/.  Keeping commits earlier than that would have resulting in a much messier PR.  In the squashed commit I've aimed (in the commit message there) to give proper credit to those who contributed.  If full traceability of this code is needed then one can look through the original repository.

Comments are welcome!  In particular @nickzoic @MrSurly I'd appreciate if you could comment on the way this merge is constructed, if you think it's the right way to do it or not.  Thanks!

### CODE REVIEW

**Comment by hoihu** [comment]
excellent news! 👍

Looking forward to the merge. Thanks to all the contributors for their hard work on this port.

**Comment by MrSurly** [comment]
Yay!

**Comment by MrSurly** [comment]
What about current active PRs?  Some of them have been open a _long_ time  (\*cough\* deepsleep \*cough\*), and if ESP32 marches forward in a different repo, synchronization can become difficult.  Will mainline ESP32 changes be merged back into micropython-esp32 until outstanding PRs/ issues are resolved?

**Comment by dpgeorge** [comment]
> What about current active PRs? ... Will mainline ESP32 changes be merged back into micropython-esp32 until outstanding PRs/ issues are resolved?

I'd rather shift all code development to this repo, and freeze micropython-esp32, if possible.  That said, it's not too difficult to just mirror all commits made here into that repo (by simply merging upstream, ie micropython into micropython-esp32).

It's possible to merge PRs from the micropython-esp32 repo into this repo.  They are after all just diffs/patch files.

For people who have a fork of micropython-esp32 with custom branches and commits it would be recommended to move those branches and commits to a fork of this repo (eg using `git format-patch` and `git am`).

**Comment by dpgeorge** [comment]
> That said, it's not too difficult to just mirror all commits made here into that repo (by simply merging upstream, ie micropython into micropython-esp32).

Actually, it's probably a good idea to do this for a fixed "deprecation" period, to help those who have forked micropython-esp32 to migrate to this repo.  In that case, micropython-esp32 will continue to evolve as though nothing had changed.  The only difference would be that commits in that repo would be all coming from a merge of upstream, rather than being original ones.

**Comment by nickzoic** [comment]
Wow, okay, cool.  I'll have a look at this when I'm back from BuzzConf, probably Tuesday.

**Comment by 0x1abin** [comment]
Exciting!

**Comment by jeremyherbert** [comment]
I gave this a run through tonight, worked great! One thing though: it's not 100% clear to me why `ESPIDF` env variable is needed, given that the espressif tools setup documentation asks you to set the variable `IDF_PATH` instead. Perhaps if `ESPIDF` is unset it should default to the value of `IDF_PATH`? 

Also, fwiw, the ESP32 examples use `make flash` to program the chip rather than `make deploy`. Perhaps `flash` could be added as an alias for deploy?

**Comment by MrSurly** [comment]
>Also, fwiw, the ESP32 examples use make flash to program the chip rather than make deploy. Perhaps flash could be added as an alias for deploy?

I'm doing both MP and "pure" ESP-IDF projects, and I second this.  Also, maybe pick up `IDF_PATH` if `ESPIDF` isn't set.  Same with `erase_flash` --> `erase`.  And finally, even add a `monitor` target, which I'm finding really handy when doing ESP-IDF projects, though I do miss the picocom `CTRL-A`, `CTRL-P` sequence to reset the chip.

**Comment by jeremyherbert** [comment]
I have found a new issue with this tonight, I flashed the image on a never used device (although I did run erase first) and I tried to use the code in the readme to connect to wifi (the `wlan_connect` function). However, I get the following error:

```
E (634409) wifi: invalid magic number 1, call WIFI_INIT_CONFIG_DEFAULT to init config
E (634409) wifi: wifi_init 1395 ret=258
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in wlan_connect
OSError: Wifi Invalid Argument
```

I'm not exactly sure what this means, but I will try to look into it when I can.

**Comment by jeremyherbert** [comment]
Ok this is an oops on my part: https://github.com/micropython/micropython-esp32/issues/163

**Comment by jeremyherbert** [comment]
Ok, another issue. When using ampy or something similar, it only works the very first time after reset.

On further investigation in a serial terminal, CTRL+A enters raw REPL, but CTRL+B doesn't exit it. The ESP32 doesn't respond when connecting to a serial terminal after running ampy once.

**Comment by jeremyherbert** [comment]
Appears to fail only on a revision 0 chip. Revision 1 works fine.

**Comment by robert-hh** [comment]
@MrSurly IDF_PATH is used by the pycom branch, which has its own tailored copy of the esp idf. If you use both variants, then having two names for the two esp idf trees is helpful.

**Comment by MrSurly** [comment]
> IDF_PATH is used by the pycom branch, which has its own tailored copy of the esp idf. If you use both variants, then having two names for the two esp idf trees is helpful.

Sure, but if only one is set, why not just use whichever is set?

**Comment by nickzoic** [comment]
Also, "direnv", people :-)

**Comment by dpgeorge** [comment]
Ok, it's merged!  Thanks everyone for the feedback.

**Comment by dpgeorge** [comment]
> Perhaps if ESPIDF is unset it should default to the value of IDF_PATH?

Good idea @jeremyherbert .  I implemented that in 0593d6f5627a75d6d3cc894c4cf421158dc6cedf

> Same with erase_flash --> erase. And finally, even add a monitor target, which I'm finding really handy when doing ESP-IDF projects

It's easy to add these locally to your own makefile/GNUmakefile, but if you think they useful to have (eg monitor would be a good addition) then please make a PR for it.

**Pull request merged**
