### PR TITLE
stmhal: Enable I & D caches for M7

### PR DESCRIPTION
**Pull request by dhylands**

### CODE REVIEW

**Comment by dpgeorge** [comment]
For the F4 this is done in HAL_Init, but I see that it's not in F7's HAL_Init... so probably this should go in HAL_MspInit (or SystemInit, but HAL_MspInit seems to be more consistent with the way the F4 does it).

**Comment by dhylands** [comment]
It doesn't look like there is a HAL_MspInit function currently (just the empty weak one in the hal itself).

So I'll need to add one. I think that the logical place to put this would be in the system_stm32.c file. Does that make sense? Or would you prefer it to be in its own file? Or someplace else?

**Comment by dpgeorge** [comment]
Either system_stm32.c or boards/STM32F7DISC/board_init.c.  It's probably more suited to system_stm32.c because this functionality should be available to all F7 boards, not just the STM32F7DISC.

**Comment by dhylands** [comment]
I added HAL_MspInit to system_stm32.c.

It's an empty function for F4 (essentially replacing the empty function included in the HAL) and enables the caches for the F7.

**Pull request merged**
