### PR TITLE
Preliminary ESP32 documentation, v2

### PR DESCRIPTION
**Pull request by dpgeorge**
This builds upon #4420, as discussed there.  I also added docs for the esp32 module (as a separate commit).

### CODE REVIEW

**Comment by dpgeorge** [comment]
Now that the esp32 HSPI/VSPI bugs are fixed I have updated the SPI part of the quick ref to remove the 2 warnings.

**Comment by dpgeorge** [comment]
@mattytrentini any further comments, anything I missed?

**Comment by mattytrentini** [comment]
No, at this stage it looks quite good! Post-release we can continue the work but I think this is something that is useful _now_ and that we can really build on.

**Comment by dpgeorge** [comment]
Thanks @mattytrentini 

This was merged in 69e72954ad4757f8e3faccef6333cb33842ce052 and acd647100b0fb02aab32500c4a3ffd0faceae7e8

**Pull request closed without merging**
