### PR TITLE
machine_adc.c: added raw_to_voltage(), use calibration

### PR DESCRIPTION
**Pull request by mishafarms**
This change uses the ESP32 built-in calibration for the ADC.

Michael

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.  This is a nice addition, but the user facing Python API needs to be coordinated with other ports that support ADC calibration.

**Comment by mishafarms** [comment]
Thank you,
Can you point me to the other ports that support ADC calibration?

**Comment by dpgeorge** [comment]
> Can you point me to the other ports that support ADC calibration?

No other port has an API exposed yet.  But the stm32 port does have the ability to calibrate the ADC and this is currently done automatically when the ADC is initialised.

**Comment by dpgeorge** [comment]
Support for reading calibrated voltages on esp32 was implemented in 63438a31bb6d0c8012e338433df95700f1cbca97.  See also #7788.

**Pull request closed without merging**
