### PR TITLE
tools/pyboard.py: Add command-line option to make soft reset configurable.

### PR DESCRIPTION
**Pull request by zpif**
Leaves the default as-is, but allows using --no-soft-reset to disable the soft reset when connecting.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for this, a nice addition.  Rebased and merged in 41adf178309759d5965c15972f04987a2635314c

**Comment by jimmo** [comment]
FYI, BooleanOptionArgument was only added in Python 3.9 so this will break pyboard.py on older Python versions.  (@dpgeorge how far back do we need to support?)

**Comment by dpgeorge** [comment]
> how far back do we need to support?

This did originally work on Python 2...

**Comment by dpgeorge** [comment]
The use of BooleanOptionalAction was removed in 145fedef8d74a504c4b7c000e6c305602d07feff

**Pull request closed without merging**
