### PR TITLE
rp2: Make networking options consistent.

### PR DESCRIPTION
**Pull request by jimmo**
Enable the same set of networking features on boards with wifi/ethernet.

### CODE REVIEW

**Comment by jimmo** [comment]
Note: This PR adds `MICROPY_PY_WEBREPL` but does not include freezing webrepl/manifest.py (like PYBD and ESP32 do). Should we consider fully including webrepl on these boards too?

**Comment by dpgeorge** [comment]
Looks good, thanks.  Merged in c5563aa024c60c6da1ebe79e97f2307b49999499



> Should we consider fully including webrepl on these boards too?

Yes probably.  Might be good to add a `manifest_network.py` which freezes in webrepl and urequests (and maybe ntptime), and then a board can include this if it enables networking.

**Comment by aallan** [comment]
Oh, this looks good. Will it go into tonight's nightly? If so, can you point me at the documentation and I'll get that included in our getting started documentation for Pico W. Thanks!

**Comment by dpgeorge** [comment]
This PR won't make much of a difference to Pico W just yet.  It doesn't have all the pieces to get WebREPL working.

**Comment by aallan** [comment]
> This PR won't make much of a difference to Pico W just yet. It doesn't have all the pieces to get WebREPL working.

Ah! Is there a PR (yet) to follow that'll put those pieces in place?

**Comment by dpgeorge** [comment]
> Ah! Is there a PR (yet) to follow that'll put those pieces in place?

Not yet...!

**Pull request closed without merging**
