### PR TITLE
msvc: Update genhdr script to emit MicroPython version numbers

### PR DESCRIPTION
**Pull request by stinos**

### CODE REVIEW

**Comment by dpgeorge** [comment]
I didn't realise Windows build needed a special implementation of py-version.sh...

I was considering just making these VERSION #defines simple hand-made defines in mpconfig.h which would be updated by hand at each version change.  But thought that automating it would lead to less chances for error (and no chance to forget to update the defines when releasing a new version), at the cost of complexity of py-version.sh.

Do you think the complexity of py-version.sh is worth it?

**Comment by stinos** [comment]
It's only the non-cywgin/mingw port which needs it: Windows doesn't come standard with bash (or alike) shell so I chose to re-implement py-version.sh with available tools (msbuild) instead of forcing a working bash or cygwin installation.

And yes I think the relatively small cost of maintaining py-version by far outweighs having to manually update a file for every version. Especially since it's there already to fetch tag/date it feels logical to get the version components as well.

**Comment by dpgeorge** [comment]
Since we need Python to build uPy (to run makeqstrdata.py) would it be better to write py-version.sh in Python, py-version.py?  Then the only dependencies would be make and Python...

**Comment by stinos** [comment]
That should be the best option: only one script to maintain and as a bonus it will probably be simpler/easier to understand than the sh version

**Comment by dpgeorge** [comment]
There would still be 2 scripts: one to generate the version info, and one to process the qstrs.  They could be merged but that seems wrong since they really do different things.

Writing py-version.sh in Python would be much nicer.

**Comment by stinos** [comment]
> There would still be 2 scripts

yeah sorry wasn't clear: I meant 'one py-version script' vs py-version.sh and the code in genhdr.targets there is now

**Pull request merged**
