### PR TITLE
Rcswitch

### PR DESCRIPTION
**Pull request by Narcolapser**
The beginnings of an re-implementation of the RC switch library. I've seen a number of other people yearning for this, as was I. I'll keep working on it, but I hope by starting this off, hopefully others who have been eager for it will help get the library more fleshed out.

### CODE REVIEW

**Comment by pfalcon** [comment]
Please make sure that this is an original code written by you from scratch (in which case please use your copyright in the file headers), or it's based on the source with compatible license to MicroPython (GPL, LGPL aren't compatible).  If you intend this to be merged eventually, please also follow the codestyle (link to it was presented when you submitted the pull request).

**Comment by Narcolapser** [comment]
I can say confidently that it is either written by me from scratch or originated in micropython. I can say this because I tried to re-implement the RCswitch library and failed. I couldn't figure out how to get it to work. So instead I copied micropython's OneWire library, figured out how to operate a pin from python. Wrote my own signalling system, and the result is this.

Should I change the name to avoid the license issue?

**Comment by pfalcon** [comment]
@Narcolapser : Thanks for clarifications, and for posting early version here to keep other people in loop, that's definitely a good idea, and probably worth posting about it on the forum too.

 > Should I change the name to avoid the license issue?

I don't have immediate answer, changing name mat be good to just avoid confusion, but that can be decided at later time.

**Comment by dpgeorge** [comment]
Closing due to lack of interest here.

IMO this could be easily (?) implemented using a hardware UART or SPI peripheral and written in pure Python.  Feel free to try writing such a driver!

**Pull request closed without merging**
