### PR TITLE
tools/autobuild: Add auto build for GENERIC_C3_USB.

### PR DESCRIPTION
**Pull request by xorbit**

### CODE REVIEW

**Comment by xorbit** [comment]
Not sure how this one line commit in a shell script is supposed to affect code coverage in a bunch of C files? 😆

**Comment by dpgeorge** [comment]
Merged in 0ec5052f622307429ab5dd74f1582bcd0a8e0aa1

**Comment by wangshujun-tj** [comment]
In Windows 7 system, a USB device whose driver cannot be found will appear in C3 firmware. Where can I find the driver

**Comment by dpgeorge** [comment]
> Where can I find the driver

You need to install a USB serial driver.  See eg https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/get-started/establish-serial-connection.html

**Comment by wangshujun-tj** [comment]
Thank you for your quick reply
But what I want to solve is the device problem generated by io18 and io19
After the IDF environment of windows is completely installed, it can be used, but it is too large

**Comment by xorbit** [comment]
@dpgeorge Info related to the built-in serial/JTAG USB device is unfortunately largely missing from Espressif's docs, I mostly managed to get it implemented by looking at what they did in the IDF to make the console work and digging through source code.  The page you link to is for ESP32-C3 boards with external USB/serial converter, not the internal CDC device.

@wangshujun-tj When I try it on Windows 10, it works automatically, a "USB JTAG/serial debug unit" device shows up in device manager when viewing "devices per container", also a COM port shows up under "Ports (COM & LPT)" and I can access the MicroPython console with PuTTY.  Can't help you with Windows 7, it has reached end of life, is not supported anymore and I would highly recommend not using it.

**Comment by QGB** [comment]
```
C:\Espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\share\openocd\scripts>openocd -f board/esp32c3-builtin.cfg
Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000
Warn : Transport "jtag" was already selected
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : esp_usb_jtag: Device found. Base speed 40000KHz, div range 1 to 255
Info : clock speed 40000 kHz
Info : JTAG tap: esp32c3.cpu tap/device found: 0x00005c25 (mfg: 0x612 (Espressif Systems), part: 0x0005, ver: 0x0)
Info : Examined RISC-V core; found 1 harts
Info :  hart 0: XLEN=32, misa=0x40101104
Info : starting gdb server for esp32c3 on 3333
Info : Listening on port 3333 for gdb connections
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Info : Hart 0 unexpectedly reset
Error: libusb_bulk_write error: LIBUSB_ERROR_IO
Error: missing data from bitq interface
Error: Unable to execute JTAG queue
Error: Failed to write ESP32C3_TIMG1WDT_PROTECT (-4)!
Error: Failed to disable WDTs (-4)!
Error: libusb_bulk_write error: LIBUSB_ERROR_IO
Error: missing data from bitq interface
Error: dmi_scan failed jtag scan
Error: failed write at 0x17, status=2
Error: libusb_bulk_write error: LIBUSB_ERROR_IO
Error: missing data from bitq interface
Error: dmi_scan failed jtag scan
Error: failed write at 0x17, status=2
Error: Failed to enable EBREAKS handling (-4)!
Error: libusb_bulk_write error: LIBUSB_ERROR_IO
Error: missing data from bitq interface
Error: dmi_scan failed jtag scan
Error: failed write at 0x10, status=2
Error: libusb_bulk_write error: LIBUSB_ERROR_IO
Error: missing data from bitq interface
Error: dmi_scan failed jtag scan
Error: failed read at 0x11, status=2
Error: Failed to read dmstatus!
Error: Failed to resume core (-4)!
Error: libusb_bulk_write error: LIBUSB_ERROR_IO
Error: missing data from bitq interface
Error: dmi_scan failed jtag scan
Error: failed read at 0x11, status=2
Error: libusb_bulk_write error: LIBUSB_ERROR_IO
Error: missing data from bitq interface
Error: dmi_scan failed jtag scan
Error: failed read at 0x11, status=2
Error: libusb_bulk_write error: LIBUSB_ERROR_IO
Error: missing data from bitq interface
Error: dmi_scan failed jtag scan
Error: failed read at 0x11, status=2
Error: libusb_bulk_write error: LIBUSB_ERROR_IO
Error: missing data from bitq interface
Error: dmi_scan failed jtag scan
Error: failed read at 0x11, status=2
```

**Pull request closed without merging**
