### PR TITLE
stmhal: Add hal and cmsis files from STM32Cube_FW_F7_V1.1.0

### PR DESCRIPTION
**Pull request by dhylands**
This includes the same set of files as are currently in the f4 directory plus a couple .h that were needed.
It looks like i2s got renamed as sai, so I kept the _sai_ files.
All files were converted to linux line endings using 2unix from:
https://github.com/dhylands/projects/tree/master/utils/src/2dos
All trailing whitespace was removed using:
for f in f7/inc/\* f7/src/*; do sed --in-place 's/[[:space:]]+$//' $f; done

### CODE REVIEW

**Comment by dpgeorge** [comment]
Do you need inc/Legacy for it to compile?

I think SAI is another audio protocol, independent of I2S (@blmorris is this true?).  So probably we don't need those files.

I see trailing whitespace in many hal files, eg hal/f7/inc/stm32f7xx_hal_uart_ex.h.

I think we can also remove trailing whitespace from the new cmsis files.

Do we need cmsis/inc/core_cmSimd.h?

**Comment by blmorris** [comment]
> I think SAI is another audio protocol, independent of I2S (@blmorris is this true?). So probably we don't need those files.

My quick take - SAI (Serial Audio Interface) is a dedicated audio engine supporting a superset of the I2S functionality provided by the SPI / I2S engine in STM32F40x and 41x processors. The STM32F42x and 43x processors also have an SAI peripheral. I'm not sure if the SPI hardware on the '42x and '43x processors supports I2S or if they need to use SAI.
I've been focussed on I2S and haven't done much research on SAI, but it appears to me that SAI would be the best choice to support I2S as well as several other audio protocols on the processors which provide it - SAI is designed from the start to be a dedicated audio engine, rather than a set of features grafted on to the SPI engine. (Among the audio-specific features provided by the SAI are an integrated 8-word FIFO for each audio sub-block and 32-bit shift registers, so that 24- and 32-bit protocols don't require two data loads per audio sample.)
My preference would be to keep SAI; the next time I design an STM-based board supporting audio (likely to happen sooner or later) I would choose a processor with SAI from the start.

**Comment by dhylands** [comment]
> Do you need inc/Legacy for it to compile?

They went and renamed a bunch of macros. So the legacy header file creates a bunch of #defines to map the old names to the new ones.

If we remove it (from stm32f7xx_hal_def.h) then we'll need to put #ifdefs throughout the rest of the code for places where we're using a HAL macro that they renamed.

> I think SAI is another audio protocol, independent of I2S (@blmorris is this true?). So probably we don't need those files.

Yeah - I think SAI is enabled in my STM32F7DISC/stm32f7xx_hal_conf.h - I'll disable it and remove the files. They're easy enough to add back if @blmorris wants to actually use them.

> I see trailing whitespace in many hal files, eg hal/f7/inc/stm32f7xx_hal_uart_ex.h.
> 
> I think we can also remove trailing whitespace from the new cmsis files.

So - it looks like there are trailing whitespace in alot of files.

If you'd like, I can do a separate PR which just does whitespace cleanup and fix all of the files in the entire tree. Make everything have linux line endings and remove whitespace.

I'll fix the cmsis files regardless.

> Do we need cmsis/inc/core_cmSimd.h?

core_cm7.h #includes it. If I modify core_cm7.h to not #include it then everything still seems to build. So I can remove it if you'd like.

**Comment by dhylands** [comment]
I cleaned up the whitespace in the cmsis files, removed core_cmSimd.h and removed the *sai* files

**Comment by blmorris** [comment]
@dhylands @dpgeorge - I have read a bit more about the audio interfaces on the F7 chips.
These processors provide three I2S interfaces as optional configurations for the first three SPI instances, but they are simplex only - there isn't the additional I2Sext instance linked to each of the SPI engines to support duplex operation. This is reflected in the fact that the hal/f7 files include  `_i2s.[ch]` but not `_i2s_ex.[ch]` files - the `_i2s_ex` files provided the functions for duplex transfers.
Duplex audio transfers are supported in the F7 processors by the SAI engine; as you say the HAL files for this can be added back in if and when we need them.
Another cool thing about the F7 series is that it provide an S/PDIF RX interface which supports Dolby or DTS 5.1 channel compressed audio - this is the optical interface that can transfer full 5.1 channel audio between a DVD/Blu-Ray player to a receiver. I've been looking for a clean way to implement this for a little while.

**Comment by dpgeorge** [comment]
Thanks @blmorris for the info.  I think for now we'll exclude SAI files, but they're easy to add back if/when they're needed.

**Comment by dpgeorge** [comment]
Done in 7c934ae5019d285b58cec3d1edcbc44d90fa6295.

**Pull request closed without merging**
