### PR TITLE
travis: Use tools/metrics.py to compute size diff of minimal ports.

### PR DESCRIPTION
**Pull request by dpgeorge**
To try and make Travis CI size check more robust, by not relying on the saved firmware from a previous build (which may use a different compiler, environment, etc) but rather compile both the PR and head and diff them.

### CODE REVIEW

**Comment by tve** [comment]
The build passed but the travis log https://travis-ci.com/github/micropython/micropython/jobs/320802044 for the minimal build shows a ton of errors of the sort:
```
In file included from /usr/include/stdio.h:27:0,
                 from ../../py/malloc.c:27:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
```
I suspect this is not good...

**Comment by stinos** [comment]
Probably can delete check_code_size.sh then, since it seems to be made specifically for the previous usage?

**Comment by dpgeorge** [comment]
> for the minimal build shows a ton of errors

Fixed by installing 32-bit gcc libraries (to build minimal port in -m32 mode).

> Probably can delete check_code_size.sh then, since it seems to be made specifically for the previous usage?

Yes indeed!

---------

I have no idea what is wrong with this, but building and comparing master and this PR (which just changes travis and tools) leads to a code size change for both `bare-arm` and `minimal` ports...

**Comment by dpgeorge** [comment]
It looks like the underlying problem with consistently reproducing the build size is that error string compression is not deterministic.  I split out that fix as #5943.  Hard to know if it really fixes this PR until that fix is in master (because this one diffs master with the current PR).

**Comment by dpgeorge** [comment]
Ok, this looks like it's working properly now, ready to go in.

**Comment by dpgeorge** [comment]
Now merged.  Let's see how this goes...

**Comment by stinos** [comment]
Not sure if this is related but I just got this: https://travis-ci.org/github/stinos/micropython/jobs/678028912 which has
```
$ git checkout master
error: pathspec 'master' did not match any file(s) known to git
The command "git checkout master" exited with 1.
$ git show -s
commit 6a1c7ea81598489373ed9e2b84cb300584050ae8
Author: Damien George <damien.p.george@gmail.com>
Date:   Wed Apr 22 15:19:13 2020 +1000
    README: Update Travis CI links to point to travis-ci.com.
```

**Comment by dpgeorge** [comment]
> error: pathspec 'master' did not match any file(s) known to git

Oh, that's a pain... not sure exactly why it doesn't work but we'll need to find a way to checkout the "master" commit...

**Comment by stinos** [comment]
Maybe it's just a matter of using `origin/master`?

**Comment by dpgeorge** [comment]
> Maybe it's just a matter of using `origin/master`?

Maybe... I'd suggest to try executing `cat .git/config` as part of the CI build to see exactly what's available.

**Comment by dpgeorge** [comment]
Also, note that I've switch to `travis-ci.com` from the `.org` because `.com` is now free for open-source, and supports the new github API.  So the `.com` may do things slightly differently from the `.org` site.

To make progress here might be required to create a PR against your repo.  I'll see if I can...

**Comment by stinos** [comment]
Oops was already doing the same myself. Relevant output:
```
$ cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/stinos/micropython.git
	fetch = +refs/heads/win-metrics:refs/remotes/origin/win-metrics
[branch "win-metrics"]
	remote = origin
	merge = refs/heads/win-metrics
```

**Comment by dpgeorge** [comment]
Looks like it's because it's a branch, not master.

**Comment by stinos** [comment]
Explicitly fetching master works for me, and should always work no matter how Travis does the initial clone/fetch:
```
        - git fetch origin refs/heads/master:refs/remotes/origin/master
        - git checkout origin/master
```

But: this is the master version I have so it's comparing my branch vs my latest master. But that only really makes sense if my master branch is up to date with e.g. upstream master otherwise it's comparing apples and oranges.

The same is actually true everywhere: if someone creates a PR but doesn't branch from latest master, is there a point in comparing size with master? Maybe it should instead compare with the last common commit?

**Comment by dpgeorge** [comment]
> Maybe it should instead compare with the last common commit?

Agreed.  Maybe the first line of `git show-ref` can be used as this commit.

**Comment by stinos** [comment]
Hmm. This is much, much harder than I thought. In fact I currently have no idea what it would take to come up with a solution which works for most cases.
- show-ref isn't usable since it shows refs, but a branch can be branched from any commit and an SHA is not a ref?
- 'last common commit' isn't necessarily a commit in master since branches/PRs can start from other branches
- Travis builds can be started pretty much from anywhere (also tags etc) so that makes things much harder
- when you merge a bunch of commits in master, there's no other branch involved and the logic should be 'compare size against previous master' but I have no idea how git could ever know what that was
- same problem with git log: when I branch from the micropython repository (called 'upstream' for me), Travis still runs for my own repository which doesn't know about the upstream
- locally I'd use something like `git reflog show | grep "moving from" | head -1 | cut -d ' ' -f1` but that doesn't work on Travis because it clones the branch directly so there's no reflogs earlier than the clone

For PRs and the likes (i.e. not new commits being pushed to master), a possible strategy would be something like: assume the repository was at one pointed forked from micropython/micropython (makes sense), add that as a remote named upstream and fetch it, somehow figure out the last commit common between the two and use that one.

**Comment by dpgeorge** [comment]
>  This is much, much harder than I thought. In fact I currently have no idea what it would take to come up with a solution which works for most cases.

Looking at a PR in this repo, Travis does this at the start:
```
$ git clone --depth=50 https://github.com/micropython/micropython.git micropython/micropython
Cloning into 'micropython/micropython'...
remote: Enumerating objects: 4196, done.
remote: Counting objects: 100% (4196/4196), done.
remote: Compressing objects: 100% (3403/3403), done.
remote: Total 4196 (delta 986), reused 2186 (delta 566), pack-reused 0
Receiving objects: 100% (4196/4196), 6.35 MiB | 18.00 MiB/s, done.
Resolving deltas: 100% (986/986), done.
$ cd micropython/micropython
$ git fetch origin +refs/pull/5955/merge:
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 8 (delta 5), reused 4 (delta 2), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/micropython/micropython
 * branch            refs/pull/5955/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
```
But on your fork building the branch (not a PR):
```
$ git clone --depth=50 --branch=win-metrics https://github.com/stinos/micropython.git stinos/micropython
Cloning into 'stinos/micropython'...
$ cd stinos/micropython
$ git checkout -qf 6a1c7ea81598489373ed9e2b84cb300584050ae8
```
Looking at both those, I don't immediately see any way to make it work for both.

-----------------

Stepping back a bit, prior to this PR being merged the way it worked is that it would save the result of a previous build in Travis persistent store, then diff against that.  That scheme is also not perfect, and indeed there were always problems with it giving spurious results.  Which really comes down to the same problem: what is the previous version it should diff against?

With this PR (which is merged) it seems to work fine on this repo with new PRs.  It's then just making it work with forks.  Some ideas:
1. like before, save the commit hash of the most recent non-PR in Travis persistent storage, and use that hash as the reference
2. just skip doing the size-diff check if `git checkout master` fails.

**Comment by stinos** [comment]
> it seems to work fine on this repo with new PRs

It's not going to give correct (well, expected) result when the PR isn't started from the tip of master though? @jimmo pointed out this can be fixed with `git merge-base` though.

Also for builds of the master branch it won't do anything since the comparison will be between the same 2 commits but that's maybe not an issue. But that can also be solved by idea 1.

**Comment by dpgeorge** [comment]
> It's not going to give correct (well, expected) result when the PR isn't started from the tip of master though? @jimmo pointed out this can be fixed with `git merge-base` though.

Yes that's right, it won't work if it's not forked from tip.  That was actually how it previously worked because it'd always compare a PR to the most recent master build (at the point the PR was made).  That's probably (partially) why the previous scheme gave spurious increases sometimes.

But, yeah, this can be fixed using `git merge-base` (and probably can't be fixed using (1) above).

> Also for builds of the master branch it won't do anything since the comparison will be between the same 2 commits but that's maybe not an issue. But that can also be solved by idea 1.

The original scheme didn't do a size comparison for builds of master, only for PRs, using `if [ "$TRAVIS_PULL_REQUEST" = "false" ]`.  So that's the idea here, to check master with itself so that will always pass.

**Pull request merged**
