### PR TITLE
lib/fatfs: Unify fatfs configuration. Stmhal and cc3200 use single file.

### PR DESCRIPTION
**Pull request by hosaka**
Each filesystem config definition for stmhal and cc3200 moved to the respective mpconfigport and used in ffconf.h to define filesystem behaviour, so two files are removed. Includes were replaced with the full path to lib/fatfs. The default values in ffconf.h follow the template file(ffconf_template.h), perhaps making it redundant and a candidate for deletion.

If there are no issues with this, the esp8266 port will follow to use the same file.

### CODE REVIEW

**Comment by danicampora** [comment]
Looks good to me. +1

**Comment by pfalcon** [comment]
Looks good enough for me too - there's something to comment on, but I'll skip that as it's all within fuzz factor. Except @alex-march, do you intend this to be squashed for merging or not (please don't do that now, just answer).

**Comment by alex-march** [comment]
Even if it's something minor, please let me know, I don't mind fixing typos or even indentation. I wasn't planning to squash them, since they're related to separate ports, but I certainly can if you insist. I will probably remove the ffconf_template file since it's of no use anymore.

**Comment by alex-march** [comment]
The travis build fails on bootloader, but my local build runs just fine and generates the bootloader, that's odd.

**Comment by danicampora** [comment]
Probably you need to do a clean build.  To fix it, in mpconfigport.h:

```
#ifndef BOOTLOADER
#include "FreeRTOS.h"
...
```

**Comment by pfalcon** [comment]
> Even if it's something minor, please let me know, I don't mind fixing typos or even indentation.

It's not that. My concern would be that lib/fatfs/ should contain just pristine upstream code (so it can be a git module for example).

Another minor nitpick is this change: https://github.com/alex-march/micropython/commit/8ee25b8f01293ce66f818a6ec3aafd1a1a9d0ade#diff-181e798f15c738dbb59d0ae7fcff0523 . I'd squash it (change to this particular file!) to the previous commit touching that file.

Again, I don't think that for this case any of these 2 are important. So, just need to wait for @dpgeorge review.

**Comment by alex-march** [comment]
> My concern would be that lib/fatfs/ should contain just pristine upstream code
I agree with you there, this can be either made into a module and updated separately. I am not very familiar with how gitmodules are maintained, but I'd gladly have a stab at it if needed.

Commits squashed, single file change moved into the unify commit. Thanks for the suggestion.

**Comment by pfalcon** [comment]
> but I'd gladly have a stab at it if needed.

No need IMHO, that would be scope creep with many new questions to answer. This already brings bunch enough good changes, further good changes can be left for when they will be really needed.

**Comment by dpgeorge** [comment]
lib/fatfs is not pristine because we have some custom patches, eg 6b755d827ac96fab8649f35b0e3508a28106c532.  So it'd require some effort to convert it to a submodule.

So this PR looks good.  But maybe use config variables `MICROPY_FATFS_xxx` in case we have another fs driver in the future?

**Comment by alex-march** [comment]
Hi Damien, all renamed.

**Comment by alex-march** [comment]
Before this is closed. I think cc3200/diskio.h can also be deprecated in favour of lib/fatfs/diskio.h. Let me whip up a quick commit.

**Comment by alex-march** [comment]
The drawback of this, is using zero values for returns of ffconf.c functions, same as stmhal version. Alternatively, drive defines can be moved into the diskio.h, but cc3200 doesn't use PD_SDCARD or PD_USER. Please let me know if it's something to consider or drop for now.

**Comment by danicampora** [comment]
There's something I don't like. You've removed the:

```c
#define FLASH       0
```

in ffconf.h

and now you have created PD_FLASH, which diskio.c uses, but the other files return a hardcoded 0...

I rather have the drive numbers defined in a header file so that all file system routines can use the  named constants instead of hard coded values.

**Comment by alex-march** [comment]
Yes, I was not sure about leaving the hardcoded returns. I'll move the PD_ defines into the header file so they are shared between the ports and modify other ports to use them.

**Comment by dpgeorge** [comment]
Let's not get carried away with too many changes.  The original PR (with renamed MICROPY_ constants) was good enough.

**Comment by alex-march** [comment]
Since it was relevant to reducing the duplicated files, I thought it might apply to this PR as well. But of course, the decision is yours! :)

**Comment by dpgeorge** [comment]
@alex-march is the PR in a ready-to-merge state?  @danicampora are you happy with the changes?

**Comment by alex-march** [comment]
Yes, ready to merge.

**Comment by pfalcon** [comment]
> Let's not get carried away with too many changes. The original PR (with renamed MICROPY_ constants) was good enough.

I wish all contributors see that as clearly as maintainers...

**Comment by danicampora** [comment]
Yes, I am happy now, sorry for the delay ;-)

**Comment by dpgeorge** [comment]
Merged, ending in c27e5c4b0bcdae50bdeb29a9c9b8adb431c343b3.

@alex-march @danicampora I made one change to keep cc3200 the same as before: added an option for MAX_LFN and configured it as https://github.com/micropython/micropython/blob/master/cc3200/mpconfigport.h#L66

**Comment by danicampora** [comment]
@dpgeorge thanks!

**Pull request closed without merging**
