### PR TITLE
esp32: support for native code generation

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR adds initial support for native code generation on esp32.  This was quite difficult to do because of a few major differences with the esp32 architecture:
- windowed registers
- esp32 can only do 32-bit loads from executable memory
- esp32 uses setjmp for NLR

Native and viper functions work, and the native/viper tests in `tests/micropython` all pass.  But I didn't do thorough testing and I'm sure there are still some bugs here and there.

The code here requires some conditional compilation to switch behaviour for esp8266 vs esp32 when doing native code generation, along with some general clean up.

Also, a new native architecture will need to be defined to distinguish between esp8266 and esp32 in .mpy files.

### CODE REVIEW

**Comment by maludwig** [comment]
YES YES PLZ, I NEED IT! YES. YOU'RE MY HERO! I APPROVE!

**Comment by maludwig** [comment]
So...what happens now? How can I help you get this merged?

**Comment by jimmo** [comment]
@maludwig I think testing is likely to to be the most helpful thing here.

**Comment by maludwig** [comment]
@jimmo is there a formal process? I have many ESP32s kicking about, I could try it out and just see if its awesome? And then just write here how awesome it is?

**Comment by dpgeorge** [comment]
> How can I help you get this merged?

There are still some WIP and TODO comments in some of the commits here, so they need to be addressed.  But also, yes, feel free to test it and give feedback.  There's no formal process (apart from running the test suite), just see if you can crash it :)

**Comment by dpgeorge** [comment]
I've now finished this off and it should be good to merge.  Just needs some final testing that it didn't break esp8266 (or stm32) native code generation.

**Comment by dpgeorge** [comment]
This was merged!

**Pull request merged**
