### PR TITLE
stmhal: Detect and freeze modules/scripts for stmhal port if they exist

### PR DESCRIPTION
**Pull request by kamikaze**
If there is any of FROZEN_DIR/FROZEN_MPY_DIR exist - run the make-frozen.py on it when executing make command. #2517

### CODE REVIEW

**Comment by kamikaze** [comment]
anyone? :)

**Comment by peterhinch** [comment]
The current STM solution enables the use of different directories for different projects. We already have project-specific build-time options such as the target board type. These are readily encapsulated in a project specific Bash script - typically a one-liner to do make clean, build for the correct target, put the board into DFU mode and flash it.

I'd prefer to see the STM solution implemented on the ESP rather than vice-versa.

**Comment by pfalcon** [comment]
> I'd prefer to see the STM solution implemented on the ESP rather than vice-versa.

There's a standard solution, implemented in common makefiles, intended to be used by each port. Ports which don't use it, will be refactored to use, so patching them in adhoc way (like this pull request does), doesn't make sense.

The standard logic of frozen modules (as introduced in
https://github.com/micropython/micropython/commit/f28efa19713977a61395b19fec1fe501aeee4c0e) works very simple: if FROZEN_DIR makefile variable is defined, any files under it will be used as frozen modules. Some ports define their-standard value for FROZEN_DIR, some don't, but it's always possible for a user to override FROZEN_DIR by a user without need to patch Makefile.

**Comment by kamikaze** [comment]
but with this change users are still able to override FROZEN_DIR. And it still saves an option to make any overide magic you've told about. The only thing it adds - default paths with checking for its existance. Saves some time and hairs for newcomers, changes nothing for others.

**Comment by kamikaze** [comment]
waiting for a verdict ) I think it would be a better way to accept or reject PRs, so there would not be so much in queue )

**Comment by pfalcon** [comment]
The underlying reason of your problems is inconsistency between ports. So, the way forward is to make sure that all ports work similarly. Then even if it happens that this handling is not the best, any fixes will be available to every port. And there's no current issues known with a generic frozen modules handling scheme (well, perhaps except that it's not documented).

So, what needs to be done is to switch stmhal to use standard frozen modules rules. Your patch doesn't do that, so it's not useful, sorry. Even if it's applied, as a next step, all changes introduced in it will be removed by following the process above.

**Comment by pfalcon** [comment]
Note that in #2517, both @dhylands and @robert-hh explained you how you can have these changes (which are useful to you) without need to submit them upstream (where they're not useful).

**Comment by kamikaze** [comment]
this is not about me anymore. This is about being more user/developer friendly in development process aspect. Ease of use too. And if someone will decide to freeze something and instead of just doing it - he will need to ask for a help and search for answers on github - it is a wrong way to go. This tiny change breaks nothing, changes nothing for gurus (they still can override everythin as they did) and makes freeze process a little bit easier for a newcomers in some cases. For me it's ok to get rid of this change when a more complex solution will become ready. So why it's not useful? In such way we could throw away all Makefile content and help newcomers to write it from scratch. Every time for everyone... if they will ask such questions at all and not just switch to other projects

**Comment by kamikaze** [comment]
where I can find "standard frozen modules rules" ?

**Comment by pfalcon** [comment]
Ok, make-consistent changes were applied: https://github.com/micropython/micropython/commit/3967ca7390ff8257728ef6237b93977b63bde41d . Note that nothing changes on user's side: you still need to run `make FROZEN_DIR=subdir` to get them to work. Perhaps the commit above clarifies that it needs to be run after `make clean`. `make clean` is a universal first-step solution to all problems: something doesn't work? - your next step is `make clean`. Only if problem persists after make clean, you start to think what you're doing wrong, look at the source, read manual, etc.

**Comment by pfalcon** [comment]
>  "standard frozen modules rules" ?

common rules are in py/*.mk

**Comment by pfalcon** [comment]
> In such way we could throw away all Makefile content and help newcomers to write it from scratch.

We do have Makefiles. You (and other newcomers) have few choices:

1. Learn how to use them.
2. Tell there's something wrong with them.
3. Argue for specific changes (the smaller the better), and argue well and eloquently.

The most productive way is of course no.1. The most non-productive is no.2. And if you want to go for no.3, you're welcome to, but did you really consider no.1?

**Pull request closed without merging**
