### PR TITLE
zephyr: add support for 2 sensors

### PR DESCRIPTION
**Pull request by erwango**
This pull request provides support for 2 sensors TMP006 and HTS221.

Sensor support will be helpful to demonstrate more use cases using micropython on zephyr

### CODE REVIEW

**Comment by pfalcon** [comment]
@erwango: I don't think that such approach scales. There's potentially unlimited number of sensors in the world, and MicroPython can't have a separate module for each of them. Instead, there should be a single module for all sensors. The API I envision would be:

~~~
import utime
import zsensor

s = zsensor.Sensor("BME280")
while True:
    s.measure()
    temp = s.get_float(zsensor.TEMP)
    press = s.get_float(zsensor.PRESS)
    humidity = s.get_float(zsensor.HUMIDITY)
    print(temp, press, humidity)
    utime.sleep(1)
~~~

Which is a direct translation of the sample in http://docs.zephyrproject.org/subsystems/sensor.html#fetching-values .

I can help with implementing such a module. For that, we'd need to agree on a reference board with builtin sensor(s), apparently candidates are frdm_k64f and disco_l475_iot1, and I'd need a reference for Zephyr sample which works with any sensor on such a board. Thanks.

**Comment by GAnthony** [comment]
@erwango, thanks for pushing the tmp006 PR.  
Even though that PR appears pretty generic, for the CC3220SF launchxl, it depends on the tmp006 temperature sensor driver in Zephyr, which has not yet been pushed. 
In fact, only recently the underlying I2C driver was merged.
So, I think you may need to remove that commit for now, until the tmp006 sensor driver PR is pushed and merged.

**Comment by pfalcon** [comment]
> I can help with implementing such a module.

Available as https://github.com/pfalcon/micropython/blob/zephyr-wip/ports/zephyr/modzsensor.c (zephyr-wip branch). A test: https://github.com/pfalcon/micropython/blob/zephyr-wip/ports/zephyr/scripts/example_sensor.py .

**Comment by dpgeorge** [comment]
The `zsensor` module for Zephyr (proposed above) was merged in 0e52ee957df7700e27fe5bb2378b24b4cecfab08

**Pull request closed without merging**
