### PR TITLE
tests: Format with black

### PR DESCRIPTION
**Pull request by dlech**
This adds the python files in the `tests/` directory to be formatted with `./tools/codeformat.py`.

In a few places `# fmt: off`/`# fmt: on` was used where the code had special formatting for readability or where the test was actually testing the specific formatting.

### CODE REVIEW

**Comment by dlech** [comment]
I'm guessing that this was intentionally omitted for a reason, but I thought I would try it anyway.

**Comment by dpgeorge** [comment]
> I'm guessing that this was intentionally omitted form the recent formatting changes for a reason, but I thought I would try it anyway.

Yes, because it was a big change and needed to be thoroughly looked over, precisely because some tests are actually testing the syntax, eg single vs double quote on strings.

I'm happy to make this change, it keeps things consistent, but would want to go through the changes to make sure everything is OK (and CI is failing at the moment...).

**Comment by dlech** [comment]
I've updated this to fix the tests and omit `tests/basics` for now (most of the compiler tests seem to be in that directory, so we can look over those more closely separately later)

**Comment by dpgeorge** [comment]
Instead of excluding specific tests in `EXCLUSIONS` I'd prefer to use `#fmt: off` for those tests, eg like the repl ones and cmd-showbc (but the blanket-wide exclusion for `tests/basics/*.py` can still stay).  This is then more consistent with the use of `// *FORMAT-OFF*` for uncrustify in parts of the C source.

**Comment by dlech** [comment]
> like the repl ones

I tried this but it causes errors:

```
error: cannot format /Users/david/Documents/GitHub/micropython/tests/cmdline/repl_autocomplete.py: Cannot parse: 3:5: impo sys
error: cannot format /Users/david/Documents/GitHub/micropython/tests/cmdline/repl_emacs_keys.py: Cannot parse: 7:0: 
error: cannot format /Users/david/Documents/GitHub/micropython/tests/cmdline/repl_words_move.py: Cannot parse: 4:3: 2341
error: cannot format /Users/david/Documents/GitHub/micropython/tests/cmdline/repl_cont.py: Cannot parse: 30:0: print(x)
```

So I don't think we don't have a choice on the repl files.

**Comment by dlech** [comment]
I've added an extra commit to fix the one line of code coverage that was lost. 

The qemu-arm test is failing on these two lines in `tests/float/float2int_intbig.py`

```python
print(int(14187745.0))
print("%d" % 14187745.0)
```

which prints

```
14187746
14187746
```

When the `0` after the `.` is removed, it prints the correct result.

**Comment by dlech** [comment]
It looks like the qemu-arm failure is due to #4212, so I've worked around it with `# fmt: off` for now.

**Comment by dlech** [comment]
floating point issue is addressed in #5832

**Comment by dpgeorge** [comment]
Ok, great, this PR looks good now, so merged in 3dc324d3f1312e40d3a8ed87e7244966bb756f26 and 6110cd30780c1b539bf9a67352962bf026b6a2ce

**Pull request closed without merging**
