### PR TITLE
esp32: Enable NimBLE support on all builds (IDF 3.3.1 and 4.0-beta1).

### PR DESCRIPTION
**Pull request by jimmo**
Based on #5282

This PR moves to the latest stable release of the 3.3 IDF.

As NimBLE is now supported in DF 3.3.1, this means that the `ubluetooth` module will now work on all ESP32 builds.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Great, thank you!

To get travis to pass would need to edit `.travis.yml` to add a submodule update of the nimble module for IDF3 builds.

**Comment by jimmo** [comment]
OK, done.

**Comment by dpgeorge** [comment]
Squashed and merged in 3032ae1155db4bd89786f715f5227967d2cb71cf

**Comment by dpgeorge** [comment]
Also updated the firmware download page to mention that BLE is now available on esp32 IDFv3 builds.

**Pull request closed without merging**
