### PR TITLE
stm32: Fix RMII typo in stm32f405_af.csv

### PR DESCRIPTION
**Pull request by mcauser**
As per discussion: https://github.com/micropython/micropython/issues/5286

### CODE REVIEW

**Comment by dpgeorge** [comment]
Looks good to me, thanks.  Can @untitledlt confirm it works?

**Comment by mcauser** [comment]
The build now runs successfully against master.
Will have to wait until I get home to test on one of my Black VET6 boards

**Comment by untitledlt** [comment]
I was able to build and flash successfully. Thanks!

```
MicroPython v1.11-549-gf2ecfe8b8 on 2019-11-08; MCUDEV STM32F407VE with STM32F407VE
Type "help()" for more information.
>>>
>>> import network
>>> dir(network)
['__class__', '__name__', 'LAN', 'route']
```

**Comment by mcauser** [comment]
I didn't have a LAN module to test this with, so I ordered a one of these [LAN8720 modules](https://www.aliexpress.com/item/32947407343.html). I'll revisit in a few weeks.

**Comment by dpgeorge** [comment]
Ok I'm happy with this change (even if untested), so merged in 258b1478307c1f9d89ed67309e145b9a55aeaadc

@mcauser if you manage to test it that would be great, please let us know the result.

**Pull request closed without merging**
