### PR TITLE
delete-char-fix in readline.c

### PR DESCRIPTION
**Pull request by livius2**
I do not know whether the fix is complete
especially what should happened in MICROPY_REPL_AUTO_INDENT for delete char

### CODE REVIEW

**Comment by robert-hh** [comment]
It is pretty common to configure the backspace key sending 127, not 8. Thefore backspace was deifned as both 8 and 127. The Del-Key on the PC keyboard sends "\x1b[3~".

**Comment by pfalcon** [comment]
So, what does this fix exactly?

**Comment by livius2** [comment]
> So, what does this fix exactly?
Now delete char do the same as you pres backspace - delete prewious char
but should delete next char

**Comment by dpgeorge** [comment]
Sorry but this will break the REPL usage for lots of existing users, on all platforms.

@livius2 what particular OS/terminal did you use that the current backspace/delete was a problem for you?

**Comment by livius2** [comment]
I use windows 10 terminal and when i press delete button it work as backspace
But how this is possible that for someone it work ok with this source code?
If code itself always go back and never forward?
`
vstr_cut_out_bytes(rl.line, rl.cursor_pos - nspace, nspace);
// set redraw parameters
redraw_step_back = nspace;
redraw_from_cursor = true;
`

**Comment by dpgeorge** [comment]
> If code itself always go back and never forward?

There is code to handle "delete" as an escape sequence.  Search for "delete_key:' in readline.c.

> I use windows 10 telnet terminal

What board do you connect to?  wipy or esp8266?

**Comment by livius2** [comment]
>There is code to handle "delete" as an escape sequence. Search for "delete_key:' in readline.c.

Ach then i have looked in the wrong place

>What board do you connect to? wipy or esp8266?

Wipy2.0

**Comment by pfalcon** [comment]
Ok, let me close this issue for now. If you have any additional info, feel free to add it. Also, maybe helpful to find other users which have such issue (if any). If you don't know such, a good place to socialize is http://forum.micropython.org/

**Pull request closed without merging**
