### PR TITLE
stmhal: Add mem8/mem16/mem32 operations to machine module.

### PR DESCRIPTION
**Pull request by dhylands**
This uses the newly factored machine_mem functions.

### CODE REVIEW

**Comment by dhylands** [comment]
Question: Do we want he constants which are currently in the stm module to be in the machine module?

**Comment by pfalcon** [comment]
> Do we want he constants which are currently in the stm module to be in the machine module?

STM32-specific ones? I already shared my opinion, but for completeness: IMHO, no. At least, not haste with that.

**Comment by dhylands** [comment]
rebased onto updated #1717

**Comment by pfalcon** [comment]
Looks good, but I guess @dpgeorge should ack this (can be rebased in the meantime).

**Comment by dpgeorge** [comment]
Thanks @dhylands, now merged in b61336483b8b4729309f95d232306ced97b00840.

> Do we want he constants which are currently in the stm module to be in the machine module?

No.  They are too specific to the MCU and I think machine module should be kept clean, with generic machine things.  If you write code with stm module, it's only going to work on stm hardware, and having specific module for that will prevent errors (eg if constants are in machine module, and constant just happen to have the same name on another MCU, then code won't raise an exception on that other MCU but will behave very badly).  Also, for tab-completion to be friendly and not have heaps of options, best to keep modules clean.

**Pull request closed without merging**
