### PR TITLE
ports/esp32: add r/w access to the rtc slow memory

### PR DESCRIPTION
**Pull request by andynd**
add it as machine.RTC().slow_memory(addr [, value])

This is helpfull for example to communicate with the ulp.

### CODE REVIEW

**Comment by andynd** [comment]
Merged upstream master

**Comment by andynd** [comment]
*poke*

**Comment by andynd** [comment]
more *poke*

**Comment by dpgeorge** [comment]
Thanks for the contribution, and sorry for the slow response.

IMO it's not necessary to add a function like this.  There is already a way to do a similar thing, using `machine.mem32`:
```python
value = machine.mem32[0x50000000 + offset] # read RTC_SLOW_MEM
machine.mem32[0x50000000 + offset] = value # write RTC_SLOW_MEM
```
Also, you could use `uctypes.bytearray_at(0x50000000, 8 * 1024)` to create a bytearray that references this memory region.

I guess it would make sense though to add a constant for the `RTC_SLOW_MEM` address, eg to the `esp32` module.

**Comment by dpgeorge** [comment]
Closing, see comment above.

**Pull request closed without merging**
