### PR TITLE
examples/socket: Use correct variable name.

### PR DESCRIPTION
**Pull request by Dorukyum**
I noticed the wrong variable name was used here, decided to fix it.

### CODE REVIEW

**Comment by robert-hh** [comment]
The commit message format is wrong. It should be:

topic: Message Text.

e.g.

examples: Use correct variable name in socket example.

You can change it locally and then do a force push to your repository fork, which will update the PR.

**Comment by Dorukyum** [comment]
I've updated the commit message and signed it off but I don't get why the check fails and returns "Unwanted email address". The commit was done on GitHub, is that an issue?

**Comment by dpgeorge** [comment]
> The commit was done on GitHub, is that an issue?

It's OK for docs changes, but not for code changes.

**Comment by dpgeorge** [comment]
Thanks for the contribution here!

**Pull request merged**
