### PR TITLE
Re issue #1509 RTC initialisation fix

### PR DESCRIPTION
**Pull request by peterhinch**
Checks for year (RTC_TR) instead of backup register 0 to detect power up.

### CODE REVIEW

**Comment by danicampora** [comment]
Maybe squash your 2 commits into one.

**Comment by peterhinch** [comment]
@danicampora Alas this has stretched my meagre knowledge of git to breaking point. I've achieved the feat on my local repo but as far as I can see I can't push the change because git status reports that my branch and origin/master have diverged. If you feel it's worth pursuing, perhaps you could offer some guidance?

**Comment by danicampora** [comment]
@peterhinch doing: `git push peterhinch master --force` after squashing doesn't work?

**Comment by dhylands** [comment]
@peterhinch I'm going to guess that this is because you did some changes on the master branch and committed them to the master branch in your repository.

If you work on a branch, this can be prevented.

If your committed changes are the most recent, then you can create a branch so that you don't lose them, and you can reset your master branch back to before the changes were made.

I'd be happy to help you fix things up. We can do it the slow way (over email - dhylands at gmail dot com) or perhaps a Skype call or IRC or something? I'm in the Pacific timezone (UTC - 7).

Perhaps send me the branch.txt and log.txt files from running the following:
```
git branch > branch.txt
git log -6 > log.txt
```
via email to get started.

**Comment by peterhinch** [comment]
@danicampora  The --force option seems to have done the trick.
@dhylands Thanks for the offer of help. I'll work on a branch in future.

**Comment by dpgeorge** [comment]
Only downside of this is if someone configured the year register to be 0 (ie year=2000).  Unlikely, but maybe it's more robust to check that year=0, month=0 and date=0?

Also, @peterhinch it seems you inadvertently changed some indentation in the calibration function.  Was that intentional?

**Comment by blmorris** [comment]
@dpgeorge - Actually, looks like @peterhinch corrected some mixed tab-space indentation from one of my commits - a gift from Emacs before I figured out how to configure it correctly.

**Comment by peterhinch** [comment]
This is now done. Re the cal indentation, I noticed my editor had altered this, and that it no longer conformed to the coding standard. I guessed the reason but avoided making any manual changes. I've now corrected it with the aim of making it compliant.

**Comment by dpgeorge** [comment]
Merged in b106532b32b7b92d62250ca6a9edea078e042597.

**Pull request closed without merging**
