### PR TITLE
esp32/ulp: Explicitly enable ULP in build config.

### PR DESCRIPTION
**Pull request by andrewleech**
Resolves `esp32: ULP binary loading support was broken after 1.10 release` #5159

I was able to reproduce the working ULP example in v1.10 using https://github.com/ThomasWaldmann/py-esp32-ulp/blob/master/examples/counter.py

As described in https://github.com/ThomasWaldmann/py-esp32-ulp/issues/42 this was broken in v1.11 release, throwing an `OSError: 260`
I was also able to reproduce this error.

The same error is present on current master builds for both IDF v3 and v4

Explicitly enabling ULP in the board config as attached fixes the error, allowing the counter example to run the same as v1.10

I'm not sure if `CONFIG_ESP32_ULP_COPROC_RESERVE_MEM=1024` is the most appropriate value, this was picked from https://github.com/espressif/esp-idf/blob/master/examples/system/ulp/sdkconfig.defaults

This example config has only 512 however:
https://github.com/espressif/esp-idf/blob/master/examples/system/deep_sleep/sdkconfig.defaults

The ULP ram is taken out of RTC slow ram, I'm not sure what else uses this?
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/kconfig.html

### CODE REVIEW

**Comment by dpgeorge** [comment]
Great, thank you!

> I'm not sure if `CONFIG_ESP32_ULP_COPROC_RESERVE_MEM=1024` is the most appropriate value

The default in `components/esp32/Kconfig` is 512, which is the value it gets if you don't explicitly set this config option.  Maybe it's best not to set this value at all in our build so it gets the IDF's default?   A user can anyway override it for their custom board with a custom sdkconfig file.
Also, I think the fix will need an extra pair of config values for IDF3:
```
CONFIG_ULP_COPROC_ENABLED=y
```

**Comment by andrewleech** [comment]
Ah yes, I only tested on IDFv4, I did meanto chase up whether it used to have a different name.

I wasn't sure where to find whether there was an actual default set, searching for the key didn't pull up `Kconfig` so I missed that. Yep, letting it fall through to the default makes sense for now.

Updated on both counts in the commit I just pushed.

**Comment by dpgeorge** [comment]
> I wasn't sure where to find whether there was an actual default set, searching for the key didn't pull up `Kconfig` so I missed that.

You need to grep for the config value without the `CONFIG_` prefix, because that's not included in the list of config values in the Kconfig files.

**Comment by dpgeorge** [comment]
Squashed and merged in 9ca8a503ed3d7b31fc1cfe0e2e51925d3c0c3396

**Pull request closed without merging**
