### PR TITLE
stmhal: Add os.invalidate which unmounts and remounts a filesystem.

### PR DESCRIPTION
**Pull request by dhylands**

### CODE REVIEW

**Comment by pfalcon** [comment]
There's no invalidate() in https://docs.python.org/3/library/os.html , and that's good reason to keep not having it. As I mention in #1587, I expect this functionality to be done by os.sync(). It should just sync all mounted filesystems. And should sync both ways - not just make sure media state agrees with write buffers, but also that read buffers agree with media. The last point is usually overlooked, because it's assumed that system takes full control of disk, but if it's kind of removable, and without good way to detect a fact that it was replaced, then sync() should just to it.

**Comment by dhylands** [comment]
I'm quite srtongly opposed to having the invalidate functionality attached to sync, because it just plain the wrong place to put it (for reasons wihch I've already explained).

However, I'll repeat myself (again). Performing a sync on the host and on the pyboard WILL cause corruption if both sides have unwritten modifications. If you want to toss the the modifications on the pyboard side, then you should just call invaidate (whatever its called - I just picked os.invalidate out of the air as an example). You CAN'T have the modifications from both sides. It's not possible (they're both block based protocols - last write wins).

**Comment by pfalcon** [comment]
> the invalidate functionality attached to sync

There's no need to "invalidate" anything in the first place. Just flush read buffers, by whatever means available.

> However, I'll repeat myself (again). Performing a sync on the host and on the pyboard WILL cause corruption if both sides have unwritten modifications.

So let me repeat myself again too - NEVER do that. Sync stuff ONLY sequentially, knowing that another side in the meantime did not write anything. Behavior in other cases is UNDEFINED (pyboard's write buffers of course should have priority implementation-wise - after all, it's pyboard's storage).

**Comment by dhylands** [comment]
> the invalidate functionality attached to sync
> There's no need to "invalidate" anything in the first place. Just flush read buffers, by whatever means available.

ok - that's just a terminology thing. When referring to CPU caches, the term "invalidate" describes exactly what you just said.



> So let me repeat myself again too - NEVER do that. Sync stuff ONLY sequentially, knowing that another side in the meantime did not write anything. Behavior in other cases is UNDEFINED (pyboard's write buffers of course should have priority implementation-wise - after all, it's pyboard's storage).

Well, I guess you're free to create your own patch.... We'll just have to agree to disagree.

**Comment by pfalcon** [comment]
You're free to not withdraw this patch - it's @dpgeorge who will decide if it's worth adding this new functionality instead (in future in addition to) fixing existing (os.sync()). I just shared my opinion (though I'd like there were more formal criteria, like adding more stuff than CPython has should be grounded by good usecases).

**Comment by dhylands** [comment]
I didn't create the patch to actually be included. I really only created for you, and you don't seem to want it. Shrug.

**Comment by pfalcon** [comment]
I appreciate that, but it wouldn't help me. After calling sync on Linux side and not seeing a file on pyboard side, my immediate thought was "what's python's analog of sync command?", started typing os.sync, and indeed, it was there, without arguments, as expected. I simply wouldn't know about invalidate(), wouldn't know what arg it takes. I thought you targeted it for some programmatical usage (in rshell or something), while I'm really looking to make 1st small step towards resolving "multi-owned storage" issue - in simple manual way, using means already familiar to a user.

**Comment by dhylands** [comment]
Sure but the semantics of sync doesn't include re-reading the disk to pick up new changes (regardless of how much you want it to), nor does it include dropping all of the internally cached memory. And I would argue that we don't want that to happen either.

The closest thing I've found on linux is "echo 1 > /proc/sys/vm/drop_caches"

Just because os.sync() sounds similar to the linux sync command (and performs an operation which has the same semantics as the linux sync command) doesn't make it the right thing to do to get the complimentary action on the pyboard.

I think that the right thing to do is to detect when the host has the filesystem mounted and make the pyboard filesystem read-only (from the pyboard perspective). Even that will cause issues since the pyboard could have a file open and the file contents are removed or changed by the host.

**Comment by pfalcon** [comment]
> Sure but the semantics of sync doesn't include re-reading the disk to pick up new changes (regardless of how much you want it to)

For me, word "sync" includes doing that too (if it's needed, and it is).

> nor does it include dropping all of the internally cached memory.

I never proposed that. What I have in mind is augmenting os.sync() to write down write caches, then invalidating read caches (by whatever means, you show good way).

> I think that the right thing to do is to detect when the host has the filesystem mounted and make the pyboard filesystem read-only (from the pyboard perspective).

And I agreed it's good next step to plan and implement. It's obviously more complicated, that's why it's next step.

> Even that will cause issues since the pyboard could have a file open and the file contents are removed or changed by the host.

Exactly, so it's not a panacea. That's why it's *next* step which requires *planning* (maybe after good thinking we'd come to conclusion it doesn't buy us much, as none of us would like to activate it for ourselves by default (then we hardly can think about activating it by default for other users)).

**Comment by dhylands** [comment]
> Sure but the semantics of sync doesn't include re-reading the disk to pick up new changes (regardless of how much you want it to)
> For me, word "sync" includes doing that too (if it's needed, and it is).

So you're arguing that we should change the definition of os.sync to the @pfalcon version even though it doesn't agree with CPython? (or linux).

I still argue that I don't want the performance hit of invalidating the caches (the performance hit is having to reload the caches) every time a sync is performed (which is currently a few seconds after every write).

**Comment by pfalcon** [comment]
Someone of us is really confused. I'm talking about modifying this function: https://github.com/micropython/micropython/blob/master/stmhal/moduos.c#L354 . That function is called explicitly by a user and in no other way. (Or if you imply that there's obfuscated, unearthly way that function is called otherwise, that should stop.)

**Comment by dhylands** [comment]
OK - but even still. The definition os os.sync() is still quite clear:
https://docs.python.org/3/library/os.html#os.sync

**Comment by pfalcon** [comment]
See initial comment https://github.com/micropython/micropython/pull/1589#issuecomment-154731816 regarding overlooks and assumptions. (Intuitive) definition of sync is indeed clear - it does sync, global and to the fullest extent possible.

**Comment by dpgeorge** [comment]
As an alternative to os.invalidate(), how about calling os.unmount() followed by os.mount()?  [Yes, this does not address the issue of the semantics of os.sync().]

**Comment by dhylands** [comment]
Thats what os.invalidate did internally :)

**Comment by pramasoul** [comment]
If a USB device announces it is a USB Mass Storage device, the host expects
the device to be a slave, whose contents change only on host command. It
doesn't assume an obligation to maintain a consistent filesystem on the
device, except when it unmounts the device. The host is free to buffer
filesystem activity as it sees fit. The sync() call is not about
synchronizing shared state; it's about preparing to unmount:

The sync() system call forces a write of dirty (modified) buffers in the
block buffer cache out to disk. The kernel keeps this information in core
to reduce the number of disk I/O transfers required by the system.


User understanding and discipline is required to stay safe and sane with a
pyboard connected. Unmount it from the host when the pyboard is writing the
filesystem. Don't read on the pyboard once the host starts doing any
writing. Do a sync() on the host and remount the filesystem on the pyboard
after host writes are finished.

**Comment by PappaPeppar** [comment]
I have seen a few attempts to solve this particular problem (sharing a block device), they all more or less failed. The people trying to do this were capable engineers, so it is probably a difficult problem to solve. This is the reason why MTP is used nowdays. Maybe that's the solution for pyboard as well.

**Comment by dpgeorge** [comment]
> This is the reason why MTP is used nowdays. Maybe that's the solution for pyboard as well.

I did consider MTP right at the very start of the project, but it was not as wide spread as I'd liked, unlike USB mass storage.

@dhylands rshell is basically implementing a kind of MTP.

**Pull request closed without merging**
