### PR TITLE
Nrf9160 base support

### PR DESCRIPTION
**Pull request by glennrub**
This PR introduce the building blocks for supporting nrf9160 (cortex-m33) as a target device. 
It also includes a board definition of Nordic Semiconductors official development kit pca10090.

The base support enables compilation/flashing for  the target board (pca10090) with a secure and non-secure application, where micropython resides in the large non-secure application giving a REPL.

(This will be the first in a series of PR's. Next lined up is linking the non-secure application against Nordic Semiconductors BSD socket library wrapped in under usocket, uselect and network modules providing LTE connection and GNSS.)

### CODE REVIEW

**Comment by dpgeorge** [comment]
I've tested this and it works, I get a REPL!

**Comment by glennrub** [comment]
Merged in 82fe6b0526ad8c10e923174a45063f93f312d681 and 98c2eabaff6c049810d7cbf8aafb536080ae5b60.

**Comment by cruiseflight** [comment]
> I've tested this and it works, I get a REPL!

This is great news, I have been looking for Python on the nrf9160! Would you mind sharing how you got that done? Did you flash a boot loader first? Sorry for asking beginner questions, I have just started with the 9160.

**Comment by cruiseflight** [comment]
Never mind, it was just compiling the nrf build and flashing the two hex files with the nrfconnect programmer. REPL works! Now I am trying to figure out how to use GPS and the LTE modem...

**Comment by dpgeorge** [comment]
> Now I am trying to figure out how to use GPS and the LTE modem...

They are not currently implemented/supported.

**Comment by cruiseflight** [comment]
What can we do to support LTE connections? That would make this a very powerful tool.

**Comment by glennrub** [comment]
Hi @cruiseflight ,

I have a branch providing LTE/GNSS in progress. I'm preparing a PR to collect some feedback (RFC). However, if you are eager to get a LTE link right now you can take a look at it: https://github.com/glennrub/micropython/tree/nrf9160_sockets

For further discussion regarding details on how to use the socket module proposed, we should consider moving further discussions to the MicroPython Forum, as this item is closed.

**Pull request closed without merging**
