### PR TITLE
py/deque: Implemented collectons.deque

### PR DESCRIPTION
**Pull request by dmazzella**
This patch implements support for collections.deque
It is controlled by the config option MICROPY_PY_COLLECTIONS_DEQUE
and is disabled by default.

### CODE REVIEW

**Comment by dmazzella** [comment]
@pfalcon this is a "porting" of cPy deque

**Comment by pfalcon** [comment]
Yeah, and exactly the thing I warned *against* in the previous ticket (which you for some reason closed) - there's no need to support arbitrary-sized deques, so no need to use memory-hungry double-linked lists. Circular buffer is *the* underlying structure which is needed.

**Comment by dmazzella** [comment]
sorry, I haven't understood that you want only support deque(maxlen=N)

**Comment by dmazzella** [comment]
are you sure you want break cPy compatibility?

**Comment by pfalcon** [comment]
No, I'm sure that we need circular buffer data type in MicroPython, and I'm sure that when we implement something, we should try to implement it in a way compatible with CPython. CPython's collections.deque(maxlen=N) offers circular buffer functionality, so that's what we need to implement, not some adhoc type instead.

Otherwise, we always implement only subset of the CPython functionality that we need, so if we need collections.deque(maxlen=N), that's what we implement, and not more. Someone needing collections.deque() with arbitrary length can open a separate ticket and argue, why it's needed at all, why it's needed to be written in C vs Python, why it should be in mainline (who will support it), etc.

**Comment by dmazzella** [comment]
this implementation is based on cPy  deque datatype if use maxlen=N this implementation use the same [datatype of cPy](https://github.com/python/cpython/blob/master/Modules/_collectionsmodule.c#L71)

**Comment by dmazzella** [comment]
if you prefer i can use a new config option MICROPY_PY_COLLECTIONS_DEQUE_NO_ARBITRARY_LEN (1)
and use it in deque_make_new to force use maxlen=N

**Comment by dmazzella** [comment]
@pfalcon why coveralls fail to check deque.py? any hint?

**Comment by pfalcon** [comment]
Did you pay attention to this part:

> no need to use memory-hungry double-linked lists. 

?

The whole idea of developing MicroPython is to optimize RAM usage to the maximum extent possible. We don't have a place to store links from a double-linked links, the overhead we can afford is 0 (or very low number above zero, like 0.01). That's exactly how circular buffer works. Another idea, is that we need alloc-free structures (alloc once, don't allocate afterwards), that's again how circular buffer works.

**Pull request closed without merging**
