### PR TITLE
extmod/moducryptolib: Add crypto functions module, impl reuses axTLS routines.

### PR DESCRIPTION
**Pull request by pfalcon**
The API follows guidelines of https://www.python.org/dev/peps/pep-0272/ ,
but is optimized for the code size, with the idea that full PEP 0272
compatibility can be added with a simple Python wrapper mode.

The naming of the module follows (u)hashlib pattern.

At the bare minimum, this module is expected to provide:

* AES128, ECB (i.e. "null") mode, encrypt only

Implementation in this commit is based on axTLS routines, and implements
following:

* AES 128 and 256
* ECB and CBC modes
* encrypt and decrypt

### CODE REVIEW

**Comment by pfalcon** [comment]
Points to consider:

1. This reuses all the collected knowledge from the design of previous "u" modules. It can be summarized as: Python is the language, where users are expected to write convenient wrappers (in Python). Then, the main criteria for the builtin modules should be: the smallest size. Any boilerplate stuff should be moved to such convenience wrappers, otherwise allowing people who need that, to use this module in the stringent resource constraints (like it usually is). This goes down to the no need to provide symbolic names for well-known number in the builtin modules. 

2. ~~Module name: this patch uses "ucrypto", but I think we should have "ucryptolib", similar to hashlib. This may also help to avoid confusion with the wrapper name, which will be named "uCrypto", based on the popular CPython package: https://www.dlitz.net/software/pycrypto/api/current/ .~~ Decided on "ucryptolib".

3.  PEP 272 compatibility: PEP 272 is nice, truly Pythonic spec, without kwonly args and other unproven novelties applied all over the place. But, it for some reason imagines that crypto algs are implemented in "modules". We implement them in classes. We could provide @staticmethod new, but there's no point in doing that, see p.1.

4. Casing of class names in module. Again, follows hashlib with lower-case naming. Again, may help to avoid confusion with Crypto/uCrypto.

5. Actual API. So far this implements literal methods form PEP 272, but we know that for real use in constrained environments, we need inplace functions. Again, applying the previous experience, then we simply don't need garbage-producing funcs. So, only encryptinto() and decryptinto(), likely taking offset/size.

**Comment by pfalcon** [comment]
Resubmit of #3413, more discussion there.

**Comment by Jongy** [comment]
@pfalcon What about this PR?
I'd be happy to continue working on it and add an mbedtls impl. But we should probably continue to discuss your points mentioned int the last comment.

**Comment by dpgeorge** [comment]
@Jongy a slightly modified version of this PR was merged in the personal fork here: https://github.com/pfalcon/micropython/commit/ddf14955c3859f419417f792fac9e381543e5345 .  I'm happy with how that commit looks and would be happy to apply the patch to this repository, to supersede this PR.

Regarding the points above:

1. It's fair enough to provide the most minimal functionality in the module.  And since there's no corresponding `cryptolib` module in CPython we have more liberty to specify how the `ucryptolib` module would look.

2. `ucryptolib` is nice, it mirrors `uhashlib`.

3. Using classes makes sense, to minimise size, and also make it simpler to use.

4. I have no strong opinion about upper vs lower case, but lower case does match class names in `uhashlib`.

5. In the revised patch linked above the methods are `decrypt(buf[, out_buf])` and `encrypt(buf[, out_buf])`.  If you supply the optional `out_buf` then the result goes into that buffer, otherwise a new bytes object is created with the result.  That's a good balance between PEP 272 compatibility, ease-of-use (`decrypt` is easire to read than `decryptinto`), and possibility to perform an inplace operation.  Specifying the size/offset of the buffer(s) can then be done using a memoryview.

@Jongy do you have any further thoughts/comments?  It should be straightforward to provide an mbedtls implementation of this module.

**Comment by dpgeorge** [comment]
For the record, PyCrypto (https://github.com/dlitz/pycrypto) is no longer maintained (last commit was 4 years ago) and PyCryptodome (https://github.com/Legrandin/pycryptodome) is a fork that is actively maintained.  There is also the `cryptography` module (https://github.com/pyca/cryptography) which provides more high-level recipes for cryptography, and a hypothetical `ucryptography` should be able to be built upon `ucryptolib`.

**Comment by Jongy** [comment]
@dpgeorge I'll get working on it.

Everything is indeed quite straightforward. There's one last thing I'm not sure about - not knowing whether it's an encrypt/decrypt object in the `new` method requires lots of unnecessary copying around of stuff, storage, etc. If we could decide during the `new` method whether we'll be used for encryption/decryption, things would be simpler.

(It also gets complicated with mbedtls which doesn't support round keys conversion from encrypt to decrypt out of the box) like axtls does)

What about adding an extra argument for that? Or that would break future uses of ucryptolib by a higher level crypto library that expects the PEP272 interface?

**Comment by Jongy** [comment]
>If we could decide during the new method whether we'll be used for encryption/decryption, things would be simpler.

Okay, I found a nice workaround in the code to handle this nicely (without changing the interface). Will create a new PR.

**Comment by dpgeorge** [comment]
The version of this from the pfalcon repository, which includes some additional changes to this PR, was merged in 567bc2d6ce18f55e7a1d2c8e023ead44f5c2cc45, see also 12fde67a2593447f12b3430efa10636f622d2dd8 for docs update.

**Pull request closed without merging**
