### PR TITLE
Travis CI: lint Python code for syntax errors

### PR DESCRIPTION
**Pull request by cclauss**
http://flake8.pycqa.org

Error codes: http://flake8.pycqa.org/en/latest/user/error-codes.html

### CODE REVIEW

**Comment by stinos** [comment]
This doesn't build due to Flake8 errors, would the plan be to fix those or to start adding exclusions in tavis.yml?

**Comment by cclauss** [comment]
I need someone who has better knowledge of the codebase to guide me on which ones should be fixed and which should be suppressed.

**Comment by stinos** [comment]
Well, the ones like `F632 use ==/!= to compare str, bytes, and int literal` which occur in the tests for `is` etc should definitely be supressed since those are intentional. Likewise for the REPL tests.

That uniflash.py file on the other hand looks a bit troublesome indeed: it doesn't parse here (using Python 3.7) so the reported error is correct, it has some stylistic issues (space after function name, using `==` for comparing `None`) but also another error: it uses `ProcessException` which isn't defined. I assume Flake didn't report the `ProcessException` problem because it cannot parse the file, however you should verify that's really the case: imo if we'd add linting, it should really be able to catch those errors else it's not all that useful.

Sidenote: uniflash.py also has at least one runtime error (line 56 concatenates str with None) and all in all the only thing it does is calling a .bat file with the supplied arguments so I'm not sure if that is much better than just calling the file directly. As such the fix could be to just get rid of the file :)

Can you also change your commit message so that the format is in line with other commits (see the history) and also add information about what Flake8 errors are tested for so people don't have to look that up manually?

**Comment by cclauss** [comment]
Awesome.  Thanks.

__F632 use ==/!= to compare str, bytes, and int literal__ issues will raise SyntaxWarnings on Python >= 3.8  https://docs.python.org/3.8/whatsnew/3.8.html#changes-in-python-behavior

When flake8 finds a syntax error it stops processing that file and moves onto the next one.

**Comment by stinos** [comment]
Ok. Probably shouldn't worry about Python 3.8, MicroPython isn't implementing that yet.

**Comment by dpgeorge** [comment]
I suggest to skip the `tests/` directory completely, if that's possible.

**Pull request closed without merging**
