### PR TITLE
add "default" keyword argument to min/max functions

### PR DESCRIPTION
**Pull request by pohmelie**
https://docs.python.org/3/library/functions.html#max
https://docs.python.org/3/library/functions.html#min

### CODE REVIEW

**Comment by pfalcon** [comment]
`max(seq, default=foo)` is equivalent to `max(seq) if seq else foo`. So, what's the point of adding more C code, if it's already easily doable without it?

**Comment by pohmelie** [comment]
@pfalcon 
1. Since micropython implements python 3.4, I think it is good to be as close to cpython 3.4 as possible.
2. It is standard min/max behaviour in 3.4. Why not to include this?
3. It is less than 10 lines of code.
4. It does not affect speed and memory.
5. 
> is equivalent to

It is not, cause `seq` can be lazy evaluated and then your construction breaks.
``` python
>>> seq = map(abs, range(0))
>>> bool(seq)
True
>>> max(seq) if seq else 0
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: max() arg is an empty sequence
```
I think a lot of useful python constructions can be dropped with argumentation as «it can be written by user», but this is way to javascript :laughing:

**Comment by pfalcon** [comment]
@pohmelie, when you submitted the patch here on github, you were pointed to https://github.com/micropython/micropython/wiki/ContributorGuidelines (i.e. expectation is that you already read it). It contains answers to all of your arguments.

**Comment by pohmelie** [comment]
@pfalcon 
Actually not. What about equivalent code?. Cause there is no possibility to write min/max function, which will use builtin min/max (since laziness), only rewrite min/max in python. And builtin functions became useless.
Now I read contributor guide, but my opinion does not changed. Firstly, this feature is not point to afraid to, cause it is tiny (of course tones of tinies counts). Secondly, min/max can be written in python, so why they are realized in c just partly? To be consistent this should be fully realized in c or fully realized in python. Why "key" argument exist, but "default" does not? Where is the edge?

**Comment by pfalcon** [comment]
> Cause there is no possibility to write min/max function, which will use builtin min/max (since laziness), only rewrite min/max in python. And builtin functions became useless.

Sorry, I don't understand what you mean here. It's possible to override any builtin function. So yes, if you like, you can rewrite it in python with full set of arguments.

> of course tones of tinies counts

Yup, half-bit is tiny, anything else isn't ;-).

> Secondly, min/max can be written in python, so why they are realized in c just partly?

That's how we do it, you'll find that everywhere. Don't use "obscure" features and you're good ;-).

> To be consistent this should be fully realized in c or fully realized in python.

No.

> Why "key" argument exist, but "default" does not? 

Because "key" is more or less chore to implement on user's side, while default can be handled with a single Python expression (not even a single line).

> Where is the edge?

Found in discussion. General presumption is "anything which can be not added, should not be added".

**Comment by pohmelie** [comment]
> Sorry, I don't understand what you mean here. It's possible to override any builtin function. So yes, if you like, you can rewrite it in python with full set of arguments.

I mean that only way to extend builtin method is:
``` python
def my_max(*args, **kwargs):
    if "default" in kwargs:
        default = kwargs.pop("default")
        try:            
            return max(*args, **kwargs)
        except ValueError:
            return default
    else:
        return max(*args, **kwargs)
```
But this is bad because of is someone raises `ValueError` in lazy evaluated, then you will see `default` as output without exception. So, can just rewrite whole min/max without builtins, but is it good? What for then we have builtin min/max?

> Don't use "obscure" features and you're good

What «obscure» did you find in `default`?

> Because "key" is more or less chore to implement on user's side, while default can be handled with a single Python expression (not even a single line).

It can't. As I said above. Only try/except, but this is not the good way. Please, show me the code of «single python expression».

> General presumption is "anything which can be not added, should not be added"

So why not to rewrite builtins (min/max) in pure python?

**Comment by pfalcon** [comment]
> But this is bad because if someone raises ValueError in lazy evaluated, then you will see default as output without exception.

So, do you really mean that you apply min/max to a generator or something? Even if so, as long as it's your code, you have freedom to rewrite it in any way possible.

> What for then we have builtin min/max?

To cover 99.9% usecases. It's not good idea to burden everyone's ROM size with something needed maybe by 1 in 1000 people.

> What «obscure» did you find in default?

I personally didn't know it's there, and even if I needed that functionality, I'd use if/else.

> So why not to rewrite builtins (min/max) in pure python?

As usual, the  right solution is usually somewhere inbetween, on the extremes.


So, you raised your case - applying min/max to iterators. I personally don't think it's worth to add so many bytes (how many exactly, there's figures?). Other folks may think differently. What I'd like though is minimal port binary size not growing. That means adding more #ifdef's. (#ifdef'ing entire min/max is the right way here).

**Comment by pohmelie** [comment]
> do you really mean that you apply min/max to a generator or something?

Yes

> you have freedom to rewrite it in any way possible

Of course I can rewrite min/max, but this not what I want.

> To cover 99.9% usecases

I think it's not 99.9, since it is done in cpython and this is the only way to deal with iterators/generators.

> I'd use if/else.

You can't, since iterator/generator is `True` always.

> #ifdef'ing entire min/max is the right way here

This should be the first answer :) I will come back with #ifdef's

**Comment by pfalcon** [comment]
> I think it's not 99.9, since it is done in cpython and this is the only way to deal with iterators/generators.

That's why we have "django criteria" in contributor's guidelines - if you can show that 3rd-party packages use it regularly, that's good argument.

> This should be the first answer :) I will come back with #ifdef's

Please make sure these are separate commits.

**Comment by pohmelie** [comment]
updated

**Comment by pfalcon** [comment]
Let me just quote what's written above:

> (#ifdef'ing entire min/max is the right way here).

> Please make sure these are separate commits.

So, please just see if your new patch follows these recommendations.

**Comment by pohmelie** [comment]
Don't get it… min/max use min_max, I've override min_max. Why I need to ifdef min/max?

**Comment by pfalcon** [comment]
Based on the arguments above, and how it was done before. If something is not clear, feel free to ask for more details. 22ff397fb11fac323607ef2e51d81a4ed96c2c50, 282ca09f8e386f24e1e87acd3de93954b6a8035c, e2d44e30c77360789d6e7c1211b222f93b92e0df show examples how to do that. That should be the first commit in series.

**Comment by pohmelie** [comment]
Should this be turned off for minimal only (as for examples)?

**Comment by pfalcon** [comment]
Yes. As pointed above, the whole idea of this is to make sure that the minimal ports don't grow in size (shrink instead, indeed). So, default should on, only two minimal ports should override that to 0.

**Comment by pohmelie** [comment]
updated

**Comment by pfalcon** [comment]
Still not there, sorry. Let's go thru checklist again:

1. There should be 2 commits.
2. First commit should introduce MICROPY_PY_BUILTINS_MIN_MAX (sic!) config option, nothing else. This commit is immediately mergeable (as long as it's done correctly, examples are provided).
3. 2nd commit should add support for "default" argument, by applying minimal changes (duplicating function body isn't such way).

**Comment by pohmelie** [comment]
Oh, I see. You want switch for min/max, not for "default" keyword. Am I right?

**Comment by pfalcon** [comment]
Yes. The reason for that is that we already have probably one hundred config options. And we'll easily have another hundred as we progress. But if we add an option for each function's argument, we'll have a thousand, and that's not manageable.

Sorry for the confusion. With your original patch, you essentially had 3) in the list above, and I just asked you to add 2), which is half-dozen lines as you can see. Again, if my answers are too terse or unclear, please ask for details (I generally write them with the idea that more details can be seen by looking at the code itself and its change history - we keep it clean and easily reviewable, and ask contributors to do the same).

**Comment by pohmelie** [comment]
updated

**Comment by dpgeorge** [comment]
I'm ok with this as it is now.  Adding the default keyword adds 24 bytes on stmhal.

**Comment by pfalcon** [comment]
Good!

@pohmelie : If you want to make a completely perfect patch, you could add a testcase for new argument. See https://github.com/micropython/micropython/blob/master/tests/basics/builtin_minmax.py . Let me know if you're up to it, or I'll handle it later.

**Comment by pohmelie** [comment]
@pfalcon, I will try to add testcases.

**Comment by pohmelie** [comment]
Is it ok?

**Comment by pfalcon** [comment]
Yes, except you didn't add your original case of working with lazy iterable. I've added it as https://github.com/micropython/micropython/commit/36c6d2fa7dd01886e7fa781fb47f9cc4201ad115 - now that it's supported, we don't want it to regress ;-).

Great work, thanks!

**Comment by dpgeorge** [comment]
Good work guys!

**Comment by pohmelie** [comment]
@pfalcon, I did, but then I remove them, cause I don't really now can I use map/range/abs in tests. Maybe they can be disabled like min/max/filter etc.

@dpgeorge, thanks :wink:

**Comment by pfalcon** [comment]
>  but then I remove them

That was smart, because with my adding it, now build is broken (when running it with native codegen). I'll fix it. Generally, testsuite is intended to be run against "full" build, so you can assume that standard functions are available. But then, those are unittests, i.e. should test just one feature at time, and avoid pulling too much functionality into one test. So, it's a matter of compromise how to handle it. I'd like it to be there still, because that was the case your argued for.

**Pull request closed without merging**
