### PR TITLE
Pep 492 (async, await), take 2

### PR DESCRIPTION
**Pull request by dpgeorge**
Now that pep 492 is officially accepted for Python 3.5 I updated our minimal implementation of it for the new syntax.  We can merge this as a start to providing (already functional) async/await support.

I am keen to use async coroutines to implement "multitasking" on the pyboard and I think having a clean native syntax (the whole point of pep 492) will encourage this further.

We can update uasyncio to use the new syntax.

### CODE REVIEW

**Comment by pfalcon** [comment]
> We can update uasyncio to use the new syntax.

The promise was that new syntax should largely be compatible with old, at least for user code. So, what do you mean by "use the new syntax"?

> clean native syntax (the whole point of pep 492) will encourage this further.

Yes, clean native syntax which prohibits to write efficient code (by combining coroutines and generators). So, maybe let's first discuss to what extent, and how, we want to implement pep 492?

**Comment by dpgeorge** [comment]
> So, what do you mean by "use the new syntax"?

yield from -> await, @coroutine -> async def.

> So, maybe let's first discuss to what extent, and how, we want to implement pep 492?

I want people to be able to write tasks as such:

```python
async def task1():
    while True:
        # stuff
        await task_switch()

async def task2():
    while True:
        # other stuff
        await task_switch()

loop.schedule([task1(), task2()])
loop.run_forever()
```

This is already supported by the current PR and adds almost no overhead to the actual running of the scheduler.

**Comment by pfalcon** [comment]
Well, did you deliberately choose example which looks (and works) worse than in classic syntax? ;-)

~~~~
def task1():
    while True:
        # stuff
        yield
~~~~

So, pep492 requires prohibiting yield* in async def. Are you going to implement that? (Sorry, I don't look at the code - let's discuss requirements first). If not, are they still allowed? If yes, it's language incompatibility. Actually, if no, it's still language incompatibility, because errors are not caught ;-).

What about async for/async with - do we ever want those implemented?

**Comment by roger-** [comment]
@dpgeorge

Will there be a (minimal) scheduler builtin for those who don't want to use uasyncio?

**Comment by dpgeorge** [comment]
This PR is getting a bit stale and I don't have time to work on it in the near future.  Instead we should discuss how async/await will be implemented in uPy (if at all), what sort of compatibility we want, etc (as asked above by @pfalcon).  See #1329.

**Pull request closed without merging**
