### PR TITLE
Support 32-bit compilation on OS X Clang

### PR DESCRIPTION
**Pull request by jpochyla**
While 64-bit clang has been supported since #607, x86 still didn't work. This should fix that, although in a similarly hacky way.

### CODE REVIEW

**Comment by pfalcon** [comment]
@jpochyla : Please add as a separate commit change to .travis.yml to test this. See https://github.com/micropython/micropython/commits/travis-clang

**Comment by prusnak** [comment]
@jpochyla ping

**Comment by jpochyla** [comment]
@pfalcon I don't really understand the request, can you re-word it please? Should I commit to the travis-clang branch? Sorry about the delay btw.

I've just squashed the commits and edited the commit message a bit.

**Comment by pfalcon** [comment]
@jpochyla : Generally, for any change, we'd need to know that it works, and keeps working going forward. That's especially true for changes which not everyone uses or can/knows how to use. For example, I don't use MacOSX, far less its 32-bit support. So, I suggested that you tried to add lines required to test your change via Travis CI. It should be a separate commit. The branch listed above gives an example of similar changes for Travis CI (your Travis CI changes would go to it, but caveat is that that branch is broken, so maybe you'd be interested to investigate/fix it too).

**Comment by prusnak** [comment]
Pushed extra commit to trigger travis build. 

Build is fine , make test fails one test, but that's probably not related (works OK on real HW).

**Comment by pfalcon** [comment]
@dpgeorge : So are you ok with nlrx86.S, etc. changes from this PR? Please leave merging to me (.travis.yml changes should go to travis-clang branch).

**Comment by dpgeorge** [comment]
> So are you ok with nlrx86.S, etc. changes from this PR?

Yes it's ok by me.

Ideally we'd convert nlrx86.S to nlrx86.c (as was done with nlrthumb), but I don't think anyone has time for that :)

**Comment by prusnak** [comment]
@pfalcon Can we have this in as Damien is OK with the change?

**Comment by pfalcon** [comment]
@prusnak : Ok, by travis change should go to travis-clang branch. And I can't do required cherry-picking because @jpochyla's repo no longer has this branch. Nor yours has. Do you have this in a branch somewhere? If so, please re-push as a new PR.

**Comment by prusnak** [comment]
I can see the branch here: https://github.com/jpochyla/micropython/tree/osx-clang-32bit

**Comment by pfalcon** [comment]
Nevermind, I figured how to get it. Note that travis-clang branch is still broken and waits for people who care about clang build.

**Comment by pfalcon** [comment]
And thanks!

**Comment by pfalcon** [comment]
> I can see the branch here: https://github.com/jpochyla/micropython/tree/osx-clang-32bit

Weird, because it didn't seem to be there...

**Pull request closed without merging**
