### PR TITLE
py/objstr: implement bytes.hex() function

### PR DESCRIPTION
**Pull request by prusnak**
This commit implements `bytes.hex()` and `bytes.fromhex()` functions. I think these are very useful e.g. for education as teaching to use the `binascii` module when there is already a function for that in the standard library is wrong IMHO.

We could also add `hex()`/`fromhex()` to `bytearray`, but this is also not included in this PR.

Let me know what you think.

### CODE REVIEW

**Comment by prusnak** [comment]
Any ideas/opinions? Pointers how to implement `bytes.fromhex()` class method? Or what's the best way to add functions to bytearray?

**Comment by pfalcon** [comment]
> Any ideas/opinions?

Breaks CI, duplicates functionality already available, bloats the small language, violating its principles.

**Comment by prusnak** [comment]
I still do think that `foo = bar.hex()` is much more readable than `foo = binascii.hexlify(bar).decode()`.

**Comment by pfalcon** [comment]
It's easy to agree. But MicroPython's focus is still on the minimality.

Way to go forward with this patch would be to wrap it in a config option, as almost all things added nowadays should be. That should be an absolutely baseline requirement.

Beyond that, to have a "social contract" that it's not enabled for generic ports, which can be reused on large number of hardware targets, in an attempt to limit fragmentation of the platform.

That's still a big risk, so I personally would be wary of going that way. But I don't make decisions here any longer. (But I'm interested in avoiding to revert too much in my fork).

And maybe platform is already fragmented enough that just adding default-off features is not the biggest of evils...

**Comment by pfalcon** [comment]
Anyway, additional criticism: I never heard about bytes.hex() until this PR. It's just a CPython 3.5 novelty. Whereas binascii module has its 10-15 years history and well-known.

**Comment by pfalcon** [comment]
But it's hard not to see similarity with https://github.com/micropython/micropython/pull/3382 - there I also try to add readable/writable methods to classes, and is being told that there're other ways to achieve that effect.

And yes, I still think that adding stream.readbin()/stream.writebin() is useful thing to do, while bytes.hex() - not. There's no universal rule, each case may need individual attention. The difference to me cleat:

1. stream.readbin()/stream.writebin() allows to easily and beautifully write parsers/generators for hundreds and thousands of protocols/binary formats.
2. While bytes.hex() is limited only to "education and teaching", which aren't even the intended use for MicroPython (CPython is there already), and interactive use (feel free to define a helper func yourself). The portable apps would still use binascii module.

Also funny that CPython dudes could overload hex() builtin for bytes. But nope, they went to add a new method...

**Comment by pfalcon** [comment]
And yep, ubinascii.hexlify() can work with any buffer, whereas this is a thing in itself. It seems cute when standing alone, but when multiplied to work across more types (still not all!), when reverse transformation added, it will turn into real bloat.

**Comment by dpgeorge** [comment]
> I still do think that `foo = bar.hex()` is much more readable than
> 
> `foo = binascii.hexlify(bar).decode()`

I agree, it is much nicer to use built-in methods than a separate module.  But we do have to be conscious of code size, especially if the functionality already exists.

Thanks for the contribution but I'll close this PR, because:
- functionality already exists
- there has not been further interest in it
- if it were going to be included (eg because there was lots of interest), then it would need to be reimplemented by reusing the existing code in `extmod/modubinascii.c` (to minimise total code size)

**Comment by jimmo** [comment]
> * if it were going to be included (eg because there was lots of interest), then it would need to be reimplemented by reusing the existing code in `extmod/modubinascii.c` (to minimise total code size)

See https://github.com/micropython/micropython/pull/7539

**Pull request closed without merging**
