### PR TITLE
esp8266: Fatfs API.

### PR DESCRIPTION
**Pull request by hosaka**
Following the discussion at #1483.

### CODE REVIEW

**Comment by dpgeorge** [comment]
What functionality does it provide?  You haven't exposed any new functions to the Python side.

**Comment by alex-march** [comment]
@dpgeorge: It provides the API to the flash IO, using fatfs lib. There aren't any new functions, indeed. Discussing this at #1483 I decided to separate the development of the python functions (probably the moduos and first filesystem init) and the API itself. These functions just allow write/read the sectors to flash. Perhaps they do not need to be included in the compilation just yet, that's why I separated the commit with Makefile and linker which can be omitted. If this poses no interest at all, you can close the PR and I will continue until some user side functions are also available.

**Comment by dpgeorge** [comment]
Ok.  It's a bit hard to review just by looking at the code, I would need to execute it to see what's going on.

One thing I notice is that you have 4k sectors, and 16 of them (to give 64k of space).  This might not be enough for a fatfs.  With the ramfs test that I have, it has 64 of 512-byte sectors, and fatfs uses 34 of those sectors just to write the fat and initial directory structure when making the fs for the first time.  You might need to implement 512-byte sectors using a RAM-caching mechanism.

Also, selecting 4k sectors mean that *all* fat filesystems that you mount must use 4k sectors, and the FATFS structure needs a 4k buffer.  So if you have /flash and /sd then that's 8k to buffers.

So I'd recommend trying to make it 512 byte sectors.  But then you'll anyway need a 4k buffer cache, or will have to come up with other tricks.

How does Lua do it... what size sectors?

**Comment by pfalcon** [comment]
Lua uses randomly selected flash filesystem: https://github.com/pellepl/spiffs . Well, not completely random, it had the right license ;-). But I had it in my stars before it was picked up by esp8266 - surveyed it for its usage for micropython, and at that time I concluded that it's underfunctional, unknown one-man toy project which unlikely was tested enough and thus will be quite a chore to use. But it had right name - if esp8266 uses SPI flash, and there's "spiffs" that's what gotta be used on esp8266, right? And it seems that usage gave it quite it boost, with almost 100 stars and 10 contributors. Alas, it didn't deal much with the functionality, because it's still:

> Presently, spiffs does not support directories.

**Comment by alex-march** [comment]
Sure, there's not a lot going on with it though as you say, it's just a start on the fatfs port.

The 4k sectors are set by the SDK includes, lua uses same sector sizes but with different file system entierly, reads and writes in 4k too. And yes, running f_mkfs will fail when checking how many sectors are available. My understanding of the internal flash structure was wrong, as @pfalcon pointed out, we're not limited to 64kb of flash. And once I figure out how much space we can utilise after upy image is flashed, I will update the sizes and take on board what you suggested, keeping the sectors at 512 bytes but caching the data into 4k buffers. As of now, the functions can freely manipulate any sector, including erasing the upy data.

**Comment by dpgeorge** [comment]
The reason we use fatfs for stmhal is because the block devices can be mounted by a PC.  But since esp8266 doesn't have that, it can use any fs, even spiffs.  And maybe something like that makes sense, because fatfs uses a lot of blocks just for the meta data.

@alex-march ignoring fatfs for now, if you can provide efficient (in RAM) functions to read/write 512-blocks of flash, then that's all that's needed.  The rest (fatfs, user filesystem, mounting, etc) follows easily from that just by coping stmhal's code.

**Comment by alex-march** [comment]
The esp modules, although mostly 512kb flash, cant have a maximum of 4Mb, according to the manufacturer. So it would make sense to keep fatfs in place, once larger modules are more available meta data blocks shouldn't be a problem, just my thought of course.
@dpgeorge: Okay, sounds good to me. Will work on that next and update the PR.

**Comment by turbinenreiter** [comment]
The NodeIT is an esp8266 that will come with 4Mb of flash and a microSD card expansion board via SPI. So it sure will be useful.

**Comment by alex-march** [comment]
More updates on the fatfs: Reading/Writing in increments of 512 bytes now works as we discussed. Any review comments would be very appreciated.

@dpgeorge: Using your cc3200 as example, I have implemented a similar way of writing chunks of 512 bytes with 4K cache. I have started the implementation in a separate file and it grew bigger so I left it as it is. The sflash_cache file simply contains all operations relevant to the 4k cache buffer. I can, if necessary, merge all implementation into one file, just like cc3200/sflash_diskio.c. Or opposite, further encapsulate the cache functions to have a more generic buffer that doesn't have calls to ESP APIs and leave it separated.

A quick test that I used to verify flash i/o access, also in my dev branch [esp8266/main.c](https://github.com/alex-march/micropython/blob/esp-fatfs-dev/esp8266/main.c#L70)
The HAL printf function is in also in [esp_mphal.c](https://github.com/alex-march/micropython/blob/esp-fatfs-dev/esp8266/esp_mphal.c#L91)
```c
void sflash_test_io(void) {
    BYTE data[5120];
    memset(&data[0], 0xDE, 1024);
    memset(&data[1024], 0xAD, 1024);
    memset(&data[2048], 0xBE, 1024);
    memset(&data[3072], 0xEF, 1024);
    memset(&data[4096], 0xBB, 1024);

    disk_initialize(FLASH);

    // try writing some data, it should be the same as read data
    if (RES_OK == disk_write(FLASH, data, 104, 10)) {
        if (RES_OK == disk_read(FLASH, data, 104, 10)) {
            mp_hal_stdout_tx_printf("data buffer result: 0x");
            for (int i = 0; i < sizeof(data); i+=1024)
            {
                mp_hal_stdout_tx_printf("%02X", data[i]);
            }
            mp_hal_stdout_tx_str("\r\n");
        }
    }
}
```
Using two separate buffers instead of read/write into the same one also runs as expected:
```
>>> data buffer result: 0xDEADBEEFBB
```

**Comment by pfalcon** [comment]
> One question that I have so far is: Writing to flash only seems to work when the sector is erased beforehand, although I've had situations when it worked without. Does it have to be erased? @pfalcon

Of course, that's how flash works: to write new content, it needs to be erased first. And erase blocks are usually bigger than write blocks. Underlying technology is however such that default bit state is "1", and by "writing", it goes to "0". So, it should be possible to write more 0 bits over already written data, but not 1's (erase "writes" all 1's over block).

**Comment by alex-march** [comment]
@pfalcon Thank you for the explanation!

**Comment by pfalcon** [comment]
> upd: mkfs/mount/f_read/write and friends are also working, I can create and read from files. The only thing that I missed is the ioctl block size return needs to be set to 1. Just like in the cc3200.

So, do you say that this code is fully working and ready to be merged? Please also add really new information as new comments, there're no github notifications for edits, so it's easy to miss.

**Comment by alex-march** [comment]
I tried to avoid posting every minor update as a separate comment, otherwise I'd be talking to myself! There's one change that I would like to add, changing the ioctl block size return and it's ready to be merged. Additionally, the read/write functions need to have a sector offset. From our previous discussion, I tried dumping the memory and examining the earliest empty sector to fit the fs. Currently I'm using sector 104 but I am not sure if it's the best choice.

I will soon start porting other os python functions and open a separate PR.

**Comment by pfalcon** [comment]
> Currently I'm using sector 104 but I am not sure if it's the best choice.

Using any hardcoded sector number is mistake. It all should be configurable, and with the current state of esp8266 port (pre-alpha), better configurable by a user.

> I will soon start porting other os python functions and open a separate PR.

If you target all this for merging upstream, I'd like to ask you to be considerate what you do and how. "Other os python functions" were already implemented. There's no need to implement them again for each and every port - that's too time consuming and the result is unmaintainable. Instead, we should make what's already implemented be reusable for other ports.

For example, with this patch, there already would be a question why you didn't follow suggestion to implement filesystem support via http://docs.micropython.org/en/latest/library/pyb.html#pyb.mount and instead preferred to add ~900 lines of C code.

**Comment by alex-march** [comment]
> It all should be configurable.

I agree, it should be automatic and perhaps determine available space for the start of the filesystem, also taking into account different flash sizes, like nodemcu does. I'm merely saying that it's working as it should if I start in that sector. How the sector should be decided is another issue, all there is now, is one #define that acts as an offset for read/write/erase functions.

Of course, there's no need to have the exact duplicates for separate ports and what's previously been written should be reused. How this should be made possible, is something I would like to consult you and other developers on. With regards to the fs implementation, I don't recall suggestions for what you're referring to in particular. While the ~900 lines just add the fatfs layer and make it usable for user functions, I thought of it as a good starting point for fs support on ESP since it didn't exist at all.

**Comment by pfalcon** [comment]
> With regards to the fs implementation, I don't recall suggestions for what you're referring to in particular. 

https://github.com/micropython/micropython/pull/1483#issuecomment-147389766

> How this should be made possible, is something I would like to consult you and other developers on.

It's not easy (to even come to agreement what and how to do), but we're working hard on that in #1430, #1550, #1552, #1553. The sadder to see, that while we work hard to avoid duplicated or misplaced code somewhere, more duplicated code is proposed to be added elsewhere. Pay special attention to #1552 - the code which was written by someone once, now proposed to be removed. Why? Because that code was done for the benefit of particular port, and provides zero benefit to *MicroPython*. I don't know if I mentioned it, but *all* the code in current esp8266 port is in my list for removal (or complete rehashing).

> While the ~900 lines just add the fatfs layer and make it usable for user functions, I thought of it as a good starting point for fatfs support on ESP since it didn't exist at all.

Just to set scale right - 900 lines is much of code. 100 lines is ok. And indeed it's that dilemma - there's no fatfs support for esp8266, so of course it's valuable. And yet it's immediately goes in some folks' list of "to be removed later". Guess it's not ideal situation, perhaps it would be much better if code was added to both further a specific port *and* MicroPython as a whole. Just think that @dpgeorge didn't really have to implement http://docs.micropython.org/en/latest/library/pyb.html#pyb.mount - pyboard already had C code for fatfs, he did that to let easily add filesystem support in Python, and other ports would be firstto benefit for that.

And final word - that's all just my opinion, don't let that stop of frustrate you. You of course can have your own opinion, just hope that you considered choices above.

**Comment by alex-march** [comment]
Okay, I can see your point and by no means your comments frustrate me, figuring out the best solution is the objective of a healthy argument after all.

It is true that as the project evolves, some contributions will go to the "remove list" inevitably. But I don't view it as a major issue, because with constant changes something is bound to be removed. In an ideal scenario, we wouldn't have to write port-specific implementations. If the aim of micropython is to run on multiple targets, duplication, redundancy and more maintenance can be expected, to a reasonable extent of course. But that's my personal opinion.

I admit that at the time of your comment I didn't fully understand that you were referring to pyb.mount and I wasn't aware of it's functions. I shall look further into it and might attempt a different solution. In the meantime, we need to decide what to do with this patch, out of ~900, around ~500 are probably comments that came from fatfs templates and license text.

**Comment by pfalcon** [comment]
> I admit that at the time of your comment I didn't fully understand that you were referring to pyb.mount and I wasn't aware of it's functions.

Well, so I would hope that you'd ask for clarification if something is unclear. Another point is that we already have too much functionality, and trying to understand it is sometimes better than adding more (which other people again will miss).

> In the meantime, we need to decide what to do with this patch, out of ~900, around ~500 are probably comments that came from fatfs templates and license text.

As usual - if you sign off that this provides something real-world useful and barring specific suggestions for improvements, someone will need to test this (exact test instructions will help), ack, and then it will be merged.

**Comment by mianos** [comment]
Alex, I have been looking at the linker scripts and a few of the variables and am also trying to work out a definitive answer to what segment the user flash should start. It seems to be set to an arbitrary #define in most places and quite a few different values. Theoretically the linker script could set a value once the segment is built. Worse case a config variable would be OK but I am not sure that is a proper solution to preventing the flash writing from smashing something else.

**Comment by alex-march** [comment]
@mianos Agreed on that. If the linker script can set this up, this would be an ideal solution. Also will help to avoid all the ifdefs for various ESP boards with different flash sizes.

In the meantime, I have started working towards a more generic solution as suggested by @pfalcon but might need someone elses input regarding the portability of stmhal user mounting. Details are in 4eb78f7.

**Comment by dhylands** [comment]
I took another look as fsusermount.c and it looks pretty portable. It really just needs a python object which supports a few methods:
https://github.com/micropython/micropython/blob/master/stmhal/fsusermount.c#L71-L74

I would say that fsusermount.c is definitely a candidate for being moved out into lib, probably even lib/fatfs

**Comment by danicampora** [comment]
I agree with the user mount part. Take a look at this other one too: https://github.com/micropython/micropython/blob/master/cc3200/mods/moduos.c#L137

**Comment by alex-march** [comment]
The last comment includes qdefs and fsusermount.c in the build. My only questions are regarding the stmhal/ffconf.h and diskio.c. Is it possible to reuse them for other ports, such as this? Currently it isn't because RTC/STM_HAL includes. SImilar with ffconf.h, the configuration can definitely be generic across the ports, with individual settings in mpconfigport.h. For example I need to disable the multi partition setting.

**Comment by pfalcon** [comment]
> SImilar with ffconf.h, the configuration can definitely be generic across the ports

Of course it can be. And proposing patches how to achieve that is the best way to proceed. As usual, patches should be optimized for size (if there's a desire for quicker turnaround of course).

**Comment by alex-march** [comment]
Well, rebase is indeed dangerous. I'll reopen a new PR when I tidy everything up. Apologies for the mess.

**Comment by pfalcon** [comment]
It's not, but one needs to have some practice ;-).

**Comment by alex-march** [comment]
Moved to #1626.

**Pull request closed without merging**
