### PR TITLE
DFU Byte alignment for L476

### PR DESCRIPTION
**Pull request by rolandvs**
(1) Some time ago I experienced problems while loading the `STM32L496RG` using `dfu`. In search of a solution (see also [stm forum](https://community.st.com/thread/37026-dfu-fail-verify-8-byte-align-magic) more people had this experience using `dfu-util`. Thanks to @dhylands who provided me with a patch for `../tools/dfu.py` which is included in this PR.

(2) In `..py/mkenv.mk` the setting `PYTHON=python` enforces the use of the system wide `python 2.xx` (PEP394). I suggest to change this to `python3` instead as "we" would like to move away for python2 and it is the preferred way to call `python3` and not rely on setting a __link__ yourself or use __virtual environments__.

(3) The `pydfu.py` reports an used function as depreciated, so I changed it to use the new one.

As they are related I put them together in this PR.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Re point 1: it looks good, but I guess it might add 4 bytes extra to all dfu files, even non-L4 targets?

Re point 2: this is related to (a duplicate of?) #1616.  We need to provide support for Python 2 because it's still widely used, and all the support scripts in this repo should run on Python 2 and 3 (is there something that doesn't?).  You could set the PYTHON variable on the make command line, or we could allow this setting to be overridden in a custom `makefile`/`GNUmakefile` by defining `PYTHON ?= python`.

Re point 3: that looks ok, but do you know if `getfullargspec` is supported on older PyUSB versions?

**Comment by rolandvs** [comment]
On (2) Interesting read #1616. As far as I know python2 is supported until 2020 so why not change now? Using OSX will always come up with the (older) OS version when typing `python` and you are advised to install your own versions with your own libraries separated from the OSX version.

I can live with the command line addition `PYTHON ?= python3`.

On (3) I try to use the release (usually you get the latest version by default through pip/brew/ whatever). Then try to fix it if it is wrong. IMHO - my suggestion would be to let people upgrade their environment and not always try to support all versions, not withstanding my deepest respect for people who spend their precious time to make it work in all situations.

**Comment by dpgeorge** [comment]
> It will add enough bytes to align it to 8 bytes. This will only affect the DFU file.

Ok, thanks for clarification.  I merged that patch in 6e50df4e21f13dc62858afbb927e563b721433b8

> On (3) I try to use the release (usually you get the latest version by default through pip/brew/ whatever). Then try to fix it if it is wrong.

I have an older v1.0.0 pyusb and it works ok for me, so I merged this patch in feec0a6909c00ebf0df3250fabaaf10bff73614b

> I can live with the command line addition PYTHON ?= python3.

I'd prefer this option to forcing python3.

**Comment by dpgeorge** [comment]
@rolandvs a much simpler way to provide Python 2/3 compatibility would be to use something like this:
```python
getargspec = getattr(inspect, 'getfullargspec', inspect.getargspec)
if getargspec(...):
    ...
else:
    ...
```

**Comment by rolandvs** [comment]
@dpgeorge - Burned the "other" solution :-)

**Comment by dpgeorge** [comment]
Thanks @rolandvs , the patch to get Python 2 working again with pydfu.py was merged in 11a38d5dc5365c9fa1d3edc05f948e21293ce127

**Pull request closed without merging**
