### PR TITLE
ports/rp2/machine_i2s.c: Detect and deinitialize I2S instances on boot.

### PR DESCRIPTION
**Pull request by marecl**
In reference to #14339  

`machine_i2s_init0` makes all of these pointers NULL without checking if there was a pointer already. Furthermore, garbage collector doesn't care enough to call `I2S.deinit()`.
This created an issue, where invoking `machine.soft_reset()` would hard crash an entire board.  
Fix is a check if `machine_i2s_obj` contains an object (assumed to be a valid `machine_i2s_obj_t`). If memory address is not NULL - object gets deinitialized. No further crashes are observed.

### CODE REVIEW

**Comment by dpgeorge** [comment]
> Furthermore, garbage collector doesn't care enough to call I2S.deinit().

To fix that, finalisers should be enabled on the I2S object on all ports, following how esp32 does it.  That requires two things:
1. Remove the `#if MICROPY_PY_MACHINE_I2S_FINALISER` guard from `extmod/machine_i2s.c`.
2. Make rp2, stm32, mimxrt ports all use `mp_obj_malloc_with_finaliser()` instead of `mp_obj_malloc()` in their `mp_machine_i2s_make_new_instance()` implementations.

**Comment by robert-hh** [comment]
If you do not want to follow the recommendation of Damien, this deinit should better be placed at the end of main() between the label `soft_reset_exit:` and the call to `gc_sweep_all();`.  At that point the I2S data structure is still intact and `mp_machine_i2s_deinit()` can be called safely. After `gc_sweep_all()` has run, all allocated data elements can not be considered any more as valid, which includes the I2S object and it's buffers. So they must not be used in machine_i2s_init0(). You might have to create a function like `machine_i2c_deinit_all()` in machine_i2s.c which is called at behind label `soft_reset_exit:` in main.c.

**Comment by marecl** [comment]
> If you do not want to follow the recommendation of Damien, this deinit should better be placed at the end of main() between the label `soft_reset_exit:` and the call to `gc_sweep_all();`. At that point the I2S data structure is still intact and `mp_machine_i2s_deinit()` can be called safely. After `gc_sweep_all()` has run, all allocated data elements can not be considered any more as valid, which includes the I2S object and it's buffers. So they must not be used in machine_i2s_init0(). You might have to create a function like `machine_i2c_deinit_all()` in machine_i2s.c which is called at behind label `soft_reset_exit:` in main.c.

I'll work on this, just don't have a lot of free time. I'd rather go with Damien's solution as it seems more appropriate and portable. I don't have other devboards, so most likely fixing it globally (like calling `__del__` or `__exit__`) would free us from meddling with hardware.

**Comment by dpgeorge** [comment]
This was fixed differently in d2e33fe3096eec60d7017b0f17c4ddb6910a4d0b

**Pull request closed without merging**
