### PR TITLE
esp8266: fatfs development

### PR DESCRIPTION
**Pull request by hosaka**
Hi,

I've been trying to port the existing fatfs to esp and wanted to report some progress. I was following what has been done in nodemcu before and code is somewhat based on that. I will be keeping this PR as a general progress bar and most likely create a clean branch when and if the work is complete.

Once the sflash_diskio/diskio APIs are completed, would it be better to create a separate fs.c/h to expose the functions to other upy modules (os)? I have been using cc3200 file layout until now.

### CODE REVIEW

**Comment by danicampora** [comment]
> Once the sflash_diskio/diskio APIs are completed, would it be better to create a separate fs.c/h to expose the functions to other upy modules (os)? I have been using cc3200 file layout until now.

Please note that the CC3200 is special because there's no direct access to the serial flash, we have to go through TI's filesystem. Besides that, no, you don't need separate fs.c/fs.h, you only need what you see in this directory: https://github.com/micropython/micropython/tree/master/cc3200/fatfs/src (minus the SD card part).

**Comment by alex-march** [comment]
@danicampora Thanks for the advise. I did notice the TI calls while reading the code, so far I have the fatfs/src structure the same way as cc3200, apart from the sdcard (maybe one day).

**Comment by alex-march** [comment]
I'm having some issues with calling filesystem functions (f_mkfs for example) in the esp init, which overflows the text segment. Is it possible to use the ICACHE_FLASH_ATTR with fs functions to avoid this?
```
xtensa-lx106-elf-ld: build/firmware.elf section `.text' will not fit in region `iram1_0_seg'
xtensa-lx106-elf-ld: region `iram1_0_seg' overflowed by 1484 bytes
```

**Comment by dpgeorge** [comment]
See esp8266/esp8266.ld, starting line 82.

**Comment by alex-march** [comment]
@dpgeorge Thank you, that helped!

**Comment by alex-march** [comment]
After having read some more nodemcu/smart.js/spiffs code, is it correct to assume the following is correct? 
For example, on a 512k flash size ESP:
Total blocks: 8
Block size: 65536
Total sectors: 128
Sector size: 4096
Sectors per block: 16
ESP parameter sectors: 4 (last 4, 128 - 4)
Usable flash size: (124 * sector size) 507904

_MIN_SS in ffconf.h also needs to be set to 4096. Unlike in spiffs, where you set your total fs size, address, block sizes and you're good to mount it, in fatfs it should be implemented as a part of the API between the diskio and the SPI flash?

**Comment by pfalcon** [comment]
@alex-march: I'd recommend starting from the beginning and implement function to read given number of sectors, starting from given sector number (or linear sector address? using sector numbers would allow to address bigger flashes). Then play with it, making sure you understand real flash layout. Then once you get comfortable, implement sector writing and again test it. After that, I believe @dpgeorge implemented a way to instantiate fatfs from userspace with arbitrary parameters, and it just should work automagically. And only as the last step, they can be thinking about having some predefined file systems with predefined bounds by default.

**Comment by alex-march** [comment]
@pfalcon: Thanks for your reply. I have SDK functions for read/write/erase wrapped in already. The user addresses the sectors from 0 to 16 and the drivers adds the sector offset and the size. Let me quickly sketch the picture for the 512Kb flash and what I'm trying to do.
512kb-flash-layout
As of now, the driver functions are working fine on their own, I can write and read back the data from either of those sectors. Using the fatfs API only works if I change the min volume size to 16 like I mentioned, but there is an issue somewhere when I try to read back the file. I am testing the code from the main but keeping it outside of the dev branch. As you said, there's no need to consider predefined FS before having the API working. So would be great to confirm with others if I'm on the right track.

**Comment by pfalcon** [comment]
> I have SDK functions for read/write/erase wrapped in already. 

Then please submit them for review and potential inclusion into mainline.

> The user addresses the sectors from 0 to 16 and the drivers adds the sector offset and the size. Let me quickly sketch the picture for the 512Kb flash and what I'm trying to do.

Ok, so where would start? Well, please apply critical thinking to anything you read in Espressif SDK docs or on a forum. There're 2 levels of knowledge: something which applies to ESP8266 chip (and other chips) and something which is built (more or less arbitrarily) on top of that. We're interested in 1st kind of knowledge, and mostly not interested in 2nd kind. Or let me put it like: I'm personally interested in it just for reference, and see no reason why it would be different for you. MicroPython doesn't use all that OTA update mumbo-jumbo and associated arbitrary conventions as drawn on a picture.

So, scratch that picture. Flash organization for esp8266 is: it starts with few structured segments which get loaded by bootrom into ram. Then esp8266 has ability to map SPI flash into address space for code execution. So, there's another code segment (no additional structure, i.e. headers). It can be anywhere in flash, but common sense says it should be packed close to the RAM structured segments. So, that what lies at the beginning of flash. At the end of flash, bootrom and wifi code use couple of sectors to store settings. That's all. Anything inbetween belongs to anyone, and anyone can build anything there. Espressif for example builds OTA update scheme. But you don't need to build anything there, and uPy port doesn't. And all that space is usable for filesystem for example.

That's why I suggested to start with flash sector reading function and playing with it. It should not take sector number from 0 to 15, it should take sector number as defined by flash. You should not believe what I say above, you should be able to read any arbitrary sector and see it for yourself. Hope this helps ;-).

**Comment by alex-march** [comment]
@pfalcon That's very helpful, thank you. I was under the impression that the upy layout was similar, leaving only a 64Kb chunk, I know better now. I understand that from upy point of view we're not interested in the Espressiff flash structure such as OTA and other bells and whistles. For now, I will experiment with addressing all sectors using the API that I have. In the meantime, I will continue to work on generic driver until it looks a more solid and will open a separate PR, this was purely for discussions sake. Благодарю!

**Pull request closed without merging**
