### PR TITLE
Port for Mikroelektronik CLICKER2 board

### PR DESCRIPTION
**Pull request by rolandvs**
Port for a `CLICKER2` board of mikroelektronik.
I did this a long time ago and updated it to the last version of micropython.

Next to the usual suspects, added a `modules` and `docs` directory, a **local** **linker** file for the STM32F407 due to a different use of the memory. Also use the extra sector 11 for additional `/flash` disk storage and detected an hidden error (see #3884).

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.  It looks like you got this board working quite well.  But at this stage I would not be comfortable merging this to master because it will give the impression that these boards are officially sanctioned/supported.  For now it can stay as a PR.

**Comment by rolandvs** [comment]
@dpgeorge I have no problem with that :-) I'll also put it on my repo (just the delta) so others could use if they like it.

**Comment by dpgeorge** [comment]
> But what would be the criteria to add a board?

The main two items are: 1) easily obtainable by the public; 2) can be maintained (on the software side) for a long period of time.  Admittedly some of the boards there at the moment don't satisfy these requirements (eg, AFAIK, LIMIFROG is out of production) but they were added quite some time ago.  The main boards are the pyboards and the ST Nucleo/Discovery boards.

**Comment by dpgeorge** [comment]
> if a board would be open-source and fully documented (layout/schematic) would that fit the criteria (1) too?

Well, ideally you'd be able to purchase the board from somewhere.  But I can see the benefit of having a semi-official board that can be manufactured at home, for those that like to follow such a path.

> In this pull request I added a label to make the extra block of memory available ... 
> Would that be something of a PR or just an ISSU

Isn't that what #3884 is about?

**Pull request closed without merging**
