### PR TITLE
stmhal: f7: Fix recent RTC to build on F7

### PR DESCRIPTION
**Pull request by dhylands**
Does it make sense to add STM32F7DISC to the travis build?

### CODE REVIEW

**Comment by dpgeorge** [comment]
Merged in 165734522ee48f4452125d9c56b1a9e41d24f630.

> Does it make sense to add STM32F7DISC to the travis build?

Maybe.  It won't slow it down by much.

**Comment by chuckbook** [comment]
@dhylands 
Better use 
        HAL_PWR_EnableBkUpAccess();
instead of
        PWR->CR |= PWR_CR_DBP;

**Comment by dpgeorge** [comment]
Isn't it the same thing?  And saves a function call.

**Comment by chuckbook** [comment]
just to get rid of conditional compiles

**Pull request closed without merging**
