### PR TITLE
modussl: SSL socket wrapper module based on axTLS. Enabled for unix port.

### PR DESCRIPTION
**Pull request by pfalcon**
WIP

### CODE REVIEW

**Comment by pfalcon** [comment]
This is preview of ussl module, without axtls port. The latter is in very dirty state and will take bunch of time to clean for pushing, and it probably will stay dirty for a long time after that. But otherwise this increases x86_64 binary size by 21840 bytes, and x86_32 by 22220. That's on par with highly optimized commercial I read about (well, they might include both client and server, this is only client). And while I spent enough time to optimize axTLS, it's clear there're more opportunity for optimization. So, let it stay dirty like that.

So, this review is mostly about how modussl is plugged into build framework. There's nothing yet how axtls itself will be built (it's going to be hacky enough).

**Comment by danicampora** [comment]
Cool, I will start prototyping the CC3200 ussl module very soon.

**Comment by dpgeorge** [comment]
Ok, it looks pretty clean from my point of view.  I see that ssl is really not special to sockets, rather it's a stream layer that takes a stream (anything that supports read/write) and turns it into an encrypted stream.  In Python you create the encrypted stream by: `ssl_stream = ussl.wrap_socket(stream)`.

Just to make sure I understand, the following is the chain of calls for a read: `ssl_stream.read -> stream.c:stream_read -> modussl.c:socket_read -> axtls:ssl_read -> modussl.c:mp_stream_posix_read -> stream_p->read -> <underlying stream read function>`.  That's pretty deep... but I guess there is no way around it.

Note that the CPython docs state that `wrap_socket` returns an object (ssl.SSLSocket) that has methods such as accept, bind, connect, recv and send.  But I see here that your return value from `wrap_socket` instead implements the stream/file methods read and write (and friends).  How is this compatible?

Also, how does axtls allocate memory; does it use malloc or a user-defined function?

**Comment by pfalcon** [comment]
>  I see that ssl is really not special to sockets, rather it's a stream layer that takes a stream (anything that supports read/write) and turns it into an encrypted stream. 

Yes, with a usual caveat of non-blocking streams. axtls actually does something weird with non-blocking sockets - there's a place where it blocks on them (via select). I'm not sure if it happens on all codepaths or just in special case, but that's unlikely right (well, unless it's done to prevent timing attack or something).

> Just to make sure I understand, the following is the chain of calls for a read:

Well, I didn't think about it like that, but yes, apparently that's how it is. It could be reduced by making some of those inline, which will require even more hacking, but otherwise, it's just like that.

> Note that the CPython docs state that wrap_socket returns an object (ssl.SSLSocket) that has methods such as accept, bind, connect, recv and send. But I see here that your return value from wrap_socket instead implements the stream/file methods read and write (and friends).

Well CPython docs say many things, e.g. that ssl.SSLSocket inherits from socket, and that's how it gets all the extra methods. We can't do that due to https://github.com/micropython/micropython/issues/1159. But then why limit it to be a socket subclass instead of being a proper stream wrapper, for pseudo-convenience of wrapping unconnected socket instead of connecting it and wrapping then?

> How is this compatible?

As usual, it's subset and called "ussl".

**Comment by pfalcon** [comment]
Merged in aaa8867d4a4a1274ea43429c00e8bdfa6b28a015 , except not enabled by default.

**Pull request closed without merging**
