### PR TITLE
ports/zephyr: Update to Zephyr 3.2.0.

### PR DESCRIPTION
**Pull request by bogdanm**
This commit updates the Zephyr port with the changes listed in https://docs.zephyrproject.org/3.2.0/releases/release-notes-3.2.html, specifically:

- Changed `#include <zephyr/zephyr.h>` to `#include <zephyr/kernel.h>`.
- Changed `FLASH_AREA_LABEL_EXISTS(storage)` to `FIXED_PARTITION_EXISTS(storage)`.
- Changed Bluetooth include paths from `bluetooth/` to `zephyr/bluetooth`.

Only minimal testing was done using a Nordic nRF5340-DK board (`nrf5340dk_nrf5340_cpuapp`): compile, flash, run some simple Python code), but the changes are cosmetic, not functional.

The commit was also tested to work with the recent Zephyr 3.3.0 release.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.  But see #9335 which does the same thing.  There is a discussion there about naming of peripherals, maybe you know how to solve it.

**Comment by bogdanm** [comment]
Apologies, I completely missed that one :) I wil take a look at the peripheral naming discussion there.

**Comment by bogdanm** [comment]
@dpgeorge Please let me know if you like the approach that I took in the latest commit above (https://github.com/micropython/micropython/pull/10830/commits/a9645943170bd9f1be45483e2ee83827adbd017b). If so, I will extend it to all the relevant modules (it only works for `machine_pin.c` right now) and I will include it in the original PR if needed. For reference, this is what the new script generates (`build/gen_dt_node_names.h`) for the nRF5340DK board:

```
#ifndef MICROPY_INCLUDED_ZEPHYR_GEN_DT_NODE_NAMES_H
#define MICROPY_INCLUDED_ZEPHYR_GEN_DT_NODE_NAMES_H

struct dt_node_name_map {
    const char *const gen_name;
    const char *const actual_name;
};

static const struct dt_node_name_map dt_node_map[] = {
    {"UART_0", "uart@8000"},
    {"I2C_1", "i2c@9000"},
    {"SPI_4", "spi@a000"},
    {"GPIO_0", "gpio@842500"},
    {"GPIO_1", "gpio@842800"},
   {NULL, NULL}
};

#endif
```

Tested succesfully with `west build -b nrf5340dk_nrf5340_cpuapp` and this code:

```
>>> from machine import Pin
>>> LED = Pin(("GPIO_0", 28), Pin.OUT)
>>> LED.value(1)
>>> LED.value(0)
```

**Comment by jimmo** [comment]
Thanks for this @bogdanm -- I added some comments relevant to this PR over at https://github.com/micropython/micropython/pull/10859#issuecomment-1447653246

**Comment by Ayush1325** [comment]
Maybe this should be closed in favor of https://github.com/micropython/micropython/pull/9335

**Pull request closed without merging**
