### PR TITLE
stmhal/hydrabus hydrabus tests

### PR DESCRIPTION
**Pull request by sylvainpelissier**
Add "XA", "XB", "YA" and "YB" uart names for hydrabus board.
Add SPI "X" and "Y" names.
Add hydrabus target.
Update SPI tests.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the PR, but we are actually trying to move away from board-specific tests to more generic tests that work on all boards.  So we won't be adding a specific "hydrabus" target in the tests (you are welcome to keep it locally, of course).  Also, unless hydrabus actually labels its UART and SPI with the names X/XA/Y/etc it doesn't make sense to label them like this in the config.  Those names should reflect what the board calls them.

**Comment by sylvainpelissier** [comment]
Thanks for your answer. How I can modify the tests to be generic and to have them passing on hydrabus board.

**Comment by dpgeorge** [comment]
> How I can modify the tests to be generic and to have them passing on hydrabus board.

For now, you can use the "minimal" target instead of "pyboard".

**Comment by sylvainpelissier** [comment]
I agree but for minimal target no pyb tests are run.

**Comment by dpgeorge** [comment]
> I agree but for minimal target no pyb tests are run.

pyb tests are specifically for the pyboard hardware.  What exactly are you trying to achieve with this PR?

**Comment by sylvainpelissier** [comment]
I wanted to have the pyb tests passing on hydrabus board to ensure that nothing is broken during low-level development.

**Comment by pfalcon** [comment]
@sylvainpelissier : The general idea is that MicroPython can be ported to very many boards (hundreds, thousands), and already ported to dozens. From that, following ideas come:

1. We can't have support for each board in the mainline.
2. Instead, there should be always-improving core which works across boards (requiring contribution from maintainers of individual board forks).
3. Beyond what's available in the mainline, everyone can maintain additional things in per-board forks.

So, there's "minimal" test target which is intended to work across various boards, down to the smallest ones. If you see opportunity, please contribute to that testsuite (again, it must work across boards!). Beyond that, feel free to maintain hydrabus-specific tests yourself.

**Comment by sylvainpelissier** [comment]
OK, thank you for clarification, I'll keep my own hydrabus specific tests separately.  You can reject this PR.

**Comment by sylvainpelissier** [comment]
If anybody interested, I uploaded my tests for Hydrabus: https://github.com/sylvainpelissier/micropython-hydrabus-tests

**Pull request closed without merging**
