### PR TITLE
esp8266: Add rudimentary user script flash support

### PR DESCRIPTION
**Pull request by atx**
So, this is the quick and cheap way to do it. I would like some input on whether this is a good path to take or some simple file system (FAT, spiffs...) should be used instead. Note that there is only about 15kB of code space left.

### CODE REVIEW

**Comment by pfalcon** [comment]
We have 640e0b221e972f9a2da2d870bf3fc5a93c18f0ec and https://github.com/micropython/micropython/pull/1005 already. I don't think we need yet another adhoc way to do it.

**Comment by atalax** [comment]
That should work. I am going to use the frozen modules instead then.

**Comment by roger-** [comment]
@pfalcon 

How would `pyb.mount()` work with the ESP's flash?

**Comment by pfalcon** [comment]
How do I know? Someone who implements it will tell. The point, each port should not try to invent its own stuff. Yes, it means refactoring existing stuff to be reusable across ports. But without doing it, it will be unmaintainable mess.

**Comment by roger-** [comment]
Okay, I thought it just need a Python class to work.

**Comment by dpgeorge** [comment]
@roger- you can now put scripts on the esp8266 using the "frozen module" support; put them in esp8266/scripts (see esp8266/scripts/main.py).

**Comment by baccrog** [comment]
@dpgeorge 

Awesome, thanks!

**Comment by roger-** [comment]
@dpgeorge 

Awesome, thanks!

**Pull request closed without merging**
