### PR TITLE
lwip: add support for raw socket type

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR adds support for `SOCK_RAW` sockets in `extmod/modlwip.c`, which means support for these sockets on esp8266 and stm32 boards (Ethernet and WiFi).

Raw sockets allow to implement things like ping in Python, see eg uPing: https://forum.micropython.org/viewtopic.php?f=15&t=5287

### CODE REVIEW

**Comment by Jongy** [comment]
Perhaps it should be made a compile-time config in `mpconfig.h`?

**Comment by dpgeorge** [comment]
> Perhaps it should be made a compile-time config in `mpconfig.h`?

I tried to minimise the extra code by reusing the UDP code where possible, but I didn't actually check code size increase.  I guess it does make sense to make it compile-time optional, since raw packets are only needed for advanced usage.

**Comment by Jongy** [comment]
I think the `IS_ENABLED` trick in Linux would really help here, since there are many `if` clauses which are only relevant if the feature is enabled.

If you'd like, I'd be happy to import the relevant header file from Linux into MicroPython, and to make use of it in this PR.

**Comment by Jongy** [comment]
> I think the IS_ENABLED trick in Linux would really help here, since there are many if clauses which are only relevant if the feature is enabled.

Actually, all configs are either `1` or `0` here (instead of either `1` or not defined at all) then the `IS_ENABLED` for MP is as simple is `if (MICROPY_...)` :)

**Comment by dpgeorge** [comment]
Ok, I've now made this configurable at build time via `MICROPY_PY_LWIP_SOCK_RAW`.

On esp8266 raw sockets cost 336 bytes of code, and on stm32 they cost 632 bytes.  I've enabled raw sockets on both these ports because I feel it's worth the cost.

**Comment by dpgeorge** [comment]
Merged in 80f5cef8d4937d1312a823a2a42c46b5140e5595

**Pull request closed without merging**
