### PR TITLE
Preliminary ESP32 documentation

### PR DESCRIPTION
**Pull request by mattytrentini**
Primarily focusing on the QuickRef, this PR adds a skeleton that can be built on for ESP32 documentation. 

It was copied from the ESP8266 docs and then modified appropriately. Note that more work is required for this documentation but at least it's a start that contains some updated details for ESP32 users.

### CODE REVIEW

**Comment by mattytrentini** [comment]
Please note that I had some difficulty managing the merge since the repository we started working from wasn't forked from mainline. However the list of files changed appears correct.

**Comment by dpgeorge** [comment]
Thanks very much for this!

Did you intend to add the tutorial files?

**Comment by mattytrentini** [comment]
I did, if that's ok? They're not being built into the docs because they weren't finished - but they did have some work invested in trying to update them for ESP32. It should make it easier to continue that work later.

I do understand that it would be nice to simply remove them. I'll leave it up to you!

**Comment by dpgeorge** [comment]
Ok, I managed to rebase this on top of master, it's pretty clean after ignoring all the commits outside the docs/ directory.

I see that the esp32/tutorial/ files are pretty much a direct copy of the esp8266 files.  Only 5 files out of 14 are changed.  4 of those that are changed (repl.rst, network_basics.rst, filesystem.rst, index.rst) have minimal changes, mostly to replace the word "esp8266" with "esp32".  The file intro.rst is significantly different.

Since the tutorial is mostly a copy of esp8266 and not really complete I don't think it should be merged here.  And ideally we'd use the same tutorial for both the esp8266 and esp32, they are similar enough chips (at least the functionality exposed by uPy is).  Having them the same would save a lot of effort maintaining it.

But the esp32's tutorial/intro.rst can be kept because it has useful information.

So my recommendation would be:
- keep only tutorial/intro.rst (and possibly tutorial/index.rst)
- refer users to the esp8266 tutorial at the end of tutorial/intro.rst, with a disclaimer that some things might be different on esp32
- reduce size of esp32 img in quickref from 700k down to 70k
- squash all commits into one commit

For the last point: there are 4 separate authors in this PR here for the esp32 docs.  If it's all squashed into 1 commit with all contributors mentioned in the git commit message body, is that OK with the authors?  Who would be the author of this single commit?

I'm happy to make the above changes and push as a separate PR for review.

**Comment by mattytrentini** [comment]
> Ok, I managed to rebase this on top of master, it's pretty clean after ignoring all the commits outside the docs/ directory.

Good, glad to hear I didn't cause you too much grief!

> [snip]
> So my recommendation would be:
> 
>     * keep only tutorial/intro.rst (and possibly tutorial/index.rst)
>     * refer users to the esp8266 tutorial at the end of tutorial/intro.rst, with a disclaimer that some things might be different on esp32
>     * reduce size of esp32 img in quickref from 700k down to 70k

This is all reasonable (and sorry about that last point; I had that on my todo list but it was forgotten).

>     * squash all commits into one commit
> For the last point: there are 4 separate authors in this PR here for the esp32 docs. If it's all squashed into 1 commit with all contributors mentioned in the git commit message body, is that OK with the authors? Who would be the author of this single commit?

I'll check with the other authors but I suspect that I'm probably the most appropriate choice - I pestered others to make the changes, it's only fair that I own supporting them!

> I'm happy to make the above changes and push as a separate PR for review.

Thanks, that'd be great. I'll reach out to the other authors tonight.

**Comment by mattytrentini** [comment]
@rprr @HowManyOliversAreThere @seanlano Do you folks mind if it's my name against the squashed commit? If we receive positive feedback I'll say you guys did the work, if it's criticism I'll take the blame! :)

**Comment by rprr** [comment]
Fine with me as well.

Ram

**Comment by seanlano** [comment]
> @rprr @HowManyOliversAreThere @seanlano Do you folks mind if it's my name against the squashed commit? If we receive positive feedback I'll say you guys did the work, if it's criticism I'll take the blame! :)

Fine with me @mattytrentini , unfortunately my contributions were very minimal, but thanks for the mention!

**Comment by dpgeorge** [comment]
I've made the changes suggested above and posted it as #4424.

**Pull request closed without merging**
