### PR TITLE
Update paths to be relative to $(TOP) defined in mpconfigport.mk.

### LINKED ISSUE #3628: examples/embedding does not build
When I try to build the example in `examples/embedding`, I get the following error:

```
..../micropython/examples/embedding$ make V=1
make -f ../../examples/embedding/Makefile.upylib MPTOP=../..
make[1]: Entering directory '..../micropython/examples/embedding'
make[1]: *** No rule to make target '../../unix/main.c', needed by 'build/genhdr/qstr.i.last'.  Stop.
make[1]: Leaving directory '..../micropython/examples/embedding'
Makefile:8: recipe for target '-lmicropython' failed
make: *** [-lmicropython] Error 2
```

### PR DESCRIPTION
**Pull request by talljosh**
This fixes #3628 for me.

### CODE REVIEW

**Comment by talljosh** [comment]
I may have been a bit hasty in this pull request. While it does fix the bug, it also broke the ability to embed from outside the micropython/ source tree. I've fixed that in this commit: https://github.com/talljosh/micropython/commit/3e00e359e25f1ca8fccd78420d2da54a8462dc5a. Should I submit another pull request?

**Comment by dpgeorge** [comment]
Thanks for the report and for the fix!

Can you please undo the initial changes you made to rename TOP to MPTOP (ie TOP shouldn't be there, it should be named MPTOP)?  Then your patch will be a lot smaller and still work.

You can keep this PR, just push the changes as another commit to the branch you're using for this PR.

**Comment by talljosh** [comment]
Done.

My original rationale for using TOP instead of MPTOP was that that's what `ports/unix/Makefile` does.

**Comment by dpgeorge** [comment]
Thanks for updating; rebased, squashed and merged in c2f4f36010c8636f837aa28028d9dd9a951959d5

> My original rationale for using TOP instead of MPTOP was that that's what ports/unix/Makefile does.

Yeah I understand, but I think it's cleaner to keep it as MPTOP within this particular Makefile so users understand what is going on.

**Pull request closed without merging**
