### PR TITLE
extmod/moductypes: Add calc_offsets() to automatically calc field offsets.

### PR DESCRIPTION
**Pull request by pfalcon**
This implements long-conceived function to automatically calculate offsets for uctypes structure definitions. This means that the order of field definition is important, and thus requires using OrderedDict for structure definition. And for that to continue having nice, convenient syntax, OrderedDict literal support, as was merged recently, is required.

There're also a couple of another commits implementing more features.

    To use this function, a structure descriptor should be done using OrderDict,
    and no offsets need to be specified, calc_offsets() will fill them in based
    on the layout type. For example:
    
    desc = OrderedDict((
    ("f1", uctypes.UINT8),
    ("f1", uctypes.UINT16),
    ))
    uctypes.calc_offsets(desc, ctypes.LITTLE_ENDIAN)
    
    While doing this, structure size calculation for native layout was also
    fixed - rounding up of structure size depends not on max field size, but
    on max field alignment. For example, on x86, alignment of UINT64 is 4,
    so a structure of UINT32 and UINT64 has size of 12 (and not 16, as was
    calculated previously).

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the patches.  I guess it makes sense to provide an optional auxiliary function `calc_offsets()` rather than change the whole `uctypes` module to support only OrderedDict with always automatically calculated offsets (which might have been the approach had OrderedDict been used from the beginning).

But how will it handle filling in tuples that are potentially in ROM?  For example, it's possible in the future that compiled bytecode optimises constant tuples to share them and/or place them in ROM.  This will lead to problems with the inplace modification of tuples done here (if I understand correctly how it's implemented).

**Comment by pfalcon** [comment]
> rather than change the whole uctypes module to support only OrderedDict with always automatically calculated offsets (which might have been the approach had OrderedDict been used from the beginning).

Sure, always calculating offsets automatically was never an idea, it was always considered an optional feature, straight from the inception of "uctypes" module some 4 years ago. It just took so much to actually implement it.

> But how will it handle filling in tuples that are potentially in ROM?

That's simply not supported. Someone wanting to e.g. "freeze" code containing such uctypes struct definitions, would need to "freeze" them first by (automatically) converting them to structs with offsets (which would make them arch specific). Initial infrastructure for that is already conceived/provided: https://forum.micropython.org/viewtopic.php?f=15&t=5308 .

**Comment by dpgeorge** [comment]
> That's simply not supported.

But what's proposed here is an API that explicitly specifies that user supplied tuples are to be modified.  This is really against what a tuple is, a constant object.  The user has no idea how tuples are implemented or when they may be constant or shared, and thus not usable with this API.  The compiler may one day decide to share tuples that are the same, eg if `("f1", uctypes.UINT8)` appears twice in the same file.

Please change it so that tuples are not modified, at least not as part of the API.  Eg support lists, or modify the OrderedDict by replacing tuples with new ones, or return an entire new data structure.

**Comment by pfalcon** [comment]
> But what's proposed here is an API that explicitly specifies that user supplied tuples are to be modified.

Yes, and that's exception specifically for MicroPython, to allow for efficient memory usage. And that exception, while rare, does exist and documented: http://docs.micropython.org/en/latest/reference/glossary.html#term-callee-owned-tuple .

> The user has no idea how tuples are implemented or when they may be constant or shared, and thus not usable with this API.

With this API, only literal tuples are supported, and once they are passed (as part of larger data structures) to the API, they are owned by the API, and can't be used for any other purpose. This fact can be documented.

> The compiler may one day decide to share tuples that are the same, eg if ("f1", uctypes.UINT8) appears twice in the same file.

Or it may decide for example to store [large literal] dictionaries in ROM, with the heuristic that it's probably constant, and relocate it to RAM on first update. There're so many possible advanced optimizations, that all of them can't be anticipated in advanced and dealing with them better be left until later.

> Please change it so that tuples are not modified, at least not as part of the API. Eg support lists, or modify the OrderedDict by replacing tuples with new ones, or return an entire new data structure.

Well, this is very special API whose API contract is that it may modify data structures it uses, it's just that. To remind, the baseline requirements for the design of uctypes structure definitions were:

1. To be human-readable. Well, more than that, to be nice on human eye.
2. And yet, to be as memory efficient as possible, as are intended for MicroPython, which may run in very stiff memory environment.

All design decisions are based on those requirements, e.g.

* We could use just lists for everything in structure definitions. But that's not easy on human eye. Human cognition loves differentiation for different levels. Instead of "flat" [[[[[[]]]]]] it's better to have {[([({})])]}.
* But not only using dictionaries is better on human eye, {a: b, c:d} is actually more memory efficient than [[a, b], [c, d]]. That's why the whole crusade for OrderedDict literals, because OrderedDict([[a, b], [c, d]]).
* Likewise, (a, b) is more memory efficient than [a, b].


> Eg support lists

That could be done, i..e. support lists in addition to tuples, i.e. besides

~~~
{
    "arr": (uctypes.ARRAY, uctypes.UINT8 | 2),
}
~~~

let users write:

~~~
{
    "arr": [uctypes.ARRAY, uctypes.UINT8 | 2],
}
~~~

But that's moot point, as any knowledgeable user would prefer 1st variant, as requiring less memory.


So yes, it's like that - the uctypes module is a (the!) special one, and stretches Python semantics at places (more than anything else in MicroPython, and such places are of course localized, asymptotically rare, and discouraged to be repeated). That's why it took so much time to develop it further - while the initial idea seemed simple, I was stumped by all these issues coming down the implementation road of keeping it efficient. So, in the end, I decided that what was started needs to be finished. And of course, by preserving the original requirements of memory efficiency (which for many ports would be the difference between allowing using such facilities, and not allow to use them at all, as there's not enough memory).

**Comment by dpgeorge** [comment]
Comments about const tuple (tuples must always be considered const) weren't addressed, so closing.

Any extensions to uctypes will be driven by need as they arise.

**Pull request closed without merging**
