### PR TITLE
Apply black to format all Python code

### PR DESCRIPTION
**Pull request by dpgeorge**
Per discussion in #4223 here's an attempt to format the Python code (but not tests) using black.

In the spirit of black its defaults are used.

Main changes are:
- literal hex numbers use uppercase for the letters
- double quotes are preferred over single quotes
- previously aligned comments/assignments are no longer aligned

### CODE REVIEW

**Comment by dpgeorge** [comment]
@tannewt do you already have a format for Python code?  Would you adopt black (or yapf)?

**Comment by tannewt** [comment]
We've just started using black. While it makes some weird decisions, I think consistency with all other Python code is a good goal. The PR to do this in our libraries is here: https://github.com/adafruit/cookiecutter-adafruit-circuitpython/pull/63

**Comment by dpgeorge** [comment]
> We've just started using black. While it makes some weird decisions, I think consistency with all other Python code is a good goal.

Ok, sounds good.  I'd be happy with black.

**Comment by andrewleech** [comment]
I'd be really happy if someone forced me to start using black. 
I haven't made the leap on my projects yet, but want to.

I think it will be a struggle for some people to get used to all of it's choices (myself included) but their documented rationale really makes sense to me.

**Comment by dpgeorge** [comment]
Closed in favour of #5700 (which uses black with 99 length line limit).

**Pull request closed without merging**
