### PR TITLE
Fix linker map for STM32L476 chips to be more like the STM32F4xx

### PR DESCRIPTION
**Pull request by dhylands**
I think that this is a  simpler solution for #2460 is this PR

### CODE REVIEW

**Comment by dpgeorge** [comment]
This will reduce the size of the flash FS.  Also, you'd need to update storage.c to change the location of the FS.

**Comment by dhylands** [comment]
Oops. Thanks - I thought that I had to fix that and forgot.

It makes the filesystem the same size as the pyboard (which I thought was reasonable).

Currently the 0x8020000 is hard-coded in the Makefile. If we changed it to come from mpconfigboard.mk then we could allow the L4 to keep the filesystem size at 126K and allow it to use common.ld which needs a 16K FLASH_ISR.

**Comment by dhylands** [comment]
I fixed storage.c to use the new base.

**Comment by dpgeorge** [comment]
@dhylands : did you see my other idea for a solution in this comment: https://github.com/micropython/micropython/pull/2454#issuecomment-250053505 ?

**Comment by dhylands** [comment]
@dpgeorge - I saw it but didn't appreciate it until just now :)

I have yet another solution which would allow for evn larger filesystems on those systems which have larger flash. I put together a python script which will read an ELF file and if a named section exists, it will print out the address of the section.

Then we can create 2 common files. One which has .isr_vector and .text with a filesystem in between them (for F405 and friends), and a second which has just .text (with the isr_vector at the beginning of it) (for L4xx and friends)

The Makefile can then call the script and figure out the correct makeup and addresses to use to construct the dfu file. For the processors like the L4, we can put the filesystem at the end of flash and have the size be tunable.

Then an L4 with say 1Mb of flash could have a 512K filesystem and 512K for .text

If we add symbols into the filesystem segment we can also eliminate some of the hard-coded values from storage.c

If you don't like this proposal, then I'd say we should go with your proposal from #2454

**Comment by dpgeorge** [comment]
I like the idea to give more filesystem to the L4 (since all its pages are 2k in size), but I think it can be done quite easily as follows: 1) make FLASH_ISR for the L4 take up 64k; 2) use my proposal in #2454 to fill this segment as full as possible; 3) adjust storage.c for the L4 to put the filesystem at the end of the flash (settings will depend if the L4 has 512k or 1mb).

It's worth keeping in mind that there are more sophisticated ways to pack the code and filesystem into the flash, in case we need it in the future.  But for now I think just go with a simple solution that doesn't need to run extra scripts :)

BTW, if the DFU layout changes then one also needs to adjust the deploy-stlink target.

**Comment by dhylands** [comment]
This version increases the .isr_vector to 16K (to match the F4xx)
It also moves the filesystem to the end of flash and increases it to 512K for the STM32L476DISC and increases it slightly to 128K for the LIMIFROG

I also got my script working, which you can see over here:
https://www.dropbox.com/home/elfinfo?preview=elfinfo.py

Using this would allow TEXT_ADDR to be determined automatically (instead of being hard-coded in the mpconfig.mk file)

It could be done a bit simpler using bash/objdump/grep/awk, but then that would add awk as a dependency (already required for axtls but not otherwise):
TEXT_ADDR = 0x$(shell $(CROSS_COMPILE)objdump -h $(BUILD)/firmware.elf | grep .text | awk '{print $4}')

**Comment by dhylands** [comment]
> This version increases the .isr_vector to 16K (to match the F4xx)
> It also moves the filesystem to the end of flash and increases it to 512K for the STM32L476DISC and increases it slightly to 128K for the LIMIFROG

@dpgeorge So does this do what you want? Or is there something else you'd like changed?

**Comment by dpgeorge** [comment]
I was trying to think of another way so we didn't need the TEXT_ADDR variable, but I couldn't.  I think what you did here is good, especially since the L4 filesystem location is configurable and you can have it much larger than before.  Merged in 1f433c719b1d29a44c52befdf1476d154ebb3c68 with one fix: the FLASH_TEXT length for the 512k device was wrong, 0x60000 changed to 0x5c000.

**Pull request closed without merging**
