### PR TITLE
esp32/adc: Fix wrong mapping of ADC channels to GPIOs.

### PR DESCRIPTION
**Pull request by ekondayan**
Thi PR fixes a wrong mapping between ADC block 2 channels and GPIOs.
The right mapping can be seen in the esp32 datasheet on page 60 in IO_MUX table.

I can confirm this PR fixes the mapping for  ESP32-D0WD-V3 and ESP32-PICO-V3-02

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks, it looks OK to me.

@jonathanhogg any comment?

**Comment by jonathanhogg** [comment]
Oops! Sorry, my fault. I took the list from the IDF documentation and forgot to double-check the ordering.

I should probably check the datasheets for the C3, S2 and S3…

**Comment by jonathanhogg** [comment]
Good news, [C3](https://www.espressif.com/sites/default/files/documentation/esp32-c3_datasheet_en.pdf), [S2](https://www.espressif.com/sites/default/files/documentation/esp32-s2_datasheet_en.pdf) and [S3](https://www.espressif.com/sites/default/files/documentation/esp32-s3_datasheet_en.pdf) all look to be correct going by the pin descriptions in the datasheets (linked).

**Review by dpgeorge — APPROVED** [review]

**Comment by dpgeorge** [comment]
Merged in b18d4392b4a4c5e6ed50dbcdb4a88828703289cb

**Pull request closed without merging**
