### PR TITLE
Fix auto-qstr generation when "make -B" is used

### PR DESCRIPTION
**Pull request by dpgeorge**
Fix for #2959

### CODE REVIEW

**Comment by dpgeorge** [comment]
This should be good to merge.  @dhylands do you see any issues with the change to the makefile?  (note that the changes to travis.yml will be discarded, they are just for testing purposes, to see if the patch fixed the issue; which it does seem to)

**Comment by dpgeorge** [comment]
I paste here the commit comment for further explanation of what's going on:
```
    For make v3.81, using "make -B" can set $? to empty and in this case the
    auto-qstr generation needs to pass all args (ie $^) to cpp.  The previous
    fix for this (which was removed in 23a693ec2d8c2a194f61482dc0e1adb070fb6ad4)
    used if statements in the shell command, which gave very long lines that
    didn't work on certain systems (eg cygwin).

    The fix in this patch is to use an $if(...) expression, which will evaluate
    to $? (only newer prerequisites) if it's non empty, otherwise it will use
    $^ (all prerequisites).
```

**Comment by pfalcon** [comment]
+1

**Comment by dhylands** [comment]
+1

Using $(if ...) instead of bash if seems like a very good solution.

**Comment by dpgeorge** [comment]
Thanks guys for the review, now merged.

**Pull request merged**
