### PR TITLE
esp8266: Update to SDK version 1.1.0

### PR DESCRIPTION
**Pull request by atx**

### CODE REVIEW

**Comment by pfalcon** [comment]
Did you check with the scope/logic analyzer/whatever that pull down is not available, maybe we should just add definitions back in? ;-)

**Comment by atalax** [comment]
> Did you check with the scope/logic analyzer/whatever that pull down is not available, maybe we should just add definitions back in? ;-)

Tested. It actually seems, that `PIN_PULLDWN_EN()` enables a pull up, go figure.

**Comment by chrismas9** [comment]
This pulldown issue appears to relate only to GPIO16. This is a special pin, the RTC output that is normally connected to reset to awake from deep sleep. In that case reset has an external pullup and you would never want a pulldown fighting a pullup

**Comment by dpgeorge** [comment]
There are no pull down capabilities on any pin, right?  If so then we should merge this.

The special GPIO16 pin is not (yet) supported by the pyb.Pin class.

> It actually seems, that PIN_PULLDWN_EN() enables a pull up, go figure.

It could be a weak/strong pull up compared to the other pull up.

**Comment by pfalcon** [comment]
> There are no pull down capabilities on any pin, right?

Let's say that nobody knows for sure, so I'd prefer that #if 0 with comment were put around for now.

**Comment by pfalcon** [comment]
I'm also not exactly sure why we need .ld changes. Just because sdk 1.1.0 has them? Or it doesn't work without them?

**Comment by pfalcon** [comment]
> I'm also not exactly sure why we need .ld changes. Just because sdk 1.1.0 has them? Or it doesn't work without them?

Ok, so it doesn't work without them - exception vector table now appears to be part of the user apps, and the loader apparently switch exception table base to them, because w/o this change, an app cycles with exception being printed. @atalax : But you really could include this info in commit message (preferrable) or comments.

**Comment by pfalcon** [comment]
Reworked a bit per above comments and merged, thanks. (tested)

**Comment by pfalcon** [comment]
> > Did you check with the scope/logic analyzer/whatever that pull down is not available, maybe we should just add definitions back in? ;-)

> Tested. It actually seems, that `PIN_PULLDWN_EN()` enables a pull up, go figure.

Here's independent confirmation of the same fact http://esp8266.ru/forum/posts/5133 (in Russian).

**Pull request closed without merging**
