### PR TITLE
rp2/boards/ARDUINO_NANO_RP2040_CONNECT: Enable webrepl.

### PR DESCRIPTION
**Pull request by iabdalkader**

### CODE REVIEW

**Comment by robert-hh** [comment]
You could add 
#define MICROPY_PY_OS_DUPTERM_NOTIFY    (1)
as well. For instance the utelnetserver.py code uses it.

**Comment by iabdalkader** [comment]
Done. Any progress with the testing ? btw I found an issue with the sockets poll timer, and fixed, I think it was causing issues on soft reboots. The attached firmware fixes that issue and enables `MICROPY_PY_OS_DUPTERM_NOTIFY`.
[firmware.uf2.zip](https://github.com/micropython/micropython/files/8695130/firmware.uf2.zip)

**Comment by iabdalkader** [comment]
I think it's `MICROPY_PY_UOS_DUPTERM_NOTIFY` not OS.

**Comment by iabdalkader** [comment]
`mp_uos_dupterm_notify` is only implemented in `esp32` and `mimxrt` ports, so that flag is not useful.

**Comment by robert-hh** [comment]
> I think it's MICROPY_PY_UOS_DUPTERM_NOTIFY not OS.

That's right. 
No testing done today until now. If you consider the actual state as good, please submit a firmware. That save me from juggling with all the commits and PRs.

**Comment by iabdalkader** [comment]
> please submit a firmware

I did, it's attached a few comments above.

**Comment by iabdalkader** [comment]
Cherry-picked this in another PR.

**Pull request closed without merging**
