### PR TITLE
Add new port to Microchip SAMD microcontrollers

### PR DESCRIPTION
**Pull request by dpgeorge**
This adds basic support for SAMD21 and SAMD51 microcontrollers under the `ports/samd/` directory.

Boards that are supported are Adafruit Trinket M0 and ItsyBitsy M4 Express.  A USB REPL is available, as well as a UART REPL.  Firmware size is around 100k with big-ints enabled, and floats enabled on the M4 Express.

CMSIS header files are provided by the new asf4 submodule (and only CMSIS headers are used from there).

The USB driver is provided by the tinyusb project, which is added as a submodule as well.

The bootloader on the supported Adafruit boards is UF2, and a tool is added to build UF2 files (direct from upstream https://github.com/Microsoft/uf2).  Deployment must be done manually by entering the bootloader (double-tap the RST button), mounting the board's drive and then copying over `firmware.uf2`.

### CODE REVIEW

**Comment by profra** [comment]
Thank you for the first steps in that direction. It would be also a nice implementation for the new  [Arduino Nano 33 IoT board](https://store.arduino.cc/nano-33-iot) ... any plans in this direction?

**Comment by shazz** [comment]
Great news! I'll try to add the board files for the Adafruit pygamer (ATSAMD51)

**Comment by dpgeorge** [comment]
> It would be also a nice implementation for the new [Arduino Nano 33 IoT board](https://store.arduino.cc/nano-33-iot) ... any plans in this direction?

It's straightforward to support the SAMD21 part of that board, but supporting the esp32 WiFi coprocessor is a lot more effort, and there are currently no plans for that.

**Comment by ladyada** [comment]
support for the esp32 wifi coproc is here https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI but it does not fit in the low memory of the '21 at this time!

**Comment by dpgeorge** [comment]
> support for the esp32 wifi coproc is here

Cool, thanks for the link!

**Comment by shazz** [comment]
@dpgeorge, I added the Adafruit pygamer board:

````
MPY: soft reboot
MicroPython v1.11-126-g7c2e83324-dirty on 2019-07-06; Adafruit PyGamer with SAMD51J19A
>>> print("hello pygamer!")
hello pygamer!
````

I'll work on a display driver now.

**Comment by dpgeorge** [comment]
> Would you accept a pull request ?

Yes

**Pull request merged**
