### PR TITLE
boards: NUCLEO_H723ZG: ADC AF definitions.

### PR DESCRIPTION
**Pull request by brave-ulysses**
stm32h723_af.csv to more closely match stm32h723zg.pdf. not sure how to handle differential inputs.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the fix, I did get this wrong in d995c010428420c7690d5cd59b9580c3f4f9649a

It is possible to describe differential inputs, eg for PA1:
```
ADC1_INN16/ADC1_INP17
```
Are you able to update the file with differential inputs as well?

**Comment by brave-ulysses** [comment]
certainly. should this be in a new pull request?

**Comment by dpgeorge** [comment]
> should this be in a new pull request?

No, please just update it in this PR.

**Comment by brave-ulysses** [comment]
didn't like the commit message. amended with
git commit --amend -s -am "boards: ports-stm32: NUCLEO_H723ZG: differential ADC AF definitions."
git push -f origin HEAD

not sure if this is correct...

**Comment by brave-ulysses** [comment]
also added PC2_C and PC3_C definitions from DS13313 Rev 3 page 59/234
not sure if the logic is present to use adc3 on these pins
Analog switch between ports Pxy_C and Pxy  page 133/234

**Comment by brave-ulysses** [comment]
@dpgeorge 
i think this is complete...

**Comment by dpgeorge** [comment]
Yes this looks good now, thank you.

Rebased, squashed and merged in ad216be5f13ac86e67cafa6257aea5d6e7f82cda

**Pull request closed without merging**
