### PR TITLE
Fix #2040: Remove unimplemented UART methods from esp8266 docs

### LINKED ISSUE #2040: esp8266: missing UART.deinit()
I assume that since there has been a release, discrepancies with the documentation are actually bugs now. Please let me know if that's not a case, then I will stop submitting them.

The documentation at http://micropython.org/resources/docs/en/latest/esp8266/library/machine.UART.html#uart.deinit mentions a `UART.deinit()` method, which doesn't seem to be present on the ESP8266 port:

```
>>> UART.deinit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'UART' has no attribute 'deinit'
```

### PR DESCRIPTION
**Pull request by deshipu**

### CODE REVIEW

**Comment by pfalcon** [comment]
If you, as someone interested in this, consider this acceptable solution for now, let's go for it. But please follow commit messages conventions, as described in https://github.com/micropython/micropython/blob/master/CONTRIBUTING.md (I'll fix it myself this time).

**Comment by pfalcon** [comment]
Merged, thanks.

**Comment by deshipu** [comment]
Thanks. I could have sworn it wasn't there before when I last read it, though.

**Comment by pfalcon** [comment]
It always was at https://github.com/micropython/micropython/wiki/ContributorGuidelines#how-to-contribute . Given that it's pre-last section, well...

**Pull request closed without merging**
