### PR TITLE
mimxrt: Added CMake build system.

### PR DESCRIPTION
**Pull request by alphaFred**
Added CMake build system for mimxrt port. Thanks a lot @robert-hh for the support and testing.

### CODE REVIEW

**Comment by alphaFred** [comment]
Hi @dpgeorge 
As discussed, here is the current state of my CMake integration for mimxrt port.

**Comment by dpgeorge** [comment]
What is the argument/reason for switching to cmake?  I much prefer traditional make, and I would like to see the `mimxrt` port still have make support.  So if cmake support is added it would be optional (ie the existing `Makefile` stays as-is).

**Comment by robert-hh** [comment]
Speaking for myself: we assumed the using cmake would be the new policy, since the esp32 and especially the RP2 port moved to using cmake. Since the mimxrt port is still small, that would have been a good time to change. But obviously make can be continued. The Makefile of the mimxrt port looks still rather clean.
@alphaFred, since you implemented that, what is your view?

**Comment by dpgeorge** [comment]
> we assumed the using cmake would be the new policy, since the esp32 and especially the RP2 port moved to using cmake

Aah, I see.  esp32 moved to cmake because it was the only way to support the IDF and all the new SoC variants.  rp2 used cmake from the beginning for similar reasons: its SDK is cmake based.  And zephyr also, its SDK is cmake.  Other ports will stay with traditional make.

> The Makefile of the mimxrt port looks still rather clean.

Yes, because it's quite simple, just a set of C files.

**Comment by alphaFred** [comment]
I had the same impression. Personally I am by far not an expert on cmake (nor Make for that matter) so I have no strong feelings towards or against any one of the make systems.

One point I wanted to bring to your attention is the fact that NXP is releasing their SDK on github since beginning of the year ([MCUX-SDK](https://github.com/NXPmicro/mcux-sdk)) with full cmake support. This is a point for cmake in my opinion and it is probably worth to change the library submodule in any case.

**Comment by dpgeorge** [comment]
> it is probably worth to change the library submodule in any case.

Yes, possibly.  Hopefully it's almost as simple as just changing the submodule!

**Comment by robert-hh** [comment]
At the moment it's simple using the nxp-drivers: Just add the respective source files.

**Comment by alphaFred** [comment]
From what I have seen so far it is quite similar to RP2 for instance. Where you select the NXP SDK "library" and choose which drivers etc. you want. Then cmake will take care of it.

**Comment by alphaFred** [comment]
I actually planned to test that once I finished all the points for the CMake PR.

For now should I continue with the PR or not? I would of course rework it such that the original Makefile will be retained

**Comment by dpgeorge** [comment]
> For now should I continue with the PR or not?

Let's concentrate on `machine.Pin` first, then the filesystem.

**Comment by alphaFred** [comment]
fine with me. I am working on the last AF file - next time I will pick a controller with less pins :smile:  If everything works out I might  be done by the weekend, let's see.

**Comment by robert-hh** [comment]
The file system PR is based on the actual master, so it can be tested without the Pin PR.

**Comment by alphaFred** [comment]
Fixes: #7331

**Comment by dpgeorge** [comment]
I see this is still in draft, so won't review it until it's out of draft.

**Comment by alphaFred** [comment]
Hi @dpgeorge 
Yes this is still in draft. With the latest PRs I needed to rework/update it multiple times. I will probably need some more time to make it pretty, too. 

I will let you know once I feel comfortable.

**Comment by alphaFred** [comment]
Hi @dpgeorge and @robert-hh - since this topic has been sitting idle for some time and I rather used my resources to improve the mimxrt port I will close that PR for now.
When the mimxrt port has reached a more "stable" state in terms of features and hence changes to the build system I will reconsider integrating CMake support.

**Pull request closed without merging**
