### PR TITLE
stmhal: put common definitions from linker files to common.ld

### PR DESCRIPTION
**Pull request by blazewicz**
FLASH/RAM memory layout is exactly the same for all boards, they differ only in capacities, starting addresses and heap location.

### CODE REVIEW

**Comment by blazewicz** [comment]
I've edited the commit (stmhal/Makefile) so that each port can use their linker script from any directory with common.ld still accessible from within stmhal/boards.

**Comment by dhylands** [comment]
I'd like to take this one step further (so I think that this is good start). The Espruino Pico, for example uses the STM32F401CDU6 which only has 384K flash, and some other 401's I use have STM32F401RET6 which has 512K flash.

Currently, the Espruino Pico image is within a few bytes of filling the flash (0x0805ffc4 max 0x08060000) so only 60 bytes left, so I'd like to have a 384K flash linker script (or #define) for that board, but have 512K flash for other boards using a different chip.

**Comment by blazewicz** [comment]
@dhylands I get your point, please have a look at `stmhal/boards/stm32f429.ld` - IMHO it should be placed in STM32F429DISC directory since it defines external SRAM which is present on this specific board.

And that's why next step should be to create separate linker script for each board, leaving only common.ld in current location.

We already have many different boards and if someone wants to add own custom one he would have plenty of examples how to do that.

What I am not sure about is if project maintainers want to heave these two changes in single PR (or single commit?).

@dpgeorge what do you think?

**Comment by pfalcon** [comment]
> What I am not sure about is if project maintainers want to heave these two changes in single PR (or single commit?).

Nope, I personally can suggest to do it step by step. I'm +1 with this current step (didn't review thoroughly each line).

**Comment by dpgeorge** [comment]
Thanks, a nice clean-up.  Merged in 9310dad15d2572de89d853c71118eed5f8309028.

**Pull request closed without merging**
