### PR TITLE
Fix `super()` call in ssd1306 driver

### PR DESCRIPTION
**Pull request by jimmo**

### CODE REVIEW

**Comment by peterhinch** [comment]
This isn't the only thing wrong here, and with this line fixed the driver still fails. See https://github.com/micropython/micropython/issues/3323. Waiting a fix for the subclassing issue from @dpgeorge.

**Comment by shenki** [comment]
I tested this with MicroPython v1.9.3-239 on the pyboard 1.0 lite and it worked for me

**Comment by peterhinch** [comment]
You are right. Evidently something was wrong with my firmware build when I tested this.
I've verified that this PR works with both I2C and SPI devices, using v1.9.3-238-g42c4dd09.

**Comment by dpgeorge** [comment]
Thanks @jimmo for this fix, and thanks to others for testing.  Merged in bb3412291a0f88cb958852b268d5dc43db23d4fb

**Pull request closed without merging**
