### PR TITLE
mimxrt: Allow to choose the pin to use for miso and cs

### PR DESCRIPTION
**Pull request by Romaric-RILLET**
Use keywords mosi and cs to give pins (machine.Pin) objects to use for mosi ans cs signals.
Teensy 4.1 may use pin D1 or D39 for mosi, pin D0 or D38 for CS0.

Example usage:
spi = SPI(1,cs=Pin.board.D0, miso=Pin.board.D1)

### CODE REVIEW

**Comment by robert-hh** [comment]
Thank you for the contribution. After working so much at that mimxrt port, I am happy if someone else chimes in. I like the idea of using pointers instead of macros in the pin definition. That saves space. I use that in a PR for ETH as well, but that one is not yet published.
Nevertheless, If the intention for this PR is to use Teensy 4.1 Pin 38 and 39 for MISO1 and CS1, then a simple change in mpconfigport.h is sufficient. Otherwise I do not like to have cs and miso keywords, but not mosi. And, the cs keyword was already introduced recently to select between using cs=0 and cs=1 of a SPI hardware. So you could use pin 10, or 37 for cs at SPI(0), allowing to connect two different SPI peripherals.

**Comment by robert-hh** [comment]
Thank you for the contribution. After working so much at that mimxrt port, I am happy if someone else chimes in. I like the idea of using pointers instead of macros in the pin definition. That saves space. I use that in a PR for ETH as well, but that one is not yet published.
Nevertheless, If the intention for this PR is to use Teensy 4.1 Pin 38 and 39 for MISO1 and CS1, then a simple change in mpconfigport.h is sufficient. Otherwise I do not like to have cs and miso keywords, but not mosi. And, the cs keyword was already introduced recently to select between using cs=0 and cs=1 of a SPI hardware. So you could use pin 10, or 37 for cs at SPI(0), allowiQng to connect two different SPI peripherals.

**Comment by Romaric-RILLET** [comment]
My need with this PR is to use Pin 1 for MISO and 0 for CS0 with Teensy 4.1.
I can change mpconfigport.h, but other users of teensy 4.1 may want to use
pin 39 for miso, 38 for CS or both.
This will need 4 versions of mpconfigport.h.

I did not add the keyword "mosi" because for the 3 spi mosi signal, only
one of the two cpu pins is available on board pins.
(On Arch Mix, LPSPI4_SDO may be available on GPIO_B0_02/board 29
or GPIO_B1_06/board 5 but I don't have this board to test) .
I may add mosi and sck keywords if this is preferred (this may be more
coherent with doc
https://docs.micropython.org/en/latest/library/machine.SPI.html).

With this PR, it also possible to select cs number (like with the previous
cs keyword)
SPI(0,cs=Pin.board.D37) # CS 1
SPI(0,cs=Pin.board.D10) # CS 0
but it's also possible du select the pin for CS 0
SPI(1,cs=Pin.board.D0) # CS 0
SPI(1,cs=Pin.board.D38) # CS 0

**Comment by robert-hh** [comment]
The existing usage for the cs=Pin keyword is different from yours. With your implementation, you assign different Pin to the CS0 signal of the SPI module, whereas the existing cs=0|1 keyword selects between the CS0 and CS1 signal of the SPI module.
I think it is less of a problem to use D0 and D1 instead of D38 and D39, if that is only a Teensy 4.1 request.
Sorry, I did not look to deep into your code yet. But if you go for Signal keyword options, then it should be generic.

**Comment by dpgeorge** [comment]
@Romaric-RILLET @robert-hh is this PR still interesting?  If so then it needs to first be rebased on the latest master, since a lot changed in the mimxrt port since this was opened.

**Comment by robert-hh** [comment]
Not for me. It is superseded by 0f048a5a2a4cb239784cd152c9cd3fa0deb86db7, which allows to use any pin for CS.

**Comment by Romaric-RILLET** [comment]
This PR is still  interesting.
It  allows  selecting the pin used for each signal.
0f048a5
<https://github.com/micropython/micropython/commit/0f048a5a2a4cb239784cd152c9cd3fa0deb86db7>
allows
to select which cs is used.
https://www.pjrc.com/teensy/IMXRT1060RM_rev3.pdf at page 306, shows the
muxing possibility for each signal.

0f048a5
<https://github.com/micropython/micropython/commit/0f048a5a2a4cb239784cd152c9cd3fa0deb86db7>
uses
le cs keyword as an integer to select the chip select number (and -1 to
disable chip select).
This pr uses cs and miso keywords as pin object so is incompatible with
0f048a5
<https://github.com/micropython/micropython/commit/0f048a5a2a4cb239784cd152c9cd3fa0deb86db7>
nrf, rp2, samd, esp32 ports use sck, mosi, miso keywords as pin object.

**Comment by robert-hh** [comment]
Compiling for the MIMXRT1015_EVK and MIMXRT1170_EVK boards fails.

**Pull request closed without merging**
