### PR TITLE
Rename the 'javascript' port to 'webassembly'.

### PR DESCRIPTION
**Pull request by ntoll**
Does exactly what it says, renames the javascript port to webassembly. Decision making context via: #9061

### CODE REVIEW

**Comment by ntoll** [comment]
Not sure what's wrong with the commit message formatting. :shrug:

**Comment by jimmo** [comment]
Capital R for rename.

Sorry I have a 90% complete PR to improve the output of the commit message check. Will finish it off and submit it soon.

**Comment by ntoll** [comment]
:rofl: 

My inner teacher wants to get out the red pen of pedantry. AFAICT the jury's out and both upper or lower case are allowed in an "it depends" sort of a way. https://www.grammarly.com/blog/capitalization-after-colons/

**Comment by ntoll** [comment]
Capitalised the "R". ;-)

**Comment by dpgeorge** [comment]
Thank you!

**Pull request merged**
