### PR TITLE
extmod/modframebuf.c Amend mapping names as requested. Amend doc.

### PR DESCRIPTION
**Pull request by peterhinch**
This amends the names of the 1-bit maps to M_HMSB, M_HLSB and M_VLSB as requested in https://github.com/micropython/micropython/pull/2839#issuecomment-287680838 and amends the doc to describe these mappings.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks.  Let's wait for other comments (if any).

We should also provide some backwards compatibility for users of MVLSB, simply by leaving the MVLSB line in the dict, as well as adding the M_VLSB version.

**Comment by peterhinch** [comment]
In the absence of comments I've updated the source and the test script.

**Comment by dpgeorge** [comment]
> In the absence of comments I've updated the source and the test script.

Thanks!  Although after looking at it with somewhat fresh eyes I now have a comment: I think the names are still a bit cryptic and would be easier to understand if the monochrome variables were named MONO_xxx instead of M_xxx.  With RGB565 it's pretty obvious what it is, GS4 is ok but could arguably be GRAY4, but M is too short and even given the context (of a framebuffer) it's still hard to decipher if you're not familiar with it.

What do you think?

**Comment by peterhinch** [comment]
I'm +0.5 for keeping the names as they are but documenting the convention to aid both users and implementers of future modes. Anyone choosing a mode will need to RTFM to understand the spatial and colour mappings so the names aren't too critical beyond having a consistent convention. I can amend the doc if you wish.

I can't see why Travis is failing: in the listing the framebuf1 test passes.

**Comment by dpgeorge** [comment]
> Anyone choosing a mode will need to RTFM to understand the spatial and colour mappings so the names aren't too critical beyond having a consistent convention.

True.  But a someone reading code they didn't write should be able to follow what's going on, and if they read MONO_VLSB ("ok, that's related to the bit-depth which I don't need to change") they'll have much more of an understanding than M_VLSB ("hmm, I'll need to look that up to see what that parameter is and if I should change it").

> I can't see why Travis is failing: in the listing the framebuf1 test passes.

Probably it's a spurious failing of the size check of the minimal build.  It might fix itself if you rebase this PR against the latest master.

**Comment by peterhinch** [comment]
OK, I'm convinced :) I've changed the names, tests and doc as suggested. After a prolonged battle with git I *think* I've rebased it too...

**Comment by peterhinch** [comment]
I've located the Travis problem
```
$ tools/check_code_size.sh
Old size: 77476 new size: 77480
Validation failure: Core code size increased
The command "tools/check_code_size.sh" exited with 1.
```
Where do we go from here?

**Comment by pfalcon** [comment]
> Where do we go from here?

From here we go to figuring out why "peterhinch wants to merge 96 commits into micropython:master from peterhinch:framebuf_names" ;-) (see the subtitle of this PR). That's a little bit too many for "extmod/modframebuf.c Amend mapping names as requested. Amend doc.".

**Comment by peterhinch** [comment]
I got into a hopeless mess with git, a tool which still regularly defeats me. I was trying to rebase as per the request from @dpgeorge. Suggestions gratefully received.

**Comment by pfalcon** [comment]
Right, and you should have rebased, unfortunately you did something else, tell us what. Generic question in this case - did you ever run "git pull" command? If yes, that's the cause of the problem. You should *never* run that command bare, always should run it as "git pull --rebase". That's universal git rule (as in: you'll never get into problems with any project if use "git pull --rebase", but there're a lot of projects with which you can get into trouble with bare "git pull").

The solution is likely also the generic - start form scratch, from master, create a new branch, git log the old branch, find your useful commits (1-2 among 93), cherrypick to the new branch, delete old branch, rename new to the old name, force push, done.

**Comment by peterhinch** [comment]
Thank you! I think this is now fixed, apart from the Travis issue.

**Comment by pfalcon** [comment]
Well, it says that all checks passed, so Travis breakage was also an artifact of unrelated commits.

**Comment by dpgeorge** [comment]
Thanks, merged in 468c6f9da147d6e752e437a32211e317a116b6df

**Pull request closed without merging**
