### PR TITLE
tests: Adapt misc/features.py tests for ports without floating point.

### PR DESCRIPTION
**Pull request by danicampora**
I believe that the goal of the test remains unchanged with this patch.

### CODE REVIEW

**Comment by pfalcon** [comment]
Dunno, first patched case clearly tests floating division and casting result to int. File header also shows that it's a 3rd-party test, and it's beneficial to pass it as-is without modifications...

**Comment by danicampora** [comment]
> first patched case clearly tests floating division and casting result to int

Uupss, you are right.

**Comment by danicampora** [comment]
Maybe is better to add the patched version of this tests into a soon to be created `tests/wipy` directory.

**Comment by pfalcon** [comment]
Let's see what @dpgeorge says, maybe he agrees it makes sense to make it integer-only. Skipping it another choice (anything in tests/misc/ is "special" in some sense).

**Comment by danicampora** [comment]
> Skipping it another choice (anything in tests/misc/ is "special" in some sense).

Yes, I am "currently" skipping it along with some others, but I'm trying to skip as few tests as possible:
https://github.com/micropython/micropython/pull/1348

**Comment by dpgeorge** [comment]
This change is fine.  Indeed it's a contributed test case but not something that exists independently; it was created solely for uPy.  The floating point tests are tested in tests/float so don't need them here and it makes sense to keep this integer-clean.

**Comment by dpgeorge** [comment]
Merged in 4af54242422455ce9523df725b964f0fc68eced6.

**Pull request closed without merging**
