### PR TITLE
add esp32 smartconfig

### PR DESCRIPTION
**Pull request by Lupino**
#3427 

```python
import smartconfig
import network
wlan = network.WLAN(network.STA_IF)
if not wlan.active():
    wlan.active(True)

smartconfig.set_type(smartconfig.ESPTOUCH)
smartconfig.start()
while smartconfig.status() != smartconfig.SC_STATUS_LINK_OVER:
    pass
smartconfig.stop()

print(smartconfig.get_ssid())
print(smartconfig.get_password())
print(smartconfig.get_phoneip())
```

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution, and sorry for the very late reply.  This looks like a nice feature to add, are you still interested in it?

**Comment by Meekdai** [comment]
smartconfig is a good feature, I am very interested in it, and would like to test some.

**Comment by Mrszcup** [comment]
哦

> Thanks for the contribution, and sorry for the very late reply. This looks like a nice feature to add, are you still interested in it?

We need him very much, which is a necessary basic general ability

**Comment by Li-Lian1069** [comment]
when can i use it?

**Comment by omarbenhamid** [comment]
@dpgeorge I find it interesting also, I merged Lupino's branch in to my "custom built" fork and seems to work well. What would need to be done to get this merged in main micropython ? I can spend some time on it.

**Comment by Walkline80** [comment]
[Here](https://github.com/espressif/esp-idf/tree/master/examples/wifi/smart_config) is the espressif idf smartconfig sample, I was 
 tested on ESP32(idf 5.0-dev) and ESP32C3(idf 4.3.1), however ESP32 cannot receive `SC_EVENT_SEND_ACK_DONE` event, it means that the smartconfig initiator cannot exit event loop until timedout, but it still can get ssid and password correctly, is there anyone can optimize my code? Beacuse I'm already tried my best on c module, and I'm not good at c or cpp.....

**Comment by projectgus** [comment]
It seems like @Lupino is no longer working on this PR (no update since April 2019, and no reply to [Damien's question from 2021](https://github.com/micropython/micropython/pull/4404#issuecomment-865632701).)

I'm going to close this now, but if anyone wants to take @Lupino's branch, rebase it and test it, add some documentation, and then open a new PR for review then please do this - feel free to both link back to this PR and also mention me in a comment for a review.

**Pull request closed without merging**
