### PR TITLE
Add support for Softdevice S132 Version 6.1.1

### PR DESCRIPTION
**Pull request by hnhoan**
@glennrub I split the pull request as you suggested.  This one is to add new softdevice s132 6.1.1

### CODE REVIEW

**Comment by glennrub** [comment]
Thanks @hnhoan , this PR looks good to me. There are no users yet, but facilitates to move to next version.

I'll try to follow up with a PR here to move all other nrf52 boards to use this new 6.1.1. I'll run some sanity checks on the new version before removing the 6.0.0 linker script and download function..

**Comment by glennrub** [comment]
@hnhoan, were the two last commits in this PR added by purpose? I thought it looked merge ready before the latest content was added.

**Comment by hnhoan** [comment]
@glennrub I am not very familiar with Git stuff.  It's the first time I use pull request.  The last commits are for adding boards support for the BLYST Nano as a second PR.  I though it would be done in 2 parts.  I didn't know it would affect this PR.

**Comment by glennrub** [comment]
Hi @hnhoan , i took the liberty to help you out a bit. I've created a branch with the updates i planed to follow up with from you first commit in this PR. So what i did, was to cherry-pick your commit in (just a minor change in s140 name in the script for downloading) and adjusting the commit message a bit. Then i built on top of your commit. Could you take a look at this, if this is ok for you? I have as i said used your first commit here as base, to keep you as author.

https://github.com/micropython/micropython/compare/master...glennrub:nrf-sd-6.1.1

I'm also fine with your initial commit here, if you could reset your PR to only include the first initial commit. Please let me know which direction you would prefer.

**Comment by hnhoan** [comment]
@glennrub I am fine with that no problem at all, thanks.

**Comment by glennrub** [comment]
@hnhoan, i'll close this PR now as #4526 has been merged. I guess we can now go back to #4490 to get the target board in.

**Pull request closed without merging**
