### PR TITLE
py/parse: Fix macro evaluation by adding extra expansion macro.

### PR DESCRIPTION
**Pull request by dpgeorge**
Unfortunately, a recent patch (see 0016a45368d8e7272d1c1f891994d6de4effcb40) to reduce code size in the parser made heavy use of macros that MSVC didn't like.  Hopefully this fixes it.

### CODE REVIEW

**Comment by dpgeorge** [comment]
> Hopefully this fixes it.

No luck it seems...

**Comment by stinos** [comment]
Hmm that's nasty. I'll see if I can come up with something.

**Comment by stinos** [comment]
This seems to work, had to move the comma:
```
// Macro to create a list of N-1 identifiers where N is the number of variable arguments to the macro
+#define RULE_EXPAND(...) __VA_ARGS__
 #define RULE_PADDING(rule, ...) RULE_PADDING2(rule, __VA_ARGS__, RULE_PADDING_IDS(rule))
-#define RULE_PADDING2(rule, ...) RULE_PADDING3(rule, __VA_ARGS__)
-#define RULE_PADDING3(rule, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, ...) __VA_ARGS__
-#define RULE_PADDING_IDS(r) PAD12_##r, PAD11_##r, PAD10_##r, PAD9_##r, PAD8_##r, PAD7_##r, PAD6_##r, PAD5_##r, PAD4_##r, PAD3_##r, PAD2_##r, PAD1_##r,
+#define RULE_PADDING2(rule, ...) RULE_EXPAND(RULE_PADDING3(rule, __VA_ARGS__))
+#define RULE_PADDING3(rule, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, ...) __VA_ARGS__,
+#define RULE_PADDING_IDS(r) PAD12_##r, PAD11_##r, PAD10_##r, PAD9_##r, PAD8_##r, PAD7_##r, PAD6_##r, PAD5_##r, PAD4_##r, PAD3_##r, PAD2_##r, PAD1_##r

// Use an enum to create constants that specify where in rule_arg_combined_table a given rule starts
```

**Comment by dpgeorge** [comment]
Thanks @stinos for looking into this, much appreciated.  I shouldn't have been so eager to push these parser changes without checking the MSVC build :)

The real problem is that one of the padding macros sometimes has an empty `__VA_ARGS__` value, which is not allowed by the CPP spec.  The latest change should have fixed this.

**Pull request merged**
