### PR TITLE
stm32: Enable link-time optimisation as a build option

### PR DESCRIPTION
**Pull request by projectgus**
Adds capability to do `make LTO=1` for stm32 port. Currently disabled by default. Until now, nrf is the only MicroPython port with LTO support.

Goal is improving support on very small STM32 targets like the STM32L072 (20KB RAM, 192KB flash, 32MHz CPU). Every byte counts!

## Build Performance

Building test firmwares for B_L072Z_LRWAN1 and PYBV11. GCC is `arm-none-eabi-gcc (Arch Repository) 12.1.0`. Build system is a Ryzen 5 3600 (6 Cores 12 Threads). 

Build method is `make clean BOARD=B_L072Z_LRWAN1 && time make -j BOARD=B_L072Z_LRWAN1 LTO=1`. No ccache. Best of 3 runs for build time.

| Board          | Options | Build Time                                      | text segment size | difference   |
|----------------|---------|-------------------------------------------------|-------------------|--------------|
| B_L072Z_LRWAN1 | LTO=0   | 54.12s user 8.99s system 735% cpu 8.583 total   | 193420            |              |
|                | LTO=1   | 49.97s user 8.95s system 666% cpu 8.839 total   | 188040            | -5380 (2.8%) |
| PYBV11         | LTO=0   | 70.53s user 10.51s system 755% cpu 10.731 total | 369228            |              |
|                | LTO=1   | 69.05s user 10.60s system 735% cpu 10.834 total | 360812            | -8416 (2.3%) |

Difference is pretty minor, but measurable (and 5KB on a board that currently has <3KB free in the default image is not too shabby!)

Surprisingly, on my system the build times (CPU time and wall time) seemed basically the same with or without LTO, and LTO is actually a little faster in CPU time. This might be different with older gcc versions or more constrained hardware.

## Runtime Performance

Testing on Pyboard V1.1, run as `./run-perfbench.py -p -d /dev/ttyACM0 168 100`

```
> ./run-perfbench.py -p -d /dev/ttyACM0 -s pyboardv11-no-lto.txt pyboardv11-lto.txt
diff of scores (higher is better)
N=168 M=100                pyboardv11-no-lto.txt -> pyboardv11-lto.txt         diff      diff% (error%)
bm_chaos.py                    357.38 ->     352.89 :      -4.49 =  -1.256% (+/-0.01%)
bm_fannkuch.py                  77.25 ->      77.52 :      +0.27 =  +0.350% (+/-0.01%)
bm_fft.py                     2524.17 ->    2516.82 :      -7.35 =  -0.291% (+/-0.00%)
bm_float.py                   5877.62 ->    5748.99 :    -128.63 =  -2.188% (+/-0.02%)
bm_hexiom.py                    42.25 ->      42.22 :      -0.03 =  -0.071% (+/-0.00%)
bm_nqueens.py                 4372.41 ->    4407.51 :     +35.10 =  +0.803% (+/-0.00%)
bm_pidigits.py                 635.78 ->     633.96 :      -1.82 =  -0.286% (+/-0.17%)
core_import_mpy_multi.py       477.10 ->     477.72 :      +0.62 =  +0.130% (+/-0.01%)
core_import_mpy_single.py       58.76 ->      58.74 :      -0.02 =  -0.034% (+/-0.00%)
core_qstr.py                    63.38 ->      63.11 :      -0.27 =  -0.426% (+/-0.00%)
core_yield_from.py             359.39 ->     357.57 :      -1.82 =  -0.506% (+/-0.00%)
misc_aes.py                    408.89 ->     397.27 :     -11.62 =  -2.842% (+/-0.00%)
misc_mandel.py                3433.68 ->    3375.74 :     -57.94 =  -1.687% (+/-0.01%)
misc_pystone.py               2310.39 ->    2265.40 :     -44.99 =  -1.947% (+/-0.00%)
misc_raytrace.py               369.97 ->     367.60 :      -2.37 =  -0.641% (+/-0.01%)
viper_call0.py                 590.87 ->     605.92 :     +15.05 =  +2.547% (+/-0.00%)
viper_call1a.py                563.23 ->     576.78 :     +13.55 =  +2.406% (+/-0.00%)
viper_call1b.py                443.97 ->     452.46 :      +8.49 =  +1.912% (+/-0.01%)
viper_call1c.py                448.74 ->     457.39 :      +8.65 =  +1.928% (+/-0.00%)
viper_call2a.py                548.53 ->     561.37 :     +12.84 =  +2.341% (+/-0.00%)
viper_call2b.py                383.19 ->     389.49 :      +6.30 =  +1.644% (+/-0.01%)
```

A few percent slower in some tests (standout is misc_aes.py at -2.8%), but faster in some others (all viper calls got about 2% faster). Can't explain why LTO would make some operations slower...

On STM32L072 (B-L072Z-LRWAN board), run as `./run-perfbench.py -p -d /dev/ttyACM0 32 10`
                                                                                                           
```
> ./run-perfbench.py -p -d /dev/ttyACM0 -s stm32l072-no-lto.txt stm32l072-lto.txt
diff of scores (higher is better)
N=32 M=10                  stm32l072-no-lto.txt -> stm32l072-lto.txt         diff      diff% (error%)
bm_fannkuch.py                 873.71 ->     874.48 :      +0.77 =  +0.088% (+/-0.08%)
bm_nqueens.py                  333.55 ->     334.51 :      +0.96 =  +0.288% (+/-0.00%)
bm_pidigits.py                 133.18 ->     134.70 :      +1.52 =  +1.141% (+/-0.09%)
core_import_mpy_multi.py        57.39 ->      57.61 :      +0.22 =  +0.383% (+/-0.06%)
core_qstr.py                    11.07 ->      11.09 :      +0.02 =  +0.181% (+/-0.00%)
```

Most tests don't run in this resource footprint. LTO slightly faster, but not really.

## Other tradeoffs for enabling LTO

* Source-level native code debugging is more of a challenge, as execution flow can jump unexpectedly between source files.
* Undefined Behaviour that isn't an issue with LTO=0 may become exposed with LTO=1.
* Marginally higher possibility of hitting compiler bugs, although LTO is pretty mature these days...

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks, this is nice!

I'd suggest two things:
- Decide on a name for the makefile-level `LTO` variable, so that we can use this consistently across all ports.  Is `LTO` unique enough that it won't clash with anything else?  It could be `USE_LTO` or `MICROPY_LTO`?
- Enable LTO on small stm32 boards, I'd say F0, L0, G0 and L432KC

**Comment by jimmo** [comment]
> Marginally higher possibility of hitting compiler bugs, although LTO is pretty mature these days...

I don't know anything about the history of LTO and compiler bugs, but if this is a thing then do we need to consider turning it off by default below certain compiler versions? I think people are still regularly using 8.x and 9.x for example.

@tannewt @dhalbert @jepler CircuitPython uses LTO right? I saw in https://github.com/adafruit/circuitpython/commit/9d10a3da66cd799b659457ca9785be1a33105dc6 that it looks like you're seeing problems on GCC 10.x ?

**Comment by dhalbert** [comment]
> @tannewt @dhalbert @jepler CircuitPython uses LTO right? I saw in [adafruit@9d10a3d](https://github.com/adafruit/circuitpython/commit/9d10a3da66cd799b659457ca9785be1a33105dc6) that it looks like you're seeing problems on GCC 10.x ?

We have been using LTO for years, and in general are quite happy with it, though it does make for slower builds. It can make a huge difference in code size. We have used it on the SAMD and nRF ports, but have not yet tried it on STM or Espressif (I think

We did some tricky things in the commit you mentioned to improve compilation of the translation strings when using LTO, but there is not an inherent problem with gcc10: see https://github.com/adafruit/circuitpython/pull/6440.  And we used it on versions below gcc10 without particular difficulty. Sometimes you have to make sure certain sections, such as the interrupt vector, don't disappear, but the problems have all been solvable.

@tannewt and @jepler may have further comments as well.

**Comment by dhalbert** [comment]
Also see https://github.com/adafruit/circuitpython/pull/6436, which did some tuning of an LTO option.

**Comment by chrismas9** [comment]
`Difference is pretty minor`

On the F091 port the filesystem size is 20K with 1700 bytes spare. This will increase it to 26K. That's not minor, it's massive. All filesystem sizes on small chips should be increased if this is implemented.

**Comment by tannewt** [comment]
Generally LTO has been great for the smallest builds.

Another caveat to know is that it's not great for multi-tiered memory systems because it may merge code across memory regions. (For example merging RAM-only code into flash stored code.) Our small micros don't have this memory setup though.

**Comment by projectgus** [comment]
Thank you @tannewt and @dhalbert for the context, that's really useful! It's interesting you see size improvements with `-flto-partition=one` over `balanced`, I'm pretty sure I didn't notice a size change on the stm32 builds (but this could be for any number of reasons). @dhalbert do you happen to know what gcc version you used for those benchmarks?

If that's the case then it's probably worth parameterising the partition method in the variable, same as you've done for CircuitPython.

**Comment by projectgus** [comment]
Fairly unexpected finding. LTO builds with default "balanced" partitioning are *not significantly slower* on gcc 12.1 than LTO=0, even on pretty low end hardware.

PYBV11 builds on both my 2016 Dell laptop (i7-6500U 2 Cores 4 Threads)  and my desktop Ryzen 5 3600 (6 Cores 12 Threads) are both within about 2% total wall time of LTO=0 vs LTO=1, which I think is within the margin of error.

Building for NUCLEO_L073RZ on my desktop the LTO build is 0.7 seconds slower, which is 8% slower.

**Comment by projectgus** [comment]
@dpgeorge Thanks for the useful feedback!

>   Decide on a name for the makefile-level LTO variable, so that we can use this consistently across all ports. Is LTO unique enough that it won't clash with anything else? It could be USE_LTO or MICROPY_LTO?

The nrf port is using `LTO` already. Although it's a short acronym, I think it's only ever commonly used as an environment variable for this purpose so if I'd suggest keeping it if you're comfortable with that (in the same way names like CFLAGS are treated as generic rather than scoped to a project).

>    Enable LTO on small stm32 boards, I'd say F0, L0, G0 and L432KC

Ack, will do!

> I don't know anything about the history of LTO and compiler bugs, but if this is a thing then do we need to consider turning it off by default below certain compiler versions? I think people are still regularly using 8.x and 9.x for example.

I think it's probably OK to keep it on regardless of version. I think I've been using LTO since gcc 4.x and I've never run into a bug that was caused by the compiler due to LTO. I have definitely run into bugs that were only exposed by enabling LTO, but those were actual bugs or UB. But it will be a thing to keep in mind when reproducing a bug, that it's possible it will appear or disappear depending on the LTO setting and gcc version...

**Comment by projectgus** [comment]
@dpgeorge @jimmo (& others)

One thing that does happen is that if you do a "dirty" config change from LTO=0 to LTO=1 builds without also doing a clean build, you can see some pretty scary looking linker errors (that go away with a clean build). If this is likely to be a problem then an easy way around it is to put a suffix on all the LTO object files (like name-lto.o vs name.o).

The other approach about it would be to add a note in the docs, though. Which made me wonder about build docs. Is it worth adding a section about LTO this in the port Makefile, or even a generic "Options when building MicroPython" section in the docs themselves? Happy to write such a section if so. Apologies if there is one already, but I missed it.

**Comment by projectgus** [comment]
Have rebased, and also updated with some new perfbench runs on Pyboard and STM32L072.

**Comment by dpgeorge** [comment]
> One thing that does happen is that if you do a "dirty" config change from LTO=0 to LTO=1 builds without also doing a clean build, you can see some pretty scary looking linker errors (that go away with a clean build).

Yeah, this happens with lots of other things as well, basically changing any Makefile-level option.  Eg `MICROPY_PY_BLUETOOTH` on PYBD_SF6.  I'd say we can let that be as it is for now, and defer it to another time (maybe never) to fix in a comprehensive way.

**Comment by dpgeorge** [comment]
> Which made me wonder about build docs. Is it worth adding a section about LTO this in the port Makefile, or even a generic "Options when building MicroPython" section in the docs themselves?

Adding a not to stm32's Makefile would be worth doing (nrf has a similar note).  For generic docs it'd possibly go in `docs/develop/gettingstarted.rst`.

**Comment by dhylands** [comment]
> Yeah, this happens with lots of other things as well, basically changing any Makefile-level option. Eg `MICROPY_PY_BLUETOOTH` on PYBD_SF6. I'd say we can let that be as it is for now, and defer it to another time (maybe never) to fix in a comprehensive way.

One simple way is to make all of the objects depend on all of the Makefiles (available in $(MAKEFILE_LIST).

**Comment by projectgus** [comment]
> One simple way is to make all of the objects depend on all of the Makefiles (available in $(MAKEFILE_LIST).

@dhylands This is a good practice (albeit not without footguns), but it doesn't solve this use case of overriding some variables on the make command line. I don't know of a good way around that one.

**Comment by dpgeorge** [comment]
Rebased and merged in 2c015375d1e795b4c1a996e50b27234e07f3f638 through dd77dbd4f72734da2b11ff52c553d636d1eee614

Thank you!

**Comment by H-Grobben** [comment]
Situation: I need some Fuses set in the processor (to be exact, disable the Boot0 pin functionality because the device would often go into bootloader mode). I added the Fuses to a .c file in the board folder, with a .ld file with the locations of the fuses. When I build without LTO, the fuses are found in the Hex file. If I use LTO=1 during build, the fuses are absent in the hex file. Is this expected behavior?

**Comment by jimmo** [comment]
@H-Grobben you need to set the `used` attribute, e.g.

`const uint32_t optionbytes1  __attribute__(( section(".optionbytes1"), used )) = 0xFBEFF8AA;`

(It's not enough to do this via `KEEP` in the linker script)

**Pull request closed without merging**
