### PR TITLE
py/makeversionhdr: honor SOURCE_DATE_EPOCH if present

### PR DESCRIPTION
**Pull request by titouanc**
This enables support for reproducible builds of Micropython

### CODE REVIEW

**Comment by titouanc** [comment]
@dpgeorge I'm not sure why the check "coverage/coveralls" fails on this PR, as I don't believe that my change is affecting any of the files mentioned as "Uncovered existing lines", is there anything I could do to fix that ?

Besides that, is the change acceptable for you ?

**Comment by dpgeorge** [comment]
> I'm not sure why the check "coverage/coveralls" fails on this PR,

That check fails quite often now and I'm not sure why... the coverage report seems to sometimes miss lines.  Anyway, just ignore it for this PR.

> Besides that, is the change acceptable for you ?

Yes it looks like a good solution to the problem of reproducible builds.  There was some previous discussion, many years ago, about this but I can't find the issue/PR to link to.

Is the `SOURCE_DATE_EPOCH` variable a standard/common one to use for this?  Or maybe it should be MP specific like `MICROPY_SOURCE_DATE_EPOCH`?

**Comment by titouanc** [comment]
`SOURCE_DATE_EPOCH` is indeed a specified standard for the purpose, see https://reproducible-builds.org/specs/source-date-epoch/

**Comment by titouanc** [comment]
I was indeed trying to add a test that would check the build date reported by micropython, but didn't manage to get any output from micropython. The only missing part was the `-i` option, thank you very much @dpgeorge .

I wrote the test using grep (exit code=0 if pattern found), so the test is less sensitive to other changes in the banner text (like adding more words before). I also suggest to keep this in a separate job so that it gives a distinct error from the tests themselves, and this new check can run in parallel of the others.

Finally, I had to rewrite my commit messages to make them pass the newly introduced "verify git log" check.

**Comment by dpgeorge** [comment]
Thanks for updating.  I squashed the second two commits here and merged this, see 4fb5f012c32a2ed394091039a7213472001a98c9 and b8f5f5cd85e83fd136fac5e90ed5d486c2924a42

**Pull request closed without merging**
