### PR TITLE
tests: Add scripts to print and clean *.exp,out

### PR DESCRIPTION
**Pull request by dlech**
This adds a couple of scripts to the tests/ directory to print the diffs of failed tests and also to clean up the .exp and .out files after failed tests.

Travis is also updated to use this new script, including using it for more builds.

### CODE REVIEW

**Comment by stinos** [comment]
Good idea, but any chance to rewrite this in Python so it works on more systems?

**Comment by dlech** [comment]
converted to python

**Comment by dpgeorge** [comment]
I would suggest, instead of having new scripts for this, to add the functionality to the existing `tests/run-tests` script.  That script can already do related things like `--list-tests` and `--write-exp`, so adding `--print-failures` would make sense to me.

For cleaning: I'm already just using `git clean -f tests/`.  Is there a benefit to adding a special command for this?

**Comment by dlech** [comment]
>  Is there a benefit to adding a special command for this?

If you have created a new test that isn't in git yet, then it would be deleted by `git clean ...`.

**Comment by dlech** [comment]
refactored into `run-tests` script

**Comment by dpgeorge** [comment]
Looks good, thanks!  Merged in 581f9135a4148e236d62b2d28911f98aa92905e1

**Pull request closed without merging**
