### PR TITLE
List slice bounds fix

### PR DESCRIPTION
**Pull request by dpgeorge**
This is an alternative fix to #3090.

### CODE REVIEW

**Comment by tomlogic** [comment]
Nice, simple fix.  I am concerned about changing `stop` to be inclusive instead of exclusive to the slice, and how that could cause problems as we start supporting negative slices elsewhere in the codebase.

For example, `range(1, 100, 5)[15:5:-3]` should return `range(76, 26, -15)`, but with this patch it returns `range(76, 31, -15)`.  If we were to support a `slice()` object, it would need to report `stop` as 1 less than the stored value on a negative step.

I feel like finding a solution where we can store -1 in `stop` may allow removal of special-case code, or where the negative-step version of code isn't an exact mirror of the forward-step version.

That said, I would certainly vote for merging this to master now, and starting a discussion on how to refactor the code.

**Comment by dpgeorge** [comment]
> For example, range(1, 100, 5)[15:5:-3] should return range(76, 26, -15), but with this patch it returns range(76, 31, -15).

Thanks for that report as well... it was broken prior to this PR and now I just pushed another commit to fix it (and add some tests).  

> I feel like finding a solution where we can store -1 in stop may allow removal of special-case code, or where the negative-step version of code isn't an exact mirror of the forward-step version.

Yes that sounds like a good idea, but I think we agree that the optimisation can occur after the bugs are fixed.  Do you know of any more bugs with negative slicing?

**Comment by tomlogic** [comment]
Covers everything I'm aware of.

**Comment by dpgeorge** [comment]
Ok, this was merged.  Thanks @tomlogic for the bug report and the tests!

**Pull request merged**
