### PR TITLE
esp8266: Added wlan.isconnected() to maintain parity with other ports.

### PR DESCRIPTION
**Pull request by owens-bill**
Per @danicampora's comment on the commit for PR #1338, I've added a simple method to network.WLAN that returns a boolean value for whether the board is connected to its chosen AP and has received an IP address.

### CODE REVIEW

**Comment by danicampora** [comment]
@owens-bill Thanks!. I'll add the `.status()` method to the CC3200.

**Comment by pfalcon** [comment]
But having both .isconnected() and .status() is superfluous as they largely  do the same (well, .status() is superset of .isconnected()). We should consider if having .status() separate is more beneficial than  .isconnected(), taking into account that the choice affects *all* networking drivers, not just WiFi.

Cons for .status(): would need to have symbolic constants for values, even if they're just CONNECTED/DISCONNECTED.

Pros for .status(): Common sense is that not all technologies allow to say whether link is connected or not (e.g. SLIP over serial), so faithful approach requires at least 3 values: CONNECTED/DISCONNECTED/DONTKNOW. Of course, it's possible to treat DONTKNOW optimistically as CONNECTED, all depends on what are real-world usecases for .isconnected()/.status() at all.

**Comment by owens-bill** [comment]
> But having both .isconnected() and .status() is superfluous as they largely do the same

No strong feelings either way, though .isconnected() may improve portability since it only needs to be checked for True rather than knowing which status message to look for.

**Comment by pfalcon** [comment]
> rather than knowing which status message to look for.

Well, if adopt status() as standard way to do it, we'd also adopt standard status values - at least symbolic, likely also numeric.

Anyway, @dpgeorge , as the author of original isconnected() API, what do you think about all this?

**Comment by dpgeorge** [comment]
The way I used isconnected() is in a loop waiting for the dynamic IP to be assigned.

Note that it's not just wifi: pyb.USB_VCP() has an isconnected() method to check if the VCP is connected to a host.

This method is supposed to be a simple, obvious and self-documenting way of seeing if some "link" is connected and can be used to read/write/send/recv data.  There're lots of ways to fail (ie for it to return False), but should be only one way to succeed (return True), and that is if the link is connected and ready.

**Comment by danicampora** [comment]
> This method is supposed to be a simple, obvious and self-documenting way of seeing if some "link" is connected and can be used to read/write/send/recv data. There're lots of ways to fail (ie for it to return False), but should be only one way to succeed (return True), and that is if the link is connected and ready.

That's why I think is a good idea to keep it.

**Comment by pfalcon** [comment]
Merged now, thanks, with same comments as #1318.

**Pull request closed without merging**
