### PR TITLE
Stm32 on board RMII ethernet

### PR DESCRIPTION
**Pull request by forester3**
I added several definitions in boards/STM32F7DISC to work on board RMII ethernet.
And I tested script in wiznet_connect.py, too.

This PR is related to #3379 PR.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks @forester3 for submitting this.  I took this PR and rebased it on top current master code, cleaned it up, and made it work with the new lwIP 2.0 version.  See #3808.

@boochow are you aware of this PR?

**Comment by dpgeorge** [comment]
Do `Rx_Buff` and `Tx_Buff` need to be located in a special spot in RAM using the linker script?  From what I can see they still have caching enabled so probably they don't need special handling (only `DMARxDscrTab` and `DMATxDscrTab` are special here).  It would be simpler to define `Rx_Buff` and `Tx_Buff` as normal, static, global arrays.

**Comment by forester3** [comment]
Hi,

Perhaps, I messsaged to his blog, but he did not respond.
Since the message has not been approved and has not been published, there is no way to check.

Thank you.




----- Original Message -----

**Comment by boochow** [comment]
@dpgeorge I borrowed this code from ST's example project "LwIP_HTTP_Server_Netconn_RTOS" (bundled with STM32CubeMX). I did so because ethernetif.c generated by STM32CubeMX(FW_F7_V1.8.0) did not work. I agree with you that these buffers could be defined as static global arrays but I couldn't get it worked. Actually, I don't know why Rx_Buff and Tx_Buff have to be placed at the fixed address.

@forester3 I am very sorry I have missed your comments on my blog. I'll answer your questions later.

**Comment by dpgeorge** [comment]
@boochow thanks for your original work getting this going.

> I borrowed this code from ST's example project "LwIP_HTTP_Server_Netconn_RTOS" (bundled with STM32CubeMX).

Ok.  The license for this looks compatible with what we already have, for what we already use from the ST libraries, so that's good, we can use it.

> I agree with you that these buffers could be defined as static global arrays but I couldn't get it worked.

I will try to make it work because it will be cleaner with them static globals.

**Comment by dpgeorge** [comment]
This was superseded by #4541 (which was merged).

**Pull request closed without merging**
