### PR TITLE
stm32/boards: Add MCUDEV_F407VE board.

### PR DESCRIPTION
**Pull request by mcauser**
Based on: https://github.com/mcauser/BLACK_F407VE

### CODE REVIEW

**Comment by dpgeorge** [comment]
All these boards (7 of them) look very similar.  Is it needed to have configs for all of them?  Can one build run on all, or one build have a make option to select the MCU variant?  Eg `make BOARD=BLACK_F407 VARIANT=VE`?

At the very least it should be possible to include common config from the base board, eg like PYBD_SF3 and PYBD_SF6 inherit from PYBD_SF2.

**Comment by mcauser** [comment]
There's a lot of similarities, but also a lot of differences.

The Black VE and ZE have a completely different layout, but the ZE and ZG only difference is the CPU.
The two DevEBox boards are the same layout but with different CPUs VE and VG.
The two VCC GND boards are different layouts, but both have the same crystals, spi flash and eeprom.
All of the MCUDev boards use 8M crystals, but the VCC GND ones use 25M.

I can merge the ZE+ZG and VE+VG boards with a variant - the main difference being more flash.

I think the bdev.c could potentially be moved higher up, so all boards which have onboard SPI/QSPI flash can optionally use it.

**Comment by dpgeorge** [comment]
@mcauser are these boards still relevant? (including #5527 and #5529; are there any others?)  If so I'm happy to merge them as-is.  Clean-up / factoring can happen later (and maybe once pins.csv files can be shared).

**Comment by dpgeorge** [comment]
Closing due to inactivity.  Feel free to reopen with `board.json` and images if the board is still relevant and in production.

**Pull request closed without merging**
