### PR TITLE
teensy: Add support for machine.rng() on Teensy 3.5 & 3.6

### PR DESCRIPTION
**Pull request by dhylands**
This assumes that PR #2519 has been applied

### CODE REVIEW

**Comment by pfalcon** [comment]
machine.rng() isn't in https://github.com/micropython/micropython/wiki/Hardware-API - why is it being added?

**Comment by dhylands** [comment]
Because it was in stmhal's machine module

**Comment by kamikaze** [comment]
will it be merged someday? :)

**Comment by dhylands** [comment]
I expect that's up to @dpgeorge. He hasn't made any comments on any of the teensy commits, so I'm not sure if there are any issues or he's just busy.

**Comment by dpgeorge** [comment]
See https://github.com/micropython/micropython/pull/2513#issuecomment-831665012

**Pull request closed without merging**
