### PR TITLE
Add new board STM32F722VE

### PR DESCRIPTION
**Pull request by badlyby**
Add new board and fix sectors set.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.  I guess this supersedes #4930?

What is the actual board name, is it a Nucleo or Discovery board, or something else?  Can you please change it to match existing boards, eg `NUCLEO_F722VE`.

Can you please redo the `stm32f7xx_hal_conf.h` file to the new format, see eg in `ports/stm32/boards/PYBD_SF2` directory.

**Comment by badlyby** [comment]
I'll resubmit it in a new format and a new name.

**Comment by badlyby** [comment]
> Thanks for the contribution. I guess this supersedes #4930?
> 
> What is the actual board name, is it a Nucleo or Discovery board, or something else? Can you please change it to match existing boards, eg `NUCLEO_F722VE`.
> 
> Can you please redo the `stm32f7xx_hal_conf.h` file to the new format, see eg in `ports/stm32/boards/PYBD_SF2` directory.

I'll resubmit it in a new format and a new name.

**Comment by dpgeorge** [comment]
See #4932 for updated version.

**Pull request closed without merging**
