### PR TITLE
Integration for limifrog. 

### PR DESCRIPTION
**Pull request by tobbad**
After the integration of L4 this little patch will add support for the Limifrog which was the final aim of:
http://forum.micropython.org/viewtopic.php?f=12&t=1332

I use the same clock configuration which works fine for stm32l476-discovery. Xavier (creator of LimiFrog) however mentions in his `Known_Limitation_and_Features.pdf` document (30.3.2016) that:

> Another one is the clock that goes to the USB peripheral, its frequency must be 48MHz.
> When setting the system clock to 80MHz, the division ratios available from the first PLL mean it is not possible to obtain 48MHz from that one. The second PLL (PLLSAI1) must be used. However, on 10 samples I tested, generating 48MHz with the second PLL (from an 8MHz external source) did not allow the USB to work reliably: some samples were OK, others were not – apparently, because some configuration registers could not be written properly.

So if you have any issues with this configuration please add a note at the mentioned thread in the 'Other Boards" forum.

Some of the files (pin.csv, stm32l4xx_hal_conf.h) are the same as for STM32L476DISC. In the mk file I just added a deploy2b (deploy to board) target as I need a special memory map set up. In my opinion the deploy-stlink target is not generic enough. Is there a possibility to add a make target only if an alternative is not defined?

The loader script is setup to support the debug image fits in the flash. As the LimitFrog (and stm32l476-discovery) have a 8/16Mbyte QSPI-Flash on board, the user flash device will later be mapped to the QSPI see work in progress:
https://github.com/tobbad/micropython/tree/stm32l476discovery_integration_qspi

### CODE REVIEW

**Comment by tobbad** [comment]
I changed the linker script to stick to the usual distribution of the Flash:
- RESET vectors at 0x08000000
- FLASH_TEXT at 0x08020000
Therfore the special deploy2b target was removed. The binary only fits the flash if it is build as release.

**Comment by dpgeorge** [comment]
@tobbad I'm trying this PR out with the latest code in master that has all L4 PRs merged.  But it doesn't work.  I'll look into it sometime, but maybe you'll get a chance to do that before me?

Also, can you please verify that the STM32L476DISC build works on a board?

**Comment by dpgeorge** [comment]
Limifrog board now seems to be working, including USB VCP mode.  I don't know what I did to fix it...

**Comment by dpgeorge** [comment]
Merged in 770f169e63cfd5f69cea1d822d5cf1b20dcc3b48.  See also 08d3d5d9ab2ac0d39fb04e41d446a8fbbcf70354 for capability to enter DFU mode.

**Comment by dpgeorge** [comment]
@tobbad when you get a chance can you please check that the latest code works on the STM32L476DISC board?  Thanks!

**Pull request closed without merging**
