### PR TITLE
ports/w60x: Add ports for W60X module based boards.

### PR DESCRIPTION
**Pull request by wdyichen**
W600 is an embedded Wi-Fi SoC chip which is complying with IEEE802.11b/g/n international standard and which supports multi interface, multi protocol. It can be easily applied to smart appliances, smart home, health care, smart toy, wireless audio & video, industrial and other IoT fields. This SoC integrates Cortex-M3 CPU, Flash, RF Transceiver, CMOS PA, BaseBand. It applies multi interfaces such as SPI, UART, GPIO, I2C, PWM, I2S, 7816. It applies multi encryption and decryption protocol such as PRNG/SHA1/MD5/RC4/DES/3DES/AES/CRC/RSA.

Currently only port modules with WiFi,GPIO, UART, software SPI, I2C, PWM, WDT and Timer，more module ports will be added in the future.

These chips are widely available and can be purchased from various major distributors like Seeed, Taobao, etc, or directly from WinnerMicro. 

W600 uses standard arm-none-eabi-gcc and openocd to compile and debug firmware.

W600 is available in the long term, and code are licensed under Apache license.

We will update the migration code frequently, especially when the SDK updates or fixes bugs.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the submission.  Since there is not much of a description here in the PR it's unclear what the intention is for this code, but I assume you want to add it to this repository.

For a new port to be added there are some things that must be considered.  See eg #4557 for a previous discussion about another port.

What is the W60X?  Is it popular and easily avaliable?  Does it use an open-source toolchain?  Will the chip be available in the long term?  Will this port be maintained in the long term?

**Comment by wdyichen** [comment]
Hi @dpgeorge , thank you for your interest. I modified the description of PR.

**Comment by mcauser** [comment]
Air602 WiFi Module - https://www.seeedstudio.com/Air602-WiFi-Module.html
Air602 USB Dev Board - https://www.seeedstudio.com/Air602-WiFi-Development-Board.html

Seeed W600 Module - https://www.seeedstudio.com/W600-Module-p-4020.html
Seeed W600 UART Dev Board - https://www.seeedstudio.com/Grove-W600-p-4019.html

Winner Micro product page - http://www.winnermicro.com/en/html/1/156/158/497.html
Collection of W60x resources - https://w600.chip.haus/

**Comment by wdyichen** [comment]
A new development board was added: https://www.seeedstudio.com/W600-Arduino-IoT-Wi-Fi-Board-p-2926.html

**Comment by chrismas9** [comment]
Is this port supported by Winner Micro, or is it a private contribution? What is the bug status of the W60x? ESP8266 and ESP32 have some issues like non linear analog that don't look like being fixed. Espressif seem to just delete broken features from the data sheet instead of fixing them. Having a better alternative for commercial and industrial use would be great.

What is the status of the 68 pin W601 and modules for it? The W600 doesn't have ADC so I think the W601 would be of interest to MicroPython users. It's only on the Chinese website. Do you know if there is an English data sheet for the W601?

It's good to see the WMIOT601 reference module has FCC approval.

**Comment by wdyichen** [comment]
Hi @chrismas9 , thank you for your interest.

1. This port is provided and maintained by WinnerMicro.
2. The bugs we're talking about here are those that haven't been discovered yet. If they're proven, we'll fix them.
3. Yes, W600 does not have ADC, W601 has ADC. But W600 can use RC circuit to collect ADC with IO, which is suitable for inaccurate occasions.
4. W601 is already on sale. We have now updated the English documents: http://www.winnermicro.com/en/html/1/156/158/536.html.

**Comment by dpgeorge** [comment]
Thanks @wdyichen for the information.

I didn't look at this PR in detail yet, because there is a lot to go through.  But from what I did see so far I have the following questions:
- threading is enabled, so does the W600 SDK provide an RTOS?  Is this RTOS necessary for the WiFi and/or the TCP/IP stack to work?
- it looks like the `usocket` module is based on the ESP32 implementation and calls into the lwIP high-level socket API, like `lwip_connect()`.  Did you try to instead use the PCB-level API of lwIP via the `extmod/modlwip.c` module?  Or is there a reason this is not possible (maybe related to the above question about threads)?
- SSL/TLS is not enabled.  In there a reason for this?
- I see the W600 has 1MiB of internal flash.  How much of this is used by the current MicroPython firmware you have here?
- The heap size is set to 45k.  Is it possible to increase this or is the rest of the RAM (288k it looks like in total) used by the WiFi and TCP/IP stack?

**Comment by wdyichen** [comment]
Thanks @dpgeorge .

Yes, w600sdk integrates FreeRTOS. At present, both LwIP stack and WiFi stack are.
In this porting code, MPY is just a task running in FreeRTOS, 
In the process of transplantation, we found that usocket module can be seamlessly 
integrated with our protocol stack, while using modlwip module needs some adaptation, 
so we use usocket module

MBEDTLS applications have not been ported in W600 SDK, but SSL modules will be added in the future.

This migration code compiles 321KB firmware, 
because a part of flash is used as the filesystem, so IMG firmware can not exceed 352KB at most.
W600 now has a 2Mflash version, which may be a better choice.

This 45K heap is only allocated to MPY applications, and WiFi and TCP / IP stacks do not use this part of heap memory. 
W600 has block memory (160k + 128k), only the first 160K memory is used, while the latter 128K memory is reserved for WiFi and tcp/ip stacks.

**Comment by dpgeorge** [comment]
> MBEDTLS applications have not been ported in W600 SDK, but SSL modules will be added in the future.

It would be easy to just enable axtls or mbedtls within MicroPython, there is no need to have it come from the W600 SDK.  But it requires a fair amount of flash space.

> This migration code compiles 321KB firmware,
> because a part of flash is used as the filesystem, so IMG firmware can not exceed 352KB at most.
> W600 now has a 2Mflash version, which may be a better choice.

This was my concern, that there would not be enough flash space for a useful set of features (eg TLS included).  Indeed the 2Mbyte flash version sounds like a better choice.

> W600 has block memory (160k + 128k)

So, can more of this 160k be allocated to MicroPython applications, or is 45k the maximum?

**Comment by wdyichen** [comment]
- Please forgive me how to use mbedtls in mpy. 
When I update the submodule, I see the source code of axtls, 
but there is no source code for mbedtls, 
so I think we may need to port mbedtls in the W600 SDK.

- W600 has hardware encryption and decryption function, 
which can be replaced in mbedtls. 
The final code increment is about 25K+. 
At present, 1M flash is enough.

- Because porting code compiles need to rely on w600 sdk, 
you can only use up to 45K+ of memory without modifying sdk code. 
If you modify the sdk code to reduce the memory occupied by wifi 
when compiling the firmware, you can still increase the memory used by mpy.

**Comment by nickzoic** [comment]
I've got some of these modules somewhere around so I'll have a go at building and see if I can provide some feedback.

**Comment by wdyichen** [comment]
w600 currently only supports gcc 4.x version, please refer to the url in README.

**Comment by tve** [comment]
I'm trying to use a W600, compiling the firmware... Maybe you could enable issues on your repo so I can ask questions there?
For my use-case I need SSL, but you only enable that with MICROPY_USE_2M_FLASH, but I don't see that 2MB devices exist? Is it possible to configure the partitions so one can use SSL and drop OTA? It looks like just defining MICROPY_USE_2M_FLASH on a 1MB device produces a working firmware but I suspect that OTA will fail, or does something else fail too?

**Comment by tve** [comment]
Another problem I have is that none of the tools, such as pyboard, rshell, or mpfshell work. The reason is that line endings are printed as `\r\r\n` instead of `\r\n` and that defeats the "entered raw mode repl" detection in pyboard.py. I suspect there is a `\n`->`\r\n` conversion being done in the SDK/OS layer.

**Comment by wdyichen** [comment]
Sorry, @tve 

> because mbedtls (ssl) is too integrated, 1Mflash does not have enough storage space.
> Because mpy is based on W600SDK, its OTA function is not tailorable.
> Enable` MICROPY_USE_2M_FLASH, as long as the firmware size does not exceed the limit, it can also be used on 1Mflash, no need to worry.

> You are right, this conversion exists in sendchar () in SDK

**Comment by tve** [comment]
> You are right, this conversion exists in sendchar () in SDK

Yup, I just found it... I'll hack that, hopefully that will make pyboard work...

**Comment by tve** [comment]
Some more issues:
- when updating the firmware the filesystem gets wiped, so one also has to re-upload all the files.
- if I immediately try to connect to Wifi in main.py it hangs in the connection establishment
- when it hangs ctrl-C has no effect, there also seems to be no way to prevent main.py from running at boot time

**Comment by wdyichen** [comment]
> Some more issues:
> 
> * when updating the firmware the filesystem gets wiped, so one also has to re-upload all the files.
> * if I immediately try to connect to Wifi in main.py it hangs in the connection establishment
> * when it hangs ctrl-C has no effect, there also seems to be no way to prevent main.py from running at boot time

You can use the firmware of * _gz.img format for programming. When using the littlefs file system, as long as its size does not exceed 384KB, the existing files will not be lost.  Did you add the code for WIFI connection in main.py?  The WIFI connection method will not hang. If it is necessary to query the WIFI connection status in an endless loop, please add a delay in the loop to prevent the hang and not responding to ctrl + c.

**Comment by tve** [comment]
@wdyichen thanks for all the help!

I can confirm that I had `while not wlan.isconnected(): pass` in main.py. Changing it to `while not wlan.isconnected(): time.sleep_ms(100)`  works around the Wifi issue. I still can't ctrl-C out of it. It sounds like there are two issues coming out of this:
- the Wifi FreeRTOS task(s) needs to run even if the MP task is in an infinite loop, this may be a task priority issue or perhaps FreeRTOS is not configured to be pre-emptive? (I forget what options FreeRTOS provides). Alternatively, perhaps MICROPY_EVENT_POLL_HOOK in mpconfigport.h or something in mphalport.c needs to be tweaked to ensure the Wifi task doesn't starve.
- the UART driver should really be interrupt-driven and ctrl-C should be checked in the interrupt handler, this probably means the SDK should not be used for the main uart...

Thanks also for clarifying the difference between `make flash` and `make image`, I didn't understand that from the readme. I tried `make image` but it always fails:
```
connecting serial...
serial connected.
wait serial sync.......
serial sync sucess.
mac 28-6D-CD-2B-90-05.
start download.
0% [
download failed, please reset and try again.
make: *** [Makefile:355: image] Error 145
```
Also a suggestion: in `./tools/download_img.sh` you have a line `SERIAL_NAME=` with instructions to modify it. If instead you commented out that line (`#SERIAL_NAME=`) one could use something like `make V=x SERIAL_NAME=ttyUSB2 image` and would not have to edit the file each time the port changes.

**Comment by tve** [comment]
Somehow SSL doesn't work for me:
```
MicroPython v1.10-286-g162de770b-dirty on 2020-01-27; WinnerMicro module with W600
Type "help()" for more information.
>>> import usocket as socket
>>> import ussl as ssl
>>> s = socket.socket()
>>> s.connect(('192.168.0.14', 4883))
>>> s = ssl.wrap_socket(s)
#%')+Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 5] EIO
>>>
```
After this the repl is dead, i.e., it does not echo any characters nor execute anything. The above sequence works fine on an esp32 (using MP v1.12 though). The server I'm connecting to runs mosquitto with the default TLS configuration.

**Comment by wdyichen** [comment]
> @wdyichen thanks for all the help!
> 
> I can confirm that I had `while not wlan.isconnected(): pass` in main.py. Changing it to `while not wlan.isconnected(): time.sleep_ms(100)` works around the Wifi issue. I still can't ctrl-C out of it. It sounds like there are two issues coming out of this:
> 
> * the Wifi FreeRTOS task(s) needs to run even if the MP task is in an infinite loop, this may be a task priority issue or perhaps FreeRTOS is not configured to be pre-emptive? (I forget what options FreeRTOS provides). Alternatively, perhaps MICROPY_EVENT_POLL_HOOK in mpconfigport.h or something in mphalport.c needs to be tweaked to ensure the Wifi task doesn't starve.
> * the UART driver should really be interrupt-driven and ctrl-C should be checked in the interrupt handler, this probably means the SDK should not be used for the main uart...
> 
> Thanks also for clarifying the difference between `make flash` and `make image`, I didn't understand that from the readme. I tried `make image` but it always fails:
> 
> ```
> connecting serial...
> serial connected.
> wait serial sync.......
> serial sync sucess.
> mac 28-6D-CD-2B-90-05.
> start download.
> 0% [
> download failed, please reset and try again.
> make: *** [Makefile:355: image] Error 145
> ```
> 
> Also a suggestion: in `./tools/download_img.sh` you have a line `SERIAL_NAME=` with instructions to modify it. If instead you commented out that line (`#SERIAL_NAME=`) one could use something like `make V=x SERIAL_NAME=ttyUSB2 image` and would not have to edit the file each time the port changes.

Thanks for your feedback and suggestions, I will check for pending issues later.  make image failed, the firmware * _gz.img size may exceed 384KB.  Note that to use .img, just press the reset key to reset, and you do not need to press pa0 to enter the rom mode.

**Comment by wdyichen** [comment]
> Somehow SSL doesn't work for me:
> 
> ```
> MicroPython v1.10-286-g162de770b-dirty on 2020-01-27; WinnerMicro module with W600
> Type "help()" for more information.
> >>> import usocket as socket
> >>> import ussl as ssl
> >>> s = socket.socket()
> >>> s.connect(('192.168.0.14', 4883))
> >>> s = ssl.wrap_socket(s)
> #%')+Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> OSError: [Errno 5] EIO
> >>>
> ```
> 
> After this the repl is dead, i.e., it does not echo any characters nor execute anything. The above sequence works fine on an esp32 (using MP v1.12 though). The server I'm connecting to runs mosquitto with the default TLS configuration.

Is this using 2M flash?  You try if you can run the ssl example in this document:http://www.winnermicro.com/en/upload/1/editor/1573450100546.pdf

**Comment by tve** [comment]
> > Somehow SSL doesn't work for me:
> > ...

> Is this using 2M flash? You try if you can run the ssl example in this document:http://www.winnermicro.com/en/upload/1/editor/1573450100546.pdf

Yes, I'm using the 2M flash build on a 1M flash chip (W600-PICO). I made the build myself. Is there a pre-built image with SSL I can download?

I tried the example from the PDF with some print statements added:
```
> cat baidu.py
import socket
import ussl
s = socket.socket()
addr = ('www.baidu.com', 443)
s.connect(addr)
print("Connected to baidu")
sec = ussl.wrap_socket(s)
print("Socket wrapped")
sec.write("GET / HTTP/1.1\r\n\r\n")
print("Sent get")
n = sec.read(1024)
print(n)
sec.close()
s.close()
```
log:
```
    __            __
    \ \    /\    / /
     \ \  /  \  / /
      \ \/ /\ \/ /
       \  /  \  /
       / /\  / /\
      / /\ \/ /\ \
     / /  \  /  \ \
    /_/    \/    \_\
Waiting on Wifi...
Connected!
MicroPython v1.10-286-g162de770b-dirty on 2020-01-27; WinnerMicro module with W600
Type "help()" for more information.
>>> import baidu
Connected to baidu
mbedtls_ssl_handshake error: -2500
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "baidu.py", line 7, in <module>
OSError: [Errno 5] EIO
```
I haven't traced down what error -2500 could mean...

**Comment by robert-hh** [comment]
Hello @wdyichen. Thank you for your work. I just made a few tests with a TB-01 Wi-Fi device. Some comments:

-  littflefs seems to need some rework. When calling uos.getcwd() after booting, the devices simply stalls. That happens both with the firmware from the WinnerMicro pages and a self-compiled version. After calling uos.chdir("/flash") getcwd works. So it looks like the initilization is missing or wrong.
- file operations with littlefs have funny effects. Sometimes are characters added upfront the name of a new created file. Or data written to a file is not what it meant to be. The FAT filesystem works perfect.
- Using the configuration from the firmware package, I cannot build an image with less than 512kB size, following your instructions. It is about 530kB. I have to disable WiFi AP to make it smaller than 512K. Downloading IMG files does not work to the end. The download works, but the image does not boot. 
 
I recognized already that I can also use the 2MB loader settings, especially since the img download fails. I modified also the download script for flash files not to erase the image area.

It is good that the ftp server operates in active mode. That way, Windows command line ftp works. And yes, please activate the "Issues" tab on your repository.

**Comment by wdyichen** [comment]
> Hello @wdyichen. Thank you for your work. I just made a few tests with a TB-01 Wi-Fi device. Some comments:
> 
> * littflefs seems to need some rework. When calling uos.getcwd() after booting, the devices simply stalls. That happens both with the firmware from the WinnerMicro pages and a self-compiled version. After calling uos.chdir("/flash") getcwd works. So it looks like the initilization is missing or wrong.
> * file operations with littlefs have funny effects. Sometimes are characters added upfront the name of a new created file. Or data written to a file is not what it meant to be. The FAT filesystem works perfect.
> * Using the configuration from the firmware package, I cannot build an image with less than 512kB size, following your instructions. It is about 530kB. I have to disable WiFi AP to make it smaller than 512K. Downloading IMG files does not work to the end. The download works, but the image does not boot.
> 
> I recognized already that I can also use the 2MB loader settings, especially since the img download fails. I modified also the download script for flash files not to erase the image area.
> 
> It is good that the ftp server operates in active mode. That way, Windows command line ftp works. And yes, please activate the "Issues" tab on your repository.
> 
> Edit: I am using version 7.3.1 of the gcc compiler. You mentioned that it only works with version 4. So what are the issues with other versions?

hello @robert-hh, thanks for your feedback.

The firmware size and the SSL problem mentioned by others may be caused by the 2M firmware that you have written to the 1M module. As far as I know, TB-01 has two modules, 1Mflash and 2Mflash. It is recommended that you use the tb-01 module of 2M flash for testing.

The gcc version is because this project is based on WMSDK. WMSDK is compiled based on GCC4.x, so there may be problems with higher versions of gcc (includes will vary between different versions of gcc). If you do not encounter compilation problems That is also possible, this is uncertain. But what is certain is that as long as the higher version of gcc can be compiled, the firmware will definitely work.

As you mentioned, we opened the Issues tab.

**Comment by robert-hh** [comment]
Hello Yichen. Thank you for the response. About your feedback:
I compiled the firmware too with a GCC 4.9 compiler. The result is the same. The size exceeds 521k. By stripping down some features, I can get it below 512k. In any case the problem with littlefs persists. That is already present with the firmware image from the winnermicro web site. In any case, FAT works well and using FAT results in a smaller firmware image.
About the 2MByte versions: There seem no breakout boards available with the chip. All I could find were 1MB versions.

**Comment by robert-hh** [comment]
Just in case someone is interested, I fixed a bug and an omission in main.c of that port. The link is here:
https://github.com/WinnerMicro/micropython/issues/1#issuecomment-612608250
The bug: File system operations are not stable. After the first garbage collection, the FS tipped over, both for FAT and littlefs.
The omission: After boot, littlefs, getcwd() cause a freeze. What was missing was the proper set-up of cur_dir at boot time.
I did not make a PR, since I could not fork the WinnerMicro fork of micropython without creating a new git account. That seemed too much of work.
The W600 (and more the W601) looks like a good replacement for the ESP8266. The same code runs about 2-3 times faster, and it has a good UART, ftp built-in, Encryptionm, ... I hope the 2MB flash versions will show up soon as breakouts at more places than tabao.com.
And I hope that WinnerMicro will update it's micropython version.

**Comment by nickzoic** [comment]
>  I did not make a PR, since I could not fork the WinnerMicro fork of micropython without creating a new git account. That seemed too much of work.


Good stuff!

The fork-of-a-fork thing is very painful but it is doable: I work on both MicroPython and CircuitPython!

I'll post some instructions, it's not obvious ...

**Comment by robert-hh** [comment]
@nickzoic 

> The fork-of-a-fork thing is very painful but it is doable: I work on both MicroPython and CircuitPython!
> I'll post some instructions, it's not obvious ...

Any progress on the instructions?

**Comment by stinos** [comment]
Isn't this essentialy just adding another remote to git? I.e. say now you have `origin` pointing to your fork roberthh/micropython, something like `upstream` pointing to micropython/micropython so if you add another `upstream_cp` poiting to circuitpython/micropython and 'origin_cp' pointing to your fork of that you have everything in one repository.

However seeing that CircuitPython is `6213 commits ahead, 2058 commits behind micropython:master.` just using completely separate directories might be way easier.

**Comment by robert-hh** [comment]
The problem is, that if I try to form winnermicro/micropython, if get the fork of micropython/micropython. But that is just a side story. Since the winnermicro fork is at version 1.10, I copied the w600 files from that repository to my copy fork/clone of micropython/micropython into a branch called w60x. That way, it is now based on the up-to-date version of micropython.

**Comment by nickzoic** [comment]
Yep, so, if I recall correctly:

* You can only have one 'github fork' of a project per user.
* ... but you can have as many branches as you want, even if they're of different 'forks'.

So:

* Make a fork on Github of the original Micropython repo, so now you've got a `yourname/micropython` repo which you can use to make pull requests
* Clone your fork.
* In that clone, do `git remote add micropython https://github.com/micropython/micropython` and/or `git remote add circuitpython https://github.com/adafruit/circuitpython` etc. Then do `git fetch --all`
* You can now check out branches from any of those repos and make your own branches based on them, eg: `git checkout remotes/circuitpython/master; git checkout -b nickzoic-circuitpython-123456`
* When you push those branches with `git push -u origin yourbranchname` they'll end up on your github fork and you can PR them ... github will work out which upstream the PR actually belongs to.

**Comment by snorkman88** [comment]
Hi @wdyichen what is the status of this port? Is there a stable version of it?
Thanks!

**Comment by dpgeorge** [comment]
There has not been much interest in this MCU/port in the past 2 years.  Also, it is a lot of work to add a new port to MicroPython due to the ongoing maintenance effort.  So I will close this pull request.

Feel free to maintain this port in a separate repository and keep it up to date with MicroPython.  If there is enough interest in it, the issues with gcc version can be resolved, and someone is willing and able to maintain it, then we can reconsider getting it into this repository.

Thanks for your efforts!

**Comment by robert-hh** [comment]
There is a recent port for the W60X device kept recent here: https://github.com/robert-hh/micropython/tree/w60x and some pre-built images here: https://github.com/robert-hh/Shared-Stuff. The work of extending this PR's version was done by @e-tobi and me, with support and feedback by @wdyichen .
The branch is updated regularly, especially when there are major changes to the code base of new revisions. The W60x is quite nice and a good alternative to the ESP8266. It's a pity that only the 1MB version is available. But it has sufficient many GPIO ports to add an external flash chip. The library for the device is OK, but the build set-up is not compatible to MP. Therefore I never considered to make a PR.

**Comment by dpgeorge** [comment]
Thanks @robert-hh for pointing out your fork/branch (at least I didn't know of it).  It's good to hear that something has come of this work.

**Comment by wdyichen** [comment]
Thanks @dpgeorge @robert-hh for attention.  I am no longer supporting this project due to job changes. We may port mpy to new chips in the future.

**Comment by LexxM3** [comment]
> Thanks @dpgeorge @robert-hh for attention. I am no longer supporting this project due to job changes. We may port mpy to new chips in the future.

@wdyichen, is the situation that you (personally) are not supporting the W600/W601 or is the situation that Winner Micro is no longer supporting and/or manufacturing the W600/W601?

I've recently come across these devices and I am in agreement with others such as @robert-hh that W600/W601 at current cost levels or below very much has a place in the market.  I apologize if this is obvious, but the reason it has not had a significant pick up seems almost entirely due to this shallow and intermittent software support.  Myself, @robert-hh, and others would be happy to take over and continue the support at this stage based on @robert-hh's work, but we need to know whether that's a waste of effort because Winner Micro has abandoned this chip entirely.  If you cannot answer this, @wdyichen, perhaps you can motivate someone at Winner Micro to do so promptly.

**Comment by wdyichen** [comment]
> > Thanks @dpgeorge @robert-hh for attention. I am no longer supporting this project due to job changes. We may port mpy to new chips in the future.
> 
> @wdyichen, is the situation that you (personally) are not supporting the W600/W601 or is the situation that Winner Micro is no longer supporting and/or manufacturing the W600/W601?
> 
> I've recently come across these devices and I am in agreement with others such as @robert-hh that W600/W601 at current cost levels or below very much has a place in the market. I apologize if this is obvious, but the reason it has not had a significant pick up seems almost entirely due to this shallow and intermittent software support. Myself, @robert-hh, and others would be happy to take over and continue the support at this stage based on @robert-hh's work, but we need to know whether that's a waste of effort because Winner Micro has abandoned this chip entirely. If you cannot answer this, @wdyichen, perhaps you can motivate someone at Winner Micro to do so promptly. Perhaps as further motivation for Winner Micro to be communicative and transparent is that such approach will maintain credibility for the company within the developer community for other and future devices (whereas lack of it may well not).

It's just that I personally don't support it. winnermicro still makes and supports the chip.

**Pull request closed without merging**
