### PR TITLE
ESP32: enable wake-on-touch

### PR DESCRIPTION
**Pull request by manningt**
ports/esp32/modesp32.c: Add touch_pad_set_meas_time & touch_pad_set_fsm_mode.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the patch.

Perhaps it's better to call these functions in `ports/esp32/machine_touchpad.c`, just after `touch_pad_init()`?  That would match better with what the ESP32 docs say about the use of these functions, and also mean that `touch.config()` can be called before (or after) `esp32.wake_on_touch()`

**Comment by manningt** [comment]
I originally put the 2 calls in `machine_touchpad.c`.  I moved them to `modesp32.c` figuring it would only change the touch_pad behavior (FSM mode & meas_time) for applications using wake_on_touch, instead of changing it for all touch_pad applications.  I'd be fine with putting it after `touch_pad_init()`; I just wanted to explain the reasoning.  Please indicate which you prefer.

**Comment by dpgeorge** [comment]
>  I'd be fine with putting it after `touch_pad_init()`; I just wanted to explain the reasoning.

It's definitely good to consider the impact of a change.  But I'd prefer it to go just after `touch_pad_init()`.  Using the hardware timer for touch should give better results (I guess?) and gives a cleaner implementation.  If it really affects users then we can (later on) add an option to TouchPad to select which FSM mode is used.

**Comment by manningt** [comment]
Made the change to perform the 2 calls after touch_pad_init in machine_touchpad.c, per the preference.

**Comment by dpgeorge** [comment]
Thanks for updating the PR.  I tested it and found that it takes about 0.5 seconds (a noticeable time at the REPL) to initialise (construct) and call config() on a touch pad object.  And this is because the `sleep_cycle` value is large.  Reducing this value to 0x1000 makes it much faster and from what I measure doesn't really affect the light-sleep current.

The default values for `sleep_cycle` and `meas_cycle` are 0x1000 and 0x7fff.

I'd prefer to keep the `sleep_cycle` the default of 0x1000.  Eventually it could be configured by the user.  @manningt do you agree to change it to 0x1000?

**Comment by manningt** [comment]
Agree to leave the` sleep_cycle` and `meas_cycle` at their defaults, so I removed the call to touch_pad_set_meas_time.  Changing the sleep_cycle does result in a power savings (20-40 uA on my custom PCB), but it requires modifying the threshold setting (set using touchpad.config), which may impact some users.

**Comment by dpgeorge** [comment]
Thanks for updating.  Merged in 887a6712c2a302bd0bdeceb8ee9bc33a6de64dae

**Pull request closed without merging**
