### PR TITLE
The CC3200 port is ready to go live

### PR DESCRIPTION
**Pull request by danicampora**
There are still things to do, like adding Python bindings for SPI and I2C, but the core functionality is in. The REPL can be accessed over telnet and UART, and the file system is accessible through the FTP server running on the board. There are 2 drives, a 128KB one located in the serial flash and another on the SD card (if inserted). With the release image there are currently 72KB of RAM available for the MicroPython heap and 6.5KB reserved for the stack. The goal is to still have around 64K of heap available after adding SPI, I2C and hardware timers support. The rest should be implemented in Python depending on the specific needs of each project.

### CODE REVIEW

**Comment by dpgeorge** [comment]
It's a big merge and I can't check it all.  And I don't even have a CC3200 board to test it on...

Are all the files necessary?

**Comment by danicampora** [comment]
Well I see that many files were changed by Git to fix the line ending thing. Do you know how to fix that in a better way?

Apart from the line endings I have only modified readline to add the VT100 commands.

**Comment by pfalcon** [comment]
Yes, this is definitely very big merge. And if it's done like that - as one big code drop, all the individual revisions are not needed, especially if they're "Added a dummy hal copied from the teensy port, still not compiling". Why push to mainline stuff which doesn't compile? It should be rebase-squashed with later fixes, cutting amount of changes dramatically.

**Comment by dpgeorge** [comment]
I will rebase anyway.

Let's not change any of the files in stmhal if it's just line-end conversion.  I deliberately left them that way so it's easier to diff against a new version of the hal.

IIRC, there was only 1 file which we wanted to change line endings.

**Comment by danicampora** [comment]
Ok, I'll see how to fix the line endings and revert them back to what they were. Could you check what is the line endings config that you have set on your machines?

@pfalcon, I'll rebase my master branch too, you are right about that.

**Comment by pfalcon** [comment]
And that's without looking into actual content of changes. https://github.com/danicampora/micropython/commit/7d785828e51e223e0050e1d21934f4b09a366230 imports fatfs. But we already have fatfs in the codebase, having 2 copies is not maintainable. But that's minor comparing with https://github.com/danicampora/micropython/commit/c175554e1f1c5853813210a0be36cb1ab951ff5c which bring GPL material into the codebase and thus contaminates it. MicroPython is MIT licensed project, having copyleft license (no matter with "exceptions" or not), immediately brings concerns.

**Comment by dpgeorge** [comment]
I don't have any line ending config.  Ie blank.

The point of putting fatfs in lib/ was so CC3200 could use it.  I think @danicampora removed his duplicate after we moved fatfs.  Squishing should show this.

**Comment by danicampora** [comment]
Yes, I removed FatFS from the CC3200 directory after it was moved to lib/.
My port can't work without FreeRTOS...

**Comment by dpgeorge** [comment]
FreeRTOS has a modified GPL which does not require you to provide source of your "other" part of the application...

**Comment by danicampora** [comment]
So, if having FreeRTOS GPL is not possible, either a have to find another
RTOS, or this branch is gonna have to remain separate.

**Comment by pfalcon** [comment]
Or FreeRTOS remains separate... I just wonder why all these issues weren't discussed before or along the way...

**Comment by danicampora** [comment]
Well, the FatFS issue was discussed and dpgeorge agreed to move to the /lib
directory. For FreeRTOS, I just didn't realize it was going to be a
problem, it is part of the CC3200 SDK, so I just went along with it.

**Comment by danicampora** [comment]
Well, at least take my changes in readline with the VT100 command, so that I don't have to keep merging them everytime ;-)

**Comment by chrismas9** [comment]
So, if having FreeRTOS GPL is not possible, either a have to find another
    RTOS, or this branch is gonna have to remain separate.

I don't know if it is suitable, but http://scmrtos.sourceforge.net/ScmRTOS is MIT licensed.

**Comment by dpgeorge** [comment]
The first thing we should do is split out all changes to existing code, merge those, and then we will have just new files in the cc3200-launchxl directory to deal with.

What are the changes to existing code?  Don't worry about converting newlines.  Is the only other thing the change to readline?

**Comment by danicampora** [comment]
Well, besides readline, there's also this:

https://github.com/danicampora/micropython/commit/9825cc0c3ab89ab19dba61b8adc3def70951163b

Of which I am not sure of, but I had to add it, otherwise when interrupting
a running script from /flash, instead of simply breaking it would jump to a
soft_reset.

And this:
https://github.com/danicampora/micropython/commit/b267e604caa4049e23c80d94fcd6348b95eafb60
(scroll to the bottom, to py/ob.c and py/obj.h). I believe that fix for the
NDEBUG define is correct.

Those all are the changes out of the cc3200-launchxl directory.

**Comment by dpgeorge** [comment]
In 17d299b7bd24cb4e98dd3e714989a30bafa67ba1 I used VT100 codes in readline.

**Comment by dpgeorge** [comment]
In 8788b131ecff3c2f203efbdb9f30942823981136 I fixed the NDEBUG thing in py/obj.c and py/obj.h

**Comment by danicampora** [comment]
Nice, thanks!!

**Comment by dpgeorge** [comment]
> Of which I am not sure of, but I had to add it, otherwise when interrupting a running script from /flash, instead of simply breaking it would jump to a soft_reset.

This, I don't understand why it does it.  You say that if it runs /flash/boot.py or /flash/main.py and you press CTRL-C while one of these are running, then it does a soft reset?

**Comment by danicampora** [comment]
What happens is the following: when I press CTRL-C, the code in pyexec.c jumps to:
```c
        // uncaught exception
        // FIXME it could be that an interrupt happens just before we disable it here
        mp_hal_set_interrupt_char(-1); // disable interrupt
        // print EOF after normal output
        if (exec_flags & EXEC_FLAG_PRINT_EOF) {
            stdout_tx_strn("\x04", 1);
        }
        // check for SystemExit
        if (mp_obj_is_subclass_fast(mp_obj_get_type((mp_obj_t)nlr.ret_val), &mp_type_SystemExit)) {
            // at the moment, the value of SystemExit is unused
            ret = PYEXEC_FORCED_EXIT;
        } else {
            mp_obj_print_exception(printf_wrapper, NULL, (mp_obj_t)nlr.ret_val);
            if (mp_obj_is_subclass_fast(mp_obj_get_type((mp_obj_t)nlr.ret_val), &mp_type_KeyboardInterrupt)) {
                ret = PYEXEC_KB_EXIT;
            } else {
                ret = 0;
            }
        }
```
`mp_type_KeyboardInterrupt` is not a subclass of `mp_type_SystemExit`, so the check for SystemExit fails, thats why I added the else block afterwards. I made I mistake with my previous comments, the truth is that without the added code, interrupting a 'main.py' script with CTRL-C causes the output of `__fatal_error("could not run MAIN.PY");`

Probably is because I have a bug in my implementation of the `interrupt char` for the CC3200, but I was not able to see the issue. Let's have another look....

**Comment by danicampora** [comment]
I have the following code in 'main.py' to test CTRL-C:
```python
# main.py -- put your code here!
import pyb

led = pyb.GPIO('GPIO9', pyb.GPIO.OUT)

while True:
    led.toggle()
    pyb.delay (250)
```
Just before the board runs the endless loop that toggles the LED, I see the processor executing (mp_call_function_0()) in:
```c
    if (nlr_push(&nlr) == 0) {
        mp_hal_set_interrupt_char(CHAR_CTRL_C); // allow ctrl-C to interrupt us
        mp_call_function_0(module_fun);
        mp_hal_set_interrupt_char(-1); // disable interrupt
```
and then, when I press CTRL-C, instead of continuing execution from `mp_hal_set_interrupt_char(-1); // disable interrupt` it executes the `else` block... any idea what's going on? Thanks!

**Comment by danicampora** [comment]
The main difference from the stmhal port is that for the CC3200 CTRL-C interrupts are only marked for the VM to notice them, there is no pendsv mechanism.

**Comment by dpgeorge** [comment]
Everything is functioning correctly.  The problem is that you shouldn't have a fatal error if execution of boot.py or main.py returns non-zero.  In stmhal/main.c it calls flash_error on error, which just flashes some leds then continues.

**Comment by danicampora** [comment]
Good point, I was just testing it a minute ago with the official pyboard.
Somehow when I checked the stmhal/main.c I misunderstood the whole thing.
It is clear now, sorry for the confusion :(

**Comment by danicampora** [comment]
The pyexec mess is fixed with https://github.com/micropython/micropython/commit/8ff2c57677c734919e6f5e16fd2b9f5595672daa

**Comment by dpgeorge** [comment]
Okay, so I assume now that the only changes in this PR are the addition of the files in the cc3200-launchxl directory?

**Comment by danicampora** [comment]
Yes, plus the changes to `.travis.yml`.

**Comment by danicampora** [comment]
I just noticed that the README.md is a bit `outdated`, the build command is incorrect and the bootloader documentation is missing. I am fixing it right now.

**Comment by danicampora** [comment]
The documentation is now up to date after 1a3a267f020e173e89d38d9cbff5c5d096ceedce

**Comment by pfalcon** [comment]
Any progress on this PR? There're some pending move refactors to do on stmhal port, which I kinda postpone because they will likely lead to conflicts here.

**Comment by danicampora** [comment]
AFAIK, the cc3200-launchxl directory can be taken and added to the repo. @dpgeorge, if there's still anything pending from my side, please let me know, I'll do it ASAP.

**Comment by dpgeorge** [comment]
I can confirm that th cc3200-launchxl dir builds cleanly against current master, so it's simply a matter of importing this new directory.

The TI drivers have a BSD style license.  @danicampora's code is MIT licensed.  The FreeRTOS code is modified GPL which doesn't require you to release source code for the components external to FreeRTOS.  We should probably add a note somewhere saying that the license may be different for different parts of the repo.

About the name of the dir: can it just be cc3200?  Will there be other boards in the future based on the cc3200 that this port can support?

**Comment by danicampora** [comment]
Now that you mention it, there's going to be another board with the CC3200 very soon. We are finishing the design and there's going to be Kickstarter campaign to launch it, very shortly. I would suggest to make the dir CC3200, and later on create a /board directory inside to put all the boards specific parts in it, just like it is done with the stmhal port.

**Comment by dpgeorge** [comment]
> We are finishing the design and there's going to be Kickstarter campaign to launch it, very shortly.

This is news!  Can you give more details?  Is it your design/project?  Does it primarily run uPy or is that just a bonus?

**Comment by danicampora** [comment]
Yes, of course I can give more details ;-)
I am working on it together with 2 very good dutch friends (I live in the Netherlands, but I'm not dutch myself). It is going to be 100% MicroPython centric directed towards IoT applications. The initial launch will include a tiny main board with the CC3200 and several stackable boards with lots of cool things. The goal is to make the boards very low cost, including the main board (it won't be able to compete with the ESP8266 in terms of price, but it will get close). If everything goes as planned, the campaign should be there by end of February.

**Comment by danicampora** [comment]
This Wednesday I am holding a presentation about MicroPython and the CC3200 in an embedded systems group in Eindhoven. Hopefully, some of them will be very interested in collaborating with the project.

**Comment by dpgeorge** [comment]
> It is going to be 100% MicroPython centric

It sounds good and I look forward to seeing it live!  But for now the question is: will this repository here hold the official code for your product?  Or will you have a separate one as did the recent OpenMV cam https://github.com/iabdalkader/openmv ?

**Comment by danicampora** [comment]
Well, since in my own repo everything started very messy (and slow...), my idea at this moment is start a separate at some point one to hold the official code, and begin with a more structural and organised workflow there. How do you suggest to do it in order to make things as smooth as possible for the MicroPython upstream?

**Comment by dpgeorge** [comment]
Well, it doesn't seem sensible to have 2 separate repos for the cc3200 port.  Most likely the one here will get neglected if yours is the "more official" one.  It would be nice to keep our work well integrated, and any bugs you find in the core (or features you think should be added) can be better served if we work in the same repo.  On the other hand, it might be best from an issue-tracking point of view to keep things separated.  Also, you would likely want/need write access to this repo so you don't have to keep doing PRs :)

Maybe we can make a separate repo under the micropython organisation?

**Comment by danicampora** [comment]
@dpgeorge I agree 100% with your previous comments. The more we can keep our work well integrated, the better.
That idea about the separate repo under the MicroPython organisation sounds really good.

**Comment by dpgeorge** [comment]
@pfalcon any thoughts regarding how we do this?  Merge cc3200 into this repo or create a new repo under the micropython organisation?

**Comment by pfalcon** [comment]
Well, dunno. Of course, it would be better to have single repo, but that would require spending additional effort on refactoring code to make it clean before merging to common repo. @danicampora seemed to agreed that that's the way to go in
https://github.com/micropython/micropython/pull/1065#issuecomment-69995858 , but I don't see improvements - there're still ~ hundred of commits which add/remove/add things instead of dozen commits which just add final version of things.

But I understand that @danicampora may have other priorities than code clean up right now, and keeping common codebase would be still better than trying to maintain separate trees. So, I'll let you guys to decide on that.

**Comment by danicampora** [comment]
Well, @pfalcon has a point I haven't done any rebasing yet on the old commits, but I did start to squeeze every merged branch since the last one I merged (ExtInt), into one single commit. I really haven't done it on the old commits because: 1. @dpgeorge once said he would refactor anyway when bringing the CC3200 code in (Bad excuse, I know...), and 2. Like pfalcon said, I do have some other priorities at the moment, but cleaning up the history is indeed important. Anyway, I promise to rebase everything before starting implementing any new feature (that should be tomorrow, I hope...) Apologies for the long list of silly commits... ;-)

**Comment by dpgeorge** [comment]
Ok, well, we can aim to have it in a single repo; in this repo.  Need a few things for that to happen:

1. Tidy up this PR for merge.  Either make it 1 huge commit, or ~ dozen well separated ones.

2. Give @danicampora read/write access to this repo, with the understanding that he'll only push to cc3200 directory (at least for starters).  Also, must use our commit message format, with dir name and colon first.

3. Make sure that the cc3200 port has both the launch-xl board support, the soon-to-exist board from @danicampora, and will be used for any other cc3200 based boards.

**Comment by danicampora** [comment]
>Tidy up this PR for merge. Either make it 1 huge commit, or ~ dozen well separated ones.

I will do this ASAP, probably I'll squash the whole history into a single commit.

>Give @danicampora read/write access to this repo, with the understanding that he'll only push to ?cc3200 directory (at least for starters). Also, must use our commit message format, with dir name and colon first.

Ok, I will only push to the cc3200 directory, and will use the your commit message format.

>Make sure that the cc3200 port has both the launch-xl board support, the soon-to-exist board from @danicampora, and will be used for any other cc3200 based boards.

I will rename the cc3200-launchxl directory to cc3200, and create a /boards/launch-xl directories with all the specifics of this board inside. When more boards are added, the same approach will be followed.

I'll do my best to have all this ready today, I'll let you know...

**Comment by danicampora** [comment]
@dpgeorge @pfalcon I think the current state of the pull request fulfills the conditions discussed. Since I was the only one (up to now, I hope...) committing to the cc3200 port, I thought that the easiest was to squash everything into a single commit.

**Comment by dpgeorge** [comment]
Merged!  See 8785645a952c03315dbf93667b5f7c7eec49762f.

I removed the cc3200/doc/ directory and all its files.  Yes it's nice and convenient, but no we don't want 10mb of pdfs in this repo.

@danicampora please observe the following rules for pushing commits:

1. Always prefix message with "cc3200: " (or "py: " or whatever dir you are making the majority of the changes in).
2. Only use at most 72 chars for the first line of the message, then have a blank line, then an optional paragraph with extra detail with maximum line length of 72 chars.
3. First line should be a concise and precise description of the change, written in the style that "if I apply this patch, this is what will happen" (eg Add feature, fix bug; not added feature, fixed bug).
4. Optional paragraph should provide more information if it's needed.  Also a reference to the issue number if it addresses an issue.
5. Always try to rebase your changes on top of the latest master so that the history remains linear.  You'd use: git checkout master; git pull; git checkout my-dev-branch; get rebase -i master; get checkout master; git merge my-dev-branch; git push.

Thanks!

**Comment by danicampora** [comment]
> I removed the cc3200/doc/ directory and all its files. Yes it's nice and convenient, but no we don't want 10mb of pdfs in this repo.

Fair enough!

Regarding the commit rules, I will follow them precisely every time. Thanks!!

**Pull request closed without merging**
