### PR TITLE
tools/mpy-tool.py: Win Compile path fix.

### PR DESCRIPTION
**Pull request by mbedNoobNinja**
`tools/mpy-tool.py`:  Inspect platform and adapt the path.
`tools`:  Replace **/** with **\\** for compilations on win platforms.

### CODE REVIEW

**Comment by stinos** [comment]
Similar to #10573. But I think replacing the backslashes should not be done depending on platform, but always? It's possible to create a .mpy on windows then use it on linux for instance, right?

**Comment by mbedNoobNinja** [comment]
Sure it is possible, but It must be possible for the user to create the .mpy on whatever platform he has (in my case ,it is only WIN 10 + msys2)

**Comment by stinos** [comment]
Sorry should have been more clear; when creating a .mpy with the msvc port it can have backslashes, or forward slahes, or both even. So in order to make that work, all slashes must always be converted, irregardless of platform.

**Comment by dpgeorge** [comment]
Now that `mpy-cross` converts `\` to `/`, is this PR needed?  See 7e9a15966acf80ff50fdf5c52553dd56de164bb3

**Comment by mbedNoobNinja** [comment]
Hi @dpgeorge, I tried  https://github.com/micropython/micropython/commit/7e9a15966acf80ff50fdf5c52553dd56de164bb3 commit and indeed that fixed the issue. Micropyton is now compilable on Windows machines and this PR is not needed anymore.

**Pull request closed without merging**
