### PR TITLE
contributing: Made PR section stand out

### PR DESCRIPTION
**Pull request by higstar**
Seeing as I skipped over the first link, as I only read "reporting an issue..." and went straight down to the coding conventions, I thought it could be improved by bolding the PR section.

### CODE REVIEW

**Comment by stinos** [comment]
Personally I don't regard this an improvement: there's basically just one sentence, I don't think we should try to account for people who don't have the patience to read a single sentence (no offence meant, and I suffer from that problem sometimes as well) because by that logic we can just as well put everything in bold.

If anything there can be some rephrasing though: 99% of the time one only needs to read the code convetions when submitting a PR but not when submitting an issue, but now there's no clear distinction between those.

**Comment by higstar** [comment]
> rephrasing

I did consider converting to bullet points, or putting the submitting PR part first, however then it would loose the "Especially" comment.

**Comment by dpgeorge** [comment]
This is such a short file, I don't think it's necessary to make this part stand out like this.

Instead, if the real problem is that issues/PRs are not being submitted in the correct form, then it would be better to add issue and PR templates https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by higstar** [comment]
No sweat, I got fired up with Hacktoberfest with a few PRs :)

**Pull request closed without merging**
