### PR TITLE
wiznet5k/ethernet/socket: Improve the performance of socket operations.

### PR DESCRIPTION
**Pull request by Li-Weiwei**
Use mp_hal_delay_ms instead of HAL_Delay in busy waiting to improve the
performance of connect, send, recv, sento and recvfrom.  
See discussion in issue #3307.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the patch.

The problem with it is that it would now be possible to break from one of these socket methods using ctrl-C.  That would be a good improvement, but it looks like there are a few cases where an exit via ctrl-C (which raises an exception) would leave the wiznet in an inconsistent state.

A simple way to fix it would be to call `pyb_thread_yield()` instead of the delay (actually it would need a macro to configure this to call to be something else if the driver is used by another port).  With this solution you'd need to keep the GIL calls in the modwiznet5k.c file.

A full solution would explicitly check for pending exceptions in the wiznet driver, and if one was pending then do clean up before raising it.

I would suggest doing it the former way (pyb_thread_yield) as a first step.

**Comment by Li-Weiwei** [comment]
I have re-made the changes, do not know whether to comply with specifications, please review and propose amendments. Thank you.

**Comment by dpgeorge** [comment]
This looks good!  Did you test it, did it improve performance?

**Comment by Li-Weiwei** [comment]
yes, I test it on pybv10, use the test script in issue #3307.

**Comment by dpgeorge** [comment]
@Li-Weiwei thanks for your effort and for making a very clean set of commits.  I tested this and it does indeed improve performance when using threading.  Merged in 73e387cff6a3e31a9ea0c300d92a1a4a62d791ef

**Pull request closed without merging**
