### PR TITLE
Apply astyle to format all code (v1)

### PR DESCRIPTION
**Pull request by dpgeorge**
Per discussion in #4223, here is one attempt at formatting the code.

### CODE REVIEW

**Comment by MrSurly** [comment]
For reference, the formatting from https://github.com/micropython/micropython-esp32/issues/65 (`astyle -KSUHp -s4`) seemed to be acceptable in the past.

**Comment by dpgeorge** [comment]
Rebased on latest master to pull in changes to `mp_raise` functions.

**Comment by dpgeorge** [comment]
> For reference, the formatting from [micropython/micropython-esp32#65](https://github.com/micropython/micropython-esp32/issues/65) (`astyle -KSUHp -s4`) seemed to be acceptable in the past.

In long-arg form this is:
```
--indent-cases
--indent-switches
--unpad-paren
--pad-header
--pad-oper
--indent=spaces=4
```

Using indent-cases causes cases like this:
```c
case X: {
    int foo = bar();
    break;
}
```
to be formatted to:
```c
case X: {
        int foo = bar():
        break;
    }
```
which is understandable but touches a lot of code that uses this pattern.

Using pad-oper (pad operators, eg spaces in `a + b`) is probably a good idea because it fixes a lot of situations where the space is no there.  But it has issues with casting, eg:
```c
(void*)*(expr) -> (void*) * (expr)
(size_t)-1 -> (size_t) -1
```
These can be fixed by adding parenthesis around the expression that is being cast.

**Comment by dpgeorge** [comment]
One problem with astyle that I just noticed is that it doesn't handle bit-width specifications that are not constants.  It treats them as labels.  Eg it gives (from `py/objexcept.h`):
```c
typedef struct _mp_obj_exception_t { 
    mp_obj_base_t base;
size_t traceback_alloc : 
    (8 * sizeof(size_t) / 2);
size_t traceback_len : 
    (8 * sizeof(size_t) / 2);
    size_t *traceback_data;
    mp_obj_tuple_t *args;
} mp_obj_exception_t;
```
Using `--keep-one-line-statements` keeps it on one line but dedents it:
```c
typedef struct _mp_obj_exception_t { 
    mp_obj_base_t base;
size_t traceback_alloc : (8 * sizeof(size_t) / 2);
size_t traceback_len : (8 * sizeof(size_t) / 2);
    size_t *traceback_data;
    mp_obj_tuple_t *args;
} mp_obj_exception_t;
```
It looks like the only way to fix this (apart from modifying astyle) is to remove the parenthesis around the expression:
```c
typedef struct _mp_obj_exception_t {
    mp_obj_base_t base;
    size_t traceback_alloc : 8 * sizeof(size_t) / 2;
    size_t traceback_len : 8 * sizeof(size_t) / 2;
    size_t *traceback_data;
    mp_obj_tuple_t *args;
} mp_obj_exception_t;
```

**Comment by stinos** [comment]
Modifying astyle is an option of course, but the parentheses aren't really needed anyway so if removing them fixes it, it seems an ok solution? (This is the selling point of clang-format of course: using an AST to get proper contextual information avoids this, too bad it's not mature enough.)
+1 on padding operators and indenting switches

**Comment by dpgeorge** [comment]
Closed in favour of #5700.

**Pull request closed without merging**
