### PR TITLE
Move fsusermount.* out of stmhal for reuse

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by pfalcon** [comment]
This does minimal set of changes to just get going on this front. Config vars, etc. are subject to change when clear idea what they should be emerges. (To remind, issues like that was a reason why it wasn't made reusable in the first place, we should not block on such issues.)

**Comment by dpgeorge** [comment]
Looks good.

**Comment by pfalcon** [comment]
@dpgeorge : Thanks, merged. So, the further plan would to follow the same basic pattern as lwip module. Except there having module-level interface was OK, but here it's apparently clear that it makes sense to make VFS a full-fledged type, which would expose .open(), maybe .close(), .rename(), .remove(), etc.

**Comment by dpgeorge** [comment]
> here it's apparently clear that it makes sense to make VFS a full-fledged type, which would expose .open(), maybe .close(), .rename(), .remove(), etc.

But how to resolve the issue that the builtin `open` function will not be able to access such a VFS?  (Whereas on pyboard it currently does work.)

**Comment by pfalcon** [comment]
> But how to resolve the issue that the builtin open function will not be able to access such a VFS?

Based on the same idea as for lwip module. There, "import lwip as socket", and all works. With VFS, it'll be more involved (as it does make sense to have >1 FS mounted). E.g.:

~~~
vfs = FATFS(...)
open = vfs.open
# Now open can access VFS
~~~

Details and further steps (and need for them) can be considered later.

>  (Whereas on pyboard it currently does work.)

Sure, it'll keep working, only if/when there will be more general way to handle, can consider to switch. (Otherwise, a port would have choice - either to stmhal-style, or treat VFS as a standalone object).

**Comment by dpgeorge** [comment]
But things are conceptually different on stmhal/cc3200: the idea there is that pyb.mount (now os.mount and os.unmount) is providing access to the underlying "O/S" to do a true mount/unmount of the actual filesystem, and hence the bulitin open (and all other functions, like os.listdir) just work.  In contrast, the vfs object idea is separate and independent to the filesystem of the underlying OS.

**Comment by pfalcon** [comment]
> But things are conceptually different on stmhal/cc3200: the idea there is that pyb.mount (now os.mount and os.unmount) is providing access to the underlying "O/S" to do a true mount/unmount of the actual filesystem,

There's no OS and no "actual OS  filesystem" on them. So, whatever is made of them is result of conventions or stipulations. And we can assess what's able: arbitrarily, only 1 user-mounted filesystem is supported; arbitrarily, only single type of filesystem is supported.

>  In contrast, the vfs object idea is separate and independent to the filesystem of the underlying OS.

Yes, to resolve the restrictions mentioned above. How to integrate it into global open() is well-separated matter, with obvious solutions, like maintaining a map {"/mount/prefix": vfs_object}. (What's not obvious is whether such integration is needed, so let it stay a separate matter.)

**Comment by pfalcon** [comment]
> it makes sense to make VFS a full-fledged type, which would expose .open(), maybe .close(), .rename(), .remove(), etc.

Unfortunately, first stumbling block on that way is FatFs itself, which instead of taking FATFS* for operations, instead takes "volume numbers" and bothers to do mapping itself. So, that mapping would need to be worked around.

**Pull request closed without merging**
