### PR TITLE
Allow Unix variant to override MICROPY_EVENT_POLL_HOOK

### PR DESCRIPTION
**Pull request by dlech**
This allows unix variants to extend or replace more config options:

- extend builtin modules
- extend root pointers
- replace event poll hook

### CODE REVIEW

**Comment by dlech** [comment]
There seems to be a bug in uncrustify, so we can either have proper syntax with bad formatting:

```c
#define MICROPY_PORT_ROOT_POINTERS \
    const char *readline_hist[50]; \
    void *mmap_region_head; \
    MICROPY_BLUETOOTH_ROOT_POINTERS \
        MICROPY_VARIANT_ROOT_POINTERS \
```

Or an extra semicolon with proper formatting:

```c
#define MICROPY_PORT_ROOT_POINTERS \
    const char *readline_hist[50]; \
    void *mmap_region_head; \
    MICROPY_BLUETOOTH_ROOT_POINTERS; \
    MICROPY_VARIANT_ROOT_POINTERS \
```

**Comment by stinos** [comment]
Related #8144 i.e. it's going to take many more PRs like this before all options are wrapped and everyone is satisfied :)

**Comment by jimmo** [comment]
@dlech @stinos I think I'd prefer to make this work in a similar fashion to MP_REGISTER_MODULE (i.e. also add MP_REGISTER_ROOT_POINTER). See https://github.com/micropython/micropython/pull/8566 for the first step in deprecating MICROPY_PORT_BUILTIN_MODULES

That doesn't address MICROPY_EVENT_POLL_HOOK (although perhaps it could?) but also the broader issue raised in #8144 needs more thought.

**Comment by stinos** [comment]
> I'd prefer to make this work in a similar fashion to MP_REGISTER_MODULE (i.e. also add MP_REGISTER_ROOT_POINTER).

That sounds good

**Comment by dlech** [comment]
> That doesn't address MICROPY_EVENT_POLL_HOOK (although perhaps it could?)

This could be quite tricky to get right. As an example, here is our most complicated implementation currently: https://github.com/pybricks/pybricks-micropython/blob/f69bd694ba481563c980e09fae41b60c0ecea4fc/bricks/virtualhub/mp_port.c#L143-L185

Just allowing to override `MICROPY_EVENT_POLL_HOOK` seems like the simplest solution.

**Comment by dlech** [comment]
I have dropped the commits for registering extra modules and root pointers since those have been solved another way. 

The remaining commit for overriding `MICROPY_EVENT_POLL_HOOK` is still needed and has been rebased.

**Comment by dpgeorge** [comment]
Allowing to override MICROPY_EVENT_POLL_HOOK seems reasonable.  Merged in 03fb6718339fb77022a84b25875cc1daf804ac9a

**Pull request closed without merging**
