### PR TITLE
esp8266: SPI flash access functions and user mounting.

### PR DESCRIPTION
**Pull request by hosaka**
Combined all the effort from previous discussions: #1483, #1507.
- FatFS and SPI flash driver now only consist of 3 files with #1597 in place. Simplified read/write functions.
- Byte-by-byte writing for user space as well as 512 byte sector writes used by fatfs.
- All flash access functions are added to the esp module, prefixed with flash_*, all tested.
- Added user mounting via pyb.mount.

Needs further work:
- All read/writes have a fixed start/end offset address defined in [flash.h#41](https://github.com/alex-march/micropython/commit/c1d945a567a5ae81103967dc9624020ed93560c5#diff-30690a12b7f3b19c7101e08e1c05a433R41) in ESP sectors. [Previously discussed](https://github.com/micropython/micropython/pull/1507#issuecomment-153207970), it is possible to have an automatic offset decided by the linker. In the meantime I can keep or remove the existing #define.
- I haven't actually tested the pyb.mount yet, but shouldn't be too hard.
- Byte-by-byte access can be optimised by detecting if the requested size can fit in the buffer straight away and use memcpy. [flash.c#L111](https://github.com/alex-march/micropython/commit/c1d945a567a5ae81103967dc9624020ed93560c5#diff-b1a34dda7a441839ad25186dfeed826fR111)

### CODE REVIEW

**Comment by pfalcon** [comment]
@alex-march : Thanks, so far waiting in the queue due to other things in works.

**Comment by dpgeorge** [comment]
It looks clean.  You should now be able to do f_mount... did you try that out?

**Comment by alex-march** [comment]
Hey! No problem, I'm travelling at the moment so not in a hurry. Damien, I
haven't tried it with this patch, but previous version I could mkfs, mount,
open/write/read/close etc. no problem, so I believe this should work fine.
I haven't tried mounting using pyb.mount however, was hoping to try it when
I get back, or someone else might be able to.

**Comment by turbinenreiter** [comment]
pyb.mount(device, mountpoint) needs two args - the first is the device. Can't use the SD card driver because SPI isn't implemented. Functions for SPI flash are there, but there is no device object. That means I have to wrap the esp.flash_* functions up into a device object like described in the docs (with readblocks, writeblocks, etc.) or am I missing something?

**Comment by pfalcon** [comment]
So, I had a quick a look at the patchset, and have bad news. This implement it backwards - it implements some "FATFS filesystem API", and then "flash reading" on top of it. But it doesn't make sense to do that. How it should work is the other way around - there should be as-simple-as-possible flash reading/writing routines, and any filesystem should be layered on top of them.

**Comment by danicampora** [comment]
> there should be as-simple-as-possible flash reading/writing routines, and
any filesystem should be layered on top of them.

I agree.

**Comment by pfalcon** [comment]
To get this going in the right direction, I pushed esp.flash_read() implementation in https://github.com/micropython/micropython/commit/90202b4c0de9f38c69b0cedc659d62432e2168e8 . It reads flash. No more and not less (in particular, it doesn't read randomly defined subset of flash). It reads it with byte granularity, if you're to trust vendor documentation (which you always should expect to contain errors). It's not tested - I don't have access to esp8266 hardware realistically till the end of year. But it is simple to review and see that it is as good as vendor documentation is, based on which it written.

**Comment by pfalcon** [comment]
Next step should be making pyb.mount functionality easily available to any port. Confirmation criteria is its availability in unix port. Of course, it shouldn't be pyb.mount() there, but for example os.vfsmount() (we can't use "vfs" suffix because of conflict with POSIX statvfs()). This all actually was discussed in https://github.com/alex-march/micropython/issues/1 and previous tickets, and unfortunately, doing it in another order leads to layering violation.

**Comment by pfalcon** [comment]
And here's next step in that direction: https://github.com/micropython/micropython/pull/1645

**Comment by alex-march** [comment]
@pfalcon:

Why do you think it's backwards? The read/write routines are already fairly simple and just use the vendor spi_* funcions wrapped with a buffer for byte addressing, they are not a part of fatfs implementation, the same API is *used* for fatfs, but not with esp.flash_*, perhaps apart from typedefs and return enums. Just like in your commit, it just calls the flash functions without any fatfs business. To further separate it, I can modify return types in flash.c to standard bool/uint32 to get rid of fatfs includes. If I get rid of the #defined offset as I mentioned in the first post, whole flash address space will be available.

I still keep in mind the unix port for pyb.mount. This is as far as I was going to take the esp8266 port with flash functions.

**Comment by pfalcon** [comment]
I think so because your code is written like that. You can compare my implementation of esp.flash_read() linked above with yours at https://github.com/micropython/micropython/pull/1626/files#diff-61309edb43a99b782d081351c5c602d1R585 . It's my function which calls vendor API for reading flash. Yours does something completely different.

> To further separate it, I can modify return types in flash.c to standard bool/uint32 to get rid of fatfs includes. If I get rid of the #defined offset as I mentioned in the first post, whole flash address space will be available.

But that all was discussed ~2 months ago, why it's still "can be done" instead of "done"? More generally, why people err on the side of complex solutions, even though every discussion revolves around "make simple step-by-step changes, be feedback-driven, achieve quick turnaround, let feeling of progress uphold you". So sorry again, but I really think I need to help with doing actual code changes, because seemingly agreed-upon plan doesn't lead to expected code.

**Comment by alex-march** [comment]
The code is written exactly like that, vendor functions behind the buffer functions, with the cache buffer in a separate module flash.c/h, there's nothing else in between and I see no point in mixing in the cache functions with the modesp. Your function does exactly the same, but calls the spi_flash_read() directly without buffer, I was under the impression that read/write work on 4kb chunks only, hence it's position behind the buffer, if that's not the case it can certainly be called directly and skip the buffer. There's really 2 files involved: modesp.c and flash.c, where are you seeing the fatfs calls? Changing return types/enums to avoid including fatfs API is a matter of one commit and hardly a problem.

> discussed ~2 months ago, why it's still "can be done" instead of "done"?

I wasn't aware that I am doing this towards some deadline or constraints. Unless that is the case, why are you in such a hurry? You're welcome to take the patch and add whatever you deem necessary.

**Comment by pfalcon** [comment]
> I wasn't aware that I am doing this towards some deadline or other constraints. Unless that is the case, why are you in such a hurry? You're welcome to take the patch and add whatever you deem necessary.

There's certainly no deadline or hurry, and I didn't mean to burden your travel with this stuff, so we can put off discussion until you have time. (I'm answering now, because later i'll be doing something else.)

So, while there's no hurry, there would be nice to have some progress on something. I wrote that function in 5 minutes (so long because I check vendor docs). So, I don't see a reason why 5-minute functions needs to be written 2 months. You of course will say that in 2 months you wrote much more than that, and that's exactly what I point as anti-pattern to each contributor who submits hard-to-review (harder than needed), too-much-to-change loadsome patches - don't do that, start small and easy, then adjust your pace based on feedback you get (and we try to provide quick feedback, so hopefully the overall pace is fast enough).

**Comment by pfalcon** [comment]
> The code is written exactly like that, vendor functions behind the buffer functions, with the cache buffer in a separate module flash.c/h, there's nothing else in between and I see no point in mixing in the cache functions with the modesp.

That's how you see your code. What I see in your code is that esp.flash_read() calls flash_disk_read_bytes(). Sorry, there's no disk at that level. It's disk *can* be made on top of flash, not flash on top of disk. And when I follow thru all those calls, I arrive at https://github.com/micropython/micropython/pull/1626/files#diff-61309edb43a99b782d081351c5c602d1R585 which does random arithmetic which proves that it doesn't read flash.

And I know why it happens so - because your commits ordered "esp8266/fatfs: Filesystem API and SPI flash drivers.", then "esp8266: Add flash IO functions to the esp module." So, you wrote "Filesystem API", and then stuffed on top of it "esp8266: Add flash IO functions to the esp module." That's a layering violation. And while writing "Filesystem API", you missed what we discussed these 2 months - that to add FATFS support to esp8266, no single line of esp8266 FATFS support code needs to be written. Because all that was already written and debugged by @dpgeorge , the only thing which needs to be done is liberating that code from stmhal port where it's held captive.

**Comment by pfalcon** [comment]
> I was under the impression that read/write work on 4kb chunks only

You didn't test it? I wrote my function based on what's written in vendor doc.

And here's what interests me - FAT filesystem should work with arbitrary (reasonable) sector size. 4K is sector size of modern HDD, you with @dpgeorge don't say that FAT can't be used with modern HDD, Then maybe you say that elm-chan's FatFs implementation doesn't support 4K sectors? That's possible, but doesn't make much sense - information in FAT is stored in clusters, and 8K was a normal cluster size long-long ago. Answering these question would require experimenting with FatFs, and the comfortable way to do that is using it with unix port.

So, if it was done in that order, it might be possible 1) not write all that byte buffer code; or 2) invest that effort into adding 4K sectors support for FatFs instead.

Instead we have what we have in this patch, and as I hopefully make clear, it's not ideal. That's my personal opinion, there's still @dpgeorge to decide. But what I'm essentially saying is that contributors should respect his effort and code, and use it, instead of trying to duplicate again and again.

**Comment by dpgeorge** [comment]
The FatFS library supports sector sizes up to 4096 bytes.  But it's hard coded, so all block devices that use this filesystem driver must use the same sector size.  Also, fatfs needs a buffer in RAM of that sector size.  Given that 512 byte sectors are common, that's why it was chosen for stmhal (and it then has minimum RAM overhead within the fatfs driver).

**Comment by alex-march** [comment]
> no single line of esp8266 FATFS support code needs to be written

This, by the way, brings me to a questions: @dpgeorge, I would like to separate the RTC function from the [diskio.c#L278](https://github.com/micropython/micropython/blob/master/stmhal/diskio.c#L278) and use a similar define in mpconfigport.h, MICROPY_FATFS_NORTC that's used by [ffconf.h#L252](https://github.com/micropython/micropython/blob/master/lib/fatfs/ffconf.h#L252). But I would need to move the get_fattime code somewhere else to avoid including the STM32_HAL_H. Would it be reasonable to have a function in rtc.c/h that returns fattime? With that, diskio.c can be moved over to lib/fatfs just like I did with previous pull req. Of course, this would be a separate PR. And with it, I can remove the diskio.c from this PR.

**Comment by alex-march** [comment]
> You didn't test it? I wrote my function based on what's written in vendor doc.

I didn't. The flash_read was written to work with cache as well, so anything pending during the writes could be fetched from cache and didn't require flash_sync in between read/write operations since new cache was fetched automatically when required, regardless of how the vendor function reads. That was the reasoning behind doing "random arithmetic" as you referred to it.

With last the few commits, I took your implementation, flash_read now uses the vendor function directly, skipping the cache. Thus, flash_sync is required after every non 4K write to read back the data. Here's the basic tests that I ran:
```python
>>> import esp
>>> rbuf = esp.flash_read(0x60000, 512)
>>> buf = bytearray([42] * 512)
>>> rbuf == buf
False
>>> esp.flash_init() # no longer need init to flash_read, since we don't read from cache
True
>>> esp.flash_write(0x60000, buf)
>>> rbuf = esp.flash_read(0x60000, 512) # not flushed yet, still in cache
>>> rbuf == buf
False
>>> esp.flash_sync()
True
>>> rbuf = esp.flash_read(0x60000, 512) # flushed, written to flash
>>> rbuf == buf
True
>>> 
```

- I removed fatfs types and returns as you suggested, modesp.c and flash.c are independent of fatfs.
- No longer using #defines for flash start/end sector, whole flash range is available.
- flash_init doesn't need to be exposed either, can init inside flash_write.
- I would also like to reuse stmhal/diskio.c, so I'll wait for Damiens reply.
- Bits of code for cache reading are still left in, I can remove it entirely if manual syncing is okay.

Let me know your thoughts!

**Comment by alex-march** [comment]
@dpgeorge, @pfalcon: Do let me know if this patch is still of interest with the last update. Otherwise I'll close it.

**Comment by dpgeorge** [comment]
@alex-march sorry, but can we put this on hold for 1 more week?  Thanks!

**Comment by alex-march** [comment]
No problem at all. Thanks for the reply!

**Comment by pfalcon** [comment]
I actually did some patching in the direction @alex-march asks about on the last flight I had, but since that it sits in my git stash and I couldn't get to cleaning it up and submitting for review... So yep, sorry that it takes much time. The points brought are all valid.

**Comment by pfalcon** [comment]
@alex-march : So, I hope you're aware of https://github.com/micropython/micropython/issues/1806 . I can tell you that if esp8266 already had filesystem support merged, it would make our life easier. But then the whole point of the project is to progress uPy as a whole, not just esp8266, so I still think that the course of action outlined above is right. And next step is to implement .flash_write() & .flash_erase() functions and have them tested. As you have related code, are you interested these functions to be merged with your authorship? If so, can you please refactor current code to implement them in the same way as commits 90202b4c0de9f38c69b0cedc659d62432e2168e8 and e13d462f77b0ac0d06b4bb798d50b1d08bc27a60 do? Note that it would be understood that if in current situation you'd prefer to leave handling that matter to me.

Previous comment doesn't concern other parts of your code at this stage, but again, if recent events make you lean to particular solutions, let's have that settled. (My concern is as usual to value contributors' efforts and avoiding duplications of work.) Thanks.

**Comment by alex-march** [comment]
@pfalcon: Yes, I am aware of the KS campaign, I'm glad you guys are doing it and it's a great deal of work. Hope it all goes well.
> interested these functions to be merged with your authorship?

Absolutely, if it helps the project, it will be my pleasure.
> lean to particular solutions

I would like to establish if reading should skip the cache buffer all together like in your commits, just using the SDK functions directly, and then we do manual sync after every write. Or both read and write happen through cache, like it was before, and there's no need to sync in between since it happens automatically in the caching algo (please see my python test code above).

Either way, after your answer, I will refactor the functions as you suggested and do some testing again.

**Comment by alex-march** [comment]
One more concern:
> implement .flash_write() & .flash_erase() 

Can't erase be implemented in python as a 0 bytearray write instead, or should it be written as a part of the modesp in C? The vendor function erases sectors only.

**Comment by pfalcon** [comment]
> I would like to establish if reading should skip the cache buffer all together like in your commits, just using the SDK functions directly

Right, the level of functionality we discuss currently is all about just using SDK functionality directly, so please separate out cache buffer (we'll return to it later).

> Can't erase be implemented in python as a 0 bytearray write instead, or should it be written as a part of the modesp in C? 

As I explained earlier, flash erase actually "writes" **1**'s to flash. But you can't write 1 to flash - only 0. So, erase is a standalone and necessary operation, and to work with flash, you need all 3 - read, write, erase.

> The vendor function erases sectors only.

That's correct and OK.

**Comment by alex-march** [comment]
Here's another test of flash functions. SDK gets called directly, buffer is removed.
```python
>>> import esp
>>> sec_addr = 0x60000
>>> sec_size = 4096
>>> 
>>> buf = bytearray(512)
>>> buf[0]
0
>>> esp.flash_erase(sec_addr // sec_size)
>>> buf = esp.flash_read(sec_addr, len(buf))
>>> buf[0]
255
>>> wbuf = bytearray([42] * len(buf))
>>> wbuf[0]
42
>>> esp.flash_write(sec_addr, wbuf)
>>> buf = esp.flash_read(sec_addr, len(buf))
>>> buf == wbuf
True
>>> wbuf = esp.flash_read(sec_addr + 1, len(wbuf))
>>> buf == wbuf
False
>>> 
```
Since the buffer is not present, there's no way of testing fsusermount now with 512 sectors. Should I go ahead an remove it from this PR?

**Comment by pfalcon** [comment]
From quick peek, looks good!

> Since the buffer is not present, there's no way of testing fsusermount now with 512 sectors. Should I go ahead an remove it from this PR?

Well, the best way is to submit new code as a separate PR for quick processing. This PR can stay largely as is for now.

**Comment by alex-march** [comment]
@pfalcon: Great. I will leave this as is and have another branch/PR ready later.

**Comment by alex-march** [comment]
With #1816 in place, I will be removing the diskio.c from this PR.

**Comment by alex-march** [comment]
How do I rebase this PR on top of master and not have all the commits by other users that happened in between being picked up by GitHub? I've already managed to mess it up before, so just wanted to ask before I do something terrible :)

**Comment by dhylands** [comment]
It looks like you're working on a branch, so the usual procedure that I do is to do something like the following:
```
git checkout master
git pull
git checkout your-branch
git rebase master
```

**Comment by dhylands** [comment]
I see that github says you've got conflicts, which means that the rebase will fail partway through. So then you need to resolve the conflicts, add/commit the file you changed and then do a ```git rebase --continue```

When I know I'm going to run into this, I normally create a patch file as a backup, using
```
git checkout your-branch
git format-patch HEAD~N
```
where N is the number of commits in your branch.

**Comment by alex-march** [comment]
Thank you @dhylands! This went better than my last attempt! All related commits are now squshed.

@pfalcon while removing the diskio.c from this patch, I was not able to compile stmhal version due to FatFS requiring get_fattime function if the _FS_NORTC is not enabled in ffconf.h. This simply needs another config #define and I will submit another PR for this to avoid modifying too many files here.

**Comment by pfalcon** [comment]
Thanks @alex-march, to proceed with that, I've cherry-picked the commit related to our discussion above, removed unrelated changes and made codestyle be consistent with surrounding code and pushed it as https://github.com/micropython/micropython/commit/81407729a57a5425f2ec1e04b68c847d2b24f1a4. Thanks for driving this, we'll take it from here.

**Comment by dpgeorge** [comment]
The esp8266 port now has fatfs support, internal flash support, as well as mounting user block devices.

**Pull request closed without merging**
