### PR TITLE
documentation typos

### PR DESCRIPTION
**Pull request by makuk66**
Fixing a few documentation typos

### CODE REVIEW

**Comment by pfalcon** [comment]
Please follow existing commit message format, see history for examples: https://github.com/micropython/micropython/commits/master . More info: https://github.com/micropython/micropython/wiki/ContributorGuidelines#how-to-contribute

**Comment by danicampora** [comment]
Hi @makuk66 thanks for the contribution. I'll edit your commit messages and squash all them into one, but next time please follow the commit guidelines as suggested by @pfalcon :-)

**Comment by danicampora** [comment]
Thanks, merged in https://github.com/micropython/micropython/commit/c773053f58680ad52130d84c3c1f22ad474da942

**Comment by makuk66** [comment]
Sure, will do. Thanks!

**Pull request closed without merging**
