### PR TITLE
esp8266: Implement uart.any()

### PR DESCRIPTION
**Pull request by dpgeorge**
Also includes update of docs.

### CODE REVIEW

**Comment by pfalcon** [comment]
+1. Let's however avoid all the "u" vs "non-u" confusion, if the default name of the module is `uselect`, let's use it (sample uselect.poll() code in the docs).

**Comment by dpgeorge** [comment]
> Let's however avoid all the "u" vs "non-u" confusion, if the default name of the module is uselect, let's use it (sample uselect.poll() code in the docs).

I agree, but in the docs there is no uselect, only select (see docs/library/select.rst).

**Comment by pfalcon** [comment]
Weird. Ok, we'll need to fix that later.

**Comment by dpgeorge** [comment]
Rationale for *not* including a similar method for tx, eg uart.can_tx(): this operation is much less common than polling for input and can be achieved using select.poll if needed.

**Comment by dpgeorge** [comment]
Also, eventually we want to rename the pyb stuff in this file to something like `machine_uart_XXX`.

**Comment by dpgeorge** [comment]
This was merged.  Docs will still need updating to change select to uselect.

**Pull request merged**
