### PR TITLE
 unix/modusocket: Finish socket.settimeout() implementation.

### PR DESCRIPTION
**Pull request by pfalcon**
~~~
unix/modusocket: Initial implementation of socket.settimeout().


unix/modusocket: Finish socket.settimeout() implementation.

1. Return correct error code for non-blocking vs timed out socket
(POSIX returns EAGAIN for both, we want ETIMEDOUT in case of timed
out socket). To achieve this, blocking/non-blocking flag is added
to the mp_obj_socket_t, to avoid issuing fcntl() syscall each time
EAGAIN occurs. (mp_obj_socket_t used to be 8 bytes, having some room
in a standard 16-byte alloc block.)

2. Handle socket.settimeout(0) properly - in Python, that means
non-blocking mode, but SO_RCVTIMEO/SO_SNDTIMEO of 0 is infinite
timeout.

3. Overall, make sure that socket.settimeout() call switches blocking
state as expected.
~~~

### CODE REVIEW

**Comment by pfalcon** [comment]
Based on consideration of issues https://github.com/micropython/micropython/issues/2379, https://github.com/micropython/micropython/pull/2381 , it becomes clear that .settimeout() operation if we want (non-blocking otherwise) streams to be both composable and real-world robust.

This PR consists of: 

1. The original content of https://github.com/micropython/micropython/pull/2381, with 2 commits squashed, commit message updated, and authorship preserved.

2. My fixes to not regress non-blocking socket behavior, and Python-compliant behavior for various values (None, 0, non-zero) passed to .settimeout().

**Comment by dpgeorge** [comment]
Thanks for this, and thanks for building on the original PR and maintaining the commit history.  I agree it's a good addition.  Merged in 80a25810f9b246094b31ce7d465a0f25842c9be6 and 0c18633ea9bed6a0c1031357c4eacbb016deb41a

**Comment by dpgeorge** [comment]
I guess it now makes sense to remove the part in the docs that tells this is not available in all ports.

**Comment by pfalcon** [comment]
> I guess it now makes sense to remove the part in the docs that tells this is not available in all ports.

Sure.

**Pull request closed without merging**
