### PR TITLE
esp32/machine_adc: Fix configuration of default ADC atten value.

### PR DESCRIPTION
**Pull request by dpgeorge**
Prior to this fix, if the ADC atten value was not explicitly given then adc1_config_channel_atten() would never be called.

See issue #8275.

### CODE REVIEW

**Comment by dpgeorge** [comment]
@jonathanhogg FYI

**Comment by UnexpectedMaker** [comment]
Ok, trying this now on all ESP32 variant....

**Comment by UnexpectedMaker** [comment]
ESP32-S3 is now giving me 4095 on a read() which is great, but read_uv() is 926,000 - what is that supposed to translate to?
```
>>> from machine import Pin, ADC
>>> adc = ADC(Pin(10))
>>> adc.read()
4095
>>> adc.read_uv()
926000
>>> adc.read_uv()
926000
>>> adc.read_uv()
926000
>>> adc.read_uv()
926000
>>> adc.read()
4095
>>> 
```

**Comment by UnexpectedMaker** [comment]
TinyPICO is boot-looping on latest master built with IDF 4.4 release :(

```
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4560
load:0x40078000,len:14548
ho 0 tail 12 room 4
load:0x40080400,len:3928
entry 0x4008062c
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x4014f92a  PS      : 0x00060933  A0      : 0x800d787d  A1      : 0x3ffcf440  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x3ffb7764  A5      : 0x0000040e  
A6      : 0x3ffcf470  A7      : 0x3ffbf29c  A8      : 0x00000000  A9      : 0x3ffcf410  
A10     : 0x00000000  A11     : 0x0000040e  A12     : 0x40084a30  A13     : 0x00000000  
A14     : 0x3ffcf470  A15     : 0x00060020  SAR     : 0x0000001d  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000008  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  


Backtrace:0x4014f927:0x3ffcf4400x400d787a:0x3ffcf470 0x400d76cc:0x3ffcf4a0 




ELF file SHA256: 6b64fe19a28ec983

Rebooting...
```

**Comment by dpgeorge** [comment]
> read_uv() is 926,000 - what is that supposed to translate to?

It's microvolts, so 0.926V, which looks correct.

**Comment by UnexpectedMaker** [comment]
> 

Wouldn't 1.1V be correct in this case? 1.1V and 0.92V is a massive difference. Almost 18%.
If I have to add magic numbers to make my VBAT pin read 4.2V using adc.read_uv(), then how is that different to magic numbers using adc.read() ?

**Comment by dpgeorge** [comment]
> Wouldn't 1.1V be correct in this case?

With 0db attenuation (the default), the ADC can measure up to about 950mV, according to the docs: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/adc.html#adc-attenuation

**Comment by UnexpectedMaker** [comment]
Interesting, I always thought it was 0v-1.25V we were using. Seems I've had a total disconnect there! Thanks for the brain shove!

So S3 and S2 seems to be ok now. But I cant test ESP32 (atm) cause of the boot loop.

**Comment by dpgeorge** [comment]
> But I cant test ESP32 (atm) cause of the boot loop.

This is probably the same issue as #8260.

**Comment by jonathanhogg** [comment]
Actually, it occurs to me that what I forgot to do was to initialise the attenuation in the `madc_make_new()` function, a la:

```diff
diff --git a/ports/esp32/machine_adc.c b/ports/esp32/machine_adc.c
index 515d629a7..3263b89a1 100644
--- a/ports/esp32/machine_adc.c
+++ b/ports/esp32/machine_adc.c
@@ -153,6 +153,7 @@ STATIC mp_obj_t madc_make_new(const mp_obj_type_t *type, size_t n_pos_args, size
         madcblock_bits_helper(self->block, self->block->bits);
     }
 
+    madc_obj_atten[self - madc_obj] = -1;
     mp_map_t kw_args;
     mp_map_init_fixed_table(&kw_args, n_kw_args, args + n_pos_args);
     madc_init_helper(self, n_pos_args - 1, args + 1, &kw_args);
```

as you can't get to the init helper without getting past this.

This is a simpler fix and means that the attenuation doesn't need to be stored off-by-one – although `ADC_ATTEN_MAX` is certainly a better choice of sentinel value than `-1`.

**Comment by dpgeorge** [comment]
I did consider that.  But the reason I went with the current approach is so that if an ADC is constructed without specifying `atten`, it retains its previous value.  Eg `ADC(Pin(33), atten=1)`, and then `ADC(Pin(33))` still has atten=1.  (Most peripherals work this way, to allow you to obtain a peripheral object without reconfiguring it.)

**Comment by jonathanhogg** [comment]
Gotcha. Will keep that in mind for future work.

**Pull request merged**
