### PR TITLE
unix: toggle for fatfs, since djgpp/freedos does not support this

### PR DESCRIPTION
**Pull request by pohmelie**
@dhylands was the original author of this patch, but @pohmelie made
changes to implement toggle.
http://forum.micropython.org/viewtopic.php?f=2&t=1718&p=9829#p9829
https://github.com/dhylands/micropython/commit/b16d5d87b43bc155bb268a1435985839d2e58d74

### CODE REVIEW

**Comment by pfalcon** [comment]
There shouldn't be a reason why FatFs doesn't work with djgpp, so I'd suggest better working in the direction of supporting it.

**Comment by pohmelie** [comment]
@pfalcon 
```
../py/../extmod/vfs_fat_file.c:143:32: error: 'ENOTSUP' undeclared (first use in this function)
                     *errcode = ENOTSUP;
                                ^
../py/../extmod/vfs_fat_file.c:143:32: note: each undeclared identifier is reported only once for each function it appears in
```
djgpp have no `ENOTSUP` in `errno.h` http://www.delorie.com/djgpp/doc/libc/libc_293.html

**Comment by pfalcon** [comment]
You can easily define it as a workaround, though we with @dpgeorge decided that there should be mperrno.h with consistent error list and numbering.

**Comment by dhylands** [comment]
Having consistent numbering will only work if you're running bare metal. If you're running on an OS (i.e. linux) then you still have to deal with the fact that the values change depeding on the underlying architectures. For example ETIMEDOUT has a different values on say mips-linux versus x86-linux. And the values also change across platforms (windows, mac, linux, unix).
http://www.ioplex.com/~miallen/errcmp.html

**Comment by pfalcon** [comment]
Right, that's why we'll use it only for bare-metal and will base numbering on linux-x86 as the most common. Here, for djgpp, indeed just defining missing symbols (to the values of linux-x86 whenever possible) is the only choice.

**Comment by dhylands** [comment]
So how will you deal with the fact that say ETIMEDOUT is different between
linux-mips and linux-x86?

Or are you just saying that bare-metal will use linux-x86 and all of the OS
based ones will use the errno definitions for their OS?

On Sat, Apr 2, 2016 at 10:38 AM, Paul Sokolovsky <notifications@github.com>
wrote:

> Right, that's why we'll use it only for bare-metal and will base numbering
> on linux-x86 as the most common. Here, for djgpp, indeed just defining
> missing symbols (to the values of linux-x86 whenever possible) is the only
> choice.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/micropython/micropython/pull/1956#issuecomment-204763826>
>



-- 
Dave Hylands
Shuswap, BC, Canada
http://www.davehylands.com

**Comment by pfalcon** [comment]
> Or are you just saying that bare-metal will use linux-x86 and all of the OS
based ones will use the errno definitions for their OS?

Yes.

**Comment by pohmelie** [comment]
Ok, so continue in #1959

**Pull request closed without merging**
