### PR TITLE
C API: downcase all MP_OBJ_IS_xxx macros and MP_xxx_SLOT_IS_FILLED functions

### LINKED ISSUE #293: RFC: Cleaning up macro naming, possibly switch to inline functions
This is to capture https://github.com/micropython/micropython/issues/269#issuecomment-34872553 and following discussion.

Summary:
1. Macros with THEIR CAPS break continuity in API. Suggested fix: downcase names of macros which are part of mp_obj_\* API.
2. As an extra step, consider leveraging C99 inline functions - both to replace macros and have inlinability guarantees for speed-critical accessors.

### PR DESCRIPTION
**Pull request by dpgeorge**
This is an attempt to resolve #293 by downcasing most of the uppercase macros/functions, to clean up the C API.

These macros/inline-functions that have been downcased could in principle be (inline) functions so it makes sense to have them lower case, to match the other C API functions.

The remaining macros that are upper case are:
- MP_OBJ_TO_PTR, MP_OBJ_FROM_PTR
- MP_OBJ_NEW_SMALL_INT, MP_OBJ_SMALL_INT_VALUE
- MP_OBJ_NEW_QSTR, MP_OBJ_QSTR_VALUE
- MP_OBJ_FUN_MAKE_SIG
- MP_DECLARE_CONST_xxx
- MP_DEFINE_CONST_xxx

These must remain macros because they are used when defining const data (at least, MP_OBJ_NEW_SMALL_INT is so it makes sense to have MP_OBJ_SMALL_INT_VALUE also a macro).

For those macros that have been made lower case, compatibility macros are provided for the old names so that users do not need to change their code immediately.

### CODE REVIEW

**Comment by robert-hh** [comment]
I am sure that this will confuse me, because then it is harder to tell, what's a Macro (or define) and what is a function.

**Comment by dpgeorge** [comment]
> I am sure that this will confuse me, because then it is harder to tell, what's a Macro (or define) and what is a function.

At the moment it's not consistent that uppercase names are macros, some are indeed inline functions.  And others may be switched to inline functions (or real functions) in the future (see #293 for further discussion about this point).

So, given that there's no clear distinction between macro and (inline) function, it seems that the best thing to do is just make everything consistently lowercase.  Then you know that it's always just lowercase.  (EXCEPT for those which MUST be macros (see above).)

**Comment by pfalcon** [comment]
I'd say that if this was done at all, it should be merged soon. Otherwise this becomes yet another ever-backlogged, hard to maintain refactor. Indeed, there's one conflict already.

**Comment by dpgeorge** [comment]
Ok, merged in eee1e8841a852f374b83e0a3e3b0ff7b66e54243 through 6e30f96b0b0ab14853085e5300d80d7c1a6f67c5

**Pull request closed without merging**
