### PR TITLE
esp32/modesp32.c: add esp32 non volatile storage support

### PR DESCRIPTION
**Pull request by upyfx**
quick ref:
```
import esp32

esp32.nvs_set('testkey', 'testvalue')
esp32.nvs_get('testkey')
esp32.nvs_erase('testkey')
esp32.nvs_erase_all()
```

### CODE REVIEW

**Comment by upyfx** [comment]
Please what is the right way to deliver a test (ex: directory, similar test) ?

**Comment by junhuanchen** [comment]
This is fun!

**Comment by dpgeorge** [comment]
Thanks for the contribution, it looks quite good, to just read/write bytes objects.

@Lisa999 how does this compare to your implementation?

**Comment by dpgeorge** [comment]
I see that the ESP IDF has functions to get/set a range of signed/unsigned integer types (8-64 bit).  I don't know, is it worth exposing all of that functionality?

**Comment by Lisa999** [comment]
@dpgeorge: This is a nice try, but i have to disagree with this approach. 
For example: 
`nvs_set_blob(nvs_handle, key, value, strlen(value));`
It's assuming that value is a STRING, but it's using a blob function to store the string.

Here are **my** functions:
checkNVS()
mod_esp_nvs_set_int (mp_obj_t _key, mp_obj_t _value)
mod_esp_nvs_get_int (mp_obj_t _key)
mod_esp_nvs_set_str (mp_obj_t _key, mp_obj_t _value)
   --> Using: nvs_set_str(mpy_nvs_handle, key, value)
mod_esp_nvs_get_str (mp_obj_t _key)
mod_esp_nvs_erase (mp_obj_t _key)
mod_esp_nvs_erase_all (void)

example (code to see which reset has been performed for the next cycle): 
`            
# Set reset NVS variable
esp.nvs_setstr('reset', 'rebootasync')
`

The only thing i'm doubting about is whether to put it into ESP or into ESP32...

I happy to make a PR, IF you promise to pull #3576 after @andynd has fixed it.

**Comment by upyfx** [comment]
This follow Micropython's Django Principle.

**Comment by Lisa999** [comment]
Django? Django is all-inclusive, Flask Lightweight.
I would say that Micropython is more like Flask, everything should be lightweight and modular to avoid using huge amounts of memory.

**Comment by dpgeorge** [comment]
Thanks @Lisa999 for the input.  It's probably a good idea to at least add "type" annotations to the method names so others can be added in the future if needed; such as `nvs_set_blob()`, `nvs_set_i32()`, etc.

Looking more at what the ESP IDF provides, I'd also suggest to make the NVS interface an object, rather than just functions in a module.  This is because it's possible to open multiple NVS handles.  It's like a mini database.  Eg:
```python
nvs = esp32.NVS("my_storage", "w") # open read/write
nvs.set_i32("key", 1234)
nvs2 = esp32.NVS("other_storage", "r") # open read-only
blob = nvs2.get_blob("key2")
```

**Comment by mattytrentini** [comment]
See #4436 for a related issue.

**Comment by mattytrentini** [comment]
ESP-IDF Non-volatile storage library docs can be found here:

https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/storage/nvs_flash.html

(Link above is broken though the text is correct)

**Comment by Lisa999** [comment]
> Thanks @Lisa999 for the input. It's probably a good idea to at least add "type" annotations to the method names so others can be added in the future if needed; such as `nvs_set_blob()`, `nvs_set_i32()`, etc.
> 
> Looking more at what the ESP IDF provides, I'd also suggest to make the NVS interface an object, rather than just functions in a module. This is because it's possible to open multiple NVS handles. It's like a mini database. Eg:
> 
> ```python
> nvs = esp32.NVS("my_storage", "w") # open read/write
> nvs.set_i32("key", 1234)
> nvs2 = esp32.NVS("other_storage", "r") # open read-only
> blob = nvs2.get_blob("key2")
> ```

@dpgeorge: Since you build the Partition class for the ESP32, i'll keep my part of the bargain and have NVS working for Micropython v1.11 . However it's still functions based, do you have an example of a good object based class so i can rewrite my code?

**Comment by dpgeorge** [comment]
> do you have an example of a good object based class so i can rewrite my code?

I think the `esp32.Partition()` class is a really good example to base NVS on, see #4910. 

Also, it might be neater to use subscription to read/write NVS values, similar to how `machine.mem32[..]` works.  Eg:
```python
nvs = esp32.NVS('storage', 'w')
nvs.i32['key'] = 1234 # store value
print(nvs.blob['key2']) # retrieve value
```
See `extmod/machine_mem.c` for code to implement that kind of API.

**Comment by nevercast** [comment]
Its not clear to me why Partition class needed to be merged before implementing NVS. There is very little interaction between OTA/Partition functions and nvs functions. 

@Lisa999 what was your intention in waiting for Partition functionality to be merged? Also are you working on this PR now ?

**Comment by Lisa999** [comment]
@nevercast : the Partition PR is not connected to this PR. I already have a working NVS class, however not object oriented but function oriented. @dpgeorge refered to the Partition class as an example how to build something like an object oriented  class. The NVS OO class is on my to do list, probably going to start with the next few weeks.

**Comment by dmartauz** [comment]
@Lisa999 Any plans to finish OO implementation of NVS?

**Comment by Lisa999** [comment]
> @Lisa999 Any plans to finish OO implementation of NVS?

Absolutely, as promised. Is on my todo list. However it gets overriden all the time by urgent matters that take up all of my time. I hope to make a start the next few weeks.

**Comment by pumelo** [comment]
@Lisa999 would you mind publishing your work on NVS somewhere? probably I can step in to finish the OO work, as I'm interested in NVS too ...

**Comment by remibert** [comment]
I do the merge on the commit 60f5b941e096aba270a7d4af8faa33169de8364f, I attached the files merged, but I don't know to do this with github.
[nvs.zip](https://github.com/micropython/micropython/files/5080260/nvs.zip)

**Comment by dpgeorge** [comment]
This is superseded by the NVS supporte added in c10d431819f9f7095c3573c98f01c98526a2cb0b

**Pull request closed without merging**
