### PR TITLE
.gitignore: add *.pyc

### PR DESCRIPTION
**Pull request by blazewicz**
Example:

```
~/git/micropython/esp8266 $ make
...
LINK build/firmware.elf
   text    data     bss     dec     hex filename
 524604    1056   56208  581868   8e0ec build/firmware.elf
Create build/firmware-combined.bin
('flash    ', 33456)
('padding  ', 3408)
('irom0text', 492248)
('total    ', 529112)
('md5      ', 'b6b9f8f387e48aa2099546071f77d583')
~/git/micropython/esp8266 $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

    ../py/makeqstrdata.pyc

nothing added to commit but untracked files present (use "git add" to track)
```

### CODE REVIEW

**Comment by dpgeorge** [comment]
Is this for Python 2 only?  Usually .pyc files go in `__pycache__` which we ignore.

**Comment by blazewicz** [comment]
In _py/mkenv.mk:45_  variable `PYTHON` is defined as `python`.

I have default Ubuntu 16.04's `python` and `python3` packages.

```
~ $ python --version
Python 2.7.12
```

I didn't modify anything, happens on fresh pull.

**Comment by dpgeorge** [comment]
The issue is that Python 2 doesn't use `__pycache__` to store .pyc files.  And makeqstrdata.pyc is being generated because tools/mpy-tool.py imports it.

**Comment by dpgeorge** [comment]
Rebased and merged in d1a366fdd4a0f60e0487bd45a8b456804c75ea5d.

**Pull request closed without merging**
