### PR TITLE
Added getpeercert, modeled after C Py

### PR DESCRIPTION
**Pull request by MrSurly**
Discussion: https://github.com/micropython/micropython-esp32/issues/144

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks.  Tested on esp32 and merged in d5191edf7ff81f5f07243cb2a318508c1e9cc5df with a few changes:
- use mp_obj_is_true instead of compare to mp_const_true
- raise NotImplemented error instead of ValueError (see eg modussl_axtls setblocking for precedence on this point)
- added a simple test for the functionality

**Comment by pfalcon** [comment]
So, the commit message of this patch could have been more detailed (as fixed by @dpgeorge). I'd also really suggest to add config options for any additional methods added to the module, as any of them will be very rarely used. (I'm going to add for this one.)

**Comment by dpgeorge** [comment]
> I'd also really suggest to add config options for any additional methods added to the module, as any of them will be very rarely used. (I'm going to add for this one.)

Please don't add it for this method: it's short and provides direct access to the cert which cannot obtained in any other way, so is useful functionality.  More config options just makes things more complex to configure and harder for users to know what functionality they can rely on.

**Comment by pfalcon** [comment]
Ok, I'll wait till actual case of space pressure (which is always around the corner).
w
> harder for users to know what functionality they can rely on.

User can rely of module contents as it was before (wrap_socket). Users *can't* rely on getpeercert() availability: it's not available in other TLS modules, and keeping peer cert beyond the initial handshake doesn't make sense, so any space-conscious TLS lib would dispose of it ASAP, and this function wouldn't be implementable.

**Pull request closed without merging**
