### PR TITLE
stmhal: Rename mphal.* to stmhal_mphal.* to be consistent with other ports.

### PR DESCRIPTION
**Pull request by pfalcon**
The idea is that "mphal.h" will be central header which describes standard
MPHAL API, consistent across ports.

### CODE REVIEW

**Comment by dpgeorge** [comment]
-1

I'd rather use mphalport.*.

**Comment by pfalcon** [comment]
What do you mean? All other ports already follow that pattern, stmhal is the only exception:

~~~~
$ find -name "*mphal.h"
./windows/windows_mphal.h
./esp8266/esp_mphal.h
./unix/unix_mphal.h
./pic16bit/pic16bit_mphal.h
./stmhal/mphal.h
~~~~

Do you want me to rampage thru every port and rename that? I can. But the point of the change I really want to make is to demote stmhal from being "special" port, and this change is the minimal to make progress in that direction. Also, it's pretty clear that they were named like that to avoid similarly-named sources in different dirs. I don't know why it was done like that, I'm not the one who did it like that, and prefer not to be one to break it.

**Comment by dpgeorge** [comment]
The reason I named them such is, as you say, to avoid including the wrong mphal file when stuff from stmhal/ was used in a different port.  But now that I look at it again, there are other ways around that problem.  1) do as per mpconfigport.h and use <> brackets in the include; 2) use the directory name in the path to mphal.h, eg "esp8266/mphal.h".

I think the correct end-goal is to use py/mphal.h to define common stuff, and then have this file #include MICROPY_MPHALPORT_H if that macro is defined (it would be defined in mpconfigport.h I guess), otherwise just #include <mphalport.h>.  Then each port has a mphalport.h file (and possibly implementation in mphalport.c).  This is consistent with mpconfig and qstr files.

So I think we should just jump straight to this solution, possibly in bite-sized commits. 

BTW, cc3200 is also "different" in that it calls it cc3200_hal.h.

**Comment by pfalcon** [comment]
> I think the correct end-goal is to use py/mphal.h to define common stuff, and then have this file #include MICROPY_MPHALPORT_H if that macro is defined (it would be defined in mpconfigport.h I guess)

Yes, and including MICROPY_MPHALPORT_H needs to be first thing it does, because some of HAl functions may be actually #define's (then it should skip declaring prototypes for them).

> So I think we should just jump straight to this solution, possibly in bite-sized commits. 

Ok, so what should be next step exactly then, so I didn't just break peoples' ports on my own?

**Comment by dpgeorge** [comment]
> Ok, so what should be next step exactly then, so I didn't just break peoples' ports on my own?

I'll have a go at it and open a PR for discussion.

**Comment by dpgeorge** [comment]
See #1563.

**Pull request closed without merging**
