### PR TITLE
uzlib: Test adaptive huffman tree to cover more tinflate code. WIP

### PR DESCRIPTION
**Pull request by hosaka**
I am not very knowledgeable in the subject, please suggest a better, smaller, encoded string if possible to test dynamic huffman tree.

### CODE REVIEW

**Comment by hosaka** [comment]
I have also spent some time trying to understand how to produce deflated data for adaptive huffman tree with different code lengths to cover various cases in `tinflate.c/tinf_decode_trees()`. There's a quick explanation of this over on [w3.org](https://www.w3.org/Graphics/PNG/RFC-1951#dyn). But I don't know how to generate this with cpython or any other way.

**Comment by dpgeorge** [comment]
> I am not very knowledgeable in the subject, please suggest a better, smaller, encoded string if possible to test dynamic huffman tree.

It already looks pretty minimal to me!

> I have also spent some time trying to understand how to produce deflated data for adaptive huffman tree with different code lengths to cover various cases in tinflate.c/tinf_decode_trees(). There's a quick explanation of this over on w3.org. But I don't know how to generate this with cpython or any other way.

I don't think there's any easy way to do it apart from generating heaps of random data, compressing it, and looking for uses of those other cases.

Alternatively -- and I'd suggest to do it this way -- just write by hand your own deflated data, making sure it's valid deflate data, and covers those cases.  Trace through the C code to see exactly what it expects from the input and give it that (probably easier to write it in binary to start with, using Python 0b01010111011 format, then convert to bytes).  Then deflate it and see what text it corresponds to and use that for the test.

**Comment by hosaka** [comment]
> I don't think there's any easy way to do it apart from generating heaps of random data, compressing it, and looking for uses of those other cases.
That's what I have been doing so far :)

I might do what you suggested and try to craft the data manually to match all the cases. As I don't know how long it will take me, I will open another PR later, when I figure it out! Or we can put this on hold for now.

**Comment by dpgeorge** [comment]
Ok, let's just merge this addition now then.  But can you please put it in uzlib_decompress.py, in the PATTERNS list, because this test has nothing to do with the DecompIO wrapper but rather the underlying deflate algo (am I correct in this assumption?).

**Comment by hosaka** [comment]
Yes, that was my mistake. I've moved it to uzlib_decompress.py. Cheers.

**Comment by dpgeorge** [comment]
Great, thanks, merged in 9fdba0e09c7522130d6609362973bdf5feda1a2e.

**Pull request closed without merging**
