### PR TITLE
RP2: Don't advertise remote wakeup for USB serial

### LINKED ISSUE #6866: rp2 More USB woes
I raise this in case it sheds any more light on the USB issues.
I am using `rp2-pico-20210209-unstable-v1.14-11-gc7aaee2b2.uf2`.

I have a substantial `uasyncio` application developed on Pyboards and ported to the Pico. The test script outputs regular messages via print statements. The application maintains a heartbeat LED via a coroutine on the Pico.

It runs fine if I suppress all print output.

With print statements enabled it also runs so long as I periodically press a key on the keyboard (in rshell or in miniterm). If I don't, it runs for a while then stops. The heartbeat stops flashing until I press a key, when running resumes. The code has evidently stalled.

Unfortunately my attempts to create a trivial test case have so far failed. I have never encountered this behaviour on Pyboards, ESP8266 or ESP32.

### PR DESCRIPTION
**Pull request by liamfraser**
Fixes #6866

### CODE REVIEW

**Comment by lurch** [comment]
I've just tested this, and can confirm that it fixes #6866 :+1:

**Comment by dpgeorge** [comment]
Looks OK to me, thank you!

**Comment by lurch** [comment]
Just for cross-link purposes: this was also fixed in pico-sdk with https://github.com/raspberrypi/pico-sdk/pull/289

**Comment by dpgeorge** [comment]
Merged in ca3d51f12206a88463f2b2a2d27756a1b519cb6a

**Comment by lurch** [comment]
ping @tannewt

**Pull request closed without merging**
