### PR TITLE
extmod/modlwip: Abort TCP conns that didn't close cleanly in a while.

### PR DESCRIPTION
**Pull request by dpgeorge**

### CODE REVIEW

**Comment by dpgeorge** [comment]
@t35tB0t this patch should fix sockets that have been abandoned.  It automatically calls `tcp_abort()` after 2 seconds on sockets that have been closed (by `socket.close()`) but are still around.

**Comment by dpgeorge** [comment]
The patch here uses a timeout of 2 seconds between a graceful close() of a TCP connection and an abort.  I think that's a bit short given that some links (eg slow wifi) will take longer than that.

The SO_LINGER option is used to control this, but it's a bit more complicated than just setting the timeout.  As far as I understand, POSIX defined sockets work like this:
- default behaviour of a TCP connection is SO_LINGER disabled, and the socket closes in the background (ie `socket.close()` returns immediately), with effectively an infinite timeout (ie waits forever for a graceful close); this is the current behaviour of uPy lwIP bindings
- enabling SO_LINGER with 0 timeout means that `socket.close()` does an abort straightaway (not usually recommended, since all connections end as reset connections)
- enabling SO_LINGER with a non-zero timeout (expressed in seconds) means that `socket.close()` *blocks* until either 1) the socket closes gracefully; or 2) the linger timeout expires.  (And I think the close call blocks even if the socket is in non-blocking mode.)

The PR here is different to all of the above: `socket.close()` remains non-blocking (returns immediately), the socket tries to close gracefully in the background, and aborts after the 2 second timeout.

I think the following action should be taken:
1. merge this PR but with a longer timeout, like 10 seconds; Rationale: on embedded systems we don't want to hog resources forever so the timeout should be finite, but it's likely that these systems will run in regions with poor/slow connectivity so the timeout can't be too short.
1. implement the SO_LINGER option in full as described above. Rationale: cleaning up socket resources is important to maintain stability of the system, so full control over how it's done should be given to the user.

@t35tB0t your input here is welcome.  Perhaps the default timeout for `socket.close()` should be configurable at built time by some option like `MICROPY_PY_LWIP_CLOSE_TIMEOUT`.

**Comment by t35tB0t** [comment]
POSIX compliance using SO_LINGER options sounds like a good idea.  Yet, 
looking at the defined behaviors, it seems the SO_LINGER deviates from 
the actual need here - which is to have an efficient way to handle 
exceptions ranging from slow connection timeouts to severe ENOMEM 
conditions.  SO_LINGER with zero timeout gives us the  access to 
tcp_abort but will do its thing on *every* close.  This is does not 
differentiate between a close-on-exception vs a normal-close so I'll 
harp on a recurring theme here.

In order to provide more robust TCP socket exception handling, it is 
suggested that optional parameters be added to method socket.close(type, 
timeout).  These would provide the dynamic control that is helpful for a 
small uPy device.  Closure types already defined by LWIP tcp.c functions 
are: ('CLOSE','ABORT','ABANDON') where 'CLOSE' implies 'GRACEFUL_CLOSE' 
and timeout defaults to 10 seconds.  Extending this one function like 
this is really powerful and does not break existing code.

The PR with a fast timeout demonstrates that an aggressive 
close-on-exception approach is effective way to throw off broken 
connections with minimal resource impact.   The uPy server test code is 
deleting the socket upon severe exception and retrying packet sending 
when buffer space is limited.  With the PR, this triggers the same 
2-second timeout which certainly works.  With socket.__del__() method 
modified to invoke tcp_abandon() it was difficult to fill buffer space 
with lingering packets and ENOMEM no longer occurs.

As-is, we haven't been able to crash the F429 after days of throwing 
things at it.  Considering where we started from, this is all quite 
impressive.  Also, it is interesting to note that, through all the code 
changes, the F429's bulk Tx transfer speed from the same test code has 
come down from a peak of >75Mbps to about 61Mbps.

Suggestions summary:

(1) Commit the PR with timeout defaulting to 10 seconds.  This provide 
immediate improvement to main.  Test to verify that 10 seconds is still 
immune to lingering packet jamming issues.

(2) Change socket.__del__() from tcp_close() to tcp_abandon() (This 
means users should issue an explicit socket.close() before leaving 
scope.  And that is good.)

(3) Extend socket.close() behavior with optional parameters: Normal 
Close with Timeout,  Abort with RST, and silent Abandon. Default such 
that a socket.close() does a normal graceful close with a 10-second timeout.

(4) Consider implementing SO_LINGER (its interesting but we don't have 
a  strong use-case for it yet:  infinite time out is too long, abort 
isn't a normal close.  The only thing interesting to me is the ability 
to have the socket.close() block until timeout.  Then, with an exception 
handler, one can verify that the connection closed gracefully.   When 
one is churning many connections, blocking the close could be onerous.  
However, for a uPy device with few connections, it could be useful.  In 
a sense, the blocking SO_LINGER with non-zero timeout provides the 
opposite utility to a severe mid-connection exception exit.  The other 
SO_LINGER modes are not so useful.  So, we "fix" the awkward SO_LINGER 
behaviors by giving the user control over timeout and under which 
conditions we abort or abandon a connection.

**Comment by t35tB0t** [comment]
side note to @dpgeorge :  I wasn't sure if I was supposed to close issue 4590 or let a developer do so.  Based on PR4671 commits, issue 4590 is no longer apparent.  When zombie packets could no longer be spawned and the stack couldn't be jammed - I closed the issue.  Now I'm thinking I should have let you close it when/if committing to master.  Next time,  I'll close only in comment and let the issue automatically close when/if the related commits are merged unless you specify otherwise.

**Comment by dpgeorge** [comment]
I merged this PR in d5f0c87bb985ae344014dc2041fbaad5c522f638, with the default timeout increased to 10 seconds.

**Comment by dpgeorge** [comment]
A fix to the commit added by this PR was made in 019dd84af1e8e9bbdbbb6377c28950d31f05a77c

@t35tB0t FYI

**Comment by dpgeorge** [comment]
This PR was merged (see above links).  SO_LINGER TODO is now tracked by issue #7442.

**Pull request closed without merging**
