### PR TITLE
esp32: Use check_esp_err() for get error message.

### PR DESCRIPTION
**Pull request by IhorNehrutsa**
I suggest making the path to understanding the error easier.

First, all esp-idf errors will have native error messages. For example:
ESP_ERR_ESP_NETIF_DNS_NOT_CONFIGURED will be output, not 
Wifi Unknown Error 0x500A

Second, ESP_ERR_XXX_XXX error codes have more info in Google search requests.

### CODE REVIEW

**Comment by MATTYGILO** [comment]
Same problem

**Review by MATTYGILO — APPROVED** [review]

**Comment by IhorNehrutsa** [comment]
@robert-hh
May you review this PR?
Thanks

**Comment by robert-hh** [comment]
That PR seems useful for all users, and there is no change in code size. Looks good.

**Comment by IhorNehrutsa** [comment]
Closed in favor #10888

**Pull request closed without merging**
