### PR TITLE
esp32/machine_rtc: Allow MEM_USER_MAXLEN to be changed during compile. Fixes #4973

### LINKED ISSUE #4973: esp32/machine_rtc: Make it easy to change the RTC UserMem size.
Hello,

I'm using a lot of RTC memory for my own C level code inside some C Modules. I'm running out of slow mem space when linking. I believe that this is my primary issue: https://github.com/micropython/micropython/blob/master/ports/esp32/machine_rtc.c#L54

While having user memory available from Python is a really nice feature, usually, it conflicts with my design.

I would like to be able to change MEM_USER_MAXLEN from the `make` line, as I prefer to not manipulate MicroPython source in my builds so that I can keep up to date with upstream improvements.

I believe if `#define MEM_USER_MAXLEN 2048` was replaced with
```
#ifndef MEM_USER_MAXLEN 
  #define MEM_USER_MAXLEN 2048
#endif 
```

Then I would be able to specify this value to be 0x0 or something sufficiently small on my `make` line when building the ESP32 port that it wont occupy a half my slow memory.

I'm happy to make a PR, but I thought this should be discussed first.

*Edit*: Another option would be to have this memory dynamically sized by the linker based on the free amount of slow ram available. I'm not familiar enough with linker scripts to suggest a PR for this.

Josh.

### PR DESCRIPTION
**Pull request by nevercast**
Don't define MEM_USER_MAXLEN if it already exists, i.e. may have been defined on the command line as C arguments.

Fixes: https://github.com/micropython/micropython/issues/4973

### CODE REVIEW

**Comment by nevercast** [comment]
I will be setting this from my cmodule like so:
```
CFLAGS_USERMOD += -I$(DSSTUB_MOD_DIR) -DMEM_USER_MAXLEN=0
```

**Comment by nevercast** [comment]
I have just verified that this patch fixes my issue. By using the `CFLAGS_USERMOD` line above in my cmodule `Makefile`. Once this PR is merged, I can start building from upstream again.

**Comment by andrewleech** [comment]
I mostly work with the stm32 port, where there's lots of this kind of #ifdef for overriding during build, so the concept should be fine.

Most of the build defines there though follow a common pattern like `MICROPYTHON_PY_XYZ`, as seen in https://github.com/micropython/micropython/blob/master/ports/stm32/boards/B_L072Z_LRWAN1/mpconfigboard.h fit example.

I'm not sure if this pattern (or similar) is also common in esp port, but I'd suggest it's good to follow either way to highlight the fact this is intended and a build variable (with hard coded default).

**Comment by nevercast** [comment]
Hi @andrewleech 

I don't see anything called `mpconfigboard.h`. For the ESP32 we do use an `sdkconfig` file which essentially sets up the underlying system on the ESP32 image. I suspect its similar.

I do like the idea of having a common place to configure MicroPython for each port, and we do have `mpconfigport.h` which is probably the most similar thing we have. We just don't have different configs for different boards (other than those with and without external PSRAM).

I'm happy to move some defaults to elsewhere, but for the moment I don't think there is a home for this sort of thing on the ESP32 port. It would also still need to be an `#ifndef` because I'm trying to make 0 changes to MicroPython repository when building, so I need to declare the variable as a `C_FLAG`.

**Comment by mattytrentini** [comment]
ESP32 doesn't currently have the concept of a board like STM32; the mpconfigboard.h is akin to the mpconfigport.h but for board-level configuration.

I've _started_ looking in to extending the ESP32 port to handle boards; it would make sense given the glut of different boards that have appeared. Could use some help though because my first priority was bringing that concept to the ESP8266 (primarily to make it easy for a beginner to start with the popular Wemos boards and their distinct "Dx" naming of pins).

**Comment by andrewleech** [comment]
Sorry my intention when linking to that file wasn't so much meaning to use a board config file, but just an example of #define naming conventions. 

Still, I'm not sure if that convention is used elsewhere on the esp ports, but I think it's a good idea for consistency nonetheless.

**Comment by nevercast** [comment]
I was talking to @zrecore this more regarding his D2WD board issues. You're right @mattytrentini that with the increase in ESP32 boards I'd like to see an approach to having board configs. Similar to the way stm32 port is handling it. We have a board directory. We should have subfolders for board configurations/community boards with their own sdkconfig, defines, and partition.csv so that when someone wants to compile uPy for a board they have purchased from Tindie or wherever, they can just `make BOARD=tinypico` and it builds as recommend

**Comment by nevercast** [comment]
@jimmo Is there anyway to achieve this with your changes in #4991 ? I'd really like my small change to land in master but if I can achieve the same with your changes, I'll do that and either rebase on top of what you have, or just wait for that to land and create a new PR.

**Comment by jimmo** [comment]
@nevercast Yes, this is exactly the intention of #4991. You would set this variable in boards/BOARD/mpconfigboard.h (not the makefile).

Note: the convention seems to be to name it `MICROPY_HW_`, and generally you don't see port-specific (e.g. `_ESP32_`) parts. I'd call it `MICROPY_HW_RTC_USER_MEM_MAX`.

**Comment by nevercast** [comment]
I see, `_HW_` is anything that is port specific?

**Comment by nevercast** [comment]
Rebased and applied recommendations. Is it worth adding any documentation regarding this? Or a board config to demonstrate that this can be configured in `mpconfigboard.h` ?

**Comment by nevercast** [comment]
Spoke with @jimmo and he seemed happy with this. Is there anything blocking this being merged, @dpgeorge ?

**Comment by nevercast** [comment]
Can I please get some feedback on this? I am using this feature so I can't use mainline upy. Cheers.

**Comment by nevercast** [comment]
Rebased and squashed. Had to do it at my end anyway so pushed the change upstream.

**Comment by dpgeorge** [comment]
Followed up in #5349

**Pull request closed without merging**
