### PR TITLE
stmhal: Rename STM32F401NUCLEO to NUCLEO_F401RE

### PR DESCRIPTION
**Pull request by dhylands**
This makes the board match the name printed on the board (and
agree with the documentation)

### CODE REVIEW

**Comment by dpgeorge** [comment]
Underscores are used for ESPRUINO_PICO and NETDUINO_PLUS_2, so would be nice to keep things consistent and use underscore here... except that the hyphen is used in the actual name given by ST to the board, so maybe indeed best to use hyphen here (and in #1870)?

Also, probably want to change the MICROPY_HW_BOARD_NAME definition to match the directory name in this case.

**Comment by dhylands** [comment]
Even though the board has a dash, it's probably better to use underscore for consistency. I'll fix both PRs.

**Comment by dhylands** [comment]
Renamed using underscore
Added SPI definitions
Changed board name (in mpconfigport.h)

**Comment by dpgeorge** [comment]
Merged in 00f921ce0258bb490cef1c82216a1b443e3b570f and 99fc0d120a139a1525384663552b568fab6215e2.

**Pull request closed without merging**
