### PR TITLE
Added FeatherS2 and TinyS2 to build system

### PR DESCRIPTION
**Pull request by UnexpectedMaker**
As the title says - sorry I dropped the ball on this!

### CODE REVIEW

**Review by mcauser — CHANGES_REQUESTED** [review]

**Review by mcauser — APPROVED** [review]

**Comment by dpgeorge** [comment]
Unfortunately this won't work because the build server uses IDF 4.2, which doesn't support S2 (I don't think?).  I didn't want to update to IDF 4.3 because the memory layout is different and there are issues with FreeRTOS allocations, like for ssl connections.

Not sure what the best way forward is in the short term.

**Comment by UnexpectedMaker** [comment]
> Unfortunately this won't work because the build server uses IDF 4.2, which doesn't support S2 (I don't think?). I didn't want to update to IDF 4.3 because the memory layout is different and there are issues with FreeRTOS allocations, like for ssl connections.
> 
> Not sure what the best way forward is in the short term.

Oh, hmm, you didn't mention this back when we discussed it.. ok, so how do I get builds for my users without having to continually build them from source?

**Comment by dpgeorge** [comment]
See #7559 for a solution.

**Comment by UnexpectedMaker** [comment]
> See #7559 for a solution.

Oh, you fixed it already? wowza, good stuff!

So nothing I need to set for this? If I add more S2/S3 boards I just need to put them in the right area so they Gert built with the right IDF?

**Comment by dpgeorge** [comment]
> If I add more S2/S3 boards I just need to put them in the right area so they Gert built with the right IDF?

Correct.

**Comment by dpgeorge** [comment]
Merged in 25159129dd9e22474d09235ce6d7a4156fd13c6f

**Comment by UnexpectedMaker** [comment]
Hey @dpgeorge - Where do the builds from the build system live? How do I see them, or point people to them?

**Comment by robert-hh** [comment]
All built images can be found here: https://micropython.org/download/all/

**Comment by mcauser** [comment]
Should those binaries get the "um_" prefix to match the latest boards?

**Comment by dpgeorge** [comment]
> Should those binaries get the "um_" prefix to match the latest boards?

Yes, I think so.

**Pull request closed without merging**
