### PR TITLE
qemu/mpconfigport: Enable VFS reader, loading .mpy files and io.IOBase.

### PR DESCRIPTION
**Pull request by dpgeorge**
### Summary

This change allows importing from the VFS, and enables the following 7 additional tests: builtin_execfile, io_iobase, json_dump_iobase, import_mpy_invalid, import_mpy_native, import_mpy_native_gc, vfs_userfs.

This is split out from #8381 (ROMFS).  In that PR it's needed for the qemu port to be able to test ROMFS features.

### Testing

These 7 new tests will run on CI.

### Trade-offs and Alternatives

This increases the size of the qemu port, but IMO that's OK, it's intended for testing, and this gets it testing more things.

### CODE REVIEW

**Comment by projectgus** [comment]
Is anything else needed for those tests to run in CI? I either see them not mentioned or skipped in https://github.com/micropython/micropython/actions/runs/12296239476/job/34314834928

**Comment by dpgeorge** [comment]
> Is anything else needed for those tests to run in CI? I either see them not mentioned or skipped in

If you go to that action, and expand the "Build and run test suite" bit, and then search for "import_mpy" you should see at least those 3 new tests passing.  And the other 4 should also be there.

**Comment by dpgeorge** [comment]
See also #15937, which enables more mpy tests on qemu.  This PR is one of the commits of that PR.

**Comment by projectgus** [comment]
> If you go to that action, and expand the "Build and run test suite" bit, and then search for "import_mpy" you should see at least those 3 new tests passing. And the other 4 should also be there.

Ah, my mistake. That's what I did but I was searching with Firefox Ctrl-F which doesn't work (even after scrolling the whole log), because it's only partially loaded somehow. If I use the search box on the page, or "View Raw Log" and Ctrl-F in that, then I can see the tests. :facepalm:

**Review by projectgus — APPROVED** [review]

**Pull request merged**
