### PR TITLE
Implement consistent machine.ADC with read_u16() method

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR implements the beginnings of a revised machine.ADC class which is intended to make the ADC class more standardised across ports.  See #3943 and #4213 for background discussion.

The PR here implements the following (simple) API for stm32, esp8266, esp32 and nrf ports:
```python
from machine import ADC

adc = ADC(source) # source can be a pin or channel (eg int)
adc.read_u16() # take a reading, returning a value between 0 and 65535 inclusive
```

On stm32 the source can be any pin that has ADC support, or a constant `ADC.CORE_VREF`, `ADC.CORE_VBAT`, `ADC.CORE_TEMP` for internal channels.  It will pick the correct ADC peripheral that supports that source (eg ADC1, ADC2 or ADC3).  Other ports support taking a pin and/or a channel number.

The method `read_u16()` is named to emphasise the units, that it's an unsigned 16-bit number, and is the raw ADC reading scaled to 16 bits.

The aim of this PR is to make basic ADC functionality available in a consistent way across ports.  Other things (eg setting resolution, sample time, selecting ADC peripheral block) can be added later, but at least construction and reading (implemented by this PR) are necessary features and the approach taken here is hopefully obvious and not controversial (up to perhaps the name `read_u16`).  In other words, it should be possible to decide on the API presented here regardless of how additional features (mentioned above) might be implemented and exposed to the user.

Comments/discussion are very welcome.

### CODE REVIEW

**Comment by carterw** [comment]
I like the idea of returning the type of the ADC data. How do you distinguish between pin and channel on devices that have both pins and channels? Is the 'source' argument compounded? Or just whatever the device can do somehow?

**Comment by dpgeorge** [comment]
> How do you distinguish between pin and channel on devices that have both pins and channels?

For an already-constructed ADC object you can't tell the difference.  I don't really see a need for this because a pin source is really just a pin (in analog mode) connected to a specific channel (at least that's how it works on stm32, which has both internal and pin-connected channels).

> Is the 'source' argument compounded? Or just whatever the device can do somehow?

It's up to a port/device to decide what the "source" argument means, and the ADC constructor is in general overloaded to accept different types for "source".  All ports should allow a pin to be passed in as the source, and the corresponding ADC "channel" (if a port has such a concept) will then be selected.  And then usually passing in an integer would select a channel.

**Comment by dpgeorge** [comment]
> So it seems like in your implementation the appropriate SAR would be derived from the pin number instead of being specified directly there as 'unit'?

Yes, correct.  Although there are currently no plans to implement ADC2 because it's used by the WiFi (but it could fit into this API in the future).

**Comment by dpgeorge** [comment]
> there you are including a 'block' parameter in the init method. Not the case for ADC?

That PWM proposal shows an alternative way of specifying "blocks".  But I do prefer what is proposed in #4213, where a block is exposed as an actual object/class like `ADCBlock`.  That seems to me to be a more powerful approach.

**Comment by carterw** [comment]
So in the 4213 PR there are two forms of the ADC class. One is 'generic' and intended to provide basic commonly used setups and the xxxBlock() class would be an alternative with platform-specific settings? That seems reasonable to me.

I'm concerned that the resolution of this class signature semantics issue is taking a long time - going on a year. And until it does get resolved none of the PR's can be completed and closed, it is a log jam. What can be done to move it to resolution?

**Comment by dpgeorge** [comment]
> xxxBlock() class would be an alternative with platform-specific settings?

The `ADCBlock` class is intended to represent an actual ADC peripheral which does the conversion of the analog value, and has multiple channels (in contrast to `ADC` which is just a single endpoint/channel).  But yes, `ADCBlock` would probably have more settings/configuration.  That's the intention anyway.

**Comment by dpgeorge** [comment]
I merged this PR in ebacdfabb6e2ac695d6660f2a6420ab84db76d39, 625609a7378ab6ee92855e031335cc1a915a99c8, 0e72cc90291d254014edee7be66b066c73d1fc71, 983283a8cd504e2f9438a836effa9e862f19ec97, 9cad134a2f861a0f8864b70ab80c9d6cc61c2932

**Comment by nevercast** [comment]
> > So it seems like in your implementation the appropriate SAR would be derived from the pin number instead of being specified directly there as 'unit'?
> 
> Yes, correct. Although there are currently no plans to implement ADC2 because it's used by the WiFi (but it could fit into this API in the future).

You would fit ADC2 in as `ADCBlock` only? Perhaps throwing an exception if a `machine.ADC` is constructed with an ADC2 pin on ESP32? The extra hoop may give sufficient caution regarding conflict with WiFi. 

```
>>> adc = machine.ADC(pin=machine.Pin(4)) # ADC2/0
ValueError: Pin(4) uses the ADC2 peripheral and conflicts with WiFi usage. See http://docs.micropython.org/l/fha7haf for more information, and workarounds.
>>>
```
```

**Comment by carterw** [comment]
I use an ADC2 pin successfully in an application (loboris port) when WiFi isn't activated. That's because literally all the other ADC-capable pins are already assigned and in use. So really I think there is no reason to not include it, let the developer make the choice.

**Comment by nevercast** [comment]
What's the consequence when WiFi is in use? Is it just an IDF error?

**Comment by carterw** [comment]
I don't know, I reboot with a different setup if I need WiFi and don't activate that pin.

**Comment by kevinjwalters** [comment]
There's some variation in how an ADC sample that's smaller than 16 bits is converted to that width.

A straight shift:

https://github.com/micropython/micropython/blob/ef9fde7339b12e17596966afb2b3d641ca5fcff2/ports/nrf/modules/machine/adc.c#L185

Somehing more elaborate putting some values in the lsbs:

https://github.com/micropython/micropython/blob/8e048d2548867aac743866ca5a4c244b7b5aac09/ports/esp32/machine_adc.c#L96-L97

Is that as intended?

**Comment by dpgeorge** [comment]
> There's some variation in how an ADC sample that's smaller than 16 bits is converted to that width.
> ...
> Is that as intended?

Yes that's intended.  Both those examples above are the same, it's just that the nrf one is simplified when `adc_bit_width=8`.  It's a Taylor expansion of:
```
u16 = raw * 65535 / ((1 << adc_bit_width) - 1)
```

**Comment by kevinjwalters** [comment]
Oh, I somehow misread the nrf one as return `MP_OBJ_NEW_SMALL_INT(raw << 8)`, sorry about that! Is there a reason to limit the nRF52 to 8bit? It's a [bit noisy](https://learn.adafruit.com/clue-metal-detector-circuitpython/adc-analysis) at 12bits but that's what CircuitPython runs it at.

I've been having a look at the various Espressif ADCs and we were discussing whether MicroPython applied a correction in the code to the rather shoddy raw ADC output, hence my interest in the code. Some graphs in [Adafruit Forums: Feather ADC comparison including 2.6V limited ESP32-S2](https://forums.adafruit.com/viewtopic.php?f=60&t=174020&p=852007&hilit=uncorrected#p852007) if you're interested. I think the regular ESP users all know this but I got surprised by the ESP32-S2 giving some confusing results with an analogue peripheral.

**Comment by dpgeorge** [comment]
> Is there a reason to limit the nRF52 to 8bit?

No reason, it could be changed to 12 bits (and maybe given an option to select the bits, following esp32).

**Pull request closed without merging**
