### PR TITLE
javascript: Rename port from 'javascript' to 'wasm'.

### PR DESCRIPTION
**Pull request by ntoll**
Does exactly what it says, renames the `javascript` port to `wasm`.

See discussion on the forum here: https://forum.micropython.org/viewtopic.php?f=3&t=12916

### CODE REVIEW

**Comment by dlech** [comment]
Makes sense to me. Trying to think forward, if we ever wanted to target, e.g., the WASI runtime in addition the Emscripten runtime, would it be a separate port or just a variant?

Just for reference for anyone interested, [this](https://pythondev.readthedocs.io/wasm.html#cpython-on-webassembly) is a quick rundown of how CPython handles the two different runtimes in terms of `sys.platform`, `os.name()`, etc.

**Comment by dlech** [comment]
> See discussion on the forum here: https://forum.micropython.org/viewtopic.php?f=3&t=12916

It could be helpful to include the reasoning in the commit message in case anyone is tempted to change it back.

**Comment by jimmo** [comment]
Hi @ntoll!

Thanks for this, I have occasionally wondered the same thing. I wasn't sure if the name should be "wasm" or "emscripten", but I don't really know enough about the ecosystem to be precise enough with the terms. (I guess what I'm trying to say is "are we naming the port for the toolchain or the target"). How does WASI fit into this? (I think this is exactly what @dlech is asking)

The impression I get from the CPython docs that @dlech linked to is that we should name this port "wasm" (or perhaps "webassembly") but "emscripten" and "wasi" would be two different variants / configurations of this port.

So yes, keen to merge this PR as-is assuming the logic above is correct.

**Comment by dpgeorge** [comment]
Welcome @ntoll, great to see you here!

Until a few weeks ago I would have been in favour of this rename, because it does indeed generate wasm output.

But then I had a need to switch it back to generate pure Javascript because I was trying to get a build of `mpy-cross` running in the browser.  Using the wasm output adds an asynchronous element to it the whole system, you need to wait until the page is loaded and it then loads the wasm code asynchronously, and only after that is done can you start using it.  Switching back to Javascript output using `-s WASM=0` allows you to generate a pure .js file for inclusion in a webpage and everything is synchronous.  For `mpy-cross` -- and other instances where you just want to run a single piece of Python code to completion -- it seems to me to be much more convenient to use the Javascript output.

In that case, if it's not clear that a rename is the obvious thing to do, I'd rather not rename it.

**Comment by ntoll** [comment]
Hey folks,

Thank you so much for the welcome. I think we probably all agree that naming things is hard :tm: :slightly_smiling_face: .

Clearly, this is not a technical issue, but an aesthetic one, and renaming the port is a trivial 15 minute search and replace. The danger is, of course, the colour of the bike shed (a bike shed potentially containing hairy yaks). We're all busy people and probably have better things to do with our time. :wink: 

Heads up, if what I'm currently doing pans out as I hope it will, I'll be spending a LOT more time working with this port of MicroPython and will likely be contributing/suggesting less trivial changes or refinements. I'll liaise with @dpgeorge and/or mention things on the forum before any PRs get here. I feel it very important that work isn't done until we have a consensus about if it needs to happen, and if so, how.

N.

**Comment by dpgeorge** [comment]
Talking to @jimmo about this, it might make sense to rename this port to `webassembly`, because that's a better description of the target platform for this port.  There are a few different and related technologies here, like Javascript, WASM, WASI, Emscripten, and WebAssembly is a decent umbrella term for those technologies.

What do you think about `webassembly` @ntoll ?

**Comment by ntoll** [comment]
We have a winner..! :slightly_smiling_face:  Gimme 10mins and I'll update the PR to the new name. :+1:

**Comment by dpgeorge** [comment]
Naming things is definitely hard, and MicroPython suffers its fair share of it.

**Comment by ntoll** [comment]
I look forward to the upcoming release of PicoPython. </joke>

**Comment by ntoll** [comment]
Superseded by #9073.

**Pull request closed without merging**
