### PR TITLE
mpy-cross/Makefile: add OS detecting for building mpy-cross tool

### PR DESCRIPTION
**Pull request by ccccmagicboy**
add OS detecting for building mpy-cross tool itself too. test under github action runner here: [mpy-cross](https://github.com/ccccmagicboy/MicroPython_fw_action/actions/runs/49871075)

### CODE REVIEW

**Comment by stinos** [comment]
This has been discussed before and it's not a sufficient solution but more of a dedicated workaround for some cases so this might fix things for some, and break things for others. See #4143 #4996 #3361 and possibly others.
So I think it's time to fix this once and for all (both for mpy-cross and micropython itself). I propose we list the cases which should work and then come up with a solution. I don't mind doing/testing all of this, if people can provide proper instructions for setting up build evironments I don't have.

Cases I can think of, feel free to add and or comment for those not needed:
- gcc from mingw-w64, invoking make on msys2
- clang for windows, invoking make on msys2
- gcc from mingw-w64, invoking make on cygwin
- gcc cross-compiler from mingw-w64, invoking make on linux
- whatever people use for ESP on windows (please comment what this is and how it works)

There's also a gcc which comes with cygwin which I think doesn't create windows binaries but I don't think we need that.

**Comment by ccccmagicboy** [comment]
The mpy-cross building environment of mine is a github actions windows-latest host(Windows Server 2019) with a default MINGW64_NT-10.0-17763 toolchain. When use the master branch of upstream micropython code here, after building the result executable file is a **mpy-cross** which without the  .exe extension which is not what i expect, so I add a .exe extension to this executable file. And this PR maybe useful for who have a similar environment.

**Comment by stinos** [comment]
> a default MINGW64_NT-10.0-17763 toolchain.

As far as I'm aware mingw-w64 is only gcc, not make, so I assume this runs in an MSYS2 shell?

> the result executable file is a mpy-cross which without the .exe extension which is not what i expect

Not 100% sure what you mean here: does the build output create mpy-cross and you rename the file to mpy-cross.exe?

**Comment by ccccmagicboy** [comment]
Sorry, please forgive me, my English in not so good. What i mean **add a .exe extension** is via:
```
ifeq ($(OS),Windows_NT)
# define main target
PROG = mpy-cross.exe
else
# define main target	# define main target
PROG = mpy-cross	PROG = mpy-cross
endif
```
and the default toolchain including a mingw32-make
59FEE77A-48E1-4578-99BF-34A5CBD996F3

**Comment by dpgeorge** [comment]
As far as I can tell this adds support for a custom `$(OS)` variable in the Makefile (which seems only to be defined on Windows?) and if it's defined to `Windows_NT` then it adds a `.exe`.

I guess this could be a very simple way to fix this whole problem of adding .exe, but maybe the check needs to be more sophisticated to detect more environments that need .exe added.  See eg https://stackoverflow.com/questions/714100/os-detecting-makefile

**Comment by stinos** [comment]
Indeed, see comments above: this detection doesn't work for all/most scenarios; haven't checked all possibilities on the Windows side of things but what definitely does not work is cross-compiling since when building on linux targetting mingw the `$(OS)` isn't `Windows_NT` yet a `.exe` gets produced. Not sure if we need to take that into account (I don't know why the Travis cross-compilation build doesn't do it actually, it builds mpy-cross natively) but it's just to illustrate that OS detection is too limited and the proper solution is likely going to be to just ask the compiler what it's going to produce.

**Comment by chrismas9** [comment]
I have started working on this again. I think I have a solution for all build environments but it needs a lot of testing. Right now I am installing 4 build environments on separate hard drives for WSL, MSYS2, Cygwin and Linux and documenting the installation processes for each. Then I will rebase my solution and start testing.

**Comment by stinos** [comment]
Sounds good! But why do you need this on separate drives for all of them? I'm fairly certain WSL, MSYS2 and Cygwin do not interact with each other in any way, also not because essentially they are portable i.e. just unpack a zip file and run from that directory (though WSL is a bit different to that end, but not much)

**Comment by chrismas9** [comment]
I want to test my documentation. I have an Acronis image of a clean Windows install with a few utilities added. After installing the environment and documenting each step I will re-image the disk and follow my documentation to see if it is complete.

I found in the past it's easy to miss a step if you don't start with a clean install. For example if you previously installed a tool chain, maybe a vendor IDE, and it installed make you may forget to install and document it and won't notice the omission. Also the WSL and Linux configs are different, for example with WSL I run Git on Windows so the WSL and Linux documentation will be different.

4 disk's. I have a swappable drive bay for 2.5" drives so it's quick to swap. I can re-image a drive in 10 minutes. I can nuke one config say for MSYS2 and not loose the other configs. This is all about testing the build environment setup. Once that's done I may install them all on one disk for testing the MicroPython building.

**Comment by dpgeorge** [comment]
Closing in favour of #4996.

**Pull request closed without merging**
