### PR TITLE
extmod/modonewire.c: Fix onewire timing and logic.

### PR DESCRIPTION
**Pull request by xorbit**
The timing of the onewire module was way too fast when reading.
The write timing was correct, with a 10us low pulse for 1 and
60us for 0.  But read would pulse low for 5us and then sample
the wire after 10us.  This is way too fast since a 1 can be
a pulse of up to 15us and would be read as 0.  Plus the whole bit
time for read was only 50us, while a client may output a pulse
of up to 60us to indicate a 0.  Compounding the problem, the code
would not check if the bus was high before starting a bit pulse,
just blindly plowing through whatever the slave might have been
sending with the next bit before the slave was done.

This code now outputs a 10us pulse for read to be consistent with
the write, then samples the bus after 30us as is the case with
most implementations I found.  The total read bit time is 60us.
The code also first checks whether the bus is high before starting
a bit, and waits in 10us increments up to 100us before starting to
output a bit pulse.

### CODE REVIEW

**Comment by xorbit** [comment]
Ugh. With the pile of stupid formatting commits, I'll redo this in a clean pull request.

**Comment by stinos** [comment]
Look into using interactive rebase instead (`git rebase -i <sha of parent commit>`: it allows you to e.g. squash all commits into one. Then `git push --force` in the same branch. No need for another PR, which also has the benefit all information about one PR stays localized and is easy to look up.

**Comment by tve** [comment]
What is the reference you use for the protocol timing spec? I'm looking at a DS18B20-PAR datasheet and I see:
- "A read time slot is initiated by the master device pulling the 1-Wire bus low for a minimum of 1 μs and then releasing the bus."
- "Output data from the DS18B20-PAR is valid for 15 μs after the falling edge that initiated the read time slot. Therefore, the master must release the bus and then sample the bus state within 15 μs from the start of the slot."
- "Figure 14 illustrates that the sum of T INIT , T RC , and T SAMPLE must be less than 15 μs for a read time slot."

So IMHO the read timing is fine. Checking that the line is high before initiating a bit transfer makes sense, but I have net seen any driver that does that, and I've seen and coded my fair share of one-wire drivers...

**Comment by xorbit** [comment]
@stinos Sorry, I'm not an advanced enough git user to know all that stuff.  I already redid it in #7050.

**Pull request closed without merging**
