### PR TITLE
Custom float (and complex) casts

### PR DESCRIPTION
**Pull request by nickovs**
This PR implements support for the `__float__` and `__complex__` special methods as described in the [Python data mode](https://docs.python.org/3.5/reference/datamodel.html#object.__complex__) for platforms that support the `float` and `complex` types. These methods allow custom classes to provide `float` or `complex` representations of themselves.

## Compatibility with C Python

The exceptions raised by this PR are the same types as those raised by C Python, but the messages are different (shorter, and constant). One minor difference in functionality is that this code raises a TypeError if the type of the results from these methods is not the desired `float` or `complex`, whereas C Python 3.6 and 3.7 allow subclasses of those types but issue a deprecation warning to indicate that the strict type will be required in the future.

## Is this addition necessary?

The main benefit of this addition is that it improves compatibility with C Python. The two use cases that motivated its creation were (a) custom classes representing sensors that have numeric, non-integer values and (b) allowing better compatibility for a micro-implementation of a subset of NumPy.

The additional code is very small (the static exception messages take up more space than the code on most CPU architectures, and could be made smaller if they were less informative). The code is only present on platforms that already carry the weight of the optional `float` and `complex` classes.

### CODE REVIEW

**Comment by peterhinch** [comment]
:+1: Use cases for `__complex__` include graphics, navigation and electronics. Anywhere you want to twiddle a vector.

**Comment by dpgeorge** [comment]
Thanks for the PR.  Since `__int__` is already supported it would make sense to support float and complex special methods as well.

You'll see that `__int__` is implemented using `mp_unary_op(MP_UNARY_OP_INT, obj)` and it may be cleaner/simpler/more-consistent to do it in a similar way with `MP_UNARY_OP_FLOAT` / `MP_UNARY_OP_COMPLEX`.  Essentially the change would be that `mp_obj_get_float()` falls back to calling `mp_unary_op(MP_UNARY_OP_FLOAT, obj)`, which is automatically delegated to `__float__` by adding an entry to `py/objtype.c:mp_unary_op_method_name`

**Comment by nickovs** [comment]
@dpgeorge Moving this into `mp_unary_op()` would clean up a little of the implementation in `objfloat.c` and `objcomplex.c` but I would then have to make `mp_unary_op()` implement the fallback logic for when a class has no `__float__` but has `__int__` or  it has no `__complex__` but it has `__float__`, since otherwise `mp_unary_op()` would raise an `unsupported type` error. It seems to me that those bits of logic belong in `objfloat.c` and `objcomplex.c`, but if you are happy for them to be in `objtype.c` (on the grounds that this is part of the Python data model) then I'm happy to put them there.

**Comment by nickovs** [comment]
Looking into this some more, the way that `mp_unary_op()` raises exceptions rather than returns errors seems make handling the implicit conversions between ints, floats and complex numbers rather difficult.

As an aside, while inspecting the code that implements unary operators I spotted a subtle bug, which I've logged in #6175. I look forward to winning the "Obscure and Occult Bug of the Month" prize with this one :-)

**Comment by dpgeorge** [comment]
> implement the fallback logic for when a class has no `__float__` but has `__int__` or it has no `__complex__` but it has `__float__`

Does this PR implement that logic?  It doesn't look like it does.

> It seems to me that those bits of logic belong in `objfloat.c` and `objcomplex.c`, but if you are happy for them to be in `objtype.c` (on the grounds that this is part of the Python data model)

The idea is that, internally in uPy, `type->unary_op(self, MP_UNARY_OP_INT)` implements `type.__int__(self)` in an efficient way.  And efficient here mostly refers to reduced code size, it's simpler to add a new case to a switch in `unary_op` than it is to add a whole new method to the type.

If you look at how `mp_obj_int_make_new()` is implemented, it falls back to `mp_unary_op(MP_UNARY_OP_INT, args[0]);` to implement `args[0].__int__()` as a last resort for the conversion.

So IMO it'd make sense to follow this logic, for consistency.

But this is easier said than done.  For example, does it make sense for `mp_obj_get_float()` to call `mp_unary_op(MP_UNARY_OP_FLOAT, arg)` as a final conversion attempt?  If yes then this allows passing custom types to math functions, eg `math.sin(mytype)`, where `mytype` implements `__float__`.  And this is actually compatible with CPython (the current PR doesn't allow/implement this).

OTOH, making `mp_obj_get_complex()` work in the same way (trying `MP_UNARY_OP_COMPLEX` at the end) will now make `1j + mytype` succeed, which is not compatible with CPython (and not something one wants to allow, I guess).

**Comment by nickovs** [comment]
OK, so it sounds like I should move to code for implementing floats into `mp_unary_op()` and use that as the last resort method for `mp_obj_get_float()` but leave the code for handling complex much as it is (since it's last resort is to call `mp_obj_get_float()`. I will get that a try.

**Comment by dpgeorge** [comment]
A little bit related: looking at how int make_new and float make_new work, I found a small inconsistency which is fixed by #6179

**Comment by nickovs** [comment]
So it turns out that the proposed approach has a problem (or at least an incompatibility with CPython). In CPython, if the class of`x` implements `__float__()` then while evaluating `math.sin(x)` works, evaluating `1.0 + x` raises a type error. This is because the CPython `mathmodule.c` code makes an explicit call to a function that eventually calls `__float__()`. Moving the code into `mp_obj_get_float()` results in `1.0 + x` succeeding if `x` implements `__float__()`. Worse, it means that is `x` implements both `__float__()` and `__add__()` then `1.0 + x` will use the float coercion rather than the explicit addition implementation.

For CPython compatibility I think I should probably put the code back where it was and fix up the `math` module to try to convert values into floats.

**Comment by dpgeorge** [comment]
> Moving the code into `mp_obj_get_float()` results in `1.0 + x` succeeding if `x` implements `__float__()`.

When I looked at it, I saw this behaviour with complex but not float.  Because `mp_obj_float_binary_op()` calls `mp_obj_get_float_maybe(rhs_in)` to extract the float from the RHS, and the maybe variant doesn't check for `__float__`.

My very simple patch to implement `__float__` is:
```diff
diff --git a/py/obj.c b/py/obj.c
index 07b161255..ccab66d27 100644
--- a/py/obj.c
+++ b/py/obj.c
@@ -359,6 +359,10 @@ mp_float_t mp_obj_get_float(mp_obj_t arg) {
     mp_float_t val;
 
     if (!mp_obj_get_float_maybe(arg, &val)) {
+        arg = mp_unary_op(MP_UNARY_OP_FLOAT, arg);
+        if (mp_obj_get_float_maybe(arg, &val)) {
+            return val;
+        }
         #if MICROPY_ERROR_REPORTING == MICROPY_ERROR_REPORTING_TERSE
         mp_raise_TypeError(MP_ERROR_TEXT("can't convert to float"));
         #else
diff --git a/py/objtype.c b/py/objtype.c
index a539fcab2..ee31eedaf 100644
--- a/py/objtype.c
+++ b/py/objtype.c
@@ -373,6 +373,7 @@ const byte mp_unary_op_method_name[MP_UNARY_OP_NUM_RUNTIME] = {
     [MP_UNARY_OP_LEN] = MP_QSTR___len__,
     [MP_UNARY_OP_HASH] = MP_QSTR___hash__,
     [MP_UNARY_OP_INT] = MP_QSTR___int__,
+    [MP_UNARY_OP_FLOAT] = MP_QSTR___float__,
     #if MICROPY_PY_ALL_SPECIAL_METHODS
     [MP_UNARY_OP_POSITIVE] = MP_QSTR___pos__,
     [MP_UNARY_OP_NEGATIVE] = MP_QSTR___neg__,
diff --git a/py/runtime0.h b/py/runtime0.h
index e6eeff97d..4691ec130 100644
--- a/py/runtime0.h
+++ b/py/runtime0.h
@@ -76,6 +76,7 @@ typedef enum {
     MP_UNARY_OP_HASH, // __hash__; must return a small int
     MP_UNARY_OP_ABS, // __abs__
     MP_UNARY_OP_INT, // __int__
+    MP_UNARY_OP_FLOAT, // __float__
     MP_UNARY_OP_SIZEOF, // for sys.getsizeof()
 } mp_unary_op_t;
```
This approach works with `float(mytype)`, `math.sin(mytype)` but not with `1.0 + mytype`.

**Comment by nickovs** [comment]
I can never get `git rebase` to do what I need when the master branch has moved underneath me, so I've created #6201 with everything rebased and squashed.

**Comment by jimmo** [comment]
Superceded by #6201

**Pull request closed without merging**
