### PR TITLE
Fix unix install target

### PR DESCRIPTION
**Pull request by dlech**
This fixes a couple of issues with the install target in the unix makefile. See commit messages for details.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Looks ok to me.  But maybe the install targets can be moved to the main unix Makefile, so one can install other variants if desired?  Eg `make VARIANT=dev install` would be useful.

@jimmo was there a reason to make the install targets work only for the standard variant?

**Comment by dlech** [comment]
updated

**Comment by dpgeorge** [comment]
Thanks!  Merged in c5f4268c9955f08894fec78c1eeacf78f55256c4 and 4af79e76943312bf71be395a71fa80ab39e7c2c2

**Comment by jimmo** [comment]
> @jimmo was there a reason to make the install targets work only for the standard variant?

No strong reason one way or the other. Mostly because it previously only worked for the default build (i.e. you couldn't write `make minimal install`).

This change looks good.

**Pull request closed without merging**
