### PR TITLE
[NRF] Blink LED1 after boot instead of steady ON

### PR DESCRIPTION
**Pull request by rolandvs**
As it seems to me it does not serve any further purpose I would propose to blink the LED and get everything in a non-active state after startup.

### CODE REVIEW

**Comment by dpgeorge** [comment]
> What does other ports do here

stm32 flashes an LED very briefly, I'd say it's shorter than 50ms, but still quite noticeable.  It turns it on at the start of the boot sequence and off after executing boot.py.

**Comment by glennrub** [comment]
It makes sense to leave the LED in an off state after boot. And i realized also that keeping the LED on for 1 second is a bad idea, as it will significantly delay the entry into REPL. So, around 50ms makes sense. 

As an alternative i tried to add a second do_str() right before entering REPL to turn the LED off again, keeping the original code to turn it on. It seems to be slightly shorter than 50ms, but looks good as well. That would align a bit with stm32 port and also prevent an active busy loop in the boot sequence.

**Comment by dpgeorge** [comment]
To make the blink longer and not hold up any code, I'd suggest to follow stm32 and turn on the LED ASAP in the start-up process (eg just after the `soft_reset:` label) then turn it off just before executing boot/main.py.  It would then need to be done in C, using something like `led_state(&board_led_obj[0], 1)` (to turn it on, and `led_init()` called at the very start of the boot).

**Comment by glennrub** [comment]
I agree with @dpgeorge's propsal here. I believe the educational line of _do_str()_ has achived its purpose by now, and its time for it to go in favor of a neat bootup =)

**Comment by rolandvs** [comment]
@glennrub : I'm sorry, it seems that a bit more came along with the patch for the LED alone.

**Comment by glennrub** [comment]
@rolandvs, Looks very neat now! :) 

I cloned your branch and tested it with pca10028. The blink is long enough for me =) The code also aligns well with the stm32 port and provides public functions for LEDs from other c-modules during debug/development, which is nice.

Only one thing, for consistency, maybe we should move the `led_init()` inside the `soft_reset`? This will make sure that all LEDs are configured off and as output when starting up again from a soft reset.

Do you think its possible to fix up the branch, to ease merging? This is really two commits. One for the `leds.c` module which ideally should go in first, followed by the `main.c` patch using the new API exposed by `leds.c`.

**Comment by glennrub** [comment]
@rolandvs, i forgot one thing in my previous comment. 

> ... do_str() has achived its purpose by now, and its time for it to go ...

By this i tried to say, delete it =) So, the new `#if (0)` could be elided in my opinion.

**Comment by rolandvs** [comment]
@glenrub I changed the files, tested it, but before I commit I have a question: the use of `#MICROPY_HW_LED_TRICOLOR` seems not very useful. Its use of the colors is not supported and still need (1,2,3,4) as parameter. Isn't it better to remove the TRI-color stuff?

**Comment by glennrub** [comment]
> the use of #MICROPY_HW_LED_TRICOLOR seems not very useful. Its use of the colors is not supported and still need (1,2,3,4) as parameter. Isn't it better to remove the TRI-color stuff?

@rolandvs , you might be right, i'll take a look at it as well. We can probably follow up this up as a new issue. If i recall it correctly i intended to render a QSTR for the different colours to ease the lookup. But, maybe its better to remove it.

**Pull request closed without merging**
