### PR TITLE
stm32/mboot: Add support for signed and encrypted DFU files (v2)

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR adds support to stm32/mboot for signed and encrypted DFU firmware updates.  The update can happen over USB DFU or via loading from the filesystem.

The code here is based on the initial work done by @andrewleech in #5309 .  The concepts are similar (libhydrogen is still used) but quite a few things changed.

TODO:
- [x] make libhydrogen a git submodule (currently it's included verbatim)
- [x] remove testing-only commits that enabled mboot encryption on various boards
- [x] more tests on hardware

### CODE REVIEW

**Comment by dpgeorge** [comment]
Updates made:
- libhydrogen is now a git submodule (it's only about 400k)
- renamed `MBOOT_ENABLE_PACK` to `MBOOT_ENABLE_PACKING`

**Comment by dpgeorge** [comment]
Further update: finalisation of firmware is now done right after the final signature passes (rather than when the host requests the device to leave DFU mode, which is not reliable because it doesn't work with all DFU tools).

**Comment by dpgeorge** [comment]
Final updates:
- made mboot run at 96MHz on F4/F7 boards when MBOOT_ENABLE_PACKING is enabled, to make it faster
- left MBOOT enabled on NUCLEO_WB55 for testing and demo purposes
- updated mboot README
- improved commit messages

**Comment by tve** [comment]
I'm not seeing any unit tests for this?

**Comment by andrewleech** [comment]
Yeah I should have written some form of test for the signature/encrypting scripts and handling, though like the rest of mboot it's pretty hardware tied at the moment and with mboot being pure C (not python) it does make unit testing harder.

**Comment by andrewleech** [comment]
Thanks @dpgeorge for these excellent improvements to the encrypted mboot work, I look forward to integrating this into my project!

**Pull request merged**
