### PR TITLE
windows: modffi

### PR DESCRIPTION
**Pull request by dmazzella**
This PR add modffi functionality to windows port

### CODE REVIEW

**Comment by stinos** [comment]
More info here: https://github.com/stinos/micropython/issues/2
Additional questions (@pfalcon @dpgeorge)
- Is there a convention for how to include external sources in uPy: submodules or just dump code?
- In the latter case: the license seems to permit modification so can we just keep LICENSE and get rid of what's not strictly needed (e.g. win64.obj/README.ctypes,...)?
- unix/ffi* tests pass after adding a bunch of possible dll names corresponding to libc/libm, a bit ugly but functional
- the unix/ffi_callback test should pass a size_t arguments to the native qsort function but we need to pass `l` type to the ffi object's func() call on 64bit windows builds, because `i` leads to a 32bit integer being used. This does magically work out on unix though, any idea why?

@dmazzella you should do something like `git rebase -i upstream/master` to get your changes rebased onto the last commit in master, and squash commits together

**Comment by pfalcon** [comment]
First of all, thanks, it's definitely a good idea to support ffi module for windows. But it all should be nice and clean of course.

> Is there a convention for how to include external sources in uPy: submodules or just dump code?

For libffi specifically, we have https://github.com/micropython/micropython/issues/2191. I'm afraid it won't do to have one libffi copy for Linux, one for Windows, and people kinda asking for baremetal too (https://github.com/micropython/micropython/issues/2894)... But we could work towards having a single patched (but upgradable!) version.

**Comment by dmazzella** [comment]
@pfalcon 
i have used the same libffi used by [cpython](https://github.com/python/cpython/tree/master/Modules/_ctypes/libffi_msvc) and [cffi](https://bitbucket.org/cffi/cffi/src/bac0dd1b86f9d0f3b6ea2ecbc77dfc8b83458a2f/c/libffi_msvc/?at=default)

> (but upgradable!) 

we can refer to this repositories for upgrade

what do you think?

**Comment by pfalcon** [comment]
No, we already have libffi submodule in the tree: https://github.com/micropython/micropython/tree/master/lib . Everyone should be using that. If needed, per #2191, the submodule can be converted to the inline subdir, and light patches to it applied. CPython and CFFI should be using upstream libffi in general. If not, that's a great shame on them - that they didn't contribute their patches upstream.

**Comment by stinos** [comment]
> we already have libffi submodule in the tree

it's worth trying that out. Looking at e.g. https://github.com/winlibs/libffi/blob/master/win32/vc14_x86/libffi/libffi.vcxproj it might just be a matter of adding the right selection of source files.

**Comment by stinos** [comment]
Update: spent some time trying to get micropython's libffi to work, this isn't going to be easy. Most problems are for example listed here: https://github.com/libffi/libffi/issues/275, note the issue is still open.

**Comment by pfalcon** [comment]
Well, revision we use for libffi isn't new and we unlikely have novelties like _Complex type there ;-). Try to get it to build with Mingw, MSVC can be done afterwards.

**Comment by stinos** [comment]
> revision we use for libffi isn't new

That is not the problem here: on the contrary, it is still 'too' new: I didn't inspect the complete log but since the last release, 3.2.1 (which works ok for msvc after a very minor patch), a bunch of changes were made, mainly to the assembly code, which made it derail to the point I wouldn't even know where to start fixing it.

Mingw build works just fine btw, so it's likely just a matter of copy-pasting the build steps from the unix Makefile

**Comment by pfalcon** [comment]
Well, potentially we can downgrade. There's nothing magic in preparing a frame of params to call a function by pointer, the value of libffi is that it comes with support for a bunch of platform, with different ABI variants if needed. That's also a risk of downgrade - if uPy+ffi will be ported to a relatively new platform requiring new libffi version.

**Comment by stinos** [comment]
I'm also not really a fan of downgrading to a couple of years back. Altenatively we could upgrade: the very last version does at least support 64bit msvc builds, and mingw, just not 32bit. I did ask the guy who recently ported the assembly to 64bit if there are plans to do the same for 32bit though, so maybe that gets added sooner or later.

@dmazzella since you wanted ffi for msvc I assume you have a usecase for it; suppose it was there but only for 64bit, does that work for you

**Comment by dmazzella** [comment]
@stinos My need is to make it work with all the architectures, only for 64 is not enough

**Comment by stinos** [comment]
It's up to @pfalcon and @dpgeorge then. Merging this just doesn't seem sane to me given we have libffi already and it's usable for unix/mingw (btw @dmazzella is that an option for you maybe?). Either mark this as 'contrib-not-for-mainline' so that future visitors know it's working and they can use your branch, or downgrade?

I'll keep an eye on libffi to see how it progresses.

**Comment by dmazzella** [comment]
I close this PR for now.

@stinos i colse also the fork on my account, if you want, merge it on your repo, than i colse it.

**Comment by pfalcon** [comment]
> I'll keep an eye on libffi to see how it progresses.

@stinos , yes, please do it, in the libffi ticket you quoted above or elsewhere. It's not good that various projects have msvc specific forks around instead of fixing it once in upstream.

**Comment by stinos** [comment]
For reference, I asked about a 32bit msvc implementation in this recent PR https://github.com/libffi/libffi/pull/291#issuecomment-301262616

**Comment by andrewleech** [comment]
@stinos, @dmazzella FYI it appears upstream x86 MSVC support has been added, at least these docs changes suggest as such: https://github.com/libffi/libffi/pull/475

What would it take to enable modffi on windows port against that now?

**Comment by stinos** [comment]
> What would it take to enable modffi on windows port against that now?

Has been a while but form my [previous commit](https://github.com/stinos/micropython/commit/ccdb416f2a74a2f54f770f9644c29ecc7a8b9a85) for this it looks like the idea is:
- add dlfcn_win32
- use recent ffi version
- add ffi_config.h for windows
- add dmazella's tests and other modifications

**Comment by stinos** [comment]
Tried this today: using x64, most recent libffi (updating current submodule to point to https://github.com/libffi/) and dlfcn_win32, all ffi calls segfault. Not immediately an idea what the problem is: something wrong in build or in uPy?

If anyone wants to look into this I can push the changes I made.

**Pull request closed without merging**
