### PR TITLE
add NUCLEO_F746ZG and NUCLEO_L476RG

### PR DESCRIPTION
**Pull request by shaoziyang**
- add NUCLEO_F746ZG
- add NUCLEO_L476RG
- modify NUCLEO_F401RE/F411RE I2C1 pin

### CODE REVIEW

**Comment by dpgeorge** [comment]
Can you please split the single commit into 3 separate commits: one for F7, one for L4, and one to update the existing F401/F411.  Thanks!

**Comment by shaoziyang** [comment]
I have pull request again, with separate commits.

**Comment by dpgeorge** [comment]
Hi @shaoziyang : support for NUCLEO L476RG has now been added in a separate commit.  If you want to have your PR merged then please separate out the changes into one commit for F746, and one to update the existing F401/F411.

**Comment by dpgeorge** [comment]
The fixes for NUCLEO F401/F411 were done in 069fc48bf60b31fca4339d26cee7b4a415b185f9

Please open a new PR if you want to add support for the F746, thanks.

**Pull request closed without merging**
