### PR TITLE
tools/mpy_ld.py: Support jumping more than 2k on armv6m architectures.

### PR DESCRIPTION
**Pull request by dpgeorge**
### Summary

Native .mpy files targetting armv6m (eg RP2040) cannot currently have more than about 2kiB of native code (between the start of the file and the init function).

This PR fixes that by using bigger jumps to jump to the init function.

### Testing

Tested with `examples/natmod/features0/` by forcing `mpy_ld.py` to always emit the long jump.  It works.

### CODE REVIEW

**Comment by dpgeorge** [comment]
This is an alternative to #12241 that uses less bytes (8) to encode the jump.

**Comment by jonnor** [comment]
This looks nice and simple. I will test it later. Probably the -2 adjustment of the offset is what I missed when I tried to implement this.

> # This function must return the same number of bytes for the encoding of the jump regardless of the value of `entry`.

As it stands, the function does not obey this property - it's either 2 or 4 bytes. As you mentioned in the review of my code, this can cause issues because the length of instructions is used else where to compute the layout. Is the plan to skip the conditional and always do the long jump (once verified)?

**Comment by dpgeorge** [comment]
> As it stands, the function does not obey this property - it's either 2 or 4 bytes

No, it always emits 8 bytes.  See the `struct.pack("<HHHH", ...)` at the end of the function.  There is no other return in the function.

**Comment by vshymanskyy** [comment]
I have run this change with wasm2mpy tests (with and without forcing long jumps) and noticed no regressions.
Coremark builds fine, but still doesn't run probably due to unknown reason.

**Comment by jonnor** [comment]
> > As it stands, the function does not obey this property - it's either 2 or 4 bytes
> 
> No, it always emits 8 bytes. See the `struct.pack("<HHHH", ...)` at the end of the function. There is no other return in the function.

You are right, of course. I do not know where my head was at.

**Comment by jonnor** [comment]
Tested with a module that exceeds the 2k limitation (before this commit, fails with `AssertionError: 3295` in `assert b_off >> 11 == 0 or b_off >> 11 == -1, b_off`). Builds successfully and looks to run ok on a RPI Pico. So I think this is good to go @dpgeorge !

**Comment by dpgeorge** [comment]
Thanks @jonnor and @vshymanskyy for testing and review!

**Pull request merged**
