### PR TITLE
Emacs style readline

### PR DESCRIPTION
**Pull request by pramasoul**
For those of us whose fingers expect emacs-style control characters in REPL readline. No yank-buffer. Cost: about 100 bytes of code and zero RAM. Easily quashed in <code>mpconfigport.h</code>.

Should <code>mpconfig.h</code> default this off? Discuss.

### CODE REVIEW

**Comment by dpgeorge** [comment]
It's definitely not "micro"... but I am sympathetic to supporting cursor movement without using cursor keys.

So adding ctrl B, F, P and N might be ok.  Ctrl D could be useful if you don't have a delete key (but then backspace or ctrl-H works well enough).  Ctrl K is probably not needed.  Why didn't you add ctrl U?

**Comment by pramasoul** [comment]
I modelled my changes on the CPython REPL behavior. From the emacs end of the egg, fingers hit Ctrl-D to kill the char _under_ the cursor rather than immediately leftward, and Ctrl-K to kill from cursor to end-of-line inclusive. And Ctrl-U in emacs introduces an optional numeric argument, so emacs fingers do Ctrl-A Ctrl-K instead. But Ctrl-U is in the CPython REPL so I've added it.

This is pointless esoterica, since real programmers use <code>vi</code>. Or [butterflies](https://xkcd.com/378/) (or in your case precision inflaton bowling). This patch makes no contribution to functionality, merely to the feeling of fidelity to CPython on initial contact. On pyboard it adds 140 bytes to the text segment.

Is this kind of patch good for micropython? Or does it take it further from your vision of what it should be?

**Comment by dpgeorge** [comment]
Note that you can save some bytes by using the existing implementation of "delete".

> I modelled my changes on the CPython REPL behavior.

That behaviour comes from GNU readline, and in fact all programs that use GNU readline will have these emacs-like bindings.

> Is this kind of patch good for micropython?

This kind of patch is about usability and is not directly related to the core implementation (you don't need the REPL to run scripts) so there is some leeway here, certainly up for discussion.

I understand that there are a large number of users who are very familiar with these key bindings, and such users find it frustrating when the bindings don't exist because typing them is second nature.  Same thing can be said about vi bindings.  Well, we won't support vi bindings because that requires much more complicated modal input.

Power users (who benefit from these bindings) are going to be using uPy and uPy should be kind to such users, so the REPL doesn't feel clunky and slow to interact with.  Emacs users will know these bindings straight away, and vi users can easily learn them as a replacement for hjkl, etc (fingers still stay close to the home row).  That would be one argument for supporting them.

Another argument is that if we have tab completion (and soon smart indent via #1368) then surely we can do with some simple (and relatively cheap) bindings for cursor movement.

Yet another argument is that it would be good to provide an alternative to the normal cursor keys and their escape sequences, in case on some machine/terminal the escape codes are messed up and the fallback would be to use ctrl-B/F/P/N/D (which should work in all cases).

**Comment by pramasoul** [comment]
> Note that you can save some bytes by using the existing implementation of "delete".
But for this detail: Ctrl-D deletes the character _under_ the cursor. Delete acts to it's left.

I'll take a pass looking for savings.

**Comment by dpgeorge** [comment]
There is backspace and delete implementations, separate.

**Comment by pfalcon** [comment]
My 2 cents: I'm also sympathetic to this patch, but think it should be disabled by default (like, default default; if some port, even pyboard, wants it on, ok).

**Comment by dpgeorge** [comment]
Reworked and merged in 7d588b0c7c9698d23b1e5e7b54e0e2094ad8f464.

Dix to get REPL tests working merged in 3dd0b69e467fd89e5113dbc5ee43f33282a66c91.

Thanks @pramasoul.  But next time can you please open separate PRs for distinct features / fixes (which in this case would be emacs keys in one, and run-tests fixes in another).

**Comment by pfalcon** [comment]
What about this:

>  but think it should be disabled by default 

?

**Comment by dpgeorge** [comment]
Oops, fixed in d8a7f8bff2978a158203fec31f270b616f444047.

**Comment by pfalcon** [comment]
Thanks!

**Pull request closed without merging**
