### PR TITLE
Add uPy errno constants and uerrno module

### PR DESCRIPTION
**Pull request by dpgeorge**
See #976 for background.

There are 2 parts to this addition:
- py/mperrno.h with uPy specific errno constants, named like MP_EAGAIN (basic ones taken from linux header file)
- extmod/moduerrno.c implementing the (u)errno module (only a few of the constants are included for now, we can add them as needed)

A few points to think about:
- I put mperrno.h in py/ because it's pretty much part of the core (will be used by stream.h, for example)
- should the module be uerrno or just errno? it implements all of the CPython errno module so arguably can be just errno
- should mod(u)errno.c go in py/ or extmod/? it's not really core so that's why I put it in extmod/ to start with
- I implemented the errorcode dictionary to do lookups of errno numbers, since I think this is very useful (and doesn't need any extra qstrs, just ROM for the table array)
- baremetal ports can use MP_Exx consts directly, but for unix (and windows?) we will need a way to map errnos returned from system calls to uPy errnos; such a thing is not included in this PR

### CODE REVIEW

**Comment by pfalcon** [comment]
> it implements all of the CPython errno module so arguably can be just errno

But above you wrote "only a few of the constants are included for now". I don't think it will be soon if ever that we include all errors in there, so let it be uerrno.

**Comment by pfalcon** [comment]
> should mod(u)errno.c go in py/ or extmod/?

My idea was to use it (via adhoc check) when printing OSError exceptions, what makes it py/.

**Comment by pfalcon** [comment]
> I implemented the errorcode dictionary to do lookups of errno numbers, since I think this is very useful (and doesn't need any extra qstrs, just ROM for the table array)

Well, that's a bit surprising. It doesn't need extra qstrs, it has whole extra reverse dictionary! My idea for OSError printing was to do reverse lookup in an adhoc way. Well, it's hard to argue e.g. "leave for later" if it's in standard Python, but I see a config option to disable it (not necessarily now, later).

**Comment by pfalcon** [comment]
With all that, it's still unclear what to do with OS-based systems which provide their own error value mapping. Well, there's little to do but to define MP_E* to underlying E* (i.e. raw numeric values will be used only on baremetal ports).

**Comment by dpgeorge** [comment]
> But above you wrote "only a few of the constants are included for now". I don't think it will be soon if ever that we include all errors in there, so let it be uerrno.

CPython docs state: "symbols that are not used on the current platform are not defined by the module".  So we'd actually have a conforming errno module no matter what we put in there (as long as the errorcode reverse dict exists).  The question is then: will people want to add errnos that are not already built in?

> With all that, it's still unclear what to do with OS-based systems which provide their own error value mapping.

See my final point in the first post.  My idea was to proide a lookup table mapping OS -> uPy errnos.  Alternative is, as you suggest, to make mperrno.h define the MP_Exxx values to the OS values.  I guess if we have the errorcode dict and print the strings instead of numbers then it doesn't really matter what the underlying value is.

**Comment by pfalcon** [comment]
> The question is then: will people want to add errnos that are not already built in?

Sure, Linux users want to have access to all errno's it has (handled by making errno.py).

> My idea was to proide a lookup table mapping OS -> uPy errnos. 

I.e. we really want to create MicroPython kingdom? ;-) I think that's premature and requires overhead (mapping is either slow or requires a small bunch of memory). It's also paradigmatically wrong (depending on the paradigm of course), e.g. may complicate/confuse FFI with native system.

**Comment by dpgeorge** [comment]
Ok, I'll merge this with the following changes:

- move moduerrno.c from extmod/ to py/
- make mperrno.h use configurable numeric values, in the sense that it'll either include the system errno.h and define MP_Exxx to those, or just define MP_Exxx to the fixed constants it currently has (for baremetal targets)

**Comment by dpgeorge** [comment]
Merged, see 3f56fd64b86b581780464a13653f9bea1e20dbba and 596a3feb8fd3cfbaa899c23b010f79a7088863fb.

**Comment by pfalcon** [comment]
@dpgeorge : Looks good, thanks! Any specific reason you didn't enable internal errnos for esp8266?

**Comment by dpgeorge** [comment]
> Any specific reason you didn't enable internal errnos for esp8266?

Because extmod/modlwip.c first needs to be converted to use MP_Exxx symbols.  Otherwise there'll be a mismatch in numbers.

I can change modlwip.c, if you agree that's the right thing to do?

**Comment by pfalcon** [comment]
Well, we decided to switch the entire codebase to MP_E*, the fallback path is that they're defined to underlying system's. So yes, that's the right thing to do, and I don't see any issues, unless I miss something.

**Comment by dpgeorge** [comment]
@pfalcon BTW, your idea to make nicer OSError exceptions is a good one.  There are 2 ways I can think to do it:

- provide a function mp_obj_new_exception_os_error(int errno) that does it [or even provide an nlr_raise_os_error(int errno)]
- hack mp_obj_new_exception_arg1 to check if the type is OSError and the arg is an int, and if so convert it to a string

**Comment by dpgeorge** [comment]
modlwip converted in 0055457b5fb3e4d941503fac1706256a2f2f2dc7.  esp port now uses internal errnos in 0d6d315ba6c36cc493c844f69a898469bf231abc.

**Comment by dpgeorge** [comment]
> hack mp_obj_new_exception_arg1 to check if the type is OSError and the arg is an int, and if so convert it to a string

I implemented this in d45e5f8c357d13e66aeac644e2b5ead8c734025f.  Works well, but can be changed/adapted if needed.

**Comment by pfalcon** [comment]
OMG, no! OSError's argument must be an int, and moreover it must be a valid errno *. That's part of public interface. Please revert, the way to do handle it is in mp_obj_exception_print().

* (or some distinguishable from them value, e.g. negative number - as a temporary (long-time) hack).

**Comment by dpgeorge** [comment]
> SError's argument must be an int, and moreover it must be a valid errno *. That's part of public interface.

I see.  CPython has the second arg as a string, so we can do that instead and then there's no hack in the printing (and still conforms with the public interface).  Eg: OSError(1, 'EPERM')

**Comment by pfalcon** [comment]
If they have that, then perhaps we can use that for additional description where it's warranted (i.e. where currently string is passed to OSError, what is wrong). But OSError's should be very lightweight by default, as they're expected to occur (in multiples) with normal application flow.

**Comment by dpgeorge** [comment]
> But OSError's should be very lightweight by default, as they're expected to occur (in multiples) with normal application flow.

Even with a single argument (the errno) the constructor currntly allocates a tuple to hold it, and hence uses a GC block.  So it can take 2 arguments without using any more RAM than it currently does.  Ie, OSError(1, 'EPERM') would use the same memory as OSError(1).

**Comment by pfalcon** [comment]
Tuple of 2 elements always takes more space than tuple of 1 elements, though in particular cases memory allocation may mask that. Let's not depend on that in design.

And note that CPython actually does quite a lot of magic with OSError exception (on whatever phase):

~~~
>>> OSError(2, "foo")
FileNotFoundError(2, 'foo')

>>> open("fsdfsd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'fsdfsd'
~~~

**Comment by dpgeorge** [comment]
> though in particular cases memory allocation may mask that. Let's not depend on that in design.

The code already does depend on it, to a large extent.  Object sizes are tuned to fit in 4 words.

Anyway, we can handle it in mp_obj_exception_print().  Should it print something like CPython, eg
```
OSError: [Errno 1] EPERM
```
Or simply:
```
OSError: EPERM
```
?  I'd go for the former, so you can see the number as well as the string.

**Comment by pfalcon** [comment]
> OSError: [Errno 1] EPERM

Yep, that was my idea too.

**Comment by dpgeorge** [comment]
Done in 9a9249964155f333131bbd728ffc755e80dc68a2.  To test use:
```
>>> import sys
>>> sys.print_exception(OSError())
OSError: 
>>> sys.print_exception(OSError(1))
OSError: [Errno 1] EPERM
>>> sys.print_exception(OSError(2))
OSError: [Errno 2] ENOENT
>>> sys.print_exception(OSError(3))
OSError: 3
```

**Comment by pfalcon** [comment]
Tested on linux-armv8, works great, thanks!

**Comment by dpgeorge** [comment]
> My idea for OSError printing was to do reverse lookup in an adhoc way. Well, it's hard to argue e.g. "leave for later" if it's in standard Python, but I see a config option to disable it (not necessarily now, later).

Such a config option was added in f563406d2e342be1535592f80680c510f9aade9a

And in b1b090255c5156987b36711e929544546603029c the list of error codes was made configurable, with a default provided.

**Pull request merged**
