### PR TITLE
mimxrt: Fix an error introduced with commit 297892c for UART baud rate change.

### PR DESCRIPTION
**Pull request by robert-hh**
There is a single UART clock for all devices, so switching it will affect all devices used at that time. Therefore, this PR removes switching the UART clock and sets it to 40Mhz, which covers the range down to <200 baud and has an acceptable precision at 921600 and 3000000 baud.

### CODE REVIEW

**Comment by robert-hh** [comment]
@dpgeorge Sorry for making some chaos. Sitting on the sofa, I  noticed that UART clock switching on-the-fly affects all UARTs currently used. The MIMXRT101x series has a single clock pre-scaler for all UARTs. The MIMXRT117x has individual clock pre-scalers. So I switched back to have a fixed UART clock art 40MHz instead of 80Mhz, as it was before. With 40Mhz 300 baud can still be supported, and 921600 baud is still in the specs. Only the old Teletypes at 50 and 75 baud are not. The drawback of this change is, that all clock_config.c files had to be touched.
Tested with i.MX RT 1010, 1021, 1052 and 1062 boards at 300 and 921600 baud.

**Comment by iabdalkader** [comment]
Can we still get `3000000` baud with this ? That's the CYW43's firmware/secondary baudrate.

**Comment by robert-hh** [comment]
Surprisingly 3 MBit works. The bit time is 325ns instead of 333, which is 2.5% off. But that is just within the specs of max. 3% deviation. Even 80Mhz clock you cannot match 3MBit perfectly, only the error is smaller. If you have a choice, better use 2_500_000 or 4_000_000 Mbit. Than  you have precise timing.

**Comment by iabdalkader** [comment]
Yes I can confirm 3Mbits works for 117x with the current master (didn't test this PR).

**Comment by robert-hh** [comment]
Using 80MHz/3 works as well for the MIMXRT10xx boards. The timing deviation for 3Mbit is small, but no support any more for 4MBit. 2Mbit "just" works, 1MBit is fine, 921600 as well. The lowest rate is then 150 Baud, which is not very common.

**Comment by robert-hh** [comment]
@dpgeorge Damien, would you please consider to merge this fix for a bug I made, even if no-one but me seems to have been hit by it. At least no one complained.

**Comment by dpgeorge** [comment]
Thanks, this looks fine.

Clock trees can be complicated!

**Comment by robert-hh** [comment]
Thanks. After staring at the clock tree for a while, I kind of understand it. The clock tree of the MIMXRT11xx series is larger, but much more regular.

**Comment by iabdalkader** [comment]
After merging this back in our fork, sadly the BT stopped working at 3Mbits. It only works if I revert the clock change, or reduce firmware download baudrate to 921600 or 2.5Mbits.

**Comment by robert-hh** [comment]
I just measured the baud rate at a MIMXRT1176 board, and at 3 MBaud setting I get 2.97 MBaud, which is about 1% off. That's clearly in the acceptable range.
With a Teensy 4.1, I get 3.07 MBaud, when set to 3 MBaud, which is the expected deviation of 2.5%. 2.5 Mbaud and 4 MBaud are precisely met.

**Comment by iabdalkader** [comment]
> which is the expected deviation of 2.

It seems the CYW43 is less tolerant to baudrate errors than other things. Note it works with the 117x I tested it before.

**Comment by robert-hh** [comment]
Reverting the above commit does not change the UART baud rate at the MIMXRT1176. It changes it for the Teensy to an error of 1.25%.

**Comment by iabdalkader** [comment]
> Edit: Actually this PR does not affect the MIMXRT1176 clock setting at all.

Yes, the CYW43 worked with 117x when I tested it with this PR back then. The 1060 seems to work fine at 2.5Mbits. It seems for the CYW43 the baudrate must be within ~1%

**Comment by robert-hh** [comment]
At the MIMXRT1176 the base clock for UART is 74.25MHz. That results in the seen 1% below 3MBd. The same for 2.5MBd and 4 MBd. Maybe the CYW43 is slightly above and has a smaller error at 2.5MBd. Do you have access to the CYW43 TX pin to measure the actual baud rate it uses?

**Comment by iabdalkader** [comment]
Maybe @kwagyeman can help test it ? For now I just reduced the baudrate to 2.5Mbits to fix the issue.

**Comment by kwagyeman** [comment]
I can't probe the signals. They are not on exposed pins. I could scrape off the solder mask on a via to do so. But, I risk board damage.

**Pull request merged**
