### PR TITLE
neopixel-low: Improvements to neopixel and docs

### PR DESCRIPTION
**Pull request by maludwig**
My neopixels were glitchy, and it turned out to be a timing issue, the previous code didn't account for register overflow, and didn't respect the 4 different state values. I've improved the C code for the neopixels to support the WS2811, as well as the more modern WS2812B and WS2812S modules timing. I've also opened up the tight timing function for raw calls from python, which frees up RAM held by the IRAM_ATTR flag, by allowing the non-critical code to be paged out.

I've also fixed the relevant bits of the docs where neopixels are mentioned, and a few bits which tripped me up on the initial install.

### CODE REVIEW

**Comment by maludwig** [comment]
So...what happens now? Do I need to tell someone about this PR? Do I need to do a thing?

**Comment by mattytrentini** [comment]
The code looks in good shape - and you've clearly taken some care with the timings - though I haven't yet had a chance to try it out.

However, I've been investigating a different method - using the [RMT module](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/rmt.html). I've been working to expose the RMT tx capabilities and believe that this would be a better approach than relying on timing. RMT is independent of the processor and highly accurate - and it should be quite straightforward to create a NeoPixel driver _completely in Python_ using the RMT to send the pulses. You can see the start of the work on [my fork on the esp_rmt branch](https://github.com/mattytrentini/micropython/blob/esp32_rmt/ports/esp32/esp32_rmt.c). It's worth noting that this isn't a unique idea: FastLED have switched their ESP32 implementation to using RMT too - and it [seems successful](https://blog.ja-ke.tech/2019/06/02/neopixel-performance.html).

Anyway, I like your work but I'm hoping that using RMT might be a better way to implement NeoPixel driving.

**Comment by maludwig** [comment]
Nice @mattytrentini , I'll check your stuff out!

**Comment by maludwig** [comment]
@mattytrentini , so I'm looking through things, and I think while this may work for the ESP32, which would be great, I'd still like to keep it functional with the pure-timing stuff, because I'd like to also put this into the other ports, if this one gets approved.

I'd like to keep it, shall we say, portable.

https://www.youtube.com/watch?v=7uW47jWLMiY

**Comment by dpgeorge** [comment]
Thanks for the contribution.  If it's possible to do proper neopixel timing in software that would be convenient.  Using the RMT could also be an option, and having both ways to do it (software and RMT) would be ideal if they both work correctly.

> because I'd like to also put this into the other ports

+1 to have a portable implementation.

I was actually working on a similar thing for stm32 with the following signature:
```python
pixelbitstream(pin, timing_ns, buf)
```
Where `timing_ns` is a 4-tuple of nanosecond timing values, 0-high, 0-low, 1-high, 1-low.  Typical values would be `(450, 800, 850, 400)` for standard neopixel, and can be changed for other variants.

@maludwig do you think you can modify your implementation to take in this 4-tuple of nanosecond timing values?

**Comment by maludwig** [comment]
Hey @dpgeorge , I'd be more than happy to have it accept a 4-tuple of timing values, but I don't have an STM32 to test it with. I'd also like to leave the existing CPU tick implementation to allow for the finest grained control.

I think that would be better too, because then we could put the timing into the Python side and then future devs wouldn't need to brush up on C++ to add a new timing spec.

I also want to add the concept of "double-buffering", like, VSync, so that a FreeRTOS task can run concurrent to the main Python task, so that your Python code can put stuff into buffer B while concurrently, the neopixels are streaming buffer A, and then put stuff into buffer A when the other core is streaming our buffer B to the pixels. But maybe that's a future commit.

**Comment by dpgeorge** [comment]
See #5294 for an stm32 implementation.

**Comment by maludwig** [comment]
Looks like our two implementations are compatible. Same high level view. You've made yours in a bit of a different way. I've maintained backwards compatibility with the old ways, but your code is smaller and looks cleaner, and is inside machine, where mine is inside neopixel.

I don't have an STM to test with or I'd help you merge yours.

My only suggestion for yours, would be to make the pixelbitstream be a part of neopixel, rather than part of machine. I think of machine like, things specific to that hardware.

I'll leave comments on your PR. Got anything more you'd like me to do before we merge?

**Comment by maludwig** [comment]
@dpgeorge I've added pixelbitstream for you, kept the tick-based version too, but the pixelbitstream implementation will correct for CPU freq for those who want to just use timing.

I've also wiped out my previous fixes to the docs, since I think it was you actually who added support for the latest ESP-IDF.

Can we merge this now?

**Comment by maludwig** [comment]
@mattytrentini I just found this, thought you might find it interesting:
https://github.com/espressif/esp-idf/tree/f91080637/examples/peripherals/rmt/led_strip

You've probably already seen it, for I thought, just in case!

**Comment by maludwig** [comment]
@dpgeorge Should I be losing hope on merging this guy?

**Comment by mattytrentini** [comment]
@dpgeorge How's this looking to you? Looks good to me and seems to take in the tuple as you requested...

**Comment by jimmo** [comment]
@maludwig Sorry about the delay on this PR. For v1.17 we merged the bitstream feature mentioned in https://github.com/micropython/micropython/pull/5117#issuecomment-536431342 for stm32/esp32/esp8266 and in the process of adding this to ESP32 I fixed the same overflow bug as this PR and made the timing customisable from Python. I have not been able to see any glitching with this driver. Subsequently, bitstream has been added for more ports.

Further to this, last week I implemented an RMT driver to replace the bit banging implementation and so far sounds like it further improves reliability -- see https://github.com/micropython/micropython/pull/7985

**Pull request closed without merging**
