### PR TITLE
New port for Infineon PSoC6 microcontrollers

### PR DESCRIPTION
**Pull request by jaenrig-ifx**
Hi MicroPython code owners,

The current contribution is an ongoing development of the PSoC6 port:
- Initial board CY8CPROTO-062-4343W
- Enabled machine classes : I2C, GPIO, RTC.
- Enabled ITF STA of network.WLAN (Using LwIP and mbedTLS Infineon dependencies)
- All relevant docs for this port and current state

In upcoming contributions we plan to:
- Remove all external dependencies and content imported from the ModusToolbox Infineon SDK. (Many of these files are a bit trashy and irrelevant to the MicroPython projects :))
- machine, network and ble modules completion

Minor changes are done outside the `ports/psoc6` itself, or any dedicated sections in` tools/` and` test/`.
Looking forward to hear your feedback :) 

Thanks!

### CODE REVIEW

**Comment by mattytrentini** [comment]
There's a huge amount of effort here and it's looking promising! Still seems under active development though; is it a good time for a review?

**Comment by jaenrig-ifx** [comment]
Hi @mattytrentini,

Thanks for your comment and support!
The complete port is work in progress. But we will stop making changes to this branch, and add further contribution in new PRs.

Any recommendation for such big contribution like a new port?

To make it a little bit less overwhelming, be aware that many of boards/CYC8PROTO-062-4343W files currently hardcoded for convenience, will be removed as soon as we have a proper integration with the ModusToolbox PSoC6 SDK, and will become an external dependency.

We could also wait a bit and have more completion (and some cleanup) but the intention is to make what is there available already to the community, and get feedback to avoid any wrongdoing in upcoming work 😃.

**Comment by mattytrentini** [comment]
Hi @jaenrig-ifx, 

It's great to submit a PR - especially a large one like this - early! We just need to figure out how best to manage it, because there is a lot to review. 

It might be helpful if you could provide a little guidance of the areas you feel are most stable so we can start there? Or if there are parts where you'd particularly like feedback (maybe some implementation that's quite different to other ports?) that would be useful too.

The main thing I'd like to avoid is folks spending time reviewing code that's likely to change. :)

**Comment by jaenrig-ifx** [comment]
Hi @mattytrentini,

Agree :) The parts that are not worth a thorough review right now:
- ports/psoc6/boards/** -> But the mpconfigboard.mk and mpconfigboard.h most will be refactored removing all third party and importing by using the PSoC6 SDK.
- ports/psoc6/modules/network -> This is still very preliminary work in progress.

The rest is quite complete, beside some improvements or secondary missing functionality. Little has been changed outside the port or its corresponding section in /tests, /tools or /docs. But those changes (some metafiles and common scripts) which affect the rest of the project would be of extra consideration for review I would say.

Does this help already?

We have put quite some care in fulfilling all the conventions and consciously get all green in the quality gates , but maybe from a more high level source tree, overall project architecture, convention in modules implementation... a more expert contributor have additional considerations, guidelines or requirements we are yet unaware.

Thanks a lot!

**Comment by projectgus** [comment]
This is an automated heads-up that we've just merged a Pull Request
that removes the STATIC macro from MicroPython's C API.

See https://github.com/micropython/micropython/pull/13763

A search suggests this PR might apply the STATIC macro to some C code. If it
does, then next time you rebase the PR (or merge from master) then you should
please replace all the `STATIC` keywords with `static`.

Although this is an automated message, feel free to @-reply to me directly if
you have any questions about this.

**Pull request closed without merging**
