### PR TITLE
extmod, lib: Move all 3rd party library code to lib/

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR moves the `re1.5`, `uzlib` and `crypto-algorithms` from `extmod/` to `lib/`.

The eventual goal I have in mind is to move to a situation where all 3rd-party code lives in the `lib/` or `drivers/` directories, and all other directories in this repo contain code original to this project.  It's also possible to have original code in `lib/` and `drivers/`.  But `py/` and `extmod/`, and to a large extent `ports/*/` should contain only original code.  (Also `tools/` has some 3rd-party code.)

That gives a clear distinction of what code goes where, and helps to separate licenses/copyright.

With this PR applied, everything in `extmod/` will now be original source (and `py/` is already that way).

Please comment/discuss if you think there's a better solution to this, if it's not worth the noise, etc.

### CODE REVIEW

**Comment by MrSurly** [comment]
This is just a directory structure update, right?  It doesn't remove any of the "core" libraries from the MP build?

**Comment by dpgeorge** [comment]
> This is just a directory structure update, right? It doesn't remove any of the "core" libraries from the MP build?

That is correct, it's a simple `git mv extmod/uzlib lib/` operation (etc), plus appropriate edits to `#include` directives now that paths have changed.

**Comment by stinos** [comment]
As an addition perhaps add the explanation to the README or similar so it's documented somewhere what the intent is? I think the noise added (in the end just a couple of commits amongst the thousands of others) is well worth it, having all 3rd party code spearate is just better on most fronts.

The only small surprise now is that I seem to have been exposed to many projects having their 3rd party code in directories with names like _3rdparty_ or _ext_ or _deps_, whereas here the directory named _extmod_ also sounds like 'external' but actually has what I'd consider internal code. But that's minor, just need to realize *extmod* roughly means 'non-builtin modules which are sometimes implemented realying on external code'.

**Comment by dpgeorge** [comment]
> As an addition perhaps add the explanation to the README or similar so it's documented somewhere what the intent is?

Will do.

> The only small surprise now is that I seem to have been exposed to many projects having their 3rd party code in directories with names like _3rdparty_ or _ext_ or _deps_, whereas here the directory named _extmod_ also sounds like 'external' but actually has what I'd consider internal code.

Yeah, but renaming `extmod/` is really too hard to do now.

But, `lib/` will contain both 3rd-party and internal code (eg `mp-readline`, `utils`, `netutils`, `timeutils`).... so may it is worth considering separating those?  Eg a new `3rdparty` directory??

Well, the main aim with this PR is to move "library" code out of extmod, because code like crypto-algorithms and uzlib are not tied purely to extmod modules (eg mboot uses these libraries as pure C libraries).

**Comment by stinos** [comment]
> so may it is worth considering separating those? Eg a new 3rdparty directory??

Well if things are being moved anyway, it's indeed maybe not bad to move them like that right away. I think it would be nice to have a clear distinction between code of different origin. Also because of the licensing as you mentioned. It doesn't seem very hard, maybe chosing the name for the directory will be the hardest part :)
But would be good to hear others' thoughts on this.

**Comment by dpgeorge** [comment]
I'd like to move forward with this PR, merging it pretty much as-is.  Eventually `lib/` will be where all 3rd-party code goes, and existing code there like timeutils will be moved elsewhere (eg support/ or shared/ or common/).

**Comment by stinos** [comment]
Is there anything holding back moving timeutils etc now already?

**Comment by dpgeorge** [comment]
> Is there anything holding back moving timeutils etc now already?

Only what to call the destination directory :)  So if you have any ideas for that, please say.

Also whether to keep the layout of the existing dirs/files or to reorganise them.  The files to move out of `lib/` would be:
```
$ tree embed libc memzip mp-readline netutils timeutils upytesthelper utils
embed
├── abort_.c
└── __errno.c
libc
└── string0.c
memzip
├── import.c
├── lexermemzip.c
├── make-memzip.py
├── memzip.c
├── memzip.h
└── README.md
mp-readline
├── readline.c
└── readline.h
netutils
├── dhcpserver.c
├── dhcpserver.h
├── netutils.c
├── netutils.h
└── trace.c
timeutils
├── timeutils.c
└── timeutils.h
upytesthelper
├── upytesthelper.c
└── upytesthelper.h
utils
├── gchelper_generic.c
├── gchelper.h
├── gchelper_m0.s
├── gchelper_m3.s
├── gchelper_native.c
├── interrupt_char.c
├── interrupt_char.h
├── mpirq.c
├── mpirq.h
├── printf.c
├── pyexec.c
├── pyexec.h
├── semihosting.c
├── semihosting.h
├── stdout_helpers.c
└── sys_stdio_mphal.c
```
That layout is not too bad but I can think of some improvements:
- move `utils/printf.c` to `libc/printf.c`
- move `embed/*` to `utils/`
- rename `utils/` to `runtime/` (utils is very generic)
- rename `mp-readline/` to just `readline/`

**Comment by dlech** [comment]
`shared/` or `common/` sound good to me.

**Comment by dpgeorge** [comment]
One blocker to moving `extmod/crypto-algorithms/` to `lib/crypto-algorithms/` is that axtls has a hard-coded:
```
#include "../../../extmod/crypto-algorithms/sha256.h"
```
So would need to update the axtls submodule first.

**Comment by stinos** [comment]
> shared/ or common/ sound good to me.

+1 for `shared`, it is simple and clear enough

> move utils/printf.c to libc/printf.c
> move embed/* to utils/
> rename utils/ to runtime/ (utils is very generic)
> rename mp-readline/ to just readline/

+1 on all of these, makes sense.

**Comment by jimmo** [comment]
+1 on `shared` and the suggested moves.

**Comment by dpgeorge** [comment]
This is now working.

**Comment by dpgeorge** [comment]
See #7515 for moving files to `shared/`.

**Pull request merged**
