### PR TITLE
docs/esp8266: Add more NeoPixel examples

### PR DESCRIPTION
**Pull request by mcauser**

### CODE REVIEW

**Comment by pfalcon** [comment]
@mcauser : Thanks for your contribution, but the purpose of both quickstart and tutorial is not to dump loads of code on users, but to show how to use things in quick/simple ways respectively.

**Comment by mcauser** [comment]
@pfalcon Thanks for the feedback. I am not sure where detailed examples of built it libraries _should_ go.

Putting examples in the code seems like unnecessary bloat.

Putting examples in the Quick Ref would clutter and overload new users. Agreed.

The tutorial seems like the right place. But if you want to keep that nice and light too, perhaps an extended tutorial, or the ability to hide detailed code behind Show More links.

If it were a separate package, the detailed examples would most likely live in the package repo on GitHub.

Worst case, we scatter the info amongst various blog and forum posts.

**Comment by mcauser** [comment]
Also, the `Quick reference for the ESP8266` page in the documentation could be improved by linking to relevant tutorial or library pages.

**Comment by pfalcon** [comment]
> Worst case, we scatter the info amongst various blog and forum posts.

Why is this "worst case"? I don't understand where this idea of centralization comes from and in what it's grounded. MicroPython is offspring of Python community and follows its best practices. 70K modules at https://pypi.python.org/pypi - they aren't and can't be part of (C)Python and can't be managed personally by Guide van Rossum, the Python creator. They belong to the wide, distributed Python community.

That said, if you really think that you come up with an example which will be beneficial to almost every other MicroPython user, we have examples/ dir in the source tree.

**Comment by pfalcon** [comment]
> Also, the Quick reference for the ESP8266 page in the documentation could be improved by linking to relevant tutorial or library pages.

Not only "Quick reference for the ESP8266", but the documentation overall may benefit from that. If you're proficient with RST format, we'd appreciate your help with that. Please start with simple, easy to review patches, preferrably tackling one things per patch (like, no change one line, but add cross-links or fix formatting/typos in one file). Thanks!

**Pull request closed without merging**
