### PR TITLE
esp8266: fix bugs in esp8266/modnetwork.c when connecting to ap

### PR DESCRIPTION
**Pull request by puuu**
This patches should fix the bugs discussed in #3061 .

### CODE REVIEW

**Comment by dpgeorge** [comment]
Since the station_config struct is initialised to all zeros at the beginning of the function there's no need to store the empty string in the case that the password is not given.  You can just put the memcpy for the password into the `if (n_args > 2)` block.

**Comment by puuu** [comment]
OK, I see. Changed it that way.

Tested it successfully by connecting to an unprotected and a WPA2 encrypted network.

**Comment by dpgeorge** [comment]
Thanks, merged in 4b235800a4ebba19a98bba50a5a98d2c407d99a7

**Comment by pfalcon** [comment]
@puuu : Thanks for being around and fixing it!

**Pull request closed without merging**
