### PR TITLE
windows: Add an icon for Windows.

### PR DESCRIPTION
**Pull request by braydenm303**
But not actually embed the icon in the executable, since
that would add a precious 7KB to the executable's size.

The icon includes optimized variants at 16px, 24px, and 32px.

Signed-off-by: Brayden Morris <braydenm303@gmail.com>

### CODE REVIEW

**Comment by stinos** [comment]
.ico files are generally usable, not just by the windows port, so shouldn't this be in another directory?

**Comment by braydenm303** [comment]
Windows uses `.ico`, and macOS uses `.icns`, while linuxes usually use `.png` or `.svg`.

I'll make a more interoperable set of icons based on an `.svg`, and also commit that for review.

**Comment by stinos** [comment]
> uses

Maybe I should first have asked ask: for what :) You mean using them as an icon for an executable or file format or more general puprpose? Does that make sense to add it without actually using them and without instructions of how that could be done?

**Comment by jimmo** [comment]
Closing due to inactivity. @braydenm303 I think @stinos makes a good point here, the ico file would be worthwhile if you want to add it as an icon resource to micropython.exe (which would be good), but probably not necessary to add just on its own.

**Pull request closed without merging**
