### PR TITLE
github/workflows: Cancel when branch is updated.

### PR DESCRIPTION
**Pull request by dlech**
This adds a concurrency section to all github workflows to cancel any in progress workflow when a branch is updated. This should cancel any ongoing or queued workflows, e.g. when a pull request is updated.

### CODE REVIEW

**Comment by dlech** [comment]
I did a force push to this branch and it appears to work (jobs canceled). 

Docs for reference: https://docs.github.com/en/actions/using-jobs/using-concurrency

**Comment by dlech** [comment]
It would be nice if we could do something like this with appveyor builds to as well because we can get quite a backlog there waiting for builds we know are going to fail (or stop using appveyor altogether and move those builds to github actions?).

**Comment by dpgeorge** [comment]
Thanks, this looks good.

Is there a way to include other files in yaml?  Just so we don't have to duplicate so much.

> It would be nice if we could do something like this with appveyor builds to as well because we can get quite a backlog there waiting for builds we know are going to fail - every force push adds 20 minutes of wait time (or stop using appveyor altogether and move those builds to github actions?).

It is a bit annoying how appveyor always runs (even when it doesn't need to) and takes the longest of all CI.  It would be nice to switch to github actions for it, if that's possible.

**Comment by dlech** [comment]
> Is there a way to include other files in yaml? Just so we don't have to duplicate so much.

There is some possibility to reuse workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows

But it looks like it just applies to jobs, so I don't think it could be used for this particular case.

**Pull request merged**
