### PR TITLE
ESP8266: Improved time keeping

### PR DESCRIPTION
**Pull request by Adam5Wu**
1. Implement access to non-RTC system clock, which is more stable than built-in RTC;
2. Modified general time function to use system clock instead of RTC;
3. Implement more accurate code for tracking RTC clock.

### CODE REVIEW

**Comment by Adam5Wu** [comment]
New commits simplifies system clock time keeping, restores RTC memory usage to match that of the pre-PR implementation; properly restores clock upon reset:
- Soft reset will have minimal impact to either RTC clock or system clock (RTC clock is used to recover system clock)
- External hard reset will result in loss of some seconds after last RTC reading (affects both RTC and system clock), but it's better than nothing. :D

**Comment by pfalcon** [comment]
Thanks, but please follow https://github.com/micropython/micropython/blob/master/CONTRIBUTING.md (format of commit messages, no merge commits in pull requests, etc.)

**Comment by Adam5Wu** [comment]
Sorry about that! :)
No more commits unless discussed and request in this PR.

**Comment by Adam5Wu** [comment]
Actually, the current branch is a bit messy. Let me redo the branch and submit a new PR.

**Comment by Adam5Wu** [comment]
New PR: #2728

**Comment by pacmac** [comment]
Is it possible to resurrect this modification as what appears to be a solution to the horrendously bad accuracy of the 8266 deepsleep timer ?

**Comment by pfalcon** [comment]
Sure, this is still on todo - someone will need to re-research the matter and re-make the patch in clean way.

**Comment by maharjanmilan** [comment]
can we merge this?

**Pull request closed without merging**
