### PR TITLE
wipy: Fixed some typos in the tutorial doc.

### PR DESCRIPTION
**Pull request by dhylands**

### CODE REVIEW

**Comment by dhylands** [comment]
The build failure seems to be infrastructure related. The same ```make -C qemu-arm test``` works fine locally.

**Comment by pfalcon** [comment]
qemu-arm tests fail non-deterministically regularly. There's no need to spoil PR with empty commits, you should be able to log in to Travis CI and re-trigger a build.

**Comment by dhylands** [comment]
Only people with write access to micropython repository are allowed to retrigger a build. I was planning on squashing the commit once I confirmed that it rebuilt.

**Comment by danicampora** [comment]
Merged in https://github.com/micropython/micropython/commit/f3308daa6fb74bc42f764b505d738a82bca8b508, thanks :-)

**Pull request closed without merging**
