### PR TITLE
Nordic port for nrf51822, nrf52832 and nrf52840

### PR DESCRIPTION
**Pull request by tralamazza**
This is an initial port for the nRF series including nrf51822, nrf52832 and nrf52840 support.

Modules currently supported:
- UART
- LED
- Pin
- ADC
- PWM (nrf52)
- SPI
- I2C

Additional micropython modules:
- music - backport of micro:bit music module for both nrf51 and nrf52 (+ ticker and softpwm drivers)
- Temperature
- RTC (Real time counter - low-power counter)
- ubluepy - Bluetooth LE module using existing python library, [bluepy](http://ianharvey.github.io/bluepy-doc/index.html), as API template. (Extended to also act as a peripheral role)

Additional features:
- Bluetooth LE REPL

Current target boards supported by nrf51822:
- BBC micro:bit
- pca10000 (dongle)
- pca10001 (dev-kit)
- pca10028 (dev-kit)
- pca10032 (dongle)

Current target boards supported by nrf52832:
- Bluefruit nRF52 Feather
- BL652 & DVK from Laird
- pca10040

Current target board supported by nrf52840: pca10056

The port introduces a new HAL written from scratch to make it license compatible with micropython for redistribution. Header files for individual chips (Nordic Semi MDK) are distributed, as it uses a compatible BSD license. Hence, no dependency on any other 3rd party for HAL or libraries.
All targets, except for the nrf52840, have Bluetooth LE support using Nordic Semiconductor Bluetooth Stacks (Softdevice) downloaded directly from Nordic's website using the provided script. 

Some modules are not be 100% aligned with current micropython machine API. However, the port is functional and gives a good base to start writing micropython code on the nrf5x devices with or without Bluetooth LE.

Subsequent patches are expected to get the port up to date to the new machine module APIs, adding new HAL drivers and modules, adding new target boards and optimizing flash/ram footprint (specially on the nrf51 targets).

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks @tralamazza and @glennrub for this great work!  It looks relatively clean.  I will have to try it out, especially the BLE REPL.

For reference, see #2801 for a previous PR of this set of code, and some relevant comments there.

**Comment by dpgeorge** [comment]
I tried this PR out on 2 devices:
- PCA10036 (engineering A version of nRF52832): I can get a UART REPL but enable the soft device S132 doesn't work, probably because this version of the silicon has heaps of bugs.
- microbit: I got the non-SD and SD versions working via UART REPL.  The SD version (S110) seemed to advertise itself, and I even saw the Nordic UART service, but I couldn't pair with the device so didn't get much further testing it.  Any hints how to pair with it?

**Comment by glennrub** [comment]
Hi @dpgeorge, I'm happy to read that you have tried it out!

When it comes to the pca10036 and the engineering version of the nrf52832, it's is a bit buggy. You were a bit more lucky than me, i had to try it out myself and it resulted in HardFault immediatly. It should be consider whether its worth the time to add support for this board or not. 

It's good that the testing with micro:bit went a bit better. Could you elaborate a bit more on how you tried to connect to the micro:bit? PC or tablet/phone? Dongle or inbuilt? Using the nus_console? Personally i'm using the nus_console with a dongle (broadcom chipset).

(I have to also put a note here if you mange to get it up running. There is a known issue related to the BLE REPL on the nrf51, that the device stops notifying if you type to fast on the keyboard. So for now, the trick is to be a bit gentle to the nrf51 until this has been resolved.)

**Comment by aykevl** [comment]
What's the status of this port?
I've tried it out and managed to port it to the [WT51822-S4AT](http://www.wireless-tag.com/wireless_module/BLE/WT51822-S4AT.html) (also known as nRF51822-04). It's very cheap (~$2.50 on AliExpress) and really small.
I got a REPL on serial and BLE serial to work - but not much more than that. Creating a `machine.Pin` appears to crash the device. I also don't know how to upload scripts to it.

**Comment by glennrub** [comment]
The port is still actively developed and maintained. 

When it comes to the specific device you have tried out i cannot explain why this is not working for you. I just did a quick test on a pca10001 which has the nrf51822QFAAG0, and i can not see any problems with machine.Pin. 

I'll be more than happy to help you out on this, to get your device up running. However, i would suggest that we move the further discussion over to the [Forum](https://forum.micropython.org/viewtopic.php?f=12&t=859) or that you raise an issue in the nrf-port's [issue tracker.](https://github.com/tralamazza/micropython/issues)

**Comment by aykevl** [comment]
Ok, thanks. I've fixed the `machine.Pin` issue and made a pull request for this board (https://github.com/tralamazza/micropython/pull/107).

**Comment by dpgeorge** [comment]
@glennrub @aykevl great to see you are both actively working on this port.  I would like to have nrf5x support officially in this repo and it makes sense to (somehow) merge this PR.  I assume by the fact that the PR is here and still open that you want to have it merged.  If merged, would you then be interested to continue to maintain it within this repository (ie not on your personal fork)?

**Comment by glennrub** [comment]
@dpgeorge Sounds good! The motivation was and still is to get the PR merged in the upstream repository and continue development/maintenance there, discontinuing the personal fork. If you consider to merge this PR and have something specific that you would like to be changed/facilitated please let us know.

**Comment by askvictor** [comment]
What would be involved in getting this working on a board such as this: https://www.aliexpress.com/item/nRF51822-Bluetooth-4-0-BLE-SOC-Temperature-Atmospheric-Pressure-Acceleration-Sensor-Module-Gyroscope-Light-Sensor-MPU6050/32816579479.html ?

**Comment by aykevl** [comment]
> What would be involved in getting this working on a board such as this: 

It should not be *that* difficult. Bare minimum steps to get it up and running:

1. Get an SWD programmer. I have had good results with the ST Link v2 clones all over AliExpress.
2. See where the SWD pins are exposed. I think these are the four holes at the side of the board (CLK/DIO/VCC/GND). To be safe, follow the traces from the chip to the holes, using the datasheet of the nRF51 as a reference for which pins are the SWD pins (SWCLK, SWDIO). Note: do not connect VCC to a programmer as long as the battery is connected!
3. Check whether this device has a 32kHz crystal attached for lower power during sleep. It probably has. If it has not and it is configured as if it has, the device will hang.
3. Connect the programmer and see if it can connect to the chip.
3. Configure the REPL. You need to decide whether to use UART (easy to configure, requires extra wires) or NUS (REPL over a BLE connection). In the former case, you just configure the pins. In the latter case, you also need to flash a SoftDevice and not just the application - but it does not require extra wires.
6. Flash the compiled application, flash the SoftDevice if you use it, and reset.

You can see examples of board configurations in ports/nrf/boards. Just copy one and modify it to your needs. You can disable some unused peripherals like SPI.

So when you have this, you can see whether you get all sensors up and running. I see all of them use I2C so you need to figure out to which pins they are connected (probably all on the same bus) and possibly extra interrupt pins per chip. Follow the traces for this and check the relevant datasheets for the sensors.
At the moment I2C doesn't work very well but we are working on replacing the HAL (should land very soon) and in my experience I2C support has become a lot better: only scanning support doesn't seem to work.

**Comment by askvictor** [comment]
Awesome thanks for the detailed reply; I'll order one and give it a go. Not too sure what you mean by softdevice, but can work that out if I get it started up.

**Comment by hoihu** [comment]
@aykevl Thanks for all the work on this port. I‘ve been following progress on this port mainly because I‘d be interested to use an nrf device for a project. I skimmed through the new HAL nrfx and wondered about the relative strict copyright licence?

**Comment by aykevl** [comment]
@hoihu Actually the nrfx HAL is licensed under a 3-clause BSD license which is very permissive. It was specifically made to make it easier for open source projects.

Here is some more information about the new licenses and the new HAL:
https://devzone.nordicsemi.com/b/blog/posts/introducing-nordics-new-software-licensing-schemes

Oh and note that this is a joint effort, @glennrub deserves at least half of the credit ;)

**Comment by askvictor** [comment]
@aykevl I've finally got the hardware and time to have a go at loading micropython on the [aforementioned little nrf module](https://github.com/micropython/micropython/pull/3137#issuecomment-367514852); However, I'm lost as to what flash util to use. Also, and pointers or howtos on how to get the st-link programmer up and running would be handy; I've not worked with ARM microcontrollers before.

**Comment by aykevl** [comment]
Maybe we should document it in the README. But this is what I do to start the OpenOCD background process:

    openocd -f interface/stlink-v2.cfg -f target/nrf51_stlink.tcl

If the OpenOCD exits with an error and it mentions a voltage (around 3.3V), it's most likely some wires aren't connected correctly. If it doesn't show the voltage it probably didn't recognize the programmer.

When you get OpenOCD connected you can flash with the following commands, from memory:

```
$ telnet localhost 4444     # connect to OpenOCD shell
(inside openocd shell)
> nrf51 mass_erase
> program build-sometarget/firmware.hex
> reset
```

If you want to program together with the SoftDevice, you also have to program the SoftDevice first the first time:

```
> nrf51 mass_erase
> program path/to/softdevice.hex
> program build-sometarget/firmware.hex
> reset
```

**Comment by vshymanskyy** [comment]
Are there any plans to integrate this into the mainline? What is blocking this?

**Comment by glennrub** [comment]
@vshymanskyy, representing this PR/nrf-port i do not see any blockers. @dpgeorge, could you comment on plans of getting it merged, or whether you see any blockers?

As stated before, we are ready to move the development and maintenance to mainline as soon as/if merged.

**Comment by dpgeorge** [comment]
> @dpgeorge, could you comment on plans of getting it merged, or whether you see any blockers?
> 
> As stated before, we are ready to move the development and maintenance to mainline as soon as/if merged.

Apologies for not keeping up with this PR.  It's mainly because there is so much other work to do just to maintain and develop everything else :)  But I can see that this has been actively maintained for over a year now so am confident to add it to mainline as an officially supported port.

So, I just need to think what's the best way to proceed.  Following the usual practice of commits here, this PR would be rebased on top of master.  I don't know if it makes sense to squash a few/many/all of the commits, or none.  And maybe some support libraries should be put into a submodule.

**Comment by dpgeorge** [comment]
Rebasing on top of master goes very smoothly, thanks for keeping it clean!  There are 901 commits so it would be good to squash that down somehow.  It seems that a lot of the work was done before the move to the ports/ directory, so perhaps it makes sense to squash all the commits before the move, and that would squash about 800 commits into one...

**Comment by dpgeorge** [comment]
> And maybe some support libraries should be put into a submodule.

I see that the nrfx HAL code is already a submodule, great!

And building a few of the boards works perfectly (using arm-none-eabi-gcc 8.1.0).

I tested the microbit board and it works, except it hangs on soft reset (ctrl-D).  But that's not a blocker to merge this PR.

**Comment by tannewt** [comment]
Merging rather than rebasing would be best for circuitpython since we’ve
already merged it in. Otherwise all the commit ids will change and be
duplicated.

On Tue, Jul 3, 2018, at 11:46 PM, Damien George wrote:
>> And maybe some support libraries should be put into a submodule.


> I see that the nrfx HAL code is already a submodule, great!


> And building a few of the boards works perfectly (using arm-none-eabi-
> gcc 8.1.0).> I tested the microbit board and it works, except it hangs on soft
> reset (ctrl-D).  But that's not a blocker to merge this PR.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].

Links:

  1. https://github.com/micropython/micropython/pull/3137#issuecomment-402380258

**Comment by dpgeorge** [comment]
I see that there's a custom random module, which shouldn't be necessary.  In fact it looks like it's using HW RNG and I think this is wrong because the random module should use a PRNG so that the random sequence is reproducible by setting the seed.  There's always `os.urandom` for true random numbers.

**Comment by dpgeorge** [comment]
There's also the addition of microbit code: display, images and music.  In principle it's ok to have this, and the display code is useful.  Ultimately it would be good to support the microbit via this repository, but getting 100% compatibility with the existing microbit API will require a fair bit more effort, and merging of more code from there (eg the speech module, with its license).  Well, that's not really to decide right now, just to think about whether something like the music code should be included.

**Comment by glennrub** [comment]
> So, I just need to think what's the best way to proceed. Following the usual practice of commits here, this PR would be rebased on top of master. I don't know if it makes sense to squash a few/many/all of the commits, or none. And maybe some support libraries should be put into a submodule.

Thanks @dpgeorge for the feedback, and i'm happy to hear that the PR is considered to be merged!
 
I would imagine that a squash of all of the commits would be OK. However, as @tannewt pointed out it might get a bit tricky for ciruitpython if all commit ids change. I'm not an expert on what would be the best here.

> Also, licensing and copyright for everything here needs to be checked.

I believe licenses/copyright's should be pretty much in order. It would of course be good that it's checked explicitly. Is there a tool for this? or would it be manually checking?

A note on microbit files:
For the microbit ported files under `boards/microbit/modules` the license and author's file has been supplied as the license text of that repository describes it. (https://github.com/bbcmicrobit/micropython/issues/460)
Other modules from microbit that has been ported; modrandom, modmusic, microbitfs, softpwm and ticker includes license text in-file which grants permission to copy/modify/redistribute. Hence, moved out and detached from the `microbit/modules` license.

> I see that there's a custom random module, which shouldn't be necessary. In fact it looks like it's using HW RNG and I think this is wrong because the random module should use a PRNG so that the random sequence is reproducible by setting the seed. There's always os.urandom for true random numbers.

We'll take a look at this, shouldn't be too hard to remove the HW_RNG one.

> There's also the addition of microbit code: display, images and music. In principle it's ok to have this, and the display code is useful. Ultimately it would be good to support the microbit via this repository, but getting 100% compatibility with the existing microbit API will require a fair bit more effort, and merging of more code from there (eg the speech module, with its license). Well, that's not really to decide right now, just to think about whether something like the music code should be included.

Yes, i agree, the display module is almost a must for microbit to make something fun. Additional drivers/modules ported from microbit (modmusic, modrandom, microbit-FS, softpwm and ticker) has been adopted to additionally run on nrf52, and run simultaneously with Bluetooth LE. So i guess from my side it's not only about supporting the microbit from this port, but also to share the good drivers written for microbit with other compile targets.

**Comment by dpgeorge** [comment]
> Merging rather than rebasing would be best for circuitpython since we’ve already merged it in. Otherwise all the commit ids will change and be duplicated.

@tannewt  I think it might actually be cleaner (a cleaner git history) for you if I do a rebase and squash a lot of commits.  If I do a pure merge, then when you merge us you will see a big merge of this nrf branch, plus connections in the graph to all the commits you already merged.  And then you need to merge the merge I make.  On the other hand, if I do a rebase and squash then you'll see a handful of new commits for the nrf port which will just be like any normal commit we make in this repo, and you then just have to merge them as usual.  But because you already have the changes in the rebased/squashed commits the merge will be blank (given that there were no changes in the meantime).  And the history will be much cleaner for you.  All your original merges of the nrf code will still be in your repo.  Maybe you want to give this a test run, try out both scenarios, to see exactly how it works?

**Comment by dpgeorge** [comment]
> I would imagine that a squash of all of the commits would be OK.

@glennrub if you (and other authors on this branch) are OK with a rebase and squash (maybe not of all, but at least of all commits before the move to the ports/ dir) then that is definitely my preferred option.

> I believe licenses/copyright's should be pretty much in order. It would of course be good that it's checked explicitly. Is there a tool for this? or would it be manually checking?

I'll go through and check it manually.  I think it's the only way to do it properly.

> We'll take a look at this, shouldn't be too hard to remove the HW_RNG one.

Ok.  It's not a blocker to merge this, we can do the change after a merged.  I was more curious as to why it was duplicated in this way.

> So i guess from my side it's not only about supporting the microbit from this port, but also to share the good drivers written for microbit with other compile targets.

Yes that's a good goal, to have the microbit classes available for other ports.  That can come it time as well.

So I guess the things to do to get this merged are:
1. decide/agree that rebasing and squashing is the right way to merge the code
2. check licensing and copyright

**Comment by glennrub** [comment]
> glennrub if you (and other authors on this branch) are OK with a rebase and squash (maybe not of all, but at least of all commits before the move to the ports/ dir) then that is definitely my preferred option.

@dpgeorge, i've reached out to the other co-authors to ask if a big squash is acceptable, and the fact that credit/commit history gets lost. I thinks as a minimum all co-authors should get credited in the big squash commit.

**Comment by aykevl** [comment]
Great to see this PR so close to a merge!

> @glennrub if you (and other authors on this branch) are OK with a rebase and squash (maybe not of all, but at least of all commits before the move to the ports/ dir) then that is definitely my preferred option.

I'm generally no fan of rewriting/squashing history (except for single-feature PRs) but if you'd rather see older commits squashed that's fine to me. I would, however, prefer when the more recent commits (e.g. after the ports/ move) wouldn't be squashed. It breaks `git blame` among others.

Something else: I'm wondering how this port will be managed after the merge? Lately it's mostly been managed by @glennrub with me as an on-and-off active contributor with PRs being closed fairly quickly, but I'm worried that development will slow down after the merge, as you already seem to have a lot of work with MicroPython. How will management be organized after the merge? I can think of a few ways:

* Business as usual - you review and merge patches.
* More like the Linux development model, e.g. review is mostly done by one of the port maintainers but the final merge is done by you. Pre-reviewed PRs don't need an extensive review so can be merged more quickly.
* Give port maintainers commit access so they can review and merge PRs themselves (but only for their port).

**Comment by dpgeorge** [comment]
> I thinks as a minimum all co-authors should get credited in the big squash commit.

Yes, definitely we will do this.  See how it was done for the esp32 port here: bc08c884a2e7d1d3a4476c224f230b90ee2bf1e3



> I would, however, prefer when the more recent commits (e.g. after the ports/ move) wouldn't be squashed.

Ok, I think we can accommodate this.

> I'm wondering how this port will be managed after the merge?

I'm happy to give push access to nrf maintainer(s) to make management more efficient.  The idea would be for a process like this:
- minor changes to the nrf port could be pushed by nrf maintainer(s) without review (but the changes should only touch code in the ports/nrf dir, or associated location in docs/)
- major changes to the nrf port, or uncertain changes, would ideally be put up for review
- changes that touch other parts of the code base must go up for review
- PRs/contributions to nrf port can be merged by nrf maintainers

If you have other ideas/suggestions, let me know.

**Comment by dpgeorge** [comment]
I did a test-run of rebasing and squashing all the commits (around 800) before the move to the ports directory, and squashed them with the commit that did the move of nrf5/ to ports/nrf.  You can see the branch here: https://github.com/dpgeorge/micropython/commits/ports-add-nrf .  In particular the first, squashed commit, with a very long commit message (that might be made a bit shorter): https://github.com/dpgeorge/micropython/commit/280afa8a64cb4ce1269b70c83e54e384dbdea610 .  I left the other 97 commits, after the move to ports/nrf/, unsquashed (but rebased, and there were some edits to the commit messages to make them more consistent with the nrf prefix at the start).

It's either this aproach, or no squashing at all and just rebasing the 900 or-so commits (and trying to reword the commit messages to not run over 72 characters on the first line...).

**Comment by aykevl** [comment]
I took a quick look at the proposed PR and it looks good!

Just a note: the ubluepy module in there is not considered stable as we haven't agreed on a BLE API yet. So we shouldn't promise backwards compatibility to it, it may be replaced some day. I think most other things are roughly stable.

> I'm happy to give push access to nrf maintainer(s) to make management more efficient. The idea would be for a process like this: [...]

Sounds good!

**Comment by glennrub** [comment]
> I did a test-run of rebasing and squashing all the commits (around 800) before the move to the ports directory, and squashed them with the commit that did the move of nrf5/ to ports/nrf. You can see the branch here: https://github.com/dpgeorge/micropython/commits/ports-add-nrf . In particular the first, squashed commit, with a very long commit message (that might be made a bit shorter):

@dpgeorge , Thanks a lot for doing this test-run to see how it could look like! For the squashed commit, we can probably replace the commit log there with either the names on the contributors that has contributed with commits to this squash set or trim down the log by removing my entries, keeping the other contributors only. If wanted, i can provide the hashes of these commits, or name/usernames on the contributors which is part of the squashed commit.

I have received positive feedback from the co-authors that they are OK with squashing commits. @aykevl's comment about keeping the recent commits as is after the move to ports/ was a good input, and i agree that it would make sense to do it that way. And your test-run looks like it is addressing this very nicely.

Summarized, the only modification to the test-run which i would like is to update the commit message to credit the other co-authors of their commits in the squash. Else, it looks good from my side.

**Comment by dpgeorge** [comment]
> Just a note: the ubluepy module in there is not considered stable as we haven't agreed on a BLE API yet. So we shouldn't promise backwards compatibility to it, it may be replaced some day. I think most other things are roughly stable.

Ok, noted.

> Thanks a lot for doing this test-run to see how it could look like

I've now updated this branch (at https://github.com/dpgeorge/micropython/commits/ports-add-nrf) (with a force-push) to make all the commit messages conform to the format used in this repo.  I tried to make minimal modifications when doing it.  @glennrub you may want to have a quick look to check that you're happy with how it looks now.  There are still the 98 commits in total which retain the history of all the changes since Oct 2017 (9 months).

> For the squashed commit, we can probably replace the commit log there with either the names on the contributors that has contributed with commits to this squash set or trim down the log by removing my entries, keeping the other contributors only. If wanted, i can provide the hashes of these commits, or name/usernames on the contributors which is part of the squashed commit.

Retaining the hashes of the commits (in the long commit message) only make sense if they point to somewhere that can last indefinitely.  Eg if the original history is preserved somewhere in a repo (eg yours, on a branch) so that the hashes remain constant.

To make the commit message more readable but still retain most of the history and credit, you may want to do it like was done with the merge of the ESP32 code, see commit here: https://github.com/micropython/micropython/commit/bc08c884a2e7d1d3a4476c224f230b90ee2bf1e3 .  To make this I just combined adjacent commits by the same author in one paragraph, and listed the author's name just once at the start of each paragraph.

**Comment by glennrub** [comment]
> I've now updated this branch (at https://github.com/dpgeorge/micropython/commits/ports-add-nrf) (with a force-push) to make all the commit messages conform to the format used in this repo. I tried to make minimal modifications when doing it. @glennrub you may want to have a quick look to check that you're happy with how it looks now. There are still the 98 commits in total which retain the history of all the changes since Oct 2017 (9 months).

@dpgeorge, the updated branch looks good to me!

> To make the commit message more readable but still retain most of the history and credit, you may want to do it like was done with the merge of the ESP32 code, see commit here: bc08c88 . To make this I just combined adjacent commits by the same author in one paragraph, and listed the author's name just once at the start of each paragraph.

Great idea. If you need some help please let me know. Or, maybe you already have a script to automate this conversion a bit?

**Comment by dpgeorge** [comment]
> Great idea. If you need some help please let me know. Or, maybe you already have a script to automate this conversion a bit?

No script, but it shouldn't be too hard with some vim macros.  I'll give it a try.

**Comment by dpgeorge** [comment]
@glennrub I updated the commit message for the first nrf commit on my branch.  I also separated out the change you made to lib/utils/pyexec.h to expose `pyb_set_repl_info` as public.  I think it's getting very close now to being able to merge.

**Comment by dpgeorge** [comment]
> Would it also be possible to rewrite the glennrub author to my name?

No problem, now done.

> The other one was to lib/netutils adding parsing of ipv6 addresses, but that was reverted

Yes I saw that, and this change has been cleanly removed.

**Comment by glennrub** [comment]
> No problem, now done.

Thank you, @dpgeorge! Now, it all looks good from my side.

**Comment by dpgeorge** [comment]
I've now checked the copyright and licensing and am happy with it.  Thank you very much @glennrub and @aykevl and other contributors for keeping it clean.

I submitted PR #3948 which is this PR with the commits squashed as discussed above, and that would be the one that is merged instead of this PR (it's the same code of course!).  @glennrub I did not make any changes to that branch of mine (which is now the PR) since you last looked at it (when I fixed your author name).

**Comment by glennrub** [comment]
@dpgeorge, The two headers,
* ports/nrf/drivers/ticker.h
* ports/nrf/drivers/softpwm.h

lacks license and copyright notice from bbcmicrobit/micropython. I would assume it would be bad practice to add license text and copyright on others behalf (Relates to the issue in bbcmicrobit/micropython: https://github.com/bbcmicrobit/micropython/issues/460). Should we consider to copy the _AUTHORS_ file and _LICENSE_ from from boards/microbit/modules to ports/nrf/drivers?
Do you see any problems that these header files lacks copyright statement in the headers, or is it covered by the c-implementation?

**Comment by dpgeorge** [comment]
> The two headers ... lacks license and copyright notice from bbcmicrobit/micropython.

Ok, so there's the issue of licensing and of copyright.  For the former, the LICENSE file at the root of the micro:bit repo will cover these header files.  The license says that "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software".  Since these files are *copied* we should include the copyright and permission notice "in the Software".  So I think it's fair to put the LICENSE data at the start of these header files.

For the copyright, we can see from the git history of the micro:bit repo that these two headers had Mark Shannon and myself as authors, but to be on the safe/fair side we should list all names in the AUTHORS file as copyright holders.

So we can add this text at the top of these two headers and that should cover it in the right way.

> Do you see any problems that these header files lacks copyright statement in the headers, or is it covered by the c-implementation?

There's not really much to copyright, and the license/copyright in the corresponding .c files would probably be enough to cover the .h as well, but to be on the safe side we can do as I suggest above.  Would you be happy with that?

**Comment by glennrub** [comment]
> There's not really much to copyright, and the license/copyright in the corresponding .c files would probably be enough to cover the .h as well, but to be on the safe side we can do as I suggest above. Would you be happy with that?

@dpgeorge , Sorry for bringing this up so late in the process. I honestly had forgotten about these two files and found this by coincidence when i looked over the final PR. I'm good with the proposal, that should cover it. I've created a PR to tralamazza/master, adding the license and authors as suggested above;
https://github.com/tralamazza/micropython/pull/213

**Comment by dpgeorge** [comment]
This has finally been merged, via #3948.

Thank you to all involved!

**Comment by pfalcon** [comment]
Even with 800-commit squash, this merge is still a big noise-bomb for the codebase. For example https://github.com/micropython/micropython/commit/7c74b7da48545fb66fad6135820fea6d69ea4fc1, "nrf/drivers/softpwm: Rename init function to softpwm_init0.". Rename, why? If no reason, then why it's not squashed into the preceding commit touching that file? It's not the single case, it's fair to say that if 800 commits were squashed together, than a hundred more could have been squashed too. With extra pass to fix codestyle deviations.

**Comment by aykevl** [comment]
I don't know about `softpwm_init0` but I'm guessing it's name was changed to keep it consistent with the other initializers (see ports/nrf/main.c).

I think we mostly agree, and I've tried to do it as much as possible. For example, we had a branch to switch to a new HAL that contained tens of commits that were all squashed together as this switch really is one (very big) change.

**Pull request closed without merging**
