### PR TITLE
py/nlr: maybe restore warning via #pragma message

### PR DESCRIPTION
**Pull request by pmp-p**
both gcc and clang accept that 
need testing of other compilers ?

### CODE REVIEW

**Comment by stinos** [comment]
What would be the reason to restore this? It would just yield a bunch of warnings on the windows port, but it actualy works just fine so the warning isn't really justified.

**Comment by pmp-p** [comment]
dunno maybe as a test if that one https://github.com/micropython/micropython/blob/master/py/persistentcode.c#L776 can be replaced by #pragma message  too :)

**Comment by stinos** [comment]
Forgot to mention the crux: I don't think C99 has anything standard. in any case `#pragma message "abc"` does not work on msvc, nor does `#warning`. Something like `#pragma message ("warning: abc")` does work.

**Comment by stinos** [comment]
Aha, seems msvc has `__pragma` for that same purpose in which case syntax is `__pragma(message("warning: " str))`

But again: I'm not a fan of using this to introduce hundreds (or so) warnings in the msvc port :)

**Comment by pmp-p** [comment]
so something like that  would work everywhere ?
```
#ifdef __GNUC__
#define MP_WARNING(str) _Pragma("GCC warning" str)
#else
#define MP_WARNING(str) __pragma(message("warning: " str))
#endif
``` 
And no i don't specially want to reactivate this warning if it is too chatty, i just want to turn some errors in warnings while building a new port.

**Comment by stinos** [comment]
This does the trick for msvc:
```
#ifdef _MSC_VER
#define MP_WARNING(str) __pragma(message("warning: " str))
#endif
```

However since there's already the function `mp_warning` this one should probably get a different name

**Comment by dpgeorge** [comment]
> What would be the reason to restore this? It would just yield a bunch of warnings on the windows port, but it actualy works just fine so the warning isn't really justified.

I agree with @stinos here, I don't see any reason to have this warning.  The setjmp/longjmp implementation of NLR works well, and this warning was added long ago when it wasn't clear that it would work.  So probably better to just replace this line with an appropriate comment.

> dunno maybe as a test if that one https://github.com/micropython/micropython/blob/master/py/persistentcode.c#L776 can be replaced by #pragma message too

That one needs to be an error, it won't build without `mp_raw_code_save_file`

**Comment by stinos** [comment]
For completeness / future reference: the aforementioned macro for gcc actually does not work and results in `error: _Pragma takes a parenthesized string literal`. To get that string concatenation working it seems some extra stringify workarounds are required, [thanks StackOverflow](https://stackoverflow.com/questions/8724644/how-do-i-implement-a-macro-that-creates-a-quoted-string-for-pragma):

```
#if defined(__GNUC__)
#define MP_GCCMESS_HELPER1(x) MP_STRINGIFY_HELPER(GCC warning x)
#define MP_GCCMESS_HELPER2(y) MP_GCCMESS_HELPER1(#y)
#define MP_COMPILER_WARNING(x) _Pragma(MP_GCCMESS_HELPER2(x))
#elif defined(_MSC_VER)
#define MP_COMPILER_WARNING(str) __pragma(message("warning: " str))
#else
#define MP_COMPILER_WARNING(str)
#endif
```

**Comment by pmp-p** [comment]
> That one needs to be an error, it won't build without `mp_raw_code_save_file`

no it won't build if none of those are defined ```#if defined(__i386__) || defined(__x86_64__) || defined(__unix__)``` which is obviously the case for new port hardware which can use MICROPY_PERSISTENT_CODE_SAVE has a facility and link mp_raw_code_save_file later.

so my logic is still : 
1) make a warning macro that produce a warning and not a build error.
2) replace the error by that warning.
in order to implement ports without messing with core and also provide a way for developper to send an **informative** warning without breaking build. that's what #warning is made for ... usually.

**Comment by dpgeorge** [comment]
> make a warning macro that produce a warning and not a build error

Most (all?) of the code in this repository builds with `-Werror` because of the view that code is either correct or incorrect, that warnings should be treated as errors.  So I don't really want to introduce this concept of "warnings".

**Comment by pmp-p** [comment]
Correctness of the code is irrelevant here and since ways used to get that correctness are ok "iif it ain't broke, don't fix it"

but warning system was broken in the process :

 - build process can't self document itself when a parameter induce non conformance to RFC. Do you expect everybody to understand all the conditionnal defines and their implication ?

 - A clear warning is better than a separate todo list , or a buried FIXME/TODO comment when trying modifications.


> So I don't really want

i've guessed that but when it's a definitive postion on the case please just close, so fewer time is spent thank you.

**Comment by pmp-p** [comment]
also -Werror=implicit-function-declaration and -Werror=unused-function are an annoyance for user mod build system (well at least for people who ever attempted to use that).

**Comment by embeddedt** [comment]
I wouldn't consider `implicit-function-declaration` an annoyance. In 99% of the cases where it's triggered, it means that something is wrong with your code.

**Comment by pmp-p** [comment]
@embeddedt i agree,  but it's specific to javascript port the way fastcomp emscripten link shared objects, i think it's fixed in upstream branch though.

**Comment by dpgeorge** [comment]
I'll close this because, as mentioned, this project considers warnings as errors.

> so just in case and for future reference what would be the best place to put @stinos macro which seems to cover all cases ?

In `py/misc.h`, after `MP_STATIC_ASSERT`.

**Pull request closed without merging**
