### PR TITLE
ports/esp32: Support setting the wifi protocol mode.

### PR DESCRIPTION
**Pull request by glenn20**
This PR provides support for setting/getting the wifi protocol mode (11B|11G|11N).

**Provides:** Adds the `protocol` option to `WLAN.config()` to support setting/getting the wifi protocol modem, eg:

```
import network
ap = network.WLAN(1); ap.active(True)
ap.config(protocol=network.MODE_11N)
ap.config(protocol=network.MODE_11B|network.MODE_11G)
```

Curiously, the constants for these modes were already present in `modnetwork.c`, but previously no method for using them.

Also adds network.MODE_LR which enables Espressif's long-range mode for communication between ESP devices.

### CODE REVIEW

**Comment by beyonlo** [comment]
Excellent!
Thanks :)

**Comment by dpgeorge** [comment]
Thanks, this looks good!



> Curiously, the constants for these modes were already present in `modnetwork.c`, but previously no method for using them.

That's from esp8266's `phy_mode()` function.  esp32 also has that but it's only a dummy function.  We should eventually remove that and add this new `config(protocol=)` option to esp8266 as well.

**Comment by glenn20** [comment]
> Thanks, this looks good!
> 
> > Curiously, the constants for these modes were already present in `modnetwork.c`, but previously no method for using them.
> 
> That's from esp8266's `phy_mode()` function. esp32 also has that but it's only a dummy function. We should eventually remove that and add this new `config(protocol=)` option to esp8266 as well.

@dpgeorge Ah - that explains it. I'm happy to add a commit to this PR to add the protocol arg for esp8266 - unless you prefer to leave that for another day.

I will add a commit with a proposed update to the docs.

**Comment by AmirHmZz** [comment]
@glenn20 Thank you for bringing those ESP-IDF features to Micropython!

**Comment by dpgeorge** [comment]
This is good.  Merged in 76f2e3e62bd2bc177a62649bae34b67d9bd2c8b1 through e6e60f4330c176e1a9443a994ba29ea155d7aca7

**Pull request closed without merging**
