### PR TITLE
[RFC] extmod/modbluetooth: Expose completion of GATTC discovery

### PR DESCRIPTION
**Pull request by codefreax**
Expose completion event of the GATTC discovery operations:

 - `BLE.gattc_discover_services(...)`
 - `BLE.gattc_discover_characteristics(...)`
 - `BLE.gattc_discover_descriptors(...)`

The event signals to the app that discovery is complete, i.e. all
results have been handled, and no more `_IRQ_GATTC_*_RESULT` events will
be generated.

This commit implements the event for the NimBLE stack.

We could also expose three separate events, one for service discovery, one for characteristics, one for descriptors. We would then have to extend the event ID width (now 16 bits).

We should also decide whether we want to reorder event IDs, i.e. move the discover_complete event ID(s) to the corresponding foo_result event IDs.

### CODE REVIEW

**Review by jimmo — COMMENTED** [review]
Thank you @codefreax -- I agree this is definitely a worthwhile addition, and something I'd considered doing also.

Some thoughts:
 - Is it worth including with the event which type of discovery competed?
 - Could we maybe reuse the SCAN_COMPLETE event (hard to do without a breaking change...which might be OK at this stage).
 - Also need to implement the btstack version (I can do this after this is merged).

**Comment by codefreax** [comment]
I would like to avoid adding another "enum" to communicate which type of discovery completed. But adding one distinct event per type, (and growing the IRQ type from 16 bits to 32) does not sound attractive either.

How about adding an error field to each of the RESULT IRQs (`SCAN_RESULT`, `GATTC_SERVICE_RESULT`, ...)? For a valid result, I'd set error to 0. For an error, set the corresponding error. And `BLE_HS_EDONE` I'd map to `MP_ENOENT`. Or to `-1` maybe?

**Comment by codefreax** [comment]
Adding an `error` field would make sense for other IRQs, too. In https://github.com/micropython/micropython/pull/5933 I propose to add it to READ_RESULT. Please have a look!

**Comment by agners** [comment]
I think I would bite the bullet here and extend IRQ type to 32-bit. Afaik, this would not break the API as Python just knows integers. Then just adding the three events at the end. This makes the API nicely symmetric.

I guess reordering the events (in terms of value) is not ok as this would really break API.

Adding an additional field to each `_IRQ_GATTC_*_RESULT` would break the API too, so if anything we could maybe return a `None` object in the uuid field or similar. That likely would trip existing code too though.

**Comment by friebel** [comment]
We already expose the status code in write:
```
IRQ_GATTC_WRITE_STATUS(conn_handle, value_handle, status)
```

I like the symmetry we get by adding status to read too:
```
IRQ_GATTC_READ_RESULT(conn_handle, value_handle, status, char_data)
```

IMHO, it is not too bad that the only implementation-independently defined error code is 0. I think there would be value in translating btstack/nimble status codes into something implementation agnostic. But if the number of defined error codes is high, it may not make sense to invest the necessary ROM bytes for that. As the next step, I'd add the implementation-specific status code to `IRQ_GATTC_READ_RESULT` and look into status code translation independent of that.

**Comment by agners** [comment]
> I think I would bite the bullet here and extend IRQ type to 32-bit.

I tried to implement this, and it was rather straight forward. The only downside is the ring buffer which currently only supports 16-bit values.

On the other hand, I was wondering does BLE even allow to discover for services and characteristics/descriptors at the same time (on the same device)? NimBLE on ESP32 apparently does not support this (see #5686). If this is not something is actually allowed by in the BLE spec, then a single event indeed is all which is needed. The event will have the connection handle, so scanning of multiple devices would still be possible.

**Comment by friebel** [comment]
Extended the IRQ event type to uint32/smallint and added three separate event types:
- `IRQ_GATTC_SERVICES_COMPLETE`
- `IRQ_GATTC_CHARACTERISTICS_COMPLETE`
- `IRQ_GATTC_DESCRIPTORS_COMPLETE`

If we decide to expose read errors (https://github.com/micropython/micropython/pull/5933) via an API-breaking change, I'd reorder event IDs here to move SERVICES_COMPLETE after SERVICE_RESULT and so on.

I am wondering what to do with the status code. We could
a) expose the implementation-specific status code as is
b) translate nimble/btstack codes to the closest MP error codes
c) translate nimble codes to btstack, or vice-versa, or to some new MP-specific status codes
d) translate DONE to 0 so that we can specify "status is 0 if discovery completed successfully, or an implementation-specific code in case of error"

I lean a bit towards d), as it allows the user to retry in case of error without knowing which BLE implementation is used while keeping MP code/complexity low. Implemented a) for now.

Note that this is not tested yet.

**Comment by agners** [comment]
Given that we expose implementation defined error codes already in other places, I think d) is a good trade-off.

**Comment by friebel** [comment]
Rebased.

**Comment by friebel** [comment]
Added ringbuffer 32-bit unit tests.

**Comment by petrkr** [comment]
Seems nice, it could solve also our problem with LoadProhibited. I tested it and looks nice

https://github.com/blesync/micropython-blesync/issues/3

**Comment by jimmo** [comment]
Please see #6033 for a slightly different implementation of this for both NimBLE and btstack (with some other fixes and simplification of the event/irq numbers).

**Comment by dpgeorge** [comment]
This is implemented by 6a3c89d584db4f14c7e2432b7c5ad87951e6c2d5

**Pull request closed without merging**
