### PR TITLE
tools/mpremote: Detach mpremote from pyboard.py.

### PR DESCRIPTION
**Pull request by jimmo**
This commit just takes the necessary parts of pyboard.py and merges them with pyboardextended.py to make a new transport_serial.py, and updates the rest of mpremote to use this instead.

It is difficult to continue to add features to mpremote (which usually requires modification to pyboard.py) while also maintaining backwards compatibility for pyboard.py.

The idea is that this provides a starting off point for further refactoring of mpremote to allow different transports (webrepl, BLE, etc).

_This work was funded through GitHub Sponsors._

### CODE REVIEW

**Comment by robert-hh** [comment]
... and so it grows. Didn't mpremote start as a simple tool? I hope you can resists to add a GUI.

**Comment by jimmo** [comment]
> ... and so it grows. Didn't mpremote start as a simple tool?

@robert-hh  Technically this PR is a net removal of code from the mpremote distribution ;) And the idea is to simplify mpremote by making a much clearer boundary between the device and the high-level tool.

But while it did start pretty simple (although I'm not sure you can call the `mount` magic simple!) we're trying to push mpremote as "the" tool for working with MicroPython devices. And as such there are a bunch of features we want to support.

Top of my list right now are:
 - A smarter `cp -r` (I don't think we'll go all the way to a bidirectional sync though ala `rshell`).
 - On the fly conversion to .mpy files via mpy-cross.
 - A REPL for devices that don't have a on-board compiler.
 - WebREPL and BLE REPL transports.

> I hope you can resists to add a GUI.

I'm personally not interested in a GUI tool, but this is definitely something that people want, and I think we should definitely provide the building blocks so that someone who does build such a tool doesn't have to re-invent the wheel with the part that talks to the device. The problem we have is that pyboard.py is not really ideal for this task, and we can't easily improve it without breaking compatibility.

**Comment by peterhinch** [comment]
@jimmo 
> I don't think we'll go all the way to a bidirectional sync though ala rshell

The `rsync` in `rshell` is unidirectional in the sense that files are only copied from source to destination. It is an extremely useful feature for deploying and updating targets, especially with large projects with multiple files. I use `rshell` almost as much as `mpremote` simply because it has this feature. I'd love to see this in `mpremote`.

**Comment by dpgeorge** [comment]
This is essentially just a refactoring, with the aim of future generalisations and simplifications.

**Comment by jamesadevine** [comment]
@jimmo @dpgeorge looking for a bit of guidance here.

I would love to contribute a Socket implementation for interacting with the REPL over local network connections. Practically, this just requires swapping serial.Serial with a class that matches its interface, using sockets underneath. This was the model available before this PR via pyboard.py.

Separating mpremote from pyboard.py is great. Though, with this refactor, I am not sure it is clear how I would contribute a "SocketTransport". Would you prefer a new transport be declared, duplicating the code from SerialTransport? Or common'ing the code from SerialTransport into Transport? Or modifying the serial transport ctor to accept an ip/socket combo and using sockets instead of serial.Serial?

**Pull request merged**
