### PR TITLE
esp32: Add initial support for ESP32S2 SoCs

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR adds initial support for ESP32S2.

To build:
- need IDF v4.3-beta1 (at least, I think IDF v4.4-dev also works)
- must do `export IDF_TARGET=esp32s2` before running make
- build using `make BOARD=GENERIC_S2`
- to deploy to the device make sure it's in bootloader mode (must be done manually) then run `make BOARD=GENERIC_S2 PORT=/dev/ttyACM0 deploy`

The MicroPython REPL is on UART0 (default pins) and also USB CDC.

~~USB is currently not supported because it needs the very latest IDF (there doesn't seem to be a stable IDF release with USB that can be configured as a CDC/VCP).  I did manage to start the USB using IDF v4.2 but it's just a blank USB device with no interfaces.~~

### CODE REVIEW

**Comment by dpgeorge** [comment]
@UnexpectedMaker I tested this on a FeatherS2 and it works!  As mentioned above no USB yet but it does give a REPL over UART.

**Comment by microDev1** [comment]
nice! I was also working on this ([here](https://github.com/micropython/micropython/compare/master...microDev1:port-esp32s2)) but took a different approach with the implementation. Thanks! for adding 👍

**Comment by UnexpectedMaker** [comment]
> @UnexpectedMaker I tested this on a FeatherS2 and it works! As mentioned above no USB yet but it does give a REPL over UART.

Awesome! When you say "it's working on the FeatherS2" - is there a list of know things that are not implemented yet? Apart from native USB? I believe the SPI peripherals might be different on the S2, at least to how they are named etc.

**Comment by dpgeorge** [comment]
> is there a list of know things that are not implemented yet?

If you look at this PR you'll see which things needed to be disabled to get it building.  They include:
- bluetooth
- SD card
- touch pad
- one of the DACs
- one of the HW SPIs
- a couple of GPIO
- temperature sensor
- hall sensor
- ULP
Some of those just need a few tweaks to get working (eg touch pad), others just aren't supported by the chip (eg bluetooth).

**Comment by UnexpectedMaker** [comment]
> > is there a list of know things that are not implemented yet?
> 
> If you look at this PR you'll see which things needed to be disabled to get it building. They include:

Sorry, I should have looked first, but mars2020 was happening ;)

**Comment by dpgeorge** [comment]
Update: USB CDC is now supported, and works as the REPL.  It requires building against IDF v4.3-beta1.

**Comment by UnexpectedMaker** [comment]
> Update: USB CDC is now supported, and works as the REPL. It requires building against IDF v4.3-beta1.

Wicked. As this is the first time we've had native USB on ESP32 (so I've never had to look) is there a place for us to assign our VID/PIDs ?
I assume it wold be a board level setting in a sdkconfig.usb override?

**Comment by dpgeorge** [comment]
> is there a place for us to assign our VID/PIDs ?

Yes, it's an IDF level Kconfig setting that we can easily configure in `boards/<board>/mpconfigboard.cmake`

**Comment by kadamski** [comment]
@dpgeorge is this going to work on a popular ESP32-S2-Saola-1 board or the usb-serial chip on those boards is going to be a problem?

**Comment by dpgeorge** [comment]
> is this going to work on a popular ESP32-S2-Saola-1 board or the usb-serial chip on those boards is going to be a problem?

It will work, there just needs to be a separate board config for the Saola that does not enable USB and instead uses the UART for the REPL.  So it'll be very similar to existing non-S2 ESP32 boards.

**Comment by UnexpectedMaker** [comment]
Hey @dpgeorge - I'm still unable to build inning this PR. In fact, I cant even build for TinyPICO without getting the same tinyusb error - which is weird as TinyPICO is not using `boards/sdkconfig.usb`

```
../usb.c:31:10: fatal error: tinyusb.h: No such file or directory
 #include "tinyusb.h"
          ^~~~~~~~~~~
compilation terminated.
```

**Comment by dpgeorge** [comment]
> I'm still unable to build using this PR. In fact, I can't even build for TinyPICO without getting the same tinyusb error

must do export IDF_TARGET=esp32s2 before running make

**Comment by UnexpectedMaker** [comment]
> > I'm still unable to build using this PR. In fact, I can't even build for TinyPICO without getting the same tinyusb error
> 
> must do export IDF_TARGET=esp32s2 before running make

Though I'm not sure how yet, I'm looking at adding that into the board definitions, so we can also have esp32s3 etc

**Comment by dpgeorge** [comment]
> Though I'm not sure how yet, I'm looking at adding that into the board definitions

I tried this... I think it's a limitation of the IDF that it cannot be done.

**Comment by UnexpectedMaker** [comment]
> > Though I'm not sure how yet, I'm looking at adding that into the board definitions
> 
> I tried this... I think it's a limitation of the IDF that it cannot be done.

Hmm, maybe it's being grabbed too late? I'l ask Gus if he has any ideas as to why it won't work. Thanks for trying it though!

**Comment by dpgeorge** [comment]
> Hmm, maybe it's being grabbed too late?

The relevant logic is in `tools/cmake/targets.cmake:macro(__target_init)`

**Comment by microDev1** [comment]
Having `set(IDF_TARGET esp32s2)` first thing in `mpconfigboard.cmake` should work.
I just tested this with building `GENERIC_S2` successfully by using just `make BOARD=GENERIC_S2`.

**Comment by chtinnes** [comment]
Regarding memory,  will the PSRAM be automatically used by MicroPython? As far as I can see, the SRAM is reduced to 320KB for all of the S2 chips and therefore not sufficient for many applications.

**Comment by UnexpectedMaker** [comment]
> Regarding memory, will the PSRAM be automatically used by MicroPython? As far as I can see, the SRAM is reduced to 320KB for all of the S2 chips and therefore not sufficient for many applications.

Yes, I have PSRAM implemented in my fork for inclusion in mainline once this PR is merged.

**Comment by UnexpectedMaker** [comment]
Current status from me - S2 stuff now supported that wasn't in this initial PR
- PSRAM
- 2x DACs
- Added all remaining GPIO and moved ones that can't be used (used for FLASH/PSRAM.

Touch sensor stuff looks quite a bit harder than expected as the S2/S3 has a whole different/newer API that doesn't exist on the regular ESP32. So I'm leaving that for someone more knowledgable ;)

**Comment by UnexpectedMaker** [comment]
@dpgeorge any word on when this will get merged?

**Comment by dpgeorge** [comment]
I've now updated this and cleaned it up, and it should be in a good state to merge.

@UnexpectedMaker would you be able to test the S2 build?  I included the fix suggested by @microDev1 so it automatically selects the IDF target for esp32s2.

**Comment by UnexpectedMaker** [comment]
> I've now updated this and cleaned it up, and it should be in a good state to merge.
> 
> @UnexpectedMaker would you be able to test the S2 build? I included the fix suggested by @microDev1 so it automatically selects the IDF target for esp32s2.

Sorry I've not gotten to this yet  @dpgeorge - I want to test this, but I'm slammed with my TinyS2 release... hopefully I'll have some time on the weekend.

**Comment by dpgeorge** [comment]
> I want to test this, but I'm slammed with my TinyS2 release... hopefully I'll have some time on the weekend.

I tested it myself on normal and S2 boards and am happy with it, so will merge.

**Comment by UnexpectedMaker** [comment]
> > I want to test this, but I'm slammed with my TinyS2 release... hopefully I'll have some time on the weekend.
> 
> I tested it myself on normal and S2 boards and am happy with it, so will merge.

Oh excellent! Once it's merged I'll work out how to rebase my changes and merge the differences and do a PR.

**Comment by robert-hh** [comment]
I have issued with WiFi using that version with  a feather-s2. Wifi is very unreliable. It freezes after a few transaction.  WebRepl does not work. Ping into the board stops after a while. My ftp server does not respond, even the less demanding foreground version.

**Comment by robert-hh** [comment]
The above mentioned issue disappears if not all available memory is assigned to the python heap in main.c, line 109. It seems that the WiFi stack runs out of memory silently. See also the note by  `petrkr commented on 19 Apr 2020` in #5554.

**Comment by UnexpectedMaker** [comment]
> The above mentioned issue disappears if not all available memory is assigned to the python heap in main.c, line 109. It seems that the WiFi stack runs out of memory silently. See also the note by `petrkr commented on 19 Apr 2020` in #5554.

The S2 has WEAY less SRAM than its predecessor - and I'm still working on the MP support for PSRAM.   
You can try using my "current PR" and compiling and see if the WiFi reliability improves.
https://github.com/micropython/micropython/pull/7163

**Comment by robert-hh** [comment]
> You can try using my "current PR" and compiling and see if the WiFi reliability improves.

That's indeed what I wanted to try next.

**Comment by robert-hh** [comment]
This branch works well on my feather s2 board. WiFi seems fine, and SPIRAM and FLASH are there in full glory.

**Pull request merged**
