### PR TITLE
zephyr: Fixes for zephyr 2.3.0 release

### PR DESCRIPTION
**Pull request by MaureenHelm**
Fixes various issues in the zephyr port when updating to the zephyr 2.3.0 release

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for this, I tested it on a frdm_k64f and it works.

But I needed to use the latest master revision of zephyrproject-rtos, and it looks like this change will not work with any prior release of zephyr (eg v2.2.0).

Is it possible to support v2.2.0 as well as master?  If not, can we wait for the next zephyr release, or do we expect users to build against master?

**Comment by MaureenHelm** [comment]
> But I needed to use the latest master revision of zephyrproject-rtos, and it looks like this change will not work with any prior release of zephyr (eg v2.2.0).
> 
> Is it possible to support v2.2.0 as well as master? If not, can we wait for the next zephyr release, or do we expect users to build against master?

I tend to build against master, but you're right, we should wait to merge this until it builds with a zephyr release. The 2.3 release is planned for the end of May.
https://github.com/zephyrproject-rtos/zephyr/wiki/Program-Management#actual-and-planned-milestone-dates

**Comment by dpgeorge** [comment]
> we should wait to merge this until it builds with a zephyr release.

Ok, let's wait then.  In the meantime users must build against zephyr v2.2.0.

**Comment by MaureenHelm** [comment]
Rebased to fix merge conflict

**Comment by dpgeorge** [comment]
@MaureenHelm it looks like Zephyr v2.3.0 is now released.  I tried building this PR against it but ran into a couple of issues: `k_sleep` is now `k_msleep` and `struct device` no longer has a `config` member to get the name of the device from (needed by `machine_i2c.c`).  Are you able to update this PR to build against v2.3.0?

**Comment by MaureenHelm** [comment]
> @MaureenHelm it looks like Zephyr v2.3.0 is now released. I tried building this PR against it but ran into a couple of issues: `k_sleep` is now `k_msleep` and `struct device` no longer has a `config` member to get the name of the device from (needed by `machine_i2c.c`). Are you able to update this PR to build against v2.3.0?

Yes, I'll do it this week.

**Comment by dpgeorge** [comment]
> The scope of this PR grew a bit to include fixes for `k_sleep` and `struct device`, but I felt it made more sense to keep all the zephyr 2.3.0 related fixes together in a single PR.

Yes I agree.  Thanks for updating everything.  I also tested these changes with Zephyr 2.3.0 and the `frdm_k64f` board and it works.

But I just had a thought: should we rename `zephyr.stacks_analyze()` to `zephyr.thread_analyze()`?  Because the original name was chosen to match the corresponding Zephyr function it seems a bit messy (for someone new to this port) to continue to call it by the old name.

**Comment by MaureenHelm** [comment]
> But I just had a thought: should we rename `zephyr.stacks_analyze()` to `zephyr.thread_analyze()`? Because the original name was chosen to match the corresponding Zephyr function it seems a bit messy (for someone new to this port) to continue to call it by the old name.

I don't have an attachment to `zephyr.stacks_analyze()` and don't mind changing it, but that would break compatibility. The same question came up in #5757.

**Comment by dpgeorge** [comment]
> I don't have an attachment to `zephyr.stacks_analyze()` and don't mind changing it, but that would break compatibility. The same question came up in #5757.

Yes it'd break compatibility.  But... this function is more of a debugging/inspection function rather than something that's part of a program (because it prints output rather than returning data) and so IMO it's a softer break of compatibility.

I think it's worth changing because it follows Zephyr naming.

As for #5757: I understand that's also about breaking compatibility... maybe we should just go for it.

**Comment by MaureenHelm** [comment]
> Yes it'd break compatibility. But... this function is more of a debugging/inspection function rather than something that's part of a program (because it prints output rather than returning data) and so IMO it's a softer break of compatibility.

I agree, this is a good point.

> I think it's worth changing because it follows Zephyr naming.

Done

> As for #5757: I understand that's also about breaking compatibility... maybe we should just go for it.

Given your point above, I think we can just drop it for now.

**Comment by dpgeorge** [comment]
Great, thank you for updating.  Rebased and merged in 38b4f1569e7755f78b991352ae5d53055ad67790 through 1ae861819dbe8a57cdfda882b093d8d564d8f1c9

**Pull request closed without merging**
