### PR TITLE
extmod/machine_i2c: Do a fast poll during I2C.scan().

### PR DESCRIPTION
**Pull request by dpgeorge**
Fixes issue #12912.

This is needed to get scan working again on rp2 after the change made in 8c432ea2d437255eefb4aff18764936ad11b70c7

### CODE REVIEW

**Comment by dpgeorge** [comment]
@projectgus  FYI

**Comment by projectgus** [comment]
@dpgeorge Thanks for the heads-up.

Wondering, does it make sense for the case where `defined(MICROPY_EVENT_POLL_HOOK_FAST) && !defined(MICROPY_EVENT_POLL_HOOK)` to `#define MICROPY_EVENT_POLL_HOOK MICROPY_EVENT_POLL_HOOK_FAST` for all cases?

**Comment by dpgeorge** [comment]
We need to eventually clean up/generalise/improve these event poll macros.  Eg we probably need something like:
```
MICROPY_CHECK_EVENTS;
MICROPY_WAIT_EVENT;
MICROPY_WAIT_EVENT_WITH_TIMEOUT(t);
```
But that will take some thinking, and for now I just wanted a simple fix for the I2C scan.

**Comment by projectgus** [comment]
@dpgeorge There are a few other places this will bite, see #12925

**Pull request merged**
