### PR TITLE
tools/pyboard: Fix exception: 'list' object has no attribute 'clear'

### PR DESCRIPTION
**Pull request by mbuesch**
This fixes:

```
$/micropython/tools$ ./pyboard.py --device /dev/ttyUSB0 --filesystem ls
ls :
         139 boot.py
         186 main.py
Traceback (most recent call last):
  File "./pyboard.py", line 608, in <module>
    main()
  File "./pyboard.py", line 572, in main
    args.files.clear()
AttributeError: 'list' object has no attribute 'clear'
```

I guess this probably is caused by argparse changing types between versions.
So don't rely on the type. Just re-assign the attribute.

### CODE REVIEW

**Comment by dpgeorge** [comment]
I guess you are using Python 2, which doesn't seem to have `list.clear()`?  Maybe it'd be better to use `del args.files[:]` instead, just in case a reference to `args.files` was taken somewhere.

**Comment by mbuesch** [comment]
Oooh. Of course you are right. :)
I accidentally used Python 2 (because the shebank points to python binary).

I updated the commit to use del instead.

What do you think about changing the shebang to:
```
#!/usr/bin/env python3
```

**Comment by dpgeorge** [comment]
> I updated the commit to use del instead.

Great, thanks.

> What do you think about changing the shebang to:
> 
> ```
> #!/usr/bin/env python3
> ```

Yeah, I guess that's a good idea, since Python 2 is now EOL.  It can anyway still be used via `python2 pyboard.py`.

**Comment by mbuesch** [comment]
I added a commit to change the shebang to Python 3.

**Comment by dpgeorge** [comment]
Thanks!  Rebased and merged in 1cadb12d1c4baefd65a7e1030356b63cc0f6c3a6 and 1604606238ae7dbb1ead582172d84d23d885eaf8

**Pull request closed without merging**
