### PR TITLE
rp2/machine_pwm: simpler, more accurate frequency formula, and rounding for duty cycle consistency

### PR DESCRIPTION
**Pull request by pdg137**
As I [commented here](https://github.com/micropython/micropython/issues/8122#issuecomment-1323998587) the current formula for setting DIV and TOP as a function of frequency uses a complicated iterative algorithm to try to maximize TOP while keeping it relatively accurate.  However, in the iterative loop it consistently pushes the frequency upwards, by an amount that depends on prime factors in the formula.  This results in surprisingly inaccurate frequencies, for example 1760 Hz being represented as 1838 Hz instead. There are also strange issues with it like a frequency of 9 Hz or 14 Hz being "too small", while 8 Hz works fine.

I don't see any reason to use the iterative algorithm, so this commit changes it to something based on simple division, first using the smallest possible DIV value the results in TOP < 65535, then computing TOP from DIV.  I have tested the code in a variety of situations and it generally seems to work better, though there are a few frequencies (like 1280 Hz) that the old one happens to hit perfectly while my code is a little off (it makes 1280.003 Hz).

Here is a graph of frequency error comparing the two algorithms:

image

Also, here is a graph showing that the new algorithm always maximizes TOP:

image

In this commit I also changed the duty cycle computations to use rounding instead of floor-ing, which has the desirable result that `pwm.duty_u16(pwm.duty_u16())` doesn't change the duty cycle. The current code generally keeps lowering the value if you keep setting it to what it thinks it is set to.

### CODE REVIEW

**Comment by pdg137** [comment]
To demonstrate the difference more clearly, here are some recordings of a frequency sweep from 200 to 2000 Hz, played through a little speaker controlled by a transistor on pin 7.  This is the code:

```ruby
from machine import Pin, PWM
import time
pwm = PWM(Pin(7))

time.sleep_ms(500)
try:
    pwm.duty_u16(32768)
    for f in range(200, 2000):
        pwm.freq(f)
        time.sleep_ms(1)

except KeyboardInterrupt:
    pass

pwm.duty_u16(0)
```

With the base version of Micropython (`v1.19.1-713-g7fe7c55bb`), using the old algorithm:

https://user-images.githubusercontent.com/466760/204633458-41b7002d-0ec8-4648-888b-84244e40b76d.mp4

With the version in this pull request (`v1.19.1-714-g8f33e1dc9`):

https://user-images.githubusercontent.com/466760/204633482-11a514e1-9346-496f-bcdc-b8f1e66d84ea.mp4

**Comment by robert-hh** [comment]
@mattytrentini A little bit of testing shows, that the result is fine. The frequency is monotonic and within the expected precision, even at frequencies where the `div` value changes, like at the CPU freq of 125MHz for 1907 to 1908 Hz.
The code has and edge case with a numeric overflow. That happens in lines 128 and 132 for the calculation of `16 * source_hz`, which overflows if the CPU freq is larger than 268.435456 MHz (2**32 / 16). That can be demonstrated.

**Comment by pdg137** [comment]
So should I make that change and update the MR? It's a little sad to have to go to 64 bits just to support overclocking, but maybe it won't be too slow?

**Comment by robert-hh** [comment]
I like your code pretty much. It is simple and precise and works well. About your question:
Overclocking is used, and sooner or later someone will stumble over it. The code size increase for declaring source_hz as uint64_t is 24 byte. The same with casting. I do not know the speed impact.
As an alternative, a hint could be made in the RP2 quickref documentation about PWM not being supported at clock speeds beyond 268 MHz. That has the faint smell of blaming the user not taking care of a known restriction.

**Comment by pdg137** [comment]
Thanks for all the feedback.

I had an idea. What if we do it like this?

```c
        if (source_hz > 268000000) {
            div16 = (16 * (uint64_t)source_hz + TOP_MAX * freq - 1) / (TOP_MAX * freq);
        } else {
            // 16*source_hz overflows over ~268M
            div16 = (16 * source_hz + TOP_MAX * freq - 1) / (TOP_MAX * freq);
        }
```

Then it will work fine for overclockers and without using 64-bit arithmetic for everyone else.  If that looks good to you, I'll push an update.

We will need it in a few places, including this pre-existing one:

https://github.com/micropython/micropython/blob/8f33e1dc968bcec739f12d7a0acbf02ff2958c52/ports/rp2/machine_pwm.c#L103-L109

**Comment by robert-hh** [comment]
That should be faster, because there is not call to a ulldivmod function (or the like),  but it will add probably more code. So let's just wait if there a comments from @jimmo or Damien.

**Comment by dpgeorge** [comment]
Thanks for this improvement, it's definitely a lot better than what I wrote originally.  I didn't realise my iterative algorithm was that bad :joy: 

Re 32-bit overflow for large sysclk: I think we should fix this so the code supports larger CPU frequency.  But as noted above there are a few existing places that need fixing as well.  Using `uint64_t` is definitely the simplest way to fix those overflows, but it will slow down the calculation.

Maybe we can have a general helper function like this:
```c
uint32_t safe_div(uint32_t offset, uint32_t denom) {
    uint32_t source_hz = clock_get_hz(clk_sys);
    if (source_hz > 268000000) {
        return (16 * (uint64_t)source_hz + offset) / denom;
    } else {
        return (16 * source_hz + offset) / denom;
}
```

@pdg137 do you want to try fixing the overflows?  If you do, please do it as a separate commit.  Otherwise, we can merge this PR as-is and fix it in a separate PR.

**Comment by pdg137** [comment]
Okay! I added a function like you suggested, and I think I fixed up all the places with overflow issues. I took the liberty of adding rounding to the `duty_ns` functions to make them more accurate while I was at it.

For the name I picked `get_slice_hz` since `slice_hz` was already used elsewhere in the code for basically the same thing, and it seemed kind of meaningful. If anyone sees anything else to fix, please let me know! 🎄

**Comment by robert-hh** [comment]
The change looks good in the measurement.  I just picked a few frequencies, like around 1907/1908, and for machine.freq() below and above 268MHz. The monotonic behavior is maintained, and frequencies are fine beyond 268Mhz.

**Comment by dpgeorge** [comment]
Thanks for the improvements, very good!

**Pull request merged**
