### PR TITLE
ports/esp8266/modules/webrepl_setup: New password message with information about password size range allowed.

### PR DESCRIPTION
**Pull request by iha**
This PR makes the information about password size range allowed explicit. I found this information because I read de micropython source code.

### CODE REVIEW

**Comment by dpgeorge** [comment]
It looks good (saves the user guessing how many chars are valid by repeated attempts), but I suggest to shorten the message to something like `"New password (between 4 and 9 chars):"`.

**Comment by iha** [comment]
@dpgeorge , I agree. The last commit goes with your suggestion.

**Comment by pfalcon** [comment]
I'd suggest to shorten it to "New password (4-9 chars):".

**Comment by iha** [comment]
I rewrote the code to make it more concise.

**Comment by dpgeorge** [comment]
Thanks for updating the patch, it's been merge in 1b7d6a795149588eb44c1b33dd7c34fe6669460a with a minor change to put back the "chars" word in the message, because "4-9" on its own is a bit cryptic.

**Pull request closed without merging**
