### PR TITLE
update cmake support

### PR DESCRIPTION
**Pull request by TakashiKusachi**
This fix adds support for CMAKE generator expressions in include paths and definitions.

If _arg in the modified foreach syntax is composed of generator expressions, then
e.g. $<$<config:Debug>:DEBUG=1>.
MICROPY_CPP_FLAGS will contain -D. This will result in an error in gcc.

Therefore, a fix is needed to use generator expressions and not generate it if it is empty.

### CODE REVIEW

**Comment by TakashiKusachi** [comment]
My environment
OS : Windows 10
CMAKE : 3.21.4
gcc : arm-none-eabi-gcc.exe (GNU Arm Embedded Toolchain 10-2020-q4-major) 10.2.1 20201103 (release)

**Comment by dpgeorge** [comment]
Thanks for the contribution.  But you can see from the zephyr CI that this is broken:
```
CMake Error at /micropython/py/mkrules.cmake:96 (add_custom_command):
  Error evaluating generator expression:

    $<STREQUAL:MP_CONFIGFILE=<mpconfigport_minimal.h>

  $<STREQUAL> expression requires 2 comma separated parameters, but got 1
  instead.
Call Stack (most recent call first):
  CMakeLists.txt:119 (include)


CMake Error at /micropython/py/mkrules.cmake:70 (add_custom_command):
  Error evaluating generator expression:

    $<STREQUAL:MP_CONFIGFILE=<mpconfigport_minimal.h>

  $<STREQUAL> expression requires 2 comma separated parameters, but got 1
  instead.
Call Stack (most recent call first):
  CMakeLists.txt:119 (include)
```

**Comment by TakashiKusachi** [comment]
Thank you.
I did find out that there was a problem with this fix. And today I found out that there is another problem with this one.
It seems that what was preventing this fix from working was the fact that I couldn't use <> in CMAKE's generator expressions.
Another problem I found today is that I can't apply the library definitions that ${MICROPY_TARGET} depends on to the qstr preprocess.

I don't know a smart way to deal with this problem.
I will close this request tomorrow.

Translated with www.DeepL.com/Translator (free version)

**Comment by dpgeorge** [comment]
I'm not experienced enough with CMake to know how to solve this issue.

**Comment by TakashiKusachi** [comment]
I am addressing the second issue as follows.

``` c {.line-number}
get_target_property(libraries ${MICROPY_TARGET} LINK_LIBRARIES)
foreach(_lib bsp_lib;bsp_lib_core;lwesp)
    get_property(include TARGET ${_lib} PROPERTY INCLUDE_DIRECTORIES)
    get_property(definitions TARGET ${_lib} PROPERTY COMPILE_DEFINITIONS)
    get_property(option TARGET ${_lib} PROPERTY COMPILE_OPTIONS)
    get_property(inter_include TARGET ${_lib} PROPERTY INTERFACE_INCLUDE_DIRECTORIES)
    get_property(inter_definitions TARGET ${_lib} PROPERTY INTERFACE_COMPILE_DEFINITIONS)
    get_property(inter_option TARGET ${_lib} PROPERTY INTERFACE_COMPILE_OPTIONS)

    list(APPEND MICROPY_CPP_INC_EXTRA  ${include})
    list(APPEND MICROPY_CPP_DEF_EXTRA  ${definitions})
    list(APPEND MICROPY_CPP_FLAGS_EXTRA  ${option})
    list(APPEND MICROPY_CPP_INC_EXTRA  ${inter_include})
    list(APPEND MICROPY_CPP_DEF_EXTRA  ${inter_definitions})
    list(APPEND MICROPY_CPP_FLAGS_EXTRA  ${inter_option})
endforeach()
```

It scans the libraries registered in ${MICROPY_TARGET} and gets the options etc. from each library.

The second line should originally contain ${libraries}. 
However, I used
```
target_link_libraries(${MICROPY_TARGET} PUBLIC bsp_lib bsp_lib_core lwesp -lc -lm -lgcc)
```
that doesn't work because -lc -lm -lgccin it.

Then, the next line may not be necessary.
```

    get_property(include TARGET ${_lib} PROPERTY INCLUDE_DIRECTORIES)
    get_property(definitions TARGET ${_lib} PROPERTY COMPILE_DEFINITIONS)
    get_property(option TARGET ${_lib} PROPERTY COMPILE_OPTIONS)

    list(APPEND MICROPY_CPP_INC_EXTRA ${include})
    list(APPEND MICROPY_CPP_DEF_EXTRA ${definitions})
    list(APPEND MICROPY_CPP_FLAGS_EXTRA ${option})
```

Translated with www.DeepL.com/Translator (free version)

**Pull request closed without merging**
