### PR TITLE
docs: Replace "umodule" with "module" everywhere.

### PR DESCRIPTION
**Pull request by jimmo**
The "import module" vs "import umodule" is something of a FAQ, and it comes up on the forum and when I'm teaching MicroPython in-person.

In summary -- my experience has been that most people don't care about the subtle distinction between "uos" and "os". I understand and agree with the argument that the "u" is a reminder that it's the "micro" version, but I don't think it outweighs the confusion. It's one of the first things that you see in the documentation, but I don't think it's one of the first things you need to know as a beginner MicroPython programmer. Your existing Python code should just work, and the MicroPython documentation should match the idiomatic way to write code.

I think since #5241 was merged, we're in quite a good situation:
 - People can consistently use "import foo" across all ports. (with the exception of the minimal ports)
 - The ability to override/extend via "foo.py" continues to work well.

This PR updates the documentation such that:
 - All ufoo.rst is now foo.rst
 - Updates all internal references in the docs to exclusively use "foo" not "ufoo".
 - Updates library/index.rst to simplify the explanation of module naming and move the "ufoo" part to an extra detail at the end for people who care.

Note: the replacements were done with a quick script, so they aren't perfect and will need some manual fixups (e.g. I can see that the very first diff is "requests" which should probably be still "urequests"...). But before I do the manual cleanup, I'd like to get some feedback on whether people think this is a worthwhile change.

Refs:
 - Recent forum thread: https://forum.micropython.org/viewtopic.php?f=2&t=7102
 - #5241 which made the ufoo->foo aliasing consistent on all ports.

### CODE REVIEW

**Comment by MrSurly** [comment]
Last I checked (a while ago), the Unix port did not have aliases for <module> --> <umodule>

**Comment by jimmo** [comment]
> Last I checked (a while ago), the Unix port did not have aliases for <module> --> <umodule>

This was implemented in #5241

The existing weak links system (used on STM32/ESP32/ESP8266) was replaced with an automatic rule to alias foo to ufoo if it exists (now enabled on most ports).

**Comment by MrSurly** [comment]
> This was implemented in #5241

Okay then. =)

**Comment by hoihu** [comment]
completly agree with the arguments, +1. 

And after all we do have a „micro“ - in „micropython“ (or „upy“) so we still have the „u“ 😉. I just wished upy would have been chosen rather than mpy.

**Comment by tannewt** [comment]
Has there been any discussion about moving non-standard APIs out of modules that share a name with CPython? Managing filesystems (http://docs.micropython.org/en/latest/library/uos.html?highlight=uos#filesystem-mounting) is one example. In CircuitPython, we moved these APIs to a separate `storage` module. That way code written in MicroPython will then work in CPython.

**Comment by dpgeorge** [comment]
> Has there been any discussion about moving non-standard APIs out of modules that share a name with CPython? Managing filesystems  is one example

There was some related discussion about a "storage" module in https://github.com/micropython/micropython/pull/4772#issuecomment-491137274

I do understand the arguments for doing this, moving non-CPython stuff out of CPython-named modules.  But it's not easy.  For example, what about `time.sleep_ms()`, `time.ticks_ms()` and `uzlib.DecompIO` (none of those exist in CPython)?  And also minor additions like extra args to existing CPython functions/methods.  In the end a u-module is not a strict subset of the corresponding CPython module but rather has a (large) overlap with it, and so one can write Python code that runs under both CPy and uPy that uses only the overlap.

Moving all the uPy-specific filesystem stuff out of `uos` into a uPy-specific module is pretty easy to do (and make backwards compatible), and may be a good idea, something to look in to.  But some of the other stuff is much harder to separate.

**Comment by mzdaniel** [comment]
For learnability and aesthetics perspective, simplifying namespaces is a big +1. As Jimmo mention and as instructor myself, using "module" everywhere instead of "umodule" is important while teaching Python. For example, a bicycle is not expected to acelerate as much as an airplane, but the aceleration concept is the same regardless of the name.

Compatibility wise, it isn't a particularly pleasant experience to have to wrap code in try/except blocks for obvious namespaces just to 'teach' the computer where to find the functionality people need, making code much harder to read, write, and reason about.

**Comment by jimmo** [comment]
I have rebased this and sorted out the manual fixups. Also a bit of a reword of the overview in `library/index.rst`.

The two remaining u-libraries mentioned in the docs are `uctypes` (which has almost no overlap with `ctypes`) and `ureqests`. The former I suggest we rename to `ntypes` or `native` or something (leaving uctypes as an alias) in a separate PR, and `urequests` is in `micropython-lib` anyway and not subject to weak links.

One thing I just realised is that we're now going to break any existing docs links to the `latest` tag. e.g. https://docs.micropython.org/en/latest/library/uos.html is now https://docs.micropython.org/en/latest/library/os.html   I guess three options (in order of preference):
 - Add placeholder/redirect ufoo.rst --> foo.rst
 - Only rename the content, not the files
 - Do nothing, the 404 page gives a link back to the docs home page.

**Comment by dpgeorge** [comment]
> Add placeholder/redirect ufoo.rst --> foo.rst

I should be able to do this on the server side.

**Comment by jimmo** [comment]
> I should be able to do this on the server side.

It's weak links all the way down :)

Thanks, sounds perfect.

**Comment by dpgeorge** [comment]
Merged in 218606351c6f9688a3f90dad791bcb2109adcf1b through d7fbc755dc208be0d252afb379ab4e9880a2b693

**Pull request closed without merging**
