### PR TITLE
Apply clang-format to format all code (v1)

### PR DESCRIPTION
**Pull request by jimmo**
Per discussion in #4223, here is a 1st attempt at reformatting the code using clang-format.

The major difference is that this requires dedenting all #if / #endif. I have used `// clang-format off` in a few key places where it hurts readability (nlr.h, persistentcode.h).

The Python script has a couple of `sed` expressions that make a few MicroPython-specific fixups (spaces inside `{ struct initialisation }` and `(foo*)expr` casting (although I think clang-format's default behavior for the latter (i.e. `(foo *)expr`) is actually more consistent with the `int *foo` style we use. (Note that it also adds the space in `m_new0(uint16 *, ...)`).

I've fully expanded the config file (using --dump-config) so it's clearer to see what all the options are.

I'd love to figure out how to make the enums do the right thing (especially for the args lists). Overall though, this fixes a lot of things, and other than the dedented `#if` everything seems pretty minor and very consistent.

### CODE REVIEW

**Comment by dpgeorge** [comment]
I guess first thing is to fix the compile errors...!

> and `(foo*)expr` casting (although I think clang-format's default behavior for the latter (i.e. `(foo *)expr`) is actually more consistent with the `int *foo` style we use. (Note that it also adds the space in `m_new0(uint16 *, ...)`).

I'd be happy to just let clang-format do its thing here and not fix that up with sed.

**Comment by jimmo** [comment]
> I guess first thing is to fix the compile errors...!

Woah... some suprises from clang-format there. Fixed with `// clang-format off` in bc0.h and parse.c (which was probably the right thing to do anyway for readability).

> 
> > and `(foo*)expr` casting (although I think clang-format's default behavior for the latter (i.e. `(foo *)expr`) is actually more consistent with the `int *foo` style we use. (Note that it also adds the space in `m_new0(uint16 *, ...)`).
> 
> I'd be happy to just let clang-format do its thing here and not fix that up with sed.

Great. Fixed.

**Comment by dpgeorge** [comment]
Looking through this diff, the majority of changes are one of the following:
- in a macro, an identifier in parenthesis that's followed by `&` will have no space around the `&`, eg `(x)&0xff`
- space placed before pointer `*` for casting, eg `(mp_int_t *)ptr`
- all #'s (ie preprocessor directives) dedented to start at column 1
- no space between braces in initialiser, eg `{&mp_type_type},` (there's an additional `sed` step added in `codeformat.py` to put these back, because clang-format changes a lot of lines with this rule, but this `sed` should probably be removed for consistency)
- single line statements reformatted to be on multiple lines (eg single-line cases, single-line inline functions)
- end-of-line comments are aligned with surrounding lines' comments
- comments that appear just before a # line are also dedented fully to remain aligned with the dedented # line
- #define's have their value aligned with surrounding lines
- named initialiser's values are unaligned

In total about 10% of lines are changed.

**Comment by dpgeorge** [comment]
Closed in favour of #5700.

**Pull request closed without merging**
