### PR TITLE
Brendan/olimex e407 hwconfig

### PR DESCRIPTION
**Pull request by BrendanSimon**
Please pull this branch which has the following changes.
* hwconfig module for Olimex E407 board.
* example of fading a LED, and flashing if button pressed, using uasyncio.

### CODE REVIEW

**Comment by BrendanSimon** [comment]
Hi.  Just wondering if I've done this pull request correctly and maintainers have been notified.  Is the pull request ok?
Thanks, Brendan.

**Comment by pfalcon** [comment]
@BrendanSimon , at the very least please squash "fixes" commit into "uasyncio example" commit. Also, things like `#=======` are superfluous.

And otherwise, all existing hwapi/ examples were added to structurize further work on Hardware API, e.g. https://github.com/micropython/micropython/issues/2603 . None of the current 5 examples works as expected with the current MicroPython. And there's clear pushback against letting MicroPython work nicely and correctly with these examples and having nice HW API. So, I'm as the author of those examples, not even sure about their further fate.

**Comment by BrendanSimon** [comment]
Sorry about the `#====` lines.  I find it easier to see where all the functions start/end (which to me is a benefit), but understand that's just my personal preference and happy to remove them to stick to the micropython conventions.

Reading #2603 I get the impression that using `Signal` instead of `Pin` is the preferred way to use the Hardware API.  Is that correct?

As the examples currently use Pin, instead of Signal, is this the reason for the pushabck you mention?

I am using the latest micropython (git master), and the examples were committed post v1.8.6, so I assumed they were the way forward.  If that is not the case, then what is the way forward for using the Hardware API?

**Comment by BrendanSimon** [comment]
I've squashed the commits for the uasyncio example as suggested.

I've deleted the branch on my fork, and re-pushed the branch (hope that works ok with this pull request?)

Happy to make other changes (Signal, etc) on advice.

Thanks, Brendan.

**Pull request closed without merging**
