### PR TITLE
tools: Allow pyboard.py to work when boot.py prints things.

### LINKED ISSUE #1491: pyboard.py fails to enter raw_repl if boot.py prints anything
If my boot.py looks like:

```
import pyb
uart = pyb.UART(6,115200)
pyb.repl_uart(uart)
print("REPL is also on UART 6 (Y1=Tx Y2=Rx)")
```

then when I do a Control-D I see:

```
PYB: sync filesystems
PYB: soft reboot
REPL is also on UART 6 (Y1=Tx Y2=Rx)
Micro Python v1.4.5-143-gdcbe936-dirty on 2015-09-22; PYBv1.0 with STM32F405RG
Type "help()" for more information.
```

However, when I then try to use pyboard.py to run a simple hello.py program which just does:

```
print('Hello World')
```

then I get the following error:

```
518 >./pyboard.py hello.py 
OK
PYB: sync filesystems
PYB: soft reboot
REPL is also on UART 6 (Y1=Tx Y2=Rx)
raw REPL; CTRL-B to exit
>
could not enter raw repl
```

It seems that pyboard.py ONLY works if boot.py doesn't print anything at all, and main.py exits to the REPL.

It occurred to me, that we might not boot.py to run at all when entering the raw-repl or that we might want boot.py to run in a different mode.

For example, when I used the boot-switch.py boot.py file (https://github.com/dhylands/upy-examples/blob/master/boot_switch.py) with rshell, then it would go through the whole complicated flash the leds and have to wait for the timeout multiple times for each command executed.

So then I thought maybe it would be nice to have some way for boot.py to know that it was being run to enter a raw-repl versus a regular repl. The way the code is currently structured this isn't really possible. The one way I could think of doing it would be to make a Control-D variant which did a soft-reboot, but with an implied enter raw repl. Then we could set something for boot.py to use, and it could choose to do a simplified initialization and perhaps not bother executing main.py etc.

So I thought I put this up for discussion to see what opinions others had.

### PR DESCRIPTION
**Pull request by dhylands**
rhsell now works properly when boot.py prints something.

fixes #1491

### CODE REVIEW

**Comment by dhylands** [comment]
The build failure here seems to be unrelated to pyboard.py (qemu)

**Comment by dpgeorge** [comment]
I know I've had a lot of problems in the past trying to get pyboard.py to sync correctly on soft reboot, and so would be reluctant to change this.  But, this patch looks very neat and I can't see how it would break any existing behaviour.  What tests did you do?

**Comment by dhylands** [comment]
I ran the pyboard tests ```./run-tests --target pyboard```, with and without the patch, and with and without a print in boot.py.

Without the patch and with a print in boot.py, it hangs immediately.

For the other 3 cases, I get one of 2 results:

After a hard reset, I get this result:
447 passed, 11 skipped, 1 failure (pyb1)

If I don't do the hard reset and just run the tests a second time, then I get:
446 passed, 11 skipped, 2 failures (pyb1, halerror)

It doesn't matter whether I'm running with or without the patch, I observe the above.

**Comment by dpgeorge** [comment]
Running the pyboard tests, they all succeed for me (with and without this patch).

Merged in 519cef813eff8a44d8f112cce5bcb07008ddbc98

**Pull request closed without merging**
