### PR TITLE
top: Refactor makefile variables and dependencies.

### PR DESCRIPTION
**Pull request by jimmo**
I'm working on a bigger change to standardise networking across ports, and noticed by accident that the mimxrt port was including a lot of lib files unnecessarily in the QSTR generation. While fixing that I ended up pulling a much longer piece of string.

This has the following goals:
 - Remove all handling of extmod and user-c-modules from port Makefiles (i.e. ports can now just set the required variables for what they want, and only `include $(TOP)/extmod/extmod.mk`).
 - Related, simplify extmod configuration for bluetooth, wiznet, cyw43.
 - Make `GIT_SUBMODULE` handling for extmod components handled in extmod.mk.
 - Remove unnecessary files from SRC_QSTR in a few ports (mainly mimxrt, samd, nrf) by breaking up SRC_C into smaller variables reflecting what types of files they are (e.g. lib, drivers, etc).
 - Make the gen-pin-qstr handling more similar across ports. (No effect, but it related to the SRC_C change).

_This work was funded through GitHub Sponsors._

### CODE REVIEW

**Comment by jimmo** [comment]
One of the main things I wanted to fix here was that the `MOD` variables meant two different things. One is user-c-modules, and the other is port-specific modules. This got complicated when extmod was mixed in. I think this is a lot clearer now, mostly because the port Makefile no longer has to know about either extmod or user-c-modules, and is free to use `*_MOD_*` as it see fits.

**Comment by dlech** [comment]
This seems like it should be split up in to multiple commits (it is changing quite a few unrelated things). 

It seems like there are potentially breaking changes here. To what extent might users have to change their external makefiles?

**Comment by jimmo** [comment]
> This seems like it should be split up in to multiple commits (it is changing quite a few unrelated things).

I guess the main way to split it is:
1) general fixups (e.g. changing = to +=, rename SRC_QSTR to SRC_QSTR_C)
2) extmod + bluetooth
3) user c module
4) port-specific fixes (e.g. splitting out SRC_C in mimxrt)

> It seems like there are potentially breaking changes here. To what extent might users have to change their external makefiles?

For a user c module, the intent is not at all.

For an out-of-tree port that doesn't use extmod or user c modules, no change. In many cases, if they continue to reference the EXTMOD_SRC_C and SRC_MOD variables there shouldn't be any problem.

The main thing is the rename of `SRC_QSTR` to `SRC_QSTR_C`. I can revert that part I guess.

**Comment by jimmo** [comment]
@dlech I have split this up into 9 commits, and removed the rename of SRC_QSTR. This should mean that an out-of-tree makefile will just continue working (but now harmlessly reference some now-unset variables: `SRC_MOD` and `CFLAGS_MOD`).

I've updated the original PR description.

> But perhaps one thing we could do better is add a migration/upgrade section (with a heading so it is easy to find) to the release notes

Yes, good idea! There's a few things in this release that warrant it.

**Comment by dlech** [comment]
It is much easier to follow the changes now that it is split up. Thanks.

**Pull request closed without merging**
