### PR TITLE
extmod/framebuf: Add circle() method

### PR DESCRIPTION
**Pull request by mcauser**
Leading on from #2367 and its new `framebuf1_setpixel()` and `framebuf1_getpixel()` methods.
~~Untested - currently experiencing compile issues~~

### CODE REVIEW

**Comment by deshipu** [comment]
Thank you for working on it, I had something similar in plans.

I'm not sure if it's a good idea to have the same code repeated for every possible framebuffer type (I have a PR that adds a 16-bit framebuffer https://github.com/micropython/micropython/pull/2364 and at some point we might be adding more), and to have the high-level drawing functions in the framebuf module directly.

I think it would be much better to have them in a separate `Canvas` class, that would take a display or framebuf object as a parameter during creation, and that would use a number of basic methods on those objects (such as `pixel()`, `hline()`, `vline()`, `fill_rect()`, added in https://github.com/micropython/micropython/pull/2366) to implement the drawing commands in a more general manner. It could be written either in C or Python, but it should be calling the Python API then, so that you can use it with display drivers written in Python. Because `hline` and `vline` draw a bunch of pixels at once, it should still be fairly fast, and with this general API, it could support displays that are too big to fit into framebuffer in memory.

What do you think?

**Comment by deshipu** [comment]
Example code could then look like this:

```
display = SSD1306_I2C(128, 128, i2c)
canvas = Canvas(display.framebuf)
canvas.circle(64, 64, 32, 1)
display.show()
```

**Comment by pfalcon** [comment]
I wanted to gave that warning seeing @deshipu's patches, but it won't be required, but of course it is: before you guys duplicate something like https://github.com/olikraus/u8glib or some other existing graphics library, please think if that's what you want to do - spend a lot of time writing something written bunch of times already.

**Comment by mcauser** [comment]
I agree. Was committing some old uncommitted code as I noticed you were working in the same area of the codebase.

I think something along the lines of these:

```
.line(x0, y0, x1, y1, color)
.rect(x, y, w, h, color)
.fill_rect(x, y, w, h, color)
.circle(x0, y0, radius, color)
.fill_circle(x0, y0, radius, color)
.triangle(x0, y0, x1, y1, x2, y2, color)
.fill_triangle(x0, y0, x1, y1, x2, y2, color)
.round_rect(x0, y0, w, h, radius, color)
.fill_round_rect(x0, y0, w, h, radius, color)
.invert(bool)
.invert(x, y, w, h)
.bitmap(x, y, bitmap, w, h, color)
.copy(x0, y0, w0, h0, x1, y1)
.move(x0, y0, w0, h0, x1, y1, color)
```

**Comment by mcauser** [comment]
circles

Works :)

**Comment by deshipu** [comment]
> before you guys duplicate something like https://github.com/olikraus/u8glib or some other existing graphics library

Well, we don't have much choice here, do we? We can't simply replace everything that you have already implemented here with u8glib -- you have made a lot of API decisions that are fundamentally incompatible with anything out there, so we would break people's programs and drivers (even though u8glib was voted as the 4th most popular feature request). Fortunately, all those algorithms for drawing shapes are really basic and well understood, so implementing them in Python is not really that much work.

**Comment by deshipu** [comment]
On a more practical note, the u8glib library only supports a fraction of the displays that we already have drivers for in MicroPython. It would be strange and sad to only have a few selected displays supported fully (with all the graphical operations), and the rest only having a basic pixel and fill operations. With this approach, we support all the displays that have drivers, and any additional ones that get their drivers written in the future -- and you can write the drivers in python.

**Comment by dpgeorge** [comment]
Regarding u8glib: that library is as much about the low level display driver (implemented in C) as it is the higher level drawing operations.  If we wanted to use u8glib but allow to plug in a Python low-level driver then we'd be working against that library and discarding more than half of it.

There's also http://ugfx.io/index.html which was used in the uPy EMF badge https://github.com/emfcamp/micropython, but it doesn't have a compatible license (only free for hobby use).

From the Python side remember that there is PIL and Pillow and maybe we can implement a subset of that module for high level graphics operations.

**Pull request closed without merging**
