### PR TITLE
docs/pyboard: Clarify files on pyboard

### PR DESCRIPTION
**Pull request by vlowe**
Text and formats have been simplified.

Note: formatting for me and @jimmo appear different to the website version as shown in the screenshots below.

**When compiled on my laptop:**
local

**Website**:
image

### CODE REVIEW

**Comment by dpgeorge** [comment]
> appear different to the website version

That's most likely because you don't have the theme installed; grep for `sphinx_rtd_theme`

**Comment by vlowe** [comment]
I have these within my `pip freeze`

>Sphinx==2.1.2
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3

**Comment by dpgeorge** [comment]
> I have these within my `pip freeze`

Ok, so it looks like you have the correct theme.  Well, the style doesn't really matter, as long as the content is correct.

**Comment by dpgeorge** [comment]
Thanks for this, merged in 6592a30f4b6ed056411361d0c703fe814886e65b with an additional line added to describe the README.txt file.

**Pull request closed without merging**
