### PR TITLE
esp8266: add support for WiFi radio sleep

### PR DESCRIPTION
**Pull request by dpgeorge**
If/when no WLAN interfaces are active (ie both STA and AP are inactive), the device will automatically go into radio sleep mode, which reduces current of the device by about 55mA.  Addresses #4295

### CODE REVIEW

**Comment by dpgeorge** [comment]
@pacmac if you could please test this that would be great!

**Comment by pacmac** [comment]
Confirmed, power drops by 53ma when disabling both STA and AP:

```
WLAN(0).active(0)
WLAN(1).active(0)
```

Damien, thanks soo much, this opens up a lot of opportunities where low power and wifi is not needed, but will also help where wifi is needed but can be disabled.

**Comment by dpgeorge** [comment]
Thanks for testing.  Does it remain in the low power state on hard reset if the interfaces were previously disabled?

**Comment by pacmac** [comment]
Yes, tried both reset button and remove / re-apply power and it's still running in low power.

**Comment by profra** [comment]
@dpgeorge Fulfilled dream, wonderful message, thank you very much!!!
@dpgeorge @pacmac I will test it very soon and I have only one question... is current esp-open-sdk from GitHub suitable for the build or one needs another SDK version?

**Comment by diginfo** [comment]
> is current esp-open-sdk from GitHub suitable for the build or one needs another SDK version?

Yes, it works with the current SDK version, no need to upgrade.

**Comment by dpgeorge** [comment]
Note that this feature also lets the radio sleep while connected to a WiFi access point when there is no traffic.  Reduction in current in such a situation is about 50mA.

**Comment by robert-hh** [comment]
Yes, that's what I've seen when I just tested it with an Wemos D1 Mini. With WiFi, current about 80 mA, in sleep about 25 mA, and when connected and just listening about 25 mA most of the time with short peaks of 80 mA.That's very good.

**Comment by peterhinch** [comment]
This sounds almost too good to be true :) Are there really no tradeoffs?

**Comment by dpgeorge** [comment]
>  Are there really no tradeoffs?

The modem sleep while connected to an AP is most likely a sleep between DTIMs from the AP, which usually come every 100ms (so sleep for about 95ms, wake for 5ms to turn on modem and receive).  So it would introduce a latency in reception of an Ethernet frame of up to 100ms.  You can try pinging the device while it's doing this DTIM sleep to see how it responds.

**Comment by peterhinch** [comment]
With firmware built from today's source and on the reference board I'm still getting a hard reset if I disable both interfaces.
```
PYB: soft reboot
MicroPython v1.9.4-703-g7f948a5-dirty on 2018-12-03; ESP module with ESP8266
Type "help()" for more information.
>>> from network import WLAN
>>> 
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== WLAN(0).active(0)
=== WLAN(1).active(0)
=== 
pm close 7
fpm open,type:2 0
fpm 758

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 30964, room 16 
tail 4
chksum 0x1d
load 0x3ffe8000, len 1084, room 4 
tail 8
chksum 0xdc
load 0x3ffe8440, len 808, room 0 
tail 8
chksum 0xe2
csum 0xe2
����n��r��n|�
               l
                lll`��r�l�l�


                              l`��r�l�l�


                                          l`��r�l
                                                  �

                                                   ll`rlrl����b
                                                                ��b�b
                                                                     br�
                                                                          b��n���
MicroPython v1.9.4-703-g7f948a5-dirty on 2018-12-03; ESP module with ESP8266
Type "help()" for more information.
>>> scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 

connected with misspiggy, channel 3
dhcp client start...
ip:192.168.0.19,mask:255.255.255.0,gw:192.168.0.1
pm open,type:2 0

>>> 
```
Re ping times, with AP disabled and Station mode enabled I'm getting response times similar to before the change:
```
$ ping 192.168.0.19
PING 192.168.0.19 (192.168.0.19) 56(84) bytes of data.
64 bytes from 192.168.0.19: icmp_seq=1 ttl=255 time=25.1 ms
64 bytes from 192.168.0.19: icmp_seq=2 ttl=255 time=45.5 ms
64 bytes from 192.168.0.19: icmp_seq=3 ttl=255 time=70.5 ms
64 bytes from 192.168.0.19: icmp_seq=4 ttl=255 time=90.5 ms
64 bytes from 192.168.0.19: icmp_seq=5 ttl=255 time=116 ms
64 bytes from 192.168.0.19: icmp_seq=6 ttl=255 time=2.48 ms
64 bytes from 192.168.0.19: icmp_seq=7 ttl=255 time=5.24 ms
64 bytes from 192.168.0.19: icmp_seq=8 ttl=255 time=1.80 ms
64 bytes from 192.168.0.19: icmp_seq=9 ttl=255 time=2.14 ms
64 bytes from 192.168.0.19: icmp_seq=10 ttl=255 time=3.82 ms
64 bytes from 192.168.0.19: icmp_seq=11 ttl=255 time=1.77 ms
64 bytes from 192.168.0.19: icmp_seq=12 ttl=255 time=4.24 ms
64 bytes from 192.168.0.19: icmp_seq=13 ttl=255 time=2.17 ms
64 bytes from 192.168.0.19: icmp_seq=14 ttl=255 time=3.04 ms
64 bytes from 192.168.0.19: icmp_seq=15 ttl=255 time=2.90 ms
```

**Comment by robert-hh** [comment]
When testing 3 days ago, it worked. Now both a Wemos D1 Mini and a Huzzah ESP8266 Feather crash most of the time, but not always.

MicroPython v1.9.4-701-g10bddc5c-dirty on 2018-12-01; ESP module with ESP8266
Type "help()" for more information.
and
MicroPython v1.9.4-703-g7f948a56-dirty on 2018-12-03; ESP module with ESP8266
Type "help()" for more information.

**Comment by dpgeorge** [comment]
> With firmware built from today's source and on the reference board I'm still getting a hard reset if I disable both interfaces.
> 
> paste mode; Ctrl-C to cancel, Ctrl-D to finish
> === WLAN(0).active(0)
> === WLAN(1).active(0)
> 
pm close 7
fpm open,type:2 0
fpm 758
```
Yes I can confirm that it crashes with this code if WLAN(0) is connected to an AP.  It probably needs some delay to first disconnect before entering power save mode.

> When testing 3 days ago, it worked. Now both a Wemos D1 Mini and a Huzzah ESP8266 Feather crash most of the time, but not always.

@robert-hh can you please detail the crash: is it when deactivating both interfaces (STA and AP), or when it's in power saving mode while connected to an AP?

**Comment by robert-hh** [comment]
@dpgeorge It works now for both devices.

**Comment by robert-hh** [comment]
About Ping times: I see the same pattern as @peterhinch. After a sequence of slow responses the ping times go down. During the slow responses, the power consumption is still low, while it goes up to the high value in the fast response phase. After stopping pings, the power consumption will drop again within a second.
For the initial test, ping is done once-per-second. If I call ping slower, like once every 5 seconds, then ping times vary between <5ms and >100 ms, which is the expected behavior.

**Comment by dpgeorge** [comment]
> It works now for both devices.

That's great, thanks for testing.

> After a sequence of slow responses the ping times go down. During the slow responses, the power consumption is still low, while it goes up to the high value in the fast response phase. After stopping pings, the power consumption will drop again within a second.

Sounds like the device decided that there is enough traffic to go into high-throughput mode, ie turn off sleep.  Then it goes back to sleep when the traffic is gone.

> For the initial test, ping is done once-per-second. If I call ping slower, like once every 5 seconds, then ping times vary between <5ms and >100 m

If the ping interval is short, eg 0.2s, then it might go into high-throughput mode earlier.

**Comment by spacemanspiff2007** [comment]
Will this work for ESP32, too?

**Comment by spacemanspiff2007** [comment]
Thank you for your quick reply!

**Pull request closed without merging**
