### PR TITLE
Soft reboot into friendly REPL, to allow to back soft reboot by hard reboot

### PR DESCRIPTION
**Pull request by pfalcon**
RFC patch for https://github.com/micropython/micropython/issues/3030

### CODE REVIEW

**Comment by pfalcon** [comment]
If it's ok, will update all other ports.

**Comment by pfalcon** [comment]
Updated all ports. This should be ready to merge.

**Comment by dhylands** [comment]
Prior to this change, if my pyboard was running a main,py (I tested using the following main.py):
```
import pyb

tick = 0
led = pyb.LED(4)    # 4 = Blue
while True:
    if tick <= 3:
        led.toggle()
    tick = (tick + 1) % 10
    pyb.delay(100)
```
Then I could use pyboard.py to run arbitrary files. Let's suppose I have hello.py with a simple:
```
print('hello')
```
and while the blue LED was blinking I could run:
```
../tools/pyboard.py hello.py
```
and the blue led program would stop, a soft reset would occur and then hello.py would run.

With the change proposed in this PR, when I now try to run hello.py then it doesn't run. It just runs main.py and never interrupts it.

**Comment by pfalcon** [comment]
Aha, so that's why reboot in raw repl stays in raw repl - apparently, in such case main.py isn't run. Crazy. So, the only solution is to make pyboard.py recognize both friendly and raw repl after "soft" reboot.

**Comment by dpgeorge** [comment]
> apparently, in such case main.py isn't run

Yes.  See #2940 and #2936 for related discussion.

**Comment by dpgeorge** [comment]
As discussed, this will break behaviour of entering raw REPL with a main.py.

**Pull request closed without merging**
