### PR TITLE
tools: Add script to build multiple configs of int and float types

### PR DESCRIPTION
**Pull request by doogle**
Both 32-bit and 64-bit binaries are built for all combinations of:
- none, longlong, and multiprecision ints
- single and double precision floats

### CODE REVIEW

**Comment by dpgeorge** [comment]
I'm in 2 minds about this PR.  On the one hand it's useful for testing.  On the other, it's very niche and won't be used often.  Furthermore, it only adds convenience not functionality.  I'd prefer to aim to keep the entire repository as "micro" as possible so am leaning towards not merging this PR.  Any objections?

**Comment by doogle** [comment]
That is absolutely fine with me! :-)

Tbh I never really wanted this to become an actual PR, and instead this was just a 'show your working' thing, as there was some interest in this after I mentioned it in passing.
I definitely agree with you that this shouldn't be merged... it's a bit too specialised towards one type of test-case (ie. for when I was working on features that required testing with each of the different integer types) and it was always just a Quick-and-Dirty hack. This is something I'd expect a developer to knock up if-and-when needed (as I did), rather than something that should exist in the repo.

**Comment by dpgeorge** [comment]
@doogle thanks for comments!  I very much appreciate your work with the floating point code so don't get the wrong impression about discarding your work -- as you say it's easy for another dev to knock up when/if needed.

**Comment by doogle** [comment]
@dpgeorge no worries! I really don't see this as 'discarded work', no wrong impression got :-)

**Comment by pfalcon** [comment]
@doogle: Thanks for you reply. Your work was thorough and impressive, but I kinda hinted then that it's just one small issue, and there're gazillion of other small issues to tackle. I wonder if you still might be interested to contribute small, nice-rainy-weekend fixes to uPy... Here's on this weekend, I had another look into running as many as possible CPython stdlib modules on uPy. Here's quick fixes which came out of it: https://github.com/micropython/micropython/commit/1bc534247cfe585afeba41b58b25a21af158ae4e , https://github.com/micropython/micropython/commit/fdaac1dbf8109ec42b6bf63bfea9627ddc3e4920 .

Actually wait, the last one is exactly your realm, a float issue! ;-). I didn't want to add quick&dirty round to N (N>0) decimal places implementation using multiple/round/divide - without considering overflow issues. Maybe you'd be interested to look into that (and it shouldn't be perfect, just consider if/when overflow is possible, and if it makes sense to go potentially long way to have completely overflow-less impl vs just documenting which max N is guaranteed to produce valid result).

**Comment by doogle** [comment]
@pfalcon Sorry for the delay in replying, I was away and then really busy with work stuff (which has mainly consisted of arguing with GStreamer).

That definitely sounds like an interesting issue to tackle... I'll start looking into it. The multiply/round/divide approach is a nice way around the lack of ```round()```'s ability to round to any decimal place, but there should be a more concrete way of doing it.

And for sure, all this float stuff is just a small part of the project :-) It's been nice watching the progression of Micro Python in other areas as well, especially as it contains both a language runtime as well as low-level platform support and driver code, which makes for an interesting mix.

**Pull request closed without merging**
