### PR TITLE
ports/nxp: Plan to Integrate Micropython and NXP's MCU

### PR DESCRIPTION
**Pull request by Albort12138**
-Add nxp MIMXRT1064 port.
 -Enable sdcard lcd lpi2c pinmux led

### CODE REVIEW

**Comment by yanyao12138** [comment]
This PR tries to integrate Micropython and MIMXRT1064 MCU. The new submodule named as 'nxplib' was added to contain the copy the NXP MCUxpresso SDK. Currently, some basic feature was enabled(eg pinmux sdcard lpi2c littlevgl led). Since I am a new one to contribute to the community there are some mistakes. I will be grateful if some of you guys can give me some suggestions.

**Comment by dpgeorge** [comment]
Thanks for making the PR cleaner with the submodule.

I guess the first question is: what is the scope of this port, what variants of MCUs could it potentially target?  Is it just the MIMXRT1064, or all MIMXRTxxxx's, or also i.MX6/8?  The name of the port should reflect the MCUs that it supports, eg maybe this port should be called mimxrt?

**Comment by yanyao12138** [comment]
> Thanks for making the PR cleaner with the submodule.
> 
> I guess the first question is: what is the scope of this port, what variants of MCUs could it potentially target? Is it just the MIMXRT1064, or all MIMXRTxxxx's, or also i.MX6/8? The name of the port should reflect the MCUs that it supports, eg maybe this port should be called mimxrt?

Thanks for the Reply. We have the plan to enable the majority of NXP's MCUs( if they can) including Kinetis series LPC series and i.mx rt series. Currently, we take mimxrt1064 as the try and enable little of IP module. If this PR was approved. We will enable more MCUs. What more, mimxrt1050 mimxrt1060 mimxrt1020 have been enabled(have not been updated).   Through this PR, we hope to get suggestions from you guys.

**Comment by yanyao12138** [comment]
Hi @dpgeorge , please help me review this PR?. We hope to accelerate the progress of community support.

**Comment by ezequielgarcia** [comment]
Hi @yanyao12138, have you noticed this PR from @martinribelotta (from 2017) https://github.com/micropython/micropython/pull/3400 that adds support for LPC43xx family? Perhaps you can start from that, or reuse some of the effort. You will see that the port is really clean, currently consisting in just 700 LoC.

**Review by tannewt — COMMENTED** [review]
Hi, is it possible to remove FreeRTOS from this? Most MicroPython ports don't use an RTOS. The boiler plate from the board directory would be better shared between boards.

LittleVGL is also large on its own and would be better added as a second PR.

Thanks for this first PR!

**Comment by yanyao12138** [comment]
> Hi, is it possible to remove FreeRTOS from this? Most MicroPython ports don't use an RTOS. The boiler plate from the board directory would be better shared between boards.
> 
> LittleVGL is also large on its own and would be better added as a second PR.
> 
> Thanks for this first PR!

Hi Scott, thanks for the reply. I will remove the FrreeRTos and LittleVGl.

**Pull request closed without merging**
