### PR TITLE
tools/pyboard.py: Add "edit" and "touch" fs commands.

### PR DESCRIPTION
**Pull request by jimmo**
"touch" creates a file if it doesn't exist.

"edit" will copy the file locally (to temporary location), run $EDITOR, then copy it back if the editor returns zero.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Does it make sense to add shortcuts to mpremote (ie touch -> fs touch, edit -> fs edit)?  If so, `docs/reference/mpremote.rst` also needs updating.

**Comment by jimmo** [comment]
> Does it make sense to add shortcuts to mpremote (ie touch -> fs touch, edit -> fs edit)? If so, `docs/reference/mpremote.rst` also needs updating.

I had no idea these shortcuts existed for the other filesystem commands. Yes, if `cat` has a shortcut, then these two should too.

Also updated pyboard.py.rst and mpremote.rst.

And changed the use of NamedTemporaryFile to just use mkstemp directly because according to https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile "Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows).".

**Comment by mattytrentini** [comment]
These will be immensely useful, thanks folks!

**Comment by jimmo** [comment]
I have updated this to make "edit" only apply to mpremote, keeping "touch" on pyboard.py.

I've also made it so you can terminate the list of file arguments, allowing chaining of fs and edit commands with other commands.

**Comment by dpgeorge** [comment]
Thanks for updating.  Merged in a311e9e3d419cf447c8a4cf2beed4a341e8387e3 through 59e3348c101efee4071dd2224d01ccce6075b692

**Comment by robert-hh** [comment]
The "edit" command is fine. I stumbled however over a problem with sublime text or code as editor. For these, the $EDITOR value has to be set, such that sh waits until the editor closes. Otherwise writing back does not work. Editors that anyhow wait like nano or vim behave clean.

**Comment by jimmo** [comment]
> I stumbled however over a problem with sublime text or code as editor. For these, the $EDITOR value has to be set, such that sh waits until the editor closes.

@robert-hh Isn't this the case if you use `subl` as your editor for any other tool that works like this? e.g. as `$GIT_EDITOR` (or `core.editor` in `.gitconfig`).

I use Sublime too, but it's kind of a pain to use as $EDITOR by default because it insists on opening in an existing window (which might not be on the same desktop, etc). I have a horrible script that forces a new window state (https://github.com/jimmo/dotfiles/blob/master/common/home/bin/s) and then use `s -w` as my `core.editor`. There's probably an easier way :)

**Comment by robert-hh** [comment]
just `subl` opens a new file an returns the sh to the prompt.
`subl -w <filename>` waits.
`subl -n <filename>` opens the file in a new window. Options -n and -w can be combined.
Similar options exist for code.

**Pull request closed without merging**
