### PR TITLE
tools: Add C middle-processor to make builtin tables proper hash tables.

### PR DESCRIPTION
**Pull request by dpgeorge**
This tool sits in between the C preprocessor and the C compiler.  It takes the output of the C preprocessor and reorders any builtin tables to make them proper hash tables.  Lookups at runtime then use hashing, not linear search.  For large tables it makes the lookup a lot faster (don't have solid data though on speed improvements...).

See script for usage.

### CODE REVIEW

**Comment by dpgeorge** [comment]
This was work done as part of the ESA project.  Main reason for the PR is to advertise this new tool.

**Comment by dpgeorge** [comment]
Using this script to compile stmhal, pyboard gives a 2.5% increase in performance of pystone benchmark at zero cost of flash or RAM.  Combining this with recent patch bbe8d51bd9ab0c848ee833000dcc93eb78bcbcad takes pyboard pystone result from 1776 to 1901 (using 20000 iterations).

**Comment by dpgeorge** [comment]
Merged in 4bd95f8b4407ff85c68676285c02236ee72d72cb.

**Comment by danicampora** [comment]
Wow! Very cool Damien.

**Pull request closed without merging**
