### PR TITLE
extmod/vfs_lfsx.c: normalize pathname in chdir

### PR DESCRIPTION
**Pull request by robert-hh**
This change scans for '.', '..' and multiple '/' and normalizes
the path name in the function chdir. If the resulting path does not exist,
an error is raised. Non-existing interim path elements are ignored,
if they are removed during normalization.
Compiled & tested for PYBD_SFx, ESP32, ESP8266.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thank you, this looks clean and does not allocate any extra memory.

**Comment by robert-hh** [comment]
Thanks. But the fix for rename needs to allocate some storage for one of the names. That could be a fixed char[MICROPY_ALLOC_PATH_MAX + 1] array, or storage allocated with alloca or malloc/free. Do you have any preference?

**Comment by petrkr** [comment]
This looks fine too:
```

uPyShell:~/$ ls                                                                                                                                                                                                                               
   d/[B] name                                                                                                                                                                                                                                 
     --- assets                                                                                                                                                                                                                               
     900 boot.py
     --- config                                                                                                                                                                                                                               
     --- examples                                                                                                                                                                                                                             
     --- lib                                                                                                                                                                                                                                  
     --- pinouts                                                                                                                                                                                                                              
     --- pubsub                                                                                                                                                                                                                               
     --- util                                                                                                                                                                                                                                 
      18 webrepl_cfg.py
     --- www                                                                                                                                                                                                                                  
```

![image](https://user-images.githubusercontent.com/6428351/81052582-ff3a5000-8ec3-11ea-8bab-2a221fe4666e.png)

**Comment by dpgeorge** [comment]
Merged in d3ea28d04a7df9ca536a9002c8fda2f6e3a88f09 with minor changes to comment layout to match rest of file.

**Comment by robert-hh** [comment]
I was about to close these, just to tell that you did that already. 
Thanks, and have a good day.

**Pull request closed without merging**
