### PR TITLE
docs: Move to single ToC

### PR DESCRIPTION
**Pull request by pfalcon**
Previously, only "selected chapters" were shown in left-pane ToC (of
Read The Docs theme). These chapters were selected out of order. The
rest of chapters were hidden beyond "Documentation Contents" pseudo-
chapter. This arguably led only to confusion, as many people probably
never tried to open that pseudo-chapter, and those who did, were
confused. Such organization is even worse for PDF output, causing
chapters go in mix-mashed order.

So, instead move to single clean ToC. This will allow readers of HTML
to have access to any doc content at their fingertips (and straight
before their eyes), and will allow to finally have clean PDF docs.

### CODE REVIEW

**Comment by pfalcon** [comment]
I wanted to investigate this issue for a long time. IMHO, that's the cleanest way to deal with it. If approved, I'll propagate to other port indexes.

**Comment by dpgeorge** [comment]
Yes, this looks like a good change.

One issue: after merging this there will be a dangling link to the `esp8266_contents.rst` page, which is linked from the topindex.html file (grep for `_contents`).  Eg on pyboard it's this page: http://docs.micropython.org/en/latest/pyboard/pyboard_contents.html .  So either that entry should be removed from topindex.html, or replaced with `_index` (I prefer the latter).

**Comment by pfalcon** [comment]
Thanks. I'll take care of the latter issue.

**Comment by pfalcon** [comment]
> or replaced with _index (I prefer the latter).

Done. Also, applied to all 4 ports' docs. Merging.

**Pull request closed without merging**
