### PR TITLE
support latest esp-idf

### PR DESCRIPTION
**Pull request by oclyke**
PR that demonstrates type of work required to address #8182 

Note: this PR is not well tested and does not follow contribution guidelines but is just meant to be a starting point for a more serious effort (sorry! I don't have much time right now)

### CODE REVIEW

**Comment by IhorNehrutsa** [comment]
I tried on ESP-IDF master branch. 
:(
```
Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4344
load:0x40078000,len:13808
load:0x40080400,len:3340
entry 0x40080618
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x401437d4  PS      : 0x00060633  A0      : 0x80143934  A1      : 0x3ffce510  
A2      : 0x3ffc5680  A3      : 0x00000101  A4      : 0x3ffbf1ec  A5      : 0x3ffbf1e8  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x3ffc5680  A9      : 0x00000000  
A10     : 0x00000001  A11     : 0x3ffc2de0  A12     : 0x00060820  A13     : 0x00000003  
A14     : 0x00000008  A15     : 0x3ffce79c  SAR     : 0x0000001d  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x000000b0  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  


Backtrace:0x401437d1:0x3ffce5100x40143931:0x3ffce540 0x400d6f6a:0x3ffce560 0x400d6dd9:0x3ffce590 




ELF file SHA256: c7c051821df43fd1

Rebooting...
```

**Comment by ekondayan** [comment]
I confirm the Core 1 panic on my ESP32-PICO-V3-02. The last working commit is `b64925c5673206100eaf4337d064d0fe3507eaec`. 
I've traced the breaking commit to `219242de89c9a804c18af897bb5bf2ea3bff479b`.
It has something to do with the UART interrupts.

**Comment by AmirHmZz** [comment]
I also have the same problem with esp-idf 4.4.

**Comment by dpgeorge** [comment]
> I also have the same problem with esp-idf 4.4.

The released v4.4 IDF does work with MicroPython.  If you see issues using v4.4 then please open a separate ticket with details on the problem.

**Comment by ekondayan** [comment]
I confirm that the latest esp-idf 4.4 (commit: c29343eb94d2f2ca17b3a5b38c82452e556147f2) does not have this issue.

**Comment by dpgeorge** [comment]
Closing due to inactivity.

**Pull request closed without merging**
