### PR TITLE
[STM32F4DISC] Fixed accelerometer driver issue.

### PR DESCRIPTION
**Pull request by dinau**
(1) Mofified according to this post,
STAccel script in STM32F4 DISC
http://forum.micropython.org/viewtopic.php?f=2&t=595&p=3609&hilit=read_id#p3609
(2) Fixed SPI clock polarity(CPOL) to 1 from 0.
Please refer to datasheet of LIS302DL and LIS3DSH.
The detail explanation is here,
https://sites.google.com/site/johnkneenmicrocontrollers/spi/spi_f407#linkSPIClkPhase
(3) Modified SPI clock more high speed (2MHz).

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution, but this is not the correct fix.  The staccel.py driver was originally working, and I have just verified that it broke when SPI transfers started using DMA.  If you disable interrupts in the read_bytes function of STAccel then you'll see that it works just fine (disabling interrupts forces SPI to not use DMA).  So there's something wrong with SPI+DMA and that needs fixing.

**Comment by dinau** [comment]
@dpgeorge
Thank you for the information.
I've modified the source according to your advice by using disable_irq() function.
It works well.
I think the DMA issue should be fixed in the future.

dinau

**Comment by dpgeorge** [comment]
I found the problem with the SPI DMA transfers (although not the cause of the problem) and provided a fix in d80174d7c3fe36f139c639d6a820cc4cbb88ddf9.  So the original staccel.py script should work.

**Comment by dpgeorge** [comment]
@dinau the reason the clock polarity is 0/low is because that's how ST's example code for the F4 Discovery board is written.  They could have it wrong... can you point me to a reference in the datasheet that says that the clock polarity should be 1/high?

**Pull request closed without merging**
