### PR TITLE
stm32: support for BLE on STM32WB55 MCUs

### PR DESCRIPTION
**Pull request by dpgeorge**
This is a WIP to add support for the RF coprocessor on STM32WB55 MCUs, in BLE mode.

It requires that the `stm32wb5x_BLE_HCILayer_fw.bin` wireless stack be already programmed to the device in the secure flash area.  See ST docs (STM32Cube_FW_WB_V1.1.0, directory `Projects/STM32WB_Copro_Wireless_Binaries`) for how to do this.  (It may work with `stm32wb5x_BLE_Stack_fw.bin` but that's untested at this point.)

The implementation here provides an IPCC shared memory communication layer to talk with the coprocessor and exposes it as a BT HCI device to the Nimble stack, the latter which runs on the main processor.  From the user's point of view the API is the standard `bluetooth` module and should behave the same as other BLE ports/boards (currently stm32 PYBD, and esp32).

gap_scan and gap_advertise are working.  Supported boards are NUCLEO_WB55 and USBDONGLE_WB55.
    
Known limitations/problems:
- requires BLE_HCILayer WS firmware to be already programmed (edit: or BLE_Stack also works)
- after doing DFU programming of main FW device requires a reset to work
- gap_scan with finite timeout somehow stops event processing at end of timeout, and typing any key at the REPL will restart processing (edit: now fixed)
- gap_advertise requires a properly formed advertising packet to work
- connecting to the device does not yet work (edit: now working)
- connecting from the device to another peripheral is not yet tested (edit: tested and working)
- IPCC IRQs are not yet implemented

### CODE REVIEW

**Comment by dmazzella** [comment]
> connecting to the device does not yet work

@dpgeorge progress on this point?

**Comment by dmazzella** [comment]
> This is a WIP to add support for the RF coprocessor on STM32WB55 MCUs, in BLE mode.
> 
> It requires that the `stm32wb5x_BLE_HCILayer_fw.bin` wireless stack be already programmed to the device in the secure flash area. See ST docs (STM32Cube_FW_WB_V1.1.0, directory `Projects/STM32WB_Copro_Wireless_Binaries`) for how to do this. (It may work with `stm32wb5x_BLE_Stack_fw.bin` but that's untested at this point.)
> 
> The implementation here provides an IPCC shared memory communication layer to talk with the coprocessor and exposes it as a BT HCI device to the Nimble stack, the latter which runs on the main processor. From the user's point of view the API is the standard `bluetooth` module and should behave the same as other BLE ports/boards (currently stm32 PYBD, and esp32).
> 
> gap_scan and gap_advertise are working. Supported boards are NUCLEO_WB55 and USBDONGLE_WB55.
> 
> Known limitations/problems:
> 
> * requires BLE_HCILayer WS firmware to be already programmed
> * after doing DFU programming of main FW device requires a reset to work
> * gap_scan with finite timeout somehow stops event processing at end of timeout, and typing any key at the REPL will restart processing
> * gap_advertise requires a properly formed advertising packet to work
> * connecting to the device does not yet work
> * connecting from the device to another peripheral is not yet tested
> * IPCC IRQs are not yet implemented

I can confirm that correctly work with `stm32wb5x_BLE_HCILayer_fw.bin` and `stm32wb5x_BLE_Stack_fw.bin`

**Comment by dpgeorge** [comment]
> I can confirm that correctly work with `stm32wb5x_BLE_HCILayer_fw.bin` and `stm32wb5x_BLE_Stack_fw.bin`

Great, good to know!

I managed to get all the GAP and GATT features working, and tested that it can be connected to, and it can connect to something.

The code needs a bit of cleaning, but is otherwise feature-ready.

**Comment by dmazzella** [comment]
@dpgeorge is this ready for merge?

**Comment by dpgeorge** [comment]
> is this ready for merge?

Not yet, it needs cleaning up.  Are you able to test it, connecting to something and being connected to?

**Comment by dmazzella** [comment]
> Are you able to test it, connecting to something and being connected to?

Yes, I tried the scan, peripheral and central and I had no problem.

**Comment by dpgeorge** [comment]
This was cleaned up and merged.

**Pull request merged**
