### PR TITLE
stm32f405 feather files

### PR DESCRIPTION
**Pull request by ladyada**
Tested all GPIO with `machine` twiddling, I2C with BMP280 library, SPI #1 with SPI Flash chip, SPI #2 with TFT FeatherWing,  2x DAC pins, and SD card.

Couldn't figure out where to stick USB VID/PID?

https://www.flickr.com/photos/adafruit/48833485193/

### CODE REVIEW

**Comment by hoihu** [comment]
> Couldn't figure out where to stick USB VID/PID?

you should be able to define it like:

`usb_mode('VCP+HID', vid=0xf055, pid=0x9800) # specify VID and PID` 

within your boot.py. If that's what you mean?

Great btw to see adafruit making STM32 boards.

**Comment by ladyada** [comment]
thanks :) its a fun chip! 
i dont think we ought to submit the boot.py here, so i will provide that in the example code when the micropython documentation is up.

**Comment by chrismas9** [comment]
> within your boot.py

I think this may have unintended consequences. If boards ship with OEM VID & PID the VID & PID will change after a file system reset. I think Windows would assign a different COM port number when the VID changes.

I would like to see a way for OEMs to use their OEM VID. You can copy `stm32/usb.h` into your board folder, change the VID & PID and include it in `mpconfigboard.h.` This will build binaries with your VID & PID, however there may be licensing problems. The header file should probably be renamed to` OEM_usb.h` (eg `adafruit_usb.h`). The license would probably need to be changed to restrict its use to only that OEMs boards. Would that be acceptable under the MicroPython MIT license? Would it leave the OEM at risk of violatingt the USBIF license? If a clone maker copied your board and used your source code or binaries to distribute your VID would you be seen as facilitating illegal use of the VID by publishing the VID on an open source site?

One solution would be to host the board files outside of the MicroPython repository.

Currently this won't work for the SAMD port as the VID and PID can't be overridden.

**Comment by ladyada** [comment]
hiya @chrismas9 that may be outside the scope of this PR, we're going to go with @hoihu's suggestion :)

**Comment by dpgeorge** [comment]
Thanks!

One minor point: I think the board name should be prefixed with ADAFRUIT, to match the existing samd boards that we have in this repo.

How about `ADAFRUIT_F405_EXPRESS`?

**Comment by ladyada** [comment]
comin' right up!

**Comment by ladyada** [comment]
done :)

**Comment by dpgeorge** [comment]
Thank you!  Merged in 06ae818f9360e83284c64614144f1ad00998a739

**Comment by ladyada** [comment]
:D

**Pull request closed without merging**
