### PR TITLE
add round.c to libm_dbl

### PR DESCRIPTION
**Pull request by v923z**
This PR adds the implementation (taken from https://github.com/ifduyue/musl/blob/b4b1e10364c8737a632be61582e05a8d3acf5690/src/math/round.c) of `round` to `lib/libm_dbl`, and the file path to the Makefile in `ports/stm32/`, so that firmware for the `PYBD` variant can be compiled with double precision. The original issue can be found in https://github.com/v923z/micropython-ulab/issues/132. 
This PR is an extension of https://github.com/micropython/micropython/pull/5789.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the PR.  As with the single-precision version of this function, it's not actually used/needed anywhere in the firmware, but I guess this helps C extensions (like ulab).

There's an unrelated commit here with setter/getter changes which would not be merged in this PR.

**Comment by v923z** [comment]
Thanks for the feedback! 

> Thanks for the PR. As with the single-precision version of this function, it's not actually used/needed anywhere in the firmware, but I guess this helps C extensions (like ulab).

Right. As I've mentioned, someone raised an issue at `ulab`.

> 
> There's an unrelated commit here with setter/getter changes which would not be merged in this PR.

Sorry, I somehow mixed up my branches. I have removed the changes pertaining to `runtime.c`, so this should be clean now.

**Comment by dpgeorge** [comment]
Thanks for updating, merged in 27767aafa21754e6cdbf52a719e7ce395f0fe672

**Comment by v923z** [comment]
Fantastic, many thanks!

**Pull request closed without merging**
