### PR TITLE
cc3200/modnetwork: Add print_ver() diagnostic function.

### PR DESCRIPTION
**Pull request by pfalcon**
Prints NWP/MAC/PHY version, as affected by servicepack installed.

### CODE REVIEW

**Comment by pfalcon** [comment]
I used this for example to verify that "make servicepack" as introduced in 0748143a4c648ad7bcdbbf125d039ceb7490f4e6 actually worked.

**Comment by danicampora** [comment]
Nice! But shouldn't it be inside the WLAN class instead (as it only 
applies to the WLAN NIC)?

**Comment by pfalcon** [comment]
> Nice! But shouldn't it be inside the WLAN class instead (as it only applies to the WLAN NIC)?

I dumped my thoughts on that a second later. I'm not sure putting it in WLAN class will make much better - such function is bound to be undocumented, and putting it somewhere deep just will make it harder to discover it.

**Comment by danicampora** [comment]
Good point...

**Comment by dpgeorge** [comment]
MAC address should be different for different interfaces, so seems better suited to live in the WLAN class.  And if it were to be designed to be useful for other ports, I'd suggest naming it `version` and letting it return a str (or tuple of str, or whatever) so it can be programatically used.

**Comment by pfalcon** [comment]
> MAC address should be different for different interfaces, so seems better suited to live in the WLAN class. 

It's not MAC address, those are versions of various software components of vendor WiFi firmware. It's not intended to be portable to other ports, and in current incarnation is intended to be a *quick* diagnostic tool to check that vendor WiFi firmware upgrades (called by them "servicepacks") actually succeed. Someone can make it less quick (e.g. return a tuple) at later time.

**Comment by dpgeorge** [comment]
> It's not intended to be portable to other ports

Consider stmhal with multiple network drivers (eg one being cc3100).  The "print_ver" function would be useful in that setting, and would be implemented per interface.

**Comment by pfalcon** [comment]
Yep, I came to conclusion that it would better be `network.WLAN.print_ver()`, as suggested by @danicampora . Now just need to find time to do that/test it.

**Comment by pfalcon** [comment]
Ok, reworked to be network.WLAN.print_ver() and merged.

**Pull request closed without merging**
