### PR TITLE
py/modio: Implement uio.resource_stream(package, resource_path).

### PR DESCRIPTION
**Pull request by pfalcon**
The with semantics of this function is close to
pkg_resources.resource_stream() function from setuptools, which
is the canonical way to access non-source files belonging to a package
(resources), regardless of what medium the package uses (e.g. individual
source files vs zip archive). In the case of MicroPython, this function
allows to access resources which are frozen into the executable, besides
accessing resources in the file system.

This is initial stage of the implementation, which actually doesn't
implement "package" part of the semantics, just accesses frozen resources
from "root", or filesystem resource - from current dir.

### CODE REVIEW

**Comment by pfalcon** [comment]
Towards finishing https://github.com/micropython/micropython/issues/1346

**Comment by pfalcon** [comment]
Ok, existing tests pass, new test added, merging.

**Comment by dpgeorge** [comment]
It would have been nice if I had time to look over this before it being merged.

Now that the VFS stuff is there, why not implement it using that?  Such a feature is probably going to be needed anyway.

**Comment by pfalcon** [comment]
> It would have been nice if I had time to look over this before it being merged.

Well, I follow the usual process - if there's little to review, I just merge it. This time, it was additionally instigated by the fact that the ticket where it was discussed closes to its 2nd anniversary (and which didn't receive any comments over all this time, which only proves there's little to review). Besides, there's no lack of things which *need* review ;-).

> Now that the VFS stuff is there, why not implement it using that? Such a feature is probably going to be needed anyway.

"it" - what? resource_stream() is a function which does 2-way dispatching: either to existing "frozen modules" pseudo-filesystem, or to open(). That's it, nothing else is involved.

Now completely different, unrelated question is whether "frozen modules" has got anything to do with VFS, and the answer is known - nope, the whole idea of it is to provide a *kind* of filesystem when no real filesystem is available. "frozen modules" pseudo-filesystem is very small, which is good because our VFS layer is growing bigger to accommodate real-world requirements and ease of use (#2950), so it's important to keep the feature-limited alternative to it. It's feature limited, but should still have complete set of features, which was subject of #1346 for almost 2 years.

Unfortunately, our "frozen" psudo-filesystem is not as small as it could be, because we have 2 parallel structure for "frozen source" vs "frozen bytecode" - with parallel functions to deal with them. Last time that code was refactored, it was proposed to unify handling, but we didn't choose to go this last natural step. And it catches us now. To use the feature added by this patch, why needs to put Python code to "for bytecode" dir, while static resources to "for source" dir, which is of course confusing and cumbersome.

**Pull request closed without merging**
