### PR TITLE
esp8266: Update README.md

### PR DESCRIPTION
**Pull request by bhuvanchandradv**
Add the toolchain export step before building MicroPython for ESP8266.

### CODE REVIEW

**Comment by pfalcon** [comment]
Sorry, but this information is misleading. It silently assumes that Xtensa toolchain is installed in ${HOME}/esp-open-sdk/xtensa-lx106-elf/bin, and there's no warranty that's the case. Instead, people should follow setup instructions of a particular toolchain they use. E.g. https://github.com/pfalcon/esp-open-sdk/ output the exact PATH to use at the end of the build process.

**Comment by pfalcon** [comment]
Information is also available in esp-open-sdk's README, and I made it more prominent: https://github.com/pfalcon/esp-open-sdk/#using-the-toolchain

**Comment by alex-march** [comment]
You can instead have a comment something along the lines of "make sure to have xtensa toolchain is in your PATH". But I agree with pfalcon, this has been described well in the sdk how-to.

**Comment by pfalcon** [comment]
> You can instead have a comment something along the lines of "make sure to have xtensa toolchain is in your PATH".

Pushed such an addition to master.

**Comment by bhuvanchandra** [comment]
I add the path as an example, any way my intention is to add the information about exporting the tool-chain path before building. At least now with commit 9e78ab4b866c8bc4cf8b1bc21b848aadc64097cb this information is added. Thanks!

**Pull request closed without merging**
