### PR TITLE
esp32: add support for machine.Pin.hold/capacity

### PR DESCRIPTION
**Pull request by shawwwn**
GPIO drive capacity and GPIO hold should now work on esp32

#### Ref:
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/gpio.html#_CPPv212gpio_hold_en10gpio_num_t

#### Docs:
```
import machine
p=machine.Pin(10)
p.init(drive=p.DRIVE_CAP_STRONGEST, hold=True)
```

EDIT: move functionality to Pin.init()

### CODE REVIEW

**Comment by pfalcon** [comment]
These should be implemented as params to init() method: http://docs.micropython.org/en/latest/esp8266/library/machine.Pin.html?#machine.Pin.init

**Comment by shawwwn** [comment]
There is a problem. If the function is implemented in init(), then there is no feedback.
User won't be able to get the current state from the pin, which will pose a problem for some applications.

**Comment by shawwwn** [comment]
Moved to machine.Pin()

Need something extra to obtain current gpio status. Maybe a general peripheral register read/write in the esp32 module?

**Comment by pfalcon** [comment]
> There is a problem. If the function is implemented in init(), then there is no feedback.
User won't be able to get the current state from the pin, which will pose a problem for some applications.

Well, in this case, it won't be worse than the other MicroPython ports - and that's the whole idea of MicroPython - to provide firm, consistent base to let people to develop apps for any hardware, not just one hardware.

If you want to go beyond that, the first question would:

1. Is it really needed to get values of pin properties like slew/drive/etc.? Please provide usecases, what kind of applications this feature enables which are otherwise not possible?
2. Once confirmed it's really needed, we have a pattern to follow on how to resolve such cases: network interfaces also have need to set/query absolutely arbitrary parameters, which may differ from port to port: http://docs.micropython.org/en/latest/pyboard/library/network.html#network.config . Implementation, wise, .config() method would be an alias of .init() method. When we last time discussed Pin API, it was mentioned as a choice to replace init() with config(), but that didn't go thru, we decided to stick with consistent .init() for all classes in `machine`. Well, if Pin property read-back is really needed, making .init() and .config() the same function only makes sense.

But there's also 3.:

3.

> Maybe a general peripheral register read/write in the esp32 module?

Indeed, maybe nothing that needs to be done on the level of `machine` API. For rare cases where it's needed, maybe adhoc functions in port-specific modules are enough.

Maybe. Someone needs to come up with a clear proposal, which is based on already established APIs, and works well across ports (and is efficient, small, etc., as standard requirements for MicroPython).

**Comment by shawwwn** [comment]
In response to your 1, I'm currently poking into the ULP capability of my ESP32. I do want to recover my pin/register state after a deep sleep. Sure there are other ways to do it, only with more code. But I thought the whole aim of Micropython is to write less code because it's already implemented in C.
To your 2 and 3, I guess you did make a valid point. I'm glad that you apply a kind of industrial-level scrutiny onto MP.

As for me, I'm just a casual board user who want to maximize my device's capability. I issue PR because I see features that are missing or would otherwise be incompatible with my current device.
I have multiple devices, so portability is also my focus. Since there is no standard guideline for incorporating vendor specific API into MP, the bare minimum I can do is to maintain the robustness of Micropython's common part when dealing with device-specific code(also thank you for reminding me that in your first comment). To which, I have already make sure that MP won't crash when accepting a script from another platform.

If my implementation of the API still doesn't fit your underlying design/scheme/"code of conduct" then I will be happily retract my contributions and keep them to my own fork.

**Pull request closed without merging**
