### PR TITLE
Add Appveyor CI builds for msvc port

### PR DESCRIPTION
**Pull request by stinos**
Appveyor is like Travis, but for Windows builds. The appveyor.yml configuration file will build the msvc port in all configuration/platform conbinations and run the tests for each fo those.

If there is interest for this it can be put to use and @dpgeorge needs to go to http://www.appveyor.com/, create an account and add a project pointing to the uPy repository on GitHub (no further configuration needed, the yml takes care of that). The process is self-explanatory and GitHub integration setup is automatic. Once that is done a 'badge' for these builds can be added to the README just like for Travis. If I understand it correctly GitHub will also show status on pull requests just like for Travis.

Appveyor can also build/test using minw/msys2 and whatnot, which would be a welcome addition to the current cross-compile in Travis.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Yes, this would be good to have.  I can register appveyor.  Can appveyor.yml go in windows/ dir?

**Comment by stinos** [comment]
Yes but then the location has to be set in the web ui explicitely under 'Custom configuration .yml file name' - I adjusted the PR to have it as ```windows/.appveyor.yml``` now.

**Comment by dpgeorge** [comment]
I set up appveyor.  Can you please repush to trigger a build?

**Comment by stinos** [comment]
I did but no build was triggered; I checked the latest build log on https://ci.appveyor.com/project/dpgeorge/micropython and it cloned from dpgeorge/micropython though, that should be the 'public' micropython/micropython..

**Comment by dpgeorge** [comment]
> and it cloned from dpgeorge/micropython though, that should be the 'public' micropython/micropython.

Yes you are right!  Should now be fixed.  Please try repush again.

**Comment by stinos** [comment]
Seems ok now!

**Comment by dpgeorge** [comment]
Rebased and merged in da199e4407f38c170179c33aef862fd5109145e2.  Very nice!

**Comment by stinos** [comment]
Yes it seems to work well, I'll add a mingw build later

**Pull request closed without merging**
