### PR TITLE
samd: Refactor to use shared tinyusb, implement unique id (with cross-port refactor)

### PR DESCRIPTION
**Pull request by projectgus**
Three related changes for tinyusb on samd port (including a refactor that also covers rp2 and renesas-ra):

* Switch to use the shared tinyusb implementation (same functionality, shared source code). This is a precursor to supporting Python-implemented USB devices on this platform.
* Add a helper for "bytes to hex" conversion that is implemented in multiple ports for serial numbers. Refactor the rp2 and renesas-ra ports to use the helper instead of the same piece of code.
* Implement a unique USB device serial number for samd based on the existing `machine.unique_id()` implementation. Previously this was all-zeroes `// TODO`.

Can split into two PRs if that is easier to review.

Tested on a Seeed WIO Terminal and a Seeed XIAO.

Code size impacts:

| Stage |Flash Size - WIO Terminal (SAMD51) | Seeed XIAO (SAMD21) |
| ---- | --- | --- |
| master | 261180 | 184144 |
| Refactor to shared tinyusb | 261208 | 184180 |
| Implement serial number | 261284 | 184244 |

### CODE REVIEW

**Comment by projectgus** [comment]
There is a merge conflict between this PR and #12846 as they make some of the same changes. If either merges, I'll rebase the other.

**Comment by dpgeorge** [comment]
This can be rebased now.

**Comment by projectgus** [comment]
Rebased, updated the size numbers.

**Comment by dpgeorge** [comment]
Merged, thank you.

**Pull request merged**
