### PR TITLE
rp2: Move to latest SDK, and fixup code.

### PR DESCRIPTION
**Pull request by kilograham**

### CODE REVIEW

**Comment by dpgeorge** [comment]
I've merged the changes to N_GPIOS from #6825 .

And the update to the pico-sdk submodule needs to be in its own commit (to make it easier to rebase and manage submodules).

If you can make those changes (two commits, one for pico-sdk and one for update to the .ld file) that would be great.  If not I can do it, just let me know.

**Comment by kilograham** [comment]
i'm away from that computer right now, so go ahead if you have a sec

**Comment by dpgeorge** [comment]
Ok, I'm working on it.

**Comment by dpgeorge** [comment]
Merged ld changes in 52d3ae707d7ddb8cf2c06962923226221d281206 and updated pico-sdk in 9b277d981528173f59daab196873a8c11aa17e26

Thanks!

**Pull request closed without merging**
