### PR TITLE
Bare-Metal Raspberry Pi port

### PR DESCRIPTION
**Pull request by naums**
Hello.

This pull requests contains mainly a Makefile and start-code for a bare-metal port of Micropython to the Raspberry Pi along with driver-code for the UART-interface to receive any output from the device. It does not contain additional modules and does not feature any sort of command prompt. 

This port works on the Raspberry Pi Zero (tested) and should also work on the Raspberry Pi 1. It will however probably not work out-of-the-box on the Raspberry Pi 2 or 3, as they feature a different processor. 

If you want to read more, I wrote a term paper [1] about porting Micropython to bare-metal Raspberry Pi (and adding modules to it).

[1] https://www.stefannaumann.de/en/2017/12/porting-micropython-to-bare-metal-raspberry-pi-2/

Regards,
Stefan Naumann

### CODE REVIEW

**Comment by boochow** [comment]
Hi, @naums this is very interesting project.
Are you planning to implement REPL on bare-rpi ?

**Comment by naums** [comment]
Yes and no. I'm not going to implement that anew. I saw something like a REPL somewhere in the libs-folder. I didn't manage to work out how to link that one into this port, back when I tried the first time, but I could give it another try later.

**Comment by boochow** [comment]
@naums FYI  starting from your PR, I tried porting REPL on RPi referring [MicroPython on Unicorn](https://micropython.org/unicorn/).
It works, although its abilities are very limited.
The repository is [here](https://github.com/boochow/micropython-raspberrypi).

**Comment by dpgeorge** [comment]
Thanks for this, it's great to see ports like this.

The work here has been extended by @boochow 's excellent work in the repo linked above, and anyone interested to run MP on bare-metal RPi boards should definitely look at that repo.

**Pull request closed without merging**
