### PR TITLE
User CXX Module support

### PR DESCRIPTION
**Pull request by mo-FEAR**
this changes the order and fixes the syntax of (struct) member assignment in some macros in py/obj.h so that C++ files will compile without compile errors, linker errors, or warnings. It requires slight modifications to the way modules are defined, see the user cpp example folder for details.

The documentation would still need to be updated to reflect these changes, if approved.

Update: [examplemodule.hpp](https://github.com/micropython/micropython/pull/12984/files#diff-213ccc0bcd6fc8edd83319ae3a706b5aa68fcd4666c5e0eda89e6e91b37cbf3f) could use some header guards, and ```#define MP_DEFINE_CONST_FUN_OBJ_N(obj_name, n_args, fun_name)``` shouldn't be part of the pull-request, I created that as a convencience for myself. But perhaps it can also be merged.

### CODE REVIEW

**Comment by stinos** [comment]
> so that C++ files will compile without compile errors, linker errors, or warnings. 

As far as I'm aware this was largely the case already (I do this all the time, so did the existing C++ user module eexample), so can you split this up in small commits with focused changes, each clearly explaining for which compiler and under what circumstances there was an error and which one?

Also because of the many changes to the user module files it's pretty hard to see what goes on. Could you split this in e.g. first only renaming the examplemodule.c to examplemodule.cpp and adding the existing example.cpp code into it? Exapnding the example can then be a separate commit (or PR even).

**Comment by mo-FEAR** [comment]
I think [this](https://github.com/orgs/micropython/discussions/10777) sums up the problem that this PR solves

**Comment by dpgeorge** [comment]
Please don't change the existing `cppexample`, it works fine.  Instead I suggest to create a new example that shows the alternative way of making a C++ user module.

**Comment by stinos** [comment]
> I think this sums up the problem that this PR solves. 

Fair enough but the exact reason has to be in the commit message, explaining what it solves ('blahblahblah is invalid in C++ and leads to compiler error cx533333 when code like xyz is used')  and why ('allowing to implement mp_obj_t in pure C++' or something like that). People often use file/line history in git and seeing a change which is said to 'user CXX modules no longer require an additional .c' is pretty meaningless (plus arguably that should be C++ not CXX, after all the former is the name of the language).

> I'm aware MP is written in C, but that shouldn't prohibit adjusting the public API (obj.h etc) to support pure C++ user modules (ie without having to split the definitions out into c files).

If it's merely about the 'physical' split: there's no need for that I think, because `extern "C"` also solves that? So again if you have a commit fixing this it's good to explain exactly why it's better than alternatives.

**Comment by mo-FEAR** [comment]
@stinos  @dpgeorge 

I hate to step on some guy's tail here... but whoever implemented primitive C++ support to begin with should have done exactly that. It would be easier for me to resolve this if the admins at mpy unblock my main account. This one is just backup in case I forget my password.

**Comment by stinos** [comment]
> should have done exactly that

Sorry I'm not following, what do you mean with 'that' here? In any case: seeing that I have been building C++ modules using micropython for a decade or so by now, it's a bit of a stretch saying that something should have been done.

Also to clarify: no-one really implemented C++ support as such. Instead what happened is some people made the public API like obj.h legal C++ (partly, in ad-hoc steps for specific usecases) and completely separate from that and many years later if I recall correctly some people added support for compiling C++ source files. And made a basic sample of a user module which incorporates compiling C++ source. Sidenote: it's possible 'some people' is mainly me but that's not relevant, I'm just trying to explain the step-by-step way how things work here. And it's great that you're now trying to add to that.

**Pull request closed without merging**
