### PR TITLE
OneButton Lib

### PR DESCRIPTION
**Pull request by tgfuellner**

### CODE REVIEW

**Comment by pfalcon** [comment]
@tgfuellner : It would be suggestable that you maintained such a library as an independent project, akin to 80,000+ Python projects which are independent from the Python core: https://pypi.python.org

**Comment by tgfuellner** [comment]
ok

**Comment by deshipu** [comment]
I think this could be closed?

**Comment by pfalcon** [comment]
Actually, I wanted to ask @tgfuellner if he'd be interested to contribute something like that to micropython-lib after appropriate fixing (PEP8, etc.) I however started, but didn't finish reviewing this code, and forgot about it. In either case, this particular PR would be among last be closed unmerged (it's useful, just mis-destined for uPy core, so can hang around to catch somebody's attention).

**Comment by cprior** [comment]
Thanks for leaving it here, useful code.
Reference: http://www.mathertel.de/Arduino/OneButtonLibrary.aspx

(Came here loking for existing FSM implementations.)

**Review by oracul0909 — APPROVED** [review]
Approve my changes to get the code workable.

**Comment by peterhinch** [comment]
See also [this existing solution](https://github.com/peterhinch/micropython-async/blob/master/v3/docs/DRIVERS.md#4-interfacing-pushbuttons).

**Comment by dpgeorge** [comment]
Closing due to lack of interest.  This feature can anyway be maintained outside this repo.

**Pull request closed without merging**
