### PR TITLE
Add Python-configurable USB HID mode.

### PR DESCRIPTION
**Pull request by dpgeorge**
With this patch different HID modes can be configured in Python.  You
can either use predefined mouse or keyboard, or write your own report
descriptor.

Eg, in boot.py you can write:

``` python
pyb.usb_mode('CDC+HID', pyb.hid_keyboard)
```

This sets the USB device to CDC with HID as a keyboard.  Then to send a report:

``` python
hid = pyb.USB_HID()
def press_key_once(key):
    buf = bytearray(8) # report is 8 bytes long
    buf[2] = key
    hid.send(buf) # key pressed
    pyb.delay(10) # wait until report sent; can also use: select.select([], [hid], [])
    buf[2] = 0
    hid.send(buf) # key released
```

There is the original mouse mode:

``` python
pyb.usb_mode('CDC+HID', pib.hid_mouse)
```

And now you can define your own report descriptors:

``` python
pyb.usb_mode('CDC+HID', (0x1234, 0, 2, 10, b'...'))
```

Where the data in the tuple is: PID, subclass, protocol, max_packet_len, report_desc.

This is experimental, but the default mouse and keyboard work.

Some basic things need to be decided/agreed upon for the API:
1. You must now explicitly enable a USB mode using pyb.usb_mode (eg in boot.py).  Otherwise the USB is not enabled.  This is actually a feature, since it allows you to save power by not turning on the USB peripheral if you don't need it.  The default boot.py now has `pyb.usb_mode('CDC+MSC')` uncommented.  And "safe boot mode" also enables CDC+MSC mode, so it's pretty much as it was before.  Just need to make people aware that if they have a blank boot.py then they won't get any USB device showing up.  They can enter safe boot mode to fix this.
2. USB is a bit different from all other peripherals (eg UART), in that we don't create an instance of the top-level USB object (eg unlike uart=pyb.UART(1,9600)).  In the current implementation, you set the USB mode using pyb.usb_mode(...), then create the specific objects using vcp=pyb.USB_VCP() and hid=pyb.USB_HID().  These specific objects have methods to control them (like sending a HID report).  But there is no top-level USB object.  That's mostly because it's not needed, since once it's initialised there's nothing more you can do.  Trying to make the USB peripheral more like, eg, UART, we could make a USB object, such as usb=pyb.USB(), and then have a method usb.init('CDC+HID', ...).  Then the VCP is accessed with usb.VCP(), etc.  What are people's opinions on this?
3. The USB mode for CDC/VCP is called CDC, but the object is called USB_VCP.  (Note CDC=communications device class, VCP=virtual comm port).  VCP is kind of a subset/subclass/specialisation of CDC, and I prefer to use VCP because "virtual comm port" is much more descriptive and tells you exactly what it is.  So that's why the object is named USB_VCP.  It would be nice to change CDC to VCP for consistency reasons.  Ie, you would select mode using `pyb.usb_mode('VCP+MSC')` or `pyb.usb_mode('VCP+HID', ...)`.  This is a small change that doesn't affect anything except end-user experience and consistency for them.  Opinions?

### CODE REVIEW

**Comment by ice3** [comment]
Great news ! 
It would be awesome if we could put your own HID descriptors. 

I work in the field of research in Computer Human Interaction and it is something that would definitively be useful. For instance a co-worker made this to study OS's transfert function : http://libpointing.org/echomouse/index.html

Do you think we can also receive messages from HID ? 
This trick is used in echoMouse to receive the data without the need for a driver in Windows. 

What can we do to help the branch be merged in master ? 

For your questions, here are my 2 cents: 
 1. It's probably a good idea. Nevertheless, some people would be surprised and think they have broken everything, so the documentation message needs to be clear. Moreover, we use the STM32F4DISC in the lab and when the boot.py is in HID mode for USB, the only way to get a USB-FileSystem is to remove the "boot.py" (```open("boot.py", "w")```) so changing the behavior of an empty boot.py can have a lot of repercussions (in our case, breaking the FS so it's recreated on boot)

 2. I don't know what's best.  

 3. It can be clearer to use the same term everywhere I think, so VCP everywhere seems fine to me.

**Comment by dhylands** [comment]
You could support a usb_mode of None to mean USB off and then still maintain backwards compatability (so leave the default as CDC+MSC).

I would imagine that most people have not changed the usb_mode, so changing CDC+MSC to VCP+MSC should be less disruptive than having the USB connection suddenly stop working on a firmware update.

**Comment by dpgeorge** [comment]
> Do you think we can also receive messages from HID ?

Yes, quite possibly.  A keyboard device can have its LEDs turned on/off, so that must send data out of the PC, and we could use this.

> What can we do to help the branch be merged in master ?

Give feedback on the API, request features (within reason!), and test the firmware.  This "hid" branch should work and you can test it out.  There are currently 2 descriptors implemented (mouse and keyboard).  It would be great if you could submit a descriptor for another device such as a joystick.

> Nevertheless, some people would be surprised and think they have broken everything, so the documentation message needs to be clear.

That's why I propose moving to v1.4 for this change (see #1061).

> Moreover, we use the STM32F4DISC in the lab and when the boot.py is in HID mode for USB, the only way to get a USB-FileSystem is to remove the "boot.py"

You should be able to enter "safe mode" on the discovery board.  Just hold down "User" while resetting.  It works on the discovery board I have.

**Comment by dpgeorge** [comment]
> You could support a usb_mode of None to mean USB off and then still maintain backwards compatability (so leave the default as CDC+MSC).

I tried to do this with my first attempt implementing this HID stuff, but it was messy.  To keep the old behaviour you'd need to:

- have some global variables with the usb config, set to MSC+CDC by default
- on a pyb.usb_mode call, save all the arguments passed to this function in the global variables and not actually do any config
- after boot.py is run, set the usb based on the config saved in the global variables (and don't set it up if the config was None)

Changing to the new behaviour in this PR makes it much cleaner:

- no global config state
- pyb.usb_mode does the config at the time of the call

You also get the added feature that you don't need to set the usb in boot.py anymore.  You can turn on the usb at any point in your code (eg only turn it on if the user presses USRSW).  I think this is a great feature to have, and worth the incompatibility with previous behaviour.

I think it's also easier to document the new behaviour: it's simply that pyb.usb_mode sets up the USB.  And if you don't set it up, the USB is not enabled.

**Comment by dpgeorge** [comment]
> You could support a usb_mode of None to mean USB off and then still maintain backwards compatability (so leave the default as CDC+MSC).

Actually, I think I better understand what you meant: that if you didn't configure the USB at all (either None for disable, or some mode to set it up), then it defaults to CDC+MSC.  This is easy to implement: just set a flag if it was configured during boot.py, and, if the flag is not set after boot.py runs, then config CDC+MSC mode.  This will also allow you to configure it in main.py as well, by first disabling it in boot.py.

**Comment by dhylands** [comment]
> > You could support a usb_mode of None to mean USB off and then still maintain backwards compatability (so leave the default as CDC+MSC).
> 
> Actually, I think I better understand what you meant: that if you didn't configure the USB at all (either None for disable, or some mode to set it up), then it defaults to CDC+MSC. This is easy to implement: just set a flag if it was configured during boot.py, and, if the flag is not set after boot.py runs, then config CD

Yeah - that summarizes (well) what I was trying to say.

**Comment by ice3** [comment]
Here is a minimal code for a joystick. It reads a mini joystick connected to PC2-PC3 and sends the info by HID.
``` python
import pyb
from pyb import Pin, ADC

hid_desc = b'\x05\x01\x09\x04\xa1\x01\x05\x01\x09\x01\x15\x00\x26\xff\x0f\xa1\x00\x95\x01\x75\x10\x09\x30\x81\x02\x09\x31\x81\x02\xc0\xc0'
pyb.usb_mode("CDC+HID", (0x1234, 0, 2, 4, hid_desc))


hid = pyb.USB_HID()
p_x = ADC(Pin("PC3"))
p_y = ADC(Pin("PC2"))
buf = bytearray(4)

while 1:
    # read DAC value and split the 12bits data in 2 bytes
    val_x = p_x.read()
    sup_x = val_x >> 8
    inf_x = val_x & 255
    val_y = p_y.read()
    sup_y = val_y >> 8
    inf_y = val_y & 255
    # print("{:b} -- {:b}-{:b}".format(val, sup, inf))  #debug sup and inf
    buf[1] = sup_x
    buf[0] = inf_x
    buf[3] = sup_y
    buf[2] = inf_y
    hid.send(buf)
    pyb.delay(10)
    print(".", end="")  #prints a . each time a HID packet is sent
```

The joystick is correctly seen by jstest-gtk on linux:

screenshot from 2015-01-14 11 22 32

Here is the human readable descriptor for the joystick: 
```
0x05, 0x01,        // Usage Page (Generic Desktop Ctrls)
0x09, 0x04,        // Usage (Joystick)
0xA1, 0x01,        // Collection (Application)
0x05, 0x01,        //   Usage Page (Generic Desktop Ctrls)
0x09, 0x01,        //   Usage (Pointer)
0x15, 0x00,        //   Logical Minimum (0)
0x26, 0xFF, 0x0F,  //   Logical Maximum (4095)
0xA1, 0x00,        //   Collection (Physical)
0x95, 0x01,        //     Report Count (1)
0x75, 0x10,        //     Report Size (16)
0x09, 0x30,        //     Usage (X)
0x81, 0x02,        //     Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
0x09, 0x31,        //     Usage (Y)
0x81, 0x02,        //     Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
0xC0,              //   End Collection
0xC0,              // End Collection
```

The only problem I have seen is that the logical value seems to be 32767 while it is specified 4095, maybe a HID joystick thing...

**Comment by dhylands** [comment]
According to: https://www.kernel.org/doc/Documentation/input/joystick-api.txt
the joystick API scales the value to fit between -32767 and 32767
So I suspect it's mapping 0 to -32767 and 4095 to 32767 and everything else is being linearly interpolated.

**Comment by slush0** [comment]
Do you plan to implement also "old-style" way of sending reports, like

> pyb.hid((0, 10, 0, 0))

Not only that using bytearray instead of tuple is pretty verbose, but it also breaks existing code (at least many tutorials).

**Comment by dpgeorge** [comment]
> Do you plan to implement also "old-style" way of sending reports, like

No, that was not in the plan.  We can retain the `hid` function for backwards compatibility (for a few versions and then remove it eventually), but the tutorials should change to reflect the new behaviour.  We can also make it so that the new hid send function can take a tuple as well as a bytarray.

**Comment by slush0** [comment]
> We can also make it so that the new hid send function can take a tuple as well as a bytarray.

Awesome.

**Comment by dpgeorge** [comment]
BTW, I am working on merging this, just got a few things to tidy up first.

**Comment by dpgeorge** [comment]
This has now been merged; see issue #1061.

**Comment by dpgeorge** [comment]
@ice3 Thanks for the joystick example.  But I can't seem to get it working.  I have slightly modified the HID code, and the mouse still works, but your JS example does not.

You must now put the usb_mode call in boot.py.  Here is what I have in boot.py:
```python
import pyb

# HID descriptor for a joystick
hid_desc = bytes([
   0x05, 0x01,        # Usage Page (Generic Desktop Ctrls)
   0x09, 0x04,        # Usage (Joystick)
   0xA1, 0x01,        # Collection (Application)
   0x05, 0x01,        #   Usage Page (Generic Desktop Ctrls)
   0x09, 0x01,        #   Usage (Pointer)
   0x15, 0x00,        #   Logical Minimum (0)
   0x26, 0xFF, 0x0F,  #   Logical Maximum (4095)
   0xA1, 0x00,        #   Collection (Physical)
   0x95, 0x01,        #     Report Count (1)
   0x75, 0x10,        #     Report Size (16)
   0x09, 0x30,        #     Usage (X)
   0x81, 0x02,        #     Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
   0x09, 0x31,        #     Usage (Y)
   0x81, 0x02,        #     Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
   0xC0,              #   End Collection
   0xC0,              # End Collection
])

pyb.usb_mode("VCP+HID", pid=0x1234, hid=(0, 2, 4, hid_desc))
```

and in main.py:
```python
hid = pyb.USB_HID()
accel = pyb.Accel()
buf = bytearray(4)

while 1:
    val_x = accel.x() + 40
    sup_x = val_x >> 8
    inf_x = val_x & 255
    val_y = accel.y() + 40
    sup_y = val_y >> 8
    inf_y = val_y & 255
    buf[1] = sup_x
    buf[0] = inf_x
    buf[3] = sup_y
    buf[2] = inf_y
    print(val_x, val_y, buf)
    hid.send(buf)
    pyb.delay(20)
    print(".", end="")  #prints a . each time a HID packet is sent
```

I'm using the accelerometer as the input.  The device is recognised as /dev/input/js0 and jstest-gtk opens it, but nothing happens (ie no reports seem to come through).  Any thoughts?

**Comment by ice3** [comment]
Hum...
The boards are at work, so I won't be able to reproduce until monday.

I imagine that  ```print(val_x, val_y, buf)``` prints something meaningful. 

First, I would try a ``dmesg | taill``` to see the messages about the board (USB and HID errors tend to be quite noisy). Then nou can try something like ```cat /dev/input/js0 | hd``` and see if something appears or with [hiddump](https://github.com/DIGImend/usbhid-dump) to see the HID messages received by the computer. 

If there is nothing, then I think the problem comes from micropython. Otherwise, maybe the messages are corrupted / malformed, you can access the parsed messages with ```evdev /dev/input/eventX``` (the eventX correspond to the joystick, probably the last one in the list) and see if there is a problem.

Have you tested it on Windows ?

**Comment by slush0** [comment]
Very cool, it *almost* works for me. Just one question - how can I configure "vid"? When I set pid=0x534c, "lsusb" see my device as "0x534c:0x534c" (both pid and vid are the same).

**Comment by dpgeorge** [comment]
Oops, vid now fixed in aa730620bb95edbf1816b10b7c559a25a70b2146.

**Comment by slush0** [comment]
Ha! Works now! I can finally mimic TREZOR device with pyboard! So just get ECDSA work there and I'm almost done :-)

**Comment by slush0** [comment]
Damn, it seems USB_HID instance don't have any support for reading HID messages. Am I correct?

**Comment by dpgeorge** [comment]
Correct, no read support yet.  Any help with this much appreciated!

**Comment by dpgeorge** [comment]
Does anyone have a simple example (descriptor and host/PC driver) for a HID device that has reports going IN and OUT, ie both directions on the USB bus?

**Comment by dhylands** [comment]
Keyboard (has keys and LEDs)
Joystick with Rumble.

**Comment by slush0** [comment]
Not kind of "easy" device, but if you emulate vid=0x534c, pid=0x0001 and go to mytrezor.com (with proper plugin installed - you'll be asked), website sends HID report to the device as trying to initialize it.

**Comment by ice3** [comment]
In [EchoMouse](http://libpointing.org/echomouse/index.html) they used to talk to a PIC with HID. 
You have the USB / HID descriptor in the code. Basicaly, you only need to add an endpoint in the USB descriptor and a OUTPUT in the HID descriptor. 

The hard part is to react on the HID incoming messages on the pyboard (and maling them in the computer) but I think ST functions have the necessary.

**Comment by ice3** [comment]
I have tried on my board with joystick messages and it works, with the code from january. I also tried with your code, replacing the accelerometer with the ADC and it works too.
Only changed this: ```pyb.usb_mode("CDC+HID", (0x1234, 0, 2, 4, hid_desc))```to this: ```pyb.usb_mode("VCP+HID", pid=0x1234, hid=(0, 2, 4, hid_desc))```

Configuration:
```
Micro Python v1.3.10-33-gee831ca on 2015-02-16; F4DISC with STM32F407
Ubuntu 14.04.1 LTS
```

I don't have a pyboard, so I can't test with the accelerometer. But, maybe the values are too small (I see a -40 shifting, so the values are in [-40, 40] ?)
I think it is important to know if the values are actually sent or not (cat /dev/input/js0 | hd)

**Pull request closed without merging**
