### PR TITLE
extmod/modframebuf.c: Add RGB444 (12 bit) color format to framebuffer.

### PR DESCRIPTION
**Pull request by jcernato**
The RGB444 format uses only 75% memory compared to RGB565 (16 bit). For every even pixel the 'red' and 'green' data is stored in one byte. The consecutive byte holds the 'blue' data in the first (MSB) four bits, while the last for bits (LSB) hold the 'red' data for the consecutive uneven pixel. This byte-sharing requires some logic and bitwise operations to set the pixel data correctly.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.

This format doesn't seem very common, and if we include it in the framebuf module then everyone has to "pay" for it in terms of increased firmware size.  Do you have some links to hardware that uses this format?

**Comment by peterhinch** [comment]
It is practical to save even more RAM with a framebuffer whose pixel size is smaller than that required by the hardware. The color data is expanded at runtime on a line by line basis. See [this driver](https://github.com/peterhinch/micropython-nano-gui/blob/master/drivers/ssd1351/ssd1351_generic.py). Even greater RAM savings may be achieved with a lookup table, e.g. [this driver](https://github.com/peterhinch/micropython-nano-gui/blob/master/drivers/ili93xx/ili9341.py) which uses 4-bit pixels expanded to 16-bit at runtime.

These techniques can be used to drive displays whose color formats aren't natively provided by `modframebuf.c`.

**Comment by jcernato** [comment]
@dpgeorge I bought this display "https://www.waveshare.com/wiki/Pico-LCD-2" which is a plug and play solution for the raspberry pico. While the provided demo-code might work with the Pico (haven't tested), it certainly does not with the Pico-W (allocation error).
The built in display-driver ST7789VW supports 12, 16 and 18 bit.

Thanks @peterhinch  for the links, these drivers provide a very elegant way to save RAM! A full 'high color' framebuffer seems a bit excessive on a microcontroller anyway.

**Comment by peterhinch** [comment]
See the [st7789 driver](https://github.com/peterhinch/micropython-nano-gui/blob/master/drivers/st7789/st7789_4bit.py). This uses 4-bit color with a LUT. This means that you have a set of 16 colors, each defined to 16-bit accuracy. It supports the exact display you are using with [nano-gui](https://github.com/peterhinch/micropython-nano-gui) and [micro-gui](https://github.com/peterhinch/micropython-micro-gui).

A full 16-bit buffer for this display would require 153,600 bytes (320x249x2) which is absurd on any Pico. The 4-bit driver reduces this to 38,400 bytes which is still big but entirely manageable if you instantiate it early.

**Pull request closed without merging**
