### PR TITLE
esp32/hashlib: Fix HASHLIB dependencies.

### PR DESCRIPTION
**Pull request by IhorNehrutsa**
Fix warning when all HASHLIB define`s is 0.
https://github.com/micropython/micropython/blob/d19371cb23b58151f27695a445f33505af6bdb1e/ports/esp32/mpconfigport.h#L104-L106

EDITED:
The warning is:
```
/home/pc/micropython/extmod/modhashlib.c:68:13: warning: 'hashlib_ensure_not_final' defined but not used [-Wunused-function]
   68 | static void hashlib_ensure_not_final(mp_obj_hash_t *self) {

```

### CODE REVIEW

**Comment by stinos** [comment]
Could you add in the commit message which warning it is?

**Comment by dpgeorge** [comment]
Is this necessary?  If all parts of `hashlib` are disabled then you may as well disable `MICROPY_PY_HASHLIB` altogether.

**Comment by IhorNehrutsa** [comment]
The warning is:
```
/home/pc/micropython/extmod/modhashlib.c:68:13: warning: 'hashlib_ensure_not_final' defined but not used [-Wunused-function]
   68 | static void hashlib_ensure_not_final(mp_obj_hash_t *self) {
```

> Is this necessary? If all parts of `hashlib` are disabled then you may as well disable `MICROPY_PY_HASHLIB` altogether.
In some ports `MICROPY_PY_HASHLIB_xxx` are independed from `MICROPY_PY_HASHLIB`.

**Comment by dpgeorge** [comment]
> In some ports `MICROPY_PY_HASHLIB_xxx` are independed from the `MICROPY_PY_HASHLIB`

Can you please provide more detail?  Why would a port enable `MICROPY_PY_HASHLIB` yet disable all of the hashing functions within that module?

**Comment by dpgeorge** [comment]
@IhorNehrutsa you need to provide more detail for the reason for this change.

**Pull request closed without merging**
