### PR TITLE
extmod: add ucryptolib with AES

### PR DESCRIPTION
**Pull request by Jongy**
Based on  #3460 and #3413.
Commits taken from pfalcon/pfalcon, specifically from 5ecec690b327aa784f21591b2f19817102242a91.
(Then I've added my additions)

### CODE REVIEW

**Comment by Jongy** [comment]
tests pass w/ mbedtls, too.

**Comment by dpgeorge** [comment]
Thanks for the PR.  It does make quite a lot of changes to the original code for the ucryptolib module, but I understand that's done to make it easire to share common code among the axtls and mbedtls implementations.

One change that is made here (upon the original implementation) is that the axtls object no longer allows decrypt after encrypt.  I guess this is OK since 1) the docs explicitly state that encrypt after decrypt, and vice versa, are not allowed; 2) there are no tests for decrypt after encrypt using the same crypto object.  It's also fair enough to forbid decrypt after encrypt on the axtls implementation, otherwise users will use that feature, and their code may then break when using another implementation.

I also see that mode constants (MODE_ECB, MODE_CBC) have been added to the module.  The original implementation made a point not to add these because they are "well known" constants.  It might be worth leaving these constants out to save code size (as per the original design philosophy).

**Comment by pfalcon** [comment]
> leaving these constants out to save code size (as per the original design philosophy).

Ditto for patching error messages to increase their size. Interested folks can (and should) implement a Python wrapper around ucryptolib to add all the constants and error messages they want.

**Comment by Jongy** [comment]
> One change that is made here (upon the original implementation) is that the axtls object no longer allows decrypt after encrypt. I guess this is OK since 1) the docs explicitly state that encrypt after decrypt, and vice versa, are not allowed; 2) there are no tests for decrypt after encrypt using the same crypto object. It's also fair enough to forbid decrypt after encrypt on the axtls implementation, otherwise users will use that feature, and their code may then break when using another implementation.

Furthermore, the extra logic required to support interleaving encrypts/decrypts on the same objects incurs performance penalty and code size increase.
Besides ECB, this is not even useful, so I feel okay to remove it.

> I also see that mode constants (MODE_ECB, MODE_CBC) have been added to the module. The original implementation made a point not to add these because they are "well known" constants. It might be worth leaving these constants out to save code size (as per the original design philosophy).

The penalty is 80 bytes for both, which isn't much IMO. Personally I'd prefer to write code using these fellas. Since it's easy to cut them out and make them optional with an `#if`, I guess that's what I'll do.

> Ditto for patching error messages to increase their size. Interested folks can (and should) implement a Python wrapper around ucryptolib to add all the constants and error messages they want.

I think the code size increase that extra error messages have caused is so slight comparing to their extra usefulness.

Anyway I do agree that MicroPython users should be able to compile it as minimal as possible, so an interesting feature to add would be to be able to cut out strings and replace with abbreviations or even magic values that can be looked up in a dictionary. In a similar way to how `qstr`s work, we can have a macro that expands to the string in case of "full" compilation, or expands to a magic value generated from the string in case of a minimal compilation. Also throw in abbrevs, etc.
Until we have that feature ^^, I prefer to increase code size by 50 bytes and have nicer messages for users of this module (Keep in mind - it's an external one). But I guess @dpgeorge it's up to you, I can shorten the messages if you'd like that.

**Comment by dpgeorge** [comment]
> But I guess @dpgeorge it's up to you, I can shorten the messages if you'd like that.

It'd be good to retain the existing error messages, and make the new ones that you add follow similar style to the existing ones in this module.

> so an interesting feature to add would be to be able to cut out strings and replace with abbreviations

We do already have 3 levels of error messages: terse, normal and detailed (see eg `MICROPY_ERROR_REPORTING`).  But the extmod modules don't use this config option and only provide one level of error reporting.

**Comment by dpgeorge** [comment]
> By "existing ones" you mean those before my edits?

Yes.  For example keep `mp_raise_ValueError("mode")`.

> Since it's basically just another option in the mpconfigport.h, any reason I shouldn't use MICROPY_ERROR_REPORTING in this case? I think it's suitable.

It's fine to use this option in extmod code, it's there to be used.  But just think: if you can write a short but understandable error message that doesn't benefit from being longer and can be used for all error-reporting levels (terse, normal, detailed) then that's a good way to go because it reduces the amount of code that needs to be written/reviewed/maintained.

For example, in `ubinascii.unhexlify` there is `mp_raise_ValueError("odd-length string")`.  That's short and to the point and doesn't really need to be any longer or more detailed: you passed in a *string* that has an *error* with the *value*, namely that it is of *odd-length*.  Note that the exception type (ValueError) gives a lot of information already about the kind of error, so no need to repeat that information in the info message.  Furthermore, this example can't really be reduced in size (without abbreviations, eg using str instead of string).  So it's pretty well suited for all error levels.

**Comment by Jongy** [comment]
Done. Committed separately on purpose and I believe it should be kept unsquashed because we can learn a lot from this Git history, what we care about and put effort into, etc.

**Comment by dpgeorge** [comment]
Thanks for updating based on feedback.  I've now merged this, see 473fe45da23f371d7beb6117c31922f9c9ee5942 through to 31f2f1e9675058685f4da5e7245473dcf6387135

I squashed the part that undid the changes to the tests because I don't see any need to make changes and then undo them straightaway.  The comment for this commit keeps the relevant info about minimising code size.

@Jongy job well done, thank you!  But for the future a few code-style nitpicks for this repo: 1) open braces go on the same line as the function prototype; 2) tests (eg conditionals) usually have the variable on the LHS and the constant on the RHS.

**Pull request closed without merging**
