### PR TITLE
py: Clarify which mp_unary_op_t's may appear in the bytecode.

### PR DESCRIPTION
**Pull request by pfalcon**
Not all can, so we don't need to reserve bytecodes for them, and can
use free slots for something else later.

### CODE REVIEW

**Comment by pfalcon** [comment]
Next step of https://github.com/micropython/micropython/issues/3291. Similar changes would be applied for binary ops.

**Comment by pfalcon** [comment]
Build failed, because somehow, the Thumb2 codesize increased. Which is sad, but probably have to live with.

**Comment by dpgeorge** [comment]
Looks good, thanks.

> Build failed, because somehow, the Thumb2 codesize increased.

With the compiler I'm using (arm-none-eabi-gcc 7.2.0) there is no change in size in the minimal build with this patch applied.

**Comment by pfalcon** [comment]
Merged.

**Pull request closed without merging**
