### PR TITLE
powerpc: Makefile fixes

### PR DESCRIPTION
**Pull request by shenki**

### CODE REVIEW

**Comment by dpgeorge** [comment]
Looks good, thanks!

Note: we don't use "signed-off" in MicroPython commit messages.  AFAIK that has specific meaning for committing to the Linux project and we'd need to adopt the same meaning here, or explicitly say what our meaning is.

Would be simpler at this stage to just not use signing-off.  What do you think?

**Comment by shenki** [comment]
> Note: we don't use "signed-off" in MicroPython commit messages. AFAIK that has specific meaning for committing to the Linux project and we'd need to adopt the same meaning here, or explicitly say what our meaning is.

The meaning is generally that you agree to the developer certificate of origin when submitting a change:

 https://developercertificate.org/

Many open source projects have adopted it. I put it there as it's in my muscle memory when publishing commits!

I think it would be appropriate for micropython to adopt in the future. However I'll repush these changes without the sob so they can go in now.

**Comment by dpgeorge** [comment]
> The meaning is generally that you agree to the developer certificate of origin when submitting a change:
> 
> https://developercertificate.org/
> 
> Many open source projects have adopted it. I put it there as it's in my muscle memory when publishing commits!
> 
> I think it would be appropriate for micropython to adopt in the future.

Yes I agree.  I guess as a transition it's ok for some commits to use it and not others?

**Comment by shenki** [comment]
Yeah that's fair enough. I don't think there's any harm, it's just there's no requirement until Micropython adopts it formally.

**Pull request closed without merging**
