### PR TITLE
networking: Allow boards to define additional network interfaces.

### PR DESCRIPTION
**Pull request by iabdalkader**
Allows boards to add additional network interfaces, following `MICROPY_BOARD_ROOT_POINTERS`. With this it should be possible for a board with a network interface to add it without changing `mpconfigport.h`

Note: Can this be fixed please ? I looked at the uncrustify config and tried changing options around but no luck.

```C
#define MICROPY_PORT_NETWORK_INTERFACES \
    MICROPY_HW_NIC_ETH  \
->       MICROPY_BOARD_NETWORK_INTERFACES \
```

### CODE REVIEW

**Comment by dpgeorge** [comment]
> Note: Can this be fixed please ?

I don't follow.  Do you want to have extra indent on the last line?  Or not?  The PR at the moment looks good, it doesn't have any extra indent and uncrustify doesn't complain.

**Comment by iabdalkader** [comment]
> Do you want to have extra indent on the last line? Or not

I don't want the extra indent, `codeformat.py` (uncrustify) adds an extra indent to the last of every multiline define body, I fixed those manually. Plus I get some warnings, it could be a newer uncrustify:

```bash
$ uncrustify -v
Uncrustify_d-0.74.0_f

$ ../tools/codeformat.py rp2/mpconfigport.h 
micropython/tools/uncrustify.cfg:902: option 'sp_before_tr_emb_cmt' is deprecated; did you want to use 'sp_before_tr_cmt' instead?
micropython/tools/uncrustify.cfg:905: option 'sp_num_before_tr_emb_cmt' is deprecated; did you want to use 'sp_num_before_tr_cmt' instead?
micropython/tools/uncrustify.cfg:1121: option 'indent_sing_line_comments' is deprecated; did you want to use 'indent_single_line_comments_before' instead?

$ git diff rp2/mpconfigport.h 
```
```diff
diff --git a/ports/rp2/mpconfigport.h b/ports/rp2/mpconfigport.h
index 461ae3de8..60ca0343d 100644
--- a/ports/rp2/mpconfigport.h
+++ b/ports/rp2/mpconfigport.h
@@ -197,7 +197,7 @@ extern const struct _mod_network_nic_type_t mod_network_nic_type_nina;
 
 #define MICROPY_PORT_NETWORK_INTERFACES \
     MICROPY_HW_NIC_NINAW10  \
-    MICROPY_BOARD_NETWORK_INTERFACES \
+        MICROPY_BOARD_NETWORK_INTERFACES \
 ```

**Comment by dpgeorge** [comment]
Merged in fe8b47e29fb40566fa35e97e02ab06cfab19bf6e

**Comment by dpgeorge** [comment]
I'm using:
```
$ uncrustify -v
Uncrustify_d-0.72.0
```
And it doesn't add an extra indent on these lines.  So it must be the newer version you are using.

**Comment by iabdalkader** [comment]
> So it must be the newer version you are using
```
$ uncrustify -v
Uncrustify_d-0.74.0_f
```

When/if it gets updated it's going to be an issue.

**Pull request closed without merging**
