### PR TITLE
renesas-ra: Consolidate hal_entry.c code and remove hal_entry() func.

### PR DESCRIPTION
**Pull request by dpgeorge**
The hal_entry.c code is duplicated across all boards, so consolidate it to a common ra_hal.c file.  And remove the hal_entry() function because it simply calls main().

### CODE REVIEW

**Comment by dpgeorge** [comment]
@TakeoTakahashi2020 I am trying to simplify the renesas-ra port, to reduce the amount of code that is in the `boards/` directories.  This PR is a start, it just makes a small step to remove some duplicated code.

What do you think?

**Comment by TakeoTakahashi2020** [comment]
Thank you very much @dpgeorge san.  I agree with you and it's good for me.  I just checked build and got REPL for all EKs & CLICKER.  It looks working well.

**Comment by dpgeorge** [comment]
Thank you @TakeoTakahashi2020 san for reviewing and testing.

Now merged.

**Comment by iabdalkader** [comment]
@TakeoTakahashi2020 Is there any reason PA/B pins are not generated with `make-pins.py` ? I need to use those pins in `mpconfigboard.h` but they're not generated in headers.

**Comment by TakeoTakahashi2020** [comment]
@iabdalkader san, Thank you for the report of make-pins.py issue.  I was not aware of it sinece EK & CLICKER's device has no PA/B pins.  I will check it.

**Pull request merged**
