### PR TITLE
Fix mpy cross make undefine

### LINKED ISSUE #3099: mpy-cross makefile error messages 'invalid `override' directive'
Running make clean on mpy-cross and a subsequent build produces the following output. The build is otherwise successful.
```
$ cd mpy-cross
[adminpete@axolotl]: /mnt/qnap2/data/Projects/MicroPython/micropython/mpy-cross
$ make clean
Makefile:4: invalid `override' directive
Makefile:5: invalid `override' directive
Makefile:6: invalid `override' directive
Makefile:7: invalid `override' directive
Makefile:8: invalid `override' directive
Makefile:9: invalid `override' directive
Makefile:10: invalid `override' directive
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
rm -f mpy-cross
rm -f mpy-cross.map
rm -rf build 
[adminpete@axolotl]: /mnt/qnap2/data/Projects/MicroPython/micropython/mpy-cross
$ make -j 8
Makefile:4: invalid `override' directive
Makefile:5: invalid `override' directive
Makefile:6: invalid `override' directive
Makefile:7: invalid `override' directive
Makefile:8: invalid `override' directive
Makefile:9: invalid `override' directive
Makefile:10: invalid `override' directive
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
mkdir -p build/genhdr
make: Warning: File `build' has modification time 20 s in the future
mkdir -p build/py
mkdir -p build/py/../extmod
mkdir -p build/py/../lib/embed
mkdir -p build/py/../lib/utils
Generating build/genhdr/mpversion.h
GEN build/genhdr/qstr.i.last
GEN build/genhdr/qstr.split
GEN build/genhdr/qstrdefs.collected.h
QSTR updated
GEN build/genhdr/qstrdefs.generated.h
CC ../py/mpstate.c
CC ../py/nlrx86.c
...
```

### PR DESCRIPTION
**Pull request by dpgeorge**
Fixes #3099

### CODE REVIEW

**Comment by dpgeorge** [comment]
This PR (the change to mpy-cross/Makefile) seems to fix the issue with warnings from make v3.81 about "override" being invalid.  @peterhinch @dhylands can you please verify that it does fix it for you, if you still have make v3.81?

**Comment by peterhinch** [comment]
Alas I've upgraded my machines and lost V3.81.

**Comment by dhylands** [comment]
I no longer see the warnings and the build works.

**Comment by dhylands** [comment]
Aside: I found a really nify script called git-pr from https://gist.github.com/jhnns/d654d9d6da6d3b749986 which works really nicely for checking out PR branches.

**Comment by dpgeorge** [comment]
Thanks guys for checking, this is now merged.

**Pull request merged**
