### PR TITLE
STM32G4 series added

### PR DESCRIPTION
**Pull request by H-Grobben**
I've added the STM32G4 series to the micropython project. I did test the implementation on the Nucleo board that is also included here (G474RE), and I also tested the FDCAN in pyb_can.c. But probably seeing what is happening to other pyb_* files this one needs to be transfered later to a machine_can.c.
Only thing with the Nucleo board is that it uses the LPUART as connection to the USB serial on the integrated programmer (ST-Link v3), so to use MicroPython I needed to re-wire the uart. A readme is supplied within the board folder with the 2 wires I added.
The G4 series is also added to the stm32lib, which I also just sent in a pull request.

### CODE REVIEW

**Comment by H-Grobben** [comment]
I did not enable the continuous integration build of the added Nucleo board in de ci.sh script, because I don't know if that should be done for all pull requests, and because I changed the build optimization setting for the STM32 boards in the Makefile during debug. Otherwise the code wouldn't fit during my debug sessions.

**Comment by dpgeorge** [comment]
Thanks for this, it's definitely a great addition!  I will get to reviewing this as soon as I can.

**Comment by chrismas9** [comment]
@dpgeorge Would now be a good time to review [https://github.com/micropython/micropython/pull/5396](url) - support for LPUART1 as standard UART?

It would be good to have REPL on STLINK without having to modify the NUCLEO G474RE hardware. I can rebase and retest it. I would also like to discuss the port name ('LP1' or next available UART number) as using LP1 added some complexity. Due to how the UART driver works the next available UART number has to be used internally and can easliy be explained in mpconfigboard.h which is where everyone has to look to see what UARTs are available for a port.

**Comment by H-Grobben** [comment]
Integrated pull request #5396 and tested it on Nucleo board G474RE. Now we don't need additional wires for REPL uart
https://github.com/AEMICS/micropython/commit/0c39b07ed2a5754ced4e11a716340afb3df27ef1

**Comment by H-Grobben** [comment]
I'v renamed the branch in our repo to STMG4, which breaks the link to this pull request. I will re-create the pull request.

**Pull request closed without merging**
