### PR TITLE
Make unix usocket connect and bind functions more similar to CPython

### PR DESCRIPTION
**Pull request by savant2212**
Make connect and bind functions use as argument: tuple (host, port) for ipv4, tuple (host,port,flow,scope) for ipv6 and string for unix socket. 

current version don't resolve dns names to ip addresses.

### CODE REVIEW

**Comment by dpgeorge** [comment]
@pfalcon what to do here?

Personally I would like to see unix's usocket module support a more human friendly interface to socket.connect.  But I see that you have been very clever in how you've implemented it: if one always calls getaddrinfo and uses the result in connect then the code will be portable between CPython and unix/uPy.

The Python docs do however specify that the return value of getaddrinfo is an IP address string and port pair for AF_INET, so your implementation is not compliant in that respect.

**Comment by pfalcon** [comment]
Well, *socket* module (from micropython-lib) does provide human-friendly interface.

Otherwise, this is just waits for overall evolution of uPy. Current criterion is that it's strange that bare-metal, space-constrained ports provide more "human-friendly" interface than unix, not that unix needs something more "human-friendly" (micropython-lib has a lot of that). So, I don't want to reject this, but there're more important things to add builtin. For example, I kinda see os.read() should be such, as its FFI implementation is not efficient. base64 is missing, random, etc. Maybe when all that is added, it will be clear we don't want couple of Ks more ;-).

**Comment by pfalcon** [comment]
Otherwise, patch has following issues: codestyle inconsistent with codebase (whitespace placement), new features are not configurable.

**Comment by dpgeorge** [comment]
> Well, socket module (from micropython-lib) does provide human-friendly interface.

You mean socket.create_connection?

> Current criterion is that it's strange that bare-metal, space-constrained ports provide more "human-friendly" interface than unix

That's because they needed the socket API implemented from scratch, and it wanted to be a uniform interface for multiple different socket (NIC) implementations.

**Comment by dpgeorge** [comment]
@pfalcon how are your feelings about this after 3 months?  I'm now -0.1 on merging, after successfully writing and using multiple TCP and http, client and server scripts that use usocket directly [and use getaddrinfo, eg getaddrinfo("localhost", 7000)].

**Comment by pfalcon** [comment]
Well, I still not see a strong usecase to have these builtin. Moreover, all socket examples I came by over last few months happened to be getaddrinfo() based. So, I guess it slowly becomes a baseline to use getaddrinfo(), as a generic way to supporting different addressing schemes and protocols (IPv4, IPv6, etc.)

So, let's just close this then, until good reasons to resurrect it will be provided.

**Comment by dpgeorge** [comment]
Ok!  Let's promote use of getaddrinfo where appropriate.

**Pull request closed without merging**
