### PR TITLE
extmod/vfs: Implement import from non-FAT filesystems.

### PR DESCRIPTION
**Pull request by aykevl**
To make it possible to import from other types of filesystems.

Consumes about 100 bytes, so should maybe be disabled by default.

EDIT: see https://github.com/tralamazza/micropython/issues/96#issuecomment-336736379

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks, but this feature is part of a pending PR: see https://github.com/micropython/micropython/pull/3034 in particular this https://github.com/micropython/micropython/pull/3034/commits/28c5f78e0f18401e72d490ba70ef9c1c383509be (I don't expect you to have seen that, it was quite hidden!)

**Comment by aykevl** [comment]
Ah, I see. Any idea if/when it might be merged? It's not super important, but would be useful for the nrf port.

**Comment by dpgeorge** [comment]
> Any idea if/when it might be merged?

I will do it after v1.9.3 is released.

**Comment by dpgeorge** [comment]
This was implemented by 89b1c4a60cd43697e755b645127387d3b34e6d3f

**Comment by aykevl** [comment]
Thank you!

**Pull request closed without merging**
