### PR TITLE
Zephyr port: Update for Zephyr 1.14

### PR DESCRIPTION
**Pull request by pfalcon**
Zephyr is at 1.14-rc1 now, final release is to be made by the end of month or so. This patchset includes changes accumulated in my branch.

### CODE REVIEW

**Comment by pfalcon** [comment]
@MaureenHelm: FYI

**Comment by dpgeorge** [comment]
Thanks, it looks good.  Is it ready to be merged now, or wait until 1.14 is released (since the current version here compiles cleanly with 1.13.0)?

**Comment by pfalcon** [comment]
Well, I exactly waited until 1.14 RC phase before submitting those, but I'd suggest to merge them now, to let interested parties to test it before the 1.14 release.

**Comment by dpgeorge** [comment]
Ok, merged in a42c1d9fd5bc18dc69c635c3dc876bd52cba2240 through 493ee7df1875f3b15eac1a725e933fa7a386bd71

**Comment by MaureenHelm** [comment]
Thanks @pfalcon and @dpgeorge!

**Pull request closed without merging**
