### PR TITLE
tools/gen-cpydiff.py: Fix formatting.

### PR DESCRIPTION
**Pull request by iabdalkader**

### CODE REVIEW

**Comment by stinos** [comment]
This file is already formatted by code-format.py I think, so not sure this fix is really worth it. Or is this something newer versions of black do, i.e. what lead you to these changes? If anything, imo it would be better to at once apply formatting more consistently: if I'm not mistaken PEP8 wants those comments to start with a capital and end with a dot. Which is also what most other files in the tools/ directory seem to do. But in any case it would be better if all comments in the file look the same. And you missed the comment at the top as well. Did you consider other files in this directory as well?

**Comment by stinos** [comment]
Likely this is the reason https://github.com/psf/black/pull/1740. It's in the release 21.4b0 which gets used by the CI.
Please mention this in the commit message.

@dpgeorge : when merged the commit SHA should also be put into .git-ignore-revs

**Comment by dpgeorge** [comment]
Thanks for this!  Merged in 0f78c36c5aa458a954eed39a46942209107a553e with improved commit message, and additional commit 30d9f77cc535306eeb9eed6f17e71355fd58995a for change to `.git-blame-ignore-revs`

**Comment by iabdalkader** [comment]
> what lead you to these changes

Hi sorry for not replying earlier, I sent another PR and it failed checks because of this file so I ran codeformat.py on it and sent this PR to fix it first, now both PRs are merged @stinos

**Pull request closed without merging**
