### PR TITLE
Added the nRF52840-MDK-USB-Dongle board definition

### PR DESCRIPTION
**Pull request by mattytrentini**
Added a board definition for the [nRF52480-MDK-USB-Dongle](https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle/).

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks a lot!  I guess you tested it?  Did you test with BLE enabled, ie using the SoftDevice?  Also, did you test USB serial?

Regarding the images: no other board in the repo has board images in the board configuration directory, so best not to put them there.  I think at this stage just linking to external URLs for the images is the best thing to do in the README.md.

**Comment by mattytrentini** [comment]
I did test the basics, the REPL over USB serial. I haven't tested the BLE soft device yet; I'll put it on the todo list!

OK, I'll remove the images. Though I must say that for the relatively small size increase, _more_ images could be quite helpful! 

There's one other thing that occurred to me after submitting the PR; as I've noted in the README `make deploy` is invalid for this board. I _could_ make it valid if, instead of using `nrfjprog`, we used `nrfutil`...

**Comment by dpgeorge** [comment]
> I did test the basics, the REPL over USB serial. I haven't tested the BLE soft device yet;

Testing USB is the main thing.  BLE would be a bonus :)

> OK, I'll remove the images. Though I must say that for the relatively small size increase, _more_ images could be quite helpful!

In the docs images would be helpful.  Maybe that can be looked at as part of SoD...

> There's one other thing that occurred to me after submitting the PR; as I've noted in the README `make deploy` is invalid for this board.

It might be possible to set `FLASHER` in the board's .mk file so that it selects a flashing method that does work, maybe openocd?

**Comment by glennrub** [comment]
I finally got a MDK dongle in my hand to test this out. It worked very well :)

>  Did you test with BLE enabled, ie using the SoftDevice?

The `ble_drv.c` needs a separate PR to compile (I'll PR this in parallel). Besides from that it worked great with some slight modifications to makefiles / linker scripts. I'll propose some changes in review.

@mattytrentini, my MDK turned out to have the UF2 bootloader, not the Open Bootloader. I guess future MDKs might get shipped with the UF2 bootloader instead. When DFU uploading an UF2 MicroPython firmware to the drive, it disappeared, and subsequent updates not possible for me. I kind of expected this. (Luckily i manged to recover it by an external flasher). For now, i believe it would be fine to document as you do, how generate for Open Bootloader. Maybe worth adding a section that Open Bootloader currently needs to be flashed using a programmer in case it has the UF2. 

> It might be possible to set FLASHER in the board's .mk file so that it selects a flashing method that does work, maybe openocd?

I believe this is a good idea, setting the `FLASHER` to `nrfutil`. The tool is available via `pip`. And, if we could also add a deploy hook for this board in the Makefile that generates the DFU package and transfer it. We would possibly also need to indicate which serial port to use. Maybe use the same approach as esp8266 port, setting PORT parameter to make? 
https://github.com/micropython/micropython/blob/master/ports/esp8266/Makefile#L200

**Review by glennrub — COMMENTED** [review]
I really hope i did not overwhelm you with big changes. Take a look at it, and see if you like any of it :)
Meanwhile, i'll proceed updating the `ble_drv.c` so that we get the BLE back.

**Comment by glennrub** [comment]
See https://github.com/micropython/micropython/pull/6142 for the mentioned `ble_drv.c` fix.

**Comment by glennrub** [comment]
@mattytrentini, to help out a bit i've pushed my proposed changes to the top commit at [nrf52840_mdk branch](https://github.com/glennrub/micropython/commits/nrf52840_mdk). If you think this is a good idea and it works for you, feel free to cherry-pick the commit and squash it into yours. I would not mind. I have not updated the `README` in this commit, only shown the linker/makefile changes i had in mind.

**Comment by dpgeorge** [comment]
Before this can be merged the images need to be removed.

**Comment by glennrub** [comment]
@dpgeorge, @mattytrentini , i'm ok merging this as is. I can issue a follow-up PR with my proposals on how to run this with SD and `nrfutil` as `FLASHER` after merge of this. We should really consider the tail bootloader (end of flash) to not accidentally write a filesystem or even code over that region (size of the bootloader is 128kb). I'll cover this in the follow-up PR.

**Comment by dpgeorge** [comment]
@mattytrentini I know you were going to look at pulling in @glennrub 's patch linked above, but as he mentions it might be better to just put this is now and then @glennrub can follow up with his changes.  What do you think?

**Comment by mattytrentini** [comment]
@glennrub Apologies for appearing to ignore your messages; I wasn't _actually_ ignoring you, I just hadn't had a chance to return to this issue! I've shifted off a project that was going to use the nRF52 series and I've been kept very busy on other work. For what it's worth your changes _look_ good.

@dpgeorge Yes, I think that's the best approach.

**Comment by dpgeorge** [comment]
Rebased, squashed and merged in 486cb6dd4a1a17ff2567f721855d4626fdf69412

**Pull request closed without merging**
