### PR TITLE
ports/esp32/ulp: Enable ULP (FSM) for S2 + S3.

### PR DESCRIPTION
**Pull request by ThinkTransit**
This pr enables the ULP for the S2 and S3 chips.

Note this is the FSM (Finite State Machine) ULP, not the RISCV ULP.

### CODE REVIEW

**Comment by mattytrentini** [comment]
Nice addition!

Perhaps we should update the [ULP docs](https://docs.micropython.org/en/latest/library/esp32.html#ultra-low-power-co-processor) as well? Specifically to a) specify that it's the ULP _FSM_ and b) that it's supported on ESP32/S2/S3.

**Comment by ThinkTransit** [comment]
> Nice addition!
> 
> Perhaps we should update the [ULP docs](https://docs.micropython.org/en/latest/library/esp32.html#ultra-low-power-co-processor) as well? Specifically to a) specify that it's the ULP _FSM_ and b) that it's supported on ESP32/S2/S3.

Good idea will do.

**Comment by ThinkTransit** [comment]
Docs updated.

**Comment by stephanelsmith** [comment]
Are there any updated examples on getting started with ULP on latest firmware?

Quick look found this:
https://github.com/micropython/micropython-esp32-ulp

Right direction?

**Comment by dpgeorge** [comment]
Thank you!

**Comment by wnienhaus** [comment]
> Are there any updated examples on getting started with ULP on latest firmware?
> 
> Quick look found this: https://github.com/micropython/micropython-esp32-ulp
> 
> Right direction?

Yip, right direction, however at present micropython-esp32-ulp does not support the S2 and S3, because their ULP FSM is not binary compatible with that of the original ESP32. I'm currently busy adding support (see https://github.com/micropython/micropython-esp32-ulp/issues/85 for status), so hopefully in a week or two there will be a testable version - would be happy to get feedback then.

**Pull request merged**
