### PR TITLE
mimxrt: Extend the module time.

### PR DESCRIPTION
**Pull request by robert-hh**
Methods added:
time.time()
time.time_ns()
time.gmtime()
time.localtime()
time.mktime()

The rp2 port was uses as the template for the change.

### CODE REVIEW

**Comment by kadamski** [comment]
The two files - the ports/rp2/modutime.c and ports/mimxrt/modutime.c are almost identical. They really differ in non-important ways. This is anyway true for other ports as well. We should really share more code and avoid as much of duplication. But until that is made easily available, this looks as good as other ports :)

**Comment by robert-hh** [comment]
Yes. I took the file from the rp2 module and changed just  few but important lines: access to and use of the RTC. And both files contain code found as well machine_rtc.c. So more standardization may be possible, but it does not exist yet. And it would add just another layer of code, increasing the code size of each port without adding functionality. For some ports this is essential.

**Comment by dpgeorge** [comment]
This looks good as it is.  But I do agree there's scope for eventually factoring out all the common code across ports that implement these time functions.

**Comment by robert-hh** [comment]
Yes. There is a lot of duplication. It could move into a extrmod/modutime.c, and the rtc access method into mphalport.c

**Comment by dpgeorge** [comment]
> It could move into a extrmod/modutime.c, and the rtc access method into mphalport.c

Yes that makes sense (although see also extmod/utime_mphal.c).  But this PR can go in first.

**Comment by dpgeorge** [comment]
Merged in 8edc3aacdda7b65ad6dd6ad4af0bb1a570ef9f47

**Pull request closed without merging**
