### PR TITLE
rp2/machine_uart.c: Change wait in uart.flush() and uart.read().

### PR DESCRIPTION
**Pull request by robert-hh**
Do not wait in the worst case up to the next ms tick.

Fixes Issue #13377

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the patch.

Now I think about it, maybe also the `mp_machine_uart_read` function needs to be changed in the same way?

UART interrupts are enabled for both RX and TX, but they are FIFO interrupts and so an IRQ won't necessarily fire, eg, if you're waiting for exactly 1 incoming byte.

For writing in `mp_machine_uart_write`, it might be OK to wait for an IRQ there, because the loop only waits if the FIFO is full, and that will definitely trigger an IRQ once the FIFO is drained.

**Comment by dpgeorge** [comment]
Would be good if we can write a test for this failure, eg write some bytes out on the UART and time how long the flush takes.

**Comment by robert-hh** [comment]
Thanks for the comments. I will do both, changing uart.read and write a test case.

**Comment by robert-hh** [comment]
Updated with a test and change for uart.read().

**Comment by projectgus** [comment]
Good catch, thanks @robert-hh. Forgot that you don't always get an interrupt in these cases due to the FIFOs.

**Comment by dpgeorge** [comment]
I've updated the test so it tests multiple baud rates, and so it's possible to run on other ports/boards.

**Pull request merged**
