### PR TITLE
Regenerate all qstrs when config files change

### PR DESCRIPTION
**Pull request by dpgeorge**
This should address #2982 in a minimal and effective way.

### CODE REVIEW

**Comment by stinos** [comment]
Works for me, thanks!

**Comment by dpgeorge** [comment]
@stinos I used exactly the logic you suggested in your initial pseudo-code in https://github.com/micropython/micropython/issues/2982#issue-217497824 .  I think this is good enough to make it work in most cases.

**Comment by stinos** [comment]
It took me a while to figure out that concise Makefile syntax but yes that's what I was after. This should indeed fix most cases.

**Comment by dpgeorge** [comment]
Thanks for the feedback, merged in 7ad04d17dabd503b0a79426166bcdc9e8ea4bf91

**Pull request closed without merging**
