### PR TITLE
py: modify parse.c to avoid need for ssize_t (not available on all platforms)

### PR DESCRIPTION
**Pull request by tomlogic**

### CODE REVIEW

**Comment by tomlogic** [comment]
I'm porting to an ARM-based platform which didn't have unistd.h or ssize_t.  I found it was possible to (I believe) safely modify the code to use size_t variables.  The loop conditional ensures that the subsequent subtractions in the loop body don't go beyond 0.

**Comment by dpgeorge** [comment]
Did you check code size / generated code?  It will probably less efficient this way (more subtractions to do during the loop).

The alternative is to define your own ssize_t in mpconfigport.h and/or provide a trivial unistd.h in the port's directory.

**Comment by dhylands** [comment]
I see ssize_t defined in 3 different header files (on my ubuntu 16.04 system).
1 - stdio.h
2 - unistd.h
3 - sys/types.h

The recv function (from sys/socket.h) returns type ssize_t and the docs have it #including <sys/types.h>

**Comment by tomlogic** [comment]
I have not compared code size on a Unix build, but from looking at the diff, there are the same number of subtractions in the new code as in the old.

I'm using IAR Embedded Workbench which defines `size_t` as a `__SIZE_T_TYPE__` and does not define `ssize_t` anywhere.  I imagine I can get away with creating a `unistd.h` for my platform that typedefs `ssize_t` as a signed integer.

**Comment by dpgeorge** [comment]
`typedef intptr_t ssize_t` should be adequate.

**Pull request closed without merging**
