### PR TITLE
extmod: fix btree so stream is not GC'd, and so it doesn't leak memory

### PR DESCRIPTION
**Pull request by dpgeorge**
For ports that have a system malloc which is not garbage collected, the stream object for the DB must be retained separately to prevent it from being reclaimed by the MicroPython GC.  This is true for the unix and esp32 ports.  A test is provided for this case, which fails on unix without this PR's fix.

Fixes issue #5940 (although the actual scenario there is not tested to see if it's fixed by this patch).

Also, for ports that have a system malloc which is used by btree, the memory should be free'd when the btree object goes out of scope by using a finaliser.

### CODE REVIEW

**Comment by carstenblt** [comment]
Problem is fixed for my use case on esp32.

**Comment by dpgeorge** [comment]
Thinking about this some more, the patches here are not strictly needed.  The main point is that the `btree` object will not close the underlying file/stream object when the btree is closed/deleted.  It's up to the user to do that.  And if the user retains a reference to the file/stream to close it then the GC can find a reference to the file/stream, the btree does not need to have such a reference.

So the alternative to this patch here would be to update the documentation to state very explicitly that 1) code should always retain a reference to the underlying file/stream; 2) code should always do a `btree.close()` followed by a `file.close()` to clean up the DB.

**Comment by carstenblt** [comment]
In my opinion the "expected" behavior still would be to not have the file object gc'd. Also, does it have any negative side effects?

In my use case keeping the file reference wouldn't be necessary, as I never intend to close the file and I don't have any "clean shutdown" procedures. I imagine this to be the case for many applications.

**Comment by dpgeorge** [comment]
> In my opinion the "expected" behavior still would be to not have the file object gc'd. Also, does it have any negative side effects?

I tend to agree, that it shouldn't crash just because the code didn't retain a reference (which, as you say, may not be needed in certain cases).

The cost to retain the reference in the btree object is just a little bit of code space (heap memory use is 0 because the btree object still uses only 2 GC blocks).

OTOH, the finaliser code is probably not needed.

**Comment by dpgeorge** [comment]
Merged just the fix with retains a reference to the underlying stream (and not the finaliser code).

**Pull request merged**
