### PR TITLE
RFC: use Kconfig for configuration

### PR DESCRIPTION
**Pull request by dlech**
This is a proposal MicroPython 2.0.

As we know, MicroPython has many, many configuration options. The current method of using a combination of `mpconfigport.h` and `mpconfigport.mk` works reasonably well, but I find myself spending quite a bit of time jumping through the source code to figure out what options actually do and how they interact with each other.

Kconfig is a configuration system for software projects based on make and C. It comes from the Linux kernel and is used in many other large projects, like U-boot, Busybox, Zephyr, etc. It works by declaring configurations using the [Kconfig language](https://www.kernel.org/doc/html/latest/kbuild/kconfig-language.html). It provides a _very_ powerful way to express dependencies between configuration options. It also provides and easy way for users to build custom configurations using an interactive menu rather than having to edit text files.

Recently, a Python implementation of Kconfig called [Kconfiglib](https://github.com/ulfalizer/Kconfiglib) has been developed. It is tested against the Linux kernel and used in the Zephyr project (among others), so it quite stable and robust already.

So far, I have added basic support for Kconfig to the STM32 port and converted a few groups of configuration options to the new format. I've been quite happy with the results.

Here are some screenshots of what it looks like (there is also a text-based menu interface for those who don't like to leave the terminal or use the mouse :wink:):

image

This is the default view. The upper pane shows the selected configuration. Detailed information on each option is visible in the lower pane.

image

The tree format makes it easy to browse the options in an organized way and hides irrelevant options.

image

For example, we have selected the STM32 port above, so only STM32 boards are listed.

image

The dependency of options is also shown. For example options that only affect the inline Thumb emitter are only visible/selectable if the parent option is selected.

image

There are also lots of hidden options that are not user-selectable because they only depend on other selections. But these can be shown for debugging.

---

In addition to the menu system, Kconfiglib is also fully automatable (because it is a Python library), so it will be much easier for anyone that wants to automatically generate custom configurations to do so.

Changing the configuration system like this will of course be quite disruptive for anyone using custom configurations already (which is why I consider it a MicroPython 2.0 thing) and will undoubtedly come with some growing pains. But this will certainly make customizing MicroPython much easier for users. And if MicroPython is going to be around for many more years, this will be a great help in keeping it maintainable.

Also, please see the individual commit messages for more nitty-gritty details.

### CODE REVIEW

**Comment by peterhinch** [comment]
That sounds great - the config options are confusing.

Some of us work on multiple projects. Consequently some build options need to be defined on a per project basis, notably the set of frozen modules. Currently this can be done with manifests and symlinks.

The ideal would be to be able to define an entire configuration on a per project basis, with an ability to create a new project with its config initially copied from an existing one. Maybe Kconfig already enables this?

**Comment by chrismas9** [comment]
This looks very useful. I am currently working on adding more options to the 192 and 256k STM32 ports to make room for frozen code. I am documenting the code size of each option and adding more options to mpconfigboard.h

I would be interested in collaborating on this for STM32.

**Comment by stinos** [comment]
> I find myself spending quite a bit of time jumping through the source code to figure out what options actually do and how they interact with each other

This only solves the latter, right? Or is there a way to have the full description of the options (as stated in mpconfigport.h) displayed in the  selection menu?

Still, this looks like an interesting alternative to just having different aliases/shell scripts/whatever people use now to deal with different configurations. However a major hindrance to adoption seems to be that it breaks many things, and I don't know enough to tell if it's really needed; so:
- does everything in principle remain backwards-compatible so people can just continue using `make CROSS_COMPILE=xxx V=1` and similar? (after fixing things like unconditionally including kconfig.h which breaks pretty much all builds) If not, is there a way to make it so, i.e. have Kconfig on top of all other things, less invasive? That would be the ideal scenario.
- is it really needed to have so many changes to makefile variable names?
- how do kernel devs and others deal with maintainance? Until now a config option and it's dependencies get defined in the code (and sometimes the makefile I guess) only. Now this knowledge has to be duplicated in the Kconfig file.

**Comment by dlech** [comment]
> The ideal would be to be able to define an entire configuration on a per project basis, with an ability to create a new project with its config initially copied from an existing one. Maybe Kconfig already enables this?

Yes it does. Kconfig saves all of the selected configuration options in a single file that can be copied and shared.

**Comment by dlech** [comment]
> > I find myself spending quite a bit of time jumping through the source code to figure out what options actually do and how they interact with each other
> 
> This only does something for the latter, right? Or is there a way to have the full description of the options (as stated in mpconfigport.h) displayed in the selection menu?

All user-visible options can have a `help` paragraph that gives a detailed explanation of the option. This information is displayed in the selection menu (in the text version, you have to press `h` to show it). The few options I have converted so far don't really show this very well.

**Comment by dlech** [comment]
> However a major hindrance to adoption seems to be that it breaks many things, and I don't know enough to tell if it's really needed

I am 100% in favor of not breaking things if it can be avoided. But I am afraid there will be some things that can't be avoided. So that's really what I'm trying to get a feel for here. This is a major change and in spite of our best effort there will be some annoying (hopefully minor) breakages. So do we as a community thing that this provides enough benefit in the long run to outweigh the rough spot it will cause in the short term.


>     * does everything in principle remain backwards-compatible so people can just continue using `make CROSS_COMPILE=xxx V=1` and similar? (after fixing things like unconditionally including kconfig.h which breaks pretty much all builds) If not, is there a way to make it so, i.e. have Kconfig on top of all other things, less invasive? That would be the ideal scenario.

Passing make variables will still work as before. But certain variables, like `BOARD=` will get moved to the configuration file, so they won't work as before.

To fix the current failures, all ports/boards will be given a default configuration file rather than conditionally including kconfig.h. I don't really see a point to being able to use Kconfig for some ports, but not all of them.

---

Getting slightly off topic here...

In this PR, I have also proposed a new top-level `Makefile`. So it would mean running `make` in the top level directory instead of `make -C ports/stm32`, for example. Part of the reason for doing this is that perhaps in the future we could use something like Kbuild that would greatly simplify makefiles.

It would look something like this... In a makefile, we would just have:

    obj-$(CONFIG_MICROPY_PY_USELECT) += moduselect.o

Instead of what we have now in the C files:

    #include "py/mpconfig.h"
    #if MICROPY_PY_USELECT
    ...
    #endif // MICROPY_PY_USELECT

This would speed up build time since we no longer have to parse files that are not compiled.

... but this is a discussion for another day.

---

>     * is it really needed to have so many changes to makefile variable names?

Do you mean adding the `CONFIG_` prefix everywhere? Yes, this is just how Kconfig works. Although it creates a bunch of noise, I actually think it is kind of nice because it shows us which options have been converted to Kconfig and which have not. We aren't going to be able to convert all of the options in a single day, so it will be useful to have this distinction to know where to look.


>     * how do kernel devs and others deal with maintainance? Until now a config option and it's dependencies get defined in the code (and sometimes the makefile I guess) only. Now this knowledge has to be duplicated in the Kconfig file.

I wouldn't say that it gets duplicated. Rather the option and the dependencies are _defined_ in Kconfig and are only _used_ in code. So a patch that introduced a new configuration option usually includes both the new item in the Kconfig file as well as changes to code that use that option.

And on the maintenance side of things, for the ARM architecture of the Linux kernel, there is a builder that continuously builds random configurations. This helps find compile errors for obscure combinations of options and also reveals many bugs in the relations defined in the Kconfig file (e.g. we forgot to define that option A needs to always select option B because A can't possibly work unless B is enabled)

**Comment by stinos** [comment]
> All user-visible options can have a `help` paragraph that gives a detailed explanation of the option

Aha. Problem is these are now all in mpconfig.h. Could be moved in theory, but that's not ideal when one is reading the source.

> Do you mean adding the CONFIG_ prefix everywhere?

Yes. Though according to the Kconfig documentation that can be overridden actually.

> there is a builder that continuously builds random configurations

That's pretty interesting actually. And it would probably identify some current problems (don't remember what exactly, but in the past I saw coptions which couldn't be mixed). On the other hand given the sheer amount of possibilities this might take a long time.

> So do we as a community think that this provides enough benefit in the long run to outweigh the rough spot it will cause in the short term?

If it's really really not possible to build this alongside, and on top of, the current situation which uses fairly 'standard' options (Makefiles for *nix, MSbuild files for msvc port) I'll probably never be a fan myself: in the long run it still adds a not-so-standard 3rd party tool in a pretty invasive way, seemingly breaking simpler ways of doing things. E.g. apart from the qstr generation step, embedding MicroPython in another project can be as simple as just adding all source files to whatever build system used. So in essence I think all you need is Python and a compiler, and then from there you use whatever you want.

But still I think it could be possible to do this in a non-invaisve way (might be missing something crucial though): as far as I can tell the meat of what Kconfig does is create  .h for the code and a .config with Makefile syntax; would it then not be possible to just include those if they exist and do the usual if they do not?

**Comment by dlech** [comment]
> Though according to the Kconfig documentation that can be overridden actually.

Nice. I missed that.

> If it's really really not possible to build this alongside, and on top of, the current situation which uses fairly 'standard' options (Makefiles for *nix, MSbuild files for msvc port) I'll probably never be a fan myself: in the long run it still adds a not-so-standard 3rd party tool in a pretty invasive way, seemingly breaking simpler ways of doing things.

I think whether it is "simpler" or not is a matter of perspective, but I get your point. As much as I like the idea of using Kconfig, I realize that what we have right now is probably "good enough" for most people, so it is hard to justify making such a change. 

> But still I think it could be possible to do this in a non-invaisve way (might be missing something crucial though): as far as I can tell the meat of what Kconfig does is create .h for the code and a .config with Makefile syntax; would it then not be possible to just include those if they exist and do the usual if they do not?

We could make it less invasive as you suggest, but then we would end up in the situation where configuration options all have to be defined in two places so that everything would still work without Kconfig, which sounds very fragile to me.

**Comment by stinos** [comment]
> configuration options all have to be defined in two places

Yes that's true, and indeed not ideal..

**Comment by dpgeorge** [comment]
@dlech do you know if Kconfig can configure linker-level options?  That would be necessary, eg, to configure VFS FAT/LFS1/LFS2.

**Pull request closed without merging**
