### PR TITLE
extmod/re: Fix compilecode.c compile problem on IAR tool chain.

### PR DESCRIPTION
**Pull request by armink**

### CODE REVIEW

**Comment by stinos** [comment]
I think you should restructure the code so that the patch is clear. E.g. don't move lines around when not needed. Also don't duplicate entire lines of logic to just add/remove one thing: this makes maintainance a lot harder and trickier than it should be; as far as I can see the only actual change is removing the `(void`) for IAR? Put just that in a macro, and reuse it in the 2 locations.

**Comment by armink** [comment]
@stinos OK. I just remove `(void)`, the gcc and IAR tool chain can also be built successfully.

**Comment by armink** [comment]
The  Keil MDK tool chain also has same problem.

**Comment by dpgeorge** [comment]
Thanks for the contribution.  For the record, can you please explain what the exact compile issue/error/warning is for IAR (and MDK)?

**Comment by armink** [comment]
The error on IAR:
image

---
The error on MDK:
image

**Comment by dpgeorge** [comment]
Ok, thanks.  It's because the 2nd and 3rd args of the ternary operator are treated like they are in the same expression and must have similar types.  void is not compatible with int so that's why the compiler is complaining.

**Comment by armink** [comment]
Yes, I [porting MicroPython](https://github.com/RT-Thread-packages/micropython) to [RT-Thread OS](https://github.com/RT-Thread/rt-thread) platform. This platform supported IAR and MDK IDE also.

In addition to this problem, the MicroPython is working well on RT-Thread OS.

**Comment by dpgeorge** [comment]
Thanks for the patch, merged in 6a693db71d032518dedc50731376c15bebe6cec9

**Pull request closed without merging**
