### PR TITLE
esp8266: rtc memory documentation; scan() bugfix

### PR DESCRIPTION
**Pull request by MarkR42**
Fixes bug #2116 

adds some documentation for esp8266 rtc.memory

### CODE REVIEW

**Comment by pfalcon** [comment]
Thanks for the patches. But: Please avoid posting unrelated changes to a single pull request. Please avoid submitting pull requests containing any reverts, merges, and otherwise unrelated changes. MicroPython uses rebase-based workflow: https://github.com/micropython/micropython/wiki/DevelWorkflow . (If you want to contribute to documentation, please consider making that doc novice-friendly, it's written by someone who take rebase-based workflow by granted).

**Comment by pfalcon** [comment]
Thanks for your patch! Unfortunately, its commit message(s) don't follow the project conventions. These are described in https://github.com/micropython/micropython/blob/master/CODECONVENTIONS.md , and you were presented link to this document when you prepared this pull request (via https://github.com/micropython/micropython/blob/master/CONTRIBUTING.md document, which contains links to other important information).

Before the patch can be merged, the commit message(s) should be fixed. We encourage you to do this on your side (via git interactive rebase features, `git rebase -i`). Alternatively, project maintainers may fix it (at their choice), but if that's done, it will always lead to delayed processing (up to 1 month).

The project codebase receives high praises for its quality and cleanliness, that was enables us (contributors) to easily prepare patches for it. Let's make sure that after our contributions, the codebase stays clean as before! Thanks!

**Comment by pfalcon** [comment]
Now let's consider only https://github.com/micropython/micropython/pull/2158/commits/259aca5cadc4002122237087caffbb95f1a764ee . ssid_len in struct bss_info isn't documented in the official vendor documentation (SDK API guide). What's your stance on that? My stance should be generally understood - anything undocumented can be changes (e.g. gone) at any time without a notice. Should we use it then? If it fixes almost improbable issue with 32-char ESSID, sure, why not? But then the patch should disclose the fact that undocumented API is used, so there was a clear path to fix it when it breaks.

**Comment by MarkR42** [comment]
It's a tricky one, because the 1 official example I could find, used strlen() incorrectly (where it could overrun the buffer), but then capped the result to 32 bytes so that it would not take > 32 bytes.

Trying to take more than 32 bytes of the ssid is definitely wrong, and definitely happens if there is a real ssid of exactly 32 bytes (without a null). Such accesspoints really do exist in the real world (outside of my test lab). I don't know if it ever crashes, but I've had some crashes for unknown reasons.

I suppose the "safe" solution is to use strnlen() with maxlen=32 if that's available in our C library.

---

In the 20A-ESP8266__RTOS_SDK__Programming Guide__EN_v1.4.0.pdf, there is this example:
```

void scan_done(void *arg, STATUS status)
{
uint8 ssid[33];
char temp[128];
if (status == OK){
struct bss_info *bss_link = (struct bss_info *)arg;
while (bss_link != NULL)
{
memset(ssid, 0, 33);
if (strlen(bss_link->ssid) <= 32)
memcpy(ssid, bss_link->ssid, strlen(bss_link->ssid));
else
memcpy(ssid, bss_link->ssid, 32);
```

Which seems to me, to be an example of "how to write C badly". It calls strlen() twice, with possible buffer overrun on both occasions, then limits the result to 32, so it only copies 32 bytes, because its buffer is 33 bytes to include the null char.

So yeah, maybe strnlen(bss_link->ssid,32) ?
 
What do you think?

**Comment by pfalcon** [comment]
I think you did great research and we should use bss_info::ssid_len, just should document all nuances of its usage, like I did in update to you patch, committed as 822e9ca8f3d2f63c7477bb7fb859b5d9ad948a3b. Thanks again for the research, and please use that as an example how MicroPython patches should look like.

**Comment by pfalcon** [comment]
Also please pay attention to all the previous comments regarding workflow/commit message style. Following those simple rules will allow for quick patch turnaround (not following - good way to make patch stuck in queue for prolonged times).

This PR is done in my list. To save your time with resubmitting remaining changes, docs/library/machine.RTC.rst is intended to describe machine.RTC class, which itself is RFCed in https://github.com/micropython/micropython/wiki/Hardware-API#the-rtc-real-time-clock-class . As you can see, there's no .memory member there, and the most obvious conclusion is that it should not be documented in docs/library/machine.RTC.rst. Such conclusion may seem surprising, but it's also very true - it's better not to have documentation, that to have incorrect/confusing one (also compare with "anything undocumented can be changes (e.g. gone) at any time without a notice"). The hardest part of MicroPython maintainership is exactly dealing which such "paradoxical" stuff. If you want to touch that stuff, don't expect any sustainably quick progress with those. Good news is that we have a lot of stuff to do which is unambiguously useful.

**Pull request closed without merging**
