### PR TITLE
mimxrt: Add the Timer class to the module machine.

### PR DESCRIPTION
**Pull request by robert-hh**
It supports three hardware timer channels based on the PIT timers
of the MIMXRT MCU. The timer id's are 0, 1 and 2

On soft reboot, all active timers will be stopped.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Did you consider "software" timers, namely support for an unlimited number of timers which are backed by a single hardware timer?  I was thinking it should be rather easy to copy how stm32 does it with the pairing heap.

Actually, it's probably worth changing things so that there is `machine.SoftTimer` for software timers, and then `machine.Timer` for actual hardware backed timers.  But that's a bit of a distraction for this PR.

**Comment by robert-hh** [comment]
No, I did not consider Software timers (yet). Should be not too complicated. We just have to agree on a basic tick period, like 1 ms, such that the overhead is not too heavy,

**Comment by dpgeorge** [comment]
> We just have to agree on a basic tick period, like 1 ms, such that the overhead is not too heavy,

With the stm32 pairing heap implementation, it can be made so that the tick is adjustable so it only interrupts when the next runnable callback is ready.  Ie as efficient as possible.

**Comment by robert-hh** [comment]
I looked at the machine_timer and the softtimer implementation in stm32, and it at first glance it looks as if it could be carried over almost unchanged. The only thing to add would be something like the soft_timer_handler(). That can be done by one of the hardware timers, which run at regular or (non)regular interrupts, if re-configured each time. That's something to be determined. That would result in two hard timers and additional soft timers.
OK. I thought timer would be an neat small exercise with the NXP SDK while waiting for the Pin PR to pass, but now the work grows.

**Comment by dpgeorge** [comment]
This PR is a good addition as-is.  Soft timers can come later if needed.

**Comment by robert-hh** [comment]
OK. For RTC, should I change the datetime tuple to the CPython order, or keep it in the MicroPython Dosc order?

**Comment by dpgeorge** [comment]
Merged in there with 2 changes:
- make sure timer objects are in the root pointer section so they don't get GC'd if still in use
- remove the timer deinit function, it's not needed because the finalisation code in combination with `gc_sweep_all()` will deinit any active timers on soft reset

I think there is a minor bug remaining (but I didn't verify it): if you create a timer twice with the same id then when the GC collects the unused one it will stop the timer.  The way to fix this would be to retrieve the existing timer object from `timer_table` if it's not NULL.

**Comment by dpgeorge** [comment]
> For RTC, should I change the datetime tuple to the CPython order, or keep it in the MicroPython Dosc order?

I think it should change to the CPython order...

**Comment by robert-hh** [comment]
I'll check that hint about a possible bug. And the change the RTC.

**Pull request closed without merging**
