### PR TITLE
travis: Improve way that bare-arm/minimal job computes size-diff check.

### PR DESCRIPTION
**Pull request by dpgeorge**
Follow on from #5941, to make it more robust when finding the fork-point of a PR relative to upstream/master (especially for forks of this repo).

Alternative would be to only compute the code size-diff check if it's a pull request.

### CODE REVIEW

**Comment by dpgeorge** [comment]
@stinos FYI

**Comment by stinos** [comment]
Looks good. Works for branches forked of this repositories' master now. Maybe I should create a PR just to see if that's ok as well?

**Comment by dpgeorge** [comment]
> Maybe I should create a PR just to see if that's ok as well?

You mean, a PR on a fork?  Don't we need to merge this first to test that?

**Comment by stinos** [comment]
Just a PR against the main repository for starters, using the code from this PR as-is i.e. just by cherry-picking or merging your branch. See https://github.com/micropython/micropython/pull/5993

**Comment by stinos** [comment]
Seems to work, but Travis creates a merge commit apparently so `git show -s` output is rather cryptic like `Merge a51520558877960ea7000b1305b799eea8b11f18 into 5c8bf12acf3d4cc4cebf971a6f61508559a28143` but that's not really a problem.

**Comment by dpgeorge** [comment]
> Travis creates a merge commit apparently so `git show -s` output is rather cryptic

Could change the `git show -s` to something like `git log upstream/master..HEAD`?

**Comment by stinos** [comment]
Not sure if it's ever going to be needed but that would be pretty clear yes.

**Comment by dpgeorge** [comment]
Ok, I pushed that change (force pushed, but that was the only change).  I think it's good to have it to debug any future issues with this job.

**Pull request merged**
