### PR TITLE
py/objmodule.c: Implement default weak links for all ports.

### LINKED ISSUE #1740: unix: struct/ustruct not consistent with pyboard
On the pyboard, import struct works.

On micropython, import ustruct works, but import struct doesn't (assuming that you haven't installed micropython-lib/struct).

Shouldn't struct be a weak-link to ustruct? (as it is on the pyboard?)

What about the other umodules?

### PR DESCRIPTION
**Pull request by jimmo**
I use the Unix port a lot for testing and keep tripping over this. I very strongly agree that the modules should be called `ufoo` but also really like the weak linking behaviour so that code "just works" while still providing a nice mechanism for customisation and extension. After seeing a couple of recent forum posts about this, I looked through the history on #1740 and I'd like to propose that we just do this.

This also avoids duplication in the ports and avoids a port "accidentally" missing a weak link (although I didn't notice any existing cases of this).

I'm not aware of any effect this will have on existing code. (Please correct me if I've missed anything here). If you're extending/overriding built-in modules (e.g. using `os` from micropython-lib) then that will take precedence over the weak links, so will continue to function as it does currently.

---

Previously ports chose whether or not to alias `ufoo` -> `foo`, and each
port implemented this explicitly. This changes objmodule to always provide a
`foo` weak link for any core `ufoo` module.

Other than now enabling weak links for the Unix port, this should be a
no-op on any ports currently enabling weak links.

`utime` and `uos` are provided by the ports, so they must still provide
their own weak links for these modules.

Fixes #1740

### CODE REVIEW

**Comment by kevinkk525** [comment]
I strongly agree that the Unix port needs to be compatible to the other ports. It's a very useful tool for testing.

**Comment by stinos** [comment]
Can you add a comment in the commit message about the effect this has (if any) on os and other libraries from micropython-lib installed via upip or similar?

**Comment by jimmo** [comment]
> Can you add a comment in the commit message about the effect this has (if any) on os and other libraries from micropython-lib installed via upip or similar?

@stinos I am not aware of any meaningful effect this will have. I've updated the PR description.

The only thing I can think of is if code uses the presence of (for example) `uos` vs `os` to change its behaviour, in any way other than to just go ahead and import the other one. I haven't been able to think of any reason why someone would do that...

**Comment by stinos** [comment]
Sorry it's just that I don't know how weak links are implemented so I was thinking of what happens for example when os from micropython-lib is installed. Will `import os` still import that, or will it import the linked uos, and break existing behaviour?

**Comment by dpgeorge** [comment]
> I don't know how weak links are implemented so I was thinking of what happens for example when os from micropython-lib is installed. Will `import os` still import that, or will it import the linked uos, and break existing behaviour?

Weak links are effectively the same as having a set of symbolic links on the filesystem that is searched *last*.  So an `import os` will search built-in modules first, then all paths in `sys.path` then weak links last.

**Comment by dpgeorge** [comment]
See also #4449 for related discussion.

**Comment by peterhinch** [comment]
> I strongly agree that the Unix port needs to be compatible to the other ports. It's a very useful tool for testing.

Agreed. The coverage build is better for testing/support because it includes all MicroPython features. I think the standard Unix build should be the same.

**Comment by dpgeorge** [comment]
See #5241 for an alternative to this.

**Comment by dpgeorge** [comment]
Superseded by #5241

**Pull request closed without merging**
