### PR TITLE
extmod/nimble: Run the eventq in micropython.schedule.

### PR DESCRIPTION
**Pull request by andrewleech**
This PR changes the background nimble processing to run the nimble eventq handler via schedule() and remove the ringbuffer system. 

This change basically ensures that the python IRQ callback for any BLE operation is run to completion before the next BLE operation is handled.

I've only tested the peripheral mode running my application on reader so far, but it appears to be running very reliably - I've had no transmission sync/order/race issues for many hours where previously I'd have a glitch at least every 10-20 minutes.

I'm looking at how to achieve the same in btstack and it appears far less straightforward there. I can't find anything that looks like a similar functional boundary to split across to schedule().
Event callbacks in btstack_packet_handler() are typically run during the processing of mp_bluetooth_hci_poll_h4(), not going via any sort of event queue.

Perhaps I just need to run the entire mp_bluetooth_hci_poll() function via schedule?

### CODE REVIEW

**Comment by dpgeorge** [comment]
This is a large architectural change, although very interesting to consider.

The main problem I can see with it is that, if scheduled code does not run for some time (eg due to a blocking filesystem access) then the BLE stack may have problems because it is not serviced in time.



> I've only tested the peripheral mode running my application on reader so far, but it appears to be running very reliably - I've had no transmission sync/order/race issues for many hours where previously I'd have a glitch at least every 10-20 minutes.

Do you mean to say that this change was prompted because you saw some reliability issues with the existing code?

**Comment by jimmo** [comment]
I'm not sure how this will work on ESP32 where we don't provide the npl_os functionality. However there may be other solutions there to still avoid the ringbuffer (such as making the NimBLE task an actual MicroPython thread).

**Comment by andrewleech** [comment]
There's a few issues I've hit with the current ringbuffer system, not so much bugs but more limitations.

Our app is designed to respond to data written to one characteristic and update a different one to be read. The ringbuffer essentially decouples the irq's from the stack though, so a batch of BLE write and read operations can go through one after another without the app being aware, then the irq's all get raised in a batch, long after the phone has read the char that was supposed to be updated already. 

Similarly, if the read_request IRQ is used, it now happens out of order with the rest of the IRQ operations as it's handled in interrupt so that data can be returned to the stack from the function. There can be other BLE irq's from previous operations that are still sitting in the ringbuffer waiting to be processed. So again, of a provide write was being relied on to inform what should be returned from a read_request it may or may not have been handled already.

Also having the read_request operate in interrupt while the rest are in schedule can be a confusing inconsistency, meaning you have to be extra careful with the IRQ function to be sure no allocs happen in common areas of the function.

On the subject of irq's returning data though, this is a big one for my upcoming proposed BLE pairing/bonding work. I'd like to defer much of the key caching/storing to application space (to avoid fixed buffers in C and give the user the option of how many to store, what format and where etc) however this requires the IRQ to be handled inline, like the read_request. Currently, this means all the key handling has to happen in interrupt space which is harder to manage.

With the schedule irq's, you save the memory of the ringbuffer, and all irq's are guaranteed to happen in order, inline with the stack, in regular python runtime with access to the heap.

I do have more changes and fixes to this pr in my working branch, I'll push them up today. I still haven't solved btstack though, nor have I looked at esp32 at all.

**Comment by dpgeorge** [comment]
Superseded by #6594

**Pull request closed without merging**
