### PR TITLE
Base64Url encoding

### PR DESCRIPTION
**Pull request by odewdney**
The default base64 implementation adds a linefeed to the end of the string. To perform a base64url encoding we need to remove this, the padding and translate the two replaced characters. This is fine on a desktop, but on a resource constrained device this involves multiple copies of the string. This PR adds an optional parameter to the b2a_base64 and a2b_base64 that allow the caller to control the encoding with an const/enum defined bit flags. Also the a2b function allocates the correct output buffer size.

### CODE REVIEW

**Comment by tve** [comment]
Cool! Documentation?

**Comment by dpgeorge** [comment]
Thanks for the contribution.  In general, the main issue with such extensions is that it's not compatible with CPython, so it makes it harder to write code that runs under both CPython and MicroPython.  I understand the motivation to make such an extension, but maybe there are alternatives.  How would you write code in CPython to do this (deal with URLs)?

**Comment by odewdney** [comment]
string.translate(b2a_base64(payload)[:-1].decode('utf-8'),{ ord('+'):'-', ord('/'):'_' }).rstrip(b"=")

This will end up with 4 copies of the string, with auth and data payloads using this encoding, this is significant memory usage on small embedded systems.

the base64 library does something similar.

The hex functions in the module already is an extension to allow a separator.
The current code writes beyond the buffer in the a2b function if you supply 3 character string.

I think native code should be leveraged to provide useful functionality.

**Comment by tve** [comment]
Would it be better to copy/port/optimize the base64 class altogether? It can't be that much code?

**Comment by dpgeorge** [comment]
> Would it be better to copy/port/optimize the base64 class altogether?

If the `base64` library provides the needed functionality (it looks very close, only doesn't strip the trailing ='s) then it'd be much preferred to implement that, because it's an existing CPython API.

**Comment by odewdney** [comment]
So, how about implementing the base64 library base64 functions, using a shared core functionality with the binascii library that i have implemented? Although i would still like to add a nopadding flag to the urlsafe_x functions..
the python doc dont say anything about being strict with the input to urlsafe_b64decode, but rfc4648 3.3 says that it MUST reject invalid characters unless the spec says otherwise for security reasons..

**Comment by dpgeorge** [comment]
CPython did eventually implement the `newline` argument in 3.6, and MicroPython then implemented it in 2e3a2785cdd5c63788cac7ec8b5d62105ecfe4aa .  So that solves one of the original issues of this PR.

For the `base64` module and URL encoding: it adds a lot of code size to the firmware.  I think a better approach would be to write some low-level C helper functions (eg in `_hexlib`) that provides basic base64/hex encoding/decoding, and then make wrapper modules in Python for `binascii.py` and `base64.py`, that both use this underlying C code.  That approach is more sustainable in terms of long term growth of firmware and adding new features.

So I'll close this PR.

**Pull request closed without merging**
