### PR TITLE
docs: Add Micropython Differences with test script.

### PR DESCRIPTION
**Pull request by flowergrass**

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks @flowergrass.

This PR introduces a small framework to track differences between uPy and CPython.  It consists of:
- A set of "tests" which test for an individual feature that differs between uPy and CPy.  Each test has a category (eg syntax, core language), a human-readable description of the difference, and then a short code snippet which demonstrates the difference.  See docs/differences/tests directory.
- A program (see docs/differences/udiff.py) which runs all the tests (on uPy and CPy) and generates nicely-formated .rst documenting the differences.
- Integration into the docs build so that everything is automatic, and the differences appear in a way that is easy for users to read/reference.

For a demo of the output see: http://docs.micropython.org/udiff/differences/index.html

**Comment by dpgeorge** [comment]
The idea with using this new framework is:
- when a new difference is found it's easy to write a short test for it, along with a description, and add it to the existing ones
- when something is no longer different the docs build system will give an error and that difference can be removed

**Comment by stinos** [comment]
Looks neat!

**Comment by pfalcon** [comment]
This is titanic work, thanks. But I feel concerns about this, and after thinking for awhile (more than 5mins, yet less than a day), how to best formulate them, they are:

1. It's definitely great to add a new type of tests. We already have regression tests, no-heap-alloc tests (implicitly a part of regression tests), benchmark comparison tests. Would be good to have cpython differences tests. But then they should belong to tests.
2. I'm concerned that this is being pushed straight to docs. We already have big maintainability problems with docs, so any bigdrop into docs raises concerns.
3. Another concern is that choosing between an issue database (not bug database!) and docs, this stuff would rather belong to issue (not bug!) tracker. Trying to use docs as an issue tracker might be not too bad for docs in a perfect state on which nothing else is to be done, but we're far from it.

Those would be high-level concerns, and corresponding suggestions: move this under tests/, follow "tests first approach", like it should follow all patterns of existing tests (aka "executable docs"), not of a textual documentation.

More specific concerns:

4. This adds an adhoc formats for tests, these rather should be valid python scripts (like the rest of tests are), so any "foreign" metadata should be wrapped in Python means, of which is the most obvious a docstring.
5. It should not try to pretend that these are "bugs", just as "known differences". Thus, besides "description" there should be "cause" and "workaround" fields.
6. I'd argue that there're repeating miscategorization patterns, e.g. all builtin type subclassing issues should go under "Classed and objects" or whatever, all slice issues under "Slice", etc.

**Comment by pfalcon** [comment]
Ah, almost forgot - the commit messages are very sparse. The information @dpgeorge provided in his comments should really be part of the commit messages.

**Comment by pfalcon** [comment]
Another small issue: there can be too much horizontal scrolling in comparison tables: http://docs.micropython.org/udiff/differences/builtin_types.html#bytes . Not something to jump and "fix", but think if it can/worth be done better.

**Comment by flowergrass** [comment]
> It's definitely great to add a new type of tests. We already have regression tests, no-heap-alloc tests (implicitly a part of regression tests), benchmark comparison tests. Would be good to have cpython differences tests. But then they should belong to tests.

The tests have all been moved to tests/cpydiff/ directory.



> This adds an adhoc formats for tests, these rather should be valid python scripts (like the rest of tests are), so any "foreign" metadata should be wrapped in Python means, of which is the most obvious a docstring.

The tests are now valid python scripts with metadata in docstrings. Using run-tests on the directory results in all FAILs as expected.

> It should not try to pretend that these are "bugs", just as "known differences". Thus, besides "description" there should be "cause" and "workaround" fields.

Cause and workaround fields have been added to all tests although they are scarcely used for now.

**Comment by pfalcon** [comment]
Looks great, thanks! I guess any further tweaks can be done later, I'm +1 on merging this. The only remaining concern are the commit messages and squashing to fewer number of commits, but I hope @dpgeorge will look into that when merging.

This is very nice, I look forward to add few testcases myself.

**Comment by dpgeorge** [comment]
Ok, this was rebased, squashed a bit, some bugs fixed, commit messages added and merged; see 86c7507233929366ff17c9666200a33123491a8e, b7fa63c7ced460fd2d3aceb35257a62ff08831c1 and 3218ccd70d8f387662987f6c1beb79102288b13d.

**Pull request closed without merging**
