### PR TITLE
Add embeddable MicroPython component

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR adds a "port" with the following features:
- convert uPy source to add a custom prefix to all functions
- convert uPy source to add the state structure as the first argument to all functions
- amalgamate uPy source into a single .c and .h file
- build libmicropython.a from the amalgamated source
- provide a simple embedded example

The outputs are:
- upy.c and upy.h: a completely self-contained distribution of the core+extmod components
- libmicropython.a: just a compiled versionu of upy.c (with specific options from mpconfigport.h)
- embed: a demo, built from embed.c and libmicropython.a

### CODE REVIEW

**Comment by dpgeorge** [comment]
To try it out:

- cd embed
- make
- ./embed

Also look at embed.c to see how you can create multiple uPy instances that have completely separate state.

**Comment by hauptmech** [comment]
Looks good to me. (Multiple instances in parallel is nice)

**Comment by pfalcon** [comment]
> build libmicropython.a from the amalgamated source

I personally consider amalgamation a rather bad technique (practical in many cases, but nonetheless, bad). The idea is very simple - if someone wanted to ship vulnerabilities, trojans, backdoors, they would use "amalgamation" to ship gigantic non-reviewable source devoid of change history. Then it's unclear why someone who doesn't have such intentions would choose an amalgamation as a way to do it as a general way (vs practical, niche hack to use when nobody looks). So, would be nice to make amalgamation a separate feature, and build library from authentic source (perhaps modified in reviewable way). 

Otherwise, this patchset is much more complex than how it could start. Which in turn will lead to extra effort required to maintain it (and risk becoming a separate kingdom instead of naturally fitting part of uPy). But if going that way is a way to start going, ship it!

**Comment by pfalcon** [comment]
> Be warned, there are many dragons here!

Indeed, it will be literally unmaintainable. Again, I don't see why there's a need to start so complicated. People wanted embedding for years, and should get it finally. *When* people will want multiple parallel interpreters, they can wait and eventually get it too.

**Comment by hauptmech** [comment]
Having a state context that's not global is very nice. It's not that I want parallel interpreters, it's that I have a little bit more confidence that the boundaries of micropython are well defined. There's less likely  to be some hidden global variable hanging onto state between instantiations that I missed.

Given the current heavy lifting the C pre processor is doing, having another preprocessor in the build process does not worry me.

I was just about to start digging through the *.h files to see what I need to install in /usr/include; a single file is much easier.

Regarding names, lib___.a and ___.h should be the same. `micropython.[a,h]` seems the most clear to me. With the api prefix I have a preference for short. upy_. A prefix of micropy_ is no problem though.

Since we have big fancy modern compilers in application embedding, using the typedef type name in the definitions would make the automatic help a little more pleasant to read. the *_t suffix does a good enough job to signal we are looking at a type.

`#define MICROPY_VERSION_STRING` should probably go in the upy.h file. There may be other things like this.

Are there any specific aspects of embed that need testing?

**Comment by tarruda** [comment]
Hi @dpgeorge

First of all, great work on micropython, I tested in my machine and was impressed by how fast/lightweight is feels compared to CPython! At least a simple "hello world" shows the startup to be much faster:

```
$ time python -c 'print("hello world")'
0.02s user 0.00s system 83% cpu 0.024 total
$ time micropython -c 'print("hello world")'
0.00s user 0.00s system 0% cpu 0.001 total
```

I found this project when googling for a lightweight python implementation with an embedding focused design, like lua. While micropython has different goals, it is not that far from the ideal lua-like python implementation I was looking for, and the fact that you can write a script to remove all global state only proves it.

Forgive me if I don't fully grasp the purpose of this PR, but why not simply adapt this script to remove global context without generating the amalgamate and commit the changes permanently?

Wouldn't it be better for maintenance to share the same source code structure for both microcontrollers and embedding scenarios rather than having embedders work with generated code(which could make debugging harder)? Is there some reason for keeping global state in the main source code?

As I side note, if you want to write scripts for transforming C code I recommend you to look into [pycparser](https://github.com/eliben/pycparser) which is a full C99 parser in pure python and has some nice APIs for visiting/transforming nodes and even regenerate C code from the modified AST.

**Comment by dmazzella** [comment]
+1

**Comment by dmazzella** [comment]
It could also be useful to have the version for msvc

**Comment by stinos** [comment]
If you have access to *nix-like build tools you should be able to test that already with some minor modifications (like adjusting the makefile to make it use windows/mpconfigport.h): generate the source and/or amalgamation and drop the result into a VS project where you also add msvc/common.props to get the same build options, and that should build since after all it's the same source.

Thinking of it, those modifications are similar for all ports. Suppose you'd want to embed the unix port with all options it currently has it would be nice if you could say e.g. ```cd embed && make UPY_PORT=unix``` which would have embed's Makefile pick up the Makefile (to get the sources) and mpconfigport.h (to get build options) from the unix directory. I'm not sure that is the best way to go though.

**Comment by dmazzella** [comment]
@stinos have you tried this?

**Comment by dpgeorge** [comment]
> Forgive me if I don't fully grasp the purpose of this PR, but why not simply adapt this script to remove global context without generating the amalgamate and commit the changes permanently?
> 
> Wouldn't it be better for maintenance to share the same source code structure for both microcontrollers and embedding scenarios rather than having embedders work with generated code(which could make debugging harder)? Is there some reason for keeping global state in the main source code?

Yes, this is something I was considering: to change the code in py/ core to take the VM/runtime state as the first argument, instead of having global data.  Then any ports that need to save space or need more efficiency would run a script (during the make process) which stripped out the state argument (first argument) and just reference the global variable.  Stripping is much easier than inserting.

**Comment by tarruda** [comment]
> Yes, this is something I was considering: to change the code in py/ core to take the VM/runtime state as the first argument, instead of having global data

Nice to know!

> Then any ports that need to save space or need more efficiency would run a script (during the make process) which stripped out the state argument (first argument) and just reference the global variable. Stripping is much easier than inserting.

Maybe there's a cleaner approach that doesn't require altering source code prior to compilation:

- Prefix every public API function declaration with something like `MPAPI`. For example, `void mp_init(mp_state *state);` becomes `MPAPI void mp_init(mp_state *state);`
- In the most inner micropython header(the header which is a dependency for all other headers) add something like this on the top:

```c
#ifndef MPAPI
# define MPAPI extern
#endif
```
- Add an extra file in the repository that `#include`s every other file(eg: amalg.c). This file would define:
 - `MPAPI` as `static` before including any other file
 - a global variable of whatever type is used to represent a VM state
 - a wrapper for every function that accepts a vm state that passes the global variable as first argument. 

Then, anyone wanting to save space would simply compile `amalg.c`(possibly by including it in a project). I'm pretty sure that with `-O1` gcc will inline static functions that only have one call site(which would be every API function). Also, debugging symbols would be correct, even in the small footprint version, so it would provide users with a better debugging experience.

**Comment by stinos** [comment]
bq. have you tried this?

Just did, tried for a while but couln't get it to compile..

Changing the Makefile to include msvc's mpconfigport leads to undefined qstrs later on. Which in turn can be fixed by adding extra source files from the unix directory to the makefile (input.c, modos.c etc, the ones listed in sources.props).

Next up: in upy.c alignof is replaced with micropyalignof but that is referenced here:
```
#ifndef alignof
#define micropy_alignof(mp_state, type) offsetof(struct { char c; type t; }, t)
#endif
```
so if alignof is already defined, which is the case after including msvc's mpconfigport.h, this is incorrect. Can be fixed by providing a proper definition or replacing invokations of micropy_alignof with alignof.

Next: the math fun defines in upy.c have an mp_state argument added but without a type, and there's some mismatch because micropy_py_ is added to the function decl but not where it gets used :
```
#define MATH_FUN_1(py_name, c_name) \
    STATIC mp_obj_t mp_math_ ## micropy_py_name(mp_state, mp_obj_t x_obj) { return micropy_obj_new_float(mp_state, MICROPY_FLOAT_C_FUN(c_name)(micropy_obj_get_float(mp_state, x_obj))); } \
    STATIC MP_DEFINE_CONST_FUN_OBJ_1(mp_math_## py_name ## _obj, mp_math_ ## py_name);
```
At that point I gave up because even though I could probably fix it here, changes would get overwritten the next time upy.c gets generated so it' no use and transform.py is over my head after a long working day :] And also because the idea of having the upy core use the state and then stripping it if needed deserves an extra +1 because it will likely fix all the above problems..

**Comment by pfalcon** [comment]
@dpgeorge : Besides criticism from technical and maintenance sides of things, I'd like to record here criticism from organizational/paradigmatic point of view, shared privately previously. So, it's detrimental to the project progress to encourage some users instead of working with project upstream source code to work with some hacked-up version of it. It's hard to encourage people to contribute at all, and giving them instead of the source some dummy is a plain discouragement to try do (it's literally like "we don't even give you real source, guess if we want you to contribute back").

Now about adding a VM* to every function: I wondered if that may be driven by multithreading support, but reviewing https://github.com/micropython/micropython/pull/2165, I don't see anything like that. So, let me put it simple: there's no need to make each function to accept VM* for embedding. The situation is such that 1 year ago, few people needed embedding. Now few more people need embedding. They need official way of embedding, that's it, no a castles in air. They need to get it, leverage it, and contribute improvements back to bootstrap it. If at some point later they will raise well backed requirement of a need to support multiple VMs, then it can be considered. Done now, adding an extra param to all funcs won't do anything but increase register pressure, and this increase code size and decrease performance.

I personally don't find this PR suiting my embedding needs (as it makes me jump thru useless hops, the only outcome of which is complicating to contribute back, and will make life harder for other users even more).

**Comment by hauptmech** [comment]
> Done now, adding an extra param to all funcs won't do anything but increase register pressure, and this increase code size and decrease performance.

@pfalcon Adding the VM* will do something. The question seems to be whether micropython should be a microprocessor library that can be optimized for big iron, or a normal library that can be optimized for the microprocessor. 

I think it should stay true to its roots. I am happy to use a preprocessed, amalgamated version.

That said, I'm curious what the actual performance hit is on optimized code. Constant propagation might clean out the VM* argument.

>  It's hard to encourage people to contribute at all, and giving them instead of the source some dummy is a plain discouragement to try do (it's literally like "we don't even give you real source, guess if we want you to contribute back").

No one is getting dummy source. `./py` is the source and there is no problem. The amalgamation is a build artifact and a necessary `.h` file. It's all good.

The nice thing about open source is that people will come to contribute and maintain the parts of a code that are important to them. If no one maintains a part of it, it dies a natural death. 

Why not put your minimal approach side by side this one and commit them both? `./embed/approach_1` and `./embed/approach_2`. Time will tell which was better. Maybe both will find their own niche.

**Comment by pfalcon** [comment]
That's exactly what I did, updating my previous example based on previously raised concerns: https://github.com/micropython/micropython/issues/2189 . I however think there's no point to have 2 ways of doing it, especially in the face of concerns raised above - that the way presented here is less helpful to the project than other approached to do it.

**Comment by pfalcon** [comment]
> As I side note, if you want to write scripts for transforming C code I recommend you to look into pycparser which is a full C99 parser in pure python and has some nice APIs for visiting/transforming nodes and even regenerate C code from the modified AST.

I just noticed that JerryScript has vera++ in the dependencies, and advertises itself as "Vera++ is a programmable tool for verification, analysis and transformation of C++ source code. Vera++ is mainly an engine that parses C++ source files and presents the result of this parsing to scripts in the form of various collections - the scripts are actually performing the requested tasks." Scripts are in TCL. It would be ironical to use vera++ as a testcase for uPy embedding, and use result of that embedding to prepare uPy for embedding.

That's not the only thing JerryScript has. According to the README, it has "Mature C API, easy to embed in applications". And here're commits just over last couple of weeks:

* https://github.com/Samsung/jerryscript/commit/a816ab8bb0324e89b4440b139eeb27514e9ecf57
* https://github.com/Samsung/jerryscript/commit/b828d4a46344b87d70a5959cae4e5e69c4cdc884
* https://github.com/Samsung/jerryscript/commit/4afd76d932c2a76a8fa0278fa9c11cbeb15b4a8a
* https://github.com/Samsung/jerryscript/commit/c557a0a0474cffd51d2b3ce06afb0d83b4e9efbc

JerryScript's API even remotely isn't stable. MicroPython is light years ahead in API stability. But on the fence, it's written that JerryScript has stable API and ease of embedding, so people come to use JerryScript. They don't carry it away to dark corners in amalgamations, they come back to submit patches to use upstream. And JerryScript project grows. It's light years behind MicroPython, but things are moving fast, and not doing right things at right time may be rather detrimental in the long run.

**Comment by hauptmech** [comment]
>  I however think there's no point to have 2 ways of doing it

Currently there are 0 ways of doing it. Everyone embedding uPy is doing so on their own private forks.

If there is only one way, I much prefer this PR (or a similar VM* + single include file approach). But it seems an easy solution to make both available.

**Comment by dmazzella** [comment]
> If there is only one way, I much prefer this PR (or a similar VM* + single include file approach). But it seems an easy solution to make both available.

+1 for single file approach

**Comment by dmazzella** [comment]
news about this?

**Comment by kkimdev** [comment]
Hi, what's the status of this?  Is there a plan to merge this to mater?

**Comment by dpgeorge** [comment]
> Hi, what's the status of this? Is there a plan to merge this to mater?

There was already merged a different approach to embedding, see `examples/embedding/`.  This PR is still open and available for people to pull themselves to use the feature.  Feedback on the approach here vs the one in examples/embedding is welcome.

**Comment by kkimdev** [comment]
Got it. Thanks!

**Comment by dmazzella** [comment]
Hi @dpgeorge ,
I know that this PR is closed for another solution, but having the context for each function is really comfortable and guarantees more flexibility in use.

Honestly, I also find the amalgamation approach very interesting.
as with duktape and jettyscript it has proven to be a very practical solution for embed scripting languages into big projects.

Are there any hopes for a revision to the master of this pr?

Thanks in advance.
D.

**Comment by fluffrabbit** [comment]
Hey, never used this project but thought I'd weigh in.

After reading the readme in the embedded example, I'm already confused about what constitutes in-tree vs out-of-tree. Makefiles should be simple. Amalgamation is a solution to this, but it's not auditable if you include the amalgamated source in your tree, which is one of the reasons I'm not using Duktape. Putting Micropython in a subfolder and cross-compiling the library for different architectures using makefiles or cmake would be required for my use cases.

**Comment by dpgeorge** [comment]
Closing in favour of #9529.

@ghost I think #9529 is exactly what you want.

@dmazzella we can revisit the amalgamation approach once #9529 is merged.

**Pull request closed without merging**
