### PR TITLE
Add .gitattributes for unifying line endings

### PR DESCRIPTION
**Pull request by stinos**
By default all files will be converted to have LF line endings upon
checkin into the repository, and to maintain those LF line endings
on checkout on the filesystem as well - unless specified otherwise by
the .gitattributes file:
- binary files like .jpg will not be touched
- project files modified through Visual Studio or similar get CRLF
- external code like stmhal/cc3200/fatfs will not be touched and retains
  the CRLF used in (most) files in those directories

Git already applies this system in this commit which is why some files
have their line endings normalized and are committed as well.

Note this PR is mostly to show what can be done. Main functionality is to get rid of issues like d35ac95 where CRLF sneaks into the core code: that won't happen anymore since git would convert any CRLF to LF upon committing. But we should first establish the rules regarding line endings policy. For instance the policy could be to simply force everything to LF for consistency which would mean about 230 files need conversion. Or since most files in the cc3200 directory already have LF maybe the remaining ones should be converted as well, but the stmhal/fatfs can remain as-is.

### CODE REVIEW

**Comment by dpgeorge** [comment]
docs/make.bat would need to stay with CRLF, since it's intended to run on a Windows cmd line.

All 3rd party imports (stmhal/hal, stmhal/cmsis, lib/fatfs) should stay as-is so it's easier to do a diff when a new version comes out.

**Comment by stinos** [comment]
cmd doesn't care about line endings - at least, I never had problems with it and this make.bat still works just fine with LFs

Regarding the diffs: git handles this for you, that is one of the points for using it. Those files would be set to always have LF so git diff recognizes this and only shows actual changes. For instance if I set stmhal to be LF, then commit and checkout again and copy a 'new' version with CRLF and one character change git diff conveniently shows
```
--- a/stmhal/hal/inc/stm32f4xx_hal_adc.h
+++ b/stmhal/hal/inc/stm32f4xx_hal_adc.h
@@ -10,7 +10,7 @@
   *
   * <h2><center>&copy; COPYRIGHT(c) 2014 STMicroelectronics</center></h2>
   *
-  * Redistribution and use in source and binary forms, with or without modification,
+  * redistribution and use in source and binary forms, with or without modification,
   * are permitted provided that the following conditions are met:
   *   1. Redistributions of source code must retain the above copyright notice,
   *      this list of conditions and the following disclaimer.
warning: CRLF will be replaced by LF in stmhal/hal/inc/stm32f4xx_hal_adc.h.
The file will have its original line endings in your working directory.
```

**Comment by dpgeorge** [comment]
Ok, thanks for comments.

Regarding make.bat.  I also assume that people might view/edit it in notepad (or other Win editor), and so will need the CRLFs to view it properly.

I take your point with using git diff to track changes for new 3rd party versions.  But also I like to use normal diff for this and I don't think it supports an "ignore line endings" option.

**Comment by dhylands** [comment]
I use a tool called meld http://meldmerge.org/ (sudo apt-get install meld if you're on ubuntu)

It turns out its written in Python. I has file filters which can ignore all whitespace changes, an the thing I really like is that it can compare directories as well as individual files.

It's on the slow side for really huge files.

**Comment by stinos** [comment]
re: batch files: no-one should ever be using notepad :] and any other sane text editor doesn't care about CRLF. But I added it to the CRLF list.

re: diff: standard diff indeed doesn't seem to have an option to ignore line endings. It can ignore all spaces but then it's literally all of them which isn't all that useful.

re: Meld: yes that seems nice. I've been using P4Merge because Perforce happened to be the first versioning system I ever used, and it does the job as well.

**Comment by pfalcon** [comment]
Yes, so this appears to be that's interesting kind of change which fix while annoying, still rather localized problem. And the fix somehow affects many more people and hard to get right, because it hits few hard-to-decide and borderline cases. So, I'd defer to others whether this should be merged. But the good news is that even if this isn't merged, folks who were affected by the original issue, can have this .gitattributes in their local repo, uncommitted, and that issue will be resolved for them nonetheless ;-).

**Comment by dpgeorge** [comment]
@stinos thanks for the initial .gitattributes file.  I redid the commit in feff00e1a58aad4e7251d9c10403768fa814c5dd to clean up some things.

It's good to have this, not least because I see now lots of stmhal files that should have LF endings but don't.  Eventually they'll be converted, eg when upgrading to next ST Cube library.

**Comment by dhylands** [comment]
I wrote a little utility many years ago which counts the number of various styles of line endings in a file:
https://github.com/dhylands/projects/tree/master/utils/src/CountLineEndings

The Trail column is the number of lines that have traling spaces.

This is what it reports in the current stmhal directory:
```
    LF     CR   CRLF CRCRLF  Other  Trail FileName
------ ------ ------ ------ ------ ------ ---------------------------
   237      0      0      0      0      0 accel.c
    29      0      0      0      0      0 accel.h
   462      0      0      0      0      0 adc.c
    28      0      0      0      0      0 adc.h
    44      0      0      0      0      0 autoflash
     0      0      0      0      0      0 boards
    54      0      0      0      0      0 bufhelper.c
    28      0      0      0      0      0 bufhelper.h
     0      0      0      0      0      0 build-CERB40
     0      0      0      0      0      0 build-CERBOT
     0      0      0      0      0      0 build-PYBV10
     0      0      0      0      0      0 build-STM32F4DISC
   828      0      0      0      0      0 can.c
    40      0      0      0      0      0 can.h
     0      0      0      0      0      0 cmsis
   377      0      0      0      0      0 dac.c
    29      0      0      0      0      0 dac.h
   279      0      0      0      0      0 diskio.c
   365      0      0      0      0      0 extint.c
    59      0      0      0      0      0 extint.h
    84      0      0      0      0      0 ffconf.c
   298      0      0      0      0      1 ffconf.h
   281      0      0      0      0      0 file.c
    29      0      0      0      0      0 file.h
   192      0      0      0      0      0 flash.c
    29      0      0      0      0      0 flash.h
   124      0      0      0      0      1 font_petme128_8x8.h
   115      0      0      0      0      0 fsusermount.c
    39      0      0      0      0      0 fsusermount.h
    66      0      0      0      0      0 gccollect.c
    39      0      0      0      0      0 gccollect.h
    62      0      0      0      0      0 gchelper.s
    13      0      0      0      0      0 GNUmakefile
     0      0      0      0      0      0 hal
   119      0      0      0      0      0 help.c
   582      0      0      0      0      0 i2c.c
    35      0      0      0      0      0 i2c.h
    47      0      0      0      0      0 import.c
    44      0      0      0      0      0 input.c
    65      0      0      0      0      0 irq.c
    39      0      0      0      0      0 irq.h
   539      0      0      0      0      0 lcd.c
    27      0      0      0      0      0 lcd.h
   307      0      0      0      0      0 led.c
    50      0      0      0      0      0 led.h
    76      0      0      0      0      0 lexerfatfs.c
   554      0      0      0      0      0 main.c
   320      0      0      0      0      0 Makefile
   214      0      0      0      0      0 make-stmconst.py
     2      0      0      0      0      0 memory.h
   154      0      0      0      0      0 modnetwork.c
    85      0      0      0      0      0 modnetwork.h
   612      0      0      0      0      0 modnwcc3k.c
   473      0      0      0      0      0 modnwwiznet5k.c
   609      0      0      0      0      0 modpyb.c
   132      0      0      0      0      0 modstm.c
   253      0      0      0      0      1 modstmconst.gen.c
   362      0      0      0      0      0 moduos.c
   296      0      0      0      0      0 moduselect.c
   447      0      0      0      0      0 modusocket.c
   350      0      0      0      0      0 modutime.c
   232      0      0      0      0      0 mpconfigport.h
     7      0      0      0      0      0 mpconfigport.mk
    71      0      0      0      0      0 mphal.c
    18      0      0      0      0      0 mphal.h
   116      0      0      0      0      0 pendsv.c
    32      0      0      0      0      0 pendsv.h
   662      0      0      0      0      0 pin.c
    32      0      0      0      0      0 pin_defs_stmhal.c
    96      0      0      0      0      0 pin_defs_stmhal.h
    95      0      0      0      0      0 pin.h
    92      0      0      0      0      0 pin_named_pins.c
    38      0      0      0      0      0 portmodules.h
   115      0      0      0      0      0 printf.c
     0      0     92      0      0      0 pybcdc.inf_template
     6      0      0      0      0      0 pybioctl.h
   123      0      0      0      0      0 pybstdio.c
   383      0      0      0      0      0 pyexec.c
    43      0      0      0      0      0 pyexec.h
   719      0      0      0      0      0 qstrdefsport.h
    69      0      0      0      0      0 rng.c
    30      0      0      0      0      0 rng.h
   511      0      0      0      0      0 rtc.c
    30      0      0      0      0      0 rtc.h
    20      0      0      0      0      1 scard.log
   327      0      0      0      0      1 sdcard.c
    40      0      0      0      0      0 sdcard.h
   335      0      0      0      0      0 servo.c
    33      0      0      0      0      0 servo.h
   712      0      0      0      0      0 spi.c
    34      0      0      0      0      0 spi.h
     0      0    523      0      0    271 startup_stm32f40xx.s
    42      0      0      0      0      0 std.h
   136      0      0      0      0      6 stm32f405.ld
   436      0      0      0      0      0 stm32f4xx_it.c
    79      0      0      0      0      0 stm32f4xx_it.h
   245      0      0      0      0      0 storage.c
    35      0      0      0      0      0 storage.h
   388      0      0      0      0      0 system_stm32f4xx.c
   115      0      0      0      0      0 systick.c
    30      0      0      0      0      0 systick.h
  1352      0      0      0      0      0 timer.c
    45      0      0      0      0      0 timer.h
   775      0      0      0      0      0 uart.c
    55      0      0      0      0      0 uart.h
   652      0      0      0      0      0 usb.c
   501      0      0      0      0      9 usbd_cdc_interface.c
     0      0     44      0      0      0 usbd_cdc_interface.h
     0      0    581      0      0    109 usbd_conf.c
     0      0     94      0      0      0 usbd_conf.h
   196      0      0      0      0      0 usbd_desc.c
    29      0      0      0      0      0 usbd_desc.h
     0      0      0      0      0      0 usbdev
   347      0      0      0      0      8 usbd_msc_storage.c
    28      0      0      0      0      0 usbd_msc_storage.h
    66      0      0      0      0      0 usb.h
     0      0      0      0      0      0 usbhost
     0      0      0      0      0      0 usb-ser-mon.log
   144      0      0      0      0      0 usrsw.c
    30      0      0      0      0      0 usrsw.h
```

**Comment by stinos** [comment]
@dhylands that's nifty, thanks!

**Comment by dpgeorge** [comment]
Very useful @dhylands!

**Pull request closed without merging**
