### PR TITLE
mimxrt: Adding serial number

### PR DESCRIPTION
**Pull request by d3v1c3nv11**

### CODE REVIEW

**Comment by robert-hh** [comment]
Thank you for the suggestion. This would be the third place in the code which accesses this information directly. That's seems not to be efficient, and might not match all controllers. Therefore I changed the approach in the WIP port for the i.MX RT1176 controller and defined a function in mphalport.c, which accesses OCOTP and provides the information for the other functions, like Ethernet MAC and machine.unique_id(). So it might be the right time now to follow this approach. Code below:
```
void mp_hal_get_unique_id(uint8_t id[]) {
    #if defined CPU_MIMXRT1176_cm7
    OCOTP_Init(OCOTP, 0U);
    *(uint32_t *)&id[0] = OCOTP->FUSEN[0x10].FUSE;
    *(uint32_t *)&id[4] = OCOTP->FUSEN[0x11].FUSE;
    #else
    OCOTP_Init(OCOTP, CLOCK_GetFreq(kCLOCK_IpgClk));
    *(uint32_t *)&id[0] = OCOTP->CFG0;
    *(uint32_t *)&id[4] = OCOTP->CFG1;
    #endif
}
```

**Comment by robert-hh** [comment]
I have made PR #8051 that includes the mentioned change in retrieving the machine ID as the last commit. If you use that for your PR, I can drop it in my PR later (or the other way around.

**Comment by dpgeorge** [comment]
Can you please update this now that master contains the improvement mentioned above for getting the machine ID?

Also please check code formatting.

**Comment by dpgeorge** [comment]
Superseded by #8094.

**Pull request closed without merging**
