### PR TITLE
Add argument to control brightness

### PR DESCRIPTION
**Pull request by singhkpratham**
Inspired from circuitpython/rpi_ws281X. https://circuitpython.readthedocs.io/projects/neopixel/en/latest/api.html#neopixel.NeoPixel

### CODE REVIEW

**Comment by singhkpratham** [comment]
Hi @dpgeorge , please have a look into this and accept/reject

**Comment by dpgeorge** [comment]
Thanks for the contribution.  For a previous attempt at something similar see #3623.

I would be inclined not to merge this code.  The main reason is that it will slow down the driver for all users even when the brightness feature is not used.  Instead it would probably be more efficient to compute the dimmed colour outside this driver and pass in already-dimmed values (you could also do other colour manipulations this way).  Eg:
```python
def dim_colour(c, brightness):
    return tuple(int(round(v * brightness)) for v in c)
red = dim_colour((255, 0, 0), 0.5)
for i in range(8):
    np[i] = red
```

An alternative would be to create a new class that has a brightness option, eg:
```python
class NeoPixelDim:
    def __init__(self, pin, n, brightness=0.5, bpp=3, timing=1):
        super().__init__(pin, n, bpp, timing)
        self.brightness = brightness
    def __setitem__(self, index, val):
        super().__setitem__(index, int(round(v * brightness)) for v in c)
```

**Comment by peterhinch** [comment]
I agree. The class should, of course, read
```python
class NeoPixelDim(NeoPixel):
    def __init__(self, pin, n, brightness=0.5, bpp=3, timing=1):
        super().__init__(pin, n, bpp, timing)
        self.brightness = brightness
    def __setitem__(self, index, val):
        super().__setitem__(index, int(round(v * brightness)) for v in c)
```

**Comment by dpgeorge** [comment]
>  The class should, of course, read ...

Yes indeed, it should derive from NeoPixel.

**Pull request closed without merging**
