### PR TITLE
OO version of FatFS library

### PR DESCRIPTION
**Pull request by dpgeorge**
This is work in progress, but comments welcome :)

It adds a variant of the FatFS library which takes a FATFS object (or similar) as the first argument of all functions.

It also modifies (in a minimal but hacky way) the extmod/vfs_fat\* code to use it when MICROPY_FATFS_OBJ is defined.

Unix is used for testing and with this PR you can create more than one RAMFS.

### CODE REVIEW

**Comment by meski** [comment]
Have we looked at alternatives to FAT?  It was always the least robust of
the file systems on DOS/Windows.   (horror memories of fixing fat chains.)



On Thu, Jun 2, 2016 at 2:06 AM, Damien George <notifications@github.com>
wrote:

> This is work in progress, but comments welcome :)
>
> It adds a variant of the FatFS library which takes a FATFS object (or
> similar) as the first argument of all functions.
>
> It also modifies (in a minimal but hacky way) the extmod/vfs_fat* code to
> use it when MICROPY_FATFS_OBJ is defined.
>
> Unix is used for testing and with this PR you can create more than one
> RAMFS.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/micropython/micropython/pull/2140
> Commit Summary
>
>    - lib/fatfsobj: Add OO version of FatFS library.
>    - extmod/vfs_fat: Rework so it can optionally use OO version of FatFS.
>    - unix: Switch to OO version of FatFS library.
>
> File Changes
>
>    - *M* extmod/fsusermount.c
>    <https://github.com/micropython/micropython/pull/2140/files#diff-0>
>    (38)
>    - *M* extmod/vfs_fat.c
>    <https://github.com/micropython/micropython/pull/2140/files#diff-1>
>    (69)
>    - *M* extmod/vfs_fat_diskio.c
>    <https://github.com/micropython/micropython/pull/2140/files#diff-2>
>    (39)
>    - *M* extmod/vfs_fat_ffconf.c
>    <https://github.com/micropython/micropython/pull/2140/files#diff-3>
>    (39)
>    - *M* extmod/vfs_fat_file.c
>    <https://github.com/micropython/micropython/pull/2140/files#diff-4>
>    (36)
>    - *M* extmod/vfs_fat_file.h
>    <https://github.com/micropython/micropython/pull/2140/files#diff-5>
>    (6)
>    - *M* extmod/vfs_fat_misc.c
>    <https://github.com/micropython/micropython/pull/2140/files#diff-6>
>    (22)
>    - *A* lib/fatfsobj/diskio.h
>    <https://github.com/micropython/micropython/pull/2140/files#diff-7>
>    (79)
>    - *A* lib/fatfsobj/ff.c
>    <https://github.com/micropython/micropython/pull/2140/files#diff-8>
>    (4273)
>    - *A* lib/fatfsobj/ff.h
>    <https://github.com/micropython/micropython/pull/2140/files#diff-9>
>    (357)
>    - *A* lib/fatfsobj/ffconf.h
>    <https://github.com/micropython/micropython/pull/2140/files#diff-10>
>    (339)
>    - *M* unix/Makefile
>    <https://github.com/micropython/micropython/pull/2140/files#diff-11>
>    (2)
>    - *M* unix/mpconfigport.h
>    <https://github.com/micropython/micropython/pull/2140/files#diff-12>
>    (1)
>
> Patch Links:
>
>    - https://github.com/micropython/micropython/pull/2140.patch
>    - https://github.com/micropython/micropython/pull/2140.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/micropython/micropython/pull/2140>, or mute the thread
> <https://github.com/notifications/unsubscribe/AE5ZoIelmmu9NtBLgQtC2DWbkww8hypUks5qHa4CgaJpZM4Irtu7>
> .
>



-- 
Meski

 http://courteous.ly/aAOZcv

"Going to Starbucks for coffee is like going to prison for sex. Sure,
you'll get it, but it's going to be rough" - Adam Hills

**Comment by dpgeorge** [comment]
> And the biggest question I sought to find answer to is: How big are changes to FatFs, would it scale to patch it and pull in vendor updates to our branch? But there're only blob code drops of already patched code.

My grand plan was to have a seprate repo for a patched version of fatfs, which is separately maintained (and tested).  I started doing that and it can be found at https://github.com/dpgeorge/microvfs/tree/dev .  I took a pristine copy of fatfs and used git commits to track the changes, see here: https://github.com/dpgeorge/microvfs/commits/dev .

There are many deep changes and I think the easiest way to integrate upstream changes to fatfs is to diff the new fatfs version with the one I started from, and then add the changes manually.

> I also would think we'd want to switch to our version FatFs, but I guess introduction of lib/fatfsobj in parallel to lib/fatfs is maintenance measure, to not require all ports to switch at once.

Yes.  At the moment the current PR will not work correctly with stmhal.  I need to re-implement the creation of partition tables.

> Have we looked at alternatives to FAT?

I would like to have the option for other filesystems.  My grand-grand plan was to implement a flexible "micro vfs" architecture (see https://github.com/dpgeorge/microvfs) which provided functions like vfs_open, vfs_stat, vfs_mount, vfs_umount, etc, and which could support arbitrary block devices and arbitrary filesystems.  But I didn't get that far yet.

**Comment by pfalcon** [comment]
> There are many deep changes and I think the easiest way to integrate upstream changes to fatfs is to diff the new fatfs version with the one I started from, and then add the changes manually.

I'd suggest to follow "vendor branch" workflow, known yet from CVS times: there's a branch which tracks vendor releases as-is, each tagged with upstream version. So, you can easily diff any upstream versions. For this to work, not just the latest release needs to be imported, but few. Extra points for importing *all* vendor releases.

Then, from a particular tag, a work branch can be created, with changes on top of it. With git's facilities (like ranged cherry-pick), change from work-vX.X to work-vY.Y could be ported largely automatedly, with minimal efforts.

I'm using this workflow for esp8266 lwip repo, etc. 

> My grand-grand plan was to implement a flexible "micro vfs" architecture (see https://github.com/dpgeorge/microvfs) which provided functions like vfs_open, vfs_stat, vfs_mount, vfs_umount

With the workflow above, this doesn't work, or rather, misplaced. Actually, it's misplaced even with other workflow - it's one thing to modify FatFs to remove (ahem, misplaced in our view) code to handle adhoc mounting, and another to provide more universal mounting (why tie it to FatFs? - it's the same mistake as in original FatFs).

**Comment by dpgeorge** [comment]
> it's one thing to modify FatFs to remove (ahem, misplaced in our view) code to handle adhoc mounting, and another to provide more universal mounting

The idea is to provide a universal vfs sub-system, of which fatfs is just a component.  But the fatfs component would be a modified version of the upstream code (to make it more OO like).  In this case the workflow could be:

- Have a repo dedicated to modifying fatfs to be OO like.  It could use vendor branch workflow.
- Have a repo for the universal vfs sub-system, which pulls in the above repo (and other ones for other filesystems).
- Pull in the above repo into uPy.

**Comment by pfalcon** [comment]
> Have a repo dedicated to modifying fatfs to be OO like. It could use vendor branch workflow.

+1

> Have a repo for the universal vfs sub-system, which pulls in the above repo (and other ones for other filesystems).

If you think it's worth it. Note that what this subsystem would be is a mount table management code and multiplexer for filesystem calls using it. Done directly in uPy, mount table could use a dictionary (perhaps with and adhoc code to scan it still), whereas in separate codebase that all needs to spelled out from scratch.

**Comment by jms19** [comment]
Well I see things are heading in the right direction and am more than happy to make my SPIFFS glue code fit as a genuinely useful test case. Currently my filesystem object has an open method after which the filehandle behaves normally. It's also got hard-coded calls to the ESP8266's flash functions.

http://jschneider.net/spiffs.html

**Comment by tannewt** [comment]
Whats the status of this PR? I'm interested in adding multi-mount support to CircuitPython and would love to coordinate our efforts.

**Comment by dpgeorge** [comment]
> Whats the status of this PR?

I'm actually working on it right now :)  I will post something soon then we can discuss.

**Comment by tannewt** [comment]
Awesome! What order of magnitude is soon? Hours? Days? Weeks?

**Comment by dpgeorge** [comment]
> Have a repo dedicated to modifying fatfs to be OO like. It could use vendor branch workflow.

Ok, this is now done, see https://github.com/micropython/oofatfs .  The current working branch is work-R0.12a.

As discussed above, I think the best way to migrate to this new OO fatfs is to allow it to exist in parallel with the old fatfs driver for the time being, and carefully change users of code (starting with unix) to the new version.

@tannewt once the OO component lands you should be able to start using it right away.  It should happen in a few days.

**Comment by tannewt** [comment]
Ok awesome work @dpgeorge! I'll probably switch our esp8266 and samd ports
over straight away.

**Comment by jms19** [comment]
I'd like to ask for clarification.

Which of these two is this issue about ?

a) adding lots of different flavours of FAT filesystems. By FAT I mean what the PC DOS through to Windows 9x operating systems used. Main feature is a file allocation table making it unsuitable for use on flash devices.

b) allowing for non-FAT filesystems in which case please could you fix the terminology.

Jon

**Comment by dpgeorge** [comment]
This is now ready to merge to master.  The new oofatfs component is at the latest R0.12b (which supports exfat).  Unix tests are passing.  From here it requires converting esp8266 port to use oofatfs, and then gradually cleaning up the interface of the VfsFat class and uos modules.

**Comment by dpgeorge** [comment]
> Which of these two is this issue about ?
> 
> a) adding lots of different flavours of FAT filesystems. By FAT I mean what the PC DOS through to Windows 9x operating systems used. Main feature is a file allocation table making it unsuitable for use on flash devices.

No, it's not about that.  The existing FatFs library already provides support for FAT12, FAT16, FAT32.

> b) allowing for non-FAT filesystems in which case please could you fix the terminology.

It's not about that either.

What it is about is described by the title of the issue: converting the existing FatFs library to an object-oriented variant.  Ultimately this will allow for plugging in other, non-FAT filesystems but there're a few steps to go before we get there.

**Comment by dpgeorge** [comment]
This has now been merged and a generic VFS sub-system has been added, see dcb9ea72157f1d9f3b0dc306c2c31cbd647f5ee1 and fb3ae1784e1905709f82aadb7f1c8994682f9759.

The unix and esp8266 ports have been updated to use the new VFS system, and can mount an arbitray number of devices.

@tannewt you should be able to integrate this into your port, just follow how it's done by esp8266.

@jms19 there is now a generic VFS sub-system that is indepented to the FatFs driver, so if you like you can try creating a SPIFFS component to plug into this system.  Such a component should fit above the block device and below the VFS infrastructure.  It should implement calls such as mount, umount, listdir, chdir, remove, rename, mkdir, rmdir, open.  See extmod/vfs_fat.c for how FatFs works (it's exposed via the VfsFat object).

**Comment by tannewt** [comment]
Thanks a bunch @dpgeorge. That sounds really promising. I've gotten distracted by PWM and HID and will let you know when I circle back to it.

**Comment by tannewt** [comment]
Spent the day merging this in. My first impression is that it looks really good! I really like the cleanup of the `uos` module in particular. Thanks again!

**Pull request merged**
