### PR TITLE
py/py.mk: When building axtls use -Wno-all to prevent all warnings.

### PR DESCRIPTION
**Pull request by dpgeorge**
Building axtls gives a lot of warnings with -Wall enabled, and explicitly disabling all of them cannot be done in a way compatible with gcc and clang, and likely other compilers.  So just use -Wno-all to prevent all of the extra warnings.  -Wno-uninitialized is still needed though.

Should fix issue #4182.

### CODE REVIEW

**Comment by pfalcon** [comment]
Looks good.

**Comment by pfalcon** [comment]
... But something wrong seems to have happened with CI, apparently after yesterday's Github semi-downtime - CI boxes seem to have gone from all PRs, even old.

**Comment by pfalcon** [comment]
For example, this one is actually failed in Travis: https://travis-ci.org/micropython/micropython/builds/444883363

**Comment by dpgeorge** [comment]
Oops, it looks like I didn't keep enough of the -Wno-xxx's to get the coverage build to work.  Now added back, and also tested with clang on unix.

**Comment by dpgeorge** [comment]
Merged in 746dbf78d3067f32c8885217d53ff9231dac3772

**Pull request closed without merging**
