### PR TITLE
README: With "async" support, bump supported language version to 3.5.

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by pfalcon** [comment]
@dpgeorge , @pohmelie : I think it's now fair to make this change. Let me know if some "but"'s should be added.

**Comment by pohmelie** [comment]
Maybe add note, that async/await/async with/async for is just sugar for yield from/etc.
Current micropython version is much less strict, since you can yield and yield from from async def, no implicit call to __await__ and no awaitable objects, no coroutine type.

**Comment by pohmelie** [comment]
Maybe add info to https://github.com/micropython/micropython/wiki/Differences and link to them.

**Comment by pfalcon** [comment]
> Maybe add note, that async/await/async with/async for is just sugar for yield from/etc.

Nope, that's superfluous information, as fasr as MicroPython README goes. As long as *all* variants of async are implemented, and we can say "entire 3.5 syntax implemented", that's enough.

> Current micropython version is much less strict

MicroPython is always less strict, and should stay that way (more efficiency, less check bloat). People who're interested in strict mode, should just run their up with CPython regularly.

**Comment by pfalcon** [comment]
> Maybe add info to https://github.com/micropython/micropython/wiki/Differences and link to them.

Feel free to add the points there, as you know them (I don't for example). It's not good idea to link sub-maintained unofficial notes into the official, front-facing README.

**Comment by dpgeorge** [comment]
I don't think it's yet fair to make this change.  Grammar/syntax changes still to make are addition of matrix mult operator, and unpacking generalisations.

**Comment by pohmelie** [comment]
@pfalcon, ok, I will add some info to `differences` wiki page. Which category it is? «By design» or «implementation»?

**Comment by pfalcon** [comment]
@dpgeorge : As you wish, that's preparation for upcoming 1.8, to not forget it if needed.

**Comment by pfalcon** [comment]
@pohmelie : I'd say implementation, but feel free to add where you see fit, can be moved later. Thanks!

**Comment by pfalcon** [comment]
Add mentioned of "async" separately in 3f3ccef8292414d99d4ebd19eddebc6db3124bc4.

**Comment by pohmelie** [comment]
Need some review and update of [wiki page](https://github.com/micropython/micropython/wiki/Differences), since I'm not too good documentation writer :grin:

**Comment by pfalcon** [comment]
@pohmelie : Thanks for starting it, I rewrote it to hopefully make it clear, please see if still has all points you wanted to mention.

**Comment by pohmelie** [comment]
@pfalcon, thanks, your version is much cleaner :+1:

**Pull request closed without merging**
