### PR TITLE
Try to detect the pyboard and use that as the default port.

### PR DESCRIPTION
**Pull request by dhylands**
My take on providing a default port.

For OSX, pyserial needs to be patched. I documented how to do that over here:
https://github.com/micropython/micropython/wiki/Micro-Python-on-Mac-OSX#patching-pyserial-27

### CODE REVIEW

**Comment by pfalcon** [comment]
More dependencies, niiiiiiceeee... And unlike https://github.com/micropython/micropython/pull/1314 , this patch again leads us outside domain supported by uPy (that's after @dpgeorge took you idea in #1282 and added to micropython-serial couple of additional methods). That's why I was -1 even on #1314 - once you start to add not-really-needed dependencies, you don't know where to stop.

**Comment by dhylands** [comment]
You know what they patches welcome.

**Comment by dhylands** [comment]
So what exactly are your requirements?

You seem to want the correct answer with no additional dependencies, also have it be cross-platform and not use "arbitrary" strings - which is how the original is coded. It's easy enough to make it fail if the dependency doesn't exist and just do the original behavior in that case (although based on your other complaints - that also seems to be unacceptable)

**Comment by dhylands** [comment]
Updated PR to fall back on original behaviour if the added dependency (of serial.tools.list_ports) doesn't exist.

**Comment by pfalcon** [comment]
So I personally don't "want" anything or have requirements, just share my opinion that the tool is already good enough like it is, and point at various problems which attempts to make it "better" bring. So, I hope you guys will make those change if they really bring more boon than problems. (I fail to seem them doing so, yeah, but that's only me.)

**Comment by dhylands** [comment]
IMHO - I think that the code is better with the changes than without. For exactly the reason that you argue elsewhere. The currect code opens /dev/ttyACM0 which is an arbitrary string and only happens to be right on exactly one platform when you don't have some other usb device plugged in which occupies /dev/ttyACM0.

With this proposed change, running pyboard.py will pick the correct serial port more reliably than it did before.

**Comment by pfalcon** [comment]
> The current code opens /dev/ttyACM0 which is an arbitrary string

Ok, I see the issue. I personally would treat /dev/ttyACM0 shown in a help as, well, additional help what kind of thing should be passed here. I would, if it at all would have been shown. But it's currently not, so nobody even supposed to know that it's a default value (except @dpgeorge), so just removing a default value and making --device arg mandatory (possibly renaming to --port, almost certainly adding a short option) would solve "all" the problems.

**Comment by dpgeorge** [comment]
Mandatory args should not be "options" in the sense of --arg.  They should be positional; eg picocom /dev/ttyACM0 --baud 115200.

**Comment by dpgeorge** [comment]
Now that tools/pyboard.py supports telnet mode (see cd14188bc8b4cd942ea7ea5cf5eb27955d8695ae) as well as direct tty mode I can see more clearly @pfalcon's point of view and would now advocate removing the default entirely.  This would force the user to specify the "device", where device can mean any "URI" that accesses a pyboard.  The device would be the first argument, eg:
```
pyboard.py /dev/ttyACM0 script.py
pyboard.py 1921.68.1.1 script.py
```
Then run-tests would require a device argument if target is not unix:
```
./run-tests --target pyboard --device /dev/ttyACM0
./run-tests --target wipy --device 192.168.1.1
```

**Pull request closed without merging**
