### PR TITLE
ports/unix/mpconfigport.h: Enable "help" module by default.

### PR DESCRIPTION
**Pull request by ccooper21**
The "help" module is disabled by default for the UNIX port, making it
difficult to explore the available modules (e.g. via the use of the
"help('modules')" call).  This change enables it by default.

### CODE REVIEW

**Review by pfalcon — CHANGES_REQUESTED** [review]
This is a FAQ. There's no need for C "help" implementation in unix port, because it can be implemented in Python. And the fact that nobody did it proves that it's not much needed at all. What unix port needs is https://github.com/micropython/micropython/issues/2908. Then when it's done, more useful things can be added (yet need to be implemented).

**Comment by ccooper21** [comment]
Even if it is undesirable to have this enabled by default, doesn't it at
least make sense to include the related configuration options in the
"mpconfigport.h" file so that others have a chance to figure out how to
enable this without having to investigate how it works for other ports?

Frankly, I didn't even know this feature existed until someone recently
mentioned it in the forums.  I was disappointed to discover that it didn't
work for the UNIX port, where I do much of my development.  You mentioned
this could be implemented in Python instead.  Unfortunately, I don't know
how to do that.  In any case, it doesn't make much sense to me why there
should be multiple implementations for the same thing written in different
languages.  Why don't all the ports use a Python implementation if that is
preferred?

**Comment by robert-hh** [comment]
Whether the "help" feature is resonable at all, may be discussed. But if yes, it is better in my opion to use the built-in variant, simply because it is always in sync with the actual configuration. An external module would have to be re-tailored constantly.
And yes, keeping the size in focus is mandatory. But memory sizes of devices increase, and for instance the 512k target of ESP8266 seems not really of interest any more, whereas last year it still seemd to be a valid objective.

**Comment by peterhinch** [comment]
On baremetal `help('modules')` lists frozen bytecode. As far as I know this has to be in C because FBC exists outside the filesystem. If on Unix everything is in the filesystem, modules in the Python path can be located and listed in Python. No syncing required. Or am I missing something?

**Comment by pfalcon** [comment]
> Even if it is undesirable to have this enabled by default, doesn't it at least make sense to include the related configuration options in the "mpconfigport.h" file so that others have a chance to figure out how to enable this without having to investigate how it works for other ports?

1) We have *all* configuration options listed in py/mpconfig.h.
2) For different uPy users, different options are interesting and important. For example, you say it's *_HELP, someone else may want something else, to satisfy everyone, we'll need to duplicate py/mpconfig.h content.
3) @dpgeorge specifically said he doesn't want options with default values to be set in mpconfigport.h (i.e. there should be only overrides. (I'd personally be happy to make exception for some options, including ack'ing yours proposal for *_HELP).

**Comment by pfalcon** [comment]
> But memory sizes of devices increase, and for instance the 512k target of ESP8266 seems not really of interest any more, whereas last year it still seemd to be a valid objective.

Memory size of my devices doesn't increase - the boards I have in my drawer for 3 years has the same amount of memory as before, ditto for various routers, etc. ;-).

In general, the outlook of this problem is described in https://github.com/micropython/micropython/wiki/ContributorGuidelines : there're two alternatives: CPython, which has builtin help on Unix, with which we don't want to compete, and other small languages, with which we want to stay competitive. Otherwise, uPy is very configurable and everyone should be able to adjust it for their needs, the default config however emphasize uPy's strong sides, which are: small size, and competitiveness with other small-size languages.

**Comment by pfalcon** [comment]
> On baremetal help('modules') lists frozen bytecode. As far as I know this has to be in C because FBC exists outside the filesystem. If on Unix everything is in the filesystem, modules in the Python path can be located and listed in Python. No syncing required. Or am I missing something?

Help can be implemented as:

~~~
def my_help(*args, **kwargs):
    # Do what you want

import builtins
builtins.help = my_help
~~~

That can be imported from site.py or boot.py (we didn't decide which unix port should use, thus not implemented). If some things aren't doable, they can be implemented (optional; default off; with tests to not decrease coverage).

**Comment by pfalcon** [comment]
> Why don't all the ports use a Python implementation if that is preferred?

Because all ports have different requirements and usecases.

**Comment by ccooper21** [comment]
> We have all configuration options listed in py/mpconfig.h.

Thanks for mentioning this.  I had not encountered the `py/mpconfig.h` file yet.  Maybe I'm not appreciating its intent, but it does seem like something that isn't a great idea to modify locally.

>  it can be implemented in Python

How would one go about enumerating the available modules from Python that are not on the file system?  This would include the stuff that comes standard with MicroPython and additional frozen code.  I spent 20 minutes trying to figure this out, and was unsuccessful.  I also looked at how the C implementation works, but I don't see where any of the C plumbing that it is being used is exposed to Python.

**Comment by justinmoon** [comment]
This would be very useful ([as discussed on micropython forum](https://forum.micropython.org/viewtopic.php?t=7069))

**Comment by dpgeorge** [comment]
This was enabled in 6430cd3e02d4ec4a8fc949754b434f745b1973e6 (on standard and dev variants of the unix port).

**Pull request closed without merging**
