### PR TITLE
extmod/moducryptolib: Add crypto functions module, impl reuses axTLS routines.

### PR DESCRIPTION
**Pull request by pfalcon**
The API follows guidelines of https://www.python.org/dev/peps/pep-0272/ ,
but is optimized for the code size, with the idea that full PEP 0272
can be added with a simple Python wrapper mode.

At the bare minimum, this module is expected to provide:

* AES128, ECB (i.e. "null") mode, encrypt only

Implementation in this commit is based on axTLS routines, and implements
following:

* AES 128 and 256
* ECB and CBC modes
* encrypt and decrypt

### CODE REVIEW

**Comment by pfalcon** [comment]
Points to consider:

1. This reuses all the collected knowledge from the design of previous "u" modules. It can be summarized as: Python is the language, where users are expected to write convenient wrappers (in Python). Then, the main criteria for the builtin modules should be: the smallest size. Any boilerplate stuff should be moved to such convenience wrappers, otherwise allowing people who need that, to use this module in the stringent resource constraints (like it usually is). This goes down to the no need to provide symbolic names for well-known number in the builtin modules. 

2. Module name: this patch uses "ucrypto", but I think we should have "ucryptolib", similar to hashlib. This may also help to avoid confusion with the wrapper name, which will be named "uCrypto", based on the popular CPython package: https://www.dlitz.net/software/pycrypto/api/current/ .

3.  PEP 272 compatibility: PEP 272 is nice, truly Pythonic spec, without kwonly args and other unproven novelties applied all over the place. But, it for some reason imagines that crypto algs are implemented in "modules". We implement them in classes. We could provide @staticmethod new, but there's no point in doing that, see p.1.

4. Casing of class names in module. Again, follows hashlib with lower-case naming. Again, may help to avoid confusion with Crypto/uCrypto.

5. Actual API. So far this implements literal methods form PEP 272, but we know that for real use in constrained environments, we need inplace functions. Again, applying the previous experience, then we simply don't need garbage-producing funcs. So, only encryptinto() and decryptinto(), likely taking offset/size.

**Comment by pfalcon** [comment]
This requires (trivial) axTLS patches, not yet landed.

**Comment by pfalcon** [comment]
Other thing which concerns me is padding. I was surprised to find that PEP 272 requires input to be even number of cipher blocks, so for now we can ignore it. But I'm sure we need to deal with it in general. (To allow efficient/transparent implementation of crypted channels for arbitrary-sized records.)

**Comment by pfalcon** [comment]
And per our previous discussions, uPy module would provide the most basic crypto primitive, which is just block-sized encryption (ECB mode). But that alone is not useful unfortunately, as in real-world usages other  modes are used, CBC is probably still one of the widest used.

So, as PEP 272 works in terms of modes, I thought it makes sense to support that, it still allows to scale down to just ECB encryption.

**Comment by dmazzella** [comment]
@pfalcon I have worked on uCrypto last year, but instead use axtls i have used:
- rijndael-alg-fst.c 
- des.c

from [web.mit.edu](web.mit.edu/freebsd/head/sys/crypto/) and this is the motivation becouse i have never do a PR.

Tests:

ucrypto_aes_1.py

```
try:
    import uhashlib as hashlib
    from uCrypto import AES
except ImportError:
    try:
        from Crypto.Cipher import AES
        import hashlib
    except ImportError:
        print("SKIP")
        raise SystemExit

hash = hashlib.sha256(b"A" * 64).digest()

modes = [
    AES.MODE_ECB,
    AES.MODE_CBC
]
key = b'A'*16
for m in modes:
    CHIPER_AES = AES.new if hasattr(AES, "new") else AES
    IV = b'A'*16 #An Initialization Vector (IV) is required on CBC ignored in ECB
    assert CHIPER_AES(key, m, IV).decrypt(CHIPER_AES(key, m, IV).encrypt(hash)) == hash
    print("AES encrypt and decrypt OK")
```

ucrypto_des_1.py

```
try:
    from ubinascii import unhexlify
    from uCrypto import DES3 as DES
except ImportError:
    try:
        from binascii import unhexlify
        from Crypto.Cipher import DES3 as DES
    except ImportError:
        print("SKIP")
        raise SystemExit

modes = [
    DES.MODE_ECB,
    DES.MODE_CBC
]
key = unhexlify('BB'*24)
data = unhexlify('AA'*32)

for m in modes:
    iv = unhexlify('BA'*8) #An Initialization Vector (IV) is required on CBC ignored in ECB
    CHIPER_DES = DES.new if hasattr(DES, "new") else DES
    encrypted = CHIPER_DES(key, m, iv).encrypt(data)
    decrypted = CHIPER_DES(key, m, iv).decrypt(encrypted)
    assert decrypted == data
    print("DES encrypt and decrypt OK")
```

**Comment by pfalcon** [comment]
@dmazzella : Yeah, adding crypto module was discuss long enough ago, I proposed a minimal AES256 impl which I ever found and patched for AES128 support, @dpgeorge proposed his impl supporting only encrypt op, on the basis that a minimal usage would select CTR mode, a lot of people was writing crypto in pure Python, which of course doesn't make sense except as an exercise, etc.

It makes sense to resolve this finally, and in practical way, the same way as we already offer e.g. SHA1 - by reusing the underlying TLS library with all its crypto. That's not complete solution, we'll need to have a backup plan for TLS-less build, but the ordering can be just that: let's offer a realworld useful functionality finally, then work on backup plan when priorities permit.

Comments on points in https://github.com/micropython/micropython/pull/3413#issuecomment-341898639 are welcome.

**Comment by pfalcon** [comment]
This fails in Travis with:

~~~
3 tests failed: ucrypto_aes128_cbc ucrypto_aes128_ecb ucrypto_aes128_ecb_enc
The command "(cd tests && MICROPY_CPYTHON3=python3.4 MICROPY_MICROPYTHON=../ports/unix/micropython_coverage ./run-tests)" exited with 1.
~~~

Not sure what's wrong. If PyCrypto is not installed in Travis, the tests should be just skipped.

**Comment by pfalcon** [comment]
Ah, d'oh:

~~~
--- ucrypto_aes128_cbc.py.exp	2017-11-08 18:23:47.410681262 +0000
+++ ucrypto_aes128_cbc.py.out	2017-11-08 18:23:47.410681262 +0000
@@ -1 +1,2 @@
-SKIP
+b'\x1d\x84\xfa\xaa%\x0e9\x143\x8b6\xf8\xdf^yh\xd0\x94g\xf4\xcf\x1d\xa0I)\x8a\xa0\x00u0+C'
+b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f'
~~~

Well, I'd wonder, if that should be fixed by allowing to skip CPython tests...

**Comment by pfalcon** [comment]
I can't update this PR, so resubmitted as https://github.com/micropython/micropython/pull/3460.

**Pull request closed without merging**
