### PR TITLE
STM32F091: Enable lfs1 filesystem.

### PR DESCRIPTION
**Pull request by chrismas9**
With the current NUCLEO_F091RC features the LFS1 filesystem size is 12K.
This can be increased by disabling some features, eg:

MICROPY_PY_BUILTINS_COMPLEX approx 2K.
MICROPY_PY_FRAMEBUF approx 4K.
MICROPY_PY_ONEWIRE approx 600B
MICROPY_PY_UHEAPQ, MICROPY_PY_UTIMEQ approx 1K.
MICROPY_PY_ASYNC_AWAIT approx 1K.
MICROPY_HW_ENABLE_ADC approx 3K.
MICROPY_HW_ENABLE_DAC nearly 2K.
MICROPY_HW_UART approx 200B per UART. There are eight enabled.

Many of these are disabled on the NUCLEO_L432KC port which gives it a 26K filesystem.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks, this is a nice change!

I think we should disable the following features to get more space for the filesystem:
- MICROPY_PY_BUILTINS_COMPLEX
- MICROPY_PY_FRAMEBUF
- MICROPY_PY_UHEAPQ, MICROPY_PY_UTIMEQ

An then increase the filesystem a bit.

Are you able to do that?

**Comment by chrismas9** [comment]
Filesystem now 20K with ~1700 bytes free for growth. Rebased and force pushed.

**Comment by dpgeorge** [comment]
Thanks for updating.  I tested it and it works well, although I needed to do a manual `VfsLfs1.mkfs(pyb.Flash(start=0))`.

Merged in fdbca3c1435910b23ad96d751a226f27e24b5aee and 868f23b362171ee131bd6bfa784911fb8fc66202 with some very minor cosmetic changes.

**Comment by chrismas9** [comment]
> although I needed to do a manual VfsLfs1.mkfs(pyb.Flash(start=0))

I though that was aleways the case with lfs. It would be nice if the filesystem was created when missing, like for FAT, at least when there is only one filesystem type enabled in a port.

**Comment by robert-hh** [comment]
that is usually done in _boot.py. it tries to mount the fs, and if that fails, the fs is created and then mounted.

**Pull request closed without merging**
