### PR TITLE
unix/mpconfigport: Enable MICROPY_PY_DELATTR_SETATTR

### PR DESCRIPTION
**Pull request by andrewleech**
This setting is enabled by default in the stm32 port and in the unix coverage port.

This feature is used heavily by my structured_config module so would be really handy to have on by default in unix port.
Ref: https://gitlab.com/alelec/micropython-structured-config

### CODE REVIEW

**Comment by dpgeorge** [comment]
+1 to enable this.  It's a generally useful feature and because it's part of the object model it cannot be added at runtime by some loadable Python code (like an extension to a module could be added).

I think the main reason this wasn't enabled initially (apart from increasing code size) is because of performance concerns.  But performance was improved for this feature, so would be good to just check the performance change with this option enabled.

**Comment by andrewleech** [comment]
It's probably worth thinking about this for esp32 port as well for consistency.   
I'd be more loath to enable it on smaller devices like esp8266 though.

**Comment by dpgeorge** [comment]
Yes, esp32 makes sense as well, to enable it.

**Comment by jimmo** [comment]
This PR was referenced from the forum: https://forum.micropython.org/viewtopic.php?f=2&t=9131

Can we leave ESP32 for a separate PR? Seems like definitely worth enabling for Unix, and if not in the `standard` variant, definitely in the `dev` variant.

**Comment by dpgeorge** [comment]
Ok, merged in 32c99174e143b45d056c83a33f8de7502a82370c

(I ran the performance benchmark tests on unix before and after this patch and couldn't measure a noticeable difference.)

**Pull request closed without merging**
