### PR TITLE
global: Remove the STATIC macro.

### PR DESCRIPTION
**Pull request by projectgus**
@dpgeorge has said for a while that he wants to get rid of the `STATIC` macro. No time like the present!

The macro is fully removed rather than deprecated. I think this is reasonable as it's a relatively quick refactor to clean up from, but I have a script (see below) to post a heads-up to everyone with an open PR that adds the `STATIC` macro.

If that's not acceptable then I think we could add a CI check that blocks addition of `STATIC`, but keep the macro defined otherwise. But I think this way is probably less fiddly in some ways (doesn't leave contributors bouncing off the CI.)

## Methodology

1) `git ls-files | egrep '\.[ch]$' | xargs sed -Ei "s/(^| )STATIC($| )/\1static\2/"`
2) Do some manual cleanup in the diff by searching for the word STATIC in comments and changing those back.
3) `git-grep STATIC docs/`, manually fixed those cases
4) `rg -t python STATIC`, manually fixed the codegen lines that used STATIC.
5) A few files in renesas-ra port flagged codespell so there are some spelling fixes on top of everything else.
6) Few one-off cases (coverage.cpp file, a lone STATIC in a parenthesis, etc.) were caught by CI.

## Automated heads-up

I have knocked up a [quick script](https://gist.github.com/projectgus/0aa5264d193bd58017205aa5486a9217) to leave a comment on every PR that seems to add `STATIC` in the diff, letting them know that when they rebase they'll need to change it to `static`.

(Of course, there will also be some inevitable merge conflicts from changed lines. There isn't really a way around that, apart from not moving away from the macro.)

## Follow-up work

Separate PR https://github.com/georgerobotics/cyw43-driver/pull/109 to remove STATIC from cyw43-driver repo. Once merged then can revert the commit in this branch that manually sets the macro when building those files.

*This work was funded through GitHub Sponsors.*

### CODE REVIEW

**Comment by projectgus** [comment]
@jimmo The comment script took me just under 30 minutes. Not sure if that counts as good automation or not (leaving hundreds of comments would take hours but I would never do that, the real time saved is PR authors knowing in advance that when they rebase they'll have to apply the change.)

**Comment by jimmo** [comment]
> @jimmo The comment script took me just under 30 minutes. Not sure if that counts as good automation or not? 😁

@projectgus Excellent automation, would automate again.

Thanks for doing this PR :)

**Comment by dpgeorge** [comment]
The original reason for this STATIC macro was to define it to nothing so that all static functions become global functions, and therefore visible to certain debug tools.  From commit d5df6cd44a433d6253a61cb0f987835fbc06b2de:
```
Some tools do not support local/static symbols (one example is GNU ld map file).
Exposing all functions will allow to do detailed size comparisons, etc.
```
Personally I have never used this feature.  And with the use of LTO and heavy inline optimisation, analysing size of individual functions when they are not static is not a good representation of the size of code when fully optimised.

So I don't really see any use for this STATIC macro.  And it's simpler not to have the macro, ie just use `static` as-is, because then you know exactly what it's doing.  Eg for newcomers they don't have to learn what the STATIC macro is.

One other point in favour of removing it, is that it stops bugs with `STATIC inline`, which should always be `static inline`.

**Comment by projectgus** [comment]
@tannewt @dhalbert Heads-up about something with potential to cause some transient pain in the next merge. :)

**Comment by robert-hh** [comment]
It will likewise be pain for everyone with open PRs, I guess.

**Comment by robert-hh** [comment]
@projectgus For the automation script I used a slightly modified version and replaced
`git ls-files`  with `git show --pretty="" --name-only <first_commit>..<last_commit> | sort | uniq`, with `<first_commit>` and `<last_commit>` being the commit id's of the PR. That way, only the files are touched that belong to the PR. Otherwise all files of the repository will be processed.

**Comment by Gadgetoid** [comment]
Thank you for posting your methodology, it helped me prepare my codebase and raise a PR against ulab - https://github.com/v923z/micropython-ulab/pull/664

And a patch against `pimoroni-pico` - https://github.com/pimoroni/pimoroni-pico/pull/906

AIUI all downstream code can pretty much make this change immediately. In our case (pimoroni-pico) we pretty much universally expect `STATIC` to resolve to `static` and, afaik, have never used the mentioned technique for debugging since most of our Python bindings are just glue to underlying classes anyway.

> It will likewise be pain for everyone with open PRs, I guess.

Pain is good. Separates the serious contributors from the drive bys 😆

**Comment by robert-hh** [comment]
> Pain is good. 

Pain is pain. Besides that, I expect quite a few merge conflicts, independent from how the change will be made. - If a branch is not processed according to this PR before attempting a rebase, there will be merge conflicts at the new commits when rebasing. Git cannot tell whether `STATIC` or `static` is right, and will eventually even include adjacent lines into the conflict's span.
- If a branch is processed according to this PR before rebase, it could only work if there are no changes to the master branch after applying the global replace. If there have been such, there will by conflicts is the base part of the code.

There are some ways to avoid that, like:
-  deliberately change STATIC to static in the files changed in a branch before rebasing to the changed master. That must be done in reverse order from the newest to the oldest commit.
- create a new branch for a feature , do a bulk change of the old branch for this feature and cherry-pick the commits from the old branch to the new one.

Obviously, code that did not use the STATIC macro is not affected.

**Comment by Gadgetoid** [comment]
According to a grep of every open PR, those affected include (129/342):

* https://github.com/micropython/micropython/pull/13764
* https://github.com/micropython/micropython/pull/13755
* https://github.com/micropython/micropython/pull/13727
* https://github.com/micropython/micropython/pull/13689
* https://github.com/micropython/micropython/pull/13658
* https://github.com/micropython/micropython/pull/13630
* https://github.com/micropython/micropython/pull/13583
* https://github.com/micropython/micropython/pull/13572
* https://github.com/micropython/micropython/pull/13470
* https://github.com/micropython/micropython/pull/13429
* https://github.com/micropython/micropython/pull/13390
* https://github.com/micropython/micropython/pull/13378
* https://github.com/micropython/micropython/pull/13340
* https://github.com/micropython/micropython/pull/13281
* https://github.com/micropython/micropython/pull/13276
* https://github.com/micropython/micropython/pull/13011
* https://github.com/micropython/micropython/pull/13000
* https://github.com/micropython/micropython/pull/12949
* https://github.com/micropython/micropython/pull/12918
* https://github.com/micropython/micropython/pull/12853
* https://github.com/micropython/micropython/pull/12810
* https://github.com/micropython/micropython/pull/12780
* https://github.com/micropython/micropython/pull/12732
* https://github.com/micropython/micropython/pull/12722
* https://github.com/micropython/micropython/pull/12650
* https://github.com/micropython/micropython/pull/12644
* https://github.com/micropython/micropython/pull/12540
* https://github.com/micropython/micropython/pull/12487
* https://github.com/micropython/micropython/pull/12464
* https://github.com/micropython/micropython/pull/12429
* https://github.com/micropython/micropython/pull/12347
* https://github.com/micropython/micropython/pull/12346
* https://github.com/micropython/micropython/pull/12345
* https://github.com/micropython/micropython/pull/12331
* https://github.com/micropython/micropython/pull/12324
* https://github.com/micropython/micropython/pull/12293
* https://github.com/micropython/micropython/pull/12291
* https://github.com/micropython/micropython/pull/12155
* https://github.com/micropython/micropython/pull/12047
* https://github.com/micropython/micropython/pull/12008
* https://github.com/micropython/micropython/pull/11880
* https://github.com/micropython/micropython/pull/11723
* https://github.com/micropython/micropython/pull/11679
* https://github.com/micropython/micropython/pull/11672
* https://github.com/micropython/micropython/pull/11572
* https://github.com/micropython/micropython/pull/11500
* https://github.com/micropython/micropython/pull/11430
* https://github.com/micropython/micropython/pull/11365
* https://github.com/micropython/micropython/pull/11360
* https://github.com/micropython/micropython/pull/11244
* https://github.com/micropython/micropython/pull/11183
* https://github.com/micropython/micropython/pull/10859
* https://github.com/micropython/micropython/pull/10854
* https://github.com/micropython/micropython/pull/10852
* https://github.com/micropython/micropython/pull/10783
* https://github.com/micropython/micropython/pull/10752
* https://github.com/micropython/micropython/pull/10724
* https://github.com/micropython/micropython/pull/10607
* https://github.com/micropython/micropython/pull/10595
* https://github.com/micropython/micropython/pull/10400
* https://github.com/micropython/micropython/pull/10062
* https://github.com/micropython/micropython/pull/9997
* https://github.com/micropython/micropython/pull/9685
* https://github.com/micropython/micropython/pull/9644
* https://github.com/micropython/micropython/pull/9624
* https://github.com/micropython/micropython/pull/9497
* https://github.com/micropython/micropython/pull/9458
* https://github.com/micropython/micropython/pull/9367
* https://github.com/micropython/micropython/pull/9356
* https://github.com/micropython/micropython/pull/9309
* https://github.com/micropython/micropython/pull/9046
* https://github.com/micropython/micropython/pull/8995
* https://github.com/micropython/micropython/pull/8945
* https://github.com/micropython/micropython/pull/8922
* https://github.com/micropython/micropython/pull/8767
* https://github.com/micropython/micropython/pull/8766
* https://github.com/micropython/micropython/pull/8744
* https://github.com/micropython/micropython/pull/8637
* https://github.com/micropython/micropython/pull/8593
* https://github.com/micropython/micropython/pull/8503
* https://github.com/micropython/micropython/pull/8381
* https://github.com/micropython/micropython/pull/8331
* https://github.com/micropython/micropython/pull/8318
* https://github.com/micropython/micropython/pull/8270
* https://github.com/micropython/micropython/pull/8253
* https://github.com/micropython/micropython/pull/8236
* https://github.com/micropython/micropython/pull/8229
* https://github.com/micropython/micropython/pull/8027
* https://github.com/micropython/micropython/pull/7990
* https://github.com/micropython/micropython/pull/7845
* https://github.com/micropython/micropython/pull/7828
* https://github.com/micropython/micropython/pull/7796
* https://github.com/micropython/micropython/pull/7784
* https://github.com/micropython/micropython/pull/7781
* https://github.com/micropython/micropython/pull/7725
* https://github.com/micropython/micropython/pull/7703
* https://github.com/micropython/micropython/pull/7562
* https://github.com/micropython/micropython/pull/7526
* https://github.com/micropython/micropython/pull/7512
* https://github.com/micropython/micropython/pull/7133
* https://github.com/micropython/micropython/pull/7048
* https://github.com/micropython/micropython/pull/6963
* https://github.com/micropython/micropython/pull/6946
* https://github.com/micropython/micropython/pull/6668
* https://github.com/micropython/micropython/pull/6665
* https://github.com/micropython/micropython/pull/6639
* https://github.com/micropython/micropython/pull/6482
* https://github.com/micropython/micropython/pull/6408
* https://github.com/micropython/micropython/pull/6389
* https://github.com/micropython/micropython/pull/6263
* https://github.com/micropython/micropython/pull/6125
* https://github.com/micropython/micropython/pull/6080
* https://github.com/micropython/micropython/pull/6044
* https://github.com/micropython/micropython/pull/6024
* https://github.com/micropython/micropython/pull/6008
* https://github.com/micropython/micropython/pull/5973
* https://github.com/micropython/micropython/pull/5926
* https://github.com/micropython/micropython/pull/5711
* https://github.com/micropython/micropython/pull/5542
* https://github.com/micropython/micropython/pull/5514
* https://github.com/micropython/micropython/pull/5482
* https://github.com/micropython/micropython/pull/5473
* https://github.com/micropython/micropython/pull/5452
* https://github.com/micropython/micropython/pull/5449
* https://github.com/micropython/micropython/pull/5195
* https://github.com/micropython/micropython/pull/5104
* https://github.com/micropython/micropython/pull/5025
* https://github.com/micropython/micropython/pull/4464
* https://github.com/micropython/micropython/pull/3583

This was achieved by fetching a .patch file for every open PR and running:

```
grep -lr "+STATIC" patches/ > affected.txt
```

Then wrangling the result into a list of URLs.

**Comment by robert-hh** [comment]
That's quie a number, even if some of them can be considered as unmaintained or duplicates.

**Comment by Gadgetoid** [comment]
> That's quie a number, even if some of them can be considered as unmaintained or duplicates.

I concur! Earliest is from January 2018!! Is there a point at which PRs should be considered stale and closed for sanity's sake?

But either way, the potential impact is significant 😬

**Comment by robert-hh** [comment]
> Is there a point at which PRs should be considered stale and closed for sanity's sake

That would be a lot of work, looking into each of them. Damien closes sometimes some. And obviously, when they address an issue which is fixed otherwise. There could be a kind of timeout. Usually after a while there are changes to the main line which makes simple rebase impossible. If then the PR is not updated, it cannot be merged. So a check for the last change date could be a means.

**Comment by robert-hh** [comment]
> Waiting to do it will just lead to more code that needs to be updated. 

The discussion is not about waiting. It's just about the side effects and ways to proceed. Of course, who ever makes a PR has to maintain it.

**Comment by projectgus** [comment]
Rebased, checked no new STATIC snuck in.

@Gadgetoid Thanks for running through that and generating the PR table. I am planning to do something similar by automatically commenting on these PRs after merge (script linked in description), but it is good to provide the early link back notification as well! :pray:

**Comment by robert-hh** [comment]
> Rebased, checked no new STATIC snuck in.

After making the global replace, did you have to manually revert some of them?

**Comment by projectgus** [comment]
> After making the global replace, did you have to manually revert some of them?

The first time I had to, yes. After rebasing this branch on master I diffed against the pre-rebase commit, searched for STATIC in the diff and verified there weren't any occurrences.

**Comment by dpgeorge** [comment]
I've made the following changes to this PR:
- merged `cyw43-driver` changes and updated the submodule here
- removed the commit that defines STATIC for `cyw43-driver` source
- split out the codespell changes to the `renesas-ra` port to a separate commit, and enabled codespell CI on that port
- embellished the commit message for this PR with the reasoning for the change

**Comment by dpgeorge** [comment]
Note: it's not anyway possible to build (the unix port at least) with `STATIC` defined to nothing, because it leads to clashing symbols.  Eg `socket_read` is defined in both `modsocket.c` and `modtls_mbedtls.c`.

**Comment by dpgeorge** [comment]
Merged!

This actually fixed 14 cases of `STATIC inline`.

**Comment by projectgus** [comment]
Thanks @dpgeorge!

**Comment by projectgus** [comment]
Have run the reminder script, as evidenced by the many link backs above. :sweat_smile:

**Comment by dpgeorge** [comment]
> Have run the reminder script

Thanks!  Let's see how this goes...

**Comment by robert-hh** [comment]
At least that was quite a notification Tsunami.

**Pull request merged**
