### PR TITLE
docs/esp8266: Add SSD1306 to quickref

### PR DESCRIPTION
**Pull request by mcauser**
untitled-1

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks also for this.  The spelling fixes and addition of ntptime to the quickref are good.

For the SSD1306: the added text is rather long, too long for a quick reference.  I think what you've written would find a better home in the (esp8266) tutorial, which could aim to be a tutorial about general displays, but focusing on the SSD1306 to start with (but, eg, the framebuf part is general to all displays that use it).

**Comment by mcauser** [comment]
I'll split up the SSD1306 content into both a quickref and tutorial

**Comment by dpgeorge** [comment]
> I'll split up the SSD1306 content into both a quickref and tutorial

Ok, thanks!

**Comment by dpgeorge** [comment]
I merged the ntptime addition in 5a8f392f09e3826ff2a1f4330700198e9c0d42cc and the spelling fixes in a2c4cb484d6018a65dabd921c509fc12b71a088b.  I didn't merge the SSD1306 commit.

Closing PR.  Feel free to open another with the SSD1306 content as part of the tutorial.

**Pull request closed without merging**
