### PR TITLE
fix typo and add code markup

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution, it looks good.

But we usually require that contributions are made with an email address that is associated with the contributor themselves, to make it possible to contact contributors in the future if needed.  Please change the commit to use such an address if it's not already, thanks.

**Comment by thijstriemstra** [comment]
So I suppose anonymous contributions are not accepted which is worrying to me and a first. Feel free to use or close this pull request. Sad to hear such a cool project with these absurd rules.

**Comment by stinos** [comment]
But by opening a PR under your name you basically gave up anonomity already? PR history on a repo on Github isn't too different from git commit history.

**Comment by thijstriemstra** [comment]
Yes im using my own name already. Im not going to adjust my pr in order to get my email address in there, sorry.

**Comment by dpgeorge** [comment]
> I suppose anonymous contributions are not accepted

If you would like it to be an anonymous contribution then I can take the patch here and apply it under my own name.

**Comment by dpgeorge** [comment]
I applied this patch in 31cf49c672f6e141df2178e2ab0b6560244ea2e6 under my name.

We need to have traceability for each line of code, to help with licensing and copyright, and also with `git blame` to help fix potential bugs in the future.

**Comment by thijstriemstra** [comment]
So you decided not to leave a single trace of my involvment in the making of that patch. Hands down crappiest PR I have ever opened.

**Comment by rolandvs** [comment]
I think the maintainers do a beautiful job providing us access to a very nice piece of software. They are very knowledgable and responsive and this repo is very active.
It is always good that people bring in improvements, but is it really needed to make such a fuzz about this PR? Many of us involved bring in lots of improvements, ideas and bug fixing; we don't need to be credited; we help to improve the very thing we are using (and got it for free!)

**Comment by thijstriemstra** [comment]
@rolandvs I have never encountered this behaviour or rules in any open source project. Period.

**Comment by thijstriemstra** [comment]
> we don't need to be credited

Unbelievable.

**Comment by dpgeorge** [comment]
> So you decided not to leave a single trace of my involvement in the making of that patch. You could've made a reference to the author, couldn't you?

I'm sorry, but I assumed you wanted it to be fully anonymous.  I based this assumption on the following statements you made:

> So I suppose anonymous contributions are not accepted which is worrying to me and a first. Feel free to use or close this pull request.

> Yes im using my own name already. Im not going to adjust my pr in order to get my email address in there, sorry.

I then said "If you would like it to be an anonymous contribution then I can take the patch here and apply it under my own name".  It looks like you responded to this with a confused emoji, which is a bit hard to interpret.  I left it for a bit waiting for any further response, then just wanted to move forward and thought that taking the useful patch here was the right thing to do.  If I had mentioned you by name in the patch then your name would be forever in the git history which I something that I got the impression you did not want.  That would have been impossible to undo.  On the other hand, it's still possible to add credit to you if you would like (eg by another commit you make; or reverting and redoing this commit, but that's a bit drastic IMO).

> I have never encountered this behaviour or rules in any open source project.

If you have suggestions for how to improve our workflow then please do tell us.

**Pull request closed without merging**
