### PR TITLE
mimxrt/modmachine.c: Fix settings for the MIMXRT1170 board.

### PR DESCRIPTION
**Pull request by robert-hh**
These were not changed with commit c0b64a3f2 for using tools/boardgen.py.

### CODE REVIEW

**Comment by jimmo** [comment]
Thanks for this @robert-hh ! The build-all-the-boards script caught this overnight, thanks for the fix. See also https://github.com/micropython/micropython/pull/12878

**Comment by robert-hh** [comment]
@jimmo: I just noticed that with PR #12211 the option disappeared in the MIMXRT board to denote a Pin by an integer. That way is used a lot in the documentation. So either one has to be adapted.

**Comment by jimmo** [comment]
Thanks for updating the documentation @robert-hh !

**Comment by robert-hh** [comment]
Looking into the changed code it would have been complicated (or ugly) to restore the integer variant for naming a Pin. So I went for changing the documentation.

**Pull request merged**
