### PR TITLE
py/lexer: Wrap f-string arguments to format in parens.

### LINKED ISSUE #9635: f-string comma parsed differently than python3.9
A tuple without enclosing parens can be printed by f-string in Python 3.9:
```
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> f"{1,=}"
'1,=(1,)'
```

In MicroPython, it is a SyntaxError:
```
MicroPython v1.19.1-544-g89b320737-dirty on 2022-10-15; linux [GCC 10.2.1] version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> f"{1,=}"
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: invalid syntax
```

### PR DESCRIPTION
**Pull request by jimmo**
Fixes #9635 -- @jepler 

(As pointed out by @jepler, this provides a convenient workaround for the lack of `!r` for debugging, as printing a tuple of a value will implicitly cause the value to be repr'ed. But mostly fixing this for correctness as it can silently lead to the wrong results.)

+16 bytes on PYBV11.

This is important for literal tuples, e.g.

`f"{a,b,}, {c}"` --> `"{}".format((a,b), (c),)`

which would otherwise result in either a syntax error or the wrong result.

_This work was funded through GitHub Sponsors._

### CODE REVIEW

**Comment by jepler** [comment]
Thanks! We'll be happy to see this in CircuitPython as well.

**Comment by dpgeorge** [comment]
Are literal tuples really that useful in f-strings?  You'd usually pass in a variable that evaluates to a tuple, eg `f"{x}"`, rather than a literal tuple.

The concern with this patch is that it adds 2 bytes to the generated string for each argument of the f-string.  It's not that much but still something to consider.

**Comment by dpgeorge** [comment]
I tested calling `vstr_add_strn()` instead of 2x `vstr_add_byte()`, but it's larger code size.

**Comment by jepler** [comment]
Thanks!

**Pull request merged**
