### PR TITLE
ports/samd/boards/ADAFRUIT_TRINKET_M0: Update configuration to use new Port features.

### PR DESCRIPTION
**Pull request by vdbpeter**
This PR updates board specific configuration files to utilise the new Port features. Each board defines its own block device size, Pin & Led layout and UART parameters.  (The Port's README is the user's reference). 

`mpconfigboard.h`: `Flash` size & define UART.
`mpconfigboard.mk`: `LFS1`
`pins.c`: Define `Pin` & `Led` arrays.
`pins.h`: Define Structs & Consts.

### CODE REVIEW

**Review by mchobby — COMMENTED** [review]
I did already manage some pin definition on 
/micropython/ports/samd/boards/ADAFRUIT_TRINKET_M0/machine_pin.h 
and made some work on Machine.Pin & Machine.ADC class.
Could we combine the work ?
current work on Machine.Pin & Machine.ADC
https://github.com/micropython/micropython/pull/7359
initial work on machine.Pin 
https://github.com/micropython/micropython/pull/7211

Cheers

**Comment by vdbpeter** [comment]
Yes- am happy to, but want to wait until I get feedback on my current PRs from the Maintainers (and inevitable changes) before I continue. 

There are a LOT of peripherals on this MCU, so any help would be great!

Have you looked at [samd-peripherals](https://github.com/adafruit/samd-peripherals)? Scott's done phenomenal work already and obviously would like to see us tap into that. I haven't spent any decent time in it yet to see how to use it.
Cheers

**Comment by mchobby** [comment]
Hi Peter, 
Happy to meet you.
> 
> Have you looked at [samd-peripherals](https://github.com/adafruit/samd-peripherals)? Scott's done phenomenal work already and obviously would like to see us tap into that. I haven't spent any decent time in it yet to see how to use it.
> Cheers

Indeed Scott's make a great job. I do like the way of Pin definition are done. I did tried to include it into MicroPython but it immediately turn into a compile nightmare. My C skill dates from 90', it is more comfortable to turn an Arduino driver to MicroPython than making C based MCU development.
In the meantime, I did adopt your pins.c approach definition (stored in the board directory). I will soon move my ADC work under the new pin definition. after, I will start some work on PWM support.

Cheers from Belgium,
Dominique

**Comment by dpgeorge** [comment]
Merged in fb79e586362227d75069e92c9965921c13c9aacf

**Pull request closed without merging**
