### PR TITLE
 ports/mimxrt: Add initial port to NXP i.MX RT series CPUs

### PR DESCRIPTION
**Pull request by jimmo**
This is an extremely minimal port, in the style of the SAMD one, as a placeholder to hopefully get others interested in adding more functionality. It's largely based on the TinyUSB mimxrt implementation, using the NXP SDK. Currently supports the Teensy 4.0 board.

Note, if you already have the tinyusb submodule initialized recursively, you will need to run the following as the tinyusb sub-submodules have been rearranged (upstream):
```
git submodule deinit lib/tinyusb
rm -rf .git/modules/lib/tinyusb
git submodule update --init lib/tinyusb
```

This also adds the NXP SDK submodule (also from TinyUSB) to `lib/nxp_driver`

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Looks like a great start! Take a look at my PR here: https://github.com/adafruit/circuitpython/pull/2532 I started annotating variables and functions to be placed in TCM. It'd be cool to use the same annotations between CircuitPython and MicroPython. The annotations should help speed up STM32 as well.

**Comment by MaureenHelm** [comment]
Have you looked at the zephyr port? It works on a bunch of i.MX RT EVK boards (1010, 1015, 1020, 1050, 1060, 1064). I've been working on adding support for the file system in #5462.

**Comment by jimmo** [comment]
> Looks like a great start! Take a look at my PR here: [adafruit#2532](https://github.com/adafruit/circuitpython/pull/2532) I started annotating variables and functions to be placed in TCM. It'd be cool to use the same annotations between CircuitPython and MicroPython. The annotations should help speed up STM32 as well.

Thanks @tannewt -- Yes definitely keen to investigate TCM (especially on the STM32, although I understand it's slightly more limited there).

Just a note on your macro names (`PLACE_IN_?TCM(_DATA|_BSS)?`), I'd prefer something that describes the purpose of using the macro, rather than specifically naming it TCM (which is an ARM thing). Also `MP_` prefix seems consistent.

I noticed in #5318 (not yet merged) that @dpgeorge introduced `MP_FASTCODE` for this purpose. So maybe `MP_FASTCODE`, `MP_FASTDATA`, `MP_FASTBSS` ?

Something else to consider (in the future) would be how to support varying amounts of ITCM -- perhaps two or three levels.

> Have you looked at the zephyr port? It works on a bunch of i.MX RT EVK boards (1010, 1015, 1020, 1050, 1060, 1064). I've been working on adding support for the file system in #5462.

Yes, briefly (along with TinyUSB, CircuitPython, and the Teensyduino core). Was there anything in particular you wanted to bring attention to in the Zephyr port? (Or possibly that using Zephyr might be a better option for supporting these boards...which I do agree to some extent, although there is still a lot of interest in bare-metal ports. I think it's really great to support both options).

My main goal in this PR was to do the minimum possible bare-metal port as a starting point for future development, and TinyUSB gave me a great start.

I have a 1011 EVK board which I will add support for soon.

**Comment by tannewt** [comment]
> Have you looked at the zephyr port? It works on a bunch of i.MX RT EVK boards (1010, 1015, 1020, 1050, 1060, 1064). I've been working on adding support for the file system in #5462.

I haven't. Generally HALs don't work for us because they expect pin mappings to occur at compile time when we do them at runtime. I'd love to learn more about the Zephyr and MicroPython integration though. We feel like we'll need it at some point for doing concurrency well. It'd also be great to be using an open source BLE stack rather than the Nordic SoftDevice like we are now in CircuitPython. (MicroPython is using NimBLE which is another option.)

**Comment by tannewt** [comment]
> > Looks like a great start! Take a look at my PR here: [adafruit#2532](https://github.com/adafruit/circuitpython/pull/2532) I started annotating variables and functions to be placed in TCM. It'd be cool to use the same annotations between CircuitPython and MicroPython. The annotations should help speed up STM32 as well.
> 
> Thanks @tannewt -- Yes definitely keen to investigate TCM (especially on the STM32, although I understand it's slightly more limited there).
> 
> Just a note on your macro names (`PLACE_IN_?TCM(_DATA|_BSS)?`), I'd prefer something that describes the purpose of using the macro, rather than specifically naming it TCM (which is an ARM thing). Also `MP_` prefix seems consistent.
> 
> I noticed in #5318 (not yet merged) that @dpgeorge introduced `MP_FASTCODE` for this purpose. So maybe `MP_FASTCODE`, `MP_FASTDATA`, `MP_FASTBSS` ?
> 

I'm definitely not wedded to the names but I think it is important to tie it to the names used in the linker script. Feel free to comment on my PR with name suggestions. I may merge it tomorrow and can follow up after too.

The other dimension I'd like to capture is whether data needs DMA access or not. I know it is a common restriction for core coupled memory.

I was a bit bummed to see that the section attribute overwrites the whole section name rather than just adding a bit like `hot` and `cold` attributes do. I'm tempted to propose something along those lines to gcc. :-)

> Something else to consider (in the future) would be how to support varying amounts of ITCM -- perhaps two or three levels. (Edit to clarify: i.e. `MP_FASTCODE` would be the core set of most important functions, and maybe `MP_FASTCODE_IF_AVAILABLE` (but not named that!) if more space is available).
> 

Ya, I've thought about this a bit. My hope was to fit most of the VM in 32k and then just have a 256k tier which is all of the C code. I don't really like to spend memory on code that may not be used at all such as hardware APIs that a main.py doesn't use.

I'd also love to get the trace output going so that it is easier to analyze which bits are used most often. Not sure when that will happen though. :-)

**Comment by MaureenHelm** [comment]
> Was there anything in particular you wanted to bring attention to in the Zephyr port? 

Just wanted to raise awareness that it's there and supports [>200 boards](https://docs.zephyrproject.org/latest/boards/index.html) upstream, so a new bare metal port might not be necessary in a lot of cases including i.MX RT10xx EVKs. @pfalcon did the original zephyr port including support for network sockets, pins, and sensors, and I've added I2C and file systems. I'd like to start adding documentation, but waiting on some feedback on my pending PRs.

**Comment by jimmo** [comment]
Updated to add a board definition for the 1010 EVK board (thanks @mattytrentini for the loaner board for testing).

This was a fairly mechanical copy from the tinyusb board definition, so we could probably just bring over all the EVK boards.

**Comment by dpgeorge** [comment]
Thanks for the work on this, great to see this MCU series having a bare-metal port.

Merged in 6cea369b89b2223cf07ff8768e50dc39bbb770fe through 7eea0d8b6c8ac97a585ed96ead7e1ffef0687c63 with some minor changes (code formatting, and to build with latest master).

**Pull request closed without merging**
