### PR TITLE
First pass at adding Sparkfun Teensy Micromod

### PR DESCRIPTION
**Pull request by KurtE**
This included first pass through the creating all of the configuration files.

I also edited a little the other two teensy boards pins.csv files
For example on T4.1 there are 4 more Analog pins.  Also added
symbolic names for Serial RX/TX pins RX1-RX8 TX1-TX8 on T4.1
T4 and Micromod only have 7...

Also updated the text for how to use teensy_loader_cli for the other
boards.  like --mcu=TEENSY41  --mcu=TEENSY_MICROMOD

Hopefully - I did not screw up too badly

### CODE REVIEW

**Comment by robert-hh** [comment]
Thanks for the effort. I'm sure you tested all the Pin alias names. As you have seen, the commit message format is wrong. A suitable commit message could be for instance `mimxrt: Add the Sparkfun Teensy Micromod board.` with the colon and the full stop at the end.

Since the Sparkfun Micromod breaks out all GPIO pins, the UART, SPI and I2C settings in mpconfigboard.h can be extended as well and rearranged to provide access to all devices. That requires more testing.

The change to the teensy_loader_cli command looks not right to me, even it works. The MCU of all Teensy 4.x boards is the i.MX RT 1062, which matches the --mcu=imxrt1062 option about the MCU. And so this single option works for all three Teensy boards, and there is not need to complicate or change the deploy instruction.

You may also split the changes for Teensy 4.0 and Teensy4.1 off into a separate PR.

You have as well to make a separate PR for the picture of the board in the micropython-media repository at https://github.com/micropython/micropython-media Take care that the Board name and file name match the settings of the json file.

**Comment by KurtE** [comment]
> Thanks for the effort. I'm sure you tested all the Pin alias names. As you have seen, the commit message format is wrong. A suitable commit message could be for instance `mimxrt: Add the Sparkfun Teensy Micromod board.` with the colon and the full stop at the end.
> 

Sorry all different projects all with different conventions.  Will try to do better next time. 

> Since the Sparkfun Micromod breaks out all GPIO pins, the UART, SPI and I2C settings in mpconfigboard.h can be extended as well and rearranged to provide access to all devices. That requires more testing.
> 

I did update the mpconfigboard to match the Micromod.  For example under Arduino Serial2 and Serial4 are logically swapped which LPUART as to better match the pins of the MicroMod, so that was swapped in the UART table.  Like the T4 it has 7 Uarts, not 8 like the T4.1

Likewise for I2C, Wire1 and Wire2 are swapped. 

> The change to the teensy_loader_cli command looks not right to me, even it works. The MCU of all Teensy 4.x boards is the i.MX RT 1062, which matches the --mcu=imxrt1062 option about the MCU. And so this single option works for all three Teensy boards, and there is not need to complicate or change the deploy instruction.
> 

I am assuming you are trying to use the standard program from: 
https://github.com/PaulStoffregen/teensy_loader_cli
If so the option:  --mcu=imxrt1062  only works for T4.
From that web page:
```
--mcu=<MCU> : Specify Processor. You must specify the target processor. This syntax is the same as used by gcc, which makes integrating with your Makefile easier, we also now support passing in a logical name. Valid options are:
--mcu=TEENSY2           Teensy 2.0
--mcu=TEENSY2PP         Teensy++ 2.0
--mcu=TEENSYLC          Teensy LC
--mcu=TEENSY30          Teensy 3.0
--mcu=TEENSY31          Teensy 3.1
--mcu=TEENSY32          Teensy 3.2
--mcu=TEENSY35          Teensy 3.5
--mcu=TEENSY36          Teensy 3.6
--mcu=TEENSY40          Teensy 4.0
--mcu=TEENSY41          Teensy 4.1
--mcu=TEENSY_MICROMOD   MicroMod Teensy
--mcu=imxrt1062         Teensy 4.0
--mcu=mk66fx1m0         Teensy 3.6
--mcu=mk64fx512         Teensy 3.5
--mcu=mk20dx256         Teensy 3.2 & 3.1
--mcu=mk20dx128         Teensy 3.0
--mcu=mkl26z64          Teensy LC
--mcu=at90usb1286       Teensy++ 2.0
--mcu=atmega32u4        Teensy 2.0
--mcu=at90usb646        Teensy++ 1.0
--mcu=at90usb162        Teensy 1.0
```
The mcu argument not only tells what the processor it is, but it also tells it things like, how big the flash is.
The T4, T4.1 and now Micromod are the only ones shipped by PJRC that used same processor but different
other information.  Which is why the difference here.  And likewise within the main Arduino code bases where we
have to when necessary detect by which board:  Like in HardwareSerial2.cpp:
```
#ifndef ARDUINO_TEENSY_MICROMOD
static HardwareSerial::hardware_t UART4_Hardware = {
...
#else  // Teensy Micromod
static HardwareSerial::hardware_t UART3_Hardware = {
...
#endif
```

> You may also split the changes for Teensy 4.0 and Teensy4.1 off into a separate PR.
> 

Can do if needed.

> You have as well to make a separate PR for the picture of the board in the micropython-media repository at https://github.com/micropython/micropython-media Take care that the Board name and file name match the settings of the json file.

ditto

**Comment by robert-hh** [comment]
> If so the option: --mcu=imxrt1062 only works for T4.

That's not true. The option definitely --mcu=imxrt1062 works for both T4.0 and T4.1. I use it pretty regularly for both chips. The differences between boards are in the respective mpconfigboard.* files.

> Likewise for I2C, Wire1 and Wire2 are swapped.

What do you mean with Wire1 and Wire2 swapped?

About UART/I2C/SPI numbering: For the Teensy board they are arranged such that the meet the PJRC pinout sheet. If Sparkfun has a similar labeling on the board, the device numbers should match that.

**Comment by KurtE** [comment]
> > If so the option: --mcu=imxrt1062 only works for T4.
> 
> That's not true. The option definitely --mcu=imxrt1062 works for both T4.0 and T4.1. I use it pretty regularly for both chips. The differences between boards are in the respective mpconfigboard.* files.

Again assuming Pauls program is used.  I am surprised if it does not fail in T4.1, but my guess is it may not support the full 
size of the Flash (8mb), and if so probably likewise on MMOD(16mb).

Yes the mpconfig files appear to be setup to handle the generation of the hex files hopefully for the right sizes.  I did set it to the 16mb in the new one. 

Secondary note: You can not currently generate a build to be able to be saved on a new board which has been locked by the user.  That is if you purchase a board that is setup to be lockable, and you have programmed it with your key and said to lock the board to only allow it to be programmed by you, then your builds do not generate the encrypted .ehex files needed to be passed through to the tools or the teensy program.

> What do you mean with Wire1 and Wire2 swapped?
> 
> About UART/I2C/SPI numbering: For the Teensy board they are arranged such that the meet the PJRC pinout sheet. If Sparkfun has a similar labeling on the board, the device numbers should match that.
```
#if defined(ARDUINO_TEENSY_MICROMOD)
	TwoWire Wire2(&IMXRT_LPI2C3, TwoWire::i2c3_hardware);
	TwoWire Wire1(&IMXRT_LPI2C4, TwoWire::i2c4_hardware);
#else
	TwoWire Wire1(&IMXRT_LPI2C3, TwoWire::i2c3_hardware);
	TwoWire Wire2(&IMXRT_LPI2C4, TwoWire::i2c4_hardware);
#endif
```
So in mpconfigboard.h I have:
```
// Wire Wire1/Wire2 are swapped on MMOD vs T4.1...
#define MICROPY_HW_I2C_INDEX   { 1, 4, 3 }
```
Where T4 and T4.1 have:
```
#define MICROPY_HW_I2C_INDEX   { 1, 3, 4 }
```

**Comment by robert-hh** [comment]
The space reserved for the MicroPython firmware is 1 MB. That fits for all boards. The remainder of the flash will be used by the file system, which is maintained by the firmware, not by the teensy loader. We have also a PR open for  a bootloader built into the firmware, which works the same for all mimxrt boards. Then one will need the Teensy loader only for the first set-up, and the file system in maintained on firmware updates.

It seems that the MicroMod board breaks our more GPIO pins that the Teensy boards. Then you could add more SPI and I2C devices, and also add the CS1 pins for the SPI devices (the 5th entry for each SPI block).

**Comment by KurtE** [comment]
> The space reserved for the MicroPython firmware is 1 MB. That fits for all boards. The remainder of the flash will be used by the file system, which is maintained by the firmware, not by the teensy loader. We have also a PR open for a bootloader built into the firmware, which works the same for all mimxrt boards. Then one will need the Teensy loader only for the first set-up, and the file system in maintained on firmware updates.
> 
You might want to look at the new page on Teensy code security, which also talks about the minimal amount of flash that will be erased:  https://www.pjrc.com/teensy/td_code_security.html

That is with current Teensyduino releases, which upgrade the boards firmware to V1.07, we have have builtin support to maintain LittleFS file system setups across being reprogrammed. 
image

> It seems that the MicroMod board breaks our more GPIO pins that the Teensy boards. Then you could add more SPI and I2C devices, and also add the CS1 pins for the SPI devices (the 5th entry for each SPI block).

MicroMod has more pins than T4 and less than T4.1,  I think it is 45, 40, 55

If you look at my last posting in the thread: https://forum.micropython.org/viewtopic.php?f=12&t=6783&p=66784#p66784
I posted a sketch that I use to test pins out.    The difficulty I find in using some of the MicroMod boards like the Teensy, 
is there is at least two different pin naming schemes, sometimes more.  Many of their breakout boards have different names for 
the same signal.  But in normal Teensy world we use names like D0-Dnn... So I tried so supply both ways, as after all they are just
used to map to the actual underlying pin. 

So my test sketch, enums through the: machine.Pins.board() list and gets each attribute and builds a list of unique pins and what logical names there are.  It then switches all of them to PULL_UP mode and then loops reading their current values and prints out any of them that change with all of their logical names... So can use jumper to GND to see which pin is which.  Also if you enter an empty line in Serial port switches to PULL-DOWN...  Also command to dump the naming table.

As I showed in that program:
```
num pin list
Physical Pins   Logical Names
GPIO_AD_B0_13    A11 D25 MM_SDA1 RX6
GPIO_AD_B0_12    A10 D24 MM_SCL1 TX6
GPIO_EMC_29      QSPI_IO3
GPIO_EMC_28      QSPI_IO2
GPIO_AD_B1_09    A9 D23 MCK MM_MCLK
GPIO_AD_B1_08    A8 D22 MM_BATT_VIN3
GPIO_SD_B0_04    D39 DAT2 MM_DAT2
GPIO_SD_B0_05    D38 DAT3 MM_CS1 MM_DAT3
GPIO_SD_B0_02    D35 DAT0 MM_CIPO1 MM_DAT0
GPIO_EMC_08      D5 MM_D1
GPIO_AD_B1_07    A2 D16 MM_RX2 RX2
GPIO_AD_B1_06    A3 D17 MM_TX2 TX2
GPIO_EMC_05      D3 MM_PWM0 WS_TX
GPIO_EMC_04      D2 MM_PWM1 SD_TX
GPIO_EMC_22      FLASH_CS
GPIO_AD_B1_02    A0 D14 MM_A0 TX3
GPIO_AD_B1_01    A4 D18 MM_SDA
GPIO_EMC_07      D33 MM_G10
GPIO_EMC_06      D4 MM_D0 SCK_TX
GPIO_B0_11       D9 MM_G7
GPIO_B0_10       D6 MM_G6
GPIO_SD_B0_03    D34 DAT1 MM_DAT1
GPIO_B1_01       D7 MM_I2S_SDO RX4
GPIO_B1_00       D8 MM_I2S_SDI SD_RX TX4
GPIO_SD_B0_01    CLK D36 MM_SCK1
GPIO_B0_12       D32 MM_G9
GPIO_SD_B0_00    CMD D37 MM_COPI1
GPIO_AD_B1_00    A5 D19 MM_SCL
GPIO_AD_B1_03    A1 D15 MM_A1 RX3
GPIO_EMC_24      PSRAM_CS
GPIO_EMC_25      QSPI_CLK
GPIO_AD_B0_02    D1 MM_TX TX1
GPIO_AD_B0_03    D0 MM_RX RX1
GPIO_EMC_26      QSPI_IO0
GPIO_EMC_27      QSPI_IO1
GPIO_B0_06       D42 MM_G2
GPIO_B0_07       D43 MM_G3
GPIO_B0_04       D40 MM_G0
GPIO_B0_05       D41 MM_G1
GPIO_B0_02       D11 MM_COPI
GPIO_EMC_36      D31 MM_CAN_TX
GPIO_AD_B1_14    A12 D26 MM_G8
GPIO_AD_B1_15    A13 D27 MM_G11
GPIO_EMC_31      D29 MM_I2C_INT TX7
GPIO_EMC_32      D28 MM_33V_EN RX7
GPIO_AD_B1_10    A6 D20 MM_I2S_FS TX5 WS_RX
GPIO_AD_B1_11    A7 D21 MM_I2S_CLK RX5 SCK_RX
GPIO_EMC_37      D30 MM_CAN_RX
GPIO_B0_03       D13 LED MM_SCK
GPIO_B0_08       D44 MM_G4
GPIO_B0_09       D45 MM_G5
GPIO_B0_00       D10 MM_CS
GPIO_B0_01       D12 MM_CIPO

Setting all pins to PULL up - so test by jumpering pins to GND
A Python version of the Pin High/Low test
Simple keyboard interface
        Empty line, will toggle between IO pins Pulled UP and Pulled Down
        p - print pin table out showing all pin names for pin
        . - will toggle printing progress dots on or off
LOW: D3 MM_PWM0 WS_TX
HIGH: D3 MM_PWM0 WS_TX
LOW: D45 MM_G5
HIGH: D45 MM_G5
LOW: A13 D27 MM_G11
HIGH: A13 D27 MM_G11
LOW: D1 MM_TX TX1
HIGH: D1 MM_TX TX1
LOW: A9 D23 MCK MM_MCLK
HIGH: A9 D23 MCK MM_MCLK
```

**Comment by robert-hh** [comment]
> That is with current Teensyduino releases, which upgrade the boards firmware to V1.07, we have have builtin support to maintain LittleFS file system setups across being reprogrammed.

That's interesting. Did you try if it works with the MicroPython firmware?

**Comment by KurtE** [comment]
> That's interesting. Did you try if it works with the MicroPython firmware?

I don't think so.  at least I tried:
I put a couple files on the board
```
D:\GitHub\micropython\drivers\sdcard>ampy -p com55 ls /flash
/flash/sdcard.py
/flash/sdtest.py
```
I then reprogrammed the card.  Note: I am using the Teensy app not the CLI for this.  I then tried to see what files were there.

```
D:\GitHub\micropython\drivers\sdcard>ampy -p com55 ls /flash

D:\GitHub\micropython\drivers\sdcard>
```

But I don't know your setup well enough to know if the Teensy install did something to your FS or if you have something programmed into your image that knows it is the first boot and initializes a blank FS.

**Comment by robert-hh** [comment]
So it does not look like the file system is preserved. The boot code of microypython in _boot.py tries to mount the file system. If that fails, a new empty file system is created. 
boot code: https://github.com/micropython/micropython/blob/master/ports/mimxrt/modules/_boot.py

**Comment by alphaFred** [comment]
Since we have defined our own memory layout which is valid for the whole mimxrt port board lineup we do not necessarily follow the teensy specifics. For the use with MicroPython it also does not matter in my perspective since we set up everything by ourselves.

**Comment by KurtE** [comment]
>So it does not look like the file system is preserved. The boot code of microypython in _boot.py tries to mount the file system. If that fails, a new empty file system is created.
boot code: https://github.com/micropython/micropython/blob/master/ports/mimxrt/modules/_boot.py

Thanks for the link to where the _boot.py is.  I sort of skipped over it a few times in the source tree without really 
seeing it. 

> Since we have defined our own memory layout which is valid for the whole mimxrt port board lineup we do not necessarily follow the teensy specifics. For the use with MicroPython it also does not matter in my perspective since we set up everything by ourselves.

I guess a real question to you, who work on and use MicroPython to decide, is how do you want your system to work.

For example:  if the whole thing controlling where the file system is stored is controlled by the _boot.py statements like:
```
   vfs = os.VfsLfs2(bdev, progsize=256)
```
And if changing the 256 to maybe 512 might allow the file system to be maintained, is it worth it? 

Can I do this on a board by board basis?   The esp8266 port makes it appear like that is possible?  Or at least there is a _boot.py in the modules folder, but there is also one under the boards/GENERIC_512K as well. 

Again this is something that you are in control of on your platform.

What I have to decide is how much work is this worth to me?  I personally would rather program the Teensy using Arduino code base in C or C++, but I do understand, that there are others w>So it does not look like the file system is preserved. The boot code of microypython in _boot.py tries to mount the file system. If that fails, a new empty file system is created.
boot code: https://github.com/micropython/micropython/blob/master/ports/mimxrt/modules/_boot.py

Thanks for the link to where the _boot.py is.  I sort of skipped over it a few times in the source tree without really 
seeing it. 

> Since we have defined our own memory layout which is valid for the whole mimxrt port board lineup we do not necessarily follow the teensy specifics. For the use with MicroPython it also does not matter in my perspective since we set up everything by ourselves.

I guess a real question to you, who work on and use MicroPython to decide, is how do you want your system to work.

For example:  if the whole thing controlling where the file system is stored is controlled by the _boot.py statements like:
```
   vfs = os.VfsLfs2(bdev, progsize=256)
```
And if changing the 256 to maybe 512 might allow the file system to be maintained, is it worth it? 

Can I do this on a board by board basis?   The esp8266 port makes it appear like that is possible?  Or at least there is a _boot.py in the modules folder, but there is also one under the boards/GENERIC_512K as well. 

Again this is something that you are in control of on your platform.

What I have to decide for myself, is how far do I want to take it?

**Comment by alphaFred** [comment]
The location of the flash file system is controlled via the Linker Script. The flash driver is configured in such a way that a user can only access this particular flash area in the first place. The flash driver knows via the Linker Script the actual physical location of the flash file system and it's size. 

If you perform any file system operations they are calling down to the flash driver. For any layer above the flash driver the file system has essentially virtual addresses starting at address zero which is translated by the driver. 

Therefore you can not erase the MicroPython firmware via the flash driver API for instance. 

Using my bootloader, the file system is retained since it is aware of our flash layout and would only erase the area for the firmware.

**Comment by alphaFred** [comment]
In the example call you see the `bdev` object. That is the block device which our flash driver provides to you. 

```
from machine import Pin

bdev = mimxrt.Flash()
```

**Comment by KurtE** [comment]
As I mentioned in the previous comments, the current version of the Teensy firmware chip is such that it preserves the majority of the FLASH, which allows something like a filesystem to survive through being reprogrammed.  For example with Arduino, code right now, I can do something like:
```
#include <LittleFS.h>

LittleFS_Program myfs;
...
void setup()
{

  // Open serial communications and wait for port to open:
  Serial.begin(115200);
  while (!Serial) {
    // wait for serial port to connect.
  }
  if (!myfs.begin(15*1024*1024)) {
    Serial.printf("Error starting %s\n", "PROGRAM FLASH DISK");
    while (1) {
      // Error, so don't do anything more - stay stuck here
    }
  }
  Serial.println("LittleFS initialized.");
...
```
And on Micromod have 15MB littleFS drive using flash memory that survives through programming  cycles.

But it is totally up to you to decide if you will take advantage of this or not. 

Not sure what more I should do here.

**Comment by alphaFred** [comment]
No worries. Thanks a lot for pointing that out. I just wanted to shed some light on the implementation. 

It is a good thing that Paul does now support such a feature. If we can use it we have to analyse. It probably requires to do some extra things for teensy again. I guess I understand why Paul is doing his design in that way but I am no fan of it. 

For the time being there are two options if you update the firmware frequently. Either set up the file system every time or use my bootloader. However updating the firmware is something that happens not too often in my perspective.

**Comment by robert-hh** [comment]
> I guess a real question to you, who work on and use MicroPython to decide, is how do you want your system to work.

The Final decision about MicroPython is by Damien George. There are a few groups of people who develop MCU specific ports, like @alphafred, @miketeachman and me for the MIMXRT MCU family. But we have to stay compatible with the other ports. So not every feature variant, that is supported will be implemented.

> And if changing the 256 to maybe 512 might allow the file system to be maintained, is it worth it?

If a certain features requires a per-board-setting, it will be configured as such. E.g. the starting point for python code embedded into the firmware is boards/manifest.py. There, the first line is `freeze("$(PORT_DIR)/modules")`. That could be changed to check for  a board specific modules directory instead, if required. But, for the bootloader this is most likely not the reason. The files system should look for the PJRC bootloader just like an opaque blob of data. Especially since it does not have to be a LFS system. It could be FAT as well.

> As I mentioned in the previous comments, the current version of the Teensy firmware chip is such that it preserves the majority of the FLASH, which allows something like a filesystem to survive through being reprogrammed. 

I loaded a Teensy 4.0 with the 1.07 firmware, and it does NOT preserve the file system. Instead it fails in a first attempt to upload the firmware. A second attempt works. I assume that the loader expects a certain firmware header structure, which is not present. Since you seem to know a lot about these PJRC/Teensy internals, do you know by chance the structure of this header?

**Comment by KurtE** [comment]
> I loaded a Teensy 4.0 with the 1.07 firmware, and it does NOT preserve the file system. Instead it fails in a first attempt to upload the firmware. A second attempt works. I assume that the loader expects a certain firmware header structure, which is not present. Since you seem to know a lot about these PJRC/Teensy internals, do you know by chance the structure of this header?

Not much.  Paul has done all of this work himself.  I have done some PR's to the cli.   

The format of the file is standard Intel Hex file.  Been awhile since I parsed the file.   I am not sure what verification happen during this phase.  Other than maybe if you specify a hex file who contains addresses that don't make sense for the hardware specified it will error out. 

As for preserving LittleFS,  others have done more work on this part.   Probably similar to what your FS code might do which checks some settings and if things smell right... 

Sorry again this part of the code I have not touched much.

**Comment by robert-hh** [comment]
Thanks. I'm pretty familiar to the Intel Hex format. Parsing the file and looking in to the IVT header shows, that the IVT header created by a Teensyduino sample code differs slightly from the NXP documentation, in that the header version is set to 0x43 instead of 0x40 or 0x41, as stated in the Reference Manual.
So I will ask Paul about it.

**Pull request closed without merging**
