### PR TITLE
WIP: feat(esp32): Link esp32.extram.bss.ld if place bss into spiram

### PR DESCRIPTION
**Pull request by xcguang**
The changes only work for `esp32` port `GENERIC_SPIRAM` board
- We'd better enable `CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY` by default, otherwise the others don't know how to enable it unless he is very skilled in `esp-idf`
- Link `esp32.extram.bss.ld` if enable `CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY`
- The `EXT_RAM_ATTR` attribute can be used if you want to place the variable into psram.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.

> The changes only work for esp32 port GENERIC_SPIRAM board

Actually they would affect all SPIRAM boards, eg also TINYPICO.

> We'd better enable `CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY` by default, otherwise the others don't know how to enable it unless he is very skilled in `esp-idf`

Instead of enabling it we could just set it to "n" and leave a comment in the file that it can be set to "y" to use the feature.

-----

But I'm not sure this will work because when SPIRAM is enabled, MicroPython takes all of the memory for the heap (see `mp_task`).  Thus it would clash with any bss that was put there.

**Comment by xcguang** [comment]
Yes, It can be set `n` by default.
I didn't tested it, because I have no board with spiram, so I add `WIP` prefix,  which means "Work In Progress", after I confirm it works well, I will remove `WIP`(I commit it since my local project is unsafe, I don't know how to submit code in the micropython project yet, maybe my practice is out of rule).

**Comment by dpgeorge** [comment]
> after I confirm it works well

Ok, no problem.  Just post comments when you make progress.

**Comment by dpgeorge** [comment]
This would need to be redone on the new CMake build system now used for esp32 (and might not be needed anymore).

**Pull request closed without merging**
