### PR TITLE
Nrf sd 6.1.1

### PR DESCRIPTION
**Pull request by glennrub**

### CODE REVIEW

**Comment by dpgeorge** [comment]
Is it worth retaining support for older soft devices?  Or at least just retain the "download" shell function and linker script?  Then users can still easily use the old soft device if for some reason they need to (by specifying an older `SOFTDEV_VERSION`).  The default `SOFTDEV_VERSION` can still be updated, and download-all can be updated to just download the latest.

**Comment by glennrub** [comment]
> Is it worth retaining support for older soft devices?

Thanks @dpgeorge for your comment.

Personally i would recommend to stay on only one version of each SoftDevice series to ease maintenance.

Actually i faced this issue a bit earlier, maintaining multiple variations of the SoftDevice of one series. It became a maintenance hassle after a while. At one point it was support for SD s132 v.2.0.1, v3.0.0 and v5.0.0 at the same time, and the code became hard to write and debug, example in link:
https://github.com/tralamazza/micropython/blob/before_nrfx_hal/ports/nrf/drivers/bluetooth/ble_drv.c#L197-#L203 

The luck with v6.0.0 and 6.1.1 is API compatible as far as i can see. So this time it would not be an issue. In general i am not too keen on keeping several versions of the same BLE stack as all feature variations and exceptions of each individual stack needs to be fresh in mind when wrapping for micropython / bug fixing. It might also be that newer SoftDevices provides new features that old does not, making the exposure to micropython even different between SD version on the same hardware target.

Keeping the download script could work out, but might have limited value. If there is a minor/major update of the SD in the future that triggers the wrappers to use a new API it will not compile for legacy SD versions anymore. Making the download kind of useless. Unless we keep the wrapper code backwards compatible. I'm not sure what is best here. :)

**Comment by dpgeorge** [comment]
> Personally i would recommend to stay on only one version of each SoftDevice series to ease maintenance.

Ok, sounds good to me.  In that case this PR looks good to go in.

**Comment by glennrub** [comment]
Great! Merged in 696549d2e5cfbd2621bbe037af53e97af96b29c2.

**Pull request closed without merging**
