### PR TITLE
py: Fix access of locals/globals within a thread.

### LINKED ISSUE #2916: NameError: name 'i' is not defined when using threads
Hi,

I am playing around with the _thread module. I am having the problem that some variables are suddenly vanishing.
```python
import _thread
import utime

i=0
def run():
    global i
    while True:
        i = (i + 1) % 100
    print("terminating")

def start():
    _thread.start_new_thread(run, ())
    print("sleeping")
    utime.sleep(3)
    print("wakeup")
```
When I run this I get:
```python
>>> bug.start()
sleeping
wakeup
>>> Unhandled exception in thread started by <function run at 0x3ffe2740>
Traceback (most recent call last):
  File "bug.py", line 8, in run
NameError: name 'i' is not defined
```
Is this expected? Seems surprising to me.

I am using micropython 1.8.7 on the wipy 2.0.

### PR DESCRIPTION
**Pull request by dpgeorge**
Should fix #2916.

### CODE REVIEW

**Comment by dpgeorge** [comment]
This fix should be correct and doesn't impact ports that don't have threading enabled.

@danicampora please test and let me know how it goes.

**Comment by danicampora** [comment]
@awesome, I'll test it in a few minutes :-)

**Comment by danicampora** [comment]
@dpgeorge I've ran several tests including my example and @crasu's, it seems solved :-). Thank you!

**Comment by crasu** [comment]
Works thank you very much!

**Comment by dpgeorge** [comment]
Ok, this is now merged.  uPy handles the locals dict differently to CPy but this patch seems to be the correct way to make threading work correctly.

**Pull request merged**
