### PR TITLE
rp2/boards: Add PIMORONI_PICOSYSTEM.

### PR DESCRIPTION
**Pull request by Gadgetoid**
Add PIMORONI_PICOSYSTEM board.

* Provide picosystem_framebuffer root pointer
* Configure flash size

Our "picosystem" module currently lives in https://github.com/pimoroni/picosystem

### CODE REVIEW

**Comment by dpgeorge** [comment]
Can you please add a `board.json` file?

**Comment by Gadgetoid** [comment]
Ooh, that's new! I'll look into it.

We're currently using a very heavily modified downstream for PicoSystem, so I'm not sure how useful this is at the moment- still a step in the right direction I suppose!

**Comment by dpgeorge** [comment]
> We're currently using a very heavily modified downstream for PicoSystem

Yes I saw that.  A good goal for this repo here (the MicroPython project in general) is to facilitate modifications like that that are mainly bundling in drivers and libraries.  It would be great if we could offer the base firmware image here, and all you need to do is literally append your custom modules.

> I'm not sure how useful this is at the moment

A simple board.json is all that is needed, so it appears on the download page.  You can link to your custom firmware if you like.

**Comment by jimmo** [comment]
@Gadgetoid I think it probably makes sense to not include this board here, because the PicoSystem is quite dependent on your custom firmware. It will be confusing if there are two "official" firmwares for this board, and clearly the Pimoroni one is likely the one that people want.

Feel free to re-open though (with a board.json, and a pins.csv after [#9731](https://github.com/micropython/micropython/pull/9731) is merged).

**Comment by mattytrentini** [comment]
For what it's worth, I have a PicoSystem and am _much_ more interested in a mainline build than the custom Pimoroni firmware. I conceded that I'm probably not a typical case. 😜

**Pull request closed without merging**
