### PR TITLE
machine_bitstream: Implement for rp2 and unify all variants.

### PR DESCRIPTION
**Pull request by robert-hh**
Like the variant for esp32 and mimxrt it is implemented by active polling the systick counter. The rp2 systick counter seemed to be unused before. Since it is a 24 bit counter, the longest bit pulse pair must not exceed ~67ms at 125MHz or ~34ms at 250MHz. For speed, the code uses direct register access. The timing is precise within +/- 20ns at 125 Mhz clock.

I did not find a way to implement it efficiently using the PIO. The PIO has not sufficient scratch memory registers to store the four bit times.

### CODE REVIEW

**Comment by dpgeorge** [comment]
It would be nice to combine all these bitstream implementations to reduce code duplication.  But maybe do that as a refactoring exercise once they are all implemented?

**Comment by jimmo** [comment]
Thanks @robert-hh !

On rp2 should we could consider freezing the neopixel.py module?

> I did find a way to implement it efficiently using the PIO. The PIO has not sufficient scratch memory registers to store the four bit times.

Not sure I follow -- there's examples/rp2/pio_ws2812.py that does this. Or is the issue that the timing needs to be hardcoded, so a PIO implementation cannot handle arbitrary bit widths?

**Comment by robert-hh** [comment]
@dpgeorge: These implementations are short and very hardware dependent. For instance, esp32 and mimxrt use a 32bit increasing counter, rp2 a 24 bit decreasing one; and all mechanisms are different. Combining these would not reduce the variation. So either you would move the hardware-related code into other files (like mphalport.*),  or you would have #ifdef sections with all variants in the same file, which does not improve readability.
@jimmo : Of course I know the pio_ws2812 example. But that implements a hard-coded timing just for that device. Bitstream uses a configurable timing. A good PIO implementation should only require, that after a set-up only the bit data stream is fed into the state machine as sequence of bytes and no interim data buffer has to be allocated. But for that the four timing values would have to be stored in the state machine. And that's not possible. Only two values can be permanently stored. OSR would be needed for receiving the data, and another register for counting the time ticks.

**Comment by robert-hh** [comment]
The most recent attempt generalizes the hardware related calls, but one problem exists, of how to tell the compiler/linker to move that code into RAM. When executed from flash, the timing is not good. The first bit(s) timing is wrong.

**Comment by dpgeorge** [comment]
Try looking at the `EXCLUDE_FILE` part of `memmap_mp.ld`.

**Comment by robert-hh** [comment]
So that works fine for the ARM based devices. Where is it  defined for the ESP32?

**Comment by dpgeorge** [comment]
> Where is it defined for the ESP32?

I'm not sure.

But, I'm happy for this PR to be merged as-is, ie without generalising it.  We can refactor later on if it makes sense/is possible.

**Comment by robert-hh** [comment]
I have a version now which is identical for mimxrt and rp2. That includes changes to the mimxrt files and the rp2 files, both c and .ld files. I can push that, or keep it aside.

**Comment by hoihu** [comment]
> On rp2 should we could consider freezing the neopixel.py module?

IMO a good addition, especially when looking at the quickref doc:
https://docs.micropython.org/en/latest/rp2/quickref.html#neopixel-and-apa106-driver

I believe the user expects to have the neopixel module present when flashing the device...

**Comment by robert-hh** [comment]
The not-yet-pushed esp32 variant is now also identical to rp2 and mimxrt, besides the instruction for the linker to move the code to RAM. I found information and examples how to do that, but I expect a little bit of exercise until it works. Then the function could be moved to a common place and the code in the respective mphalport.h files can be cleaned if required. What name should it have, if moved to extmod? machine_bitstream_high_low.c?

**Comment by robert-hh** [comment]
The linking challenge for ESP32 is solved. Now machine_bitstream is identical for ESP32, rp2 and mimxrt.

**Comment by robert-hh** [comment]
With the most recent commit, all of stm32, esp32, esp8266, rp2 and mimxrt use the same implementation of machine_bitstream.c, located in drivers/bitstream. Except for the esp8266, the timing is pretty good. The ESP8266 is somewhat asymmetric, possibly requiring separate compensation for the high and low pulse.

**Comment by dpgeorge** [comment]
Thanks for the effort to unify the variants.

Please note that @jimmo spent a lot of time tuning the stm32 code, in particular the Cortex-M0 version with hand-tuned assembly.  Both versions for stm32 should remain unchanged after any code factoring (ie the generated machine code should be the same before and after refactoring).

Also, I think the common source code should be `extmod/machine_bitstream.c`, to live alongside `extmod/machine_pulse.c` etc.

**Comment by robert-hh** [comment]
I have seen this STM32 code, a very pretty one with precise timing. It is removed for now, but I can put that back for STM32. STM32 would then use it's specific code. That would allow me to roll back a change that was made for STM32 only.
extmod/machine_bitstream exists already. That is the Python API module. Therefore I went for placing it into drivers/bitstream, assuming that there may drivers for other coding than just high/low sequences.

**Comment by robert-hh** [comment]
I looked again into @Jimmo's  code. The non-Cortex M0 version is identical to the one I have as common version. Only instead of direct register access the common code has function calls, which in turn are defined as inline ode #defines in the port specific mphalport.h, turning into direct register access again. Wouldn't the cortex M0 also also apply to the RP2? I have to check. For RP2, I use at the moment the systick counter.

**Comment by robert-hh** [comment]
So this includes now the assembler version of @jimmo for STM32 Cortex-M0. Basically the common code is still the STM32 driver with stubs for Macros from mphalport.h instead of direct calls.  Obviously the difference between the versions did not disappear. It just moved from the driver to mphalport.h. The donwside of unification is, that port-specific timing optimization is reduced.

**Comment by robert-hh** [comment]
I close that one for now. Reasons:

- the new esp32 PR for bitstream works better than the old polling based.
- the port-specific implementations have a more precise timing than the generalized one. That holds especially for the STM variant.

I will roll it back to the rp2-only implementation and make a PR for that later.

**Comment by dpgeorge** [comment]
> I will roll it back to the rp2-only implementation and make a PR for that later.

Ok, sounds good.

**Pull request closed without merging**
