### PR TITLE
py: Allow keyword arguments for namedtuple

### PR DESCRIPTION
**Pull request by stinos**

### CODE REVIEW

**Comment by stinos** [comment]
> Is this ready to go?

not sure if this was addressed to me, but if so: yes as far as I'm concerned this is ready/up for review

**Comment by pfalcon** [comment]
> not sure if this was addressed to me

I guess it was, or at least, there's an issue that github doesn't send a notification when pull request is updated with new content - only when a comment is posted. So, it's easy to miss PR and having an explicit comment that PR was updated is helpful.

Looks great, thanks for these refactors, merged!

**Comment by pfalcon** [comment]
But with this patch applied, following now fails on x86 (32bit):

~~~~
micropython: ../py/objtype.c:130: mp_obj_class_lookup: Assertion `(MP_OBJ_IS_OBJ(type->locals_dict) && (((mp_obj_base_t*)(type->locals_dict))->type == (&mp_type_dict)))' failed.
FAIL  basics/class_store_class.py
~~~~

It doesn't fail on x64.

**Comment by pfalcon** [comment]
~~~~
-    mp_obj_namedtuple_type_t *o = m_new0(mp_obj_namedtuple_type_t, 1);
+    mp_obj_namedtuple_type_t *o = m_new_obj_var(mp_obj_namedtuple_type_t, mp_obj_t, n_fields);
~~~~

Note the previously used m_new**0**.

**Comment by pfalcon** [comment]
Fixed in 276159e5ddedfdb863bf34e4ae25c58621af5750.

**Comment by stinos** [comment]
Thanks, I didn't test all possible builds. You think it's worth adding a unix build with MICROPY_FORCE_32BIT=1 for Travis?

**Comment by pfalcon** [comment]
Dunno, maybe, it was pretty random that I checked that config too...

**Comment by dpgeorge** [comment]
@stinos @pfalcon thanks guys, this is a very neat change, and is surely faster when constructing and accessing named tuples.

In 7f23384d4920f7d1a4ea743a51a2d54fd0889e72 and 84e0cf0d215d1248a6f2c4dc977c5702f317fe06 I made some changes to the error handling so that all-in-all this change increases code size by only 16 bytes on both unix x64 and stmhal.

**Pull request closed without merging**
