### PR TITLE
Extend bluetooth API

### PR DESCRIPTION
**Pull request by agners**
Add API to discover services/characteristics by UUID. This is useful if only a specific services/characteristics is required as it simplifies code in those cases. It also allows to sidestep a problem currently seen with ESP32 where scanning for characteristics while service scanning is still active leads to a crash (#5686). Unfortunately it is no possible to tell when scanning finished. Just scanning for a single UUID and scanning for a single characteristics allows to sidestep this problem easily.

Using the UUID specific API's has been suggested by ESP IDF developers: https://github.com/espressif/esp-idf/issues/4913#issuecomment-617755796

### CODE REVIEW

**Comment by agners** [comment]
This still needs documentation update and fixing in btstack, but I before tackling this I wanted to gauge general opinion on this API extension.

**Comment by dpgeorge** [comment]
Does this add functionality that is not already available in some other way?  The idea with the `bluetooth` module is that it's very raw and minimal, and there shouldn't be more than one way to do something.

**Comment by agners** [comment]
@dpgeorge because it scans for a single UUID only, the IRQ even then the UUID has been found also marks the completion of the scan, which allows to immediately continue scanning (which otherwise would lead to a crash, at least on ESP32 devices, see issue #5686).

Since currently a complete event is missing, this really is new functionality in that sense.

An alternative would be to have a completion event wired about, what pull request #5906 tries to wire up. However, scanning all services/capabilities will be slightly slower still, and will be more complex to implement for simple cases.

I think as NimBLE and btstack have a similar API on C level already, and the API is quite straight forward and reuses the completion callbacks, it is still worth considering an addition, even if we have another mechanism to get a completion even like #5906.

**Comment by dpgeorge** [comment]
> because it scans for a single UUID only, the IRQ even then the UUID has been found also marks the completion of the scan

I haven't had time to read the BT spec, but my question would be: does this scan-for-UUID get implemented in the low-level BLE stack as an optimised query between BLE devices so that less data needs to be sent over the air (ie only the requested UUID), or is it just a filtering of UUID's by the host controller?

Also, reading the BTstack API it seems that it's possible to get multiple results from such a query, and that the query for a UUID (service or char) is ended only by a `GATT_EVENT_QUERY_COMPLETE`.  If that's the case then #5906 is also needed for this scenario (I think this completion event should be added anyway).

And are there any other optimised requests like this that would need to be considered in the future?  It doesn't look like there is a "discover characteristic descriptor by UUID" so perhaps what's added in this PR is everything that remains...?

Finally, if the functionality of this PR is merged (which I would tend towards if it reduces on-air traffic), I think it could be simplified a lot (the amount of extra code) by just reusing the existing `gattc_discover_services()` and `gattc_discover_characteristics()` methods and extending them to take an optional additional argument, which if given is the UUID to scan for.

**Comment by agners** [comment]
To be honest, I am not familiar with BLE very much. This document seems to suggest that this is an native operation: https://www.oreilly.com/library/view/getting-started-with/9781491900550/ch04.html

And yes, this document also says that multiple services can have the same UUID (I guess UUID is a service "class"), hence multiple IRQs will get fired. I think you are right, only #5906 allows to properly fix this.

**Comment by jimmo** [comment]
Please see #6033 for a slightly different implementation of this for both NimBLE and btstack (with some other fixes and simplification of the event/irq numbers).

**Comment by dpgeorge** [comment]
This has been implemented in 919d640aec637004110d9f4df9814523a3bfd847

**Pull request closed without merging**
