### PR TITLE
Implement fallback for in-place special methods

### PR DESCRIPTION
**Pull request by pfalcon**
Allows to do things like obj += obj1, if only `__add__` is defined.

### CODE REVIEW

**Comment by pfalcon** [comment]
@dpgeorge , is this is so easy, why we haven't done this before? This adds 8 bytes for Thumb2 and 16 bytes for x86_64, so let's just have this in unconditionally.

**Comment by pfalcon** [comment]
(This comes from CPython's datetime module and its testsuite, which in turn comes from desire to bump micropython-lib and be able to port real-world apps to micropython).

**Comment by dpgeorge** [comment]
Yes it looks good indeed.  +1 to have it unconditional code.

Probably deserves a comment in py/runtime0.h, explaining why the ordering of the binary ops is important.

**Comment by pfalcon** [comment]
Merging, thanks.

> Probably deserves a comment in py/runtime0.h, explaining why the ordering of the binary ops is important.

I submitted https://github.com/micropython/micropython/issues/3291 on that, let's find the perfect order, and then document everything (including existing cases of order/count dependence).

**Pull request closed without merging**
