### PR TITLE
tools/verifygitlog.py: Add tool to verify git messages.

### PR DESCRIPTION
**Pull request by dpgeorge**
I use this script to verify git messages before pushing.

See further info/discussion in #6781

### CODE REVIEW

**Comment by tve** [comment]
The only comment I have is that whatever checks the commit messages either needs to auto-fix them (like the codeformat does) or it needs to explain what needs to be fixed. Users should not have to reverse-engineer scripts to figure out what the script didn't like and how it's supposed to be. I know you just posted your personal script for reference. I'm just making a general comment...

**Comment by stinos** [comment]
@tve auto-fixing the text is virtually impossible, but a short description like you mention in the other PR is the way to go.

**Comment by dpgeorge** [comment]
> needs to auto-fix them (like the codeformat does)

Yeah, I was thinking the same thing just after pushing this.  Ideally it'd be like codeformat and then you just don't need to think about how the formatting should be (especially coming from other projects, where commit msgs are different).  And having string formatting also makes it easier to auto-generate (part of) the release notes.

But to start with a message telling how to fix it (and maybe also suggested replacement text) would be good.

**Comment by dpgeorge** [comment]
An alternative script was added in d48860c7ddfb37bdc48d0f3afc3a26dcd54cca0f

**Pull request closed without merging**
