### PR TITLE
WIP extmod/moduselect: Refactor towards introduction of poll.ipoll().

### PR DESCRIPTION
**Pull request by pfalcon**
This follows previous refactor made to unix/moduselect.

### CODE REVIEW

**Comment by pfalcon** [comment]
This is just a first step, which should not bring any semantic changes.

**Comment by pfalcon** [comment]
The first commit posted so far is easier to review with whitespace changes ignored, https://github.com/micropython/micropython/pull/3026/files?w=1

**Comment by dpgeorge** [comment]
First patch looks ok.  You may want to use size_t where appropriate, instead of mp_uint_t.  Otherwise these types will be changed at a later date.

**Comment by pfalcon** [comment]
Ok, finished implementation, tested on esp8266, merged to master as 2 commits to make it easier to hunt for future bugs.

**Pull request closed without merging**
