### PR TITLE
docs: Generate separate docs build for each port.

### PR DESCRIPTION
**Pull request by danicampora**
This is my attempt to generate separate docs build for each port reusing as many of the current .rst files as possible. The libraries directory is common and things can be made specific there by using the `..only` directive. Each port has it's own `quickref,rst`, `general.rst`, `conf.py` and `topindex.html`. Everything else is shared.

To build the documentation of a given port:

``` bash
cd docs
python make-docs.py --port stmhal
```

Only stmhal and esp8266 are supported for the moment. The esp8266 needs a lot of
work, but I simply left things as they were and removed all of the
pyboard specific stuff.

Please shoot at this without mercy. Thanks ;-)

### CODE REVIEW

**Comment by dpgeorge** [comment]
There is a difference between stmhal and the pyboard.  I would say that the docs should be generated for the pyboard, not stmhal.  Eg, there are many boards supported by stmhal, but each one will have a different pinout in the quickref.

I also made an attempt at doing what you've done here, but mine is a lot simpler: I don't have a build script, and I use the same conf.py and toplevel.html for all ports.

toplevel.html is run through the Jinja 2 templating language so you have full power to customise that file per port.  The way I did it was to set some variables in conf.py (like the port name) which are available in the templated html.

To build it's just done using make:
```
make SPHINXOPTS="-t port_pyboard" BUILDDIR=build-pyboard html
```
That's easy to automate for all variations:
```
for ver in $(git tag | grep -v v1.0-rc1 | sort -V); do
    git checkout $ver
    for port in pyboard wipy esp8266; do
        make SPHINXOPTS="-t port_$port" BUILDDIR=build-$ver-$port html
    done
done
```

**Comment by danicampora** [comment]
> There is a difference between stmhal and the pyboard.

OK.

> toplevel.html is run through the Jinja 2 templating language so you have full power to customise that file per port. The way I did it was to set some variables in conf.py (like the port name) which are available in the templated html

I am new to all this sphinx stuff so I am glad to see that there are better ways to do it.

> I also made an attempt at doing what you've done here, but mine is a lot simpler: I don't have a build script, and I use the same conf.py and toplevel.html for all ports.

Can you share what you did? Then I can try it and redo this PR with your approach...Or are you planning to submit your own PR?

**Comment by dpgeorge** [comment]
> I am new to all this sphinx stuff

So am I :)

> Can you share what you did?

I didn't want to make a PR because it's still work in progress.  So here is the most important part of the diff:

```diff
diff --git a/docs/conf.py b/docs/conf.py
index 944b990..b00a8d0 100755
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -277,3 +277,19 @@ texinfo_documents = [

 # Example configuration for intersphinx: refer to the Python standard library.
 intersphinx_mapping = {'http://docs.python.org/': None}
+
+# custom
+from collections import OrderedDict
+micropy_port = os.getenv('MICROPY_PORT') or 'pyboard'
+tags.add('port_' + micropy_port)
+ports = OrderedDict((
+    ("unix", "unix"),
+    ("pyboard", "the pyboard"),
+    ("wipy", "the WiPy"),
+    ("esp8266", "esp8266"),
+))
+prefix = "http://micropython.org/resources/docs/port/"
+html_context = {
+    'port_name':ports[micropy_port],
+    'all_ports':[(n, prefix + p) for p, n in ports.items()],
+}
```

```diff
diff --git a/docs/topindex.html b/docs/topindex.html
index 9f1f8be..382354e 100644
--- a/docs/topindex.html
+++ b/docs/topindex.html
@@ -8,6 +8,19 @@
     v{{ release|e }}{% if last_updated %}, {{ _('last updated') }} {{ last_updated|e }}{% endif %}.
   </p>

+  <p>
+    MicroPython runs on a variety of systems and each has their own specific
+    documentation.  You are currently viewing the documentation for
+    <strong>{{ port_name }}</strong>.
+  </p>
+
+  <p>
+    Documentation for other systems are available:
+    {% for p in all_ports %}
+      <a href="{{ p[1] }}">{{ p[0] }}</a>{% if not loop.last %}, {% endif %}
+    {% endfor %}.
+  </p>
+
   <p><strong>Documentation for MicroPython and the pyboard:</strong></p>

   <table class="contentstable"><tr>
```

The main thing is that if you set the variable html_context to a dict in conf.py then the members of that dict are available in the html.

With the above patch to conf.py you build a different port using `make MICROPY_PORT=pyboard html`.

**Comment by danicampora** [comment]
@dpgeorge thanks!

**Comment by dpgeorge** [comment]
I have it set up now that micropython.org receives a notification from github whenever there is a push to the repo.  So this can be used to trigger a build of the docs.  We need a 3-level system for the specific docs, based on language, version and port.  The path to the docs would be something like:
```
http://docs.micropython.org/<lang>/<ver>/<port>/
```
Auto-generation would just be done by the shell loop given a few posts above.

The missing piece is having a menu system to select lang/ver/port.

**Comment by danicampora** [comment]
@dpgeorge How about now? It's using your code, plus moving the tutorials, quickref and general to the port folder (I believe all that is very port specific). Also, I changed the build folder to `port_name/build`. 

In order to build:

```bash
make MICROPY_PORT=pyboard BUILDDIR=pyboard/build html

or

make MICROPY_PORT=esp8266 BUILDDIR=esp8266/build html

...

```

Thoughts?

**Comment by danicampora** [comment]
We can add the menu feature after having documented at least one more port. I started to write stuff for the WiPy already but I'd like to have the new docs build structure in place before continuing...

**Comment by danicampora** [comment]
I think we should have a common tutorial folder and a port-specific folder. For instance `assembler.rst` can be common (for ports with the inline assembler enabled).

**Comment by dpgeorge** [comment]
> Also, I changed the build folder to port_name/build.

You never need to specify the build folder.  It's just on the command line, with default being build.  So it can be anything and the scripts and sources in the docs/ directory don't need to know what it is (or what form it takes).

> I think we should have a common tutorial folder and a port-specific folder.

Assembler will only be common to all ports with the same instruction set.  Viper on the other hand (and other uPy specifics) will be common across everything.

**Comment by danicampora** [comment]
> You never need to specify the build folder. It's just on the command line, with default being build. So it can be anything and the scripts and sources in the docs/ directory don't need to know what it is (or what form it takes).

Sorry, I didn't write it correctly. I meant to say that IMHO the build folder should be specified like `port_name/build` in the command line. I didn't add any knowledge about this in the scripts.

Regarding what you say about the assembler, you are right, so let's leave it where it is for the moment.

**Comment by dpgeorge** [comment]
Ok, I think this is good to merge.  For the time being we'll still have the original readthedocs docs, but I'll also duplicate it at micropython.org/resources/docs so we can test the new features.  Once it's working properly we can switch the url to docs.micropython.org.

**Comment by dpgeorge** [comment]
Merged in 7ca1bd314bd5e3146f8c868f91af54d17dd04d45.

**Comment by danicampora** [comment]
Thanks!

**Comment by pfalcon** [comment]
@dpgeorge : Is stuff under http://micropython.org/resources/docs/ really autogenerated ? Last docs there are from Jun 10.

Also, how someone supposed to find/reach to them? For example, once I have http://micropython.org/resources/docs/ , how can I get to actual docs? (Can you enable dir listings there /add landing page/whatever?) Thanks.

**Comment by dpgeorge** [comment]
Hah, no, that's only supposed to be testing and the update script is not running :)  Once proven and once it has enough features to be on par with current readthedocs (menu with version, language, ability to export PDF...) then I'll move it to docs.micropython.org/.  And then it'll have a landing page.

**Comment by pfalcon** [comment]
Well, that's why https://github.com/micropython/micropython/issues/876#issuecomment-115024515 talks about "mess". And scientific studies show that we have 3 layers of mess: code doesn't correspond to ideas, docs don't correspond to code, and easily browsable docs don't correspond to doc sources ;-). (Still no hurry of course, but ability to browse docs for different ports to spot commonalities and inconsistencies is quite helpful.)

**Comment by dpgeorge** [comment]
@pfalcon http://micropython.org/resources/docs/ should now be auto-re-generated on each github push.  If you go to than addr then it redirects to en/latest/pyboard.  You'll have to manually change pyboard to wipy or esp8266 to get those docs.  There is no unix version yet.

**Comment by pfalcon** [comment]
Thanks! Links are in wiki at https://github.com/micropython/micropython/wiki/Boards-Summary

**Pull request closed without merging**
