### PR TITLE
Adding extra step for building.

### PR DESCRIPTION
**Pull request by luckcfm**
I just added an extra step that I had to make to compile properly.

### CODE REVIEW

**Comment by nevercast** [comment]
There is a lot going on here, with commits going back to December. Can you please squash this PR?

**Comment by nevercast** [comment]
Also, considering the amount of changes, I feel as though the PR body is a bit brief. Can you tell us what changes you're making and perhaps why? 

It's hard to review if this PR does as intended if its intention isn't clear. 

Thank you for making this proposal.

**Comment by nevercast** [comment]
This PR tramples a bunch of files that seemingly have nothing to do with adding extra steps to building.

Please touch the least amount of files to achieve the desired outcome. As it stands, I wouldn't approve this PR.

Please feel free to make the changes and repush to your branch. We can then review the PR again.

**Comment by dpgeorge** [comment]
This looks like it was opened against the wrong repo by accident (it happens sometimes, easy to do with github).

**Comment by nevercast** [comment]
Ah. That would wake sense. Whoops.

**Pull request closed without merging**
