### PR TITLE
esp32/modules:Format the filesystem as FAT in UF2 bootloader.

### PR DESCRIPTION
**Pull request by Wind-stormger**
Format the filesystem as FAT in UF2 bootloader.

By the way, I sorted out two long strings as  variables, it looks tidy now.

### CODE REVIEW

**Comment by robert-hh** [comment]
I do not understand the intention of the change. Usually I would not expect `uos.VfsLfs2.mkfs(bdev)` to fail except if the board does not support LFS2 at all, which is not the case for ESP32.  Or if there is a hard error flash. So, formatting to FAT will almost never happen.

**Comment by Wind-stormger** [comment]
> I do not understand the intention of the change. Usually I would not expect `uos.VfsLfs2.mkfs(bdev)` to fail except if the board does not support LFS2 at all, which is not the case for ESP32. Or if there is a hard error flash. So, formatting to FAT will almost never happen.

When using UF2 bootloader, it must be FAT.
The issue has been around for about a year. #8453

**Comment by robert-hh** [comment]
I know that the drive which the .uf2 bootloader presents is a FAT drive. That makes it visible to the PC. I did not look into the ESP32 uf2 bootloader. But the other bootloaders do not need a drive on the board. Instead, they create a virtual drive and write directly to the flash. The ESP32 bootloader may work differently. 
But, the code you present will in most cases not create a FAT file system. It keeps an existing FAT filesystem, but if a new one has to be created, the first choice is LFS2. So if the board must have a FAT file system, it must be created manually.

**Comment by Wind-stormger** [comment]
So I used try except to make sure it was Lfs2 in all other cases.

**Comment by HonestQiao** [comment]
This fix can not fix my problem.
The detail explain is [https://github.com/micropython/micropython/issues/8453#issuecomment-1404600688](https://github.com/micropython/micropython/issues/8453#issuecomment-1404600688)

**Pull request closed without merging**
