### PR TITLE
extmod/modframebuf: Make FrameBuffer handle 16bit depth

### PR DESCRIPTION
**Pull request by deshipu**
While there usually is not enough memory to allocate a buffer for the
whole screen for most of the 16-bit TFT displays, it's still useful to
have a framebuffer for updating parts of the screen.

### CODE REVIEW

**Comment by dpgeorge** [comment]
It's nice that you didn't need to commit to a specific RGB encoding scheme.

You should be able to factor some of the code to be in common with the 1-bit buffer (at least the text method).  But I guess that's best left for a follow-up patch.

Did you find use for this code?  Can you give some example screens than use 16-bit colour?

**Comment by deshipu** [comment]
I couldn't find a way to avoid the code duplication, because C is a strongly typed language, so even though the code looks the same, it operates on different types. I suppose I could have some `void *` pointers in some places, and some function pointers for actually manipulating the types, but that feels like re-implementing an OO language in C.

I have a very particular use for this code. I just released a library for MicroPython that handles six different types of RGB displays (all of them use 565 16-bit color by default, although many are capable of 24bit or 18bit color too), https://bitbucket.org/thesheep/micropython-display, and now I want to write a higher-level library for it, that would allow use of tile maps and sprites. However, initial tests with Python code show that all the pixel-pushing required to implement blitting with transparency and dirty rectangles and similar things is way too slow for any animations. I'm hoping to be able to do it in C with the framebuffers.

An alternative would be to write a tiles-and-sprites engine completely in C (that would actually be easier to do), but then it could be problematic to get it merged in MicroPython itself, and at the moment there is no way to run C extensions from the filesystem.

I also plan to add more patches that add more useful methods to both framebuffer classes, so that I can write a general-purpose graphics library for drawing lines, circles, rectangles, etc. Then the 16-bit framebuffers will automatically also become more useful.

**Comment by dpgeorge** [comment]
> I couldn't find a way to avoid the code duplication, because C is a strongly typed language, so even though the code looks the same, it operates on different types.

You could pass a "set pixel" function to the text rendering routine to make it generic.

> However, initial tests with Python code show that all the pixel-pushing required to implement blitting with transparency and dirty rectangles and similar things is way too slow for any animations. I'm hoping to be able to do it in C with the framebuffers.

It looks like your driver does not use a frame buffer at the moment and just sends data directly to the display.  Since the resolution is "high" and it's colour, the framebuf is too large for RAM.  You say you can just make a small region have a buffer, but how exactly will that work with the driver... won't you anyway need to provide all methods to act on the non-buffered part as well as the buffered part of the screen?

> and at the moment there is no way to run C extensions from the filesystem.

Maybe this (dynamic native modules) is something to work on now.  At the very minimum one just needs a way to dynamically load a bare C function, one that doesn't need any data or bss, and one that doesn't need to access any of the uPy runtime functions (like memory allocation).  In that case you just get to write pure functions, but that might be enough for your case (eg copying data from one buffer to another).

**Comment by deshipu** [comment]
My idea is to use the framebuffer objects in similar way to PyGame's `Surface` objects -- as generic containers for image data. A crucial part of this is the `blit()` method (in a separate pull request), that lets you copy one framebuffer onto another. The display drivers will have the same API as the framebuffers, except that modifications are sent to the display immediately.

This way I can create a small framebuffer in memory for a dirty rectangle, blit all the tile and sprite graphics that I need, and then send it to the display as a single chunk of data (using the hardware SPI driver).

In the future I may also try to write some drivers for decoding image files (BMP for a start) and then the framebuffer would be a useful structure for storing them.

**Comment by deshipu** [comment]
One more use case is for the buffer of the framebuffer to sit on the read-only flash as a bytestring in a byte-compiled python module. Then the size restrictions are not as severe, and you could easily store a full-screen image that you can then blit to the display.

**Comment by deshipu** [comment]
>> I couldn't find a way to avoid the code duplication, because C is a strongly typed language, so even though the code looks the same, it operates on different types.

> You could pass a "set pixel" function to the text rendering routine to make it generic.

So I looked into this a little bit more, and I'm afraid I don't know C well enough to pull it off. When I'm defining a function that takes a function pointer as one of the arguments, I have to specify the signature of that function pointer -- including the type of all arguments it takes. So I can't have one function taking an array of bytes and a boolean (or unsigned char) color, and another taking an array of `uint16_t`s and a 16-bit color.

**Comment by dhylands** [comment]
The normal way to do this is that the "generic" function takes a void * which is compatible with all pointers. Then, inside the function, it would look at the type of the image/framebuffer and cast that void * input pointer into a pointer of the appropriate type.

**Comment by deshipu** [comment]
But then I would need to pass the color as a pointer?

**Comment by deshipu** [comment]
So this function:
```
STATIC inline void framebuf1_setpixel(const mp_obj_framebuf1_t *fb, int x, int y, uint8_t color) {
    size_t index = (y >> 3) * fb->stride + x;
    uint8_t offset = y & 0x07;
    fb->buf[index] = (fb->buf[index] & ~(0x01 << offset)) | (color != 0) << offset;
}
```
Would become something like:
```
STATIC inline void framebuf1_setpixel(const void *fb_in, int x, int y, void *color_in) {
    const mp_obj_framebuf1_t *fb = (const mp_obj_framebuf1_t *)fb_in;
    const uint8_t color = *(uint8_t *)color_in;
    size_t index = (y >> 3) * fb->stride + x;
    uint8_t offset = y & 0x07;
    fb->buf[index] = (fb->buf[index] & ~(0x01 << offset)) | (color != 0) << offset;
}
```

And then I would call it like this:
```
    framebuf1_setpixel((void *)self, x0, y, (void *)&col);
```

But how do I handle the return value here:

```
STATIC inline uint8_t framebuf1_getpixel(const mp_obj_framebuf1_t *fb, int x, int y) {
    return (fb->buf[(y >> 3) * fb->stride + x] >> (y & 0x07)) & 0x01;
}
```
To return a `void *` I would need to first allocate memory for the color to be returned, right?

**Comment by dhylands** [comment]
No need to cast to a void *, so you can do:
```C
framebuf1_setpixel(self, x0, y, &col);
```
For individual colors, I think that they'll all fit in a uint32_t so I would be inclined to use that for the color rather than a void * and use uint32_t as the type for col and the return type of the function. i.e. only use void * for stuff that is logically a pointer.

**Comment by deshipu** [comment]
You are right, the largest we can realistically expect is 24bit color, 32bit with alpha channel. That will work. Thank you, I will try to do it.

**Comment by deshipu** [comment]
Hmm... one more thing. I can't inline the functions then, can I?

**Comment by dhylands** [comment]
Functions that are called through a function pointer obviously can't be inlined.

If you declare a function static inline then it will emit stand-alone code, if required (i.e. if you take the address of a function). If you call a static inline function directly, then it may be inlined.

**Comment by deshipu** [comment]
I just noticed that the structs for both framebuf1 and framebuf16 are identical (they have the buffer, the width and the height) except for the type of buffer (which can be easily cast inside the setpixel/getpixel functions), so we might not even need separate structs...

**Comment by deshipu** [comment]
I rebased it on top of https://github.com/micropython/micropython/pull/2367 (to get the getpixel and setpixel functions) and refactored the whole thing to share as much code as possible between the different framebuffers.

**Comment by deshipu** [comment]
I rebased and added some tests for the 16-bit framebuffer, and they are failing at the moment. I will work on it some more. The tests for framebuffer1 seem to be passing.

**Comment by dpgeorge** [comment]
> I will work on it some more

No hurry.  I want to test this code on real hardware as well.

**Comment by deshipu** [comment]
I was testing it on real hardware so far, using this driver: https://bitbucket.org/thesheep/micropython-ili9341/src/1fd322f33fb68194e9a848d9fe5c74789aea15b8/ili9341.py?at=default&fileviewer=file-view-default

In order to display the contents of a framebuffer on it, you have to do:

```
from machine import SPI, Pin
import ili9341
display = ili9341.ILI9341(SPI(1), cs=Pin(2), dc=Pin(15), rst=Pin(16))
display.fill(0x0000)
display._block(x, y, framebuffer_width, framebuffer_height, framebuffer_buffer)
```

**Comment by deshipu** [comment]
I guess I will need to implement framebuffer.size() function to be able to properly implement blit() in Python.

**Comment by deshipu** [comment]
I wonder what would it take to make the framebuffer objects support the buffer protocol, so that we could write them out directly with SPI or I2C?

**Comment by dpgeorge** [comment]
> I wonder what would it take to make the framebuffer objects support the buffer protocol, so that we could write them out directly with SPI or I2C?

That would be relatively easy.  But I don't think it'll work as expected because of the stride, ie you can't just send out all the data you need to send it in horizontal pieces.

Regarding

> I rebased it on top of #2367 (to get the getpixel and setpixel functions) and refactored the whole thing to share as much code as possible between the different framebuffers.

You can probably improve it further by using a similar scheme to the SPI class: you'd define a frame buffer protocol at the C level and it'd be a structure with the getpixel and setpixel functions.

**Comment by deshipu** [comment]
>> I wonder what would it take to make the framebuffer objects support the buffer protocol, so that we could write them out directly with SPI or I2C?

>That would be relatively easy. But I don't think it'll work as expected because of the stride, ie you can't just send out all the data you need to send it in horizontal pieces.

An iterator of buffer objects then?

> You can probably improve it further by using a similar scheme to the SPI class: you'd define a frame buffer protocol at the C level and it'd be a structure with the getpixel and setpixel functions.

I thought about it, but not all methods are expressed in terms of getpixel/setpixel. We could do that, and it would simplify the code a lot, but at a cost in efficiency. Then again, the most complex code is for the 1-bit framebuffer, which is going to be used for things like 128x64 screens -- hardly challenging sizes. So perhaps we should stop trying to be smart and instead just implement all the operations in terms of setpixel/getpixel, have just one FrameBuffer type with a "depth" parameter and save some space this way?

**Comment by deshipu** [comment]
As an added benefit, we will then be able to blit a 1-bit framebuffer onto a 16-bit one, and vice versa.

**Comment by dpgeorge** [comment]
> As an added benefit ...

It would also allow to easily support different bit ordering/formats of FrameBuffer1 (eg msb/lsb, and y/x major).

**Comment by peterhinch** [comment]
I could see the framebuffer being used on Embedded Artists (cols=264, lines=176, bits=1) e-paper displays - but these are slow to refresh so a lack of performance wouldn't be an issue.

**Comment by deshipu** [comment]
That's ~5kB of a memory buffer. I think that the small amount of memory generally available on many platforms will make this still fast enough. And platforms with more memory tend to be also faster...

**Comment by deshipu** [comment]
OK, so here goes the newest version:

- renamed FrameBuffer1 to FrameBuffer,
- added an optional "depth" parameter to the constructor, defaulting to 1,
- added fields in the struct for depth, getpixel and setpixel,
- rewrote all the operations in terms of getpixel and setpixel,
- also rewrote blit() and fill_rect() from the other pull requests.

**Comment by dpgeorge** [comment]
It looks good, at least for the first pass :)

I agree we should get the API right first (and make it relatively generic, ie for multiple depths) and then optimise for speed later, if needed (eg by having a dedicated 1-bit rect fill).

Regarding the constructor: I would say it's better to have depth the 4th arg (and mandatory), and stride the optional 5th.  Ie: `FrameBuffer(buf, width, height, depth[, stride]).  Because in most cases you use the default stride (and it makes sense to have a default stride = width), but having a default depth is just an arbitrary choice.

What about later on, adding different bit order for the case depth=1, how will that be specified in the constructor?  Some ideas: 1) pass a string as the depth, like "1vm" (vertical, msb) or "2hl" (horizontal, lsb); 2) use special constants for the different 1-bit depths, eg -1 is vertical msb, and then expose them as const identifiers in the FrameBuffer class; 3) add an extra keyword argument with the format.  I think I like option 2.  In that case maybe we should anyway provide constants for the supported bit-depths, eg FrameBuffer.DEPTH16 and Framebuffer.DEPTH1_VERTLSB.  Thoughts?

**Comment by deshipu** [comment]
I haven't thought about it. Right now all the algorithms are agnostic to the byte order -- they just handle whole pixels, and don't care about their internal structure. This may change if we add any functions that do color manipulation or blending, or if we make the `blit` function work between framebuffers with different formats (personally I would rather avoid that, and instead provide functions for converting between the formats explicitly, to encourage use of one format in the whole program, otherwise the `getpixel` and `setpixel` functions become quite complex and slow).

You are right, that it would make sense to allow encoding more than just the depth of the image in the framebuffer. We should probably rename the parameter to `format` then. I also noticed, that `getpixel` and `setpixel` shouldn't be tied to the *instance* of framebuffer, but to its format -- so we could actually have an array of `getpixel`, `setpixel` pairs, and use the format as an index? However, then the numbering would need to be consecutive, and we would *have* to use constants for it. What do you think?

**Comment by deshipu** [comment]
I rebased on master, and added the changes discussed in the previous two comments.

**Comment by hoihu** [comment]
@deshipu I tried your patch on my limifrog HW. I used an SEPS525 driver IC and a 160x128 16bit color OLED display from Densitron. It works well.

It would be great to have this functionality merged.

One wish (may be something for another pull request...): The font should be selectable and not be hardcoded in the framebuffer module IMO. Because on this display the font is tiny :)

**Comment by deshipu** [comment]
The font should go into a separate library, in my opinion, with a lot more text handling functions, but as you say, it's for another patch, possibly in a year or two when the embargo is lifted.

**Comment by peterhinch** [comment]
I have suggested an approach to fonts [here](https://github.com/peterhinch/micropython-font-to-py.git).

**Comment by hoihu** [comment]
@peterhinch thanks, looks interesting. I'll give it a try.

**Comment by dpgeorge** [comment]
Ok, I have cleaned up and merged this patch.  The following changes were made:
- fixed clipping bugs in fill_rect
- moved format constants to module level (so they can be reused, eg, by an future colour conversion functions)
- simplified constant names to RGB565 and MVLSB (monochrome, vert, lsb)
- made format argument mandatory (instead of defaulting to MVLSB)
- added back FrameBuffer1 factor function so as to be backwards compatible with original behaviour
- optimised fill and fill_rect by adding a format-specific version of this function (makes a big difference when clearing the screen, for example)

See 225e22b2877c7731b7428db0e28d3ad7e6751e35 and 81e171b7bb38cff377ca389cd6fb179aea325998 and a081b49d55ef409d612666d79a97e79259c8adba.

**Pull request closed without merging**
