### PR TITLE
extmod/vfs_posix_file: Fix flush handling in msvc builds.

### PR DESCRIPTION
**Pull request by stinos**
Flushing console output in msvc builds always fails because that output is not buffered so don't propagate that as an error (in a simlar way as was done in 1c047742 for macOS).

Now, the comment for this bit of code says

```
// fsync(stdin/stdout/stderr) may fail with EINVAL (or ENOTSUP on macos),
// but don't propagate that error out.  Because data is not buffered by
// us, and stdin/out/err.flush() should just be a no-op.
```

and tracing back its origin via 68b1bc2042f8e5dcdfbe12c5b0dace0b174f6911 to 3e0b46b9af8b7a6934b7ac68671ef8f55be2b848 the commit says

```
sys.stdout.flush() is needed on CPython to flush the output, and the change
in this commit makes such an expression also work on MicroPython (although
MicroPython doesn't actual need to do any flushing).
```

so 'should be no-op' and 'do not actually need flushing' makes me wonder: why doesn't the implementation do that, by skipping the flushing in case stdin/stdout/stderr is passed? Code for that would also be simpler.

Another reason I'm asking is that I found this issue because with msvc in debug builds where all runtime checks are enabled, trying to flush stderr results in a failed assert.

### CODE REVIEW

**Comment by dpgeorge** [comment]
> so 'should be no-op' and 'do not actually need flushing' makes me wonder: why doesn't the implementation do that, by skipping the flushing in case stdin/stdout/stderr is passed?

CPython internally buffers data written to stdout and does not do a syscall for the data until later on, eg when a newline is printed, or the program exits, or flush is called.

MicroPython has no such internal buffering, any data written to stdout is immediately sent to a syscall.

Checking on Linux, when stdout is a terminal, calling flush/fsync always returns EINVAL.  But when stdout is a file (eg via redirection at the shell) flush/fsync succeed.  So I think we need to retain the existing behaviour and attempt to call fsync for all files, even stdout, in case the underlying OS is actually buffering the data on the OS side of things.

We could update the comment to reflect this.

> Another reason I'm asking is that I found this issue because with msvc in debug builds where all runtime checks are enabled, trying to flush stderr results in a failed assert

Does this PR fix that situation?

**Comment by stinos** [comment]
> But when stdout is a file (eg via redirection at the shell) flush/fsync succeed

Ok that makes sense now. Added this to the comment (should that be a separate commit?)

> Does this PR fix that situation?

No, this only fixes the return value of `vfs_posix_file_ioctl`, just calling `fsync(stderr)` or similar always causes that assertion failure. Because `fsync` for msvc is a PP def of `_commit` which isn't POSIX and does things its own way. By default in micropython this assertion doesn't do anything in release builds and in debug builds only prints a message to the debugger: there's code in ports/windows/init.c which makes the error reporting work like that. Only when changing the error reporting mode to make such failures halt the process and show a dialog, which we do in debug builds to make it easier to see where things might be wrong, it becomes an actual issue.

**Comment by dpgeorge** [comment]
> Added this to the comment (should that be a separate commit?)

Thanks, it's fine in the same commit.

I have merged this PR.



> No, this only fixes the return value of `vfs_posix_file_ioctl`, just calling `fsync(stderr)` or similar always causes that assertion failure.

From your description of this problem, I'm not sure it's worth fixing?  Well, if you think it is, then feel free to fix it.

**Comment by stinos** [comment]
Still evaluating how annoying it is :) But the fix would be an msvc-specific 'do not fsync if handle is stin/out/err' which isn't super nice anyway.

**Comment by dpgeorge** [comment]
> do not fsync if handle is stin/out/err'

But, what happens if stdout is a file, wouldn't fsync be valid to call in that case?

**Comment by stinos** [comment]
Yes it would (at least in a brief test I did earlier with redirecting); should have been more clear, the fix would be 'do not fsync if handle is "real and not redirected" stin/out/err'. I think there are ways to figure that out. Or maybe there's another winapi call which already does that check. Or one which doesn't do that check but just fails.

**Pull request merged**
