### PR TITLE
Replace py-version.sh with makeversionhdr.py, written in Python.

### PR DESCRIPTION
**Pull request by dpgeorge**
To build uPy currently requires make (for Makefile), bash (for py-version.sh) and Python (for makeqstrdata.py).  That seems pretty reasonable except when you learn that on Windows py-version.sh needs ugly work around like this: https://github.com/micropython/micropython/commit/c52f1258a8ececbaf25331c6cbfc373e6ed133b4

So this PR replaces py-version.sh with a Python version, makeversionhdr.py (Py 2 and 3 compatible).  This eliminates the need for bash to run build scripts (at least for the core py stuff).

Yes the Python version of py-version.sh is longer than the bash version, but it's also more robust and easier to add new features.

Also, py-version.h was renamed to mpversion.h for filename consistency with mpconfig*.h.

@stinos: can you check that this actually works with Windows?  May need some tweaks...

### CODE REVIEW

**Comment by dhylands** [comment]
@dpgeorge - yeah - when I first created it, I started writing it in python, and after I got to about twice as many lines of code I said stuff it. I can do this bash way simpler.

Anwyays - thats the history behind it (FYI).

**Comment by stinos** [comment]
The script works fine, see https://github.com/stinos/micropython/commit/1de8e52dbac6d0be9ab1e356ab11beee937ab3a1 for updated genhdr.targets which now just calls makeversionhdr.py

**Comment by dpgeorge** [comment]
Merged in 95f53461c2c42490d12acd41463b86f0056e6f40, including @stinos patch for genhdr.targets.

**Comment by stinos** [comment]
Thanks!

**Pull request closed without merging**
