### PR TITLE
py: Convert float to correct int type

### PR DESCRIPTION
**Pull request by doogle**
To address issue #1042.

I've shifted some of the stuff added by 6e0b6d0 around, so it's shared. Also, float.h and ieee754.h are now used. This avoids some magic numbers in mp, as well as provides support for big-endian floats.

I've added the classification function, which returns one of the five classifications described in https://github.com/micropython/micropython/issues/1042#issuecomment-68859457.
It's slightly more fiddly than simply checking the exponent value to take edge cases into account. A possible (size) optimisation here would be to just err on the side of caution with the edge cases, rather than handling them as accurately as possible.

### CODE REVIEW

**Comment by dpgeorge** [comment]
I'm not sure about the complexity of this, especially all the INT_LOG macros.  Is mpz_set_from_float broken, or did you just want to make it more portable / factor out magic numbers ?

My idea with the float classification function is that it would replace the standard fpclassify, but I don't think that's possible.  Since we have fpclassify anyway, I guess we don't need to duplicate its functionality.  So... what is the simplest (and perhaps not precise) way of detecting if a float will fit in an int (but something more complex than a range check)?

**Comment by doogle** [comment]
I wanted to try to avoid the magic numbers in mp, and to just take them from platform headers. Tbh, if we're saying that `float` always means single precision (32-bit) IEEE-754 floating point, and `double` always means (non-mixed endian) double precision (64-bit) IEEE-754 floating point, then these 'magic numbers' are pretty safe and can be hardcoded into mp (as they were with the original version of `mpz_from_float()`.
So I'm happy to forget about the new approach of using float.h and ieee754.h. It would make sense to have the mantissa and exponent widths defined somewhere shared (mpconfig.h?) still.

Regarding the classification... there needs to be both the test to see if a given mp_float_t will fit into a small int, and when `MICROPY_LONGINT_IMPL == MICROPY_LONGINT_IMPL_LONGLONG`, to see if it will fit into a `mp_longint_impl_t`.

`fpclassify()` could remain in use. `FP_NAN` and `FP_INFINITE` would each result in an exception. `FP_ZERO` and `FP_SUBNORMAL` would result in a short int zero. Then a smaller classification function could handle the other cases, using explicit masking and shifting.
And by erring on the side of caution, the difference in range between positive and negative numbers could be ignored (the `if (u.ieee.negative)` part in my pull request).
This should then result in a much smaller classification function.

I'll scrap this pull request and take another shot at it if this sounds ok to you?

**Comment by dpgeorge** [comment]
> So I'm happy to forget about the new approach of using float.h and ieee754.h.

They (one or the other or both) don't seem to be available when compiling stmhal port (at least on my dev environment).

> It would make sense to have the mantissa and exponent widths defined somewhere shared (mpconfig.h?) still.

mpconfig.h is for configuration values that you can override (using mpconfigport.h).  These numbers are truely fixed, so should go in misc.h.

> FP_ZERO and FP_SUBNORMAL would result in a short int zero

Can these 2 cases not be caught by your simpler function in one hit?  Or are they really special cases that need devoted code paths?

> And by erring on the side of caution, the difference in range between positive and negative numbers could be ignored (the if (u.ieee.negative) part in my pull request).

Yes, I think it's fair to make that simplification.

> I'll scrap this pull request and take another shot at it if this sounds ok to you?

Please!  Be sure to pull latest because some things have changed.

**Comment by doogle** [comment]
AFAIK it was only iee754.h that wasn't present (it looks like it's a glibc header). Either way, both headers can be avoided.

Good to know with mpconfig.h. I wasn't fully comfortable putting those values there, but also wasn't sure how much misc.h should be (ab)used.

> Can these 2 cases not be caught by your simpler function in one hit? Or are they really special cases that need devoted code paths?

`fpclassify()` will tell us if this is the case, so it will be possible to return a small int zero without calling the extra classification function (`mp_classify_fp_as_int()`). However, calling `mp_classify_fp_as_int()` for zero or subnormal values will still result in the correct classification (ie. that it will fit into a small int), so yes, the code path could be simplified in this way.

**Pull request closed without merging**
