### PR TITLE
drivers/display/ssd1306: Support 64px wide displays

### PR DESCRIPTION
**Pull request by deshipu**
In particular, the WeMOS D1 Mini board comes with a shield that
has a 64x48 OLED display. This patch makes it display properly,
with the upper left pixel being at (0, 0) and not (32, 0).

I tried to do this with the configuration commands, but there doesn't
seem to be a command that would set the column offset (there is one
for the line offset, though).

### CODE REVIEW

**Comment by deshipu** [comment]
I'm not proud of this code -- in fact, it's pretty ugly. I tried to maintain backwards compatibility with the previous init signature (adding width at the end, with a default value), even though it probably belongs together with height. I would love to hear suggestions about how to handle this better.

**Comment by pfalcon** [comment]
I think it should be width, height. It's better to break compatibility now, than later, and much better than drag around ugly signature forever. That's also a good lesson to learn - it's better to include all the natural things right away, even if they seem to be not used initially, than to break compatibility later. And we will break it a lot while the project is essentially still in alpha, so minimizing that with a good forward thinking helps. Cf. with a case of passing `id` to "H"SPI constructor.

**Comment by dpgeorge** [comment]
If there really are devices that have width!=128 then I guess we should have `width,height` as the first 2 args (excl self).  I think it's anyway more obvious reading code like SSD1306(128, 32, i2c) than SSD1306(32, i2c), since you'd expect these arguments to be the size of the display.

I see that the Adafruit driver supports 96 pixel wide displays, and does it by sending SET_COL_ADDR, then 0, then width-1.

**Comment by deshipu** [comment]
This driver does the same thing. It just didn't allow you to pass ``width``. In this patch I'm also adding a hack for displays that are 64 pixels wide, which are offset by 32 pixels to the left -- I have no idea why they did it that way, and I have no proof that all 64x48 displays are like that, but the one sold as a WeMoS shield is like that, and I figure it will be relatively popular among Micropython users.

**Comment by mcauser** [comment]
I have the WeMos D1 mini + 64x48 OLED shield. Can test the feature on my device.

Modified the Adafruit library to offset column start by 32px. That got it working.
https://github.com/mcauser/Adafruit_SSD1306/commits/esp8266-64x48

**Comment by mcauser** [comment]
It works!
```
import ssd1306
from machine import I2C, Pin
import math
i2c = I2C(sda=Pin(4), scl=Pin(5))
display = ssd1306.SSD1306_I2C(64, 48, i2c, 60)
display.fill(0)
display.pixel(0,0,1)
display.pixel(63,0,1)
display.pixel(0,47,1)
display.pixel(63,47,1)
display.text('SSD1306',4,2,1)
display.text('64x48',12,11,1)
display.text('Awesome!',1,36,1)
display.show()
display.invert(True)
smiley = [7,192,24,48,32,8,64,4,64,4,255,254,167,154,175,186,156,114,128,2,64,36,67,196,32,8,24,48,7,192]
display.draw_bitmap(24, 20, smiley, 15, 15, 1)
display.show()
```
it-works

I added a method for outputting bitmaps. Not sure if it belongs in `class SSD1306` or a higher level graphics library, which could render complex shapes such as polygons, circles, solid filled, lines, bitmaps etc.

```
def draw_bitmap(self, x, y, bitmap, w, h, col=1):
    byteWidth = (w + 7) // 8
    for j in range(h):
        for i in range(w):
            if i & 7:
                byte <<= 1
            else:
                byte = bitmap[byteWidth * j + i // 8]
            if byte & 0x80:
                self.framebuf.pixel(x + i, y + j, col)
```

**Comment by deshipu** [comment]
I think that should go to ``extmod/framebuf.c`` or a general-purpose ``graphics`` module that would operate on framebuffers directly.

**Comment by mcauser** [comment]
Circles!

```
def draw_circle(self, x0, y0, r, col=1):
    f = 1 - r
    ddF_x = 1
    ddF_y = -2 * r
    x = 0
    y = r

    self.framebuf.pixel(x0, y0 + r, col)
    self.framebuf.pixel(x0, y0 - r, col)
    self.framebuf.pixel(x0 + r, y0, col)
    self.framebuf.pixel(x0 - r, y0, col)

    while x < y:
        if f >= 0:
            y -= 1
            ddF_y += 2
            f += ddF_y
        x += 1
        ddF_x += 2
        f += ddF_x

        self.framebuf.pixel(x0 + x, y0 + y, col)
        self.framebuf.pixel(x0 - x, y0 + y, col)
        self.framebuf.pixel(x0 + x, y0 - y, col)
        self.framebuf.pixel(x0 - x, y0 - y, col)
        self.framebuf.pixel(x0 + y, y0 + x, col)
        self.framebuf.pixel(x0 - y, y0 + x, col)
        self.framebuf.pixel(x0 + y, y0 - x, col)
        self.framebuf.pixel(x0 - y, y0 - x, col)
```

eg.
```
import ssd1306
from machine import I2C, Pin
import math
import time
i2c = I2C(sda=Pin(4), scl=Pin(5))
display = ssd1306.SSD1306_I2C(64, 48, i2c, 60)
display.fill(0)
display.show()
w = 64
h = 48
for i in range(0,h,2):
    display.draw_circle(w//2, h//2, i, 1)
    display.show()
    time.sleep_ms(25)
```

**Comment by deshipu** [comment]
Right, note how all those methods need is just the ``self.framebuf`` object. If you make them into a separate library, it will automatically work with all display drivers that use ``framebuf``.

**Comment by dpgeorge** [comment]
Squashed and merged in ab8a5d51999b5c9214004200a8e0528caf160cc6.

Regarding bitmaps blitting and circle drawing: the framebuf module is a good place for these.

**Comment by mcauser** [comment]
framebuf.circles() in #2373

**Pull request closed without merging**
