### PR TITLE
(unix): Add support for uos.urandom(n)

### PR DESCRIPTION
**Pull request by hvegh**
Use getrandom function if available, otherwise read from /dev/urandom

### CODE REVIEW

**Comment by pfalcon** [comment]
Feel free to keep trying, but the problem was solved years ago: https://github.com/micropython/micropython-lib/blob/master/os/os/__init__.py#L257 . There's even a universal guide how to solve any kind of such problems: https://github.com/micropython/micropython/wiki/ContributorGuidelines

**Comment by hvegh** [comment]
Not sure what you are implying...

The microcontroler ports all have c implementations of urandom:
https://github.com/micropython/micropython/blob/master/ports/esp8266/moduos.c

Why shouldn't the unix port have the same?

**Comment by hvegh** [comment]
The c implementation is more efficient in terms of byte usage and performance, especially when using getrandom... 
Another big advantage for me, it will allow me to test code on unix that is intended to be executed on a microcontroller without full micropython-lib included... 
So where to draw the line... well I would ague that access to (hw) random generator can be considered core functionality and warrants C implementation. As an important building block for crypto.

**Comment by adamples** [comment]
I think that ops concern is valid: uos library on unix does not contain documented function, which makes writing code portable between different ports a lot harder.

Having urandom method in os lib doesn't "fix" this problem in any way: it's a different library, with completely different set of functions.

Also @pfalcon I don't understand why is this not merged nor closed? It seems to me that valid implementation was provided.

**Comment by dpgeorge** [comment]
I think this is a worthy addition, to make unix more compatible with bare-metal.

Merged in d11ff0499fe52cfc9443aa6c0cb1620fd3dd1e70

Thanks @hvegh !

**Pull request closed without merging**
