### PR TITLE
select for ESP8266

### LINKED ISSUE #2380: `uselect` missing from the ESP8266 port
There is no platform independent way to work out when your sockets are ready to be read from/or timeout to run your other events from time to time.

See also #2379.

### PR DESCRIPTION
**Pull request by danni**
An implementation of `select.poll` for the ESP8266. Currently implements `POLLIN` and `POLLHUP` but the others should be fairly easy to implement. Reaches quite deeply into `modlwip`, but maybe that's okay?

Fixes #2380

### CODE REVIEW

**Comment by dpgeorge** [comment]
It loosk like you copied most of this implementation from stmhal, right?  @pfalcon had other plans for the architecture, but I would be ok merging this PR as a temporary (maybe even long-term) implementation.

**Comment by danni** [comment]
I certainly cargoculted a lot of it, but I then wrote a completely new implementation of poll() separate from stmhal.

I was wondering whether it would be interesting to add other kinds of objects besides sockets, specifically I'm thinking GPIO. I'd love to do `poll.register(pin, select.RISING)`.

**Comment by pfalcon** [comment]
My concern with changes like this (vs " @pfalcon had other plans for the architecture") is - who will work to implement it in a better way then? Other concern is that "better" implementation may work a bit differently or have different interface, and then it will be a hard and breaky change. Fortunately, the latter concern doesn't apply here, so I'm +1 for such implementation in principle, though there're many specific issues.

> Currently implements POLLIN and POLLHUP

So, complete implementation to merge definitely should implement POLLOUT. Moreover, the most featureful implementation is currently in unix port, and that includes one-shot mode (epoll-like), as required by uasyncio. Moreover, while unix port is the most featureful enough now, it's still not completely developed, with a feature of adding an arbitrary associated object in queue (as optimization for uasyncio). There's a ticket on that: https://github.com/micropython/micropython/issues/1550

> I certainly cargoculted a lot of it, but I then wrote a completely new implementation of poll() separate from stmhal.

That's drawback rather than benefit. From maintainer's point of view, the following would be much better process: 1) refactor stmhal's implementation to be reusable across ports; 2) add to it features mentioned above.

> I was wondering whether it would be interesting to add other kinds of objects besides sockets, specifically I'm thinking GPIO. I'd love to do poll.register(pin, select.RISING).

Sounds cool (in principle). But please consider thinking and working on already existing project ideas, that being making fill-features and consistent across ports socket polling interface. From my maintainer perspective, it's not conclusive that duplicating code and adding gappy features to it drives project forward.

> Reaches quite deeply into modlwip, but maybe that's okay?

Depends. I'd say it both reaches too deep by touching lines which doesn't have to be touched, and not enough, by not introducing an inline function/macro.

There may be more inline comments.

@danni , Sorry if that looks hard. As I already hinted, if it was easy, it would have been done already. Rest assured that this patch goes the right way and appreciated. But you touch a hard and complex enough area, and have a chance to wear maintainer's hat (or shoes). So, feel free to use that chance and consider how to make project better in general, not just resolve a problem at hand in a random manner (looking overall). Thanks.

**Comment by pfalcon** [comment]
@dpgeorge : So, as my work on uasyncio is being put off and put off, I wonder if we should merge this as is after all?

**Comment by pfalcon** [comment]
Though well, as-is this can't be merged, and needs cleanup anyway.

**Comment by dpgeorge** [comment]
@pfalcon I'd be ok to merge it, after a little bit of cleaning.  Do you want to do it?

**Comment by pfalcon** [comment]
@dpgeorge : So, I don't think this can go without fair amount of cleaning, and preserving @danni 's name on it will be quite cumbersome, so better to do it from scratch. The plan for uasyncio is:

1. Be able to run task queue without heap alloc. (https://github.com/micropython/micropython/issues/2622)
2. Be able to await without heap alloc. (https://github.com/micropython/micropython/issues/2622)
3. Then work on actual I/O support (will require patching of io.BytesIO to become a universal buffer, etc.)

**Comment by pfalcon** [comment]
>  @pfalcon had other plans for the architecture

Ok, so after thinking about it, I guess I give up on "O(1)-like processing", where socket callback would just add current socket to "ready" queue for .poll() to just pop up. The reason is that it wouldn't be O(1) anyway. for example, without checking for duplicates, the queue could can overflow. And checking for duplicates is already not O(1). To alleviate that, hasmap would need to be used, but that's memory bloat, and it goes like that in domino effect. So, for a system like MicroPython, the most memory efficient solution seems like the default "right" one, and anything else is "premature optimization". And then there's just technical debt busting refactoring: at the very least, there should be extmod/moduselect, as a middle-line, there should be no stmhal/moduselect.

**Comment by dpgeorge** [comment]
> at the very least, there should be extmod/moduselect, as a middle-line, there should be no stmhal/moduselect.

Well, I'd be happy to move stmhal/moduselect.c to extmod/moduselect.c, then adapt it so esp8266 can use it for sockets.  After that we can optimise/exetend/generalise usocket as needed.

**Comment by dpgeorge** [comment]
extmod/moduselect.c has been generalised to work with any port, ioctl support for lwip sockets is added in cb53226b0cda3a69331138fee4936f67f72da76d, and uselect module is enabled for esp8266 in e50cb73b7a35a09757dc9d583167f7dcfe18f038.

Basics tests for select with socket on esp8266 works (read, write and hup detection).

**Pull request closed without merging**
