### PR TITLE
extmod/machine_i2s: factor some port I2S code into common extmod file

### PR DESCRIPTION
**Pull request by dpgeorge**
There are currently 4 ports that support I2S (rp2, mimxrt, stm32, esp32) and a lot of code is duplicated across these implementations, especially the 3 bare-metal ports.

This PR aims to factor this code.  It starts with some basic/obvious duplicated code, to make it easier to review that there is no functional change.  Further factoring still needs to be done (not necessarily in this PR).

### CODE REVIEW

**Comment by dpgeorge** [comment]
I factored a lot more code here.

@miketeachman FYI.

**Comment by miketeachman** [comment]
I took a scan through the commits and it looks good to me.  This will definitely help to guarantee consistency when/if I2S is ported to a new micro, esp for the I2S API.

Is there anyway I can help?   e.g.  merge in the PR to a local build and do some regression testing on my hardware?

While you are making I2S changes I'd like to put in a plug for pulling in an stm32 PR that improves the accuracy of the I2S SCK frequency.
[I2S PLL value](https://github.com/micropython/micropython/pull/10613)

**Comment by dpgeorge** [comment]
> Is there anyway I can help? e.g. merge the PR to a local build and do some regression testing on my hardware?

If you could do some simple testing, that would be very helpful.  I have not yet tested this change, although I was very careful doing the factoring, to make sure nothing changed.

**Comment by miketeachman** [comment]
OK, I'll create a local build based on this PR and make a few I2S tests.  What is your timeline to submitting this PR?   I may not be able to get to this for a couple of days.

**Comment by dpgeorge** [comment]
> What is your timeline to submitting this PR? I may not be able to get to this for a couple of days.

I'm not in a hurry.  Would be good to merge it, say, in a week's time.

**Comment by miketeachman** [comment]
I tested this PR with development boards for stm32, esp32, mimxrt, and rp2.  I saw no issues using examples taken from [MicroPython I2S Examples](https://github.com/miketeachman/micropython-i2s-examples).

Unrelated to this PR, I discovered one regression that was introduced in v1.21 for the esp32 port.  The TX/MONO configuration only outputs sound to the left channel.  Prior to v1.21, both right and left channels have sound in this configuration.  The source of the regression is a bug in the ESP-IDF v5 shim code that is used to map legacy public types to the new `slot mode` and `slot mask` conventions.  After this PR is submitted I'll volunteer to fix this regression by converting the esp32 I2S code to use the new ESP-IDF conventions, eliminating the need for the shim code.

**Comment by dpgeorge** [comment]
> I tested this PR with development boards for stm32, esp32, mimxrt, and rp2. I saw no issues using examples taken from [MicroPython I2S Examples](https://github.com/miketeachman/micropython-i2s-examples).

Fantastic, thank you!



> After this PR is submitted I'll volunteer to fix this regression by converting the esp32 I2S code to use the new ESP-IDF conventions, eliminating the need for the shim code.

Sounds great, thanks!

**Pull request merged**
