### PR TITLE
unix: add MICROPY_USE_LIBC_PRINTF compile time option, defaults to disabled

### PR DESCRIPTION
**Pull request by dxxb**
Compile with MICROPY_USE_LIBC_PRINTF=1 to link against libc's *printf() functions.

```
# make -C unix
LINK micropython
   text    data     bss     dec     hex filename
 371073     872    1400  373345   5b261 micropython

# make -C unix/ MICROPY_USE_LIBC_PRINTF=1
LINK micropython
   text    data     bss     dec     hex filename
 370428     888    1400  372716   5afec micropython

# make -C unix/ minimal
 LINK micropython_minimal
   text    data     bss     dec     hex filename
 144317     408     716  145441   23821 micropython_minimal

# make -C unix/ MICROPY_USE_LIBC_PRINTF=1 minimal
LINK micropython_minimal
   text    data     bss     dec     hex filename
 143678     416     716  144810   235aa micropython_minimal

```

### CODE REVIEW

**Comment by dxxb** [comment]
I could have also used MICROPY_STANDALONE instead of adding an ad-hoc compile time option but that would make using *printf() from libc the default.

**Comment by pfalcon** [comment]
Well, we're deprecating unix/mpconfigport.mk as much as possible . If something can be configured via mpconfigport.h, it should be done there (even if it means adding #ifdef to lib/*). That's the direction I tried to follow lately, and it's on my todo to eliminate more options from mpconfigport.mk (some will still need to be set there, but that's 1-2-3 numbered exception). You may want to wait for @dpgeorge's review of this though.

**Comment by dxxb** [comment]
@pfalcon, ack about mpconfigport.mk vs. mpconfigport.h. Any comment about using MICROPY_STANDALONE instead? I'll wait for more feedback from @dpgeorge and update the PR accordingly.

**Comment by pfalcon** [comment]
I think MICROPY_USE_LIBC_PRINTF is a right option, and this feature should not reuse MICROPY_STANDALONE.

**Comment by dpgeorge** [comment]
Given the above discussion about mpconfigport.h, and the fact that almost all ports are using lib/utils/printf.c, how about the following: add lib/utils/printf.c to py.mk source file, add a config variable MICROPY_USE_INTERNAL_PRINTF that's default enabled, and then wrap lib/utils/printf.c in this config variable.

Note that MICROPY_USE_INTERNAL_PRINTF follows scheme used by MICROPY_USE_INTERNAL_ERRNO.

**Comment by pfalcon** [comment]
> add lib/utils/printf.c to py.mk source file

That's the route I'd like to follow (move stuff to py.mk and generally py/*.mk from port-specific Makefiles).

> add a config variable MICROPY_USE_INTERNAL_PRINTF that's default enabled, and then wrap lib/utils/printf.c in this config variable.

Yes, for that variable to be set in mpconfigport.h, not in some Makefile, right?

+1 from me then.

**Comment by dxxb** [comment]
PR updated as per @dpgeorge and @pfalcon comments above.

**Comment by dpgeorge** [comment]
@dxxb: travis build fails.  You need to disable internal printf for qemu-arm port, and also remove utils/printf.c from cc3200/bootmgr/bootloader.mk.

**Comment by dxxb** [comment]
@dpgeorge I thought the failure was unrelated to my changes, my bad. PR updated. Bootloader build fails but failure seems unrelated...

**Comment by dxxb** [comment]
If I leave utils/printf.c in cc3200/bootmgr/bootloader.mk the build succeeds.

**Comment by dxxb** [comment]
Should the unix port set MICROPY_USE_INTERNAL_PRINTF to 0? (Right now it defaults to 1) My preference is for yes.

**Comment by pfalcon** [comment]
> Should the unix port set MICROPY_USE_INTERNAL_PRINTF to 0? (Right now it defaults to 1) My preference is for yes.

As said earlier, this change should not lead to any regressions to MicroPython. (Adding bloat, like extra libc dependency, is a regression.)

**Comment by dxxb** [comment]
@pfalcon Oh, moving goalposts are we? https://cdn.meme.am/instances/500x/59363536.jpg Earlier you said you didn't want executable sizes to increase (in fact they shrink, see PR description above). From #2361:

>> Would a pull request implementing this, i.e. adding utils/printf.c to LIB_SRC_C only if (say) MICROPY_USE_LIBC_PRINTF equals 1, be accepted?

> Yes, if it's done cleanly, and doesn't affect size of the minimal builds (or decreases it).

How common is the case of the *unix* port being compiled without libc at all? Whenever the OS provides a dynamically linkable libc, micropython would be adding bloat by having its own version of *printf().

**Comment by pfalcon** [comment]
@dxxb , you see, somebody made a change to use own printf, you apparently don't follow why it was done, and yet propose to revert it, that worries. What if you change is landed, and then somebody proposed to revert it?

> Whenever the OS provides a dynamically linkable libc, micropython would be adding bloat by having its own version of *printf().

That's too many if's. MicroPython can run on any unix-like OS, regardless of whether it provides dynamically linkable libc, statically linkable libc, or no linkable libc. In all cases it offers sustainably minimal size, and consistent, and correct (as can be proven by MicroPython testsuite) working.

**Comment by dpgeorge** [comment]
Merged in e2ac8bb3f14b076a29244022865e3b47c6c0800a.  Thank you!

Re cc3200 bootloader: the reason it needs explicit inclusion of printf.c is because the makefile for that component does not include the standard py.mk etc files.

@dxxb you should be able to use external printf now with `make CFLAGS_EXTRA='-DMICROPY_USE_INTERNAL_PRINTF=0'`

**Comment by dxxb** [comment]
Thank you @dpgeorge, @pfalcon 

> @dxxb you should be able to use external printf now with make CFLAGS_EXTRA='-DMICROPY_USE_INTERNAL_PRINTF=0'

Yes, it works as expected.

**Pull request closed without merging**
