### PR TITLE
nrf/Makefile: Update to match latest oofatfs version.

### PR DESCRIPTION
**Pull request by glennrub**
See corresponding commit b5f33ac2cb6076468a77f36d69df6db16b62134a

### CODE REVIEW

**Comment by dpgeorge** [comment]
Looks good to me.  I guess Travis didn't pick this up because nRF doesn't have FATFS enabled by default?

**Comment by glennrub** [comment]
Yep, that's correct. Because of the size it consumes it has been disabled. However, i'm thinking that it might make sense to enable it for the nrf52840 targets. I'll take look later on a split of mpconfigport.h for nrf51/nrf52832/nrf52840 to facilitate different options opt'ed in.

**Comment by glennrub** [comment]
Merged in 1f5d945afa20a2d780b8197ce1dd1d5cfd05724b.

**Comment by dpgeorge** [comment]
>  I'll take look later on a split of mpconfigport.h for nrf51/nrf52832/nrf52840 to facilitate different options opt'ed in.

In the stm32 port, there is a base stm32/mpconfigport.h file which is common to all boards, and then each board can provide additional options, and/or override defaults, via a stm32/boards/BOARD/mpconfigboard.h file.

**Pull request closed without merging**
