### PR TITLE
unix/main: Implement -m option for packages.

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by pfalcon** [comment]
Something which was in technical debt for a while. Works pretty much like CPython, couldn't spot a difference in my testing ;-).

**Comment by dpgeorge** [comment]
Looks ok, but I didn't test it.

**Comment by pfalcon** [comment]
Travis build failure is due to extra condition added to builtinimport.c and minimal port code size increase due to that.

**Comment by pfalcon** [comment]
MSVC strikes again with C99 non-compliance with varlen arrays, switching to use alloca().

**Comment by pfalcon** [comment]
Actually, as usual, vstr_t ends up being used.

**Comment by pfalcon** [comment]
> Looks ok, but I didn't test it.

This was mostly to review code patterns used, and well, I had to rewrite it with vstr_t in the end. I pondered about how to implement it and tested well enough, so merging. Maybe we should think how to integrate such command line params  tests for unix port into coverage build.

**Comment by pfalcon** [comment]
Merged in edc02bd952ed4a2042f81b0eaa41f0168ed3d98d.

**Comment by dpgeorge** [comment]
> Maybe we should think how to integrate such command line params tests for unix port into coverage build.

The mechanisms should be there in the cmdline/ tests.

**Pull request closed without merging**
