### PR TITLE
lib/mynewt-nimble: Update to NimBLE release 1.3.0.

### PR DESCRIPTION
**Pull request by jimmo**
This was released last month. There's no particular fixes or improvements that I'm aware of that affect us but I was planning to do some other BLE work and wanted to get onto the latest version first.

Tested by running the multitests on two pyboards running NimBLE 1.3 and then pyboard and unix running btstack.

### CODE REVIEW

**Comment by dpgeorge** [comment]
I tested this with PYBD-PYBD and it works OK.  Also seems to decrease code size by a bit.

**Comment by dpgeorge** [comment]
Sorry to be a pain, but can you please split this in to 2 commits: one to update the submodule, then one to update extmod code for the new lib...

**Comment by jimmo** [comment]
Done!

**Comment by dpgeorge** [comment]
Thanks!

**Pull request merged**
