### PR TITLE
drivers: WIP getting WizNet5500 working with stm32 port.

### PR DESCRIPTION
**Pull request by dpgeorge**
Original patch due to @hjf issue #1859.  The patch here is simplified but still WIP.

### CODE REVIEW

**Comment by Lisa999** [comment]
>>> import network,pyb
>>> nic = network.WIZNET5K(pyb.SPI(1), pyb.Pin.board.X11, pyb.Pin.board.X12)
>>> nic.ifconfig(('192.168.178.204', '255.255.255.0', '192.168.178.1', '192.168.178.1'))
>>> nic.ifconfig()
('192.168.178.204', '255.255.255.0', '192.168.178.1', '192.168.178.1')
>>> 
>>> 
>>> # now use usocket as usual
>>> import usocket as socket
>>> addr = socket.getaddrinfo('www.micropython.org', 80)[0][-1]
>>> s = socket.socket()
>>> s.connect(addr)
>>> s.send(b'GET / HTTP/1.1\r\nHost: www.micropython.org\r\n\r\n')
45
>>> data = s.recv(10000)
>>> print(data)
b'HTTP/1.1 200 OK\r\nServer: nginx/1.8.1\r\nDate: Sun, 15 Oct 2017 11:38:38 GMT\r\nContent-Type: text/html; charset=utf-8\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nVary: Accept-Encoding\r\nX-Frame-Options: SAMEORIGIN\r\n\r\n1fa8\r\n<!DOCTYPE html>\n\n\n\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    \n\n    <link rel="icon" href="/static/img/favicon.ico">\n\n    <title>MicroPython - Python for microcontrollers</title>\n\n    <link href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet">\n\n    <link href="/static/css/style.css?v=2" rel="stylesheet">\n\n    \n  <link href="/static/css/pygments.css" rel="stylesheet">\n  <link href="/static/home/css/style.css" rel="stylesheet">\n\n\n    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">\n    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">\n\n    <meta property="og:type" content="website" />\n    <meta property="og:url" content="http://micropython.org/" />\n    <meta property="og:title" content="MicroPython - Python for microcontrollers" />\n    <meta property="og:description" content="MicroPython is a lean and efficient\n        implementation of the Python 3 programming language\n        that includes a small subset of the Python standard library and is\n        optimised to run on microcontrollers and in constrained environments." />\n    <meta property="og:image" content="http://micropython.org/static/img/Mlogo_138wh.png" />\n\n</head>\n\n<body>\n\n<nav class="navbar navbar-dark" role="navigation">\n    <div class="main-menu">\n        <a class="navbar-brand" href=\'http://micropython.org\'>\n            <span>\n                \n            </span>\n            <span>\n                MicroPython\n            </span>\n        </a>\n\n        <button type="button"'
>>> s.close()
>>> 

It's working! Super! Thx Damien!

**Comment by Lisa999** [comment]
:-( 
And now the asyncio (used by picoweb) isn't working...
Problems in the asyncio:
- setsockopt(_socket.SOL_SOCKET, _socket.SO_REUSEADDR, 1) isn't working, exception: AttributeError
- poller.ipoll(delay, 1) is giving exceptions: OSError 2

**Comment by dpgeorge** [comment]
I further simplified this PR and tested it myself with a W5500 module.  It works at least as well as the W5200 (with about a 15% improvement in TCP speed).  Now merged in c0ea91bc898139aca3ad3e21fc33ff9f0e817952 and e36821a7662e9c65ee2bfb8c23925a10d2167faf

@Lisa999 @Li-Weiwei note that compiling the firmware for WIZNET support now requires defining the MICROPY_PY_WIZNET5K config option to either 5200 or 5500, depending on which chip should be supported by the firmware.

**Comment by Li-Weiwei** [comment]
@dpgeorge We've been talking about switching from w5200 to w5500 in the past, because the w5500 is easier to buy and cheaper to buy.  
Now the w5500 has received support, thank you very much.

**Comment by dpgeorge** [comment]
> And now the asyncio (used by picoweb) isn't working...
> Problems in the asyncio:
> ...

The Wiznet driver, for both 5200 and 5500 chipsets, doesn't (yet) support SO_REUSEADDR, non-blocking mode or ioctl (for poll'ing).  It requires a bit of effort to get all these features working, and it's best to discuss it in a separate issue.

**Comment by Lisa999** [comment]
Raised issue: [https://github.com/micropython/micropython/issues/3373](url)
I see the pyboard as an IOT device, but it looks more like an OT device since Internet connections are hard to make with this board....

**Pull request closed without merging**
