### PR TITLE
modlwip: Fix socket.accept so it can handle dropped connections that are waiting

### PR DESCRIPTION
**Pull request by dpgeorge**
See #4590 for discussion, this should fix at least on of the bugs found there.

### CODE REVIEW

**Comment by dpgeorge** [comment]
@t35tB0t it'd be great if you could please test this.

**Comment by t35tB0t** [comment]
Tested #4644 with fresh pull as shown below.  With pr4644 changes, the 
dropped connection behavior has substantially improved.  The dropped 
connections do not trigger looped-linked-list lockup.  However, we are 
able to jam LWIP such that it stops accepting connections (but still 
running somewhat because we can exit).  So, on to next bug...

With a variation of the traffic running against pr4644, we were able to 
eventually able to essentially break the ability of LWIP to accept new 
connections.  A "LWIP not accepting connections" failure is now 
observed.  This was while running a simple socket setuip and accept 
command line sequence.  However, its far easier to repeat using  the 
full web.py server test application.  It seems  we've jammed LWIP (stuck 
in 'Waiting for client...' server.accept() ).  Its clear that 
setver.accept() has stopped accepting connections and this upy call does 
not return (but will with SIG-INT interrupt).  No packets from LWIP show 
up on the wire.  Ping responses are missing.  LWIP acts like nothing is 
coming in on the wire.  A CTRL-D soft-reset and restart recovers everything.

Conclusions:
1) pr4644 is a significant fix and networking stability improvement 
(congrats for cracking the case on one nasty bug DPG);
2) There is at least one more bug (LWIP not accepting connections) 
triggered by thrashing and generally ill-behaved socket connections.

**Comment by dpgeorge** [comment]
Thanks for testing.

I confirm that I can reproduce the issue with "lwip not accepting connections", if I hit it with the cAbort test from 2 independent sources, plus an nmap scan.

**Comment by dpgeorge** [comment]
I found the cause of at least one more of the issues: upon abrupt closure of a TCP connection any queued incoming pbufs or TCP PCBs were not being freed (by the uPy lwIP bindings).  This is now fixed by the latest commit in this PR.  With this patch the behaviour is significantly improved, and the cAbort() test will run much faster, even 2 in parallel.

**Comment by t35tB0t** [comment]
sync'd up with dd8f33 and, yes its more resilient.  Attached is a hacked up script to jam LWIP connections.  Running it a few time resulted in LWIP no longer accepting connections. However, ping responses are present.  Letting it sit for many minutes does not recover.  SIG-INT does break to prompt and resuming web server fully recovers stack.  In spite of the jam, this is a significant improvement.

see attached - no other traffic was needed to jam the stack.
[scapy-connection-abort.zip](https://github.com/micropython/micropython/files/3017617/scapy-connection-abort.zip)

**Comment by dpgeorge** [comment]
I can't seem to reproduce the issue with the scapy test.  Using this PR on a STM32F769DISC board running the web.py script from earlier tests, I run the above scapy script in a loop over 150 times so far without an issue.  Web requests from a browser succeed (even though the scapy test still continues to run).

(Note: the web.py script doesn't actually accept any of the scapy connections, and I assume this is the correct behaviour because scapy is sending malformed TCP streams).

**Comment by t35tB0t** [comment]
Ok... Then I'll check my build here and re test.

**Comment by dpgeorge** [comment]
Ok, since the 4 commits here are definite improvements / fix bugs, I merged them in da938a83b587c7387b8849f795f3497735d14267, 2ec7838967aec9d43d44c2d53377e827d6fcf041, 490e0f39d1470d4cdf4b91a0632f6147ab4220ea and 2848a613ac61fce209962354c2698ee587a2c26a

**Comment by dpgeorge** [comment]
> Confirming issue still present in: ...

Ok.  But let's continue the discussion in the original issue #4590

**Comment by dpgeorge** [comment]
Upon testing with older versions of lwIP the following fix was needed for one of the commits introduced here: 734ada3e2980d1bbf5c7a1ea5c624b34be16dfa9

@t35tB0t FYI

**Pull request closed without merging**
