### PR TITLE
tools/ci.sh: Fix listdir test by setting _FILE_OFFSET_BITS=64.

### PR DESCRIPTION
**Pull request by dpgeorge**
### Summary

As suggested in https://github.com/micropython/micropython/issues/16312#issuecomment-2514587579 it may be possible to fix the unix MIPS listdir test.

### Testing

Hopefully CI passes!

### CODE REVIEW

**Comment by dpgeorge** [comment]
This is how the CI used to fail on the unix qemu MIPS port:
```diff
--- /home/runner/work/micropython/micropython/tests/results/extmod_vfs_posix_paths.py.exp	2024-12-04 02:01:22.215945136 +0000
+++ /home/runner/work/micropython/micropython/tests/results/extmod_vfs_posix_paths.py.out	2024-12-04 02:01:22.215945136 +0000
@@ -1,12 +1,12 @@
-listdir("/"): ['subdir']
-listdir("."): ['subdir']
+listdir("/"): []
+listdir("."): []
 getcwd() in {"", "/"}: True
 chdir("subdir"): None
 getcwd(): /subdir
 mkdir("two"): None
-listdir("/"): ['subdir']
-listdir("/subdir"): ['file.py', 'one', 'two']
-listdir("."): ['file.py', 'one', 'two']
+listdir("/"): []
+listdir("/subdir"): []
+listdir("."): []
 print('hello')
 hello
 <module 'file' from 'file.py'>
```
But now with `_FILE_OFFSET_BITS` defined to 64 the tests all pass.

Thanks @stinos for the hint!

**Comment by projectgus** [comment]
@dpgeorge Good to have this fixed! Maybe I don't fully understand the root cause, but should we fix this in the port Makefile rather than the CI system - for non-CI builds of this port+config?

**Comment by dpgeorge** [comment]
> Maybe I don't fully understand the root cause

Neither do I!



> should we fix this in the port Makefile rather than the CI system - for non-CI builds of this port+config?

Yes, that's a good idea.  Just for MIPS builds (at this stage, that's where we see the failure).

**Comment by agatti** [comment]
Shouldn't this be applied to the Unix/Arm qemu build too?

I've seen this issue in #15800 for both MIPS and Arm; as in, the toolchains I was using in the CI-like environment had that define baked in somehow and made tests pass in my VM.

**Comment by stinos** [comment]
This should probably be applied for all 32bit builds, preferably in the Makefile.

**Comment by dpgeorge** [comment]
> This should probably be applied for all 32bit builds, preferably in the Makefile.

I've now added it unconditionally to the unix Makefile, so it is applied for all builds.  The CI actually passes with that (on 32-bit and 64-bit builds).

I'm not exactly sure how to make it apply for 32-bit only builds.  Any ideas?  Or maybe it can stay unconditionally enabled?

**Comment by stinos** [comment]
It has no effects on 64bit builds (https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html).
Should also be added to at least the windows port Makefile, and maybe other 'large' ports as well?

**Comment by dpgeorge** [comment]
I have updated this PR to force `_FILE_OFFSET_BITS=64` on both the unix and windows ports.  On 64-bit systems this should have no effect.  On 32-bit systems it will force 64-bit file sizes which should work on pretty much all systems these days.

**Review by projectgus — APPROVED** [review]

**Pull request merged**
