### PR TITLE
Remove board that has no use

### PR DESCRIPTION
**Pull request by rolandvs**
This board is "generic" and somehow useless. Let's remove it.

### CODE REVIEW

**Comment by dpgeorge** [comment]
I can't remember the exact reason this board was added (@ryannathans ?), but I think it could have been to show that the F439 is a supported MCU and have a board to build for the F439 to check for any compile-time regressions.  If we don't have another official board that supports the F439 then this should probably stay.

**Comment by ryannathans** [comment]
I added and continue to use this board. Cheers for the heads up. 

The board exists to support the F439. No other boards are compatible with this chip.

@rolandvs how is this "somehow useless"?

**Comment by rolandvs** [comment]
The reasoning behind this comes from the end at #3885 and the end of #3991 where the use of other than "official" boards (i.e. ST, Nordic and some popular 3rd party) is somehow dispirited :-) for all the good reasons.

The F439 is not really different to the F429 and has no board to go with it :-), that's why I put in the PR.

As you can read from the mentioned PR's I like to support as many boards as possible.

**Comment by dpgeorge** [comment]
> where the use of other than "official" boards (i.e. ST, Nordic and some popular 3rd party) is somehow dispirited :-) for all the good reasons.

Yes, that's a good reason to remove it.  But...



> The F439 is not really different to the F429

There is some F439-only code in flashbdev.c which this F439 board would test (at least in terms of compilation).  There are also different af.csv files.  So it's important to have a board that uses the F439.  It would be even better if it were an official ST board, but for now let's keep this generic one.

**Comment by ryannathans** [comment]
Due to the "dual use" nature of the chip, there are no official ST boards last I checked :(

**Comment by rolandvs** [comment]
OK sounds reasonable to me, then could we make an effort to expose some more of the chip as a first step to use the crypto engine as it is also available in a lot of derivates...?

**Comment by ryannathans** [comment]
That would be nice, but how many people will that be useful to? I.e how many using micropython with this chip? 

Keep in mind that to use the chip you need to make your own PCB

**Comment by dpgeorge** [comment]
> then could we make an effort to expose some more of the chip as a first step to use the crypto engine

That would be nice, but it's a low priority item.  Eventually the HW crypto could be used (in a user-transparent way) to accelerate the functionality in `ucryptolib`.

Anyway, let's close this particular PR.

**Pull request closed without merging**
