### PR TITLE
Minor BTStack updates

### PR DESCRIPTION
**Pull request by andrewleech**
Minor updates I found during work to support generic HCI radios.

nimble support has a define `MICROPY_PY_BLUETOOTH_RANDOM_ADDR` which will set a new random bluetooth address each run. This is now mirrored on btstack.

Also the initial uart baud rate wasn't being set to `MICROPY_HW_BLE_UART_BAUDRATE` like on nimble.

### CODE REVIEW

**Comment by jimmo** [comment]
Looks good, thanks @andrewleech 

FYI my plan is to move configuration of the address out to Python but for now making them the same is definitely worth doing.

**Comment by andrewleech** [comment]
@jimmo I agree, I would like to migrate all the Bt/mac address settings into a common python accessible interface. For now though I've added another btstack change to mirror the current nimble behavior:
* extmod/btstack: Provide default BT mac address if none already available.

This resolves the issue with zephyr hci radio's that start up with mac of 00:00:00:00:00:00

**Comment by andrewleech** [comment]
Also added a commit to allow overriding total attribute size MICROPY_PY_BLUETOOTH_MAX_ATT_DB_SIZE
Requires setting from make / mpconfigboard.mk

BTstack currently has fixed 512 byte attr storage which is easy enough to use up with a few services / characteristics.

Eventually I presume this will be replaced with a similar managed "maloc" to nimble?

**Comment by andrewleech** [comment]
Most of the functionality here has been integrated / fixed in other ways. Attribute size picked off here for reference: https://github.com/micropython/micropython/pull/6448

**Pull request closed without merging**
