### PR TITLE
Nrf52840 mdk2

### PR DESCRIPTION
**Pull request by glennrub**
Follow-up on PR #6054.

I've added a Make flag `DFU` in the mpconfigboards.mk which has the intention of disabling all Bootloader awareness. Hence, claim the full flash and set a standard programmer. I'm not happy with the name. Any, better suggestion on what to call this? I thought of `BOOTLOADER_DISABLE` and similar, but then it sounds like the compilation provides a bootloader. This is why i pointed it more in direction of DFU capability disable.

### CODE REVIEW

**Comment by glennrub** [comment]
@mattytrentini , i'm not sure if you have tried it out yet, but i guess this can be merged if you agree to the updated [Readme.txt](https://github.com/micropython/micropython/pull/6252/files#diff-bbeee4b2cce3f4ee69a41b85a745bd14507d85fdd798ec3c710c510f00305c71L47-R58) for the `nrf52840-mdk-usb-dongle` board 

I'll rebase the branch and validate it still meets the expectations.

**Comment by glennrub** [comment]
Ref. latests force-push: Cleaned up commit messages and rephrased a bit in the nrf52840-mdk-usb-dongle README.

**Comment by tve** [comment]
I think I'm running into the same issues with a PCA10059, which also came with Open Bootloader. Any plans to extend this stuff to the pca10059?

**Comment by glennrub** [comment]
> I think I'm running into the same issues with a PCA10059, which also came with Open Bootloader. Any plans to extend this stuff to the pca10059?

@tve, Great idea!

i've pushed a new commit to make `pca10059` also use the inbuilt bootloader for flashing (still possible to claim the full flash by defining DFU=0). I'll have to update the README.md files a bit to get the `nrfutil` flashing documented at port level to cover both boards (currently it is  documented only for the `nrf52840-mdk-usb-dongle`). However, you can try it out while i'm sorting out the documentation.

**Comment by tve** [comment]
Awesome, will try today. In case it helps, this is what I have as my little script to generate firmware and flash the pca10059:
```
#! /bin/bash -e

make -j6 BOARD=pca10059 SD=s140

# generate package with softdevice (only needed once)
#nrfutil pkg generate --debug-mode --hw-version 52 --sd-req 0x00 --sd-id 0xB6 \
#    --application build-pca10059-s140/firmware.hex \
#    --softdevice drivers/bluetooth/s140_nrf52_6.1.1/s140_nrf52_6.1.1_softdevice.hex \
#    build-pca10059-s140/dfu.zip

# generate package just with app
nrfutil pkg generate --debug-mode --hw-version 52 --sd-req 0xB6 \
    --application build-pca10059-s140/firmware.hex \
    build-pca10059-s140/dfu.zip

# do the flashing
nrfutil dfu usb-serial -pkg build-pca10059-s140/dfu.zip -p /dev/serial/by-id/usb-Nordic* -t 0 -b 460800
```
The one flag that may not be obvious: `-t 0` prevents nrfutil dfu from waiting 30+ seconds on "something" before deciding to flash the thing. There's a thread on some nordic forum where I found that.

**Comment by glennrub** [comment]
> The one flag that may not be obvious: -t 0 prevents nrfutil dfu from waiting 30+ seconds on "something" before deciding to flash the thing. There's a thread on some nordic forum where I found that.

@tve, I've been using `nrfutil==5.2.0` from `pip` (the latest i can resolve). I have not seen any issues with this version. Flashes immediately. 
I'm open to add this `-t 0` if it prevents a 30 seconds delay, just in case. But it would be still interesting to know how it got delayed.

What version have you been running?

**Comment by tve** [comment]
> What version have you been running?

```
> nrfutil version
nrfutil version 6.1.0
```

**Comment by glennrub** [comment]
Did a test with the latest `nrfutil==6.1.0` as well, did not hit any extra delay. Do you happen to have a `udev`-rule for the device, could it be related to enumeration of the USB ACM?

**Comment by glennrub** [comment]
@tve, I've appended the `-t 0` in any case. It might be something that could happen often to users. Thanks a lot for pointing it out! :)

**Comment by tve** [comment]
OK, so the deploy target worked:
```
(mdk2) /h/s/n/m/p/nrf> make -j6 BOARD=pca10059 SD=s140 deploy
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.

|===============================================================|
|##      ##    ###    ########  ##    ## #### ##    ##  ######  |
|##  ##  ##   ## ##   ##     ## ###   ##  ##  ###   ## ##    ## |
|##  ##  ##  ##   ##  ##     ## ####  ##  ##  ####  ## ##       |
|##  ##  ## ##     ## ########  ## ## ##  ##  ## ## ## ##   ####|
|##  ##  ## ######### ##   ##   ##  ####  ##  ##  #### ##    ## |
|##  ##  ## ##     ## ##    ##  ##   ###  ##  ##   ### ##    ## |
| ###  ###  ##     ## ##     ## ##    ## #### ##    ##  ######  |
|===============================================================|
|You are not providing a signature key, which means the DFU     |
|files will not be signed, and are vulnerable to tampering.     |
|This is only compatible with a signature-less bootloader and is|
|not suitable for production environments.                      |
|===============================================================|

Zip created at build-pca10059-s140/firmware_dfu.zip
  [####################################]  100%
Device programmed.
```
The sd target doesn't work:
```
(mdk2) /h/s/n/m/p/nrf> make -j6 BOARD=pca10059 SD=s140 sd
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make: hexmerge.py: No such file or directory
make: *** [Makefile:464: nrfutil_dfu_sd] Error 127
(mdk2) /h/s/n/m/p/nrf [2]>
```

**Comment by glennrub** [comment]
@tve, for the SD target, did you also install the `intelhex` package as described in the [README.md patch](https://github.com/micropython/micropython/pull/6252/files#diff-930eb6e82c3d8e67ba5b84136d676bcac2081773efc00fc1ca4865d282f3554aR177-R201)

**Comment by tve** [comment]
> @tve, for the SD target, did you also install the `intelhex` package as described in the [README.md patch](https://github.com/micropython/micropython/pull/6252/files#diff-930eb6e82c3d8e67ba5b84136d676bcac2081773efc00fc1ca4865d282f3554aR177-R201)

Of course not! ;-)

Well, after installing it, the flashing still didn't work. After lots of crazy troubleshooting I'm realizing it has to do with the fact that I run `make -j6` and the `nrfutil_dfu_sd` and `deploy` tasks are run concurrently by make. I suggest adding some dependency to prevent that.

**Comment by glennrub** [comment]
Thanks a lot for testing it @tve, by using the `-j9` i could also see issues with the flashing of SD. As it run in parallel with generating and flashing the application i lost connecting with the bootloader. I have put a commit on top which solves the problem for me. It would be great if you could test if it works for you as well.

**Comment by tve** [comment]
Works like a charm!

**Comment by glennrub** [comment]
Cross-checking the PR with other target boards revealed a bug in the latest change i did (parallel execution prevention of the nrfutil). Fixed in latest force-push.

**Comment by glennrub** [comment]
Merged in 248968863595fb285b1209927e27c37b06faf857 through d0b8554df477ca1b9daf634d01604e3f760909ca.

**Pull request closed without merging**
