### PR TITLE
py: Add MICROPY_PY_ALL_SPECIAL_METHODS and __iadd__ special method under it

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by pfalcon** [comment]
One day we'll need to add all special methods, but that means adding bunch of qstr's which will never be used for large subset of projects. So, that's how I propose to do it.

**Comment by dpgeorge** [comment]
I'd say we can go even further and have an option to disable special methods all together.  It means not needing instance_unary_op or instance_binary_op at all.

**Comment by pfalcon** [comment]
Well, that would be a separate feature. Having special methods is a good thing and close part of Python semantics. It's just probably 20% of them are used in 80% of time, so for smaller ports, it would make sense to support at least few such methods. Specific reason for this patch is even simpler - to have symbolic operation names in disassembly dump, while not changing status quo for stmhal and other embedded ports.

So, hopefully this is ok for merging.

**Comment by pfalcon** [comment]
Merged.

**Pull request closed without merging**
