### PR TITLE
Add support for NUCLEO_L476RG

### PR DESCRIPTION
**Pull request by sergiuszm**

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks!

As @dhylands points out, you can probably use the existing stm32l476_af.csv file, it should work just the same (unless there are errors in that existing file, which should then be fixed).

What tests did you do with this board?  How did you deploy the firmware (open ocd or st-link or ...)?  How did you access the REPL, on which serial port?

**Comment by sergiuszm** [comment]
@dpgeorge I can use existing stm32l476_af.csv file. I have created a separate file because I like when everything in a solution is clean, but I can change that.

I deployed firmware via st-link, but I can try with ocd too to be sure that everything is working as expected.

I have accessed the REPL via VCP. So far I have checked basic functionality (led, rtc, millis etc.).

If there is something more which I should check just let me know.

Do you prefer everything in the single commit?

**Comment by dpgeorge** [comment]
> I can use existing stm32l476_af.csv file. I have created a separate file because I like when everything in a solution is clean, but I can change that.

In this case the clean solution is to reuse existing files that already do the job.  The X_af.csv files should work for all pin variants of a given line of MCUs.  So please change the PR to use the existing file.

> I deployed firmware via st-link, but I can try with ocd too to be sure that everything is working as expected.

I was just curious, it should work with all methods.

> I have accessed the REPL via VCP. So far I have checked basic functionality (led, rtc, millis etc.).

Did you use the st-link VCP (through a UART), or the other USB connector with direct VCP access to MicroPython?

> If there is something more what I should check just let me know.

Does the filesystem work?

> Do you prefer everything in the single commit?

If it's just adding a new board directory then yes, a single commit is best.

**Comment by sergiuszm** [comment]
> Did you use the st-link VCP (through a UART), or the other USB connector with direct VCP access to MicroPython?

I connected my board via USB connector with direct VCP access. I have a CP2102 UART to USB if you would like me to test it.

> Does the filesystem work?

```
>>> import os
>>> os.listdir()
['main.py', 'pybcdc.inf', 'README.txt', 'boot.py']
>>> f = open("hello.txt", "w")
>>> f.write("Hello world")
11
>>> f.close()
>>> os.listdir()
['main.py', 'pybcdc.inf', 'README.txt', 'boot.py', 'hello.txt']
```

So, I will delete this PR, recreate this branch and put everything in a single commit with discussed changes.

**Pull request closed without merging**
