### PR TITLE
tools/ci.sh: Add build of W5500_EVB_PICO board to rp2 CI.

### PR DESCRIPTION
**Pull request by dpslwk**
update ci.sh since https://github.com/micropython/micropython/pull/8962 was merged

### CODE REVIEW

**Comment by dpgeorge** [comment]
I'm not sure this is needed?  We can't build every board in CI, it takes too long.  And there is already the `W5100S_EVB_PICO` being built which is almost identical to the W5500 version.

We definitely need to add `PICO_W` to the CI though.

**Comment by dpslwk** [comment]
Sounds fair, I was not sure if adding to the CI was needed or not for board builds to show up on https://micropython.org/download/

Related to the `W5100S_EVB_PICO` and `W5500_EVB_PICO` boards I wonder if they should include the same `manifest.py` as the `manifest.py` as the `PCIO_W` which adds upip and urequests

**Comment by jimmo** [comment]
> Sounds fair, I was not sure if adding to the CI was needed or not for board builds to show up on https://micropython.org/download/

Nope, that runs through a separate process that just builds every board.
 
> Related to the `W5100S_EVB_PICO` and `W5500_EVB_PICO` boards I wonder if they should include the same `manifest.py` as the `manifest.py` as the `PCIO_W` which adds upip and urequests

Yes. I also plan to combine these two boards into a single board with different variants (similar to what we do with e.g. https://micropython.org/download/pybv11/). See e.g. #9056 for the first step towards making "board variants" supported on more ports. This will also allow us to make a "W5100S HAT" variant too.

**Comment by dpgeorge** [comment]
We won't add this to CI.

**Pull request closed without merging**
