### PR TITLE
Flash 16 m

### PR DESCRIPTION
**Pull request by gmos**
Board files for the WROVER module with SPIRAM (4 MB used) and 16MB Flash.

### CODE REVIEW

**Comment by gmos** [comment]
"bare-arm and minimal ports build" chack mai be flawed.  Core code size increased with 4 bytes.  Hard to understand for a change that only affects the ESP32 builds.  Or did I miss something?

**Comment by tve** [comment]
Can you explain why you made the partitions the way you did? (Comments in the files might help...)

**Comment by gmos** [comment]
The large WRover modules have 16MB flash instead of the 4MB normally found on the WRoom types.
Basically I have added a partition table csv file that allocates the extra 12MB to the file system (vfs) partition.  So you'll end up with a much bigger FAT or LittleFS file system.  Both types of FS will gladly use the extra space.
Didn't change the other partitions, since there is no need to do so.
Per your request I also have added a comment to the partitions-16MiB.csv file.
Will push it soon.

**Comment by tve** [comment]
Thanks. I had gotten a little confused 'cause I didn't see that the -2Mib partition.csv has a smaller factory partition than the plain partition.csv so it looked as if you had increased the factory partition as well.

**Comment by dpgeorge** [comment]
A 16MiB partition was added in 5093d49fae5b59d6440d34b4c05f2950f40a6b9f as part of ESP32S2 support.

So I'll close this PR.  Feel free to reopen if what you need is still not supported (and then please update to use cmake).

**Pull request closed without merging**
