### PR TITLE
esp32: Use SPIRAM in mem-map mode so all of it can be used for uPy heap.

### PR DESCRIPTION
**Pull request by dpgeorge**
Also enable CONFIG_SPIRAM_IGNORE_NOTFOUND to allow boards with faulty or missing SPIRAM to still boot.

### CODE REVIEW

**Comment by mattytrentini** [comment]
Looks good and will be invaluable for PSRAM-enabled ESP32 devices!
But what does `CONFIG_SPIRAM_USE_MEMMAP` do? I can't seem to find any useful documentation on it...

**Comment by dpgeorge** [comment]
> what does `CONFIG_SPIRAM_USE_MEMMAP` do

It's the simplest way to use SPIRAM: it just initialises it and maps it to the memory area starting at 0x3f800000.  It doesn't do anything else (eg allow it to be part of the ESP32 heap).

**Comment by robert-hh** [comment]
This is a good PR, since it allows to run the same image for device with and w/o SPIRAM. However, on a device without SPIRAM, this image runs about 10% slower than a image build without SPIRAM support.
The difference between the builds is using either sdkconfig.spiram or sdkconfig

**Comment by dpgeorge** [comment]
> However, on a device without SPIRAM, this image runs about 10% slower than a image build without SPIRAM support.

Yes.  Enabling SPIRAM enables some extra switches in the compiler to workaround some cache issues, which decreases overall performance.  That's why I think it's good to maintain both a non-SPIRAM and SPIRAM configuration.

**Comment by dpgeorge** [comment]
Merged in 6a95e74387725e77ea368769ff53e03042ce7869

**Pull request closed without merging**
