### PR TITLE
py/objarray: Detect bytearray(str) without an encoding.

### PR DESCRIPTION
**Pull request by jimmo**
This prevents a very subtle bug caused by writing e.g. `bytearray('\xfd')` which gives you `(0xc3, 0xbd)`. CPython doesn't allow you to do this.

Reported in https://github.com/orgs/micropython/discussions/9844

Unfortunately it's +60 bytes. Can undo the change to objstr.c and make it also use the `"wrong number of arguments"` error, but that only gets it down to +44 bytes. Could also hide this behind `MICROPY_CPYTHON_COMPAT`.

_This work was funded through GitHub Sponsors._

### CODE REVIEW

**Comment by dlech** [comment]
Since `bytearray` and `array` are optional and the strings are optimized out when `MICROPY_ERROR_REPORTING == MICROPY_ERROR_REPORTING_NONE`, the code size change doesn't seem too bad.

**Comment by dpgeorge** [comment]
I think we should make this change, if only to make `bytes(..)` and `bytearray(...)` have the same behaviour when passed a str.

I also agree with @dlech that increasing code size a bit is OK because these things are already optional (and bare-arm doesn't change size, it uses NONE for error reporting).

So the question is about the error message string:
1. Continue to just use `"wrong number of arguments"` everywhere.
2. Use `"string argument without an encoding"` where appropriate for a more meaningful message (this could be slightly shorter as `"string argument without encoding"`).
3. Use ``MICROPY_ERROR_REPORTING_TERSE` to select option (1) and `MICROPY_ERROR_REPORTING_NORMAL` to select option(2).

**Comment by dpgeorge** [comment]
Also note that the `viper_addr.py` test needs fixing.

**Comment by jimmo** [comment]
Updated to do option 3. (And update tests).

**Comment by dpgeorge** [comment]
Not sure why qemu-arm is failing the tests... something to do with unicode?

**Comment by dpgeorge** [comment]
Thanks, rebased and merged in 2c8dab7ab4ec0884c6428afc613d9dcc322d8c6d

**Pull request closed without merging**
