### PR TITLE
Add stm32f7 support3

### PR DESCRIPTION
**Pull request by dhylands**
It turns out that the cmsis/devinc/stm32f7xx.h file already defines STM32F7 so I dropped that from CFLAGS.

I'm going to guess that newer versions of the hal will add STM32F4 to the stm32f4xx.h file.

### CODE REVIEW

**Comment by dhylands** [comment]
rebased this on the new hal commit

**Comment by dpgeorge** [comment]
@dhylands how are you compiling it?  When I build I get:
```
Assembler messages:
Error: unknown cpu `cortex-m7'
Error: unrecognized option -mcpu=cortex-m7
```
If I remove the `-mcpu=cortex-m7` but leave the `-mtune=cortex-m7` then I get instead:
```
cmsis/inc/core_cmInstr.h: In function '__REV':
cmsis/inc/core_cmInstr.h:405:1: sorry, unimplemented: Thumb-1 hard-float VFP ABI
```
I'm using arm-none-eabi-gcc 5.2.0 from Arch Linux repo.

**Comment by dpgeorge** [comment]
Regarding the enabling of all GPIO clocks in main(): is this necessary?  In pin.c the GPIO clock is enabled only when a pin is configured, and this is supposed to save power for GPIO banks that are not used.  Does the F7 need all GPIOs enabled to work?

**Comment by dhylands** [comment]
> I'm using arm-none-eabi-gcc 5.2.0 from Arch Linux repo.

It sounds like your toolchain doesn't have M7 support. 

I'm using the 4.9.3 toolchain from https://launchpad.net/gcc-arm-embedded

arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20141119 (release) [ARM/embedded-4_9-branch revision 218278]

It looks like I don't quite have the latest. I'll test that too.

> Regarding the enabling of all GPIO clocks in main(): is this necessary? In pin.c the GPIO clock is enabled only when a pin is configured, and this is supposed to save power for GPIO banks that are not used. Does the F7 need all GPIOs enabled to work?

Probably not. I'll remove that.

**Comment by dhylands** [comment]
I realized I forgot to push the change which removed SAI from hal config (now in a77a59c276cfae16bdfe079c259439e1d8e673fb)

**Comment by dhylands** [comment]
And I tested with the latest version from launchpad, which is:
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 224288]

and that seems to be building error/warning free.

**Comment by dhylands** [comment]
Presumably travis is using the launchpad toolchain?

**Comment by dpgeorge** [comment]
I think travis uses launchpad.  I guess I'll have to trust that it works and use travis to find errors!

**Comment by dpgeorge** [comment]
I've already made some changes to your original PR.  Did you just remove the GPIO init from main() and the SAI change?

**Comment by dhylands** [comment]
I haven't done the removal of GPIO yet. 

I think I'd also need to enable the PortK clock in the boards/STM32F7DISC/board_init.c function.

**Comment by dhylands** [comment]
Removed the extra GPIO initialization in main.c
Added initialization of PortK to board_init.c

I did this as a separate commit since you said you'd already done some other changes.

**Comment by dhylands** [comment]
Commit https://github.com/dhylands/micropython/commit/80f6db9d743296183585b41323958b868542c3bb fixes pyb.bootloader() to work on the M7

**Comment by dpgeorge** [comment]
Ok, I rebased and reworked it a little.  I didn't merge the "Whitespace cleanup" commit because it's not necessary.  Everything else should be as you had it.

See 92d4b51ad5d828930334f87d9619a78b5877a384 for the last commit of the series.

**Comment by dhylands** [comment]
Cool - I also added some info to the Wiki page: https://github.com/micropython/micropython/wiki/Board-STM32F745-Discovery

**Comment by dhylands** [comment]
I think I now have usb serial working. I need to remove all of my debug code and rebase/retest. Will open a new PR tomorrow with a bunch of other small changes.

**Pull request closed without merging**
