### PR TITLE
re: _compilecode: error if emitted byte is out of range

### LINKED ISSUE #7078: Assertion error in re1.5
Build the Unix port with DEBUG=1, then try to match a particular regular expression.

```
src/micropython/ports/unix$ ./micropython
MicroPython v1.14-122-g9fef1c0bd-dirty on 2021-03-27; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> import ure as re
>>> re.match(63*"a" + "|", "x")
micropython: ../../extmod/re1.5/recursiveloop.c:79: recursiveloop: Assertion `!"recursiveloop"' failed.
Aborted
```

The original regular expression I encountered this with was a long series of "literal|literal|..." intended to be useful, the above is a minimized version.

I'm guessing it has to do with the offset of a `split` being large enough that it becomes negative .. with 62 repetitions of 'a', everything is 'okay'.

I think this has to do with overflowing some 8-bit offset.  When additionally defining MICROPY_PY_URE_DEBUG, the not-quite-crashing expression's disassembly can be seen to begin:
```
>>> re.compile(62*"a" + "|", re.DEBUG)
 0: rsplit 5 (3)
 2: any
 3: jmp 0 (-5)
 5: save 0
 7: split 135 (126)
 9: char a
```
while the crashing version has a negative `split` target at instruction 7:
```
>>> re.compile(63*"a" + "|", re.DEBUG)
 0: rsplit 5 (3)
 2: any
 3: jmp 0 (-5)
 5: save 0
 7: split -119 (-128)
 9: char a
```

Knowing all this, it looks like my regular expression is simply too much for re1.5. However, maybe the problem could be found at compile time and changed to result in an exception rather than an assertion error (or, probably, unpredictable behavior at runtime if assertions are disabled)

### PR DESCRIPTION
**Pull request by jepler**
…adding a test for this case.

Locally, this change increases the size of PYBV10 by +80 bytes text.

The complication where the argument is checked for constness reduces code size slightly (-14 bytes).  This gcc extension is supported by clang and is already used in the stm and teensy ports.

This change assumes that the results that overflow an int8_t do not overflow a platform int.

Closes: #7078

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the patch, but I'm not sure this is the right approach, to protect all uses of `EMIT`.  A lot of the `EMIT` are just constants or ASCII literals (see eg `case '['`) and do not need checking.

An alternative approach would be to introduce new `EMIT_xxx` macros which have checks on the args.  I might be wrong but I think the only one is when it's like `EMIT(x, REL(a, b))`, which could be made to something like:
```c
#define EMIT_REL(at, to) EMIT_CHECKED(at + 1, REL(at, to))
```

**Comment by jepler** [comment]
Thanks for the suggestion, I've updated this pull request.  I believe additional locations need to be tagged, such as
```diff
-            EMIT(term + 1, cnt);
+            EMIT_CHECKED(term + 1, cnt);
```
where cnt accumulates the number of bytes inside a character class.  Triggering case there would be the unreasonable regular expression
```python
>>> re.compile("[" + "a" * 256 + "]")
```

**Comment by dpgeorge** [comment]
Thanks for updating.  Squashed and merged in 172fb5230a3943eeb6fbbb4de1dc56b16e2a7637 with some more tests added to cover almost all cases.

**Comment by jepler** [comment]
Thanks!

**Pull request closed without merging**
