### PR TITLE
py/nlr: Fix 7232, add '_' prefix to function symbols for clang

### PR DESCRIPTION
**Pull request by eightycc**
Fixes issue 7232 by adding a '_' prefix to symbol names used as C function entry points.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.

I'm wondering if using `__clang__` is the right approach, considering 52b6764894755324db036731ae1d6ec77172419a which uses `#if defined(__APPLE__) || defined(__MACH__)`?  Or maybe the latter there should be changed to `__clang__` as well?

**Comment by eightycc** [comment]
I believe the problem is with Clang's handling of C function symbols regardless of OS, but I'm not 100% certain. I'll perform a test build with Clang on Ubuntu ARM64 to verify.

**Comment by eightycc** [comment]
I tested on Ubuntu ARM64 and found that I was wrong, it is a MacOS ABI issue. I'll rework and push the updated patch. Thank you for catching that.

**Comment by eightycc** [comment]
I have corrected my original patch to add a prefix underscore to C function symbols when targeting a Darwin OS. The proper way to do so is to test for \_\_APPLE\_\_ *and* \_\_MACH\_\_, where \_\_APPLE\_\_ tests for an Apple OS and \_\_MACH\_\_ tests that it is based on CMU Mach. Using both tests ensures that just Darwin (Apple's open source base for MacOS, iOS, etc.) is recognized. \_\_APPLE\_\_ by itself will test for *any* Apple OS, which can include older OS 7-9 and any future Apple OS. \_\_MACH\_\_ tests for *any* OS based on CMU Mach, including Darwin and GNU Hurd.

I have also added a commit that corrects similar logic in py/nlrx64.c so that it detects just Darwin. As originally written, it would evaluate true for *any* Apple OS and also for GNU Hurd.

**Comment by dpgeorge** [comment]
Thanks for updating, and for the detailed description (which was added to the commit message).  Merged in 126b1c727118352923703719a2a3d45b9fad3c97 and 7ceccad4e2f1e9d073f5781c32e5b377e8391a25

**Pull request closed without merging**
