### PR TITLE
esp32: Add temperature reading.

### PR DESCRIPTION
**Pull request by ticpu**
From source code of esp-idf in components/esp32/test/test_tsens.c
Temperature doesn't represent any particular unit and isn't calibrated.

### CODE REVIEW

**Comment by dpgeorge** [comment]
> And sure, I can add it to esp32 as an "internal_temperature_sensor" of some sort.

I think `esp32.temperature()` is good enough.  It's unambiguous and unlikely to clash with anything else in that module.

> Is there a place I can document it as such?

Not yet... there needs to be a section added to the docs describing esp32 specific things.  It'd be a good start to add documentation for the `esp32` module itself.

**Comment by ticpu** [comment]
Terminal ready

>>> import esp32
>>> esp32.temperature()
133

And it changes when in the freezer to about 105.

**Comment by dpgeorge** [comment]
Is it linearly correlated with actual degrees C?  Maybe the function can take optional calibration args for the offset and slope, and return the corrected value.

**Comment by ticpu** [comment]
A quick test shows that it is linear.

esp32.temperature | °C
-- | --
105 | -18
133 | 33
137 | 43
138 | 45
140 | 48
145 | 58
151 | 70

screenshot from 2018-07-10 00-20-48

**Comment by dpgeorge** [comment]
> shows that it is linear.

It's kind of close... `C = 2*esp32.temperature() - 230`.  But probably best in the end to just return the raw value and let the user do what they want with it.

**Comment by ticpu** [comment]
After more maths..


esp32.temperature | °C | °K |  
-- | -- | -- | --
105 | -18 | 255 | -18
133 | 33 | 306 | 35.5652173913043
137 | 43 | 316 | 43.2173913043478
138 | 45 | 318 | 45.1304347826087
140 | 48 | 321 | 48.9565217391304
145 | 58 | 331 | 58.5217391304348
151 | 70 | 343 | 70

=esp32.temperature() * (44/23) + (-5034/23)

**Comment by ticpu** [comment]
```
>>> import esp32
>>> esp32.temperature()
29
>>> esp32.temperature(True)
131
```

This will make it easier for new comers and will please power users.

**Comment by peterhinch** [comment]
This gives some idea of linearity
image

**Comment by dpgeorge** [comment]
Will the same calibration work on other boards?  It would need to be tested.

**Comment by ticpu** [comment]
We can not translate to degrees Celcius according to those numbers.

They are all four in the same part of the freezer, here are the numbers:

IP | datetime | NTP time | °C (raw)
-- | -- | -- | --
172.20.20.206 | (2018, 7, 11, 2, 2, 10, 0, 957124) | (584590200, 4170311143) | 10 (122)
172.20.20.211 | (2018, 7, 11, 2, 2, 10, 0, 960250) | (584590200, 4177098179) | -22 (106)
172.20.20.175 | (2018, 7, 11, 2, 2, 10, 0, 960728) | (584590200, 4180500218) | -11 (111)
172.20.20.230 | (2018, 7, 11, 2, 2, 10, 0, 960489) | (584590200, 4195499023) | 10 (122)

Here on the counter:

IP | datetime | NTP time | °C (raw)
-- | -- | -- | --
172.20.20.230 | (2018, 7, 11, 2, 2, 2, 42, 957248) | (584589762, 4154827614) | 23 (128)
172.20.20.206 | (2018, 7, 11, 2, 2, 2, 42, 957354) | (584589762, 4165126244) | 33 (133)
172.20.20.211 | (2018, 7, 11, 2, 2, 2, 42, 957886) | (584589762, 4165200830) | 0 (117)
172.20.20.175 | (2018, 7, 11, 2, 2, 2, 42, 957945) | (584589762, 4169246164) | 8 (121)

**Comment by dpgeorge** [comment]
I tested this PR with 2 boards, both just sitting on the bench.  The Wrover-Kit gives a raw value of 114-115 and the Lolin32 gives a raw value of 127-128.  So different devices would need different calibration.

**Comment by ticpu** [comment]
Alright, I'll revert to before adding conversion and at least it gives the user the option to calibrate.

On an unrelated note, they are still in the freezer and the ones with higher values tend to RTC drift more.

IP | datetime | NTP time (second, fraction (x/4294967295)) | °C (raw)
-- | -- | -- | --
172.20.20.175 | (2018, 7, 11, 2, 4, 5, 21, 957570) | (584597121, 4129685437) | -20 (106)
172.20.20.206 | (2018, 7, 11, 2, 4, 5, 21, 957414) | (584597121, 4171117107) | 0 (117)
172.20.20.211 | (2018, 7, 11, 2, 4, 5, 21, 957049) | (584597121, 4133028360) | -34 (100)
172.20.20.230 | (2018, 7, 11, 2, 4, 5, 21, 957506) | (584597121, 4217936817) | -1 (116)

**Comment by nickovs** [comment]
It's worth noting that the on-die temperature will vary significantly from the packaging temperature, which in turn will vary from the ambient temperature. My guess is that you're not going to find a good way to use this sensor to measure ambient temperature since it's going to depend on a host of other factors such as air flow. That said, knowing the die temperature is very useful for everything from clock calibration to knowing when to throttle the CPU so it would still be valuable to have access to this but it might make sense to not even try to return an absolute temperature that represents anything in the outside world.

**Comment by dpgeorge** [comment]
> Alright, I'll revert to before adding conversion and at least it gives the user the option to calibrate.

@ticpu did you get a chance to do this?

And perhaps the function should be named `esp32.raw_temp()` so it doesn't mislead users in to thinking it returns a degrees value.

**Comment by ticpu** [comment]
I was sure I had this pushed already, my bad. I didn't push it with the raw_ prefix and once calibrated, I guess it should be moved to the machine module and documentation should handle the case of explaining the kind of unit it returns.

**Comment by dpgeorge** [comment]
> I didn't push it with the raw_ prefix and once calibrated...

It's really up to the user to calibrate it in their script, so I do think that calling it `raw_temp()` makes it clear as to the value it returns.  And it means that if there ever were a calibrated version (added to the `esp32` module) it could be called `temperature()` and not break existing code.

**Comment by ticpu** [comment]
Alright, let's settle on esp32.raw_temperature() then, I'm not keen on using abbreviations, I just pushed it.

**Comment by dpgeorge** [comment]
Thanks for updating.  Now merged in 4f5b435d9bb6da9721051105e187adc5cc39164a, with minor edit to make the function take only 0 arguments.

**Pull request closed without merging**
