### PR TITLE
tools/normalise_mpconfigport.py: Add script to normalise config (WIP)

### PR DESCRIPTION
**Pull request by dpgeorge**

### CODE REVIEW

**Comment by robert-hh** [comment]
This script will does run on Debian 10, since the default Python version is 3.7. Python 3.7 does not support assignment expressions.

**Comment by dpgeorge** [comment]
I really like the walrus operator!

Anyway, updated to not use it.

**Comment by robert-hh** [comment]
Thanks. Agreed that it looks much better with the walrus operator. But the new code variant looks good. Very clear.

**Comment by dpgeorge** [comment]
This is not really needed now that we have ROM feature levels.

**Pull request closed without merging**
