### PR TITLE
backport of MrSurly/micropython-esp32@dev-deepsleep

### PR DESCRIPTION
**Pull request by mactijn**
This is a direct backport (?) of https://github.com/micropython/micropython-esp32/pull/85 by @MrSurly

A quick test reveals it still works as intended, but no extensive testing has been done.

### CODE REVIEW

**Comment by MrSurly** [comment]
@dpgeorge @nickzoic 

My understanding is that the existing PRs for the `micropython-esp32` repo are still considered active? 

If not, I can move them over.

**Comment by mactijn** [comment]
I wasn't aware of that, my apologies if I've breached protocol or something.

This patch and the WPS one are stuff I needed, so I backported them. Not wanting to waste the effort I put into it, I pushed these PRs.

**Comment by MrSurly** [comment]
> I wasn't aware of that, my apologies if I've breached protocol or something.

Not at all! I'm glad someone is using it.  Just don't want duplicated effort.

**Comment by mactijn** [comment]
I'm closing this PR again, as @MrSurly is continuing this in https://github.com/micropython/micropython/pull/3531

**Pull request closed without merging**
