### PR TITLE
tools/ci.sh: Fix setup of code-size CI job.

### PR DESCRIPTION
**Pull request by dpgeorge**

### CODE REVIEW

**Comment by dpgeorge** [comment]
@jimmo any clues what to do with `ci_code_size_build` so that it works like it did before, and can diff between master and the PR?  See also https://github.com/micropython/micropython/pull/6781#issuecomment-762869489

**Comment by stinos** [comment]
Probably have to treat the result of `git log upstream/master..HEAD --no-merges -1` as the `pull_request` branch.

**Comment by stinos** [comment]
@dpgeorge  you also need to set clone depth in the yml file

**Comment by jimmo** [comment]
I was just looking into this too -- the issue is that the working branch is shallow (has no commits other than the merge commit and the PR commits), so merge-base fails. I was going to suggest adding `git pull --ff-only --deepen=100` to the start of the function, but @stinos suggestion make more sense.

I'm not sure what to suggest about the merge commit... it doesn't prevent merge-base from doing the right thing (and it doesn't appear to be always there), so I think just that one change to increase the clone depth should be sufficient to fix this?

Also, while you're at it, I think you can add `master` to the end of the `git fetch --depth=100 upstream` line to force it to only get the history for the one branch.

**Comment by dpgeorge** [comment]
Ok, this looks like it's now working.  Changes are:
- fetch-depth increased from 1 (default) to 100 (as suggested by @stinos)
- added "master" to git-fetch (as suggested by @jimmo)

**Pull request merged**
