### PR TITLE
asyncio/stream: Catch and ignore ECONNRESET.

### PR DESCRIPTION
**Pull request by ned-pcs**
This commit deals with ECONNRESET (and EPIPE) exceptions while reading from sockets.
For more context, see https://github.com/micropython/micropython-lib/issues/788

### CODE REVIEW

**Comment by ned-pcs** [comment]
I see that the Unix tests that expected to see the ECONNRESET exception have failed.
Without this commit, my ESP32 client reading from a Unix micropython server would get ECONNRESET errors, though a Unix client didn't.

**Comment by Carglglz** [comment]
@ned-pcs this makes the those tests pass 
```py
...
 except OSError as exc:
    if exc.errno in (ECONNRESET, EPIPE) and r:
        return r
    raise

```

Could this work in ESP32? 👀

**Comment by ned-pcs** [comment]
@Carglglz I tried the logic you showed (`    if exc.errno in (ECONNRESET, EPIPE) and r:`) but that didn't eliminate the problem on the ESP32 side.
@dpgeorge My current test program uses Microdot as a server; I will write a simplified version that doesn't use Microdot when I get some time.

**Comment by Carglglz** [comment]
@ned-pcs I think this can be closed, see #13533 for a possible fix.

**Comment by ned-pcs** [comment]
@Carglglz I have tested your #13533 fix and it works. Closing.

**Pull request closed without merging**
