### PR TITLE
Update oofatfs to R0.13c

### PR DESCRIPTION
**Pull request by dpgeorge**
This updates the oofatfs component (based on FatFS) to the latest R0.13c.

Code size change is:
```
   bare-arm:    +0 +0.000% 
minimal x86:    +0 +0.000% 
   unix x64:    +0 +0.000% 
unix nanbox:    +0 +0.000% 
      stm32:  +184 +0.050% 
     cc3200:  +160 +0.087% 
    esp8266:  +168 +0.026% 
      esp32:  +120 +0.011% 
```

### CODE REVIEW

**Comment by dpgeorge** [comment]
@iabdalkader I did some basic tests with this and it seems OK, but would be good to do a few more before merging it.

**Comment by iabdalkader** [comment]
I already merged my updated FF13C PR into OpenMV code, and I've been using it for a while, it's working fine. I'll make a more extensive test script and send it anyway.

**Comment by dpgeorge** [comment]
Would be good to address #4305 as part of this update.

**Comment by iabdalkader** [comment]
Would this fix the issue ?

```
    if (disk_ioctl(fs->drv, GET_SECTOR_SIZE, &ssize) != RES_OK) return FR_DISK_ERR;
    if (sz_vol * ssize < 128 * 512) LEAVE_MKFS(FR_MKFS_ABORTED);  /* Check if volume size is >=128s */
```
Note the minimum is now 128 blocks. Anyway, I used the following script to test all the basic functions.

```
import os

# Create file
f = open("test.txt", "w")
f.close()

# Test open
if not "test.txt" in os.listdir():
    raise Exception("Failed to create file!")

# Test write
f = open("test.txt", "w")
f.write("HelloWorld!")
f.close()

# Test read
f = open("test.txt", "r")
buf = f.read()
f.close()

if buf != "HelloWorld!":
    raise Exception("failed to write to file!")

# Test seek
f = open("test.txt", "w")
f.seek(0)
f.write("Hello")
f.close()

# Test read
f = open("test.txt", "r")
buf = f.read()
f.close()

if buf != "Hello":
    raise Exception("Failed to seek and write to file!")

# Test append
f = open("test.txt", "a")
f.write("World!")
f.close()

# Test read
f = open("test.txt", "r")
buf = f.read()
f.close()

if buf != "HelloWorld!":
    raise Exception("Failed to append to file!")

# Test unlink
os.unlink("test.txt")
if "test.txt" in os.listdir():
    raise Exception("Failed to unlink file!")
```

**Comment by dpgeorge** [comment]
> Would this fix the issue ?

The sector size is already computed in the variable `ss` so no need to compute it again.  And then the formula should probably use division so it doesn't overflow the multiplication for >4gb cards.  Eg:
```c
if (sz_vol < 25 * 1025 / ss) LEAVE_MKFS(FR_MKFS_ABORTED);
```

**Comment by dpgeorge** [comment]
Sorry, that formula should round up, like this:
```c
if (sz_vol < (25 * 1024 + ss - 1) / ss) LEAVE_MKFS(FR_MKFS_ABORTED);
```

**Comment by dpgeorge** [comment]
Upstream oofatfs was updated to fix #4305, and I pulled that new version into this PR.

This should be good to go in now.

**Comment by dpgeorge** [comment]
This was merged in 1a24bac6cb3dcb7418c20040149ca19050913109 through b5f33ac2cb6076468a77f36d69df6db16b62134a

**Pull request closed without merging**
