### PR TITLE
ports/esp32/modnetwork.c: Added WPS.

### PR DESCRIPTION
**Pull request by eydam-prototyping**
Added WPS (PIN and PBC-Mode) for ESP32.

Signed-off-by: Tobias Eydam <eydam-prototyping@outlook.com>

### CODE REVIEW

**Comment by eydam-prototyping** [comment]
I added WPS-Support, since #4464 was not merged. I considered the post from @dpgeorge in the PR. I think, it shoud be ok now.

You can test this commit by running this code:

```python
import network
import time

wlan = network.WLAN()
wlan.active(True)

wlan.connect(wps=True)
while wlan.status() == network.STAT_WPS_PROBING:
    print(".")
    time.sleep(1)

if wlan.status() == network.STAT_CONNECTING:
    print("WPS finished, connecting to " + wlan.config("essid"))
else:
    print("WPS failed")
    return

while wlan.status() == network.STAT_CONNECTING:
    print(".")
    time.sleep(1)
    
if wlan.isconnected():
    print("successfully connected")
    print(wlan.ifconfig())
```
Or you can use WPS-PIN-Mode:

```python
import network
import time

wlan = network.WLAN()
wlan.active(True)
wlan.connect(wps=True, wps_mode=network.WPS_TYPE_PIN)
print("Enter WPS-Pin into Router: " + wlan.config("wps_pin"))
while wlan.status() == network.STAT_WPS_PROBING:
    print(".")
    time.sleep(1)

if wlan.status() == network.STAT_CONNECTING:
    print("WPS finished, connecting to " + wlan.config("essid"))
else:
    print("WPS failed")
    return

while wlan.status() == network.STAT_CONNECTING:
    print(".")
    time.sleep(1)
    
if wlan.isconnected():
    print("successfully connected")
    print(wlan.ifconfig())
```
When the ESP32 is connected to the WiFi, you can read the password via `wlan.config("password")` and store it for the next boot.

Please let me know what you think.

**Comment by eydam-prototyping** [comment]
Is there anything I can do to get this merged?

**Comment by stritti** [comment]
would be really awesome to have this feature 💕

**Comment by WaGi-Coding** [comment]
all the wps topics somehow die ._. Would be great to have WPS functionality

**Comment by lomby92** [comment]
@eydam-prototyping why did you close this PR?

**Pull request closed without merging**
