### PR TITLE
tools/mpremote: Improve speed of echoing device data to console.

### PR DESCRIPTION
**Pull request by dpgeorge**
By reading and writing in chunks.

When connected to a device that is constantly outputting data, this gets mpremote CPU usage down from about 90% to 5% (on my local machine).

### CODE REVIEW

**Comment by jimmo** [comment]
Related to the lines included in this change -- I saw reported elsewhere that it would be good to just pass the bytes straight through to the terminal, and add a special mode to escape unprintables. The rationale is that this breaks unicode output, and that should work by default.

**Comment by dpgeorge** [comment]
> I saw reported elsewhere that it would be good to just pass the bytes straight through to the terminal, and add a special mode to escape unprintables

Yes I agree.

What should the mode be, `--escape-non-ascii`?  And just ignore utf-8?  Otherwise it's quite tricky to interpret utf-8 when the characters are split up.

**Comment by jimmo** [comment]
I was thinking either `--escape` or `--no-raw`. (i.e. `--raw` is the default). Prefer `--escape`.

I don't think you need to do anything fancy w.r.t. utf-8. If the user wants escaping then unfortunately utf-8 will be escaped, but the point is that you're using --escape for debugging (or similar) and so not seeing utf-8 doesn't seem like a problem.

In the raw (default) mode, you don't need to do anything, the terminal will just do the right thing.

**Comment by dpgeorge** [comment]
I added an `--escape` option, disabled by default.

**Comment by dpgeorge** [comment]
Escape option renamed to `--escape-non-printable`.

**Pull request merged**
