### PR TITLE
mimxrt/sdram: Add SDRAM support.

### PR DESCRIPTION
**Pull request by alphaFred**
Adds support for SDRAM. 

Many thanks to @robert-hh  for his continuing support.

### CODE REVIEW

**Comment by alphaFred** [comment]
@dpgeorge 
As promised, my next PR for `mimxrt` port :-) Many thanks for your time in advance. Looking forward to your review.

**Comment by alphaFred** [comment]
Hi @dpgeorge, @robert-hh noticed a small bug that caused an issue for the MIMXRT1064-EVK. I fixed it now.
PR is ready for review.

**Comment by alphaFred** [comment]
@dpgeorge thanks a lot for your review. I have fixed your comments.
As always let me know if the change can be merged. I will rebase to latest master and squash then myself.

**Comment by dpgeorge** [comment]
Ok, looks good now!  Please rebase and squash to make it ready for merging.

**Pull request merged**
