### PR TITLE
rp2/tusb_port.c: Allow boards to configure USB VID and PID.

### PR DESCRIPTION
**Pull request by iabdalkader**

### CODE REVIEW

**Comment by mcauser** [comment]
All of the Adafruit RP2 boards are configured with VIDs and PIDs. eg.
https://github.com/adafruit/circuitpython/blob/main/ports/raspberrypi/boards/adafruit_feather_rp2040/mpconfigboard.mk

Add them to this PR too?

**Comment by iabdalkader** [comment]
@mcauser Add them how do you mean ?

**Comment by mcauser** [comment]
@iabdalkader Inside each `mpconfigboard.h` file add the board's specific macros:

```
#define USBD_VID = 0x239A
#define USBD_PID = 0x80F2
```

I have a [bunch of open PRs](https://github.com/micropython/micropython/pulls?q=is%3Aopen+is%3Apr+author%3Amcauser+rp2%2Fboards) for other RP2 boards.
If this one gets merged first, I can append the macros to each of my PRs.
Or sort it all out later.

**Comment by iabdalkader** [comment]
@mcauser Added VID/PID for ADAFRUIT_FEATHER_RP2040.

**Comment by dpgeorge** [comment]
Thanks for this, it's a needed improvement.

But do you think it makes sense to call the config values `MICROPY_HW_USBD_VID` and `MICROPY_HW_USBD_PID`, to match other "hardware" based config values?  Other ports like stm32 already use `USBD_VID` and `USBD_PID`, so they should also (eventually) be changed as well to prefix `MICROPY_HW_` if we choose to use these names here.

So the choice is:
- stick with `USBD_VID` and `USBD_PID`
- use `MICROPY_HW_USBD_VID` and `MICROPY_HW_USBD_PID` in this PR, and change other ports to match in a separate PR

**Comment by iabdalkader** [comment]
> use `MICROPY_HW_USBD_VID` and `MICROPY_HW_USBD_PID` in this PR, and change other ports to match in a separate PR

@dpgeorge I choose 2 I think we should stop copying this inconsistency from port to port.

**Comment by iabdalkader** [comment]
@dpgeorge Although I think it should be called `MICROPY_HW_USB` instead of `MICROPY_HW_USBD` like all the other USB related macros in rp2, nrf and stm32 ports.

**Comment by dpgeorge** [comment]
> Although I think it should be called `MICROPY_HW_USB` instead of `MICROPY_HW_USBD` to match all the other USB related macros in rp2, nrf and stm32 ports, and because it's not necessarily a USB device it could be a host.

Does a USB host have a VID/PID?  A hub will have a VID/PID but that's because it's a device and a host, and it's the device side that has the VID/PID.

Regardless of that, I agree it makes sense to use `MICROPY_HW_USB` as the prefix because it does match all the other constants.  I guess it's just a question of `MICROPY_HW_USB_DEV_VID` vs `MICROPY_HW_USB_VID`.

**Comment by iabdalkader** [comment]
> Does a USB host have a VID/PID? A hub will have a VID/PID but that's because it's a device and a host, and it's the device side that has the VID/PID.

No I don't think so, but macros like `MICROPY_HW_USB_HS` can be used for a host or a device. But if only a device would use them, then there's no need to make the distinction between host/device, otherwise all the other macros should also be changed to `MICROPY_HW_USB_DEV_` or `MICROPY_HW_USBD_`. Alternatively we could use `MICROPY_HW_USB_HOST_` when the distinction is needed. Either way is fine by me as long as they're consistent in board files and across ports.

**Comment by dpgeorge** [comment]
> ... otherwise all the other macros should also be changed to `MICROPY_HW_USB_DEV_` or `MICROPY_HW_USBD_`. Alternatively we could use `MICROPY_HW_USB_HOST_` when the distinction is needed.

Ok, yes, let's leave it as `MICROPY_HW_USB_VID` etc.

**Comment by dpgeorge** [comment]
Merged in 7ae9e6ef6900ad2d386bf5453b47a89b026b51f1 and 23e2e0077910a7a47c0c0fc752b9056bdccfd5bb

**Comment by dpgeorge** [comment]
See follow up #7603.

**Pull request closed without merging**
