### PR TITLE
smthal: automate generation of headers for all flash files

### PR DESCRIPTION
**Pull request by SpotlightKid**
At the moment, the source for the files, which are written to a board's flash drive, when it is initialized (`boot.py`, `main.py`, `README.txt`) is inlined into `main.c` as static char arrays. Only for `pybcdc.inf` a header file is generated and included in `main.c`. The source snippets for the other files are generated with `tools/file2h.py` but have to be inserted into `main.c` manually, it seems.

This makes it impossible to customize the contents of the files in flash, without changing the source code and having to mess with custom branches etc. when you want to track MicroPython development.

This PR changes `main.c` to include all the above files from headers files and adds rules to `stmhal/Makefile` to integrate the generation of these headers into the build. `tools/file2.py` is replaced with a version, which outputs full header files and also encodes the input files as char arrays with each byte as a hexadecimal literal. This avoids having to deal with line endings and escaping quotes etc. It also generates a `size_t` variable with the size of the array.

Input files are located in `stmhal/flash_files` (similar to `teensy/memzip_files`) and the PR also moves the input template for `pybcdc.inf` there. Input files have CRLF line endings and are marked in `.gitattributes` with `-text`, so git does not convert line endings on these files. Generated headers are placed in `$(BUILD)/genhdr` like other make generated files.

I have also fixed (IMHO) `tools/insert-usb-ids.py`  to ensure it outputs a file with CRLF line endings.

The upshot of all this is, that with this PR it is possible to run

```
$ make BOOT_PY_SRC=/path/to/my/boot.py
```

to compile in a custom `boot.py` file (or `MAIN_PY_SRC` for `main.py` and `README_TXT_SRC` for `README.txt`). Due to how `file2h.py` is implemented though, the source ''filenames'' must be the same, i.e. exactly `boot.py` , `main.py` resp. `README.txt`, otherwise the generated variable names will be wrong and `main.c` compilation will fail.

It is also not possible to include additional files this way, since it is still hard-coded into  `main.c` which generated headers are included and which files are written when the flash is initialized.

I'm not an expert on Makefiles, so I hope the rules I have added and the changes I have made, make sense. I have tested building and flashing a firmware for the STM32F4DISC and when I perform the flash initialization, all files are created correctly.

### CODE REVIEW

**Comment by dpgeorge** [comment]
This is a good idea, and it could be extended to include other files (kind of like a FROZEN dir for frozen scripts).  But I'm curious: why do you need to customise the factory boot.py/main.py/README?

**Comment by SpotlightKid** [comment]
@dhylands Thanks for the hints. I have to test how these work together with the file `pybcdc.inf`, which is generated in itself.

@dpgeorge The initial reason I came up with this is that I have a STM32F4DISCOVERY board, without a USB OTG connector, so I use it with a USB-to-serial adapter. I can enable the REPL on UART6 via the board config, but then I always have to remember to switch to a custom branch where I made the appropriate changes to `mpconfigboard.h`, keep that branch updated, etc. Being able to customize `boot.py` via the make command, simplifies things very much.

Also, I generally switch off USB storage mode, because it is annoying to have the drive auto-mount dialog pop up each time I plugin in a board (not the one without the USB connector).

Another reason would be simplifying deployment of a whole application. With one command you can bake your modules via `FROZEN_DIR` into the firmware and customize `boot.py` to enable the USB mode you need, and `main.py` to have something like:

    from myapp import main; main()

Then your board is ready to go with just one firmware upload command, no need to switch cables to upload files, or press buttons to activate DFU mode, etc.

**Comment by dpgeorge** [comment]
Thanks @SpotlightKid for the discription.  I think a better way might be to simply put your custom boot.py and/or main.py in to the FROZEN_DIR.  I think they override anything in the filesystem and so that workflow should already work.

**Comment by SpotlightKid** [comment]
No, I think I tested that for `boot.py` and it didn't work. I'll recheck.

**Pull request closed without merging**
