### PR TITLE
rp2: Override mpconfigboard.cmake manifest from the command line.

### PR DESCRIPTION
**Pull request by iabdalkader**
* Make cmd FROZEN_MANIFEST override both the default and board manifests.

### CODE REVIEW

**Comment by dpgeorge** [comment]
This is a common problem with the esp32 port, and there the solution is to selectively set the frozen manifest with:
```
if(NOT MICROPY_FROZEN_MANIFEST)
    set(MICROPY_FROZEN_MANIFEST ${MICROPY_PORT_DIR}/boards/manifest.py)
endif()
```
That's a pretty ugly solution because every `mpconfigboard.cmake` file must have that.

What we need is a way to override the manifest via:
- `make FROZEN_MANIFEST=mymanifest.py`
- `cmake -D MICROPY_FROZEN_MANIFEST=mymanifest.py`

(In cmake, all uPy variables are prefixed with `MICROPY_`, hence the name difference there.)

Maybe a good way to do this is, at the start of `CMakeLists.txt` *before* `mpconfigboard.cmake` is included, detect if `MICROPY_FROZEN_MANIFEST` has been set or not (from the command line).  Then if it has this value overrides everything.  Otherwise the default value is obtained, either from the board or the generic manifest.

**Comment by iabdalkader** [comment]
> That's a pretty ugly solution because every mpconfigboard.cmake file must have that.

I agree, that was my initial thought then I realized exactly that.

> before mpconfigboard.cmake is included

`mpconfigboard.cmake` will then override it, that's why I changed the variable name passed to cmake (in Makefile) to `FROZEN_MANIFEST`, so `mpconfigboard.cmake` doesn't override it.

I think the current PR is the most straightforward, alternatively here's another option. Let me know if you want this instead and I'll amend the PR.

```cmake
set(MICROPY_USER_FROZEN_MANIFEST ${MICROPY_FROZEN_MANIFEST})

# Include board config
include(${MICROPY_BOARD_DIR}/mpconfigboard.cmake) 

# Set the frozen manifest file
if (NOT MICROPY_FROZEN_MANIFEST)
    set(MICROPY_FROZEN_MANIFEST ${PROJECT_SOURCE_DIR}/boards/manifest.py)
endif()

# Command line manifest takes precedence over the default/board manifest
if (MICROPY_USER_FROZEN_MANIFEST)
    set(MICROPY_FROZEN_MANIFEST ${MICROPY_USER_FROZEN_MANIFEST})
endif()
```

**Comment by dpgeorge** [comment]
I would like to keep it such that the user-facing variable name for configuring the cmake build is `MICROPY_FROZEN_MANIFEST`.

Your solution in the comment above would satisfy this, and I'd prefer that to what's currently in this PR.

Another way to do it, is have the boards use a different variable name like `MICROPY_DEFAULT_FROZEN_MANIFEST`, then:
```cmake
# Include board config, it may override MICROPY_DEFAULT_FROZEN_MANIFEST
set(MICROPY_DEFAULT_FROZEN_MANIFEST ${PROJECT_SOURCE_DIR}/boards/manifest.py)
include(${MICROPY_BOARD_DIR}/mpconfigboard.cmake) 

# Set the frozen manifest file if it's not already specified
if (NOT MICROPY_FROZEN_MANIFEST)
    set(MICROPY_FROZEN_MANIFEST ${MICROPY_DEFAULT_FROZEN_MANIFEST}
endif()
```

**Comment by iabdalkader** [comment]
I went with my suggestion above to avoid changing the board manifest config name.

**Comment by dpgeorge** [comment]
Great, thanks for updating.  Merged in df86cef59ac3f92fcdc433e4679c8243a8c3159d

Eventually would be good to update the esp32 port to follow how it's done here.

**Comment by iabdalkader** [comment]
> Eventually would be good to update the esp32 port to follow how it's done here.

Yeah I can fix it too. It seems this is repeated in every single board config file:
```
if(NOT MICROPY_FROZEN_MANIFEST)
    set(MICROPY_FROZEN_MANIFEST ${MICROPY_PORT_DIR}/boards/manifest.py)
endif()
```

**Pull request closed without merging**
