### PR TITLE
py/objint: Make byteorder argument optional in byte-conversion methods.

### PR DESCRIPTION
**Pull request by AmirHmZz**
This PR intends to make `byteorder` argument optional in `int.to_bytes()` and `int.from_bytes()` methods. According to [CPython documentation](https://docs.python.org/3/library/stdtypes.html#int.to_bytes), `byteorder` argument is optional and set to "big" by default. This PR makes Micropython compatible with CPython in this case.

### CODE REVIEW

**Comment by projectgus** [comment]
Hi @AmirHmZz,

Thanks for sending the PR for this!

>

**Comment by projectgus** [comment]
Hi @AmirHmZz,

Thanks for noticing this and submitting this PR.

> According to [CPython documentation](https://docs.python.org/3/library/stdtypes.html#int.to_bytes), byteorder argument is optional and set to "big" by default. This PR makes Micropython compatible with CPython in this case.

To expand a bit on this, these `byteorder` arguments only became optional in CPython 3.11 ([3.10 version is here](https://docs.python.org/3.10/library/stdtypes.html#int.to_bytes)). MicroPython only advertises full compatibility with [CPython 3.4](https://docs.micropython.org/en/latest/genrst/index.html) at this point.

That said, there are a number of improvements from later CPython versions that are supported in MicroPython and this one might be useful to have. :grin:

I was going to suggest adding unit test cases for these as well, although it will be a little fiddly because the unit tests compare behaviour with CPython by default only some CPython versions will accept the optional argument.

**Comment by projectgus** [comment]
I asked @dpgeorge about this change and it seems like it really will depend on the code size hit as to whether it's desirable to merge. It's currently small, which is encouraging.

However, Damien noted that in Python 3.11 the `int.to_bytes()` function also gained a default value for the `length` argument. What's the size impact if this is added as well? It's desirable to keep the CPython compatibility changes consistent as possible, although if that additional change somehow has much higher code size impact then it can be dropped.

> Where should I add unit tests? I will be glad to contribute!

Thanks, that'd be great!

`tests/basic/int_bytes.py` has the current test cases for `int.to_bytes` and `int.from_bytes`. However, this test file works by comparing output to CPython which won't be consistent for this change. You'll need to do something like `tests/basics/string_format_cp310.py` and `tests/basics/string_format_cp310.exp` which has the test case and expected output in separate files.

Suggest something like `int_bytes_optional_args_cp311.py`.

> making that arg optional is reducing redundant allocations and deallocations on "big" string which is used in most cases. I use int>bytes and bytes>int conversions many many times in my projects and most of them are in the loops.

I would have expected if you're either freezing your .py files into the firmware, or compiling to .mpy with mpy-cross, then the "big" string should end up interned as a QSTR with minimal performance impact. If you've got some "real world" type code where this change makes a significant performance difference, please share it as it'd be interesting to look into.

**Comment by AmirHmZz** [comment]
@projectgus Thanks for feedback. I've added tests and also made length optional in `int.to_bytes()`.

**Comment by projectgus** [comment]
Nice work @AmirHmZz, thanks! Implementation and tests look good to me. It's encouraging this implementation is free or almost free in terms of code size on most of the smaller microcontroller ports.

**Review by projectgus — APPROVED** [review]
Looks good to me, I think whether this is merged will come down to @dpgeorge's call about the binary size cost.

**Comment by projectgus** [comment]
One thing about the optional length argument for `int.to_bytes()`, currently MicroPython will truncate to the length if the int doesn't fit (CPython raises an exception.) Which may be a bit counter-intuitive. However, I have a PR open (#13087) which changes the behaviour to match CPython on this.

(Regrettably, that PR adds more than 8 bytes binary size! :laughing:)

**Comment by AmirHmZz** [comment]
I've rebased this PR against `mater`.

**Comment by projectgus** [comment]
This still looks good to me, and the code size impact is pretty small, but we'll need to wait for @dpgeorge to take a look now.

**Review by projectgus — APPROVED** [review]

**Comment by dpgeorge** [comment]
Thanks for this, it does look good now: CPython compatibility with minimal code size increase.

Rebased and merged!

**Pull request merged**
