### PR TITLE
esp8266 additions: sys.stdXXX.buffer, and loading of .mpy files

### PR DESCRIPTION
**Pull request by dpgeorge**
There are 2 independent commits here, that both add features to the esp8266 port:
1. Enable sys.{stdin,stdout,stderr}.buffer to allow binary IO over stdio (as opposed to default text IO).  This helps to write portable code across ports, knowing that sys.stdXXX.buffer is connected to the REPL/serial port.  Adds 176 bytes to code size.
2. Enable loading of precompiled .mpy files.  This allows to use mpy-cross to make a .mpy file, copy it across to the board, then it can be imported.  Helps to reduce memory usage (since there's no compiling of the module on board) without having to use frozen modules and recompiling the firmware.  Adds 1452 bytes to code size.

### CODE REVIEW

**Comment by hosaka** [comment]
The mpy-cross commit is long awaited and it would be great to see this finally added! Some docs to go along with it for the esp8266 might be due as well.

**Comment by pfalcon** [comment]
+1

**Comment by robert-hh** [comment]
I support both changes. Maybe you could support mpy files to wipy too at that time, by just adding this single line "#define MICROPY_PERSISTENT_CODE_LOAD (1)" to mpconfigport.h. It was you, Damien, who gave that hint.

**Comment by dpgeorge** [comment]
> Maybe you could support mpy files to wipy too at that time,

Well, this is really up to @danicampora .  I'd fully support enabling it because it'll help reduce RAM usage for the compilation/import stage.  Downside is that WiPy would lose about 1k of heap, but I think that's acceptable.

**Comment by robert-hh** [comment]
On interesting property of this merge is its forgivingness: It's indeed sys.stdXXX.buffer.read, sys.stdXXX.buffer.write, ...., and it does not matter whether XXX is in, out or err. Only the actual function counts. So you can write sys.stdout.buffer.read(x)

**Comment by danicampora** [comment]
> Well, this is really up to @danicampora . I'd fully support enabling it because it'll help reduce RAM usage for the compilation/import stage.

+1 :-)

**Pull request merged**
