### PR TITLE
top: Update `help()` output.

### PR DESCRIPTION
**Pull request by jimmo**
- Make all ports use the same wording and correct docs link.
- Don't include unavailable features in STM32 help output.

_This work was funded through GitHub Sponsors._

### CODE REVIEW

**Comment by jimmo** [comment]
@dpgeorge Can we also change https://micropython.org/help/ to do a redirect to https://docs.micropython.org/

(That page currently links to https://micropython.org/doc/ which is 404. I guess that could also redirect to the docs?)

**Comment by dpgeorge** [comment]
I have change micropython.org:
- removed "Help!" link from the footer
- made /help redirect to the docs (as such, the old help page is gone)

**Comment by dpgeorge** [comment]
The mimxrt port is failing, but that should be a simple fix.

**Comment by dpgeorge** [comment]
A nice clean up, thanks!

**Pull request merged**
