### PR TITLE
unix: Enable uasyncio on dev variant.

### LINKED ISSUE #6109: uasyncio on unix port
Currently uasnycio is not compiled into the unix port but it does work if I copy the extmod/uasyncio directory into the library path of the unix port (and I think I had to change something in the build options but I can't remember, it's long ago and I'm currently setting up my PC again so can't test yet).

Would be good to have it available on the unix port too.

### PR DESCRIPTION
**Pull request by jimmo**
- Fixes up the usage of manifest.py on unix port to match other ports.
- Enables MICROPY_PY_UASYNCIO and the uasyncio manifest on dev variant.

I wonder if we should also enable this in the default "standard" build too, but either way that's separate to this.

Fixes #6109

### CODE REVIEW

**Comment by dpgeorge** [comment]
Did the frozen test script get deleted accidentally, or not checked in after a mv?

**Comment by jimmo** [comment]
There's a sneaky .gitignore for *.py in ports/unix that caught me out. Fixed. (I like this .gitignore entry though)

**Comment by dpgeorge** [comment]
It looks like the manifest files were also not checked in after the mv (there are 3 missing, the default one, and one for dev and coverage builds).

**Comment by dpgeorge** [comment]
Merged in 27abac95d87b69f4282e2ca21ab19eff7bf6012b and 4050281311744ae5946aa1faec8aa75339bcab2b (with minor changes, coverage build doesn't include default manifest).

**Pull request closed without merging**
