### PR TITLE
py/repl: Check for a space or lparen after the keyword.

### PR DESCRIPTION
**Pull request by hosaka**
Reported in #1850. Each keyword needs to have a space or a lparen right after. I didn't want to write extra functions or add variables, so the macro might not the most elegant option, but we can use any other method.

### CODE REVIEW

**Comment by hosaka** [comment]
As an argument against myself, strlen() is executed at run time, which is probably not necessary to determine the length for a handful of constant strings.

**Comment by pfalcon** [comment]
Thanks for looking into my bugreport ;-). But indeed, why use strlen() and not sizeof()? gcc will optimize strlen(), but we're writing in C here, right? Also, I'd personally be ok even with testing just for space. Because addition of '(' is more or less random - there can be a lot more other things. You'd be surprised which:

~~~
>>> if.1 != 2:
...  print(1)
... 
1
~~~

So, there "correct" way to deal with it would be by testing than char after keyword is not ident char (alnum or '_'). But again, checking just for space would be enough in my list - people who write dirty code like above call for surprises.

**Comment by hosaka** [comment]
Always glad to help! You're right, no need to use strlen(). Without the '(' check the following becomes invalid:
```python
if(1==1):
```
It will then have to be neither of: ident, allnum, '_' or '(' for the above case to work.

**Comment by dpgeorge** [comment]
@hosaka only line 41 of repl.c should need changing.

**Comment by pfalcon** [comment]
> following becomes invalid:
> if(1==1):

This is as valid regarding code style as "if.1!=2:". Most likely, it's invalid - there should be space, period.

**Comment by hosaka** [comment]
@dpgeorge You're right, I didn't think of that.
@pfalcon I left the only check for a single space, and the test cases.

**Comment by pfalcon** [comment]
Sorry, given the content of the line @dpgeorge pointed to, the "proper" solution I mentioned above is the only viable choice. I suggest applying following patch:

~~~
-/*
-bool unichar_is_alpha_or_digit(unichar c) {
-    return c < 128 && (attr[c] & (FL_ALPHA | FL_DIGIT)) != 0;
+// An "identifier" char - alpha, digit, or underscore
+bool unichar_isident(unichar c) {
+    return c < 128 && ((attr[c] & (FL_ALPHA | FL_DIGIT)) != 0 || c == '_');
 }
-*/
+
~~~

And the just use unichar_isident() instead of unichar_isalpha() in line 41.

**Comment by hosaka** [comment]
Makes sense, since alnum and underscores are the only chars allowed in the identifier, there must have been a reason for commenting out the original `unichar_is_alpha_or_digit`. I hope you don't mind, I have applied your patch.

**Comment by pfalcon** [comment]
Thanks. +1 from me.

**Comment by dpgeorge** [comment]
Function should be named "isident" not "isindent".  (And it kind of duplicates lexer.c:is_tail_of_identifier.  Except the latter supports utf-8 identifiers.)

**Comment by hosaka** [comment]
Typo fixed. The `is_tail_of_identifier` practically does the same thing, it would be best to avoid duplicating code, but it is local to lexer only.

**Comment by pfalcon** [comment]
The problem of is_tail_of_identifier is that it takes mp_lexer_t*. So, merging as is.

(For folks who care, we have 2 identical copies of log_base2_floor in codebase.)

**Comment by dpgeorge** [comment]
Rebased and merged in 69d9e7d27d62d54c0625d4181c80478b0313384d.

**Pull request closed without merging**
