### PR TITLE
Use mp_stack API instead of local pointer for gc_collect and stack initialization

### PR DESCRIPTION
**Pull request by kklimek**
This change allows to embed micropython as library without REPL and use gc_collect

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.  It looks good, but I'm just unsure how it "allows to embed micropython as library without REPL and use gc_collect"?

**Comment by kklimek** [comment]
I'm using MicroPython in separate Zephyr thread, next to our core system. This means that I don't use main.c that initializes heap. Instead I'm creating zephyr thread with MP on demand (when i.e. we have some extra BL to execute) that is more a helper then main app runner. When calling gc.collect() from python it crashes, because it relies on local pointers that are unitialied

**Comment by stinos** [comment]
>  This means that I don't use main.c that initializes heap

But you do initialize the heap, right? I.e. did you copy all initialization main.c does and call it from within the thread? Just asking because we're also running MicroPython in a seperate thread (Windows port, though that shouldn't matter) and do not have any problems, but we do call all initialization (`mp_stack_ctrl_init` `mp_stack_set_limit` `gc_init` `mp_pystack_init` `mp_init` and `mp_obj_list_init` for `mp_sys_path` and `mp_sys_argv`)

**Comment by kklimek** [comment]
Yes, I have whole initialization code in my thread, but zephyrs `gc_collect` implenetation uses local pointers from `ports/zephyr/main.c` instead of pointers available from `mp_stack` API

**Comment by kklimek** [comment]
So basicaly this is the case:

```
STATIC MP_NOINLINE mp_obj_t moramp_gc_collect(void) {
    void *dummy;
    gc_collect_start();
    gc_collect_root(&dummy, ((mp_uint_t)MP_STATE_THREAD(stack_top) - (mp_uint_t)&dummy) / sizeof(mp_uint_t));
    gc_collect_end();
    return mp_const_none;
}

MP_DEFINE_CONST_FUN_OBJ_0(function_moramp_gc_collect, moramp_gc_collect);

static void micropython_thread_loop(void *python_code_ptr, void *arg2, void *arg3) {
    python_code* code = python_code_ptr;
    printk("Starting python:\n%s\n", code->code);

    char mp_heap[MICROPY_HEAP_SIZE];

    mp_stack_ctrl_init();
    mp_stack_set_limit(MICROPY_HEAP_SIZE);
    memset(mp_heap, 0, MICROPY_HEAP_SIZE * sizeof(mp_heap[0]));
    gc_init(mp_heap, mp_heap + MICROPY_HEAP_SIZE);
    mp_init();

    mp_obj_t *moramp_module = mp_obj_new_module(QSTR_FROM_STR_STATIC(MORAMP_MODULE));
    mp_obj_dict_t* module_globals = mp_obj_module_get_globals(moramp_module);

    mp_obj_dict_store(module_globals, MP_OBJ_NEW_QSTR(QSTR_FROM_STR_STATIC("gc_collect")),
                      MP_OBJ_FROM_PTR(&function_moramp_gc_collect));

    mp_module_register(QSTR_FROM_STR_STATIC(MORAMP_MODULE), moramp_module);

    nlr_buf_t nlr;
    if (nlr_push(&nlr) == 0) {
        mp_lexer_t *lexer;
        lexer = mp_lexer_new_from_str_len(MP_QSTRnull, code->code, code->length, 0);
        mp_parse_tree_t parse_tree = mp_parse(lexer, MP_PARSE_FILE_INPUT);
        mp_obj_t compiled_code = mp_compile(&parse_tree, lexer->source_name, false);
        mp_call_function_0(compiled_code);
        nlr_pop();
    } else {
        mp_obj_print_exception(MICROPY_DEBUG_PRINTER, MP_OBJ_FROM_PTR(nlr.ret_val));
    }

    mp_deinit();
}
```

To prevent crashes I had to disable `gc_auto_collect_enabled` and call `moramp.gc_collect()` (exposed through registered module from C code) manualy. Otherwise it would crash on `gc_collect` calls

**Comment by stinos** [comment]
Ok looks good. Would be good to add that explanation to the commit message so it's clearer what it is about.

**Comment by dpgeorge** [comment]
Thanks for the explanation.  The commit message was updated and merged in 53f3cbc2c4f07236fe022c9c7af20b33443c60b1

**Pull request closed without merging**
