### PR TITLE
py/mkrules.mk: Show frozen modules sizes together with executable size.

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by pfalcon** [comment]
Let's eyeball it, see that it's big and needs optimization ;-)

**Comment by dpgeorge** [comment]
Doesn't this only work for unix, since bare-metal ports don't use the $(PROG) target?

**Comment by pfalcon** [comment]
> Doesn't this only work for unix, since bare-metal ports don't use the $(PROG) target?

Yes, but that's good start.

**Comment by dpgeorge** [comment]
Ok, well, unix doesn't even have frozen bytecode by default so the patch doesn't seem that useful... and it would look a lot prettier if the size was done in one go, eg:
```
$ size $(find build/build -name "frozen*.o") micropython
```

**Comment by pfalcon** [comment]
> Ok, well, unix doesn't even

Good, it means this change won't cause alarm. Though now it has it: https://github.com/micropython/micropython/commit/a4e38db30dacf6bd2d0b5c9221ca6efef7202a92

> if the size was done in one go, eg:

That makes it hard to check that at least one exists, but I'll look into doing it like that.

**Comment by pfalcon** [comment]
Ok, used command suggested by @dpgeorge in 4dc7c5649b0be88e542b4f7ec050a1d6e00d436c.

**Pull request closed without merging**
