### PR TITLE
qemu: Rename qemu-arm port to qemu.

### PR DESCRIPTION
**Pull request by dpgeorge**
Because this port now supports multiple architectures.

Follow-up to #15743.

### CODE REVIEW

**Comment by dpgeorge** [comment]
@agatti does this rename look good to you?

**Comment by agatti** [comment]
At a first glance it looks OK, although for #15714 I will have to rename `ports/qemu/test-frzmpy/frozen_asm.py` to make it unique to the Arm port and add a similar file for RV32 (and modify the makefiles to reflect that of course).

**Comment by dpgeorge** [comment]
> I will have to rename `ports/qemu/test-frzmpy/frozen_asm.py` to make it unique to the Arm port

That sounds fine, you can do that as part of #15714.

**Comment by dpgeorge** [comment]
@agatti this is now merged.

**Pull request merged**
