### PR TITLE
core: Add property getter/setter to runtime.c

### PR DESCRIPTION
**Pull request by v923z**
I had to clean up my repository, and this PR is really nothing but re-submitting https://github.com/micropython/micropython/pull/5648. All my comments from that thread are still valid. I hope this is OK.

### CODE REVIEW

**Comment by v923z** [comment]
@dpgeorge If you want to, you can close the PR: based on a comment (https://github.com/micropython/micropython/pull/5648#issuecomment-831531599), I have implemented class properties in a `numpy`-compatible way, so this feature is no longer required: https://github.com/v923z/micropython-ulab/releases/tag/3.0.0

**Comment by dpgeorge** [comment]
> I have implemented class properties in a `numpy`-compatible way, so this feature is no longer required

Do you mean this commit: https://github.com/v923z/micropython-ulab/commit/11965261827feae7f19a920bc3a41e03a3071ab6 ?

**Comment by v923z** [comment]
> Do you mean this commit: [v923z/micropython-ulab@1196526](https://github.com/v923z/micropython-ulab/commit/11965261827feae7f19a920bc3a41e03a3071ab6) ?

Exactly.

**Comment by jimmo** [comment]
Thanks @v923z

Seeing as you have a good alternative with `attr`, we'd prefer not to go with this approach as MicroPython tries to avoid the use of property objects in the core.

**Pull request closed without merging**
