### PR TITLE
extmod/modurandom: Add some extra random functions.

### PR DESCRIPTION
**Pull request by dpgeorge**
I implemented these for the microbit and some were non trivial (eg random float between 0 and 1) so thought they would be nice to have here, upstream.

Functions added are:
- randint
- randrange
- choice
- random
- uniform

Probably we want to have them configurable and disabled by default.  A lot of them can easily be coded in Python (ie in micropython-lib).  At the very least I think the random() function should stay.

### CODE REVIEW

**Comment by pfalcon** [comment]
Looks good.

> some were non trivial (eg random float between 0 and 1)

Well, the trivial implementation is to divide yasmarang() by 2.0^32 ;-). That wouldn't give as many bits as possible, but well...

> Probably we want to have them configurable and disabled by default.

Yep. They may be useful where they are, but I'd say even random() is easy in python.

**Comment by dpgeorge** [comment]
> Well, the trivial implementation is to divide yasmarang() by 2.0^32 ;-). That wouldn't give as many bits as possible, but well...

I don't know if that would give a uniform distribution between 0 and 1.  With double precision floats, you can cast a 32-bit int into the double (both the output of the PNRG and 2^32).  Dividing these numbers might give a uniform distribution, but definitely not the full range of fractions as you mention (and so maybe the holes in the 0..1 range are not evenly distributed).

For single precision it's not clear it would work very well, because 2^32 won't convert cleanly to a float, and, as well as not being a uniform output, you probably miss out on some fractions close to 1.0.

**Comment by dpgeorge** [comment]
This PR has been updated:

- new urandom functions are configured with MICROPY_PY_URANDOM_EXTRA_FUNCS (can anyone thing of a better name?)
- disabled by default, enabled for unix coverage build and stmhal
- added some tests for existing funcs (extmod/urandom_basic.py) and new ones (extmod/urandom_extra.py)

**Comment by dpgeorge** [comment]
Merged, see 0ae97f531d700119a3b07026c9e77069710303a6.

**Comment by dpgeorge** [comment]
@stinos this broke windows, sorry!  I thought I'd fixed it...  what to do to unbreak it?

**Comment by stinos** [comment]
No problem! Your last commit e713222 fixes the build itself but the urandom test fails because MICROPY_PY_URANDOM_EXTRA_FUNCS is not 1; in which case the test should be skipped, but it uses ```sys.exit(1)``` which should apparently be ```sys.exit()```. Well that, or MICROPY_PY_URANDOM_EXTRA_FUNCS should be set. Can you apply that or do you want a PR?

**Comment by dpgeorge** [comment]
I see, thanks.  I'll change it to sys.exit() then.

**Comment by dpgeorge** [comment]
Fixed in ac11e89fa37e64874a83611fbd7e894cc1a5be22.

**Pull request closed without merging**
