### PR TITLE
esp32: Convert to build using cmake as an IDF component (IDF v4.0.2)

### PR DESCRIPTION
**Pull request by dpgeorge**
This improves on #6473 and the esp32-idf41-cmake branch.  It uses IDF v4.0.2 and converts the esp32 port to fully use cmake and idf.py.  Traditional make support is removed.  Support for all existing boards is included.  WiFi and BLE work.

TODO:
- [x] make CI work
- [x] update esp32/README

### CODE REVIEW

**Comment by dpgeorge** [comment]
This should be good to go in now.

**Comment by jimmo** [comment]
This is really great, and hugely simplifies the ESP32 port, and glad to finally remove the v3/v4 IDF split. Thanks @dpgeorge !

I'm keen to see this merged, but I guess just so that it's recorded somewhere that I can link to, my understanding is that this means that we're temporarily removing support for (wired) LAN and user c modules. In the meantime, v1.14 and v1.13 firmware will still be available with LAN support, and user c modules can be built against the v1.14 tag until a cmake-based replacement is available.

Just as a note, is py/mkrules.cmake and py/py.cmake now identical to rp2/micropy_rules.cmake and rp2/micropy_py.cmake? (Separate PR though maybe)

**Comment by dpgeorge** [comment]
> this means that we're temporarily removing support for (wired) LAN and user c modules. In the meantime, v1.14 and v1.13 firmware will still be available with LAN support, and user c modules can be built against the v1.14 tag until a cmake-based replacement is available.

Yes, correct.

> Just as a note, is py/mkrules.cmake and py/py.cmake now identical to rp2/micropy_rules.cmake and rp2/micropy_py.cmake? (Separate PR though maybe)

No, they are different.  The rp2 versions were actually a precursor to the ones in this PR.  The aim is to migrate rp2 to use these new ones (which should improve rp2 build slightly because it'll now support ninja, and other minor improvements).

**Comment by UnexpectedMaker** [comment]
w00p! Great work @dpgeorge !

> I'm keen to see this merged, but I guess just so that it's recorded somewhere that I can link to, my understanding is that this means that we're temporarily removing support for (wired) LAN and user c modules. In the meantime, v1.14 and v1.13 firmware will still be available with LAN support, and user c modules can be built against the v1.14 tag until a cmake-based replacement is available.
> 

BTW, PPP works fine in MP with IDF4, so no idea why it's still being excluded.  One of my community members built IDF4 from source (pre cmake) and enabled the PPP stuff and it using it in their project without issue.

**Comment by dpgeorge** [comment]
> BTW, PPP works fine in MP with IDF4, so no idea why it's still being excluded.

PPP is included now.

**Comment by UnexpectedMaker** [comment]
> > BTW, PPP works fine in MP with IDF4, so no idea why it's still being excluded.
> 
> PPP is included now.

Thanks Damien!

**Pull request merged**
