### PR TITLE
webassembly/library: Decode string to print as utf-8.

### PR DESCRIPTION
**Pull request by Anton-2**
Current code is looping over bytes, and triggering one event for each. 
We can use UTF8ToString to decode the buffer directly, and send the whole string in one event.
Bonus : this allow to use utf-8 encoded strings in MicroPython and have them displayed correctly.

### CODE REVIEW

**Comment by jimmo** [comment]
Thanks @Anton-2 -- this is the same issue as reported here: https://twitter.com/stuartcw/status/1594905739029536768

We were talking about this exact code a couple of days ago on Discord -- https://discordapp.com/channels/574275045187125269/1022482520845070407/1044491730776502314

I'm not sure if the right answer is for the print event to generate a decoded string (which is what this PR does). InsteadI think it should just copy the data into a UInt8Array and pass that on... i.e. I don't think this layer should be unicode-aware, it's just transporting bytes. It's possible for the Python program to generate utf-8 output that will straddle two different calls to mp_js_write. If something wants to re-assemble this into decoded strings, then that should happen at a different point (for example, the xterm.js will do this).

**Comment by Anton-2** [comment]
Ok, but what to do then for the node.js part ? We are writing directly to process.stdout, will this accept an UInt8Array ?

And how can I trigger the case of "It's possible for the Python program to generate utf-8 output that will straddle two different calls to mp_js_write" to test it ?

I've got a version working like you described, tested successfully with MicroPyScript, but don't know how to test it on node.js.

**Comment by jimmo** [comment]
> We are writing directly to process.stdout, will this accept an UInt8Array ?

I believe so -- https://nodejs.org/api/stream.html#writablewritechunk-encoding-callback

> And how can I trigger the case of "It's possible for the Python program to generate utf-8 output that will straddle two different calls to mp_js_write" to test it ?

It's not currently possible on the webassembly port (because `sys.stdout` isn't available, although that's easy to enable at compile time).

On a microcontroller target, you can write the utf-8 encoded bytes in chunks... e.g.

```
>>> _,_ = sys.stdout.write(b'\xe2\xad'), sys.stdout.write(b'\x90')
⭐
```

Although I notice that in CPython this isn't possible (sys.stdout won't let you write bytes, only str).

However this works in CPython

```
>>> _,_ = os.write(sys.stdout.fileno(), b'\xe2\xad'), os.write(sys.stdout.fileno(), b'\x90')
⭐
```

If I strace that process, I can see that two separate writes were done to the terminal:

```
write(1, "\342\255", 2)                 = 2
write(1, "\220", 1)                     = 1
```

You can flush and sleep etc the terminal will correctly reassemble it.

**Comment by Anton-2** [comment]
Let's go with this, new PR to come.

**Pull request closed without merging**
