### PR TITLE
all: Rename `uasyncio` to `asyncio`.

### PR DESCRIPTION
**Pull request by jimmo**
Follow up to #9018 (and #9069)

It's CPython-compatible enough that it deserves to be called `asyncio`. I don't want to see any more code that does `import uasyncio as asyncio`.

This PR replaces `uasyncio` with `asyncio` everywhere, renames files, etc. A tiny lazy-loading `uasyncio.py` is added to the frozen manifest that allows for backwards compatibility with existing code.

_This work was funded through GitHub Sponsors._

### CODE REVIEW

**Comment by dpgeorge** [comment]
> We could maybe add a reverse-weak-links-for-frozen-modules feature

Yes, if it's purely done for backwards compatibility and there's a way to do it in fewer bytes in C, then I think we should try that.

**Comment by jimmo** [comment]
> > We could maybe add a reverse-weak-links-for-frozen-modules feature
> 
> Yes, if it's purely done for backwards compatibility and there's a way to do it in fewer bytes in C, then I think we should try that.

An alias is a bit tricky because there are 7 asyncio modules frozen.

A very simple option is to detect an import path starting with uasyncio and map it. e.g. in builtinimport.c

```c
    #if MICROPY_PY_ASYNCIO
    // If the import is for "uasyncio" or "uasyncio/...", then map to "asyncio".
    if (strncmp(module_name, "uasyncio", 8) == 0 && (module_name[8] == '.' || module_name[8] == 0)) {
        ++module_name;
        --module_name_len;
    }
    #endif
```

This comes out about 100 bytes better than adding `uasyncio.py`. However it's maybe a bit weird to unconditionally remap uasyncio at the top-level import. (Although this is only a backwards compatibility break if someone previously had an uasyncio.py in their filesystem and had `MICROPY_PY_UASYNCIO` enabled, which would be a bit strange).

You could also do this in frozenmod.c but then you have a situation where `import asyncio` followed by `import uasyncio` will cause a double-import.

**Comment by dpgeorge** [comment]
Let's keep the frozen `uasyncio.py` as-is, and optimise frozen code some more later on.

**Comment by dpgeorge** [comment]
Merged!

**Comment by andrewleech** [comment]
I'm _very_ happy this has been merged, thanks @jimmo 

Minor note for anyone playing along at home - I have an existing project where I wanted compatibility with an existing cpython library using `asyncio` so in my `main.py` I have
```
import uasyncio as asyncio
sys.modules["asyncio"] = asyncio
```
before importing the external library, such that when it does `import asyncio` it "just worked".

With micropython updated to include this MR, well my snippet above blows up with an infinite recurtion error in the new `uasyncio` `__getattr__`! Certainly an easy fix, just had to remove my old workaround!

**Pull request merged**
