### PR TITLE
unix: remove custome file.c code and use extmod's VFS-POSIX version instead

### PR DESCRIPTION
**Pull request by dpgeorge**
Even if the unix port doesn't use the VFS subsystem it can still use the VFS POSIX file code because it's equivalent to the custom code in `ports/unix/file.c`.

### CODE REVIEW

**Comment by stinos** [comment]
This is good. For Windows you'll have to explcicitly add vfs_posix_file.c in both Makefile and sources.props. Or maybe these files should just default to use extmod/*.c but I assume there's a reason they don't. I can look into that if you want?

**Comment by dpgeorge** [comment]
Thanks for the review and suggestion.  I think I have the Windows and MSVC builds worked out now.

**Comment by stinos** [comment]
Yes should be good. Tests still pass and they cover this pretty well I think.

**Comment by dpgeorge** [comment]
> Tests still pass and they cover this pretty well I think.

Yes, there are `tests/io/*` for this.

**Pull request merged**
