### PR TITLE
ports: Move the dht_readinto() method to the machine module.

### PR DESCRIPTION
**Pull request by robert-hh**
Changed ports:

- esp8266
- esp32
- rp2
- pyboard
- mimxrt

The related PR in micropython-lib for dht.py has to be merged first to avoid import errors.

### CODE REVIEW

**Comment by dpgeorge** [comment]
The micropython-lib submodule has been updated, and this PR merged in 8afa6df23db55f54367d653e66a39ac77844fe8a through eefd946e60aba3ac61c7bfbd0272d07be289e3f3

**Comment by robert-hh** [comment]
I just noticed that this line in dht.py does not work for Pyboard:

`    dht_readinto = __import__(sys.platform).dht_readinto`

Because sys.platform is `pyboard`, but the module is `pyb`. That affects the legacy part.

**Comment by dpgeorge** [comment]
Oh no!  Then we should fix that back in micropython-lib, and just make sure to update that lib submodule in this repo before a release.

**Comment by robert-hh** [comment]
Will be there in a few moments.

**Comment by robert-hh** [comment]
Done. I tried that version with an older firmware.

**Pull request closed without merging**
