### PR TITLE
extmod/moductypes: Add aliases for native C types.

### PR DESCRIPTION
**Pull request by pfalcon**
SHORT, INT, LONG, LONGLONG, and unsigned (U*) variants are being defined.
This is done at compile using GCC-style predefined macros like __SIZEOF_INT__.
If the compiler doesn't have such defines, no such types will be defined.

### CODE REVIEW

**Comment by pfalcon** [comment]
Without these, there's no easy way to provide 32-vs-64-bit clean binding for native APIs.

Related questions though:

1. Should aliases be provided for CHAR and UCHAR? Intended answer: no, uctypes works in a conventional model where they are 1-byte, and the interested parties can just do `UCHAR = UINT8`. An interesting question is default signedness of char, but, but... we can't support all of C's quirks...

2. Likewise, question of FLOAT and DOUBLE aliases. And the same answer - uctypes works in a model where those map 1:1 to FLOAT32 and FLOAT64.

3. More interesting question is that I now consider detailed definitions for bitfields, BFUINT8, BFINT8, etc. to be bloat. There're 2 way to deal with that: just introduce a flag like uctypes.BF to OR with int type to signify bitfielfd, e.g. `9 << uctypes.BF_POS | 1 << uctypes.BF_LEN | uctypes.UINT32 | uctypes.BF`. Or, even go further: currently, uctypes goes a bit of way to support maximum offset ranges possible for different types. E.g., range of non-bitfields types is larger, because for bitfields, more bits are used to encode position/length. This is already not preserved in .calc_offset() function implementation which will be posted next. So, might be possible to drop different ranges altogether, and standardize on one (smallest) range for all types. Then, no special flag is necessary, non-zero value for pos/len bits will signify that's a bitfield, e.g.: `9 << uctypes.BF_POS | 1 << uctypes.BF_LEN | uctypes.UINT32`.

**Comment by dpgeorge** [comment]
Since the only new constant that differs on 32 vs 64-bit archs is (U)LONG, why not just include that one, and then maybe call it something like WORD?

> If the compiler doesn't have such defines, no such types will be defined.

In such a case, how would a user of uctypes handle the missing values?  Wouldn't it mean that all uses of these new constants would first have to check if they exist, and, eg, use sys.maxsize to provide a fallback?

**Comment by dpgeorge** [comment]
>     3\. So, might be possible to drop different ranges altogether, and standardize on one (smallest) range for all types. Then, no special flag is necessary, non-zero value for pos/len bits will signify that's a bitfield, e.g.: `9 << uctypes.BF_POS | 1 << uctypes.BF_LEN | uctypes.UINT32`.

That seems reasonable, since BF_LEN value must (?) always be non zero (unlike BF_POS).

**Comment by pfalcon** [comment]
> Since the only new constant that differs on 32 vs 64-bit archs is (U)LONG, why not just include that one, and then maybe call it something like WORD?

On ILP32 vs LP64 specifically. Well, this module is intended to be generic "C data convention" module, not tied into particular model, or bitness. There's nothing wrong with using it on 8 or 16 bit systems for example.

This module turns into hazard however, becoming the biggest in extmod/ . Well, this module was envisioned as covering wide range of usecase, and providing all-encompassing feature set (heck, it's called after the ctypes module in CPython), **and** being immediately usable by end users. And well, there's no good way to deal with C conventions in Python otherwise (except by encoding them at compiled time). So, that's it.

But that's the first and the last module I've designed this way. For all the rest, I'm trying to follow CPython's 2-level approach, where C-level module is optimized for size, and all conveniences should go into Python-level. Except that **confirmed** (not random) users can access C-level module directly. So, HW API? No float, can be done in a wrapper. uctypeslib? No symbolic constants, should be done in wrapper (so, 473fe45da23f371d7beb6117c31922f9c9ee5942 shouldn't have gone in).

> In such a case, how would a user of uctypes handle the missing values?

Users of compilers which don't follow well-established conventions, will need to define these preprocessor macros manually in their mpconfigport.h. Realistically, correlation between users using such compilers and needing things like uctyles.LONG is pretty small, and by the time they need it, they can as well migrate to another compiler.

**Comment by pfalcon** [comment]
> That seems reasonable, since BF_LEN value must (?) always be non zero (unlike BF_POS).

Yes, there would be such a requirement. Ok, will go for that solution.

Then I'm probably ready to replace uctypes.NATIVE with no argument, uctypes.LITTLE_ENDIAN with "little", uctypes.BIG_ENDIAN with "big" too.

**Comment by dpgeorge** [comment]
Maybe these additions should be configurable: a lot of baremetal ports use uctypes (eg stm32, esp8266, esp32) and arguably don't need these aliases because if uctypes is used on those systems you know the size of types.



> Then I'm probably ready to replace uctypes.NATIVE with no argument, uctypes.LITTLE_ENDIAN with "little", uctypes.BIG_ENDIAN with "big" too.

What about the conventional "@", "<" and ">" characters?

**Comment by pfalcon** [comment]
> Maybe these additions should be configurable

Maybe. Ideally, I'd prefer to add all the missing functionality to the uctypes (posted here is just beginning), and then think about what to make configurable, but with the slow response you provide here it doesn't work as good. I'll config option here.

> What about the conventional "@", "<" and ">" characters?

Well, values of sys.byteorder are also "conventional". There're roughly 2 conventions for stuff related to "binary data handling".

1. "Single character", from CPython's struct module, also reused for uPy's ffi module and stream.readbin/writebin.
2. "Longer words", like sys.byteorder, int.from_bytes, ctypes, reused in uctypes.

It makes sense to follow one way or another, but not mix them needlessly.

**Comment by pfalcon** [comment]
> Maybe these additions should be configurable

Made this change. It's still on by default.

**Comment by pfalcon** [comment]
@dpgeorge, thanks for merging a couple of other uctypes patches, and this should be an easy merge too. Why in general it takes so long to merge patches, even those which were commented and updated per suggestions?

**Comment by dpgeorge** [comment]
Merged in 38151f35c19751207a96e9a6c6a12d84e2e3fb88

**Pull request closed without merging**
