### PR TITLE
py/objslice: Add slice.indices() as defined by Python

### PR DESCRIPTION
**Pull request by deshipu**
As documented in
https://docs.python.org/3/reference/datamodel.html#slice.indices

### CODE REVIEW

**Comment by pfalcon** [comment]
I'm -1 on this by the same as reason as https://github.com/micropython/micropython/pull/2407 - this is niche feature which almost nobody needs, and which can be implemented with 2-3 lines of Python code otherwise.

**Comment by deshipu** [comment]
I thought it's not possible to monkey-patch C builtin classes, like the `slice`?

**Comment by pfalcon** [comment]
Yes, but you can do work done by .indices() in few lines of Python code instead (abstract it to a function or even to a class as needed). That's good compromise for not growing core of the language with code not needed in 99+% of cases.

**Comment by deshipu** [comment]
Well, in my experience, the ``indices`` method is useful every time you are implementing slicing on your own objects. If that is what you consider "not needed in 99+%" cases, then why have exposed slice objects at all? They are not useful outside of this "rare" use case.

**Comment by PinkInk** [comment]
It allows to pass a coverage test. 

Tim

On 10 Oct 2016, at 19:35, Radomir Dopieralski <notifications@github.com> wrote:

Well, in my experience, the indices method is useful every time you are implementing slicing on your own objects. If that is what you consider "not needed in 99+%" cases, then why have exposed slice objects at all? They are not useful outside of this "rare" use case.

**Comment by pfalcon** [comment]
> useful every time you are implementing slicing on your own objects.

Yes, but slicing on user objects is implemented is pretty rarely (at least for MicroPython usecases). That's what I mean by "not needed in 99+%".

> why have exposed slice objects at all? They are not useful outside of this "rare" use case.

So, slicing (of builtin types) is very important part of the language, and internally implemented by having a slice object. Then there was a request to let slice object to be used with custom objects, and indeed, there's a huge difference between not being able to do that at all and being able, that's why there was a config setting added to optionally expose .start, etc. attributes. However, there's pretty little difference whether there's one more convenience method, or one less, as long as it's needed relatively rarely overall, and same effect can be achieved with existing attributes and few lines of code. That's important to keep the core small, but also to avoid fragmentation - we already have too many config settings, and we'll be getting more, but should grow conservative with adding those, as otherwise writing portable code gets rather complicated.

**Comment by deshipu** [comment]
That makes sense, thanks. Do you think it would make sense to have a library in micropython-lib or somewhere else with such convenience methods that are missing from MicroPython as compared to Python, as to avoid duplication of effort and subtle bugs from differences in implementation?

**Comment by pfalcon** [comment]
Yes, if you think it's useful, having something like slicetools (similar to itertools) in micropython-lib sounds good.

**Comment by deshipu** [comment]
Thanks.

**Comment by dpgeorge** [comment]
FWIW, I never even knew about slice.indices(), let alone used it :)

**Comment by peterhinch** [comment]
Likewise :)

**Pull request closed without merging**
