### PR TITLE
esp8266/machine_pin: Disable ets_loop_iter during hard IRQ handler.

### PR DESCRIPTION
**Pull request by dpgeorge**
Otherwise ets_loop_iter may be reentered.

Fixes issue #5714.

@peterhinch I tested this and it seems to work for me, but would be great if you could also test.

### CODE REVIEW

**Comment by peterhinch** [comment]
I'm getting no joy with this, I'm afraid. I have gleaned some more information.

- Failure occurs with `hard = False` or `hard = True`
- I reduced the frequency to 5Hz (10 interrupts/sec) with no change
- Debug info follows. It looks identical regardless of the state of `hard`.

hard = False
```
162
Fatal exception 0(IllegalInstructionCause):
epc1=0x4027e538, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 31256, room 16 
tail 8
chksum 0x6c
load 0x3ffe8000, len 1004, room 0 
tail 12
chksum 0xd0
ho 0 tail 12 room 4
load 0x3ffe83f0, len 1064, room 12 
tail 12
chksum 0x92
csum 0x92
```
hard = True
```
Fatal exception 0(IllegalInstructionCause):
epc1=0x4027e538, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 31256, room 16 
tail 8
chksum 0x6c
load 0x3ffe8000, len 1004, room 0 
tail 12
chksum 0xd0
ho 0 tail 12 room 4
load 0x3ffe83f0, len 1064, room 12 
tail 12
chksum 0x92
csum 0x92
���g��s��o|�
              l
               ldd`��r�l�d�


                             l`��{�l�l�$`��s�d�

                                                      ll`slrd����c��c�cb{��sb��o���
MicroPython v1.12-213-g2ffa622-dirty on 2020-03-04; ESP module with ESP8266
Type "help()" for more information.
```

**Comment by peterhinch** [comment]
@dpgeorge I can confirm your observation that the crash I'm getting can be prevented by pinging the board.

I was aware that in the application re-entrancy was a hazard. The application uses WiFi and works reliably; tests without explicit WiFi use work while being pinged. Testing with a 5Hz square wave was an attempt to eliminate timing issues: with no WiFi use the test fails under these conditions. The above evidence seems to rule out timing as a cause.

This PR usefully fixes a problem with high PRF's but does not impact the crash where WiFi is unused.

Is your idea that it's related to wifi power management correct?

**Comment by dpgeorge** [comment]
Ok, I think we are seeing different issues here.  The only problem I can replicate is:
- master without this PR
- hard IRQ
- wifi STA enabled and connected to an AP, but no wlan activity (so esp8266 is in wifi power save mode)
- a 20Hz square wave generated by the esp8266's PWM, or externally
Under these conditions the esp8266 eventually prints `pm 572` and stops responding (but it seems it still runs in the background because it doesn't have a WDT reset and sometimes prints Lmac errors).

The PR here fixes the problem I see, and it seems to make sense (re-entering ets_loop_iter).

But I never see any hard reset, which is what you see.

**Comment by dpgeorge** [comment]
I merged this PR because it definitely fixes a bug.

@peterhinch can you test with v1.12 release code?  Then I can disassemble it to see exactly where the crash is that you see.

**Pull request merged**
