### PR TITLE
stm32: add support for STM32WLxx MCUs

### PR DESCRIPTION
**Pull request by dpgeorge**

### CODE REVIEW

**Comment by andrewleech** [comment]
Hi @dpgeorge did you have a matching stm32lib update to go with this? 
I tried grabbing them from here: https://github.com/STMicroelectronics/STM32CubeWL/tree/1555f88ae1c5898c239bd8a8520203a776ab4995/Drivers (master at time of writing) but they throw up a lot of build failures.

**Comment by andrewleech** [comment]
I've pushed a branch of stm32lib with the neccesary libraries up at https://github.com/micropython/stm32lib/pull/15

**Comment by andrewleech** [comment]
On a related note, I've been trying to get the stm32 uart bootloader working from micropython. On the seeed modules boot0 pin is not exposed so the hw route to triggering the bootloader is not available.

On this part, only UART or SPI is available for DFU from the rom bootloader. Repl is on uart1 so it would be quite convenient to also use DFU on the same uart.

Running `machine.bootloader(1)` as-is just reset's back into mictopython however.

According to ST's AN2606 Page 384 the bootloader flash address is 0x1FFF0000 (as opposed to 0x1ff00000 for F7 etc)
ref: https://www.st.com/resource/en/application_note/cd00167594-stm32-microcontroller-system-memory-boot-mode-stmicroelectronics.pdf
Note: uart1 is supported by the DFU and should auto-baud.

Adding that address to machine_bootloader stops it rebooting, but now the chip just appears to stop responding. I also added a uart_deinit in case that helped, it didn't.
``` c
// Activate the bootloader without BOOT* pins.
STATIC NORETURN mp_obj_t machine_bootloader(size_t n_args, const mp_obj_t *args) {
    #if MICROPY_HW_ENABLE_USB
    pyb_usb_dev_deinit();
    #endif
    #if MICROPY_HW_ENABLE_STORAGE
    storage_flush();
    #endif
    uart_deinit_all();

    __disable_irq();

    #if MICROPY_HW_USES_BOOTLOADER
    if (n_args == 0 || !mp_obj_is_true(args[0])) {
        // By default, with no args given, we enter the custom bootloader (mboot)
        powerctrl_enter_bootloader(0x70ad0000, MBOOT_VTOR);
    }

    if (n_args == 1 && mp_obj_is_str_or_bytes(args[0])) {
        // With a string/bytes given, pass its data to the custom bootloader
        size_t len;
        const char *data = mp_obj_str_get_data(args[0], &len);
        void *mboot_region = (void *)*((volatile uint32_t *)MBOOT_VTOR);
        memmove(mboot_region, data, len);
        powerctrl_enter_bootloader(0x70ad0080, MBOOT_VTOR);
    }
    #endif

    #if defined(STM32F7) || defined(STM32H7)
    powerctrl_enter_bootloader(0, 0x1ff00000);
    #elif defined(STM32WL)
    powerctrl_enter_bootloader(0, 0x1FFF0000);
    #else
    powerctrl_enter_bootloader(0, 0x00000000);
    #endif
```

Have you ever tried UART dfu on any other part?

**Comment by rlourette** [comment]
Any status on this port?

**Comment by dpgeorge** [comment]
I've rebased this on latest master and tested it.  Not all features are working (and the second core and LoRa is not yet supported), but it should be good to go in for an initial release.

**Comment by dpgeorge** [comment]
RTC now works (needed the RTC APB bus clock enabled, which is a new thing on the WL).

**Comment by Micado2** [comment]
Hello, I'm surprised, I boot the NUCLEO WL55 but the weight is around 217KB without LoRa stack, if I add it, the result is 267KB.
It's over the NUCLEO Flash size! Do you think optimization is possible???

**Comment by andrewleech** [comment]
> Hello, I'm surprised, I boot the NUCLEO WL55 but the weight is around 217KB without LoRa stack, if I add it, the result is 267KB. It's over the NUCLEO Flash size! Do you know if optimization is possible???

This probably needs to be in a new issue, however I'd expect most of the size here would be the pre-allocated filesystem space? I'm not sure about the quickest way to adjust this though.

**Comment by dpgeorge** [comment]
The filesystem is allocated 24k and the littlefs driver takes about 14k, so you can reclaim about 38k by disabling the filesystem.  There are other things that can be done to reduce size, disabling options.

**Comment by cmdarby** [comment]
> I've rebased this on latest master and tested it. Not all features are working (and the second core and LoRa is not yet supported), but it should be good to go in for an initial release.

Thanks for your efforts towards tying to get this to work. Have there been any new developments? It would be great if we could run our MicroPython code directly on this particular STM32 with LoRa support, rather than having to run on a separate additional microcontroller which then uses this microcontroller as just a modem.

**Comment by jimmo** [comment]
@cmdarby See https://github.com/micropython/micropython/pull/9130 which I think is what you're asking for.

**Comment by DuaneKaufman** [comment]
> SEEED_LORA_E5_MINI board

@andrewleech : is this board supported? How does one get Micropython installed?

Appreciate your help!

Sincerely,
Duane

**Comment by andrewleech** [comment]
> > SEEED_LORA_E5_MINI board
> 
> @andrewleech : is this board supported? How does one get Micropython installed?
> 
> Appreciate your help!
> 
> Sincerely,
> Duane

I don't remember if I ever got it working... though I think I might have managed to flash it with a build via JTAG/swd interface.

SEEED really broke the design by making it incredibly hard to update / flash the module, it's a real pain. As such I wouldn't consider it supported as such.

**Comment by DuaneKaufman** [comment]
Dear Andrew,
I am grateful for your effort, and if you could share what you remember, I could try to give it a go. I have a STLINK V3 and a (I believe) Segger programmer, and am willing to self-educate, but pointers are always welcome!

Sincerely,
Duane

**Comment by andrewleech** [comment]
I don't remember much more than that to be honest, though you could probably start with the [NUCLEO_WL55](https://github.com/micropython/micropython/blob/9c7067d9ad91a303389ec0add306bedac55e18f9/ports/stm32/boards/NUCLEO_WL55/mpconfigboard.h#L40) board profile and swap over the repl uart, compile then try flashing that on with either of those debuggers and try to get it started. 

I vaugley recall using dupont wires to connect a debugger to the board.

The seed board has [UART1 connected to the usb com port](https://core-electronics.com.au/attachments/localcontent/LoRa-E5miniv1_852158b2b21.pdf) wherea the NUCLEO board has LPUART1 connected to the com port / repl. So change `MICROPY_HW_UART_REPL` to `PYB_UART1` and compile it and you might be ready to go.

**Pull request merged**
