### PR TITLE
mpremote: Use hatch to build mpremote package.

### PR DESCRIPTION
**Pull request by jimmo**
Extending on the idea from https://github.com/micropython/micropython/pull/8404/ (@andrewleech ) the idea is to use as little custom code as possible and use standard tools (i.e. `hatch`) from the Python packaging ecosystem to:
 - Get the correct version tag from the git history (via hatch-vcs)
 - Add pyboard.py to the package. (And soon, manifestfile.py too)

Also includes the GitHub workflow from #8404 to build the wheel. Increased the fetch depth to 1000 (we're currently 850 commits from 1.19.1 !!!)

This works both via `python -m build` (this is what the workflow uses) as well as `hatch build`. `python -m build` has the advantage of automatically fetching all dependencies, you don't need to manually install any hatch packages.

In order to make the versioning work, we need to add mpremote tags to this repo. I suggest adding for example `mpremote-v0.4.0`, which can be matched by the `tag-pattern` regular expression. Right now it matches the MicroPython version instead (e.g. v1.19.1). Alternatively, we could pin the mpremote releases to the MicroPython releases and use the same tags?

The version strings look like:
`X.Y.Z` -- Clean build at the tag
`X.Y.Z.postN+gHASH` -- Clean build, N revisions from the most recent tag
`X.Y.Z.postN+gHASH.dYYYYMMDD` -- Dirty build, N revisions from the most recent tag

### CODE REVIEW

**Comment by jimmo** [comment]
Also adds a `requirements.txt` mostly for personal preference and uses that for the project requirements -- it's nice to be able tojust run `pip install -r requirements.txt` when running the package directly from the source repo.

**Comment by jimmo** [comment]
Another note: I investigated using `setuptools` rather than `hatch` and wasted a lot of time trying to get the `pyboard.py` inclusion to work. It does not appear to be supported.

**Comment by andrewleech** [comment]
Could also consider moving mpremote and its dependant scripts to a submodule for a much cleaner package design and ease of tag/release...

**Comment by jimmo** [comment]
> Could also consider moving mpremote and its dependant scripts to a submodule for a much cleaner package design and ease of tag/release...

Honestly there was a point when I was trying to get setuptools to work where I considered this, but you still have the same problem with pyboard.py living in main-repo/tools.

And the `mpremote-vX.Y.Z` tags work well.

**Comment by dpgeorge** [comment]
Thanks for this, it's a good improvement.

> Alternatively, we could pin the mpremote releases to the MicroPython releases and use the same tags?

Yes I think this is the best and simplest solution, and will reduce confusion for users, to just have mpremote and MicroPython versioned the same.  I tested this and it works, although we will need to now always have a revision number in the version, eg `v1.20.0`.  I'm very happy to do that.

**Comment by dpgeorge** [comment]
I tuned the github workflow to only run on a pull request if tools/ files change (but it still runs unconditionally on a normal push to master).

**Pull request merged**
