### PR TITLE
py/vmentrytable.h: Replace ranged array init with explicit entries.

### PR DESCRIPTION
**Pull request by dpgeorge**
Ranged designated initialisers are (apparently) a GNU C compiler extension and not part of the C99 standard, so for portability the code shouldn't use them.

Writing out the whole table explicitly, as done in this patch, seems the simplest way to do it without ranged initialisers.  It also allows one to see clearly how the opcodes are arranged and which ones are still available for use.

### CODE REVIEW

**Comment by pfalcon** [comment]
I'd suggest this to be postponed and least until https://github.com/micropython/micropython/issues/3291 is fully implemented (may take a while).

But actually, there were quite a few changes lately affecting developers' experience/comfort, and it would be nice to well interleave any further similar changes, like this - for few months. Or maybe do even smarter, like why not write a custom preprocessor for "ranged initializers"? And given that we already have it builtin, the action of writing a standalone can be postponed until after it's actually needed ;-)

**Comment by pfalcon** [comment]
> see clearly how the opcodes are arranged and which ones are still available for use.

I wouldn't call this long sheet of identifiers a clear-vision. At the very least, it lacks separator comments with hex codes (or perhaps, non-ranged idx'es instead).

**Comment by dpgeorge** [comment]
> But actually, there were quite a few changes lately affecting developers' experience/comfort, and it would be nice to well interleave any further similar changes, like this - for few months.

Better still to get them out of the way ASAP.  And I don't see how this hurts development.

> Or maybe do even smarter, like why not write a custom preprocessor for "ranged initializers"?

I'd rather not add even more preprocessing scripts because it makes using alternative build systems harder.

> And given that we already have it builtin, the action of writing a standalone can be postponed until after it's actually needed ;-)

This PR was made because there were now 2 independent reports of ranged initialisers giving problems.

> At the very least, it lacks separator comments with hex codes (or perhaps, non-ranged idx'es instead).

Adding comments or designated initialisers just adds more code to update.  It's very easy to use an editor to count lines from the start of the array to work out what opcode something is (and any separator comments would make this much harder to do).

**Comment by pfalcon** [comment]
> Better still to get them out of the way ASAP.

Sorry, but it's not putting them out of the way, it's putting them *in* the way.

> And I don't see how this hurts development.

Discussed in https://github.com/micropython/micropython/issues/3255, https://github.com/micropython/micropython/pull/3122, https://github.com/micropython/micropython/pull/3290#issuecomment-326919775 , etc.

> I'd rather not add even more preprocessing scripts because it makes using alternative build systems harder.

That's why most projects have one build system.

> It's very easy to use an editor to count lines from the start of the array to work out what opcode something is (and any separator comments would make this much harder to do).

Very easy? Very easy is looking and seeing it right away, and the current syntax does just that, including avoiding noise of repeated values. Anything else is hard(er, much).

**Comment by dpgeorge** [comment]
> Sorry, but it's not putting them out of the way, it's putting them in the way.

These things need to be done.  Doing them sooner is better.

> And I don't see how this hurts development.
> 
> Discussed in #3255, #3122, #3290 (comment) , etc.

This change is completely unlike those.  This file is hardly ever touched.

> That's why most projects have one build system.

This project is an embeddable component used in widely different systems, with a build system enforced by the parent system.  We should support such things (or at least not make it more difficult).

> ... and the current syntax does just that, including avoiding noise of repeated values

Please suggest an alternative which is C99 compatible and which doesn't require a preprocessor.

**Comment by pfalcon** [comment]
> This change is completely unlike those. This file is hardly ever touched.

I presented an alternative opinions - that all these change make a background of complicating development on the codebase. This file is hardly ever touched, but you propose this change exactly at the time of https://github.com/micropython/micropython/issues/3291, and ideas I had to resolve some of issue there (e.g. to use `[MP_BC_BINARY_OP_MULTI ... MP_BC_BINARY_OP_MULTI + MP_BINARY_OP_LAST_BC]`) won't work any longer. And besides, "hardly ever touched", but perhaps looked at bu everyone, and this change makes it much less readable.

Anyway, I have little to add to the above, if you think that all these concerns don't outweight desire to do it right away, feel free to.

**Comment by dpgeorge** [comment]
> and ideas I had to resolve some of issue there (e.g. to use [MP_BC_BINARY_OP_MULTI ... MP_BC_BINARY_OP_MULTI + MP_BINARY_OP_LAST_BC]) won't work any longer.

Then it's lucky that the PR here was brought up before such a change was made.  And it shows that it's better to change things sooner so they don't become more entrenched.

**Comment by pfalcon** [comment]
@dpgeorge, so any further steps on this (e.g. figuring out CI errors/merging)?

**Comment by dpgeorge** [comment]
I didn't realise, but it turns out taking the address of a label (as done when computed gotos are enabled) is also a gcc extension.  And there's no way to do a similar thing (as label addresses) in C99 (that I know of).  So it doesn't matter that ranged designated initialisers are also used for this optimisation in the VM.

In 44f0a4d1e7a315c8d2b21fc4b0471d88e382a91e I added a note to such effect.  Users who need strict C99 compliance must disable the computed goto optimisation.

**Pull request closed without merging**
