### PR TITLE
docs/library/uos.rst Clarify AbstractBlockDev section.

### PR DESCRIPTION
**Pull request by peterhinch**
This doc is rather confusing as it implies that **AbstractBlockDev** is a member of **uos** rather than being a template for the creation of user classes. Users are likely to go looking for a base class where none exists. This PR aims to:

 1. Identify the purpose of block devices at the start.
 2. Reformat and adapt the text to clarify the **AbstractBlockDev** class template.
 3. Add a note about return values from **ioctl**.

### CODE REVIEW

**Comment by dpgeorge** [comment]
> Reformat and adapt the text to clarify the AbstractBlockDev class template.

I understand the desire to do this, but there are references throughout the docs to this class and its methods which probably no longer work (grep for `AbstractBlockDev` in the docs to find them).

Note that there's also `network.AbstractNIC` which is similar to `AbstractBlockDev`.  Is that `AbstractNIC` also confusing?

Maybe an alternative is to just make it explicit in the docs that `AbstractBlockDev` does not exist.

**Comment by peterhinch** [comment]
`reference/filesystem.rst` requires revision: I opted to float the idea before spending time on it.

That aside there are four docs each having a single reference to **:class:`uos.AbstractBlockDev`** which would need to be replaced by a link.

>  Is that AbstractNIC also confusing?

`network.rst` doc has a paragraph clarifying that the class does not actually exist.

I'm happy to make the above changes, or simply to amend the PR to make the non-existence of the class explicit in `uos.rst` and leave the other docs unchanged. I guess the choice is a matter of writing style. Please advise how you wish to proceed.

**Comment by dpgeorge** [comment]
> or simply to amend the PR to make the non-existence of the class explicit in `uos.rst` and leave the other docs unchanged.

That's what I would prefer, to be similar to `AbstractNIC`.

**Comment by peterhinch** [comment]
I've submitted PR #5520 making this revision.

**Pull request closed without merging**
