### PR TITLE
stm32/usb_cdc: Add VCP support to uos.dupterm

### PR DESCRIPTION
**Pull request by andrewleech**
Use `uos.dupterm` for all repl configuration in main (vcp(0) or uart if enabled).
This means `dupterm` can also be used to disable the boot repl port if desired.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for this, it's definitely a move in the right direction.  But there are a few issues:
1) It's a lot less efficient to go via the dupterm code (for read and write) than it is to go directly to the USB CDC driver.  Going through dupterm requires pushing/popping an NLR buf and lots of indirection.  This may even affect idle-at-the-REPL power consumption due to all the extra code that is executed between WFI() sleeps waiting for key presses.  And now that USB HS is supported it's important to keep the USB CDC path as fast as possible.
2) It looks like the stdout tx function now goes to `usbd_cdc_tx` instead of `usbd_cdc_tx_always`.  I think this means that when you plug in a board and go to the serial port for the first time, the uPy banner will now be missing.

Both of these should be fixable.  For (1) I would suggest that dupterm has a compile-time hook to put in fast-path code for a given port.  The fast-path code would check if the serial objects are known entities (eg USB, UART) and use faster code if they are.

**Comment by andrewleech** [comment]
@dpgeorge I'm not entirely sure I've made this better, but I've certainly made the changeset bigger. 
Hasn't had enough testing yet either. 
But it will be in use over the coming weeks to allow disabling repl on vcp for our release builds so will have time for more iterations as needed.

**Comment by andrewleech** [comment]
This has now had active use for the past two weeks to disable repl on vcp and/or move repl to vcp(1) and appears to work well

**Comment by dpgeorge** [comment]
I tested this PR and there are a few things I'd like to change:
1. instead of `mp_uos_dupterm_is_builtin_stream()` being a weak function, make it a compile-time macro so ports that don't want this feature don't incur overhead
1. don't remove `pyb.repl_uart()`, that can be done separately (and later on)
1. instead of adding the CTS flow option to USB_VCP (which is a neat idea, but can be separated) and using it to see if `usbd_cdc_tx_always()` should be called, simply test the variable `self->cdc_itf->attached_to_repl` (that should have equivalent behaviour, and really simplify the code)
1. remove the `uos.dupterm(stream, None)` addition which searches for the first available slot, and instead just use a fixed slot for USB_VCP (if it goes in an auto slot, how do you know which one to use to disable the REPL?)
1. in stm32/main.c, move the auto activation of USB_VCP(0) on dupterm to before boot.py is called, so that 1) boot.py can disable the USB_VCP REPL if it wants; and 2) so that any `print()` calls in boot.py will work if the USB device is initialised explicitly in boot.py
1. fix the build when `MICROPY_HW_UART_REPL` is enabled

@andrewleech if you don't have any objections I'm happy to do all this.

**Comment by dpgeorge** [comment]
I also tested VCP throughput and current consumption with this PR as-is, and they are (within measurement error) unchanged.

**Comment by andrewleech** [comment]
Thanks for the testing! If you've got time for the changes please do, I definitely don't have any objections.

**Comment by dpgeorge** [comment]
Ok, will do.

I'm curious how you disabled REPL on USB_VCP(0) if it's always automatically re-enabled after boot.py runs, I guess you disable it in main.py?  But then how do you know which slot it's in to disable it?

**Comment by andrewleech** [comment]
I just checked my code... I basically just throw the hammer at it
```
if __release__:
    # Disable micropython repl immediately on boot
    import uos
    for slot in range(3):
        try:
            uos.dupterm(None, slot)
        except ValueError:
            break
```
Your idea of at least having it fixed is a better one. Perhaps it would make sense to provide a method of interrogating what's in each slot.

**Comment by dpgeorge** [comment]
This PR was reworked as described above and merged in 9d6f70f7154aa01a02d3de1c669241e3a1439218

**Pull request closed without merging**
