### PR TITLE
added property setter/getter to runtime.c

### PR DESCRIPTION
**Pull request by v923z**
This modification concerns only runtime.c, and implements getters/setters for properties. The code is based entirely on circuitpython's runtime.c (https://github.com/adafruit/circuitpython/blob/6dfa527f79189b6a79a7055d718313f2a14288a4/py/runtime.c#L1158, https://github.com/adafruit/circuitpython/blob/6dfa527f79189b6a79a7055d718313f2a14288a4/py/runtime.c#L1023). 

The inclusion of the functions is determined by the 
``` 
CFLAGS_EXTRA += -DMICROPY_PY_BUILTINS_PROPERTY_GETTER=1
CFLAGS_EXTRA += -DMICROPY_PY_BUILTINS_PROPERTY_SETTER=1
```
compiler switches. Setting both flags adds 288 bytes to the firmware on the unix port. 

Broader context, and rationale can be found in the forum thread: https://forum.micropython.org/viewtopic.php?f=3&t=7762

Possible use case

```c
#include <stdio.h>
#include "py/runtime.h"
#include "py/obj.h"

typedef struct _propertyclass_obj_t {
    mp_obj_base_t base;
    mp_float_t x;
} propertyclass_obj_t;

const mp_obj_type_t propertyclass_type;

// lifted from objproperty.c
typedef struct _mp_obj_property_t {
    mp_obj_base_t base;
    mp_obj_t proxy[3]; // getter, setter, deleter
} mp_obj_property_t;

STATIC mp_obj_t propertyclass_make_new(const mp_obj_type_t *type, size_t n_args, size_t n_kw, const mp_obj_t *args) {
    mp_arg_check_num(n_args, n_kw, 1, 1, true);
    propertyclass_obj_t *self = m_new_obj(propertyclass_obj_t);
    self->base.type = &propertyclass_type;
    self->x = mp_obj_get_float(args[0]);
    return MP_OBJ_FROM_PTR(self);
}

STATIC mp_obj_t propertyclass_get_x(mp_obj_t self_in) {
    (void)self_in;
    printf("in propertyclass_get_x()\n");
    return mp_obj_new_float(1.0);
}

MP_DEFINE_CONST_FUN_OBJ_1(propertyclass_get_x_obj, propertyclass_get_x);

STATIC mp_obj_t propertyclass_set_x(mp_obj_t self_in, mp_obj_t value) {
    (void)self_in;
    (void)value;
    printf("in propertyclass_set_x()\n");
    return mp_const_none;
}

MP_DEFINE_CONST_FUN_OBJ_2(propertyclass_set_x_obj, propertyclass_set_x);

STATIC mp_obj_t propertyclass_del_x(mp_obj_t self_in) {
    (void)self_in;
    printf("in propertyclass_del_x()\n");
    return mp_const_none;
}

MP_DEFINE_CONST_FUN_OBJ_1(propertyclass_del_x_obj, propertyclass_del_x);

const mp_obj_property_t propertyclass_x_obj = {
    .base.type = &mp_type_property,
    .proxy = {(mp_obj_t)&propertyclass_get_x_obj,
              (mp_obj_t)&propertyclass_set_x_obj,
              (mp_obj_t)&propertyclass_del_x_obj},
};

STATIC mp_obj_t propertyclass_xsq(mp_obj_t self_in) {
    propertyclass_obj_t *self = MP_OBJ_TO_PTR(self_in);
    return mp_obj_new_float(self->x * self->x);
}

MP_DEFINE_CONST_FUN_OBJ_1(propertyclass_xsq_obj, propertyclass_xsq);

STATIC const mp_rom_map_elem_t propertyclass_locals_dict_table[] = {
    { MP_ROM_QSTR(MP_QSTR_xsq), MP_ROM_PTR(&propertyclass_xsq_obj) },
    { MP_ROM_QSTR(MP_QSTR_x), MP_ROM_PTR(&propertyclass_x_obj) },
};

STATIC MP_DEFINE_CONST_DICT(propertyclass_locals_dict, propertyclass_locals_dict_table);

const mp_obj_type_t propertyclass_type = {
    { &mp_type_type },
    .name = MP_QSTR_propertyclass,
    .make_new = propertyclass_make_new,
    .locals_dict = (mp_obj_dict_t*)&propertyclass_locals_dict,
};

STATIC const mp_map_elem_t propertyclass_globals_table[] = {
    { MP_OBJ_NEW_QSTR(MP_QSTR___name__), MP_OBJ_NEW_QSTR(MP_QSTR_propertyclass) },
    { MP_OBJ_NEW_QSTR(MP_QSTR_propertyclass), (mp_obj_t)&propertyclass_type },	
};

STATIC MP_DEFINE_CONST_DICT (
    mp_module_propertyclass_globals,
    propertyclass_globals_table
);

const mp_obj_module_t propertyclass_user_cmodule = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t*)&mp_module_propertyclass_globals,
};

MP_REGISTER_MODULE(MP_QSTR_propertyclass, propertyclass_user_cmodule, MODULE_PROPERTYCLASS_ENABLED);
```

### CODE REVIEW

**Comment by v923z** [comment]
@dpgeorge Damien, do you think that this PR stands a chance? I would really like to have properties, because `numpy` heavily relies on them, and since `circuitpython` has properties, I have to implement nasty (and `numpy`-incompatible) workarounds for quite a lot of things just for `micropython`. 

I believe, this particular PR is probably outdated. I would be more than happy to start a new one from scratch, but I wanted to raise the issue here, so that we don't lose the reference.

**Comment by amirgon** [comment]
@v923z What's wrong with setting `attr` in `mp_obj_type_t`?
If you don't want it to hide `locals_dict`, you can call `locals_dict` methods from `attr`.
We use this technique in LVGL to create native classes with both methods and attributes.

**Comment by v923z** [comment]
@amigron

> @v923z What's wrong with setting `attr` in `mp_obj_type_t`?

I don't know if anything is wrong with it, but that is not how `micropython` does it. 

> If you don't want it to hide `locals_dict`, you can call `locals_dict` methods from `attr`.
> We use this technique in LVGL to create native classes with both methods and attributes.

Can you point to an example?

**Comment by amirgon** [comment]
> Can you point to an example?

An example: https://raw.githubusercontent.com/lvgl/lv_binding_micropython/master/gen/lv_mpy_example.c
See, for example, `mp_lv_color32_t_attr` which exposes `ch` and `full` properties and calls `call_parent_methods` which falls back to `mp_lv_color32_t_locals_dict` lookup, exposing many methods.

**Comment by v923z** [comment]
@amirgon Thanks, I will look at it!

**Comment by v923z** [comment]
This PR has been re-submitted in https://github.com/micropython/micropython/pull/7354, so closing this thread.

**Pull request closed without merging**
