### PR TITLE
stm32/modmachine.c: Add HAL version to machine.info().

### PR DESCRIPTION
**Pull request by iabdalkader**
* Which is otherwise very hard to find.

### CODE REVIEW

**Comment by dpgeorge** [comment]
I think this is a good idea, but I also think it should be more general and applicable to all ports:
- stm32 for the HAL version
- esp32 for the IDF version
- rp2 for the pico-sdk version
- zephyr for the Zephyr OS version

In addition, would be good to include the compiler version used in the build.

But where to put them?  CPython puts the compiler version in the `sys.version` string, and OS version can be found using `os.uname()`, eg:
```
>>> sys.version
'3.9.6 (default, Jun 30 2021, 10:22:16) \n[GCC 11.1.0]'
>>> os.uname().release
'5.13.9-arch1-1'
```
We can add the compiler version to `sys.version` to match CPython.  But uPy uses `os.uname()` for the uPy version (distinct from the version of Python which it implements, which is in `sys.version`):
```
>>> sys.version
'3.4.0'
>>> os.uname().release
'1.16.0'
```
It would make sense to put the OS/SDK/HAL/etc version in `os.uname().release`, but then where does the uPy version go?

**Comment by iabdalkader** [comment]
> I think this is a good idea, but I also think it should be more general and applicable to all ports:

The rp2 and nrf SDKs (and others?) don't define a major, minor and patch numbers. For these ports I just hard code the SDK version (alternatively we could try to read it from the repo tag). I put the HAL version in the REPL prompt because it makes it easier to immediately spot the uPy/HAL versions...Anyway, I think there should be an mphalport.c:mp_hal_version() for every port first, hard-coded or not, for stm32:
```C
uint32_t mp_hal_version()
{
    return HAL_GetHalVersion();
}
```

Rp2:
```C
uint32_t mp_hal_version()
{
    // Hard-coded becasue it's not defined in SDK
    return ((1<<24) | (2<<16) | (0<<8) | (0<<0));
}
```
etc...

> It would make sense to put the OS/SDK/HAL/etc version in `os.uname().release`, but then where does the uPy version go?

I think it's correct as it is, because uPy is the equivalent of the OS...There's a [platform module](https://docs.python.org/3/library/platform.html#module-platform) in Python which I think may be more suitable for SDK/HAL/GCC version too etc.. ? Or they can be in machine.

```Python
In [5]: import platform

In [6]: platform.machine
Out[6]: <function platform.machine()>

In [7]: platform.machine()
Out[7]: 'x86_64'

In [8]: platform.libc_ver()
Out[8]: ('glibc', '2.33')

In [9]: platform.platform()
Out[9]: 'Linux-5.12.15-arch1-1-x86_64-with-glibc2.33'

In [10]: platform.python_compiler()
Out[10]: 'GCC 11.1.0'
```

**Comment by dpgeorge** [comment]
> There's a [platform module](https://docs.python.org/3/library/platform.html#module-platform) in Python which I think may be more suitable for SDK/HAL/GCC version too etc..

Aah, I didn't know about the `platform` module!  That does seem like a good place, the main issue being that it'll add a fair bit of code size to add the new module and all important functions.  So it would not be a core module but rather something that's enabled only on "big" ports that really benefit from this.  The existing `sys.platform`, `sys.implementation`, `sys.version` (and `os.uname()`) would continue to be the baseline way to get info about the port.

**Comment by iabdalkader** [comment]
I see your point, but `os` module is not shared between ports, which means it will have to be added to every port's moduos.c. If that's okay, how about this ?

```
>>> sys.version
'3.4.0 \n[GCC 11.1.0]'

>>> os.uname().release
'1.16.0-with-hal1.2.0'
```

**Comment by dpgeorge** [comment]
Sorry I didn't make it very clear: I think adding the `platform` module and using it for this info (SDK version, compiler version) is a good idea.  This module would be optional and not a substitute for `sys.platform` etc.  It would be used on ports that need/want to provide this extra information.

**Comment by iabdalkader** [comment]
>  I think adding the `platform` module and using it for this info (SDK version, compiler version) is a good idea

I agree, will send another PR to add the platform module and I'm closing this one.

**Pull request closed without merging**
