### PR TITLE
extmod: Add support for Stage by deshipu.

### PR DESCRIPTION
**Pull request by UnexpectedMaker**
Added Stage source that allows board level inclusion of the stage library as seen in UM_TINYPICO:
`#define MICROPY_PY_STAGE (1)`

This is needed to use the MicroPython version of the stage/sprite libraries by @deshipu for running games etc

### CODE REVIEW

**Review by deshipu — APPROVED** [review]
I endorse this pull request.

**Comment by jimmo** [comment]
Just some extra context for discussion on this PR (thanks @UnexpectedMaker , apologies to @deshipu if I've got anything wrong here please correct!)

 - `stage` (not in this PR) is tile and sprite engine library written in Python that uses `_stage` (included in this PR) for low-level tile buffer management and rendering. i.e. this is a private implementation detail, the actual library is https://circuitpython-stage.readthedocs.io/ (https://github.com/python-ugame/micropython-stage).
 - It's really useful, especially for large color displays where a full framebuffer isn't practical (it renders the tiles as it's generating the SPI data to transmit to the display on frame update) -- i.e. it's a different approach to the existing `extmod/modframebuf.c`.
 - `_stage` can currently be used as a user c module, and also already compiles as a dynamic native mpy (with the obvious caveat of running from RAM).
 - CircuitPython provide an equivalent `_stage` which lives in https://github.com/adafruit/circuitpython/tree/main/shared-bindings/_stage and then on certain boards they freeze the Python `stage` code (via submodule to https://github.com/python-ugame/circuitpython-stage ).

It sounds like the goal here is "boards that are build by MicroPython (i.e. the UM boards) might want to use stage" -- i.e. if @UnexpectedMaker wants the official firmware for TinyPico to include stage, then somehow the MicroPython build needs to make that happen. Note that this PR alone won't quite solve that because the Python code still needs to be frozen too.

I'm not sure that making _another_ copy of the code of `_stage` in micropython/extmod is the way to go. Here's some other ideas:
 - Leave this entirely up to the board definition (i.e. make it so board definitions can add whatever submodules they like inside the board defn dir and reference them from their `mpconfigboard.{cmake,mk}`).
 - Add micropython-stage as a submodule in micropython/lib (and possibly add a `.{cmake,mk}` fragment and `manifest.py` in that repo that can be used by any board definition).
(There are issues with the above too.. keeping the submodule up to date etc, although explicit versioning might be a good thing?).

(This entire post could substitute `ulab` for `stage` and potentially any number of other useful third-party modules, we also should solve that too).

**Comment by jimmo** [comment]
Another alternative is that if a mechanism to execute .mpy files from flash without copying them to RAM existed, then we could make this no longer be a build-time problem, and allow the most flexibility from the user's perspective.

For pure-Python libraries this is an easy win as .mpy files are _nearly_ completely interoperable on all ports. For libraries like `stage` or `ulab` with some native parts, you'd have to provide a .mpy for each supported arch (perhaps we could provide a template github action that did this without too much effort from the library maintainer).

**Comment by deshipu** [comment]
> I'm not sure that making another copy of the code of _stage in micropython/extmod is the way to go.

My plan is to remove the C file from the micropython-stage repository when this PR is merged, so that there will be only one copy.

> _stage can currently be used as a user c module, and also already compiles as a dynamic native mpy (with the obvious caveat of running from RAM).

Unfortunately I never managed to get it to work as a dynamic natice mpy, because it needs access to functions that are not exposed by default.

> Note that this PR alone won't quite solve that because the Python code still needs to be frozen too.

The Python code doesn't need to be frozen, it can be added as .mpy libraries to the filesystem. We freeze it in CircuitPython because back then CPY didn't support that yet.

**Pull request closed without merging**
