### PR TITLE
stmhal/usbdev: For MSC implement SCSI SYNCHRONIZE_CACHE command.

### PR DESCRIPTION
**Pull request by dpgeorge**
Currently just a dummy command that returns "success", but it's needed for some O/S's to correctly talk with the SCSI layer.

### CODE REVIEW

**Comment by dpgeorge** [comment]
This may fix issue #3123.

Thanks to @chrismas9 I was able to see that stmhal's USB MSC SCSI layer did not implement SYNCHRONIZE_CACHE but Windows 10 Creator seems to need it for correct behaviour of the MSC device.

@chrismas9 @kwagyeman when you get a chance would you mind testing this patch to see if it fixes the issue?

**Comment by chrismas9** [comment]
@dpgeorge, if you send me a dfu I will test it.

**Comment by chrismas9** [comment]
works well, PYBFLASH mounts instantly under Windows Creator.

**Comment by kwagyeman** [comment]
It works!

**Comment by dpgeorge** [comment]
This is now merged.

> Question - how did you figure this out?

It's thanks to @chrismas9 who supplied extensive USB logs for pyboard on Anniversary and Creators versions of Windows, as well as other working boards on Creators.  Looking through the logs it was possible to see (some of) the changes that Windows had to its SCSI driver and that pyboard needed to implement the synchronize cache command for it to work.

**Pull request merged**
