### PR TITLE
Unify header guard usage

### PR DESCRIPTION
**Pull request by webmeister**
Following #3173, I came across some more missing header guards, so I decided to fix them all in one go and ensure they look the same everywhere.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Just a few comments (not an exhaustive review):
- #2239 correctly points out that identifiers should not start with `__`.  The prefix `MICROPY_INCLUDED_` withouth the double underscore should be unique enough within this project that it can be used to guard headers.
- The mpconfigport.h files shouldn't need to be guarded because they are "internal" headers that should only ever be included by py/mpconfig.h (same goes for mpconfigboard.h).

**Comment by stinos** [comment]
Just wondering: would it be an option to use ```#pragma once``` (less code, more readable, no chance of duplicate definitions or typos, no caveats when renaming files)? It is not standard but there's also no major compiler not supporting it.

**Comment by dpgeorge** [comment]
> Just wondering: would it be an option to use #pragma once

I'm wary of old compilers (old gcc?), and others (ARM MDK, IAR?) that may not support it.

**Comment by webmeister** [comment]
Fixed all comments so far. This should also take care of #2239, at least for all files belonging to MicroPython (and not copied from somewhere else, e.g. the HAL files).

**Comment by stinos** [comment]
> I'm wary of old compilers (old gcc?), and others (ARM MDK, IAR?) that may not support it.

Yes that could be a concern, I'm not 100% sure I know all the possible compilers uPy should work with. Now gcc is ok since 3.4, which is already pretty old, and armcc and iar support it as well as far as I can see. But include guards work fine as well (if done correctly) and we have those already so in the end I don't think the benefits outweigh the changes required + risk of breaking builds with whatever compiler.

**Comment by pfalcon** [comment]
This looks like a massive patch, adding a lot of noise. uPy initially didn't have include guards at all, then we decided to allow multiple inclusion, but handle include guards on as-needed basis.

**Comment by webmeister** [comment]
> This looks like a massive patch, adding a lot of noise.

This is why this is a single patch, so that you have that noise only once in the history, and afterwards everybody can build on a clean base. Also, aren't the contents of the repository more important than the history? (git blame can handle it just fine, since it touches only unimportant lines.)

> but handle include guards on as-needed basis

I'm compiling the MicroPython source code in new and interesting ways, that need header guards in at least some of the files. Initially, #3173 was enough to make it work, but now more files came up. Should I really submit pull requests for a few files every time that happens? That's just more work (and I'd argue more noise) for all of us, and does not fix the inconsistent (and possibly wrong, #2239) usage that is present at the moment.

**Comment by pfalcon** [comment]
All I can say is that we have more important things to cleanup/make consistent. Otherwise, up to @dpgeorge .

**Comment by webmeister** [comment]
So I already did the work for you :)

If there are any more consistent rules, like classes of files that should not use header guards, I can fix that as well.

**Comment by dpgeorge** [comment]
This needs to happen eventually so may as well do it now.

Files that shouldn't have guards due to them being "internal" headers that are only included once:
- mpconfigport.h
- qstrdefsport.h
- mphalport.h
- esp8266/user_config.h
- ffconf.h
- qstrdefs.h
- vmentrytable.h
- windows_mphal.h
- teensy_hal.h
- pin_defs_teensy.h
- pin_defs_stmhal.h
- font_petme128_8x8.h

**Comment by webmeister** [comment]
Okay, I made the adjustments.

I guess the pattern behind windows_mphal.h and teensy_hal.h is "whatever is defined as MICROPY_MPHALPORT_H", so I removed the guards from the files of the other ports as well. I did not remove the guards from font_petme128_8x8.h, since this file is included in two different files (extmod/modframebuf.c and stmhal/lcd.c), which could cause trouble with my usage (where I basically put all the C code that I am interested in in a single C file).

Greetings from the EuroPython sprints :)

**Comment by dpgeorge** [comment]
Thanks @webmeister .  One last thing: because this is a large change can you please confirm the email address that is used in the commit is a real and valid one at which you can be reached in the future?  Also, the work needs to be done by your person (and not on behalf of a company, for example) in order that there are no issues in the future with copyright/IP/licensing.

**Comment by webmeister** [comment]
Yes, the e-mail address is valid and should continue to work for the forseeable future. The changes in this commit were done by me and not on behalf of my company (otherwise I would have used the company's e-mail address).

Out of curiosity, could you explain what problems you expect with contributions from a company? We (my company) are still carrying around a few patches, that I would like to submit should I ever find the time (and get the necessary agreements from the company). Of course, those patches have the same license as the MicroPython project, so unless you wish to change the license at some point, there should be no problem?

**Comment by dpgeorge** [comment]
Thanks @webmeister for doing this boring work, it's now merged in 299bc625864b9e624ed599c94a5f95870516139a with minor changes (mpthreadport.h doesn't need guards, neither did esp8266/qstrdefsport.h).

> Out of curiosity, could you explain what problems you expect with contributions from a company?

IANAL, but what I understand is: if you write non-trivial code that has some form of intellectual property associated with it (eg something more than a type declaration, or code that couldn't be written any other way) then you own the IP and copyright of said code.  If you do the coding during company time then most likely the company owns the IP and copyright (and with some companies, even code you write in your spare time is owned by the company).  It's possible to transfer IP/copyright (eg to me) and for an individual that's simply a matter of putting it in a short email/letter with a signature.  But to transfer IP/copyright from a company would be a bit more involved.  And there may be unknown constraints imposed by a companies policies which forbid having their IP as part of a project like this.

Licensing is a separate issue.  When you submit code here (which should be your own IP) you agree to let it be licensed under MIT.  If you submit on behalf of a company then it's assumed the company agrees to having it MIT licensed.  Then once the code is released with such a license, that particular code will remain available for use under that license forevermore.

> Of course, those patches have the same license as the MicroPython project, so unless you wish to change the license at some point, there should be no problem?

Right.  If the license were to be changed then we'd need permission from all IP/copyright holders.  If permission couldn't be obtained then we'd need to remove the contributed code (which can be very tricky if it has a long history).

**Comment by dpgeorge** [comment]
See the zephyr port for example of code that is contributed by a company (Linaro Ltd in this case).  So in principle we are ok with such contribution.

**Comment by pfalcon** [comment]
> If you do the coding during company time then most likely the company owns the IP and copyright

I'd say "almost definitely". A company pays compensation, and owns all results of employees' work.

> (and with some companies, even code you write in your spare time is owned by the company).

How is that possible? Well, maybe it's possible with secret government agencies which "own" the whole life of their employees, or commercial contractors of such agencies, but that's a niche case, and such folks hopefully know well that they should avoid any public activity. (There're corner cases like if you use company's equipment to make something, then it's also "owned" by company, so don't write your personal code on company's laptop if your contract have such a clause).

@webmeister : We just try to tighten up contribution/copyright policing of MicroPython (in the name of growing number of users, which also include companies). So, I hope that @dpgeorge's request is just a formal/sinecure request: 1) to confirm that if you submit your contribution personally, then it wasn't done at some company's time; 2) or, if it was done at company's time, then it's ok and not disguised as personal, e.g. you use company email address, and got approval of submission from your manager.

All this shouldn't come as a surprise for a person who participates in EuroPython sprints ;-), but we have a lot of contributions from folks who apparently never thought about such issues, and we try to raise awareness.

**Comment by dpgeorge** [comment]
> I'd say "almost definitely". A company pays compensation, and owns all results of employees' work.

One example where you own IP is working at a university.

> How is that possible? Well, maybe it's possible with secret government agencies which "own" the whole life of their employees, or commercial contractors of such agencies, but that's a niche case

It's actually more common than you might think, see eg https://news.ycombinator.com/item?id=2208056 .  In particular it's not a good idea to work on "company related ideas" during your spare time.  And in some cases your employer owns your IP *for a fixed period after your employment is terminated*.  You need to be careful when signing an employment contract.

**Pull request closed without merging**
