### PR TITLE
nRF LED behaviour

### PR DESCRIPTION
**Pull request by rolandvs**
Redone #5094

### CODE REVIEW

**Comment by glennrub** [comment]
Great @rolandvs! This looks good =)

**Comment by glennrub** [comment]
Thanks @rolandvs! Merged in a069340c1ee14fe5e956e38aa4482f526145d7d3 with some adjustments in the commit messages.

**Comment by rolandvs** [comment]
I think you forgot the other file :-)

**Comment by glennrub** [comment]
I only linked the top commit of the two. Merged in 226399bcef8abf2f831cdb139c9bd0d416850ab5 and a069340c1ee14fe5e956e38aa4482f526145d7d3.

**Pull request closed without merging**
