### PR TITLE
.travis.yml: Switch to Ubuntu 14.04 Trusty.

### PR DESCRIPTION
**Pull request by pfalcon**
This allows to cut number of packages installed from 3rd-party package repos,
and otherwise cut number of overrides and hacks.

### CODE REVIEW

**Comment by pfalcon** [comment]
This fixes nanbox build issue too.

**Comment by dpgeorge** [comment]
Awesome!

We may even be able to switch to Travis' new build system using Trusty.

**Comment by pfalcon** [comment]
This already should be new build infra - they change it behind the scenes in different directions. Even older builds had notice: " This job ran on our new platform for Legacy Precise builds. Please read our blog post for more information. (https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future)".

Merged.

**Comment by dpgeorge** [comment]
Yes I see that trusty requires sudo and uses the very new build system.  That's good then.

**Pull request closed without merging**
