### PR TITLE
WIP: Update rp2 docs

### PR DESCRIPTION
**Pull request by mattytrentini**
As part of the [Google Season of Docs](https://developers.google.com/season-of-docs), the rp2 docs will be updated.

At least a quickref, intro and general information - like the other ports - will be added.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks!  Are you happy for this to be merged now, ready for updating?

**Comment by mattytrentini** [comment]
I think yes, probably best to merge it - then @NitiKaur can get on with updating it.

**Comment by robert-hh** [comment]
I just stumbled over small glitch at the UART example. Pins have to be provided as pin objects, not as numbers.

**Comment by mattytrentini** [comment]
> I just stumbled over small glitch at the UART example. Pins have to be provided as pin objects, not as numbers.

Thanks, we'll make sure it's either documented or fixed.

**Comment by dpgeorge** [comment]
Merged in a6a8941d84a4d38129bdc00be701a7ca8fc867b6 with some tweaks to the quickref to fix some inaccuracies.

**Pull request closed without merging**
