### PR TITLE
webassembly/asyncio: Schedule run loop when tasks are pushed to queue.

### PR DESCRIPTION
**Pull request by dpgeorge**
In the webassembly port there is no asyncio run loop running at the top level.  Instead the Python asyncio run loop is scheduled through setTimeout and run by the outer JavaScript event loop.  Because tasks can become runable from an external (to Python) event (eg a JavaScript callback), the run loop must be scheduled whenever a task is pushed to the asyncio task queue, otherwise tasks may be waiting forever on the queue.

### CODE REVIEW

**Comment by ntoll** [comment]
Bravo @dpgeorge

**Comment by WebReflection** [comment]
if happy about this, please remember to publish on *npm*, thank you! 🙏

**Comment by ntoll** [comment]
What @WebReflection said, @dpgeorge :rofl:

**Comment by EmilioMartinez** [comment]
Hi @dpgeorge, is there any chance to implement this change and the [top-level support for Event](https://github.com/micropython/micropython/pull/15299) to the RP2 port? Should I open an issue?

Just to clarify if it applies, the behaviour I see is that on the PiPico top-level waiting for an Event terminates the program (unless something else is running), and setting events seems to queue them without inmediate result, only to resume when something else wakes the scheduler.

I think it might be related to [this issue] (https://github.com/micropython/micropython/issues/16318), or even [this other](https://github.com/micropython/micropython/issues/13770)

**Comment by dpgeorge** [comment]
> is there any chance to implement this change and #15299 to the RP2 port?

No, it's not possible to implement this on anything other than the webassembly port, because that port has an async-like scheduler in the "operating system", ie browser/Node.



> the behaviour I see is that on the PiPico top-level waiting for an Event terminates the program (unless something else is running), and setting events seems to queue them without inmediate result, only to resume when something else wakes the scheduler.

If you think this is a bug then please make a minimal reproduction of your code that still has the bug and create a new issue for it.

**Pull request merged**
