### PR TITLE
py/objstr: Make .count() method configurable.

### PR DESCRIPTION
**Pull request by pfalcon**
Default is disabled, enabled for unix, qemu-arm ports. Saves 408 bytes
on x86.

### CODE REVIEW

**Comment by pfalcon** [comment]
> Is there a plan as to which methods are configurable and which not? It seems a bit arbitrary to just disable this one, and there's no argument provided why it should be configurable.

My plan is to gradually reduce the size of the minimal port. Ideally, I'd like to reach the state where it's possible to have an interpreter which has only str's (with minimal set of operations), lists and dicts, i.e. reduced to Scheme-like state. Besides pure beauty and small size of it, it would be also a good base to play with various alloc/gc/etc. algorithms (i.e. patch largely reduced codebase).

Gradually because otherwise it's pretty dumb work and there're more priority things to finish yet, but doing that nonetheless gives the nice feeling of progress (and compensates for code increases done).

With this specific change I follow existing pattern, of being able to enable str methods one by one (which I think it's good, for such a core class). And specific method was chosen (first) because my feeling is that's one of the rarely used ones (I for one don't remember when last time I used it).

> Also, if it's going to be configurable, it needs to be reenabled for all existing ports to not regress their features.

Or keep it enabled by default and disable just for minimal ports? I think that having it disabled makes sense due to reasons above ("rarely used"), and happy to make the change if you ack it.

**Comment by dpgeorge** [comment]
> Or keep it enabled by default and disable just for minimal ports?

That would certainly be a smaller diff/change, and mean that 3rd party ports don't need to go and reenable it explicitly themselves (or find out that it disappeared only because in their next release a user reported it as suddenly gone).  So that would be my preference.

**Comment by pfalcon** [comment]
> So that would be my preference.

Updated.

**Comment by dpgeorge** [comment]
Ok, thanks for updating, merged in 5a91fce9f868eeba37a0b1cf6c3b4435ed5eecec and a5273133829ed3e2a8c8e3c44e37e198e109f340 (with minor edits to commit message to reflect that it's enabled by default).

**Pull request closed without merging**
