### PR TITLE
docs: Enable warnings as errors

### LINKED ISSUE #6097: Warnings when building docs
While working on a documentation patch, I got a few warnings not related to my work when building the docs.

How to reproduce :

```
cd docs
make html
```

Here is the error ;

```
workspace/micropython/docs/library/micropython.rst:102: WARNING: 'any' reference target not found: MICROPY_PY_MICROPYTHON_HEAP_LOCKED
/workspace/micropython/docs/reference/pyboard.py.rst:70: WARNING: 'any' reference target not found: --baudrate
```

### PR DESCRIPTION
**Pull request by dlech**
This enables the `-W` option which treats warnings as errors when running `sphinx-build`.

Also fix two existing warnings.

Fixes #6097

### CODE REVIEW

**Comment by dpgeorge** [comment]
I'm using v3.0.3 of Sphinx and it seems to have more warnings, which leads to the build of the docs failing with this PR.  Eg:
```
docs/library/esp32.rst:87:duplicate object description of esp32.Partition.readblocks, other instance in library/esp32, use :noindex: for one of them
```
I'm in favour of using `-W` to build the docs, but the above issues would need to be fixed first.

**Comment by dpgeorge** [comment]
Here's a list of all the warnings I get:
```
docs/library/esp32.rst:87: WARNING: duplicate object description of esp32.Partition.readblocks, other instance in library/esp32, use :noindex: for one of them
docs/library/esp32.rst:89: WARNING: duplicate object description of esp32.Partition.writeblocks, other instance in library/esp32, use :noindex: for one of them
docs/library/network.WLAN.rst:104: WARNING: duplicate object description of network.WLAN.config, other instance in library/network.WLAN, use :noindex: for one of them
docs/library/pyb.Flash.rst:28: WARNING: duplicate object description of pyb.pyb.Flash, other instance in library/pyb.Flash, use :noindex: for one of them
docs/library/pyb.Flash.rst:38: WARNING: duplicate object description of pyb.Flash.readblocks, other instance in library/pyb.Flash, use :noindex: for one of them
docs/library/pyb.Flash.rst:40: WARNING: duplicate object description of pyb.Flash.writeblocks, other instance in library/pyb.Flash, use :noindex: for one of them
docs/library/uio.rst:116: WARNING: duplicate object description of uio.StringIO, other instance in library/uio, use :noindex: for one of them
docs/library/uio.rst:117: WARNING: duplicate object description of uio.BytesIO, other instance in library/uio, use :noindex: for one of them
docs/library/uos.rst:255: WARNING: duplicate object description of uos.AbstractBlockDev.readblocks, other instance in library/uos, use :noindex: for one of them
docs/library/uos.rst:270: WARNING: duplicate object description of uos.AbstractBlockDev.writeblocks, other instance in library/uos, use :noindex: for one of them
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] wipy/tutorial/wlan
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
docs/library/index.rst:26: WARNING: 'any' reference target not found: MicroPython port
docs/library/index.rst:36: WARNING: 'any' reference target not found: MicroPython port
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
docs/library/micropython.rst:102: WARNING: 'any' reference target not found: MICROPY_PY_MICROPYTHON_HEAP_LOCKED
docs/library/network.rst:41: WARNING: 'any' reference target not found: MicroPython port
docs/library/network.WLAN.rst:119: WARNING: 'any' reference target not found: MicroPython port
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
docs/library/uerrno.rst:9: WARNING: 'any' reference target not found: MicroPython port
docs/library/uerrno.rst:17: WARNING: 'any' reference target not found: MicroPython port
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
docs/library/ure.rst:141: WARNING: 'any' reference target not found: MicroPython port
docs/library/ure.rst:145: WARNING: 'any' reference target not found: MicroPython port
docs/library/ure.rst:187: WARNING: 'any' reference target not found: MicroPython port
docs/library/ure.rst:196: WARNING: 'any' reference target not found: MicroPython port
docs/library/ure.rst:202: WARNING: 'any' reference target not found: MicroPython port
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
docs/library/usocket.rst:37: WARNING: 'any' reference target not found: MicroPython port
docs/library/usocket.rst:37: WARNING: 'any' reference target not found: MicroPython Unix port
docs/library/usocket.rst:58: WARNING: 'any' reference target not found: MicroPython port
docs/library/usocket.rst:144: WARNING: 'any' reference target not found: MicroPython port
docs/library/usocket.rst:154: WARNING: 'any' reference target not found: MicroPython port
docs/library/usocket.rst:162: WARNING: 'any' reference target not found: MicroPython port
docs/library/usocket.rst:167: WARNING: 'any' reference target not found: MicroPython port
docs/library/usocket.rst:262: WARNING: 'any' reference target not found: MicroPython port
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
docs/library/ussl.rst:26: WARNING: 'any' reference target not found: MicroPython port
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
templates/replace.inc:7: WARNING: 'any' reference target not found: CPython
docs/reference/packages.rst:17: WARNING: 'any' reference target not found: MicroPython port
docs/reference/packages.rst:57: WARNING: 'any' reference target not found: CPython
docs/reference/packages.rst:75: WARNING: 'any' reference target not found: MicroPython port
docs/reference/packages.rst:75: WARNING: 'any' reference target not found: MicroPython Unix port
docs/reference/packages.rst:81: WARNING: 'any' reference target not found: MicroPython port
docs/reference/packages.rst:126: WARNING: 'any' reference target not found: MicroPython port
docs/reference/packages.rst:126: WARNING: 'any' reference target not found: MicroPython Unix port
docs/reference/packages.rst:146: WARNING: 'any' reference target not found: MicroPython port
docs/reference/packages.rst:162: WARNING: 'any' reference target not found: MicroPython port
docs/reference/packages.rst:171: WARNING: 'any' reference target not found: MicroPython Unix port
docs/reference/packages.rst:284: WARNING: 'any' reference target not found: MicroPython Unix port
docs/reference/pyboard.py.rst:70: WARNING: 'any' reference target not found: --baudrate
```

**Comment by dlech** [comment]
Should we add a CI build for docs too? With GitHub Actions, it would be possible to create a test that only runs if a file in the `docs/` directory is modified (as far as I know such a condition is not possible on Travis).

**Comment by dpgeorge** [comment]
> Should we add a CI build for docs too?

Yes!

> With GitHub Actions, it would be possible to create a test that only runs if a file in the `docs/` directory is modified

Would be interesting to try out GitHub Actions, it might eventually be able to replace Travis/Appveyor (if that's a good idea).

**Comment by dhalbert** [comment]
> Would be interesting to try out GitHub Actions, it might eventually be able to replace Travis/Appveyor (if that's a good idea).

We have switched to GitHub Actions for CircuitPython, if you want to take a look: https://github.com/adafruit/circuitpython/tree/master/.github/workflows, and actually nearly everything in the adafruit repos. It has been generally reliable, but occasionally flaky (but then so is Travis). The number of simultaneous jobs possible is impressive, and is one of the main reasons we switched.

**Comment by dlech** [comment]
I have updated this to add a GitHub action and fix all of the Sphinx v3.x warnings. This may have to just get merged to enable the action, but I did create a non-fork repository to test that the GitHub action does work as expected already.

**Comment by dpgeorge** [comment]
Thanks a lot, that's great!  Let's merge it and see how the actions work.  Rebased and merged in eeca2c3cbe84975ffabd7fda932b2f5674e8b0fc and 1e6d18c915ccea0b6a19ffec9710d33dd7e5f866

**Pull request closed without merging**
