### PR TITLE
mimxrt: Update the board .json files and add deploy_xx.md files.

### PR DESCRIPTION
**Pull request by robert-hh**
- Add board.md files for MIMXRT1060_EVK and MIMXRT1064_EVK warning
  about the experimental state.
- Add separate deploy_teensy.md and deploy_mimxrt.md files.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Can you please delete the existing empty `deploy.md` now that it's unused?

**Comment by robert-hh** [comment]
Done. The PR is updated.

**Review by dpgeorge — APPROVED** [review]

**Comment by robert-hh** [comment]
Rebased.

**Comment by dpgeorge** [comment]
Merged in 7cc9b257a9af77a9a782e055252f2c196c212d49

**Pull request closed without merging**
