### PR TITLE
IGMP added to socket.setsockopt()

### PR DESCRIPTION
**Pull request by Timmenem**
Inspired by Issue [#2691](https://github.com/micropython/micropython/issues/2691), I added IGMP support to micropython's `socket.setsockopt()` function.

I added a switch that checks for the option's level, the option that is to be changed and the value that the option is to be set to. 

The option levels that are supported  are
```
- SOL_SOCKET
- IPPROTO_IP
```
The changes make it possible to use all options relevant for IGMP on the IPPROTO_IP level:
```
- IP_ADD_MEMBERSHIP / IP_DROP_MEMBERSHIP
- IP_MULTICAST_TTL
- IP_MULTICAST_LOOP
- IP_MULTICAST_IF
```
Most of the code was taken from lwip's [sockets.c](https://github.com/pfalcon/esp-open-lwip/blob/8c39d2179a273553466043f388772abb6251a4ca/lwip/api/sockets.c#L1906) and I tried to stay as close to the standard
lwip implementation as possible. The only piece of code that is not derived from lwip's sockets.c is the `inet_aton()` function that I took from [here](https://gist.github.com/Vincent-Ma/7943007d346ad030888d37e0e6ae55fc#file-modlwip-c-L1353), as proposed by [@Vincent-Ma](https://github.com/Vincent-Ma) in Issue [#2691](https://github.com/micropython/micropython/issues/2691)

Joining a multicast group can now be achieved with the following Python code:
```
mreq =  ustruct.pack("4s",  socket.inet_aton("239.255.255.250")) + ustruct.pack("l", socket.INADDR_ANY)
socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
```
Setting `IP_MULTICAST_TTL`, `IP_MULTICAST_LOOP` and `IP_MULTICAST_IF` is achieved in a similar way:

```
iface = ustruct.pack("4s", sockets.inet_aton("239.255.255.250")
sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_IF, iface)

sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_LOOP, 1)

sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 32)
```

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.  Since there's a bit of code it might take some time to review.  But my main question would be: does it allow you to configure multicast in *exactly* the same way as is done in CPython, ie the code would be compatible?

**Comment by Timmenem** [comment]
Sorry this took me so long, but I finally had time to look into this.

With my code, the usage of `socket.setsockopt()` is exactly the same as with CPython's `setsockopt()`.
But, since the multicast group's IP and port have to be passed as binary data packed with `struct.pack()`,
there are still some issues regarding Micropython's `ustruct` module.

The "official" way of packing the data (at least according to the [Python Wiki](https://wiki.python.org/moin/UdpCommunication#Multicasting.3F)) would be:
```
mreq = struct.pack("=4sl", socket.inet_aton("224.51.105.104"), socket.INADDR_ANY)
```

Unfortunately, Micropython's `ustruct` module doesn't support the `=4` prefix, hence the line of code above cannot be used with Micropython.

Nevertheless, the code from my example above:
```
mreq =  ustruct.pack("4s",  socket.inet_aton("224.51.105.104")) + ustruct.pack("l", socket.INADDR_ANY)
```

works with regular Python, too. 

Furthermore, there are lots of tutorials on this subject on the web and each one of them seems
to use a different set of prefixes when calling `struct.pack()` (e.g., [this one](https://stackoverflow.com/questions/603852/multicast-in-python) or [this one](https://pymotw.com/2/socket/multicast.html)). 

So, I would consider this more of an issue with Micropython's ustruct module than with my code additions, which basically just resemble CPython's way of handling multicasts.

**Review by pfalcon — CHANGES_REQUESTED** [review]
Please follow guidelines in https://github.com/micropython/micropython/blob/master/CONTRIBUTING.md

**Comment by Timmenem** [comment]
Hello everyone,
I was quite busy the last weeks, but I eventually looked into it.

Except for some comments that did not match the code conventions and my commit messages (I am new to contributing to projects on Github, apologies for that), I did not find any significant problems with the code.

So I merged the upstream branch and changed some comments, but I guess there is more to pfalcon's comment. If there are still issues, could someon please give me a hint?

**Comment by dpgeorge** [comment]
@Timmenem thanks for updating the PR.  One main code-style issue that still remains is that this project uses 4 spaces per indent level.

> Most of the code was taken from lwip's sockets.c and I tried to stay as close to the standard
> lwip implementation as possible.

If you copied code from lwip then copyright and licensing need to be considered.  What are the licensing conditions of the file you copied from?  Ideally it would be written from scratch to prevent any possible issues in the future with licensing/copyright.

> The only piece of code that is not derived from lwip's sockets.c is the inet_aton() function that I took from here, as proposed by @Vincent-Ma in Issue #2691

Is this still true, did you copy inet_aton()?

**Review by pfalcon — CHANGES_REQUESTED** [review]
@Timmenem: I went thru the patch and inline-commented on some issues. I stopped when I counted more than half-dozen, but there're many more in the code, similar to already noted. You would just need to go over each line you add or change and check whether it complies with the code style.

That may take some time, because you patch is big. And that's the real issue with it actually - this patch adds too much code, definitely more than really needed. The best suggestion I would have is: please rework this patch, split it into 2 commits, yet better 2 pull requests: one for inet_pton() (there should not be inet_aton(), it's legacy and not part of MicroPython API), another for setsockopt(IP_ADD_MEMBERSHIP) (and not any other options!). Please limit the number of changed lines in each to 20. That would be the best route forward, and as the number of change lines is small, it will be quick and easy to write, and easy to review. Thanks!

**Comment by dpgeorge** [comment]
> another for setsockopt(IP_ADD_MEMBERSHIP) (and not any other options!).

IMO there should also be IP_DROP_MEMBERSHIP.

Re code style: you can use `astyle -KSUHp -s4` to check your changes conform.

**Comment by pfalcon** [comment]
> IMO there should also be IP_DROP_MEMBERSHIP.

What's the realistic usecase? One can (should be able to) drop all memberships by closing a socket, and I'd wait until a realistic app which wants to hop one multicast group to another before implementing it. Anyway, can be implemented, though 20-line constraint will be tight ;-).

**Comment by dpgeorge** [comment]
> What's the realistic usecase? One can (should be able to) drop all memberships by closing a socket

Subscribing to multiple addresses at once, and then being able to drop one or more of them without needing to close the entire socket and reopen a new one, potentially missing some packets.

**Comment by pfalcon** [comment]
So when is this needed, which protocol, what application work like that?

**Comment by dpgeorge** [comment]
> which protocol, what application

A custom protocol, a custom application.

**Comment by pfalcon** [comment]
Then custom build of MicroPython can be used for that "custom" stuff ;-). In the meantime, you can skip coding DROP support, testing it manually, then writing an automated test for it, because https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it .

Of course, it can be implemented right away, because it's trivial, not a point of contention. That's just an illustration of what logic should be used to decide what should go into the patch being worked on right here, right now - nothing superfluous.

**Comment by pfalcon** [comment]
> Please limit the number of changed lines in each to 20.

Here's an example how to do it: https://github.com/micropython/micropython/pull/3249 . Easy to develop, easy to test, easy to review.

**Comment by dpgeorge** [comment]
Closed in favour of the merged #3249.

**Pull request closed without merging**
