### PR TITLE
esp8266: Make available more reset causes

### PR DESCRIPTION
**Pull request by jcea**

### CODE REVIEW

**Comment by jcea** [comment]
I don't know where to add this to the documentation. Where is the ESP8266 specific documentation details?

**Comment by kfricke** [comment]
line 142 of 
https://github.com/micropython/micropython/blob/master/docs/library/machine.rst
or
http://docs.micropython.org/en/latest/esp8266/library/machine.html#machine-constants

**Comment by jcea** [comment]
@kfricke, much appreciated, but the new values are specific to ESP8266. What would be the better way to document them without "polluting" other ports documentation?.

Thanks!.

**Comment by pfalcon** [comment]
MicroPython moves away from port-specific and towards single generic documentation. The only place for port specific things is "General Information" page for a port, e.g. http://docs.micropython.org/en/latest/esp8266/esp8266/general.html

**Comment by dpgeorge** [comment]
See also #2500 (additional constants for stmhal).

**Pull request closed without merging**
