### PR TITLE
travis: Add job to build and test unix minimal port.

### PR DESCRIPTION
**Pull request by dpgeorge**
To test that test-suite can run with minimal features enabled.

### CODE REVIEW

**Comment by nevercast** [comment]
Good idea. Is it worth making minimal configs for other ports to ensure they aren't depending on something that should be an optional feature?

**Comment by dpgeorge** [comment]
> Is it worth making minimal configs for other ports to ensure they aren't depending on something that should be an optional feature?

That's a lot of work, and since other (bare-metal) ports don't have automated tests running in Travis CI, I don't see how it's that useful.  Running unix-minimal should be enough to check that the test suite can be run against almost any build, regardless of its config options.

**Comment by dpgeorge** [comment]
Looks like this will require a lot of work to update the tests, to get unix-minimal to pass the tests...

**Comment by dpgeorge** [comment]
All tests fixed, and merged.

**Pull request merged**
