### PR TITLE
stmhal: Print more information at HardFault time

### PR DESCRIPTION
**Pull request by dhylands**
I found some code online which gets a bunch of the register values when a HardFault occurs, so I extended the hard fault handler.

### CODE REVIEW

**Comment by danicampora** [comment]
Looks good. It's very similar to what I have for the CC3200, only that there's no printing there, only meant to be inspected with the debugger.

**Comment by dpgeorge** [comment]
Ok.  I assume there are no issues with copyright of the code since you linked to the blog?

**Comment by dhylands** [comment]
> Ok. I assume there are no issues with copyright of the code since you linked to the blog?

Good question. I couldn't find any explicit licensing on any of the posts I found.

I can contact the author and determine if its acceptable to republish using MIT license.

**Comment by dhylands** [comment]
I found all the information I need to write a HardFault Handler in the ARMv7M Architecture Reference Manuak, so let me write my version of this and then there won't be any licensing issues.

**Comment by dhylands** [comment]
Here's a much leaner, and IMHO easier to understand version.

**Comment by dpgeorge** [comment]
Merged in 41b688e25f537479afc0b0e806cd0cb02ea47bb0.  Thanks @dhylands!

**Pull request closed without merging**
