### PR TITLE
Added support for custom compile_c

### PR DESCRIPTION
**Pull request by igorgatis**

### CODE REVIEW

**Comment by dpgeorge** [comment]
Out of interest, what do you override custom_c for?

**Comment by igorgatis** [comment]
Ah, I was not aware of this override trick.

My reason: I'm not using gcc, command line looks very different.

**Comment by igorgatis** [comment]
Ah, I was not aware of this override trick.

My reason: I'm not using gcc, command line looks very different.

**Comment by dpgeorge** [comment]
Since @dhylands has provided an alternative, and it's best not to add stuff when it's not necessary, I suggest we close this.

**Pull request closed without merging**
