### PR TITLE
ports/esp32: Added SDCard support and other tweaks.

### PR DESCRIPTION
**Pull request by UnexpectedMaker**

### CODE REVIEW

**Comment by dpgeorge** [comment]
The esp32 IDFv4.4 build is failing here.

**Comment by UnexpectedMaker** [comment]
> The esp32 IDFv4.4 build is failing here.

What 4.4 version are you on? I did this on a live stream today.... built TinyPICO, some S2 and GENERIC_S3 boards and they all built fine. In fact, I built the Generic_S3_SPRAM many times...

```
 ❯ idf.py --version                           
ESP-IDF v4.4-dev-3649-gf6db71539e
```
It's failing on `makeqstrdefs.py` and a subprocess call - why would anything I did effect that?
I cant even tell from the error what's wrong. Can you give me a hint at what is broken?

**Comment by dpgeorge** [comment]
Looks like it failed building GENERIC_S3 with:
```
/home/runner/work/micropython/micropython/ports/esp32/machine_dac.c:37:10: fatal error: driver/dac.h: No such file or directory
 #include "driver/dac.h"
          ^~~~~~~~~~~~~~
compilation terminated.
```

**Comment by dpgeorge** [comment]
The IDF 4.4 version is 142bb32c50fa9875b8b69fa539a2d59559460d72 (see `tools/ci.sh`).

**Comment by UnexpectedMaker** [comment]
> Looks like it failed building GENERIC_S3 with:
> 
> ```
> /home/runner/work/micropython/micropython/ports/esp32/machine_dac.c:37:10: fatal error: driver/dac.h: No such file or directory
>  #include "driver/dac.h"
>           ^~~~~~~~~~~~~~
> compilation terminated.
> ```

But `#define MICROPY_PY_MACHINE_DAC  (0)` is set in mpconfigboard.h

**Comment by UnexpectedMaker** [comment]
Ok, fixed. Seems I got my repo into a right royal mess.

**Comment by dpgeorge** [comment]
Squashed and merged in 1904833e0c7c650e86d8e151ea57ea1fa2ab09bd

**Comment by UnexpectedMaker** [comment]
Thanks @dpgeorge :)

**Pull request closed without merging**
