### PR TITLE
tests: fixed line endings causing test failures

### PR DESCRIPTION
**Pull request by ryannathans**
fixes issue described in #1857 where tests would run and fail on windows due to line endings

### CODE REVIEW

**Comment by ryannathans** [comment]
Intereting... Looks like the conversion of existing files from \n to \r\n is required for testing PC micropython but breaks testing connected boards whereas leaving them as \n breaks PC micropython testing but fixes testing for connected boards.

**Comment by ryannathans** [comment]
Resolved test issues on windows testing of attached boards. Then I resolved the issues introduced with the original approach - ended up being a very simple solution.

Only tested on windows but I can't imagine how this fix would break something on linux.

Why can't Windows just be like all other systems, save a byte and use \n?????

**Comment by dpgeorge** [comment]
This is not logically correct.

Note that the output from running tests on pyboard is a file with \r\n endings (regardless of Linux/Windows/etc host).  This is because most terminal programs (eg picocom) require \r\n at the end of a line.

So what this line does (the one you changed) is convert those \r\n's to \n to be tested against the output from running on the host PC, where the lines are assumed to end in \n only.

There are too many existing places in run-tests that try to get around this problem of \r\n, and this just makes it even more complicated.

I think the proper solution is to just convert everything to use \n.  I submitted a PR #1876 for that.  @ryannathans can you please check if #1876 fixes your problem?  Can you also check that you can run the PC version of MicroPython under Windows, and that tests pass?

**Comment by ryannathans** [comment]
@dpgeorge **I have performed the tests on windows only**, #1876 fixes the problem. Tests that fail are due to other reaons, **line ending issue is resolved**. I will test STM32F439 port in approx 12 hours when I am with my boards again (I should really keep one in my bag at all times...). I have posted the test results on the conversation attached to #1876

**Pull request closed without merging**
