### PR TITLE
drivers/display/ssd1306.py /ssd1306: convert umlauts

### PR DESCRIPTION
**Pull request by mardigras2020**
umlauts (ä, ü, ö, Ä, Ü, Ö) and ß are not supportet and not correct displayed
This change transformes these characters to ae, ue, ..., ss
tested on ESP32, feel free to integrate

### CODE REVIEW

**Comment by tve** [comment]
I'm sure the French won't let you leave out the characters with accents ;-)

**Comment by mcauser** [comment]
I not sure this is the right place for this.
It will slow down the `.text()` method for the majority of users who won’t use the feature.

Since the display driver is hard coded to use a font which only supports ASCII chars, I think the `.text()` method should be provided the exact ASCII string to be displayed, with any Unicode->ASCII translations happening earlier/separately. Perhaps an i18n wrapper. Eg. `.text(i18n('str with accents'), ...)`

Custom fonts in the framebuffer would be another option

**Comment by robert-hh** [comment]
I agree to @mcauser. Things like that should be done outside the driver. You can make you own wrapping class based on the SSD1306 class, which performs the required changes in it's text() method.

**Comment by peterhinch** [comment]
[This repo](https://github.com/peterhinch/micropython-font-to-py) allows any font, with any character set, to be created and displayed.

**Comment by mardigras2020** [comment]
thank you for the feedback.

**Pull request closed without merging**
