### PR TITLE
esp8266: Add support for dht sensors

### PR DESCRIPTION
**Pull request by swkim01**
I created a module of dht humidity/temperature sensors for esp8266. Dht11/Dht22 sensors for the module were tested and OK. You can program as follows:

import time
import machine, dht
ds = dht.DHT(machine.Pin(4))
while True:
    humi, temp = ds.read()
    print("Humidity={} Temperature={}".format(humi, temp))
    time.sleep_ms(1000)

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution!

It might be better if we can write the entire driver in Python.  Then it's more portable (to other boards) and easier for people to modify if they need to.

The DHT is relatively simple and to read it you just need to be able to time pulses.  There is a 50us low between pulses and the length of the pulse (which is high) tells if the bit is a 0 or a 1 (pulse length is 26u-70us).  You need to read 40 bits (40 pulses) in a row.

So the question is: is Python fast enough to time the length of a pulse and store it in an array within 50us?

I did some tests and it looks like it will be able to.  With interrupts disabled I tested the following loop:
```
for i in range(n):
    vals[i] = time.ticks_us()
```
(For a proper DHT driver the body could be something like: vals[i] = time_pulse().)

At 80MHz the ESP8266 takes 30us-31us per loop.  At 160MHz it takes 15us-16us per loop.  It's very stable with interrupts disabled.

Note that the first iteration of the loop takes about 3-4 times longer, probably due to cache effects.

But these numbers are definitely within 50us, so I'd say with a way of timing pulses (see #2052) we can implement a DHT driver in pure Python.  Then it should work on all boards (so long as they are fast enough).

Steps to move forward:

1. Provide a way to enable and disable interrupts.

2. Implement a way to time pulses on a pin.

3. Write the driver in Python.

**Comment by dpgeorge** [comment]
I tried implementing the driver in Python (after making functions to disable irqs and time pulse widths on a pin).

It works (at 80 and 160 MHz), but only if you make sure to preload the cache of the ESP before entering the critical loop.

The function to do a read of the DHT sensor is:
```python
    def _read(self):
        # array to store input pulse width values
        vals = bytearray(41)

        # reset device
        p = self.pin
        p.high()
        time.sleep_ms(250)
        p.low()
        time.sleep_ms(20)

        # need to perform this dummy operation to load the ESP's cache
        vals[0] = p() 

        # timing critical
        try:
            machine.irq_allowed(0)
            p.high()
            time.sleep_us(40)
            # we don't have time here to check the pin is low, just hope it is

            # sample the pulse widths (high pulses): DHT initial response + 40 bits
            for i in range(41):
                vals[i] = p.time_us(1)
        finally:
            machine.irq_allowed(1)

        return vals
```
This just returns the bits, they need to be converted to temperature and humitidy.

It's a big hack that one needs to preload the cache before the critical loop.  Would we accept such a hack in a generic driver for all boards?  The alternative is to write the code in C (as per the original intention of this PR).  Maybe we can put all timing critical driver functions (eg 1-wire, neopixel, DHT) in a single module.

**Comment by pfalcon** [comment]
> machine.irq_allowed

There's no such function in machine API.

> Would we accept such a hack in a generic driver for all boards?

I guess nope, just the same as shouldn't accept inability to use 1-wire, DHT sensors on 1MHz CPU frequency (which otherwise should be fine).

> Maybe we can put all timing critical driver functions (eg 1-wire, neopixel, DHT) in a single C module.

And possibly try to generalize their implementations to avoid code duplication.

**Comment by dpgeorge** [comment]
@swkim01 this will need significant rework.  For example, esp_dht_read should be written in Python and esp_dht_readSensor should be the only (public) function written in C.  Probably easier to leave it to me.

**Comment by swkim01** [comment]
@dpgeorge Thank you for your concern. I hope you will make it soon.

**Comment by dpgeorge** [comment]
I added a DHT11/22 driver in 7ebfe09fbd5e8ce00ae811aea1f2d84dfc73a577.  @swkim01 can you please check that it works for you?  Usage:
```
import dht
import machine
d = dht.DHT22(machine.Pin(4))
d.measure()
d.temperature()
d.humitidy()
```
There's also a DHT11 class if you have that device instead.

**Comment by swkim01** [comment]
@dpgeorge You did good job! I tested both dht22 and dht11 and had no problem. Thank you again.

**Comment by mcauser** [comment]
@dpgeorge typo in you previous commit ^ "d.humidity()"

**Comment by mcauser** [comment]
Thanks @dpgeorge Works perfectly on my DHT11, DHT12 (using DHT11 class) and DHT22

For those reading, DHT11 and DHT22 pins, left to right, grill facing you.
1 VDD 3v3 or 5V
2 Data
3 Not connected
4 GND

The DHT12 is an upgrade to the DHT11 sensor and adds I2C interface.
Having a little trouble getting multi-byte reads to work.
http://forum.micropython.org/viewtopic.php?f=16&t=2151
Works fine in "1-wire" / DHT11 mode though.

DHT12 in DHT11 mode:
1 VDD 3v3 or 5V
2 Data
3 Connect to GND to disable I2C
4 GND

DHT12 in I2C mode:
1 VDD 3v3 or 5V
2 SDA
3 GND
4 SCL

**Pull request closed without merging**
