### PR TITLE
stmhal: Add STM32F7 Support - usb serial/internal flash disk

### PR DESCRIPTION
**Pull request by dhylands**
Fix make-pins.py to allow Port K
Add more pind definitions
USB Serial is working now
Added support for USART having Tx and Rx on different ports.
Fixed make-pins.py conditional pins to work with this.
Make USART1 be the default HWUART repl.
The STLINK usb connector also looks like a USB serial port which is attached to USART1 on the STM32F7.
Added debug capability to print out more information about a Hard Fault (#if'd off by default)

Extracted gpio clock enable logic into mp_hal_enable_gpio_clock
and called from anyplace which might need to use gpio functions
on ports other than A-D

Got internal file storage working. The flash is laid out a bit
differently - 4 x 32K, 1 x 128K with the rest 256K, so I made
the internal storage be 96K.

### CODE REVIEW

**Comment by dhylands** [comment]
I also got the internal flash working.

I factored out the gpio clock code and put it into mp_hal_enable_gpio_clock, and made all of the places which might call HAL_GPIO_Init with a port > D call it.

**Comment by dpgeorge** [comment]
Reworked and merged in a few commits, the last being 8f1eced69da2275b70f0c6426290a5370cd250f2.

@dhylands thanks for the work, but next time please try to make separate commits for distinct things, especially if the changes are not directly related.

**Comment by dhylands** [comment]
@dpgeorge My apologies (on not doing separate commits). Not sure why these ones all went into one. Will try to be more cognizant of this in the future.

**Comment by dhylands** [comment]
And, in future, if I haven't divided things finely enough or too finely - feel free to push back. I don't mind fixing things.

**Pull request closed without merging**
