### PR TITLE
added proposal comments for SPI dma modes

### PR DESCRIPTION
**Pull request by rlourette**
This is my first document pull request that I am making at the suggestion of jimmo.

I would like to propose changes to the machine SPI module signature in order to add circular DMA functionality to the SPI module. The STM32 family is quite broad. I am working with the STM32L452RE specifically, but what I am discussing should apply to the STM32L4 family as the DMA controller is common. This would be implemented differently on the Pyboard D for instance as its DMA controller has double buffer mode. Here is what I am proposing:

Add the parameters:
**callback** - called when the SPI transfer is completed on a single transfer and repeatedly for circular dma.
**callbackhalf** - called when half of a transfer is completed on a single transfer and repeatedly for circular dma.
**callbackerror** - called if there was a transfer error
**dmamode** - NORMAL or CIRCULAR

If the mode is _NORMAL_, the three new keywords would not be allowed. Only if _CIRCULAR_ was specified, would the new callbacks be supported. 

**Problem**: Where will the information for circular, callbackhalf, callbackfull, callbackerror get stored. Currently, spi_t holds all the STM32HAL SPI type of parameters.

I propose to modify struct _spi_t (in ports/stm32/spi.h) to add the following member:

```
typedef struct _spi_t {
    SPI_HandleTypeDef *spi;
    const dma_descr_t *tx_dma_descr;
    const dma_descr_t *rx_dma_descr;
    ****const dma_mode_t      *dma_mode; // Null if normal blocking behavior****
} spi_t;
```

In order to add an optional DMA configuration structure. This will hold the DMA mode (CIRCULAR, callbackhalf, callbackfull, callbackerror). If NORMAL (default) is specified the dma_mode pointer would be NULL.

To support bigger parts, DMA mode could also include:
DUALBUFFER, etc.

Each of these modes would carry a union of parameters (some required, some optional) for each of the separate DMA modes. The definition of the union would be part specific depending upon the DMA modes supported and the settings in mpconfigport.h. By default, it could be disabled (no compiled changes to the code), and enabled by those that care about this mode (like me).

Please comment.

Thanks

Rich

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the proposal.  Non-blocking (background DMA) SPI is certainly a good feature to add.

Before getting in to details of implementation, I suggest to discuss just the high-level behaviour.  The main points are 1) it should be possible for the API for non-blocking DMA SPI to be implemented across a wide variety of ports (eg stm32, esp32, zephyr); 2) ideally the non-blocking part of the API would match other peripherals that also benefit from non-blocking behaviour, eg UART, I2S (audio).  A discussion of I2S can be found at #4471, which also includes some discussion about SPI.

Regarding callbacks: the consistent way to implement these is via the `.irq()` method on a peripheral.  You would register a single irq callback function (Python function) and it would be called for all events/irqs.  UART already has such behaviour.

To move forward with this I'd recommend reading through #4471 and thinking about how a non-blocking/asynchronous API would look that works for both I2S and SPI.

**Comment by rlourette** [comment]
Thanks for the feedback. I have fully implemented what I proposed and
tested. I wish I heard from someone sooner.  All the code changes are on my
fork. It should be fairly easy to funnel all the callbacks to a single IRQ.
I am pretty sure non-blocking DMA (if DMA is supported on a platform ) can
be implemented. Circular DMA will depend upon the hardware. I have not
looked at the capabilities outside of STM32 and the Ambiq Apollo family.  I
have used MP on the ESP32, but not using this capability. My need arose
from wanting to interface to some SPI ADC converters. I needed a real-time
stream to process with precise clocking. i have it working at 100khz
sampling and all is good.

I will take a look at #4471.

Thanks again... Stay well.

Rich

**Comment by rlourette** [comment]
Damien, I read what you proposed for I2S. What I have is a low level
framework that could have the API you suggested. I wanted to get something
running so I could understand all the issues. In my implementation I read
the data out of the ring buffer from an interrupt callbacks and process the
data in MP. If I push that logic down to the SPI code and have the queuing
mechanism implemented there, the API you suggest can be realized. in my
application, I am working with a 14bit ADC that requires 18 spi clocks to
do the SAR conversion. Each chip select starts the conversion.

In my youth, I worked on SunOS with streams drivers. There I could push
modules onto the stack to implement higher level protocols. This is
essentially what I would do with your API. It would be a "module" that I
would push onto the underlying DMA framework that I have. I can see
commonality with any streaming real time source.

Is there a way to schedule something like a differed procedure call at the
'C' level much like schedule works at the MP level? It would be helpful for
the real time streaming needs of I2S/SPI and other synchronous
sources/sinks to be able to do a simple context switch from the low level
ISR (I will call this the low level ISR or LISR) to a high level isr (HISR)
which is similar to the schedule mechanism, but used for IO devices to
perform high priority functions not in the interrupt service routing (LISR).

I have been a long time user of MP and thought I would jump in with this
effort.

Stay well.

Rich

**Comment by dpgeorge** [comment]
I'll close this due to inactivity.

To move forward with it, it would at least need to be split up into two separate PRs, one to add the new board, and another for the DMA changes.

**Pull request closed without merging**
