### PR TITLE
Add board definition for Sparkfun SAMD51 MicroMod

### PR DESCRIPTION
**Pull request by andrewteta**

### CODE REVIEW

**Comment by robert-hh** [comment]
A few comments.

- Better put your changes in an own local branch and make a PR from that branch.
- The commit messages have a wrong format. It should e.g. be: `samd: Add board definition for Sparkfun SAMD51 MicroMod.` and `samd: Fix jpeg reference in board.json`. But should can squash the second commit into the first one.
- In pins.csv you mix SPI name schemes. For PA04 you use MOSI, but for PA06 you use CIPO instead of MISO. Even if there were thoughts to use COPI/CIPO this has not been implemented. So please use MISO for PA04.

I assume that you have tested your board definitions. For the picture you have to make a separate PR to https://github.com/micropython/micropython-media. Please take care that the same board & file name is used.

**Comment by andrewteta** [comment]
Thanks for the feedback, it's my first time making a pull request to the Micropython project. I'll fix the pin naming that was just a mixup while I was translating from the Sparkfun schematic to the CSV file.

Do I need to do anything to fix the commit message? I'm not sure how to do that. Should I just make a branch and a new pull request?

**Comment by robert-hh** [comment]
AFAIK, with a new branch you have to make a new pull request. If you change your PR later, you can just push the changes to your fork's branch, and then the PR will be updated. I noticed later that you already made a PR for the picture.

**Comment by andrewleech** [comment]
There's some guidance on micropython git usage here: https://github.com/jimmo/git-and-micropython

**Pull request closed without merging**
