### PR TITLE
Add optional password argument to webrepl.start()

### PR DESCRIPTION
**Pull request by Ivoah**
This commit fixes issue #2045

### CODE REVIEW

**Comment by pfalcon** [comment]
Looks good, but you don't follow commit message conventions as described in https://github.com/micropython/micropython/blob/master/CODECONVENTIONS.md . I'll fix it this time, but for quicker turnaround in the future, please pay attention to this.

**Comment by pfalcon** [comment]
And btw, you tested this, right? ;-)

**Comment by Ivoah** [comment]
> Looks good, but you don't follow commit message conventions as described in https://github.com/micropython/micropython/blob/master/CODECONVENTIONS.md . I'll fix it this time, but for quicker turnaround in the future, please pay attention to this.

Oh, sorry about that, I didn't know there were commit message conventions. I'll be sure to adhere to that in the future

> And btw, you tested this, right? ;-)

I did indeed test it :)

**Comment by pfalcon** [comment]
Merged, thanks.

**Pull request closed without merging**
