### PR TITLE
py: Convert float to correct int type

### PR DESCRIPTION
**Pull request by doogle**
A redo of pull request #1047, to address issue #1042 (currently worked around by ad2307c92c15f0aa90dbd0741fd2538719d0b5e1).

The approach I used in the end allowed for the full range of small ints to be used. Exceptions are now raised in the event of an overflow as well.

As discussed, `fpclassify()` is used to test for inf and NaN, and the new `mp_classify_fp_as_int()` function is used for all other values.

The code size could be reduced slightly by not caring so much about ensuring that the full range of small ints are used, but (in the case of `MICROPY_LONGINT_IMPL != MICROPY_LONGINT_IMPL_MPZ`), this would also result in exceptions being raised when the number could be converted to an int (which I would count as a bug).

### CODE REVIEW

**Comment by stinos** [comment]
Maybe consider adding tests for special/corner cases: there's a lot of 'magic' going on in the code so it seems a good idea to assert it works and keeps working in the future?

**Comment by doogle** [comment]
Good point @stinos. Corner cases depend on the configured value of `MICROPY_LONGINT_IMPL` and whether the build is 32-bit or 64-bit. Is there a way of detecting this?

**Comment by stinos** [comment]
Good point. I'll leave it to dpgeorge or pfalcon to provide an authorative answer - one way to test support in tests is try/catch on the specific feature and skip the test if an exception is thrown. Not sure if there is code which can be used for that here. Maybe something with an extremely large number, or a string conversion thereof?

**Comment by doogle** [comment]
True, it should be possible to detect those things by trying to generate certain large ints. I'll try some stuff out. There should be test code for this before it's merged.

Does anyone know what's going on with the CI build? I don't think it's failing because of my changes.

**Comment by doogle** [comment]
I've added some tests to make sure exceptions are raised when they should be.

I've tried to use 'good' values for the new tests. I would have preferred to have generated float values from bit-strings (rather than relying on the float string parsing), but I couldn't work out a way of doing that (the struct package doesn't seem to support floats yet due to missing support in py/binary.c:mp_binary_get_val()).

Would it make sense to roll float2int.py and float2int_doubleprec.py together? The precision can easily be detected at runtime by doing `is_dbl = (2. ** 1023.) != float('inf')`.
Incidentally, are there any tests that could benefit from the none/longlong/mpz and 32-bit/64-bit detection code I've added? (Or is it already being done somewhere else?)

Btw, the reason the power-of-10 test fails above a certain exponent (as quiried in a TODO comment) seems to just be because of floating point inaccuracies. eg. 10**12 comes out to 999999995904, rather than 1000000000000. I don't think there's a way around this, and if it's an issue I can remove the power-of-10 test.

**Comment by dpgeorge** [comment]
Thanks @doogle.  

> I would have preferred to have generated float values from bit-strings (rather than relying on the float string parsing), but I couldn't work out a way of doing that (the struct package doesn't seem to support floats yet due to missing support in py/binary.c:mp_binary_get_val()).

Yes, it's strange that structs don't support floats, and we should really fix that.  The functionality is there because array.array supports single and double precision.  Eg try `bytes(array.array('d',[1.2]))`

> Would it make sense to roll float2int.py and float2int_doubleprec.py together? The precision can easily be detected at runtime by doing is_dbl = (2. ** 1023.) != float('inf').

That sounds sensible, but is it robust across platforms?  Eg CPython seems to raise an OverflowError if I do `2. ** 1024`, yet uPy returns `inf`.

> Incidentally, are there any tests that could benefit from the none/longlong/mpz and 32-bit/64-bit detection code I've added? (Or is it already being done somewhere else?)

Yes.  The tests in basics/ that test longlong/mpz are not very systematic.  It would be nice to test longlong on 32-bit machines and 64-bit machines independently.  At the moment some tests are for 32-bit and don't test anything on a 64-bit machine.

**Comment by doogle** [comment]
> Yes, it's strange that structs don't support floats, and we should really fix that. The functionality is there because array.array supports single and double precision. Eg try bytes(array.array('d',[1.2]))

I noticed that `mp_binary_get_val_array()` supports floats but `mp_binary_get_val()` doesn't, which struck me as a bit odd. It should be a relatively easy fix, I can have a look at this.

> That sounds sensible, but is it robust across platforms? Eg CPython seems to raise an OverflowError if I do 2. ** 1024, yet uPy returns inf.

Good point. CPython catches a SIGFPE in order to raise the exception, whereas mp just allows the CPU's result. Is CPython-like behaviour in this context something that is on the mp roadmap?
Either way, the test could be expanded to also catch the exception and set `is_dbl = False` in order to be cross-platform friendly.

> Yes. The tests in basics/ that test longlong/mpz are not very systematic. It would be nice to test longlong on 32-bit machines and 64-bit machines independently. At the moment some tests are for 32-bit and don't test anything on a 64-bit machine.

I'll take a look in this area. Is there somewhere for shared test related code to go?

FWIW I've ended up with a copy of the unix directory, with a slightly modified mpconfigport.h and a (slightly hacky) shell script that loops round to create binaries for all combinations of 32/64-bit, none/longlong/mpz ints, and single/double precision floats. This allows me to run the tests on all these combinations, which has been incredibly useful while developing the float2int classification code.

**Comment by dpgeorge** [comment]
> FWIW I've ended up with a copy of the unix directory, with a slightly modified mpconfigport.h and a (slightly hacky) shell script that loops round to create binaries for all combinations of 32/64-bit, none/longlong/mpz ints, and single/double precision floats. This allows me to run the tests on all these combinations, which has been incredibly useful while developing the float2int classification code.

Sounds like something we should have running on Travis CI.  It now has gcc-multilib so should be able to run your script.

**Comment by doogle** [comment]
> Sounds like something we should have running on Travis CI. It now has gcc-multilib so should be able to run your script.

I've put up a branch in my fork called multibuild, which has this unix-all directory (it can be found at 43b0dd38019ecf4e87586c6431952926f0facd8d), to give you an idea of what I've done. As I said, it's currently a bit hacky, requiring a full rebuild each time.
I don't really know much about Travis CI so I don't know it would translate. I don't think I've done anything particularly complex with this, so it might make more sense to reimplement the idea in a Travis-friendly way, rather than trying to use my script as is.

**Comment by pfalcon** [comment]
But why that required duplicating unix directory as unix-all?

**Comment by doogle** [comment]
Tbh, mainly that it was just a quick hack in order to test the various combinations of configuration values that affected float2int behaviour. But it did require a change to mpconfigport.h, to remove the definitions of `MICROPY_FLOAT_IMPL` and `MICROPY_LONGINT_IMPL` so that the shellscript could define them on the command line, and I didn't want to do this to the mpconfigport.h in the real unix dir.

I can look at tidying this up so it can exist alongside the real unix dir. Will this help with any Travis CI integration?

**Comment by pfalcon** [comment]
> Will this help with any Travis CI integration?

It won't help with Travis CI as such, but surely will help others to easily see changes you made (as you may imagine, currently by the link you gave, one case see few thousand of added lines), and you maintain the changes, even if they're not merged for awhile.

> But it did require a change to mpconfigport.h

Sure, for good cause we can add #ifdef's to it (I'm surprised there's none such yet - I surely hit such issue already, probably have it in my git stash).


As for actually running that in Travis, there're concerns of growing build and change feedback times. (There's a thread with various ideas how to tackle that on forum, but none were approached yet).

**Comment by doogle** [comment]
> As for actually running that in Travis, there're concerns of growing build and change feedback times. (There's a thread with various ideas how to tackle that on forum, but none were approached yet).

That did occur to me when @dpgeorge mentioned it might be useful for CI. I figured it'd be worth sharing what I'd done anyway.

> Sure, for good cause we can add #ifdef's to it (I'm surprised there's none such yet - I surely hit such issue already, probably have it in my git stash).

Ah ok. I've updated that branch... the buildall script is now in the unix dir, and I've made some other minor changes as well. I've also changed the script so it doesn't do a `make clean all` each time (although it pretty much has to do a complete rebuild anyway because of the change to config values).

[This](https://github.com/doogle/micropython/compare/multibuild) is probably a better link to look at the changes.

**Comment by pfalcon** [comment]
~~~~
+#ifndef MICROPY_NOCONFIGPORT_FLOAT
 #define MICROPY_FLOAT_IMPL (MICROPY_FLOAT_IMPL_DOUBLE)
~~~~
Well, this surely should be `#ifndef MICROPY_FLOAT_IMPL`, the idea is that mpconfigport.h provides the "official" value for option, but allows to override it from command line.

**Comment by pfalcon** [comment]
If you target buildall.sh for merging, then "buildall.sh" is not god name, because it doesn't build all ;-). Name should be non-confusing, preferrably descriptive, script should start with a comment describing what it does clear enough. unix/ doesn't look like 100% the best location, we keep scripts in tools/, we keep test scripts in tests/.

Generally, that shows the problem with such scripts - it takes effort to put them into decent shape, and then still if everyone pushes a lot of such stuff it will be a mess. Don't take as discouragement - vice-versa, if you're sure it should be there, please push for it ;-).

**Comment by pfalcon** [comment]
Anyway, what's left for this patch? We try to have quick turnaround, so if this is ready, please ping if this doesn't get enough attention.  But commits like https://github.com/doogle/micropython/commit/23758c63847e9157fbd517e3719ac0d3245b17b5 concern me - I don't even have an idea how that commit could be created. It's not a real git merge, and if you used rebase workflow, it wouldn't be there at all.  Rebase workflow is highly recommended, just in case, https://github.com/micropython/micropython/wiki/DevelWorkflow

**Comment by doogle** [comment]
I think I should reiterate that the only reason I put this up on a branch was so @dpgeorge could take a look, as he seemed interested in the possibility of something like this being useful for Travis CI.

I definitely agree that my naming (especially my use of the word 'all' for the both the script and the dir names) wasn't that great. If you think it would actually be useful to have this merged then I'll move it to tools/, rename it and generally tidy it up.

Regarding commit doogle@23758c6, that was me trying to bring in any changes that had since occurred on master because of the failing Travis CI (that I was pretty sure wasn't related to my changes) as I thought that might fix the CI. Apologies if this has caused any issues/confusion. I hadn't seen that wiki page, I'll make sure I stick to that workflow.

Beyond that, I think this patch is ready. It would be nicer to use the struct package for the tests so that precise float values can be used (generated from bit or hex strings) but as discussed above, the support isn't there yet. But I don't think this is a real issue.

I'm happy with the behaviour of the actual implementation.

**Comment by pfalcon** [comment]
> the only reason I put this up on a branch was so @dpgeorge could take a look, as he seemed interested in the possibility of something like this being useful for Travis CI.

But for it to be useful for Travis CI, it should be merged first ;-). That's how travis works - it checks out source and does something with it. Yep, it could download it from somewhere, but why such complications?

**Comment by pfalcon** [comment]
Just in case, travis config is here: https://github.com/micropython/micropython/blob/master/.travis.yml . One look should be enough to see basics of its workings.

**Comment by pfalcon** [comment]
>  It would be nicer to use the struct package for the tests so that precise float values can be used (generated from bit or hex strings) but as discussed above, the support isn't there yet.

Can we have a bug for that please?

Note that there're precise hex float representation too: https://docs.python.org/3/library/stdtypes.html#float.hex ,  but I don't think it's worth to implement it yet.

**Comment by pfalcon** [comment]
> I hadn't seen that wiki page, I'll make sure I stick to that workflow.

Thanks. So, please try to squash existing commits together, so there was 1 commit == 1 feature correspondence, this will ease review, and later code research using git blame/git log -p.

**Comment by doogle** [comment]
> But for it to be useful for Travis CI, it should be merged first 

I figured @dpgeorge could just take a look to get started. As you pointed out, there's the bigger issues of extra processing time to look at before something like this would actually be useful for CI. But so it's at least useful on other devs machine for the moment, I'll rename the script and move it to tools/.

> Can we have a bug for that please?

Added #1086.

> Thanks. So, please try to squash existing commits together, so there was 1 commit == 1 feature correspondence, this will ease review, and later code research using git blame/git log -p.

Unfortunately I hadn't previously used git in this way before... it makes a lot of sense to do this! Is it safe to rebase and push, or will I need to open a new pull-request?

**Comment by dpgeorge** [comment]
Rebased and merged in c585ad1020cf81cb277ecce77952f9c896ba7bbc through 4c1a7e0d6a561be5871bb0d36b724f529e55c21d.

@doogle I had to revert a small part of tests/float/float2int.py for single precision so it would work on pyboard (the stuff under the comment heading "# basic conversion").

Note that it's difficult to autodetect the bit size because the host might run 64-bit unix, but it's testing pyboard with 32-bit floats...

**Comment by dpgeorge** [comment]
Regarding testing framework.  A simple script put in tools/ would be a good start, with minimal changes to unix/ code to make it work.

**Comment by doogle** [comment]
Thanks @dpgeorge. And I'll make sure no rebasing and merging is needed in future :-)

> Note that it's difficult to autodetect the bit size because the host might run 64-bit unix, but it's testing pyboard with 32-bit floats...

Does you mean that the configuration related code at the top of tests/float/float2int.py could come up with erroneous results? Or just that the precise values chosen for that test weren't right?

> A simple script put in tools/ would be a good start, with minimal changes to unix/ code to make it work.

Opened #1087 for this.

**Comment by dpgeorge** [comment]
> And I'll make sure no rebasing and merging is needed in future :-)

Most of the time I need to rebase anyway, because other changes make it in before a PR gets merged and we want to keep the git history flat.

> Does you mean that the configuration related code at the top of tests/float/float2int.py could come up with erroneous results?

Well, yes.  That will always yield ll_type=2 on the host (because it runs CPython), and ll_type could be something else on the uPy version being checked.

**Comment by doogle** [comment]
> Most of the time I need to rebase anyway, because other changes make it in before a PR gets merged and we want to keep the git history flat.

Ah, got it. Well, no merging then :-)

> Well, yes. That will always yield ll_type=2 on the host (because it runs CPython), and ll_type could be something else on the uPy version being checked.

Ah ok. I think I've misunderstood how the test scripts are used. I didn't realise that particular bit of code would run under CPython, I thought it would just run under uPy. I'll dig a bit more into the code to get my head around it.

**Pull request closed without merging**
