### PR TITLE
py: implemented round(f, N>0), added test

### PR DESCRIPTION
**Pull request by turbinenreiter**
In the forum someone asked about round with arguments bigger than 0, and I found that easy enough to be my first patch in C.

(forum thread: http://forum.micropython.org/viewtopic.php?f=2&t=802 )

### CODE REVIEW

**Comment by turbinenreiter** [comment]
```python
>>>round(1.123456789, 9)
1.123456768
```

should be ``1.123456789``.
It rounds wrong.

**Comment by dhylands** [comment]
@turbinenreiter I mentioned this on the forum, but I figured I'd mention it here as well.

- You've got some build failures - click on the red x to see the full log. I think you need to add some casts to convert doubles to mp_float_t
- I'd recommend squashing this into a single commit
- The PR title should have a py: at the front

**Comment by turbinenreiter** [comment]
I think I got the casts figured out, it builds on all platforms, but the test fails, because it rounds wrong in some cases.

``round(1.123456789, 8)`` rounds to ``1.1234568``, but should be ```1.12345679``

I'll try to figure that out and come back with a better pull request.

**Comment by dhylands** [comment]
@turbinenreiter That's because the FPU on the pyboard is only 32-bit, so you can only get  6 significant digits.

So I'd remove that test and call it a day :)

**Comment by pfalcon** [comment]
@turbinenreiter: Pretty good for the first patch. Few issues: it should not call round or roundf and friends directly, we have a special macro which use function appropriate for a particular port. Rounding by multiplying to power of 10 and then dividing can lead to overflow. It's ok for a first implementation, but there should be "// TODO: Mat lead to overflow" comment.

As for tests, just use "lowest common denominator" for all ports + fuzz factor, which is rounding up to 5.

**Pull request closed without merging**
