### PR TITLE
Implement help('modules') to list available modules

### PR DESCRIPTION
**Pull request by dpgeorge**
This is how CPython does it, and it's very useful to help users discover the available modules for a given port, especially built-in and frozen modules (and module weak links).  The function does not list modules that are in the filesystem because this would require a fair bit of work to do correctly, and is very port specific (depending on the filesystem).

Note that there is no additional config option for this feature, because pyhelp.c is already optional, and if a port wants to implement help() then it's highly likely they want this feature (and users should be allowed to rely on this feature so they can discover modules on a given board).

Example output on pyboard:
```
>>> help('modules')
__main__          json              stm               umachine
array             lcd160cr          struct            uos
binascii          machine           sys               urandom
builtins          math              time              ure
cmath             micropython       ubinascii         uselect
collections       network           ucollections      usocket
errno             os                uctypes           ustruct
framebuf          pyb               uerrno            utime
gc                random            uhashlib          utimeq
hashlib           re                uheapq            uzlib
heapq             select            uio               zlib
io                socket            ujson
Plus any modules on the filesystem
```

### CODE REVIEW

**Comment by dhylands** [comment]
Sweet!

**Comment by dhylands** [comment]
Do you think this deserves a mention in the output of help() ?

**Comment by dpgeorge** [comment]
> Do you think this deserves a mention in the output of help() ?

Yes, I was thinking that.  It would be done per-port, because each port defines their own help text.

**Comment by pfalcon** [comment]
> Note that there is no additional config option for this feature, because pyhelp.c is already optional

Yeah, we definitely need to work on improvement user-friendliness in background (e.g. make autocompletion pick up more stuff, strange nobody complains about this ;-) ), but I still think there should be middle-ground between not having help at all and overflowing (128K of) flash. How many bytes this adds, anyway?

**Comment by pfalcon** [comment]
> Yes, I was thinking that.

+1. I didn't know about `help("modules")` (usually use external documentation anyway). But in CPython, I at least could, as it mentions it in just `help()`.

> It would be done per-port, because each port defines their own help text.

And that's what I wanted to mention too - if touching help stuff, it would make sense to reorganize and centralize help support. E.g., add MICROPY_PY_HELP, and don't print "you can use help()" if it's not defined (there should be ticket on that), etc.

**Comment by dpgeorge** [comment]
> How many bytes this adds, anyway?

280 bytes for stmhal (or any Thumb2 arch), and 396 bytes for esp8266.

I also tried a "cheap" version which just prints the output in 1 long column (instead of 4 nice ones).  That costs: 224 bytes for stmhal, 320 bytes for esp8266.

Because there are many modules available, the 4-column output is a lot more user friendly.

> it would make sense to reorganize and centralize help support. E.g., add MICROPY_PY_HELP, and don't print "you can use help()" if it's not defined

Yes that's a good idea.

**Comment by pfalcon** [comment]
> Because there are many modules available, the 4-column output is a lot more user friendly.

I agree that if done at all, this should be optimized for aesthetics. But I'd say  MICROPY_PY_HELP_MODULES would be helpful.

> Yes that's a good idea.

That of course can be part of later work to not scope creep this PR.

**Comment by dpgeorge** [comment]
Refactoring of builtin help function to move it to core was done, see 9f04dfb568b8af339ec34ea1a94fb2eb8890bf8c.  This PR was merged in f5172af1c430cd3c20f83b8e7fe0d3ffb812e1ac

**Pull request merged**
