### PR TITLE
Tool to generate native .mpy files from a .elf file (dynamically loadable native code)

### PR DESCRIPTION
**Pull request by dpgeorge**
This PR adds a tool `elf2mpy.py` and associated build scripts/headers to build .mpy files from C source code.  Such .mpy files can then be dynamically imported as though they were a normal Python module, even though they are implemented in C.

Included in this PR are some examples: ex0, ex1 and ex2 are basic examples, and the qr example shows how to take an existing C library "off the shelf" and wrap it up into a .mpy file (to generate QR codes, work done in collaboration with @mattytrentini ).

Currently the tool supports targets of unix x86-64, ARM Thumb2 (Cortex M3 and above, eg stm32 boards), and partial support for esp32.  esp32 support is non trivial and the qr example does not work (at this stage I'm unsure why).  esp32 support relies on #5082 

To try this PR out do the following:
- go to the `tools/elf2mpy/ex0` directory
- edit `Makefile` to select the architecture (unix, stm32, esp32)
- run `make`
- copy the resulting `ex0.mpy` file to the board
- run `import ex0`
- run `ex0.foo(1, 2)` (should return 4)
- run `ex0.factorial(5)` (should return 120)

Then try out ex1, ex2 and qr.  Also use one of these examples as a template to write your own C-based module.

There's still a bit of work to do to clean this up (eg tool/file naming, directory structure, docs).  Also freezing the resulting mpy files won't work at the moment because the code relocates itself (writes to itself) when it is imported, and frozen code is read-only.  Eventually this can be fixed.

Edit: for past discussion and PR on this idea see #1627

### CODE REVIEW

**Comment by dpgeorge** [comment]
I redid this, changing it so that it builds the .mpy directly from .o files rather than .elf.  The new tool is called `ldmpy.py` and it's essentially a linker that outputs .mpy files.  This allows the resulting .mpy to be more efficient because it can skip PLT indirection.  It also fixes all the problems with esp32 (by rebuilding the GOT in a convenient form).

So now all included examples work on all supported targets (x86-64, ARM Thumb2, xtensa-esp32).

**Comment by dpgeorge** [comment]
I've updated this further.  New features include:
- global function table pointer `mp_fun_table` (fixed up in GOT) means that it's now possible to call MicroPython API functions from arbitrary C functions, ie no need to pass around a pointer to the `mp_fun_table`
- support for bss data in the C code
- support for calling `mp_printf` directly
- support for combining Python code with C code in the same .mpy file
- preliminary support for freezing these .mpy files

**Comment by dpgeorge** [comment]
@stinos the AppVeyor build is failing here because the compiler doesn't like `NORETURN` used in a typedef, declaring a function that doesn't return; see line 88 of py/nativeglue.h and the 2 most recent commits here.

Do you know how, in MSVC, to declare a function type (using typedef) that does not return?  It works under gcc...

**Comment by stinos** [comment]
> Do you know how, in MSVC, to declare a function type (using typedef) that does not return? It works under gcc...

Unless I'm missing something this cannot be done, this is a gcc extension. For msvc (and C's _Noreturn as well), noreturn behaves like inline i.e. it is not part of the type. As such I also cannot think of a usable workaround..

**Comment by dpgeorge** [comment]
> Unless I'm missing something this cannot be done,

OK.... I'll have to think of a way around it.  Possibly just put `for(;;);` at the end of the no-return function when building with a non-gcc compiler.

**Comment by dpgeorge** [comment]
This is getting closer to being finished, it now has full C coverage and builds on all Travis targets.

Still to do: docs and some renaming.

**Comment by dpgeorge** [comment]
FINALLY THIS IS DONE AND MERGED!

Still to come: docs.

**Comment by amirgon** [comment]
**Question (ESP32)**:  
After I copy the mpy file containing my C library to Flash, will it run from Flash or first copied to RAM? Will the data section be copied to RAM or remain on Flash?  
If it's all copied to RAM this may limit the usage of this feature since RAM is usually a more limited resource.

**Comment by dpgeorge** [comment]
> After I copy the mpy file containing my C library to Flash, will it run from Flash or first copied to RAM? Will the data section be copied to RAM or remain on Flash?

The code (text) will be copied to iRAM and executed from there.  BSS and rodata are copied to normal RAM.

> If it's all copied to RAM this may limit the usage of this feature since RAM is usually a more limited resource.

Yes, but note that not all flash can be executed from, only a limited part of it.  And similarly with RAM, only iRAM can be executed from.  Also note that the code must be relocated and linked in to the firmware, ie modified, so it must go in to RAM.

There is a plan to eventually support putting .mpy files in flash, to be executed from there, saving (i)RAM.  The idea is to set aside a region of flash for user modules to be "dynamically frozen" to, and to freeze them at runtime via a call like `micropython.freeze(['lib1.mpy', 'lib2.mpy'])`.

**Comment by amirgon** [comment]
Thank you for the explanation.

> There is a plan to eventually support putting .mpy files in flash, to be executed from there, saving (i)RAM. The idea is to set aside a region of flash for user modules to be "dynamically frozen" to, and to freeze them at runtime via a call like `micropython.freeze(['lib1.mpy', 'lib2.mpy'])`.

This could be very useful, especially for dynamically loading large libraries.

**Comment by rlourette** [comment]
What version of micropython is this tool (elf2mpy.py) a part of? Thanks for the work @dpgeorge

**Comment by dpgeorge** [comment]
> What version of micropython is this tool (elf2mpy.py) a part of?

It's now called `tools/mpy_ld.py` and was added in aad79adab7285cbe1c1b975fcd490542fd3ab85c, so first appeard in v1.12.

**Comment by rlourette** [comment]
Thanks!

Rich

**Pull request merged**
