### PR TITLE
WIP: tests/extmod/ussl: Basic coverage for modussl.

### PR DESCRIPTION
**Pull request by hosaka**
Some basic tests for modussl_axtls.c. This kind of goes hand in hand with me testing websockets. So I decided to open this PR in parallel to keep an eye on coverage.

Since upy doesn't implement blocking sockets for now (name prints also differ, but that's minor), this is tested with .exp, but could potentially be compatible with cpython later on.

### CODE REVIEW

**Comment by hosaka** [comment]
What I am essentially trying to do with the server test is similar to single file socket test in cpython. Which works as expected.
```python
import socket, ssl

# server
s_server = socket.socket()
s_server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s_server.bind(('0.0.0.0', 8443))
s_server.listen(5)

# dummy client
s_client = socket.socket()
s_client.connect(('0.0.0.0', 8443))

cl = s_server.accept()[0]

# ping pong
s_client.send(b"ping")
print(cl.recv(4))
cl.send(b"pong")
print(s_client.recv(4))

s_client.close()
cl.close()
```
Now, the problem I'm having, is not being able to (the output hangs) wrap the client socket after connect() or hitting #2583 (getting SIGPIPE), by calling wrap_socket() after the connect().

**Comment by dpgeorge** [comment]
@hosaka are you going to look into this again?

**Comment by hosaka** [comment]
@dpgeorge same answer as #2587 unfortunately, but glad I could contribute!

**Comment by dpgeorge** [comment]
Ok, in 38f063ea72632e395ea59b644552bb98c962393f I added a simple test (based loosely on the one in this PR) that covers about 50 out of 59 lines in extmod/modussl_axtls.c.  It doesn't use any sockets to do the test and runs on unix and esp8266.

Further tests that test the actual ssl protocol can be made later.

**Comment by dpgeorge** [comment]
@hosaka FYI I looked into your server ping/pong test in more detail.  The reason your output hangs is because the SSL handshake (initiated by the client doing wrap_socket) requires the server and client to send a certain amount of data between themselves.  This means that the server and client need to be independent entities.  This can only be done by using threads or separate scripts.

The following version of your test uses threads and works on the unix port of uPy:
```python
import utime as time
import usocket as socket
import ussl as ssl 
import _thread

def th_server():
    s = socket.socket()
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(socket.getaddrinfo('127.0.0.1', 8443)[0][-1])
    s.listen(1)
    c = s.accept()[0]
    c = ssl.wrap_socket(c, server_side=True) # this won't transfer any data on the socket
    print('server read', c.read(4)) # this will block until the client sends some data, then will do the handshake before reading the actual data
    print('server write', c.write(b'pong'))
    c.close()
    s.close()

def th_client():
    c = socket.socket()
    c.connect(socket.getaddrinfo('127.0.0.1', 8443)[0][-1])
    c = ssl.wrap_socket(c) # this will attempt to do the SSL handshake
    print('client write', c.write(b'ping'))
    print('client read', c.read(4))
    c.close()

_thread.start_new_thread(th_server, ()) 
_thread.start_new_thread(th_client, ()) 
time.sleep(2) # wait for threads to finish
```

**Comment by hosaka** [comment]
@dpgeorge thanks for the info, I suppose it makes sense when two threads are communicating between each other, but it can't be a generic test since we can't run it of hardware that doesn't support threads. I have been out of touch with upy project lately, but might have to re-join the fun! :)

**Comment by pfalcon** [comment]
> This can only be done by using threads or separate scripts.

In general case, yes, but depending on the amount of data and complexity (determinism) of the exchange, it doesn't have to be, for *POSIX-compliant* sockets e.g.:

~~~
import socket

s1 = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

s1.bind(("192.168.1.35", 32323))

s2 = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

s2.sendto(b"foobar", ("192.168.1.35", 32323))

print(s1.recv(1000))
~~~

Now you just may wonder how much of such "corner" features embedded IP stacks have, and indeed, I found that for Zephyr such way currently doesn't work: https://jira.zephyrproject.org/browse/ZEP-1966

**Comment by dpgeorge** [comment]
> In general case, yes, but depending on the amount of data and complexity (determinism) of the exchange, it doesn't have to be, for POSIX-compliant sockets

Yes for some simple cases it will work with a single flow of control.  @hosaka did already mention such a case (see the second post in this ticket, the first code example), but the issue here was that wrapping the sockets with ussl would always lead to a block.  I tried but couldn't find any case at all that used ussl with both a client and server in the same script (without threading).

**Pull request closed without merging**
