### PR TITLE
modbuiltins: Add NotImplemented builtin constant.

### PR DESCRIPTION
**Pull request by pfalcon**
From https://docs.python.org/3/library/constants.html#NotImplemented :
"Special value which should be returned by the binary special methods
(e.g. **eq**(), **lt**(), **add**(), **rsub**(), etc.) to indicate
that the operation is not implemented with respect to the other type;
may be returned by the in-place binary special methods (e.g. **imul**(),
**iand**(), etc.) for the same purpose. Its truth value is true."

Some people however appear to abuse it to mean "no value" when None is
a legitimate value (don't do that).

### CODE REVIEW

**Comment by pfalcon** [comment]
Maybe we should even use MP_OBJ_NULL for that, because in C builtin methods, that's what means "operation not implemented".

**Comment by dpgeorge** [comment]
I see you merged this already... by accident?

It's too dangerous to return NULL/SENTINEL as an object.  You basically can't do anything with it without causing a segfault.   To fix that you'd need to check for NULL/SENTINEL at the start of almost every function in runtime.c and obj.c.

**Comment by pfalcon** [comment]
> I see you merged this already... by accident?

Oops ;-( Yeah, surely by accident - it's a bit hard to deal with many outstanding branches, especially if top-level goal is to make realistic 3rd-party code to run, which as usual requires bunch of changes...

**Comment by pfalcon** [comment]
> You basically can't do anything with it without causing a segfault.

Well, I hoped at least comparison works, but nope. So, refactor mp_type_ellipsis into mp_type_singleton, and use that instead?

**Comment by dpgeorge** [comment]
> So, refactor mp_type_ellipsis into mp_type_singleton, and use that instead?

Could do, would probably save bytes.  print function would have to be generic, perhaps in the instance have a qstr which is the string to print.

The only CPython incompatibility would be: type(Ellipsis) = <class singleton> = type(NotImplemented).

**Comment by pfalcon** [comment]
Hello,

On Tue, 05 May 2015 06:39:05 -0700
Damien George <notifications@github.com> wrote:

> > So, refactor mp_type_ellipsis into mp_type_singleton, and use that
> > instead?
> 
> Could do, would probably save bytes.  print function would have to be
> generic, perhaps in the instance have a qstr which is the string to
> print.

Why? I wanted to do object address comparison in print(), like we
usually do for singleton objects.

> 
> The only CPython incompatibility would be: type(Ellipsis) = <class
> singleton> = type(NotImplemented).

Let's consider this fact and implementation detail. Both Ellipsis and 
NotImplemented are defined as singleton objects, so there's no sense to
get type of them and do anything with it.


-- 
Best regards,
 Paul                          mailto:pmiscml@gmail.com

**Comment by dpgeorge** [comment]
> Why? I wanted to do object address comparison in print(), like we usually do for singleton objects.

There are currently no special cases in mp_obj_print (except debugging case).  So I think it's cleaner to have a singleton_print method.  Having 2 special checks will slow down all prints.  (Yes, you can argue that printing need not be efficient...)

> Let's consider this fact and implementation detail. Both Ellipsis and NotImplemented are defined as singleton objects, so there's no sense to get type of them and do anything with it.

Yes I agree, I was just pointing it out.

**Comment by pfalcon** [comment]
> There are currently no special cases in mp_obj_print (except debugging case). So I think it's cleaner to have a singleton_print method. Having 2 special checks will slow down all prints.

Ah, sure, all check will live in singleton_print method, not in mp_obj_print. (Well, actually as those objects live in ROM, making objects bigger by a qstr str may probably save a byte or two and not waste RAM ;-) ).

> (Yes, you can argue that printing need not be efficient...)

Well, printing is sending responses in webapps (keeping RF transmitting on), etc., so it shouldn't waste cycles without need too ;-).

**Comment by pfalcon** [comment]
Fixed in 76677270218fb5732296e4fe1a0acbe05c8f818c.

**Pull request closed without merging**
