### PR TITLE
nrf: Facilitate use of freeze manifest.

### PR DESCRIPTION
**Pull request by glennrub**
Adding FROZEN_MANIFEST to the Makefile which is set to
boards/manifest.py by default.

Adding the boards/manifest.py that will include the ports
'freeze' folder.

Adding BOARD_DIR to the Makefile which can be referenced in
boards/<board>/mpconfigboard.mk to include a board specific
manifest.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Looks good!

But I see that it now freezes the `freeze` dir by default, whereas before it needed to be explicitly enabled.  This is fine, but .travis.yml will need to be updated to build mpy-cross, so Travis builds pass.

**Comment by glennrub** [comment]
@dpgeorge , does it look as you would expect?  I added a new commit up front of my original commit to add the mpy-cross build in travis.

**Comment by dpgeorge** [comment]
@glennrub it looks good to me.  Only I'd also suggest updating README.md to reflect the fact that freezing is done by default, ie just put scripts to freeze in `freeze/`, no need for a special make invocation.

**Comment by glennrub** [comment]
>  Only I'd also suggest updating README.md to reflect the fact that freezing is done by default, ie just put scripts to freeze in freeze/, no need for a special make invocation.

Thanks, @dpgeorge , I'm glad you mentioned it. Looking a bit closer at it, it turns out that the `freeze/test.py` will consume about ~700 bytes. It's a bit to much on nrf51 for demo/test purpose. So, on a second thought i'll remove this auto freeze. Then it will either be a manual `make` invocation or set by a target board's `.mk` file.

Would you mind if i keep the travis patch in any case? i believe this can be useful in the future.

**Comment by dpgeorge** [comment]
> Would you mind if i keep the travis patch in any case? i believe this can be useful in the future.

Yes I think it's a good idea to keep it, and maybe even to make Travis build with a frozen manifest included to test this feature.

**Comment by dpgeorge** [comment]
Merged in 990341d18e72636c300e1880dd11500c07bd9f46 and 4f76f6618507c01a067d69cc5b9934fafe261e18

**Pull request closed without merging**
