### PR TITLE
pyb_main: Add kwarg "opt" to set mp_optimise_value

### PR DESCRIPTION
**Pull request by pramasoul**
Allows one to set the internal<code>mp_optimise_value</code>to other than zero, as can be done in the unix port with the<code>-O</code>command-line arg. Use in<code>boot.py</code>, e.g.:

``` python
# boot.py -- run on boot-up
# can run arbitrary Python, but best to keep it minimal

import pyb
pyb.main('test.py', opt=2) # main script to run after this one
```

Useful for e.g. conditioning expensive logging operations on the built-in [debug constant](https://docs.python.org/3/library/constants.html#__debug__), e.g.

``` python
if __debug__:
    log.debug("Response %s", expensive_formatting_function(r))

```

### CODE REVIEW

**Comment by dpgeorge** [comment]
Yes, such a feature is definitely needed (I wanted it more than once before).

Should we provide finer grained setting of opt, eg using a decorator per function/class?  Probably not.

Should we instead put the control in the micropython module?  Eg:
```python
micropython.optimise(2)
```
Then, once set, any import'd, exec'd, eval'd or compile'd script would use the new optimisation value.

**Comment by pramasoul** [comment]
In Cpython, ```__debug__``` is a constant that can only be configured on interpreter startup, viz. https://docs.python.org/3/library/constants.html#__debug__ This keeps ```__debug__``` from being overloaded with complex configuration duties. It is only ever ```True``` or ```False```, and consistently so throughout a program's execution.

**Comment by pramasoul** [comment]
There is benefit in maintaining the restriction to setting ```__debug__``` that [Cpython imposes](https://docs.python.org/3/library/constants.html#__debug__):
>__debug__
>This constant is true if Python was not started with an -O option.

The unix port of micropython has an ```argv``` so can use the ```-O``` flag. The relevant part of ```unix/main.c``` is:
```C
if (strncmp(argv[a], "-O", 2) == 0) {
  if (isdigit(argv[a][2])) {
    MP_STATE_VM(mp_optimise_value) = argv[a][2] & 0xf;
  } else {
    MP_STATE_VM(mp_optimise_value) = 0;
    for (char *p = argv[a] + 1; *p && *p == 'O'; p++, MP_STATE_VM(mp_optimise_value)++);
  }
}
```
Using keyword arguments in the ```boot.py``` invocation of ```pyb.main()``` is closely analogous, in that you get to do it only when the interpreter starts, and you can't change it's value within your code.

**Comment by dpgeorge** [comment]
Yes I agree with you.  I'm happy to merge this.

We need to think how it applies to #1430: other ports will want the feature, and it should work the same for them.

**Comment by pramasoul** [comment]
Something out-of-band, analogous to ```argv``` or environment variables on startup?

**Comment by dpgeorge** [comment]
> Something out-of-band, analogous to argv or environment variables on startup?

Most MCUs won't have env vars.  cc3200 has pyb module so it can use the `main` function to specify opt level.  We just need to think where `main` goes with the new hardware API, but that's a different discussion.

**Comment by dpgeorge** [comment]
Merged in 7731edf2f5cf7227a58315853d6351d4d4516f81.  Make opt arg positional and keyword (ie not kw only) in cas cc3200 port wants to implement same functionality with minimal footprint.

**Comment by danicampora** [comment]
@dpgeorge 

> We just need to think where main goes with the new hardware API, but that's a different discussion.

Maybe the `micropython` module?

**Comment by dpgeorge** [comment]
> We just need to think where main goes with the new hardware API, but that's a different discussion.
> 
> Maybe the micropython module?

Yes, maybe.

**Pull request closed without merging**
