### PR TITLE
lib: Update picosdk to 1.3.0 and tinyusb to 0.12.0

### LINKED ISSUE #8025: rp2: [Arduino Nano RP2040 Connect] REPL via Serial not working.
I tried flashing,

* [Latest nightly](https://micropython.org/download/ARDUINO_NANO_RP2040_CONNECT/)

the serial console was not appearing, so I flashed the blink example from here
* [blink.uf2](https://content.arduino.cc/assets/Blink.ino.elf.uf2)

Just to make sure that the flashing still works.
I wiped the memory with the following tool and reflashed the latest nightly from above.
* [flash_nuke.uf2](https://cdn-learn.adafruit.com/assets/assets/000/099/419/original/flash_nuke.uf2?1613329170)

Still no appearing REPL via serial.
Is there an advice to get it working?

```dmesg
[ 2583.404690] usb 1-1: Device not responding to setup address.
[ 2583.611390] usb 1-1: Device not responding to setup address.
[ 2583.817882] usb 1-1: device not accepting address 77, error -71
[ 2583.817996] usb usb1-port1: attempt power cycle
[ 2584.224458] usb 1-1: new full-speed USB device number 78 using xhci_hcd
[ 2584.224599] usb 1-1: Device not responding to setup address.
[ 2584.434692] usb 1-1: Device not responding to setup address.
[ 2584.641228] usb 1-1: device not accepting address 78, error -71
[ 2584.767899] usb 1-1: new full-speed USB device number 79 using xhci_hcd
[ 2584.768298] usb 1-1: Device not responding to setup address.
[ 2584.974668] usb 1-1: Device not responding to setup address.
[ 2585.181168] usb 1-1: device not accepting address 79, error -71
[ 2585.181303] usb usb1-port1: unable to enumerate USB device
```

### PR DESCRIPTION
**Pull request by iabdalkader**
* Fixes #8025

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thank you.

What testing did you do?  All ports that use TinyUSB will eventually need to be tested:
- [ ] rp2
- [ ] samd
- [ ] mimxrt
- [ ] nrf

**Comment by iabdalkader** [comment]
> What testing did you do? All ports that use TinyUSB will eventually need to be tested:

I just tested rp2 and can confirm it's working, and I can also test nrf, but don't have any of the other boards.

**Comment by dpgeorge** [comment]
> but don't have any of the other boards.

I can test samd and mimxrt.

**Comment by robert-hh** [comment]
I can test the mimxrt boards that I have here, mimxrt1010_EVK, mimxrt_1020_EVK, mimxrt1050_EVK, Seeed Arch Mix, Teensy 4.0, Teensy 4.1.

**Comment by robert-hh** [comment]
Tested with the above mentioned boards. REPL comes up. mpremote can be used for data exchange. The firmware for MIMXRT1060_EVK and MIMXRT1064_EVK build fine. MIMXRT1060_EVK should be covered by the Teensy tests, MIMXRT1064_EVK having the same core as well.

**Comment by iabdalkader** [comment]
Tested a board with NRF52840 and RPI Pico.

**Comment by dpgeorge** [comment]
I tested MINISAM_M4 and rp2 PICO.  REPL and file transfer over serial work.

**Comment by dpgeorge** [comment]
Merged in 97a7cc243b028833bdcb8ce0bc19b2bce7545851

**Comment by iabdalkader** [comment]
@dpgeorge There seems to be regression after the pico-sdk 1.3.0 update, RP2 Bluetooth is no longer working, it seems to get stuck right after UART is initialized (so possibly UART driver in general is broken). I think I've tracked it down to this commit: https://github.com/raspberrypi/pico-sdk/commit/2622e9bc292a26cb576a80c3c7c30481dda04181 it seems to enable an extra IRQ that needs to be handled in `uart_service_interrupt`

**Comment by dpgeorge** [comment]
Interesting!  I raised this as #8073 so it doesn't get lost.

**Pull request closed without merging**
