### PR TITLE
stmhal: Add definitions for MCU_SERIES_F4 and MCU_SERIES_F7

### PR DESCRIPTION
**Pull request by dhylands**
I noticed that there was a #if STM32F7 which should have been #if defined(STM32F7) and I also noticed that the STM32F7 flag wasn't being defined when assembling startup_stm32.S

### CODE REVIEW

**Comment by dpgeorge** [comment]
Maybe we should just provide some defines of our own for all source files (all .c, all .S) for the mcu series and part; eg:
```
-DMCU_SERIES_F4
-DMCU_PART_F405
```
?

**Comment by dhylands** [comment]
So far, I've really only needed to know the series. The difference s between CPUs is typically RAM/flash size, and peripheral set. I think its better to detect he peripheral set by checking for the base register name (i.e. I'd rather see us use #if defined(UART7) rather than trying to figure out if its an F7 or F4 and infer that way.

I think that defining our own makes sense and then we're not dependent on the HAL inquestion changing their minds later on.

So Im' in favor of adding -DMCU_SERIES_F4/F7 but wouldn't bother with the part for now (unless there is someplace that we need it).

**Comment by dpgeorge** [comment]
I agree.  I was just thinking that the part would be useful for #1407 and the cmsis devinc file.

**Comment by dhylands** [comment]
> I agree. I was just thinking that the part would be useful for #1407 and the cmsis devinc file.

I don't think it really helps there (since make needs to know the name of the header file to pass to make-stmconst.py). I think using the mpconfigboard.mk is the right way to go.

cmsis requires that the user put a #define STM32F401xE someplace (we add it to the boards hal_conf file).

If we move it to mpconfigboard.mk then we can remove it from the hal_conf and use the mpconfigboard.mk macro for both purposes (cmsis at least seems to be consistent that the header file is always a lower case version of the define followed by .h)

**Comment by dhylands** [comment]
I added MCU_SERIES_M4 and MCU_SERIES_F7 and changed all of the refernces to STM32F7 to be MCU_SERIES_F7 instead.

**Comment by dpgeorge** [comment]
Merged in 8f59bacb92cb705d79f08f29f4d64c0a774ab78f.

**Pull request closed without merging**
