### PR TITLE
ports/esp32/modules/neopixel.py: Add len() and str() methods to NeoPixel module in ESP32 port

### PR DESCRIPTION
**Pull request by dybber**
Make programming with NeoPixels feel more like operating on an array.

### CODE REVIEW

**Comment by dpgeorge** [comment]
I think `__len__` is a good addition, but `__str__` is not necessary (and will lead to really long output if the number of pixels in the object is large).

**Comment by dybber** [comment]
I use MicroPython for teaching purposes, and use the NeoPixel-object as the first array object they will interact with. I find it very useful with the __str__ implementation in that case. In any production system, you wouldn't use it, but people can just avoid calling __str__ if the array is large.

**Comment by mattytrentini** [comment]
An alternative for `__str__` could be to display an arbitrary maximum number of pixels...

**Comment by dpgeorge** [comment]
Closed in favour of #7072.

**Pull request closed without merging**
