### PR TITLE
mpy-tool.py: Fix a build error.

### PR DESCRIPTION
**Pull request by robert-hh**
That caused the compile of frozen_content.c to fail.
Kudos go to @hippy for identifying the spot to change, but he could
not create a PR. So I'm doing that on his behalf.

### CODE REVIEW

**Comment by dpgeorge** [comment]
I don't understand why this is needed because the opcode names should all be strings.  What exactly broke?  If something broke then maybe we need to add a test to CI to catch that case.

**Comment by dpgeorge** [comment]
Ah, I see, #8356

**Comment by dpgeorge** [comment]
The fix here makes the output a bit ugly, eg:
```
    0x11,0x02, // 'LOAD_NAME print'
    0x10,0x03, // 'LOAD_CONST_STRING \\'
    0x35,0x01, // 'CALL_FUNCTION_VAR_KW 1'
    0x11,0x02, // 'LOAD_NAME print'
    0x10,0x04, // 'LOAD_CONST_STRING \nX'
    0x35,0x01, // 'CALL_FUNCTION_VAR_KW 1'
```
ie, everything is now quoted.

I suggest line 864 is changed to `opcode_name += " " + repr(self.qstr_table[arg].str)`.  Then the above is:
```
    0x11,0x02, // LOAD_NAME 'print'
    0x10,0x03, // LOAD_CONST_STRING '\\'
    0x35,0x01, // CALL_FUNCTION_VAR_KW 1
    0x11,0x02, // LOAD_NAME 'print'
    0x10,0x04, // LOAD_CONST_STRING '\nX'
    0x35,0x01, // CALL_FUNCTION_VAR_KW 1
```
This will now also quote other strings, like in `LOAD_NAME`, which might even make the comments clearer.

Alternatively, use `self.qstr_table[arg].qstr_esc` to get:
```
    0x11,0x02, // LOAD_NAME print
    0x10,0x03, // LOAD_CONST_STRING _backslash_
    0x35,0x01, // CALL_FUNCTION_VAR_KW 1
    0x11,0x02, // LOAD_NAME print
    0x10,0x04, // LOAD_CONST_STRING _0x0a_X
    0x35,0x01, // CALL_FUNCTION_VAR_KW 1
```

**Comment by robert-hh** [comment]
@dpgeorge Yes, the comments do not look well. But it is 'just' a temporary file hardly ever looked at. The first suggested change makes a better reabable code, just in case. So I'll change that.

**Comment by dpgeorge** [comment]
Thanks, merged in 5c46721a1cc32bdb8f700955f9b441a08056f7b0

**Comment by dpgeorge** [comment]
Test for this was added in c4b8dae4387b3a01cf4139c75f0852c5a6ffc108

**Pull request closed without merging**
