### PR TITLE
ports/nrf: Add RTC support to NRF ports

### PR DESCRIPTION
**Pull request by RetiredWizard**
I've cobbled together an update to the NRF build that adds support for the RTC and missing time methods (sleep, localtime, etc..). I don't really understand the meat of the update, I've mostly lifted it from Circuitpython but it compiles and appears to work.

I'm sure there are a number of things that I didn't do correctly, however I figured having a working PR to start with might make it easier to get the update in place.

Signed-off-by: RetiredWizard <github@retiredwizard.com>

### CODE REVIEW

**Comment by RetiredWizard** [comment]
Looks like I still have some work to do. I was so excited to get it to work on the board I was testing, I didn't notice the dependency I had on the NRF libraries.

I knew there was something wrong with having to add that include path to the Makefile :smile:

**Comment by robert-hh** [comment]
That looks like quite a bit of work. A few initial questions:
- About the file name & location: I wonder why you called it machine_rtc.c. Given the file structure of the nrf port, I would have it expected as module/machine/rtc.c.
- In modules/machine there is already a module called rtcounter.c. Can that coexist with rtc? I did not look into the data sheet, if there are two units for real time counting.

A not about Copyright notes: Since you used code from Circuitpython, did you carry over their Copyright note?

**Comment by RetiredWizard** [comment]
> * About the file name & location: I wonder why you called it machine_rtc.c. Given the file structure of the nrf port, I would have it expected as module/machine/rtc.c.

I don't really have a good grasp on the MP file structure :grin:  Your naming suggestion makes sense, I'll update the PR.

> * In modules/machine there is already a module called rtcounter.c. Can that coexist with rtc? I did not look into the data sheet, if there are two units for real time counting.

My understanding is that some of the nrf chips have 2 rtc units that are used (by the devkit?), perhaps one of those are used by rtcounter. I'll see if I can figure out enough to confirm that. The newer chips like the nRF52840 have 3 units with a spare one that this PR uses. I haven't gone back and positively confirmed this but I'm assuming the boards that wouldn't compile and have the MICROPY_PY_MACHINE_RTC parameter set to (0) are the older chips with just 2 units.

> 
> A note about Copyright notes: Since you used code from Circuitpython, did you carry over their Copyright note?

I think the only module that had lifted logic from Circuitpython was machine_rtc.c and the logic I lifted had to be tweaked but this is a good point. I'll grab any Copyright note from the source material and double check the reset of the code.

Thanks!!!

**Comment by robert-hh** [comment]
I tried to run the PR on a nRF52840 device. It compiles well, but the clock does not run. I can set a time, but that time does not change. Which device did you use for testing?

**Comment by RetiredWizard** [comment]
> I tried to run the PR on a nRF52840 device. It compiles well, but the clock does not run. I can set a time, but that time does not change. Which device did you use for testing?

Oops 😊 I really was reaching on this project. I didn't even think to check the operation of the clock. I only checked that the methods showed up and that I could set the date/time. Looks like I have some more digging to do ☹️

**Comment by RetiredWizard** [comment]
I just glanced over rtcounter.c (really should have done that sooner) and I think I may have come at this from the wrong direction. I'm going to close this for now and rework it after I've studied rtcounter for a while.

Thanks for looking at this @robert-hh :grin:

**Pull request closed without merging**
