### PR TITLE
Making the memory manager more pluggable

### PR DESCRIPTION
**Pull request by vitiral**
This is the pull request for making the memory manager more pluggable -- i.e. separate the gc from the heap manager to allow advancements on both separately.

This is part of the solution for #1168 and is a rework of several PR attempts:
- #1234
- #1320
- #1321

This PR attempts to consolodate the advice from those failed PR's and make a change that is as minimally invasive as possible to the existing code base and meets the coding guidlelines as much as possible.

The pull request uses the existing infrastructure to allow each build to select which garbage collector implementation it wants, either the original or the "basic" as the pluggable versions are being called. Eventually more gc implementations will be added, the next planned one is one that simply uses unix's malloc/free.

In addition, an `astyle.fmt` file has been added to the `tools/` directory that should define a fair number of micropython's coding conventions so that new contributors can automatically get their code formatted correctly and painlessly. This file may be a work in progress.

### CODE REVIEW

**Comment by vitiral** [comment]
TODO: need to integrate #1595 into `*basic` code.

**Comment by vitiral** [comment]
**TODO**: 
`mp_state_ctx` is tied into EVERYTHING.

t has documentation stating the following:
> This structure combines the above 2 structures[including the `gc_state` structure], and adds the local and global dicts.
> Note: if this structure changes then revisit all nlr asm code since they have the offset of nlr_top hard-coded.

I think I have a mechanism to cleanly break this appart, but I need to know if changing the `gc_state` object will really affect ASM code. Is it possible this can be broken appart so that `gc_state` is not part of `mp_state_ctx`?

**Comment by dpgeorge** [comment]
> I think I have a mechanism to cleanly break this appart, but I need to know if changing the gc_state object will really affect ASM code. Is it possible this can be broken appart so that gc_state is not part of mp_state_ctx?

It needs to stay as one whole.  The idea is that we might in the future allow to pass around a single pointer which points to all the internal VM state, so that we can make it reentrant.  This pointer would point to the mp_state_ctx, which then has in it all the other stuff, including memory manager state.

**Comment by vitiral** [comment]
OK, but will changing the gc struct break ASM code?

**Comment by dpgeorge** [comment]
> OK, but will changing the gc struct break ASM code?

No.  Changing mp_state_mem_t won't break the asm nlr code.

**Comment by dpgeorge** [comment]
Closing due to inactivity.  See related effort in #3580.

**Pull request closed without merging**
