### PR TITLE
pyb.adc.rst Remove outdated ADCAll code example.

### PR DESCRIPTION
**Pull request by peterhinch**
As requested in comment to PR #3656. Added a simple example to illustrate ADCAll instantiation.

### CODE REVIEW

**Review by chuckbook — COMMENTED** [review]
there is a typo in ADC.rst ADCAll description:
prarmeter --> parameter

**Comment by chuckbook** [comment]
Would it make sense to add or change ADCAll.read_channel to return adjusted values?

**Comment by peterhinch** [comment]
It provides access to the raw value which may be of use to some. Also it's presumably non-allocating whereas adjusted values  return floats precluding their use in an ISR.

**Comment by chuckbook** [comment]
I just thought of an additional method to provide an easy to use way getting meaningful results for the casual user. Maybe something like read_channel_cooked. It might also be a good idea to provide results as integer mV to avoid IRQ mem allocs.

**Comment by dpgeorge** [comment]
Thanks for this, merged in 06006459447c8e7eaa031058a83f54bb06891bcb

**Comment by dpgeorge** [comment]
> prarmeter --> parameter

Thanks, this typo was fixed in c24b0a7f2b7c0c30ef5fde62342eab7c0931f400

> Would it make sense to add or change ADCAll.read_channel to return adjusted values?

Yes, and I think in general it would be good to also provide better consistency across ports with the range of values returned by an ADC read, and also supporting different use cases.  For example `adc.read_u16()` would return 0-65535 (but might not support 16-bits of precision depending on the hardware), `adc.read_mv()` could return an integer with units of millivolts, and `adc.read()` could be the user-friendly method that users first learn about which returns a float in volts.

**Comment by chuckbook** [comment]
Although it makes sense to use normalized return values it eventually may irritate a beginner or casual user. Can we provide read_V(), read_mV() and read_uV() in addition to the raw values? This would allow to use the upcoming delta-sigma adcs in an appropriate way.

**Comment by chuckbook** [comment]
Yes, a left adjusted value is still a raw value but normalized towards 2^n. The only problem I see is that very soon 16 bit won't be sufficient.
Most if not all MCUs ready for MPY have internal band gap references. If no such feature is available there is still a default value (3.3V in case of the PYBV11).
And it's not just the beginners that would benefit from cooked values, once and a while even a gray beard gets lazy. Think of a battery monitor triggered by a 1 minute RTC wakeup event. A simple adcall.read_mV() would make a pretty simple supervisor.

**Comment by dpgeorge** [comment]
> The only problem I see is that very soon 16 bit won't be sufficient.

For such ADC's we could extend the API to allow `read_u24()` which should be sufficient :)  And it could anyway still provide a more standard `read_u16()` but with a small loss in precision.

**Comment by chuckbook** [comment]
Have a look at [https://www.mouser.de/Semiconductors/Data-Converter-ICs/Analog-to-Digital-Converters-ADC/_/N-4c43g?P=1z0w8n9] :grinning:
The cooked functions should return reals for V and signed integer for mV and µV.
Signed integer is important as we may have to deal with offset voltages as well.

**Pull request closed without merging**
