### PR TITLE
py/compile: Fix handling of unwinding BaseException in async with.

### LINKED ISSUE #4552: async with does not correctly handle exceptions devired directly from BaseException
The problem: I'm trying to port https://github.com/python-trio/trio to micropython. During this I've hit a problem with apparent module globals corruption that has me stumped.

Specifically, as part of that work I have backported the `contextvars` module to micropython-lib. This module is imported correctly. It has a nice global `_set_context` function … which happens to suddenly not be there any more:
```
  File "/srv/src/contextvars/contextvars/__init__.py", line 28, in run
NameError: name '_set_context' isn't defined
```

## How to reproduce

You need `http://github.com/smurfix/micropython-lib`, `master` branch, and `http://github.com/smurfix/trio`, `micro` branch, and this test program:
```
#!./micropython

import sys
sys.path[0] = "/tmp/lib" # wherever you installed micropython-lib to
sys.path.insert(0,"/srv/src/trio")  # wherever you checked out trio
import trio

async def run():
	async with trio.open_nursery() as n:
		await trio.sleep(1)
		print("Yes")

trio.run(run)
```

Running this with (the `master` branch of the Unix port of) micropython results in this stack trace:
```
Traceback (most recent call last):
  File "t.mpy", line 20, in <module>
  File "/srv/src/trio/trio/_core/_run.py", line 1383, in run
  File "/srv/src/trio/trio/_core/_run.py", line 1371, in run
  File "/srv/src/trio/trio/_core/_run.py", line 1369, in run
  File "/srv/src/trio/trio/_core/_run.py", line 1369, in run
  File "/srv/src/trio/trio/_core/_run.py", line 1365, in run
  File "/srv/src/trio/trio/_core/_run.py", line 1365, in run
  File "/srv/src/trio/trio/_core/_run.py", line 1504, in run_impl
  File "/srv/src/trio/trio/_core/_run.py", line 1499, in run_impl
  File "/srv/src/trio/trio/_core/_run.py", line 1495, in run_impl
  File "/srv/src/contextvars/contextvars/__init__.py", line 28, in run
NameError: name '_set_context' isn't defined
```
despite there being a perfectly valid `def _set_context()` declaration in that file. The numerous tests for `contextvars` pass, so there seems to be something more sinister going on.

Needless to say this is quite difficult to reduce to a more self-contained subset that still shows the problem. Ideas how to figure this out would be appreciated.

### PR DESCRIPTION
**Pull request by dpgeorge**
Fixes #4552

### CODE REVIEW

**Review by smurfix — APPROVED** [review]

**Comment by pfalcon** [comment]
Could have a second line in commit message saying "Should match against BaseException, not just Exception."

**Comment by smurfix** [comment]
Also maybe scan the sources for other instances of using Exception instead of BaseException?

**Comment by pfalcon** [comment]
> Also maybe scan the sources for other instances of using Exception instead of BaseException?

@smurfix, Should be a good way to start contributing to the MicroPython development ;-).

**Comment by dpgeorge** [comment]
Thanks for the review, merged in 12ce9f268909435b49f558d1d3c15ad7591d6fe8

**Pull request closed without merging**
